### ISSUE TITLE
一段英语一段中文是不是会更好？

### ISSUE THREAD

**Issue by zhl111** [immersive-translate/immersive-translate#1]
这离开的太远了，都不能对照原文了
- [Wall Street Breakfast: Euphoria Sweeps Markets | Seeking Alpha](https://seekingalpha.com/market-news/wall-street-breakfast?mailingid=29669062&messageid=wall_street_breakfast&serial=29669062.3268330 )  2022/11/11
![image](https://user-images.githubusercontent.com/29135984/201355523-c892d023-9697-4153-9b02-30d4a88c959e.png)

**Comment by theowenyoung** [comment]
谢谢反馈，这种情况属于原网页不标准，他用<br><br> 作为分段，正常的话，我们希望使用 <p></p> 进行分段，我看下有没有好办法能兼容<br>这种情况～

**Comment by theowenyoung** [comment]
对该网站做了特殊适配： https://github.com/immersive-translate/immersive-translate/releases/tag/nightly-0.0.20.1

晚点发正式版。

**Comment by dongzide** [comment]
> 对该网站做了特殊适配： https://github.com/immersive-translate/immersive-translate/releases/tag/nightly-0.0.20.1
> 
> 晚点发正式版。

按单句进行翻译不是更适合对照吗？反正谷歌的文本翻译也是按句子切分的。按段落翻译如果文章的段落特别长也难以对照中英文查看

**Comment by theowenyoung** [comment]
我觉得段落是一个比较适宜的分割点，太长了不好对照，但是太短，比如一句一句的翻译，读起来又不够流畅。

**Comment by dongzide** [comment]
> 我觉得段落是一个比较适宜的分割点，太长了不好对照，但是太短，比如一句一句的翻译，读起来又不够流畅。

有一定到了，如果按段落翻译，对于类似推特或网贴这样的内容（分段很多，可能一句话就是一段）较好，但对于那种记者撰写的深度新闻或者小说文章等长段落就不太友好。

可以加个设置选项，自由选择按句子翻译，还是按段落翻译。

**Comment by theowenyoung** [comment]
其实，按句子翻译，技术上也不好实现...

我感觉，其实现在大多数深度新闻，每一段也不是很长～ ,我是主要在这里面找的文章～  https://www.buzzing.cc/ 

<img width="741" alt="image" src="https://user-images.githubusercontent.com/62473795/201613797-c665c224-cc1c-457d-9bd5-e9ccf43fe8ca.png">

**Comment by dongzide** [comment]
> 其实，按句子翻译，技术上也不好实现...
> 
> 我感觉，其实现在大多数深度新闻，每一段也不是很长～ ,我是主要在这里面找的文章～ https://www.buzzing.cc/
> 
> <img alt="image" width="741" src="https://user-images.githubusercontent.com/62473795/201613797-c665c224-cc1c-457d-9bd5-e9ccf43fe8ca.png">

按句子翻译不好实现吗？你的整页翻译功能是如何实现的，我自己研究过google翻译api，如果你整体发送一大篇文本给接口，它返回的翻译结果就是 **单个句子** 的数组。所以我想按句子翻译应该是最简单的，因为谷歌翻译接口返回的就是按句子翻译的结果。

**Comment by theowenyoung** [comment]
网页翻译主要是要通过操作dom来选择，替换一些翻译的节点，如果按句子分的话，并没有对应的dom css选择器可以选中该句子，并替换。

全局正则替换，对于文本很好，但是对于网页来说，很难搞定，尤其是，现在大多数网页都有动态生成的新节点，比如推特加载更多，新生成的节点，如果用js里的dom监听函数就更容易实现，自己解析parse html文本，就挺难搞的。
