### ISSUE TITLE
以后有没有可能出一个VScode插件？

### ISSUE THREAD

**Issue by photkey** [immersive-translate/immersive-translate#100]
网页沉浸式翻译的体验太好了，等这个插件稳定以后，有没有可能出一个vscode版的插件？主要是翻译源码中的注释，以及readme文档。

**Comment by theowenyoung** [comment]
好吧 挺不错的想法～

readme的 markdown view 很适合。

**Comment by 0x5c0f** [comment]
在线催一下vscode支持  。

**Comment by keyboard3** [comment]
暂无此计划

**Comment by 1ilin** [comment]
对于readme的折中办法：既然是仅阅读的话，用浏览器打开md文件，[Markdown Viewer](https://chromewebstore.google.com/detail/markdown-viewer/ckkdlimhmcjmikdlpkmbgfkaikojcbjk)这个插件渲染
然后在插件管理页允许immersive-translate读取文件url，就能实现翻译md文件
![image](https://github.com/immersive-translate/immersive-translate/assets/111619610/985e2ff4-5cfa-4bb7-baf8-441101d0170e)

**Comment by msuadOf** [comment]
最近看paper和仓库的时候碰到了adoc，似乎并没有像markdown那么好的支持；最近看paper浏览器小圆球一点都快习惯了，写代码的时候忽然没了很不习惯，希望能出一个开箱即用vscode插件
