### ISSUE TITLE
[Bug]: 插件与 Gitlab Mermaid 渲染冲突

### ISSUE THREAD

**Issue by gitsang** [immersive-translate/immersive-translate#1000]
### 插件版本号 | Version

v0.9.8

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome, Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

插件会导致 Mermaid 被截断

![image](https://github.com/immersive-translate/immersive-translate/assets/49085035/26d3595c-f495-4061-b7b1-ce1afee1bf75)

### 出现问题的网址 | URL

https://gitlab.com/sang.opensource/sandbox/hello

### 重现步骤 | To Reproduce

![GIF 2023-10-9 13-41-19](https://github.com/immersive-translate/immersive-translate/assets/49085035/9247400a-424b-4588-b97e-16dd84bfe61e)

### 补充说明 | Additional context

可能关联的 Issue

- https://github.com/crimx/ext-saladict/issues/2105

**Comment by theowenyoung** [comment]
谢谢反馈，确实是 Edge上有问题，甚至不需要 点击翻译，也会影响。我们调查一下。

**Comment by keyboard3** [comment]
我反复测试了下，应该不是插件的问题。我edge和chrome都试了，插件安装卸载表现一样

https://github.com/immersive-translate/immersive-translate/assets/13177744/780fd0ed-14a0-4527-998f-1c0da1e96cf2

**Comment by gitsang** [comment]
> 我反复测试了下，应该不是插件的问题。我edge和chrome都试了，插件安装卸载表现一样

有没有可能是其他插件影响的，按照我之前上传的 GIF，确实开关此插件会有影响（但我确实也不太记得当时是否还开了其他的插件，如果是，也许是此插件和其他插件的共同作用？）。

另外，我更新插件到 v0.10.6 后，发现已经不再出现问题（我打开了我所有的插件与此插件，都不再出现上述问题），也许已经被无意间修复了。因此我将先关闭此 issue，如果还有什么需要我提供的，我会尽力提供。
