### ISSUE TITLE
[Bug]:推特只能翻译博文，不能翻译引用的链接的标题

### ISSUE THREAD

**Issue by softmetal66** [immersive-translate/immersive-translate#1001]
### 插件版本号 | Version

0.9.8

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

推特只能翻译博文，不能翻译引用的链接的标题
![Snipaste_2023-10-09_13-55-37](https://github.com/immersive-translate/immersive-translate/assets/112331657/e54e7da8-5724-483d-b7d1-1564340a7ce5)

### 出现问题的网址 | URL

twitter

**Comment by keyboard3** [comment]
我试了几个帖子正常的，你可以发下这个帖子吗？

**Comment by theowenyoung** [comment]
似乎 X 改版后，现在的链接都是这样了，看不到标题了？ 

<img width="624" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/c56120f1-d484-4c94-8bcd-67163c4d60b1">

如果还是有问题，请重新打开这个 issue哈，暂时先关掉。
