### ISSUE TITLE
[Bug]: Youtube 博主视频页重排后翻译仍为旧版，且显示错误

### ISSUE THREAD

**Issue by grejioh** [immersive-translate/immersive-translate#1002]
### 插件版本号 | Version

0.9.9

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在 YouTube 博主的主页，点击“最新”、“热门”、“最早”选项使得视频列表重排后，不会重新翻译。且有时候**新英文标题**、**重排前英文标题**以及**重排前翻译**会同时出现。

### 原始网页
<img width="1156" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/43024589/21c5829e-63d3-4309-80f5-1d70b989d282">

### 首次翻译后 （正常）
<img width="1114" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/43024589/73c35548-309e-4c4d-88e5-a16653528199">

### 点击“最早”选项（翻译和标题顺序错误且翻译为重排前翻译）
<img width="1137" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/43024589/758fd6a5-7f66-495c-be73-dee49c893eb6">

### 点击显示原文再点击翻译 （**新英文标题**、**重排前英文标题**以及**重排前翻译**同时出现）
<img width="1179" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/43024589/280e6fc5-4568-492e-a4e4-e7ddfc414c67">

### 出现问题的网址 | URL

https://www.youtube.com/@hubermanlab/videos

### 重现步骤 | To Reproduce

1. 打开网站，点击翻译
2. 选择“最早”（或者“热门”）
3. 显示原文，再点击翻译

### 补充说明 | Additional context

非常好用！非常感谢您的付出！

**Comment by theowenyoung** [comment]
确实，该问题已经存在很久，Youtube 网站自身使用的技术有点复杂，他会复用上一个页面的节点，导致我们无法检测到变更。

需要找时间再研究一下。

目前建议这样：

进入： https://www.youtube.com/@hubermanlab/videos

点击： 热门

再翻译

**Comment by keyboard3** [comment]
0.12.6 已修复

**Comment by grejioh** [comment]
Thanks!
