### ISSUE TITLE
阅读本地电子书，支持设置字体大小、夜间模式以及tts语音朗读。

### ISSUE THREAD

**Issue by Leroy-X** [immersive-translate/immersive-translate#1004]
### 您希望的更新和改进是什么 | Update or Improve

阅读本地电子书，诸如epub，希望可以支持设置字体及大小、夜间模式，如果能有tts语音朗读就更好了。
（这样我就可以少装一个epub阅读器扩展了）
非常感谢！

**Comment by theowenyoung** [comment]
目前 字体的大小可以通过 `Ctrl` 和 `+` 来调整，mac上是 `cmd` `+`

字体，夜间模式，tts 暂时没有计划支持，建议使用 epub 制作双语书之后导出到其他的epub阅读器来实现相关功能。
