### ISSUE TITLE
High memory and CPU usage

### ISSUE THREAD

**Issue by liuxin-liuxin** [immersive-translate/immersive-translate#1006]
### 您希望的更新和改进是什么 | Update or Improve

After clicking on translate and refreshing several times, it consumes a large amount of memory and the CPU will continue to increase

**Comment by Dia-Kurozawa** [comment]
Meet the same issue here, pls fix thx :>

**Comment by theowenyoung** [comment]
Can you give some more context? 

Like OS platform, browser, and any special sites?

**Comment by liuxin-liuxin** [comment]
OS platform:Windows 10 Enterprise Edition LTSC,

 browser:Chrome,version: 117.0.5938.150

 special sites:Any website(Integrated the translation plugin into Chrome browser, clicked to refresh the browser multiple times and performed multiple translations)

**Comment by theowenyoung** [comment]
Sorry, I tried again this day with Window 11, Chrome 117, and I tried this page: https://urbigenous.net/library/how_to_build.html

Click Translate Button, then refresh the whole page, again and again, about 5 times.

I didn't see the higher CPU here, I use https://guanjia.qq.com/ to monitor the CPU stats.
