### ISSUE TITLE
能否对特定网页设定仅译文选项

### ISSUE THREAD

**Issue by alphavvv** [immersive-translate/immersive-translate#1007]
### 您希望的更新和改进是什么 | Update or Improve

对某些网址 以及繁体中文 能否支持让用户单独设置该网址/该语言为仅译文样式 繁中完全没有必要双语对照 但是其它网站又需要双语对照

**Comment by yupunit** [comment]
+1

**Comment by theowenyoung** [comment]
目前主要问题是 仅译文的模式会丢失 原文的 链接，或者其他标签信息，所以目前还不够好用。 

建议这种情况下，配置浏览器自带的翻译使用 仅译文模式。

**Comment by alphavvv** [comment]
> 目前主要问题是 仅译文的模式会丢失 原文的 链接，或者其他标签信息，所以目前还不够好用。 
> 
> 
> 
> 建议这种情况下，配置浏览器自带的翻译使用 仅译文模式。

双语模式下还有一个问题是如果不在文章顶部 快速滑到中部底部会影响当前的滚动位置 仅译文的话这个问题也会好点 请问固定滚动位置不影响浏览这种在双语模式下可能实现吗

**Comment by theowenyoung** [comment]
> > 目前主要问题是 仅译文的模式会丢失 原文的 链接，或者其他标签信息，所以目前还不够好用。
> > 建议这种情况下，配置浏览器自带的翻译使用 仅译文模式。
> 
> 双语模式下还有一个问题是如果不在文章顶部 快速滑到中部底部会影响当前的滚动位置 仅译文的话这个问题也会好点 请问固定滚动位置不影响浏览这种在双语模式下可能实现吗

无法实现

**Comment by keyboard3** [comment]
新版可以在https://dash.immersivetranslate.com/#advanced 中配置仅译文翻译地址
