### ISSUE TITLE
[Bug]: 一句话被拆成了两句进行翻译

### ISSUE THREAD

**Issue by tiezhudotwang** [immersive-translate/immersive-translate#1008]
### 插件版本号 | Version

v0.10.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

如图，`or deal with other people's broken code.`是连续的一句话，但是翻译里被拆成了两句`或处理其他人的问题。损坏的代码。`

![1697074744001](https://github.com/immersive-translate/immersive-translate/assets/126638121/9e2c76a4-90e6-41c0-90d5-a7ab307c7ed7)

### 出现问题的网址 | URL

http://paulgraham.com/schlep.html

### 重现步骤 | To Reproduce

1. 打开http://paulgraham.com/schlep.html
2. 点击翻译

### 补充说明 | Additional context

无

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/eb623180-fa50-486f-9757-33e4a5605401)
这个跟插件无关，跟你选择的翻译无关，这是我的deepl翻译
