### ISSUE TITLE
[Bug]:  翻译字幕出现错行及重复行

### ISSUE THREAD

**Issue by zgjcom** [immersive-translate/immersive-translate#1012]
### 插件版本号 | Version

0.10.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

使用GPT 3.5 翻译字幕的时候会出现 2行英文被合并成一行翻译 导致后面就会错行  或者出现大量重复行
![Snipaste_2023-10-15_00-58-50](https://github.com/immersive-translate/immersive-translate/assets/11371223/85141d75-80cc-4ad8-9a5c-4af49d1a928e)

**Comment by theowenyoung** [comment]
最近为 OpenAI 增加了联系上下文的功能，所以会合并多个段落。大多数情况工作的还不错，但是还是有一些bad case.

你可以上传一下你的这个字幕文件吗？我们测试下。

**Comment by theowenyoung** [comment]
做了一个调整，刷新页面后再试试可能效果会好点。

大多数情况下，合并是被GPT判断为必要的才会合并。

**Comment by zgjcom** [comment]
> 最近为 OpenAI 增加了联系上下文的功能，所以会合并多个段落。大多数情况工作的还不错，但是还是有一些bad case.
> 
> 你可以上传一下你的这个字幕文件吗？我们测试下。

[2. Common Code Smells.zip](https://github.com/immersive-translate/immersive-translate/files/12908787/2.Common.Code.Smells.zip)
压缩包里是原字幕 和 翻译后的双语字幕

另外问一下哪里清缓存 有时候想重新翻译一下  重新打开同名文件 点翻译直接就是100%

**Comment by theowenyoung** [comment]
在【关于】 tab里面，可以清除缓存。

**Comment by theowenyoung** [comment]
目前翻译是这样：

<img width="1277" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/674eab5e-0fdb-41e4-bec0-7e4e47fdae74">


我认为还可以？

**Comment by theowenyoung** [comment]
重复在这里应该是合理的，因为2句英文是同一句中文。

**Comment by zgjcom** [comment]
> 重复在这里应该是合理的，因为2句英文是同一句中文。

ok 那是我想岔了 我看到那么多重复的就以为出错了  

另外将来有没有办法加入批量翻译的功能 一个课程几分钟  然后我得不断的手动选择 字幕 翻译 再导出 然后观看

**Comment by theowenyoung** [comment]
> > 重复在这里应该是合理的，因为2句英文是同一句中文。
> 
> ok 那是我想岔了 我看到那么多重复的就以为出错了
> 
> 另外将来有没有办法加入批量翻译的功能 一个课程几分钟 然后我得不断的手动选择 字幕 翻译 再导出 然后观看

嗯，可以的～ 记下来了
