### ISSUE TITLE
Feature Request: Add a shortcut key for enabling/disabling Hover Translate.

### ISSUE THREAD

**Issue by JaydonZhao** [immersive-translate/immersive-translate#1013]
### 您希望的更新和改进是什么 | Update or Improve

Compared with manually clicking the extension and finding the button to toggle the hover translate, shortcuts will be more helpful. Also, this feature will also keep the app consistent with its name: Immersive-translate

**Comment by theowenyoung** [comment]
We do support shortcuts.

The default shortcut is `Alt+a`, you can define them here (Interface -> Keyboard shortcuts):

<img width="1255" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/9e431910-2504-45ef-9113-51e118f25599">
