### ISSUE TITLE
Reopen #1013 Feature Request: Add a shortcut key for enabling/disabling Hover Translate.

### ISSUE THREAD

**Issue by JaydonZhao** [immersive-translate/immersive-translate#1014]
### 您希望的更新和改进是什么 | Update or Improve

#1013
 
Dear marvelous developer:
目前的shortcut list中只有一些开关翻译的选项，没有直接开关**Hover Translate**的选项。
我发现目前 Immersive Translate 对 Hover Translate 的方案是 鼠标Hover +shift/Alt/ctrl 来进行 Hover Translate。与其这样不如直接增加一个单独的开关Hover Translate  的开关快捷键。因为这样可以避免一直不断的按shift/Alt/ctrl来进行Hover Translate，只需要按一次即可开关，并且大多数场景都是要么这个站点一直开着Hover Translate，要么就直接不用。通过一个单独的快捷键直接开关才更符合用户场景。

<img src="https://github.com/immersive-translate/immersive-translate/assets/43411963/5962421a-61c0-41a7-94e0-384734ed80f6" width="400px">

### 补充说明 | Additional context

（目前的方案: Alt/shift/ctrl + Hover，也有bug，经常遇到的issue：设置了一个修饰键+Hover，但经常没有按修饰键，Immersive Transalate也会直接对Hover的text进行翻译）

**Comment by theowenyoung** [comment]
相当于为 【鼠标滑过直接翻译】 设置一个快捷键。

> 目前的方案: Alt/shift/ctrl + Hover，也有bug，

这个确实，我偶尔也会遇到，需要重新调试一下。如果这个问题解决的话，还需要 建议 里的新快捷键吗？

你一般是什么场景需要用鼠标滑过呢？

**Comment by JaydonZhao** [comment]
需要的 目前的方案 修饰键+hover 需要一直反复去按修饰键 不如直接用新的快捷键更用户友好。

1. 比如如果用户要浏览专业性更高一点的网站，就需要经常经常使用到Hover Translate：
    1. 此时如果直接翻译整个页面，影响排版，降低阅读辨识度
    2. 此时如果将Hover Translate设置为不需要修饰键直接翻译，又会把所有的鼠标滑过的区域全部翻译，排版十分不好看 阅读辨识度大大降低

2. 如果用户浏览一般的简单英文文本网站，则不需要Hover Translate，可以直接关掉。  如果用户英文很差，Hover
Translate也是去了意义，此时更适合用户的选项应该是直接翻译页面


综上针对用户场景分析，为Hover Translate设置一个开关快捷键是更方便快捷，符合用户场景的


Owen ***@***.***>于2023年10月16日 周一18:43写道：

**Comment by theowenyoung** [comment]
> 需要的 目前的方案 修饰键+hover 需要一直反复去按修饰键 不如直接用新的快捷键更用户友好。

实际上 可以按住，不需要每次都按一下，这个你试过吗？

**Comment by JaydonZhao** [comment]
随便找了各 Wikipedia 页面试了一下，很不好用，很多时候无响应，貌似还会出现瞬时CPU占用过高的issue

而且 一直按着的这个设计 肯定不如在访问某个站点 阅读之前 按以下按钮开关的方便的多呀![image](https://github.com/immersive-translate/immersive-translate/assets/43411963/3d70cdaf-33b0-4a0c-b474-2c6e71ae1515)

**Comment by theowenyoung** [comment]
也可以。

那么这个快捷键的功能就是，按下该快捷键之后：

仅在该页面生效，鼠标滑过 会直接翻译该段落。

再按一次，取消该临时行为。


这个逻辑ok吗？

**Comment by JaydonZhao** [comment]
嗯嗯可以的
Appreciate the effort of the marvelous developers of Immersive Translate❤️

**Comment by JaydonZhao** [comment]
再次留言，期待开发者的关注❤️

**Comment by theowenyoung** [comment]
正在重新规划所有的快捷键，期待可以为绝大多数行为增加快捷键支持。

**Comment by nb5p** [comment]
I'm excited for this feature to be launched as well!

**Comment by theowenyoung** [comment]
最新版本 1.1.0 版本起已支持自定义一个鼠标悬停翻译的快捷键，

设置后，在当前页面按下快捷键后，则会临时开启鼠标悬停直接翻译，再次按下则取消该行为。 欢迎体验和反馈～
