### ISSUE TITLE
[Bug]: DevTools 重复请求 yandex.com ，造成页面崩溃 ，关闭翻译，重复的请求就停止

### ISSUE THREAD

**Issue by yunygo** [immersive-translate/immersive-translate#1015]
### 插件版本号 | Version

0.10.4

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/10007232/c55f1131-56e7-4c05-8e8d-ea7683769ddf)

当打开这个页面，开启自动翻译之后，DevTools 就不断刷新 yandex.com 的请求

### 出现问题的网址 | URL

https://javascript.info/array#loops

### 重现步骤 | To Reproduce

目前在过 JavaScript 体系，会实时打开 DevTools 调试代码，不确定怎么必现这个情况

**Comment by yunygo** [comment]
> 无法复现，我们的插件内部完全没有yandex相关的请求，你可以在隐私窗口里允许沉浸式翻译插件，然后再测试看看？

我之后再观察下，看是否有办法必现这个问题

**Comment by theowenyoung** [comment]
好的，有问题再重开这个issue哈～
