### ISSUE TITLE
[申请适配]namu.wiki

### ISSUE THREAD

**Issue by alphavvv** [immersive-translate/immersive-translate#1016]
### 您希望的更新和改进是什么 | Update or Improve

namu维基是一个韩语的信息网站 很多信息比较全 希望规则能够增加对namu维基的样式优化

### 补充说明 | Additional context

https://namu.wiki/

**Comment by theowenyoung** [comment]
是否只翻译正文部分即可？包括 正文部分的导航：

<img width="1030" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/4c471a18-3132-4dac-aad4-5ad229dc093f">

**Comment by alphavvv** [comment]
> 是否只翻译正文部分即可？包括 正文部分的导航：
> 
> 
> 
> <img width="1030" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/4c471a18-3132-4dac-aad4-5ad229dc093f">
> 
> 

展开内容和脚注等也需要翻译 namu的小细节写的很全 另外希望能够保留原文某些灰底格子的样式
![image](https://github.com/immersive-translate/immersive-translate/assets/83694637/9e79d677-ca4b-4a85-b223-b9965ae77eaa)![image](https://github.com/immersive-translate/immersive-translate/assets/83694637/c9397a90-6652-4d2c-b9ab-1a06f98b2c01)![image](https://github.com/immersive-translate/immersive-translate/assets/83694637/03427323-9e20-4760-aeb7-256280ed1a02)

示例：https://namu.wiki/w/(G)I-DLE

**Comment by FattySpring** [comment]
> > 是否只翻译正文部分即可？包括 正文部分的导航：
> > <img alt="image" width="1030" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/4c471a18-3132-4dac-aad4-5ad229dc093f">
> 
> 展开内容和脚注等也需要翻译 namu的小细节写的很全 另外希望能够保留原文某些灰底格子的样式 ![image](https://user-images.githubusercontent.com/83694637/275513670-9e79d677-ca4b-4a85-b223-b9965ae77eaa.jpeg)![image](https://user-images.githubusercontent.com/83694637/275513709-c9397a90-6652-4d2c-b9ab-1a06f98b2c01.jpeg)![image](https://user-images.githubusercontent.com/83694637/275513741-03427323-9e20-4760-aeb7-256280ed1a02.jpeg)
> 
> 示例：https://namu.wiki/w/(G)I-DLE

![image](https://github.com/immersive-translate/immersive-translate/assets/25144301/dbab3468-cc59-419f-b93e-8489a55e33ce)

注脚我这里看的跟截图不太一样，其他内容看起来翻译的都全的。

**Comment by alphavvv** [comment]
> > > 是否只翻译正文部分即可？包括 正文部分的导航：
> 
> > > <img alt="image" width="1030" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/4c471a18-3132-4dac-aad4-5ad229dc093f">
> 
> > 
> 
> > 展开内容和脚注等也需要翻译 namu的小细节写的很全 另外希望能够保留原文某些灰底格子的样式 ![image](https://user-images.githubusercontent.com/83694637/275513670-9e79d677-ca4b-4a85-b223-b9965ae77eaa.jpeg)![image](https://user-images.githubusercontent.com/83694637/275513709-c9397a90-6652-4d2c-b9ab-1a06f98b2c01.jpeg)![image](https://user-images.githubusercontent.com/83694637/275513741-03427323-9e20-4760-aeb7-256280ed1a02.jpeg)
> 
> > 
> 
> > 示例：https://namu.wiki/w/(G)I-DLE
> 
> 
> 
> ![image](https://github.com/immersive-translate/immersive-translate/assets/25144301/dbab3468-cc59-419f-b93e-8489a55e33ce)
> 
> 
> 
> 注脚我这里看的跟截图不太一样，其他内容看起来翻译的都全的。
![image](https://github.com/immersive-translate/immersive-translate/assets/83694637/f257d919-359c-4fa2-8538-70b3c39f6bca)
设置里面选默认展开注释就有了 主要是希望能够适配一下样式 比如说展开了注释之后和原文混在一起分不清样式 namu的文章又很长 看多了乱

**Comment by FattySpring** [comment]
> > ![image](https://github.com/immersive-translate/immersive-translate/assets/25144301/dbab3468-cc59-419f-b93e-8489a55e33ce)
> > 注脚我这里看的跟截图不太一样，其他内容看起来翻译的都全的。
> > ![image](https://github.com/immersive-translate/immersive-translate/assets/83694637/6fa24844-e711-407b-8751-591a5e55a21f)
> > ![image](https://github.com/immersive-translate/immersive-translate/assets/83694637/6d04c763-5a42-46d0-80b3-5e5cd5197d46)
> > 设置里面选默认展开脚注就有了 主要是希望能够适配一下样式 比如说展开了注释之后和原文混在一起分不清样式 namu的文章又很长 看多了乱

译文暂不支持还原原文的样式
