### ISSUE TITLE
[Bug]:  macos apple id 登录失败

### ISSUE THREAD

**Issue by beautydinosaur** [immersive-translate/immersive-translate#1017]
### 插件版本号 | Version

0.10.1(226)

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

使用Apple ID 登入時，會造成空白頁面，無法登入

### 出现问题的网址 | URL

(https://immersivetranslate.com/accounts/login)

**Comment by theowenyoung** [comment]
我这里似乎是正常的：

<img width="879" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/58fad6b0-d2fb-403b-8e62-754c8f5dfb7c">


你的macos版本是？

**Comment by beautydinosaur** [comment]
￼
我的情況是這樣

Mac 版本是14.0

**Comment by theowenyoung** [comment]
刷新页面呢？

或者直接进入： https://immersivetranslate.com/accounts/login 也无法登录吗？
