### ISSUE TITLE
[Bug]: 按键第三次之后容易失灵

### ISSUE THREAD

**Issue by Ymigmli** [immersive-translate/immersive-translate#1019]
### 插件版本号 | Version

0.10.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

默认alt键段落翻译，但是经常在翻译第二、三个之后的段落时容易失灵，需要将鼠标移至其他地方或者移至其他地方点一下，再放回需要翻译的段落，才可正常段落翻译

### 出现问题的网址 | URL

twitter等很多网站都是

### 重现步骤 | To Reproduce

默认alt键段落翻译，但是经常在翻译第三个段落时容易失灵，需要将鼠标移至其他地方或者移至其他地方点一下，再放回需要翻译的段落，才可正常段落翻译

### 补充说明 | Additional context

无

**Comment by theowenyoung** [comment]
感谢反馈，我们再调查下这个问题。

**Comment by theowenyoung** [comment]
请问你有试过其他快捷键吗？比如 Shift。

我们测试发现了另一种情况，就是当前窗口 失去焦点之后，比如切换到别的应用，再回来之后，会出现不按快捷键，也会直接翻译的情况。

但是第二段 第三段失灵的情况还没遇到过。

**Comment by keyboard3** [comment]
暂无反馈 暂时关闭此issue
