### ISSUE TITLE
producthunt站点翻译有问题（局部翻译）

### ISSUE THREAD

**Issue by danielesk** [immersive-translate/immersive-translate#102]
https://www.producthunt.com/marketplace?ref=header_nav

只翻译了头部，其他页面（如主页）翻译的也不全面，测试了几个翻译服务都是这样
![image](https://user-images.githubusercontent.com/10652829/217245313-61d2f607-a644-4cdc-bd6e-0c734f171057.png)

**Comment by theowenyoung** [comment]
已修复，点击 浏览器扩展图标后会自动更新最新规则～

**Comment by danielesk** [comment]
@theowenyoung 翻译出现了遮挡、覆盖
![image](https://user-images.githubusercontent.com/10652829/217474017-2f785c6f-89d6-4d1d-841a-ec2e49034605.png)

**Comment by crocodile2021** [comment]
已调整适配，不过要等下个版本发布，大概一到两天后～

**Comment by theowenyoung** [comment]
新版已经发布了，商店版还在审核～

暂时关掉这个问题，有问题再打开。
