### ISSUE TITLE
建议添加网页翻译并离线缓存的新功能

### ISSUE THREAD

**Issue by huerkang-hogan** [immersive-translate/immersive-translate#1020]
### 您希望的更新和改进是什么 | Update or Improve

希望能够直接实现以下功能：直接翻译整个网页并打印打下。

### 补充说明 | Additional context

因为有些大网页翻译过程很慢很卡，如果能离线阅读将更舒畅

**Comment by theowenyoung** [comment]
目前就是支持的呀，你直接点击【更多】，【立即翻译到页面底部】，然后保存网页即可。
