### ISSUE TITLE
[Bug]: 启用OpenAI翻译且“每次请求最大段落数”大于1时，“Prompt”会增加字幕翻译的提示词

### ISSUE THREAD

**Issue by qyhfrank** [immersive-translate/immersive-translate#1021]
### 插件版本号 | Version

0.10.5

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

启用OpenAI翻译且“每次请求最大段落数”大于1时，“Prompt”会增加字幕翻译的提示词“Translate the following subtitles into Simplified Chinese, keep 5 paragraphs, and do not explain any sentences”

**Comment by theowenyoung** [comment]
确实，下个版本修复。 不过理论上这个prompt对于翻译应该是没有影响的，你那边测试会有影响吗？

**Comment by qyhfrank** [comment]
我自定义了System Prompt，有时候会把字幕翻译这句提示词给翻译进结果了，哈哈，没有太大的影响。感谢修复，期待下个版本！

**Comment by theowenyoung** [comment]
已修复。
