### ISSUE TITLE
[Bug]: x浏览器启动脚本异常打开界面

### ISSUE THREAD

**Issue by 5418541** [immersive-translate/immersive-translate#1028]
### 插件版本号 | Version

0.10.5

### 平台 | Platform

Android

### 浏览器 | Browsers

Other

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

当在x浏览器启动脚本后 会有一个悬浮球 这时候点击屏幕任何地方悬浮球都会展开和关闭界面 然后就导致对页面的点击失效了 只有刷新页面才可以恢复对网页点击 但是如果再次打开翻译 也就是悬浮球页面 也会变成上面那样 我上此反馈一次了 但是好像没有人关注

### 出现问题的网址 | URL

任何可以打开悬浮球的网页

### 重现步骤 | To Reproduce

1点击翻译
2此时展开悬浮球
3点击屏幕任何地方都会只有开关悬浮球的操作，网页则没有任何反应

### 补充说明 | Additional context

希望可以尽快定位修复

**Comment by theowenyoung** [comment]
是否是其他插件影响？
我这里正常。


复活节 ***@***.***> 于 2023年10月18日周三 下午8:24写道：

**Comment by 5418541** [comment]
我浏览器卸载重装后，还是这样

**Comment by theowenyoung** [comment]
无法复现.. 可以录屏说明一下吗？
