### ISSUE TITLE
油猴脚本版沉浸式翻译无法正确使用DeepL API

### ISSUE THREAD

**Issue by CyberBacchus** [immersive-translate/immersive-translate#103]
## 测试环境
- 系统：macOS13.2 (22D49)
- 脚本版本：0.2.50
- Safari版本：16.3 (18614.4.6.1.5)
- Edge版本： 109.0.1518.78 (Official build) (arm64)
## 脚本设置
仅选择翻译服务为DeepL，填入密钥，目标语言简体中文
### 在Safari中使用沉浸式翻译*脚本*，通过DeepL API翻译，有翻译结果但为乱码
<img width="699" alt="image" src="https://user-images.githubusercontent.com/114143232/217253237-5e684196-0f6f-46a4-a20b-3859082a954c.png">

### 在Edge中使用沉浸式翻译*脚本*，通过DeepL API翻译，无法显示翻译结果
<img width="690" alt="image" src="https://user-images.githubusercontent.com/114143232/217253182-c43adc8a-77a6-407c-ba52-bc9c26fa2a5e.png">

### 在Edge中使用沉浸式翻译*插件*，通过DeepL API翻译，可以正常显示翻译结果
<img width="728" alt="image" src="https://user-images.githubusercontent.com/114143232/217253434-a75d5f4c-fd98-4898-8d8c-55f4f542ef25.png">

如果有需要，我可以提供我的API供您调试，请通过matrix联系我

**Comment by theowenyoung** [comment]
感谢详细的问题详情，之前有过2位同学反应safari deepl api 乱码的问题，我这好像没有重现～

好，我联系你～

**Comment by theowenyoung** [comment]
刚又提交了个新版本，但是还是没解决我tamper monkey本地的乱码问题。我本地的userscript本来就是ok的，然后我尝试客户端加了一个指定 utf8的标志，不知道会不会解决你的问题..

这个链接似乎认为字体丢失或者损坏也可能是原因，也许你可以试试：

https://www.zhihu.com/question/22501644/answer/215362976

**Comment by CyberBacchus** [comment]
忘记看这个issue了，实在不好意思。指定编码之后，网页确实都可以正常翻译了。我之前认为wikiwand依然存在问题，但这应该是本地缓存的问题，清除后可以解决。非常感谢你的改进。
