### ISSUE TITLE
code don't translate 

### ISSUE THREAD

**Issue by linpan** [immersive-translate/immersive-translate#1030]
### 您希望的更新和改进是什么 | Update or Improve

![image](https://github.com/immersive-translate/immersive-translate/assets/6077601/4f36ebfc-ecfb-41f6-ba53-5b98219b8cf2)

### 补充说明 | Additional context

docs: https://fastapi.tiangolo.com/deployment/server-workers/#containers-and-docker

**Comment by keyboard3** [comment]
已修复 刷新下
