### ISSUE TITLE
[Bug]: 启用插件会给页面上的所有iframe发送消息

### ISSUE THREAD

**Issue by zhdy2062** [immersive-translate/immersive-translate#1031]
### 插件版本号 | Version

0.10.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

页面中引入了iframe，iframe中监听了message事件，会接收到来自插件的数据：
{
    "id": "0.4098054637241535",
    "response": {},
    "type": "system|ping#ask#ping"
}

影响iframe中的判断

### 重现步骤 | To Reproduce

1. index.html 父页面引入iframe
2. iframe.html 监听message事件
      window.onmessage = function(e) {
            console.log(e)
            console.log(e.data)
        }
3. 会额外接收来自该插件的消息

**Comment by theowenyoung** [comment]
请问是哪个网址，我们可以做下排除

Kiana Rak ***@***.***> 于 2023年10月19日周四 下午6:25写道：

**Comment by zhdy2062** [comment]
不好意思，没有特定的网址，是在公司内网地址发现的，我在重现步骤中提到了，简单写一个页面引入iframe，监听message事件就可以复现

**Comment by theowenyoung** [comment]
嗯，这个我知道，我们确实使用了iframe的消息监听 API，用于在父页面统一控制 翻译的请求频率，理论上来说，希望网站自己在监听事件的时候可以自己判断下消息来源和类型，但是似乎有一些网站不经过任何判断就处理iframe的消息。

目前，我已经去掉了该特性：

`"useIframePostMessage": false`

请点击一下面板，更新最新的规则，然后再试试哈～
