### ISSUE TITLE
[Bug]: 字幕翻譯

### ISSUE THREAD

**Issue by r91085** [immersive-translate/immersive-translate#1033]
### 插件版本号 | Version

0.10.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

字幕翻譯後不會顯示，只會顯示一個小小的空白方框

![image](https://github.com/immersive-translate/immersive-translate/assets/37505035/7bb54d29-4346-47c2-97f7-94cc7a468dba)

### 出现问题的网址 | URL

https://www.youtube.com/watch?v=MTjb1ps8iVs&t=1958s

### 重现步骤 | To Reproduce

1. 打開網址
2. 點擊插件，按下翻譯
3. 字幕區顯示「正在使用google翻譯 請稍待」的訊息
4. 之後什麼都沒有，只有一個小小的空白字幕框

**Comment by keyboard3** [comment]
奇怪 我这边倒是挺正常的

**Comment by FattySpring** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/25144301/bf5bf8f5-8e67-4d67-b00a-4074313d13e0)
直接选自动生成正常吗

**Comment by r91085** [comment]
經過反覆測試，似乎是在 youtube 的字幕已經選擇內建翻譯字幕時會有問題。如果顯示原文看起來是正常的。

但是在這個設定下，其他字幕翻譯插件，是可以正常運作的

**Comment by FattySpring** [comment]
在部分情況下，選中自動翻譯【繁體中文】時候字幕源檔會出現問題。 在此設定，YouTube 雙字幕 也存在問題

**Comment by FattySpring** [comment]
字幕源沒有內容無法翻譯
