### ISSUE TITLE
[Bug]: 翻译服务名称。DeepL 显示的DeepI

### ISSUE THREAD

**Issue by augusl** [immersive-translate/immersive-translate#1034]
### 插件版本号 | Version

0.10.5

### 平台 | Platform

iOS

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

[Bug]: 翻译服务名称。DeepL 显示的DeepI

**Comment by keyboard3** [comment]
好的 下个版本调整

**Comment by theowenyoung** [comment]
0.10.6 版本已调整，感谢反馈。
