### ISSUE TITLE
希望添加独立的代理服务器设置，用于openai的访问限制

### ISSUE THREAD

**Issue by qq164004640** [immersive-translate/immersive-translate#1035]
### 您希望的更新和改进是什么 | Update or Improve

希望添加独立的代理服务器设置，用于openai的访问限制
增加http代理或者SOCKS5代理设置，这样就不影响正常使用网页

**Comment by keyboard3** [comment]
没看懂，你可以自己独立设置openAI的 api地址呀

**Comment by qq164004640** [comment]
我用[SwitchyOmega]插件来允许我选择性的代理国外网页，但是OPENAI的API对使用地区做了限制，像香港代理就无法使用，这个时候就需要[沉浸式翻译]插件走一个独立的代理节点来正常访问其他国家
简单的意思就是，是否能给这个插件增加一个代理服务器的设置
![image](https://github.com/immersive-translate/immersive-translate/assets/59138378/f9b4a5d3-587e-443d-aa1e-234151d79e3f)

**Comment by keyboard3** [comment]
这个事情插件肯定不会给你做的。你可以用whsitle来针对openAI api代理到其他节点
