### ISSUE TITLE
[Bug]: 超出翻译限额会有emoji

### ISSUE THREAD

**Issue by abc7895556** [immersive-translate/immersive-translate#1038]
### 插件版本号 | Version

0.10.2

### 平台 | Platform

iOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

提供一个按钮开关这个⭕️❓

### 出现问题的网址 | URL

github.com

**Comment by keyboard3** [comment]
没看懂 开关什么？

**Comment by theowenyoung** [comment]
你可以点击 ❓ 查看错误详情。
