### ISSUE TITLE
[Bug]: 特殊页面无法匹配为pdf，进行在线pdf翻译

### ISSUE THREAD

**Issue by lazygoat644** [immersive-translate/immersive-translate#1042]
### 插件版本号 | Version

0.10.5

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

以下页面无法识别为网页pdf，从而进行在线pdf翻译。
![image](https://github.com/immersive-translate/immersive-translate/assets/25381858/b374aa52-d5fb-40af-b36f-5e6d071dfe11)

### 出现问题的网址 | URL

https://aisel.aisnet.org/cgi/viewcontent.cgi?article=1009&context=sighci2008

**Comment by keyboard3** [comment]
在线地址必须后缀为.pdf才能正确识别成功
