### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by dashingli** [immersive-translate/immersive-translate#1043]
### 插件版本号 | Version

0.9.3

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

插件开启字母翻译功能 YouTube的英文字母不翻译为中文

**Comment by keyboard3** [comment]
升级到0.10.5+试试
