### ISSUE TITLE
[Bug]: Sentry 官方文档未按一段进行翻译

### ISSUE THREAD

**Issue by HINIOA** [immersive-translate/immersive-translate#1044]
### 插件版本号 | Version

0.10.6

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

此文档页面的某些段落未整段翻译，而是在段落中分句翻译。

![image](https://github.com/immersive-translate/immersive-translate/assets/39027408/75a8ff15-49b1-4f59-aed4-a44652989d1e)
![image](https://github.com/immersive-translate/immersive-translate/assets/39027408/7de0e4d7-87a9-4210-89f5-dc169258b0e2)

### 出现问题的网址 | URL

https://docs.sentry.io/product/accounts/quotas/manage-event-stream-guide/#-what-are-my-busiest-projects

### 重现步骤 | To Reproduce

点击 “翻译” 按钮

**Comment by theowenyoung** [comment]
感谢反馈，已修复，请刷新网页再试哈～
