### ISSUE TITLE
[Bug]: 翻译错误

### ISSUE THREAD

**Issue by lzfgit-byte** [immersive-translate/immersive-translate#1049]
### 插件版本号 | Version

0.10.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/37234536/ab384276-f600-41e6-a4bf-6d2262b749b2)

### 出现问题的网址 | URL

https://dart.cn/language/operators

### 重现步骤 | To Reproduce

打开，滑到那个翻译位置即可

**Comment by theowenyoung** [comment]
这个应该你选择的翻译服务有关（可以在第三方的翻译服务在线网站测试同样的文字，然后提issue给第三方翻译服务），刚测试openai是正常的：

<img width="957" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/45eb5a00-f7bb-457d-ba30-ebffa49a453f">
