### ISSUE TITLE
iPad在阅读epub的时候最后几行会丢失

### ISSUE THREAD

**Issue by w0330t** [immersive-translate/immersive-translate#105]
PC端也有这个问题。
譬如，这是第九章的原文:
![image](https://user-images.githubusercontent.com/4970238/217288706-754295f2-1e58-4b3c-9474-5a2053ea7dd2.png)
![image](https://user-images.githubusercontent.com/4970238/217288758-69161955-2fcb-41cc-a379-2bd42f4f515c.png)
然后使用插件后会变成这样：

https://user-images.githubusercontent.com/4970238/217288962-03f8a5a8-bbd8-4926-8906-62c1edaaad26.mp4

**Comment by theowenyoung** [comment]
由于特定epub阅读器问题，插件端暂时没法做什么。先关闭了哈～
