### ISSUE TITLE
[Bug]: 字幕文件翻译后导出功能无法执行

### ISSUE THREAD

**Issue by kinson08** [immersive-translate/immersive-translate#1050]
### 插件版本号 | Version

0.10.7

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

对本地的字幕文件进行翻译后，点击导出导出双语字幕时，一直显示转圈，无法导出双语字幕文件，仅导出译文也是同样问题。点击New到时能生效。

**Comment by theowenyoung** [comment]
请提供一下字幕文件，打包为 zip 包，上传到这里～

**Comment by kinson08** [comment]
字幕文件能上传，识别也挺好，翻译也没问题，就是无法导出双语或译文。



--------------------------------------------------------------------------------


 
 ------------------ 原始邮件 ------------------ 
 
 ***@***.***> 
 发送时间: 2023-10-26 22:10:41 
 ***@***.***> 
 ***@***.***>***@***.***> 
 主题: Re: [immersive-translate/immersive-translate] [Bug]: 字幕文件翻译后导出功能无法执行 (Issue #1050) 
 
 

 请提供一下字幕文件，打包为 zip 包，上传到这里～

 
—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

 
 



 
 
 TRANSLATE with x
 
 
 English 


 ArabicHebrewPolish BulgarianHindiPortuguese CatalanHmong DawRomanian Chinese SimplifiedHungarianRussian Chinese TraditionalIndonesianSlovak CzechItalianSlovenian DanishJapaneseSpanish DutchKlingonSwedish EnglishKoreanThai EstonianLatvianTurkish FinnishLithuanianUkrainian FrenchMalayUrdu GermanMalteseVietnamese GreekNorwegianWelsh Haitian CreolePersian 



 
 
 
 
 
 
 
 TRANSLATE with 
 
 
 COPY THE URL BELOW 
 
 
 
 Back 
 
 
 
 EMBED THE SNIPPET BELOW IN YOUR SITE 
 
 
 
Enable collaborative features and customize widget: Bing Webmaster Portal
 
Back

**Comment by kinson08** [comment]
[One.txt.zip](https://github.com/immersive-translate/immersive-translate/files/13183745/One.txt.zip)

**Comment by kinson08** [comment]
safari的油猴插件或者chrome的插件都有同样的问题

**Comment by keyboard3** [comment]
字幕文件命名格式不对，不能是以txt作为后缀。得以srt/ass这种文件名，你手动将txt修改成srt就可以了
