### ISSUE TITLE
[Bug]: 翻译inoreader dashboard界面出现断层

### ISSUE THREAD

**Issue by SinterChen** [immersive-translate/immersive-translate#1051]
### 插件版本号 | Version

0.10.7

### 平台 | Platform

macOS

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在页面翻译内容，内容出现左右结构而不是上下结果，译文出现在右边，并且译文下半部分被截断看不见
![CleanShot 2023-10-27 at 09 29 59@2x](https://github.com/immersive-translate/immersive-translate/assets/15107116/542c9f0b-2f36-46a7-9fd6-323add69d0d8)

### 出现问题的网址 | URL

https://www.inoreader.com/dashboard

### 重现步骤 | To Reproduce

进入网站，拖到最下面Currently Trending in Inoreader 模块
然后用插件进行翻译

**Comment by keyboard3** [comment]
已修复，再试下看
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/6cf076aa-6fa7-4db1-9c5d-6c183348245e)
