### ISSUE TITLE
希望System Prompt 支持多行文本

### ISSUE THREAD

**Issue by jiangying000** [immersive-translate/immersive-translate#1054]
### 您希望的更新和改进是什么 | Update or Improve

![image](https://github.com/immersive-translate/immersive-translate/assets/23182033/44be5086-b9cc-45ef-a5e8-52b9ffdddffb)

**Comment by theowenyoung** [comment]
可以，下个版本支持～

**Comment by theowenyoung** [comment]
0.10.9 已经支持。
