### ISSUE TITLE
[Bug]: 微软翻译高亮词顺序不对

### ISSUE THREAD

**Issue by ResDreamMon** [immersive-translate/immersive-translate#1055]
### 插件版本号 | Version

0.10.7

### 平台 | Platform

Android

### 浏览器 | Browsers

Other

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

以下是一段出现错误的翻译
原内容：Line 4 checks if the passport is invalid, and if so alerts the user of this (line 5) and if not it uses the alternate case (line 6) and tells the user the passport is still acceptable (line 7)
翻译结果：行检查护照是否无效，如果是，则提醒用户此（行），如果不是，则使用备用大小写（行）并告诉用户护照仍然可以接受（行 4 5 6 7 ）

很明显，数字4 5 6 被放错了位置。

### 出现问题的网址 | URL

https://pyflo.net/what-is-python/

**Comment by keyboard3** [comment]
你是不是用了微软翻译，这是微软在遇到某些边界占位符的时候容易出现这种情况。可以切换到谷歌翻译试下

**Comment by theowenyoung** [comment]
这种属于少数情况下，翻译服务出现幻觉的情况。插件这边应该做不了什么。
