### ISSUE TITLE
[Bug]: 当ytb视频有多个语言字幕时会选择错误的语言

### ISSUE THREAD

**Issue by heheda123123** [immersive-translate/immersive-translate#1057]
### 插件版本号 | Version

0.10.8

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

比如这个视频，https://www.youtube.com/watch?v=SfGuIVzE_Os&list=PLlrATfBNZ98dudnM48yfGUldqGD0S4FFb&index=8
他会自动选择俄语的。最好能根据沉浸式翻译的设置自动选择到 “英语” 
![image](https://github.com/immersive-translate/immersive-translate/assets/97490782/9415fd8e-42e8-4c88-ac52-7f8ec7e35e41)

### 出现问题的网址 | URL

https://www.youtube.com/watch?v=SfGuIVzE_Os&list=PLlrATfBNZ98dudnM48yfGUldqGD0S4FFb&index=8

**Comment by FattySpring** [comment]
打开这个视频自动选中俄语是因为在这个视频中俄语是人工字幕，在用户没有设定的情况下，YouTube会优先选择人工字幕而不是自动生成。在多语言字幕场景下需要手动选一次英语，之后的多语言字幕会自动选到英语

**Comment by heheda123123** [comment]
> 打开这个视频自动选中俄语是因为在这个视频中俄语是人工字幕，在用户没有设定的情况下，YouTube会优先选择人工字幕而不是自动生成。在多语言字幕场景下需要手动选一次英语，之后的多语言字幕会自动选到英语

这个视频，为啥我改了“英语（自动生成）-双语”之后，刷新页面，又变回了“俄语 >>英语”
