### ISSUE TITLE
[Bug]: pdf文档翻译乱码

### ISSUE THREAD

**Issue by kurokonobanira** [immersive-translate/immersive-translate#1058]
### 插件版本号 | Version

0.10.8

### 平台 | Platform

iOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

pdf文档翻译页面乱码

**Comment by kurokonobanira** [comment]
![微信图片_20231029222514](https://github.com/immersive-translate/immersive-translate/assets/149303892/f6db912d-6ab6-4f3f-a25a-8056174d6b3c)

**Comment by keyboard3** [comment]
这是由于safari 版本太低，pdf viewer不兼容的原因。 需要升级才行
