### ISSUE TITLE
[Bug]: 腾讯交互翻译标题内容不对

### ISSUE THREAD

**Issue by TullyMonster** [immersive-translate/immersive-translate#1059]
### 插件版本号 | Version

0.10.8

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

文本段落翻译正常，标题样式的文本翻译错误
![image](https://github.com/immersive-translate/immersive-translate/assets/47771282/7bf77643-1709-4309-85dd-92488bb68644)

### 出现问题的网址 | URL

https://www.biostarhandbook.com/the-unix-bootcamp.html

### 重现步骤 | To Reproduce

使用的是“腾讯交互翻译”

### 补充说明 | Additional context

https://www.biostarhandbook.com/the-unix-bootcamp.html 需要认证才可访问

**Comment by keyboard3** [comment]
你可以将这个页面不翻译时的状态通过这个步骤保存成htm文件吗  https://immersivetranslate.com/docs/faq/#%E7%BD%91%E9%A1%B5%E7%BF%BB%E8%AF%91%E6%9C%89%E9%97%AE%E9%A2%98%E5%A6%82%E4%BD%95%E4%BF%9D%E5%AD%98%E7%BD%91%E9%A1%B5%E5%8F%8D%E9%A6%88

**Comment by keyboard3** [comment]
暂无反馈 暂时关闭此issue
