### ISSUE TITLE
【建议】添加反向弱化和点击显示原文/译文

### ISSUE THREAD

**Issue by Unintendedz** [immersive-translate/immersive-translate#106]
有时希望重点关注译文，在译文不通畅的时候再看原文。
还有像 https://angular.cn/docs 这种点击显示原文/译文的方式也非常实用。

反向弱化效果大概如下图（这是我手动搞的）

![image](https://user-images.githubusercontent.com/64687143/217324466-232d0009-5f31-49bb-a0dc-09c3b1d6c39b.png)

另外，很感谢你做的这个插件！

**Comment by theowenyoung** [comment]
嗯，修改原文样式的功能正在计划中。

**Comment by theowenyoung** [comment]
由于修改原文会破坏原网站的功能，所以暂时没有这个计划了哈。
