### ISSUE TITLE
[Bug]: ytb字幕openai翻译错位

### ISSUE THREAD

**Issue by heheda123123** [immersive-translate/immersive-translate#1060]
### 插件版本号 | Version

0.10.8

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

https://www.youtube.com/watch?v=PPup1yeU45I&list=PLlrATfBNZ98dudnM48yfGUldqGD0S4FFb&index=83

前面是正常的，到 3min18s 变成了如下这样
![image](https://github.com/immersive-translate/immersive-translate/assets/97490782/4acc312e-86f9-4332-a42f-023bbafc2919)
继续播放变成了这样
![image](https://github.com/immersive-translate/immersive-translate/assets/97490782/4d2295b7-5f12-4426-8df1-381a96b6f339)
3min40s恢复正常

**Comment by theowenyoung** [comment]
这是 openai 翻译的是吗？

**Comment by heheda123123** [comment]
嗯
![image](https://github.com/immersive-translate/immersive-translate/assets/97490782/0d612d5b-9356-4934-93a8-d282f3ebb0eb)

**Comment by heheda123123** [comment]
另外，这两个模型从使用上来说有什么区别呢？
![image](https://github.com/immersive-translate/immersive-translate/assets/97490782/7801633d-044b-4bea-b1da-6ee60699855d)

**Comment by theowenyoung** [comment]
> 另外，这两个模型从使用上来说有什么区别呢？ ![image](https://user-images.githubusercontent.com/97490782/279058482-7801633d-044b-4bea-b1da-6ee60699855d.png)

目前这俩是一样的。

GPT-3.5-turbo 会随着时间的变更指向不同的版本，目前指向的就是 0613 的版本。

未来假如gpt推出更新的版本，那么 GPT3.5-turbo 会指向更新的版本。0613则永远指向 0613
