### ISSUE TITLE
[Bug]: 在Apple Community 尾页标号显示不正确

### ISSUE THREAD

**Issue by Tinyu-Zhao** [immersive-translate/immersive-translate#1062]
### 插件版本号 | Version

V0.10.8

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在Apple Community 尾页标号翻译显示出来很奇怪,基本上所有的都是
![CleanShot 2023-10-31 at 10 38 34@2x](https://github.com/immersive-translate/immersive-translate/assets/44396641/c1f450d8-da3e-4916-8088-90a952880d99)

### 出现问题的网址 | URL

https://discussions.apple.com/thread/940396

### 重现步骤 | To Reproduce

点击翻译,滑动到上述指定位置即可

**Comment by FattySpring** [comment]
已适配，刷新下页面
