### ISSUE TITLE
[Bug]: 会修改一些特殊布局网页导致页面布局异常

### ISSUE THREAD

**Issue by AkaHanshan** [immersive-translate/immersive-translate#1063]
### 插件版本号 | Version

0.10.8

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

https://anywhere.epam.com/en/blog/senior-front-end-developer-interview-questions
在这个页面进行翻译时候，左右侧的翻译会导致宽度增加从而遮挡住中间的网页内容
<img width="1420" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/48984202/d76892e2-d756-4fd3-bb7e-27ce5e25a015">

### 出现问题的网址 | URL

https://anywhere.epam.com/en/blog/senior-front-end-developer-interview-questions

**Comment by keyboard3** [comment]
已适配，刷新下，不要翻译全部区域，翻译主要区域。不然广告还是会被翻译
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/fe219929-a088-4bbd-9a72-2c1b31034cb9)
