### ISSUE TITLE
[enhancement]可以翻译本地打开的html文件

### ISSUE THREAD

**Issue by UnknownPoem** [immersive-translate/immersive-translate#1064]
### 您希望的更新和改进是什么 | Update or Improve

需求情景：
部分用户可能存在这样一种需求：把用户手册或说明书下载到本地再浏览。

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/75613d4c-3c83-4133-a2b5-fe2ff6025edf)
已有该功能
