### ISSUE TITLE
自定义API不全

### ISSUE THREAD

**Issue by superen7527** [immersive-translate/immersive-translate#1067]
> 目前 第二点也已经支持了哈， 可以选择【自定义API】，见文档：
> 
> https://immersivetranslate.com/docs/services/custom/

你好。好像理解错了，自定义不了body{"text": "xxx", "source_lang": "auto", "target_lang": "ZH"}

_Originally posted by @superen7527 in https://github.com/immersive-translate/immersive-translate/issues/309#issuecomment-1783811003_

希望支持自定义body 插件只需要自动语言代码和指定响应体 reopen不了

**Comment by theowenyoung** [comment]
抱歉 这个暂无计划支持，因为很难用映射关系去支持各种接口标准，所以最通用的办法就是我们提供标准的接口形式，这样第三方可以任意实现。
