### ISSUE TITLE
关于和Relingo插件的兼容问题

### ISSUE THREAD

**Issue by myh66** [immersive-translate/immersive-translate#1069]
### 您希望的更新和改进是什么 | Update or Improve

这个插件也会将原文进行修改标注出生词，好像会动态的修改，会导致沉浸式翻译翻译的句子包含原文和（）内的文字
这样看起看来很难受，没有原来的那么美观，能够找到兼容的方案是最好的~
eg.
![image](https://github.com/immersive-translate/immersive-translate/assets/53999290/b9dbd47f-586b-4365-8c56-86725b8fc676)

### 补充说明 | Additional context

Relingo官网：https://relingo.net/zh/index

**Comment by theowenyoung** [comment]
将会在下个版本支持。

**Comment by theowenyoung** [comment]
<img width="723" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/8337b487-d515-4168-aa22-25c315063475">

**Comment by myh66** [comment]
> <img width="723" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/8337b487-d515-4168-aa22-25c315063475">
> 

nice
