### ISSUE TITLE
notion 的 site 似乎不能翻?

### ISSUE THREAD

**Issue by HaveF** [immersive-translate/immersive-translate#107]
https://val-town.notion.site/Val-Town-Newsletter-3-173ea2960a654472907008f5be3edcc2

**Comment by theowenyoung** [comment]
<img width="1214" alt="Screenshot 2023-02-08 at 07 43 50" src="https://user-images.githubusercontent.com/62473795/217392461-3fe48683-2020-4d2c-a6cb-4bd3ee2f0895.png">

我这可以

**Comment by HaveF** [comment]
总感觉有问题，但又说不上哪里有问题...不翻译或就翻译了一段

![image](https://user-images.githubusercontent.com/54462/217393462-8f00f3b6-a63c-4bc5-8c80-caef6fa7fd4b.png)

Console:
![image](https://user-images.githubusercontent.com/54462/217394182-e6674dd5-863b-4c07-9e18-e98ac3b6ffba.png)

> 另外，是不是考虑加个 [sentry](https://sentry.io/welcome/) 来收集客户端错误?

**Comment by theowenyoung** [comment]
这个错误应该是notion自己的。

sentry 再等等吧哈哈，感觉没时间加呀～ 也许你可以贡献下😄

**Comment by theowenyoung** [comment]
看起来双方都监听了 mutation 变化，有可能有冲突。

**Comment by HaveF** [comment]
嗯，是点完 “翻译” 之后弹出的错

**Comment by zgbjmy2009** [comment]
等着解决了啊，我的直接翻译不了。https://starksheet.notion.site/Starksheet-bfb55bc581e446598d7bf5860e219b03
