### ISSUE TITLE
关于翻译被过滤时出现问号的问题

### ISSUE THREAD

**Issue by myh66** [immersive-translate/immersive-translate#1070]
### 您希望的更新和改进是什么 | Update or Improve

现有的方案是点击问号进行二次请求翻译，这能够解决大部分的问题，但是无法解决一类问题，类似如Azure的openai api请求，由于Azure的过滤机制相较于普通的openai的过滤机制要严格许多，导致翻译的时候导致部分翻译区域出现？导致某一段文无法翻译，（我自己尝试过申请解除过滤机制，但是非常难过，普通的个人乃至小微企业申请解除都是很难的）
我在这提出一种原则上可行的方案，将？部分的翻译通过其他api来翻译，然后将这些翻译结合起来，可以是这一句，一段都行，。可以单独多加一个选择二次翻译的接口，这样子对于用户来说应该是能够有效的解决这个问题。

**Comment by myh66** [comment]
确实麻烦，而且受众很少，那我先用着吧，但是openai和Azure的openai切换好麻烦要写哪个地址，我都是导出哪个配置文件来切换，能不能单独加一个框◕‿◕

**Comment by theowenyoung** [comment]
为啥不直接用 openai？ 价格似乎是一样的？

**Comment by myh66** [comment]
> 为啥不直接用 openai？ 价格似乎是一样的？
大陆的卡，港卡都付不了，onekey没赶上车...

**Comment by myh66** [comment]
> 为啥不直接用 openai？ 价格似乎是一样的？
能用肯定不上Azure了
