### ISSUE TITLE
OpenAI API希望能自定义超时时间

### ISSUE THREAD

**Issue by im-Kalix** [immersive-translate/immersive-translate#1072]
### 您希望的更新和改进是什么 | Update or Improve

我试图使用自定义的OpenAI API进行翻译，但是绝大多数请求都超时了，只有极少数较短的句子能给出翻译结果。

希望可以通过允许用户自定义超时时间，来解决这个问题！:)

**Comment by theowenyoung** [comment]
openai 账户问题: https://immersivetranslate.com/docs/services/openai/#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9

建议绑卡，开通正式账户解决，普通的账户几乎不可用于翻译。
