### ISSUE TITLE
可否增加设置[最少翻译字符数]的功能？

### ISSUE THREAD

**Issue by nyanTvT** [immersive-translate/immersive-translate#1073]
### 您希望的更新和改进是什么 | Update or Improve

阅读外文文献时，网页标题元素/文献小标题，甚至表格也会翻译，影响整体排版，是否可以增加设置[最少翻译字符数]的功能？
![delete](https://github.com/immersive-translate/immersive-translate/assets/148878573/9571373a-c7f4-439b-a5ca-6375afd74c5d)

**Comment by theowenyoung** [comment]
可以在【开发者设置】里面修改 full user config, 使用以下属性修改，默认是最小是4个字符，2个单词。 

```
    "paragraphMinTextCount": 4,
    "paragraphMinWordCount": 2,
```
