### ISSUE TITLE
[Bug]: Deepl翻译服务，<code></code>元素内容被错误的置于段落最后。

### ISSUE THREAD

**Issue by 23cicada** [immersive-translate/immersive-translate#1074]
### 插件版本号 | Version

0.10.9

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

这是OpenAI翻译：
<img width="682" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/52289446/e5d66b8e-4be7-4c99-aa5b-98e05989dc04">

这是Deepl翻译：
<img width="682" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/52289446/91494cfe-2eb3-4fd5-91aa-10ab7f650094">

Deepl翻译中，code元素内容Window.open Window.prototype被错误的置于段落最后

### 出现问题的网址 | URL

https://stackoverflow.com/questions/24008630/what-is-the-difference-between-window-and-window

### 重现步骤 | To Reproduce

打开上述URL地址直接翻译可复现

**Comment by theowenyoung** [comment]
确实，但是这个目前没啥好办法优化。

我们尝试过不同的方式优化这个问题，发现目前的方案对大多数有代码块的段落适配性最强，也就是更不可能出现问题。
