### ISSUE TITLE
改进youtube翻译

### ISSUE THREAD

**Issue by devyujie** [immersive-translate/immersive-translate#1075]
### 您希望的更新和改进是什么 | Update or Improve

能否像双语字幕那样，在视频中点击CC字幕就启动翻译，而不是只能在插件里设置**自动开启双语字幕**，因为我发现如果开启自动，CC字幕是被常开的，但是看中文视频的时候显然不需要开CC字幕，而且很多up主都会内置视频字幕，这就造成**字幕重叠**，看英文视频看的又少。这就造成可能需要频繁点开插件设置选项，显然不是很便捷，还有优化体验的空间。

**Comment by theowenyoung** [comment]
或者中文字幕默认不开是不是也能解决这个问题？

**Comment by theowenyoung** [comment]
> 开关选项：是否显示字幕

这个只要不开【自动启用字幕】，字幕就不会显示？

> 下拉选项：仅显示原字幕、仅显示翻译字幕、双语字幕

这个已经支持的，在【更多】，选择 【仅译文】，这样就是只有翻译字幕了。

原字幕的话，直接不启用沉浸式翻译就好了。

**Comment by theowenyoung** [comment]
>   这个目前好像全局生效？要是能单独针对视频字幕就好了，内置的翻译字幕功能每次刷新页面后都需要手动打开，比较麻烦

是的，全局的.. （我感觉这个issue应该提给 youtube... 

>

**Comment by theowenyoung** [comment]
> 或者中文字幕默认不开是不是也能解决这个问题

好吧，这个似乎没法做到，只有在打开字幕之后，我们才能检测到语言..

暂时就手动关闭一下吧。

或者 临时开关下 【自动启用字幕】

**Comment by devyujie** [comment]
那只能先手动了
