### ISSUE TITLE
[Bug]: Azure 翻译挂了

### ISSUE THREAD

**Issue by hcoona** [immersive-translate/immersive-translate#1078]
### 插件版本号 | Version

0.10.9

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

错误信息是 `l.entries() is not iterable`

### 出现问题的网址 | URL

哪个都这个错误

### 重现步骤 | To Reproduce

随便哪个网站，点 Azure 翻译

**Comment by theowenyoung** [comment]
感谢反馈，确实在上个版本引入了bug，上个版本 给 azure 支持了 世纪互联 的自定义api，然后引入此bug.

将在下个版本 0.10.10 修复。
