### ISSUE TITLE
[Bug]: Youtube字幕翻譯的目標語言選取繁體中文時會在開頭顯示出所有字幕的翻譯文本，而非逐句的翻譯

### ISSUE THREAD

**Issue by Yusei-StarDust** [immersive-translate/immersive-translate#1079]
### 插件版本号 | Version

0.10.9

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

Youtube字幕在目標語言選取為繁體中文的時候，會在影片開頭顯示所有文本的譯文，而非逐句翻譯。然若將目標語言轉換成簡體中文就無此Bug。
![image](https://github.com/immersive-translate/immersive-translate/assets/26076608/883eeb1f-4799-474d-8d38-06272ad9e735)

### 补充说明 | Additional context

測試了幾個影片，字幕是英文(自動產生)和英文的話好像會產生這個bug，但有的影片反倒卻沒這問題，實在怪哉。
目標語言選繁體中文有問題的例子：
https://www.youtube.com/watch?v=FbkBdWbCXx8
https://www.youtube.com/watch?v=LBr7kECsjcQ
沒有問題的例子：
https://www.youtube.com/watch?v=r7WgNxoupO0

**Comment by theowenyoung** [comment]
这个好像没法做什么，看了一下 是youtube给的繁体字幕有问题，没法修复：

![img_v2_294774e1-fec7-403a-905b-dbab2896807g](https://github.com/immersive-translate/immersive-translate/assets/62473795/0fca0f43-d69a-4529-ab0a-56174ac4d4ee)


遇到这种视频，可能要去【设置】【视频字幕设置】【使用沉浸式翻译来翻译】 就会优先用沉浸式来翻译字幕，就不会有这个问题...

**Comment by Yusei-StarDust** [comment]
沒想到竟然還有這種事情😮感謝解惑
