### ISSUE TITLE
仓库版本与商店版本不同步

### ISSUE THREAD

**Issue by danielesk** [immersive-translate/immersive-translate#108]
仓库版本0.2.52，chrome商店版本0.2.47
 建议版本稳定后尽量保持，这样可以体验到新版稳定特性

**Comment by theowenyoung** [comment]
嗯，目前一直在持续更新商店版本的，只是商店版本要审核，所以慢一点。（上个版本因为一些问题被驳回了，新版本正在审核中）

**Comment by tianheg** [comment]
Firefox Addon 版本还是 0.2.50
