### ISSUE TITLE
[Bug]:  在谷歌搜索的输入框中，使用输入框快速法翻译不生效

### ISSUE THREAD

**Issue by yamazakitouma** [immersive-translate/immersive-translate#1080]
### 插件版本号 | Version

0.10.9

### 平台 | Platform

macOS

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

1. 进入谷歌搜索主页
2. 在谷歌搜索主页的搜索框中输入中文
3. 连击空格三下，发现无法对输入框键入文本进行翻译

### 出现问题的网址 | URL

 www.google.cn

### 重现步骤 | To Reproduce

1. 进入谷歌搜索主页
2. 在谷歌搜索主页的搜索框中输入中文
3. 连击空格三下，发现无法对输入框键入文本进行翻译

**Comment by theowenyoung** [comment]
是不是按太慢了？

我这测试是ok的。

**Comment by yamazakitouma** [comment]
不是啊，我都快把键盘按废了…… 然后在 JD 的客服聊天界面里，那个输入框生效，我真服了。
