### ISSUE TITLE
pdf翻译时能否保持字体颜色和原来一致

### ISSUE THREAD

**Issue by heheda123123** [immersive-translate/immersive-translate#1083]
### 您希望的更新和改进是什么 | Update or Improve

如图，原来是黑底白字，翻译之后变成了白底黑字，还有白色的方块背景色，看起来就很混乱
![image](https://github.com/immersive-translate/immersive-translate/assets/97490782/09d65431-67c2-46ae-96a2-f398fe3e2a18)
![image](https://github.com/immersive-translate/immersive-translate/assets/97490782/b3e4611f-03a0-4035-b86c-a4d83f3bfbf9)
测试的pdf如下
[test_pdf.pdf](https://github.com/immersive-translate/immersive-translate/files/13256659/test_pdf.pdf)

**Comment by keyboard3** [comment]
嗯 这种情况建议将背景图关掉，因为背景图带了文字，需要通过白色遮盖住原文字才能显示出译文。所以目前没有办法处理
