### ISSUE TITLE
reddit，翻译页面后，在回复框中使用输入框增强功能时，整个页面会重新刷新，输入框会偏离很远

### ISSUE THREAD

**Issue by heheda123123** [immersive-translate/immersive-translate#1084]
### 您希望的更新和改进是什么 | Update or Improve

随便打开一个reddit话题，先翻译页面。
在输入框内输入 // ，后面跟上中文，最后按三次空格。
然后整个页面会刷新，输入框会跑到上面或者下面很远的位置，得找一找

希望能保持输入框的位置在当前可视的位置

**Comment by keyboard3** [comment]
嗯  复现了。这个网站比较特殊，我们正想办法处理

**Comment by keyboard3** [comment]
0.12.7 已修复
