### ISSUE TITLE
希望能支持dropbox同步

### ISSUE THREAD

**Issue by LoneFireBlossom** [immersive-translate/immersive-translate#1085]
### 您希望的更新和改进是什么 | Update or Improve

目前只有Google drive同步，希望能增加dropbox的，因为我所有软件设置都是用dropbox同步的，希望能统一一下；而且众所周知，dropbox对文件同步是所有网盘里最稳定的

**Comment by keyboard3** [comment]
暂无计划增加第三方同步方式
