### ISSUE TITLE
A feature could be provided where the original text is hidden and can only be opened by clicking

### ISSUE THREAD

**Issue by hxypqr** [immersive-translate/immersive-translate#1087]
### 您希望的更新和改进是什么 | Update or Improve

When I checked with Google Translator, I found that this software has the ability to analyze HTML code and translate it line by line. I would like to ask if it is possible to provide a feature that does not retain the original text. I have found that when reading papers, it is actually not necessary to have the original text, only the translated content is sufficient. Alternatively, a feature could be provided where the original text is hidden and can only be opened by clicking, which would improve the overall reading experience

**Comment by theowenyoung** [comment]
Yes, you can change the translation mode to "translation only" by [Show translation Only]

<img width="382" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/b6794b96-c220-4b40-b28b-0d029a85499d">
