### ISSUE TITLE
StackoverFlow翻译后会有遮挡

### ISSUE THREAD

**Issue by evelynn996** [immersive-translate/immersive-translate#1089]
### 您希望的更新和改进是什么 | Update or Improve

复现链接 https://stackoverflow.com/search?q=export+excel

![image](https://github.com/immersive-translate/immersive-translate/assets/93717293/31aaadbd-cd5c-4fe4-a369-7cf7ae7eecd7)

我的翻译设置
![image](https://github.com/immersive-translate/immersive-translate/assets/93717293/9854ee21-1573-4416-9d9f-6f0f945be14b)

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/97386fb7-bc49-4d92-b851-1d335ee6eb73)
已修复 刷新下页面重试下

**Comment by evelynn996** [comment]
> ![image](https://user-images.githubusercontent.com/13177744/280609920-97386fb7-bc49-4d92-b851-1d335ee6eb73.png) 已修复 刷新下页面重试下

感谢~
