### ISSUE TITLE
[Feature Request] 适配微信读书网页版

### ISSUE THREAD

**Issue by jizusun** [immersive-translate/immersive-translate#109]
环境
- Windows 11 Version 22H2
- Firefox Developer Edition 110.0b9 (64-bit)

试了自己上传的epub文件，无法翻译正文。
![image](https://user-images.githubusercontent.com/4011348/217432444-e42a89fa-b988-4468-b8e3-ad6e68ca4ec6.png)

希望[加入开发](https://immersive-translate.owenyoung.com/CONTRIBUTION) ❤️

**Comment by theowenyoung** [comment]
微信读书的页面是 canvas 画出来的，（为了防止别人爬虫），所以没法查看. 建议使用其他epub网站..

https://immersive-translate.owenyoung.com/usage#epub-%E6%96%87%E4%BB%B6%E7%BF%BB%E8%AF%91

**Comment by jizusun** [comment]
> 微信读书的页面是 canvas 画出来的，（为了防止别人爬虫），所以没法查看. 建议使用其他epub网站..
> 
> https://immersive-translate.owenyoung.com/usage#epub-%E6%96%87%E4%BB%B6%E7%BF%BB%E8%AF%91

原来如此，感谢！
