### ISSUE TITLE
[Bug]: 使用会员自带的openai翻译行数较多的字幕文件出现的问题。

### ISSUE THREAD

**Issue by despairTK** [immersive-translate/immersive-translate#1090]
### 插件版本号 | Version

0.11.0

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

使用会员自带的openai翻译行数多的字幕文件时，会出现其中几行无法翻译，或者翻译成其他语言。例如我的字幕文件是日语，翻译成中文，且行数较多，其中几行会出现翻译成英文或者提示英文版的：抱歉，我无法翻译这个语言。即使我设置勾选了翻译缓存，再次放入字幕文件还是同样的结果。

**Comment by despairTK** [comment]
截图补充：
![QQ截图20231106175607](https://github.com/immersive-translate/immersive-translate/assets/111871110/aa377c65-da6e-4393-9be9-75ee142f87e8)
![QQ截图20231106175619](https://github.com/immersive-translate/immersive-translate/assets/111871110/ff7eec90-a175-46fc-a359-dad708ca9831)

**Comment by theowenyoung** [comment]
可以压缩一下字幕文件为 zip 包，上传到这里，我们看看～

**Comment by despairTK** [comment]
[test.zip](https://github.com/immersive-translate/immersive-translate/files/13265430/test.zip)

**Comment by despairTK** [comment]
> 可以压缩一下字幕文件为 zip 包，上传到这里，我们看看~

已上传。

**Comment by despairTK** [comment]
> 测试了一下，似乎是 GPT 的幻觉导致的...GPT 对于日语的支持似乎不太好，我清空缓存之后又试了一下，似乎就正常了。
> 
> [test.zh-CN-dual.srt.zip](https://github.com/immersive-translate/immersive-translate/files/13266000/test.zh-CN-dual.srt.zip)
> 
> <img alt="image" width="532" src="https://user-images.githubusercontent.com/62473795/280693966-56e807d9-f225-4731-82dc-1e7859ca0784.png">

好吧，还有我想问一下。使用 GPT 翻译可以设置翻译字幕时，让 GPT 联系上下文翻译，并且把一些错误的原文词语修正吗？如果可以的话，该怎么设置？
