### ISSUE TITLE
[Bug]: 进行翻译时，有些网站上的元素会被隐藏

### ISSUE THREAD

**Issue by Uoki-im** [immersive-translate/immersive-translate#1091]
### 插件版本号 | Version

V0.11.0

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![屏幕截图 2023-11-06 180533](https://github.com/immersive-translate/immersive-translate/assets/128723466/dee2d03c-be3c-4936-8d50-233934af1d0c)
![屏幕截图 2023-11-06 180548](https://github.com/immersive-translate/immersive-translate/assets/128723466/f3499977-e188-4c01-ab3c-e7e3d3d06001)
![屏幕截图 2023-11-06 181026](https://github.com/immersive-translate/immersive-translate/assets/128723466/5d2f4ab9-c608-4bd1-b482-859081d73b18)
![屏幕截图 2023-11-06 181041](https://github.com/immersive-translate/immersive-translate/assets/128723466/586ef307-ac89-4390-ba83-ca76ebdd9ef3)

### 出现问题的网址 | URL

https://crystalmark.info/en/download/

### 补充说明 | Additional context

另一个翻译后被隐藏元素的网站：https://www.nexusmods.com/cyberpunk2077/mods/2648

这只是其中之二，我试图修改设置，却也是无济于事.

**Comment by keyboard3** [comment]
因为译文目前暂不支持译文保留完整的样式，所以会导致你看到的效果。我们建议大多数情况下尽量用双语对照效果
