### ISSUE TITLE
[Bug]: 某些场景页面的语言切换翻译不对, 应该不是翻译引擎的问题

### ISSUE THREAD

**Issue by Germxu** [immersive-translate/immersive-translate#1093]
### 插件版本号 | Version

latest 0.11.0

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/20300863/f1e31cb7-939e-4765-bd31-28bc8f670f7d)
![image](https://github.com/immersive-translate/immersive-translate/assets/20300863/7274f4b1-523a-4d24-b718-8dd242d7b0d5)

如图所示, 两个页面左下角, 语言列表或者英语页面时, 翻译出来的就是  English=>中文简体
很迷幻, 应该不是翻译引擎的问题?

### 出现问题的网址 | URL

https://learn.microsoft.com/en-us/training/paths/go-first-steps/

### 重现步骤 | To Reproduce

如图所示

**Comment by Germxu** [comment]
> 感谢反馈. 但是我好像有点没明白问题是什么？ 可以再描述下你的操作，你使用的翻译服务，以及你期待的结果是什么吗？

就是它应该翻译的是 English 英文/英语  而不是  中文/简体中文 😂
第二个截图里语言列表可以看到左侧其实还有几个English 也翻译成了中文, 真正的中文选项是在右下角那几个

**Comment by theowenyoung** [comment]
你用的是什么翻译服务，我测试谷歌是正常的：

<img width="1463" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/55a12355-3138-4dac-873e-99e237c40dfc">

**Comment by Germxu** [comment]
微软的翻译, 应该是默认的?
![image](https://github.com/immersive-translate/immersive-translate/assets/20300863/08cd29d6-a2c6-4197-8fb4-218bd91c06ac)

**Comment by theowenyoung** [comment]
嗯，我这里测试微软也是这样的结果。

应该就是翻译引擎的问题。
