### ISSUE TITLE
[Bug]: 某些pdf存在遗漏文本的情况

### ISSUE THREAD

**Issue by heheda123123** [immersive-translate/immersive-translate#1094]
### 插件版本号 | Version

0.11.0

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

这个pdf https://pocoproject.org/slides/000-IntroAndOverview.pdf
会出现下图的情况，清空缓存也没用
![image](https://github.com/immersive-translate/immersive-translate/assets/97490782/0e85359f-6f09-4922-b7c9-406671461258)

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/a0b284e9-a5df-45c6-9458-5a60cc665772)
https://app.immersivetranslate.com/pdf/ 已修复，用这个在线版

**Comment by heheda123123** [comment]
> ![image](https://user-images.githubusercontent.com/13177744/281227899-a0b284e9-a5df-45c6-9458-5a60cc665772.png) https://app.immersivetranslate.com/pdf/ 已修复，用这个在线版

以后不用每次都用在线版吧？等插件更新后也是一样的?

**Comment by keyboard3** [comment]
建议都用在线版，因为这个是实时更新的。 新版本发送会带上最新修复的问题，但是到底是那个版本修复了哪些pdf问题也不会单独记录了

**Comment by heheda123123** [comment]
ok

**Comment by heheda123123** [comment]
就是挺麻烦的，能不能在插件里加个选项，是否使用在线版，勾选之后直接就内置在线版了

**Comment by keyboard3** [comment]
> 就是挺麻烦的，能不能在插件里加个选项，是否使用在线版，勾选之后直接就内置在线版了

主要是在线版无法读取其他域名的pdf文件，浏览器不让跨域访问。你通过插件翻译本地Pdf, 默认已经用的是在线版了。只是保留了对在线pdf使用离线版的功能
