### ISSUE TITLE
能否识别pdf中的代码片段并跳过翻译直接原样输出？

### ISSUE THREAD

**Issue by excosy** [immersive-translate/immersive-translate#1095]
### 您希望的更新和改进是什么 | Update or Improve

&lt;code&gt;在html里能正常识别，pdf里不清楚是否有同样的标记，但代码片段有如下几个不同于常规文本的特征：
* 使用等宽字体；
* 一个单独的段落；
* 总是使用英文；
* 非首行文字左端不会超过首行(因为带有缩进)；
* for xml/html:
  * exists line start with "<" (for xml/html);
  * < > are always paired;
  * exists </\w+>;
* for general code text:
  * exists line end with {, (, [ or only contains {, (, [;
  * exists line only contains }, ), ];
  *  contains more "=" than general paragraph;
* 可能会使用彩色标记单词，不同单词着不同色，相同单词着相同色；
* 整个段落可能带有边框或背景色；

**Comment by keyboard3** [comment]
pdf 它不会存储原始结构数据，所有字符都是单个有自己坐标的数据。 很难简单的通过特殊符号来联系整块代码段。 这里推荐一篇文章，如果你有能力部署的话，可以通过它来ocr pdf文件，能识别出代码块，不过可能样式还原不到原始效果  https://immersivetranslate.com/docs/pdf/nougat/
