### ISSUE TITLE
[Bug]: 输入增强没生效

### ISSUE THREAD

**Issue by ghost** [immersive-translate/immersive-translate#1099]
### 插件版本号 | Version

0.11.3

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

有时候在油管等网页上输入中文然后“输入框增强”连续3次空格无法翻译中文。

**Comment by keyboard3** [comment]
输入速度够快嘛？

**Comment by keyboard3** [comment]
长时间无反馈，暂时关闭此issue
