### ISSUE TITLE
翻译本地pdf文件发现的问题

### ISSUE THREAD

**Issue by danielesk** [immersive-translate/immersive-translate#110]
【以下出现的问题是在默认（自动缩放）模式下打开的】
- 当前处于翻译模式，上下翻页的时候会经常性的出现不自动翻译的情况
- 翻译会出现遮挡的情况
![image](https://user-images.githubusercontent.com/10652829/217439725-d84e6d20-94e0-47e1-95cd-96465caa6d74.png)
- 翻译出现出现重叠遮盖现象
![image](https://user-images.githubusercontent.com/10652829/217440163-6148fe10-9124-41fe-ba70-2117daf1eec1.png)
![image](https://user-images.githubusercontent.com/10652829/217440410-5902ba97-4a4c-4b22-b598-cc77e93167c9.png)
- 断句展示有问题
![image](https://user-images.githubusercontent.com/10652829/217440676-2810dc3b-6c9a-4f9a-9dbe-100681b29eee.png)
![image](https://user-images.githubusercontent.com/10652829/217441182-66867ba3-c703-4d85-8405-29c0ffb8f095.png)
- 有时候会对代码进行翻译
![image](https://user-images.githubusercontent.com/10652829/217441555-e0bf8c7f-c81c-4d22-80a8-486a799f0574.png)
- 启用虚线标注翻译的内容的时候，会出现交叉
![image](https://user-images.githubusercontent.com/10652829/217441764-c1c60f27-63ce-45ac-bedf-6e9e006eb786.png)
- 侧边目录未隐藏的时候翻译内容出现覆盖问题，隐藏重新翻译不会出现
![image](https://user-images.githubusercontent.com/10652829/217443385-3358fc54-5b22-4187-bdfc-5e72cbaf4dbe.png)

**Comment by theowenyoung** [comment]
确实, pdf的翻译目前有点粗糙，需要时间优化..

**Comment by danielesk** [comment]
@theowenyoung 身边朋友用的挺多的，麻烦优化优化吧

**Comment by theowenyoung** [comment]
暂时可以先通过 别的工具比如： https://calibre-ebook.com/ 转为 html或者epub，然后再翻译，这样体验最好。

**Comment by danielesk** [comment]
试了类似的工具，把pdf转epub格式后错乱比较严重，我先凑合用吧

**Comment by theowenyoung** [comment]
PDF相关问题统一在 https://github.com/immersive-translate/immersive-translate/issues/37 里讨论，暂时先关闭这个问题了
