### ISSUE TITLE
[Bug]: Udemy翻譯字幕時有時無

### ISSUE THREAD

**Issue by argo057** [immersive-translate/immersive-translate#1102]
### 插件版本号 | Version

0.11.2

### 平台 | Platform

iOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

有些字幕有翻譯，有些沒有
但在右邊的逐字稿，卻都有翻譯
![IMG_2949](https://github.com/immersive-translate/immersive-translate/assets/10750294/9d1ff6a0-7788-427a-abc7-338d4575861d)
![IMG_2950](https://github.com/immersive-translate/immersive-translate/assets/10750294/c8017093-f184-4612-8865-1aef6f96702d)

### 出现问题的网址 | URL

https://www.udemy.com/course/mastering-microcontroller-with-peripheral-driver-development/learn/lecture/17154118#overview

### 重现步骤 | To Reproduce

在Udemy的課程中使用英文字幕

**Comment by FattySpring** [comment]
[版本 0.12.2](https://immersivetranslate.com/docs/CHANGELOG/#0122) 已优化 Udemy 双语字幕
