### ISSUE TITLE
[Bug]:macOS Safari不显示悬浮球

### ISSUE THREAD

**Issue by yzsang** [immersive-translate/immersive-translate#1103]
### 插件版本号 | Version

0.11.3

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

Mac不显示悬浮球，不知道是否不支持，已在设置页面打开悬浮球

**Comment by keyboard3** [comment]
已支持，重新去设置页面打开悬浮球试下
