### ISSUE TITLE
[Bug]: 多端登录后，默认开启同步，之后无法修改设置

### ISSUE THREAD

**Issue by linharrrrrt** [immersive-translate/immersive-translate#1104]
### 插件版本号 | Version

0.11.4

### 平台 | Platform

Windows, macOS, iOS

### 浏览器 | Browsers

Chrome, Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

多端登录后，默认开启同步，之后无法修改设置。一修改就被改回去了。

### 重现步骤 | To Reproduce

多端登录后，默认开启同步，之后无法修改设置。一修改就被改回去了。

### 补充说明 | Additional context

一修改就被改回去了。

**Comment by linharrrrrt** [comment]
发现了问题是不同浏览器之间的时间问题，同步备份使用的时间是浏览器自带的时间，如果某一个浏览器的时间比其他的都早，那么就只能在最早的时间的那个浏览器里才能够修改设置。建议更改为记录同步服务器的时间。

**Comment by keyboard3** [comment]
抱歉这么晚才回复，我们已经修复了这个问题，只要本地变动配置，就会自动上传到云端
