### ISSUE TITLE
[Bug]: Typora官网FAQ页面排版错误

### ISSUE THREAD

**Issue by V-arc** [immersive-translate/immersive-translate#1105]
### 插件版本号 | Version

0.11.4

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/53041402/af2020ad-1600-4fbb-8809-8e68019c9b53)

### 出现问题的网址 | URL

https://store.typora.io/#faq

### 重现步骤 | To Reproduce

直接翻译

### 补充说明 | Additional context

可能需要科学上网访问页面。

**Comment by keyboard3** [comment]
这个网站的排版都是绝对定位，插件无法干预它。 你可以通过拖动浏览器窗口，让这个网页自动重排就正常了
