### ISSUE TITLE
Twitter回复加上emjoy后，无法使用输入框增强

### ISSUE THREAD

**Issue by myh66** [immersive-translate/immersive-translate#1106]
### 您希望的更新和改进是什么 | Update or Improve

实测emjoy在前面时候：
$ emjoy文本
启动输入框增强后
$ 文本
或者
$ emjpy 文本
有时候不保留emjo，y部分情况会保留emjoy

实测emjoy在末尾时候：
无法启用输入框增强

实测emjoy在中间时候：
$会保留
（不确定是否全部emjoy都会保留）

### 补充说明 | Additional context

识别只翻译文本，跳过emjoy，颜文字之类的

**Comment by keyboard3** [comment]
0.11.6 已修复
