### ISSUE TITLE
[Bug]: 在斗鱼页面开启插件会导致音画不同步

### ISSUE THREAD

**Issue by chris7395328** [immersive-translate/immersive-translate#1107]
### 插件版本号 | Version

0.11.4

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

edge浏览器，在斗鱼页面开启插件会导致音画不同步，不过如果设置d3d9模式就没问题，虽然是中文网站排除掉就行，不过应该是个bug，不确认会不会在别的网站出现。

### 出现问题的网址 | URL

https://www.douyu.com/2125

**Comment by FattySpring** [comment]
原理上我们不会干扰视频播放，未能复现该问题，暂时关闭
