### ISSUE TITLE
[Bug]: 在Android上访问reddit有几率使页面无法上下滑动

### ISSUE THREAD

**Issue by urkbio** [immersive-translate/immersive-translate#1109]
### 插件版本号 | Version

0.10.9

### 平台 | Platform

Android

### 浏览器 | Browsers

Other

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

我在Mull浏览器(based firefox)，以及kiwi浏览器(based chromium)上都遇到这个问题，当我登入reddit浏览主页面时，扩展程序开启翻译就有很大概率无法滑动页面，关掉翻译后刷新页面也不行，只有禁用掉扩展才行。

### 出现问题的网址 | URL

https://www.reddit.com

### 重现步骤 | To Reproduce

在开启扩展并在设置中设定自动翻译的情况下打开reddit网站就会复现，但是从google搜索页面进入的reddit自页面就是正常的。

### 补充说明 | Additional context

暂无

**Comment by FattySpring** [comment]
在Android kiwi 和 Firefox Beta 中都没能复现该问题

**Comment by urkbio** [comment]
> 在Android kiwi 和 Firefox Beta 中都没能复现该问题

那或许跟我手机开的无障碍有关吧，

**Comment by keyboard3** [comment]
那 暂时关闭这个issue哈
