### ISSUE TITLE
发现一个无法翻译正文的网页

### ISSUE THREAD

**Issue by Gd-Gordon** [immersive-translate/immersive-translate#111]
提供给开发者参考
https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/work-holiday-462/specified-462-work

**Comment by theowenyoung** [comment]
感谢反馈，已确认问题，预计下个版本修复～

该网页使用了自定义元素，判断自定义元素出了点问题。

**Comment by crocodile2021** [comment]
已修复，感谢反馈～
