### ISSUE TITLE
在discord网页版输入框按三下空格翻译之后，就无法编辑输入框内容

### ISSUE THREAD

**Issue by Chitsing** [immersive-translate/immersive-translate#1110]
### 您希望的更新和改进是什么 | Update or Improve

沉浸式翻译在discord网页版输入框里面，按三个空格翻译之后，就无法编辑输入框。
只能继续输入，或者移动光标。而无法执行删除文字，复制粘贴剪切之类的其他动作。

ps：记得前段时间用还可以的，今天用突然就不可以了。
系统macos 14.2，浏览器chrome 117.0.5938.149 (Official Build) (arm64)

**Comment by theowenyoung** [comment]
我这里测试是ok的，具体是哪个网址呢？

**Comment by theowenyoung** [comment]
好吧.. Chrome 不行， Firefox 可以。

**Comment by keyboard3** [comment]
0.11.5 已修复

**Comment by Chitsing** [comment]
刚测试能用了，作者牛皮，すごい，Excellent！
