### ISSUE TITLE
[Bug]: 华为P20手机X浏览器无法启动插件

### ISSUE THREAD

**Issue by kicer** [immersive-translate/immersive-translate#1111]
### 插件版本号 | Version

all

### 平台 | Platform

Android

### 浏览器 | Browsers

Other

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

华为P20手机，使用x浏览器，安装插件的油猴脚本后无法启动，右侧不显示插件图标，四指点击也没办法触发。
更换为华为P40手机，使用同一版本的x浏览器及脚本，可以正常使用。

直接在浏览器中输入 https://dash.immersivetranslate.com/ 网址，Options页一直显示Loading...字符，无法加载配置项。
打开x浏览器的远程调试功能，加载页面后console里提示：
_VM842:4600 Uncaught SyntaxError: Unexpected token '('_
对应的代码行开头部分：
_u(t){try{let{value:n,done:a}=await t.next();a?--this.#e:this.#t.push({iterator:t,value_

华为P20手机Android System WebView版本：83.0.4103.106

### 出现问题的网址 | URL

all

**Comment by theowenyoung** [comment]
应该是 浏览器内核版本太低的问题。这个可能无法解决。

**Comment by kicer** [comment]
更新108版本Android System Webview后问题解决。谢谢~
