### ISSUE TITLE
why not read aloud (TTS) with bilingual audio

### ISSUE THREAD

**Issue by trionline1234** [immersive-translate/immersive-translate#1112]
### 您希望的更新和改进是什么 | Update or Improve

Read aloud website (Text to speech) with bilingual language.

With each sentence, first , extension will read aloud with mother language, after that, extension will read aloud with original language of text many times with different speeds.
It will help for foreign language learner can practice listening with bilingual audio.

Todays, most extension with TTS only read text with just one language (such as https://chrome.google.com/webstore/detail/read-aloud-a-text-to-spee/hdhinadidafjejdhmfkjgnolgimiaplp)

**Comment by theowenyoung** [comment]
Sorry, we have no plans to add this feature in the future
