### ISSUE TITLE
YouTube自动隐藏悬浮球

### ISSUE THREAD

**Issue by threeshui1024** [immersive-translate/immersive-translate#1113]
### 您希望的更新和改进是什么 | Update or Improve

YouTube视频播放时不会自动隐藏悬浮球，bilibili是可以的（edge版本）
![image](https://github.com/immersive-translate/immersive-translate/assets/85988748/bd7a034b-7eb4-4456-8b50-41bc61bacdaf)

**Comment by BlueDolphin9527** [comment]
我也有类似的问题，希望检测到网页全屏，或者显示器全屏时自动隐藏。

**Comment by FattySpring** [comment]
> 我也有类似的问题，希望检测到网页全屏，或者显示器全屏时自动隐藏。

[0.12.7](https://immersivetranslate.com/docs/CHANGELOG/#0127)  已支持
