### ISSUE TITLE
改进建议：嵌套标签翻译导致内部标签元素消失问题

### ISSUE THREAD

**Issue by SMWHff** [immersive-translate/immersive-translate#1114]
### 您希望的更新和改进是什么 | Update or Improve

`<p>还没有账户？<span href="/auth/email-signup">注册</span></p>`
翻译后会导致内层标签元素丢失
`<font>还没有账户？注册</font>`

希望翻译后，也能保留内部标签元素。

**Comment by theowenyoung** [comment]
和 #871 #703  是一个问题。由于目前的整个方案是纯文本翻译，所以译文无法保留原格式，建议在双语模式下使用。

**Comment by mefengl** [comment]
那就在这里继续讨论吧，

如果可以添加尾注的话，其实也没什么大问题。ChatGPT 那样的尾注也不是很难看。

![image](https://github.com/immersive-translate/immersive-translate/assets/71683364/81e77f96-8e5f-4ae2-81e8-0012c0ebeb82)
![image](https://github.com/immersive-translate/immersive-translate/assets/71683364/ab87215f-2dc3-4168-9bee-3792e7da3f27)
