### ISSUE TITLE
沉浸式翻译翻译后的双语页面分享功能改进

### ISSUE THREAD

**Issue by 7234399** [immersive-translate/immersive-translate#1115]
### 您希望的更新和改进是什么 | Update or Improve

现在只有生成分享界面后才可以编辑翻译后的中文内容，而且是全文分享，而且内容重新排版了并且字体颜色重置了，这样的局限性太高了。
你们支持编辑翻译后的内容，那么应该是认可翻译的内容存在不准确的影响，我建议直接在原始的显示界面能对翻译后的中文增加编辑的功能，这样对于只想分享部分内容或者保存部分内容的直接截图就行了。

**Comment by JiangYain** [comment]
I am looking forward to the support for Markdown formatting on this sharing page, otherwise the original page will become chaotic

**Comment by keyboard3** [comment]
0.11.6 分享升级了保存页面快照
