### ISSUE TITLE
关于切换翻译服务的建议

### ISSUE THREAD

**Issue by 7234399** [immersive-translate/immersive-translate#1116]
### 您希望的更新和改进是什么 | Update or Improve

1.建议在扩展图标-翻译服务的选项中把需要设置的翻译删除掉。因为在这个界面要切换翻译服务的话是希望快速的切换了。现在的设置需要在所有的翻译服务里面去一个个找，这样太麻烦了。如果需要设置的话直接在设置里面去提前设置就好了，没有必要在这里把不能直接使用的翻译服务显示出来了。
![Nov08 11,11](https://github.com/immersive-translate/immersive-translate/assets/64468931/696a2168-00be-485f-8d5d-a08d32513b94)

2.建议鼠标悬停翻译某一段文字时增加切换别的翻译服务功能。这样可以对某一些全局翻译不准确的内容可以显示原文后再重新使用别的更加准确的翻译服务重新翻译。现在的鼠标悬停的功能只有显示全文翻译的内容或者还原原文，功能有点太单一了
![Nov08 11,29](https://github.com/immersive-translate/immersive-translate/assets/64468931/c6183a18-4798-4f4b-b5e4-4fa6ba2214e9)

3.在V0.11.5版本的更新中增加了翻译界面的分享功能，应该你们也考虑到了大家有翻译界面有分享，以及保存的需求。但是现在的功能是重新生成分享的界面后才支持译文编辑的功能。建议在原文显示的时候就支持译文编辑的功能。这样对于一些希望分享或者保存的信息存在翻译不准的问题时直接编辑好之后再选择截图保留或者分享或者直接选择现有的全文分享了。

**Comment by theowenyoung** [comment]
> 1.建议在扩展图标-翻译服务的选项中把需要设置的翻译删除掉。因为在这个界面要切换翻译服务的话是希望快速的切换了。现在的设置需要在所有的翻译服务里面去一个个找，这样太麻烦了。如果需要设置的话直接在设置里面去提前设置就好了，没有必要在这里把不能直接使用的翻译服务显示出来了。


为了保持设置简单易懂，目前该功能没有做在 UI里，可以在【开发者射者】，【Full User Config】里添加这个选项，可以关闭：

```json
  "showUnconfiguredTranslationServiceInPopup": false
```

> 2.建议鼠标悬停翻译某一段文字时增加切换别的翻译服务功能。这样可以对某一些全局翻译不准确的内容可以显示原文后再重新使用别的更加准确的翻译服务重新翻译。现在的鼠标悬停的功能只有显示全文翻译的内容或者还原原文，功能有点太单一了

目前在设置页面里，支持对 鼠标滑过 使用 独立的翻译服务，也许这个可以满足需求？

> 在V0.11.5版本的更新中增加了翻译界面的分享功能，应该你们也考虑到了大家有翻译界面有分享，以及保存的需求。但是现在的功能是重新生成分享的界面后才支持译文编辑的功能。建议在原文显示的时候就支持译文编辑的功能。这样对于一些希望分享或者保存的信息存在翻译不准的问题时直接编辑好之后再选择截图保留或者分享或者直接选择现有的全文分享了。

#83 #236  也与此有关，这个后面应该会支持，但是需要一些时间，目前的分享功能是为了让用户能快速的自动提取文章内容，生成一个干净的页面用来分享长文。

**Comment by theowenyoung** [comment]
第三个和 #1115 重复。
