### ISSUE TITLE
[Bug]:  无法识别页面内容进行翻译

### ISSUE THREAD

**Issue by snaigle** [immersive-translate/immersive-translate#1117]
### 插件版本号 | Version

0.11.4

### 平台 | Platform

macOS

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

未识别到网页的内容进行翻译

### 出现问题的网址 | URL

https://developer.apple.com/documentation/storekit/in-app_purchase/original_api_for_in-app_purchase/subscriptions_and_offers/handling_subscriptions_billing#3221919

### 重现步骤 | To Reproduce

1. 打开页面
2. 点击插件的翻译按钮
3. 页面未进行翻译

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/ab4e7864-328c-47f4-a38c-577ff3c78453)
可以翻译，你滑动顶部

**Comment by snaigle** [comment]
从顶部开始是可以翻译的， 感谢
