### ISSUE TITLE
文档手册类型的网页，左侧的导航目录经常没有翻译

### ISSUE THREAD

**Issue by monkeypiggy** [immersive-translate/immersive-translate#1118]
### 您希望的更新和改进是什么 | Update or Improve

https://pep8.org/
例如这个，翻译后只有右侧被翻译了，左侧还是英文。

**Comment by Maxopopopop** [comment]
你是不是没有在设置里面开启全部翻译

**Comment by keyboard3** [comment]
默认只翻译主要内容区域，可以通过上面这位同学说的翻译全部区域或者鼠标悬停翻译
