### ISSUE TITLE
[Bug]: 请求适配fonts.google.com/icons

### ISSUE THREAD

**Issue by Calm-er** [immersive-translate/immersive-translate#1119]
### 插件版本号 | Version

0.11.5

### 平台 | Platform

Windows, macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

https://fonts.google.com/icons?icon.platform=web
图标被翻译

### 出现问题的网址 | URL

https://fonts.google.com/icons?icon.platform=web

**Comment by FattySpring** [comment]
在【翻译主要区域】下正常，是否启用了 【翻译所有区域】？

**Comment by keyboard3** [comment]
暂无反馈 关闭此issue
