### ISSUE TITLE
建议百度翻译添加action=1参数，开启术语库翻译功能。

### ISSUE THREAD

**Issue by romejiang** [immersive-translate/immersive-translate#112]
在api接口添加action=1 可以开启术语库功能，望实现。

百度翻译的API文档
https://fanyi-api.baidu.com/doc/21

**Comment by theowenyoung** [comment]
好的，谢谢建议，相当于 为不同的翻译服务添加一些自定义的配置～

可能要一点时间才有时间加这个.

**Comment by theowenyoung** [comment]
抱歉，这个问题拖了太久了，该选项将在 0.10.7 版本支持，预计明天发布。

<img width="708" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/789d99a7-7733-4030-a1f8-88cffdb1afb1">

**Comment by theowenyoung** [comment]
已发布。
