### ISSUE TITLE
[Bug]: bing chat里的聊天输入框无法启用输入框增强，按3次空格键没反应

### ISSUE THREAD

**Issue by leslietoo** [immersive-translate/immersive-translate#1120]
### 插件版本号 | Version

0.11.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

bing chat里的聊天输入框无法启用输入框增强，按3次空格键没反应

### 出现问题的网址 | URL

bing.com

### 重现步骤 | To Reproduce

1. edge打开bing.com
2. 搜索栏下方一排按钮点聊天
3. 聊天输入框里输入中文按3次空格无反应
4. 另外，edge浏览器右侧栏里的copilot聊天输入框也是如此

![微信截图_20231116104741](https://github.com/immersive-translate/immersive-translate/assets/9415065/e0c0a6c0-d02b-4a6c-bba4-671b5da581c2)
![微信截图_20231116105235](https://github.com/immersive-translate/immersive-translate/assets/9415065/371c4901-f5c6-4e78-a185-5f67f7f9f713)

**Comment by keyboard3** [comment]
可以扫下兼容性文档，不兼容 https://immersivetranslate.com/docs/input/#%E5%85%BC%E5%AE%B9%E6%80%A7
