### ISSUE TITLE
从繁体中文翻译为简体中文的时候，建议直接替换，而不是新增一列

### ISSUE THREAD

**Issue by vicentory** [immersive-translate/immersive-translate#1121]
### 您希望的更新和改进是什么 | Update or Improve

从繁体中文翻译为简体中文的时候，建议直接替换，而不是新增一列。
估计这样，可能涉及到底层显示逻辑的改变。

### 补充说明 | Additional context

其实类似简繁转换插件，以前有个好用的插件，找不到了。Chrome应用商店搜到的都是单独窗口打开转换的，不是直接在网页显示为简体字。

**Comment by Vstory** [comment]
我记得设置有选项可以设置是替换原文的吧

**Comment by keyboard3** [comment]
针对简繁互换特殊需求，建议使用更多中有仅译文显示

**Comment by vicentory** [comment]
@keyboard3 @Vstory 简繁互换特殊需求，更多中和设置里都没有选项可以设置是替换原文的，大佬截图看一下呢。多谢
