### ISSUE TITLE
[Bug]: 安卓手机或平板上无法翻译离线mhtml

### ISSUE THREAD

**Issue by ew010** [immersive-translate/immersive-translate#1122]
### 插件版本号 | Version

0.11.5

### 平台 | Platform

Android

### 浏览器 | Browsers

Other

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在安卓平板上用狐猴浏览器或kiwi浏览器使用插件无法翻译离线mhtml，已确认【允许访问文件网址】已打开

**Comment by keyboard3** [comment]
这是因为狐猴浏览器即使开启了允许访问网址，它仍然没给我插件权限。 这个应该是他们这块实现未支持。建议采用pc电脑访问mhtml文件
