### ISSUE TITLE
[Bug]: pdf某些页内翻译文本会重复

### ISSUE THREAD

**Issue by hidaris** [immersive-translate/immersive-translate#1123]
### 插件版本号 | Version

0.11.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/8336146/ab24adda-5ed0-4132-ad2c-4a22ab62d2d8)
如图，文本会重复，且相互之间似乎有些漂移。

### 出现问题的网址 | URL

https://engraft.dev/engraft-uist-2023.pdf

### 重现步骤 | To Reproduce

1. 点击翻译pdf
2. 下划到第5页

**Comment by keyboard3** [comment]
这个pdf提取的原始数据出现脏数据，不仅包含大块重复还有零散的小块文字重复。这个pdf很难去自动适配修复
