### ISSUE TITLE
[Bug]: 部分网站的网页PDF翻译功能失效

### ISSUE THREAD

**Issue by moolawooda** [immersive-translate/immersive-translate#1127]
### 插件版本号 | Version

0.11.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox, Chrome, Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

部分期刊的网页，无法直接在页面内翻译pdf文档，需要下载后再导入翻译

### 出现问题的网址 | URL

https://journals.aps.org/prx/pdf/10.1103/PhysRevX.13.041032

### 重现步骤 | To Reproduce

1. 打开上述链接，自动进入浏览器的pdf阅读界面
2. 点击插件的翻译按钮
3. 显示翻译成功，但没有效果

### 补充说明 | Additional context

目前发现APS旗下的期刊都有这个无法翻译的问题，其余期刊的网页版pdf翻译正常，暂未发现问题。

**Comment by keyboard3** [comment]
嗯 这是个已知问题，之后会处理这个case

**Comment by keyboard3** [comment]
0.11.6 已修复
