### ISSUE TITLE
[Bug]: 在Product Hunt失效

### ISSUE THREAD

**Issue by KamiyaMinoru** [immersive-translate/immersive-translate#1128]
### 插件版本号 | Version

0.11.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 请描述这个Bug | Describe the bug

在Product Hunt失效, 只會翻譯文章或區塊標題

### 出现问题的网址 | URL

www.producthunt.com

### 重现步骤 | To Reproduce

N/A

### 补充说明 | Additional context

N/A

**Comment by keyboard3** [comment]
截个图？ 我这里都很正常啊
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/8d860f58-f25c-4e14-90c6-539babee511f)

**Comment by KamiyaMinoru** [comment]
> 截个图？ 我这里都很正常啊 ![image](https://user-images.githubusercontent.com/13177744/284109104-8d860f58-f25c-4e14-90c6-539babee511f.png)

在有些頁面成功 有些則失敗
以下範例網址為: https://www.producthunt.com/categories/work-productivity
![image](https://github.com/immersive-translate/immersive-translate/assets/78710607/6bed6e3a-fc16-48e5-96a3-bdf51f0971ca)

**Comment by keyboard3** [comment]
这个网站实现不规范  要保证双语效果不错乱，必须一对一适配。建议配合鼠标悬停翻译作为补充

**Comment by keyboard3** [comment]
或者选择翻译全部区域
