### ISSUE TITLE
不要翻译代码

### ISSUE THREAD

**Issue by 164105419** [immersive-translate/immersive-translate#1129]
### 您希望的更新和改进是什么 | Update or Improve

![image](https://github.com/immersive-translate/immersive-translate/assets/48908160/08b611aa-f623-4069-b9fe-b789b8aa07ed)
![image](https://github.com/immersive-translate/immersive-translate/assets/48908160/5a64b4ee-c74c-447a-95f2-2eeb8a844a76)

如上图所示.希望能修改.感谢

**Comment by theowenyoung** [comment]
你好，请附上 URL，谢谢！

**Comment by 164105419** [comment]
> 你好，请附上 URL，谢谢！

https://forum.unity.com/threads/detect-when-device-changes-and-get-corresponding-control-scheme.1384584/#post-9211338

**Comment by keyboard3** [comment]
已修复 刷新下页面
