### ISSUE TITLE
nature杂志总是网页全文翻译不全

### ISSUE THREAD

**Issue by mhChen-1991** [immersive-translate/immersive-translate#113]
https://www.nature.com/articles/s41392-022-01235-0
以上面的网址为例，总是只有部分的段落，得到了翻译。拉到网页下面（或自然滚动鼠标到网页其它地方），就会不翻译了。
即使点插件的“翻译所有区域”，也只会让眼前上下文的段落有翻译，其它部分，还是没有翻译。

**Comment by theowenyoung** [comment]
这个网址我点进去，不管滑动到哪，好像都会翻译呀。

你是只有这个网页有问题，还是所有网页都有类似的问题.

**Comment by mhChen-1991** [comment]
> 这个网址我点进去，不管滑动到哪，好像都会翻译呀。
> 
> 你是只有这个网页有问题，还是所有网页都有类似的问题.

我之前在nature正刊（访问网页全文需要版权）遇到这个问题。现在https://www.nature.com/articles/s41392-022-01235-0这个可以免费访问网页全文的期刊，也是遇到同样问题。所以才过来提问。

![image](https://user-images.githubusercontent.com/53018298/217465662-46b5ef77-0130-404e-b85b-3114c7defbe0.png)

我的版本是谷歌商店的版本，v0.2.47，使用win的chrome浏览器。

**Comment by crocodile2021** [comment]
已调整适配nature，点击浏览器插件图标会自动更新到最新版本。感谢反馈～

**Comment by theowenyoung** [comment]
暂时关掉这个问题了，有问题再打开。
