### ISSUE TITLE
[Bug]: OpenAi 無法翻譯為繁體中文

### ISSUE THREAD

**Issue by curtiswu33** [immersive-translate/immersive-translate#1130]
### 插件版本号 | Version

0.11.4

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

使用OpenAi 選擇目標語言為繁體中文，只會翻譯為簡體中文。

**Comment by dreamstyle** [comment]
+1

**Comment by theowenyoung** [comment]
请问有示例网页吗？我这里最新版本正常的。

**Comment by dreamstyle** [comment]
例如這個網頁：https://livingos.substack.com/p/embracing-discomfort-the-unlikely
![截圖 2023-12-11 上午10 11 33](https://github.com/immersive-translate/immersive-translate/assets/5866829/12a2da01-2778-4ac8-b490-fa6d3c5f34bd)
![截圖 2023-12-11 上午10 11 52](https://github.com/immersive-translate/immersive-translate/assets/5866829/05072564-0964-4744-9709-71dca376cc5e)
![截圖 2023-12-11 上午10 12 01](https://github.com/immersive-translate/immersive-translate/assets/5866829/eebb25c1-366a-4fe4-8231-6bd8b2955e4e)

我在推特使用時，大部分也是翻譯成簡體中文，只有一小部分會翻譯成繁體中文。

**Comment by curtiswu33** [comment]
剛剛試了一下，我這個網頁倒是正常的。

**Comment by curtiswu33** [comment]
> 我在推特使用時，大部分是翻譯成簡體中文，只有一小部分會翻譯成繁體中文。
> 
> 其他網頁也常常翻譯成簡體中文，例如這個網頁：https://livingos.substack.com/p/embracing-discomfort-the-unlikely
> 
> ![截圖 2023-12-11 上午10 11 33](https://private-user-images.githubusercontent.com/5866829/289407910-12a2da01-2778-4ac8-b490-fa6d3c5f34bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNjUzMjYsIm5iZiI6MTcwMjI2NTAyNiwicGF0aCI6Ii81ODY2ODI5LzI4OTQwNzkxMC0xMmEyZGEwMS0yNzc4LTRhYzgtYjQ5MC1mYTZkM2M1ZjM0YmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTFUMDMyMzQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTk2YzZkNmMyYjYyYTk1ZDc4ODNhNGM4Yzk0YjFlMmIyNzg0Yzg2NTU2ZGI1ZWVmMDZkZWMzNTBiNDc5OTgxMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6-5o-D9LgvcTghx_oEvhmC7OQHIYYtq0yhSX9kNiprU) ![截圖 2023-12-11 上午10 11 52](https://private-user-images.githubusercontent.com/5866829/289407924-05072564-0964-4744-9709-71dca376cc5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNjUzMjYsIm5iZiI6MTcwMjI2NTAyNiwicGF0aCI6Ii81ODY2ODI5LzI4OTQwNzkyNC0wNTA3MjU2NC0wOTY0LTQ3NDQtOTcwOS03MWRjYTM3NmNjNWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTFUMDMyMzQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGU5MWM2Y2Y5MTI5MjFjMDBjZjkyODA2YjhhMjZiNWZkZTNiM2IxMzhhNjkxMGFhZWE0OWI2ZGQ4YjJiMzE1ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4WYnloFNh6283j-l97XBW1qRD9Ku1Qp2ADAbnysaLUk) ![截圖 2023-12-11 上午10 12 01](https://private-user-images.githubusercontent.com/5866829/289407931-eebb25c1-366a-4fe4-8231-6bd8b2955e4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNjUzMjYsIm5iZiI6MTcwMjI2NTAyNiwicGF0aCI6Ii81ODY2ODI5LzI4OTQwNzkzMS1lZWJiMjVjMS0zNjZhLTRmZTQtODIzMS02YmQ4YjI5NTVlNGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTFUMDMyMzQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmZlZDlkNWI4M2Y0MWE0MDJmNmRiMjEwOTRlNzFhY2ZmOTM1MmNjYzBhN2VmNWVmYWIzN2YzY2ZlZWU4YTZjYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KJdmpEQWXtv5r6zzSDfngWQY-Avq93PAX1HQCwOzTI8)
> 
> ###  插件版本號 | 版本
> 0.12.5
> 
> ###  平台 | 平台
> macOS
> 
> ###  瀏覽器 | Browsers
>  Arc（基於Chromium的）
> 
> ### 插件類型 | Extension Type
> 瀏覽器插件 | 瀏覽器擴充功能

剛剛試了一下，這個網頁我倒是正常的。

**Comment by dreamstyle** [comment]
@theowenyoung 可以顯示繁體中文了，這太棒了，謝謝你 ❤️
