### ISSUE TITLE
不知道算是bug还是功能改进，连网页上的翻译插件也一起翻译了

### ISSUE THREAD

**Issue by freedomspiritJohn** [immersive-translate/immersive-translate#1131]
### 您希望的更新和改进是什么 | Update or Improve

https://github.com/chunibyocola/sc-translator-crx

这个浏览器插件，当我在阅读英文文章的时候，我开启了沉浸式翻译，并且用可可翻译（上面那个插件）进行查询不认识的单词，但是他把可可翻译也一起翻译了，希望可以设置排除。

![image](https://github.com/immersive-translate/immersive-translate/assets/129288685/aa336f92-4f60-41a2-bd15-0dd21032ae82)

### 补充说明 | Additional context

对于是否要移除它，我不确定，因为他有时候的翻译也是有用的，但是有时候又不想让他翻译。所以希望可以自定义是否翻译这个。因此我觉得可以考虑是否翻译某个div，或者忽略它

**Comment by KamiyaMinoru** [comment]
同樣發現此問題: 使用extension為Monica
![image](https://github.com/immersive-translate/immersive-translate/assets/78710607/46034039-4014-4bbd-86fb-2c976603f80a)

![image](https://github.com/immersive-translate/immersive-translate/assets/78710607/bad2addf-e92d-4a38-b127-db829cea0ee7)

**Comment by keyboard3** [comment]
> 同樣發現此問題: 使用extension為Monica https://monica.im/?locale=zh_TW ![image](https://user-images.githubusercontent.com/78710607/284116589-bad2addf-e92d-4a38-b127-db829cea0ee7.png)

monica 已排除翻译，稍后刷新页面即可

**Comment by keyboard3** [comment]
你这个插件需要下个版本升级才能排除

**Comment by keyboard3** [comment]
更新下0.11.6 已修复
