### ISSUE TITLE
[Bug]: 上下标不能准确翻译

### ISSUE THREAD

**Issue by 457963413** [immersive-translate/immersive-translate#1136]
### 插件版本号 | Version

0.11.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

对于有化学式的网页如化学文献，原有的上下标在译文中不能准确展示。偶尔能正确显示，但大部分时候都是错误的，如字符消失或变成其他字符甚至数字。

**Comment by keyboard3** [comment]
贴下网址

**Comment by keyboard3** [comment]
暂无反馈 暂时关闭此问题
