### ISSUE TITLE
手機網頁版Youtube

### ISSUE THREAD

**Issue by Superoldman96** [immersive-translate/immersive-translate#1137]
### 您希望的更新和改进是什么 | Update or Improve

能不能在手機用網頁版Youtube的時候，打開全屏的時候，也可以顯示字幕。
![IMG_2236](https://github.com/immersive-translate/immersive-translate/assets/43429446/fd05bd67-b2f4-4e84-b54b-63588c30b0b8)
![IMG_2237](https://github.com/immersive-translate/immersive-translate/assets/43429446/82fe691e-9d79-46f3-8ed6-00a8230427b4)

**Comment by FattySpring** [comment]
YouTube web 在iOS Safari上全螢幕沒有影片跟YouTube本身有關，暫無解決方式。
