### ISSUE TITLE
[Bug]: 在web of science界面，经常出现不翻译文献标题的情况

### ISSUE THREAD

**Issue by lelele540m** [immersive-translate/immersive-translate#1138]
### 插件版本号 | Version

0.11.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在web of science界面，经常出现不翻译文献标题的情况

### 出现问题的网址 | URL

https://www.webofscience.com/wos/

**Comment by keyboard3** [comment]
这个网站搜索的关键字会在标题上高亮显示，这个高亮时会覆盖我们翻译的译文内容。这个暂时建议点击悬浮球重翻译解决

**Comment by keyboard3** [comment]
0.12.6 已修复
