### ISSUE TITLE
希望新增设置【最少翻译字数】

### ISSUE THREAD

**Issue by msxfXF** [immersive-translate/immersive-translate#1139]
### 您希望的更新和改进是什么 | Update or Improve

希望新增设置【最少翻译字数】
在某些论文 PDF 翻译的场景下，有些表格、代码内的名词会单独翻译，造成格式错乱。
希望添加最少翻译字数，来限制对这些英文的翻译

![image](https://github.com/immersive-translate/immersive-translate/assets/38368353/9d5bf982-5493-47b0-a3cc-c46b30e2a791)

**Comment by msxfXF** [comment]
并且每次翻译，均会请求 openai，导致并发到达上限。

**Comment by keyboard3** [comment]
靠最小长度判断也不靠谱，也会造成正常内容无法被翻译。不过这个最小字数和最小单词的限制的配置，我们内部讨论下

**Comment by msxfXF** [comment]
好的辛苦啦~👍🏻👍🏻👍🏻
能否帮我找一下关键修改位置？我本地clone一份去编译，临时解决一下问题~


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月24日(周五) 上午10:40
收件人: ***@***.***&gt;;
抄送: &quot;Haofei ***@***.******@***.***&gt;;
主题: Re: [immersive-translate/immersive-translate] 希望新增设置【最少翻译字数】 (Issue #1139)




 
靠最小长度判断也不靠谱，也会造成正常内容无法被翻译。不过这个最小字数和最小单词的限制的配置，我们内部讨论下
 
&mdash;

**Comment by keyboard3** [comment]
> 好的辛苦啦~👍🏻👍🏻👍🏻 能否帮我找一下关键修改位置？我本地clone一份去编译，临时解决一下问题~
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年11月24日(周五) 上午10:40 收件人: ***@***.***&gt;; 抄送: &quot;Haofei ***@***.******@***.***&gt;; 主题: Re: [immersive-translate/immersive-translate] 希望新增设置【最少翻译字数】 (Issue #1139) 靠最小长度判断也不靠谱，也会造成正常内容无法被翻译。不过这个最小字数和最小单词的限制的配置，我们内部讨论下 &mdash; Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

代码都被转义混淆压缩过，不建议改动。 等下一版更新，或者你自己做个翻译服务server，自己处理这块的逻辑

**Comment by theowenyoung** [comment]
可以这样自定义：

在【开发者设置】里面，找到 【Full User Config】，在`generalRule`里面加入以下值：

```
"generalRule":{
    "paragraphMinTextCount": 4,
    "paragraphMinWordCount": 2
}
```

**Comment by msxfXF** [comment]
是这样吗？ 感觉好像没有生效
![image](https://github.com/immersive-translate/immersive-translate/assets/38368353/d9aae1a1-a838-4ef0-b9c2-3533730f029e)
![image](https://github.com/immersive-translate/immersive-translate/assets/38368353/85f54660-6e96-420a-85ad-2f487e325a08)

**Comment by theowenyoung** [comment]
拉下去，看看是否已经有 generalRule，覆盖了这个

**Comment by msxfXF** [comment]
是的，下面还有一个&nbsp;generalRule
不过外层没被&nbsp;rawUserConfig&nbsp;包裹


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月24日(周五) 中午12:54
收件人: ***@***.***&gt;;
抄送: &quot;Haofei ***@***.******@***.***&gt;;
主题: Re: [immersive-translate/immersive-translate] 希望新增设置【最少翻译字数】 (Issue #1139)




 
可以这样自定义：
 
在【开发者设置】里面，找到 【Full User Config】，在generalRule里面加入以下值：
 "generalRule":{     "paragraphMinTextCount": 4,     "paragraphMinWordCount": 2 }  
&mdash;

**Comment by theowenyoung** [comment]
把两个的子项合并下就好了～

Haofei Sun ***@***.***> 于 2023年11月25日周六 上午7:28写道：
