### ISSUE TITLE
[Bug]: 如果原文里有标签，翻译之后显示错误

### ISSUE THREAD

**Issue by a14907** [immersive-translate/immersive-translate#1140]
### 插件版本号 | Version

0.11.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

**插件里如果有标签，翻译之后直接乱了。下面是网页的原文：**

![raw](https://github.com/immersive-translate/immersive-translate/assets/13792421/27307e2c-4bbe-4b0a-8d17-ce5108543ee1)

**翻译效果如下，我把相关的网络请求也截图了：**

![{FCC7F158-2B1C-4711-B0B0-2472883D282A} png](https://github.com/immersive-translate/immersive-translate/assets/13792421/035c8eb0-142c-4822-998a-77d3cee763c5)

**目前很影响显示**

**Comment by theowenyoung** [comment]
这个目前是预期的行为，我们目前是屏蔽了一些可能不安全的标签，但是大多数其他标签会按照 DOMPurify.sanitize 处理后插入。

目前是因为我们需要关注某些作为占位符的标签，所以不太方便移除全部的标签...

**Comment by a14907** [comment]
> 这个目前是预期的行为，我们目前是屏蔽了一些可能不安全的标签，但是大多数其他标签会按照 DOMPurify.sanitize 处理后插入。
> 
> 目前是因为我们需要关注某些作为占位符的标签，所以不太方便移除全部的标签...

可以处理成html实体！现在的处理有点不合适

**Comment by theowenyoung** [comment]
对，我们传给第三方的原文是 html 实体，被第三方翻译服务 转成 正常的字符了.

**Comment by a14907** [comment]
> 对，我们传给第三方的原文是 html 实体，被第三方翻译服务 转成 正常的字符了.

你们保险些，把翻译的内容做下实体转换再输出到网页上！不然你们现在的处理，问题很大，如果是人家专门写html5的书，存在大量的标签，用你们的插件翻译，直接不能看

**Comment by theowenyoung** [comment]
@keyboard3 这里是否可以 提前使用正则将带有 html 实体字符的标签 视为 code, 要求第三方服务不要翻译?

**Comment by theowenyoung** [comment]
可以了，这个问题在 1.1.0 版本应该修复了～
