### ISSUE TITLE
[Bug]: 翻译Steam特定页面的更新日志时, 文本中部分行被跳过

### ISSUE THREAD

**Issue by yyjdelete** [immersive-translate/immersive-translate#1141]
### 插件版本号 | Version

0.11.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

翻译Steam特定页面的更新日志时, 文本中部分行被跳过

### 出现问题的网址 | URL

https://store.steampowered.com/app/2244130/Ratopia/

### 重现步骤 | To Reproduce

Url1: https://store.steampowered.com/app/2244130/Ratopia/
Url2: https://store.steampowered.com/news/app/2244130
Url3: https://steamcommunity.com/games/2244130/announcements/detail/3897364481852235107
Url4: https://steamcommunity.com/app/2244130/eventcomments/4030220670860724377

![image](https://github.com/immersive-translate/immersive-translate/assets/1819074/73c68710-b777-437d-8dc5-64f1ed1f3129)

以上四个url中, 只有从url4打开时更新日志被完整翻译了, 从另外3个打开时由于未知原因, 均会有相同的部分行(图中红框部分)被跳过不会进行翻译(连转圈都不会转)

因为这是页面中的一个气泡, 也贴下从url1/2/4进入时需要点击的位置
![image](https://github.com/immersive-translate/immersive-translate/assets/1819074/671b2aea-0c72-4f2b-bc0b-7b38cdacc92b)
![image](https://github.com/immersive-translate/immersive-translate/assets/1819074/a279ef2e-982a-47cb-b45d-8b90a81ff64c)
![image](https://github.com/immersive-translate/immersive-translate/assets/1819074/74031e8e-be4b-48c0-8b11-851a8d075d1b)

### 补充说明 | Additional context

试了下油猴插件和chrome新推的0.11.6, 更奇怪了, 同样的版本, 油猴插件(我用的tampermonkey)可以, 但chrome插件不行

**Comment by keyboard3** [comment]
试下最新0.12.10看看
