### ISSUE TITLE
[Bug]: 翻译文本中有数字时，出现错误

### ISSUE THREAD

**Issue by ziyangxiami** [immersive-translate/immersive-translate#1143]
### 插件版本号 | Version

0.11.6

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

 one in 14，翻译为“四分之一”，实际上应该为“十四分之一”

### 出现问题的网址 | URL

https://www.sciencedirect.com/science/article/abs/pii/S1054139X20303177

### 重现步骤 | To Reproduce

选择“谷歌翻译”，翻译该网页，即可复现。

**Comment by keyboard3** [comment]
翻译服务的问题，插件无法处理
