### ISSUE TITLE
[Bug]: 在 Google play 圖書翻譯時原文會被吃掉

### ISSUE THREAD

**Issue by nissenyeh** [immersive-translate/immersive-translate#1144]
### 插件版本号 | Version

 0.11.5

### 平台 | Platform

macOS

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在 Google play 圖書，部分段落被吃掉

### 原文

![CleanShot 2023-11-24 at 00 20 58@2x](https://github.com/immersive-translate/immersive-translate/assets/34571901/b4dc5fe1-3154-4c99-b486-cb64237e4843)

### 翻譯後，少掉兩段翻譯
![CleanShot 2023-11-24 at 00 19 58@2x](https://github.com/immersive-translate/immersive-translate/assets/34571901/b2cffa43-644d-486b-b9bc-8bba0710aca0)

### 出现问题的网址 | URL

https://play.google.com/store/books

### 重现步骤 | To Reproduce

1. 在 Google play  買書，https://play.google.com/store/books 

2. 打開電子書

<img width="848" alt="CleanShot 2023-11-24 at 00 23 46@2x" src="https://github.com/immersive-translate/immersive-translate/assets/34571901/40922f1d-b1df-4c64-a3da-bb28ebf2ac33">

3. 進行翻譯，發現部分段落原文消失
![CleanShot 2023-11-24 at 00 19 58@2x](https://github.com/immersive-translate/immersive-translate/assets/34571901/b2cffa43-644d-486b-b9bc-8bba0710aca0)

**Comment by keyboard3** [comment]
你可以升级到0.11.6 在这个页面点击右侧分享出readit页面链接出来(注意这个时候不用翻译)，我们看下这个页面

**Comment by nissenyeh** [comment]
好像不行，可能是因為這來自不公開的 Google play 電子書網頁

https://play.google.com/store/books

![CleanShot 2023-11-29 at 16 30 54@2x](https://github.com/immersive-translate/immersive-translate/assets/34571901/4d5eb1e2-68d3-4747-8fd5-5fd3801fd2a7)

**Comment by keyboard3** [comment]
那确实不太好办，你要不试下这个插件看看不能导出出一个html文件？ https://chromewebstore.google.com/detail/singlefile/mpiodijhokgodhhofbcjdecpffjipkle

**Comment by nissenyeh** [comment]
> 那确实不太好办，你要不试下这个插件看看不能导出出一个html文件？ https://chromewebstore.google.com/detail/singlefile/mpiodijhokgodhhofbcjdecpffjipkle

好的，我倒出了一個 html 頁面 ，可以試試看！

<img width="1455" alt="CleanShot 2023-11-29 at 16 45 07@2x" src="https://github.com/immersive-translate/immersive-translate/assets/34571901/ed9ee101-928f-4f4c-af88-2d72bd7eae19">


[Outlive.zip](https://github.com/immersive-translate/immersive-translate/files/13498138/Outlive.zip)

**Comment by keyboard3** [comment]
看到了 这个是由于Google翻页模式下限高，这个情况下不适合双语，你可以去面板的更多下的仅译文显示
