### ISSUE TITLE
鼠标悬停直接翻译速度太快，是否可以添加一个设置来控制翻译的延迟

### ISSUE THREAD

**Issue by hikaholik** [immersive-translate/immersive-translate#1146]
### 您希望的更新和改进是什么 | Update or Improve

很多时候就是感觉鼠标只是经过一段文字然后就自动翻译了，对不需要翻译的部分来说使用上有些不太顺手。

请增加一个选项，以让“修改鼠标悬停快捷键”设置为“直接翻译该段”的情况下控制激活翻译的速度，如设置为悬停0.5秒或者1秒后开始翻译（作为可调节的选项进行设置），而不是随时都立刻翻译。
但是如果设置了悬停后按下其他按键再开始翻译则禁用此功能。

**Comment by keyboard3** [comment]
建议用快捷键+鼠标悬停翻译
