### ISSUE TITLE
[Bug]: 翻译后，同一页面字体不一致

### ISSUE THREAD

**Issue by heheda123123** [immersive-translate/immersive-translate#1149]
### 插件版本号 | Version

0.11.6

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

如图 
![image](https://github.com/immersive-translate/immersive-translate/assets/97490782/d4c9e855-098e-4c09-a5ee-cf50e691d1e8)
pdf如下
[test.pdf](https://github.com/immersive-translate/immersive-translate/files/13465733/test.pdf)

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/5efdfdf6-f4ec-4881-af28-0ea941111305)
我这边正常，这个问题与原pdf内保存的字体有关，可能存在某种情况丢字体，这个没有啥好办法
