### ISSUE TITLE
[Bug]: 翻译插件无法翻译本地HTML网页

### ISSUE THREAD

**Issue by BlinVin** [immersive-translate/immersive-translate#1151]
### 插件版本号 | Version

0.11.6

### 平台 | Platform

macOS 10.15.7

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在阅读外文文献时，可以先将PDF文件转换成在线文件，然后再使用翻译插件进行翻译。但是Chrome打开本地html文件后，翻译插件的翻译按钮直接变灰，然后显示【Please refresh the current page before starting translation】。希望程序员大大能尽快解决这个小问题，解决痛点。

### 出现问题的网址 | URL

本地htlm文件

### 重现步骤 | To Reproduce

无

### 补充说明 | Additional context

无

**Comment by theowenyoung** [comment]
在 扩展管理页面 ，找到沉浸式翻译，然后选择 允许访问本地文件，即可（默认情况下，浏览器不允许插件访问本地文件）：

![CleanShot 2023-11-27 at 01 05 38@2x](https://github.com/immersive-translate/immersive-translate/assets/62473795/353cffb1-2553-4155-8386-63df2123c257)

**Comment by BlinVin** [comment]
> 在 扩展管理页面 ，找到沉浸式翻译，然后选择 允许访问本地文件，即可（默认情况下，浏览器不允许插件访问本地文件）：
> 
> ![CleanShot 2023-11-27 at 01 05 38@2x](https://private-user-images.githubusercontent.com/62473795/285667824-353cffb1-2553-4155-8386-63df2123c257.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNjQ5NTMsIm5iZiI6MTcwMTA2NDY1MywicGF0aCI6Ii82MjQ3Mzc5NS8yODU2Njc4MjQtMzUzY2ZmYjEtMjU1My00MTU1LTgzODYtNjNkZjIxMjNjMjU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDA1NTczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkM2VmMzhmZTJjZjQ0MDk2OWM2OTM1NDJjY2ViZjc5NDAzY2E4MTRiYWE4ZGZkNzI3ODk1OWU2ZGRkNDkwOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9N5wnrNcEuNk4FZOeXvihmQmBDVWqvhVKSVNxinsOqk)

谢谢，已解决，Chrome里面选择插件设置中的【允许访问文件网址】
