### ISSUE TITLE
[Bug]: ios safari的discord web端聊天输入框翻译失败

### ISSUE THREAD

**Issue by IMLaoJI** [immersive-translate/immersive-translate#1153]
### 插件版本号 | Version

0.11.6

### 平台 | Platform

iOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

你好，我在safari上的移动版discord页面的聊天输入框中使用不了连击三下空格自动翻译，我怀疑是输入框问题，discord上其他地方的输入框都是使用正常，

### 出现问题的网址 | URL

https://discord.com/

### 重现步骤 | To Reproduce

随意在一个频道的safari ios系统上发言

**Comment by IMLaoJI** [comment]
![60812d4f-c03a-4044-9f4e-5367a2fd34f2](https://github.com/immersive-translate/immersive-translate/assets/16029951/f8a7cc95-f95f-42c1-8a6e-11e6fb16cf71)

**Comment by keyboard3** [comment]
下个版本修复

**Comment by keyboard3** [comment]
0.12.2 已修复
