### ISSUE TITLE
关于增加“百度翻译-领域翻译”API支持的建议。

### ISSUE THREAD

**Issue by DeaneChen** [immersive-translate/immersive-translate#1154]
### 您希望的更新和改进是什么 | Update or Improve

当前的百度翻译API以及支持通过单选框开始是否启用“百度术语”功能，从而在请求API中增加action=1参数。请求新增单选框以可选是否支持启用百度翻译的“领域翻译”功能，从而在特定领域取得更为准确的翻译结果。

“领域翻译”的API文档：https://fanyi-api.baidu.com/doc/22

其与原“通用文本翻译的API”区别：

1. URL：
    通用文本翻译：https://fanyi-api.baidu.com/api/trans/vip/translate
    领域翻译：https://fanyi-api.baidu.com/api/trans/vip/fieldtranslate
2. 参数
    通用文本：不含domain参数
    领域翻译：可以用domain参数指定领域
3. 密钥：
    两者密钥通用

**Comment by theowenyoung** [comment]
可以的～

**Comment by keyboard3** [comment]
1.1.3 已支持
