### ISSUE TITLE
[Bug]: 頁面無法翻譯

### ISSUE THREAD

**Issue by r91085** [immersive-translate/immersive-translate#1156]
### 插件版本号 | Version

0.11.6

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

以下連結按下翻譯後，不會有反應，但是顯示翻譯已經完成

https://www.zabkat.com/x2h_5.htm#xa_simpic

### 出现问题的网址 | URL

https://www.zabkat.com/x2h_5.htm#xa_simpic

### 重现步骤 | To Reproduce

1.進入網頁
2.按下翻譯

**Comment by keyboard3** [comment]
滚动到顶部就可以了
