### ISSUE TITLE
建议键入【译文自定义字体】选项

### ISSUE THREAD

**Issue by BlinVin** [immersive-translate/immersive-translate#1158]
### 您希望的更新和改进是什么 | Update or Improve

rt，目前插件只能实现自定义样式，但是字体格式确实跟随网页原本字体的，这样就很被动，比如大部分英文字体是Times New Roman，但是对应的中文字体辨识度很低，降低了工作效率，希望程序员大大能加入这个选项！！！谢谢谢谢谢谢谢谢谢！！！

**Comment by timelic** [comment]
似乎我很早就反馈过这个功能。你可以试试custom style实现？

**Comment by BlinVin** [comment]
> 似乎我很早就反馈过这个功能。你可以试试custom style实现？

我看过了，自定义样式 没有 自定义字体 这个选项，有的是 字号和颜色

**Comment by timelic** [comment]
我指的是开发者设置里面的`injected css`，你试试？

**Comment by product-think2049** [comment]
> ### 您希望的更新和改进是什么 | Update or Improve
> 
> rt，目前插件只能实现自定义样式，但是字体格式确实跟随网页原本字体的，这样就很被动，比如大部分英文字体是Times New Roman，但是对应的中文字体辨识度很低，降低了工作效率，希望程序员大大能加入这个选项！！！谢谢谢谢谢谢谢谢谢！！！
> ### 补充说明 | Additional context
> 
> _No response_

同希望 +1
感谢！！

**Comment by theowenyoung** [comment]
这种情况下，可能只能用预先定义好的几种字体？

有没有参考的字体列表推荐？

**Comment by BlinVin** [comment]
> 这种情况下，可能只能用预先定义好的几种字体？
> 
> 有没有参考的字体列表推荐？

苹果的话，建议 冬青黑体简体中文

**Comment by keyboard3** [comment]
1.1.7 已支持
