### ISSUE TITLE
建議：新增可設定字體大小

### ISSUE THREAD

**Issue by lee988325** [immersive-translate/immersive-translate#116]
我是剛上手的新使用者
翻了幾次設置頁面，但是沒有發現可以設置譯文字體大小的選項。

**Comment by theowenyoung** [comment]
确实没有这个选项。默认是和原文保持一样大小的。你有修改的需求吗？可以说下你的使用场景吗～

**Comment by lee988325** [comment]
目前初步是在reddit使用
因為閱讀時習慣是將譯文當作輔助，如果譯文是和原文相同大小，會覺得譯文太過顯眼。

另外，剛剛還注意到另一個設置上的建議。
譯文顯示樣式，因為是下拉式選單，所以一次只能使用一種樣式，比如我希望用引用+弱化就沒辦法。
（如果需要分開討論，請告訴我，我再另外開一個issue）

謝謝。

**Comment by theowenyoung** [comment]
嗯懂了，现在正在开发的一个特性是 自定义译文样式的一些属性，比如 颜色。

所以你可以选择引用样式，然后自定义字体的颜色这样。实现一些更复杂的个性化。

这个可以满足你的需求吗？ （字体大小我是不建议自定义的）

**Comment by lee988325** [comment]
聽起來不錯，可以試試看。
沒有進一步的問題了。

**Comment by theowenyoung** [comment]
最新版本已支持自定义字体大小和自定义颜色～欢迎体验～

暂时先关闭这个问题了哈～ 有问题再打开。
