### ISSUE TITLE
[Bug]: 带数学公式的 PDF 论文翻译效果很糟，无法阅读   

### ISSUE THREAD

**Issue by neozhaoliang** [immersive-translate/immersive-translate#1163]
### 插件版本号 | Version

0.11.6

### 平台 | Platform

Linux

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在翻译日文写作的数学文献时，不管选择目标语言是英文或者中文，或者选择 openai/deepl 翻译效果都很差，一团乱码。

![图片](https://github.com/immersive-translate/immersive-translate/assets/23307174/e8b13567-4d04-4b67-89ad-d95784b922a3)

### 出现问题的网址 | URL

https://www.math.nagoya-u.ac.jp/~yanagida/doc/2017Alg.pdf

### 重现步骤 | To Reproduce

1. 打开上面的网页链接中的 pdf
2. 点击翻译为中文或者英文 （自动识别或者选择原语言为日文）

**Comment by keyboard3** [comment]
目前无法识别专业的论文类型pdf, 可以查看帮助 https://immersivetranslate.com/docs/pdf-helper/

**Comment by neozhaoliang** [comment]
从技术上说这应该是可以做到的，我直接选中一段带公式的区域，粘贴到 chatgpt 的对话框里面，告诉它保持数学符号不动，这时粘贴出来的格式是丢失了公式的，但是 chatgpt 可以把公式再还原出来，并调用 mathjax 渲染：

![图片](https://github.com/immersive-translate/immersive-translate/assets/23307174/3f1bec82-2cbf-4593-8fe4-eb2ed4e4c6e9)
