### ISSUE TITLE
[Bug]: 在newbing中输入框增强无法使用

### ISSUE THREAD

**Issue by Muyi58317** [immersive-translate/immersive-translate#1164]
### 插件版本号 | Version

0.11.6

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在newbing中输入框增强无法触发，但是在chat.openai.com中可以使用。

### 出现问题的网址 | URL

https://www.bing.com/search?q=Bing+AI&showconv=1&FORM=hpcodx

### 重现步骤 | To Reproduce

打开网址在bingai里输入文字并快速敲击空格

**Comment by keyboard3** [comment]
查看兼容性文档 ，目前不兼容newbing https://immersivetranslate.com/docs/input/#%E5%85%BC%E5%AE%B9%E6%80%A7
