### ISSUE TITLE
当关闭字幕后可以立刻停止翻译

### ISSUE THREAD

**Issue by heheda123123** [immersive-translate/immersive-translate#1165]
### 您希望的更新和改进是什么 | Update or Improve

因为默认是开着ytb字幕翻译的，有时候进一些中文视频或者不想看翻译的视频也会显示 openai正在翻译的提示，这个时候点击关闭字幕的按钮，但是提示仍然存在，后台应该还是在翻译？
当点击关闭字幕的时候可以立刻停止翻译

**Comment by keyboard3** [comment]
嗯 这个有后续优化计划

**Comment by theowenyoung** [comment]
刷新一下页面应该就不会继续发请求了。

**Comment by keyboard3** [comment]
1.4.2+ yotube字幕采用了实时翻译方案，会按照播放进度来预翻译缓存字幕
