### ISSUE TITLE
[Bug]: Detect language wrongly

### ISSUE THREAD

**Issue by vanbang9710** [immersive-translate/immersive-translate#1166]
### 插件版本号 | Version

0.11.6

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

Page is detected as English instead of multiple languages (Japanese and English)

### 出现问题的网址 | URL

https://twitter.com/ymgwonder/status/1729380215120609396

### 补充说明 | Additional context

The default translator of Edge detects page as "Detected language" ![|50pct](https://i.imgur.com/R9UFurb.png)

**Comment by theowenyoung** [comment]
This is not a modal of Immersive Translate.

it's Edge browser native translator.

**Comment by vanbang9710** [comment]
I meant the language detection should add a "Multiple languages" option like Edge translator

**Comment by theowenyoung** [comment]
![CleanShot 2023-12-02 at 12 58 38@2x](https://github.com/immersive-translate/immersive-translate/assets/62473795/cc6d3df9-51b9-4878-8cb8-f86448f13529)

The default option "Detect Language" is treated as Multiple languages in Immersive Translate.

**Comment by vanbang9710** [comment]
That's not what I'm talking about. The twitter url I provided has both English and Japanese. It is detected as English so it can't be auto translated to English.

**Comment by vanbang9710** [comment]
there's so many sites like that though so this is not a good enough solution. And I think translating twitter even when there's english only would increase the resource usage unnecessarily?
