### ISSUE TITLE
[Bug]: 阅读epub，用分页模式的时候鼠标无法按住滚动条

### ISSUE THREAD

**Issue by heheda123123** [immersive-translate/immersive-translate#1167]
### 插件版本号 | Version

0.11.6

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

如图，打开一个epub文件，默认是分页模式，切换成滚动模式，会发现，“下一页”的长条按钮把滚动条挡住了，无法用鼠标选中滚动条
![image](https://github.com/immersive-translate/immersive-translate/assets/97490782/11f80cd4-3dec-4ae3-a837-2c7cff6bcec5)

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/604dd1eb-f375-4093-aec5-64ef9867a1f3)
已调整
