### ISSUE TITLE
悬浮球

### ISSUE THREAD

**Issue by chaos-zhu** [immersive-translate/immersive-translate#1168]
### 您希望的更新和改进是什么 | Update or Improve

能支持悬浮在窗口左边吗，比较顺手一点

**Comment by FattySpring** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/25144301/af669c33-f06f-4f90-b408-482bb2000d23)

[版本 0.12.4](https://immersivetranslate.com/docs/CHANGELOG/#0124) 在设置中添加了一个【固定位置】的选项

**Comment by chaos-zhu** [comment]
thx
