### ISSUE TITLE
[FR]适配Edge浏览器的【分屏】

### ISSUE THREAD

**Issue by leedstyh** [immersive-translate/immersive-translate#1170]
### 您希望的更新和改进是什么 | Update or Improve

打开Edge浏览器的【分屏】时，总是翻译左侧的页面，右侧的无法翻译，这个能适配下吗。

* 选中左侧页面时，就翻译左侧
* 选中右侧页面时，就翻译右侧

**Comment by FattySpring** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/25144301/7a103bf2-0613-4921-b5a4-90b8a76597c7)

未能复现，可以录制一段视频吗？

**Comment by FattySpring** [comment]
使用悬浮球来翻译是正常的，建议在分屏的情况下先悬浮球来翻译
