### ISSUE TITLE
"切换为 仅显示译文/双语翻译" 选项藏的太深，请求加入进设置界面

### ISSUE THREAD

**Issue by IXCIMAFW** [immersive-translate/immersive-translate#1171]
### 您希望的更新和改进是什么 | Update or Improve

只有在开启 `悬浮球` 功能后，`快捷设置面板 -> 更多` 中才有 `切换为 仅显示译文/双语翻译` 选项，而此选项没有出现在设置界面中，故请求增加此选项。

**Comment by xwlops** [comment]
+1

**Comment by f3liiix** [comment]
+1

**Comment by dfmjndm** [comment]
+1

**Comment by theowenyoung** [comment]
更新进度：

下个版本将会把【切换双语/译文】按钮放在主面板上。

**Comment by FattySpring** [comment]
版本 1.1.4 已将 【切换双语/译文】按钮放在主面板上。
