### ISSUE TITLE
[Bug]: 无法取消`总是翻译该网站`

### ISSUE THREAD

**Issue by cesaryuan** [immersive-translate/immersive-translate#1172]
### 插件版本号 | Version

0.12.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

无法取消`总是翻译该网站`，希望可以手动取消由于`临时开启网站翻译的时长`导致的自动翻译，而不是强制5分钟后才能取消

### 出现问题的网址 | URL

Any

### 重现步骤 | To Reproduce

1. 将`临时开启网站翻译的时长`设置为5分钟
2. 打开任意一个英文网站，比如 https://v8.dev/docs/embed
3. 点击按钮翻译网站
4. 刷新网站
5. 尝试取消`总是翻译该网站`但是取消不了，导致每次都会自动翻译

### 补充说明 | Additional context

https://github.com/immersive-translate/immersive-translate/assets/35998162/1451a81f-3acc-4823-b571-a8a9a1596943

**Comment by iG8R** [comment]
@cesaryuan 
Thanks a lot!

**Comment by FattySpring** [comment]
[版本 0.12.4](https://immersivetranslate.com/docs/CHANGELOG/#0124) 已修复

**Comment by cesaryuan** [comment]
> [版本 0.12.4](https://immersivetranslate.com/docs/CHANGELOG/#0124) 已修复

经过测试，1处现在可以取消`总是翻译该网站`了，但是2处还是不行，点击无反应
![image](https://github.com/immersive-translate/immersive-translate/assets/35998162/40b17806-f6a4-44af-ad93-011dfecd6ee2)

**Comment by FattySpring** [comment]
感谢您的反馈，临时翻译会自动取消“总是翻译”，如果经常需要手动取消翻译，不建议使用该功能。未来可能会移除该功能，所以不再对此功能进行更新维护。
