### ISSUE TITLE
[Bug]: Via 浏览器 (安卓) 使用油猴脚本，在设置界面点击 "点此测试服务" 一直转圈。

### ISSUE THREAD

**Issue by MiaoMiao-Xie** [immersive-translate/immersive-translate#1173]
### 插件版本号 | Version

0.12.2

### 平台 | Platform

Android

### 浏览器 | Browsers

Other

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

Via 浏览器 (安卓) 使用油猴脚本，在设置界面点击 `点此测试服务` 一直转圈。但翻译功能是能正常使用的。

### 出现问题的网址 | URL

https://dash.immersivetranslate.com/#general

### 重现步骤 | To Reproduce

1. 进入设置页面 (https://dash.immersivetranslate.com/#general) 。
2. 选择 `微软翻译` 或 `腾讯交互翻译`。
3. 点击 `点此测试服务`。

**Comment by keyboard3** [comment]
via不兼容 https://immersivetranslate.com/docs/faq/#%E6%B2%89%E6%B5%B8%E5%BC%8F%E7%BF%BB%E8%AF%91%E6%B2%B9%E7%8C%B4%E8%84%9A%E6%9C%AC%E6%94%AF%E6%8C%81%E7%9A%84%E6%B5%8F%E8%A7%88%E5%99%A8。推荐其他浏览器 https://immersivetranslate.com/docs/installation/#%E5%AE%89%E5%8D%93
