### ISSUE TITLE
[Bug]: YouTube字幕消失

### ISSUE THREAD

**Issue by h304192** [immersive-translate/immersive-translate#1175]
### 插件版本号 | Version

0.12.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

只要启用了这个插件YouTube视频字幕就无法正常显示

### 出现问题的网址 | URL

https://www.youtube.com/

**Comment by MrPinku** [comment]
我也一样，全部油管视频的字幕都不显示了。
![image](https://github.com/immersive-translate/immersive-translate/assets/79267206/8c94c11e-5a37-4fce-adbf-a3a98d6ed46b)
只开了这一个插件就不显示了。
![image](https://github.com/immersive-translate/immersive-translate/assets/79267206/9d24acdf-e8c8-4b7c-b91e-fadc318da143)
不开这个但是开其他插件可以显示。

**Comment by theowenyoung** [comment]
@h304192 edge 商店最新版本应该还是 0.11.6，你是手动安装的最新版吗？

**Comment by theowenyoung** [comment]
@MrPinku  我这里油猴也是正常的：

![CleanShot 2023-12-03 at 15 46 48@2x](https://github.com/immersive-translate/immersive-translate/assets/62473795/76b62504-0fd9-490c-a4d6-f5e5379eab83)

**Comment by MrPinku** [comment]
怪，可能是自动更新后这个功能有问题，
![image](https://github.com/immersive-translate/immersive-translate/assets/79267206/08c04fd2-6857-43bc-adb3-63610609f18b)
我刚关了就能显示了-。-
好久之前开的了，因为觉得双语字幕太占位置所以关掉的。

**Comment by h304192** [comment]
> @h304192 edge 商店最新版本应该还是 0.11.6，你是手动安装的最新版吗？

是的

**Comment by h304192** [comment]
> 怪，可能是自动更新后这个功能有问题， ![image](https://private-user-images.githubusercontent.com/79267206/287503899-08c04fd2-6857-43bc-adb3-63610609f18b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1OTE4NTgsIm5iZiI6MTcwMTU5MTU1OCwicGF0aCI6Ii83OTI2NzIwNi8yODc1MDM4OTktMDhjMDRmZDItNjg1Ny00M2JjLWFkYjMtNjM2MTA2MDlmMThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAzVDA4MTkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlZTI5YzRhZGZhOTdmMjY2YjcxZjZmZDcwYWIyODhiMDUyNzY4MDNjYzM1Y2E4Nzc4ZWJkYzM3ZDhiZmI5MmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LLxgtJDAu88rrLpjTtSn-js0-pxA5xA8AYnTJOJxeMI) 我刚关了就能显示了-。- 好久之前开的了，因为觉得双语字幕太占位置所以关掉的。

我也开了这个，主要是因为翻译字幕会导致无法正常显示拥有特殊样式的字幕

**Comment by theowenyoung** [comment]
已验证，确实在开启【永久禁用字幕的时候】有这个问题，刚提交了 0.12.3 版本，已修复该问题，感谢反馈。

**Comment by xiaodiganbi** [comment]
我现在是v0.12.4 仍旧存在这个问题，关闭【永久禁用字幕】也无效，只有禁用沉浸式翻译再刷新youtube才能看到字幕

**Comment by theowenyoung** [comment]
@xiaodiganbi 截图一下你的视频字幕设置。

你的期望是 希望沉浸式翻译 帮你显示双语字幕，还是说希望沉浸式翻译不要接管你的字幕？

**Comment by xiaodiganbi** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13745836/163435b8-e6c2-492b-94f2-a9a39e4f35ca)
其实我试过改变这些设置但都仍然不能显示油管字幕

**Comment by xiaodiganbi** [comment]
突然好了，我关闭优先人工字幕一次再打开，再刷新油管，突然又能看到字幕了，虽然不知道究竟是哪里的问题但是谢谢回复

**Comment by HuZixia** [comment]
<img width="1511" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/38995480/fd664ac3-8f6a-42df-ab11-c112fbf9fe57">

Hello，反馈一下， 我刚遇到的问题和解决方案：

我在设置-字幕那里把 泰语 转成 英文之后，然后所有youtobe视频的 immersive 翻译都没了

我按照上面题主说的，关闭优先人工字幕一次再打开，再刷新youtobe，就可以正常使用了

**Comment by Ilcyb** [comment]
遇到了同样的问题，按照上面的方法关闭优先人工字幕后解决
