### ISSUE TITLE
是否支持同时设置多个openai的key

### ISSUE THREAD

**Issue by toyo2333** [immersive-translate/immersive-translate#1176]
### 您希望的更新和改进是什么 | Update or Improve

我只有普通的key，就是RPM是3，一篇网页都无法一次性翻译完成。但我有50个Key，所以你们是否支持key池，来避免请求频率受限的问题？

### 补充说明 | Additional context

嗯，就是上面的意思
key1,key2,key3...key50

**Comment by theowenyoung** [comment]
支持的，用 逗号 分隔多个key即可。
