### ISSUE TITLE
自定义API 配置能否增加 Auth Key 选项

### ISSUE THREAD

**Issue by werhner** [immersive-translate/immersive-translate#1178]
### 您希望的更新和改进是什么 | Update or Improve

自定义API 或 deeplx 配置能否增加 Auth Key 选项, 或者增加 Headers 配置选项

### 补充说明 | Additional context

自定义API 能否增加 Headers 配置选项
<img width="416" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/15964105/7f37ecc4-20ca-4bb5-b855-e1d0e3fb905d">

**Comment by theowenyoung** [comment]
建议使用 query 鉴权。 类似这样： `xxxx.com?token=xxxxx`
