### ISSUE TITLE
增加一个单语网页翻译功能

### ISSUE THREAD

**Issue by thomasTAT** [immersive-translate/immersive-translate#118]
edge 翻译没有网页快捷键,不好用.
双语翻译,太冗杂.
希望能增加一个功能,直接整个网页翻译. 
配合快捷键,可以快速切换,译文和原文.
类似的产品有:
https://github.com/FilipePS/Traduzir-paginas-web 但edge上用一段时间会莫名其妙被卸载.
腾讯翻译, 速度太慢了
最后感谢你开发了,这款扩展

**Comment by theowenyoung** [comment]
感谢反馈，隐藏原文的功能正在计划中.

**Comment by WangChuan0225** [comment]
覆盖原文进行翻译啥时候有

**Comment by sunprincess** [comment]
> 覆盖原文进行翻译啥时候有

> edge 翻译没有网页快捷键,不好用. 双语翻译,太冗杂. 希望能_增加_一个功能,直接整个网页翻译. 配合快捷键,可以快速切换,译文和原文. 类似的产品有: https://github.com/FilipePS/Traduzir-paginas-web 但edge上用一段时间会莫名其妙被卸载. 腾讯翻译, 速度太慢了 最后感谢你开发了,这款扩展

有个叫侧边翻译的（edge translate）的插件中，点击谷歌网页翻译，就可以做到

**Comment by thomasTAT** [comment]
> > 覆盖原文进行翻译啥时候有
> 
> > edge 翻译没有网页快捷键,不好用. 双语翻译,太冗杂. 希望能_增加_一个功能,直接整个网页翻译. 配合快捷键,可以快速切换,译文和原文. 类似的产品有: https://github.com/FilipePS/Traduzir-paginas-web 但edge上用一段时间会莫名其妙被卸载. 腾讯翻译, 速度太慢了 最后感谢你开发了,这款扩展
> 
> 有个叫侧边翻译的（edge translate）的插件中，点击谷歌网页翻译，就可以做到

能用不过有瑕疵. 切换原文和翻译,要占用两个快捷键. 
还有来回翻译切换,网页的位置自己会越挪越上.
暂时还是在用腾讯翻译,虽然速度感人了点.

**Comment by theowenyoung** [comment]
已实现。点【更多】，切换为仅译文模式。
