### ISSUE TITLE
希望可以改进一下学习模式

### ISSUE THREAD

**Issue by freedomspiritJohn** [immersive-translate/immersive-translate#1180]
### 您希望的更新和改进是什么 | Update or Improve

![PixPin_2023-12-04_21-47-19](https://github.com/immersive-translate/immersive-translate/assets/129288685/07f01895-f3ec-4025-9853-e5bcdf948310)
在学习模式下,翻译是模糊的,当我用鼠标对照翻译到换行的时候,只是因为在两行的空白处,就又变回模糊模式了,体验不是很好.因此希望可以把这一整块翻译范围都判定为不模糊的界限

**Comment by FattySpring** [comment]
[版本 0.12.4](https://immersivetranslate.com/docs/CHANGELOG/#0124) 已修复
