### ISSUE TITLE
[Bug]: 在wikipedia上显示问题，翻译出来的文本中间缺少分隔符

### ISSUE THREAD

**Issue by STAOY** [immersive-translate/immersive-translate#1181]
### 插件版本号 | Version

0.12.3

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

如图，类似的英文中间有·分隔符的文本，翻译后的文本中间没有分隔符用以区分。
![image](https://github.com/immersive-translate/immersive-translate/assets/86558267/627939b3-de9d-4e2b-88ab-165d9b29f1f8)
![image](https://github.com/immersive-translate/immersive-translate/assets/86558267/98654e23-68e3-4f86-b068-d73392662105)

### 出现问题的网址 | URL

https://en.wikipedia.org/

### 补充说明 | Additional context

如图，类似的英文中间有·分隔符的文本，翻译后的文本中间没有分隔符用以区分，很影响观感。希望有时间可以进行调教
![image](https://github.com/immersive-translate/immersive-translate/assets/86558267/627939b3-de9d-4e2b-88ab-165d9b29f1f8)
![image](https://github.com/immersive-translate/immersive-translate/assets/86558267/98654e23-68e3-4f86-b068-d73392662105)

**Comment by FattySpring** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/25144301/38f34091-3cea-4851-8608-f73bbffe1eed)
已修复
