### ISSUE TITLE
[Bug]: 日本人推文问题

### ISSUE THREAD

**Issue by Nine499** [immersive-translate/immersive-translate#1182]
### 插件版本号 | Version

0.12.3

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/14026156/036920a9-8ac3-4f86-919f-528cc5128f74)

日本人天天推特发 tag 等其他玩意

是不是会对 openai 造成混乱

### 出现问题的网址 | URL

https://twitter.com/miv_uu/status/1732063777531769138

### 重现步骤 | To Reproduce

没办法每次都复现，查看日本人推文如果他们写的比较乱可能会出现

**Comment by keyboard3** [comment]
没办法必现这个就没啥办法了
