### ISSUE TITLE
建议：“界面设置”→“译文显示样式”中，加多个选项：“也作用于‘仅显示译文’”。

### ISSUE THREAD

**Issue by hs01a** [immersive-translate/immersive-translate#1184]
### 您希望的更新和改进是什么 | Update or Improve

你好：
如题（建议：“界面设置”→“译文显示样式”中，加多个选项：“也作用于‘仅显示译文’”。）
作用：能快速区分有与没有翻译的文字。

**Comment by theowenyoung** [comment]
样式是为了 双语模式下区分原文和译文的。

仅译文如果开启样式的话，可能会导致原网站布局出问题。

**Comment by f3liiix** [comment]
> 样式是为了 双语模式下区分原文和译文的。
> 
> 仅译文如果开启样式的话，可能会导致原网站布局出问题。

网站布局的问题可以逐步去调优，而且原文译文都显示的话，也一样会导致很多布局上的问题，比如显示不全等等。

但是“仅显示译文”是个刚需。大部分需要翻译的人并不是为了去学习外文，仅仅只是需要能看懂，所以并不需要显示原文，每次都需要去点几次，确实体验上不佳。
