### ISSUE TITLE
翻译本地PDF

### ISSUE THREAD

**Issue by muronggongye** [immersive-translate/immersive-translate#1185]
### 您希望的更新和改进是什么 | Update or Improve

翻译本地PDF时，只能复制译文内容，原文内容不能复制。

**Comment by keyboard3** [comment]
原文内容你在左边原文不就可以复制吗？ 给你介绍个技巧，你可以面板上显示原文，右侧框里的内容就会显示出原文

**Comment by muronggongye** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，邮件已收到。
