### ISSUE TITLE
[Bug]: IT doesn't translate if contenteditable=true

### ISSUE THREAD

**Issue by iG8R** [immersive-translate/immersive-translate#1187]
### 插件版本号 | Version

0.12.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

I have encountered an issue with IT not being able to translate elements when they have contenteditable=true.

[ImmersiveTranslate-contenteditable-true-Video_2023-12-07_00-46-16.webm](https://github.com/immersive-translate/immersive-translate/assets/11407417/effdaeb2-7e07-44b7-87ed-4d40b81c59f6)

### 出现问题的网址 | URL

https://novelhi.com/book/translate

**Comment by theowenyoung** [comment]
是的，这是预期行为，contenteditable 对我们来说相当于是一个 input, 所以我们尽可能不对里面的任何元素作修改。

**Comment by theowenyoung** [comment]
Currently this is not possible because we have this hardwired into the code. I also don't recommend translating this element, it can lead some unexpected issues. 

Maybe you can manually modify its value to false before starting translation
