### ISSUE TITLE
等了好久都没加 希望能加一个

### ISSUE THREAD

**Issue by leewf9** [immersive-translate/immersive-translate#1189]
### 您希望的更新和改进是什么 | Update or Improve

对于韩语翻译来说 最好用最准确的是papago 其它引擎永远比不过papago 希望作者大大能加一个papago的引擎

### 补充说明 | Additional context

https://papago.naver.com/  这个

**Comment by theowenyoung** [comment]
papago 以前加过，后来他们关闭了免费的接口，所以就下线了。

**Comment by leewf9** [comment]
好吧原来是这样 辛苦作者
