### ISSUE TITLE
[建议]可否添加一个模糊原文的功能

### ISSUE THREAD

**Issue by yixiongwu** [immersive-translate/immersive-translate#119]
1. 当原文被模糊后阅读译文的时候会更加流畅。
2. 但发现译文不好理解的时候再显示原文辅助理解。

**Comment by theowenyoung** [comment]
有在计划中，但是这个应该还需要一段时间.

**Comment by yixiongwu** [comment]
Cool

**Comment by benjaminyin01** [comment]
不需要，这个插件已经有了高亮显示翻译的文本的功能，推荐马克笔样式

**Comment by lockmatrix** [comment]
同上，实际体验不需要模糊原文，只需要给译文一个更显著的样式就好了，我用的是虚线框。

**Comment by theowenyoung** [comment]
这个功能暂时没有计划实现，因为修改原文会对原网站造成功能性的破坏。
