### ISSUE TITLE
[Bug]: 製作雙語電子書，譯文的字體大小不對

### ISSUE THREAD

**Issue by kitcn53719** [immersive-translate/immersive-translate#1190]
### 插件版本号 | Version

0.12.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

用EPUB檔案製作雙語電子書（哈利波特系列七本），選擇模糊效果（學習效果），完成後的譯本同樣使用沉浸式插件在瀏覽器中打開，譯文字體變非常巨大難以閱讀，七本皆如此。
A.製作冰與火之歌五本皆正常。
B.將製作完成之哈利波特系列電子書使用其他EPUB閱讀器開啟，顯示正常，但無模糊效果。
C.使用沉浸式翻譯PDF文件顯示正常，但無模糊效果。
![image](https://github.com/immersive-translate/immersive-translate/assets/153255111/7daa99ad-18c3-4487-9405-8ae9376c1275)
![image](https://github.com/immersive-translate/immersive-translate/assets/153255111/2ad3bae7-eadd-41e6-a46e-9960f394a819)

**Comment by keyboard3** [comment]
原始文件发到support@immersivetranslate.com，我们复现下

**Comment by FattySpring** [comment]
1. 字体大小问题已经修复，请重新制作。
2. "使用其他EPUB阅读器打开时，显示正常，但没有模糊效果" 可能是阅读器不支持，Apple Books打开是正常的。
3. PDF文件翻譯不支持模糊效果

**Comment by kitcn53719** [comment]
可以推薦一個安卓開啟epub文件具有模糊效果的app嗎？我用readera，沒有辦法，電腦上直接使用沉浸式翻譯的插件就可以，安卓的手機跟平板上沒辦法使用
