### ISSUE TITLE
使用auto tab discard之后，恢复标签页的位置不对

### ISSUE THREAD

**Issue by crysishacker** [immersive-translate/immersive-translate#1191]
### 您希望的更新和改进是什么 | Update or Improve

一般休眠标签页之后，再恢复就会回到原本浏览的那个位置。
估计是因为双语显示导致位置不对，返回的位置基本是错的

**Comment by FattySpring** [comment]
这是因为 “auto tab discard” 恢复的标签页没有译文导致页面页面位置不对，这个我们没有办法处理。
