### ISSUE TITLE
[Bug]: 百度翻译占位符问题

### ISSUE THREAD

**Issue by timelic** [immersive-translate/immersive-translate#1194]
### 插件版本号 | Version

0.12.5

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

<img width="1353" alt="截屏2023-12-10 20 53 10" src="https://github.com/immersive-translate/immersive-translate/assets/20257354/f124ce8d-6cde-4e88-8d9a-1aca05c83a34">

使用“百度翻译”的时候，在文中有公式的地方容易替换不完全，如截图之中的#3、#4。我理解翻译的逻辑是先将行内公式替换为一些不翻译的token，翻译后再替换回去。但百度翻译似乎会吞掉一部分这些不翻译的token。我在用火山翻译的时候就没有这个问题。

### 出现问题的网址 | URL

- 

### 重现步骤 | To Reproduce

这是我还在开发中的网站，用了mathpix-markdown-it进行md渲染。但我想，只需要判断一下是不是百度翻译，然后换一个替换词就可以了？

**Comment by keyboard3** [comment]
你可以试着给百度单独配置一个合适的占位符。
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/928f65b0-5476-4a28-821c-9011c8553087)
占位符配置的规则，可以看这里 https://immersivetranslate.com/docs/services/custom/#%E4%BF%9D%E7%95%99%E5%8D%A0%E4%BD%8D%E7%AC%A6
