### ISSUE TITLE
[Bug]: 输入框增强翻译功能，如果前面，已经是英文了，后面的中文不会被翻译

### ISSUE THREAD

**Issue by wangmos** [immersive-translate/immersive-translate#1195]
### 插件版本号 | Version

0.12.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

As title 如题           

第一次写如题，连按3次空格，可以翻译为as title,然后在写下“如题”,连按3次空格，会看到它运行了，但是后面的如题二次并没有被翻译。
上面这两个字就是这么来的。

**Comment by keyboard3** [comment]
如果想要连续翻译部分内容。需要加前缀来区分需要翻译的部分内容
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/89d16220-591f-494b-a82e-cfd2212554ed)

**Comment by wangmos** [comment]
就算这样也不是每次都能触发  能不能搞成只要触发了 全面是英文的就不管，只翻译那些没有标注的或者不是英文的

**Comment by keyboard3** [comment]
我这边试着可以啊 每次都能触发啊
