### ISSUE TITLE
[Bug]: When translating arxiv.org paper, there was a problem of duplicate translation and display on UI.

### ISSUE THREAD

**Issue by bestony** [immersive-translate/immersive-translate#1197]
### 插件版本号 | Version

0.12.5

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

<img width="947" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/13283837/5bdeb9c7-ef00-48b7-8013-3315b8a47d6c">

在翻译时，同样的一段内容会重复出现两遍。

### 出现问题的网址 | URL

https://ar5iv.labs.arxiv.org/html/2303.08774?_immersive_translate_auto_translate=1

### 重现步骤 | To Reproduce

打开上述页面，会自动启动沉浸式翻译，并翻译完成。

**Comment by theowenyoung** [comment]
暂时无法复现，先关了哈，下次遇到问题的时候再直接回复即可。
