### ISSUE TITLE
[Bug]: GitHub Release页翻译问题

### ISSUE THREAD

**Issue by HumanMus1c** [immersive-translate/immersive-translate#1199]
### 插件版本号 | Version

0.12.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

GitHub Release页翻译不准确问题
截图：
![image](https://github.com/immersive-translate/immersive-translate/assets/46023154/1b7028de-45d2-4c68-b614-1ff73f040499)

### 出现问题的网址 | URL

https://github.com/Yidadaa/ChatGPT-Next-Web/releases/tag/v2.9.13

### 重现步骤 | To Reproduce

一键翻译该网页就会出现问题

### 补充说明 | Additional context
截图：
![image](https://github.com/immersive-translate/immersive-translate/assets/46023154/44005ca1-b7aa-4dfb-99eb-4d524271d37d)

**Comment by FattySpring** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/25144301/1d16bb9b-a724-4037-b40e-e84ff01a02dd)
未能复现，试试切换下其他翻译服务

**Comment by keyboard3** [comment]
暂无反馈，先关闭此issue
