### ISSUE TITLE
增加配置项：特定网页可以使用特定的翻译服务

### ISSUE THREAD

**Issue by timelic** [immersive-translate/immersive-translate#1200]
### 您希望的更新和改进是什么 | Update or Improve

OpenAI翻译和机器翻译，前者速度慢但是效果好，后者速度快但是效果一般。

有一些网页，如咨询，直接用机器翻译即可，适合快速浏览。

另一些网页，需要认真阅读，这时候机器翻译更好。

所以能不能增加一个用户配置项，或者是开发者选项，让用户可以自定义特定网页可以使用特定的翻译服务？

**Comment by theowenyoung** [comment]
目前在开发者设置里支持，请参考文档，修改翻译服务里的 matches  即可：

https://immersivetranslate.com/docs/advanced/#%E7%BF%BB%E8%AF%91%E6%9C%8D%E5%8A%A1%E9%85%8D%E7%BD%AE
