### ISSUE TITLE
[Bug]: 用完隐藏并翻译原文, 就没办法用双语对照翻译了. 

### ISSUE THREAD

**Issue by thomasTAT** [immersive-translate/immersive-translate#1201]
### 插件版本号 | Version

0.12.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

用完隐藏并翻译原文, 就没办法用双语对照翻译了. 

一般都用全文翻译速览,文章重点. 细看才开双语对照.
但是用了全文翻译,就没办法切换成双语对照了,唉.

![image](https://github.com/immersive-translate/immersive-translate/assets/109513632/9ed1be6f-6fd3-4190-ac01-9f27b5072ce4)

**即便是按双语对照翻译快捷键,仍然是全文翻译.**
![image](https://github.com/immersive-translate/immersive-translate/assets/109513632/6a279845-d571-4546-876c-314c4a73aa6c)

### 出现问题的网址 | URL

https://www.bbc.com/news/world-us-canada-67684309

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/ce7865ab-ba5d-4887-92e1-ae4d297ee5e4)
用这个来显示双语看下

**Comment by theowenyoung** [comment]
确实 这里翻译页面主要区域 应该用双语才对。 如果你默认的模式是 双语的话。

**Comment by theowenyoung** [comment]
最新版本 1.1.0 版本已经修复该问题，目前在 主快捷键和仅译文模式的快捷键之间可以互相切换。
