### ISSUE TITLE
[Bug]: openai的翻译服务不能用，怎么办？

### ISSUE THREAD

**Issue by WeipengXue** [immersive-translate/immersive-translate#1202]
### 插件版本号 | Version

V0.12.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

openai的不能用，每次测试都是：网络问题，无法连接到服务，请检查你的代理或本地网络连接后重试。 Failed to fetch[点此测试服务]

**Comment by theowenyoung** [comment]
你好，这个问题请联系 openai 的提供商，插件本身应该是正常的。
