### ISSUE TITLE
[Bug]:  未登录

### ISSUE THREAD

**Issue by AudreyLiii** [immersive-translate/immersive-translate#1206]
### 插件版本号 | Version

0.12.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

正常开网页，全是问号
![Quicker_20231213_043334](https://github.com/immersive-translate/immersive-translate/assets/128182302/bc4136d6-97b6-4c00-8b56-66278b3e64f6)

### 出现问题的网址 | URL

https://www.google.com/search?q=VScodepython&sca_esv=590391945&sxsrf=AM9HkKloYuBrLkfYgcImwF8O5yTonm3INQ%3A1702441493578&ei=FTJ5Zfj4IuGE0PEPodK5kAs&ved=0ahUKEwi41-bjyIuDAxVhAjQIHSFpDrIQ4dUDCBE&uact=5&oq=VScodepython&gs_lp=Egxnd3Mtd2l6LXNlcnAiDFZTY29kZXB5dGhvbjIIEAAYBxgeGAoyCxAAGAcYHhjxBBgKMg0QABiABBixAxiDARgKMgcQABiABBgKMgcQABiABBgKMgcQABiABBgKMgcQABiABBgKMgcQABiABBgKMgcQABiABBgKMgcQABiABBgKSMMTUNgOWNgOcAJ4AZABAJgB3wGgAd8BqgEDMi0xuAEDyAEA-AEBwgIKEAAYRxjWBBiwA-IDBBgAIEGIBgGQBgg&sclient=gws-wiz-serp

### 重现步骤 | To Reproduce

正常使用

### 补充说明 | Additional context

![Quicker_20231213_043334](https://github.com/immersive-translate/immersive-translate/assets/128182302/87e81e8b-7830-4154-8a4f-7ee09b968ed7)

**Comment by theowenyoung** [comment]
应该是需要在插件重新登录一下，重新登录试试呢？
