### ISSUE TITLE
是否可以避免在epub中翻译代码

### ISSUE THREAD

**Issue by hidaris** [immersive-translate/immersive-translate#1207]
### 您希望的更新和改进是什么 | Update or Improve

![image](https://github.com/immersive-translate/immersive-translate/assets/8336146/536a11c8-8fd5-497c-8892-769ee4e5b87f)
如图，插件在epub中会将代码一并翻译，理解会有些不方便

### 补充说明 | Additional context

[deep_learning.zip](https://github.com/immersive-translate/immersive-translate/files/13656700/deep_learning.zip)

**Comment by theowenyoung** [comment]
可以把epub 压缩成 zip 发一下吗？

看下能不能处理，大多数情况下是不翻译的，除非这个epub 不标准。

**Comment by hidaris** [comment]
> 可以把epub 压缩成 zip 发一下吗？
> 
> 看下能不能处理，大多数情况下是不翻译的，除非这个epub 不标准。

更新到上面的附件啦

**Comment by theowenyoung** [comment]
![CleanShot 2023-12-27 at 23 19 40@2x](https://github.com/immersive-translate/immersive-translate/assets/62473795/ad47b0ae-c5f5-4f18-9d64-8e47a7655ae1)

看起来没办法，它的代码没有任何标识。

**Comment by hidaris** [comment]
感谢调研
