### ISSUE TITLE
[Bug]: 谷歌搜索翻译导致页面错位 

### ISSUE THREAD

**Issue by timelic** [immersive-translate/immersive-translate#1208]
### 插件版本号 | Version

0.12.5

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/20257354/5062976a-6db0-4fa9-aff2-97fde7c0bc2a)

图中，`pdf`，`翻译此页`这几个tag有错位情况。

### 出现问题的网址 | URL

https://www.google.com/search?q=HCL-32&newwindow=1&sca_esv=590391945&sxsrf=AM9HkKkHb1FFasNl-7NWUqBr8NP2mKrMnw:1702448957342&ei=PU95ZdTBFJjYkPIP_L2dkA4&ved=0ahUKEwiU1ObK5IuDAxUYLEQIHfxeB-IQ4dUDCBE&uact=5&oq=HCL-32&gs_lp=Egxnd3Mtd2l6LXNlcnAiBkhDTC0zMjIGEAAYBxgeMgYQABgHGB4yBhAAGAcYHjIGEAAYBxgeMgYQABgHGB4yBhAAGAcYHjIGEAAYBxgeMgYQABgHGB4yBhAAGAcYHjIGEAAYBxgeSPYHUABY8QVwAHgBkAEAmAGWA6ABlgOqAQM0LTG4AQPIAQD4AQHiAwQYACBBiAYB&sclient=gws-wiz-serp

**Comment by theowenyoung** [comment]
这个有点难搞.. 谷歌的网页太奇葩了..

**Comment by timelic** [comment]
确实是这样，这class混淆之后就...
