### ISSUE TITLE
[Bug]: 为什么翻译总是出现糊在一起的情况？

### ISSUE THREAD

**Issue by ddkk3000** [immersive-translate/immersive-translate#1209]
### 插件版本号 | Version

0.12.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome, Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

如下图。翻译总是黏在一起。几乎所有的pdf书籍都是如此。

![msedge_tvFcUYcaeL](https://github.com/immersive-translate/immersive-translate/assets/10786234/99f41f5c-abbf-4a90-9339-cf99faf4b002)

**Comment by keyboard3** [comment]
论文公式pdf参考这里 https://immersivetranslate.com/docs/pdf/nougat/
