### ISSUE TITLE
翻译内容重复

### ISSUE THREAD

**Issue by lingting** [immersive-translate/immersive-translate#121]
url: https://www.jetbrains.com/help/idea/configuring-third-party-tools.html#a96bc5cb
浏览器: chrome 版本 109.0.5414.120（正式版本） （64 位）
插件: 0.2.51

![image](https://user-images.githubusercontent.com/59352063/217754223-0470e116-d234-4979-9777-9d718820eabc.png)

**Comment by theowenyoung** [comment]
确认～ 感谢反馈

**Comment by theowenyoung** [comment]
最新版已解决～ 

请更新最新版，并且 点击 浏览器图标 更新到最新规则～
