### ISSUE TITLE
[Bug]: youtube上不工作,这正常吗?

### ISSUE THREAD

**Issue by thomasTAT** [immersive-translate/immersive-translate#1210]
### 插件版本号 | Version

0.12.5

### 平台 | Platform

win 11

### 浏览器 | Browsers

edge

### 插件类型 | Extension Type

chrome extension

### 请描述这个Bug | Describe the bug

youtube上不工作,这正常吗?
![image](https://github.com/immersive-translate/immersive-translate/assets/109513632/4d7991b5-c75b-42a9-bfce-9b23e03fb3b3)

### 出现问题的网址 | URL

https://www.youtube.com/

**Comment by keyboard3** [comment]
点击显示原文然后重翻也不行嘛？ 可以等0.12.6 这个问题应该修复了
