### ISSUE TITLE
[Bug]: 选择了沉浸式翻译会员，但是仍然用我自己的api的额度

### ISSUE THREAD

**Issue by heheda123123** [immersive-translate/immersive-translate#1211]
### 插件版本号 | Version

0.12.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/97490782/e8faa7f1-c15c-46b5-b525-a8d6f8058111)
![image](https://github.com/immersive-translate/immersive-translate/assets/97490782/fb9cb6aa-352d-4f20-8638-009e05e44cfb)
要不是有邮箱提示，还真不知道。。

**Comment by heheda123123** [comment]
把自定义api key里面的api删掉，就不会有这个情况了

**Comment by keyboard3** [comment]
切换pro之后，原页面刷新才会配置生效
