### ISSUE TITLE
Youtube 字幕-英文(自動產生) 翻譯結果出現在前幾秒，沒有按時間軸出現

### ISSUE THREAD

**Issue by argo057** [immersive-translate/immersive-translate#1213]
### 插件版本号 | Version

0.12.5

### 平台 | Platform

iOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

開啟自動雙語字幕時，Youtube 自動產生的英語字幕翻譯結果出現在前幾秒，且未按時間軸出現
![IMG_2983](https://github.com/immersive-translate/immersive-translate/assets/10750294/53341f10-5df9-455e-aa37-de98e9a8c5ac)
![IMG_2984](https://github.com/immersive-translate/immersive-translate/assets/10750294/bb75e70d-6555-4232-b44b-e5f8cf1a66f0)

### 出现问题的网址 | URL

https://www.youtube.com/watch?v=LokQyLFPUOA

### 重现步骤 | To Reproduce

打開自動雙語字幕

**Comment by FattySpring** [comment]
YouTube 自带机翻字幕，繁体中文会出现格式错误，导致所有字幕在开始的时候弹出一大段字幕，基于此场景建议在【设置】【视频字幕】中开启​​【使用沉浸式翻译来翻译字幕】选项。
