### ISSUE TITLE
[Bug]: 翻译后双击文本，会退出翻译，但插件却显示当前是处于翻译后的状态

### ISSUE THREAD

**Issue by 357447923** [immersive-translate/immersive-translate#1214]
### 插件版本号 | Version

v0.12.6

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

我使用本插件翻译后，双击（或许是连续按四下）了文本，翻译后的内容会消失，但插件显示当前是翻译状态
![双击前](https://github.com/immersive-translate/immersive-translate/assets/105688182/0f139756-9eba-4070-b2c8-1119361530cd)
![双击后](https://github.com/immersive-translate/immersive-translate/assets/105688182/20b08896-f0b1-41c3-9dc7-9ed3ba5e9209)

### 出现问题的网址 | URL

https://pdos.csail.mit.edu/6.824/labs/lab-raft.html

### 重现步骤 | To Reproduce

双击(或许是连续点击四下)了翻译后的文本
在我发现这个问题的时候是双击触发，复现的时候却是连续点击四下鼠标

### 补充说明 | Additional context

其他网址目前没有出现这个问题，或许有可能是出现问题的url的问题？还是说edge的插件商城中该插件并非最新版？

**Comment by keyboard3** [comment]
0.12.7 已修复
