### ISSUE TITLE
[Bug]: 和Edge浏览器的朗读功能出现不兼容

### ISSUE THREAD

**Issue by greyczj** [immersive-translate/immersive-translate#1215]
### 插件版本号 | Version

0.12.6

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在egde把英文网站翻译成中文后，启用浏览器自带朗读功能，一开始朗读正常，但是到了中间，即将读完一段时，那段就会消失，使用Google翻译插件翻译网页再朗读不会出现这种情况。
Microsoft Edge版本 120.0.2210.61 (正式版本) (64 位)

### 出现问题的网址 | URL

https://www.bbc.com/news/world-us-canada-67712059?xtor=AL-72-%5Bpartner%5D-%5Bbbc.news.twitter%5D-%5Bheadline%5D-%5Bnews%5D-%5Bbizdev%5D-%5Bisapi%5D&at_medium=social&at_ptr_name=twitter&at_link_type=web_link&at_link_origin=BBCWorld&at_campaign=Social_Flow&at_format=link&at_link_id=8037A364-9A29-11EE-8FAC-1A98E03B214A&at_campaign_type=owned&at_bbc_team=editorial

**Comment by keyboard3** [comment]
0.12.7 已修复
