### ISSUE TITLE
[Bug]: 部分网页（GitHub）全文翻译会出现抖动

### ISSUE THREAD

**Issue by pilgrimlyieu** [immersive-translate/immersive-translate#1218]
### 插件版本号 | Version

0.12.6

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![1](https://github.com/immersive-translate/immersive-translate/assets/80107081/447f44bb-7a5b-49e7-ab2a-cc7908b47217)

![2](https://github.com/immersive-translate/immersive-translate/assets/80107081/f90d1f31-9d7e-4946-b7f7-7cc763455b32)

分别是[这个](https://github.com/tpope/vim-fugitive/issues/846#issuecomment-733639827)和[这个网页](https://github.com/tpope/vim-fugitive/issues/846#issuecomment-733639827)。

### 补充说明 | Additional context

用的是 Google 翻译。

**Comment by pilgrimlyieu** [comment]
这个 issue 也有图二的情况，而且还看到了新的 :grinning:

![3](https://github.com/immersive-translate/immersive-translate/assets/80107081/7cb9876a-388c-4a7a-9b75-64fdc459e74a)

**Comment by pilgrimlyieu** [comment]
![4](https://github.com/immersive-translate/immersive-translate/assets/80107081/287f6ef8-c823-4ab1-a66c-61f74e958f94)

似乎之前没有这样的情况？

**Comment by keyboard3** [comment]
我这边没能复现 是不是有别的插件影响了？ 隐身窗口试下看

**Comment by pilgrimlyieu** [comment]
> 我这边没能复现 是不是有别的插件影响了？ 隐身窗口试下看

经过测试，与插件 [Refine GitHub](https://github.com/refined-github/refined-github) 有关，关掉了就不会了。能否进行适配？我记得之前好像是不会的。

**Comment by cesaryuan** [comment]
> 经过测试，与插件 [Refine GitHub](https://github.com/refined-github/refined-github) 有关，关掉了就不会了。能否进行适配？我记得之前好像是不会的。

我也有同样现象，禁用Refine GitHub就没有问题了，但是之前是没有这个问题的😂

**Comment by mancuoj** [comment]
+1 同样情况，之前是没有的

**Comment by z0z0r4** [comment]
同求适配

**Comment by keyboard3** [comment]
已修复 重新刷新下页面看看

**Comment by pilgrimlyieu** [comment]
> 已修复 重新刷新下页面看看

感谢 :grinning:！

**Comment by pilgrimlyieu** [comment]
> 已修复 重新刷新下页面看看

似乎未完全修复？前面动图反映的应该是已经修复了。但打开 Refine GitHub 后仍有这个问题，在 #1227。

![1](https://github.com/immersive-translate/immersive-translate/assets/80107081/937e9005-8107-42df-ba4b-2d5a2f2a59db)

**Comment by r91085** [comment]
很多網頁都有同樣問題：例如：
https://www.techpowerup.com/review/creative-sound-blaster-x4/3.html

瀏覽器配置沒有更動過，但是以前沒有這個問題，最近才開始出現

**Comment by pilgrimlyieu** [comment]
> 很多網頁都有同樣問題：例如： [techpowerup.com/review/creative-sound-blaster-x4/3.html](https://www.techpowerup.com/review/creative-sound-blaster-x4/3.html)

我这个网页没问题。

> 瀏覽器配置沒有更動過，但是以前沒有這個問題，最近才開始出現

确实如此。

**Comment by keyboard3** [comment]
> 很多網頁都有同樣問題：例如： [techpowerup.com/review/creative-sound-blaster-x4/3.html](https://www.techpowerup.com/review/creative-sound-blaster-x4/3.html)
> 
> 瀏覽器配置沒有更動過，但是以前沒有這個問題，最近才開始出現浏览器配置没有更动过，但是以前没有这个问题，最近才开始出现

没复现，截图或者录屏看下

**Comment by keyboard3** [comment]
> > 很多網頁都有同樣問題：例如： [techpowerup.com/review/creative-sound-blaster-x4/3.html](https://www.techpowerup.com/review/creative-sound-blaster-x4/3.html)很多网页都有同样问题：例如： techpowerup.com/review/creative-sound-blaster-x4/3.html
> 
> 我这个网页没问题。
> 
> > 瀏覽器配置沒有更動過，但是以前沒有這個問題，最近才開始出現浏览器配置没有更动过，但是以前没有这个问题，最近才开始出现
> 
> 确实如此。

再试下

**Comment by pilgrimlyieu** [comment]
> 再试下

可以了。那我先关闭了，要是再出现的话再开启。感谢！
