### ISSUE TITLE
[Bug]: colab中代码框被翻译了

### ISSUE THREAD

**Issue by ouni3** [immersive-translate/immersive-translate#1219]
### 插件版本号 | Version

0.12.6

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

代码输入框被翻译了

### 出现问题的网址 | URL

https://colab.research.google.com/github/tensorflow/docs-l10n/blob/master/site/zh-cn/hub/tutorials/tf2_image_retraining.ipynb?hl=zh-cn#scrollTo=w_YKX2Qnfg6x

### 重现步骤 | To Reproduce

进入网站后翻译

**Comment by keyboard3** [comment]
0.12.7 已修复
