### ISSUE TITLE
[Bug] Android 文档里面的注意区块不会被识别并翻译

### ISSUE THREAD

**Issue by Vixb1122** [immersive-translate/immersive-translate#122]
地址：https://developer.android.google.cn/jetpack/compose/modifiers

![image](https://user-images.githubusercontent.com/17810492/217988822-250c2d59-7628-4302-96f5-58b2681237a0.png)

地址：https://developer.android.google.cn/jetpack/compose/layering
![image](https://user-images.githubusercontent.com/17810492/218255068-9d4bd0ad-80ce-4112-8ae4-b4d5af6cb00a.png)

**Comment by theowenyoung** [comment]
感谢反馈，下个版本修复～

**Comment by Vixb1122** [comment]
@theowenyoung 刚试了下，还有一种情况不会被翻译

地址：https://developer.android.google.cn/jetpack/compose/layering
![image](https://user-images.githubusercontent.com/17810492/218255068-9d4bd0ad-80ce-4112-8ae4-b4d5af6cb00a.png)

**Comment by theowenyoung** [comment]
可以了，更新下规则。

**Comment by Vixb1122** [comment]
@theowenyoung 又发现一个地方

地址：https://developer.android.google.cn/jetpack/compose/compositionlocal#intro
![image](https://user-images.githubusercontent.com/17810492/218258173-827e807d-6584-4373-a4ac-32362da50186.png)
