### ISSUE TITLE
[Bug]: 部份內容不能夠自動翻譯

### ISSUE THREAD

**Issue by hzzzzaaaa** [immersive-translate/immersive-translate#1220]
### 插件版本号 | Version

0.12.6

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

<img width="1388" alt="截圖 2023-12-15 15 26 29" src="https://github.com/immersive-translate/immersive-translate/assets/107546522/5b21f614-110a-4e6f-b408-305262aa96cf">

### 出现问题的网址 | URL

大部份外地新聞網站

**Comment by keyboard3** [comment]
给个地址复现下

**Comment by hzzzzaaaa** [comment]
> 给个地址复现下。你上面没看出来哪里没有翻译

Bloomberg.com 还有wsj.com marketwatch.com等财经网站也是，就是图𥚃英文那段。

<img width="1144" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/107546522/9782d875-bfd6-4e6d-b3ae-873e103fe8d9">

比如这个，中间的段落也是没翻译成功。  
https://www.bloomberg.com/news/articles/2023-12-15/best-luxury-and-culture-of-2023-hotels-cars-watches-food-wine-art-theater?srnd=premium-asia

翻译用的是google deeplx.

**Comment by keyboard3** [comment]
在这里把长段落换行禁掉 https://dash.immersivetranslate.com/#interface

**Comment by hzzzzaaaa** [comment]
> 在这里把长段落换行禁掉 https://dash.immersivetranslate.com/#interface

好了～感谢感谢

**Comment by keyboard3** [comment]
0.12.7 已修复
