### ISSUE TITLE
youtube自动生成字幕的断句问题

### ISSUE THREAD

**Issue by crysishacker** [immersive-translate/immersive-translate#1222]
### 您希望的更新和改进是什么 | Update or Improve

因为没有断句，通常这些翻译质量非常糟糕。但是如果能够把整个视频的字幕都送到google翻译再返还，那么翻译效果会好很多。这个功能需求非常大和普遍，能不能做出来呢？

**Comment by crysishacker** [comment]
哦我没仔细看，更新之后已经做了……你们实在太棒了！那个dualsub插件可坏了，把这个功能一个月收费50rmb，但是你们把它变免费了！多少赞美都不为过！免费服务全人类！

**Comment by crysishacker** [comment]
google translator明明是免费api那个dualsub竟然敢收费，真是太猖狂了。有了沉浸式翻译，所有chrome上的双字幕收费玩意都去死吧！

**Comment by keyboard3** [comment]
哈哈 多多宣传
