### ISSUE TITLE
[Bug]: fibery.io Userguide页面 只能翻译标题和侧边栏，翻译不了正文

### ISSUE THREAD

**Issue by saccohuo** [immersive-translate/immersive-translate#1223]
### 插件版本号 | Version

0.12.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

fibery.io Userguide页面 只能翻译标题和侧边栏，翻译不了正文
![image](https://github.com/immersive-translate/immersive-translate/assets/13887263/e6ceea6a-80b2-4d44-bf57-a1aa6f5079dd)

### 出现问题的网址 | URL

https://the.fibery.io/@public/User_Guide/Guide/Rule-51

### 重现步骤 | To Reproduce

必现

**Comment by keyboard3** [comment]
已适配，稍后刷新下页面重试下
