### ISSUE TITLE
[Bug]: OpenAI 翻译似乎不支持 aigptx.top 的代理

### ISSUE THREAD

**Issue by Moskize91** [immersive-translate/immersive-translate#1225]
### 插件版本号 | Version

0.12.7

### 平台 | Platform

macOS

### 浏览器 | Browsers

Other

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

aigptx.top 是一个代理 OpenAI 的网站，它会提供和 OpenAI 一样的 API 接口，以供使用。从原则上来说，仅仅将 OpenAI 的 API 域名替换成它的域名即可。

但目前似乎不支持 aigptx.top 提供的服务。

### 重现步骤 | To Reproduce

在设置的“翻译服务”选择 OpenAI，然后选择“自定义服务”，其中 APIKEY 填写给出的 aigptx.top 的 Key，在“自定义 API 接口地址”中填写 https://api.ohmygpt.com/。

**Comment by keyboard3** [comment]
报什么错误

**Comment by Moskize91** [comment]
@keyboard3 今天重新测试，发现已经无法复现问题，测试成功。感谢回复。
