### ISSUE TITLE
[Bug]: 插件安装在Adguard上的，无法翻译。

### ISSUE THREAD

**Issue by zyzatyy** [immersive-translate/immersive-translate#1226]
### 插件版本号 | Version

0.12.7

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension, 油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

插件安装在Adguard上的，无法翻译。
<img width="1171" alt="Screenshot 2023-12-17 at 10 30 27 AM" src="https://github.com/immersive-translate/immersive-translate/assets/111683830/3670e200-4929-4225-bf59-cc49a491af1c">

### 出现问题的网址 | URL

Instapaper

**Comment by keyboard3** [comment]
点击下问号看报错信息

**Comment by keyboard3** [comment]
不兼容Adguard，它的api可能跟油猴api不兼容，这个没办法

**Comment by keyboard3** [comment]
> 不，Adgard兼容沉浸式翻译的，其他网站都可以用，就Instapaper这个网站用不了。

建议直接安装扩展或者使用油猴脚本

**Comment by theowenyoung** [comment]
可以换个翻译服务试试。这个可能是 adguard 某些规则屏蔽了某些域名？ 试试关掉全部规则什么的试试看。
