### ISSUE TITLE
[Bug]: 翻譯後滑動頁面，文字會消失。

### ISSUE THREAD

**Issue by curtiswu33** [immersive-translate/immersive-translate#1227]
### 插件版本号 | Version

0.12.6

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在這個網站https://www.aigle.com/fr/fr，翻譯後滑動頁面，文字會消失變成空白，沒有原文也沒有譯文。

### 出现问题的网址 | URL

https://www.aigle.com/fr/fr

**Comment by keyboard3** [comment]
录屏看下，没能复现。或者是有什么其他插件干扰？

**Comment by curtiswu33** [comment]
https://github.com/immersive-translate/immersive-translate/assets/134845275/8341dd87-97dc-437e-bd43-00ab33b6427c

**Comment by keyboard3** [comment]
这个网站自身有bug 
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/fdc50f6b-f9af-4912-83fe-7c1932b1696f)
可以兼容，下一版会带上

**Comment by curtiswu33** [comment]
> 这个网站自身有bug ![image](https://private-user-images.githubusercontent.com/13177744/291312578-ed880063-baa2-49c1-9df6-c91098c53e67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NTY5ODAsIm5iZiI6MTcwMjk1NjY4MCwicGF0aCI6Ii8xMzE3Nzc0NC8yOTEzMTI1NzgtZWQ4ODAwNjMtYmFhMi00OWMxLTlkZjYtYzkxMDk4YzUzZTY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDAzMzEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxOGY4Nzk4YzM0Nzk3MzI5ZWMyMTc5NGJhODM2NWRmZTYyNDIyNjU5MDUwMjVmMWVjOTc1MWY4YjM1ZTExYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fokiyZAVy5mHFt__V7scs_vk05YQT4GX_2nXrEQMxDI) 可以兼容，下一版会带上

原來如此，感謝！

**Comment by keyboard3** [comment]
0.12.8 已修复

**Comment by curtiswu33** [comment]
> 0.12.8 已修复

感謝！！
