### ISSUE TITLE
增加网页标题翻译的进阶设置——把网页标题的翻译放在原标题之前

### ISSUE THREAD

**Issue by pbxs666** [immersive-translate/immersive-translate#1229]
### 您希望的更新和改进是什么 | Update or Improve

有的网站论坛本身原网页的名称就很长，翻译后的中文标题拼接在后面也看不到，尤其是从收藏夹或者历史记录里查看时更是难受，中文标题总是显示不全甚至都显示不出来，因为原版的外语标题太长了。

希望能增加网页标题翻译的进阶设置：标题译文前置于原文之前

### 补充说明 | Additional context

例如这是一个显示译文的标题“Vanilla Item Descriptions at Skyrim Special Edition Nexus - Mods and Community --- Skyrim Special Edition Nexus 的原版物品描述 - Mods and Community”

来自一个很著名的游戏MOD网站Nexus的一个具体MOD发布页面，它原版的标题就很长“Vanilla Item Descriptions at Skyrim Special Edition Nexus - Mods and Community”，翻译后的那部分很大概率在浏览器标签页、收藏夹或历史记录里显示不出来。

这样就会导致网页标题翻译这一功能失去它本来的作用意义，即直观方便地看懂标题的意思。

**Comment by theowenyoung** [comment]
可以，可能默认就应该这样做。加入计划了。

**Comment by theowenyoung** [comment]
1.1.0 版本起已调整为默认行为，中文标题在前，英文在后。
