### ISSUE TITLE
【改进】apple/swift-evolution 页面顶部标题出现闪烁

### ISSUE THREAD

**Issue by tisfeng** [immersive-translate/immersive-translate#1230]
### 您希望的更新和改进是什么 | Update or Improve

这个网页 https://github.com/apple/swift-evolution/blob/main/proposals/0365-implicit-self-weak-capture.md

翻译后，顶部标题不出现闪烁。

### 补充说明 | Additional context

https://github.com/immersive-translate/immersive-translate/assets/25194972/71b413f1-d6d9-4254-bf6f-e4d14c411fec

**Comment by keyboard3** [comment]
我们这边没有复现。能提供更多的信息吗，有什么其他插件会影响到github页面吗？我们插件什么版本？

**Comment by tisfeng** [comment]
我用 Safari 0.12.6 试了一下，只启用沉浸式翻译一个插件，没有出现问题。

视频中是 Chrome 0.12.7，我关闭其他所有插件测试，还是会出现这个问题

https://github.com/immersive-translate/immersive-translate/assets/25194972/ca0c8fa6-36ab-407c-b7b4-9e31fd5e80c3

**Comment by FattySpring** [comment]
已修复，刷新下页面，再试下

**Comment by tisfeng** [comment]
没问题，已经好了。

原来这个规则是远程接口控制的啊，这个挺方便。
