### ISSUE TITLE
[Bug]: 点击悬浮球不能翻译

### ISSUE THREAD

**Issue by ChloeKurumi** [immersive-translate/immersive-translate#1235]
### 插件版本号 | Version

0.12.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

点击悬浮球翻译没反应或翻译不完整，只有一行，以前是好的，最近几个版本不行了

### 出现问题的网址 | URL

https://ncode.syosetu.com/n1154in/

### 重现步骤 | To Reproduce

例如一下网站，点击悬浮球，翻译没反应
https://ncode.syosetu.com/n1154in/
https://syosetu.org/novel/273680/

**Comment by theowenyoung** [comment]
可以截图说明一下吗？ 第一个网站没有权限，第二个网站我这里：

![CleanShot 2023-12-19 at 02 08 26@2x](https://github.com/immersive-translate/immersive-translate/assets/62473795/bb47fd7a-e762-4372-a98d-23d7847d9298)

**Comment by ChloeKurumi** [comment]
> 可以截图说明一下吗？ 第一个网站没有权限，第二个网站我这里：
> 
>

我换了个浏览器试了下，好像可以........不知道什么原因，可能是插件影响？问题是以前都是好的。
![image](https://github.com/immersive-translate/immersive-translate/assets/41937301/817270c5-40dd-40ad-b130-5e368d2e07f2)
![image](https://github.com/immersive-translate/immersive-translate/assets/41937301/1846c0b0-b3c1-4811-aa74-35e898d1adbc)
我这里点击悬浮球，没反应，请求也没发送。第二个完整正文点击后，只翻译一行....

**Comment by keyboard3** [comment]
用了什么翻译服务？切换成别的呢？

**Comment by ChloeKurumi** [comment]
最近是改了什么吗？现在好了....

**Comment by theowenyoung** [comment]
不确定... 确实一直有在发新版本。那么先关了。
