### ISSUE TITLE
[Bug]: 鼠标悬停设置为“+ctrl翻译/还原”，但是“ctrl”键更像是一个开关，有时候按了一次以后鼠标悬停的地方都会翻译。

### ISSUE THREAD

**Issue by stan1233** [immersive-translate/immersive-translate#1240]
### 插件版本号 | Version

0.12.8

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

[Bug]: 鼠标悬停设置为“+ctrl翻译/还原”，但是“ctrl”键更像是一个开关，有时候按了一次以后鼠标悬停的地方都会翻译。

### 出现问题的网址 | URL

所有网站

**Comment by theowenyoung** [comment]
不知道有没有可以必现的路径，我有的时候好像也会遇到，但是不知道如何重现..

**Comment by joeyscave** [comment]
我有个类似的 bug，我设置了 shift 为悬停翻译的快捷键，但是按 cmd 也会翻译

**Comment by inused** [comment]
> 不知道有没有可以必现的路径，我有的时候好像也会遇到，但是不知道如何重现..

同样有鼠标悬停的问题。
快捷键设置的是 Ctrl，现象如下：
1. 快速点按 Ctrl 键，可以正常实现 翻译/还原 功能
2. 按住 Ctrl 键
    1. 直接开始翻译
    2. 鼠标未移开，稍等一会儿松开按键会触发还原
    3. 鼠标移动到其他文字，稍等一会儿松开按键后会触发此时鼠标位置文字的翻译

我用的是油猴脚本版本，不知道功能是如何实现的，但是看现象感觉与绑定的键盘事件有关，像是同时绑定了keydown和keyup事件。

**Comment by theowenyoung** [comment]
@inused 按照你的流程，没能浮现，稍等一会儿松开之后，没有触发还原。

设置页面 和 面板设置的快捷键是一个东西。

**Comment by theowenyoung** [comment]
最新版本 1.1.3 版本已经支持了新的快捷键：

- 你可以自定义组合键，以在页面上临时开启“鼠标悬停直接翻译”，再次按下则取消。

另外也支持单独为鼠标悬停设置一个组合键，比如 `Ctrl+E` 这种的，来配置鼠标悬停翻译。

还有就是鼠标失去焦点再返回的问题应该也已经解决了。

欢迎体验和反馈哈～
