### ISSUE TITLE
[Bug]: 翻译回退

### ISSUE THREAD

**Issue by DSLZL** [immersive-translate/immersive-translate#1241]
### 插件版本号 | Version

0.12.8

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

自动翻译到一半，中文刚刚出来就没了，直接变成原样

### 出现问题的网址 | URL

少部分

### 重现步骤 | To Reproduce

None

### 补充说明 | Additional context

None

**Comment by DSLZL** [comment]
很多英文的小众网页经常回退，连github都会

**Comment by keyboard3** [comment]
> 很多英文的小众网页经常回退，连github都会

录个屏看下 我们这边没这个情况。是不是有什么其他插件干扰？

**Comment by DSLZL** [comment]
这是个概率问题，有时候才有，我的插件如下
![image](https://github.com/immersive-translate/immersive-translate/assets/92631890/5b746773-a6d2-4baf-bfd0-c1c0b2b9f984)
以及
![image](https://github.com/immersive-translate/immersive-translate/assets/92631890/7fc1b4b9-e9bd-4675-bd18-4fd01b399816)

**Comment by keyboard3** [comment]
那这个问题可能不好找了

**Comment by DSLZL** [comment]
> 那这个问题可能不好找了

我尽量在能触发回退的页面多刷刷，用次数弥补概率看看能不能录到

**Comment by theowenyoung** [comment]
暂时无法复现，先关了哈，下次遇到问题的时候再直接回复即可。
