### ISSUE TITLE
[Bug]: YouTube翻译BUG

### ISSUE THREAD

**Issue by Sinatrade** [immersive-translate/immersive-translate#1242]
### 插件版本号 | Version

0.12.8

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

YouTube视频评论区/标题翻译后，如果打开其他YouTube视频，评论区/标题会出现上一个视频的信息，刷新网页才能解决。

**Comment by keyboard3** [comment]
录个屏看下，没有能复现

**Comment by keyboard3** [comment]
暂无反馈，暂时关闭此问题
