### ISSUE TITLE
[Bug]: 谷歌翻译服务失效

### ISSUE THREAD

**Issue by maglausphell** [immersive-translate/immersive-translate#1243]
### 插件版本号 | Version

0.5.6

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

选择谷歌翻译服务时总是timeout无法有效的翻译，而使用微软翻译则可以

**Comment by maglausphell** [comment]
谷歌的翻译服务用不了了

**Comment by keyboard3** [comment]
去官网更新版本，你这个版本太老了  https://immersivetranslate.com/ 。谷歌服务需要翻墙
