### ISSUE TITLE
[Bug]: Gemini api地址不在白名单内

### ISSUE THREAD

**Issue by inused** [immersive-translate/immersive-translate#1244]
### 插件版本号 | Version

v0.12.9

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

v0.12.9版本新增了Goole Gemini，但是油猴版本中没有对api地址放行，导致 Gemini 无法正常使用。
手动添加 @connect 标签后正常。

### 补充说明 | Additional context

另外，对于所有可以修改自定义api地址的服务，修改后在油猴版本中都会出现api地址不允许访问的情况，需要手工改动脚本，插件版本更新后还需要将被更新覆盖的部分再次添加回去。
个人对油猴脚本开发不熟悉，请问有没有办法实现自动放行？

**Comment by keyboard3** [comment]
0.12.10 油猴脚本已修复 gemini授权问题。 自定义地址都需要手工去编辑油猴去授权域名
