### ISSUE TITLE
[Bug]: PDF 阅读页面的打开文件的图标使用含义错误

### ISSUE THREAD

**Issue by yuchanns** [immersive-translate/immersive-translate#1245]
### 插件版本号 | Version

0.12.8

### 平台 | Platform

Linux

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

这个图标是分享图标，被用来表示打开文件，容易让用户感到迷惑，我认为这是一个 Bug

![2023-12-21_15-49](https://github.com/immersive-translate/immersive-translate/assets/25029451/12242032-aa84-4a07-b4c7-5d65ce912f77)

### 补充说明 | Additional context

可供参考的 FontAwesome 图标

![2023-12-21_16-02](https://github.com/immersive-translate/immersive-translate/assets/25029451/8c5d1b98-9024-4dcf-bf18-1fb3260711fe)

![2023-12-21_16-08](https://github.com/immersive-translate/immersive-translate/assets/25029451/ef0d35b0-e36b-4d83-992b-5f32b6edabad)

**Comment by keyboard3** [comment]
这个打开图标是mozilla设计的。不过确实可以优化下
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/b9b6c19c-5c9f-4411-8357-936c19e8b393)
