### ISSUE TITLE
[Bug]: 翻译Notion页面后，网页中的视频会无法播放

### ISSUE THREAD

**Issue by JasonWDY** [immersive-translate/immersive-translate#1246]
### 插件版本号 | Version

0.12.9

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

问题出现在一个软件的帮助文档，此文档是使用Notion笔记创建的，页面中有许多个嵌入视频，在未翻译网页时，这些视频都可以正常播放。
翻译网页后，之前没有播放过的视频就无法播放了，点击视频区域没有任何反应，但之前在未翻译的原始页面播放过的视频，还可以继续播放。

### 出现问题的网址 | URL

https://insydium.notion.site/nxFluids-SPH-solver-parameters-ae781b3d79134d61a1f8832d6a2f85db

### 重现步骤 | To Reproduce

1.打开网页
2.翻译网页
3.向下滚动，播放网页中的视频

### 补充说明 | Additional context

页面顶部的两个视频似乎翻译后也可以正常播放，下方的几个视频翻译后无法播放。

**Comment by keyboard3** [comment]
这是notion自身做了特殊处理，不允许第三方插件改动网页，改动之后就会导致点击事件冲突，无法响应。上面的视频因为是第三方的，嵌套在iframe中，所以能响应点击事件。下面的视频都是它自己的，所以无法响应。
这种情况插件无能为力了，建议开两个窗口，一个翻译，一个看视频

**Comment by JasonWDY** [comment]
> 这是notion自身做了特殊处理，不允许第三方插件改动网页，改动之后就会导致点击事件冲突，无法响应。上面的视频因为是第三方的，嵌套在iframe中，所以能响应点击事件。下面的视频都是它自己的，所以无法响应。 这种情况插件无能为力了，建议开两个窗口，一个翻译，一个看视频

明白了，谢谢大佬解答
