### ISSUE TITLE
[Bug]: 使用网易有道API翻译时会出现红色的问号

### ISSUE THREAD

**Issue by liwangzhuo1994** [immersive-translate/immersive-translate#1247]
### 插件版本号 | Version

0.12.9

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

使用网易有道API翻译时会出现红色的问号，连原文都看不到，刷新可以解决，不定时出现
![微信图片_20231221185546](https://github.com/immersive-translate/immersive-translate/assets/61745380/38a1aa47-0213-4cb6-95e3-2571cee66e12)

### 出现问题的网址 | URL

www.nexusmods.com

### 重现步骤 | To Reproduce

基本上翻几页就回出现

### 补充说明 | Additional context

暂无

**Comment by keyboard3** [comment]
点击问号看报错

**Comment by keyboard3** [comment]
暂无反馈，暂时关闭此问题
