### ISSUE TITLE
即使使用了自定义 prompt，也没有办法实现同语言翻译

### ISSUE THREAD

**Issue by yuanyuanyuan** [immersive-translate/immersive-translate#1249]
### 您希望的更新和改进是什么 | Update or Improve

例如 我需要翻译复杂的英语词汇为简单的英语词汇，就无法进行了。

我测试过自定义 prompt，没有翻译效果，好像只要是目标语言和源语言一样就不执行翻译。

`
Translate the text to {{to}} Language, please do not explain my original text.:

{{text}}
`
这里{{to}} 代表 english
`
Translate the text from {{to}} to {{to}} Language, please do not explain my original text.:

{{text}}
`

**Comment by yuanyuanyuan** [comment]
或者是否我设置问题，有大佬成功的可以教教么？谢谢。

**Comment by keyboard3** [comment]
是的 遇到同语言是不翻译的。 当然你可以仍然将目标语言设置成中文，然后写死提示词的 {{to}} 成英文应该就行了
