### ISSUE TITLE
[Bug]: ArXiv中的双语版本(沉浸式翻译)打开显示Server Error (500) 

### ISSUE THREAD

**Issue by stan1233** [immersive-translate/immersive-translate#1250]
### 插件版本号 | Version

0.12.10

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

ArXiv中的双语版本(沉浸式翻译)打开显示Server Error (500) 
![image](https://github.com/immersive-translate/immersive-translate/assets/20401741/f5638ca7-7912-4f96-ab6f-c5c0a5bf862f)
会有两个选项，两个打开都是报错500

### 出现问题的网址 | URL

https://arxiv.org/abs/2308.02172

### 重现步骤 | To Reproduce

https://arxiv.org/abs/2308.02172

**Comment by theowenyoung** [comment]
500 是因为这篇论文 在arxiv-vanity 里没有提供，你可以直接在下面的网站输入论文的网址，会发现这一篇确实是 500。 这个是第三方服务，我们没法知道它的服务情况，大多数论文应该是ok的。

https://www.arxiv-vanity.com/
