### ISSUE TITLE
Rules 适配: Steam 论坛页面 (后续跟进：新增适配样式)

### ISSUE THREAD

**Issue by XHXIAIEIN** [immersive-translate/immersive-translate#1251]
### 您希望的更新和改进是什么 | Update or Improve

地址：https://steamcommunity.com/discussions/forum/10/

![image](https://github.com/immersive-translate/immersive-translate/assets/45864744/ff261aa4-1bdc-46a2-adff-fc77bf89071b)

### 补充说明 | Additional context

FYI 稍微拉高了标题框，但依然没解决问题
```
{
      "matches": "https://steamcommunity.com/discussions/*",
      "globalStyles": {
        ".forum_topic": "height:60px;",
        ".forum_topic_name": "display:inline;line-height:0px;"
      },
      "excludeSelectors.add": [
        ".forum_topic_op"
      ]
}
```

**Comment by keyboard3** [comment]
已适配，把自定义规则可以去掉了
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/dd12c1b0-fb8d-4b47-af04-7dd9b8224939)

**Comment by XHXIAIEIN** [comment]
建议调整部分样式，让页面排版更加整齐

```
".forum_topic_name": "line-height: 1.25rem; padding: 6px 20px 0 0;"
".forum_topic_op": "clear: left; padding: 0 0 6px 2rem;"
```

**Comment by XHXIAIEIN** [comment]
![Snipaste_2023-12-27_10-45-03](https://github.com/immersive-translate/immersive-translate/assets/45864744/4cac3668-a8e4-42e2-b43f-0e88cd6b6c4a)

**Comment by keyboard3** [comment]
嗯 已调整
