### ISSUE TITLE
[Bug]: 使用分享功能分享arixv刚更新的官方html页面时，图会挂掉

### ISSUE THREAD

**Issue by hidaris** [immersive-translate/immersive-translate#1252]
### 插件版本号 | Version

0.12.9

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

如标题所示

### 出现问题的网址 | URL

https://browse.arxiv.org/html/2312.12451v1

### 重现步骤 | To Reproduce

1. 打开这个链接
2. 点击翻译
3. 点击分享
然后会发现图挂了

**Comment by keyboard3** [comment]
已修复, 要再分享下
