### ISSUE TITLE
[Bug]: 在使用输入框增强时，时而触发时而不触发

### ISSUE THREAD

**Issue by greataolu** [immersive-translate/immersive-translate#1253]
### 插件版本号 | Version

0.5.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在使用输入框增强时，时而触发时而不触发，建议缩短可识别空格间隔

**Comment by greataolu** [comment]
新发现，在搜狗和谷歌是正常生效的，百度不行。尝试开关其他脚本和插件也没有变化

**Comment by keyboard3** [comment]
百度不兼容  可以参考下兼容性文档https://immersivetranslate.com/docs/input/#%E5%85%BC%E5%AE%B9%E6%80%A7

**Comment by lon91ong** [comment]
必应的copilot页面似乎也不支持

**Comment by keyboard3** [comment]
> 必应的copilot页面似乎也不支持

NewBing 聊天对话不支持，他们的实现都比较特殊，无法监听到空格事件
