### ISSUE TITLE
悬浮球吸附位置增加下方选项

### ISSUE THREAD

**Issue by Curious-r** [immersive-translate/immersive-translate#1254]
### 您希望的更新和改进是什么 | Update or Improve

目前悬浮球只支持在页面左方或者右方，但像我目前的显示器布局，鼠标甩到左边可能会展开垂直标签栏，右边则会呼出页面滚动条，都存在干涉。
~~希望悬浮球位置能增加下方偏左和下方偏右的选项，对于大部分浏览器和页面来说这两个位置都不会存在重要元素。~~
才发现球可以拖动，那只增加下方的选项就可以了。

**Comment by theowenyoung** [comment]
我的macbooke 浏览器 下方是 自动弹出的系统 dock 栏..

**Comment by Curious-r** [comment]
> 我的macbooke 浏览器 下方是 自动弹出的系统 dock 栏..

😂那是浏览器以外的问题了，作为Dock常驻的用户没这个顾虑。而且你觉得下面不方便可以继续放左右，现在主要问题是想放下边的人没得选。

**Comment by FattySpring** [comment]
感谢反馈，现在的悬浮球比较复杂，不太适合放在页面上下位置，经过测试 Mac 上滚动条的比较窄不影响悬浮球的操作，并且滚动条在刚滑动后会隐藏，影响较小，在 Window 上滚动条与悬浮球不冲突，所以暂不考虑支持悬浮球放在页面上下位置

**Comment by Curious-r** [comment]
> 感谢反馈，现在的悬浮球比较复杂，不太适合放在页面上下位置，经过测试 Mac 上滚动条的比较窄不影响悬浮球的操作，并且滚动条在刚滑动后会隐藏，影响较小，在 Window 上滚动条与悬浮球不冲突，所以暂不考虑支持悬浮球放在页面上下位置

了解，感谢耐心回复
