### ISSUE TITLE
如果句子中内嵌了latex公式，翻译之后会将latex长长的源格式写出

### ISSUE THREAD

**Issue by Lixinming584** [immersive-translate/immersive-translate#1255]
### 您希望的更新和改进是什么 | Update or Improve

![微信截图_20231224084045](https://github.com/immersive-translate/immersive-translate/assets/76586970/fea74e41-5d4f-432f-98d3-89b72810eac5)

### 补充说明 | Additional context

如图所示，翻译之后不需要写出latex的源格式

**Comment by keyboard3** [comment]
给个地址

**Comment by Lixinming584** [comment]
https://garrettgoon.com/gaussian-fields/

**Comment by Lixinming584** [comment]
> 给个地址

https://garrettgoon.com/gaussian-fields/

**Comment by keyboard3** [comment]
已适配，刷新下页面
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/3d96f88b-0f9f-4c54-a35e-6610241a17ab)
