### ISSUE TITLE
增加 edge浏览器阅读模式下的翻译功能

### ISSUE THREAD

**Issue by wongtx** [immersive-translate/immersive-translate#1256]
### 您希望的更新和改进是什么 | Update or Improve

如题
![image](https://github.com/immersive-translate/immersive-translate/assets/46996862/ecdab2d7-5a5e-48b3-be9d-7d2207ba7c0f)

**Comment by keyboard3** [comment]
浏览器在阅读模式下不会给插件干预权限的，没办法

**Comment by wongtx** [comment]
感谢您的答复
