### ISSUE TITLE
下载字幕（如YouTube）

### ISSUE THREAD

**Issue by topkof** [immersive-translate/immersive-translate#1257]
### 您希望的更新和改进是什么 | Update or Improve

期待加入此功能

**Comment by junlicn** [comment]
用open AI生成中文英文双语字幕之后。能不能把双语字幕存下来。尤其是youtube的。怎么设计请你们周全考虑，谢谢。

**Comment by pendave** [comment]
Youtube 上的视频能在线显示成双语字幕，请问如何下载这个处理好的翻译过的中文字幕呢？请做个下载链接按钮可以吗？因为很多人喜欢下载字幕到本地来看和加工。
谢谢！

**Comment by FEI352** [comment]
mark，有一个旧的插件可以做到，不过那个已经很久不维护了。

**Comment by cyx951211** [comment]
https://github.com/IndieKKY/bilibili-subtitle?tab=readme-ov-file

![](https://github.com/IndieKKY/bilibili-subtitle/raw/master/screenshot/%E5%AE%8C%E6%95%B4%E6%88%AA%E5%9B%BE.png)

🎬 显示视频的字幕列表
🔗 点击字幕跳转视频对应位置
📥 多种格式复制与下载字幕
📝 多种方式总结字幕
🌍 翻译字幕
🌑 深色主题

类似上面的需求 您看下 感谢感谢

**Comment by theowenyoung** [comment]
这个功能已经在计划中了，应该会在2周内上线，它可能会被放在 Pro 的权益内。

**Comment by cyx951211** [comment]
emm。。。。。。早知道不提了。

**Comment by FEI352** [comment]
> 这个功能已经在计划中了，应该会在2周内上线，它可能会被放在 Pro 的权益内。

我理解作者你想要吃饭的心情，但是能否出一个买断的，单独的版本，毕竟Pro的其他功能也用不上。（DeepL 和很好，但不是必须）

**Comment by FattySpring** [comment]
[1.4.8](https://immersivetranslate.com/docs/CHANGELOG/#148) 已支持 YouTube 双语下载
