### ISSUE TITLE
PDF翻译语句对照

### ISSUE THREAD

**Issue by dddzzzccc** [immersive-translate/immersive-translate#1259]
### 您希望的更新和改进是什么 | Update or Improve

希望能在pdf翻译功能中实现同有道翻译段落那样的语句对照功能，即：当我靠近或者画出中文句子时，可以对应的高亮显示对应的英文语句，类似下面这样
![image](https://github.com/immersive-translate/immersive-translate/assets/131773530/9d317514-fe6f-4bd7-9d0c-649ff0189816)

**Comment by keyboard3** [comment]
嗯 要实现这样对照效果，需要对现在的改动非常大，暂时不会做
