### ISSUE TITLE
内嵌到网站前端

### ISSUE THREAD

**Issue by qiangweihewu** [immersive-translate/immersive-translate#126]
喜欢这个项目，谢谢开发者！有没有可能提供内嵌到网站前端的代码。搭建了英文站点，没有中译，但希望访客也能选择中文。之前有用谷歌翻译的内嵌代码，但服务在国内被墙了

**Comment by theowenyoung** [comment]
不错的想法～

但是内嵌到网站，需要对应的api允许跨域访问才可以？
