### ISSUE TITLE
[Bug]: 多翻译了一个无意义的片段

### ISSUE THREAD

**Issue by evelynn996** [immersive-translate/immersive-translate#1260]
### 插件版本号 | Version

0.12.11最新版

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

看图
![image](https://github.com/immersive-translate/immersive-translate/assets/93717293/d42f394a-0661-4eb3-92f7-2f794eb1ec80)

### 出现问题的网址 | URL

https://docs.spring.io/spring-data/neo4j/docs/6.0.5/reference/html/#faq.custom-queries-with-page-and-slice

**Comment by keyboard3** [comment]
这个常见于翻译服务在一些特殊情况下的异常，切换下别的翻译服务

**Comment by evelynn996** [comment]
> 这个常见于翻译服务在一些特殊情况下的异常，切换下别的翻译服务

确实，原本腾讯翻译改成 微软就没有这个问题了。
