### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by reflyable** [immersive-translate/immersive-translate#1261]
### 插件版本号 | Version

0.12.11

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

不翻译页面的主要内容

### 出现问题的网址 | URL

https://www.rfc-editor.org/rfc/rfc2181.html

**Comment by keyboard3** [comment]
已处理，刷新下页面
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/a8511d35-d9fe-4ebd-a55d-216403d21a40)
