### ISSUE TITLE
[Bug]: macOS 中 Bob 划词翻译后，沉浸式翻译 Shift + 鼠标无法翻译段落

### ISSUE THREAD

**Issue by zhatlas** [immersive-translate/immersive-translate#1265]
### 插件版本号 | Version

0.12.11

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在 macOS 系统中，我是用 Bob翻译工具，我设置了Option+D 作为触发划词翻译开关，Bob 应该是当我触发划词翻译后先去自动调用系统的Cmd+C 复制功能，然后再读剪切板中的内容来翻译。但是每次我使用 Bob 划词翻译后，沉浸式翻译shift+鼠标就无法触发段落翻译了，只能刷新页面才可以。这个问题存在吗，有没有解决办法？

**Comment by zhatlas** [comment]
#564 和这个问题描述类似，都是经历过一个其他软件快捷键后，导致沉浸式翻译的快捷键失效

**Comment by theowenyoung** [comment]
是否是页面失去了焦点？ 在页面空白处点击一下再试试呢？

**Comment by zhatlas** [comment]
> 是否是页面失去了焦点？ 在页面空白处点击一下再试试呢？

尝试过，无法成功，只能刷新网页才能恢复。可以复现，你可以尝试一下。

**Comment by zhatlas** [comment]
> 是否是页面失去了焦点？ 在页面空白处点击一下再试试呢？

确实如你所说，可能是因为页面失去了焦点。切换网页再切回，或者切换别的应用再切回，都能解决。

**Comment by zhatlas** [comment]
@theowenyoung 请问这是不是一个 bug，能否得到解决，我的这个场景很不方便

**Comment by theowenyoung** [comment]
> > 是否是页面失去了焦点？ 在页面空白处点击一下再试试呢？
> 
> 确实如你所说，可能是因为页面失去了焦点。切换网页再切回，或者切换别的应用再切回，都能解决。

点击页面任何空白处 可以解决吗？


理论上插件应该做不了什么，因为是整个窗口失去了焦点，所以浏览器本身都监听不到 keydown 的事件了，插件就更没法收到 shift 点击事件的按下了。

**Comment by zhatlas** [comment]
> > > 是否是页面失去了焦点？ 在页面空白处点击一下再试试呢？
> > 
> > 
> > 确实如你所说，可能是因为页面失去了焦点。切换网页再切回，或者切换别的应用再切回，都能解决。
> 
> 点击页面任何空白处 可以解决吗？
> 
> 理论上插件应该做不了什么，因为是整个窗口失去了焦点，所以浏览器本身都监听不到 keydown 的事件了，插件就更没法收到 shift 点击事件的按下了。

点击当前页面空白处也无法恢复，只能切换网页、切换应用、或者刷新才能恢复

**Comment by theowenyoung** [comment]
感谢反馈，测试的确存在该问题，已在 v0.12.13 版本兼容，该版本已经提交审核。
