### ISSUE TITLE
[Bug]: jstor 列表页的标题不翻译

### ISSUE THREAD

**Issue by keyboard3** [immersive-translate/immersive-translate#1268]
### 插件版本号 | Version

0.12.11

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

标题节点是shadowRoot的Host节点，该节点包含shadow节点和文本节点，这种情况下不会插入译文，需要修复

### 出现问题的网址 | URL

https://www.jstor.org/action/doBasicSearch?Query=hello&scope=eyJpZCI6ICIxMDAxNDY0NjciLCAicGFnZU5hbWUiOiAiQXJ0c3RvciIsICJwYWdlVXJsIjogIi9zaXRlL2FydHN0b3IvIiwgInR5cGUiOiAicG9ydGFsIn0%3D

**Comment by theowenyoung** [comment]
0.12.12 已修复。
