### ISSUE TITLE
[Bug]: "总是翻译的网址"对localhost地址不敏感

### ISSUE THREAD

**Issue by timelic** [immersive-translate/immersive-translate#1269]
### 插件版本号 | Version

0.12.11

### 平台 | Platform

Windows, macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

例如设置“总是翻译的网址”为`localhost:2734`，当打开`localhost:5173`时候也会自动翻译

**Comment by theowenyoung** [comment]
感谢反馈， 0.12.12 已修复，已提审。

**Comment by timelic** [comment]
非常感谢
