### ISSUE TITLE
[Bug]: 油猴脚本版无法自动使用双语字幕

### ISSUE THREAD

**Issue by QiTianzu** [immersive-translate/immersive-translate#1270]
### 插件版本号 | Version

0.12.12

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

在设置中启用“自动使用双语字幕”，当视频播放的时候，油猴脚本版不会自动显示双语字幕，需要重新开启字幕才会显示，而浏览器扩展版就可以自动显示双语字幕。

### 出现问题的网址 | URL

https://www.youtube.com/watch?v=yD154c2N4no

**Comment by keyboard3** [comment]
我这可以啊，面板中直接启用双语字幕，就自动触发双语字幕了呀。 你录个屏看看

**Comment by QiTianzu** [comment]
> 我这可以啊，面板中直接启用双语字幕，就自动触发双语字幕了呀。 你录个屏看看


https://github.com/immersive-translate/immersive-translate/assets/50047003/74142b1e-00aa-4628-8c4e-c19c9a95351a

**Comment by keyboard3** [comment]
你用的是哪个油猴插件，怎么看着是红色图标？

**Comment by QiTianzu** [comment]
> 你用的是哪个油猴插件，怎么看着是红色图标？

Tampermonkey BETA，稳定版也是同样的情况。

**Comment by QiTianzu** [comment]
先关闭字幕，然后把视频网页关了，再打开视频网页就能自动显示双语字幕了。如果启用“自动使用双语字幕”之前开启了字幕，就会造成无法自动显示双语字幕。
