### ISSUE TITLE
[Bug]: youtube上用不了沉浸式翻譯

### ISSUE THREAD

**Issue by thomasTAT** [immersive-translate/immersive-translate#1272]
### 插件版本号 | Version

0.12.12

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

youtube上用不了沉浸式翻譯，點了沒反應。
![image](https://github.com/immersive-translate/immersive-translate/assets/109513632/e9fa79ec-0fe9-436c-b1f9-ec022dcd4ad8)
![image](https://github.com/immersive-translate/immersive-translate/assets/109513632/4505a3b1-3e9d-40cc-81c2-9bfbd89678d8)

### 出现问题的网址 | URL

https://www.youtube.com/

**Comment by theowenyoung** [comment]
看一下你的目标语言是否是中文？

**Comment by thomasTAT** [comment]
> 看一下你的目标语言是否是中文？

沒事了，找到原因了，沉浸式翻譯會與language reactor 衝突。
