### ISSUE TITLE
[Bug]: 制作双语epub，无法导出

### ISSUE THREAD

**Issue by wonderful259** [immersive-translate/immersive-translate#1275]
### 插件版本号 | Version

0.12.11

### 平台 | Platform

macOS

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

15M的英文epub，翻译完成后，选择导出，一直显示导出中，但是没有导出文件。
本地另外一个3.2M的epub电子书可以正常翻译导出。
文件已上传压缩包
[Blood in the Machine The Origins of t... (Z-Library).epub.zip](https://github.com/immersive-translate/immersive-translate/files/13785539/Blood.in.the.Machine.The.Origins.of.t.Z-Library.epub.zip)
![WX20231228-181437@2x](https://github.com/immersive-translate/immersive-translate/assets/21329339/d03270e6-d484-4e72-8e75-9c1ab7c1c7ea)

### 出现问题的网址 | URL

https://app.immersivetranslate.com/ebook/make/

### 重现步骤 | To Reproduce

1.打开制作双语epub页面
2.上传epub电子书，点击翻译
3.完成后点击导出，失败

**Comment by keyboard3** [comment]
已修复，刷新重试下看
