### ISSUE TITLE
[Bug]: 大段落文章拆分之后拼接的 index 错乱

### ISSUE THREAD

**Issue by xiaotianxt** [immersive-translate/immersive-translate#1276]
### 插件版本号 | Version

0.12.12

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

大段落文本拆分之后（比如拆成 \#n \#n+1 \#n+2），经过 api 请求之后，拼接的相应变成了（\#n+1 \#n+1 \#n+2）

下图解释：请求 \#n 没有拼接在 dom 中；重复出现了两个 \#n+1 请求，和一个 \#n+2 请求。

![image](https://github.com/immersive-translate/immersive-translate/assets/17041194/56c47d7b-ea76-4dfa-a1a9-7a4bbd2302ac)

### 出现问题的网址 | URL

https://www.sciencedirect.com/science/article/pii/S0264275120313226

### 重现步骤 | To Reproduce

使用 GPT-3.5 api，最大文本长度设置 1200，进入上方页面可复现。

### 补充说明 | Additional context

[复现视频链接](https://share.cleanshot.com/RZ472YbVjGM7Fqd4tbJ0)

**Comment by xiaotianxt** [comment]
通过提高最大文本长度临时解决，但这样效果不太好。

[复现视频链接](https://share.cleanshot.com/RZ472YbVjGM7Fqd4tbJ0)

**Comment by theowenyoung** [comment]
感谢反馈，确实有问题， 已在 0.12.13 版本修复，已经提交商店审核了。
