### ISSUE TITLE
[Bug]: 翻译后使用relingo划词注解单个单词后，翻译会消失

### ISSUE THREAD

**Issue by DD5OO** [immersive-translate/immersive-translate#1277]
### 插件版本号 | Version

V0.12.12

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

翻译后，对段落的单词用Relingo扩展划词翻译显示单词注解后 该段落的翻译会消失 需要重新翻译一次（有时多划词注解几个单词才消失 有时注解一个就直接消失）

### 出现问题的网址 | URL

大部分网站都会出现

### 重现步骤 | To Reproduce

1、用快捷键网页翻译
2、对段落某词用relingo注解单词
3、翻译未消失则再注解几个

**Comment by keyboard3** [comment]
他们对原站点结构侵入性太大，甚至把沉浸式的节点都包裹进去了，添加词的时候会把沉浸式的译文节点也删除。沉浸式可以设置什么都不做，但是效果就是你一加单词，沉浸式的译文都被这个插件删除掉了

**Comment by keyboard3** [comment]
1.1.4 已兼容
