### ISSUE TITLE
[Bug]: 翻译文本丢失了元素

### ISSUE THREAD

**Issue by mybruce** [immersive-translate/immersive-translate#1279]
### 插件版本号 | Version

0.12.12

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome, Other

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

这段网页代码，使用插件进行翻译，公式部分丢失了。
```code=html
<p>没有问题</p>
<li><p><span style="white-space: nowrap;"><katex-element displaymode="inline"><span class="katex"><span class="katex-mathml"><math><semantics><mrow><mn>400</mn></mrow><annotation encoding="application/x-tex">400</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height: 0.64444em; vertical-align: 0em;"></span><span class="mord">4</span><span class="mord">0</span><span class="mord">0</span></span></span></span></katex-element></span><span> employees work from home, and</span></p></li>
<p>有问题</p>
<li><p><span style="white-space: nowrap;"><katex-element displaymode="inline"><span class="katex"><span class="katex-mathml"><math><semantics><mrow><mn>100</mn></mrow><annotation encoding="application/x-tex">100</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height: 0.64444em; vertical-align: 0em;"></span><span class="mord">1</span><span class="mord">0</span><span class="mord">0</span></span></span></span></katex-element></span><span> of employees work part-time and work from home.</span></p></li>
```

截图效果：
<img width="489" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/8289693/bb97f457-410b-4b6b-b82e-5dc5394aea2c">
两个框中的数字都是公式，但红框中的数字在翻译中就丢失了。

### 出现问题的网址 | URL

https://brilliant.org/courses/probability-fundamentals/computing-probabilities/practice-conditional-probability-4/2/?from_llp=data-analysis

### 重现步骤 | To Reproduce

将上面的网页代码保存成html文件，使用插件就能复现。

**Comment by keyboard3** [comment]
你提供的例子，我似乎没看出区别
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/bf0fa689-766d-41b9-99da-0653449d3dae)

**Comment by mybruce** [comment]
我测试发现，把openai的模型从3.5换成4就正常了，使用3.5在某些时候会丢失占位符。

<img width="806" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/8289693/402bc56b-aeb6-49ca-a7e7-9e251372846d">

<img width="340" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/8289693/7aa2fa8d-3211-41ba-a7ea-6e29bd44246a">

**Comment by keyboard3** [comment]
是的 openai 有时候就会犯抽, 木有办法 😄
