### ISSUE TITLE
[Bug]: 这个youtube视频字幕似乎无法被翻译

### ISSUE THREAD

**Issue by theowenyoung** [immersive-translate/immersive-translate#1280]
### 插件版本号 | Version

0.12.13

### 平台 | Platform

macOS

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

无法翻译字幕

### 出现问题的网址 | URL

https://www.youtube.com/watch?v=Ep-OnsDieFQ&t=1s

**Comment by keyboard3** [comment]
chrome 可以翻译

**Comment by FattySpring** [comment]
Firefox 也可以翻译
