### ISSUE TITLE
youtube视频字幕翻译不会正确断句，造成翻译质量暴跌

### ISSUE THREAD

**Issue by crysishacker** [immersive-translate/immersive-translate#1281]
### 您希望的更新和改进是什么 | Update or Improve

我是之前那个欢呼沉浸式翻译可以发送全部youtube字幕到google翻译的人
但是现在发现我错了，插件还是把原始字幕的断句（每一行）发送到google，导致断句全错
对于原本做好字幕而不是auto generate cc，表现得比youtube自身自带的中英翻译还要差。
因为youtube自带翻译，对于标点符号是识别出来，把字幕换行消除。用up制作的字幕标点来断句。

举例：https://www.youtube.com/watch?v=_T8cn2J13-4

2:09
to leave Earth entirely.The exact timing of this maneuever is critical to reach a speed
2:14
that can escape Earth's gravitational pull, but also put Orion on a course that will intersect
2:19
the Moon days later.

沉浸式翻译结果：
完全离开地球。这种机动的确切时机对于达到一定速度至关重要

可以逃脱地球的引力，但也使猎户座走上一条将相交的路线

几天后的月亮。
-----------------------
但是如果我把换行符消除呢，在google翻译网页得出结果：

The exact timing of this maneuver is critical to reach a speed that can escape Earth's gravitational pull, but also put Orion on a course that will intersect the Moon days later.
这种机动的精确时机对于达到可以逃脱地球引力的速度至关重要，而且也使猎户座走上几天后与月球相交的路线。

看起来就非常舒服了

----------------------
为什么我要说这个呢？那直接用youtube自己结果不就行了？因为youtube自带翻译“似乎”去掉了换行，正确使用up自己做的字幕的标点符号来断句，但依然很奇怪，所以指望沉浸式翻译解决这个问题

youtube自带中英翻译：
完全离开地球。这种机动的精确时机对于达到

可以逃脱地球引力的速度至关重要，同时也使猎户座走上一条能够

几天后与月球相交。

（非常奇怪，正确的是“几天后与月球相交的路线”）
-------------------
对于auto cc，youtube“似乎”也是把没有标点符号的文字全部送到google translate，并且正确断句了。但是质量依然奇差

**Comment by keyboard3** [comment]
感谢反馈：

本质依赖原始字幕短句翻译，原始字幕没有正确合并句子，很难通过代码正确合并，所谓依赖标点符号这种取巧方式非常不靠谱。想要到达最理想的效果，最好的方式是专门优化过的ai对音频流进行分析短句，或者是人工精修。

我们支持直接使用youtube机翻显示双语字幕，可以去字幕设置页，关闭优先沉浸式翻译选项即可

**Comment by crysishacker** [comment]
> 感谢反馈：
> 
> 本质依赖原始字幕短句翻译，原始字幕没有正确合并句子，很难通过代码正确合并，所谓依赖标点符号这种取巧方式非常不靠谱。想要到达最理想的效果，最好的方式是专门优化过的ai对音频流进行分析短句，或者是人工精修。
> 
> 我们支持直接使用youtube机翻显示双语字幕，可以去字幕设置页，关闭优先沉浸式翻译选项即可

为什么up自己上传的字幕，标点符号不靠谱？
