### ISSUE TITLE
[Bug]: Youtube评论区翻译BUG

### ISSUE THREAD

**Issue by Sinatrade** [immersive-translate/immersive-translate#1283]
### 插件版本号 | Version

0.12.13

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/32747447/6bb245b1-66b6-4db6-b183-09429546d844)

**Comment by keyboard3** [comment]
给个地址

**Comment by Sinatrade** [comment]
> 给个地址

https://www.youtube.com/watch?v=UKSEBn6N0RQ&list=LL&index=26

**Comment by keyboard3** [comment]
我这正常的，感觉你这个似乎有别的插件干扰样式了。你给插件隐身窗口权限，然后在隐身窗口你复现看看
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/90a342bd-e156-4c7b-b08c-c52556cb2aed)

**Comment by theowenyoung** [comment]
无法浮现，暂时关闭哈。有问题可以再回复。
