### ISSUE TITLE
[Bug]: youtube长视频双语字幕不显示

### ISSUE THREAD

**Issue by sumuen** [immersive-translate/immersive-translate#1284]
### 插件版本号 | Version

0.12.13

### 平台 | Platform

Linux

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

版本：0.12.13，翻译服务：openai 在翻译特别长的youtube视频时，比如几十个小时的教程视频，对接gpt的api接口最大线程一直收到请求，好像是要翻译所有的字幕，但是字幕迟迟不出，短时长视频不会有问题

### 出现问题的网址 | URL

https://www.youtube.com/watch?v=gyMwXuJrbJQ&t=1166s

**Comment by FattySpring** [comment]
感谢反馈，这个是符合预期的，目前双语字幕需要翻译完字幕才显示，不建议使用OpenAI 翻译长视频字幕。
