### ISSUE TITLE
iOS 版本沉浸式多指快捷翻译希望支持仅翻译选中段落

### ISSUE THREAD

**Issue by zhatlas** [immersive-translate/immersive-translate#1288]
### 您希望的更新和改进是什么 | Update or Improve

当前快捷翻译即翻译整个网页，浪费 token，能否支持翻译多指选中的段落或者网页元素

**Comment by theowenyoung** [comment]
选中翻译的话，直接调用 系统自带的翻译就好了？

**Comment by zhatlas** [comment]
> 选中翻译的话，直接调用 系统自带的翻译就好了？

这种方法首先得得用光标框选段落，不方便，另外系统方法不准确

**Comment by theowenyoung** [comment]
那也许可以新增一个类似 桌面端的 【鼠标滑过】 的功能，但是可以由多指同时touch 的时候触发 当前段落翻译？

**Comment by zhatlas** [comment]
> 那也许可以新增一个类似 桌面端的 【鼠标滑过】 的功能，但是可以由多指同时touch 的时候触发 当前段落翻译？

我是这个意思，多指触发段落翻译，按需翻译，可用性就很强了

**Comment by zhatlas** [comment]
> 那也许可以新增一个类似 桌面端的 【鼠标滑过】 的功能，但是可以由多指同时touch 的时候触发 当前段落翻译？

当前多指触发的是网页全文翻译，类似桌面端的 alt + a

**Comment by theowenyoung** [comment]
嗯，应该可以，新增一个快捷键（X指同时按），用来在移动端触发 翻译当前段落。

**Comment by FattySpring** [comment]
版本 1.1.6 已支持
