### ISSUE TITLE
Better support for seekingalpha.com

### ISSUE THREAD

**Issue by rambda** [immersive-translate/immersive-translate#1289]
### 您希望的更新和改进是什么 | Update or Improve

[Seeking Alpha](https://www.seekingalpha.com) 是一个专注于美国股票的财经网站。见[百科](https://en.wikipedia.org/wiki/Seeking_Alpha)

该网站的某些样式会被破坏，希望改进。

---

例如该网页中的评分出现了文字超出方框以及文字重叠 https://seekingalpha.com/symbol/NETTF/momentum/performance
![screenshot](https://github.com/immersive-translate/immersive-translate/assets/23667522/f4c542bf-03af-4e1f-aa14-4c2ca55e2259)
另外，原文中 Rating: Not Covered 用`style="display: none;"`隐藏起来了，译文却翻译且显示了。
<img src=https://github.com/immersive-translate/immersive-translate/assets/23667522/61a50547-9f97-4336-a718-ba3447df9ad1 width=50% height=50%>

---

再例如该网页，文字有所溢出。也许应该全部换行，或者更智能的换行。 https://seekingalpha.com/symbol/NVDA/valuation/metrics
<img src=https://github.com/immersive-translate/immersive-translate/assets/23667522/f3c131b0-b80d-4b52-b059-d232c94ba80f width=50% height=50%>
<img src=https://github.com/immersive-translate/immersive-translate/assets/23667522/0eacc048-3969-4521-8a1e-e2b0f6cc2242 width=50% height=50%>

---

再比如，插件忽略了左侧栏。

（虽然这是我希望的行为，但应该不是符合设计预期的。）
<img src=https://github.com/immersive-translate/immersive-translate/assets/23667522/ce7cb1e3-d9af-4dc7-8065-65d0ccf1b565 width=50% height=50%>

### 补充说明 | Additional context

另一种可能的解决方案是，提供一个**可选**的 user rule snippet 预设。开启后能够自动不翻译所有的评级/评分，以及侧栏。

实际上大部分常用网站或许都需要这样的“允许不翻译某些元素的”功能，都需要官方或pull requests似乎太麻烦。如果有类似 greasyfork.org 或者 userstyles.org 这样的允许互相分享的snippet托管处就更好了。当然这属于锦上添花，也许成本高于收益。

---

转念一想。

对于我这样对 css 只有最低限度知识的使用者，也许更需要一个类似于uBlock Origin的元素选择器。就是那种用吸管一吸，就能框选住一个或大或小的css元素，把对应的屏蔽代码加入屏蔽规则中的设计。这之后，往往只要再加几个通配符就能解决问题。

edit: 不熟悉 markdown 格式

**Comment by timelic** [comment]
实际上是有“允许不翻译某些元素的”功能的，https://immersivetranslate.com/docs/advanced/#user-rules

**Comment by theowenyoung** [comment]
![CleanShot 2024-01-04 at 21 18 13@2x](https://github.com/immersive-translate/immersive-translate/assets/62473795/72303c16-f30f-422b-9e0c-a70a2f076bea)

进阶设置里把最新的段落字符，改成 20，可能会比较好适配这个网站。

**Comment by keyboard3** [comment]
侧边栏默认不翻译，这是预期行为。 你这个网站免费用户和付费用户看到的内容应该有所区别，我这边的右侧没有如图所示内容，你可以用沉浸式的分享生成页面快照，发个链接我们看下

**Comment by keyboard3** [comment]
长时间未未回复，暂时关闭此issue
