### ISSUE TITLE
[Bug]: Safari点击+快捷键均没有反应

### ISSUE THREAD

**Issue by Jagerx** [immersive-translate/immersive-translate#1290]
### 插件版本号 | Version

0.12.12

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

老用户，一直正常，最近重装系统后，MAC App Store 重装后突然发现不好用了，原来正常的页面也无翻译了，服务选择Google，Github页面正常，但其他页面大部分毫无反应。设置重制过，浏览器缓存也清空过，系统重启都试过

### 出现问题的网址 | URL

https://katelynsills.com/law/the-curious-case-of-md5/

**Comment by Jagerx** [comment]
贴的网址来自于Buzzing，范例

**Comment by FattySpring** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/25144301/9663ab78-64e5-4e0e-8974-d28376265d6b)
面板截图看下，我这里是正常的

**Comment by keyboard3** [comment]
目标语言设置成日语试试？

**Comment by Jagerx** [comment]
<img width="1248" alt="2024-01-04_21-27-06" src="https://github.com/immersive-translate/immersive-translate/assets/42521386/a407c48a-65e6-4dec-b523-cee94784c22e">
日语正常 = =，重新切换回英语，就还是没有反应

**Comment by keyboard3** [comment]
目标语言再切换成中文呢？ 你切成英语肯定不翻译呀，原文是英语，目标是英语了

**Comment by theowenyoung** [comment]
@Jagerx 你的电脑系统语言设置的是什么？

**Comment by keyboard3** [comment]
将在0.12.4修复

**Comment by Jagerx** [comment]
> @Jagerx 你的电脑系统语言设置的是什么？

中文的

**Comment by Jagerx** [comment]
> 目标语言再切换成中文呢？ 你切成英语肯定不翻译呀，原文是英语，目标是英语了

嗯嗯，来回一通目标语言横跳切换，然后清空Safari缓存，开关插件后，好了... 至少现在试了几个英文网站，都能正常翻译成中文了

**Comment by Jagerx** [comment]
> 将在0.12.4修复

定位问题了啊？棒！
