### ISSUE TITLE
youtube字幕问题（续

### ISSUE THREAD

**Issue by crysishacker** [immersive-translate/immersive-translate#1291]
### 您希望的更新和改进是什么 | Update or Improve

为什么归档之后，为什么那个post我的回复你看不到，没回应了？
1.为什么up自己制作的字幕，标点符号不靠谱？这不就是标点符号的意义吗？？？
2.auto cc 无断句，无标点符号。在google翻译网页版得到结果，断句良好
示例： 
three binary star systems or with each other here with too hot and bright a type stars being stuck in the system as well as for M type red dwarfs altogether though of a six stars put out roughly fifty two point four times more luminosity than that of our Sun
三个双星系统或彼此之间，太热和明亮的a型恒星被困在系统中，以及M型红矮星，尽管六颗恒星的光度大约是太阳的五十二点四倍
结论：
所以我才希望你们能把字幕全部发送到google translate

**Comment by keyboard3** [comment]
翻译完之后 怎么和时间轴对应呢？

**Comment by crysishacker** [comment]
> 翻译完之后 怎么和时间轴对应呢？

我一直以为你是程序员，这是很简单的事情……

**Comment by keyboard3** [comment]
> > 翻译完之后 怎么和时间轴对应呢？
> 
> 我一直以为你是程序员，这是很简单的事情……

这根是不是程序员没关系，就是无法对应....

**Comment by keyboard3** [comment]
> > > > 翻译完之后 怎么和时间轴对应呢？
> > > 
> > > 
> > > 我一直以为你是程序员，这是很简单的事情……
> > 
> > 
> > 这根是不是程序员没关系，就是无法对应....
> 
> 对于youtube auto cc，我也不知道google怎么做，但是就是实现了

合并之后的翻译结果已经和之前的时间轴失去对应关系了，没法处理。只能人工校对或者让ai模型参与时间轴修正，没那么简单的

**Comment by crysishacker** [comment]
> > > > > 翻译完之后 怎么和时间轴对应呢？
> > > > 
> > > > 
> > > > 我一直以为你是程序员，这是很简单的事情……
> > > 
> > > 
> > > 这根是不是程序员没关系，就是无法对应....
> > 
> > 
> > 对于youtube auto cc，我也不知道google怎么做，但是就是实现了
> 
> 合并之后的翻译结果已经和之前的时间轴失去对应关系了，没法处理。只能人工校对或者让ai模型参与时间轴修正，没那么简单的

好吧，听了你前面那个post的建议，我现在在搞whisper，断句非常棒，以后看看怎么对接

**Comment by crysishacker** [comment]
> > > > > 翻译完之后 怎么和时间轴对应呢？
> > > > 
> > > > 
> > > > 我一直以为你是程序员，这是很简单的事情……
> > > 
> > > 
> > > 这根是不是程序员没关系，就是无法对应....
> > 
> > 
> > 对于youtube auto cc，我也不知道google怎么做，但是就是实现了
> 
> 合并之后的翻译结果已经和之前的时间轴失去对应关系了，没法处理。只能人工校对或者让ai模型参与时间轴修正，没那么简单的

对于up自己制作的字幕，时间轴对应就可以做的出来了吧？例如识别句号和逗号，也可以使用更高质量的翻译api而不是google

**Comment by keyboard3** [comment]
> > > > > > 翻译完之后 怎么和时间轴对应呢？
> > > > > 
> > > > > 
> > > > > 我一直以为你是程序员，这是很简单的事情……
> > > > 
> > > > 
> > > > 这根是不是程序员没关系，就是无法对应....
> > > 
> > > 
> > > 对于youtube auto cc，我也不知道google怎么做，但是就是实现了
> > 
> > 
> > 合并之后的翻译结果已经和之前的时间轴失去对应关系了，没法处理。只能人工校对或者让ai模型参与时间轴修正，没那么简单的
> 
> 对于up自己制作的字幕，时间轴对应就可以做的出来了吧？例如识别句号和逗号，也可以使用更高质量的翻译api而不是google

不会以来标点符号作为字幕合并或者拆分的依据。 不能保证原字幕一定有标点，也不能保证翻译服务一定会保留标点。 综合来说标点符号不是一个稳定的判断依据

**Comment by crysishacker** [comment]
> 翻译完之后 怎么和时间轴对应呢？

我找到个免费用colab t4 16g的[whisper-youtube] 项目(https://github.com/ArthurFDLR/whisper-youtube)，嗯……这种东西能对接吗？

**Comment by crysishacker** [comment]
> > > > > > > 翻译完之后 怎么和时间轴对应呢？
> > > > > > 
> > > > > > 
> > > > > > 我一直以为你是程序员，这是很简单的事情……
> > > > > 
> > > > > 
> > > > > 这根是不是程序员没关系，就是无法对应....
> > > > 
> > > > 
> > > > 对于youtube auto cc，我也不知道google怎么做，但是就是实现了
> > > 
> > > 
> > > 合并之后的翻译结果已经和之前的时间轴失去对应关系了，没法处理。只能人工校对或者让ai模型参与时间轴修正，没那么简单的
> > 
> > 
> > 对于up自己制作的字幕，时间轴对应就可以做的出来了吧？例如识别句号和逗号，也可以使用更高质量的翻译api而不是google
> 
> 不会以来标点符号作为字幕合并或者拆分的依据。 不能保证原字幕一定有标点，也不能保证翻译服务一定会保留标点。 综合来说标点符号不是一个稳定的判断依据

那能不能把这个功能做出来，但是默认不开启，然后我自己开启自己对后果负责呢？
whisper的断句实在太棒了，我发现你们的插件有专门翻译srt文件的功能，我把自己whisper产生的srt导入去就能制作双语字幕了。
我尝试了无数款字幕翻译软件，都不能把换行符取消，翻译质量无比o疼

**Comment by crysishacker** [comment]
> > > > > > > 翻译完之后 怎么和时间轴对应呢？
> > > > > > 
> > > > > > 
> > > > > > 我一直以为你是程序员，这是很简单的事情……
> > > > > 
> > > > > 
> > > > > 这根是不是程序员没关系，就是无法对应....
> > > > 
> > > > 
> > > > 对于youtube auto cc，我也不知道google怎么做，但是就是实现了
> > > 
> > > 
> > > 合并之后的翻译结果已经和之前的时间轴失去对应关系了，没法处理。只能人工校对或者让ai模型参与时间轴修正，没那么简单的
> > 
> > 
> > 对于up自己制作的字幕，时间轴对应就可以做的出来了吧？例如识别句号和逗号，也可以使用更高质量的翻译api而不是google
> 
> 不会以来标点符号作为字幕合并或者拆分的依据。 不能保证原字幕一定有标点，也不能保证翻译服务一定会保留标点。 综合来说标点符号不是一个稳定的判断依据

如果你觉得太麻烦，那么能不能告诉我怎么设置whisper让它出现标点符号才换行……虽然不是你该关心的了……

**Comment by keyboard3** [comment]
> > > > > > > > 翻译完之后 怎么和时间轴对应呢？
> > > > > > > 
> > > > > > > 
> > > > > > > 我一直以为你是程序员，这是很简单的事情……
> > > > > > 
> > > > > > 
> > > > > > 这根是不是程序员没关系，就是无法对应....
> > > > > 
> > > > > 
> > > > > 对于youtube auto cc，我也不知道google怎么做，但是就是实现了
> > > > 
> > > > 
> > > > 合并之后的翻译结果已经和之前的时间轴失去对应关系了，没法处理。只能人工校对或者让ai模型参与时间轴修正，没那么简单的
> > > 
> > > 
> > > 对于up自己制作的字幕，时间轴对应就可以做的出来了吧？例如识别句号和逗号，也可以使用更高质量的翻译api而不是google
> > 
> > 
> > 不会以来标点符号作为字幕合并或者拆分的依据。 不能保证原字幕一定有标点，也不能保证翻译服务一定会保留标点。 综合来说标点符号不是一个稳定的判断依据
> 
> 如果你觉得太麻烦，那么能不能告诉我怎么设置whisper让它出现标点符号才换行……虽然不是你该关心的了……

不了解，你可以去研究下

**Comment by crysishacker** [comment]
> > > > > > > > > 翻译完之后 怎么和时间轴对应呢？
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 我一直以为你是程序员，这是很简单的事情……
> > > > > > > 
> > > > > > > 
> > > > > > > 这根是不是程序员没关系，就是无法对应....
> > > > > > 
> > > > > > 
> > > > > > 对于youtube auto cc，我也不知道google怎么做，但是就是实现了
> > > > > 
> > > > > 
> > > > > 合并之后的翻译结果已经和之前的时间轴失去对应关系了，没法处理。只能人工校对或者让ai模型参与时间轴修正，没那么简单的
> > > > 
> > > > 
> > > > 对于up自己制作的字幕，时间轴对应就可以做的出来了吧？例如识别句号和逗号，也可以使用更高质量的翻译api而不是google
> > > 
> > > 
> > > 不会以来标点符号作为字幕合并或者拆分的依据。 不能保证原字幕一定有标点，也不能保证翻译服务一定会保留标点。 综合来说标点符号不是一个稳定的判断依据
> > 
> > 
> > 如果你觉得太麻烦，那么能不能告诉我怎么设置whisper让它出现标点符号才换行……虽然不是你该关心的了……
> 
> 不了解，你可以去研究下

那么上一个reply呢？你怎么看？能够实现吗？

**Comment by keyboard3** [comment]
这类需求太小众，暂不会安排开发精力实现
