### ISSUE TITLE
[Bug]: 输入框增强功能无法将中文“飞船”翻译为英语

### ISSUE THREAD

**Issue by IamMagicSu** [immersive-translate/immersive-translate#1293]
### 插件版本号 | Version

1.1.0

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

【输入框增强】功能无法将中文“飞船”翻译为英语。
例如我输入“飞船”，然后快速敲击三次【空格】，输入框增强功能没反应，我换成太空飞船又行了。
再次换回“飞船”，没反应。
重新开一个浏览器，同样的问题。

### 出现问题的网址 | URL

任何网页

**Comment by theowenyoung** [comment]
确认下版本，是否是 1.1.0， 因为刚好上一个版本有问题，1.1.0 解决了这个问题。

**Comment by IamMagicSu** [comment]
> 确认下版本，是否是 1.1.0， 因为刚好上一个版本有问题，1.1.0 解决了这个问题。

![image](https://github.com/immersive-translate/immersive-translate/assets/143731057/7ae90c66-c4cf-43c0-acc0-e53e3dacf783)

**Comment by theowenyoung** [comment]
我这里是正常的..  也许你再升级看看，最新版现在是 1.1.2了。

![CleanShot 2024-01-07 at 17 05 57@2x](https://github.com/immersive-translate/immersive-translate/assets/62473795/b24b3c80-dfcd-4a4b-a7ff-9fc79836cb2a)

**Comment by IamMagicSu** [comment]
真是奇了怪了，就飞船这一个词不行，其他的都没问题，而且我也升级到了1.1.2版本，甚至升级了浏览器，不过也无所谓了，可能是我个人出现的问题：
![image](https://github.com/immersive-translate/immersive-translate/assets/143731057/170ac526-5039-4154-bd27-deb4e9b7d040)

![image](https://github.com/immersive-translate/immersive-translate/assets/143731057/3e9b1541-d720-4d20-a3cd-a6935f668491)

**Comment by theowenyoung** [comment]
有没有尝试切换翻译服务试试？

**Comment by IamMagicSu** [comment]
我换成openai就可以了，Gemini就不行，看来是Gemini的问题
