### ISSUE TITLE
gemini的api，每秒最大请求数设置成了0.1，仍然会出现Google返回超出quota的报错

### ISSUE THREAD

**Issue by Tiger2Wings** [immersive-translate/immersive-translate#1295]
### 您希望的更新和改进是什么 | Update or Improve

设置Gemini的api每秒最大请求数为0.1，是手动输入的，点击鼠标只能选择整数。但是从转圈的文本来看，应该是没有按照0.1来请求，于是，api被Google暂时停掉，要再等个一段时间才有可能恢复。
请官方找个api测试一下，大概什么参数下，可以避免超出quota的报错。

**Comment by Tiger2Wings** [comment]
这个问题极有可能和本地版本等无关，还是补充一下
immersive-translate版本1.1.1
浏览器Edge版本121

**Comment by theowenyoung** [comment]
页面的loading 和 发出请求无关，只表示我们注意到了这个段落将要被翻译的意思。

刚确认了下，设置为 0.1 是生效的，相当于 10 秒才发送一个请求。

但是 API 被封禁的策略还是未知的，目前而言大多数用户被封禁的原因应该是使用了共享的 IP 被封禁。

谷歌官方的政策上限是 每分钟60次，就次数而言，可能设置为 0.5 是很保险的，ip 最好干净（独自使用）

**Comment by theowenyoung** [comment]
“超出quota的报错” 这个是极少数段落还是整个网页？有没有截图或者网址可以复现？

**Comment by august-xu** [comment]
<img width="899" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/6892564/f94538f9-4666-43e5-b586-369b3f3af021">.
但是在其他网站使用同一个key还能正常访问

**Comment by theowenyoung** [comment]
@august-xu 试试 https://example.immersivetranslate.com/ 页面还会不会有错误。

**Comment by august-xu** [comment]
<img width="1417" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/6892564/584776c0-d76d-412a-a06d-a68ee90f44be">

**Comment by august-xu** [comment]
<img width="753" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/6892564/fa0aa9b2-5cdf-4967-9099-880e5969138a">
这是用别的软件翻译的 就是成功的 😶

**Comment by august-xu** [comment]
![Screenshot_20240115_232823](https://github.com/immersive-translate/immersive-translate/assets/6892564/ef0a8cfb-710d-4129-bc4e-158ab285220b)
nextchat也是好的 感觉只是限制了沉浸式翻译😅😅😅

**Comment by theowenyoung** [comment]
@august-xu 确定是同一个key吗... 设置页测试可以成功嘛？

![CleanShot 2024-01-15 at 23 48 12@2x](https://github.com/immersive-translate/immersive-translate/assets/62473795/8aaad8a3-e4d6-4019-9f33-c06aa73408f6)


要不你加下我 tg： https://t.me/itsowenyoung ，我测试下你的 key?

**Comment by august-xu** [comment]
是同一个 就一个key 已加

**Comment by august-xu** [comment]
测试页也不成功@theowenyoung

**Comment by theowenyoung** [comment]
@august-xu 好像没收到消息，你发个消息？

**Comment by theowenyoung** [comment]
研究了一下，发现区别是 nextchat 用的是 v1beta 的api 地址，然后我将沉浸式翻译里的 Gemini 自定义 api 改成：

`https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key={key}`

就能使用了。（原因未知

**Comment by august-xu** [comment]
是的 昨天也发现了

**Comment by theowenyoung** [comment]
下个版本已默认使用 v1beta

**Comment by flyhigao** [comment]
我的经验是,英语不错的人,可以将翻译的段落的最少字符数从4改成40或者更高,可以大幅减少对api的调用.而同时对于网页的主题内容没有影响.
