### ISSUE TITLE
[Bug]: 译文超链接无法点击

### ISSUE THREAD

**Issue by Lang45** [immersive-translate/immersive-translate#1296]
### 插件版本号 | Version

1.1.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

我是非专业的。某些网站的可点击跳转字词，在开启翻译后变得不可点击跳转。大量出现，刚注册github账号都出现了。必须关闭翻译，点击，再打开翻译，体验出现断层。
![360截图20240107114452067](https://github.com/immersive-translate/immersive-translate/assets/155865802/107bed0b-c817-4590-bead-f53cf2520a3f)
![360截图20240107114509434](https://github.com/immersive-translate/immersive-translate/assets/155865802/4b383822-177a-4c65-bb17-3cedfe697e67)

![360截图20240107113020578](https://github.com/immersive-translate/immersive-translate/assets/155865802/9773fca2-fe74-4382-9462-faa0cc1cec02)
![360截图20240107114422594](https://github.com/immersive-translate/immersive-translate/assets/155865802/b1e85488-4ab3-43e0-b1b8-d2d3d227d3af)

**Comment by Lang45** [comment]
准确来说浏览器是360极速x 浏览器，原版Chrome也有这问题
是在开启 仅显示译文和翻译所有区域的情况下，这两个功能怎么藏在更多里面了？？？
偶，我知道了，你们原来知道这情况啊，藏起来了。我为了复现去设置里找了一通，我去教程里才想起在更多里面。
能不能把“仅显示译文”，这个功能做进设置里啊，给个提示可能会出现这情况也行啊，我靠我找这功能找半天

**Comment by theowenyoung** [comment]
设置里面在 【进阶设置】

**Comment by theowenyoung** [comment]
【翻译所有区域】的设置里面在 【进阶设置】里面。

【仅译文模式】的设置目前确实只在面板里提供，下个版本会在在【进阶设置】里添加该选项。

**Comment by theowenyoung** [comment]
译文的超链接无法点击目前是预期行为哈，查看其他相关问题：

https://github.com/immersive-translate/immersive-translate/issues?q=is%3Aissue+%E8%B6%85%E9%93%BE%E6%8E%A5+is%3Aclosed

**Comment by keyboard3** [comment]
![image](https://github.com/user-attachments/assets/c8225a5d-aa32-4c0a-8c69-4345124ab634)
