### ISSUE TITLE
[Bug]: 页面上部分内容无法翻译

### ISSUE THREAD

**Issue by f3liiix** [immersive-translate/immersive-translate#1297]
### 插件版本号 | Version

1.1.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

例如出现问题的网址，文章正文内容无法翻译（浏览器自带翻译也同样无法翻译），但是其他沉浸式翻译的浏览器插件可以。
猜测可能是正文内容是“后加载”的，而并非直接输出在页面上的，所以可能无法翻译？

### 出现问题的网址 | URL

https://seller-us.tiktok.com/university/essay?knowledge_id=8308896260065025&role=1&course_type=1&from=search&identity=1

### 重现步骤 | To Reproduce

打开网页，直接点击翻译图标

### 补充说明 | Additional context

无

**Comment by keyboard3** [comment]
这是因为tiktok约定了这块正文区域不被翻译，它通过 notranslate class 来约定翻译插件不然以这块区域。我们默认情况下尊重网站的约定。
这个网页已经单独适配允许翻译。刷新下页面再试下

**Comment by masteoo** [comment]
@keyboard3 hello, sorry, can you help me to save this long english pdf into Italian please? App is not working
[Virgi Marriages.pdf](https://github.com/immersive-translate/immersive-translate/files/13854370/Virgi.Marriages.pdf)

**Comment by keyboard3** [comment]
With txt files can be translated ah, you use this html/txt text translation page  https://app.immersivetranslate.com/html/

**Comment by masteoo** [comment]
@keyboard3 thanks for your feedback, how can I save the translated result in a txt, epub or pdf file? I have only tablet. Thanks
