### ISSUE TITLE
[Bug]: 昨天开始pdf翻译不能用了，app.immersivetranslate.com 的响应时间过长

### ISSUE THREAD

**Issue by dfmjndm** [immersive-translate/immersive-translate#1298]
### 插件版本号 | Version

1.1.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

app.immersivetranslate.com 的响应时间过长，翻译界面一直转圈圈

**Comment by theowenyoung** [comment]
是整个网页无法加载吗？还是翻译的过程无法加载？

是不是网络代理问题？

**Comment by dfmjndm** [comment]
> 是整个网页无法加载吗？还是翻译的过程无法加载？
> 
> 是不是网络代理问题？

![image](https://github.com/immersive-translate/immersive-translate/assets/57401901/1abbcc7f-e191-4b9b-9049-e5aa031c38fe)

**Comment by dfmjndm** [comment]
开代理不开代理都加载不出来，之前一直能用

**Comment by theowenyoung** [comment]
看起来你是在翻译本地的 pdf 吗？ 试试手动 上传 pdf 文件呢？

或者翻译在线的pdf： https://www.africau.edu/images/default/sample.pdf

**Comment by dfmjndm** [comment]
> 看起来你是在翻译本地的 pdf 吗？ 试试手动 上传 pdf 文件呢？
> 
> 或者翻译在线的pdf： https://www.africau.edu/images/default/sample.pdf

如果我访问这个在线pdf，显示如下。
![image](https://github.com/immersive-translate/immersive-translate/assets/57401901/5ecab312-463f-43ee-9b4a-49b7484ea341)
再使用插件翻译，依旧是黑屏。
![image](https://github.com/immersive-translate/immersive-translate/assets/57401901/4067b53f-19c7-426d-94ed-12e4dae230f5)

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/a58db06c-dd6f-4c70-b28c-edeaa7491454)
可以正常打开呀

**Comment by keyboard3** [comment]
暂无法复现，暂时关闭这个issue
