### ISSUE TITLE
内容较多的网页会出现明显卡顿

### ISSUE THREAD

**Issue by Andy-AO** [immersive-translate/immersive-translate#13]
在一些内容比较多的页面，打开之后拖动，会有很明显的卡顿情况，这个对使用体验的干扰比较大。

硬件是主流的台式电脑硬件。

不知道这是我的个例还是普遍的情况，这里录了个屏，可以在验证的时候进行对照。

https://user-images.githubusercontent.com/38101170/211752193-c184efc2-3c8d-4385-bc92-f43440c817a3.mp4

# links

- [Cannabidiol - Wikipedia --- 大麻二酚 - 维基百科](https://en.wikipedia.org/wiki/Cannabidiol#Ukraine)

**Comment by Andy-AO** [comment]
![image](https://user-images.githubusercontent.com/38101170/211752374-94117d59-f168-4f3a-9628-86f9cd5b2fd9.png)

**Comment by theowenyoung** [comment]
你似乎是一开始翻译，就把页面滑动到最底部？

因为默认流程是这样的： 开始翻译后，默认先翻译 前 x 个字符，然后才开始翻译你的可视区域。

你试试把进阶设置里的 前X个字符，改为0.

然后再试试看看直接滑动到页面底部。

**Comment by theowenyoung** [comment]
不过有可能你滑动的时候，如果它已经检测到中途滑动过的区域的话，那它也会把检测到的任何区域 从前到后排队翻译。

**Comment by Andy-AO** [comment]
> 你似乎是一开始翻译，就把页面滑动到最底部？
> 
> 因为默认流程是这样的： 开始翻译后，默认先翻译 前 x 个字符，然后才开始翻译你的可视区域。
> 
> 你试试把进阶设置里的 前X个字符，改为0.
> 
> 然后再试试看看直接滑动到页面底部。

这次我的设置是设置为翻译前0个字符，然后我从头开始滑动，问题是依旧出现的。滑动的时候会卡的，整个计算机都卡卡的。

猜测这个可能和 Windows 有关，不知道 Mac OS 是不是类似的。

我个人的简单观察是这个和设置关系不是太大，主要还是和网页内容的多少以及复杂程度有关。对前端了解不深，猜测网页越复杂，对网页进行更改的时候浏览器调整的负担就越重。


https://user-images.githubusercontent.com/38101170/211767812-863b7ef5-fd35-4168-94b7-3f28f7e08300.mp4

**Comment by theowenyoung** [comment]
好吧，这确实似乎和电脑性能有关？我在macos上体验当挺流畅的。 你视频里 loading 图标都不动了，理论上 loading 图标本身只是一个svg，但是你的浏览器似乎都不展示这个loading的动画。

**Comment by Andy-AO** [comment]
> 好吧，这确实似乎和电脑性能有关？我在macos上体验当挺流畅的。 你视频里 loading 图标都不动了，理论上 loading 图标本身只是一个svg，但是你的浏览器似乎都不展示这个loading的动画。

不能确定是操作系统的问题，还是电脑硬件的问题，因为我这边也没法刷个黑苹果。总感觉这个电脑的性能，尤其是单核性能还可以，并没有落后太多。

还有就是这个浏览器是否显示动画，和卡不卡顿，这实际上是个bug，在某些特定的网页会出现这种情况，即使不卡的时候也会出现。维基百科似乎总是出现这种问题，当然我不觉得这影响使用，所以就没有报告。

**Comment by Andy-AO** [comment]
> 好吧，这确实似乎和电脑性能有关？我在macos上体验当挺流畅的。 你视频里 loading 图标都不动了，理论上 loading 图标本身只是一个svg，但是你的浏览器似乎都不展示这个loading的动画。

机器的配置已经发过去了，或许可以去跑分网站对比一下性能。这样就能更好的理解是不是硬件性能的问题。

**Comment by theowenyoung** [comment]
是不是复杂的网页就是出现 loading 动画不转圈？ 我是觉得不转圈可能就是浏览器本身处理变化的时候处理不过来。

**Comment by theowenyoung** [comment]
现阶段只能暂时记下这个问题，后面再慢慢研究下。 最近在添加 pdf 翻译的支持。

**Comment by Andy-AO** [comment]
> 是不是复杂的网页就是出现 loading 动画不转圈？ 我是觉得不转圈可能就是浏览器本身处理变化的时候处理不过来。

复杂指的如果是内容多少的话，那么维基百科随便的简单的页面，没有任何卡顿都会出现动画停转的问题。但是有的网页内容非常多，动画好像仍然存在。所以说动画存在与否似乎和卡顿没有关系。

下面这个网页内容是如此少，但动画仍然是不动的。

[Bug - Wikipedia --- 错误 - 维基百科](https://en.wikipedia.org/wiki/Bug)

**Comment by Andy-AO** [comment]
> 现阶段只能暂时记下这个问题，后面再慢慢研究下。 最近在添加 pdf 翻译的支持。

谢谢，我理解这个问题可能会很复杂！ PDF的支持真的非常重要，辛苦了！

**Comment by Andy-AO** [comment]
> 现阶段只能暂时记下这个问题，后面再慢慢研究下。 最近在添加 pdf 翻译的支持。

我现在要处理PDF，是先用word转换成html，转化效果通常相当好。如果是图片版的话，我会用 ABBYY 输出 html，效果也相当好，虽然目前效果不错，但是整个流程还是麻烦些，如果直接在浏览器中可以看PDF那么要好的多。

**Comment by theowenyoung** [comment]
> > 是不是复杂的网页就是出现 loading 动画不转圈？ 我是觉得不转圈可能就是浏览器本身处理变化的时候处理不过来。
> 
> 复杂指的如果是内容多少的话，那么维基百科随便的简单的页面，没有任何卡顿都会出现动画停转的问题。但是有的网页内容非常多，动画好像仍然存在。所以说动画存在与否似乎和卡顿没有关系。
> 
> 下面这个网页内容是如此少，但动画仍然是不动的。
> 
> [Bug - Wikipedia --- 错误 - 维基百科](https://en.wikipedia.org/wiki/Bug)

好吧，我确认了一下，loading 动画现在并不是用svg实现的，而是用了css 的动画属性。这个性能应该没有svg，我完了换成 svg的loading图标 。

**Comment by theowenyoung** [comment]
> > 现阶段只能暂时记下这个问题，后面再慢慢研究下。 最近在添加 pdf 翻译的支持。
> 
> 我现在要处理PDF，是先用word转换成html，转化效果通常相当好。如果是图片版的话，我会用 ABBYY 输出 html，效果也相当好，虽然目前效果不错，但是整个流程还是麻烦些，如果直接在浏览器中可以看PDF那么要好的多。
> 
> 我知道本扩展是自带类似的功能的，但是那个效果实在一般，因为它没有很好地保留换行和分段的信息。导致结果可读性很差。

对的，pdf现在难点就是分段。 目前市面上的pdf转化 html工具都是把每一个元素用绝对定位的方式呈现，这导致完全丢失了分段的信息。 所以我目前的思路是，分析每一行直接的绝对定位之间的距离，根据距离来决定上下两行是否是同一段落。

目前在基于这个工具的转化来做： https://github.com/mozilla/pdf.js 


看起来word转化的 html 很棒啊，会自带段落信息？

但是扩展可能利用不了word的能力，只能从开源的工具里寻找好用的库来解析。

**Comment by Andy-AO** [comment]
> > > 现阶段只能暂时记下这个问题，后面再慢慢研究下。 最近在添加 pdf 翻译的支持。
> > 
> > 
> > 我现在要处理PDF，是先用word转换成html，转化效果通常相当好。如果是图片版的话，我会用 ABBYY 输出 html，效果也相当好，虽然目前效果不错，但是整个流程还是麻烦些，如果直接在浏览器中可以看PDF那么要好的多。
> > 我知道本扩展是自带类似的功能的，但是那个效果实在一般，因为它没有很好地保留换行和分段的信息。导致结果可读性很差。
> 
> 对的，pdf现在难点就是分段。 目前市面上的pdf转化 html工具都是把每一个元素用绝对定位的方式呈现，这导致完全丢失了分段的信息。 所以我目前的思路是，分析每一行直接的绝对定位之间的距离，根据距离来决定上下两行是否是同一段落。
> 
> 目前在基于这个工具的转化来做： https://github.com/mozilla/pdf.js
> 
> 看起来word转化的 html 很棒啊，会自带段落信息？
> 
> 但是扩展可能利用不了word的能力，只能从开源的工具里寻找好用的库来解析。

你要是感兴趣 MS Word 啥效果，我给你发几个转的，我现在几乎每天都转，文献库有大把这种东西。

因为PDF里面本来没带有这些信息，所以 MS Word 和 ABBYY 可能也是靠程序猜测，不一定每次都猜对，但是能够猜个八九不离十，所以可用性是极高的。感觉如果用上现在的机器学习，应该会好的多，它似乎很擅长做这类事情。是不是有这种可能呢？从网页上扒文章，然后 html 转 pdf，然后获取两种文件，弄个机器学习训练出来。

**Comment by Andy-AO** [comment]
> > > 是不是复杂的网页就是出现 loading 动画不转圈？ 我是觉得不转圈可能就是浏览器本身处理变化的时候处理不过来。
> > 
> > 
> > 复杂指的如果是内容多少的话，那么维基百科随便的简单的页面，没有任何卡顿都会出现动画停转的问题。但是有的网页内容非常多，动画好像仍然存在。所以说动画存在与否似乎和卡顿没有关系。
> > 下面这个网页内容是如此少，但动画仍然是不动的。
> > [Bug - Wikipedia --- 错误 - 维基百科](https://en.wikipedia.org/wiki/Bug)
> 
> 有空试试最新版本，修复了一下loading ，试试看这个简单页面的loading 正常不～ 谢谢

loading 仍然是不正常的，但在别的页面上就正常，比如说谷歌搜索的页面

# 正常页面
[123 - Google Search --- 123 - 谷歌搜索](https://www.google.com.hk/search?q=123)
# 异常页面
[123 - Wikipedia --- 123 - 维基百科](https://en.wikipedia.org/wiki/123)

**Comment by theowenyoung** [comment]
> > > > 现阶段只能暂时记下这个问题，后面再慢慢研究下。 最近在添加 pdf 翻译的支持。
> > > 
> > > 
> > > 我现在要处理PDF，是先用word转换成html，转化效果通常相当好。如果是图片版的话，我会用 ABBYY 输出 html，效果也相当好，虽然目前效果不错，但是整个流程还是麻烦些，如果直接在浏览器中可以看PDF那么要好的多。
> > > 我知道本扩展是自带类似的功能的，但是那个效果实在一般，因为它没有很好地保留换行和分段的信息。导致结果可读性很差。
> > 
> > 
> > 对的，pdf现在难点就是分段。 目前市面上的pdf转化 html工具都是把每一个元素用绝对定位的方式呈现，这导致完全丢失了分段的信息。 所以我目前的思路是，分析每一行直接的绝对定位之间的距离，根据距离来决定上下两行是否是同一段落。
> > 目前在基于这个工具的转化来做： https://github.com/mozilla/pdf.js
> > 看起来word转化的 html 很棒啊，会自带段落信息？
> > 但是扩展可能利用不了word的能力，只能从开源的工具里寻找好用的库来解析。
> 
> 你要是感兴趣 MS Word 啥效果，我给你发几个转的，我现在几乎每天都转，文献库有大把这种东西。
> 
> 因为PDF里面本来没带有这些信息，所以 MS Word 和 ABBYY 可能也是靠程序猜测，不一定每次都猜对，但是能够猜个八九不离十，所以可用性是极高的。感觉如果用上现在的机器学习，应该会好的多，它似乎很擅长做这类事情。是不是有这种可能呢？从网页上扒文章，然后 html 转 pdf，然后获取两种文件，弄个机器学习训练出来。

可以呀，贴一下呗～ 贴2个应该就行了～

机器学习好高端，我没搞过...

**Comment by theowenyoung** [comment]
> > > > 是不是复杂的网页就是出现 loading 动画不转圈？ 我是觉得不转圈可能就是浏览器本身处理变化的时候处理不过来。
> > > 
> > > 
> > > 复杂指的如果是内容多少的话，那么维基百科随便的简单的页面，没有任何卡顿都会出现动画停转的问题。但是有的网页内容非常多，动画好像仍然存在。所以说动画存在与否似乎和卡顿没有关系。
> > > 下面这个网页内容是如此少，但动画仍然是不动的。
> > > [Bug - Wikipedia --- 错误 - 维基百科](https://en.wikipedia.org/wiki/Bug)
> > 
> > 
> > 有空试试最新版本，修复了一下loading ，试试看这个简单页面的loading 正常不～ 谢谢
> 
> loading 仍然是不正常的，但在别的页面上就正常，比如说谷歌搜索的页面
> # 正常页面
> 
> [123 - Google Search --- 123 - 谷歌搜索](https://www.google.com.hk/search?q=123)
> # 异常页面
> 
> [123 - Wikipedia --- 123 - 维基百科](https://en.wikipedia.org/wiki/123)

不懂了，我这完全正常..

**Comment by Andy-AO** [comment]
关于loading的问题，可以忽略，因为对使用真的没影响。

**Comment by Andy-AO** [comment]
示例传给你了， MS-Word 2 个，是文字版 PDF，ABBYY 1 个，图片版 PDF，这两个基本上没有排版错误。翻译用的不是这个插件，因为这个插件我主要用于翻译在线内容，这个不影响展示 pdf 转 html 的效果。

总是上传失败，原因不明，用度盘发了，很小，下载不费时间

![image](https://user-images.githubusercontent.com/38101170/211958041-a37bbd30-6f7c-4cd2-8d01-7b48075ab526.png)


链接: https://pan.baidu.com/s/1V8Uuc00YA_gFj35-Zng8nQ?pwd=1111 提取码: 1111 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by Andy-AO** [comment]
Loading动画卡死的问题已经解决了，不知道从什么时候开始突然就好了。维基百科该卡还是卡，这进一步说明了loading动画的问题和卡顿的问题是两个问题。

**Comment by theowenyoung** [comment]
我有一个优化的方向，就是目前扩展对dom结构标记了很多东西，但是这些标记可以转移到 js 的 element 对象里， 我估计这个优化应该可以解决一些问题。

**Comment by Andy-AO** [comment]
> 我有一个优化的方向，就是目前扩展对dom结构标记了很多东西，但是这些标记可以转移到 js 的 element 对象里， 我估计这个优化应该可以解决一些问题。

哦，原来是这样，那说不定可以提高性能啊。

据说操作这个dom会导致性能不太好，所以有的会用虚拟dom缓存请求，能不改就不改，能一起改就一起改。我不太懂前端啊，但是我大概了解了一下有这种想法。

**Comment by theowenyoung** [comment]
好的，我试一下。

**Comment by theowenyoung** [comment]
最新版已优化我上面说的这个。试试看有没有好转..

**Comment by Andy-AO** [comment]
> 最新版已优化我上面说的这个。试试看有没有好转..

没有好转

还有就是，下载了个软件，能客观地检测是否影响「系统响应性」，的确发现响应性被影响，关闭之后影响结束，这个和感受一致。虽然软件自动调低了进程的优先级，问题仍然没有得到太大改善，还是影响系统。

![image](https://user-images.githubusercontent.com/38101170/212224603-596acc3b-6b4f-4e87-8144-07293d7a1e93.png)

**Comment by theowenyoung** [comment]
好吧.. 那我暂时没想到有什么可以明显优化的点了..

要不试试Firefox？不知道会不会好点...

**Comment by Andy-AO** [comment]
> 好吧.. 那我暂时没想到有什么可以明显优化的点了..
> 
> 要不试试Firefox？不知道会不会好点...

从性能的图上来看，就是一个核直接被接近占满了，但别的核还好好的。然后内存非常充足。应该资源很够啊，不知道为什么系统会卡，这个不了解，windows不清楚，所以怀疑是windows的问题，可能这个软件在windows上优化有问题，不过还需要在别的windows电脑上复现才可以。

![image](https://user-images.githubusercontent.com/38101170/212225220-883d203f-6a66-4bae-9bdc-0987ff23ecc8.png)

我这儿就试试firefox，看看这个和chromium有没有关系

**Comment by Andy-AO** [comment]
> 好吧.. 那我暂时没想到有什么可以明显优化的点了..
> 
> 要不试试Firefox？不知道会不会好点...

经过测试发现firefox上没有这个问题。看来问题和chromium有很大关系，如果你在Mac OS上测试的chromium也没问题，那么我猜测可能是windows+chromium这个平台组合会出问题。

唉，chromium 上有很多插件已经用惯了，真不知道换个平台还能不能找到

**Comment by theowenyoung** [comment]
本身这个插件做的事情是挺重的，但是我不知道为什么两个浏览器会有区别。

**Comment by Andy-AO** [comment]
> 本身这个插件做的事情是挺重的，但是我不知道为什么两个浏览器会有区别。

做平台兼容就是挺烦心的，据说现在已经好多了，之前的时候更麻烦，哈哈

**Comment by Andy-AO** [comment]
> 本身这个插件做的事情是挺重的，但是我不知道为什么两个浏览器会有区别。

真羡慕你能做这些事情，做得非常好！我的话因为个人原因干不了这些事情，看着你干的话就觉得很爽。谢谢。

如果遇到了困难，那么的确当时感到挺沮丧的，但是突破的话带来的那种喜悦和成就，也是一路速通，毫无压力，不能比的。

至于刁钻的话，换做我的话，会认为是个挑战，在公司里好像有个专门的职位叫测试吧，应该就是提供这样的挑战。毕竟有时候没有目标实际上是进步最大的问题。

软件的稳定性和兼容性感觉是软件的现实，它比理想，也就是那个功能，更能决定成败。这样的问题越早解决越好，软件越大解决起来可能越麻烦。

希望你活越来越好，加油。

O(∩_∩)O~

**Comment by theowenyoung** [comment]
谢谢！你好像看我的推！

当时解决谷歌还有维基百科各种奇怪的公式问题时，确实很有挫败感。怀疑自己的技术路线到底对不对，因为我想要更好一点的体验，让纯文本翻译可以识别一些常见的网页元素，并且在翻译之后能重新组合起来。所以我选择解析网页中每一个段落里的任何元素，然后分析和重新组合。其他同类产品一般会选择更简单的方式，就是利用`innerText` 提取每一个段落里的文本。亦或是利用强大的网页翻译API去实现。

但是最终问题解决之后，真的很神清气爽。并且对自己的技术路线选择又充满了信心。

你提的问题都非常重要和细致，普通用户遇到问题也很少会提一个很详细的问题，并且一直持续跟进和反馈。我很感谢你的问题！遇到问题，请继续慷慨的提出来！谢谢！

**Comment by theowenyoung** [comment]
是的，我确实在解决这些“刁钻” 的问题中学到了很多底层的知识和API，我用“刁钻”这个词 没有贬义的意思！

**Comment by garywill** [comment]
版本 0.2.28 on Firefox
类似问题，页面 https://ffmpeg.org/ffmpeg-filters.html
已将“前多少个字符无需等待滚动到可视区域，直接翻译？”设置为0

点翻译后，十几秒没有什么反应，
然后稍滚动一下，浏览器提示“Immersive Translate正在使Firefox变慢”
然后再等1分钟后，整个Firefox卡住半分钟
然后译文开始出现

**Comment by theowenyoung** [comment]
这个感觉没什么好办法，这个网页内容非常之多，只能等待全部分析完毕才能展示译文..

**Comment by garywill** [comment]
嗯。。分析需要时间也只能是等待了。不过就体验来说，也有可以改进的两点地方：
1. 加一个指示，让用户知道正在分析，不至于认为卡死了
2. 分析过程加点`await sleep(1)`或"wait for next tick"之类的调用，目的是为了在漫长的分析过程中，让页面原本的功能还可以使用

以上是个人的建议。扩展挺好用的，感谢作者的付出

**Comment by theowenyoung** [comment]
恩 我想想办法，因为分析的操作全部都在UI主线程内进行，next tick应该不管用，本身过程中也有很多异步操作

**Comment by StarDuster** [comment]
遇到了类似情况，当页面很长、元素较多时（如 https://matplotlib.org/stable/api/figure_api.html），使用 OpenAI 翻译，参数全默认，chrome和系统UI会直接卡到失去响应，但是其实没有观察到CPU占满或者较高的中断的情况，
![image](https://github.com/immersive-translate/immersive-translate/assets/7328584/e6cdb587-b6f0-413e-aeb0-c953ed3502c2)

已将“前多少个字符无需等待滚动到可视区域”设置为0，有所改善但是不多，还是会把整个系统都卡死至少一分钟，发现类似问题一般都出现在这类文本较多但是每段都很少的技术文档中，也许可以通过一些判断优化一下体验，减少线程数量或者更加精确的判断用户浏览的区域只处理这一小部分，网页可以不立即显示翻译但是把浏览器乃至系统都卡死会让干点别的等它翻译都做不到了（这个问题在 OpenAI 翻译感觉明显很多，可能因为 API 返回慢）

**Comment by enximi** [comment]
翻译 https://w3c.github.io/uievents-key/ 的时候遇到了类似的情况。按下alt+a之后，鼠标移动卡顿，alt+tab窗口切换卡顿。

处理器	AMD Ryzen 5 5600 6-Core Processor                 3.50 GHz
机带 RAM	48.0 GB

版本	Windows 11 专业版
版本	22H2
安装日期	‎2023/‎7/‎22
操作系统版本	22621.2428
体验	Windows Feature Experience Pack 1000.22674.1000.0

**Comment by BetterWorld-Liuser** [comment]
因为没有源码，所以没法Debug，希望把所有翻译任务都放在异步队列里，推测是网络链接卡死了主线程。

**Comment by Andy-AO** [comment]
> 因为没有源码，所以没法Debug，希望把所有翻译任务都放在异步队列里，推测是网络链接卡死了主线程。

在我的机器上，这个问题在Firefox上很轻，同样的网页，Firefox不会让Windows响应性严重劣化，但Chrome/Edge会卡Windows系统，让别的任务都没办法进行，与此同时CPU占用率却很低。

**Comment by zhp2333** [comment]
应该是chrome的调度问题。

在win11上遇到了同样的问题，在看英文论文时，网页较为复杂，在firefox中使用并不会卡顿，在chrome内核的vivaldi、opera、googlechrome浏览器中，都会卡死，导致浏览器无响应。都是在隐身模式中使用，排除了其他拓展的影响。卡顿时同时观察到，把CPU一个核心拉爆了。

![image](https://github.com/immersive-translate/immersive-translate/assets/84528398/bd848b03-247e-4b59-8ea4-8eeadf738233)

**Comment by zhp2333** [comment]
在firefox中，翻译过程中，负载均匀。
![image](https://github.com/immersive-translate/immersive-translate/assets/84528398/4bbe7969-6442-442f-8aaa-331beebf97a8)

**Comment by AreChen** [comment]
同样在看各种wiki时整个系统陷入卡顿状态,有没有一种可能性时13代的intel cpu的锅

**Comment by keyboard3** [comment]
> 同样在看各种wiki时整个系统陷入卡顿状态,有没有一种可能性时13代的intel cpu的锅

1.5.6 已经针对性做了性能优化，我们这边做过性能监控，卡顿已经处理了。但是某些性能特别差的电脑上仍有卡顿，身边没有这么老的电脑，不太好做检查。你如果仍遇到卡顿建议鼠标悬停翻译
