### ISSUE TITLE
添加忽略翻译的选择器的功能

### ISSUE THREAD

**Issue by benjaminyin01** [immersive-translate/immersive-translate#130]
firefox上用了一下这个插件，别的方面还不错，但是翻译代码示例的时候不好，不如直接不翻译。
能不能添加一个功能，把&lt;code&gt;&lt;/code&gt; &lt;pre&gt;&lt;/pre&gt;等标签里的内容不翻译。
<img width="807" alt="Screen Shot 2023-02-13 at 10 25 26 AM" src="https://user-images.githubusercontent.com/94730407/218356668-7653c962-bf9c-4555-a77e-fbaccf68c668.png">

**Comment by theowenyoung** [comment]
现在就是忽略的。

可能这个网址里没有用pre code标签吧？

发一下网址？

**Comment by benjaminyin01** [comment]
> 现在就是忽略的。
> 
> 可能这个网址里没有用pre code标签吧？
> 
> 发一下网址？

https://www.php.net/manual/en/language.basic-syntax.phptags.php

**Comment by benjaminyin01** [comment]
发现一个现象，点工具栏上的 翻译(alt+a) 按钮，不会翻译代码，但是在右键菜单点翻译，就会连代码一起翻译

**Comment by theowenyoung** [comment]
确认。 本地已修复，下个版本发布～

**Comment by theowenyoung** [comment]
新版已经发布了，商店版还在审核～

暂时关掉这个问题，有问题再打开。
