### ISSUE TITLE
给设置页的textarea设置等宽字体

### ISSUE THREAD

**Issue by timelic** [immersive-translate/immersive-translate#1300]
### 您希望的更新和改进是什么 | Update or Improve

现在的字体在调节设置时候看得很头疼，也不利于编辑。

建议css使用Menlo，Courier New，monospace这些字体。

另外字号如果小一点会更好。

**Comment by theowenyoung** [comment]
感谢建议，下个版本支持。

**Comment by theowenyoung** [comment]
已支持～
