### ISSUE TITLE
[Bug]: 译文重复翻译

### ISSUE THREAD

**Issue by cancundeyingzi** [immersive-translate/immersive-translate#1303]
### 插件版本号 | Version

1.1.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/73635883/c727aa9f-a480-4e3b-990c-f7d4af0171b4)
按两次悬停翻译,似乎是低概率出现

### 出现问题的网址 | URL

https://dash.cloudflare.com/

### 重现步骤 | To Reproduce

按两次悬停翻译

**Comment by keyboard3** [comment]
没能复现，能录个完整的操作视频吗

**Comment by keyboard3** [comment]
暂时关闭哈，如有新的发现可以重开

**Comment by keyboard3** [comment]
暂时关闭哈，如有新的发现可以重开
