### ISSUE TITLE
[Bug]: 最新版本双语模式失效？

### ISSUE THREAD

**Issue by refwww** [immersive-translate/immersive-translate#1305]
### 插件版本号 | Version

1.1.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

更新到了最新版本以后发现不管怎么设置都无法显示双语模式
![20240109155921](https://github.com/immersive-translate/immersive-translate/assets/5498798/b7b70822-c98e-4d5c-adca-f56900220673)
![20240109155939](https://github.com/immersive-translate/immersive-translate/assets/5498798/af28e93f-749f-4dd7-acb0-0d4256e6c5d1)

### 出现问题的网址 | URL

https://wiki.hyronic.dev/

**Comment by theowenyoung** [comment]
点击面板里的【更多】，【切换为双语翻译】不行吗？ 不行的话，也许可以通过在 【设置】页面，重置下设置

**Comment by refwww** [comment]
> 点击面板里的【更多】，【切换为双语翻译】不行吗？ 不行的话，也许可以通过在 【设置】页面，重置下设置

解决了。
在设置里找半天没找到这个选项，原来是在小图标的面板里
