### ISSUE TITLE
[Bug]: edge无法展开插件页面

### ISSUE THREAD

**Issue by thekingofall** [immersive-translate/immersive-translate#1306]
### 插件版本号 | Version

1.1.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/66683082/b5a2bd0e-22b2-4038-af66-2b8d2e1343bb)
edge浏览器最近总是显示空白，没有办法弹出全部

### 出现问题的网址 | URL

所有

**Comment by keyboard3** [comment]
出现这个现象之后，是一直不正常，还是偶尔不正常？

**Comment by thekingofall** [comment]
> 出现这个现象之后，是一直不正常，还是偶尔不正常？

是一直不正常，不知道出现了什么原因

**Comment by thekingofall** [comment]
我反复重装，然后重启电脑也没有改善，换成chrome倒是可以

**Comment by thekingofall** [comment]
我解决了，把语言切换为简体中文就可以了

**Comment by keyboard3** [comment]
> 我解决了，把语言切换为简体中文就可以了

咋切换语言的？ 不是打不开吗

**Comment by keyboard3** [comment]
之前用的是啥语言出错的？修改的是浏览器语言吗

**Comment by thekingofall** [comment]
> 之前用的是啥语言出错的？修改的是浏览器语言吗

哦是的，我之前测试将edge浏览器语言改为繁体中文，现在改为了简体中文就可以了
