### ISSUE TITLE
对不同的网站使用不同的翻译模型（手动切换，或设置列表）

### ISSUE THREAD

**Issue by wanzhiyu** [immersive-translate/immersive-translate#1307]
### 您希望的更新和改进是什么 | Update or Improve

我是一位新用户，非常感谢开发组所创建的这个应用，大大提升了阅读效率。
有一个关于选择翻译模型的建议。
例如，我在一些新闻类的网站或视频中，只需要使用GPT 3.5或者谷歌翻译就足以获取信息，但是在一些学术类的网站和视频中，就需要使用GPT-4 模型来获得最准确的信息。
如果允许用户创建多个“翻译接口”，每一个“翻译接口”支持一种配置的翻译模型（例如GPT3.5，或者GPT4），用户可以通过悬浮窗自行选择当前网站所调用的“翻译接口”；或者定义一个列表，列表中的键值对定义了不同网站所调用的“翻译接口”。这样就可以实现上述目标。
谢谢！

### 补充说明 | Additional context

不同“翻译接口”所消耗的价格差异较大，GPT 4比GPT 3.5甚至贵出超过10倍，这样的改进有助于降低成本的同时，尽可能提升体验。

**Comment by theowenyoung** [comment]
这个问题可以通过新增一个 GPT-4 的快捷键解决吗？

目前是单独为OpenAI翻译服务指定快捷键，但是 openai 模型这个现在还没有可以区分的快捷键。

**Comment by wanzhiyu** [comment]
快捷键 可能不如 设置列表 的方式直观，大语言模型的竞品逐渐增多，为每一种语言模型都设置一个快捷键是不够用的，也记不住。如果采用 设置列表 的方式，对于不同的网站可以自行选择使用不同的翻译接口，这有助于降低成本。例如，默认的基本设置可以使用GPT 3.5，但是用户可以自行指定部分网站使用他们喜欢的模型。

**Comment by theowenyoung** [comment]
所以对你来说，实际上是有某几个固定的网站，你想自动使用 openai gpt4 来翻译的是吗？

不知道你大概有多少网站是想添加进去的，添加自定义网站实际上交互上也挺挑战的。

**Comment by wanzhiyu** [comment]
是的，想自动使用 openai gpt4 来翻译一些固定网站。

在交互上，不知道这样的方式能否实现？（请原谅我画得不美观，但是不知道是否可以采用这样的交互方式）
![image](https://github.com/immersive-translate/immersive-translate/assets/18503895/53b6791a-c81d-4c56-ab46-c9623ab4245a)

或者可以使用代码的方式，在开发者工具中，定义多个翻译接口，并且对不同网站采用不同的翻译接口。

**Comment by theowenyoung** [comment]
嗯，可能是类似的这样的。我先把这个加一个 未来事项 的label， 应该会支持，但是可能要一点时间。

**Comment by dxvgef** [comment]
我觉得针对不同网站使用不同的翻译目标语言更有用吧？

**Comment by flamintune** [comment]
目前可以通过这种方式来对不同网站设置不同翻译服务，详细参考这里的文档https://immersivetranslate.com/docs/advanced/#%E5%AE%9E%E7%94%A8%E5%B0%8F%E6%8A%80%E5%B7%A7

**Comment by dxvgef** [comment]
> 目前可以通过这种方式来对不同网站设置不同翻译服务，详细参考这里的文档https://immersivetranslate.com/docs/advanced/#%E5%AE%9E%E7%94%A8%E5%B0%8F%E6%8A%80%E5%B7%A7

好像只能配置不同网站用不同的翻译引擎，但不能配置不同网站翻译成不同语言吧？

**Comment by flamintune** [comment]
> > 目前可以通过这种方式来对不同网站设置不同翻译服务，详细参考这里的文档https://immersivetranslate.com/docs/advanced/#%E5%AE%9E%E7%94%A8%E5%B0%8F%E6%8A%80%E5%B7%A7
> 
> 好像只能配置不同网站用不同的翻译引擎，但不能配置不同网站翻译成不同语言吧？

是的，暂时还不支持的
