### ISSUE TITLE
Ctrl悬浮翻译与Ctrl+C复制存在冲突

### ISSUE THREAD

**Issue by cesaryuan** [immersive-translate/immersive-translate#1308]
### 您希望的更新和改进是什么 | Update or Improve

当且仅当Ctrl抬起或按下的时候才触发翻译，比如在Ctrl keyup的时候触发翻译，并检测是否有其他键按下

### 补充说明 | Additional context

现在是Ctrl keydown的时候就触发翻译，容易和Ctrl+C复制文本发生冲突，如果改成当且仅当Ctrl抬起时才触发翻译的话体验会好很多

Related: #892

**Comment by theowenyoung** [comment]
keyup 的话，可能无法处理按住的时候，持续翻译当前段落。

目前似乎是设置了 150 毫秒的 延迟检测，如果在 150毫秒内按下了 ctrl+c 的话，就不会触发翻译。

**Comment by cesaryuan** [comment]
> 目前似乎是设置了 150 毫秒的 延迟检测

嗯，我测试了下确实按得快一点的话就不会触发翻译，但是我按C的速度习惯慢一点了哈哈哈

> 持续翻译当前段落。

什么情况下需要持续翻译段落呢？段落不是翻译一次就够了嘛，可能有一些场景我不知道😂

**Comment by theowenyoung** [comment]
> 什么情况下需要持续翻译段落呢？段落不是翻译一次就够了嘛，可能有一些场景我不知道😂

连续两段翻译呀～

**Comment by cesaryuan** [comment]
> 连续两段翻译呀～

测试了下好像实现不了连续两段翻译😂
![recording](https://github.com/immersive-translate/immersive-translate/assets/35998162/03051f85-47b4-496a-858d-b93b20ecdcfe)

**Comment by cesaryuan** [comment]
> 连续两段翻译呀～

感觉在没有实现这个功能的情况下还是在keyup的时候触发翻译比较好，我这边误触几率有点高了😂

**Comment by theowenyoung** [comment]
> 测试了下好像实现不了连续两段翻译😂

我这里测试是可以的，但是似乎偶尔会不灵敏，我再研究下。

> 感觉在没有实现这个功能的情况下还是在keyup的时候触发翻译比较好，我这边误触几率有点高了😂

keyup的话，体验会挺差的，用户会发现按下没有效果，所以可能解决的方向是如何更加准确的区分 Ctrl 和 Ctrl + C，这个我再研究一下

**Comment by theowenyoung** [comment]
好像最好的方法区分 Ctrl 和 Ctrl + C 就是用超时来判断..

下个版本从 150ms 改成 400ms，这个值你完了再试试吧..
