### ISSUE TITLE
[Bug]: 维基百科（wikipedia）翻译，首段错位，被移动到图框中

### ISSUE THREAD

**Issue by wanzhiyu** [immersive-translate/immersive-translate#1309]
### 插件版本号 | Version

v1.1.3

### 请描述这个Bug | Describe the bug

如下图所示，本来应该在第一段的翻译被移动到了右侧图框之中。

<img width="1122" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/18503895/89800844-0a9c-41ae-add9-c48d9f2921ef">

### 出现问题的网址 | URL

https://en.wikipedia.org/wiki/Electronic_band_structure

### 重现步骤 | To Reproduce

设置了en.wikipedia.org的“自动翻译”，采用了openai的api进行翻译。并且这一行为似乎发生在同时翻译多个wikipedia页面时发生，但是我多次尝试也无法确定是否因为这一行为触发。

### 补充说明 | Additional context

出现问题的页面源代码：
[wiki.html.txt](https://github.com/immersive-translate/immersive-translate/files/13911287/wiki.html.txt)

**Comment by wanzhiyu** [comment]
在沉浸式翻译的插件“关于”中，删除缓存，重启浏览器，新建标签页，可以解决，仅刷新同一页面没用。
之后如果有人发现这一问题，可以用这个方法临时解决。我估计就是在同时翻译多个wikipedia页面时会出现这个问题，但是我真的证明不了是不是这个原因。所以就先这用这个方法临时解决，并且注意不要同时打开多个新的Wikipedia页面。

**Comment by keyboard3** [comment]
> 在沉浸式翻译的插件“关于”中，删除缓存，重启浏览器，新建标签页，可以解决，仅刷新同一页面没用。 之后如果有人发现这一问题，可以用这个方法临时解决。我估计就是在同时翻译多个wikipedia页面时会出现这个问题，但是我真的证明不了是不是这个原因。所以就先这用这个方法临时解决，并且注意不要同时打开多个新的Wikipedia页面。

是否修改过openai的配置？ 比如调整过请求段落等？

**Comment by wanzhiyu** [comment]
是的，修改过“每次请求最大段落数”。

**Comment by keyboard3** [comment]
openai 并不会严格遵守提示词约定返回相同数量的译文段落，所以就会导致这种错位现象，段落数量可以自己酌情调整

**Comment by wanzhiyu** [comment]
谢谢，或者我想办法修改prompt
