### ISSUE TITLE
添加对当前网页的缓存清理按钮

### ISSUE THREAD

**Issue by wanzhiyu** [immersive-translate/immersive-translate#1311]
### 您希望的更新和改进是什么 | Update or Improve

对网页的翻译结果是一个非常有用的功能！感谢开发组的创意与实现！

但是，有时候会出现当前页面翻译出错或不满足预期的情况需要重新翻译，此时需要进入“关于”页面，清理全部的翻译缓存。

然而，很多时候只是当前某一个网页需要被清理缓存重新翻译，是否可以在悬浮窗的“更多”中新增一个按钮，“仅清除当前网页的翻译缓存”。

![image](https://github.com/immersive-translate/immersive-translate/assets/18503895/b264637b-f6c5-4738-b7b1-55bc538c2385)

**Comment by theowenyoung** [comment]
(目前的实现里，缓存没有按照网页来归类，而是直接按照段落级别来缓存的，所以其实不好实现..

实际上我感觉这个需求可能比较小众，也许提供一个 强制刷新缓存的快捷键是不是就够了?

**Comment by wanzhiyu** [comment]
理解了，确实是不好实现。如果是这样的话，就不麻烦啦，就现在这样的清除缓存的方式也可以的，谢谢！
