### ISSUE TITLE
youtube的字幕翻译图标建议放在自动播放的左边

### ISSUE THREAD

**Issue by yahuudang** [immersive-translate/immersive-translate#1312]
### 您希望的更新和改进是什么 | Update or Improve

现在放的位置，影响了原来的操作习惯，建议放在右边那几个按钮的最左边

### 补充说明 | Additional context

最主要的原因是，最大化按钮比较常用，原本的右下角是可以盲点的。现在容易误操作

**Comment by keyboard3** [comment]
1.1.5 已发在左边了
