### ISSUE TITLE
[Bug]: 这个页面翻译出来内容错位了

### ISSUE THREAD

**Issue by heheda123123** [immersive-translate/immersive-translate#1313]
### 插件版本号 | Version

1.1.3

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

https://lore.kernel.org/lkml/3465e0c6-f5b2-4c42-95eb-29361481f805@zytor.com/
![image](https://github.com/immersive-translate/immersive-translate/assets/97490782/4fa863b9-a4fe-45e3-a367-58ee766ea360)

**Comment by theowenyoung** [comment]
这是预期行为，因为他是纯文本页面，硬换行的，插件本身没法还原这个行为。
