### ISSUE TITLE
[Bug]: 插件引起Udemy时间戳缩略图失效

### ISSUE THREAD

**Issue by wanzhiyu** [immersive-translate/immersive-translate#1314]
### 插件版本号 | Version

v1.1.4

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

如图，当未启用沉浸式翻译插件时，鼠标在进度条上会显示缩略图：
![image](https://github.com/immersive-translate/immersive-translate/assets/18503895/316ab3c2-08f2-4748-b0cd-a5f01318a63e)

当启用沉浸式翻译插件时，鼠标在进度条上显示一根横线，甚至在已经关闭字幕的前提下，依然不显示缩略图而是显示横线：
![image](https://github.com/immersive-translate/immersive-translate/assets/18503895/4488797e-3bb0-4a93-8251-3cb30c7e8c13)

### 出现问题的网址 | URL

https://www.udemy.com/

### 重现步骤 | To Reproduce

任何一个Udemy网页视频都存在此问题。

**Comment by FattySpring** [comment]
已修复

**Comment by wanzhiyu** [comment]
谢谢！
