### ISSUE TITLE
[Bug]: Gemini 自定义API接口地址时, URL渲染出错 "/models/%7Bmodel%7D:generateContent"

### ISSUE THREAD

**Issue by ekayxu** [immersive-translate/immersive-translate#1318]
### 插件版本号 | Version

1.1.4

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

配置自定义 API 接口地址：http://custom_url/v1beta/models/{model}:generateContent?key={key}
实际渲染成 http://custom_url/v1beta/models/%7Bmodel%7D:generateContent?key=xx

**Comment by keyboard3** [comment]
给个完整的地址。 或者你直接写死模型 http://custom_url/v1beta/models/gemini-pro:generateContent?key={key}

**Comment by ekayxu** [comment]
写死模型是可以的
