### ISSUE TITLE
[Bug]: Some elements are not detected to be translated

### ISSUE THREAD

**Issue by vanbang9710** [immersive-translate/immersive-translate#1319]
### 插件版本号 | Version

1.1.4

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

The top bar is not translated ![|10pct](https://i.imgur.com/qmAuI4a.png)

### 出现问题的网址 | URL

https://tl.rulate.ru/book/29295/761700/ready_new

### 重现步骤 | To Reproduce

- Go to the URL
- Click Translate

### 补充说明 | Additional context

Built-in translating service in Edge can handle the top bar ![|10pct](https://i.imgur.com/KV5xYPx.png)

**Comment by keyboard3** [comment]
You can use mouse hover to translate the above part
<img width="330" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/13177744/b10b3f80-d637-4d65-b803-90d6070a1b91">
