### ISSUE TITLE
版本升级后部分技术文档翻译异常

### ISSUE THREAD

**Issue by danielesk** [immersive-translate/immersive-translate#132]
当前版本v0.2.57
原文地址：https://doc.rust-lang.org/stable/core/cell/index.html
![image](https://user-images.githubusercontent.com/10652829/218373064-9d58e6b3-4559-4013-8715-f5897802ad63.png)

![image](https://user-images.githubusercontent.com/10652829/218366581-c16af78d-4371-422c-8f91-6de189384a12.png)
![image](https://user-images.githubusercontent.com/10652829/218366725-744a9190-c4bf-4e09-b94b-83c36db37a21.png)

**Comment by theowenyoung** [comment]
感谢反馈～

可以了，点击 浏览器扩展图标，更新下最新规则～

**Comment by theowenyoung** [comment]
这个问题应该解决了，升级到最新版本即可～ 有问题再打开，谢谢～
