### ISSUE TITLE
[Bug]: 翻译失败，openai 账户余额不足

### ISSUE THREAD

**Issue by neozhaoliang** [immersive-translate/immersive-translate#1320]
### 插件版本号 | Version

1.1.2

### 平台 | Platform

Linux

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![图片](https://github.com/immersive-translate/immersive-translate/assets/23307174/5af28d77-4c14-44e5-9243-07e7e74b99cd)

### 出现问题的网址 | URL

很多，比如推特

### 重现步骤 | To Reproduce

使用 openai 翻译的时候就会失败

**Comment by keyboard3** [comment]
错误信息已告知，你的openai key的问题，使用openAI 必须绑定信用卡才能用。 https://immersivetranslate.com/docs/services/openai/
