### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Tiger2Wings** [immersive-translate/immersive-translate#1321]
### 插件版本号 | Version

1.1.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

Gemini，在设置页面“[点此测试服务](chrome-extension://amkbmndfnliijdhojkpoglbnaaahippg/options.html#)”
显示：

服务返回错误， 请求参数错误，请检查相应配置。
400: { "error": { "code": 400, "message": "User location is not supported for the API use.", "status": "FAILED_PRECONDITION" } }

**Comment by keyboard3** [comment]
”User location is not supported for the API use.“ 错误表示 你的ip位置不被google允许访问。切换到美国ip
