### ISSUE TITLE
希望能加回之前「添加当前网址通配符到黑名单」的功能

### ISSUE THREAD

**Issue by Zhang-Siyang** [immersive-translate/immersive-translate#1322]
### 您希望的更新和改进是什么 | Update or Improve

 之前在pop出的窗口中有一个下拉框可以选择对当前网站的某一级通配符始终不翻译，现在没有了，导致添加到黑名单里的网址是连协议带子域名的样子。但有一些网站（如公司内部系统）的根域名可能有好几个，所以没有了这个功能添加黑名单就不如之前方便了

例： http://mail.marketing.asia.example.com

### 补充说明 | Additional context

版本 V1.1.4，查看了 Changelog，V1.1.5 不涉及到相关功能，不确定是不是 V0.12.12 影响的这一功能

**Comment by theowenyoung** [comment]
确实在最近的版本中移除了该功能，但是设置页面依然支持通配符。这里移除主要是：

1. 减少普通用户的理解成本
2. 未来这里预计会添加更多其他的快捷方式，比如为该网站指定某个翻译服务等，所以这里减少了一些其他的选项。
