### ISSUE TITLE
[Bug]: Youtube字幕翻譯很大程度拖慢youtube頁面撥放速度，甚至整個chrome運行速度

### ISSUE THREAD

**Issue by aszk1415** [immersive-translate/immersive-translate#1323]
### 插件版本号 | Version

V1.1.4

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

最近更新沉浸式翻譯後出現了youtube字幕的翻譯選項後，整個chrome、及youtube播放都慢到不行，後來把字幕的功能關掉之後才恢復正常

**Comment by zzulpc** [comment]
MAC平台也有类似问题，卸载插件后可恢复，开启后youtube明显卡顿，关闭字幕功能稍有改善。

**Comment by theowenyoung** [comment]
@zzulpc 是视频播放速度卡顿吗？还是整个浏览器卡顿？

**Comment by aszk1415** [comment]
我覺得真的跟adblock有關，字幕功能可能被認為跟adblock類似的插件相似，被youtube故意降速
