### ISSUE TITLE
[Bug]: 使用gemini翻譯時，譯文出現的位置錯誤

### ISSUE THREAD

**Issue by ShawnHsieh2019** [immersive-translate/immersive-translate#1324]
### 插件版本号 | Version

1.1.4

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

使用gemini進行翻譯時，在某些新聞網站，會出現譯文出現的位置並非在原文底下且好幾段譯文被整合成一個段落呈現的問題
（換成Google或Deepl翻譯同樣的文章就不會出現上述的問題）
<img width="1421" alt="SCR-20240116-begn" src="https://github.com/immersive-translate/immersive-translate/assets/156694863/7f08c9bd-2cc9-4344-b9c3-a9dde4df4036">
![IMG_5EE9BDBABCF2-1](https://github.com/immersive-translate/immersive-translate/assets/156694863/c91ebdf0-3d46-4fe4-995f-afba0565d82a)
![Picroll_20240116_002524](https://github.com/immersive-translate/immersive-translate/assets/156694863/25503f1a-98ee-43a9-976b-bb81c3620276)

### 出现问题的网址 | URL

https://www.npr.org/2024/01/13/1224576576/taiwan-ruling-party-wins-election
https://edition.cnn.com/travel/living-abroad-best-countries-for-expats/index.html

### 补充说明 | Additional context
在ios、macos的safari中使用gemini翻譯也會遇到一樣的問題
（CNN的這篇文章只有在ios的safari上使用gemini會出現譯文位置錯誤的問題）

_No response_

**Comment by keyboard3** [comment]
有没有自己改过gemini的配置？

**Comment by ShawnHsieh2019** [comment]
<img width="857" alt="SCR-20240116-pyqd" src="https://github.com/immersive-translate/immersive-translate/assets/156694863/607a69f3-0e12-4961-8a35-e85526e3644d">
只有改過中間的三個數值

**Comment by keyboard3** [comment]
> <img alt="SCR-20240116-pyqd" width="857" src="https://private-user-images.githubusercontent.com/156694863/297010462-607a69f3-0e12-4961-8a35-e85526e3644d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MDA5MDEsIm5iZiI6MTcwNTQwMDYwMSwicGF0aCI6Ii8xNTY2OTQ4NjMvMjk3MDEwNDYyLTYwN2E2OWYzLTBlMTItNDk2MS04YTM1LWU4NTUyNmUzNjQ0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQxMDIzMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYzk3ODYzZDdhNTdmOTUxYWFjMmFkYWVlMjU4MGNiZjc0NGExYmQ0NGI3NzlmZjE3ZWM1N2I3YTNmYjhiMzZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZlBFIa4cmhsjoquu9Fl8W7o4QzX7SE7Ni82yqq8QNos"> 只有改過中間的三個數值

gemini这种ai模型不一定会严格遵守提示词，按照同等数量段落返回，所以段落数量不能太大。 如果出现错位情况，建议适当调低段落数量
