### ISSUE TITLE
[Bug]: youtube视频评论区不翻译

### ISSUE THREAD

**Issue by Birdling** [immersive-translate/immersive-translate#1326]
### 插件版本号 | Version

1.1.5

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

<img width="1348" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62651551/352c917f-5004-471f-8533-0d6b678b985e">
youtube评论区不翻译，视频推荐翻译了，safari就没事，清理过chrome的浏览数据了，还是不行

**Comment by keyboard3** [comment]
我试了正常，有没有其他插件干扰？  录个屏看下

**Comment by Birdling** [comment]
还是不行

**Comment by keyboard3** [comment]
卸载重装看看

**Comment by Birdling** [comment]
已经卸载过一遍了，还是不行

**Comment by keyboard3** [comment]
> 已经卸载过一遍了，还是不行

那你这个应该是其他插件干扰了。 你试试给沉浸式隐身窗口权限，然后在隐身窗口中访问试试

**Comment by Birdling** [comment]
<img width="1136" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62651551/25a2e57f-259f-4da0-92a0-adabce75354f">
隐身窗口是无痕模式吗？无痕模式怎么添加插件呢？

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/b7ea132c-508b-4934-83f8-36b487c5b668)

**Comment by Birdling** [comment]
可以用！

**Comment by Birdling** [comment]
怎么判断是哪个插件干扰了呢？

**Comment by Birdling** [comment]
<img width="733" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62651551/44f49997-6920-4a74-ae34-6d1ef2dc50ff">
我把扩展在这里都关了，怎么还是翻译不了youtube评论？

**Comment by keyboard3** [comment]
> 怎么判断是哪个插件干扰了呢？

挨个关闭可能得插件试试呗

**Comment by Birdling** [comment]
> > 怎么判断是哪个插件干扰了呢？
> 
> 挨个关闭可能得插件试试呗

都关了，还是翻译不了是为啥

**Comment by Birdling** [comment]
又把插件重装了一遍，还是不行

**Comment by keyboard3** [comment]
> 又把插件重装了一遍，还是不行

不是隐私窗口正常的嘛，肯定是某个东西影响，难道是浏览器脏了？
换个edge浏览器看看

**Comment by Birdling** [comment]
鼠标悬停可以翻译，不悬停不能直接翻译

**Comment by keyboard3** [comment]
暂时无法复现，先关闭这个问题哈

**Comment by keyboard3** [comment]
我怀疑是youtube 做了AB测试，你可以

**Comment by Birdling** [comment]
“面板上的保存双语页面”，保存双语页面在哪儿？

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/7da80ce9-bb12-4499-bbea-f5fe61660021)

**Comment by Birdling** [comment]
https://readit.site/a/KvwuU

**Comment by keyboard3** [comment]
> https://readit.site/a/KvwuU

更新下规则 https://dash.immersivetranslate.com/abount#about ，好了

**Comment by Birdling** [comment]
<img width="432" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62651551/c06ef69b-4e66-4e8a-a89f-9b576d4ded30">
https://readit.site/a/EMJmw
还是不行啊

**Comment by keyboard3** [comment]
> <img alt="image" width="432" src="https://private-user-images.githubusercontent.com/62651551/299945130-c06ef69b-4e66-4e8a-a89f-9b576d4ded30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjQwNjgsIm5iZiI6MTcwNjI2Mzc2OCwicGF0aCI6Ii82MjY1MTU1MS8yOTk5NDUxMzAtYzA2ZWY2OWItNGU2Ni00ZThhLWE4OWYtOWI1NzZkNGRlZDMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDEwMDkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmNDE5MzBmY2Q4NzYwNjU0NjYzNWQ5NTI2OTQzNzc5YWQ5Y2Y2YTNlMmNkZjcxZmEzMTMwY2Q4ZmRjM2YzYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hi9ZwiFaTaAIWcNkS2fi-mhQi0IiyXlTHKeIAtuUqd8">
> https://readit.site/a/EMJmw 还是不行啊
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/5caad2b2-5584-4f8c-8919-a1bae5010ac5)

啊 不可能啊，我这边已经都OK了呀。 你这个分享页面试过吗，一点都翻不了？

**Comment by Birdling** [comment]
是的，还是翻不了

**Comment by Birdling** [comment]
https://readit.site/a/EMJmw 这个网页可以翻译，但是原网页：
https://www.youtube.com/watch?v=Vn8bj0YpZg4&list=PLlpSQCrjuGkriILjGVhAMxaroOgpGDbvl&index=16
这个网页翻译不了

**Comment by keyboard3** [comment]
> https://readit.site/a/EMJmw 这个网页可以翻译，但是原网页： https://www.youtube.com/watch?v=Vn8bj0YpZg4&list=PLlpSQCrjuGkriILjGVhAMxaroOgpGDbvl&index=16 这个网页翻译不了
那就实在弄不懂了，有没有language reactor插件？建议还是再在隐私窗口下排查下，肯定第三方插件影响了

**Comment by Birdling** [comment]
我之前把插件都关了，就留这个，还是不行。关掉不够吗？还是说要删除？

**Comment by keyboard3** [comment]
> 我之前把插件都关了，就留这个，还是不行。关掉不够吗？还是说要删除？

要不微信沟通吧，沟通及时一点，你加入微信用户群 https://immersivetranslate.com/  （官网底部）， 然后私信管理员keyboard3

**Comment by LilTai8964** [comment]
删除一个视频的历史浏览记录，就行了
