### ISSUE TITLE
建议悬浮图标改回圆形

### ISSUE THREAD

**Issue by iseeyo** [immersive-translate/immersive-translate#1327]
### 您希望的更新和改进是什么 | Update or Improve

原本的悬浮图标是圆形的，靠边自动隐藏一半，现在悬浮图标靠边还是露出一大截，放在下方会影响页面其他功能及浮窗的使用！

**Comment by keyboard3** [comment]
悬浮球它是可以伸缩的，调整成圆形很奇怪，如果默认右边不合适可以去设置调整悬浮球固定方向在左边

**Comment by keyboard3** [comment]
悬浮球它是可以伸缩的，调整成圆形很奇怪，如果默认右边不合适可以去设置调整悬浮球固定方向在左边
