### ISSUE TITLE
用Gemini看YouTube视频，有些字幕有翻译，有些文字还是未翻译的状态

### ISSUE THREAD

**Issue by heiggmm** [immersive-translate/immersive-translate#1329]
### 您希望的更新和改进是什么 | Update or Improve

试了很多次还是不行，用谷歌或者微软翻译没这个问题

**Comment by keyboard3** [comment]
有没有改过gemini的配置？gemini网页翻译正常吗？

**Comment by heiggmm** [comment]
> 有没有改过gemini的配置？gemini网页翻译正常吗？

网页正常就视频会出现部分不翻译的问题，配置是默认的

**Comment by keyboard3** [comment]
gemini不一定会严格遵守提示词，按照同等数量段落返回。 如果这种情况，建议适当调低段落数量，调成5个段落再看看

**Comment by heiggmm** [comment]
> gemini不一定会严格遵守提示词，按照同等数量段落返回。 如果这种情况，建议适当调低段落数量，调成5个段落再看看

段落调的越小感觉未翻译的文字变的越多，调大了不行

**Comment by keyboard3** [comment]
> > gemini不一定会严格遵守提示词，按照同等数量段落返回。 如果这种情况，建议适当调低段落数量，调成5个段落再看看
> 
> 段落调的越小感觉未翻译的文字变的越多，调大了不行

越小，未翻译的变多？给个网址，我试试

**Comment by heiggmm** [comment]
> > > gemini不一定会严格遵守提示词，按照同等数量段落返回。 如果这种情况，建议适当调低段落数量，调成5个段落再看看
> > 
> > 
> > 段落调的越小感觉未翻译的文字变的越多，调大了不行
> 
> 越小，未翻译的变多？给个网址，我试试

https://www.youtube.com/watch?v=czu4x-XyzaE

**Comment by immccn123** [comment]
可能是 LLM 抽风导致的。

**Comment by heiggmm** [comment]
> 可能是 LLM 抽风导致的。

不是个例，好几天每个视频都会出现未翻译的情况无论视频长短

**Comment by keyboard3** [comment]
这个现象是Gemini对日语翻译不友好，日语翻译建议切换其他翻译服务

**Comment by heiggmm** [comment]
> 这个现象是Gemini对日语翻译不友好，日语翻译建议切换其他翻译服务

谢谢

**Comment by heiggmm** [comment]
> 这个现象是Gemini对日语翻译不友好，日语翻译建议切换其他翻译服务

但是今天在Gemini界面直接复制日文让他翻译没出现问题，这是不是说从GMN到沉浸的中间出现问题了？
