### ISSUE TITLE
[请求]支持tiktok.com

### ISSUE THREAD

**Issue by photkey** [immersive-translate/immersive-translate#133]
已经把tiktok.com加入总是翻译的网址，但还是没有自动翻译。

同一个视频从主页进入跟直接访问网址展现形式是不一样的，分别截图如下：

1、从主页进入：
![Snipaste_2023-02-13_14-09-15](https://user-images.githubusercontent.com/60434581/218384723-d8de99fb-70f1-41a5-a837-c6a6e8127469.png)

2、直接访问网址：https://www.tiktok.com/@paulkenton/video/7171449448931888390
![Snipaste_2023-02-13_14-12-36](https://user-images.githubusercontent.com/60434581/218384928-a8bf9a4d-fa92-449a-a19f-4d7c58ebcef6.png)

**Comment by theowenyoung** [comment]
好的，已适配，下个版本生效。

**Comment by theowenyoung** [comment]
新版已发布～ 暂时关掉这个问题了，有问题再打开～
