### ISSUE TITLE
[Bug]: 显示浏览器版本不支持的400错误

### ISSUE THREAD

**Issue by zzllrr** [immersive-translate/immersive-translate#1330]
### 插件版本号 | Version

1.1.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

400: Client Browser Version not supported
不管全文翻译，还是部分翻译都报错

### 补充说明 | Additional context

![Mersenne Prime Discovery - 2^82589933-1 is Prime!_小乐图客](https://github.com/immersive-translate/immersive-translate/assets/767635/320cb71b-6fe7-4c91-8080-ba1220d018a9)

**Comment by keyboard3** [comment]
edge版本太低了应该，升级下edge。或者换chrome浏览器
