### ISSUE TITLE
[Bug]: 微软翻译突然无法使用

### ISSUE THREAD

**Issue by 321yida** [immersive-translate/immersive-translate#1333]
### 插件版本号 | Version

1.1.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension, 油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/67246596/3c81461f-82e8-49ea-b361-fe4b481257a7)
点击翻译出现了服务报错，测试也不通过

**Comment by keyboard3** [comment]
浏览器的问题，升级下浏览器版本。或者使用chrome
