### ISSUE TITLE
进行PDF翻译时，标签页title不容易分辨

### ISSUE THREAD

**Issue by GBEYOND0613** [immersive-translate/immersive-translate#1334]
### 您希望的更新和改进是什么 | Update or Improve

在翻译后，标签页title显示为所翻译的PDF的名称

**Comment by keyboard3** [comment]
离线文档翻译 Pdf标题已支持，在线pdf文档翻译下个版本支持
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/ac6ee767-a312-4357-9bec-555889831b63)
