### ISSUE TITLE
网页特别卡

### ISSUE THREAD

**Issue by LePao1** [immersive-translate/immersive-translate#1335]
### 您希望的更新和改进是什么 | Update or Improve

从论文网站进去这个网页

![image](https://github.com/immersive-translate/immersive-translate/assets/136981189/6a7a0efd-a775-47a5-aea1-4928366010b8)

每次的转圈翻译过程中，电脑都特别卡，鼠标滑动在屏幕上滑动都掉帧，及其容易导致浏览器崩溃

![image](https://github.com/immersive-translate/immersive-translate/assets/136981189/0641650b-11fb-4955-8a91-f3f97be48647)

**Comment by theowenyoung** [comment]
看起来是因为这个网页内容本身非常大。卡顿和电脑本身的性能有关。

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/58087f79-d56a-4414-8b26-9d3893e053d0)
这里改成0试试
