### ISSUE TITLE
[Bug]: youtube翻译，有时候没有把英文翻译成中文

### ISSUE THREAD

**Issue by QingRun-Tan** [immersive-translate/immersive-translate#1338]
### 插件版本号 | Version

v1.5.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

youtube上视频翻译，英文 没有翻译成中文。不知道是怎么回事。我开启了双语翻译，但是只显示英文，不显示中文

### 出现问题的网址 | URL

https://www.youtube.com/watch?v=umepbfKp5rI&t=12643s

### 重现步骤 | To Reproduce

从3：30：00之后的视频翻译都无法进行翻译。只显示英文，没有显示中文。
![1705581572177](https://github.com/immersive-translate/immersive-translate/assets/141310846/23b361ad-3079-4feb-96fe-541185a3a739)

**Comment by FattySpring** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/25144301/a5f23ca9-9d91-43ea-aa5f-0cbdb7c6ba23)

视频双语字幕默认用的是 YouTube 自动翻译的字幕，但这个视频 YouTube 自动翻译的字幕在后半部分没有内容。你可以改用沉浸式翻译字幕，只需进入沉浸式翻译的设置，找到并选择‘视频字幕’选项，然后激活‘使用沉浸式翻译来翻译字幕’。这样，字幕就会通过沉浸式翻译生成，而不再依赖 YouTube 的自动翻译。
