### ISSUE TITLE
[問題]PDF翻譯失效

### ISSUE THREAD

**Issue by sam00905266** [immersive-translate/immersive-translate#134]
不小心多打了一個空白文件我該如何刪除? 我的問題已在樓下 

第一個回覆不會有刪除按鈕 所以最好的辦法是把 第二個回覆copy回第一個 但太麻煩了 我不想這麼做

**Comment by sam00905266** [comment]
翻譯PDF時會遭遇一片空白
裝置 macbook air m1 (2020 反正就是最早的那個M系列)
瀏覽器 edge(110.0.1587.41 (官方組建) (arm64)) chrome(版本 110.0.5481.96 (正式版本) (arm64)) 最新版本都試過 
插件版本 0.2.57(剛發現有0.2.58 不過預設商店渠道下載是這個版本 等等測試)
PDF 按翻譯後會呈現一片空白[
](https://share.cleanshot.com/L5LQdpcn)

**Comment by sam00905266** [comment]
我無法透過下載zip檔載入擴充包至瀏覽器 即便我開啟了開發者模式 給的連結仍是0.2.57版
另附詳細操作錄屏 基本上測試文件就是使用文字編輯器打上英文字 後輸出為PDF 再使用瀏覽器開啟 有懷疑會不會是PDF格式問題 所以以同樣方式從google文件下載為PDF仍然不行[
](https://share.cleanshot.com/lH9lC2v6)

**Comment by theowenyoung** [comment]
试一下 右键点击扩展图标，从本地上传pdf文件呢？


你的这个情况可能是没有给扩展访问本地文件的权限？ 需要在扩展管理里允许访问本地文件才可以

**Comment by sam00905266** [comment]
![CleanShot 2023-02-15 at 10 24 49](https://user-images.githubusercontent.com/125323096/218911542-2b7d2ba1-b037-4f51-89f7-050b66b0733b.png)
具體到哪裡操作如何開啟授權呢？

**Comment by sam00905266** [comment]
![CleanShot 2023-02-15 at 10 27 23](https://user-images.githubusercontent.com/125323096/218911722-a045d15c-1fdf-4b6b-af89-35b7fdb04757.png)
亦或是从这边调整？

**Comment by sam00905266** [comment]
感谢我了解到了 需要開啟允許存取檔案URL希望開發者可以預設開啟 或有個詳細引導之類 我開啟後 重啟瀏覽器得以使用這個功能
再次感謝 @theowenyoung

**Comment by theowenyoung** [comment]
好吧 这里可以把错误提示做的更好一点, 感谢反馈

**Comment by theowenyoung** [comment]
PDF相关问题统一在 https://github.com/immersive-translate/immersive-translate/issues/37 里讨论，暂时先关闭这个问题了

**Comment by sam00905266** [comment]
好的我瞭解了
