### ISSUE TITLE
[申请适配] pann & dcinside

### ISSUE THREAD

**Issue by alphavvv** [immersive-translate/immersive-translate#1341]
申请适配pann和dcinside 布局有些问题 重合了
![IMG_2472](https://github.com/immersive-translate/immersive-translate/assets/83694637/349f3e63-d88c-43d5-b898-4f5819dcf08a)
![IMG_2471](https://github.com/immersive-translate/immersive-translate/assets/83694637/c66d8ac4-4ea9-48b6-91a9-99705075d59a)
https://m.pann.nate.com
https://m.dcinside.com

**Comment by FattySpring** [comment]
这两个站点页面元素比较特殊，无法适配双语模式，建议使用【仅译文】模式。

![image](https://github.com/immersive-translate/immersive-translate/assets/25144301/25e4e8c2-387d-4887-80f5-452d9dc53dc9)
长按悬浮球会显示设置面板，点击上图中红色框内按钮即可切换 【仅译文】模式
