### ISSUE TITLE
[Bug]: Open AI的Api使用问题

### ISSUE THREAD

**Issue by Wesdurant** [immersive-translate/immersive-translate#1342]
### 插件版本号 | Version

最新版本

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

感谢作者在应用商店的解答，为之前的误解评论表示歉意。

大概知道问题出在哪里了，每秒请求次数限制。我填入了10几个key，能翻译的长度增加了一些。不过还是有几个疑问：

1、关于请求次数的问题，这个是按照段落来计算的吗？一段一次？

2、我在用其他第三方桌面客户端的时候，同样是调用API，就没有出现过请求次数限制的问题，甚至可以一次性翻译非常长的文章。所以在使用沉浸式翻译的时候，我是不是可以通过设置，解决这个请求次数限制的问题。

3、若能帮忙解答一下，万分感谢。

### 出现问题的网址 | URL

https://www.nytimes.com/2024/01/18/us/uvalde-school-shooting-report-doj.html

### 重现步骤 | To Reproduce

1、开启阅读模式（简悦）
2、删除我不需要的段落，只留下我想要的文本
3、翻译

### 补充说明 | Additional context

是在阅读模式下进行的翻译

**Comment by theowenyoung** [comment]
> 1、关于请求次数的问题，这个是按照段落来计算的吗？一段一次？

是的，每段一个独立请求。

> 2、我在用其他第三方桌面客户端的时候，同样是调用API，就没有出现过请求次数限制的问题，甚至可以一次性翻译非常长的文章。所以在使用沉浸式翻译的时候，我是不是可以通过设置，解决这个请求次数限制的问题。

网页翻译的请求量远远大于对话式的请求量。

**Comment by Wesdurant** [comment]
感谢回复，已解决问题
