### ISSUE TITLE
[Bug]: Github issue页面翻译后跳转页面翻译失效 

### ISSUE THREAD

**Issue by oyal** [immersive-translate/immersive-translate#1344]
### 插件版本号 | Version

1.1.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

issue页面翻译后，点击页码跳转页面，翻译失效，必须要点击显示原文，然后再点击翻译

### 重现步骤 | To Reproduce

![recording](https://github.com/immersive-translate/immersive-translate/assets/88022434/abcf1c11-deee-450e-8a52-3b66ee3748dc)

**Comment by keyboard3** [comment]
1.1.7 已修复
