### ISSUE TITLE
允许调整 Gemini API 安全级别

### ISSUE THREAD

**Issue by ZeroClover** [immersive-translate/immersive-translate#1346]
### 您希望的更新和改进是什么 | Update or Improve

Gemini API 在没有传递安全级别值时，使用缺省的设置 `BLOCK_MEDIUM_AND_ABOVE`

这导致一些文本无法被翻译。甚至有些毫无任何 `Harassment` / `Hate speech` / `Sexually explicit` / `Dangerous` 因素的内容也被阻止

建议在使用 Gemini API 时增加一个选项，允许用户调整安全级别值，以翻译更多内容。

根据 https://ai.google.dev/docs/safety_setting_gemini 和 https://ai.google.dev/api/rest/v1beta/HarmCategory

可以为以下分类：

`HARM_CATEGORY_UNSPECIFIED`
`HARM_CATEGORY_DEROGATORY`
`HARM_CATEGORY_TOXICITY`
`HARM_CATEGORY_VIOLENCE`
`HARM_CATEGORY_SEXUAL`
`HARM_CATEGORY_MEDICAL`
`HARM_CATEGORY_DANGEROUS`
`HARM_CATEGORY_HARASSMENT`
`HARM_CATEGORY_HATE_SPEECH`
`HARM_CATEGORY_SEXUALLY_EXPLICIT`
`HARM_CATEGORY_DANGEROUS_CONTENT`

传递以下值：

`BLOCK_NONE`
`BLOCK_ONLY_HIGH`
`BLOCK_MEDIUM_AND_ABOVE`
`BLOCK_LOW_AND_ABOVE`

来调整安全设置。

使用者可以选择降低安全级别以降低出现不能翻译的内容的概率。

**Comment by heiggmm** [comment]
出现同样情况，望升级

**Comment by keyboard3** [comment]
这边接口默认传递是 BLOCK_NONE

**Comment by ZeroClover** [comment]
> 这边接口默认传递是 BLOCK_NONE

但是我在翻译时仍然收到

可否确认一下是否对所有分类发出了 `BLOCK_NONE` 呢？我尝试过同样的 Prompt 手动发 API 请求并指定 `HARM_CATEGORY_UNSPECIFIED` 为 `BLOCK_NONE` 就可以正常输出。

**Comment by keyboard3** [comment]
> > 这边接口默认传递是 BLOCK_NONE
> 
> 但是我在翻译时仍然收到
> 
> 可否确认一下是否对所有分类发出了 `BLOCK_NONE` 呢？我尝试过同样的 Prompt 手动发 API 请求并指定 `HARM_CATEGORY_UNSPECIFIED` 为 `BLOCK_NONE` 就可以正常输出。

所有的
![Uploading image.png…]()

**Comment by ZeroClover** [comment]
> > > 这边接口默认传递是 BLOCK_NONE
> > 
> > 
> > 但是我在翻译时仍然收到
> > 可否确认一下是否对所有分类发出了 `BLOCK_NONE` 呢？我尝试过同样的 Prompt 手动发 API 请求并指定 `HARM_CATEGORY_UNSPECIFIED` 为 `BLOCK_NONE` 就可以正常输出。
> 
> 所有的 ![image](https://private-user-images.githubusercontent.com/13177744/298626580-48a9d4b7-5d1b-4704-aa22-1dd276ffdefd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MzU3NTQsIm5iZiI6MTcwNTkzNTQ1NCwicGF0aCI6Ii8xMzE3Nzc0NC8yOTg2MjY1ODAtNDhhOWQ0YjctNWQxYi00NzA0LWFhMjItMWRkMjc2ZmZkZWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDE0NTczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhNjM3ZmU4MWExZjRiYWQxZmMwMjZlZWUwMTUyOWNlNTUwNDRjZjYyMDJkMGJjNWM5NTFiNDJmOTNmNDQxOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DJaNjMsjLh2twkMy99U-hF_VdEMOSU-p4OMK7Xc5PM4)

试了下确实，之前应该是 Google 审计抽风了，不好意思

**Comment by keyboard3** [comment]
嗯 你上面给的这些分类，我也加进去了

**Comment by keyboard3** [comment]
> 这些分类好像在 Google Studio 的不生效。。。

啊 所以你报了假警？

**Comment by hidaris** [comment]
白天还是ok的，晚上突然报错了 
![image](https://github.com/immersive-translate/immersive-translate/assets/8336146/0978ce62-0821-4043-8022-f120660fec8d)

**Comment by keyboard3** [comment]
> 白天还是ok的，晚上突然报错了 ![image](https://private-user-images.githubusercontent.com/8336146/298638528-0978ce62-0821-4043-8022-f120660fec8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MzgzMTQsIm5iZiI6MTcwNTkzODAxNCwicGF0aCI6Ii84MzM2MTQ2LzI5ODYzODUyOC0wOTc4Y2U2Mi0wODIxLTQwNDMtODAyMi1mMTIwNjYwZmVjOGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjJUMTU0MDE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzNjZjQ0NTAyYjc1MGZiZDQ4ZDc2MmFkMGRiNGFlYTM3YjU0ZjBhNTgzZDZhOWM3ZjEzMWFhMzJhNmVhNTkzOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FPumCit2xsQ8DjEc2F702f0C63B94TP4J2ZOhidn90Y)

。。。 怪我，没有检验你的那些安全设置。 多余的安全设置gemini是不认直接报错

**Comment by ZeroClover** [comment]
不好意思，当时提 issue 时没有仔细检查，但是也没想到 Google 在 AI Studio 给的文档不适用于 AI Studio。。。

**Comment by keyboard3** [comment]
去这里更新下规则 https://dash.immersivetranslate.com/abount#about 还原了

**Comment by hidaris** [comment]
> 去这里更新下规则 https://dash.immersivetranslate.com/abount#about 还原了

非常感谢 👍
