### ISSUE TITLE
[Bug]: Gemini 的日译中把 日文翻译成了日文

### ISSUE THREAD

**Issue by immccn123** [immersive-translate/immersive-translate#1347]
### 插件版本号 | Version

1.1.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

Before:

![image](https://github.com/immersive-translate/immersive-translate/assets/41335471/c474509a-2668-4d17-93ec-7b83c032568a)

After:

![image](https://github.com/immersive-translate/immersive-translate/assets/41335471/f85bb3f3-642b-4456-9ccd-bb8340993d71)

感觉 prompt 需要优化，之前也出现过日译简中变成繁中的情况，但是不好复现。可能 LLM 就是这样的（

### 出现问题的网址 | URL

https://kamitsubaki.jp/guidelines/

### 重现步骤 | To Reproduce

直接翻译。复现率可能没有那么高。

**Comment by immccn123** [comment]
「敬意を表して、すべてのクリエイターの活動に敬意を表し、二次創作文化の発展に貢献します。」一句在原文未出现。

**Comment by keyboard3** [comment]
<img width="851" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/13177744/594d4344-0bac-4469-9549-618b077f532b">
我用openai没复现，你用了什么翻译服务

**Comment by immccn123** [comment]
> <img alt="image" width="851" src="https://private-user-images.githubusercontent.com/13177744/298277330-594d4344-0bac-4469-9549-618b077f532b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NTE0NTUsIm5iZiI6MTcwNTc1MTE1NSwicGF0aCI6Ii8xMzE3Nzc0NC8yOTgyNzczMzAtNTk0ZDQzNDQtMGJhYy00NDY5LTk1NDktNjE4YjA3N2Y1MzJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDExNDU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3ZDc5NGUwYTdkYjUzNTVmNjBkMDE3YjU2MGViNDZiN2IyZmIxN2MyMDUyMjBiOTM2ZGExOTA2YWZiZjE3ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zWYclDjx1-AfqQWwLT5NxsQ6J_BTwLT74SkETQaL7Sc"> 我用openai没复现，你用了什么翻译服务

？标题不是写着吗？

**Comment by keyboard3** [comment]
<img width="878" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/13177744/bd80e946-6cbd-417b-b515-e3cf9e6f87ad">
你用的是默认提示词吗，我这Gemini也正常

**Comment by keyboard3** [comment]
> 是默认的

你这是每次必现？

**Comment by immccn123** [comment]
不是。但是我这里在翻译大量日文文本的时候很容易出现这样的问题。不知道为什么，很神奇。

关键是翻译的结果还有缓存，即使出错也没法去进行补救重新翻译一类的。

**Comment by keyboard3** [comment]
> 不是。但是我这里在翻译大量日文文本的时候很容易出现这样的问题。不知道为什么，很神奇。
> 
> 关键是翻译的结果还有缓存，即使出错也没法去进行补救重新翻译一类的。

我发现了，Gemini对日语翻译不友好，经常性的直接返回日语原文...。建议日语翻译暂时换成别的翻译服务

**Comment by immccn123** [comment]
感谢

**Comment by azumi765** [comment]
原来是模型的bug吗，这问题出现很频繁
