### ISSUE TITLE
可否增加支持网页版的 ChatGPT翻译。

### ISSUE THREAD

**Issue by a0n1** [immersive-translate/immersive-translate#1349]
### 您希望的更新和改进是什么 | Update or Improve

现在很多插件都支持登陆网页版的 ChatGPT来使用，这也可以方便没有OpenAI 的 API的用户。谢谢。

**Comment by theowenyoung** [comment]
网页版 chatgpt 速率限制较严重，无法在沉浸式翻译中使用。
