### ISSUE TITLE
双语字幕按钮逻辑问题

### ISSUE THREAD

**Issue by Graysonnwu** [immersive-translate/immersive-translate#1350]
### 您希望的更新和改进是什么 | Update or Improve

一般来说，该按钮功能应该是(单次)开启/关闭双语字幕，而不是是否自动启用双语字幕

<img width="151" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/58651725/d9261190-1f06-46fb-b28d-cd1515842e84">

是否自动启用功能在右上角点击图标弹出的窗口中已经存在

<img width="330" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/58651725/2f435acd-b906-45ed-ac04-d8a1b9114851">

另外该图标的选择也能斟酌一下，要么纯图标，要么纯字，图标的话最好还是与其他按钮风格一致，统一为白色。（纯个人意见）

**Comment by theowenyoung** [comment]
> 一般来说，该按钮功能应该是(单次)开启/关闭双语字幕，而不是是否自动启用双语字幕

这个页面中的按钮是为了补充很多人不知道如何开启视频双语字幕用的～ 如果你知道可以在面板上开启的话，实际上可以直接选择隐藏就好了～

**Comment by Graysonnwu** [comment]
> 这个页面中的按钮是为了补充很多人不知道如何开启视频双语字幕用的～ 如果你知道可以在面板上开启的话，实际上可以直接选择隐藏就好了～

之后肯定会在这个按钮上多做文章的，比如字幕下载 #1257 、调整原文和译文的上下位置（没找到 issue 这里顺便功能建议一下吧，个人习惯译文放在原文上方）

可以参考另一个插件 [YouTube 双字幕](https://chromewebstore.google.com/detail/youtube-%E5%8F%8C%E5%AD%97%E5%B9%95/hkbdddpiemdeibjoknnofflfgbgnebcm)，他们的解决方法是将字幕相关设置都放进这个自带的设置图标

<img width="292" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/58651725/d124b989-6365-42d2-a38d-f4bf16be3f43">

- 默认字幕：设置译文目标语言
- 单字幕：仅译文模式
- 字幕下载

这样甚至这个图标都不是必须的

**Comment by oyal** [comment]
@theowenyoung  Youtube 双字幕的字体大小可以调整，我觉得这是一个很不错的的功能，我使用沉浸式翻译在 1920*1080 的屏幕下感觉字幕有点大了

![image](https://github.com/immersive-translate/immersive-translate/assets/88022434/43ddf20c-fd74-4b78-badf-e8945ed6cb7a)

**Comment by FattySpring** [comment]
> @theowenyoung Youtube 双字幕的字体大小可以调整，我觉得这是一个很不错的的功能，我使用沉浸式翻译在 1920*1080 的屏幕下感觉字幕有点大了
> 
> ![image](https://private-user-images.githubusercontent.com/88022434/298378716-43ddf20c-fd74-4b78-badf-e8945ed6cb7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4OTEwMjQsIm5iZiI6MTcwNTg5MDcyNCwicGF0aCI6Ii84ODAyMjQzNC8yOTgzNzg3MTYtNDNkZGYyMGMtZmQ3NC00Yjc4LWJhZGYtZTg5NDVlZDZjYjdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDAyMzIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwNzA0YWEzZGU4ZWNlZjg1Yzk3OWIzMzdiYzFiNjk5ZmEwODVhMWRlM2Y3MzA5MzIwMWVmZTliNzcxYzk1NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zx7bX3pcDLNLFdQXTx1mFUiILZ-qge5-ZccCx4F2VTI)

可以看下这里 [Youtube 字幕设置样式](https://immersivetranslate.com/docs/faq/#youtube-%E5%AD%97%E5%B9%95%E8%AE%BE%E7%BD%AE%E6%A0%B7%E5%BC%8F)
