### ISSUE TITLE
网页翻译时希望能够与原文的加粗、颜色、链接等格式保持一致

### ISSUE THREAD

**Issue by kilicoli** [immersive-translate/immersive-translate#1352]
### 您希望的更新和改进是什么 | Update or Improve

举几个例子：
原文包含链接：
![1](https://github.com/immersive-translate/immersive-translate/assets/113424907/ce556644-38f4-43d5-8eab-e4c182a6333c)
翻译后就不再包含链接了：
![11](https://github.com/immersive-translate/immersive-translate/assets/113424907/797d0d9b-e90c-476f-a047-68186f3f32b3)

原文包含红色字体：
![2](https://github.com/immersive-translate/immersive-translate/assets/113424907/8901127f-ad73-43eb-afa6-fa2e50336057)
翻译后就不再包含红色字体：
![22](https://github.com/immersive-translate/immersive-translate/assets/113424907/c9f0d434-689c-436b-8edc-9fb122d62f38)

希望能够更新，这样的功能蛮基础也蛮有用的

**Comment by keyboard3** [comment]
问题重复，目前只支持纯文本翻译，在不支持富文本 #https://github.com/immersive-translate/immersive-translate/issues/1296

**Comment by keyboard3** [comment]
译文的超链接无法点击目前是预期行为哈，查看其他相关问题：

https://github.com/immersive-translate/immersive-translate/issues?q=is%3Aissue+%E8%B6%85%E9%93%BE%E6%8E%A5+is%3Aclosed

**Comment by keyboard3** [comment]
1.7.8+ 已支持富文本翻译，可以更新体验下
![image](https://github.com/user-attachments/assets/22c29382-1f9f-43f1-ad54-e9460e5da523)
