### ISSUE TITLE
enhanced input box for Baidu 

### ISSUE THREAD

**Issue by seedsong2** [immersive-translate/immersive-translate#1353]
### 您希望的更新和改进是什么 | Update or Improve

저는 한국어로 바이두에서 검색어를 입력하고 중국어로 번역해서 사용하고 싶은 사용자인데, 이 기능이 바이두에서는 작동하지 않는 것을 발견했습니다. 중국어 검색이 필요한 타 언어 사용자를 위해서 이 기능을 추가해 주실 수 있을까요?

**Comment by keyboard3** [comment]
百度 호환성 문제로 입력창 단축키를 통해서만 트리거할 수 있습니다.
