### ISSUE TITLE
Set translation failure pop-up as optional

### ISSUE THREAD

**Issue by CongYun22** [immersive-translate/immersive-translate#1354]
### 您希望的更新和改进是什么 | Update or Improve

Set translation failure pop-up as optional, it could be annoying.

**Comment by keyboard3** [comment]
The pop-up window is meant to allow users to quickly resolve translation errors, which should theoretically not be confusing. What kind of errors do you typically encounter?

**Comment by CongYun22** [comment]
When a translation fails, there will be a retry button next to the original text, so the translation failure pop-up is somewhat unnecessary but distracting to the user's reading.

**Comment by theowenyoung** [comment]
By default, we have set the popup to only show up if there are more than 10 errors at the same time, which usually means that there is a big problem with your translation service.

Now we changed it to 20 , and in the future we'll provide an option in [Advanced Settings] to let you decide for yourself if you want pop-ups or not!

**Comment by CongYun22** [comment]
Thanks! That would be really helpful.
