### ISSUE TITLE
[Bug]: 网络错误500

### ISSUE THREAD

**Issue by QingRun-Tan** [immersive-translate/immersive-translate#1355]
### 插件版本号 | Version

v1.7.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

当我开启翻译时，一直报错500

### 出现问题的网址 | URL

所有网址

### 重现步骤 | To Reproduce

当我开启翻译时，出现500

### 补充说明 | Additional context

![Uploading 1706013467261.jpg…]()

**Comment by keyboard3** [comment]
微软翻译服务不稳定，切换腾讯翻译或者谷歌翻译
