### ISSUE TITLE
鼠标悬停翻译

### ISSUE THREAD

**Issue by Wongony** [immersive-translate/immersive-translate#1356]
### 您希望的更新和改进是什么 | Update or Improve

能否实现鼠标悬停+双击鼠标左/右键翻译该段。

**Comment by keyboard3** [comment]
浏览器的双击左右键有默认行为，不适合做逻辑处理

**Comment by Wongony** [comment]
如果是鼠标悬停，并且左键选定一定数量字符，翻译该段。这个逻辑处理是否合理。
