### ISSUE TITLE
[Bug]: Notion 网页无法翻译

### ISSUE THREAD

**Issue by zhatlas** [immersive-translate/immersive-translate#1357]
### 插件版本号 | Version

1.1.7

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome, Other

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

shift + 鼠标段落翻译，译文闪烁一下后消失

### 出现问题的网址 | URL

https://browserinc.notion.site/Getting-Started-with-Arc-on-Windows-145ece36acbb40f381ce1817747cb7ca

**Comment by keyboard3** [comment]
这个是notion网页的问题，它会实时修改插件添加的属性，导致无法段落悬停翻译。 用全文翻译就没有问题
