### ISSUE TITLE
一个能卡死1分钟的页面

### ISSUE THREAD

**Issue by revaraver** [immersive-translate/immersive-translate#1359]
### 您希望的更新和改进是什么 | Update or Improve

https://www.image-line.com/fl-studio-learning/fl-studio-online-manual/html/basics_shortcuts.htm
在这个网页中沉浸式翻译会让我的电脑卡死至少一分钟(期间鼠标滑动及其卡顿,且几乎无法进行任何操作,任务管理器也打不开),像类似的条目及其多的页面该插件都会让我的电脑卡死.该插件是否有什么优化的空间能缓解这一情况呢?我并没有让他从头到尾翻译整个页面.
我的cpu是e5 2680V4,不知道是否是个例

**Comment by keyboard3** [comment]
我试了这个网页，非常顺畅。 如果你觉得卡顿，你可以在这个页面 https://dash.immersivetranslate.com/#advanced 将4999改成0

**Comment by keyboard3** [comment]
> > 我试了这个网页，非常顺畅。 如果你觉得卡顿，你可以在这个页面 https://dash.immersivetranslate.com/#advanced 将4999改成0
> 
> 感谢测试,在你的建议下我这边重新在各种情况下测试了好多遍,最后成功发现重现机制. 问题在于本地缓存,如果打开它的话,那么在第2+次开启此页面时我这边会卡顿严重,关闭之后则有效缓解该卡顿问题.

我试了下，也没复现。 感觉跟浏览器有比较大的关系，你换个chrome or edge 试试

**Comment by nerocho** [comment]
我也出现过类似情况，且可以 100% 复现。
macoS Monterey 版本 12.6.7
Microsoft Edge 版本 120.0.2210.144 (正式版本) (x86_64)
插件 1.1.8
打开廖雪峰的网站，如：https://www.liaoxuefeng.com/wiki/1016959663602400/1017495723838528
有很高的概率网页无响应，点击继续等待后，翻译插件就会加载出来，网页正常。

**Comment by keyboard3** [comment]
> 我也出现过类似情况，且可以 100% 复现。 macoS Monterey 版本 12.6.7 Microsoft Edge 版本 120.0.2210.144 (正式版本) (x86_64) 插件 1.1.8 打开廖雪峰的网站，如：https://www.liaoxuefeng.com/wiki/1016959663602400/1017495723838528 有很高的概率网页无响应，点击继续等待后，翻译插件就会加载出来，网页正常，可以多刷新几次，很容易复现。

这个页面，我 mac chrome 电脑试了很多次，也没能复现。 导出你的配置，抹掉敏感信息发来我试下

**Comment by nerocho** [comment]
> > 我也出现过类似情况，且可以 100% 复现。 macoS Monterey 版本 12.6.7 Microsoft Edge 版本 120.0.2210.144 (正式版本) (x86_64) 插件 1.1.8 打开廖雪峰的网站，如：https://www.liaoxuefeng.com/wiki/1016959663602400/1017495723838528 有很高的概率网页无响应，点击继续等待后，翻译插件就会加载出来，网页正常，可以多刷新几次，很容易复现。
> 
> 这个页面，我 mac chrome 电脑试了很多次，也没能复现。 导出你的配置，抹掉敏感信息发来我试下

基本都是默认配置，没改啥，就改过一个翻译的样式，没啥敏感信息

`{
  "generalRule": {
    "isTranslateTitle": false,
    "lineBreakMaxTextCount": 280,
    "subtitleRule.add": {
      "autoEnableSubtitle": true
    }
  },
  "isChangedAlwaysTranslatedUrls": true,
  "modifiedBySystem": true,
  "pcFloatBallMainBtnTooltipShownCount": 15,
  "translationMode": "dual",
  "translationService": "transmart",
  "translationTheme": "thinDashed",
  "translationThemePatterns": {
    "dashed": {
      "zoom": "80"
    },
    "none": {
      "zoom": "80"
    },
    "thinDashed": {
      "zoom": "80"
    }
  },
  "translationUrlPattern": {
    "excludeMatches": [
      "*.epaynfc.com"
    ],
    "matches": [
      "twitter.com",
      "www.reddit.com",
      "www.kadaza.com",
      "en.wikipedia.org",
      "*.medium.com",
      "news.ycombinator.com",
      "qdrant.tech",
      "github.com",
      "appium.io"
    ]
  },
  "updatedAt": "2024-01-23T08:22:02.281Z"
}`

**Comment by keyboard3** [comment]
> 我也遇到了，主要是在YouTube上，打开视频就会卡顿，系统14.2.1 (23C71)

参考 https://github.com/immersive-translate/immersive-translate/issues/1323

**Comment by keyboard3** [comment]
无法复现，暂时关闭此issue

**Comment by BetterWorld-Liuser** [comment]
在我网络情况不好的时候会遇到翻译卡死的问题。貌似是网络请求那块在请求翻译没有得到的时候加入了轮询机制？导致我整个电脑都会卡死。

**Comment by baijing-0656** [comment]
我也遇到了这个问题。我用的是chrome 浏览器插件，移除重装能暂时解决这个问题，过段时间之后，整个浏览器都会卡死无法运行，其它程序是可以正常使用的。严重时也出现过整个电脑卡死的情况。无奈已经移除了。插件本身是很好用的，翻译速度很快。但是频繁卡死会严重影响工作，只能暂时先放弃。

**Comment by keyboard3** [comment]
> 我也遇到了这个问题。我用的是chrome 浏览器插件，移除重装能暂时解决这个问题，过段时间之后，整个浏览器都会卡死无法运行，其它程序是可以正常使用的。严重时也出现过整个电脑卡死的情况。无奈已经移除了。插件本身是很好用的，翻译速度很快。但是频繁卡死会严重影响工作，只能暂时先放弃。

你这看起来是缓存过多导致的，你可以关闭缓存使用

**Comment by fuyunyou77** [comment]
我遇到了同样的问题。在chrome中使用沉浸式翻译让我电脑发生长时间（几十秒）卡顿，连鼠标都没办法控制。主要是翻译文本量大的网页出现问题，如维基百科，该问题可以多次复现。在edge下翻译同样的页面没有这个问题

**Comment by LiuChang-ao** [comment]
我没有用这个插件（没有手动安装），直接使用edge的右键菜单翻译功能，也出现了相同的问题

**Comment by 2catycm** [comment]
非常严重的问题，经常维基百科卡死

**Comment by keyboard3** [comment]
https://github.com/immersive-translate/immersive-translate/issues/1746 参考这里

**Comment by Moeblack** [comment]
发现一个网站100%触发此问题
https://grokipedia.com/page/Minecraft#china-edition

**Comment by ThreeAurora** [comment]
<img width="1060" height="255" alt="Image" src="https://github.com/user-attachments/assets/3d1cfc48-ee45-4f15-b728-85760d981b22" />

如上图，把“直接翻译页面前多少个字符，而无需等待滚动到可视区域”，从默认的4999设置为0，似乎避免了卡顿问题，我不确定这个办法是否稳定。

用的也是这个测试页面：https://grokipedia.com/page/Minecraft#china-edition
