### ISSUE TITLE
显示货币汇率换算后的结果

### ISSUE THREAD

**Issue by fankuiz6** [immersive-translate/immersive-translate#1362]
### 您希望的更新和改进是什么 | Update or Improve

显示自动换算汇率后的货币金额

### 补充说明 | Additional context

比如看到137＄或者 ＄137 ，我想知道人民币金额，我现在需要到谷歌输入137 usd cny，解决在网站上看到等其它国家的货币金额需要再去查一遍目前汇率转换后，希望在插件里可以指定需要换算后的货币或者跟随翻译目标语言的货币，在网站上非指定目标的货币就会自动换算成指定目标货币的结果
获取汇率可以使用公开的api，比如 https://github.com/fawazahmed0/currency-api ，在用户的插件上定时获取一遍所有货币汇率保存到本地，识别到网页里有非目标货币的货币单位出现后，使用本地保存的汇率进行换算到目标货币再显示
可以参考浏览器扩展 https://microsoftedge.microsoft.com/addons/detail/universal-automatic-curre/aeejpkkbcpndcbnmhifkdeabgjafghfn
如果目前不打算更新汇率功能，希望给一个规则可以排除这个扩展换算后的结果不翻译

**Comment by keyboard3** [comment]
不打算更新汇率功能。你用的这个汇率换算之后的页面，然后通过沉浸式分享功能出来的链接给我，我可以适配下下它

**Comment by keyboard3** [comment]
打开 https://dash.immersivetranslate.com/abount#about 更新下规则，已兼容它
