### ISSUE TITLE
优化Youtube双语字幕翻译期间的体验建议

### ISSUE THREAD

**Issue by KarlLee830** [immersive-translate/immersive-translate#1363]
### 您希望的更新和改进是什么 | Update or Improve

现在在使用Gemini翻译API时，会显示

> 正在使用Gemini服务翻译字幕中，请稍等...（沉浸式翻译）

有些API（如Gemini）处理这一过程常常要花费1~2分钟，时间有些过长了。
在针对Gemini这类大语言模型过长的翻译时间的问题，能否在这期间先行使用Youtube提供的机翻字幕，在翻译完成后在提供由API提供的字幕？
![image](https://github.com/immersive-translate/immersive-translate/assets/61072264/1a3859e6-8343-4c18-8783-23d87166e081)

**Comment by keyboard3** [comment]
目前的技术方案利用YouTube自己的字幕，只能等待显示。
如果后续我们自己托管字幕显示，才能做到更好的优化
