### ISSUE TITLE
[Bug]: OpenAI的自定义Key和Gemini的ApiKey冲突

### ISSUE THREAD

**Issue by maizhouzi** [immersive-translate/immersive-translate#1364]
### 插件版本号 | Version

1.1.8

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

OpenAI的自定义Key和Gemini的ApiKey设置了其中一个，另一个就会跟着变，没有办法对OpenAI和Gemini设置不同的key
OpenAI的Key以sk-开头，Gemini的Key以AI开头。
原本OpenAI的key设置
![image](https://github.com/immersive-translate/immersive-translate/assets/66940944/66a7bfed-4865-4e4d-95f0-dc02a4e19b64)
更改Gemini的Key后
![image](https://github.com/immersive-translate/immersive-translate/assets/66940944/096b648b-f2c6-4983-9fa5-5e85e744fec6)
OpenAI的Key也跟着变成了Gemini的Key
![image](https://github.com/immersive-translate/immersive-translate/assets/66940944/619a93b3-3012-4b00-9f74-2303620ccea9)
反之亦然，这使得OpenAI的自定义Key和Gemini的ApiKey无法共存

### 出现问题的网址 | URL

All

**Comment by keyboard3** [comment]
这个是切换是网页临时状态复用的问题，刷新下页面就好了。 这个问题下个版本修复

**Comment by keyboard3** [comment]
1.2.0 已修复
