### ISSUE TITLE
[Bug]: 翻译Tegus时出现大量排版错误，无法通过Edit Rules修正

### ISSUE THREAD

**Issue by williamz** [immersive-translate/immersive-translate#1367]
### 插件版本号 | Version

V1.1.8

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

翻译Tegus时出现大量排版错误，无法通过Edit Rules修正，错误举例如图

![tegus_bug](https://github.com/immersive-translate/immersive-translate/assets/3832062/2773514c-b345-4786-9342-08b18da90d23)

尝试用Edit Rules，无效，以下是尝试的代码：

[
  {
    "globalStyles": {
      ".k2-table": "max-height:unset;"
    },
    "matches": "app.tegus.co"
  },
  {
    "atomicBlockSelectors": [
      ".doc-viewer-interview-fragment-group"
    ],
    "matches": "app.tegus.co",
    "selectors": [
      ".doc-viewer-interview-fragment-group"
    ]
  },
  {
    "atomicBlockSelectors": [
      ".doc-viewer-interview-fragment-group__section"
    ],
    "matches": "app.tegus.co",
    "selectors": [
      ".doc-viewer-interview-fragment-group__section"
    ]
  },
  {
    "atomicBlockSelectors": [
      ".doc-viewer-interview-fragment-group__content"
    ],
    "matches": "app.tegus.co",
    "selectors": [
      ".doc-viewer-interview-fragment-group__content"
    ]
  }
]

提取的一个乱码的div代码如下：

<div data-v-885f6444="" id="utterance-3" class="doc-viewer-interview-body__utterance-wrapper" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4"><div data-v-885f6444="" style="border-left: 2px solid rgb(141, 164, 165); padding-right: 16px; margin-top: 10px; margin-bottom: 27px;" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4"></div><div data-v-885f6444="" class="doc-viewer-interview-body__utterance" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4"><div data-v-885f6444="" class="doc-viewer-interview-body__speaker" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4"><div data-v-b4ab3d45="" data-v-885f6444="" style="width: 100%;" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4"><div data-v-b4ab3d45="" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4"><div data-v-d96d2f43="" data-v-885f6444="" class="doc-viewer-interview-fragment-group doc-viewer-interview-body__speaker-name" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4"><div data-v-d96d2f43="" class="doc-viewer-interview-fragment-group__content" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4"><div data-v-d96d2f43="" class="doc-viewer-interview-fragment-group__section" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4"><div data-v-bc7fb377="" data-v-d96d2f43="" class="doc-viewer-interview-fragment-span" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4"><span data-v-bc7fb377="" class="doc-viewer-interview-fragment-span--plain" data-highlight-id="" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4" data-immersive-translate-paragraph="1">Moderator</span></div></div></div></div></div></div></div><div data-v-d96d2f43="" data-v-885f6444="" class="doc-viewer-interview-fragment-group doc-viewer-interview-body__paragraph default" id="utterance-3-0" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4"><div data-v-d96d2f43="" class="doc-viewer-interview-fragment-group__content" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4"><div data-v-d96d2f43="" class="doc-viewer-interview-fragment-group__section" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4" data-immersive-translate-paragraph="1"><div data-v-bc7fb377="" data-v-d96d2f43="" class="doc-viewer-interview-fragment-span" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4"><span data-v-bc7fb377="" class="doc-viewer-interview-fragment-span--plain" data-highlight-id="" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4">It would be interesting to get your take on the </span></div><div data-v-bc7fb377="" data-v-d96d2f43="" class="doc-viewer-interview-fragment-span" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4"><div data-v-60e9fce7="" aria-haspopup="menu" aria-expanded="false" aria-owns="v-menu-57" class="k2-popover" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4"><a data-v-1e90af4f="" data-v-bc7fb377="" class="komodo-a in-interview-link in-interview-link" href="/app/company/5487/pinterest-inc" target="_blank" data-highlight-id="3-0-48" data-test="in-interview-company" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4"><span data-v-bc7fb377="" class="is-transcript-entity doc-viewer-interview-fragment-span--link" data-highlight-id="" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4">Pinterest</span></a></div><div class="v-overlay v-overlay--absolute v-theme--light v-locale--is-ltr v-menu" data-v-60e9fce7="" offset-overflow="true" additional-style-classes="in-interview-link-tooltip" style="z-index: 2000;" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4"><div class="v-overlay__content" target="[object HTMLDivElement]" style="max-width: 400px; display: none;" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4"><div data-v-60e9fce7="" class="k2-popover-content"></div></div></div></div><div data-v-bc7fb377="" data-v-d96d2f43="" class="doc-viewer-interview-fragment-span" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4"><span data-v-bc7fb377="" class="doc-viewer-interview-fragment-span--plain" data-highlight-id="" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4">, </span></div><div data-v-bc7fb377="" data-v-d96d2f43="" class="doc-viewer-interview-fragment-span" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4"><div data-v-60e9fce7="" aria-haspopup="menu" aria-expanded="false" aria-owns="v-menu-58" class="k2-popover" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4"><a data-v-1e90af4f="" data-v-bc7fb377="" class="komodo-a in-interview-link in-interview-link" href="/app/company/125/amazon-com-inc" target="_blank" data-highlight-id="3-0-59" data-test="in-interview-company" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4"><span data-v-bc7fb377="" class="is-transcript-entity doc-viewer-interview-fragment-span--link" data-highlight-id="" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4" data-immersive-translate-paragraph="1">Amazon</span></a></div><div class="v-overlay v-overlay--absolute v-theme--light v-locale--is-ltr v-menu" data-v-60e9fce7="" offset-overflow="true" additional-style-classes="in-interview-link-tooltip" style="z-index: 2000; top: 753.636px;" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4"><div class="v-overlay__content" target="[object HTMLDivElement]" style="max-width: 400.909px; max-height: 1095.45px; min-width: 99.8153px; --v-overlay-anchor-origin: top center; transform-origin: center bottom; top: -273.636px; left: 91.8182px; display: none;" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4"><div data-v-60e9fce7="" class="k2-popover-content" data-immersive-translate-walked="7fae4acd-7663-4bd7-8fc6-8c41b2aea554"></div></div></div></div><div data-v-bc7fb377="" data-v-d96d2f43="" class="doc-viewer-interview-fragment-span" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4"><span data-v-bc7fb377="" class="doc-viewer-interview-fragment-span--plain" data-highlight-id="" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4" data-immersive-translate-paragraph="1"> partnership where you can log in through the </span></div><div data-v-bc7fb377="" data-v-d96d2f43="" class="doc-viewer-interview-fragment-span" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4"><div data-v-60e9fce7="" aria-haspopup="menu" aria-expanded="false" aria-owns="v-menu-59" class="k2-popover" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4"><a data-v-1e90af4f="" data-v-bc7fb377="" class="komodo-a in-interview-link in-interview-link" href="/app/company/125/amazon-com-inc" target="_blank" data-highlight-id="3-0-111" data-test="in-interview-company" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4"><span data-v-bc7fb377="" class="is-transcript-entity doc-viewer-interview-fragment-span--link" data-highlight-id="" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4" data-immersive-translate-paragraph="1">Amazon</span></a></div><div class="v-overlay v-overlay--absolute v-theme--light v-locale--is-ltr v-menu" data-v-60e9fce7="" offset-overflow="true" additional-style-classes="in-interview-link-tooltip" style="z-index: 2000;" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4"><div class="v-overlay__content" target="[object HTMLDivElement]" style="max-width: 400px; display: none;" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4"><div data-v-60e9fce7="" class="k2-popover-content"></div></div></div></div><div data-v-bc7fb377="" data-v-d96d2f43="" class="doc-viewer-interview-fragment-span" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4"><span data-v-bc7fb377="" class="doc-viewer-interview-fragment-span--plain" data-highlight-id="" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4" data-immersive-translate-paragraph="1"> Console and those ads could end up on </span></div><div data-v-bc7fb377="" data-v-d96d2f43="" class="doc-viewer-interview-fragment-span" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4"><div data-v-60e9fce7="" aria-haspopup="menu" aria-expanded="false" aria-owns="v-menu-60" class="k2-popover" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4"><a data-v-1e90af4f="" data-v-bc7fb377="" class="komodo-a in-interview-link in-interview-link" href="/app/company/5487/pinterest-inc" target="_blank" data-highlight-id="3-0-156" data-test="in-interview-company" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4"><span data-v-bc7fb377="" class="is-transcript-entity doc-viewer-interview-fragment-span--link" data-highlight-id="" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4" data-immersive-translate-paragraph="1">Pinterest</span></a></div><div class="v-overlay v-overlay--absolute v-theme--light v-locale--is-ltr v-menu" data-v-60e9fce7="" offset-overflow="true" additional-style-classes="in-interview-link-tooltip" style="z-index: 2000;" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4"><div class="v-overlay__content" target="[object HTMLDivElement]" style="max-width: 400px; display: none;" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4"><div data-v-60e9fce7="" class="k2-popover-content"></div></div></div></div><div data-v-bc7fb377="" data-v-d96d2f43="" class="doc-viewer-interview-fragment-span" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4"><span data-v-bc7fb377="" class="doc-viewer-interview-fragment-span--plain" data-highlight-id="" data-immersive-translate-walked="ce50a4c2-1a42-4e8d-b733-8739b1238df4" data-immersive-translate-paragraph="1">. If everybody could give an overview of your career so far and what you do right now, and also how your ad budget distribution looks like?</span></div></div></div></div></div></div>

### 出现问题的网址 | URL

https://app.tegus.co/app/documents/interview/79727

**Comment by keyboard3** [comment]
这个站点注册似乎有点门槛，你可以把你现在的规删除掉，然后有问题的页面，通过沉浸式分享生成页面快照链接出来，我们就可以复现了

**Comment by keyboard3** [comment]
暂无反馈 关闭此issue
