### ISSUE TITLE
是否可以考虑支持智谱API

### ISSUE THREAD

**Issue by liuzj039** [immersive-translate/immersive-translate#1368]
### 您希望的更新和改进是什么 | Update or Improve

感谢开发者。这个插件相当好用。
这里是否可以考虑支持[智谱API](https://open.bigmodel.cn/usercenter/apikeys)。 这样可能可以更方便一部分用户。
再次感谢开发者。

**Comment by keyboard3** [comment]
智谱的API，我们测试过，翻译一篇外网的文章，36%的内容提示内容敏感，不允许翻译...
