### ISSUE TITLE
统一分享与生成网页快照的名称与按钮图标

### ISSUE THREAD

**Issue by XMB-7** [immersive-translate/immersive-translate#1369]
### 您希望的更新和改进是什么 | Update or Improve

在看文档时发现, 

![image](https://github.com/immersive-translate/immersive-translate/assets/65625632/4a168b63-2270-481c-8291-637dd0dd1ba0)

---

然而在当前版本中, 分享已经被改为了生成网页快照, 但是悬浮球这边却没有跟着改. 我还特意试了一下, 确认这俩按钮功能是一样的就是名字和图标不一样.

![image](https://github.com/immersive-translate/immersive-translate/assets/65625632/8a9612b1-78d4-4eee-b166-845386d92598)

---

顺便一提, 快捷键这边最好也改统一了.
![image](https://github.com/immersive-translate/immersive-translate/assets/65625632/19de2b51-604a-451e-8065-8740e0ef4672)

![image](https://github.com/immersive-translate/immersive-translate/assets/65625632/80a96d8d-ffa6-4499-8dd5-8f79acf32b29)

**Comment by theowenyoung** [comment]
谢谢，下个版本将会统一为生成网页快照。

**Comment by keyboard3** [comment]
1.1.9 已调整
