### ISSUE TITLE
[Bug]: 当设置点击悬浮球行为是打开面板时, 对侧栏的两个功能按钮, 鼠标划过依然显示相应信息浮窗.

### ISSUE THREAD

**Issue by XMB-7** [immersive-translate/immersive-translate#1370]
### 插件版本号 | Version

1.1.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug
当设置点击悬浮球的行为是打开插件面板时, 

![image](https://github.com/immersive-translate/immersive-translate/assets/65625632/a1436ff7-593f-4254-aa8d-41dc756019b7)

对侧栏的两个功能按钮, 鼠标划过依然能看到按钮信息提示浮窗.
 
![ScreenCapture_20240126-004824](https://github.com/immersive-translate/immersive-translate/assets/65625632/6086ad21-d334-4da3-bd1f-3a67aab13b35)

**Comment by keyboard3** [comment]
1.2.1 已修复
