### ISSUE TITLE
翻译本地PDF字体无法改变

### ISSUE THREAD

**Issue by szc1hotg** [immersive-translate/immersive-translate#1372]
### 您希望的更新和改进是什么 | Update or Improve

翻译本地PDF字体无法改变
希望能
![q1](https://github.com/immersive-translate/immersive-translate/assets/124563490/c5c2609c-81b2-46cf-8069-965497a18e5d)
在“控制样式”中加入字体设置及字体大小设置功能
沉浸式翻译是一个很棒的工具，
预祝越做越好：）
![q1](https://github.com/immersive-translate/immersive-translate/assets/124563490/8e7ce63c-7a91-4685-9cb4-ebbebc3ff211)

![q2](https://github.com/immersive-translate/immersive-translate/assets/124563490/28404aef-1f5a-4e15-a2eb-b5ef9e6a1ca9)

**Comment by keyboard3** [comment]
1.1.9 译文支持字体样式
