### ISSUE TITLE
brave浏览器的翻译实在是太不好用了，上架brave插件

### ISSUE THREAD

**Issue by yangchenguang94** [immersive-translate/immersive-translate#1374]
### 您希望的更新和改进是什么 | Update or Improve

brave浏览器的翻译实在是太不好用了，上架brave插件😊

**Comment by FattySpring** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/25144301/867968e8-5339-4145-a789-ea0c873223f6)

brave 浏览器用的就是 chrome 插件，直接安装就好了
