### ISSUE TITLE
[Bug]:  IOS safari 译文显示样式【波浪线 】无效

### ISSUE THREAD

**Issue by VincentLeeCN** [immersive-translate/immersive-translate#1376]
### 插件版本号 | Version

1.1.8

### 平台 | Platform

iOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

 IOS safari 译文显示样式【波浪线 】无效，chrome正常

**Comment by keyboard3** [comment]
1.1.9 已支持
