### ISSUE TITLE
[Bug]: 浏览器深色模式，使用翻译HTML/txt文件，看不见字。

### ISSUE THREAD

**Issue by xiekunjvj** [immersive-translate/immersive-translate#1377]
### 插件版本号 | Version

V1.1.8

### 平台 | Platform

Windows, Android

### 浏览器 | Browsers

Firefox, Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension, 油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

当浏览器深色模式时，使用翻译HTML/txt文件的页面，字体都是黑灰色看不清楚，明确记得以前使用时字体是白色的（即深色模式白色字体/浅色模式黑色字体），看到麻烦请修复一下🙇🏻‍♀️

<img width="559" alt="Snipaste_2024-01-27_22-29-06" src="https://github.com/immersive-translate/immersive-translate/assets/69800855/6ebcf2ab-6f83-4df2-9f8d-49a8a14ac1cc">
<img width="948" alt="Snipaste_2024-01-27_22-29-41" src="https://github.com/immersive-translate/immersive-translate/assets/69800855/b5f8ddd7-9131-416c-b556-3aabb1851ff3">

### 出现问题的网址 | URL

https://app.immersivetranslate.com/html/

### 重现步骤 | To Reproduce

1.点击悬浮窗→更多→翻译HTML/txt文件
2.打开文件

### 补充说明 | Additional context

*经测试，更换历史版本/更换浏览器，在桌面端及移动端均无法解决字体看不清的问题。

**Comment by keyboard3** [comment]
<img width="689" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/13177744/bcbe84f7-69dd-4c10-8021-558726cce155">
再试下看

**Comment by xiekunjvj** [comment]
> <img alt="image" width="689" src="https://private-user-images.githubusercontent.com/13177744/300258036-bcbe84f7-69dd-4c10-8021-558726cce155.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NDI2OTMsIm5iZiI6MTcwNjQ0MjM5MywicGF0aCI6Ii8xMzE3Nzc0NC8zMDAyNTgwMzYtYmNiZTg0ZjctNjlkZC00YzEwLTgwMjEtNTU4NzI2Y2NlMTU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDExNDYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxODI5MzNhMThiODNjM2ZjMjQ0M2UyNDQ4OGU3NDZlMDMwYjI1Nzk0ODIxNjZjM2ZiNmFkZDY5NjIxODI0YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RMC5QRIEVIe1aSY3Xr5OWsXtX1kD0KgvHpyfe8IXXOQ"> 再试下看



> <img alt="image" width="689" src="https://private-user-images.githubusercontent.com/13177744/300258036-bcbe84f7-69dd-4c10-8021-558726cce155.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NDI2OTMsIm5iZiI6MTcwNjQ0MjM5MywicGF0aCI6Ii8xMzE3Nzc0NC8zMDAyNTgwMzYtYmNiZTg0ZjctNjlkZC00YzEwLTgwMjEtNTU4NzI2Y2NlMTU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDExNDYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxODI5MzNhMThiODNjM2ZjMjQ0M2UyNDQ4OGU3NDZlMDMwYjI1Nzk0ODIxNjZjM2ZiNmFkZDY5NjIxODI0YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RMC5QRIEVIe1aSY3Xr5OWsXtX1kD0KgvHpyfe8IXXOQ"> 再试下看

字体可以正常看清了！感谢修复

**Comment by xiekunjvj** [comment]
> <img alt="image" width="689" src="https://private-user-images.githubusercontent.com/13177744/300258036-bcbe84f7-69dd-4c10-8021-558726cce155.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NDI2OTMsIm5iZiI6MTcwNjQ0MjM5MywicGF0aCI6Ii8xMzE3Nzc0NC8zMDAyNTgwMzYtYmNiZTg0ZjctNjlkZC00YzEwLTgwMjEtNTU4NzI2Y2NlMTU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDExNDYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxODI5MzNhMThiODNjM2ZjMjQ0M2UyNDQ4OGU3NDZlMDMwYjI1Nzk0ODIxNjZjM2ZiNmFkZDY5NjIxODI0YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RMC5QRIEVIe1aSY3Xr5OWsXtX1kD0KgvHpyfe8IXXOQ"> 再试下看

字体可以正常看清了！感谢修复
