### ISSUE TITLE
提供全文片段的OCR识别

### ISSUE THREAD

**Issue by AllenBob1973** [immersive-translate/immersive-translate#1378]
### 您希望的更新和改进是什么 | Update or Improve

1.某些片段翻译不准确，比如模糊或者页面跳转时不能准确翻译。
2.某些论文是双栏排版，实现单栏报告式排版
3.识别出的公式准确率差，公式不能单独提取

### 补充说明 | Additional context

可以参考ChatDoc的那种OCR识别，以及公式提取出Latex代码

**Comment by keyboard3** [comment]
暂无计划做OCR，论文PDF 建议采用专业的第三方工具识别，如mathpix 或者 参考这里的 nougat 在线推理 https://immersivetranslate.com/docs/pdf/nougat/
