### ISSUE TITLE
[Bug]: 断行错误（错误地把一段原文打断成多段）

### ISSUE THREAD

**Issue by seigwen** [immersive-translate/immersive-translate#1379]
### 插件版本号 | Version

1.1.8

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

翻译时断行错误（错误地把一段原文打断成多段）：
![断行错误](https://github.com/immersive-translate/immersive-translate/assets/38581695/ab4b9e1b-b15c-49b0-bc13-edfd0955e66d)

### 出现问题的网址 | URL

https://ethereum.org/en/developers/tutorials/scam-token-tricks

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/ea88f588-6285-4d59-b965-71106438217b)
打开 https://dash.immersivetranslate.com/abount#about 刷新下规则
