### ISSUE TITLE
[Feature Request] Want support for Azure Congnitive Services Translator

### ISSUE THREAD

**Issue by hcoona** [immersive-translate/immersive-translate#138]
https://learn.microsoft.com/en-us/azure/cognitive-services/translator/text-translation-overview

**Comment by theowenyoung** [comment]
OK👌 感谢建议

**Comment by theowenyoung** [comment]
The latest version has released, now we can use Microsoft translate

**Comment by hcoona** [comment]
试了一下一直 401 错误，我应该怎么提供一些细节呢？

![image](https://user-images.githubusercontent.com/712433/220501124-dfb2f0e2-6107-4e4d-bc5c-19bd77287634.png)

![image](https://user-images.githubusercontent.com/712433/220501402-7a6b1c05-8cba-443b-9221-06849bcc891a.png)

```json
{
    "id": 3,
    "url": "https://b0137e536d5b6fcdf3559083bfcd77b1fa93ac9bba99123be66756386602f2b6.com/6e282d33ab1be873fcc592bb128c1f6c8c73a769ba1af335855492998b4a93ab",
    "text": " Participants ",
    "from": "en",
    "fromByClient": "auto",
    "to": "zh-CN"
}
```

**Comment by hcoona** [comment]
我觉得你是不是没考虑到 region 可能不一样？我看文档要求提供 region，但是你的配置里面没有地方填。

https://learn.microsoft.com/en-us/azure/cognitive-services/translator/quickstart-translator?tabs=nodejs

**Comment by theowenyoung** [comment]
确实～

我修复一下

**Comment by theowenyoung** [comment]
目前似乎写死的是 `eastasia`

**Comment by theowenyoung** [comment]
可以了 0.2.65版本支持设置region了～ 再试试呢

**Comment by hcoona** [comment]
Works perfectly! Thank you for bring such an amazing tool!
