### ISSUE TITLE
[Bug]: “总是翻译”和“永不翻译”网址设置无效

### ISSUE THREAD

**Issue by glongzh** [immersive-translate/immersive-translate#1381]
### 插件版本号 | Version

1.1.8

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

已经将“总是翻译的网址”清空，甚至加入到“永不翻译的网址”，但还是会自动翻译HN网站。
![屏幕截图 2024-01-29 095308](https://github.com/immersive-translate/immersive-translate/assets/1331163/4aa8711a-f807-486b-bb50-af22d77e2f9f)
![屏幕截图 2024-01-29 095412](https://github.com/immersive-translate/immersive-translate/assets/1331163/a8b05341-3adf-4673-be43-85c92c3f2b72)

### 出现问题的网址 | URL

https://news.ycombinator.com/news

**Comment by FattySpring** [comment]
我这里测试的是生效的，看面板的状态是未翻译的，在隐私窗口试下？
