### ISSUE TITLE
[Bug]: 網站翻譯後連結皆變成純文字無法點選

### ISSUE THREAD

**Issue by curtiswu33** [immersive-translate/immersive-translate#1383]
### 插件版本号 | Version

1.1.8

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

網站翻譯後連結皆變成純文字無法點選。

### 出现问题的网址 | URL

https://www.sixsenses.com/en/resorts/crans-montana

**Comment by keyboard3** [comment]
重复 #1296
