### ISSUE TITLE
[Bug]: 进入视频后不显示双语字幕甚至单语也无法显示

### ISSUE THREAD

**Issue by Muuzzziiy** [immersive-translate/immersive-translate#1384]
### 插件版本号 | Version

1.1.8

### 请描述这个Bug | Describe the bug

Youtube 上看视频选择打开字幕以及沉浸式翻译但是不起作用，不显示双语字母，只会一瞬间出来一下然后消失，这是啥问题？？？

![1](https://github.com/immersive-translate/immersive-translate/assets/153975850/002334aa-0fd7-44e5-8138-e056af47b5f2)

### 出现问题的网址 | URL

https://www.youtube.com/watch?v=65iwnI2hjAA&t=946s

### 重现步骤 | To Reproduce

点进视频，然后字幕默认打开，但是没有字幕出现

### 补充说明 | Additional context

我另外还有一个插件是Youtube双字幕这个插件但是已经被我ban了是不是这个插件影响了？

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/4f449bc6-2b62-4471-8450-e212338374af)
我这边挺正常的，字幕用了啥翻译服务？ 刷新也不行吗？

**Comment by Muuzzziiy** [comment]
我之前是俩翻译服务一起开着就是我说的那个Youtube双字幕插件，然后就出bug了，我明天起来电脑重启一下看看解决没有吧，感觉像是俩插件在一起结果卡住了
________________________________
发件人: keyboard3 ***@***.***>
发送时间: 2024年1月29日 22:08
收件人: immersive-translate/immersive-translate ***@***.***>
抄送: 1 ***@***.***>; Author ***@***.***>
主题: Re: [immersive-translate/immersive-translate] [Bug]: 进入视频后不显示双语字幕甚至单语也无法显示 (Issue #1384)


image.png (view on web)<https://github.com/immersive-translate/immersive-translate/assets/13177744/4f449bc6-2b62-4471-8450-e212338374af>
我这边挺正常的，字幕用了啥翻译服务？ 刷新也不行吗？

―

**Comment by Askyocket** [comment]
我目前看Youtube也是显示不到字幕，可以怎么处理呢？

**Comment by shiquda** [comment]
> https://github.com/immersive-translate/immersive-translate/issues/1384#issuecomment-1915255252
是这个原因，我关了就好了

**Comment by Muuzzziiy** [comment]
> > 我之前是俩翻译服务一起开着就是我说的那个Youtube双字幕插件，然后就出bug了，我明天起来电脑重启一下看看解决没有吧，感觉像是俩插件在一起结果卡住了
> 
> 是这个原因，我关了就好了

哦哦好的

**Comment by robertdowney21** [comment]
我也有这个问题

**Comment by Muuzzziiy** [comment]
我的已经好了，就是插件冲突
________________________________
发件人: robertdowney21 ***@***.***>
发送时间: 2024年2月1日 9:14
收件人: immersive-translate/immersive-translate ***@***.***>
抄送: 1 ***@***.***>; Author ***@***.***>
主题: Re: [immersive-translate/immersive-translate] [Bug]: 进入视频后不显示双语字幕甚至单语也无法显示 (Issue #1384)


我也有这个问题

―

**Comment by robertdowney21** [comment]
我吧所有插件都关了，还是没有双语字幕

**Comment by Muuzzziiy** [comment]
你重启一下试试
________________________________
发件人: robertdowney21 ***@***.***>
发送时间: 2024年2月1日 11:18
收件人: immersive-translate/immersive-translate ***@***.***>
抄送: 1 ***@***.***>; Author ***@***.***>
主题: Re: [immersive-translate/immersive-translate] [Bug]: 进入视频后不显示双语字幕甚至单语也无法显示 (Issue #1384)


我吧所有插件都关了，还是没有双语字幕

―

**Comment by Muuzzziiy** [comment]
你把那个插件卸载重启试一下
________________________________
发件人: robertdowney21 ***@***.***>
发送时间: 2024年2月1日 11:18
收件人: immersive-translate/immersive-translate ***@***.***>
抄送: 1 ***@***.***>; Author ***@***.***>
主题: Re: [immersive-translate/immersive-translate] [Bug]: 进入视频后不显示双语字幕甚至单语也无法显示 (Issue #1384)


我吧所有插件都关了，还是没有双语字幕

―
