### ISSUE TITLE
翻译服务能否设置成多个？并且根据不同的条件选不同的服务。

### ISSUE THREAD

**Issue by ugvfpdcuwfnh** [immersive-translate/immersive-translate#1385]
### 您希望的更新和改进是什么 | Update or Improve

我需要根据不同的语言，选择不同的翻译服务。

比如，当翻译英语时，我选择“deepl”，当翻译波斯语时，我选择“谷歌翻译”。

但是现在翻译服务只能选一个，碰到不同的网页，要自己去手动更改，比较麻烦。

**Comment by flamintune** [comment]
目前仅支持对于不同网站配置不同的翻译服务，对于语言级别的配置的话暂时还不支持，或许暂时可以通过这种方式解决你的需求：把主要内容为波斯语的网站配置成用来谷歌翻译，详细参考这里的配置文档：https://immersivetranslate.com/docs/advanced/#%E5%A6%82%E4%BD%95%E8%AE%A9%E4%B8%8D%E5%90%8C%E7%9A%84%E7%AB%99%E7%82%B9%E9%BB%98%E8%AE%A4%E9%80%89%E6%8B%A9%E4%B8%8D%E5%90%8C%E7%9A%84%E7%BF%BB%E8%AF%91%E6%9C%8D%E5%8A%A1%E4%BE%8B%E5%A6%82%E6%9C%89%E7%9A%84%E7%BD%91%E7%AB%99%E6%88%91%E6%83%B3%E8%A6%81%E5%A5%BD%E4%B8%80%E7%82%B9%E4%BD%86%E8%A6%81%E8%8A%B1%E9%92%B1%E7%9A%84%E7%BF%BB%E8%AF%91%E6%95%88%E6%9E%9C%E6%9C%89%E7%9A%84%E7%BD%91%E7%AB%99%E6%88%91%E5%8F%AA%E9%9C%80%E8%A6%81%E5%85%8D%E8%B4%B9%E8%83%BD%E7%9C%8B%E7%9A%84%E7%BF%BB%E8%AF%91%E5%B0%B1%E8%A1%8C%E4%BA%86
