### ISSUE TITLE
[Bug]: 翻译本地epub文件乱码的问题

### ISSUE THREAD

**Issue by Alfred-Windsor** [immersive-translate/immersive-translate#1386]
### 插件版本号 | Version

1.1.8

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

翻译本地epub文件后，导出的 epub文件在一些阅读软件中会报错乱码（喜马拉雅、讯飞有声等），直接读取英文原件或者其他原生中文的epub书籍时没有问题。

**Comment by keyboard3** [comment]
文件发过来看下

**Comment by Alfred-Windsor** [comment]
[epub.zip](https://github.com/immersive-translate/immersive-translate/files/14100119/epub.zip)
比如这个文件，在某些软件里面可以正常显示，某些软件里面就会无法打开或者乱码变成 ☒☒☒。

使用Sigil打开会报错：
![bug](https://github.com/immersive-translate/immersive-translate/assets/152876591/9295bcf2-12db-4e23-879d-7e67beaca21d)
修复后可以打开，所有文字都会变为空白页。
