### ISSUE TITLE
翻译本地PDF时，网页标题显示为文件名称

### ISSUE THREAD

**Issue by GBEYOND0613** [immersive-translate/immersive-translate#1388]
### 您希望的更新和改进是什么 | Update or Improve

有 3 种方式可以翻译本地PDF，但是只有一种方式可以将标签页标题显示为文件名称

### 补充说明 | Additional context

3 种翻译本地PDF方式及其对应结果

1. 点击图标->右下角`更多`->`翻译本地PDF文件`
   <img width="812" alt="更多-翻译本地PDF" src="https://github.com/immersive-translate/immersive-translate/assets/57569566/ba3861a6-b54d-40fe-ae35-29aa11097b9d">

2. 点击图标->左下角`PDF/ePub`->拖入文件或选择文件
    此种情况下, 有时可以将标题显示为文件名
   <img width="829" alt="翻译PDF" src="https://github.com/immersive-translate/immersive-translate/assets/57569566/97e0950f-f037-4a79-9ce7-504ddb1e603c">
   <img width="850" alt="pdfjs有时可以正常出标题" src="https://github.com/immersive-translate/immersive-translate/assets/57569566/75594341-07a7-4a46-97c2-ed5d9ae213bd">

3. 在浏览器打开PDF文件->点击图标->点击`点击翻译PDF`
   <img width="816" alt="直接翻译" src="https://github.com/immersive-translate/immersive-translate/assets/57569566/7b38ccc5-750f-4663-ab72-123cd78da6ff">

**Comment by flamintune** [comment]
1 没成功复现
2 已实现该功能
3 请及时更新插件最新版本。
目前统一展示的title为 "<pdf文件提取出的title的翻译> - <pdf文件名的翻译> --- <pdf文件提取出的title> - <pdf文件名>" 如果pdf文件没有title信息，则不展示title信息，直接展示文件名

**Comment by GBEYOND0613** [comment]
已更新为最新版本：
1. 已解决
2. 已解决
3. 变成之前的第二种情况
    ![image](https://github.com/immersive-translate/immersive-translate/assets/57569566/4c319a09-2e2f-4a8e-b400-edcc90e8a923)

**Comment by flamintune** [comment]
最后一种情况已经在最新的插件版本v1.2.1支持了
