### ISSUE TITLE
翻译本地PDF时, 会添加白色边框, 占用屏幕空间

### ISSUE THREAD

**Issue by GBEYOND0613** [immersive-translate/immersive-translate#1389]
### 您希望的更新和改进是什么 | Update or Improve

统一翻译本地PDF时的阅读器样式, 删除冗余白边

### 补充说明 | Additional context

3 种翻译本地PDF方式及其对应结果, 只有第3种方式会产生白边, 详情见下图

1. 点击图标->右下角`更多`->`翻译本地PDF文件`
  <img width="812" alt="更多-翻译本地PDF" src="https://github.com/immersive-translate/immersive-translate/assets/57569566/8e1b7011-c1bf-462f-8915-dee2f8e652dc">

2. 点击图标->左下角`PDF/ePub`->拖入文件或选择文件
   <img width="829" alt="翻译PDF" src="https://github.com/immersive-translate/immersive-translate/assets/57569566/732c12d2-cefc-4580-917e-a95e49452007">

3. 在浏览器打开PDF文件->点击图标->点击`点击翻译PDF`
   <img width="816" alt="直接翻译" src="https://github.com/immersive-translate/immersive-translate/assets/57569566/b7456ea0-9a70-4533-99fa-6c235fbab735">

**Comment by keyboard3** [comment]
1.2.0 已解决

**Comment by GBEYOND0613** [comment]
没有解决, 我的版本是1.2.1, 但是通过快捷键翻译PDF的时候还是会有白边
