### ISSUE TITLE
可以加入某些翻譯服務的簡轉繁功能嗎？

### ISSUE THREAD

**Issue by Minidoracat** [immersive-translate/immersive-translate#139]
有些翻譯服務沒有提供繁體中文
比如 DeepL API ，請問可以再提供進一步的簡轉繁功能嗎？
不一定要用語轉換，可以先直接 google 翻譯簡轉繁

如果要用語轉換，我覺得這個會是不錯的選擇
[https://github.com/BYVoid/OpenCC](https://github.com/BYVoid/OpenCC)

**Comment by theowenyoung** [comment]
好的~ 可以做，但是需要一点时间

**Comment by theowenyoung** [comment]
客户端似乎只能用这个库： https://github.com/nk2028/opencc-js

**Comment by theowenyoung** [comment]
本地测试了一下，是可行的.. 但是引入后，大小会多 2M 多一点.

在扩展里包含还可以，如果在油猴里包含的话，似乎有点太大了？ 油猴脚本本来是700多K，加了这个之后会变成 2.9M

**Comment by theowenyoung** [comment]
可以了，最新发布的 0.2.61 版本的 deepl 已支持繁体～ 

暂时先关掉这个问题了～ 有问题再打开～

**Comment by amias1024** [comment]
作者好，最近使用發現 DeepLX 也需要這個支持，希望有空可以增加一下～
