### ISSUE TITLE
翻译文献时, 在控制样式中选择带图模式时会出现原文遮盖不全,而取消带图模式时就能完全遮盖

### ISSUE THREAD

**Issue by GBEYOND0613** [immersive-translate/immersive-translate#1390]
### 您希望的更新和改进是什么 | Update or Improve

在带图模式时也可以完整覆盖原文, 不然很影响阅读, 同时阅读到图片时, 重新勾选重新翻译, 影响阅读

### 补充说明 | Additional context

带图模式时覆盖不全: 
<img width="1280" alt="有图模式" src="https://github.com/immersive-translate/immersive-translate/assets/57569566/3b0c3216-7380-4cc1-b953-c16d0a06350c">
<img width="1280" alt="有图模式2" src="https://github.com/immersive-translate/immersive-translate/assets/57569566/6ceb570b-67cf-4b31-b2ad-e14d170f3c10">

取消勾选`带图模式`后
<img width="1280" alt="无图模式" src="https://github.com/immersive-translate/immersive-translate/assets/57569566/5b6e4573-7177-4e32-ada4-492c8afff58b">

**Comment by keyboard3** [comment]
你这个pdf应该是经过OCR处理的导致显示和原始数据的坐标无法完全对上。带图模式目的是为了让标准pdf能够同时展示文本和图片。当出现这种情况时，建议关闭带图模式
