### ISSUE TITLE
是否可以增加ChatGPT(Web)版以及微軟Copilot的翻譯選項？

### ISSUE THREAD

**Issue by ainlee** [immersive-translate/immersive-translate#1392]
### 您希望的更新和改进是什么 | Update or Improve

建議增加ChatGPT(Web)版以及微軟Copilot的翻譯選項，這算是免費資源，效果也比Bing翻譯或Google翻譯要強的多！

**Comment by akira0245** [comment]
附议 OpenAI Translator的Chatgpt Web模式就非常好用 希望这边也能加入

**Comment by theowenyoung** [comment]
ChatGPT web 版频率限制严格，不适合作为网页翻译的后端服务，未来应该不会考虑接入。
