### ISSUE TITLE
[Bug]: 翻译表格时出现错位

### ISSUE THREAD

**Issue by 1ilin** [immersive-translate/immersive-translate#1396]
### 插件版本号 | Version

1.1.9

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

如图，本应在右侧的文字出现在左侧
![image](https://github.com/immersive-translate/immersive-translate/assets/111619610/aab47df6-abee-4e6c-8655-ace0ee386127)

### 出现问题的网址 | URL

https://www.mysqltutorial.org/mysql-window-functions/

### 补充说明 | Additional context

用微软翻译、Gemini均出现此状况，其他引擎没试，推测是插件的排版问题

**Comment by keyboard3** [comment]
微软正常的，只有gemini才会有问题，因为gemini大模型是多个段落合并请求，它有时候不一定会严格按照同等段落数量返回。 这个没啥好办法，只能建议适当去设置页调低gemini段落数量
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/f6080d43-191e-46ee-8ec2-395a14237cc7)
