### ISSUE TITLE
[Bug]: google news的for you页面在页面加载更多后，之前的翻译会消失。

### ISSUE THREAD

**Issue by freedomspiritJohn** [immersive-translate/immersive-translate#1397]
### 插件版本号 | Version

1.1.9

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/129288685/c11c308a-5dae-4f36-997c-8bf436a3c45b)

### 出现问题的网址 | URL

https://news.google.com/foryou?gl=US&ceid=US:en&hl=en-US

### 重现步骤 | To Reproduce

往下扒拉

**Comment by keyboard3** [comment]
这个是谷歌网站的特殊处理，再加载下一页的时候，它还会清空上一页第三方插件添加的内容，这个目前没有好的办法处理
