### ISSUE TITLE
[Bug]:在用Youtube 双语字幕時會遇到直接顯示整部影片字幕的翻譯，然後就只會顯示原本生成的字幕 。

### ISSUE THREAD

**Issue by TACHIEN0525** [immersive-translate/immersive-translate#1398]
### 插件版本号 | Version

1.1.9

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在用Youtube 双语字幕時會遇到直接顯示整部影片字幕的翻譯，然後就只會顯示原本生成的字幕 。

### 出现问题的网址 | URL

https://www.youtube.com/watch?v=o1VBeNJ3wfI&list=PLkz_y24mlSJZJx9sQJCyFZt50S4ji1PeR&index=2

**Comment by keyboard3** [comment]
这里有处理方案 https://immersivetranslate.com/docs/faq/#youtube-%E5%8F%8C%E8%AF%AD%E5%AD%97%E5%B9%95%E7%B9%81%E4%BD%93%E4%B8%AD%E6%96%87%E4%B8%8D%E6%98%BE%E7%A4%BA

YouTube 自带机翻字幕，繁体中文会出现格式错误，导致所有字幕在开始的时候弹出一大段字幕，基于此场景建议在【设置】【视频字幕】中开启​​【使用沉浸式翻译来翻译字幕】选项。

**Comment by hjie** [comment]
开启【使用沉浸式翻译来翻译字幕】选项，问题还是存在
