### ISSUE TITLE
[Bug] Web of science 翻译显示不全

### ISSUE THREAD

**Issue by QuanYizhang** [immersive-translate/immersive-translate#140]
示例网站：https://www.webofscience.com/wos/woscc/summary/8abaed21-db9e-4569-935d-3b39837d3761-70a32e2c/relevance/1

进入wos后，翻译无法正常显示标题
![image](https://user-images.githubusercontent.com/71176371/218950317-a1f6beb4-23ee-4fce-9a01-17cb4e6f8c20.png)
![image](https://user-images.githubusercontent.com/71176371/218950352-01aa1e0f-9e58-4cdb-9c1d-3900853a2aee.png)

**Comment by crocodile2021** [comment]
抱歉，这个网站我没办法注册和登入，如果你方便的话可以私聊我一个账号进行测试～

**Comment by QuanYizhang** [comment]
麻烦您能给我一下您的邮箱或者其他联系方式吗？我将账号发给您，用于测试。

**Comment by crocodile2021** [comment]
嗯嗯，邮箱地址：owen@owenyoung.com。感谢反馈～

**Comment by QuanYizhang** [comment]
已经发送了，感谢开发者！

**Comment by crocodile2021** [comment]
已调整适配，不过要等下个版本发布，大概一到两天后～

**Comment by QuanYizhang** [comment]
感谢开发者！你们辛苦啦！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月17日(周五) 晚上9:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [immersive-translate/immersive-translate] [Bug] Web of science 翻译显示不全 (Issue #140)




 
已调整适配，不过要等下个版本发布，大概一到两天后～

**Comment by theowenyoung** [comment]
新版已经发布了，商店版还在审核～

暂时关掉这个问题，有问题再打开。
