### ISSUE TITLE
dmg文件安装包里的离线网页无法翻译

### ISSUE THREAD

**Issue by yuzhidu** [immersive-translate/immersive-translate#1401]
### 您希望的更新和改进是什么 | Update or Improve

修复这个问题

### 补充说明 | Additional context

我从https://www.wireshark.org/下载了wireshark安装包，里边有个read me first.html文件，我双击使用Edge打开，没有看到悬浮翻译窗口，网页右键的翻译网页/显示原文也不能用

**Comment by yuzhidu** [comment]
我在 Mac 上使用 Edge 作为默认浏览器，从Edge扩展安装的沉浸式翻译插件

**Comment by keyboard3** [comment]
给插件访问本地文件的权限就可以了
