### ISSUE TITLE
[Bug]: google search Generative AI is experimental 翻译断句有问题

### ISSUE THREAD

**Issue by thomasTAT** [immersive-translate/immersive-translate#1402]
### 插件版本号 | Version

1.1.9

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/109513632/645e6416-0118-406b-8e96-57a779b0582c)

![image](https://github.com/immersive-translate/immersive-translate/assets/109513632/6b99d4fc-7541-4e6f-95ba-1b0bd7c72142)

### 出现问题的网址 | URL

https://www.google.com/search?q=dentist+implant&newwindow=1&sca_esv=ed897b2776f2f88d&biw=1270&bih=1308&sxsrf=ACQVn08ZCdUGw19sdDA32dADPKq2njpFWQ%3A1707030230411&ei=1ja_ZdS6GPe0qtsPmsOpgAs&ved=0ahUKEwjU_YOUj5GEAxV3mmoFHZphCrAQ4dUDCBA&uact=5&oq=dentist+implant&gs_lp=Egxnd3Mtd2l6LXNlcnAiD2RlbnRpc3QgaW1wbGFudDIEECMYJzIFEAAYgAQyBRAAGIAEMgUQABiABDIFEAAYgAQyBxAAGIAEGAoyBxAAGIAEGAoyBRAAGIAEMgUQABiABDIFEAAYgARInkVQAFjXP3AGeAGQAQCYAacFoAGRL6oBCjItMTMuMC4yLjO4AQPIAQD4AQHCAgoQIxiABBiKBRgnwgILEC4YgAQYigUYkQLCAhEQLhiABBixAxiDARjHARjRA8ICCBAuGIAEGLEDwgIOEC4YgAQYsQMYxwEY0QPCAgoQABiABBiKBRhDwgIKEC4YgAQYigUYQ8ICERAuGIMBGMcBGLEDGNEDGIAEwgIIEAAYgAQYsQPCAggQABiABBiSA8ICCxAAGIAEGIoFGJIDwgILEAAYgAQYsQMYyQPCAggQLhixAxiABMICCxAAGIAEGLEDGIMBwgIHECMYsQIYJ8ICChAAGIAEGAoYkgPCAhAQABiABBgKGLEDGLEDGMkDwgINEAAYgAQYChixAxiDAcICChAAGIAEGAoYsQPCAgoQABiABBjJAxgK4gMEGAAgQQ&sclient=gws-wiz-serp

**Comment by flamintune** [comment]
能麻烦给个网址不，方便复现调试

**Comment by thomasTAT** [comment]
> 能麻烦给个网址不，方便复现调试

已增加

**Comment by flamintune** [comment]
还是有点难复现，能麻烦通过生成网页快照的形式来分享不，详细方法为打开沉浸式翻译悬浮球，然后点击生成网页快照，最后会得到一个url，请将这个url分享一下哈，尽量是没有经过翻译的网页快照
![6296e559-3c91-41cb-9b34-7bb079b3dae8](https://github.com/immersive-translate/immersive-translate/assets/79519446/636e7940-24f4-4c9e-afcb-3d620875b606)
![image](https://github.com/immersive-translate/immersive-translate/assets/79519446/4825527a-c674-4ce9-8bd7-a10324948884)
![image](https://github.com/immersive-translate/immersive-translate/assets/79519446/b8bed4ff-07e5-4d88-9cd0-5afe2ec0a757)

**Comment by thomasTAT** [comment]
> 我这边的翻译过后的结果与你那边的结果不同，能麻烦通过生成网页快照的形式来分享不，详细方法为打开沉浸式翻译悬浮球，然后点击生成网页快照，最后会得到一个url，请将这个url分享一下哈，尽量是没有经过翻译的网页快照 ![6296e559-3c91-41cb-9b34-7bb079b3dae8](https://private-user-images.githubusercontent.com/79519446/302161365-636e7940-24f4-4c9e-afcb-3d620875b606.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NTIzNzYsIm5iZiI6MTcwNzU1MjA3NiwicGF0aCI6Ii83OTUxOTQ0Ni8zMDIxNjEzNjUtNjM2ZTc5NDAtMjRmNC00YzllLWFmY2ItM2Q2MjA4NzViNjA2LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMFQwODAxMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2E2Y2ZkOTczMTUxYWFjMTk3YzkzNjhmZTZhOGJhN2ZmYzJjN2FmYjFjMzUxMWZkMDMwYjEwMjkzMDI4NzZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UN14yma_hWD5MFtRPMd1y-fFswS-bWVIotDor33Qbkg) ![image](https://private-user-images.githubusercontent.com/79519446/302161512-4825527a-c674-4ce9-8bd7-a10324948884.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NTIzNzYsIm5iZiI6MTcwNzU1MjA3NiwicGF0aCI6Ii83OTUxOTQ0Ni8zMDIxNjE1MTItNDgyNTUyN2EtYzY3NC00Y2U5LThiZDctYTEwMzI0OTQ4ODg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEwVDA4MDExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxYmZjNGUwOTU3MzEzOGVlMTY2YjZiNjhiNjFkYzMwMTcwZmRlODU4Y2NhODkwZTcyMTQ1MGYzY2UxNTk0NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dPbMxxxT_a8P3ZRQcjl3OhrC3OJ2cXpLjkFYfBs8Bew) ![image](https://private-user-images.githubusercontent.com/79519446/302161614-b8bed4ff-07e5-4d88-9cd0-5afe2ec0a757.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NTIzNzYsIm5iZiI6MTcwNzU1MjA3NiwicGF0aCI6Ii83OTUxOTQ0Ni8zMDIxNjE2MTQtYjhiZWQ0ZmYtMDdlNS00ZDg4LTljZDAtNWFmZTJlYzBhNzU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEwVDA4MDExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiMzg4ZWJjNDM5NzcxMzBlZDNkNGM3MjNmNDNlNjJiNWMzMDRlNmFmMjhkMzJlZmU5OTcwNzlmZWMzZDA1MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EVoCl307XvsDUQ-faZqk7lgXyU5P8ArAnfIaV6umkYg)

https://readit.site/a/u9dzF/search

**Comment by keyboard3** [comment]
> > 我这边的翻译过后的结果与你那边的结果不同，能麻烦通过生成网页快照的形式来分享不，详细方法为打开沉浸式翻译悬浮球，然后点击生成网页快照，最后会得到一个url，请将这个url分享一下哈，尽量是没有经过翻译的网页快照 ![6296e559-3c91-41cb-9b34-7bb079b3dae8](https://private-user-images.githubusercontent.com/79519446/302161365-636e7940-24f4-4c9e-afcb-3d620875b606.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NTIzNzYsIm5iZiI6MTcwNzU1MjA3NiwicGF0aCI6Ii83OTUxOTQ0Ni8zMDIxNjEzNjUtNjM2ZTc5NDAtMjRmNC00YzllLWFmY2ItM2Q2MjA4NzViNjA2LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMFQwODAxMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2E2Y2ZkOTczMTUxYWFjMTk3YzkzNjhmZTZhOGJhN2ZmYzJjN2FmYjFjMzUxMWZkMDMwYjEwMjkzMDI4NzZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UN14yma_hWD5MFtRPMd1y-fFswS-bWVIotDor33Qbkg) ![image](https://private-user-images.githubusercontent.com/79519446/302161512-4825527a-c674-4ce9-8bd7-a10324948884.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NTIzNzYsIm5iZiI6MTcwNzU1MjA3NiwicGF0aCI6Ii83OTUxOTQ0Ni8zMDIxNjE1MTItNDgyNTUyN2EtYzY3NC00Y2U5LThiZDctYTEwMzI0OTQ4ODg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEwVDA4MDExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxYmZjNGUwOTU3MzEzOGVlMTY2YjZiNjhiNjFkYzMwMTcwZmRlODU4Y2NhODkwZTcyMTQ1MGYzY2UxNTk0NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dPbMxxxT_a8P3ZRQcjl3OhrC3OJ2cXpLjkFYfBs8Bew) ![image](https://private-user-images.githubusercontent.com/79519446/302161614-b8bed4ff-07e5-4d88-9cd0-5afe2ec0a757.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NTIzNzYsIm5iZiI6MTcwNzU1MjA3NiwicGF0aCI6Ii83OTUxOTQ0Ni8zMDIxNjE2MTQtYjhiZWQ0ZmYtMDdlNS00ZDg4LTljZDAtNWFmZTJlYzBhNzU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEwVDA4MDExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiMzg4ZWJjNDM5NzcxMzBlZDNkNGM3MjNmNDNlNjJiNWMzMDRlNmFmMjhkMzJlZmU5OTcwNzlmZWMzZDA1MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EVoCl307XvsDUQ-faZqk7lgXyU5P8ArAnfIaV6umkYg)
> 
> https://readit.site/a/u9dzF/search
> 
> https://readit.site/a/aHjNF/search

已适配 更新下规则 https://dash.immersivetranslate.com/abount#about 。然后重试下
