### ISSUE TITLE
[Bug]: 输入框增强, `/英文 你好世界` -> `/English Hello world`, 而非`Hello world`.

### ISSUE THREAD

**Issue by XMB-7** [immersive-translate/immersive-translate#1403]
### 插件版本号 | Version

1.1.7

### 请描述这个Bug | Describe the bug

如题. 
而`/英语 你好世界`就能正常地翻译为`Hello world`.

**Comment by keyboard3** [comment]
我这边试着正常。 你截图下你输入增强页面的配置

**Comment by XMB-7** [comment]
![ScreenCapture_20240203-193943](https://github.com/immersive-translate/immersive-translate/assets/65625632/fd33a385-6e67-41c6-a5b8-4549457d36c4)

我又试了一下, 是模型的问题, 选3.5-turbo-1106就这样, 选3.5-turbo就正常.

**Comment by flamintune** [comment]
我选gpt-3.5-turbo-1106也还是正常的。请问这个问题还存在吗？能否给出详细的复现情况呢（输入增强页面配置+在哪个网页下的输入框出现的问题）？
