### ISSUE TITLE
请问双语字幕未来可否支持Kanopy？

### ISSUE THREAD

**Issue by sprindjack** [immersive-translate/immersive-translate#1404]
### 您希望的更新和改进是什么 | Update or Improve

这是一个电影/纪录片网站，但只提供了英文的字幕[www.kanopy.com](www.kanopy.com)

**Comment by keyboard3** [comment]
看不了哇，要图书馆卡好像

**Comment by sprindjack** [comment]
> 看不了哇，要图书馆卡好像

是的，需要图书馆购买了才能观看。搞一个读者证没啥难度。

**Comment by sprindjack** [comment]
> 看不了哇，要图书馆卡好像

我可以提供一个以供开发大佬测试

**Comment by keyboard3** [comment]
> > 看不了哇，要图书馆卡好像
> 
> 我可以提供一个以供开发大佬测试

加入tel 群 https://immersivetranslate.com/docs/communities/ 。然后找 keyboard3 私信我

**Comment by keyboard3** [comment]
已支持
