### ISSUE TITLE
[Bug]: 转换后的epub无法满足epubcheck，也可能导致了无法用pandoc转化epub

### ISSUE THREAD

**Issue by GuangDai** [immersive-translate/immersive-translate#1408]
### 插件版本号 | Version

1.2.0

### 平台 | Platform

Linux

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

https://www.bookmarketing.pro/epub-validator.html

翻译后的文件在epubcheck后会出现
![image](https://github.com/immersive-translate/immersive-translate/assets/59678726/ac339e77-640f-4b60-9553-704682727b08)

而且无法用pandoc转为md文件

![image](https://github.com/immersive-translate/immersive-translate/assets/59678726/81bba3d2-d895-4035-a3a9-5d01ba0f0a0c)

**Comment by flamintune** [comment]
能否给下你的epub文件呢？我试了下转成双语之后基本都可以用pandoc转换成markdown，暂时都没出现图中的无法提取epub文件的情况，只是可能存在转换后的markdown，不是很规则，后续会优化相关代码

**Comment by GuangDai** [comment]
[Archive.zip](https://github.com/immersive-translate/immersive-translate/files/14211834/Archive.zip)

**Comment by GuangDai** [comment]
和pandoc有关系，我用的某个项目是自己内置了一个pandoc，该pandoc无法解析，arch从仓库安装的是可以解析
[pandoc.zip](https://github.com/immersive-translate/immersive-translate/files/14211950/pandoc.zip)

**Comment by keyboard3** [comment]
长时间未回复，暂时关闭此issue
