### ISSUE TITLE
pdf翻译只能翻译第一页，以后的页面全部都是空白，已开启"允许在所有网站上运行脚本""允许访问文件网址"

### ISSUE THREAD

**Issue by sbkk000** [immersive-translate/immersive-translate#141]
pdf翻译只能翻译第一页，以后的页面全部都是空白，已开启"允许在所有网站上运行脚本""允许访问文件网址"

**Comment by theowenyoung** [comment]
PDF相关问题统一在 https://github.com/immersive-translate/immersive-translate/issues/37 里讨论，暂时先关闭这个问题了
