### ISSUE TITLE
[Bug]: 无法使用openai或者gemini翻译

### ISSUE THREAD

**Issue by 138111111** [immersive-translate/immersive-translate#1411]
### 插件版本号 | Version

1.20

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

无法使用OpenAI或者Gemini翻译。

**Comment by keyboard3** [comment]
具体报什么错误

**Comment by keyboard3** [comment]
> 无论怎样切换vpn都不行。Open AI或者Gemini都不行。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "immersive-translate/immersive-translate" ***@***.***&gt;; 发送时间:&nbsp;2024年2月7日(星期三) 下午5:45 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [immersive-translate/immersive-translate] [Bug]: 无法使用openai或者gemini翻译 (Issue #1411) 具体报什么错误 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

额 那基本断定就是你代理问题了。 gemini 对翻墙节点要求挺高，最好是美国地区

**Comment by 138111111** [comment]
已经切换到美国了，现在是openai也不成了，有什么办法能重置吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月8日(星期四) 上午10:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [immersive-translate/immersive-translate] [Bug]: 无法使用openai或者gemini翻译 (Issue #1411)





  
无论怎样切换vpn都不行。Open AI或者Gemini都不行。
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "immersive-translate/immersive-translate" @.&gt;; 发送时间:&nbsp;2024年2月7日(星期三) 下午5:45 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [immersive-translate/immersive-translate] [Bug]: 无法使用openai或者gemini翻译 (Issue #1411) 具体报什么错误 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
额 那基本断定就是你代理问题了。 gemini 对翻墙节点要求挺高，最好是美国地区

**Comment by keyboard3** [comment]
> 已经切换到美国了，现在是openai也不成了，有什么办法能重置吗？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年2月8日(星期四) 上午10:10 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [immersive-translate/immersive-translate] [Bug]: 无法使用openai或者gemini翻译 (Issue #1411) 无论怎样切换vpn都不行。Open AI或者Gemini都不行。 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "immersive-translate/immersive-translate" @.&gt;; 发送时间:&nbsp;2024年2月7日(星期三) 下午5:45 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [immersive-translate/immersive-translate] [Bug]: 无法使用openai或者gemini翻译 (Issue #1411) 具体报什么错误 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; 额 那基本断定就是你代理问题了。 gemini 对翻墙节点要求挺高，最好是美国地区 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

截图或者录视频吧，你可能表述的时候漏了什么信息

**Comment by szwuzy** [comment]
如果能确定一下Gemini的具体调用域名和地址及端口公布一下就好使了。大家可以专门配置定向的策略路由来实现翻译。不用全局VPN带来的诸多不便。

**Comment by keyboard3** [comment]
暂无反馈 关闭此issue
