### ISSUE TITLE
[Bug]: 翻译后英文会和中文重叠在同一行

### ISSUE THREAD

**Issue by kaiyuegangbaro** [immersive-translate/immersive-translate#1412]
### 插件版本号 | Version

1.2.0

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

点击翻译网页上的内容后，中文翻译会和英文原文重叠在一起
![图像8-2-2024 上午3 21](https://github.com/immersive-translate/immersive-translate/assets/159294541/e49537d7-3634-48de-826c-a053b6f4ece7)

### 出现问题的网址 | URL

https://echo360.net.au/lesson/290339d4-13b0-4d9d-b71d-5a29f176da32/classroom

### 补充说明 | Additional context

Safari，chrome，edge上都是同样的情况

**Comment by kaiyuegangbaro** [comment]
https://immersivetranslate.com/preview新链接放在这咯 感谢！

**Comment by kaiyuegangbaro** [comment]
新链接放在这咯 感谢！https://immersivetranslate.com/preview

**Comment by keyboard3** [comment]
> 新链接放在这咯 感谢！https://immersivetranslate.com/preview

你没点击分享按钮，这个地址只能看。必须最后点击右上角的那个红色按钮才能分享给别人看

**Comment by kaiyuegangbaro** [comment]
这个再试一下呢 https://readit.site/a/jNKcI

**Comment by keyboard3** [comment]
<img width="381" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/13177744/0a4052a8-d970-4b75-a628-fcd9fd9f3e8c">
跟你的不一样，我是这样的，自身似乎就重叠？

**Comment by kaiyuegangbaro** [comment]
> 不

我这边不显示重叠诶 救命

**Comment by keyboard3** [comment]
你分享网站是同样的网址吗？

**Comment by kaiyuegangbaro** [comment]
> 你分享网站是同样的网址吗？

是这个哦https://readit.site/a/TiVZ5/lesson/195f93d6-07ea-4e5f-b6f5-7ca9f0ff9999/classroom

**Comment by keyboard3** [comment]
<img width="380" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/13177744/c8ee56ed-e6a9-45fb-beb3-4a3554360f58">
仅译文不是支持的吗

**Comment by kaiyuegangbaro** [comment]
是的 但是想要中英双语这个功能

**Comment by keyboard3** [comment]
> 是的 但是想要中英双语这个功能

这个站点只能单语，技术上无法适配它。
原站点采用了absolute绝对定位，这个排版是网站在渲染的时候计算好的，没有用浏览器文档流的排版逻辑。所以插件调整双语效果之后，无法让网站应用自己的排版逻辑。

**Comment by kaiyuegangbaro** [comment]
> > 是的 但是想要中英双语这个功能
> 
> 这个站点只能单语，技术上无法适配它。 原站点采用了absolute绝对定位，这个排版是网站在渲染的时候计算好的，没有用浏览器文档流的排版逻辑。所以插件调整双语效果之后，无法让网站应用自己的排版逻辑。

可是我记得几个月之前这个网站是可以顺利中英双语的，是不是因为更新了软件版本的问题，还是说这个网站更新了
