### ISSUE TITLE
[Bug]: deeplx在翻譯含Inc./Co.時會自動斷句

### ISSUE THREAD

**Issue by hzzzzaaaa** [immersive-translate/immersive-translate#1413]
### 插件版本号 | Version

1.2.1

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

用deeplx網頁翻譯時當出現Inc./Co. 
<img width="825" alt="截圖 2024-02-07 22 57 26" src="https://github.com/immersive-translate/immersive-translate/assets/107546522/724ec367-ec50-4ea6-8791-86d829c73936">
時會斷句，目前只發生在deeplx，微軟和谷歌的沒有問題（其它的不太清楚因為沒使用過
<img width="824" alt="截圖 2024-02-08 13 54 26" src="https://github.com/immersive-translate/immersive-translate/assets/107546522/e9a53655-6ed0-422c-a9a1-c8668187300f">
）

### 出现问题的网址 | URL

https://www.bloomberg.com/news/articles/2024-01-23/china-selloff-leads-to-record-38-trillion-gap-with-us-stocks

### 重现步骤 | To Reproduce

用deeplx翻譯就會發生(只有在以 Inc.為尾的字句)

**Comment by keyboard3** [comment]
<img width="1114" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/13177744/db93bffa-76b5-4542-be92-f993f7e53d18">
deepl 自己的bug，这个没啥办法，建议做法就是鼠标悬停配置一个非deepl的翻译服务，遇到这种情况，可以用鼠标悬停重新翻译
