### ISSUE TITLE
[Bug]: deepl 翻譯時返回error 400

### ISSUE THREAD

**Issue by meikenakinori** [immersive-translate/immersive-translate#1415]
### 插件版本号 | Version

1.21

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

deepl 翻譯時返回error 400 
其他gemini 谷哥翻譯正常
使用gemini 會出現漏翻

### 出现问题的网址 | URL

https://kakuyomu.jp/works/16817330650967237345/episodes/16817330651149731502

**Comment by meikenakinori** [comment]
嘗試使用簡體中文 成功翻譯 可能與繁體中文 deepl request 的時候 出現問題

**Comment by theowenyoung** [comment]
感谢反馈，调试了一下发现这个算是一个Bug，由于 deepl 本身不支持繁体中文，所以我们会先把 deepl 翻译为简体中文，再调用 Google 将其翻译为繁体中文。这中间 部分段落使用谷歌简体转繁体的时候大小超出了谷歌的限制。

该问题可以远程解决，目前已经解决了哈，刷新页面再试一下就可以了。
