### ISSUE TITLE
建议更新chatgml-4的api支持

### ISSUE THREAD

**Issue by unicorn00** [immersive-translate/immersive-translate#1416]
### 您希望的更新和改进是什么 | Update or Improve

https://open.bigmodel.cn/dev/api#sdkauth

### 补充说明 | Additional context

试了一下，发现可以用用了，但是好像自定义设置没法通过api验证，大概是鉴权格式问题

**Comment by theowenyoung** [comment]
油猴有自己的接口域名限制，需要自行修改油猴的脚本头部的接口声明。

**Comment by unicorn00** [comment]
没有用油猴呀，指的是chrome插件

**Comment by theowenyoung** [comment]
沉浸式翻译本身是没有做过 chatgml 的适配的，如果你直接在 Openai 里填写的话，是会有问题。当前情况下，如果你需要接入的话，需要按照我们的规范，自己实现一个自定义的接口: https://immersivetranslate.com/docs/services/custom/

由于国产AI的敏感词审核问题，我们测试 chatgml 引擎之后，发现普通的外媒报道，有高达 36% 的内容会触发他们的敏感词检测，导致文章中有大篇的段落无法翻译。另外还有频率限制问题，频率限制过于严格，用于网页翻译的时候，速度会非常慢。所以沉浸式翻译官方当前还不准备接入。
