### ISSUE TITLE
视频双语字幕支持手动打开自动关闭

### ISSUE THREAD

**Issue by xgmloo** [immersive-translate/immersive-translate#1419]
### 您希望的更新和改进是什么 | Update or Improve

目前有自动打开双语字幕的选项，但是不是所有的视频都需要看双语字幕，因此需要添加一个功能，即一个手动打开双语字幕的开关，在当前视频打开双语字幕后，不影响在其他视频上是否打开双语字幕。

**Comment by theowenyoung** [comment]
短时间内可能无法解决这个问题，因为实现方式的问题。

目前的实现方式是 拦截原网站的视频字幕请求，然后处理之后再返回给网站。


如果做手动打开的话，我们可能需要自己实现网站的双语字幕。

**Comment by keyboard3** [comment]
YouTube 上沉浸式的快捷图标上可以当次开启双语字幕
