### ISSUE TITLE
腾讯翻译君提示超过每秒5次的请求限制，如何解决呢

### ISSUE THREAD

**Issue by Xanxus9527** [immersive-translate/immersive-translate#142]
your current request times equals to 7 in a second,which exceeds the frequency limit 5 for a second.please reduce the frequency of calls

**Comment by theowenyoung** [comment]
是特定的网页会这样吗？已经在扩展程序里做了 每秒请求的限制了呀？
有没有网址发一下？

**Comment by Xanxus9527** [comment]
我是测试西数发给我的英文邮件出现这样的提示。

**Comment by Xanxus9527** [comment]
我测试了一下其他的英文网站，暂时没有遇到这样的问题，感谢你的回复，如果后续有遇到会再来反馈

**Comment by theowenyoung** [comment]
暂时关闭了～ 有问题再打开

**Comment by theowenyoung** [comment]
发现了代码中关于限流的bug，重新打开，下个版本修复～

**Comment by theowenyoung** [comment]
最新版已全面优化这个问题～

（之前的话，主要是有ifarme的网页会遇到这个问题多一点
