### ISSUE TITLE
[Bug]: Coursera的课程文档中的代码块被翻译了

### ISSUE THREAD

**Issue by Marsax110** [immersive-translate/immersive-translate#1421]
### 插件版本号 | Version

1.2.1

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

我记得大部分的文档中，代码块内的代码是不会被翻译的。
但是这次在Coursera的课程文档中却看到了自动翻译。

截图：
![image](https://github.com/immersive-translate/immersive-translate/assets/134605086/f46b89df-c60f-4381-9e32-4856a90709c3)

### 出现问题的网址 | URL

https://www.coursera.org/learn/react-basics/supplement/KGYDt/javascript-modules-imports-exports

**Comment by keyboard3** [comment]
开了翻译全部区域吗？  这个地址访问会被重定向，用沉浸式快照功能生成个链接出来看下

**Comment by Marsax110** [comment]
> 开了翻译全部区域吗？ 这个地址访问会被重定向，用沉浸式快照功能生成个链接出来看下

应该是没有开启翻译所有区域的：

![image](https://github.com/immersive-translate/immersive-translate/assets/134605086/95b054fa-4231-4bfc-92a8-5aba822b2187)


https://readit.site/a/pZ23U/learn/react-basics/supplement/KGYDt/javascript-modules-imports-exports

**Comment by keyboard3** [comment]
> > 开了翻译全部区域吗？ 这个地址访问会被重定向，用沉浸式快照功能生成个链接出来看下
> 
> 应该是没有开启翻译所有区域的：
> 
> ![image](https://private-user-images.githubusercontent.com/134605086/305646449-95b054fa-4231-4bfc-92a8-5aba822b2187.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNzc2MjcsIm5iZiI6MTcwODE3NzMyNywicGF0aCI6Ii8xMzQ2MDUwODYvMzA1NjQ2NDQ5LTk1YjA1NGZhLTQyMzEtNGJmYy05MmE4LTVhYmE4MjJiMjE4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxN1QxMzQyMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzIzYTJkMGUyZTMzZDIyOTdkNTNmZDJkMDQ5M2JmYmYzMjhhY2I2YzJiZGJmOWNmODMyMzgyY2U0YzI3YjlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mHRhpXHbzsY9Rpa2gamveGOUrPIPSZVd8k0Q6_PEZY0)
> 
> https://readit.site/a/pZ23U/learn/react-basics/supplement/KGYDt/javascript-modules-imports-exports

https://dash.immersivetranslate.com/abount#about 打开刷新下规则，然后重试下
