### ISSUE TITLE
视频字幕的按钮增加隐藏标题文字功能

### ISSUE THREAD

**Issue by yahuudang** [immersive-translate/immersive-translate#1423]
### 您希望的更新和改进是什么 | Update or Improve

图标的识别度已经足够了，“双语字幕”这几个占用的也有点太宽了，导致B站有的视频，网页全屏和全屏按钮都看不到了。
建议添加个选项：隐藏/显示 按钮文字标题。

**Comment by keyboard3** [comment]
B站的双语字幕按钮已经隐藏了
