### ISSUE TITLE
[Bug]: 不显示译文，译文加载不出来

### ISSUE THREAD

**Issue by Allensure** [immersive-translate/immersive-translate#1427]
### 插件版本号 | Version

V1.2.1

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

不显示译文，译文加载不出来，或译文加载时间过长
<img width="1196" alt="截屏2024-02-18 19 32 42" src="https://github.com/immersive-translate/immersive-translate/assets/132429745/c66570dc-a4a6-48c6-b85d-98c847c3adc8">

**Comment by theowenyoung** [comment]
请问有网址吗？

**Comment by szwuzy** [comment]
如果能确定一下Gemini的具体调用域名和地址及端口公布一下就好使了。大家可以专门配置定向的策略路由来实现翻译。不用全局VPN带来的诸多不便。

**Comment by Allensure** [comment]
我在Safari上用谷歌搜索几乎任何东西都会出现这样的情况，但过几分钟之后就会恢复，我猜想这是不是可能是网络的问题？但我的网络连接一直很好，并且只在谷歌搜索的时候有这种问题，所以也可能和搜索引擎又关系？

**Comment by Allensure** [comment]
@szwuzy 
抱歉我不明白是什么意思🥲

**Comment by szwuzy** [comment]
需要开发人员确定访问Gemini API接口的调用地址和端口是什么，然后确定自己电脑可以正常连通就好使了。通过抓包和协议监控那样有可能也不全面。我也没细查，只使用了一个大概范围。
