### ISSUE TITLE
[Bug]: 段落识别出现问题

### ISSUE THREAD

**Issue by Allensure** [immersive-translate/immersive-translate#1429]
### 插件版本号 | Version

V1.2.1

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

会将英文中括号[]识别为段落划分点。
<img width="1196" alt="截屏2024-02-19 08 43 23" src="https://github.com/immersive-translate/immersive-translate/assets/132429745/b5ab2479-09e2-44a5-a99a-dc05f8ca917d">
<img width="1196" alt="截屏2024-02-19 08 44 07" src="https://github.com/immersive-translate/immersive-translate/assets/132429745/bf11c5d6-b093-4da2-8be6-959074152a04">

### 出现问题的网址 | URL

https://www.jmir.org/2017/1/e9

### 重现步骤 | To Reproduce

1. 进入网站
2. https://www.jmir.org/2017/1/e9
3. 开启翻译

**Comment by keyboard3** [comment]
打开https://dash.immersivetranslate.com/abount#about 更新下规则，然后重试下

**Comment by Allensure** [comment]
@keyboard3 你好，我已经更新到最新的规则但还是出现这个问题，请问如何操作？

**Comment by Allensure** [comment]
感谢感谢！我刚刚又更新的规则已经解决了

**Comment by YiHui-Liu** [comment]
https://journals.aps.org/prc/abstract/10.1103/PhysRevC.103.025810 依然存在问题，规则已更新至最新
