### ISSUE TITLE
某些网站会出现第一次点击翻译无效的情况

### ISSUE THREAD

**Issue by bxb100** [immersive-translate/immersive-translate#143]
点击第二次才会有效. 如果你也遇到这样的问题, 可以在这个 issue 下贴出出现问题的网站

## 可能的原因

> 这似乎和网站的框架有关，我怀疑是 next 还有argular这两个框架可能有点问题， 具体表现似乎是： 我们的扩展已经翻译了那句话，但是随后又被网站自己还原回去了.  可能有个时序的问题

**Comment by bxb100** [comment]
https://blog.mozilla.org/addons/2022/11/17/manifest-v3-signing-available-november-21-on-firefox-nightly/

**Comment by bxb100** [comment]
我发现常出现的情况是内存不足的时候, 由于没有做详细的监控, 目前无法复现.

新的 0.2.65 似乎解决了我的问题, 暂时先关闭, 如果能 dig out reason, 再 reopen

**Comment by theowenyoung** [comment]
https://dprime.kr/g2/bbs/board.php?bo_table=ottnews

该网页稳定复现。

**Comment by theowenyoung** [comment]
现在应该ok了。
