### ISSUE TITLE
[Bug]: 特定网站的公式的原文在启用翻译后无法正常显示

### ISSUE THREAD

**Issue by Wyswyss** [immersive-translate/immersive-translate#1431]
### 插件版本号 | Version

1.2.1

### 平台 | Platform

macOS

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在特定网站使用openai的api翻译时，网站原文的公式会显示源码而不是格式化的公式；在不启用沉浸式翻译插件时，公式可以正常显示。启用前后图片如下：启用前
![image](https://github.com/immersive-translate/immersive-translate/assets/25119896/87724d6d-6bd6-4867-946a-94191601fbd2)
启用后
![image](https://github.com/immersive-translate/immersive-translate/assets/25119896/adeb0863-9d20-4638-bb6e-f79dd7c802eb)

### 出现问题的网址 | URL

https://textbook.simio.com/SASMAA/ch-queueing.html#sec-queue-term

### 重现步骤 | To Reproduce

1. 配置openai apikey，并启用自动翻译；
2. 打开上述url

### 补充说明 | Additional context

在此之前已经查询了公式相关的issue，均未解决该网页的问题。

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/9ffa5196-3090-4cfa-9409-70f925ad8941)
我这正常的呀。 是不是有别的插件影响到了？ 给插件隐身权限，在隐身窗口试下

**Comment by keyboard3** [comment]
长时间未回复，暂时关闭此issue

**Comment by Wyswyss** [comment]
抱歉，确实是其他插件影响，谢谢回复！
