### ISSUE TITLE
自定义本地翻译缓存的大小和时间

### ISSUE THREAD

**Issue by Ward-zzZ** [immersive-translate/immersive-translate#1432]
### 您希望的更新和改进是什么 | Update or Improve

- 希望能够控制本地翻译缓存的大小和时间，或者能自定义永久缓存的站点
- 提这个的出发点主要是在网页论文翻译([类似](https://ieeexplore.ieee.org/document/8846699))的时候为了准确通常会利用大模型翻译。由于一篇论文内容较长且可能会反复打开观看，同时网页内容不会频繁更改，如果能够将这种站点的缓存时间弄长一点可以节省很多token。
- 虽然快照可以一定程度上实现这个功能，但是在使用文献管理软件时需要手动更改信息，在快照上阅读论文的体验也没有原网页好
- 谢谢开发者~

**Comment by keyboard3** [comment]
默认的缓存策略除非手动删除，否则会一直存在的
