### ISSUE TITLE
双语 EPUB 电子书在阅读 App 中的显示优化

### ISSUE THREAD

**Issue by wxiluo** [immersive-translate/immersive-translate#1433]
### 您希望的更新和改进是什么 | Update or Improve

双语 EPUB 电子书的功能很棒，对比过“微信阅读”的翻译，使用更好的大模型确实效果好很多。但是我发现通过 immersive-translate 制作的双语 EPUB 电子书在阅读 App 中显示兼容性有一些问题。例如：
1）在 iPhone 14 Pro/iOS 17.3.1 中的“微信阅读”中，字体设置无法在中文字体上生效
2）在 Galaxy Z Fold 5/Android 14（三星 One UI 6.0） 的“微信阅读”中，中文字体会展示为异常的小

相信大部分人制作电子书都是为了在常用的阅读 App 中看，并且主要看中文部分，希望可以改进 EPUB 电子书的字体兼容性。

![23ce4f6906f904356700dcad90550ecd](https://github.com/immersive-translate/immersive-translate/assets/218806/2ee2acad-45d1-41d4-a341-00bfe86b288b)

![dad7916a58b20cdda120b9ee90f80403](https://github.com/immersive-translate/immersive-translate/assets/218806/c909de50-36d0-402f-b351-11b59fa74943)

电子书为《A Way of Being》，如果需要我可以帮助提供 epub 文件协助优化，Github 附件无法上传 epub 文件。

**Comment by wxiluo** [comment]
Galaxy Z Fold 5/Android 14（三星 One UI 6.0） ，微信阅读 App 字体设置入口如下。如截图所见，“微信阅读”应该是判断 EPUB 是中文书籍，因此在字体候选展示了中文字体（当判断为英文书籍的时候，字体候选会是英文字体），但在展示的时候英文文字和设置字号是相同的，中文文字会展示的异常小：

![e43c1efce8c069f1d5735dcdbda9af4d](https://github.com/immersive-translate/immersive-translate/assets/218806/20c40c4a-7bd4-4eb8-83ef-a2b79f6e445b)
![1aae8bcf3d1ac76f7f49ad1ec7d4e3a7](https://github.com/immersive-translate/immersive-translate/assets/218806/b8ae2822-3d46-4752-a92b-c384c1746759)
![a69ee74f8ac590cf6ebf6fad2bd49ae4](https://github.com/immersive-translate/immersive-translate/assets/218806/931833b0-e7b0-42c6-9230-f8ea48a535f6)

**Comment by wxiluo** [comment]
在 iOS 上的问题是微信阅读的字体设置，对中文文字是无效的。 字号展示正常。

**Comment by theowenyoung** [comment]
[勇气在召唤-Courage_Is_Calling_-_Ryan_Holiday.epub.zip](https://github.com/immersive-translate/immersive-translate/files/14385413/-Courage_Is_Calling_-_Ryan_Holiday.epub.zip)

我翻译了一本，似乎在安卓的微信读书里是正常的，你是否在沉浸式翻译里对译文的字体或者其他东西做过特殊设置？

**Comment by wxiluo** [comment]
我找到了问题所在，macOS 上我的系统首选语言“Preferred Languages”是 English，Chrome 在这个情况下的默认字体可能是英文字体，导致导出后的 epub 文件受到影响。解决办法：在 General-Language & Region - Applications 中，将 Chrome 指定为 简体中文。再次制作电子书在安卓“微信读书”中就展示正常了。 

虽然安卓的显示问题解决了，但在 iOS 的“微信读书”中，这本电子书字体（中文和英文）不会随着微信读书设置，始终是黑体。另外，我用 theowenyoung 翻译的 epub 在 iOS “微信读书”中，字体的设置也是不生效的。

![IMG_4498](https://github.com/immersive-translate/immersive-translate/assets/218806/38382a00-0e0b-49e7-87f9-3f7d0dce34b5)
[勇气在召唤-Courage_Is_Calling_-_Ryan_Holiday.epub.zip](https://github.com/immersive-translate/immersive-translate/files/14386203/-Courage_Is_Calling_-_Ryan_Holiday.epub.zip)

**Comment by wxiluo** [comment]
好，这个问题我提给微信读书 iOS 好了。这里双端不一致。

**Comment by geekhuashan** [comment]
我遇到了同样的问题，ios 端现在能够很好的识别处理翻译后的双语书籍了，能随着微信的设置而改变字体以及大小了。

但是安卓端依然是这样的问题，我的字异常的小。

我发现，只要我翻译的时候样式有改动，比如颜色换了一个，不是默认的话，安卓端就识别不了。如果选择默认就可以正常显示。

现在，
1. 需要跟微信andriod 版的开发提bug
2. 或者大佬，你这边从处理电子书的时候有办法解决这个问题吗
