### ISSUE TITLE
[Bug]: 翻译插件存在XSS漏洞

### ISSUE THREAD

**Issue by h0e4a0r1t** [immersive-translate/immersive-translate#1437]
### 插件版本号 | Version

1.2.1

### 请描述这个Bug | Describe the bug

翻译插件存在XSS漏洞，导致恶意攻击者可直接获取到用户在当前网站上的Cookie、Token等敏感信息

### 重现步骤 | To Reproduce

发表的文章中带有<img>字符，翻译后直接变为<img>标签
![image](https://github.com/immersive-translate/immersive-translate/assets/48357278/73a23dc3-416c-4451-9ab6-27a69e3e8b04)

### 补充说明 | Additional context

详情已私发

**Comment by keyboard3** [comment]
所有译文内容都会经过DOMPurify过滤，不会插入可执行脚本

**Comment by h0e4a0r1t** [comment]
如果将img标签的值换成XSS图片探针
![image](https://github.com/immersive-translate/immersive-translate/assets/48357278/9d42d48c-a78c-44ae-9e29-b8ae150b248a)

那么每次有人使用该插件翻译访问我的帖子就会触发一次，平台上就可以收到一次请求信息
<img width="416" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/48357278/6dcc2619-24f7-4319-acf4-33c91f8e80cc">

如果没有csp等策略会直接获取到用户在当前网站上的Cookie、Token等敏感信息，望修改！

**Comment by keyboard3** [comment]
针对img标签已修复，打开 https://dash.immersivetranslate.com/abount#about 手动更新下规则，再试下看

**Comment by h0e4a0r1t** [comment]
已修复

**Comment by keyboard3** [comment]
> 已修复

感谢反馈
