### ISSUE TITLE
请求调用 通义千问API 

### ISSUE THREAD

**Issue by fkue587** [immersive-translate/immersive-translate#1439]
### 您希望的更新和改进是什么 | Update or Improve

请求调用 通义千问API 

### 补充说明 | Additional context

更适合国人并且现在免费 而且翻译对比谷歌更好 其他没有测试

**Comment by Nikkiiw** [comment]
同求

**Comment by jlong7398** [comment]
加1，现在价格真的便宜

**Comment by jlong7398** [comment]
通义千问现在兼容openai接口了，https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions

**Comment by Nikkiiw** [comment]
@jlong7398 https://help.aliyun.com/zh/dashscope/developer-reference/compatibility-of-openai-with-dashscope/
还是需要配置接口

**Comment by theowenyoung** [comment]
1.6.2 版本已支持。
