### ISSUE TITLE
edge浏览器侧边栏的对话框，暂时没有支持啊

### ISSUE THREAD

**Issue by Ali1995A** [immersive-translate/immersive-translate#1442]
### 您希望的更新和改进是什么 | Update or Improve

edge浏览器侧边栏的对话框，暂时没有支持啊

### 补充说明 | Additional context

edge浏览器侧边栏的对话框，暂时没有支持啊

**Comment by keyboard3** [comment]
侧边栏插件没有访问权限，支持不了
