### ISSUE TITLE
[Bug]: Unable to translate on groq（https://groq.com/）

### ISSUE THREAD

**Issue by plutomiao** [immersive-translate/immersive-translate#1443]
### 插件版本号 | Version

V1.2.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

When used on the https://groq.com/ website, there is no response at all, neither Google Translate nor openai. Other websites are normal

### 出现问题的网址 | URL

https://groq.com/

### 重现步骤 | To Reproduce

Normal settings, open the website, no response

**Comment by keyboard3** [comment]
该网站采用了flutter  canvs绘制，不遵循网页渲染规则，无法翻译
