### ISSUE TITLE
[Bug]: youtube 自动产生的字幕，无法使用双语字幕

### ISSUE THREAD

**Issue by thomasTAT** [immersive-translate/immersive-translate#1447]
### 插件版本号 | Version

1.2.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/109513632/6323473c-6bc9-46fe-bad7-60af48ca2078)

非自动产生的字幕可以正常工作

发现目标语言设置为繁体中文就有此bug。 sadly。

### 出现问题的网址 | URL

https://www.youtube.com/watch?v=XllmgXBQUwA

**Comment by keyboard3** [comment]
YouTube自己的问题  https://immersivetranslate.com/docs/faq/#youtube-%E5%8F%8C%E8%AF%AD%E5%AD%97%E5%B9%95%E7%B9%81%E4%BD%93%E4%B8%AD%E6%96%87%E4%B8%8D%E6%98%BE%E7%A4%BA
