### ISSUE TITLE
[Bug]: 开了插件之后 在b(哔哩哔哩)站上的ai字幕(cc字幕)不显示了,PC端

### ISSUE THREAD

**Issue by itheword** [immersive-translate/immersive-translate#1450]
### 插件版本号 | Version

V1.2.1

### 请描述这个Bug | Describe the bug

[Bug]: 开了插件之后 在b(哔哩哔哩)站上的ai字幕(cc字幕)不显示了,PC端

**Comment by keyboard3** [comment]
页面翻译了吗？ 是不是开启过 自动翻译双语字幕。 使用了什么翻译服务

**Comment by keyboard3** [comment]
暂无反馈 关闭此issue
