### ISSUE TITLE
能否添加支持本地部署的AI模型进行翻译

### ISSUE THREAD

**Issue by despairTK** [immersive-translate/immersive-translate#1451]
### 您希望的更新和改进是什么 | Update or Improve

添加支持本地部署的AI模型进行翻译。

### 补充说明 | Additional context

https://github.com/ollama/ollama
例如这个，最近把谷歌的 Gemma 模型部署到了本地，效果要比传统翻译服务商更好。

**Comment by ihxperfect** [comment]
刚想提这个请求，就发现其他朋友已经提了。
的确，对于本地能够部署大语言模型的来说，本地翻译是个需求，也能把模型用起来。

**Comment by Octopuszz** [comment]
希望插件支持[text-generation-webui](https://github.com/oobabooga/text-generation-webui)的API，可以直接调用本地模型

**Comment by lambdaxs** [comment]
+1

**Comment by lambdaxs** [comment]
+1

**Comment by Smellly** [comment]
+1

**Comment by ccdanpian** [comment]
+1

**Comment by H1DDENADM1N** [comment]
+1

**Comment by tinuv** [comment]
MacOS使用Ollama的临时解决方案: https://github.com/tinuv/TranslationService

**Comment by keyboard3** [comment]
ollama 本身支持openai 接口, 如果插件配置出现403错误 参见 https://immersivetranslate.com/docs/faq/#%E5%A6%82%E4%BD%95%E6%94%AF%E6%8C%81-ollama

**Comment by Copy2Translator** [comment]
OLLAMA_ORIGINS="*" ollama serve （允许跨域访问并启动ollama）

**Comment by Lionad-Morotar** [comment]
使用 Mac + LMStudio 可以参考：[《💻 本地部署 Qwen 翻译网页》](https://lionad.art/articles/local-translator)

**Comment by despairTK** [comment]
> OLLAMA_ORIGINS="*" ollama serve （允许跨域访问并启动ollama） 请问说明里的这个该如何设置？
> 
> 原来是设置环境变量，搞定

请问如何设置？

**Comment by despairTK** [comment]
@keyboard3 Windows下怎么允许跨域访问并启动ollama？

**Comment by Copy2Translator** [comment]
> > OLLAMA_ORIGINS="*" ollama serve （允许跨域访问并启动ollama） 请问说明里的这个该如何设置？
> > 原来是设置环境变量，搞定
> 
> 请问如何设置？
就是设置下系统环境变量啊，这个在他们的说明里写的比较模糊，刚开始我也没搞对
![图片](https://github.com/immersive-translate/immersive-translate/assets/75414580/995181af-5bcc-430c-9485-9e78471e0d8c)

**Comment by ialshjl** [comment]
> > > OLLAMA_ORIGINS="*" ollama serve （允许跨域访问并启动ollama） 请问说明里的这个该如何设置？
> > > 原来是设置环境变量，搞定
> > 
> > 
> > 请问如何设置？
> > 就是设置下系统环境变量啊，这个在他们的说明里写的比较模糊，刚开始我也没搞对
> > ![图片](https://private-user-images.githubusercontent.com/75414580/321824317-995181af-5bcc-430c-9485-9e78471e0d8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5Nzk1ODEsIm5iZiI6MTcxMzk3OTI4MSwicGF0aCI6Ii83NTQxNDU4MC8zMjE4MjQzMTctOTk1MTgxYWYtNWJjYy00MzBjLTk0ODUtOWU3ODQ3MWUwZDhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDE3MjEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3NmU5OTMzYzVjZDI1NTc1OWM2NmQzY2I0NTYxZmNjYTU2YjIyMDI5ZDc1YzM1ZWU3MTg1Nzc5NzRiZGQ0OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WogS93ozttgfxjkmBAfwKrhduRd233WJ7WeJvxhzhXI)

那mac的话是怎样设置？

**Comment by theowenyoung** [comment]
> > > > OLLAMA_ORIGINS="*" ollama serve （允许跨域访问并启动ollama） 请问说明里的这个该如何设置？
> > > > 原来是设置环境变量，搞定
> > > 
> > > 
> > > 请问如何设置？
> > > 就是设置下系统环境变量啊，这个在他们的说明里写的比较模糊，刚开始我也没搞对
> > > ![图片](https://private-user-images.githubusercontent.com/75414580/321824317-995181af-5bcc-430c-9485-9e78471e0d8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5Nzk1ODEsIm5iZiI6MTcxMzk3OTI4MSwicGF0aCI6Ii83NTQxNDU4MC8zMjE4MjQzMTctOTk1MTgxYWYtNWJjYy00MzBjLTk0ODUtOWU3ODQ3MWUwZDhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDE3MjEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3NmU5OTMzYzVjZDI1NTc1OWM2NmQzY2I0NTYxZmNjYTU2YjIyMDI5ZDc1YzM1ZWU3MTg1Nzc5NzRiZGQ0OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WogS93ozttgfxjkmBAfwKrhduRd233WJ7WeJvxhzhXI)
> 
> 那mac的话是怎样设置？

请参考 原 repo 的issue: https://github.com/ollama/ollama/issues/2308
