### ISSUE TITLE
[Bug]: 网络问题，无法连接到服务，请检查你的代理或本地网络连接后重试。

### ISSUE THREAD

**Issue by doctoryuiting** [immersive-translate/immersive-translate#1452]
### 插件版本号 | Version

1.2.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

从周五开始就出现这种报错，已经是在3个不同的地点以及WiFi都尝试了，仍然是报错。wifi强度都是满格，其他网页浏览都么有任何问题，就是翻译出不来。

<img width="420" alt="2dbe95c8cfaa60745256c3a12a7eae9" src="https://github.com/immersive-translate/immersive-translate/assets/161263402/3e043646-3d66-4090-9523-ba3e6ad12d91">

### 出现问题的网址 | URL

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2752602/

### 重现步骤 | To Reproduce

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2752602/

**Comment by keyboard3** [comment]
点击沉浸式扩展图标打开面板，切换其他可用翻译服务，比如腾讯交互
