### ISSUE TITLE
能否只固定翻译一部分的DOM节点.

### ISSUE THREAD

**Issue by noenif** [immersive-translate/immersive-translate#1453]
### 您希望的更新和改进是什么 | Update or Improve

能否只固定翻译一部分的DOM节点.

我渲染的一个HTML  通过v-html ,我想他只翻译那部分HTML ,对于iframe中的内容时候也进行了dom的检测呢?

**Comment by keyboard3** [comment]
你可以给dom上添加 translate="no" 属性，不让插件翻译

**Comment by 0000005** [comment]
能否支持只翻译正文？
能否支持不翻译广告？

**Comment by theowenyoung** [comment]
默认情况下，不会翻译第一个 header，第一个 nav 标签，第一个 footer 标签。
