### ISSUE TITLE
[Bug]: 仅显示译文在pdf翻译时失效

### ISSUE THREAD

**Issue by dfmjndm** [immersive-translate/immersive-translate#1454]
### 插件版本号 | Version

1.2.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/57401901/7b64030a-5ba3-4b76-85c0-d05a211fce0e)

**Comment by keyboard3** [comment]
PDF 工具是双语对照工具，只能双语对照。 无法仅译文
