### ISSUE TITLE
[Bug]: 懸浮球功能關閉，右側還是會顯示(裝置模擬時)

### ISSUE THREAD

**Issue by ad6543210** [immersive-translate/immersive-translate#1455]
### 插件版本号 | Version

1.1.6

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

啟用懸浮球的選項已關閉，正常網頁沒問題
如果使用裝置模擬(例如手機)，重新整理後。還是會在右邊看到

### 重现步骤 | To Reproduce

1. 選項中關閉懸浮球
2. 打開任意網頁
3. ctrl+shift+i
4. ctrl+shift+m (什麼都不用選就可以觸發)
5. ctrl+shift+r

**Comment by FattySpring** [comment]
PC和H5的懸浮球配置是獨立的，你要關閉h5的，需要打開的設定頁頁要成模擬狀態

**Comment by ad6543210** [comment]
模擬的方式也設定一次就可以了，謝謝
