### ISSUE TITLE
[Bug]: 未正确对待HTML标签的转义

### ISSUE THREAD

**Issue by Kerkong** [immersive-translate/immersive-translate#1458]
### 插件版本号 | Version

1.2.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

[
![G~D88 W$S1RNGNS`5@54PQ8](https://github.com/immersive-translate/immersive-translate/assets/95417363/c9d2d3e6-88fd-4151-b02f-3f519c7870fd)
](url)

### 出现问题的网址 | URL

https://hackerone.com/reports/415484

**Comment by theowenyoung** [comment]
1.2.2 版本应该修复了这个问题，chrome 商店更新一下再试试？

![CleanShot 2024-02-26 at 22 05 38@2x](https://github.com/immersive-translate/immersive-translate/assets/62473795/dba75e02-7a75-40ff-ae7c-04e8daca6571)

**Comment by theowenyoung** [comment]
好吧... 好像和翻译服务有关。 

deepl 是ok的。 谷歌和微软似乎不行，这个和翻译服务处理标签的策略有关，可能做不了什么..

**Comment by Kerkong** [comment]
![(7G) 0 QBQ1SY24)AAURD 1](https://github.com/immersive-translate/immersive-translate/assets/95417363/49d4800d-435c-4a3c-b150-e7b0396446d9)
我使用的正是deepl，并且版本更新到1.2.2了

**Comment by Kerkong** [comment]
还有一个建议就是关于前端css ::before 进行的展开标签内容展开后经常无法翻译的问题，如果可以妥善更新的话我非常乐意推荐我的朋友来升级pro，因为我们正在使用的教学网站大量的使用了这个css来进行展开操作

**Comment by theowenyoung** [comment]
> ![(7G) 0 QBQ1SY24)AAURD 1](https://private-user-images.githubusercontent.com/95417363/307822567-49d4800d-435c-4a3c-b150-e7b0396446d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NTc1MzUsIm5iZiI6MTcwODk1NzIzNSwicGF0aCI6Ii85NTQxNzM2My8zMDc4MjI1NjctNDlkNDgwMGQtNDM1Yy00YTNjLWIxNTAtZTdiMDM5NjQ0NmQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDE0MjAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzZDlhMDM1NzBiZjE1NjU3NTMzMzUwMDQxZmQ5ZTgxMzMyMDg1YWQyNTM1MmU5MDMyZGJmZTZlYTIyN2JmOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UphYh3X5wAlA7Cjq0SgXyLVvjh8UYEKHf92NTXs2LPA) 我使用的正是deepl，并且版本更新到1.2.2了

奇怪，我这里用deepl 是正常的，看我在2楼的截图... 

你在【设置】【关于】页面暂时关闭下缓存呢？

**Comment by theowenyoung** [comment]
> 还有一个建议就是关于前端css ::before 进行的展开标签内容展开后经常无法翻译的问题，如果可以妥善更新的话我非常乐意推荐我的朋友来升级pro，因为我们正在使用的教学网站大量的使用了这个css来进行展开操作

请问有示例的网址吗？我们看看。
