### ISSUE TITLE
[Bug]: 翻译结果中的 code 标签在文本中的顺序不对

### ISSUE THREAD

**Issue by randomVariable2000** [immersive-translate/immersive-translate#1459]
### 插件版本号 | Version

1.2.1

### 平台 | Platform

macOS

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/37059674/ca7991f4-7e4b-4028-acc1-42c35723294a)

code 标签的顺序或者位置不对

### 出现问题的网址 | URL

https://www.promptingguide.ai/introduction/examples

### 重现步骤 | To Reproduce

1. 前往 https://www.promptingguide.ai/introduction/examples#text-classification
2. 使用插件翻译

**Comment by keyboard3** [comment]
这个是翻译服务没有正确保持顺序，可以切换下别的翻译服务, 比如谷歌
