### ISSUE TITLE
IOS，Safari更新到2.62版后，网页每隔几秒重复刷新，直到报错

### ISSUE THREAD

**Issue by tonybestone** [immersive-translate/immersive-translate#146]
![D233F253-4143-48B2-8A12-8E009656CBE3](https://user-images.githubusercontent.com/125846426/220002085-5e32f2c6-c08a-4680-9ccf-5596187275e4.png)
![40C8A7CD-24D4-45A1-AEB2-C5F406313F37](https://user-images.githubusercontent.com/125846426/220002091-2c147859-d164-4896-a327-2b9ceea70e09.png)

**Comment by theowenyoung** [comment]
所有网页吗？还是就这两个网页？

**Comment by tonybestone** [comment]
所有网页。

**Comment by tonybestone** [comment]
没有装其他插件。

之前2.59版是正常的。

**Comment by tonybestone** [comment]
我用的是userscripts.

已经回滚到2.59版本，一切正常。

用IOS Safari测试了下2.6、2.61和2.62版，均出现以上问题。

**Comment by theowenyoung** [comment]
今天更新到了 0.2.64 版本，再试试呢？

因为好像也没有其他用户反馈有这个问题..

如果还有问题的话，测试下这个简单网页看看： <https://immersive-translate.owenyoung.com/example/>

**Comment by theowenyoung** [comment]
可以了，最新的 0.2.67 版本已修复。

确认由于引入本地简体转繁体造成内存爆炸，尤其有多个iframe的情况。

最新版已经移除了本地简体转繁体，改为调用接口实现。
