### ISSUE TITLE
[Bug]: 某些词语不翻译，而是显示#0 #、#1 #

### ISSUE THREAD

**Issue by seigwen** [immersive-translate/immersive-translate#1462]
### 插件版本号 | Version

1.2.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![Snipaste_2024-02-27_11-47-56](https://github.com/immersive-translate/immersive-translate/assets/38581695/5c433dfd-6576-4787-81ae-0e30c50c9a75)

某些词语不翻译，而是显示#0 #、#1 #

### 出现问题的网址 | URL

https://dart.dev/guides/libraries/create-packages

### 重现步骤 | To Reproduce

Go to 'https://dart.dev/guides/libraries/create-packages' and click Translate

**Comment by keyboard3** [comment]
选的是腾讯交互？ 打开 https://dash.immersivetranslate.com/abount#about 更新下规则，再试下

**Comment by keyboard3** [comment]
1.2.3 修复
