### ISSUE TITLE
[Bug]: Safari 油猴脚本 翻译一直在loading

### ISSUE THREAD

**Issue by tthzwq** [immersive-translate/immersive-translate#1464]
### 插件版本号 | Version

1.2.2

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

## 1. 翻译无响应，在所有页面上使用翻译， 一直在转圈圈

<img width="890" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/56644784/8179f5cd-6532-4b6d-ba73-96c45f575db1">

## 2. 菜单按钮点击后无反应

<img width="509" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/56644784/7fde4fb6-29e6-4c3d-9bf3-42de90811dc9">

### 出现问题的网址 | URL

*

**Comment by keyboard3** [comment]
微软翻译访问不稳定，切换其他翻译服务

**Comment by tthzwq** [comment]
> 微软翻译访问不稳定，切换其他翻译服务
Chrome 的油猴脚本 没问题，Safari的不行
