### ISSUE TITLE
在Android端的插件中，允許以觸碰等方式來觸發【輸入框增強】

### ISSUE THREAD

**Issue by blackatz456** [immersive-translate/immersive-translate#1465]
### 您希望的更新和改进是什么 | Update or Improve

您好，
我先前有跟客服反應部分網站，無法以快速輸入三次空格鍵觸發【輸入框增強】，
雖然電腦端可以用快捷鍵的方式解決，
但是目前Android端對此是無解，
請對此做類似用四指觸碰等方式來觸發【輸入框增強】?

### 补充说明 | Additional context

![image](https://github.com/immersive-translate/immersive-translate/assets/39073509/a5753370-1d0d-4bc4-bf79-53967fe207ab)

**Comment by flamintune** [comment]
最新版本1.4.8已支持移动端手势翻译，详情参考更新日志 https://immersivetranslate.com/docs/CHANGELOG/#148
