### ISSUE TITLE
新版沉浸式翻译浏览器（安卓手机版）上  https://jdkg.top/   网站有问题

### ISSUE THREAD

**Issue by cipher1019** [immersive-translate/immersive-translate#1466]
### 插件版本号 | Version

1.2.2

### 平台 | Platform

Android

### 请描述这个Bug | Describe the bug

新版沉浸式翻译浏览器（安卓手机版）（2024-02-07）上  https://jdkg.top/  这个网站有问题，问题目前发现的有两个：1、很多时候用新版新版沉浸式翻译浏览器上该网站半天无法打开，但换旧版（2023-06-15）或者其他浏览器（火狐、夸克、百度甚至华为自带浏览器）都可以无障碍打开；2、好不容易打开一回，看该网站上的英文文章按翻译球没有任何反应，无法翻译，但换用旧版或者火狐就没有任何问题。

### 出现问题的网址 | URL

https://jdkg.top/

**Comment by FattySpring** [comment]
https://github.com/immersive-translate/immersive-translate/assets/25144301/62937610-af54-4c04-b4d0-7712a3444008

未能复现，您可以尝试切换下网络，重启浏览器，或者使用新版 Firefox 浏览器安装沉浸式翻译。

沉浸式翻译 Firefox 扩展安装地址： https://addons.mozilla.org/zh-CN/firefox/addon/immersive-translate/

**Comment by keyboard3** [comment]
暂无反馈 关闭此issue
