### ISSUE TITLE
prompt支持更多的变量

### ISSUE THREAD

**Issue by 0000005** [immersive-translate/immersive-translate#1469]
### 您希望的更新和改进是什么 | Update or Improve

建议在定义大语言模型的prompt的时候支持更多的变量，让llm了解更多的背景和上下文，就可以得到更好的翻译效果。
目前只支持  {{text}} 、{{from}} 、{{to}}。
建议新增的变量：网页标题、网址。

**Comment by keyboard3** [comment]
环境变量已支持 {{imt_domain}}  {{imt_title}}
