### ISSUE TITLE
[Bug]: Incorrect text encoding when translating Chinese in Discord

### ISSUE THREAD

**Issue by longgui0318** [immersive-translate/immersive-translate#1470]
### 插件版本号 | Version

1.2.2

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

Incorrect text encoding when translating Chinese in Discord.

![20240228141854](https://github.com/immersive-translate/immersive-translate/assets/3406303/5f7376a3-fc9b-4610-9143-a928137a22bd)

**Comment by keyboard3** [comment]
打开沉浸式的面板用快照功能生成个链接，我们看下网页结构
