### ISSUE TITLE
[Bug]: 文字的翻译不显示

### ISSUE THREAD

**Issue by B-up-yige** [immersive-translate/immersive-translate#1471]
### 插件版本号 | Version

1.2.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在使用腾讯交互翻译时主要的题目文字翻译不显示
![J5ZOB57@K~3%2K$5ZFODWCJ](https://github.com/immersive-translate/immersive-translate/assets/60462379/a8882d1c-cf46-472d-bd8b-8cb805ca85be)

### 出现问题的网址 | URL

https://codeforces.com/problemset/problem/1409/C

### 重现步骤 | To Reproduce

1.打开插件
2.点击翻译

### 补充说明 | Additional context

其他的没问题，就是腾讯交互翻译会有问题

**Comment by flamintune** [comment]
翻译的时候对于不需要翻译的特殊符号或特殊文本，我们采用的是用占位符替换。

然而目前腾讯交互翻译对于占位符的处理不是很理想，试了好多次效果都不是很好，这块需要花费不小的精力去完善，目前的话建议切换其他的翻译服务。

**Comment by keyboard3** [comment]
调整了下占位符，应该可以了。打开 https://dash.immersivetranslate.com/abount#about 更新下规则，重试下看
