### ISSUE TITLE
[Bug]: 不起作用!!  [切勿在以下网址中启用输入框增强 ]

### ISSUE THREAD

**Issue by SuSuSoo** [immersive-translate/immersive-translate#1472]
### 插件版本号 | Version

1.2.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

这个功能不起作用: [切勿在以下网址中启用输入框增强]
添加网址: poe.com, *.poe.com

### 出现问题的网址 | URL

poe.com, *.poe.com

### 重现步骤 | To Reproduce

添加网址, 刷新页面, 在输入框连续按三个空格

**Comment by theowenyoung** [comment]
请不要使用逗号，每行一个，直接添加 `poe.com` 即可
