### ISSUE TITLE
[Bug]:悬浮球关闭显示后仍然显示

### ISSUE THREAD

**Issue by UnderTheAurora** [immersive-translate/immersive-translate#1474]
### 插件版本号 | Version

1.2.2

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

设置中关闭了悬浮球功能，浏览器控制台(chrome - F12 / Fn+F12)开机设备模拟后又会显示出来

**Comment by keyboard3** [comment]
PC和H5的悬浮球配置是独立的，你要关闭h5的，需要打开的设置页页要成模拟状态
