### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by kidcvs** [immersive-translate/immersive-translate#1476]
### 插件版本号 | Version

1.2.2

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![1709197187528](https://github.com/immersive-translate/immersive-translate/assets/3056462/9d61447f-bf7c-43d3-b7ee-cf12ccd561ab)
鼠标不移到翻译结果上会被模糊

### 出现问题的网址 | URL

https://chat.openai.com/c/8e01fbbf-45d6-4b7e-8acc-562c347a1037

**Comment by keyboard3** [comment]
? 这不是你自己选的译文的模糊效果吗
