### ISSUE TITLE
输入框翻译适配地址栏

### ISSUE THREAD

**Issue by PolarLinDa6** [immersive-translate/immersive-translate#1477]
### 您希望的更新和改进是什么 | Update or Improve

作者你好, 沉浸式翻译是一个优秀的扩展, 但是我在使用过程中遇到了不便之处
输入框增强是无法对地址栏起作用的, 这对习惯使用地址栏搜索的人是不便的, 希望可以适配地址栏

**Comment by keyboard3** [comment]
浏览器不允许插件在地址栏做这种复杂操作
