### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by yhll1366** [immersive-translate/immersive-translate#1478]
### 插件版本号 | Version

1.2.2

### 平台 | Platform

_Windows_

### 浏览器 | Browsers

_Chrome_

### 插件类型 | Extension Type

_浏览器拓展_

### 请描述这个Bug | Describe the bug

视频双语字幕没有显示，原本的也没有，在出现“正在加载字幕…”后不会有任何字幕出现
视频网页翻译正常

### 出现问题的网址 | URL

www.youtube.com

**Comment by keyboard3** [comment]
给插件授权隐身窗口权限，然后在重试下，检查下是否第三方插件干扰
