### ISSUE TITLE
[Bug]: ImmersiveTraslate doesn't translate some phrases and messes traslation

### ISSUE THREAD

**Issue by iG8R** [immersive-translate/immersive-translate#1479]
### 插件版本号 | Version

1.2.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

Hello.
ImmersiveTranslate doesn't translate phrases 1-2 character long, despite `Options -> Advanced Settings -> Minimum character count for paragraph translation` is set to `1`, and messes the order of the translated text.

<img src="https://github.com/immersive-translate/immersive-translate/assets/11407417/b0eb5ff3-18d4-44f3-ac32-e5fbc70ae312" width="550">

Although if using other app to translate the same text, OpenAI translates it without omitting any phrase even 1 character long.

<img src="https://github.com/immersive-translate/immersive-translate/assets/11407417/d4ae73f7-b6be-4e8c-aebc-5e09a8908ff8" width="550">

<img src="https://github.com/immersive-translate/immersive-translate/assets/11407417/cba4731c-7dac-441e-9792-1c0558d5397d" width="550">

### 出现问题的网址 | URL

https://www.69shu.pro/txt/13823/8196294

### 重现步骤 | To Reproduce

1. Go to https://www.69shu.pro/txt/13823/8196294
2. Try to translate to English with the parameters from the "Additional context" section below.

### 补充说明 | Additional context

**Options -> Developer settings -> Edit User Rules:**
```
[
  {
    "matches": "www.69shu.pro",
    "selectors": [
      ".txtnav"
    ]
  }
]
```

**Options -> General:**

<img src="https://github.com/immersive-translate/immersive-translate/assets/11407417/9bc9046a-0057-4c6e-8ed7-3f2a2a18f8e3" width="350">

**Comment by theowenyoung** [comment]
Thank you. 

After carefully debugging our plugin I realized that our system has a hard limit where the minimum number of translated characters is set to 3, meaning that there must be at least 3 valid characters in a paragraph before it will be translated.

This is a more reasonable restriction in English, but may not be particularly appropriate for Chinese.

I'll improve the hard limit here so that it respects the values set by the user.

**Comment by iG8R** [comment]
Thank you very much!
It seems to be working now.
