### ISSUE TITLE
[Bug]: 在自动翻译 `https://learnopengl.com/` 弹出窗口中的函数定义发生闪烁

### ISSUE THREAD

**Issue by Song-Tianxiang** [immersive-translate/immersive-translate#1483]
### 插件版本号 | Version

1.2.3

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

翻译窗口闪烁，没办法查看

### 出现问题的网址 | URL

https://learnopengl.com/Introduction

### 重现步骤 | To Reproduce

把鼠标放在这上面
<img width="975" alt="Screenshot 2024-03-02 at 12 29 27" src="https://github.com/immersive-translate/immersive-translate/assets/149415622/873eea6a-94e0-44f8-bbf1-28531c28f687">

**Comment by keyboard3** [comment]
已修复 打开页面刷新下
