### ISSUE TITLE
[Bug]: 相同设置，油猴脚本从0.5.6更新1.2.3后，不能翻译

### ISSUE THREAD

**Issue by AnonymousChannel** [immersive-translate/immersive-translate#1484]
### 插件版本号 | Version

1.2.3

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

油猴脚本从油猴脚本从V0.5.6更新V1.2.3后，在所有网站均V1.2.3不能使用，V0.5.6仍可正常使用，所有设置均相同。
在同一网页，通过设置不同快捷键的方式继续测试，得到新版不能正常使用的结论。
![image](https://github.com/immersive-translate/immersive-translate/assets/108347697/af5dc990-ceae-4408-9e89-7a9c3f1e0b44)
![image](https://github.com/immersive-translate/immersive-translate/assets/108347697/eec4ceea-7983-429c-a60d-b0b93f5116f3)

**Comment by theowenyoung** [comment]
请问是所有网页都不能用吗？切换一下翻译服务看看呢？

**Comment by AnonymousChannel** [comment]
> 请问是所有网页都不能用吗？切换一下翻译服务看看呢？

切换了彩云，在设置里测试成功了，但是使用时还是翻译不了。以该网址为例：https://www.sciencedirect.com/science/article/pii/S0926580521001734
![image](https://github.com/immersive-translate/immersive-translate/assets/108347697/48e73a3f-d2ab-49f6-9bb2-dda4c64410e4)
![image](https://github.com/immersive-translate/immersive-translate/assets/108347697/1d19580e-2b23-44e5-bf20-4644500d8399)

**Comment by theowenyoung** [comment]
试试腾讯交互？或者你可以换插件试试吗？而不是油猴脚本。

微软翻译 最近似乎被间接性墙了。

彩云的话，我测试了下，我这里是正常的：

![CleanShot 2024-03-02 at 19 59 08@2x](https://github.com/immersive-translate/immersive-translate/assets/62473795/7e212e0c-5795-4c1c-bd01-065bbdfbed7f)

**Comment by AnonymousChannel** [comment]
> 试试腾讯交互？或者你可以换插件试试吗？而不是油猴脚本。
> 
> 微软翻译 最近似乎被间接性墙了。
> 
> 彩云的话，我测试了下，我这里是正常的：
> 
> ![CleanShot 2024-03-02 at 19 59 08@2x](https://private-user-images.githubusercontent.com/62473795/309471367-7e212e0c-5795-4c1c-bd01-065bbdfbed7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0MzI2NDAsIm5iZiI6MTcwOTQzMjM0MCwicGF0aCI6Ii82MjQ3Mzc5NS8zMDk0NzEzNjctN2UyMTJlMGMtNTc5NS00YzFjLWJkMDEtMDY1YmJkZmJlZDdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDAyMTkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2OTMzMDEyMDk4ZjNmMjNiOWU1NGJlODg3N2JmMWE5ZmU2MTM0ZWYyNWQ4NzQ5YjE1ZDk1MjFjZGM1YmQ4ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GlfG3hlCiiTOofY33jO9qf_wVqR6tGOBDSgxtTCBTtw)

插件使用微软也是不能用，应该是被墙了。

我改了有道翻译，可以用了，感谢大佬。
