### ISSUE TITLE
[Bug]: safari 上，鼠标滑过的时候， ruby 标签会让完整的段落分开

### ISSUE THREAD

**Issue by theowenyoung** [immersive-translate/immersive-translate#1487]
### 插件版本号 | Version

1.2.3

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

使用“鼠标划过段落翻译”的功能时，如果句子中有拼音/振假名标记（或者说，带<ruby>标签），就会断开翻译，从而结果全都乱掉

![telegram-cloud-photo-size-1-5127846508388003069-y](https://github.com/immersive-translate/immersive-translate/assets/62473795/9b537ae9-8421-4ed5-ac34-eddf89897113)

图中测试案例为 https://www.aozora.gr.jp/cards/000081/files/456_15050.html

### 出现问题的网址 | URL

https://www.aozora.gr.jp/cards/000081/files/456_15050.html

**Comment by keyboard3** [comment]
打开 https://dash.immersivetranslate.com/abount#about 更新下规则，然后重试下

**Comment by edr1412** [comment]
> 打开 [dash.immersivetranslate.com/abount#about](https://dash.immersivetranslate.com/abount#about)* 更新下规则，然后重试下

感谢，解决了
