### ISSUE TITLE
Please provide an option to disable sentry tracking

### ISSUE THREAD

**Issue by pfdgithub** [immersive-translate/immersive-translate#1488]
### 您希望的更新和改进是什么 | Update or Improve

For privacy and security reasons, please provide a close option.

```
https://sentry.immersivetranslate.com/api/xxx/envelope/?sentry_key=xxx&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.7.0
```

**Comment by keyboard3** [comment]
Currently sentry reporting is disabled, you can add the attribute `enableSentryReport: false` to Edit Full User Config at this [address](https://dash.immersivetranslate.com/#developer) to disable subsequent uploads.
