### ISSUE TITLE
How to config translate engine url?

### ISSUE THREAD

**Issue by wangchuan95** [immersive-translate/immersive-translate#149]
When I use Google translate engine, I found it's full url looks like:

`https://translate.googleapis.com/translate_a/single?client=gtx&dt=t&sl=en&tl=zh-CN&q=Getting+started`

I can't access `https://translate.googleapis.com/` but `https://translate.google.com/`. How to config it?

**Comment by theowenyoung** [comment]
If you use a VPN, maybe you should config your VPN to access translate.googleapis.com with proxy?

I don't believe translate.google.com is a valid API URL.

But actually you can custom the Google API at the developer settings, edit the user config like this:

```
{
  "translationServices":{
  "google":{
      "apiUrl":"https://translate.google.com"
   }
  }
}
```

**Comment by wangchuan95** [comment]
@theowenyoung Yes I used a VPN to access Google.

Thanks a lot, but it seems that you write the url in your code, my configurations don't work:

![Snipaste_2023-02-22_13-45-51](https://user-images.githubusercontent.com/17957083/220534870-4d053974-0979-478b-a119-1852edd71b94.png)

![Snipaste_2023-02-22_13-45-08](https://user-images.githubusercontent.com/17957083/220534897-1c09ac6b-5ce5-4abd-88dc-5ab4ec41cd91.png)

**Comment by theowenyoung** [comment]
Thanks, that's a mistake, I'll fix it next version.

I've tried to used `https://translate.google.com`, and it works!

good to know https://translate.google.com is an alternative for translate.googleapis.com

**Comment by wangchuan95** [comment]
@theowenyoung I updated, but my configurations still don't work.

```JSON
[
  {
    "translationServices": {
      "google": {
        "apiUrl": "https://translate.google.com/"
      }
    }
  }
]
```
