### ISSUE TITLE
iPad端文件翻译功能不可用🚫

### ISSUE THREAD

**Issue by HenanLee** [immersive-translate/immersive-translate#1493]
### 插件版本号 | Version

1.1.9

### 平台 | Platform

iOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![IMG_7238](https://github.com/immersive-translate/immersive-translate/assets/90303938/19417867-e352-4029-a8cf-908ff3978fc6)
![IMG_0660](https://github.com/immersive-translate/immersive-translate/assets/90303938/9f572cb1-7a75-4cb4-a720-58d01b0a6c94)
同样的插件版本，手机Safari正常使用文件翻译，iPad上一倒入文件就是这个界面，点按操作没有反应，iPad上很多个版本了，都是这样不能使用。

### 出现问题的网址 | URL

https://app.immersivetranslate.com/

**Comment by keyboard3** [comment]
Safari版本太低了， 去商店安装沉浸式翻译浏览器
