### ISSUE TITLE
希望译文显示样式可以选择多种叠加显示

### ISSUE THREAD

**Issue by freedomspiritJohn** [immersive-translate/immersive-translate#1494]
### 您希望的更新和改进是什么 | Update or Improve

希望译文显示样式可以选择多种叠加显示

### 补充说明 | Additional context

此外希望添加一种新的译文显示样式---新模糊效果（学习模式）：具体就是一开始全都是模糊现实，点击哪块哪块就显示出来，这样不用鼠标一直悬停在翻译区域，更方便去查单词等操作。

**Comment by theowenyoung** [comment]
是不是 【鼠标悬停翻译】也能满足需求？

**Comment by freedomspiritJohn** [comment]
> 是不是 【鼠标悬停翻译】也能满足需求？

但是鼠标得一直悬停在那，这样我去查找单词或者鼠标在别的地方的时候，就无法看到翻译的内容了

**Comment by flamintune** [comment]
想问一下，你想要的译文叠加效果是哪种呢，我们更倾向于为每种预设译文样式增加一些单独的配置项，如下图这种，为各种预设样式添加单独的配置

![image](https://github.com/immersive-translate/immersive-translate/assets/79519446/9a8cbb0c-f925-4364-b75f-e9ad56cc993a)

**Comment by freedomspiritJohn** [comment]
> 想问一下，你想要的译文叠加效果是哪种呢，我们更倾向于为每种预设译文样式增加一些单独的配置项，如下图这种，为各种预设样式添加单独的配置
> 
> ![image](https://private-user-images.githubusercontent.com/79519446/334027131-9a8cbb0c-f925-4364-b75f-e9ad56cc993a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3OTkyNjEsIm5iZiI6MTcxNjc5ODk2MSwicGF0aCI6Ii83OTUxOTQ0Ni8zMzQwMjcxMzEtOWE4Y2JiMGMtZjkyNS00MzY0LWI3NWYtZTlhZDU2Y2M5OTNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDA4MzYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMWFmMGQ4MDI0YzEwOTNiMGY5YjE1YTFiODI0ZjVmZWE5NTZmMDBkYTIzYmM3ZDgxNTU4NWFhMzAwODg1NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ihArs3vEZZM-zKPxm_t-VE8X6weoOk01lBS4-kkhyYY)

![image](https://github.com/immersive-translate/immersive-translate/assets/129288685/e90cd374-0a20-4be9-8dc7-5ec6b91b6a0c)
比如，我可以同时应用马克笔，下划线，斜体和加粗等样式。当然也有一些可能互斥的选项，所以实现起来可能需要不同的组合项，其实加不加影响也不大，看你们怎么想了。

**Comment by flamintune** [comment]
在最新的1.5.7中支持了字重和斜体的设置，欢迎体验。对于马克笔，下划线这种因为存在混合的属性比如颜色，后面会看反馈情况再决定是否添加进来。

**Comment by flamintune** [comment]
至于新的译文显示样式---新模糊效果（学习模式），暂时不在计划内，实现起来不太容易，后面看如果用户需求大的话可能会做这个东西。
