### ISSUE TITLE
 阅读本地电子书，希望加上控制文字大小功能 Feature Request: Text Size Control for Local Ebook Reader

### ISSUE THREAD

**Issue by glows** [immersive-translate/immersive-translate#1495]
### 您希望的更新和改进是什么 | Update or Improve

阅读本地电子书， 希望加上控制文字大小功能

Regarding the feature to read local ebooks, I would kindly request the ability to control and adjust the text size. This added functionality would greatly enhance the reading experience. Thank you for your consideration.

**Comment by theowenyoung** [comment]
Hi, you can use `cmd +`, or `cmd -`  to change the page size, so the font size will follow it.
