### ISSUE TITLE
双语模式下，左右标题面板可以设置为仅显示译文

### ISSUE THREAD

**Issue by QingWoBen** [immersive-translate/immersive-translate#1497]
### 您希望的更新和改进是什么 | Update or Improve

双语模式下，左右标题面板可以设置为仅显示译文；
能够智能识别左右标题面板，如果识别错误可以一键手动框选范围。

### 补充说明 | Additional context

标题面板双语对照破坏了文章结构，很是混乱，而且标题一般很短。

**Comment by keyboard3** [comment]
给个具体示例网址，不懂什么是标题面板

**Comment by QingWoBen** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/149484872/4c640901-d980-427b-aa9a-029d8888092c)
https://docs.librechat.ai/deployment/huggingface.html
