### ISSUE TITLE
[Bug]: 360极速浏览器 版本号:13.5.2044.0，内核版本:86.0.4240.198，无法安装，如下

### ISSUE THREAD

**Issue by Fuweng365** [immersive-translate/immersive-translate#1502]
### 插件版本号 | Version

1.1.9_0 crx

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 请描述这个Bug | Describe the bug

![微信截图_20240306105932](https://github.com/immersive-translate/immersive-translate/assets/45345088/3e8ed9c4-093d-405b-be45-6ca793015ef0)
![微信截图_20240306105955](https://github.com/immersive-translate/immersive-translate/assets/45345088/6215706e-0af9-4802-8fac-1707cdfb0490)
![微信截图_20240306110011](https://github.com/immersive-translate/immersive-translate/assets/45345088/13323638-fe22-46f1-a9ce-af8da43c4abc)
如上异常，无法安装

**Comment by keyboard3** [comment]
chrome内核太低了，升级最新的浏览器
