### ISSUE TITLE
FreeBSD online manual pages support

### ISSUE THREAD

**Issue by Song-Tianxiang** [immersive-translate/immersive-translate#1504]
### 您希望的更新和改进是什么 | Update or Improve

Can we support website [FreeBSD online manual pages](https://man.freebsd.org/cgi/man.cgi)?

**Comment by keyboard3** [comment]
Open [this address](https://dash.immersivetranslate.com/abount#about) and try again

**Comment by Song-Tianxiang** [comment]
Works now, thank you
