### ISSUE TITLE
沉浸式翻譯 YouTube雙語字幕繁體中文bug

### ISSUE THREAD

**Issue by thomasTAT** [immersive-translate/immersive-translate#1505]
### 您希望的更新和改进是什么 | Update or Improve

能不能, 給繁體中文用戶, 雙語字幕字幕改成簡體, 這樣就不會有bug.
或者單獨設置某個網站默認翻譯為簡體..

**Comment by keyboard3** [comment]
1.3.1 繁体字幕问题已修复
