### ISSUE TITLE
[Bug]: 微软翻译不可用

### ISSUE THREAD

**Issue by genesofar** [immersive-translate/immersive-translate#1506]
### 插件版本号 | Version

1.2.4

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/33246763/3c1855b6-be3a-4893-b3e1-5780418041b6)
![error](https://github.com/immersive-translate/immersive-translate/assets/33246763/cc6a336b-9c72-428a-90a3-80fbe53677d0)
![error](https://github.com/immersive-translate/immersive-translate/assets/33246763/a2c59b15-d5ad-4968-b028-bc5e3b261846)

### 出现问题的网址 | URL

https://github.com/

**Comment by keyboard3** [comment]
这是自身网络访问微软翻译服务失败，尝试切换网络代理或者使用其他可用翻译服务
