### ISSUE TITLE
[Bug]: 转换为 HTML 时出现致命错误并突然退出。本文档可能被截断或损坏。

### ISSUE THREAD

**Issue by hlcle** [immersive-translate/immersive-translate#1507]
### 插件版本号 | Version

V1.2.4

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari, Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

对arxiv在线论文进行翻译的时候，有的论文不能翻译，显示：
Conversion to HTML had a Fatal error and exited abruptly. This document may be truncated or damaged.
转换为 HTML 时出现致命错误并突然退出。本文档可能被截断或损坏。
![Snipaste_2024-03-07_10-28-29](https://github.com/immersive-translate/immersive-translate/assets/63539519/34f57be0-74dd-4cf7-a878-a2da6de15a04)
 

### 出现问题的网址 | URL

https://arxiv.org/abs/2402.10200

### 重现步骤 | To Reproduce

进入网页
点击右边”双语版本“

### 补充说明 | Additional context

有的论文会出现这样问题

**Comment by keyboard3** [comment]
没懂 你这个明显是arxiv自己在转HTML文档时候出的问题啊，跟插件有啥关系，你不翻译也是这个错误啊
