### ISSUE TITLE
[Bug]: 与Noir暗黑模式冲突。

### ISSUE THREAD

**Issue by huio** [immersive-translate/immersive-translate#1508]
### 插件版本号 | Version

1.2.3

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension
油猴脚本

### 请描述这个Bug | Describe the bug

同时开启Noir插件和immersive translate，Noir暗黑模式会生效1秒然后被immersive translate所更改。
请勿在我点击翻译按钮之前对我的网页进行任何侵入性修改。

### 出现问题的网址 | URL

任何

**Comment by flamintune** [comment]
未能成功复现，能录下屏不

**Comment by huio** [comment]
> 未能成功复现，能录下屏不
视频较大，无法上传Github。已上传OneDrive。请下载观看。在线很糊。

https://microsoftproduct-my.sharepoint.com/:v:/g/personal/microsoft_microsoftproduct_onmicrosoft_com/Ecok64gBv6JNocNYs63PyykBWXWLOVb6TIxfAQCruHud7w?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=C5mH50

**Comment by flamintune** [comment]
能再麻烦生成下两个网页快照吗，方便我们去debug，分别是带沉浸式翻译变白的和关了沉浸式翻译变黑的，生成网页快照的方法在悬浮球的弹窗中
![image](https://github.com/immersive-translate/immersive-translate/assets/79519446/15063ed1-b464-450e-b192-235d9e646212)

**Comment by huio** [comment]
> 能再麻烦生成下两个网页快照吗，方便我们去debug，分别是带沉浸式翻译变白的和关了沉浸式翻译变黑的，生成网页快照的方法在悬浮球的弹窗中 ![image](https://private-user-images.githubusercontent.com/79519446/329451017-15063ed1-b464-450e-b192-235d9e646212.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMTUyMDMsIm5iZiI6MTcxNTMxNDkwMywicGF0aCI6Ii83OTUxOTQ0Ni8zMjk0NTEwMTctMTUwNjNlZDEtYjQ2NC00NTBlLWIxOTItMjM1ZDllNjQ2MjEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA0MjE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkM2ExODAxOWEzNjM4MWIzN2QxN2U0ZWMxNTkwZDU5YWVhZWMxZjQ0NTQ4ZGQ4MmYyNDgwYWYyNjE4MjcxZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6PBfOp7IZptDxBw-qps6fXf3t-OJegRAHXq3POe9yVk)

带沉浸式翻译变白的
https://readit.site/a/PZdj5
关了沉浸式翻译变黑的
这个没有悬浮球了。如何获取快照？

**Comment by huio** [comment]
> > 能再麻烦生成下两个网页快照吗，方便我们去debug，分别是带沉浸式翻译变白的和关了沉浸式翻译变黑的，生成网页快照的方法在悬浮球的弹窗中 ![image](https://private-user-images.githubusercontent.com/79519446/329451017-15063ed1-b464-450e-b192-235d9e646212.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMTUyMDMsIm5iZiI6MTcxNTMxNDkwMywicGF0aCI6Ii83OTUxOTQ0Ni8zMjk0NTEwMTctMTUwNjNlZDEtYjQ2NC00NTBlLWIxOTItMjM1ZDllNjQ2MjEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA0MjE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkM2ExODAxOWEzNjM4MWIzN2QxN2U0ZWMxNTkwZDU5YWVhZWMxZjQ0NTQ4ZGQ4MmYyNDgwYWYyNjE4MjcxZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6PBfOp7IZptDxBw-qps6fXf3t-OJegRAHXq3POe9yVk)
> 
> 带沉浸式翻译变白的 https://readit.site/a/PZdj5 关了沉浸式翻译变黑的 这个没有悬浮球了。如何获取快照？

页面是白的，快照是黑的。估计你们难排查

**Comment by huio** [comment]
> > > 能再麻烦生成下两个网页快照吗，方便我们去debug，分别是带沉浸式翻译变白的和关了沉浸式翻译变黑的，生成网页快照的方法在悬浮球的弹窗中 ![image](https://private-user-images.githubusercontent.com/79519446/329451017-15063ed1-b464-450e-b192-235d9e646212.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMTUyMDMsIm5iZiI6MTcxNTMxNDkwMywicGF0aCI6Ii83OTUxOTQ0Ni8zMjk0NTEwMTctMTUwNjNlZDEtYjQ2NC00NTBlLWIxOTItMjM1ZDllNjQ2MjEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA0MjE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkM2ExODAxOWEzNjM4MWIzN2QxN2U0ZWMxNTkwZDU5YWVhZWMxZjQ0NTQ4ZGQ4MmYyNDgwYWYyNjE4MjcxZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6PBfOp7IZptDxBw-qps6fXf3t-OJegRAHXq3POe9yVk)
> > 
> > 
> > 带沉浸式翻译变白的 https://readit.site/a/PZdj5 关了沉浸式翻译变黑的 这个没有悬浮球了。如何获取快照？
> 
> 页面是白的，快照是黑的。估计你们难排查

经过测试，仅在开启悬浮球情况下会变白。
