### ISSUE TITLE
密钥配置页面优化

### ISSUE THREAD

**Issue by scruel** [immersive-translate/immersive-translate#151]
可以参考下这个插件，支持多种密钥服务，同服务多个密钥，界面也挺直观：
https://hcfy.app
![image](https://user-images.githubusercontent.com/16933298/220518722-f8944ed3-8bb9-4807-a255-465685611f09.png)

**Comment by theowenyoung** [comment]
(也许 如果我们有自己的翻译积分后可以这么搞...

目前感觉还好呀？

**Comment by scruel** [comment]
> (也许 如果我们有自己的翻译积分后可以这么搞...
> 
> 目前感觉还好呀？

其实主要是希望能支持填写多个 key

**Comment by XHXIAIEIN** [comment]
目前可以在[开发者设置](https://immersive-translate.owenyoung.com/options/#developer)里面，编辑 `Edit Full User Config` 手动填入JSON 数据，这样会比较快：

```json
{
  "translationServices": {
    "volc": {
      "accessKeyId": "",
      "secretAccessKey": ""
    },
    "tencent": {
      "secretId": "",
      "secretKey": ""
    },
    "baidu": {
      "appid": "",
      "key": ""
    },
    "caiyun": {
      "token": ""
    },
    "youdao": {
      "appId": "",
      "appSecret": ""
    },
    "azure": {
      "APIKEY": ""
    },
    "deepl": {
      "authKey": ""
    },
    "openl": {
      "apikey": ""
    },
    "niu": {
      "APIKEY": ""
    }
  }
}
```

**Comment by scruel** [comment]
@XHXIAIEIN 仍然不支持同服务配置多个 key，这样如果某个key额度用完了，可以自动换下一个。

**Comment by theowenyoung** [comment]
目前已在大多数服务中支持用 , 分割多个 key哈。 比如 deepl, openai, caiyun 等.
