### ISSUE TITLE
OpenAI 的 API Key 负载均衡希望能实现真正的轮流使用，而不是随机选取

### ISSUE THREAD

**Issue by cssmagic** [immersive-translate/immersive-translate#1510]
### 您希望的更新和改进是什么 | Update or Improve

现在的 “负载均衡” 效果似乎是随机选取一个，还是比较容易触发 API 的调用频率限制。因此希望能实现真正的轮流使用，让每个 Key 获得最大化的冷却时间。

谢谢！

**Comment by theowenyoung** [comment]
由于网页翻译请求数确实有点多，所以还是建议使用更稳定的API，解决这个频率限制问题可能不是沉浸式翻译的重点。

**Comment by cssmagic** [comment]
理解 😭
