### ISSUE TITLE
[Bug]: OpenAI 模型输出的分割符不一定完全严谨，导致分段错误

### ISSUE THREAD

**Issue by cssmagic** [immersive-translate/immersive-translate#1511]
### 插件版本号 | Version

1.2.4

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

程序在一次发送多段原文时，使用 `\n\n%%\n\n` 作为分段标志。但 AI 模型输出的译文不一定每次都能完全符合这个格式，导致解析阶段分段错误，页面上出现 `%%` 或中英对应关系错位。

我弱弱地问一句，为什么不是在发送阶段简单地用 `\n\n` 拼接，然后在解析阶段用 `/\n+/` 来分段？（或许是有其他苦衷？不妨说来听听，我们一起想办法。）

---

模型返回：

![Screen-Shot-2024-03-07-at-11 44 53pm](https://github.com/immersive-translate/immersive-translate/assets/1231359/8040aedf-fff7-445b-848b-6c2379b2ff82)

页面效果：

![Screen-Shot-2024-03-07-at-11 44 47pm](https://github.com/immersive-translate/immersive-translate/assets/1231359/bbe8b15c-79a8-4e28-9722-30e46de41151)

**Comment by theowenyoung** [comment]
因为 \n\n 模型也不总是会尊重，目前的分隔符算是模型比较尊重的...

不过这个还有优化的空间，我们准备尝试用 json 来做分段的尝试，类似：

```json
{
   "1":"第一段",
   "2":"第二段"
}
```

**Comment by cssmagic** [comment]
谢谢回复。

在现有的方案下，解析阶段能不能优化一下对分隔符的匹配。比如 `/\n+%+\n+/` 这种宽松一点的方式。

**Comment by theowenyoung** [comment]
目前可以在开发者设置里面 手动修改这个分隔符配置：

```
{
    "translationServices": {
    "openai": {
      "translationTextSeparator": "\n\n%%\n\n"
    }
    }
}
```

**Comment by cssmagic** [comment]
另外我也讨论一下 JSON 方案。

用 JSON 应该会让模型更严谨。不过也有一些短处：

* 系统提示词会复杂很多。用户容易改崩。
* 模型倾向于把 JSON 包在一个代码块里，程序拿到响应之后需要去除头尾标记。这个环节有一定风险。

**Comment by cssmagic** [comment]
> 目前可以在开发者设置里面 手动修改这个分隔符配置： 

太好了，谢谢提示！

**Comment by theowenyoung** [comment]
> 另外我也讨论一下 JSON 方案。
> 
> 用 JSON 应该会让模型更严谨。不过也有一些短处：
> 
> * 系统提示词会复杂很多。用户容易改崩。
> * 模型倾向于把 JSON 包在一个代码块里，程序拿到响应之后需要去除头尾标记。这个环节有一定风险。

默认情况下，是每个请求只包含一段内容。所以理论上只有多段的情况下需要用 json 的prompt，所以这里可能会默认不提供 ui 界面给用户， power user 可以通过 开发者模式修改 多段内容的 prompt？

不过不管怎么说，如果做这个变更的话，我们会进行各种测试，只有它的表现在绝大多数情况都ok的时候 我们才会上。

**Comment by cssmagic** [comment]
我把分割符改成 `\n***\n` 之后极其稳定。毕竟是标准的 Markdown 语法嘛。嘻嘻。

分段的问题解决了之后，我就可以放心地把 “每次请求最大段落数” 加到 10。这样 API 的调用频率会极大地降低，比如像 #1510 这个问题也就变得不那么急迫了（但还是希望能解决 🙏 ）。

🎉🎉🎉

**Comment by theowenyoung** [comment]
如果可以的话，你可以使用几天之后，再来报告一下情况，我们可会测试一下这个分隔符是否更加稳定。

**Comment by cssmagic** [comment]
好的，没问题。

**Comment by syaoranwe** [comment]
According to the course taught by Andrej Karpathy after leaving OpenAI ([src](https://www.promptingguide.ai/research/llm-tokenization)), using YAML format is more stable than JSON format due to the tokenization of LLMs.

> 因为 \n\n 模型也不总是会尊重，目前的分隔符算是模型比较尊重的...
> 
> 不过这个还有优化的空间，我们准备尝试用 json 来做分段的尝试，类似：
> 
> ```json
> {
>    "1":"第一段",
>    "2":"第二段"
> }
> ```

**Comment by gchuyun** [comment]
> 因为 \n\n 模型也不总是会尊重，目前的分隔符算是模型比较尊重的...
> 
> 不过这个还有优化的空间，我们准备尝试用 json 来做分段的尝试，类似：
> 
> ```json
> {
>    "1":"第一段",
>    "2":"第二段"
> }
> ```

json或者yaml是个好方案，希望格式是可扩展的，可以兼容用户自定义的prompt，只要最终结果包含插件需要的字段即可。

比如，我可以让AI用2段式翻译，先直译，再意译，那么结果可能为：
```yaml
results:
   - id: 1,
     first_result: "直译结果1",
     result: "意译结果1"
   -id: 2
     first_result: "直译结果2",
     result: "意译结果2"
```
只要结果包含插件需要的id和result即可，而用户自定义prompt产生的字段插件可以直接忽略

**Comment by cssmagic** [comment]
@syaoranwe 
谢谢提醒，yaml 确实比 JSON 更简洁。不过对插件程序来说，就需要额外的解析步骤了。

**Comment by cssmagic** [comment]
@gchuyun 
我相信两段式翻译确实会提升翻译质量。不过对于插件这个场景，快捷性要大于质量。

两段式翻译在程序复杂度、响应速度、API 消耗方面的成本都太高了。

两段式翻译或许更适合用在专业的翻译系统上。

**Comment by gchuyun** [comment]
@cssmagic 
是的，我是在翻译电子书时需要这个功能，离线场景而且少量使用不太在意token消耗，如果作者采用JSON或YAML的话，并不会增加开发量

**Comment by cssmagic** [comment]
> 如果可以的话，你可以使用几天之后，再来报告一下情况，我们可会测试一下这个分隔符是否更加稳定。

@theowenyoung 
感觉相当稳定。没遇到错位问题。

**Comment by theowenyoung** [comment]
> > 如果可以的话，你可以使用几天之后，再来报告一下情况，我们可会测试一下这个分隔符是否更加稳定。
> 
> @theowenyoung 感觉相当稳定。没遇到错位问题。

刚试了一个，


https://news.lenovo.com/pressroom/press-releases/unleashing-innovation-and-better-sustainability-of-lenovos-latest-thinkpad-l-series-and-x-series-laptops/

好像还是不完美：

![CleanShot 2024-03-21 at 00 58 28@2x](https://github.com/immersive-translate/immersive-translate/assets/62473795/bd648f38-b8c0-489a-af0c-58f7d7c4892f)



body:
```
{
  "model": "gpt-3.5-turbo-0613",
  "temperature": 0,
  "messages": [
    {
      "role": "system",
      "content": "你是一个专业,地道的翻译引擎，你只返回译文，不含任何解释"
    },
    {
      "role": "user",
      "content": "请翻译为简体中文（避免解释原文）:\n\n Unleashing Innovation and Better Sustainability of Lenovo’s Latest ThinkPad L Series and X Series Laptops \n***\n19 March 2024\n***\nNew ThinkPad™ L14 i Gen 5, L16 i Gen 1, L13 Gen 5, L13 2-in-1 Gen 5, X13 Gen 5 and X13 2-in-1 Gen 5 featuring Intel® Core® Ultra™ processors with Intel vPro® are AI PCs ready to take AI workflows to the next level\n***\nThinkPad L14 Gen 5 and L16 Gen 1 available with AMD Ryzen™ PRO 7030 Series Processors\n***\nMarch 19, 2024 – Today, Lenovo™ launched its latest business laptop offerings in the form of the ThinkPad™ L series and ThinkPad X13 series. The new laptops are a testament to Lenovo’s commitment to innovation and sustainability with features such as enhanced repairability, more recycled materials, efficient power management, and powerful processing capabilities with built-in security and manageability. With these offerings, Lenovo is not only showcasing its technological expertise but also its dedication to supporting a diverse customer base in achieving success across many business segments."
    }
  ]
```

**Comment by syaoranwe** [comment]
> > > 如果可以的话，你可以使用几天之后，再来报告一下情况，我们可会测试一下这个分隔符是否更加稳定。
> > 
> > 
> > @theowenyoung 感觉相当稳定。没遇到错位问题。
> 
> 刚试了一个，
> 
> https://news.lenovo.com/pressroom/press-releases/unleashing-innovation-and-better-sustainability-of-lenovos-latest-thinkpad-l-series-and-x-series-laptops/
> 
> 好像还是不完美：
> 
> ![CleanShot 2024-03-21 at 00 58 28@2x](https://private-user-images.githubusercontent.com/62473795/314594929-bd648f38-b8c0-489a-af0c-58f7d7c4892f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMjc4NjIsIm5iZiI6MTcxMTAyNzU2MiwicGF0aCI6Ii82MjQ3Mzc5NS8zMTQ1OTQ5MjktYmQ2NDhmMzgtYjhjMC00ODlhLWFmMGMtNThmN2Q3YzQ4OTJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDEzMjYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjZDYxNzEwNWJkNzYxMmZlMzNhZTI5Y2UzMzM0NmEyM2FkNjhjOGYwM2M4MDgzYTdjYTU4NGJiZWE1NmQxN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ghwTl0S74kw0HHRFu8euhdZVbfrE85Y2uBdij_f6Dlw)
> 
> body:
> 
> ```
> {
>   "model": "gpt-3.5-turbo-0613",
>   "temperature": 0,
>   "messages": [
>     {
>       "role": "system",
>       "content": "你是一个专业,地道的翻译引擎，你只返回译文，不含任何解释"
>     },
>     {
>       "role": "user",
>       "content": "请翻译为简体中文（避免解释原文）:\n\n Unleashing Innovation and Better Sustainability of Lenovo’s Latest ThinkPad L Series and X Series Laptops \n***\n19 March 2024\n***\nNew ThinkPad™ L14 i Gen 5, L16 i Gen 1, L13 Gen 5, L13 2-in-1 Gen 5, X13 Gen 5 and X13 2-in-1 Gen 5 featuring Intel® Core® Ultra™ processors with Intel vPro® are AI PCs ready to take AI workflows to the next level\n***\nThinkPad L14 Gen 5 and L16 Gen 1 available with AMD Ryzen™ PRO 7030 Series Processors\n***\nMarch 19, 2024 – Today, Lenovo™ launched its latest business laptop offerings in the form of the ThinkPad™ L series and ThinkPad X13 series. The new laptops are a testament to Lenovo’s commitment to innovation and sustainability with features such as enhanced repairability, more recycled materials, efficient power management, and powerful processing capabilities with built-in security and manageability. With these offerings, Lenovo is not only showcasing its technological expertise but also its dedication to supporting a diverse customer base in achieving success across many business segments."
>     }
>   ]
> ```

in my case this page's test. it's stable.

```json
    "openai": {
      "APIKEY": "key",
      "apiUrl": "https://api.together.xyz/v1/chat/completions",
      "limit": "1",
      "maxTextGroupLengthPerRequest": "10",
      "maxTextLengthPerRequest": "2000",
      "model": "Qwen/Qwen1.5-14B-Chat",
      "prompt": "你是一个专业翻译引擎，擅长充分考虑上下文和语境以提供完整、准确且自然流畅的翻译。将下面提供给你的文本翻译为{{to}}，不要遗漏原文信息，译文中需要保留原文中的换行和分隔符\\n***\\n，只需回复我译文.",
      "provider": "custom",
      "systemPrompt": "You are a professional translation engine that excels at providing complete, accurate, and natural translations while taking context into full consideration. You only return the translated text.",
      "translationTextSeparator": "\n***\n"
```

![20240321213020](https://github.com/immersive-translate/immersive-translate/assets/52595143/917013e6-83c7-41d2-993b-e78d4ec02f37)

**Comment by theowenyoung** [comment]
@syaoranwe 嗯，似乎你的 Prompt 也做了处理。我测试一下。

昨天测试了一下用 JSON 要要求 openai 翻译视频的字幕，测试下来，似乎挺稳定的：

大概的 prompt 如下：

```
完成将视频字幕文件翻译为 {{to}} 的任务，要求如下：

1. 这是视频的字幕文件，所以请务必考虑这些句子的上下文，如果上下 2 句才能组成完整的一句话，那么为了完整性，上下两句 translation 都使用完整的译文。
2. 必须补全每一个 translation 字段。
3. 请返回标准的 JSON ：


示例结果：

[
  {
    "id": 1,
    "source": "source",
    "translation": "译文"
  },
  {
    "id": 2,
    "source": "source",
    "translation": "译文"
  }
]

开始翻译：

{{text}}
```

原文 json：

```json
原文json是这样：


 [
  {
    "id": 1,
    "source": "to the more level-headed man swinging a pitchfork.",
    "translation": ""
  },
  {
    "id": 2,
    "source": "(audience laughing)",
    "translation": ""
  },
  {
    "id": 3,
    "source": "And I swear, I swear.",
    "translation": ""
  },
  {
    "id": 4,
    "source": "We made eye contact,",
    "translation": ""
  },
  {
    "id": 5,
    "source": "and he rolled his eyes as if to say,",
    "translation": ""
  },
  {
    "id": 6,
    "source": "\"Could you believe this (beep) guy?\"",
    "translation": ""
  }
]
```

**Comment by keyboard3** [comment]
1.4.2+ 用了yaml格式来保证分段一致性，测下来比较稳定
