### ISSUE TITLE
能否优化对 ::before 标签以及 下拉框的翻译问题

### ISSUE THREAD

**Issue by Kerkong** [immersive-translate/immersive-translate#1512]
### 您希望的更新和改进是什么 | Update or Improve

能否优化对 ::before 标签以及 下拉框的翻译问题 这是我学习的网站 经常会出现 ::before 标签展开不翻译，还有下拉框不翻译的问题
https://tryhackme.com/

**Comment by keyboard3** [comment]
截图示例下

**Comment by keyboard3** [comment]
暂无反馈 关闭此issue
