### ISSUE TITLE
在译文与原文相同的情况下，也希望输出译文，否则可能逼死强迫症（见图）

### ISSUE THREAD

**Issue by cssmagic** [immersive-translate/immersive-translate#1513]
### 您希望的更新和改进是什么 | Update or Improve

先上个图：

![Screen-Shot-2024-03-08-at-12 10 23am](https://github.com/immersive-translate/immersive-translate/assets/1231359/af37c94b-5c14-46a5-982b-8f1481cb24ee)

我能理解在这种情况下省略译文的好处。但同时也有坏处：

* 排版不整齐。
* 我不知道这里是翻译出错了，还是译文与原文相同。

所以，请给个进阶选项吧。感谢！

**Comment by theowenyoung** [comment]
如果在考虑下很多文章里出现的：

一行 url： https://example.com/xxxxx

一个电子邮件：  xxxx@email.com


这种情况你也像同时显示2行吗？

**Comment by cssmagic** [comment]
是的，我希望的。

我的配置是这样的：

* 译文换行设置：总是换行
* 译文显示样式：弱化

因此即使有两行一样的英文，对我也不会有很大的干扰。

**Comment by theowenyoung** [comment]
好吧😑

但是实际中其实并不好做，因为不翻译会涉及到多种情况... 并不是只有 翻译服务返回一样的字符才不展示。

比如：

1. #blacklivesmatters 这种 hash 会不翻译
2. 100% 这种类数字不会翻译
3. 默认情况下小于等于3个字符的 word 不会被翻译

...

所以可能并不好提供....

**Comment by cssmagic** [comment]
如果我没有理解错的话，上面这几种情况都是不会发给翻译引擎的，对吧？

如果是，那么就比较容易界定了——从翻译引擎那里拿到的译文不论是否与原文相同都显示。我期望的只是这个，不涉及上面这几种直接跳出翻译逻辑的情况。

---

我最开始提出这个请求，其实是这么理解的：从编程的角度来看，“不显示与原文相同的译文” 这个行为其实是一个附加行为，程序肯定是做了判断的。因此提供一个开关来控制这个附加行为，应该是比较容易的……吧。 :wink:

**Comment by cssmagic** [comment]
是的，强迫症是少数。

希望有更多的强迫症进来 +1 给作者看看。
