### ISSUE TITLE
希望超链接不进行翻译直接复制到翻译中

### ISSUE THREAD

**Issue by h-dxgfx** [immersive-translate/immersive-translate#1515]
### 您希望的更新和改进是什么 | Update or Improve

希望超链接不进行翻译直接复制到翻译中
![image](https://github.com/immersive-translate/immersive-translate/assets/91577525/8645b006-8c83-4d15-9bd1-15e43f0a2bd5)
像上图中的超链接完全可以不翻译，直接将超链接复制到翻译中就好

**Comment by keyboard3** [comment]
你可以参考这个文档 https://immersivetranslate.com/docs/advanced/ 设置指定网站的超链接保留。
类似文档中[自定义网站部分](https://immersivetranslate.com/docs/advanced/#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BD%91%E7%AB%99%E9%80%82%E9%85%8D), 添加 `stayOriginalSelectors.add` key
