### ISSUE TITLE
[Bug]: 在翻译油管视频的时候好像有闪屏的现象

### ISSUE THREAD

**Issue by 2633465169** [immersive-translate/immersive-translate#1517]
### 插件版本号 | Version

0.5.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

油管全屏观看时翻译有闪屏的现象。其他的平台没有试过。

### 出现问题的网址 | URL

https://www.youtube.com/

**Comment by theowenyoung** [comment]
更新到最新版试试呢

**Comment by keyboard3** [comment]
版本太低了 升级版本
