### ISSUE TITLE
【翻译文本支持公式或Tex结构】

### ISSUE THREAD

**Issue by LHC00** [immersive-translate/immersive-translate#1518]
### 您希望的更新和改进是什么 | Update or Improve

当前翻译后的文本中，会丢失原文中的公式。希望对于同时具有字符和公式的段落，在译文中保留公式。
![image](https://github.com/immersive-translate/immersive-translate/assets/70308447/171bb323-7ef9-4401-ab70-b7839de9383f)

**Comment by FattySpring** [comment]
发下页面地址

**Comment by LHC00** [comment]
> 发下页面地址

https://pbr-book.org/4ed/Introduction/pbrt_System_Overview

**Comment by keyboard3** [comment]
https://dash.immersivetranslate.com/#about 打开这个链接更新下规则，然后重试下

**Comment by LHC00** [comment]
> https://dash.immersivetranslate.com/#about 打开这个链接更新下规则，然后重试下

可以了，给力啊大佬
![image](https://github.com/immersive-translate/immersive-translate/assets/70308447/4b27aa51-ebd5-4853-b465-0912353d4692)
