### ISSUE TITLE
 outlook邮箱网页版无法自动匹配段落

### ISSUE THREAD

**Issue by scruel** [immersive-translate/immersive-translate#152]
![image](https://user-images.githubusercontent.com/16933298/220519082-7f40e91a-74ca-449a-87d2-49b43000cffb.png)
![image](https://user-images.githubusercontent.com/16933298/220519096-4b7fbae9-ec8c-4341-a0b5-b6e09a363997.png)

**Comment by theowenyoung** [comment]
@XHXIAIEIN 我们似乎没对outlook进行过适配，只对gmail进行过适配。


不过请问这个是全部邮件都这样吗？还是特定的这个邮件？

你可以转发一下这个邮件给我吗： `owen@owenyoung.com`

**Comment by XHXIAIEIN** [comment]
我康康，我来适配一下

**Comment by scruel** [comment]
> @XHXIAIEIN 我们似乎没对outlook进行过适配，只对gmail进行过适配。
> 
> 不过请问这个是全部邮件都这样吗？还是特定的这个邮件？
> 
> 你可以转发一下这个邮件给我吗： `owen@owenyoung.com`

部分邮件会这样，已转发。

**Comment by theowenyoung** [comment]
<img width="1116" alt="Screenshot 2023-02-22 at 12 25 14" src="https://user-images.githubusercontent.com/62473795/220521658-1b60aa9d-7370-4c47-a4a6-394b8f45f396.png">

这个似乎是邮件本身的问题？

因为它自己在html里强制换行了..

@XHXIAIEIN 所以适配的话，可能只是像gmail一样，对列表，还有内容区域做一个指定区域翻译？

像这种特殊的邮件的格式，感觉没法判断？

**Comment by XHXIAIEIN** [comment]
我试着对div里面的段落添加区域翻译，应该能改善一些？
```
"atomicBlockSelectors": [
   "div p"
],
```

**Comment by scruel** [comment]
刚看确实是邮件本身换行了，感觉处理起来有点困难，还有那种 `>>>` 开头的也是，或许能在元素右上角有一个hover后显示的标记，从某个 node 进行解析的选项？交互上还可以考虑下，但这样也会增加操作成本。

**Comment by theowenyoung** [comment]
> 我试着对div里面的段落添加区域翻译，应该能改善一些？
> 
> ```
> "atomicBlockSelectors": [
>     "div p:has(span)"
> ],
> ```

好像这样还不错，就是不知道有没有更奇怪的邮件格式。

邮件格式千奇百怪的..

**Comment by theowenyoung** [comment]
> 刚看确实是邮件本身换行了，感觉处理起来有点困难，还有那种 `>>>` 开头的也是，或许能在元素右上角有一个hover后显示的标记，从某个 node 进行解析的选项？交互上还可以考虑下，但这样也会增加操作成本。

>>> 开头是是引用前文吗？ 这种情况你希望理想的做法是？

**Comment by scruel** [comment]
@theowenyoung 如果能有一个忽略翻译的规则，甚至特例如何进行操作的规则列表就好了。
~~（嗯？怎么又来了第二个需求）~~

**Comment by XHXIAIEIN** [comment]
> 如果能有一个忽略翻译的规则，甚至特例如何进行操作的规则列表就好了。

目前已经可以在 `开发者设置 - Edit User Rules` 里面自己适配特定的网站。具体的文档可以看这里：[高级自定义选项](https://immersive-translate.owenyoung.com/advanced#%E9%AB%98%E7%BA%A7%E8%87%AA%E5%AE%9A%E4%B9%89%E9%80%89%E9%A1%B9)](https://immersive-translate.owenyoung.com/advanced)

**Comment by scruel** [comment]
> > 如果能有一个忽略翻译的规则，甚至特例如何进行操作的规则列表就好了。
> 
> 目前已经可以在 `开发者设置 - Edit User Rules` 里面自己适配特定的网站。具体的文档可以看这里：[高级自定义选项](https://immersive-translate.owenyoung.com/advanced#%E9%AB%98%E7%BA%A7%E8%87%AA%E5%AE%9A%E4%B9%89%E9%80%89%E9%A1%B9)

好的谢谢

**Comment by scruel** [comment]
> > 如果能有一个忽略翻译的规则，甚至特例如何进行操作的规则列表就好了。
> 
> 目前已经可以在[开发者设置](https://immersive-translate.owenyoung.com/options/#developer) 编辑 (Edit User Rules) 自己适配特定的网站，详细的文档可以看这里：[高级自定义选项](https://immersive-translate.owenyoung.com/advanced#%E9%AB%98%E7%BA%A7%E8%87%AA%E5%AE%9A%E4%B9%89%E9%80%89%E9%A1%B9)
> 
> 例如：
> 
> ```json
> [
>   {
>     "matches": "outlook.live.com",
>     "selectors": [
>         ".aVla3"
>     ],
>     "excludeSelectors": [
>         ".XG5Jd.y1E5h.zItCb"
>     ]
>   }
> ]
> ```

不过我又想了下，是否可以有个一个模式，提供的不是完整网页全部翻译的功能，也不是部分文本划词翻译，而是hover后提供一个按钮，可以对选择区域的部分进行预处理后翻译，像元素选择器一样的交互，毕竟有时候网页上有些文本没必要去翻译，尤其是广告比较多的站点。

**Comment by theowenyoung** [comment]
已支持鼠标悬停翻译。
