### ISSUE TITLE
subtitle support rtl

### ISSUE THREAD

**Issue by keyboard3** [immersive-translate/immersive-translate#1520]
### 您希望的更新和改进是什么 | Update or Improve

First of all, I already have a subscription.
Regarding family and friends: I suggested it to them, but they said it's impossible to watch a movie when the subtitle direction is LTR, the sentences get mixed up and it's unbearable.
It's very simple to fix this
All in all, you need to add one line of code in your source code
"(The subtitle element) { direction: rtl; text-align: start; }"
For example in IQIYI this is the source code:
 "excludeSelectors.add": [
        ".iqp-subtitle"
      ],
      "id": "[http://iq.com](https://t.co/3nxX1oNsK9)",
      "matches": "[http://iq.com](https://t.co/3nxX1oNsK9)",
      "mutationExcludeSelectors.add": [
        ".iqp-subtitle *"
      ],
      "subtitleRule.add": {
        "injectedCss": [
          "[#immersive](https://twitter.com/hashtag/immersive?src=hashtag_click)-translate-quick-button-container {float: right; height: 100%;}"
        ],
        "loadingContainerSelector": ".intl-video-area",
        "loadingStyle": "bottom: 10%;",
        "quickButtonRule": {
          "appendSelector": ".iqp-contrls-right"
        },
        "subtitleUrlRegExp": "\\.xml\\?",
        "type": "xml",
        "xmlTextSelector": "sub"

You need to add one line, like this:

 "excludeSelectors.add": [
        ".iqp-subtitle"
      ],
      "id": "[http://iq.com](https://t.co/3nxX1oNsK9)",
      "matches": "[http://iq.com](https://t.co/3nxX1oNsK9)",
      "mutationExcludeSelectors.add": [
        ".iqp-subtitle *"
      ],
      "subtitleRule.add": {
        "injectedCss": [
          "[#immersive](https://twitter.com/hashtag/immersive?src=hashtag_click)-translate-quick-button-container {float: right; height: 100%;}",
          ".iqp-subtitle {direction: rtl;}"
        ],
        "loadingContainerSelector": ".intl-video-area",
        "loadingStyle": "bottom: 10%;",
        "quickButtonRule": {
          "appendSelector": ".iqp-contrls-right"
        },
        "subtitleUrlRegExp": "\\.xml\\?",
        "type": "xml",
        "xmlTextSelector": "sub"

When to the selector:

 "injectedCss": [
          "[#immersive](https://twitter.com/hashtag/immersive?src=hashtag_click)-translate-quick-button-container {float: right; height: 100%;}"
        ],

We will add the instruction for changing the text direction like this:

"injectedCss": [
    "[#immersive](https://twitter.com/hashtag/immersive?src=hashtag_click)-translate-quick-button-container {float: right; height: 100%;}",
    ".iqp-subtitle {direction: rtl;}"
]

And that's all.
Every site has its own subtitle element, but you know them all, it appears in the documentation on every site under the line
"excludeSelectors.add": [

Handle it once and you will allow speakers of 7 more languages to enjoy properly translated subtitles

**Comment by keyboard3** [comment]
If I set it this way, it may result in right alignment for versions in languages not supporting RTL (right-to-left). Therefore, it might be best to apply this setting specifically for languages that support RTL.

**Comment by SHAY5555-gif** [comment]
Certainly, here is the code that needs to be added:
.player-timedtext-text-container[lang="he"],
.player-timedtext-text-container[lang="ar"],
.player-timedtext-text-container[lang="fa"],
.player-timedtext-text-container[lang="ur"],
.player-timedtext-text-container[lang="ps"],
.player-timedtext-text-container[lang="da"],
.player-timedtext-text-container[lang="sd"] {
  direction: rtl;
  text-align: right;
}

I didn't mention this, their developers know it very well, and if I write that 8 lines of code need to be added it sounds more complicated than just one line, but I haven't forgotten about it for a moment.

**Comment by keyboard3** [comment]
> Certainly, here is the code that needs to be added: .player-timedtext-text-container[lang="he"], .player-timedtext-text-container[lang="ar"], .player-timedtext-text-container[lang="fa"], .player-timedtext-text-container[lang="ur"], .player-timedtext-text-container[lang="ps"], .player-timedtext-text-container[lang="da"], .player-timedtext-text-container[lang="sd"] { direction: rtl; text-align: right; }
> 
> I didn't mention this, their developers know it very well, and if I write that 8 lines of code need to be added it sounds more complicated than just one line, but I haven't forgotten about it for a moment.

The prerequisite for this is that the translation plug-in needs to set the translated lang to the attribute of the subtitle dom node. However, in fact, the workload is not small

**Comment by SHAY5555-gif** [comment]
If it's so complicated, you can add an option that allows the text direction to be set as RTL in the settings. Speakers of the 7 languages written from right to left will activate this option, and everyone else will not touch it

**Comment by keyboard3** [comment]
> If it's so complicated, you can add an option that allows the text direction to be set as RTL in the settings. Speakers of the 7 languages written from right to left will activate this option, and everyone else will not touch it

Although the implementation is complicated, it may still be necessary to do this, otherwise it will increase the mental complexity of the user.
