### ISSUE TITLE
增加一个选项，不翻译“网页标题 ”

### ISSUE THREAD

**Issue by Geo123abc** [immersive-translate/immersive-translate#1523]
### 您希望的更新和改进是什么 | Update or Improve

在网页上看一些文献的时候，如果开启页面翻译（“总是翻译该网站”），那么这个页面的Tab标题也会被翻译（比如此时使用Ctrl+S保存当前网页为离线文件，保存的文件名是中英混合的），此时如果使用zotero之类的软件抓取、保存页面时，标题会掺杂原文和翻译之后的内容，会给后期引用这个条目带来一些不便。

希望浏览器的Tab标题保持原文内容，不进行翻译。

**Comment by theowenyoung** [comment]
高级设置里已经有该选项。

**Comment by Geo123abc** [comment]
> 高级设置里已经有该选项。

谢谢恢复，找到了，之前没注意到
