### ISSUE TITLE
[Bug]: 谷歌翻译报错 翻译服务或网络似乎出了点问题... Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by ManutdGTA** [immersive-translate/immersive-translate#1524]
### 插件版本号 | Version

1.2.4

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

翻译服务或网络似乎出了点问题...
Cannot read properties of undefined (reading 'split')

### 出现问题的网址 | URL

any website

### 重现步骤 | To Reproduce

右键
翻译网页

**Comment by keyboard3** [comment]
没能复现，卸载重装试下

**Comment by keyboard3** [comment]
暂无反馈 关闭此issue
