### ISSUE TITLE
[Bug]: 快捷键无效：立即翻译到页面底部/显示原文

### ISSUE THREAD

**Issue by julee** [immersive-translate/immersive-translate#1525]
### 插件版本号 | Version

1.2.4

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/1493342/6b71e468-ee20-444d-aab6-bc63931e5e25)

如图，配置了 “立即翻译到页面底部/显示原文” 的快捷键，重新打开网页，然后按这个快捷键，没有任何反应。

以为和其它快捷键冲突了，配置其它按键还是不行。 然后尝试把这个快捷键 (alt+shift+f) 配置到 "翻译页面全部区域/显示原文" ，在打开网页上按快捷键alt+shift+f，  "翻译页面全部区域/显示原文" 功能被正常触发。

所以猜测是 bug。

### 重现步骤 | To Reproduce

任意英文网页。

**Comment by flamintune** [comment]
1.3.2版本已修复
