### ISSUE TITLE
悬浮球底下的可点击区域无法点击

### ISSUE THREAD

**Issue by takeeasyman** [immersive-translate/immersive-translate#1526]
### 您希望的更新和改进是什么 | Update or Improve

<img width="215" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/3069003/c5c90848-9904-4075-831b-b7930eeac11c">

悬浮球上的`分享`和`设置`按钮收起来隐藏之后，它底下的可点击区域依然无法点击。

**Comment by flamintune** [comment]
下个版本修复

**Comment by flamintune** [comment]
最新版本v1.3.1已修复
