### ISSUE TITLE
希望能实现调整各种列表匹配顺序的功能

### ISSUE THREAD

**Issue by king0billy** [immersive-translate/immersive-translate#1527]
### 您希望的更新和改进是什么 | Update or Improve

多个译文显示样式的URL匹配规则是怎样的？ 有类似路由表的按顺序匹配效果吗

比如我希望https://app.immersivetranslate.com/html/*  下的译文样式为 【无】
希望其他https://   网站的译文样式都为 【模糊效果】该如何实现？

### 补充说明 | Additional context

在Edit Full User Config里面修改了样式的先后顺序，无法实现上述效果。sync storage object里面的先后顺序和修改前一样没变化

似乎保存后会自动按照首字母顺序排序，有什么办法可以改变吗
```
"mask": {
      "matches": [
        "http://*",
        "https://*",
        "sfasasklfa"
      ]
    },
    "none": {
      "matches": [
        "https://app.immersivetranslate.com/*"
      ],
      "zoom": "75"
    },
    "opacity": {
      "matches": [
        "C:/"
      ]
    }
  },
```

**Comment by flamintune** [comment]
参考指南https://immersivetranslate.com/docs/advanced/#user-config，打开 Edit Full User Config 中设置，下面提供一个参考示例
```json
"translationTheme":"mask"
"translationThemePatterns": {
    "none": {
      "matches": [
        "https://app.immersivetranslate.com/*"
      ]
    }
  },
```

**Comment by king0billy** [comment]
> 参考指南 https://immersivetranslate.com/docs/advanced/#user-config ，打开 Edit Full User Config 中设置，下面提供一个参考示例
> 
> ```json
> "translationTheme":"mask"
> "translationThemePatterns": {
>     "none": {
>       "matches": [
>         "https://app.immersivetranslate.com/*"
>       ]
>     }
>   },
> ```

看过了，我想实现的这样的顺序实现不了
   ```
 "none": {
      "matches": [
        "https://app.immersivetranslate.com/*"
      ],
      "zoom": "75"
    },
    "opacity": {
      "matches": [
        "C:/"
      ]
    },
   "mask": {
      "matches": [
        "http://*",
        "https://*",
        "sfasasklfa"
      ]
    }
  },
```

**Comment by king0billy** [comment]
发现一个折中的解决办法，下拉框 选 译文显示样式 为模糊（学习模式）然后只设置例外的theme，例外的theme里的清单会优先按照首字母顺序匹配，没在例外匹配的默认按照下拉框选择的样式展示。
```
 "translationStartMode": "dynamic",
  "translationTheme": "mask",
  "translationThemePatterns": {
    "none": {
      "matches": [
        "https://app.immersivetranslate.com/*"
      ],
      "zoom": "75"
    },
    "opacity": {
      "matches": [
        "C:/"
      ]
    }
  },
```

**Comment by keyboard3** [comment]
因为json结构在Js序列化成对象无法保证枚举顺序，要想实现这个需求，得新增个新增字段来支撑这个需求。
