### ISSUE TITLE
视频字幕的样式可以自定义

### ISSUE THREAD

**Issue by zealousfool** [immersive-translate/immersive-translate#1528]
### 您希望的更新和改进是什么 | Update or Improve

视频字幕的样式可以自定义就好了，youtube自带的字幕样式字体太大，打开看视频有时候太影响观感了

**Comment by keyboard3** [comment]
youtube 自己可以自定义样式呀

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/ab595086-60b3-472f-92b5-6eb0893fd6bd)
