### ISSUE TITLE
[Bug]: 悬浮窗收起时，下方部分区域无法点击，除非上移悬浮窗

### ISSUE THREAD

**Issue by foresee-io** [immersive-translate/immersive-translate#1529]
### 插件版本号 | Version

1.2.4

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

悬浮窗收起时，下方部分区域无法点击，除非上移悬浮窗。

例如，下图框住的区域点不动，但更下方的网页按钮可交互。缓解措施：将悬浮窗往上拖一些，或者关掉悬浮窗。

![flame2024-03-13_21-01](https://github.com/immersive-translate/immersive-translate/assets/32860378/bfeacea6-7543-4a43-b4b6-cd9f194656bc)

**Comment by flamintune** [comment]
最新版本v1.3.1已修复

**Comment by foresee-io** [comment]
已收到版本 1.3.1 推送，bug已解决。
