### ISSUE TITLE
[Bug]:大海浏览器, 安卓手机,  1.3.1的油猴脚本,在yandex.com的搜索结果页面不显示粉红小图标,不能翻译;

### ISSUE THREAD

**Issue by boomer001** [immersive-translate/immersive-translate#1530]
### 插件版本号 | Version

1.3.1

### 平台 | Platform

Android

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

这是报错日志

 url:https://yandex.com/search/touch/?text=gif&lr=10590&redircnt=1710387169.1 , consoleMsg:Level:ERROR, message:Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src self unsafe-inline unsafe-eval yandex.com *.yandex.com yandex.ru *.yandex.ru yastat.net yastatic.net *.yastatic.net yandex.net *.yandex.net ya.ru *.ya.ru nonce-8465 yandex-images.clstorage.net mc.yandex.com". Note that unsafe-inline is ignored if either a hash or nonce value is present in the source list.

说是违反了Content Security Policy指令
似乎解决办法在这里:
https://blog.csdn.net/qq_43429963/article/details/122495389

### 出现问题的网址 | URL

https://yandex.com/search/touch/?text=gif

### 重现步骤 | To Reproduce

应用宝/小米应用市场, 下载安装 大海浏览器, 屏幕左边上划,进入网页界面, 
右下角三横菜单->油猴->开启油猴, 开启沉浸式翻译
回到搜索框,
输入 https://yandex.com/search/touch/?text=gif , 搜索就打开网页; ,

### 补充说明 | Additional context

x浏览器, 安装沉浸式翻译的油猴脚本1.3.1版, yandex.com也没有粉红图标, 不能 翻译;

**Comment by theowenyoung** [comment]
这是油猴脚本权限的限制，无法从脚本这一侧解决，建议使用 Firefox 浏览器直接安装插件，或者直接使用沉浸式翻译浏览器：

https://immersivetranslate.com/

**Comment by boomer001** [comment]
明白了, 谢谢, 小海浏览器对yandex,google做了兼容, 移除其cps; 沉浸式翻译油猴脚本可以正常运行
