### ISSUE TITLE
[Bug]: 使用 Relingo 划词注解单词后，翻译会进行，但无法显示

### ISSUE THREAD

**Issue by qixing-jk** [immersive-translate/immersive-translate#1532]
### 插件版本号 | Version

1.2.4

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在**开启自动翻译时，且翻译响应速度较快时**才会出现（即要在 relingo 更改前进行翻译）：
**出现的问题**
该段落的翻译会消失，需要重新翻译一次
- 直接就进行翻译的网页：偶发性出现
- 后方等待滚动到区域再翻译的网页：必定出现
**控制台信息**
![Clip_20240314_132536](https://github.com/immersive-translate/immersive-translate/assets/125447674/d18e97a5-50e9-4019-aa2f-d22c3d8d4afe)

**类似的问题**
https://github.com/immersive-translate/immersive-translate/issues/1069

### 出现问题的网址 | URL

绝大部分网站，特别是长网页

### 重现步骤 | To Reproduce

1. 网站自动沉浸式翻译
2. 网站自动 Relingo 标注生词

**Comment by keyboard3** [comment]
未能复现该问题，录个屏看下

**Comment by keyboard3** [comment]
感觉你这个视频中的沉浸式翻译状态不对，翻译后悬浮球应该长这样
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/1b0d41f4-ecd0-49f1-9f18-1ec555863c02)
我这边是这样的效果
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/a7f7d212-24fa-4436-9673-dafe93839cc0)

**Comment by qixing-jk** [comment]
> 你试着重置设置，或者卸载重装？

![image](https://github.com/immersive-translate/immersive-translate/assets/125447674/ef6c90d1-6cb9-4bf0-995f-1e602a4fa4b1)
![Clip_20240314_213800](https://github.com/immersive-translate/immersive-translate/assets/125447674/d76ea1d4-c9fd-45a6-8fd0-545f193fb5dd)
重装后，依旧存在类似现象，翻译球状态是对的啊，显示✅了（我只是因为他会阻挡下方点击区域，所以放到了左边）

**Comment by keyboard3** [comment]
> > 你试着重置设置，或者卸载重装？
> 
> ![image](https://private-user-images.githubusercontent.com/125447674/312858589-ef6c90d1-6cb9-4bf0-995f-1e602a4fa4b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MzQyODYsIm5iZiI6MTcxMDczMzk4NiwicGF0aCI6Ii8xMjU0NDc2NzQvMzEyODU4NTg5LWVmNmM5MGQxLTZjYjktNGJmMC05OTVmLTFlNjAyYTRmYTRiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQwMzUzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDY5NTlmZWRkMTk3M2U0NDQwNzk1MjAzODQwMjAxOWI2OTMwMmUxOWEwNzM0Y2ZmNWUyOWRlZGNlOWQ0Y2Q3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.d0024yci5eWLs9IKNs8ClCcDarknFSSPvhbJoGKsBck) ![Clip_20240314_213800](https://private-user-images.githubusercontent.com/125447674/312858937-d76ea1d4-c9fd-45a6-8fd0-545f193fb5dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MzQyODYsIm5iZiI6MTcxMDczMzk4NiwicGF0aCI6Ii8xMjU0NDc2NzQvMzEyODU4OTM3LWQ3NmVhMWQ0LWM5ZmQtNDVhNi04ZmQwLTU0NWYxOTNmYjVkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQwMzUzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTdmZTI5MWMzMWE1ZjA1MmMyYjkxYmYwMzkxYTVmYjA0OTIxMmEyOTU0NGNjOWUxMTE3OTVjYTI3MjE4ZDJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aB1zZh77yMkjIlHhCYbny41P78n7r7cHabJhoKBbRgU) 重装后，依旧存在类似现象，翻译球状态是对的啊，显示✅了（我只是因为他会阻挡下方点击区域，所以放到了左边） 我想滚慢一些（你测试应该也要滚快一些和翻译速度快些，保证加载速度）或者添加一定延迟也是能避免这个问题的

你不用自动翻译，用手动翻译看看

**Comment by qixing-jk** [comment]
> > > 你试着重置设置，或者卸载重装？
> > 
> > 
> > <img alt="image" width="54.150001525878906" height="21" src="https://private-user-images.githubusercontent.com/125447674/312858589-ef6c90d1-6cb9-4bf0-995f-1e602a4fa4b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MzQyODYsIm5iZiI6MTcxMDczMzk4NiwicGF0aCI6Ii8xMjU0NDc2NzQvMzEyODU4NTg5LWVmNmM5MGQxLTZjYjktNGJmMC05OTVmLTFlNjAyYTRmYTRiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQwMzUzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDY5NTlmZWRkMTk3M2U0NDQwNzk1MjAzODQwMjAxOWI2OTMwMmUxOWEwNzM0Y2ZmNWUyOWRlZGNlOWQ0Y2Q3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.d0024yci5eWLs9IKNs8ClCcDarknFSSPvhbJoGKsBck"> <img alt="Clip_20240314_213800" width="156.96250915527344" height="21" src="https://private-user-images.githubusercontent.com/125447674/312858937-d76ea1d4-c9fd-45a6-8fd0-545f193fb5dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MzQyODYsIm5iZiI6MTcxMDczMzk4NiwicGF0aCI6Ii8xMjU0NDc2NzQvMzEyODU4OTM3LWQ3NmVhMWQ0LWM5ZmQtNDVhNi04ZmQwLTU0NWYxOTNmYjVkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQwMzUzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTdmZTI5MWMzMWE1ZjA1MmMyYjkxYmYwMzkxYTVmYjA0OTIxMmEyOTU0NGNjOWUxMTE3OTVjYTI3MjE4ZDJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aB1zZh77yMkjIlHhCYbny41P78n7r7cHabJhoKBbRgU"> 重装后，依旧存在类似现象，翻译球状态是对的啊，显示✅了（我只是因为他会阻挡下方点击区域，所以放到了左边） 我想滚慢一些（你测试应该也要滚快一些和翻译速度快些，保证加载速度）或者添加一定延迟也是能避免这个问题的
> 
> 你不用自动翻译，用手动翻译看看

手动翻译确实没有问题的，出现前面所述的问题时，手动取消翻译再次翻译，翻译状态正常
