### ISSUE TITLE
[Bug]:  1.2.4更新到1.3.1之后配置数据全丢失

### ISSUE THREAD

**Issue by king0billy** [immersive-translate/immersive-translate#1533]
### 插件版本号 | Version

1.3.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

[Bug]:  拓展1.2.4更新到1.3.1之后配置数据全丢失. 完全回到了出厂状态。有两个月没有手动备份数据了，找到不到自动备份的数据

**Comment by keyboard3** [comment]
配置数据是存在浏览器存储，除非手动重置或者卸载重装插件，应用商店自动更新插件是不会丢数据的

**Comment by king0billy** [comment]
我也没手动重置或者卸载重装插件呀。。一夜之间就没了。而且配置没有自动定期备份功能，配置丢了就没了

**Comment by keyboard3** [comment]
这个建议自己手动去[关于页面](https://dash.immersivetranslate.com/#import_export)定期同步
