### ISSUE TITLE
油管中英文字幕需要都翻译完才显示

### ISSUE THREAD

**Issue by SongXiaoMao** [immersive-translate/immersive-translate#1537]
### 您希望的更新和改进是什么 | Update or Improve

使用VLLM跑本地模型用One-API接入后发现两个问题，看油管英文直播的视频，基本都是说几句能翻译一句，以此类推。还有就是看短视频的时候显示的还好，几十分的视频要后台都翻译完毕才会显示双语字幕，希望可以改成翻译几句后就开始显示，这样不耽误后台继续翻译，也不耽误网页显示，谢谢。

**Comment by keyboard3** [comment]
部分平台我们已支持自托管的方式，可以做到长视频按播放进度实时翻译。正在逐渐覆盖目前支持的大部分平台

**Comment by keyboard3** [comment]
1.4.2 YouTube已支持实时播放翻译
