### ISSUE TITLE
[Bug]: 微软翻译偶尔会失败

### ISSUE THREAD

**Issue by TianyuanZhu-data** [immersive-translate/immersive-translate#1538]
### 插件版本号 | Version

V1.3.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

微软翻译偶尔会失败，查看clash连接显示googletranslate，然后在设置里切换成其他翻译再切换成微软翻译，就恢复了

### 出现问题的网址 | URL

微软翻译翻译直接失败

### 重现步骤 | To Reproduce

偶尔出现

**Comment by keyboard3** [comment]
指定的微软翻译不会访问谷歌的，实际使用中我们也没发现这个问题。你再观察观察？

**Comment by LaBiXiaoChen** [comment]
建议使用腾讯交互翻译，在没有梯子或国内环境中更稳定。

**Comment by TianyuanZhu-data** [comment]
> 指定的微软翻译不会访问谷歌的，实际使用中我们也没发现这个问题。你再观察观察？

是否由于我设置整个微软服务分流到美国节点，而单独给微软翻译的域名分流到香港节点

**Comment by TianyuanZhu-data** [comment]
> 指定的微软翻译不会访问谷歌的，实际使用中我们也没发现这个问题。你再观察观察？

是可能由于我设置整个微软服务分流到美国节点，而单独给微软翻译的域名分流到与微软服务不同（香港/直连）节点
还是微软翻译本身的不稳定性，偶尔翻译失败

**Comment by keyboard3** [comment]
> > 指定的微软翻译不会访问谷歌的，实际使用中我们也没发现这个问题。你再观察观察？
> 
> 是可能由于我设置整个微软服务分流到美国节点，而单独给微软翻译的域名分流到与微软服务不同（香港/直连）节点 还是微软翻译本身的不稳定性，偶尔翻译失败

那跟沉浸式插件自身没关系了，关闭这个issue了

**Comment by TianyuanZhu-data** [comment]
> > > 指定的微软翻译不会访问谷歌的，实际使用中我们也没发现这个问题。你再观察观察？
> > 
> > 
> > 是可能由于我设置整个微软服务分流到美国节点，而单独给微软翻译的域名分流到与微软服务不同（香港/直连）节点 还是微软翻译本身的不稳定性，偶尔翻译失败
> 
> 那跟沉浸式插件自身没关系了，关闭这个issue了

好的，辛苦了
