### ISSUE TITLE
[Bug]:突然翻译不了了，所有的英文网站

### ISSUE THREAD

**Issue by TT-LIKEY** [immersive-translate/immersive-translate#1539]
### 插件版本号 | Version

1.3.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![屏幕截图 2024-03-15 215418](https://github.com/immersive-translate/immersive-translate/assets/163548869/43f15f90-9049-488f-a295-23bd40ccf926)
今天下午用的时候还好好的（我一般使用鼠标悬停+shift去翻译英文的段落），突然用着用着就不行了，怎么按也没反应，去查看了设置，重新换了快捷键也不行，把扩展删了重下也不行，到底是什么问题，折腾半天了，救救孩子吧

### 出现问题的网址 | URL

所有英文网站，包括但不限于 https://www.sciencedirect.com/science/article/pii/S0079642524000458

**Comment by keyboard3** [comment]
录个屏吧，图上啥也看不出来。 去设置页 https://dash.immersivetranslate.com/ 重置下设置看看

**Comment by TT-LIKEY** [comment]
设置过了，没有用

录屏也就是我鼠标悬停上，点设置的快捷键shift,没有任何反应，翻译不了

**Comment by keyboard3** [comment]
> 设置过了，没有用
> 
> 录屏也就是我鼠标悬停上，点设置的快捷键shift,没有任何反应，翻译不了

我这边鼠标悬浮正常，这个应该就是你本地快捷键冲突之类的问题，那几个快捷键切换着试
