### ISSUE TITLE
翻译在线 pdf 无效果

### ISSUE THREAD

**Issue by tobemaster56** [immersive-translate/immersive-translate#154]
在线 pdf 地址：https://www.rfc-editor.org/rfc/pdfrfc/rfc7946.txt.pdf

操作复现：https://lusun.com/v/RMcnnVnxBMO

浏览器： Arc
Mac，
插件版本
<img width="424" alt="image" src="https://user-images.githubusercontent.com/8998761/220539965-e1ce6777-884e-48a7-9544-dccacae1fff0.png">

**Comment by theowenyoung** [comment]
感谢反馈，确认是Bug，应该是0.62版本引入的简体转繁体带来的bug.

**Comment by theowenyoung** [comment]
发了 0.2.66 版本，这个问题ok了·

**Comment by tobemaster56** [comment]
试了一下，0.2.66 版本，确认已修复，速度给力，👍🏻
