### ISSUE TITLE
开发者能将应用程序同步到 iCloud 或其他云存储吗？

### ISSUE THREAD

**Issue by LaBiXiaoChen** [immersive-translate/immersive-translate#1540]
### 您希望的更新和改进是什么 | Update or Improve

我使用Apple生态，觉得将**设置配置到iCloud中非常方便**，希望开发者能考虑我的建议。

或者是否可以**考虑为不使用Apple的用户开放其他云存储选择**。

非常感谢！

**Comment by theowenyoung** [comment]
iOS 中可以打开这个页面： https://dash.immersivetranslate.com/ 使用谷歌 drive 同步设置。

**Comment by LaBiXiaoChen** [comment]
> iOS 中可以打开这个页面： https://dash.immersivetranslate.com/ 使用谷歌 drive 同步设置。

推荐给女性朋友时，她们也觉得好用，但因不懂梯子等技术，在使用云同步功能时遇到困难，且保存的配置文件不重视导致丢失，影响了使用体验。

**Comment by theowenyoung** [comment]
（好吧... 还有个方案就是 Pro 会员自动全平台云同步..

**Comment by LaBiXiaoChen** [comment]
好的，我之前没有注意到这个功能，我会通知她们的，非常感谢。
