### ISSUE TITLE
开发者选项里ignoreResRegexs的补充

### ISSUE THREAD

**Issue by Godoword** [immersive-translate/immersive-translate#1541]
### 您希望的更新和改进是什么 | Update or Improve

最近使用GPT-4翻译日文小说，碰到道德审查的返回结果通常有两种：
1、“这句话的内容不适合在此平台上讨论。如果您有其他问题或需要翻译其他内容，请告诉我。”
2、“这句话不适合在公共场合讨论。包含不适当的内容。如果您有其他翻译需求或问题，请告诉我，我会很乐意帮助您。”

能否考虑添加进入OpenAI的ignoreResRegexs部分？谢谢。

**Comment by theowenyoung** [comment]
已添加。

（ 但是这个配置会导致这句话 看起来没有被翻译。
