### ISSUE TITLE
OpenAI 服務的自定義模型功能改進建議

### ISSUE THREAD

**Issue by omegaduncan** [immersive-translate/immersive-translate#1542]
### 您希望的更新和改进是什么 | Update or Improve

比如我目前主要使用的模型是 `GPT-4-0125-preview`，當我臨時需要切換自定義模型來比對 AI 譯文時，我會切換到 `groq-mixtral-8x7b-32768`。比較完成後，我會取消勾選自定義模型選項，使其切回 `GPT-4-0125-preview`。
但下次再開啟自定義模型時，發現模型仍然是 `GPT-4-0125-preview`，而不是 `groq-mixtral-8x7b-32768`。
我希望系統能夠記憶單個或多組自定義模型，在使用前先手動添加到模型清單中，到時候直接用滑鼠選擇即可，不需要再重新輸入一次。謝謝。

**Comment by keyboard3** [comment]
1.5.1 已支持 自定义模型列表
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/005c01a3-09e0-4d7b-94e1-be84051f14ac)
