### ISSUE TITLE
任何网页无法翻译

### ISSUE THREAD

**Issue by jvan500** [immersive-translate/immersive-translate#1545]
### 插件版本号 | Version

1.3.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome, Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

从昨天开始，任何网页都无法翻译，感觉插件不工作了，在我的Win电脑和Mac电脑上都无法翻译。

**Comment by theowenyoung** [comment]
卸载重装，或者重新换一个翻译服务试试呢？

**Comment by keyboard3** [comment]
检查下翻译面板的目标语言，是不是设置成了英文

**Comment by marcusbai** [comment]
我是这个网站没反应，不知道是什么原因。
https://silverbullet.md/

**Comment by keyboard3** [comment]
> 我是这个网站没反应，不知道是什么原因。 https://silverbullet.md/

这个网站不让任何翻译引擎翻译，你可以试试微信截图翻译

**Comment by keyboard3** [comment]
暂无反馈 关闭此issue

**Comment by ningjiaen123** [comment]
同样的问题
