### ISSUE TITLE
希望更新claude模型

### ISSUE THREAD

**Issue by HadXu** [immersive-translate/immersive-translate#1546]
### 您希望的更新和改进是什么 | Update or Improve

希望更新claude模型

**Comment by Ricco-L** [comment]
claude3的翻译体验比GPT4更好，希望能够得到更新和改进。

**Comment by jdassd** [comment]
claude3的翻译体验比GPT4更好，希望能够得到更新和改进。

**Comment by keyboard3** [comment]
下一版支持

**Comment by ictsmc** [comment]
目前市面上的转发平台大多数为了避免各个模型不同的接口方式，将所有ai模型的请求都转成 OpenAI 格式的,目前更新的claude3是官方请求模式.能否优化一下自定义接口支持  OpenAI 格式的请求模式 .这样兼容市面上所有请求模式
