### ISSUE TITLE
[Bug]: 无法翻译在线txt

### ISSUE THREAD

**Issue by tlxxzj** [immersive-translate/immersive-translate#1547]
### 插件版本号 | Version

1.3.2

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

打开一个在线的txt文档，点击**翻译**，页面无任何变化。

### 出现问题的网址 | URL

https://pdos.csail.mit.edu/6.824/papers/linearizability-faq.txt

### 重现步骤 | To Reproduce

1. 打开网页：https://pdos.csail.mit.edu/6.824/papers/linearizability-faq.txt
2. 点击翻译
3. 页面无任何变化

**Comment by keyboard3** [comment]
打开面板更新下规则，然后重试下

**Comment by tlxxzj** [comment]
> 打开面板更新下规则，然后重试下

可以了，感谢！
