### ISSUE TITLE
提供设置temperature的方式，以支持调用智谱 glm 系列模型

### ISSUE THREAD

**Issue by suling-fun** [immersive-translate/immersive-translate#1548]
### 您希望的更新和改进是什么 | Update or Improve

由于智谱 glm 系列模型目前不支持 temperature = 0，因此当前沉浸式翻译无法正常调用

![image](https://github.com/immersive-translate/immersive-translate/assets/53048810/09f28dc0-3095-4741-a185-76be3431ec4b)

**Comment by theowenyoung** [comment]
1.3.3 版本（已提交商店审核）将会支持在开发者设置里设置温度：

![CleanShot 2024-03-21 at 22 58 37@2x](https://github.com/immersive-translate/immersive-translate/assets/62473795/61a0f206-bbf5-4e06-ae58-90b3dbef8f59)


```
{
  "translationServices": {
    "openai": {
      "temperature": 0.1
    }
  }
}
```

**Comment by suling-fun** [comment]
十分感谢🙏
已经给我公司同事大力推荐
