### ISSUE TITLE
{建议}阿里云的机器翻译接口

### ISSUE THREAD

**Issue by jinwendaiya** [immersive-translate/immersive-translate#155]
建议加上阿里云的机器翻译接口，个人认为准确率非常之高

**Comment by theowenyoung** [comment]
这个网站说即将下线： https://www.alifanyi.com/ 这个指的不是API接口的下线吧？

**Comment by jinwendaiya** [comment]
![image](https://user-images.githubusercontent.com/30795466/220554911-d4d6de04-6efd-44c2-bc87-ba931611476d.png)
是这个
>

**Comment by dugulingping** [comment]
建议跟进

**Comment by yaorenyi** [comment]
阿里云翻译通用版的调用地址：http://mt.cn-hangzhou.aliyuncs.com/api/translate/web/genera

**Comment by Anivie** [comment]
> https://translate.alibaba.com

目前仍然正常工作，且每个月一百万字免费额度，对普通用户来说也是绰绰有余了，我在文档中搜索'ali'和'阿里'都没有相关结果，请问作者是否在考虑添加阿里翻译api？

**Comment by keyboard3** [comment]
0.8.5 已支持阿里云翻译
