### ISSUE TITLE
视频和网页的双语显示独立设置

### ISSUE THREAD

**Issue by nobodysclown** [immersive-translate/immersive-translate#1551]
### 您希望的更新和改进是什么 | Update or Improve

现在网页翻译与视频翻译的 ”仅显示译文“ 和 “双语翻译” 设置是统一的，对于网页来说，仅显示译文的显示效果是更好的(类似chrome)自带的效果，不会引起排版的错乱。而对于油管视频来说，显示双语翻译是更好的，因为可能会有很多翻译上的错误，需要对比原文。希望网页和视频可以单独设置双语。

**Comment by FattySpring** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/25144301/1b95c52c-7d03-4856-9746-294236b534bf)
1.3.4 已支持
