### ISSUE TITLE
输入框增强能否增加其他快捷键

### ISSUE THREAD

**Issue by HongJunShan** [immersive-translate/immersive-translate#1553]
### 您希望的更新和改进是什么 | Update or Improve

您好，现在输入框默认是空格，但是正常输入无需转换时时经常误触，其他触发字符我是搜狗输入法(、、)不知道为什么无法生效，能否增加其他快捷键 比如连续三次Ctrl等？

**Comment by theowenyoung** [comment]
目前提供配置的快捷键都不行是吗？

![CleanShot 2024-03-20 at 02 01 36@2x](https://github.com/immersive-translate/immersive-translate/assets/62473795/61133b92-f445-4be6-ba7b-5589b1025baf)

**Comment by HongJunShan** [comment]
是的，我目前是win+搜狗输入法，不知道是不是我的原因中文状态下好几个都是有时候没反应，个人觉得Ctrl在左下角敲击着更方便，如果单Ctrl有冲突或许可以Ctrl+空格？

**Comment by theowenyoung** [comment]
可以在快捷键设置里单独设置一个快捷键：

![CleanShot 2024-03-20 at 21 34 57@2x](https://github.com/immersive-translate/immersive-translate/assets/62473795/38ce6c52-621a-4a97-bbde-ad05258f282f)
