### ISSUE TITLE
[Bug]: 翻譯後網頁出錯。

### ISSUE THREAD

**Issue by curtiswu33** [immersive-translate/immersive-translate#1555]
### 插件版本号 | Version

1.3.2

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

翻譯後網頁出錯，附上影片。

https://github.com/immersive-translate/immersive-translate/assets/134845275/c44f070f-4d23-4995-96da-a3a63fab31d1

### 出现问题的网址 | URL

https://nomadgoods.com

**Comment by keyboard3** [comment]
这个网站只能采用双语翻译，因为它的技术实现，在检测到自己的dom被移除修改之后就会触发重新渲染
