### ISSUE TITLE
Ollama 模型翻译字幕希望保留中英文之间的空格

### ISSUE THREAD

**Issue by Copy2Translator** [immersive-translate/immersive-translate#1556]
插件版本号 | Version
1.3.2

平台 | Platform
Windows

浏览器 | Browsers
Firefox

插件类型 | Extension Type
浏览器插件 | Browser Extension

Ollama 模型翻译字幕时中英文之间没有空格，DeepLX 翻译结果在中英文之间有空格，希望保留翻译后的中英文之间的空格。

![微信图片_20240320174756](https://github.com/immersive-translate/immersive-translate/assets/75414580/343de48c-b8e4-4c7f-90f9-d78efb88447a)
![Snipaste_2024-03-20_17-48-37](https://github.com/immersive-translate/immersive-translate/assets/75414580/b8a1c016-2b92-467d-8fd6-7b73aef00f31)
![Snipaste_2024-03-20_17-48-54](https://github.com/immersive-translate/immersive-translate/assets/75414580/ca46250b-55e0-44c1-b371-ae1e987e0225)

**Comment by theowenyoung** [comment]
应该可以～ 加一个 future label

**Comment by cssmagic** [comment]
@Copy2Translator 
可以先尝试自己在系统提示词里加要求。我是这么做的 :wink:

**Comment by keyboard3** [comment]
1.3.4 已支持
