### ISSUE TITLE
支持自定义全局自动翻译延迟，避免插件或其他原因导致网站样式变动导致的问题

### ISSUE THREAD

**Issue by qixing-jk** [immersive-translate/immersive-translate#1557]
### 您希望的更新和改进是什么 | Update or Improve

支持自定义全局自动翻译延迟，避免插件或其他原因网站样式变动导致的问题
这种方式实现起来也很简单，也能一定程度上缓解问题

### 补充说明 | Additional context

相关原因
https://github.com/immersive-translate/immersive-translate/issues/1532 ：虽然不知道问题为什么被关闭，但在提出在各个问题的时候发现了和我**几乎一样**的问题 https://github.com/immersive-translate/immersive-translate/issues/15
- 复现方式一致：[自动翻译的时候，它会有问题。 但是整个网页加载完成后，手动点击翻译，或使用快捷键翻译，则结果正常。](https://github.com/immersive-translate/immersive-translate/issues/15#issuecomment-1380959946)
- 解决方案为：[给这个网站加一个延迟](https://github.com/immersive-translate/immersive-translate/issues/15#issuecomment-1380960847) 并且，自己测试让翻译慢一些就能够更多的避免此类问题出现

所以类似的问题，应该也都可以通过延迟解决，所以希望能够自定义自动翻译延迟

**Comment by theowenyoung** [comment]
可以在开发者设置里添加如下配置：

```json
 "generalRule": {
    "urlChangeDelay": 5000
  }
```

![CleanShot 2024-03-21 at 01 04 28@2x](https://github.com/immersive-translate/immersive-translate/assets/62473795/21cbf1c4-915b-497c-a325-5177ff7553f0)

**Comment by qixing-jk** [comment]
并没有什么用，只能解决首屏出现的问题（并且在默认延迟下，首屏翻译也不会出现问题），出现问题的是边看边译的时候
