### ISSUE TITLE
插件翻译应当注意上下文吧

### ISSUE THREAD

**Issue by Nevergoodstudy** [immersive-translate/immersive-translate#1558]
### 您希望的更新和改进是什么 | Update or Improve

希望插件在进行翻译的时候，能够注意文章的上下文，尤其是上下文中出现的人名，地名，动词，又是经常出现上一段文字翻译的是一个动词/人名，而同一个词在下一段却是另一个动词或者人名的情况，希望开发人员在后期的改进中注意，希望这款插件办的越来越好。

**Comment by keyboard3** [comment]
这个目前没有办法做到，除非你用有道、百度这类翻译服务支持术语的服务
