### ISSUE TITLE
[Bug]:epub翻译完成并下载后，打开还是原文文档

### ISSUE THREAD

**Issue by luluchaos** [immersive-translate/immersive-translate#1562]
### 插件版本号 | Version

1.3.2

### 平台 | Platform

iOS

### 浏览器 | Browsers

Chrome, Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在ios自带的图书选取epub文件翻译完成并下载后，打开还是原文文档，无法创建新的中英翻译文档。
（原文档从ao3或者其他的电子书网站下载都这样）

### 出现问题的网址 | URL

https://immersivetranslate.com/

### 重现步骤 | To Reproduce

1. 从iOS的文件中导入epub文件并翻译
2. 翻译完成，按导出，自动下载到文件并跳转到图书
3. 发现还是无翻译的原文件
4. 从文件中查看确实有一个标题带翻译的epub但打开还是原文件

**Comment by keyboard3** [comment]
我这里用iOS和MacOS 都没有复现，附上你的epub文件看看

**Comment by luluchaos** [comment]
我这边已找到解决方法，谢谢！
