### ISSUE TITLE
[Bug]: youtube视频不能双语字幕了

### ISSUE THREAD

**Issue by Birdling** [immersive-translate/immersive-translate#1563]
### 插件版本号 | Version

1.3.3

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

https://github.com/immersive-translate/immersive-translate/assets/62651551/1c5bf4e3-e93c-4973-b16a-8fedd5aebafb

### 出现问题的网址 | URL

https://www.youtube.com/watch?v=ld7KtnULvVc

**Comment by keyboard3** [comment]
给插件隐身访问权限，在隐身窗口试下这个YouTube的字幕，怀疑是有其他插件干扰了

**Comment by Birdling** [comment]
隐身窗口正常，刚刚把所有插件关了，还是不行

**Comment by keyboard3** [comment]
> 隐身窗口正常，刚刚把所有插件关了，还是不行

油猴脚本呢？ 沉浸式没关吧，应该就是插件干扰的

**Comment by Birdling** [comment]
都关了，包括油猴脚本，只有沉浸式没关

**Comment by imtipi** [comment]
我也遇到了这个问题，需要点击自动开启双语字幕才能进行翻译

**Comment by FattySpring** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/25144301/9b8b5b6e-db76-499d-816a-18c1f2bc89f4)
需要点击【双语字幕】选择【自动开启双语字幕选项】 加载双语字幕

**Comment by keyboard3** [comment]
切换下网络节点试试

**Comment by imtipi** [comment]
> 切换下网络节点试试

![recording](https://github.com/immersive-translate/immersive-translate/assets/27230181/c32f582b-44ea-4fbe-9e4f-6b513f70ae16)
你可以在gif中看到，此问题与网络无关。具体问题为拓展菜单的翻译按钮无法翻译字幕，只有播放器内的按钮可以触发翻译

**Comment by keyboard3** [comment]
> 具体问题为拓展菜单的

新版本将网页翻译和字幕翻译分开，只能启用字幕翻译才会翻译字幕
