### ISSUE TITLE
[Bug]:  Google Chrome84显示语法错误，翻译失败

### ISSUE THREAD

**Issue by zjcnew** [immersive-translate/immersive-translate#1564]
### 插件版本号 | Version

1.3.3

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

Google Chrome | 84.0.4147.135 (正式版本) （64 位）在油猴插件上直接显示语法错误，导致翻译失败。
暴力猴版本：暴力猴v2.18.0
![screenshot-20240322-160356](https://github.com/immersive-translate/immersive-translate/assets/22335594/5873fb4b-00bc-4112-a167-c32cf9fe11c5)

### 出现问题的网址 | URL

https://www.redhat.com/sysadmin/linux-at-command

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/4bff2ddf-4976-4ae0-8e4c-5e8aa12ff548)
没有复现

**Comment by zjcnew** [comment]
> ![image](https://private-user-images.githubusercontent.com/13177744/315938996-4bff2ddf-4976-4ae0-8e4c-5e8aa12ff548.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwOTcwNzIsIm5iZiI6MTcxMTA5Njc3MiwicGF0aCI6Ii8xMzE3Nzc0NC8zMTU5Mzg5OTYtNGJmZjJkZGYtNDk3Ni00YWUwLThlNGMtNWU4YWExMmZmNTQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA4MzkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyZjRlZDkyOGFkMDIyYTZlMzI4OGEwOGI2ZTc5NzQyOWM1NWQzMzJiZjRjOWFiN2UwMDI3ODkxYWI4ZTBkOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a3Ry7r0EZ-twBnkTQ7o5w5wtTDftHwPzL0B-EgxRvPE) 没有复现

![image](https://github.com/immersive-translate/immersive-translate/assets/22335594/49878ea1-1506-41be-a9e2-73e14f3a206a)

**Comment by keyboard3** [comment]
> > ![image](https://private-user-images.githubusercontent.com/13177744/315938996-4bff2ddf-4976-4ae0-8e4c-5e8aa12ff548.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwOTcwNzIsIm5iZiI6MTcxMTA5Njc3MiwicGF0aCI6Ii8xMzE3Nzc0NC8zMTU5Mzg5OTYtNGJmZjJkZGYtNDk3Ni00YWUwLThlNGMtNWU4YWExMmZmNTQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA4MzkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyZjRlZDkyOGFkMDIyYTZlMzI4OGEwOGI2ZTc5NzQyOWM1NWQzMzJiZjRjOWFiN2UwMDI3ODkxYWI4ZTBkOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a3Ry7r0EZ-twBnkTQ7o5w5wtTDftHwPzL0B-EgxRvPE) 没有复现
> 
> ![image](https://private-user-images.githubusercontent.com/22335594/315945218-49878ea1-1506-41be-a9e2-73e14f3a206a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwOTc3NjAsIm5iZiI6MTcxMTA5NzQ2MCwicGF0aCI6Ii8yMjMzNTU5NC8zMTU5NDUyMTgtNDk4NzhlYTEtMTUwNi00MWJlLWE5ZTItNzNlMTRmM2EyMDZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA4NTEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmZTQ3MmVlZDg1N2M3OTY5Y2FjNzE4ZGM2MzhlNjlmOGJiMGU3ODVmZWQ1ZTk0OWM2ZjhkOGU2MGY1MDQ2ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZqRiwmB0Zi6T15iFI-xHDN_oIc2LHXExX9gdrL5JuQ0)

你是从官网下载油猴脚本吗？ https://immersivetranslate.com/

**Comment by zjcnew** [comment]
> https://immersivetranslate.com/

对，没错

**Comment by zjcnew** [comment]
我挨个版本测试竟然发现v1.2.1版本正常可用，https://github.com/immersive-translate/immersive-translate/blob/v1.2.1/dist/userscript/immersive-translate.user.js
![image](https://github.com/immersive-translate/immersive-translate/assets/22335594/a68cf11a-bc29-4f31-a531-f5954606c410)

但是设置页面 https://dash.immersivetranslate.com/#general 仍然无法打开，一直显示 Loading... 发现控制台是同样的报错
![image](https://github.com/immersive-translate/immersive-translate/assets/22335594/b214d9e1-6d6b-4c01-b16e-7b4666cad89a)

**Comment by keyboard3** [comment]
> 我挨个版本测试竟然发现v1.2.1版本正常可用，https://github.com/immersive-translate/immersive-translate/blob/v1.2.1/dist/userscript/immersive-translate.user.js ![image](https://private-user-images.githubusercontent.com/22335594/315953687-a68cf11a-bc29-4f31-a531-f5954606c410.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMDIzNjAsIm5iZiI6MTcxMTEwMjA2MCwicGF0aCI6Ii8yMjMzNTU5NC8zMTU5NTM2ODctYTY4Y2YxMWEtYmMyOS00ZjMxLWE1MzEtZjU5NTQ2MDZjNDEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDEwMDc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjOWQ2ZGE0NzU4ZWU3MWE1NTYyZjAwOWRlMzBlMDViOTFmNzY5ZjU3YTI4ZTNiOTQwMTMzYmZlMjJmYzAyZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7LmlUYDLRsGUFTenn8KpPucCCXsSzmrSqJ4j2aHTZS4)
> 
> 但是设置页面 https://dash.immersivetranslate.com/#general 仍然无法打开，一直显示 Loading... 发现控制台是同样的报错 ![image](https://private-user-images.githubusercontent.com/22335594/315953495-b214d9e1-6d6b-4c01-b16e-7b4666cad89a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMDIzNjAsIm5iZiI6MTcxMTEwMjA2MCwicGF0aCI6Ii8yMjMzNTU5NC8zMTU5NTM0OTUtYjIxNGQ5ZTEtNmQ2Yi00YzAxLWIxNmUtN2I0NjY2Y2FkODlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDEwMDc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViMTA4YzYxZTQ2NmIxNTBmNWY2MDNmOTFhNTczM2M4YWU0OTZhZmFiMWYxZDVkMTdhMDYwMzRiMzMxY2MzZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7ad8lAMq5BGc0XF1aVsxaZRrQjbUIylrtjgsdsMItKk)

你试着装插件应该没问题，我感觉。 可能是网络问题被异常压缩导致的
