### ISSUE TITLE
[Bug]: 实时字幕识别过程中疯狂闪

### ISSUE THREAD

**Issue by GoMateoGo** [immersive-translate/immersive-translate#1565]
### 插件版本号 | Version

1.34

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![GIF 2024-03-23 13-58-17](https://github.com/immersive-translate/immersive-translate/assets/18229643/667cb23e-45f0-4751-a635-872d8ab5f6a3)
因为gip帧率问题，闪烁比较慢，实际上要快很多倍。

### 出现问题的网址 | URL

哔哩哔哩任何一个视频

### 重现步骤 | To Reproduce

1. 打开视频，等待一会，自动根据语音自动出现实时字幕。
2. 在中文状态下会疯狂闪。
3. 我想知道如何关闭实时字幕？ 谁能告诉我？ 要被这个实时字幕搞疯了。配置都试了，这个实时字幕就是关闭不了吗？？？？

**Comment by keyboard3** [comment]
这个不是沉浸式的功能。 这个是chrome浏览器的[实时字幕](https://support.google.com/chrome/answer/10538231?hl=zh-Hans)

**Comment by GoMateoGo** [comment]
哈哈，小丑竟然是我自己。
