### ISSUE TITLE
[Bug]: 读取本地 epub 文件时，Scrolled 模式文本显示不全

### ISSUE THREAD

**Issue by usoonees** [immersive-translate/immersive-translate#1567]
### 插件版本号 | Version

v1.3.4

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

读取本地 Epub 文件，使用 Scrolled 模式文本显示不全
<img width="1438" alt="Snipaste_2024-03-23_18-39-38" src="https://github.com/immersive-translate/immersive-translate/assets/56818734/dd5722d1-7b37-4cba-ac4b-43aa37e66739">

### 出现问题的网址 | URL

https://app.immersivetranslate.com/ebook/

### 重现步骤 | To Reproduce

1. 上传 epub 文件
2. 跳转到某一页
3. 从 Paginated 模式切换到 Scolled 模式

**Comment by keyboard3** [comment]
没能复现，一开始切换还是中途切换才有？

**Comment by keyboard3** [comment]
已修复 再试下
