### ISSUE TITLE
[Bug]: soundcloud混乱的翻译

### ISSUE THREAD

**Issue by ThemanRonin** [immersive-translate/immersive-translate#1570]
### 插件版本号 | Version

v1.3.4

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/35099500/041b397c-f897-42e5-972d-d7f4cbc3ac1e)
![image](https://github.com/immersive-translate/immersive-translate/assets/35099500/0b52debe-171f-428e-b291-c77ffbcab957)

https://soundcloud.com/
下的翻译非常混乱，排版字符非常怪异。

更奇怪的是，他为什么会翻译出原网页中不存在的信息？
例如下面这个图片
![image](https://github.com/immersive-translate/immersive-translate/assets/35099500/2ba4ae10-eb02-4bd2-b1aa-519b168edd67)
在soundcloud.com网页中居然翻译出来了Icp的备案信息？ 
我查询了网页相关代码以及审查元素代码，原文中不存在任何备案原文，不知道这是怎么呈现的

### 出现问题的网址 | URL

主页：https://soundcloud.com/  
搜索页面翻译出来了Icp的备案信息：https://soundcloud.com/search?q=instrumental%20hip%20hop

### 重现步骤 | To Reproduce

soundcloud.com下100%稳定重现

### 补充说明 | Additional context

nop

**Comment by keyboard3** [comment]
已适配，只翻译正文部分
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/1df80c1e-5d63-48ed-8af2-90f9733872cd)
