### ISSUE TITLE
[Bug]: V1.2.3之后使用任何翻译引擎都会一直转圈

### ISSUE THREAD

**Issue by cesaryuan** [immersive-translate/immersive-translate#1572]
### 插件版本号 | Version

1.3.4

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

v1.3.4翻译会一直转圈，重装回1.2.2没有问题，控制台报这个错
![image](https://github.com/immersive-translate/immersive-translate/assets/35998162/49c67ae9-3473-469f-9c63-9b124719c00c)

### 出现问题的网址 | URL

任何网站

### 重现步骤 | To Reproduce

1. 安装v1.3.4的油猴脚本
2. 打开 https://www.geeksforgeeks.org/passing-a-function-as-a-parameter-in-cpp/
3. 点翻译

**Comment by theowenyoung** [comment]
是不是和其他脚本有冲突导致？

我这边 mac 和 windows  在chrome上测试都是正常的。

**Comment by cesaryuan** [comment]
> 是不是和其他脚本有冲突导致？

经过排查是这一步耗费了大量时间`await Z3(this.translationOptions.translationService, y);`

进一步步入，是getDelay中的`await this.setStrictTicks(t, a, r),`耗费了大量时间

**Comment by cesaryuan** [comment]
@theowenyoung  找到问题所在了，是暴力猴的异步API `GM.setValue` 有bug，参见https://github.com/violentmonkey/violentmonkey/issues/2058
