### ISSUE TITLE
[Bug]: 部分段落漏翻

### ISSUE THREAD

**Issue by talking-toaster** [immersive-translate/immersive-translate#1574]
### 插件版本号 | Version

0.5.5

### 平台 | Platform

Linux

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/49156890/d42a572e-a7f8-4535-815c-d81b46fe6b4f)
图中右侧有一段话`The feasible region defined by...`未翻译，刷新页面也是

### 出现问题的网址 | URL

https://nlopt.readthedocs.io/en/latest/NLopt_Tutorial/

**Comment by flamintune** [comment]
可能是插件版本的问题，更新下插件版本试试，我这边能够正常翻译
![image](https://github.com/immersive-translate/immersive-translate/assets/79519446/ba481329-241a-4655-8fc4-04d37e1b8af7)

**Comment by Copy2Translator** [comment]
漏翻这个问题我翻译本地字幕时也遇到过，用的是 DeepLX，不知道是 DeepL 的问题还是 Firefox 扩展原因造成的，等下次再遇到漏翻的情况排查下

**Comment by talking-toaster** [comment]
当前使用版本为1.3.4, 是最新版本。

重新尝试发现该问题复现方法，当开启`总是翻译英文网站`功能时，打开`https://nlopt.readthedocs.io/en/latest/NLopt_Tutorial/`网站会稳定复现该问题，关闭该功能后，进入网站手动点击悬浮球翻译，则正常翻译。

**Comment by Copy2Translator** [comment]
> 当前使用版本为1.3.4, 是最新版本。
> 
> 重新尝试发现该问题复现方法，当开启`总是翻译英文网站`功能时，打开`https://nlopt.readthedocs.io/en/latest/NLopt_Tutorial/`网站会稳定复现该问题，关闭该功能后，进入网站手动点击悬浮球翻译，则正常翻译。

使用的是 DeepL 翻译的吗？我发现 DeepL 会漏翻译，然后搜索了一下原来是个普遍现象！

**Comment by talking-toaster** [comment]
> > 当前使用版本为1.3.4, 是最新版本。
> > 重新尝试发现该问题复现方法，当开启`总是翻译英文网站`功能时，打开`https://nlopt.readthedocs.io/en/latest/NLopt_Tutorial/`网站会稳定复现该问题，关闭该功能后，进入网站手动点击悬浮球翻译，则正常翻译。
> 
> 使用的是 DeepL 翻译的吗？我发现 DeepL 会漏翻译，然后搜索了一下原来是个普遍现象！
测试了 谷歌翻译、微软翻译和openai
