### ISSUE TITLE
可以指定内容不翻译吗?

### ISSUE THREAD

**Issue by swelzh** [immersive-translate/immersive-translate#1575]
### 您希望的更新和改进是什么 | Update or Improve

可以指定内容不翻译吗?
比如人名，公司名，产品名之类的？
使用场景是在twitter.com

**Comment by theowenyoung** [comment]
可以，在【进阶设置】里设置不翻译的词即可。

**Comment by swelzh** [comment]
收到，感谢！

Owen ***@***.***> 于2024年3月27日周三 18:29写道：
