### ISSUE TITLE
[Feature Request] 右键菜单中加入仅翻译所选内容

### ISSUE THREAD

**Issue by Ptilopsis01** [immersive-translate/immersive-translate#1578]
### 您希望的更新和改进是什么 | Update or Improve

如题，目前似乎只能翻译整个网页，有时会比较浪费token，希望可以在浏览器右键菜单中加入仅翻译当前选中内容的功能

**Comment by keyboard3** [comment]
面板上可以启用鼠标悬停，按照所需段落翻译
