### ISSUE TITLE
[Bug]: 悬浮球异常出现（在 Chrome 的响应式调试模式刷新后自动出现）

### ISSUE THREAD

**Issue by cssmagic** [immersive-translate/immersive-translate#1579]
### 插件版本号 | Version

1.3.4

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

重现步骤：

1. 我的悬浮球是禁用的。

	![Screen-Shot-2024-03-28-at-02 26 28pm](https://github.com/immersive-translate/immersive-translate/assets/1231359/58529cdc-eea1-4fb3-a2d7-03ba8732a637)

1. 打开一个网页，比如 [这个](https://hellouniapp.dcloud.net.cn/pages/component/view/view)。此时悬浮球不出现（符合预期）。

1. 打开 Chrome 的调试工具，进入响应式调试模式。此时悬浮球不出现（符合预期）。

1. 刷新页面，悬浮球自动出现。效果如下图：

	![Screen-Shot-2024-03-28-at-02 28 09pm](https://github.com/immersive-translate/immersive-translate/assets/1231359/d2dc1175-3b4e-47b2-a499-bcfe04822596)

**Comment by keyboard3** [comment]
悬浮球配置在pc和h5上独立的。要禁用移动端的，也要让设置页面进入移动端模式

**Comment by cssmagic** [comment]
原来如此，谢谢回复！

不过这个设计也太不明显了 😂

**Comment by dosicker** [comment]
> 悬浮球配置在pc和h5上独立的。要禁用移动端的，也要让设置页面进入移动端模式

这真的是太骚啦~🤦‍♂️
