### ISSUE TITLE
Win10 FireFox v110 會導致記憶體使用量爆增

### ISSUE THREAD

**Issue by terry197913** [immersive-translate/immersive-translate#158]
Win10  FireFox v110 會導致記憶體使用量爆增，一直到吃光系統記憶體然後 OS 炸掉。

**Comment by cjjdaq** [comment]
在win11上也发现了同样的问题，如果网页有iframe，然后不停的重复刷新页面，内存就会不停的增加，然后一直到页面无响应。

**Comment by theowenyoung** [comment]
感谢报告，我最近在ios的脚本中也遇到类似问题，怀疑是在0.2.60版本引入了一个本地的繁体转简体造成的.

**Comment by theowenyoung** [comment]
经测试，移除后，恢复正常，新版本将移除本地繁体转简体功能.

**Comment by theowenyoung** [comment]
0.2.67已释出～

商店版还要等一下审核

**Comment by terry197913** [comment]
感謝您~
