### ISSUE TITLE
arXiv 新版HTML页面的 顶部 不应被翻译，避免占位置

### ISSUE THREAD

**Issue by foresee-io** [immersive-translate/immersive-translate#1580]
### 您希望的更新和改进是什么 | Update or Improve

从2024年起arXiv真正开放了HTML reader，但顶部会有提示语。“沉浸式翻译”扩展将会翻译顶部信息，造成额外的空间占用，如图。

Link: https://arxiv.org/html/2403.02330v1?_immersive_translate_auto_translate=1
Extension ver: v1.3.4 on Chrome
Rule ver: 2024/3/28 11:10:23

<img width="798" alt="截屏2024-03-28 16 40 31" src="https://github.com/immersive-translate/immersive-translate/assets/32860378/557a43ca-cfc8-44ff-9ae7-f9622cc55d92">

（未翻译时 顶部 占据的位置较小）
<img width="794" alt="截屏2024-03-28 16 40 53" src="https://github.com/immersive-translate/immersive-translate/assets/32860378/76534cb4-5639-408d-ac82-a081bb43aca9">

**Comment by theowenyoung** [comment]
感谢反馈，已在规则中排除 header.
