### ISSUE TITLE
双语字幕能否支持改变字体和文字颜色？

### ISSUE THREAD

**Issue by DeterminantMatrix** [immersive-translate/immersive-translate#1581]
### 您希望的更新和改进是什么 | Update or Improve

双语字幕能否支持改变字体和文字颜色？

### 补充说明 | Additional context

![image](https://github.com/immersive-translate/immersive-translate/assets/30826121/d75b9d8f-a072-40a2-a512-5522a64ce7a1)

**Comment by keyboard3** [comment]
什么平台？  1.4.2 youtube 支持了文字颜色大小改动

**Comment by wanzhiyu** [comment]
> 什么平台？ 1.4.2 youtube 支持了文字颜色大小改动

目前的原文和译文字体大小最低仅支持到70%，但是youtube中支持到最低50%，对于我大屏而言，50%是比较合适的，请问是否可以允许用户把这个值调低到50%？

**Comment by FattySpring** [comment]
[1.5.4](https://immersivetranslate.com/docs/CHANGELOG/#154) 已支持设置字体
