### ISSUE TITLE
[Bug]: 翻译结果中未附带原文的超链接

### ISSUE THREAD

**Issue by yamazakitouma** [immersive-translate/immersive-translate#1583]
### 插件版本号 | Version

1.3.4

### 平台 | Platform

macOS

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

<img width="1999" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/28669193/1f369b26-3f38-49e2-a85c-9e657b71220f">

在翻译结果中，没有附带原文的文本超链接，无论是 双语对照 还是 仅译文 模式，都无法正确在译文中显示文本超链接

### 出现问题的网址 | URL

https://helpcenter.onlyoffice.com/installation/workspace-enterprise-install-linux.aspx

### 重现步骤 | To Reproduce

1. 进入网址
2. 进行翻译

### 补充说明 | Additional context

我希望能在译文中正确展示文本超链接，这样我可以正确点击进行跳转，而不用必须使用 双语对照 模式，从原文进行点击

**Comment by keyboard3** [comment]
目前暂不支持还原原文超链接，查看其他相关问题：
https://github.com/immersive-translate/immersive-translate/issues?q=is%3Aissue+%E8%B6%85%E9%93%BE%E6%8E%A5+is%3Aclosed
