### ISSUE TITLE
Support For Local LLM

### ISSUE THREAD

**Issue by fydeos-alex** [immersive-translate/immersive-translate#1584]
### 您希望的更新和改进是什么 | Update or Improve

I wish there could be a new option to use the local large language model that supports URL links like Ollama.
It will be a fascinating function for all users who don't have openai API key, or just want to translate their local files when there is no Internet connection.

### 补充说明 | Additional context

Local LLM can be linked from URL like this: http://localhost:8000/custom-llm.
You can find more information from [https://github.com/ollama/ollama/blob/main/docs/api.md](url), and [https://cheshirecat.ai/custom-large-language-model/](url)

**Comment by fosmjo** [comment]
See [如何支持 ollama](https://immersivetranslate.com/docs/faq/#%E5%A6%82%E4%BD%95%E6%94%AF%E6%8C%81-ollama)

**Comment by keyboard3** [comment]
https://immersivetranslate.com/docs/services/ai/

**Comment by fydeos-alex** [comment]
Thanks a lot. It's my fault didn't read the doc carefully.🙏
