### ISSUE TITLE
[Bug]: ios系统safari浏览器频繁出现无法翻译情况

### ISSUE THREAD

**Issue by ceiminya** [immersive-translate/immersive-translate#1585]
### 插件版本号 | Version

1.3.4

### 平台 | Platform

iOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在iPad和iPhone都安装了沉浸式翻译的Safari浏览器插件，使用时经常出现悬浮球不显示，且无法翻译的情况。

例如，随机点进一个网页，一开始悬浮球正常显示，刷新一下或者在点链接跳转其它网页后，后续就不再会显示悬浮球，同时也无法翻译，点击插件页面，提示“ 请先刷新当前页面，再开始翻译”，但多次反复刷新仍然无效，必须将浏览器强制退出后重新进入，才会正常显示翻译和悬浮球。

尝试使用Userscripts安装了油猴脚本，仍然是同样的问题。

**Comment by keyboard3** [comment]
iOS 什么版本？ 可以试下安装 沉浸式翻译浏览器

**Comment by ceiminya** [comment]
系统版本都是17.4.1。沉浸式翻译浏览器目前可以正常使用，但是装不了其它插件，用不习惯。

**Comment by keyboard3** [comment]
录个屏看下你问题的具体情况

**Comment by ceiminya** [comment]
> 录个屏看下你问题的具体情况

[录屏](https://streamable.com/b4in6i)

**Comment by ceiminya** [comment]
> 点击悬浮器即可翻译，不需要打开面板再按按钮。 “ 请先刷新当前页面，再开始翻译”这个应该是那个网页特殊导致的，把视频中那个网页地址发出来

经常误触悬浮球，所以后来设置成了点击悬浮球打开面板再翻译。 

上面视频里出现的这两个网址[【1】](https://www.icrea.cat/Web/ScientificStaff/ramon-alvarez-puebla-560#) [【2】](https://pubmed.ncbi.nlm.nih.gov/?term=Pezzotti+G&cauthor_id=32359130)，都是一开始不出现悬浮球且无法翻译（分别在1分07秒、3分27秒），3分40秒关闭Safari浏览器，再次点击进入Safari浏览器界面之后，这两个网页均又出现悬浮球（分别在3分42秒、4分11秒）。

“ 请先刷新当前页面，再开始翻译”在平时访问twitter、github的时候都会出现。

![twitter](https://github.com/immersive-translate/immersive-translate/assets/51445012/970f9492-2cd6-4725-a406-f6c4c58e21bf)
![github](https://github.com/immersive-translate/immersive-translate/assets/51445012/c8556332-468e-4dae-853b-3a52bcee5696)

**Comment by keyboard3** [comment]
我的mac safari 目前没遇到这种情况，我们继续观察观察

**Comment by ImSingee** [comment]
iOS Safari

例如 https://longreads.com/2023/03/16/extreme-sports-reading-list/?utm_source=substack&utm_medium=email 网页

没有悬浮球、点击菜单中的扩展提示需要刷新页面（刷新后依然无效）

**Comment by keyboard3** [comment]
> iOS Safari
> 
> 例如 https://longreads.com/2023/03/16/extreme-sports-reading-list/?utm_source=substack&utm_medium=email 网页
> 
> 没有悬浮球、点击菜单中的扩展提示需要刷新页面（刷新后依然无效）

![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/5eb083da-ee82-4849-8081-4b0869b05637)
我这边正常

**Comment by ImSingee** [comment]
@keyboard3 我这边也正常了

沉浸式翻译的 iOS Safari 插件的加载是否和网络有关？因为我遇到的几次插件加载不出来似乎都是在弱网环境下

**Comment by ImSingee** [comment]
我利用 iOS 自带的模拟丢包，模拟到 50% 左右丢包率的话，有很大的概率出现：很久之后网页会加载成功，但是沉浸式翻译的悬浮球没有

并且一个很有趣的点：在此以后将网络设置恢复正常，在前述测试网页刷新多次重新加载沉浸式翻译的悬浮球依然不会加载成功，但是复制链接开一个新的标签页打开就可以正常加载出来悬浮球

**Comment by keyboard3** [comment]
> @keyboard3 我这边也正常了
> 
> 沉浸式翻译的 iOS Safari 插件的加载是否和网络有关？因为我遇到的几次插件加载不出来似乎都是在弱网环境下

是的 悬浮球要等待网页完全加载完才会显示

**Comment by ImSingee** [comment]
@keyboard3 但是弱网络环境下，后面网页加载成功后也有概率无法正常加载出悬浮球
