### ISSUE TITLE
[輸入框增強]觸發字符問題

### ISSUE THREAD

**Issue by FishFeng** [immersive-translate/immersive-translate#1586]
### 您希望的更新和改进是什么 | Update or Improve

輸入法：Win11 微軟注音
瀏覽器：Chrome 123.0.6312.86
問題：輸入法增強功能只能使用[空格鍵]三連觸發，更改成設定中其它觸發鍵[=、;、.]都無法觸發，只有空格鍵能觸發。
額外建議：以下是台灣繁體中文鍵盤布局，請將[輸入框增強]觸發字符"桃紅色的注音符號"、"綠色的倉頡符號"，避免按鍵與輸入法衝突。可考慮用數字鍵區的 *、-、+ 或 \、` 作為快速鍵。

![螢幕擷取畫面 2024-03-30 025910](https://github.com/immersive-translate/immersive-translate/assets/61592589/fe2457c3-22e8-4fe5-a8e7-ded10c521321)

**Comment by keyboard3** [comment]
我们比较建议通过快捷键触发，兼容性更高，字符触发限制比较多
