### ISSUE TITLE
希望提供本地HTML翻译支持

### ISSUE THREAD

**Issue by VinnaJ** [immersive-translate/immersive-translate#1589]
### 您希望的更新和改进是什么 | Update or Improve

在使用Safari打开本地的HTML网页后，immersive-translate无法提供翻译服务，希望得到改进和更新。非常感谢！
![Uploading 本地HTML未提供支持.png…]()

**Comment by theowenyoung** [comment]
在扩展管理里 手动开启一下本地文件的读取权限即可，文档： https://immersivetranslate.com/docs/faq/#%E7%BF%BB%E8%AF%91%E6%9C%AC%E5%9C%B0%E6%96%87%E4%BB%B6
