### ISSUE TITLE
在0.2.59版本后与扩展Relingo发生冲突

### ISSUE THREAD

**Issue by cjh-store** [immersive-translate/immersive-translate#159]
![image](https://user-images.githubusercontent.com/88535245/220795766-d3c927d4-a517-4f92-8ec9-8b8e6767c9d2.png)
![image](https://user-images.githubusercontent.com/88535245/220795849-f43763d9-13fd-4856-ad6b-21a1b9799dfb.png)
Relingo标记了生词后 会被分割成几段
不知道是因为更新了什么 导致了这种情况,在0.2.58版本是正常的

**Comment by julee** [comment]
同样也和另一个扩展 https://github.com/XQDD/highlight_new_words 冲突。
highlight_new_words 用来在网页中高亮欧陆词典生词本中的单词，帮助用来回顾学习词汇。

网页中有单词高亮的情况下，用沉浸式翻译进行翻译：

![image](https://user-images.githubusercontent.com/1493342/220816118-851a0d83-4a37-4948-a311-763573371ee3.png)

希望提供一种方法能够将这些标注的词和原来的段落保留在一起来进行翻译。

**Comment by theowenyoung** [comment]
最新版本已兼容relingo. 0.2.67

**Comment by julee** [comment]
> 

请问 [highlight_new_words](https://github.com/XQDD/highlight_new_words) 能兼容吗？

**Comment by theowenyoung** [comment]
可以的～ 我研究一下，还没用过这个

**Comment by theowenyoung** [comment]
应该可以了， 点击浏览器扩展图标更新一下规则～

**Comment by julee** [comment]
> 

试了下，没问题了。 感谢作者！
