### ISSUE TITLE
希望能优化翻译区域

### ISSUE THREAD

**Issue by Lionad-Morotar** [immersive-translate/immersive-translate#1590]
### 您希望的更新和改进是什么 | Update or Improve

目前决定一个句子需不需要翻译的设置只找到“字符长度”这一个选项。

希望能：
1. 增加选项：检测网页的主要区域，只翻译主要内容区域。
2. 增加选项：提供域名下自定义 CSS 区域接口，只翻译自定义 CSS 匹配中的区域

**Comment by keyboard3** [comment]
可以看下这个[高级自定义选项文档](https://immersivetranslate.com/docs/advanced/)
