### ISSUE TITLE
[Bug]: 导入PDF时总是加载失败

### ISSUE THREAD

**Issue by ryankamanri** [immersive-translate/immersive-translate#1591]
### 插件版本号 | Version

1.3.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

edge在PDF页面时点击插件的“点击去导入PDF”，页面加载不出来
![image](https://github.com/immersive-translate/immersive-translate/assets/61932835/c10ab494-b34a-4e92-89f3-c7ef5db29f9d)

浏览器控制台报错：
![image](https://github.com/immersive-translate/immersive-translate/assets/61932835/9d2929c5-558b-4e1d-a232-69a182fe5647)

需要手动选择打开文件才能显示

### 出现问题的网址 | URL

PDF文件

**Comment by theowenyoung** [comment]
需要你手动开启一下 本地文件的读取权限：

https://immersivetranslate.com/docs/faq/#%E7%BF%BB%E8%AF%91%E6%9C%AC%E5%9C%B0%E6%96%87%E4%BB%B6

**Comment by ryankamanri** [comment]
@theowenyoung 我开了好像也不起作用。。。但我之前用的时候都好好的，这两天突然就用不了了，也不知道咋回事儿

**Comment by keyboard3** [comment]
你在这个页面试下呢 https://app.immersivetranslate.com/

**Comment by ryankamanri** [comment]
@keyboard3 用这个页面可以正常打开

**Comment by keyboard3** [comment]
可以在插件中再试下，页面显示已修复
