### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by taoranzhishang** [immersive-translate/immersive-translate#1594]
### 插件版本号 | Version

1.3.4

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

使用翻译时提示以下内容：

当前 Gemini 服务当前承载能力已达上限，请您稍后再试，或者切换到其他翻译服务。

429: { "error": { "code": 429, "message": "Quota exceeded for quota metric 'Generate Content API requests per minute' and limit 'GenerateContent request limit per minute for a region' of service 'generativelanguage.googleapis.com' for consumer 'project_number:654326233903'.", "status": "RESOURCE_EXHAUSTED", "details": [ { "@type": "type.googleapis.com/google.rpc.ErrorInfo", "reason": "RATE_LIMIT_EXCEEDED", "domain": "googleapis.com", "metadata":

**Comment by keyboard3** [comment]
目前 gemini 不可用，谷歌风控限制太多。 1.4.1 已下架 gemini
