### ISSUE TITLE
[Bug]: 翻译日语字幕时出现多次重复，译文和双语都是

### ISSUE THREAD

**Issue by tcknight** [immersive-translate/immersive-translate#1596]
### 插件版本号 | Version

1.3.4

### 平台 | Platform

Windows

### 浏览器 | Browsers

Other

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

[20160821_ほんの５ｇ.zip](https://github.com/immersive-translate/immersive-translate/files/14836804/20160821_.zip)
字幕的重复没有固定规律，有的语句不重复，有的重复三遍有的四遍，已经上传字幕供参考

浏览器是360极速X

### 出现问题的网址 | URL

https://app.immersivetranslate.com/subtitle/

### 重现步骤 | To Reproduce

1，选取字幕 2、默认谷歌翻译但开始没开梯子提示失败，于是切换成微软翻译但翻译结果不理想 3、打开梯子切换成谷歌翻译，输出双语字幕 4、发现问题后刷新页面清楚本地缓存，但都无效，始终重复

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/843bb172-aa9c-4341-9f98-438d1592342e)
没有复现。 你录个屏看下

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/d1d9c3ce-0fa8-4303-8d0c-5d0149cdaab0)
字幕自身的时间有问题
