### ISSUE TITLE
[Bug]: Chrome商店最新版插件的译文显示样式改变？

### ISSUE THREAD

**Issue by sino1641** [immersive-translate/immersive-translate#1597]
### 插件版本号 | Version

1.3.4

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

Chrome123 更新插件1.3.4后，译文显示css会增加一项 `immersive-translate-target-translation-theme-dashed-inner`
<img width="1229" alt="Snipaste_2024-04-03_04-53-58" src="https://github.com/immersive-translate/immersive-translate/assets/13870295/a419dabf-4ff5-401b-ae0e-601493f5b143">

插件中选择的是虚线下划线，关闭该背景后恢复
<img width="1224" alt="Snipaste_2024-04-03_04-53-53" src="https://github.com/immersive-translate/immersive-translate/assets/13870295/d607201e-26be-482f-8d56-544a9433b920">

### 出现问题的网址 | URL

(https://opentelemetry.io/docs/demo/collector-data-flow-dashboard/)

### 补充说明 | Additional context

简单搜索过issue没有人提问
changelog和commits貌似也没有关于这里的变动
~~难道是我浏览器的问题~~

**Comment by keyboard3** [comment]
没看懂？译文选择的是什么样式？预期是啥

**Comment by sino1641** [comment]
> 没看懂？译文选择的是什么样式？预期是啥

Hi 
预期：
<img width="606" alt="Snipaste_2024-04-03_14-27-49" src="https://github.com/immersive-translate/immersive-translate/assets/13870295/db738f3f-de4b-46d8-9a2e-a91bbc039095">
实际：
<img width="815" alt="Snipaste_2024-04-03_14-28-07" src="https://github.com/immersive-translate/immersive-translate/assets/13870295/cdbfe387-a23c-47d6-9f0a-f5b7779dc60e">

**Comment by keyboard3** [comment]
> > 没看懂？译文选择的是什么样式？预期是啥
> 
> Hi 预期： <img alt="Snipaste_2024-04-03_14-27-49" width="606" src="https://private-user-images.githubusercontent.com/13870295/319064753-db738f3f-de4b-46d8-9a2e-a91bbc039095.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMjYwOTMsIm5iZiI6MTcxMjEyNTc5MywicGF0aCI6Ii8xMzg3MDI5NS8zMTkwNjQ3NTMtZGI3MzhmM2YtZGU0Yi00NmQ4LTlhMmUtYTkxYmJjMDM5MDk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDA2Mjk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkNWZkMzgwNjhhN2I1YmM2OTFhMjM3NGJiMWIzMWM1OGFmZTRjMzdlZmNiMWE5NTE2ZTk5YjA5NWI4YTk0ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZpQ_5PTudwOfeOrZFy8pEsRQJPAHu44M274YwqwnBRA"> 实际： <img alt="Snipaste_2024-04-03_14-28-07" width="815" src="https://private-user-images.githubusercontent.com/13870295/319064818-cdbfe387-a23c-47d6-9f0a-f5b7779dc60e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMjYwOTMsIm5iZiI6MTcxMjEyNTc5MywicGF0aCI6Ii8xMzg3MDI5NS8zMTkwNjQ4MTgtY2RiZmUzODctYTIzYy00N2Q2LTlmMGEtZjViNzc3OWRjNjBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDA2Mjk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiOGY4NTMyODM5Y2Y2NWU1OTMwNjMwY2RjODM5MWExYzZhMWNkZGIxOGM5MTFjM2NhMTQxYTFiMWM1NTE5MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0h8OlXwmIUl5ZZvD8cBeXOMEC2fmjjL0uiSvAN9F62M">

我试了这个选项没有复现，是所有网页都出现？还是只是这个网页？

**Comment by sino1641** [comment]
> > > 没看懂？译文选择的是什么样式？预期是啥
> > 
> > 
> > Hi 预期： <img alt="Snipaste_2024-04-03_14-27-49" width="606" src="https://private-user-images.githubusercontent.com/13870295/319064753-db738f3f-de4b-46d8-9a2e-a91bbc039095.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMjYwOTMsIm5iZiI6MTcxMjEyNTc5MywicGF0aCI6Ii8xMzg3MDI5NS8zMTkwNjQ3NTMtZGI3MzhmM2YtZGU0Yi00NmQ4LTlhMmUtYTkxYmJjMDM5MDk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDA2Mjk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkNWZkMzgwNjhhN2I1YmM2OTFhMjM3NGJiMWIzMWM1OGFmZTRjMzdlZmNiMWE5NTE2ZTk5YjA5NWI4YTk0ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZpQ_5PTudwOfeOrZFy8pEsRQJPAHu44M274YwqwnBRA"> 实际： <img alt="Snipaste_2024-04-03_14-28-07" width="815" src="https://private-user-images.githubusercontent.com/13870295/319064818-cdbfe387-a23c-47d6-9f0a-f5b7779dc60e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMjYwOTMsIm5iZiI6MTcxMjEyNTc5MywicGF0aCI6Ii8xMzg3MDI5NS8zMTkwNjQ4MTgtY2RiZmUzODctYTIzYy00N2Q2LTlmMGEtZjViNzc3OWRjNjBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDA2Mjk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiOGY4NTMyODM5Y2Y2NWU1OTMwNjMwY2RjODM5MWExYzZhMWNkZGIxOGM5MTFjM2NhMTQxYTFiMWM1NTE5MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0h8OlXwmIUl5ZZvD8cBeXOMEC2fmjjL0uiSvAN9F62M">
> 
> 我试了这个选项没有复现，是所有网页都出现？还是只是这个网页？


Hi 谢谢帮忙！
实测是部分网页，例如我刚试了github没有问题。。
<img width="674" alt="Snipaste_2024-04-03_14-36-13" src="https://github.com/immersive-translate/immersive-translate/assets/13870295/258248fd-db3f-46f2-b90d-ceec5b603e6c">

出问题的是一些文档类的网页：
https://opentelemetry.io/docs/demo/collector-data-flow-dashboard/
https://openobserve.ai/docs/storage/
是不是与这类网页的框架有关？

**Comment by keyboard3** [comment]
你是不是用了什么夜间主题插件?

**Comment by sino1641** [comment]
> 你是不是用了什么夜间主题插件?

谢谢！关掉Dark Reader好了
请问可能有什么兼容性方案吗？
在issues里搜dark reader貌似没有结果

**Comment by keyboard3** [comment]
> > 你是不是用了什么夜间主题插件?
> 
> 谢谢！关掉Dark Reader好了 请问可能有什么兼容性方案吗？ 在issues里搜dark reader貌似没有结果

是这个主题插件影响的，建议切换主题插件或者切换其他译文样式试试

**Comment by sino1641** [comment]
dark reader会改css：
<img width="354" alt="Snipaste_2024-06-01_03-17-06" src="https://github.com/immersive-translate/immersive-translate/assets/13870295/0190f704-79e7-4e2f-b406-d7c351eb5f71">

开发者设置里给背景 +important 可以再覆盖掉：
<img width="590" alt="Snipaste_2024-06-01_03-14-21" src="https://github.com/immersive-translate/immersive-translate/assets/13870295/2f5c77fe-0d01-43ac-a6af-4eca97449cd6">

@keyboard3  我看首页readme说已经不用这个仓库了，可以把这个加到inject.css里吗？谢谢

我看有的样式有，有的样式没有important（观测在darkreader下有的正常，有的不行才发现的），请问是出于什么考虑呢？还是单纯写的时候没想到。。
