### ISSUE TITLE
[Bug]: In some cases IT stops re-translating the page when changing the service

### ISSUE THREAD

**Issue by iG8R** [immersive-translate/immersive-translate#1599]
### 插件版本号 | Version

1.4.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

The title says for itself.

E.g. URL - https://www.69shu.pro/txt/13823/8196298

[ImmersiveTranslate-ChangeProvider-no-refresh-Video_2024-04-03_11-02-29.webm](https://github.com/immersive-translate/immersive-translate/assets/11407417/bb579c12-b8f7-491b-8541-4478ae7bbced)

**Comment by keyboard3** [comment]
1.4.5 fixed

**Comment by iG8R** [comment]
Thanks a lot!
