### ISSUE TITLE
一段话太短的话，不会触发翻译

### ISSUE THREAD

**Issue by wellitecho** [immersive-translate/immersive-translate#160]
# 问题描述
![too_short_paragrah_not_translated](https://user-images.githubusercontent.com/79682683/220808479-36b27668-73e4-4209-a992-4fdc943332c6.png)

如图。
初步测试结果显示，最少要18个字符才能触发翻译。
但是日常使用语言时，存在少于18个字符的，语义完整的语句，比如 'How are you?'，或者简短的回复，比如 'Fantastic!', 'Bien.'

# 期望的实现
即使在句子少于18个字符时，仍能触发翻译。

**Comment by XHXIAIEIN** [comment]
这个目前只能在[开发者设置](https://immersive-translate.owenyoung.com/options/#developer) 修改。


点开 `Edit Full User Config` 在里面编辑这段配置。
如果里面没有，可以自己添加到最前面。如果已经存在，直接修改即可。
```json
"generalRule": {
  "containerMinTextCount": 18
},
```

如果想针对某个网站单独配置，可以在 `Edit User Rules` 里面配置

```json
[{
  "matches": "web.telegram.org",
  "containerMinTextCount": 18
}]
```

**Comment by wellitecho** [comment]
感谢。另外发现一个问题：当句子中包含表情(emoji)的时候，不会触发翻译。见下图：

![emoji_wont_work](https://user-images.githubusercontent.com/79682683/220829924-4e438366-d20e-49fb-bb4c-79ff32276c45.png)
