### ISSUE TITLE
[Bug]: Gemini怎么没有了？

### ISSUE THREAD

**Issue by Carrihoi** [immersive-translate/immersive-translate#1600]
### 插件版本号 | Version

V1.4.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

Claude加入后，Gemini没有了。
![微信图片_20240404095208](https://github.com/immersive-translate/immersive-translate/assets/165973920/cb5cfd5e-6fd6-46b6-844b-7b1465e5902d)

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/762f0f97-1920-440c-8226-262a844b26e3)

**Comment by Carrihoi** [comment]
好的，谢谢。
