### ISSUE TITLE
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. 

### ISSUE THREAD

**Issue by DJHWSAB** [immersive-translate/immersive-translate#1603]
### 您希望的更新和改进是什么 | Update or Improve

content_script.js文件中o.current.addEventListener("touchstart", A),修改为o.current.addEventListener("touchstart", A, {passive: true}),

**Comment by keyboard3** [comment]
你是在什么场景下用到？手机上滑动翻译段落？

**Comment by keyboard3** [comment]
移动端上触摸事件已调整
