### ISSUE TITLE
[Bug]: no response when using botton " 点击导入PDF“

### ISSUE THREAD

**Issue by bolin12** [immersive-translate/immersive-translate#1605]
### 插件版本号 | Version

1.4.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

when i open a pdf file using edge browser, then i click 点击导入PDF, no response. 

### 重现步骤 | To Reproduce

as Describe the bug mentioned

**Comment by keyboard3** [comment]
Record a video to see how it works

**Comment by keyboard3** [comment]
No feedback for a long time, close this issue for now
