### ISSUE TITLE
[Bug]: 双语字幕快捷方式开关在Windows11下edge浏览器失效了

### ISSUE THREAD

**Issue by lianwensheng** [immersive-translate/immersive-translate#1606]
### 插件版本号 | Version

1.4.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

双语字幕快捷方式开关在Windows11下edge浏览器失效了，YouTube始终都无法在右下角显示这个快捷方式
![屏幕截图 2024-04-04 195119](https://github.com/immersive-translate/immersive-translate/assets/36002202/2bb5582d-d7e1-4011-b551-9a0407f9a68b)

### 出现问题的网址 | URL

https://www.youtube.com/watch?v=D89ngRr4uZg

**Comment by johnnyee** [comment]
google chrome也是这个情况

**Comment by keyboard3** [comment]
1.4.7 已修复
