### ISSUE TITLE
[Bug]: 新版本YouTube双语字幕的“字符边缘样式”无法修改了，字幕的字体好像也没办法单独设置了

### ISSUE THREAD

**Issue by lianwensheng** [immersive-translate/immersive-translate#1607]
### 插件版本号 | Version

1.4.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

更新到1.4.5版本后，YouTube双语字幕的“字符边缘样式”无法自定义了，字幕的字体好像也没办法单独设置，只能跟随网页普通译文的字体，跟原始的单语字幕样式变化有些大，看起来有种很强的割裂感，希望之后的版本能够改进下。。。
![屏幕截图 2024-04-04 204700](https://github.com/immersive-translate/immersive-translate/assets/36002202/49f6e307-2cc4-416e-95f0-b1c7b77f83ae)
![屏幕截图 2024-04-04 191814](https://github.com/immersive-translate/immersive-translate/assets/36002202/6e56acbf-fd33-4bdc-8cb4-9de97a7034fd)
![屏幕截图 2024-04-04 191338](https://github.com/immersive-translate/immersive-translate/assets/36002202/48548c91-d837-4495-bc05-f3f6a3d436a5)

### 出现问题的网址 | URL

https://www.youtube.com/watch?v=d6iQrh2TK98

**Comment by MEIPork1** [comment]
一样

**Comment by pigxyz** [comment]
字体大小好像也不能调了。很大。

**Comment by theSybi1** [comment]
一样，越来越大了，之前是设为100%的时候有200%那么大，现在设为50%的时候还是有200%那么大，卸载重装也没用，太恼火了

**Comment by FattySpring** [comment]
新版本字幕样式的设置在这里

![image](https://github.com/immersive-translate/immersive-translate/assets/25144301/d3cac9a9-0a7a-4dd0-b958-ddcacbf6e023)

**Comment by Smobniar** [comment]
> 新版本字幕样式的设置在这里
> 
> ![image](https://private-user-images.githubusercontent.com/25144301/322680750-d3cac9a9-0a7a-4dd0-b958-ddcacbf6e023.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MDM1NzgsIm5iZiI6MTcxMzcwMzI3OCwicGF0aCI6Ii8yNTE0NDMwMS8zMjI2ODA3NTAtZDNjYWM5YTktMGE3YS00ZGQwLWI5NTgtZGRjYWNiZjZlMDIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDEyNDExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyZjRiZGFkOGI5YjM1NGI4ZWU0ODRkZjVlNWMyYzY3YmZiYjE3ZDdlNjdkMDA0NmZkMTNhODBkYjYyNWU3OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dVOiUdPADAYhYR2V5z0fk606bbK2edJVpQSHTMgjF58)

但是字符边缘样式的功能没有了，我个人（和上面的朋友）都是是喜欢把背景关掉用文字阴影的

**Comment by FattySpring** [comment]
> > 新版本字幕样式的设置在这里
> > ![image](https://private-user-images.githubusercontent.com/25144301/322680750-d3cac9a9-0a7a-4dd0-b958-ddcacbf6e023.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MDM1NzgsIm5iZiI6MTcxMzcwMzI3OCwicGF0aCI6Ii8yNTE0NDMwMS8zMjI2ODA3NTAtZDNjYWM5YTktMGE3YS00ZGQwLWI5NTgtZGRjYWNiZjZlMDIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDEyNDExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyZjRiZGFkOGI5YjM1NGI4ZWU0ODRkZjVlNWMyYzY3YmZiYjE3ZDdlNjdkMDA0NmZkMTNhODBkYjYyNWU3OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dVOiUdPADAYhYR2V5z0fk606bbK2edJVpQSHTMgjF58)
> 
> 但是字符边缘样式的功能没有了，我个人（和上面的朋友）都是是喜欢把背景关掉用文字阴影的

(1.4.11)[https://immersivetranslate.com/docs/CHANGELOG/#1411] 已支持【字符边缘样式】设置

**Comment by Smobniar** [comment]
> > > 新版本字幕样式的设置在这里
> > > ![image](https://private-user-images.githubusercontent.com/25144301/322680750-d3cac9a9-0a7a-4dd0-b958-ddcacbf6e023.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MDM1NzgsIm5iZiI6MTcxMzcwMzI3OCwicGF0aCI6Ii8yNTE0NDMwMS8zMjI2ODA3NTAtZDNjYWM5YTktMGE3YS00ZGQwLWI5NTgtZGRjYWNiZjZlMDIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDEyNDExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyZjRiZGFkOGI5YjM1NGI4ZWU0ODRkZjVlNWMyYzY3YmZiYjE3ZDdlNjdkMDA0NmZkMTNhODBkYjYyNWU3OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dVOiUdPADAYhYR2V5z0fk606bbK2edJVpQSHTMgjF58)
> > 
> > 
> > 但是字符边缘样式的功能没有了，我个人（和上面的朋友）都是是喜欢把背景关掉用文字阴影的
> 
> [1.4.11](https://immersivetranslate.com/docs/CHANGELOG/#1411) 已支持【字符边缘样式】设置

好有效率，爱了！可以增加修改字幕字体的功能吗，如果字幕字体也能更换的话就太好了

**Comment by FattySpring** [comment]
[1.5.4](https://immersivetranslate.com/docs/CHANGELOG/#154) 已支持设置字体

**Comment by Smobniar** [comment]
> [1.5.4](https://immersivetranslate.com/docs/CHANGELOG/#154) 已支持设置字体

👍立刻更新了，但选项还是有点少，可以进一步显示电脑上所有的字体吗，我自己喜欢在字幕上用瘦长的字体，因为这样在同等大小下能显示更多的字，谢谢
![截屏2024-05-15 下午12 08 26](https://github.com/immersive-translate/immersive-translate/assets/48118937/252a9e34-92e8-4d83-9b65-aa2a133582d9)
![截屏2024-05-15 下午12 09 55](https://github.com/immersive-translate/immersive-translate/assets/48118937/f601177c-182e-4e50-9e26-9423503bd7ab)
