### ISSUE TITLE
[Bug]: Custom prompt requirements for OpenAI and Gemini do not work

### ISSUE THREAD

**Issue by galaxypayoff** [immersive-translate/immersive-translate#1608]
### 插件版本号 | Version

1.4.5

### 平台 | Platform

Windows, Android

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

The custom prompt requirement option is no longer working. In prior version 1.3.4, I was able to submit custom prompt requirements (names and formal name translations) for text, but that is not working for this latest version. Both OpenAI and Gemini are having the same issue. For OpenAI, I put the custom prompt requirement in the System text box, but the translation does not apply them. For Gemini, I put the custom prompt requirement in the Prompt and Multiple Prompt text boxes, but the return translation does not apply them.  This was working just fine in version 1.3.4.

**Comment by keyboard3** [comment]
1.4.6 fixed

**Comment by galaxypayoff** [comment]
Thank you!
