### ISSUE TITLE
鼠标悬停翻译当前段落功能可以单独使用

### ISSUE THREAD

**Issue by qixing-jk** [immersive-translate/immersive-translate#1609]
### 您希望的更新和改进是什么 | Update or Improve

鼠标悬停翻译当前段落功能可以单独使用，而非需要翻译后才能使用

### 补充说明 | Additional context

有些长网页全部翻译压力较大，有时候只要翻译部分内容就可以了

**Comment by keyboard3** [comment]
目前就是可以单独使用的
