### ISSUE TITLE
在 discord 某些信息无法正确换行

### ISSUE THREAD

**Issue by XHXIAIEIN** [immersive-translate/immersive-translate#161]
## 问题描述

如果由 Bot 发出的长文本信息，翻译时会挤在一堆，无法换行。

拿 Midjourney 频道举例：

https://discord.com/channels/662267976984297473/952771221915840552/1077357436312227961

![Snipaste_2023-02-23_11-41-55](https://user-images.githubusercontent.com/45864744/220817933-6db0f4d0-e701-4b9f-9fd8-11d5d4a9be48.png)

原文都是 `<span>`, `<strong>`, `<a>` 组成

![Snipaste_2023-02-23_11-56-32](https://user-images.githubusercontent.com/45864744/220818338-e3dff19b-5aee-4511-9336-f3f9a1600ff7.png)

**Comment by theowenyoung** [comment]
discord的聊天界面也有点恶心， 我记得把这个加入到 atomic selectors 好像是为了解决另外的一个什么问题来着.. 不过你可以试试改为 selectors?

**Comment by theowenyoung** [comment]
最新版本已正常。

<img width="931" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/54809955-36ca-4eea-9011-5355fbed376b">
