### ISSUE TITLE
reddit上的鼠标悬停ctrl 翻译该段落无法使用

### ISSUE THREAD

**Issue by FEI352** [immersive-translate/immersive-translate#1610]
### 您希望的更新和改进是什么 | Update or Improve

如题https://www.reddit.com/ 这个界面用不了，帖子点进去才能用。
全局翻译倒是正常
插件的版本是1.4.6

**Comment by keyboard3** [comment]
这是因为Reddit在未登录页面结构采用了shadowRoot方案，导致我们无法精确定位dom节点。 已登录之后的页面结构扁平化就能悬停翻译正常了

**Comment by FEI352** [comment]
> 这是因为Reddit在未登录页面结构采用了shadowRoot方案，导致我们无法精确定位dom节点。 已登录之后的页面结构扁平化就能悬停翻译正常了

难受啊，这个确实是reddit的问题。首页的文字还不能被copy

**Comment by keyboard3** [comment]
登录下呗
