### ISSUE TITLE
[Bug]: youtube 无法使用双语字幕 Windows Firefox 扩展

### ISSUE THREAD

**Issue by lost22git** [immersive-translate/immersive-translate#1612]
### 插件版本号 | Version

1.4.6

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![Screenshot 2024-04-06 075203](https://github.com/immersive-translate/immersive-translate/assets/65008815/72b7728a-4a2a-49e0-b032-0a41f388d44d)

![Screenshot 2024-04-06 075203](https://github.com/immersive-translate/immersive-translate/assets/65008815/2a6829f7-7732-47cc-b84d-5fc59631b6c7)

**Comment by lost22git** [comment]
也许是同一个问题 

https://github.com/immersive-translate/immersive-translate/issues/1606

**Comment by keyboard3** [comment]
你是说没有快捷图标开启双语字幕吗？ 1.4.7 已修复快捷图标显示

**Comment by lost22git** [comment]
@keyboard3 我更新了新版本，快捷图标显示了，但是还是无法开启双语

![Screenshot 2024-04-06 075203](https://github.com/immersive-translate/immersive-translate/assets/65008815/448fc5e7-6a5d-43a5-8e64-1983716e496d)

**Comment by keyboard3** [comment]
> @keyboard3 我更新了新版本，快捷图标显示了，但是还是无法开启双语
> 
> ![Screenshot 2024-04-06 075203](https://private-user-images.githubusercontent.com/65008815/320276638-448fc5e7-6a5d-43a5-8e64-1983716e496d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0ODg3NDMsIm5iZiI6MTcxMjQ4ODQ0MywicGF0aCI6Ii82NTAwODgxNS8zMjAyNzY2MzgtNDQ4ZmM1ZTctNmE1ZC00M2E1LThlNjQtMTk4MzcxNmU0OTZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDExMTQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0NzlkMjQxYmNhZTEwZmFiYzUyYTQyMWJiMDYxZTRjNmE2NzU2NjJlNzE5OTljNTZmMWE5NTNkYzNkZGUyMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XpCzF0cvARLTLafhvVQ5goLXxMHg9UfX9tetWS_vPag)

可能是被限流了，试着切换下网络节点试试

**Comment by lost22git** [comment]
@keyboard3 应该不是限流，因为在 chrome 扩展下正常工作

![Screenshot 2024-04-07 192328](https://github.com/immersive-translate/immersive-translate/assets/65008815/9026156e-0bb3-4004-a4b0-b278af27d437)

**Comment by lost22git** [comment]
看了日志，确实是打印网络错误日志

![Screenshot 2024-04-06 075203](https://github.com/immersive-translate/immersive-translate/assets/65008815/655e8a04-4f75-47b0-b62f-e1bc81d3f0c7)

难道 firefox 扩展不走代理网络？我是用 firefox-multi-account container 来设置代理网络的

**Comment by lost22git** [comment]
这个扩展有可以单独设置代理的配置么

**Comment by keyboard3** [comment]
> 这个扩展有可以单独设置代理的配置么

不支持

**Comment by lost22git** [comment]
只能用firefox 全局代理配置了 问题解决了 谢谢
