### ISSUE TITLE
[Bug]: 自定义prompt失效

### ISSUE THREAD

**Issue by jiangying000** [immersive-translate/immersive-translate#1613]
### 插件版本号 | Version

1.4.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

自定义prompt失效，发送的是这个prompt
{
  "model": "gpt-3.5-turbo-0125",
  "temperature": 0,
  "messages": [
    {
      "role": "system",
      "content": "你是一个专业,地道的翻译引擎，你只返回译文，不含任何解释"
    },
    {
      "role": "user",
      "content": "请翻译为 Simplified Chinese Language（避免解释原文）:\n\nSending command..."
    }
  ]
}

**Comment by keyboard3** [comment]
1.4.6 已修复

**Comment by jiangying000** [comment]
看起来是审核比较慢

https://chromewebstore.google.com/detail/immersive-translate-trans/bpoadfkcbjbfhfodiogcnhhhpibjhbnh
![image](https://github.com/immersive-translate/immersive-translate/assets/23182033/9a7cc6ca-3067-4278-b998-bf62e04c0245)

**Comment by keyboard3** [comment]
> 看起来是审核比较慢
> 
> https://chromewebstore.google.com/detail/immersive-translate-trans/bpoadfkcbjbfhfodiogcnhhhpibjhbnh ![image](https://private-user-images.githubusercontent.com/23182033/320184468-9a7cc6ca-3067-4278-b998-bf62e04c0245.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzODIzOTEsIm5iZiI6MTcxMjM4MjA5MSwicGF0aCI6Ii8yMzE4MjAzMy8zMjAxODQ0NjgtOWE3Y2M2Y2EtMzA2Ny00Mjc4LWI5OTgtYmY2MmUwNGMwMjQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA1NDEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MmE0NjBiODA5ZDRkMDE1MmQzMmQ1YjM5Y2U1YWE1MzFjOGJhZjVjNTliZGZkNmY5NjNlMWY0OTdiYjAwMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i_AzWgndRvpfh2Po4Tc7tFXyghRf8Yek51PJktz3Tnc)
是的 还在审核中
