### ISSUE TITLE
快速关闭悬浮球 & 添加默认关闭悬浮球的网站

### ISSUE THREAD

**Issue by rainin9** [immersive-translate/immersive-translate#1614]
### 您希望的更新和改进是什么 | Update or Improve

快速关闭悬浮球

目前在某个网站上关闭悬浮球需要进入扩展设置手动输入网站。希望能够在悬浮球设置中添加一个按键，一键关闭`*.example.com/*`网页上的悬浮球。

添加默认关闭悬浮球的网站
至少中国网站排名前500的应该加进去吧，我今天打开淘宝，悬浮球弹了出来，我人都麻了。

**Comment by theowenyoung** [comment]
这里试过吗？

![CleanShot 2024-04-06 at 19 19 21@2x](https://github.com/immersive-translate/immersive-translate/assets/62473795/e5366100-b94e-4a43-a7e4-752170ea6287)

**Comment by rainin9** [comment]
> Referen
试过，很蠢，添加的是网站的FQDN，我的建议是添加为`*.example.com/*`的形式，比如
百度：https://www.baidu.com/
百度贴吧：https://tieba.baidu.com/

淘宝：https://www.taobao.com/
淘宝商品详情页：https://item.taobao.com/

这些网站需要添加两次

**Comment by warmy1** [comment]
太碍眼了 感觉弄个透明度的设置比较好
