### ISSUE TITLE
发现字幕不能选中复制，希望可以复制字幕

### ISSUE THREAD

**Issue by azumi765** [immersive-translate/immersive-translate#1618]
### 您希望的更新和改进是什么 | Update or Improve

发现字幕不能选中复制，希望可以复制字幕。语言学习有时需要查词之类的不能复制还是有些困扰。

**Comment by theowenyoung** [comment]
请问有没有其他产品的类似交互示例～

**Comment by azumi765** [comment]
> theowenyoung



> > 请问有没有其他产品的类似交互示例～
> 
> 这个扩展好像可以选中字幕的单词来查词（可惜很久不更新了无法使用AI翻译😂），调节双语字幕间距和单独的单字幕开关也蛮实用，建议咱们也安排上😋 https://chromewebstore.google.com/detail/youtube-%E5%8F%8C%E5%AD%97%E5%B9%95/hkbdddpiemdeibjoknnofflfgbgnebcm
> 
> ![屏幕截图 2024-05-18 032350](https://private-user-images.githubusercontent.com/36002202/331710599-91b5cb6c-11c6-467a-8f2c-11850f796f2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NDA4MTIsIm5iZiI6MTcxNjQ0MDUxMiwicGF0aCI6Ii8zNjAwMjIwMi8zMzE3MTA1OTktOTFiNWNiNmMtMTFjNi00NjdhLThmMmMtMTE4NTBmNzk2ZjJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDA1MDE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxZjE3OTVjZWY3MGM4ODE0ZTIzNzJlZGEzYWM5MDgzZTdlNWYzOTkyNzU3NTc3ZWI3OTM5YzE2OWQ2NDRlMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.snaef0Cr-zzPJhfpaxPFu6IF7QiqRWQAYn3XONfqito) ![屏幕截图 2024-05-18 033851](https://private-user-images.githubusercontent.com/36002202/331713677-58f9e4aa-c867-4693-944c-0203aff01cb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NDA4MTIsIm5iZiI6MTcxNjQ0MDUxMiwicGF0aCI6Ii8zNjAwMjIwMi8zMzE3MTM2NzctNThmOWU0YWEtYzg2Ny00NjkzLTk0NGMtMDIwM2FmZjAxY2IyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDA1MDE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyZTE4MmNmYzYwYWMyNjk1NzI1NzcyOGU2MmY0MDAxMGMzMjdkNzJiZmRiNWY2NDhmZTI2ZThjY2M5ZjE1MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BgvxLKAndUQ_w28WiRLgUW2GIGADSDtlhXmlewT-PI4)

@theowenyoung

**Comment by keyboard3** [comment]
![image](https://github.com/user-attachments/assets/e0ff8613-07a0-4f8e-81b0-7f61026d9979)
