### ISSUE TITLE
[Bug]: 無法翻譯vs code網頁版https://vscode.dev/

### ISSUE THREAD

**Issue by argo057** [immersive-translate/immersive-translate#1619]
### 插件版本号 | Version

1.4.7

### 平台 | Platform

Linux

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

vs code用網頁開啟https://vscode.dev/ ，載入原始碼，無法用shift+滑鼠翻譯註釋

### 出现问题的网址 | URL

https://vscode.dev/

### 重现步骤 | To Reproduce

1. edge打開https://vscode.dev/
2. 載入原始碼
3. shift+滑鼠翻譯註釋

**Comment by keyboard3** [comment]
网页vscode中注释每行都是absolute定位，会导致双语重叠，可用性太低
