### ISSUE TITLE
句子中包含表情时，无法翻译

### ISSUE THREAD

**Issue by wellitecho** [immersive-translate/immersive-translate#162]
# 问题描述
当句子中包含表情(emoji)的时候，不会触发翻译。见下图：

![emoji_wont_work](https://user-images.githubusercontent.com/79682683/220834611-70e978bc-5833-4c54-9d5a-527c85bf9c97.png)

# 期望的实现
翻译文字内容，同时原样保持表情(emoji)

**Comment by XHXIAIEIN** [comment]
我这边似乎没有这个问题
![Snipaste_2023-02-23_14-31-30](https://user-images.githubusercontent.com/45864744/220835337-78f07fab-e17c-42dc-a108-ffb5d31315b9.png)


可能是翻译服务的不同？我用的是谷歌翻译

**Comment by wellitecho** [comment]
我刚刚测试了一下，我这边还是会有这个问题。
浏览器：Microsoft Edge Version 110.0.1587.50 (Official build) (64-bit)
插件版本：从 Edge Add-ons页面下载的 Version 0.2.61，以及从github release下载的 version 0.2.66

**Comment by wellitecho** [comment]
昨天我测试的是Whatsapp Web；我注意到你上面的是Telegram Web，所以今天我测试了一下Telegram Web。
测试结果：Telegram Web中功能正常，包含表情的句子可以触发翻译；Whatsapp Web中，包含表情的句子无法触发翻译。所以，可能与Whatsapp Web有关？

**Comment by crocodile2021** [comment]
> 昨天我测试的是Whatsapp Web；我注意到你上面的是Telegram Web，所以今天我测试了一下Telegram Web。 测试结果：Telegram Web中功能正常，包含表情的句子可以触发翻译；Whatsapp Web中，包含表情的句子无法触发翻译。所以，可能与Whatsapp Web有关？

我的whatsapp web测试是正常的，麻烦你再确认一下是不是网络或者翻译引擎的问题哦～
<img width="647" alt="imachen" src="https://user-images.githubusercontent.com/125180289/221168956-3f00ae32-d1b0-42cc-830c-7670dc0c46e9.png">
