### ISSUE TITLE
[Bug]:一段文字中的公式被按照字母拆分成很多行

### ISSUE THREAD

**Issue by GThinkAndWise** [immersive-translate/immersive-translate#1620]
### 插件版本号 | Version

1.4.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

正常显示的一段文字，经过翻译后，公式的字母，被拆分成很多行
![翻译bug](https://github.com/immersive-translate/immersive-translate/assets/132574956/c4be501e-9279-4ebf-8bc8-d14e71a3de48)

### 出现问题的网址 | URL

https://ieeexplore.ieee.org/abstract/document/10066505

### 重现步骤 | To Reproduce

1.输入地址
2.使用微软翻译全文

### 补充说明 | Additional context

![翻译bug](https://github.com/immersive-translate/immersive-translate/assets/132574956/f41cc2d1-2334-4df1-9457-784d4b43208f)

**Comment by GThinkAndWise** [comment]
感谢您的及时回复，我增加了一个网页快照：https://readit.plus/a/Z8OAp/10066505

**Comment by GThinkAndWise** [comment]
感谢您的及时回复，我增加了一个网页快照：https://readit.plus/a/Z8OAp/10066505

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/4cd8abaa-ea7a-4182-98ec-fadda0ec7c9b)
这是因为这篇文章比较特殊，公式排版太乱导致的
