### ISSUE TITLE
twitter 的翻译模版 问题

### ISSUE THREAD

**Issue by wang20150419** [immersive-translate/immersive-translate#1623]
### 您希望的更新和改进是什么 | Update or Improve

使用 2024.04.10 的适配规则，twitter 显示 的 用户名，如果是英文，则进行翻译，导致显示不美观。以前的版本，是不翻译 用户名的。如：BBC News(World) ，这个没有必要翻译。
![2024-04-10_16-37-17](https://github.com/immersive-translate/immersive-translate/assets/12016822/a307e421-a0ec-4582-87ed-43f09d01a918)

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/85971dd9-97ab-4e1d-9163-52505bd64953)
你是不是选择了翻译全部区域，我这里正常的

**Comment by wang20150419** [comment]
> ![image](https://private-user-images.githubusercontent.com/13177744/321179701-85971dd9-97ab-4e1d-9163-52505bd64953.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NDM1MzMsIm5iZiI6MTcxMjc0MzIzMywicGF0aCI6Ii8xMzE3Nzc0NC8zMjExNzk3MDEtODU5NzFkZDktOTdhYi00ZTFkLTkxNjMtNTI1MDViZDY0OTUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDEwMDAzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYWMyYTdlZDYxYjE0YTgyYWQ4NzM0MTM1NmU3MjNkMTg1N2FlNmM3NDQ2ZjgxYTQ5NGE0Y2JmN2JkYzBlYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IJbaNdVCJ0MB3kG9NnMct5pERH3Q7AkKBQ6x5iMEuyc) 你是不是选择了翻译全部区域，我这里正常的

在进阶设置里的 “是否翻译网页所有区域” ，未开启。

**Comment by wang20150419** [comment]
奇怪，来回设置刷新后，现在正常了。
