### ISSUE TITLE
[Bug]: Missed translations in version 1.4.8 but 1.4.7 works fine

### ISSUE THREAD

**Issue by iG8R** [immersive-translate/immersive-translate#1624]
### 插件版本号 | Version

1.4.8

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

After upgrading to version 1.4.8, some sites are missing translation on some parts of the pages.
E.g. https://www.69shu.pro/txt/13823/8196294

### 重现步骤 | To Reproduce

1. Go to https://www.69shu.pro/txt/13823/8196294
2. Try to translate this page

### 补充说明 | Additional context

[ImmersiveTranslate-1.48-partial-translation-Video_2024-04-10_12-02-08.webm](https://github.com/immersive-translate/immersive-translate/assets/11407417/f2b98ff7-c4c4-4a6b-a3ab-82ac0c561562)

**Comment by keyboard3** [comment]
https://dash.immersivetranslate.com/#about Turn on the rule to automatically update the rule, and then try again

**Comment by iG8R** [comment]
Thanks a lot!

**Comment by iG8R** [comment]
The issue with 1.4.8 version still exists on other sites. With 1.4.7 I didn't encounter any such issues(((
E.g. https://www.kdxs.net/completed.html

**Comment by keyboard3** [comment]
1.4.9 and for encountering this issue

**Comment by iG8R** [comment]
Thank you so much!
