### ISSUE TITLE
希望可以增加划词翻译，文本翻译入口简化。

### ISSUE THREAD

**Issue by iHuifeideyu** [immersive-translate/immersive-translate#1626]
### 您希望的更新和改进是什么 | Update or Improve

1、希望可以增加划词翻译，划词选定需要翻译的文字然后显示图标，点击图标翻译。鼠标悬停按快捷键的话感觉就和有道翻译重合了，我如果有有道翻译了为什么还需插件，功能重合了；如果设置成直接翻译的话会造成误翻译。
2、文本翻译入口太繁琐，如果我只需要翻译一小段话需要鼠标点很多入口。希望可以改成点击扩展程序栏应用图标然后输入文字就能直接翻译。

**Comment by keyboard3** [comment]
暂不会支持划词翻译
文本翻译不是主推功能，不会在面板上增加直接翻译的入口，会让沉浸式面板变的复杂
