### ISSUE TITLE
[Bug]: 自定义颜色会经常自己变回去上一次设置的颜色。

### ISSUE THREAD

**Issue by Tang121337** [immersive-translate/immersive-translate#1628]
### 插件版本号 | Version

1.4.8

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

自定义颜色会经常自己变回去上一次设置的颜色。
![image](https://github.com/immersive-translate/immersive-translate/assets/30113090/1dc1db68-b0c3-49f6-9091-5a1efaf99b46)

### 出现问题的网址 | URL

无 任何一个网页都有几率复现此bug

### 重现步骤 | To Reproduce

无 任何一个网页都有几率复现此bug

**Comment by Tang121337** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/30113090/8e446c0f-755e-4d21-b2e5-8571b56e2753)
一刷新又变回去上一次的设置了。

**Comment by flamintune** [comment]
最新版本 1.4.11 已修复该问题，更新一下版本再试试
