### ISSUE TITLE
[Bug]:  OpenAI System Prompt 未替换占位符

### ISSUE THREAD

**Issue by Qixingchen** [immersive-translate/immersive-translate#1629]
### 插件版本号 | Version

1.4.8

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

System Prompt 填入 
`A: {{text}} B: {{from}} c: {{to}}`

点击测试,期待请求内容为
`A: Hello world B: auto c: Simplified Chinese Language`
实际请求内容为
`A: {{text}} B: {{from}} c: {{to}}`

仅影响 System Prompt, 填入 Prompt 的内容替换正确.
![image](https://github.com/immersive-translate/immersive-translate/assets/4182240/d102218a-7d3c-4d1a-bc93-4dfc85e558cf)

![image](https://github.com/immersive-translate/immersive-translate/assets/4182240/9670928c-7439-4c40-8f1d-cde4f1881d5d)

### 出现问题的网址 | URL

All

**Comment by keyboard3** [comment]
1.4.11 已修复
