### ISSUE TITLE
有计划支持via浏览器吗？

### ISSUE THREAD

**Issue by wsadczh** [immersive-translate/immersive-translate#163]

**Comment by theowenyoung** [comment]
这个问题可能需要 via 实现 标准的 油猴接口才行哇。

**Comment by debug16** [comment]
> 这个问题可能需要 via 实现 标准的 油猴接口才行哇。

我问了，他们说已经内置油猴了，但是就是翻译不了

**Comment by liujianchao1995** [comment]
[https://github.com/tuyafeng/Via/issues/1136#issuecomment-1324748947](https://github.com/tuyafeng/Via/issues/1136#issuecomment-1324748947)

**Comment by KnIfER** [comment]
via 应该是基于 https://github.com/wbayer/webview-gm， 我集成了 webviewgm，也是不支持（很多脚本）。这个脚本的报错是，

（我将默认引擎设置为 腾讯交互  `defaultTranslationService = 'transmart';`）

translateCurrentQueue error  Network request fail，包装太深不知哪个url访问不了

**Comment by KnIfER** [comment]
我的新作 —— 无限之书浏览器，通过深度优化 webviewgm，已经基本支持您的翻译脚本。[见知乎 log](https://www.zhihu.com/question/49436744/answers/updated)

**Comment by KnIfER** [comment]
https://wwtm.lanzoum.com/b0a6e796d 密码:gdbw  
安装脚本比较慢，还需要优化一番

**Comment by KnIfER** [comment]
现在海阔、嗅觉、x浏览器等非内核修改的浏览器也支持沉浸翻译了，原理类似。（不过都没有我的完善，细处有坑，坑用户之坑~）

**Comment by theowenyoung** [comment]
2023.10.25 测试，在Via浏览器中 使用 微软翻译，腾讯交互翻译， DeepL，OpenAI 都是正常的。

似乎只有谷歌翻译是不正常的，这里似乎是Via 浏览器特殊做了什么。插件端暂时不能做什么。
