### ISSUE TITLE
PDF无法翻译，检测原文语言全变成中文了[Bug]: 

### ISSUE THREAD

**Issue by GomoXU** [immersive-translate/immersive-translate#1632]
### 插件版本号 | Version

1.4.8

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

PDF无法翻译，原文语言目标语言默认设置为中文且无法修改

**Comment by FattySpring** [comment]
截图看下

**Comment by GomoXU** [comment]
在插件里面恢复默认就恢复正常了，但是登录恢复数据后，bug依旧稳定复现

keyboard3 ***@***.***> 于2024年4月22日周一 20:05写道：

**Comment by GomoXU** [comment]
目前恢复默认后没有复现

Yuanhao Xu ***@***.***> 于2024年4月22日周一 20:37写道：
