### ISSUE TITLE
希望能新增这个地址的视频翻译

### ISSUE THREAD

**Issue by Xuzming-996** [immersive-translate/immersive-translate#1633]
### 您希望的更新和改进是什么 | Update or Improve

视频地址:https://archive.org/details/movies

### 补充说明 | Additional context

该地址下的所有视频，这是一个免费非盈利的资源搜索网站，可以搜索任意想看的视频。麻烦开发人员看看能不能实现啦

**Comment by FattySpring** [comment]
可以提供个有字幕的视频地址吗？

**Comment by Xuzming-996** [comment]
就是需要字幕是吗

**Comment by Xuzming-996** [comment]
> 可以提供个有字幕的视频地址吗？

是需要字幕是吗

**Comment by FattySpring** [comment]
> > 可以提供个有字幕的视频地址吗？
> 
> 是需要字幕是吗

是的，视频需要有字幕才可以翻译
