### ISSUE TITLE
[Bug]: 翻译后，原文中的超链接丢失

### ISSUE THREAD

**Issue by Li7441106** [immersive-translate/immersive-translate#1634]
### 插件版本号 | Version

1.2.4

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 请描述这个Bug | Describe the bug

英语原文中存在超链接，但翻译成中文后，这些链接丢失，无法点击

### 出现问题的网址 | URL

例如https://kubernetes.io/docs和https://prometheus.io/docs

**Comment by mraxu** [comment]
确实是这样

**Comment by keyboard3** [comment]
暂不支持 参考 #871
