### ISSUE TITLE
[Bug]: 设置了deepl密钥，但是翻译一次之后就需要重新在设置里填写密钥

### ISSUE THREAD

**Issue by henghenghahaha** [immersive-translate/immersive-translate#1637]
### 插件版本号 | Version

1.4.9

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

先在设置里设置好deepl密钥之后，然后目标网页可以翻译，再翻译另一个网页时，就显示无法翻译，还得去设置里重新输入密钥

https://github.com/immersive-translate/immersive-translate/assets/57128448/f68c6d95-1cbb-48b8-b81c-52cdddd68207

### 出现问题的网址 | URL

几乎所以情况下

**Comment by keyboard3** [comment]
新版没复现，你升级下版本看看

**Comment by henghenghahaha** [comment]
Chrome扩展程序商店还是1.4.9
![屏幕截图 2024-04-18 105914](https://github.com/immersive-translate/immersive-translate/assets/57128448/6e3e9416-163b-4196-b948-ab1f81138812)

**Comment by keyboard3** [comment]
那你在能翻译的原网页，多次刷新之后还能翻译吗？

**Comment by henghenghahaha** [comment]
有点离谱，刚录视频还能复现bug，现在我尝试了刷新页面，开一个别的标签页，关了浏览器重开都没问题了

**Comment by henghenghahaha** [comment]
打扰了
