### ISSUE TITLE
翻译的上下文问题

### ISSUE THREAD

**Issue by benjaminyin01** [immersive-translate/immersive-translate#164]
在尤其是科技文档的翻译中，有些单词有专有翻译意思。
但是看本插件的翻译，是一个段落一个段落翻译，这会造成翻译程序没有足够的上下文参考，比如有些技术资料的标题就是一个单词，本插件比如使用Google翻译的结果就不准确。
而直接使用Google翻译，就能翻译出专业术语，这可能是因为Google翻译参考了整篇文章的上下文。

本插件也应该放弃逐段路翻译的模式，改为将整个文章都发送到云翻译程序，再把翻译结果分割成段落插入原文中。

**Comment by theowenyoung** [comment]
这个恐怕短时间内无法做到，没有接口支持同时发送这么多的文本。

这个扩展也不是每一段都分开的～而是合并多个段落一起发送的。 每次最多1800个字符。

**Comment by Andy-AO** [comment]
> 这个恐怕短时间内无法做到，没有接口支持同时发送这么多的文本。
> 
> 这个扩展也不是每一段都分开的～而是合并多个段落一起发送的。 每次最多1800个字符。

书伴开发的Calibre电子书翻译器 - v2.2.0，其中有个Edge翻译，测试后发现支持18000字，而不出只是1800，导致翻译速度超快，很长的电子书分成十几个段落，几分钟就完成了。
