### ISSUE TITLE
[Bug]: movie-web可被user config 控制字幕樣式，但字幕上移至中間

### ISSUE THREAD

**Issue by Benlee1129** [immersive-translate/immersive-translate#1642]
### 插件版本号 | Version

1.4.11

### 平台 | Platform

Android

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

請問如何設置字幕的margin-bottom？讓字幕放置於最下緣。

![Screenshot_20240419-202049](https://github.com/immersive-translate/immersive-translate/assets/103996456/bb48af90-5075-4370-bfa6-3eb8d4b7a72a)

**Comment by FattySpring** [comment]
可以发下页面地址吗？

**Comment by Benlee1129** [comment]
應該不是特定網址的問題，我認為是movie-web 的margin-bottom 設定的太高了。
immersive translate 可以針對特定網址設定margin bottom 嗎？
我想設負值，把字幕下移。是否可行呢？

FattySpring ***@***.***> 於 2024年4月22日 週一 17:22 寫道：

**Comment by Benlee1129** [comment]
我發現在Fmovie 或 movie-web 二個平台中都會使用immersive translate 的YouTube 字型設定，這樣很容易就可以更改顏色和大小。
另外，可以在視頻框中自由移動字幕框的高低位置，這樣也很好。不過，字幕框下限位置會受到平台margin bottom default值的影響，在movie web中會懸在下方1/3位置。

**Comment by FattySpring** [comment]
无法复现

**Comment by Benlee1129** [comment]
您好，

我已經找到解決方案！
這個問題是由於預設的
 immersive-translate-caption-window {bottom: 80px} 所造成。
在桌面版中bottom 80px的設計，可以表現不錯的效果。但是，在手機版中 bottom 80px會讓字幕懸在半空中。

請問，我如何在 開發者設定的Edit Injected CSS中增加設定，讓 bottom 為 0px 呢？
另外， .imt-caption-window {margin-bottom: 30px}，也可用來改變bottom 位置。

雖然這個討論已經關閉，但我希望問題能得到解決。

keyboard3 ***@***.***> 於 2024年5月28日 週二 14:33 寫道：
