### ISSUE TITLE
[Bug]: FAQ of PDF Data Pack is missing

### ISSUE THREAD

**Issue by favoyang** [immersive-translate/immersive-translate#1643]
### 插件版本号 | Version

any

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

The FAQ of the PDF Data Pack is missing the description.

![image](https://github.com/immersive-translate/immersive-translate/assets/125390/20d7feba-55b4-475b-921a-93dd37fddf00)

### 出现问题的网址 | URL

https://immersivetranslate.com/en/topup/?type=pdf_pro&return_url=https%3A%2F%2Fapp.immersivetranslate.com%2Fpdf-pro%2F

### 重现步骤 | To Reproduce

1. Open the page
2. Locate to the FAQ section.

### 补充说明 | Additional context

N/a

**Comment by theowenyoung** [comment]
Thank you very much.

Fixed it.

All will take effect within 10 minutes.
