### ISSUE TITLE
调用 Claude 3 的 API 可以支持自定义 API 接口吗？一直报错

### ISSUE THREAD

**Issue by QYworld** [immersive-translate/immersive-translate#1644]
### 您希望的更新和改进是什么 | Update or Improve

使用 Openrouter 和 aihubmix 的自定义API接口，都无法使用 Claude 3
请问是目前还不支持，还是我的设置问题？

![CleanShot 2024-04-21 at 06 50 20@2x](https://github.com/immersive-translate/immersive-translate/assets/1226169/aa44c790-3fa8-430d-bf69-0e3e03b11487)

**Comment by theowenyoung** [comment]
试试用 openai，然后自定义model用 claude

**Comment by theowenyoung** [comment]
他们的接口可能适配的是 openai 的，而不是 claude 的。

**Comment by QYworld** [comment]
确实是这样，可以用了，感谢

> 试试用 openai，然后自定义model用 claude
