### ISSUE TITLE
[Bug]: iCloud-mail 页面，翻译之后无法滚动到最底部

### ISSUE THREAD

**Issue by balabalabalading** [immersive-translate/immersive-translate#1645]
### 插件版本号 | Version

1.4.9

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome, Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

iCloud-mail 页面，翻译之后无法滚动到最底部：
![iShot_2024-04-22_09 48 20](https://github.com/immersive-translate/immersive-translate/assets/98296706/8e03b1a7-1d21-44e9-82a3-7520412a9128)

### 出现问题的网址 | URL

https://www.icloud.com.cn/mail/

### 重现步骤 | To Reproduce

1.打开邮件；
2.翻译网页。

**Comment by keyboard3** [comment]
可以生成一个快照链接协助我们定位问题
<img width="352" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/13177744/489fa027-e8ca-4cc9-8275-4c3189adcc1d">

**Comment by balabalabalading** [comment]
![iShot_2024-04-22_19 10 21](https://github.com/immersive-translate/immersive-translate/assets/98296706/1e11bcde-74dc-489c-9e93-05895d8427f9)
网页快照的页面一直在转圈

**Comment by keyboard3** [comment]
嗯 这应该是iCloud页面限制高度了，你可以暂时通过仅译文显示来看到完整内容

<img width="362" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/13177744/3a0b9972-e2b8-4bd0-a45c-5c9b5de8498d">

**Comment by keyboard3** [comment]
这样你把你有问题的邮件转发到 keyboard3@icloud.com 这个邮箱里吧

**Comment by keyboard3** [comment]
打开这个地址 https://dash.immersivetranslate.com/#about 自动更新规则，然后重新去试下，内容就可以滚动了

**Comment by balabalabalading** [comment]
牛的 老哥

**Comment by balabalabalading** [comment]
这个问题又出现了，无法翻译正文的内容。
![4 C4 O](https://github.com/user-attachments/assets/17e9d791-c423-4c33-a7e3-c1e71d1d7437)

**Comment by keyboard3** [comment]
![Image](https://github.com/user-attachments/assets/e1701456-db3a-430a-bb41-3a5c7960d150)
我这里翻译正常？
