### ISSUE TITLE
[Bug]: 使用DeepLX (Alpha)，出现少翻漏翻

### ISSUE THREAD

**Issue by stan1233** [immersive-translate/immersive-translate#1646]
### 插件版本号 | Version

1.2.3

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

翻译会偷懒，使用的是DeepLX (Alpha)
![image](https://github.com/immersive-translate/immersive-translate/assets/20401741/ea2b79b9-c224-4707-8af1-cfab506349da)

**Comment by keyboard3** [comment]
这种事 deepl 自身的问题
