### ISSUE TITLE
指定网址的自定义颜色无效

### ISSUE THREAD

**Issue by photkey** [immersive-translate/immersive-translate#165]
如下图：
![Snipaste_2023-02-24_16-18-01](https://user-images.githubusercontent.com/60434581/221128711-a584933f-a0f8-4b8e-ae3c-8720a6c302ee.png)

-------------------
另外，我想除了简体/繁体中文外，其它的全部都自动翻译，因为偶尔蹦出来一个不认识的语言，它不能自动翻译，尤其是在看tiktok的评论时，经常各个国家的语言都有。目前的设置有点啰嗦呀，如下图：
![Snipaste_2023-02-24_16-18-57](https://user-images.githubusercontent.com/60434581/221129059-b90f78aa-77bc-47fb-82f2-7023d1c279ca.png)

**Comment by theowenyoung** [comment]
第一个是bug，下个版本修复～

第二个... 额.. 也许新增一个  all except target and never translate language?

**Comment by theowenyoung** [comment]
可以了，最新版本 这两个都支持了～  永远翻译的语言里，最后一项有个： 全部
