### ISSUE TITLE
[Bug]: 疑似是调用 Claude3 API 的 bug，如果不是的话，可能是什么问题导致？

### ISSUE THREAD

**Issue by QYworld** [immersive-translate/immersive-translate#1652]
### 插件版本号 | Version

1.4.11

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

设置了 Openrouter 的 Claude 3  haiku 的 API，也提示测试成功，但用其翻译时完全不起作用，请问这是设置问题，还是 bug？
换成 Openrouter 的 OpenAI GPT3.5 之类 API，都能正常翻译。

![CleanShot 2024-04-23 at 02 48 17@2x](https://github.com/immersive-translate/immersive-translate/assets/1226169/f730fa0f-cb4f-4f8c-b1c7-88b00b4d6857)

**Comment by keyboard3** [comment]
抓包下网络请求  右键审查元素/检查->网络。看下api 的响应
