### ISSUE TITLE
[Bug]: 文本量较大的文献网站卡顿的问题反馈

### ISSUE THREAD

**Issue by Kitkim160** [immersive-translate/immersive-translate#1653]
### 插件版本号 | Version

0.5.6.1/1.4.1.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension, 油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

在翻译文本量较大的文献网站的时候，会出现系统级别的卡顿，之前有学过一段时间的编程，在考虑是否是内存泄漏、单线程等问题导致的系统级别的卡顿。这可能需要开发人员排查一下。 而且新版本的插件（1.4.1.1）会相较老版本（0.5.6.1）卡顿更明显，新版本卡顿发生所需要的文本量变小了。平时在看文献过程中卡顿十分难受，尤其是在用二合一小板子看的时候。这类卡顿问题在更换电脑（大奶）后仍然存在，与电脑配置无关。

这类问题通常出现在需要翻译的网页内容十分巨大的情况下，例如一些综述文章 
（比如https://pubs.acs.org/doi/full/10.1021/acs.chemrev.3c00159  https://doi.org/10.1016/j.cej.2018.01.069 需要校外访问访问）

望插件越来越好

### 出现问题的网址 | URL

https://pubs.acs.org/doi/full/10.1021/acs.chemrev.3c00159 

### 重现步骤 | To Reproduce

分别用油猴的0.5.6.1和1.4.11版本实验均可以重现，没有设置自动翻译至网页底部

**Comment by NevCcL** [comment]
同样被这个问题折磨了很久，尤其是中等以上规模的维基百科上，复现率接近百分百。
补充：
1、反复排查后确认和电脑配置无关、和Chrome的设置无关、和win11性能模式无关
2、此问题同样能在chrome自带的全局翻译上出现

**Comment by flamintune** [comment]
最新版本 1.5.6 大幅优化了大网页，ePub 制作，字幕文件的翻译性能，上面的几个网页经测试，几乎都不会出现翻译卡顿的情况，欢迎及时更新插件

https://immersivetranslate.com/docs/CHANGELOG/?force=1#156
