### ISSUE TITLE
DeeplX doesn't support Authorization/Bearer token

### ISSUE THREAD

**Issue by littleblack111** [immersive-translate/immersive-translate#1658]
### 您希望的更新和改进是什么 | Update or Improve

Add Authorization/Bearer token support for DeeplX

**Comment by theowenyoung** [comment]
> https://deeplx.owo.network/endpoints/free.html

Please note that if you are unable to pass Authorization, you can also use URL Params instead. For example, `/translate?token=your_access_token`
