### ISSUE TITLE
協助繁體中文翻譯

### ISSUE THREAD

**Issue by StarsShine11904** [immersive-translate/immersive-translate#1659]
### 您希望的更新和改进是什么 | Update or Improve

我發現你們的繁體中文似乎怪怪的，不知是否能協助優化翻譯，我是台灣的使用者

### 补充说明 | Additional context

繁體化有是有，但是有些翻譯不整或用詞不正確，想說能不能協助你們將翻譯當地化

**Comment by keyboard3** [comment]
你指的是那一塊？網站，外掛程式介面語言還是網頁翻譯結果？

**Comment by keyboard3** [comment]
“說明網站那一部分” ？ 具体是指?

**Comment by keyboard3** [comment]
感謝反饋，我們會在後續反覆運算中調整

**Comment by keyboard3** [comment]
> 但是多少希望可以幫你們修正不正確的翻譯 還是說我將不正確的翻譯放在這裡，直接提交錯誤翻譯位置？


也可以在這個帖子中。 我們可以先內部糾正下，有這塊的專業同事

**Comment by keyboard3** [comment]
好的 我們將安排工程師調整

**Comment by keyboard3** [comment]
感謝你幫忙修改！！！ 方便留個email嗎？我們打算送你pro月會員體驗

**Comment by keyboard3** [comment]
> 電子郵件-->[yz17423@gmail.com](mailto:yz17423@gmail.com)
> 
> 說明文件的話我可能有空會慢慢翻(如果有提供修改功能的話，因為字串真的太多了)

好的，我們內部討論下，看怎麼協作合適

**Comment by keyboard3** [comment]
這些調整將在下一版

**Comment by keyboard3** [comment]
好的，非常感謝

**Comment by theowenyoung** [comment]
@StarsShine11904 谢谢，已经转给相关团队成员。

**Comment by keyboard3** [comment]
插件的介紹內容需要等待下次發版再修改

**Comment by keyboard3** [comment]
我创建了 https://github.com/immersive-translate/internationalization ，可以邀请你到这个项目中，然后开分支编辑 official/i18n/zh-TW/docusaurus-plugin-content-docs/current 下的 usage 文件即可，然后提交 pr 请求给 main 分支。我们合并之后，会同步到我们的项目中

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/6f3245c5-5490-42b2-af9a-2d88d1f4aaf2)
已在页面上支持快捷进入github入口

**Comment by keyboard3** [comment]
> 可是我已經從原本的翻譯庫裡面Fork出來一個了欸🤔

没关系，就是告诉你这里有个入口

**Comment by keyboard3** [comment]
暂无反馈 暂时关闭这个issue

**Comment by PeterDaveHello** [comment]
Hi @keyboard3 @StarsShine11904 @aseaday,

因為看到這邊的討論，另外也確認目前繁體中文網站、文件目前沒有針對這邊討論到的議題遲需更新，我花了一點時間整理並送了 https://github.com/immersive-translate/i18ns/pull/21 ，先求第一版做大幅度有效的改善，後續可以再陸續精修甚至重翻來達到更好的效果，再麻煩看看是否會有幫助，謝謝

**Comment by keyboard3** [comment]
> Hi @keyboard3 @StarsShine11904 @aseaday,
> 
> 因為看到這邊的討論，另外也確認目前繁體中文網站、文件目前沒有針對這邊討論到的議題遲需更新，我花了一點時間整理並送了 [immersive-translate/i18ns#21](https://github.com/immersive-translate/i18ns/pull/21) ，先求第一版做大幅度有效的改善，後續可以再陸續精修甚至重翻來達到更好的效果，再麻煩看看是否會有幫助，謝謝

好的 我稍后check下

**Comment by PeterDaveHello** [comment]
Hi @keyboard3,

有看到合併了，感謝，想另外請教 https://immersivetranslate.com/docs/usage/ 右上角的「繁体」中文有辦法改成「繁體」中文嗎？可能是哪邊漏改了但沒找到，對了，我大概半個月前有在 X(Twitter) 發訊息給 @immersivetran 這個帳號詢問協助翻譯的事情，但沒收到回覆、不確定是否是官方帳號以及可以用來討論的管道？謝謝

**Comment by keyboard3** [comment]
> Hi @keyboard3,
> 
> 有看到合併了，感謝，想另外請教 https://immersivetranslate.com/docs/usage/ 右上角的「繁体」中文有辦法改成「繁體」中文嗎？可能是哪邊漏改了但沒找到，對了，我大概半個月前有在 X(Twitter) 發訊息給 @immersivetran 這個帳號詢問協助翻譯的事情，但沒收到回覆、不確定是否是官方帳號以及可以用來討論的管道？謝謝

这个是网站框架自身的语言文本，这个我看下有没有地方修改

**Comment by keyboard3** [comment]
> > Hi @keyboard3,
> > 有看到合併了，感謝，想另外請教 https://immersivetranslate.com/docs/usage/ 右上角的「繁体」中文有辦法改成「繁體」中文嗎？可能是哪邊漏改了但沒找到，對了，我大概半個月前有在 X(Twitter) 發訊息給 @immersivetran 這個帳號詢問協助翻譯的事情，但沒收到回覆、不確定是否是官方帳號以及可以用來討論的管道？謝謝
> 
> 这个是网站框架自身的语言文本，这个我看下有没有地方修改

已修改。后面讨论 在i18ns 仓库里讨论，该帖子已经close了
