### ISSUE TITLE
[Bug]: 文件翻译页面显示不正常

### ISSUE THREAD

**Issue by despairTK** [immersive-translate/immersive-translate#1660]
### 插件版本号 | Version

1.4.11

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

字幕文件翻译界面显示不正常。一开始还正常，突然变成了这样。换成谷歌浏览器也是一样的显示错误。
![QQ截图20240425170807](https://github.com/immersive-translate/immersive-translate/assets/111871110/0a7dcd7c-4909-4ccd-ad1d-7ae9ee1ea561)

**Comment by despairTK** [comment]
> 你好，我试了几个版本 windows 下 edge 和 chrome 都正常，没有复现

我在微信群联系了管理员，找到了问题，页面的文本内容都与背景色一致了，所以看上去像是消失了。只要在当前页面实施全选操作，文本内容就会显示出来。但是依然不知道是什么原因造成的这样。。。管理员也不知道如何恢复。

**Comment by despairTK** [comment]
![QQ截图20240425215148](https://github.com/immersive-translate/immersive-translate/assets/111871110/6b291e4a-edc9-4488-88a5-caafb911f2a4)
![QQ截图20240425215203](https://github.com/immersive-translate/immersive-translate/assets/111871110/244fa4fa-941d-451c-9e20-152a910c94e6)

BUG图示例

**Comment by TaoLoading** [comment]
问题已修复，是浏览器样式覆盖导致的，清除缓存重试下
