### ISSUE TITLE
.ass文件翻译问题...

### ISSUE THREAD

**Issue by hrk1205** [immersive-translate/immersive-translate#1661]
### 您希望的更新和改进是什么 | Update or Improve

1、.ass文件是支持字幕格式的，比如一条字幕是这样“{\pos(640,639.846)} 你好 ” 前面的{}内容是表示高度，然后这个文件翻译后，这个格式就会不见，希望能改进一下，把翻译好的字幕，保留字幕的相应格式...
2、我翻译.ass文件的时候，发现页面是全白的...（下图）
<img width="1322" alt="截屏2024-04-26 10 46 27" src="https://github.com/immersive-translate/immersive-translate/assets/53370978/5a89dd23-3404-4af5-a2b1-a8241bf5196b">
全选文本后，可以看到是有文字的..下图）
<img width="1247" alt="截屏2024-04-26 10 46 34" src="https://github.com/immersive-translate/immersive-translate/assets/53370978/c0814539-6e40-43d8-864e-064609969899">

**Comment by TaoLoading** [comment]
问题已修复，是浏览器样式覆盖导致的，清除缓存重试下
