### ISSUE TITLE
[Bug]: 鼠标悬停翻译获取焦点

### ISSUE THREAD

**Issue by lingfengyu-dreaming** [immersive-translate/immersive-translate#1663]
### 插件版本号 | Version

1.4.11

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在edge上，鼠标悬停翻译必须先点击要翻译的段落，然后再按着`alt`键才能触发。
找了之前的issue，看到说修改了焦点来修复`alt-tab`切换窗口的快捷键问题，不知道是否和这个有关。

### 出现问题的网址 | URL

https://keepass.info/plugins.html

### 补充说明 | Additional context

插件在这种多文本网页上会造成大量卡顿啊，减小`直接翻译页面前多少个字符，而无需等待滚动到可视区域`和切换`Loading样式`到静态文本也没有好转。

**Comment by FattySpring** [comment]
在切换标签页后，需要先点击页面以获取焦点，否则无法识别鼠标所处的段落。

**Comment by lingfengyu-dreaming** [comment]
在一个页面内先翻译了一个段落，再悬停到另一个段落也会这样，需要先点一下

**Comment by theowenyoung** [comment]
是只有这个网页会这样吗？还是所有网页都这样？ 我这里是正常的，没法复现。 

试试换其他快捷键？

**Comment by keyboard3** [comment]
1.5.6 之后对大文本网页翻译做了优化
