### ISSUE TITLE
[Bug]: 网址翻译成了www.example.com

### ISSUE THREAD

**Issue by seigwen** [immersive-translate/immersive-translate#1664]
### 插件版本号 | Version

1.4.11

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

原文里的普通网址在译文里变成了www.example.com

### 出现问题的网址 | URL

https://www.producthunt.com/posts/webrend

### 重现步骤 | To Reproduce

 打开https://www.producthunt.com/posts/webrend并腾讯交互翻译

**Comment by keyboard3** [comment]
没看到你说的 www.example.com 的情况呀

**Comment by seigwen** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/38581695/aa6120ba-7aca-4283-8c18-ba3c76d48736)

**Comment by keyboard3** [comment]
腾讯交互没能复现。如果你还是遇到，建议切换其他翻译服务
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/69979997-4e10-414f-a7f9-212ab922ca86)
