### ISSUE TITLE
[Bug]: safari浏览器无法安装

### ISSUE THREAD

**Issue by XiaoxxWz** [immersive-translate/immersive-translate#1665]
### 插件版本号 | Version

1.4.12

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

点击“启用沉浸式翻译扩展”没有反应，扩展无该项内容

**Comment by keyboard3** [comment]
https://immersivetranslate.com/docs/faq/#%E5%9C%A8-ios-%E8%AE%BE%E5%A4%87%E4%B8%8A%E6%97%A0%E6%B3%95%E5%90%AF%E7%94%A8%E6%89%A9%E5%B1%95  试试这里

**Comment by XiaoxxWz** [comment]
按常见问题的操作尝试后仍旧无法安装，原本安装成功的有低版本，在发布了新版本更新后自动从浏览器中不见，重新下载安装时出现点击安装无反应的情况

**Comment by XiaoxxWz** [comment]
安装前后系统版本未升级过，当前macos版本是12.7.4

**Comment by XiaoxxWz** [comment]
https://github.com/immersive-translate/immersive-translate/assets/150432908/c0d4758d-55d1-4f79-bf54-b98ce0de3fd3
![1](https://github.com/immersive-translate/immersive-translate/assets/150432908/9c75466a-266b-448f-b483-3f8c69d7a5bd)

macos版本比较低，一直用的也挺久了

**Comment by keyboard3** [comment]
啊 为啥没有安装的扩展。 这个跟插件本身关系不大。 不行的话用Chrome吧。或者试试其他扩展能不能装，装个油猴扩展呢
