### ISSUE TITLE
[Bug]: 油管双语字幕视频重载问题

### ISSUE THREAD

**Issue by MarvelousTune** [immersive-translate/immersive-translate#1666]
### 插件版本号 | Version

1.4.11

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

网络不好重载视频或者拖动进度条到未缓冲部分都会导致双语字幕失效
只能重新进视频才恢复

**Comment by FattySpring** [comment]
是否在[设置](https://dash.immersivetranslate.com/#subtitle )中开启了【使用沉浸式翻译来翻译 Youtube 字幕】选项

**Comment by MarvelousTune** [comment]
> 是否在[设置](https://dash.immersivetranslate.com/#subtitle)中开启了【使用沉浸式翻译来翻译 Youtube 字幕】选项

我开的是始终开起双语字幕

**Comment by FattySpring** [comment]
设置页截图看下？字幕的翻译也依赖网络，网络不好的情况下可能会翻译失败，无法显示双语字幕

**Comment by MarvelousTune** [comment]
> 设置页截图看下？字幕的翻译也依赖网络，网络不好的情况下可能会翻译失败，无法显示双语字幕

![Snipaste_2024-05-01_09-33-13](https://github.com/immersive-translate/immersive-translate/assets/40261598/7a4acfd0-d1a1-42bb-996a-0c7c518f0d26)
![Snipaste_2024-05-01_09-33-24](https://github.com/immersive-translate/immersive-translate/assets/40261598/4562162c-26f6-42c0-819b-143c76095ec3)
![Snipaste_2024-05-01_09-33-36](https://github.com/immersive-translate/immersive-translate/assets/40261598/aff0ff5b-12a5-41ae-bc95-9d9e87f54327)

**Comment by FattySpring** [comment]
无法重新该问题，方便录制下屏幕吗

**Comment by MarvelousTune** [comment]
> 无法重新该问题，方便录制下屏幕吗

我可能表达有点不清楚 是网络问题导致画质自动掉了 和这个录屏里手动调画质是一样的结果

https://github.com/immersive-translate/immersive-translate/assets/40261598/7ebc0591-67da-4655-bc7d-06e99f055983

**Comment by FattySpring** [comment]
在 [1.5.4](https://immersivetranslate.com/docs/CHANGELOG/#154) 已修复
