### ISSUE TITLE
[Bug]: YouTube个别视频双语字幕的字号会自动变的特别小

### ISSUE THREAD

**Issue by lianwensheng** [immersive-translate/immersive-translate#1667]
### 插件版本号 | Version

1.4.12

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

YouTube个别视频双语字幕的字号会自动变的特别小
![屏幕截图 2024-04-26 222853](https://github.com/immersive-translate/immersive-translate/assets/36002202/a80e4b29-e8b0-4764-9a19-403c1ec00f50)

### 出现问题的网址 | URL

https://www.youtube.com/watch?v=Gi_t3v53XRU

**Comment by FattySpring** [comment]
字幕大小会根据播放器自适应，过大可能超出播放器的范围。

**Comment by theowenyoung** [comment]
确实，官方的视频字幕似乎是适配整个屏幕的：

https://www.youtube.com/watch?v=Gi_t3v53XRU

![CleanShot 2024-04-29 at 01 07 30@2x](https://github.com/immersive-translate/immersive-translate/assets/62473795/bd1999e5-1436-4f3d-a3e7-ab678a729da7)
