### ISSUE TITLE
MDN左边栏的译文排版很糟糕

### ISSUE THREAD

**Issue by nothingshiru** [immersive-translate/immersive-translate#1668]
### 您希望的更新和改进是什么 | Update or Improve

https://developer.mozilla.org/en-US/docs/Learn
![屏幕截图 2024-04-26 221334](https://github.com/immersive-translate/immersive-translate/assets/79258245/eaff64e8-72d6-4064-9acf-52c3d1522741)

### 补充说明 | Additional context

在像左右边栏这种空间有限的目录里，常常一行放不完原文+译文，不得不换行。既然得换行，相比于把译文接在原文后面，另起一行放译文或许更好？那样译文就能与原文统一左对齐

**Comment by keyboard3** [comment]
感谢反馈，由于原站点这部分元素设置了flex、inline-flex，导致无法强行换行。 下一版针对这种情况，将修复这种译文和原文不对齐的情况

**Comment by keyboard3** [comment]
这个没办法，首先于原网站的排版，无法强行换行
