### ISSUE TITLE
[Bug]: OpenAI翻译+ollama+llama3 翻译结果都一样

### ISSUE THREAD

**Issue by jopbrown** [immersive-translate/immersive-translate#1669]
2024/04/28 问题更新
[#issuecomment-2081486827](#issuecomment-2081486827)

----------------------------------

### 插件版本号 | Version

1.4.11

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

觉得OpenAI翻得不好，想要让他重翻。
清除快取后再次翻译，还是跑出原来的翻译。

### 重现步骤 | To Reproduce

1. 先翻译一次
2. 按下`关于`页面的`清除快取`
3. 刷新想要翻译的网页
4. 再次按下翻译

### 补充说明 | Additional context

从OpenAI的后台来看，确实是有调用API，跑出来的结果也不同。
但最终页面上显示的翻译还是第一次的。
合理怀疑清除快取失效。

**Comment by keyboard3** [comment]
我这边按照你的步骤，没能复现，内容变化更新了。 那你试试在关于页面禁用缓存生效吗？或者重启下浏览器呢

**Comment by jopbrown** [comment]
> 我这边按照你的步骤，没能复现，内容变化更新了。 那你试试在关于页面禁用缓存生效吗？或者重启下浏览器呢

我找到原因了，确实不是缓存的问题。

这个问题使用官方(OpenAI)的服務**不会**发生。
我这边其实是用`ollama+llama3`。

原因是沉浸式扩展在调用`v1/chat/completions`时会加上`"temperature": 0`
OpenAI 的[API](https://platform.openai.com/docs/api-reference/chat/create#chat-create-temperature)并没有定义`temperature` 为 `0`的意义。
但[社群](https://community.openai.com/t/why-the-api-output-is-inconsistent-even-after-the-temperature-is-set-to-0/329541)有人认为`temperature` 为 0 时 OpenAI 会动态调整。
所以出来的结果还是会不一样。

但`ollama+llama3`的`temperature` 为 0 就真的是 0 。
导致每次出来的结果都是一样的。
因为官方确实没有定义，所以也不能说是`ollama`的问题。

沉浸式扩展中， `temperature` 、 `top_k` 和 `top_p` 这3个关键参数能开放让使用者自己设吗？

**Comment by theowenyoung** [comment]
这个是 feature, 不是 Bug 哈，目的就是为了让 模型能更精准的翻译，而不是随意发挥。

目前可以在开发者设置里的 full user config 自定义，示例：

```json
  {
  
  "translationServices": {
    "openai": {
      "APIKEY": "xxx",
      "assistantId": "custom",
      "model": "gpt-3.5-turbo",
      "provider": "custom",
      "temperature": 0.3
    }
  }  
```

**Comment by letterk** [comment]
> ```json
>   {
>   
>   "translationServices": {
>     "openai": {
>       "APIKEY": "xxx",
>       "assistantId": "custom",
>       "model": "gpt-3.5-turbo",
>       "provider": "custom",
>       "temperature": 0.3
>     }
>   }  
> ```

自定义配置还支持别的采样参数吗, 比如top_p

**Comment by theowenyoung** [comment]
目前不支持。
