### ISSUE TITLE
neat reader 网站适配

### ISSUE THREAD

**Issue by yaohappiness** [immersive-translate/immersive-translate#167]
<https://neat-reader.com> / <https://net-reader.cn> 是一个 epub 和 pdf 在线阅读网站，给我的使用体验还是相当不错的。

immersive translate 可以很好地翻译网站的 epub 文件。但是 pdf 文件有问题，翻译错位、内容对不上段落、翻译的字体是白色的。

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/38402135/221347330-b233ebe9-f47b-49d9-99f1-9d3e5a88debc.png">

**Comment by theowenyoung** [comment]
我好像打不开这两个网站.

<img width="990" alt="Screenshot 2023-02-25 at 23 03 50" src="https://user-images.githubusercontent.com/62473795/221364190-68c00d54-dc75-4f56-99f1-015c772631fc.png">


PDF文件一般很难适配的，除非他转化后的html是重新排列过的html，不然一般都是绝对定位的元素，很难自动适配的.

**Comment by yaohappiness** [comment]
<https://www.neat-reader.com> / <https://www.neat-reader.cn> 这网站不加 `www` 还访问不了……

![image](https://user-images.githubusercontent.com/38402135/221509732-71de8e33-b7bf-48a2-b228-15b40cd0c8bb.png)

这种情况应该是很难适配
