### ISSUE TITLE
在线对比翻译服务改进 把对比翻译的输入文本框始终显示在左侧 不会因为下滑页面而被遮挡

### ISSUE THREAD

**Issue by SF-NX** [immersive-translate/immersive-translate#1671]
### 您希望的更新和改进是什么 | Update or Improve

![image](https://github.com/immersive-translate/immersive-translate/assets/89298437/2735124c-ed79-4e04-b2b6-4b220c70122f)
把对比翻译的输入文本框始终显示在左侧 不会因为下滑页面而被遮挡
![image](https://github.com/immersive-translate/immersive-translate/assets/89298437/f46d52e9-5005-4b94-9183-b62b12430d67)

**Comment by flamintune** [comment]
已实现固定左侧输入文本框
