### ISSUE TITLE
划词翻译

### ISSUE THREAD

**Issue by shanyurichen** [immersive-translate/immersive-translate#1673]
### 您希望的更新和改进是什么 | Update or Improve

可否增加划词翻译的功能，有些页面大部分是中文，只有小部分英语。整页翻译和鼠标悬停都无法翻译小段英文。个人觉得划词翻译更符合直觉。

**Comment by zhf521** [comment]
我也希望增加一个划词翻译的功能，我想在阅读文档时，遇到不会的单词可以划词翻译，用来提高英语水平。我发现在开启插件后，我会因为有了整段话的译文而不再想去阅读外文的内容。

**Comment by keyboard3** [comment]
感谢反馈，划词翻译确实不在我们的设计理念中，目前暂无计划增加此功能。推荐其他同类插件作为补充
