### ISSUE TITLE
希望添加用于调节「视频字幕字重」的选项

### ISSUE THREAD

**Issue by Thomas-Harrell** [immersive-translate/immersive-translate#1675]
### 您希望的更新和改进是什么 | Update or Improve

视频字幕 -> 在线视频双语字幕样式设置 -> 文字字重

**Comment by theowenyoung** [comment]
感谢建议，将在下个版本 1.5.13 支持

**Comment by FattySpring** [comment]
[1.5.4](https://immersivetranslate.com/docs/CHANGELOG/#154) 已添加
