### ISSUE TITLE
 使用Gemini双语字幕时的一些问题

### ISSUE THREAD

**Issue by pasical** [immersive-translate/immersive-translate#1676]
### 插件版本号 | Version

1.4.12

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

#### YouTube视频使用Gemini翻译的双语字幕时会出现中英文混杂的情况
![image](https://github.com/immersive-translate/immersive-translate/assets/112304778/dfe4638a-6f53-44b6-96b2-14f74bc97d2b)
↑如图，两行字幕都是英文

#### 原因是中文字幕提前显示完毕，而英文字幕还有一行，于是空出来的部分就被原始的英文字幕填充了
![image](https://github.com/immersive-translate/immersive-translate/assets/112304778/1da007eb-dc2e-4a00-94ab-c5ddf8b0bbaa)
↑这是上一段字幕的截图

#### 这个问题同时引发了中文断句混乱，影响观看体验
![image](https://github.com/immersive-translate/immersive-translate/assets/112304778/cea9e7b3-5ea1-4ac2-a3ff-931a138b0f5d)
↑经常有些字幕行内语义不连贯，影响观看

### 补充说明 | Additional context

基础的微软翻译和谷歌翻译都没有出现该问题。

**Comment by theowenyoung** [comment]
可以分享一下视频的地址吗？已经出现问题的 视频时间点。

这个主要是因为 ai 对于这种多个断句有问题的句子，还不能完美的遵循指令给出对应的译文导致的，贴一下视频地址，我们先记录下这个 case，看看能不能有更好的方式。

**Comment by pasical** [comment]
> 可以分享一下视频的地址吗？已经出现问题的 视频时间点。
> 
> 这个主要是因为 ai 对于这种多个断句有问题的句子，还不能完美的遵循指令给出对应的译文导致的，贴一下视频地址，我们先记录下这个 case，看看能不能有更好的方式。 

事实上，几乎所有带有字幕的长视频都会出现该问题。这是截图视频的地址https://youtu.be/ZMqhE9r5JuI
视频中有多段出现问题，比如0:39

另一个有问题的视频例子：https://youtu.be/FXVjZ8AhvTc

**Comment by keyboard3** [comment]
gemini 如果翻字幕可以设置字幕段落数为1，不过仅字幕而言，gemini 的多段支持不好的情况其实不如用普通的机器翻译
