### ISSUE TITLE
[Bug]: PDF翻译遇到如下错误

### ISSUE THREAD

**Issue by I-Good-Vegetable** [immersive-translate/immersive-translate#1677]
### 插件版本号 | Version

1.4.12

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

PDF翻译会出现
Unexpected Application Error!
Unable to preload CSS for https://app-static.immersivetranslate.com/app-assets/css/back-top-b6536ef5.css
Error: Unable to preload CSS for https://app-static.immersivetranslate.com/app-assets/css/back-top-b6536ef5.css
    at HTMLLinkElement.<anonymous> (https://app-static.immersivetranslate.com/app-assets/js/entry-index-a4907369.js:1:1763)

![image](https://github.com/immersive-translate/immersive-translate/assets/68672839/217fc5fa-6066-4ffe-a183-300f22c2f107)

### 重现步骤 | To Reproduce

1. 点击插件图标
2. 点击PDF/ePUB

**Comment by keyboard3** [comment]
单独访问 https://app-static.immersivetranslate.com/app-assets/js/entry-index-a4907369.js 正常吗？能访问的话，刷新试下。
或者切换下代理试试

**Comment by keyboard3** [comment]
暂无反馈关闭此issue
