### ISSUE TITLE
用 immersive translate 作为浏览器默认 PDF 阅读器

### ISSUE THREAD

**Issue by yaohappiness** [immersive-translate/immersive-translate#168]
可以用 immersive translate 集成的 PDF 阅读器代替浏览器原生的 PDF 阅读器。这样就可以在电脑上直接用 immersive translate 打开 PDF 了。

参考[划词翻译](https://chrome.google.com/webstore/detail/%E5%88%92%E8%AF%8D%E7%BF%BB%E8%AF%91/ikhdkkncnoglghljlkmcimlnlhkeamad)：

<img width="1118" alt="image" src="https://user-images.githubusercontent.com/38402135/221347972-104abc07-c8e5-4d0f-a4b7-3657325cdc16.png">

在发现 immersive translate 前，我一直在用这款插件，里面做得好的功能作者也可以参考一下～

**Comment by theowenyoung** [comment]
好的，我觉得后者比较好一点，当网页里有PDF文件时，弹出提示
