### ISSUE TITLE
User Rules 里的 matches 能不能支持 regex

### ISSUE THREAD

**Issue by Krysl** [immersive-translate/immersive-translate#1680]
### 您希望的更新和改进是什么 | Update or Improve

有些网页，比如：
`https://pub.dev/packages?q=xxx` 是一种页面，
`https://pub.dev/packages/xxx` 是另一种页面。
如果用 `"matches": [ "pub.dev/packages*" ],` 来匹配，会同时匹配到两个页面。但我想要对两种页面分别配置。
比较理想的方式是使用 正则表达式 或者 glob 。

**Comment by theowenyoung** [comment]
1.5.1 版本起，match 支持了 Query 参数匹配，所以可以在前面用 "https://pub.dev/packages?", 后面用没有问号的？

**Comment by Krysl** [comment]
@theowenyoung 

之前用的是：
```json
  {
    "matches": [
      "https://pub.dev/packages?*"
    ],
    "selectors": [
      ".packages .packages-description"
    ]
  }
```
但不管用。

没想到后面不用加 `*` ，有些无语。。。

`matches` 里面到底是怎么匹配的？跟 glob 似的却似是而非，想看源码却发现早就闭源了。
还是希望文档里能提几句说明一下。

总之现在是临时解决了我遇到的问题，还是非常感谢的。

**Comment by flamintune** [comment]
https://immersivetranslate.com/docs/advanced/#rules-matches-%E5%8C%B9%E9%85%8D%E9%80%BB%E8%BE%91

已在文档中添加了关于 matches 的匹配，欢迎指正。
