### ISSUE TITLE
[Bug]: 个别屏幕分辨率下，YouTube全屏时双语字幕的字体大小无法等比例缩放了

### ISSUE THREAD

**Issue by lianwensheng** [immersive-translate/immersive-translate#1681]
### 插件版本号 | Version

1.5.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

**个别屏幕分辨率下，YouTube全屏时双语字幕的字体大小无法等比例缩放了，而且全屏后字幕位置会自动大幅上移...**

未开双语字幕的情况下：
![屏幕截图 2024-05-04 004352](https://github.com/immersive-translate/immersive-translate/assets/36002202/47393cc6-0ede-4936-9e6a-b00c50a34bac)
![屏幕截图 2024-05-04 004437](https://github.com/immersive-translate/immersive-translate/assets/36002202/b65d72a4-e4a7-4d06-9b94-87d88cbedfa0)

开启双语字幕的情况下：
![屏幕截图 2024-05-04 004015](https://github.com/immersive-translate/immersive-translate/assets/36002202/dd35e29d-2de3-4b64-abb8-0032e159429b)
![屏幕截图 2024-05-04 004200](https://github.com/immersive-translate/immersive-translate/assets/36002202/db2b7b1a-37a2-4187-827b-d9c50581b806)

### 出现问题的网址 | URL

https://www.youtube.com/watch?v=HeQX2HjkcNo

### 补充说明 | Additional context

720p、768p、1080p分辨率似乎都有此Bug

**Comment by FattySpring** [comment]
全屏字幕上移是在拖动字幕后吗？

**Comment by FattySpring** [comment]
1.5.2 已修复

**Comment by FattySpring** [comment]
> > 1.5.2 已修复
> 
> 全屏后字幕位置自动上移的情况貌似还有，不过上移的幅度没有之前那么大了，习惯字幕在最下的位置每次全屏都需要手动往下拖一下😂

录制视频看下？

**Comment by FattySpring** [comment]
> > 1.5.5 已修复字幕上移
> 
> 刚发现切换其他语言字幕或者刷新视频页面，字幕还是会小幅度上移。貌似是字幕无法记忆自定义位置，我测试把字幕位置调高后刷新视频页面，字幕又回到了初始位置了😂😂😂

是的，符合预期，暂无记忆开发计划
