### ISSUE TITLE
你们使用了Traduzir-paginas-web的源代码，而其采用了Mozilla Public License 2.0许可。根据该许可，您需要公开源代码。You have utilized the source code of Traduzir-paginas-web, which is licensed under the Mozilla Public License 2.0. According to this license, you are required to make the source code public.

### ISSUE THREAD

**Issue by huantai48** [immersive-translate/immersive-translate#1682]
### 您希望的更新和改进是什么 | Update or Improve

请阅读并遵守此链接中的许可证（https://github.com/FilipePS/Traduzir-paginas-web/blob/master/LICENSE）。这意味着，无论您的产品来自哪个国家，您都应公开源代码并遵守相关规定。这些规定是开源社区的基本原则，旨在促进知识共享和合作，确保技术进步的持续发展。

Please read and comply with the license at this link (https://github.com/FilipePS/Traduzir-paginas-web/blob/master/LICENSE). This means that regardless of the country of origin of your product, you are required to make the source code public and adhere to the relevant provisions. These regulations are fundamental principles of the open-source community aimed at fostering knowledge sharing and collaboration to ensure continuous technological advancement.

**Comment by DivineMK** [comment]
Why close this as completed?

**Comment by theowenyoung** [comment]
The original author mentioned that it is another project that needs to comply with the MPL2.0 protocol: 

https://github.com/immersive-translate/old-immersive-translate/

You can view a detailed description of this issue here: 

https://www.owenyoung.com/blog/fake-open-source/
