### ISSUE TITLE
Inquiry Regarding Customizing Translation of Individual Words

### ISSUE THREAD

**Issue by VincentLee3** [immersive-translate/immersive-translate#1684]
### 您希望的更新和改进是什么 | Update or Improve

I am currently using your translation software and have a question regarding its functionality. I was wondering if your software allows for the customization of translations for individual words.
pecifically, I am interested in being able to modify or define the translation of certain words according to my preferences or specific contexts. This feature would greatly enhance the accuracy and relevance of translations for my particular needs.

Could you please provide information on whether such custom semantic functionality is available in your software? If so, could you also guide me on how to access and utilize this feature effectively?

**Comment by theowenyoung** [comment]
Currently, only certain words are supported to be untranslated, you can see the options in [Settings], [Advanced Settings].
