### ISSUE TITLE
建议增加选项允许修改模型的temperature

### ISSUE THREAD

**Issue by redapple0204** [immersive-translate/immersive-translate#1687]
### 您希望的更新和改进是什么 | Update or Improve

建议增加选项允许修改模型的temperature，有的大语言模型需要详细调节温度以获得更好的翻译效果，希望能够支持自定义温度选项

**Comment by flamintune** [comment]
在开发者设置中支持对于 temperatrue 的修改，具体文档说明在下面

https://immersivetranslate.com/docs/advanced/#openai-temperature-%E8%AE%BE%E7%BD%AE
