### ISSUE TITLE
nature.com网站下面的期刊论文无法翻译问题

### ISSUE THREAD

**Issue by zhao-hx** [immersive-translate/immersive-translate#169]
在nature communications 、ISME、nature microbiology和scientific reports等nature.com下面的期刊论文，没法使用沉浸式翻译功能。

例如以下几个链接：
https://www.nature.com/articles/s41467-018-04756-x#Sec8

https://www.nature.com/articles/s41564-022-01151-7#:~:text=A%20possible%20explanation%20is%20that%20the%20changes%20of,yields%20show%20that%20warming%20significantly%20reduces%20microbial%20biomass.

https://www.nature.com/articles/s41396-020-00748-2#Sec2

https://www.nature.com/articles/s41598-019-42260-4

**Comment by theowenyoung** [comment]
第一个：  nature.com 我打开是可以翻译的呀，如下图：

<img width="1456" alt="Screenshot 2023-02-25 at 22 53 23" src="https://user-images.githubusercontent.com/62473795/221363624-14149d41-7550-4822-ade0-0d8094f5bfb4.png">

**Comment by theowenyoung** [comment]
第二个：

<img width="1353" alt="Screenshot 2023-02-25 at 22 54 40" src="https://user-images.githubusercontent.com/62473795/221363691-b4dfb2fe-712d-4f9a-8e5b-ea41d24b0ec7.png">

**Comment by zhao-hx** [comment]
奇怪了，我点了没反应，网页也不动。用edge dev，edge，chrome都试过

**Comment by theowenyoung** [comment]
刚试了edge，chrome，firefox，chrome 油猴，好像都是正常的. 你的版本是最新的吧？

**Comment by zhao-hx** [comment]
是edge商店装的0.2.66。edge浏览器版本是最新的。

**Comment by theowenyoung** [comment]
你用的翻译服务是什么呢？点击翻译的时候没有loading？

**Comment by zhao-hx** [comment]
我用的是谷歌翻译。loading就是在转圈那个对吧？没有的。点了之后没啥反应。其他的期刊网页目前都没问题。

**Comment by theowenyoung** [comment]
你是刚开始使用沉浸式翻译吗？ 之前的版本是ok 的吗？ 

因为 0.2.60 - 0.2.66 之间的版本 有一个Bug，导致扩展的内存使用量飙升，这个问题会影响到一些复杂的网页，不知道你会不会是遇到了这种情况。最新版本 0.2.68 解决了这个问题，但是商店版还在审核中。

**Comment by zhao-hx** [comment]
我是刚开始不久。应该一直都在用的都是0.2.66。
好的，那我更新后再看一下是否OK。感谢解答！

**Comment by zhao-hx** [comment]
找到问题所在了。
在“是否翻译网页所有区域”我选了是。这是因为之前有一个网页（不记得是哪个了），打开了这一项loading就很快。
刚试了油猴版本的0.2.68，也是同样的，改了这一项设置就好了。

**Comment by theowenyoung** [comment]
好吧. 翻译网页所有区域有的时候兼容性不是很好，所以建议不要默认打开.

**Comment by theowenyoung** [comment]
最新版本已解决 翻译所有区域 时 ，没有翻译nature的问题. 商店版还在审核～
