### ISSUE TITLE
[Bug]: 更新之后无法使用

### ISSUE THREAD

**Issue by Macaria01** [immersive-translate/immersive-translate#1690]
### 插件版本号 | Version

1.5.1

### 平台 | Platform

iOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在更新之后无法使用，点击该扩展显示的是一片空白，无法点进去，进入管理界面显示检测不到该扩展，要我启用该扩展，但启用扩展界面无法打开。

### 出现问题的网址 | URL

每一个

**Comment by keyboard3** [comment]
重启和卸载重装试过没？ 录个屏看下

**Comment by keyboard3** [comment]
暂无反馈 关闭此 issue
