### ISSUE TITLE
PDF Pro 会自动翻译参考文献和附录

### ISSUE THREAD

**Issue by JimXiongGM** [immersive-translate/immersive-translate#1691]
### 您希望的更新和改进是什么 | Update or Improve

PDF Pro 会自动翻译参考文献和附录，这是我不需要的，我只需要翻译前9页即可。如果能增加这个功能，我愿意付费，否则100页的额度太少了。

**Comment by theowenyoung** [comment]
谢谢建议，我们后面会支持用户填写翻译 5-9 页这样，这个可以满足需求吗？

**Comment by JimXiongGM** [comment]
可以的

**Comment by keyboard3** [comment]
> 可以的

现在已经支持了
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/84193d60-d257-478c-83ad-6b0a4c6d4a10)
