### ISSUE TITLE
[Bug]: ”AI 专家“ 不生效

### ISSUE THREAD

**Issue by m-guo** [immersive-translate/immersive-translate#1692]
### 插件版本号 | Version

1.5.1

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

选择“AI 专家”后system prompt 还是使用的“通用”设置的自定义Prompt

### 重现步骤 | To Reproduce

浏览器默认更新到最新版本前已开启Beta，选择不同AI专家后抓包后实际都在使用自定义的“通用“提示词。

**Comment by keyboard3** [comment]
选了什么专家？录个屏看下，我这边没能复现你说的这种情况

**Comment by m-guo** [comment]
https://github.com/immersive-translate/immersive-translate/assets/8684229/f138bfe4-d0cb-41ed-849d-1dbc500cf432

**Comment by m-guo** [comment]
补充信息浏览器是Brave，基于 Chromium 内核；同时我也测试了Chrome，一样的问题。

**Comment by keyboard3** [comment]
这里算是个bug, 现在是以用户设置过的提示词优先级最高。设置过会覆盖专家的提示词。下一版修复

**Comment by keyboard3** [comment]
1.5.2 已修复
