### ISSUE TITLE
[Bug]: ollama本地翻译SRT文件时会跳过落下几段不翻译

### ISSUE THREAD

**Issue by josh9019** [immersive-translate/immersive-translate#1693]
### 插件版本号 | Version

1.51

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

ollama本地部署大模型翻译SRT字幕文件时，会跳过落下几段翻译，有连续2到4行段落会落下不翻译。我用1.3几版本的时候没有这个问题。更新后出现此问题。有什么解决办法吗？谢谢了
![1](https://github.com/immersive-translate/immersive-translate/assets/129022376/04e38a99-38bb-4ed7-b148-d972641e5f24)
![2](https://github.com/immersive-translate/immersive-translate/assets/129022376/bceae346-9b9b-4f5d-b688-25b9f8879439)
![4](https://github.com/immersive-translate/immersive-translate/assets/129022376/2cc3d83a-5665-46ea-bd3a-ebb08fa334b1)
![3](https://github.com/immersive-translate/immersive-translate/assets/129022376/5c0884e5-9c43-4daa-808d-7a8385e1cc6a)

### 出现问题的网址 | URL

srt字幕翻译

**Comment by josh9019** [comment]
我试了降低每次请求最大段落数和每秒最大请求数，还是会出现此问题。
是没有按照提示词要求返回的原因吗？，不懂...

**Comment by josh9019** [comment]
![Uploading 5.jpg…]()

**Comment by josh9019** [comment]
![5](https://github.com/immersive-translate/immersive-translate/assets/129022376/3f3dbecb-4827-4fd4-a20b-3275dd35055e)

**Comment by shadowwider** [comment]
请问一下你是怎么配置openai的自定义让他支持ollama本地的呢？我配置一直不成功，不像你是有的成功有的不成功。看了主要问题是api/chat这个接口默认是steam模式返回，这个扩展没有办法新增steam：false的参数进去。而/api/generate接口的参数调用又不一样。

**Comment by josh9019** [comment]
> 请问一下你是怎么配置openai的自定义让他支持ollama本地的呢？我配置一直不成功，不像你是有的成功有的不成功。看了主要问题是api/chat这个接口默认是steam模式返回，这个扩展没有办法新增steam：false的参数进去。而/api/generate接口的参数调用又不一样。

https://immersivetranslate.com/docs/services/ai/   官网的教程里-其他AI模型接入里有说明。
就是以下内容。
其他 AI 模型临时接入
Ollama
从[官网](https://ollama.com/)下载安装 ollama
OLLAMA_ORIGINS="*" ollama serve （允许跨域访问并启动ollama）
进入插件的[设置页](https://dash.immersivetranslate.com/#general),翻译服务选择 openAI
api_key: ollama
自定义模型: llama2 、[other models](https://ollama.com/library)
自定义 URL 地址: http://localhost:11434/v1/chat/completions

注意一定要设置环境变量才可以配置成功。
不知道能不能看懂这个说明，如果不行我可以截图给你。

**Comment by josh9019** [comment]
> 请问一下你是怎么配置openai的自定义让他支持ollama本地的呢？我配置一直不成功，不像你是有的成功有的不成功。看了主要问题是api/chat这个接口默认是steam模式返回，这个扩展没有办法新增steam：false的参数进去。而/api/generate接口的参数调用又不一样。
我这个问题好像就是你说的这个API接口问题，之前报错提示过api什么的。之前1.3版本的时候还好好的，更新之后BUG有点多。 steam/false参数api/generate接口这些一点都不懂。。。自己又不会解决。。。

**Comment by josh9019** [comment]
> 请问一下你是怎么配置openai的自定义让他支持ollama本地的呢？我配置一直不成功，不像你是有的成功有的不成功。看了主要问题是api/chat这个接口默认是steam模式返回，这个扩展没有办法新增steam：false的参数进去。而/api/generate接口的参数调用又不一样。

![QQ截图20240510093234](https://github.com/immersive-translate/immersive-translate/assets/129022376/1aaf3f21-64f5-4937-b6c5-9cae87cdf2be)
![QQ截图20240510093251](https://github.com/immersive-translate/immersive-translate/assets/129022376/db9b5744-eb1e-4e41-92da-24b300ff53d0)
环境变量里添加这两个就可以。

**Comment by josh9019** [comment]
> 请问一下你是怎么配置openai的自定义让他支持ollama本地的呢？我配置一直不成功，不像你是有的成功有的不成功。看了主要问题是api/chat这个接口默认是steam模式返回，这个扩展没有办法新增steam：false的参数进去。而/api/generate接口的参数调用又不一样。

![QQ截图20240510101536](https://github.com/immersive-translate/immersive-translate/assets/129022376/9102a07a-c76f-4764-bc98-9a7eb372438e)
环境变量加这个就可以了。

**Comment by keyboard3** [comment]
1.5.2 可以配置字幕最大段落数量，可以配置成1看看

**Comment by josh9019** [comment]
> 1.5.2 可以配置字幕最大段落数量，可以配置成1看看
解决了！！！非常感谢大佬！
我一直尝试每次请求最大段落数......还真没试字幕最大段落数量...

**Comment by shadowwider** [comment]
> > 请问一下你是怎么配置openai的自定义让他支持ollama本地的呢？我配置一直不成功，不像你是有的成功有的不成功。看了主要问题是api/chat这个接口默认是steam模式返回，这个扩展没有办法新增steam：false的参数进去。而/api/generate接口的参数调用又不一样。
> 
> https://immersivetranslate.com/docs/services/ai/ 官网的教程里-其他AI模型接入里有说明。 就是以下内容。 其他 AI 模型临时接入 Ollama 从[官网](https://ollama.com/)下载安装 ollama OLLAMA_ORIGINS="*" ollama serve （允许跨域访问并启动ollama） 进入插件的[设置页](https://dash.immersivetranslate.com/#general),翻译服务选择 openAI api_key: ollama 自定义模型: llama2 、[other models](https://ollama.com/library) 自定义 URL 地址: http://localhost:11434/v1/chat/completions
> 
> 注意一定要设置环境变量才可以配置成功。 不知道能不能看懂这个说明，如果不行我可以截图给你。

非常感谢 ，可以了。 原来真的有这个接口啊 http://localhost:11434/v1/chat/completions 因为ollama文档中没有这个路由 ，我用的其他的。
