### ISSUE TITLE
[Bug]: openai custom Model名称设置无效

### ISSUE THREAD

**Issue by yangcheng** [immersive-translate/immersive-translate#1694]
### 插件版本号 | Version

1.5.1

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

使用openai翻译，修改baseurl到deepseek，无论如何设置model name，发送的请求都是gpt-3.5-turbo

![Screenshot 2024-05-09 at 10 31 16 AM](https://github.com/immersive-translate/immersive-translate/assets/132834/829c710f-e2fb-4526-861a-165793a7963f)

**Comment by flamintune** [comment]
下个版本会修复这个问题，目前临时的解决方案是刷新下页面

**Comment by keyboard3** [comment]
1.5.2 已修复
