### ISSUE TITLE
希望能添加对DeepSeek API的支持

### ISSUE THREAD

**Issue by 200KKKKK** [immersive-translate/immersive-translate#1695]
### 您希望的更新和改进是什么 | Update or Improve

DeepSeek的API价格非常便宜，想要尝试用这个代替原本用的Gemini，希望能添加对其的支持
https://platform.deepseek.com/api-docs/zh-cn/pricing/

**Comment by theowenyoung** [comment]
请直接在 openai 里设置自定义接口即可： `https://api.deepseek.com/v1/chat/completions`

![image](https://github.com/immersive-translate/immersive-translate/assets/62473795/fa8974a0-f2da-4ee3-88a5-055f586fdea5)
