### ISSUE TITLE
[Bug]: 段落宽度超出原文

### ISSUE THREAD

**Issue by nothingshiru** [immersive-translate/immersive-translate#1698]
### 插件版本号 | Version

1.5.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

该段落有一条分成2行的长链接，译文把链接放到了一行，撑开了译文段落宽度
![屏幕截图 2024-05-11 235620](https://github.com/immersive-translate/immersive-translate/assets/79258245/c6cfbb76-5fbd-4902-91d2-f4db83fb06e0)

### 出现问题的网址 | URL

https://stackoverflow.com/questions/5797014/why-do-browsers-match-css-selectors-from-right-to-left/5813672#5813672:~:text=So%20browsers%20match%20from%20the%20right%3B

### 重现步骤 | To Reproduce

1. 打开链接
2. 使用翻译
3. 滚动到如图位置

**Comment by keyboard3** [comment]
打开面板更新下规则
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/fcf75e7a-65d7-481a-b2b6-b0a64e59e9cc)
