### ISSUE TITLE
建议化学式和公式的上下标及括号等保持半角显示

### ISSUE THREAD

**Issue by JayYanS** [immersive-translate/immersive-translate#1699]
### 您希望的更新和改进是什么 | Update or Improve

我注意到翻译文本时，虽然化学式可以保持上下标，但时都是呈现全角显示，这导致上下标与字母的间距过大，显示不美观，建议在进行翻译时，结果的公式上下标以半角显示。
![msedge_eSwIWuMo7U](https://github.com/immersive-translate/immersive-translate/assets/169546689/a2d63c1e-857b-4ef4-8b56-1c8fa48ec6f4)

**Comment by keyboard3** [comment]
原文内容在哪，正常公式都是用标准公式标签实现，这种我们会保留。除非原文是通过字符实现，这种通过翻译服务翻译之后的内容，我们没法干预
