### ISSUE TITLE
请教油猴插件可以有快捷键吗？

### ISSUE THREAD

**Issue by zhl111** [immersive-translate/immersive-translate#17]
有些网站必须手动选择全文翻译或翻译到底，才会翻译。这功能藏得太深，能不能简化步骤？

**Comment by theowenyoung** [comment]
请问是哪个网站呢？

一般来说，希望用户来报告 不兼容的网站。


全文翻译和翻译到底是两个不同的功能。

先说“翻译到底”，不应该出现正常的翻译按钮无法翻译，但是翻译到底却能翻译的网页，如果有的话，那就是出现bug了。翻译到底只是用来加快翻译。代替默认的边滚动边翻译。 （你可以在进阶设置了设置默认开启翻译到底。开启后的缺点是，遇到长网页，如果你不需要看完，它也会整个翻译完。如果你用的是付费翻译API，那会浪费很多资源，所以默认不推荐开启）

全文翻译的确可以解决一些不兼容的网页问题，但体验没有默认的智能识别主区域好，（但是我同样提供了选项，你可以把翻译行为默认设置为全文翻译，在 通用 -> 进阶设置 里面）

**Comment by theowenyoung** [comment]
油猴插件的快捷键功能在计划中，要提供的～

**Comment by theowenyoung** [comment]
Discord 我们的扩展是专门做了适配的呀，按理说不需要全文翻译。

firefox和chrome扩展已经提供了全文翻译的快捷键了～

**Comment by zyzweb** [comment]
@theowenyoung 这个翻译特别好用,希望能造点支持油猴快捷键  感谢
