### ISSUE TITLE
扩展破坏了某些网站的功能

### ISSUE THREAD

**Issue by Long0x0** [immersive-translate/immersive-translate#170]
某网站有以下代码
```
      var handleMessage = function(event) {
        var origin = event.origin;
        console.log("origin", event.origin);
        if (origin == "https://login.dingtalk.com") {
          //判断是否来自ddLogin扫码事件。
          var loginTmpCode = event.data;
          //获取到loginTmpCode后就可以在这里构造跳转链接进行跳转了

          window.location.href = "xxxx";
        }
      };
      window.addEventListener('message', handleMessage, false);
```
https://open.dingtalk.com/document/isv/scan-qr-code-to-login-isvapp

开启扩展之后导致网页错误地重定向，请问有没有办法解决呢

**Comment by theowenyoung** [comment]
好吧，这个看起来是网站自己的判断不够严谨，它用的是 origin 来判断，但是来自这个origin的可能是各种各样的message呀。

这个扩展也会用message在不同的iframe之间通信...

我再想想.. 看看有没有办法避免一下。

**Comment by Long0x0** [comment]
嗯，确实。写了个油猴脚本把它干掉了。。。感谢。

**Comment by pandada8** [comment]
能否控制是否在某些域名注入 js ? 考虑到 oapi.dingtalk.com 也不会有翻译需求

**Comment by theowenyoung** [comment]
嗯 有道理，可以,下个版本加一下.

**Comment by zuluion** [comment]
同样遇到此问题，错误重定向了
![image](https://user-images.githubusercontent.com/26626090/222871551-6ed8d239-9104-4761-8a02-f2da0dc578d3.png)

**Comment by Long0x0** [comment]
> 同样遇到此问题，错误重定向了 ![image](https://user-images.githubusercontent.com/26626090/222871551-6ed8d239-9104-4761-8a02-f2da0dc578d3.png)

```
// ==UserScript==
// @name         fix dingtalk
// @version      0.0.1
// @description  fix dingtalk
// @match        https://xxxxxxxxxxxxx*
// @run-at       document-start
// @grant        none
// ==/UserScript==

var __handleMessage;
Object.defineProperty(window, 'handleMessage', {
    get() {
        return __handleMessage;
    },
    set(h) {
        if(h.toString().includes(`获取到loginTmpCode后就可以在这里构造跳转链接进行跳转了`)) {
            __handleMessage = function () {
                console.log('handleMessage');
            }
        } else {
            __handleMessage = h;
        }
    }
});
```
这会屏蔽掉钉钉扫码登录功能

**Comment by zuluion** [comment]
> > 同样遇到此问题，错误重定向了 ![image](https://user-images.githubusercontent.com/26626090/222871551-6ed8d239-9104-4761-8a02-f2da0dc578d3.png)
> 
> ```
> // ==UserScript==
> // @name         fix dingtalk
> // @version      0.0.1
> // @description  fix dingtalk
> // @match        https://xxxxxxxxxxxxx*
> // @run-at       document-start
> // @grant        none
> // ==/UserScript==
> 
> var __handleMessage;
> Object.defineProperty(window, 'handleMessage', {
>     get() {
>         return __handleMessage;
>     },
>     set(h) {
>         if(h.toString().includes(`获取到loginTmpCode后就可以在这里构造跳转链接进行跳转了`)) {
>             __handleMessage = function () {
>                 console.log('handleMessage');
>             }
>         } else {
>             __handleMessage = h;
>         }
>     }
> });
> ```
> 
> 这会屏蔽掉钉钉扫码登录功能

感谢

**Comment by theowenyoung** [comment]
下个版本已修复该问题.

**Comment by theowenyoung** [comment]
@Long0x0  请问你有帮忙验证这个问题吗？ 已经解决了是吗？ 

其实我不知道哪个公开的网站接入了钉钉的这个登录，所以我其实没验证过～

**Comment by theowenyoung** [comment]
好的，感谢～
