### ISSUE TITLE
[Bug]: PDF Pro OCR识别pdf翻译效果差

### ISSUE THREAD

**Issue by severecold** [immersive-translate/immersive-translate#1704]
### 插件版本号 | Version

1.5.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

有丢失章节或大段不翻译问题

### 重现步骤 | To Reproduce

对需要ocr识别的pdf使用PDF PRO进行翻译，发现丢失不少章节内容
BTW，建议翻译可以指定pdf页码范围，而不是流量不足100页，干脆就不翻译。

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/125e702f-875f-4396-ae48-291a49609966)
支持指定范围
