### ISSUE TITLE
[Bug]: macos下chrome浏览器自定义翻译服务报错

### ISSUE THREAD

**Issue by hu19940121** [immersive-translate/immersive-translate#1705]
### 插件版本号 | Version

1.5.2

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

自定义翻译服务报错
![Snipaste_2024-05-14_12-16-48](https://github.com/immersive-translate/immersive-translate/assets/26077620/690c2683-1121-4c46-ae37-7aafbb078f4a)

**Comment by keyboard3** [comment]
油猴脚本还是插件？切换其他服务呢

**Comment by keyboard3** [comment]
> > 油猴脚本还是插件？切换其他服务呢
> 
> 插件 其他服务可以。openai 和claude不行 但是在windows11 系统的chorme浏览器上又没有问题

奇怪 理论上这个错误应该跟翻译服务无关的。 但是你说就ai类的不可以

**Comment by keyboard3** [comment]
无法复现，暂时关闭这个issue哈
