### ISSUE TITLE
建议：文件翻译时，能够不翻译论文/书籍的附录或参考文献

### ISSUE THREAD

**Issue by hidenmaskvip** [immersive-translate/immersive-translate#1706]
### 您希望的更新和改进是什么 | Update or Improve

在翻译pdf或epub的论文/电子书时，会把附录或参考文献也翻译了，希望能不翻译这些内容，看能否增加一个选项
原因：
1. 附录或参考文献的格式较复杂，翻译容易出很多错误
2. 参考文献感兴趣的一般会再去搜，保留原文方便查找
3. 有的参考文献列的名单很长，看的频率也低，浪费翻译资源，而且增加了翻译后双语文件的长度，不方便阅读

**Comment by keyboard3** [comment]
很难判断一个内容是不是附录或参考文献。如果你用的是 pdf-pro 可以指定翻译范围
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/c18d8fba-bc37-4a99-92b6-0225fb4ad27d)
