### ISSUE TITLE
同一文件的多次翻译效果似乎雷同

### ISSUE THREAD

**Issue by bwy727** [immersive-translate/immersive-translate#1707]
### 插件版本号 | Version

v1.5.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

我翻译的是从pdf导出的html文件，根据实际阅读效果，有时需要多次修改pdf文件，导出更新的html。可我发现除了第一次html文件的翻译时间长一些，后几次都是秒翻，而且我发现翻译的内容也没有太大的变化。

### 补充说明 | Additional context

能否有一个清除之前翻译痕迹的选项。这样保证每次对同一html文件的翻译都是崭新的效果。

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/3b9dd5b3-11bd-48a8-81d2-ab1bbd35b6b7)
https://dash.immersivetranslate.com/#about
你可以去设置页面临时关闭或者清除缓存
