### ISSUE TITLE
[Bug]: 在Arc browser突然无法工作了

### ISSUE THREAD

**Issue by fortunehan** [immersive-translate/immersive-translate#1708]
### 插件版本号 | Version

1.5.2

### 平台 | Platform

macOS

### 浏览器 | Browsers

Other

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

点击插件翻译按钮，网页上没有任何变化

在 Arc browser 上突然无法工作了。
Arc browser: 1.42.1
MacOS: 14.4.1

### 出现问题的网址 | URL

所有网址

**Comment by FattySpring** [comment]
未能复现，在[设置页](https://dash.immersivetranslate.com/#general)重置下配置或者重新安装下扩展

**Comment by fortunehan** [comment]
谢谢回复🙏，重新安装插件后恢复正常了😊

**Comment by fortunehan** [comment]
谢谢回复🙏，重新安装插件后恢复正常了😊
