### ISSUE TITLE
[Bug]: txt文档翻译无法使用openai

### ISSUE THREAD

**Issue by beavermarine** [immersive-translate/immersive-translate#1709]
### 插件版本号 | Version

1.5.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox, Chrome, Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

已经设置openai接口为默认，txt文档翻译界面的选择引擎中不显示。

**Comment by flamintune** [comment]
无法复现，能麻烦详细说下复现的步骤吗，另外的话，txt文档翻译的翻译引擎列表中只会显示已经配置好了的翻译服务

**Comment by beavermarine** [comment]
> 无法复现，能麻烦详细说下复现的步骤吗，另外的话，txt文档翻译的翻译引擎列表中只会显示已经配置好了的翻译服务

已解决，使用的是tgw的api，在没有填写apikey的情况下仍可以检测成功。在按格式填写后恢复正常。
