### ISSUE TITLE
api接口建议

### ISSUE THREAD

**Issue by photkey** [immersive-translate/immersive-translate#171]
用来用去还是deepl的翻译质量最好，奈何免费字符数有限，平常又是重度翻译用户，免费字符数远远不够。
之前提过多个key每次翻译随机，被否了，可能需要修改的东西太多了；又想了个另外的方式来实现，不知道这样是不是会更容易实现。

```
    "deepl":[
        {
            "authKey": "xxxxxx",
            "matches": [
            "www.google.com/search?q=*",
            ]
        },
        {
            "authKey": "yyyyyy",
            "matches": [
            "github.com/*"
            ]
        }
	]
```

**Comment by theowenyoung** [comment]
我也是对 DeepL 强需求，我最后解决了这种需求，和合作伙伴推出了一种[不限字符量的Deepl 翻译 Auth Key](https://immersive-translate.owenyoung.com/services/deepL#%E9%80%9A%E8%BF%87%E8%B5%9E%E5%8A%A9%E6%B2%89%E6%B5%B8%E5%BC%8F%E6%89%A9%E5%B1%95%E8%8E%B7%E5%BE%97%E6%97%A0%E5%AD%97%E7%AC%A6%E6%95%B0%E9%99%90%E5%88%B6%E7%9A%84-deepl-auth-key) 的付费服务。

用这种办法可以无限制畅享 DeepL 的翻译，你会想试用一下吗？

**Comment by theowenyoung** [comment]
关于你提到的那个实现，其实成本都是一样的，我觉得目前更不具有侵入性的做法是提供类似这样的配置就可以了：

```json
{
"deepl":{
  "authKey":"xxx",
  "alternatives":[
  {"authKey":"yyy"}
]
}
```

这样的话程序更好处理一点. 而且暂时可以只在 开发者设置里提供，而不对普通用户造成困扰。

如果你会前端开发的话，也许可以贡献下这个功能？

**Comment by theowenyoung** [comment]
还有一种办法是目前已经支持的，就是你自己搭建一个deepl的服务，在你自己的服务里轮询不同的API Key，然后在配置里配置自己的接口：

```json
{

  "deepl":{
   "freeApiUrl":"https://xxxxx.com",
   "proApiUrl":"https://xxxx.com"
}
}
```

**Comment by theowenyoung** [comment]
就和这个保持一致即可： https://www.deepl.com/zh/docs-api/translate-text/translate-text/

接口地址为 /v2/translate

**Comment by theowenyoung** [comment]
目前 Deepl 自定义key 已支持用 `,` 分割多个 key哈～ 或者也可以开通 Pro 会员。暂时关掉这个问题了～
