### ISSUE TITLE
[Bug]: 翻譯後，字會消失

### ISSUE THREAD

**Issue by curtiswu33** [immersive-translate/immersive-translate#1710]
### 插件版本号 | Version

1.5.4

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

https://github.com/immersive-translate/immersive-translate/assets/134845275/4c1dd76c-8d36-4f9a-a0a7-1bd0c8f38e98

### 出现问题的网址 | URL

https://www.beams.co.jp/shop/

**Comment by keyboard3** [comment]
这是一个新 bug, 当原文和译文一样的情况下，显示仅译文会隐藏掉原文。 你可以暂时切换回双语显示

**Comment by keyboard3** [comment]
将在1.5.5修复

**Comment by curtiswu33** [comment]
謝謝！！
