### ISSUE TITLE
youtube翻译的断句问题

### ISSUE THREAD

**Issue by crysishacker** [immersive-translate/immersive-translate#1713]
### 您希望的更新和改进是什么 | Update or Improve

我是之前那个讨论了youtube字幕翻译因为断句造成翻译错掉的人
你指出如果把全文/整句扔到翻译api，没办法和时间轴对应（主要在逗号分隔上）
我给出一个trick，就是参考youtube自带中文翻译的标点符号位置，利用他们的时间轴
这样是否可行？

**Comment by crysishacker** [comment]
好像不是逗号分割，而是怎么把一句翻译好的话割掉……

**Comment by keyboard3** [comment]
![image](https://github.com/user-attachments/assets/28179387-0600-4278-938f-d8224c4c1db7)
普通分句：根据字幕出现间隔来分句
智能分句：根据聚合文本通过AI来自动拆分

**Comment by crysishacker** [comment]
> ![image](https://private-user-images.githubusercontent.com/13177744/351923180-28179387-0600-4278-938f-d8224c4c1db7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMzA1ODYsIm5iZiI6MTcyMjAzMDI4NiwicGF0aCI6Ii8xMzE3Nzc0NC8zNTE5MjMxODAtMjgxNzkzODctMDYwMC00Mjc4LTkzOGYtZDgyMjRjNGMxZGI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDIxNDQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyNWNjMDk4MGNmMGQ2NTI3ZGZmN2VkNjAxZWViYTMzZDYzYWU3ZDUxMzFmOTFiNzhmNWZmMTNkNDJlNjlmMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rxl8qnCJFXuKHu2nNoUhHCXrjjoDKCTTzp4UBJtZQtE) 普通分句：根据字幕出现间隔来分句 智能分句：根据聚合文本通过AI来自动拆分

额，我需要的是up主做好的字幕的断句。自动生成字幕因为每一个单词都带时间戳，所以并不难解决
