### ISSUE TITLE
希望添加 YouTube 字幕「固定位置」的选项

### ISSUE THREAD

**Issue by Thomas-Harrell** [immersive-translate/immersive-translate#1716]
### 您希望的更新和改进是什么 | Update or Improve

默认情况下，字幕位置会受到视频进度条影响

导致字幕位置一上一下的，十分抢占视觉注意力

希望添加用于选择字幕位置是否固定的选项

以及字幕固定在屏幕某一百分比高度的选项

这样会更贴近实际播放器的体验

![SCR-20240516-krit](https://github.com/immersive-translate/immersive-translate/assets/106761803/b04b41cf-5bac-4ed0-8e65-1857dfa952cd)

**Comment by FattySpring** [comment]
暂无此计划，在进度条隐藏和现实的时候字幕上下移动是为了避免字幕被遮挡，正常观看是字幕位置是不会变化的。

**Comment by actforjason** [comment]
插件有自定义css的功能吗，因为有第三方插件能隐藏控制栏，可以配合使用固定字幕位置。

**Comment by actforjason** [comment]
> 插件有自定义css的功能吗，因为有第三方插件能隐藏控制栏，可以配合使用固定字幕位置。 @FattySpring

设置页面开发者设置里面有Injected CSS
