### ISSUE TITLE
[Bug]: Certain webpage text is not picked up for translation

### ISSUE THREAD

**Issue by galaxypayoff** [immersive-translate/immersive-translate#1718]
### 插件版本号 | Version

1.5.5

### 平台 | Platform

Windows, Android

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

The main text on the webnovel page is not getting picked up. I've tried the basic Google Translate and only the TOC header is translated but not the main text. It does not happen on every page but seems to happen where the page text is very long.
![image](https://github.com/immersive-translate/immersive-translate/assets/166029599/1a0452c4-76f1-48bf-a05d-d9ccdc49066c)

### 出现问题的网址 | URL

https://shubaowb.com/novel/233867/22.html

**Comment by keyboard3** [comment]
This bug will be fixed in 1.5.6 and you can temporarily use the mouseover function to translate the text
