### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by yarask09** [immersive-translate/immersive-translate#1719]
### 插件版本号 | Version

1.5.5

### 平台 | Platform

Windows

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

The translation of the srt file content is corrupted. both the translated language and the original language in the translation.
![loi](https://github.com/immersive-translate/immersive-translate/assets/170023824/356105a6-cca2-4ec7-901b-1b70ed95c593)

**Comment by keyboard3** [comment]
May I ask what target language to translate into, please attach the file to help us reproduce and troubleshoot the issue

**Comment by keyboard3** [comment]
No feedback Close this issue
