### ISSUE TITLE
更新后突然用不了了

### ISSUE THREAD

**Issue by ChloeKurumi** [immersive-translate/immersive-translate#172]
下午用起来还正常，突然用不了以为是接口的问题，就等了段时间，结果发现2023/2/26 19:41:39更新过......然后就用不了了.....一直翻译不出来....

**Comment by theowenyoung** [comment]
是油猴吗？

什么版本用不了？

具体表现是？

谷歌翻译吗？

**Comment by ChloeKurumi** [comment]
> 是油猴吗？
> 
> 什么版本用不了？
> 
> 具体表现是？
> 
> 谷歌翻译吗？

是彩云小译， 一直转圈加载，2023/2/28 03:49:57更新规则后恢复正常了，感谢修复
