### ISSUE TITLE
[Bug]: 谷歌学术部分标题无法翻译

### ISSUE THREAD

**Issue by ysdj** [immersive-translate/immersive-translate#1720]
### 插件版本号 | Version

1。

### 请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/2924182/e8631c31-1c4b-4f05-acae-a112e40ffa2d)
如图中箭头所示

### 出现问题的网址 | URL

https://scholar.google.com/scholar?start=20&q=%22mendelian+randomization%22&hl=zh-CN&scisbd=1&as_sdt=0,5&as_vis=1

**Comment by keyboard3** [comment]
> ![image](https://private-user-images.githubusercontent.com/2924182/331779819-6f7cadcb-519d-40cb-b7ea-6f00490ac8b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzQxOTQsIm5iZiI6MTcxNjE3Mzg5NCwicGF0aCI6Ii8yOTI0MTgyLzMzMTc3OTgxOS02ZjdjYWRjYi01MTlkLTQwY2ItYjdlYS02ZjAwNDkwYWM4YjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjBUMDI1ODE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2E1YjMwN2EyNjVhOGFjZTA4NGIyOWM3NmRmOTkyZGEzZjg5MWFkNjg1ZDg2ZTFiNjczNWJkYjg5Y2Y0OTIyOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VvyZD7t8H8ylJ0EORx-Vwdoz1JLYHn9huoMES6kjZzc) https://scholar.google.com/scholar?hl=zh-CN&scisbd=1&as_sdt=0%2C5&as_vis=1&q=10.21203%2Frs.3.rs-4356518%2Fv1&btnG=
已适配，打开面板更新下规则重试下
