### ISSUE TITLE
[Bug]: 使用AI制作双语epub消耗大量token但并没有显示结果

### ISSUE THREAD

**Issue by Miles629** [immersive-translate/immersive-translate#1721]
### 插件版本号 | Version

1.5.5

### 平台 | Platform

macOS

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

使用deepseek的api。
想要制作双语电子书，后台显示消耗了八百多万tokens。其中包含输出了两百多万的token。但是页面上几乎没有没有任何的显示。（试了很多次，有时候会有翻译结果但只有一点点，不到一万的样子。）总之和后台token消耗完全不匹配。

### 出现问题的网址 | URL

https://app.immersivetranslate.com/ebook/make/

### 重现步骤 | To Reproduce

1、上传一本中文epub。
2、在设置中设置openai，接口改成deepseek。模型改成deepseek-api。（可以正常翻译网页）
3、开始翻译，同时用另一个浏览器刷新查看deepseek后台。
4、观察到双语书界面很难显示任何结果。但是后台token消耗非常高（因为有延后性，可能一刷发现两百万没了。但在双语书界面通常不会有任何结果的显示。）

**Comment by Miles629** [comment]
尽管AI翻译在大部分情况下已经明显感受到比传统翻译api强了。但是似乎制作双语epub使用自定义的AI在目前版本中不太work。还是要用传统翻译api

**Comment by keyboard3** [comment]
epub没有显示译文？看起来是 deepseek 没有遵守提示词，看过翻译时网络请求的响应内容吗？

**Comment by Miles629** [comment]
> epub没有显示译文？看起来是 deepseek 没有遵守提示词，看过翻译时网络请求的响应内容吗？

尴尬，没有捏😅

**Comment by keyboard3** [comment]
暂时关闭这个问题，如果有进展可以重开

**Comment by gahoo** [comment]
还是希望能将OpenAI的选项加回epub文件的翻译服务中，如果担心效果不佳，可以增加警告或提醒。或者在进阶设置里面增加选项允许开启。

**Comment by theowenyoung** [comment]
@gahoo 目前是有的，除非你没有在设置里启用 OpenAI 。

![CleanShot 2024-07-16 at 14 00 28@2x](https://github.com/user-attachments/assets/db795077-a825-4974-9c3e-e07146c83916)

**Comment by gahoo** [comment]
现在有了，前两天还没见，太奇怪了。
