### ISSUE TITLE
[Bug]: 文言文翻译，简繁夹杂，星期一翻译成月曜日等日式用于。请修正。

### ISSUE THREAD

**Issue by yuphone** [immersive-translate/immersive-translate#1722]
### 插件版本号 | Version

1.5.5

### 平台 | Platform

macOS

### 请描述这个Bug | Describe the bug

文言文翻译，简繁夹杂，星期一翻译成月曜日等日式用于。请修正。

### 出现问题的网址 | URL

https://www.economist.com/in-brief/2024/05/17/trumps-lawyers-pounce-on-cohen-house-rebukes-biden-over-israel

**Comment by keyboard3** [comment]
没看懂，你用的什么翻译服务？建议给出一段可以复现的文本

**Comment by keyboard3** [comment]
这个翻译服务翻译译文内容，插件干预不了
