### ISSUE TITLE
[Bug]: 申請試用，文件翻譯，可是出現錯誤

### ISSUE THREAD

**Issue by azq1231** [immersive-translate/immersive-translate#1723]
### 插件版本号 | Version

1.5.5

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

已經申請試用，結果還是要升級為正式會員。
那要試用什麼？

錯誤原因：AI 额度已达到上限 (AI token quota exceeded)，您可以選擇以下方式解決：

1. 切換到 Deepl 或其他翻譯服務
2. 立刻[升級為正式會員](https://immersivetranslate.com/profile?utm_source=extension&utm_medium=extension&utm_campaign=error_modal&upgradeFromTrial=true)

### 出现问题的网址 | URL

https://app.immersivetranslate.com/text#zh-CN/zh-TW/%E6%8A%B1%E6%AD%89%2C%E6%88%91%E4%B9%8B%E5%89%8D%E7%90%86%E8%A7%A3%E9%8C%AF%E4%BA%86%E6%82%A8%E7%9A%84%E9%9C%80%E6%B1%82%E3%80%82%E8%AE%93%E6%88%91%E6%8C%89%E7%85%A7%E6%82%A8%E6%8F%90%E4%BE%9B%E7%9A%84SRT%E5%AD%97%E5%B9%95%E6%96%87%E4%BB%B6%2C%E6%A0%B9%E6%93%9A%E6%99%82%E9%96%93%E8%BB%B8%E7%82%BA%E6%82%A8%E9%80%B2%E8%A1%8C%E6%96%B7%E5%8F%A5%E3%80%82%E4%BB%A5%E4%B8%8B%E6%98%AF%E8%99%95%E7%90%86%E5%BE%8C%E7%9A%84%E7%B5%90%E6%9E%9C%3A%0A%0A1%0A00%3A00%3A00%2C967%20--%3E%2000%3A00%3A02%2C969%0A-%20%E2%99%AA%20MTV%20%E2%99%AA%0A%0A2%0A00%3A00%3A02%2C969%20--%3E%2000%3A00%3A05%2C472%0A-%20Previously%20on%20%22RuPaul's%20Drag%20Race%22...%0A%0A3%0A00%3A00%3A05%2C472%20--%3E%2000%3A00%3A08%2C041%0AYou%20need%20to%20transform%20these%20dancers%0A%0A4%0A00%3A00%3A08%2C041%20--%3E%2000%3A00%3A09%2C843%0Afrom%20RuPaul's%20Drag%20Race%20Live%0A%0A5%0A00%3A00%3A09%2C843%20--%3E%2000%3A00%3A13%2C847%0Ainto%20devastating%20drag%20queens.%0A%0A6%0A00%3A00%3A13%2C847%20--%3E%2000%3A00%3A14%2C981%0AMorphine.%0A%0A7%0A00%3A00%3A14%2C981%20--%3E%2000%3A00%3A17%2C450%0A-%20Where%20you%20lose%20me%20is%20the%20look.%0A%0A8%0A00%3A00%3A17%2C450%20--%3E%2000%3A00%3A18%2C785%0A-%20Sapphira.%0A%0A9%0A00%3A00%3A18%2C785%20--%3E%2000%3A00%3A21%2C087%0A-%20The%20outfits%20are%20different%2C%20so%20it%20is%20telling%0A%0A10%0A00%3A00%3A21%2C087%20--%3E%2000%3A00%3A23%2C022%0Aa%20completely%20different%20story.%0A%0A11%0A00%3A00%3A23%2C022%20--%3E%2000%3A00%3A24%2C424%0A-%20Plane%20Jane.%0A%0A12%0A00%3A00%3A24%2C424%20--%3E%2000%3A00%3A26%2C059%0A-%20When%20y'all%20rounded%20the%20corner%2C%0A%0A13%0A00%3A00%3A26%2C059%20--%3E%2000%3A00%3A28%2C361%0Ait%20was%20like%20the%20power%20just%20hit%20us%20in%20the%20face.%0A%0A14%0A00%3A00%3A28%2C361%20--%3E%2000%3A00%3A29%2C929%0A-%20Condragulations.%0A%0A15%0A00%3A00%3A29%2C929%20--%3E%2000%3A00%3A32%2C065%0AYou%20are%20the%20winner%20of%20this%20week's%20challenge.%0A%0A16%0A00%3A00%3A32%2C065%20--%3E%2000%3A00%3A33%2C733%0A%5Blight%20applause%5D%0A%0A17%0A00%3A00%3A33%2C733%20--%3E%2000%3A00%3A36%2C936%0ASapphira%2C%20shantay%20you%20stay.%0A%0A18%0A00%3A00%3A36%2C936%20--%3E%2000%3A00%3A39%2C739%0AMorphine%2C%20sashay%20away.%0A%0A19%0A00%3A00%3A39%2C739%20--%3E%2000%3A00%3A41%2C441%0A-%20Oh!%0A%0A20%0A00%3A01%3A25%2C143%20--%3E%2000%3A01%3A27%2C679%0A%5Bdramatic%20music%5D%0A%0A21%0A00%3A01%3A27%2C679%20--%3E%2000%3A01%3A30%2C982%0A%E2%99%AA%20%E2%99%AA%0A%0A22%0A00%3A01%3A30%2C982%20--%3E%2000%3A01%3A33%2C918%0A-%20Ooh.%0A-%20Oh%2C%20my%20goodness.%0A%0A23%0A00%3A01%3A33%2C918%20--%3E%2000%3A01%3A36%2C721%0A-%20I'm%20really%20sad%20that%20Morphine%20has%20been%20eliminated%0A%0A24%0A00%3A01%3A36%2C721%20--%3E%2000%3A01%3A40%2C024%0Ajust%20because%20I%20know%20how%20bad%20she%20wanted%20to%20make%20it%20to%20the%20end%2C%0A%0A25%0A00%3A01%3A40%2C024%20--%3E%2000%3A01%3A43%2C962%0Abut%20I'm%20also%20excited%20because%20I%20made%20it%20to%20the%20top%20four.%0A%0A26%0A00%3A01%3A43%2C962%20--%3E%2000%3A01%3A46%2C464%0A-%20It's%20going%20to%20be%20so%20boring%20without%20Mo.%0A%0A27%0A00%3A01%3A46%2C464%20--%3E%2000%3A01%3A48%2C366%0A%22I'm%20rooting%20for%20all%20of%20you.%0A%0A28%0A00%3A01%3A48%2C366%20--%3E%2000%3A01%3A50%2C535%0AMorphine%20Love%20Dion.%22%0A%0A29%0A00%3A01%3A50%2C535%20--%3E%2000%3A01%3A52%2C137%0A-%20We%20love%20you%2C%20Morphine.%0A-%20Oh%2C%20my%20sister.%0A%0A30%0A00%3A01%3A52%2C137%20--%3E%2000%3A01%3A53%2C338%0A-%20How%20are%20you%20feeling%2C%20Sapphira%3F%0A%0A31%0A00%3A01%3A53%2C338%20--%3E%2000%3A01%3A55%2C340%0A-%20This%20was%20not%20a%20part%20of%20my%20fantasy.%0A%0A32%0A00%3A01%3A55%2C340%20--%3E%2000%3A01%3A58%2C843%0A-%20That%20lip%20sync%20was%20probably%20my%20favorite%0A%0A33%0A00%3A01%3A58%2C843%20--%3E%2000%3A02%3A00%2C945%0Aof%20the%20entire%20season%20thus%20far.%0A%0A34%0A00%3A02%3A00%2C945%20--%3E%2000%3A02%3A03%2C515%0A-%20When%20she%20said%2C%20Sapphira%2C%20I%20was%20expecting%20her%20to%20say%2C%0A%0A35%0A00%3A02%3A03%2C515%20--%3E%2000%3A02%3A06%2C684%0AMorphine%2C%20shantay%2C%20you%20stay%2C%0A%0A36%0A00

**Comment by theowenyoung** [comment]
试用会员 有一个每天的限制，每天最多能使用 20 w 字符或者 20w tokens

![CleanShot 2024-05-19 at 12 02 35@2x](https://github.com/immersive-translate/immersive-translate/assets/62473795/c9b47a45-a5b7-4299-8db8-eac5dc18a476)
