### ISSUE TITLE
[Bug]: 使用本地AI翻译字幕文件会错行

### ISSUE THREAD

**Issue by despairTK** [immersive-translate/immersive-translate#1725]
### 插件版本号 | Version

1.5.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

我使用的本地AI来翻译字幕文件，但是在返回的结果中会有英文原句，但是实际上这一句其实已经翻译，原句返回来会导致附近的句子错行。如图所示：
![QQ截图20240519103704](https://github.com/immersive-translate/immersive-translate/assets/111871110/adb04698-c2c5-4c98-b125-9378cdde47e5)

**Comment by despairTK** [comment]
![QQ截图20240519105644](https://github.com/immersive-translate/immersive-translate/assets/111871110/382aa0f3-3f1c-4f55-9cf1-190d15eae058)

**Comment by despairTK** [comment]
![TCHFBO IY {~Y`C%)DBJO}1](https://github.com/immersive-translate/immersive-translate/assets/111871110/5a44eaa3-b404-4e04-b57a-b65f6fda380e)

**Comment by zx3777** [comment]
确实会错行，用在线ai翻译也一样，特别是出现只有符号的行的情况下
1
00:00:18,310 --> 00:00:38,330
・～

2
00:00:38,330 --> 00:00:58,350
・～

3
00:00:58,350 --> 00:01:18,300
・～

4
00:01:18,300 --> 00:01:38,320
・～

5
00:01:38,320 --> 00:01:58,340
・～

6
00:01:58,340 --> 00:02:05,280
・～

7
00:02:05,280 --> 00:02:11,290
・～

8
00:02:11,290 --> 00:02:14,290
みゆき

**Comment by keyboard3** [comment]
这种情况是AI没有按照提示词返回指定数量的段落，可以缩小下字幕的段落数
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/9b13141d-4eb9-48dc-9f91-ecd2fccf0e28)
