### ISSUE TITLE
【建议】扩展按钮功能

### ISSUE THREAD

**Issue by linkwoodworking** [immersive-translate/immersive-translate#173]
建议：点击插件的按钮时，可以在设置中选择【显示弹出页面】或者直接【开启网页全文翻译】

理由：常用的语言和服务都是固定的，用久了就会发现每次都需要点两下，第一下打开设置有些浪费，感觉直接开启全文翻译的优先级要比设置要高些，更符合普通人的需要

可以参考：划词翻译，他的插件里有这个功能，【通用-扩展按钮】可以看到

望考虑一下，谢谢

**Comment by theowenyoung** [comment]
如果电脑上使用的话，可以考虑使用 快捷键？ 默认是 `alt+a`

手机上使用的话，也有默认的`X指`同时触屏 就可以唤起翻译。

不过这也是一个很不错的功能～我记下来，后面加一下。

**Comment by theowenyoung** [comment]
我们未来会添加一个 悬浮在页面右侧的 快捷翻译按钮，这样对于新手可能更简单～

电脑上使用的话，建议直接用快捷键，或者鼠标右键，点击翻译。
