### ISSUE TITLE
[Bug]: 维基百科翻译不正确，出现原文没有的文本

### ISSUE THREAD

**Issue by PPeony** [immersive-translate/immersive-translate#1731]
### 插件版本号 | Version

1.5.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

维基百科翻译不对，划线的地方出现了2007，但是原文中并没有2007
![image](https://github.com/immersive-translate/immersive-translate/assets/48722223/a0baec58-b458-437c-8e9d-6db801ada954)

### 出现问题的网址 | URL

https://en.wikipedia.org/wiki/Adolf_Hitler

### 重现步骤 | To Reproduce

chrome插件使用的是进入网页就自动翻译网站，翻译用的是谷歌翻译

**Comment by theowenyoung** [comment]
这个是谷歌翻译返回的，沉浸式翻译插件没啥办法：

https://translate.google.com/?sl=auto&tl=zh-CN&text=Adolf%20Hitler%20%3Cb0%3E%3C%2Fb0%3E%20(20%20April%201889%20%E2%80%93%2030%20April%201945)%20was%20an%20Austrian-born%20German%20politician%20who%20was%20the%20dictator%20of%20Nazi%20Germany%20from%201933%20until%20his%20suicide%20in%201945.%20He%20rose%20to%20power%20as%20the%20leader%20of%20the%20Nazi%20Party%2C%20%3Cb1%3E%3C%2Fb1%3E%20becoming%20the%20chancellor%20in%201933%20and%20then%20taking%20the%20title%20of%20F%C3%BChrer%20und%20Reichskanzler%20in%201934.%20%3Cb2%3E%3C%2Fb2%3E%20During%20his%20dictatorship%2C%20he%20initiated%20the%20European%20theatre%20of%20World%20War%20II%20by%20invading%20Poland%20on%201%20September%201939.%20He%20was%20closely%20involved%20in%20military%20operations%20throughout%20the%20war%20and%20was%20central%20to%20the%20perpetration%20of%20the%20Holocaust%3A%20the%20genocide%20of%20about%20six%20million%20Jews%20and%20millions%20of%20other%20victims.%20&op=translate

![CleanShot 2024-05-20 at 19 11 38@2x](https://github.com/immersive-translate/immersive-translate/assets/62473795/8fb5b32c-9a31-47d4-84cf-c15cf7930fa2)

可以向谷歌反馈该问题，或者更换其他翻译服务。
