### ISSUE TITLE
More settings for translation text

### ISSUE THREAD

**Issue by galaxypayoff** [immersive-translate/immersive-translate#1732]
### 您希望的更新和改进是什么 | Update or Improve

Is it possible to add settings to modify the line-spacing and where word-break happens for translation text? I get weird word breaks on certain webpages, see "also" and "attractive" words below on this website: https://www.52shuku.vip/tuijian/ShaDiaoWen_240517.html
And the lines are too far apart making it's harder to scan.
![image](https://github.com/immersive-translate/immersive-translate/assets/166029599/8b6fa251-f075-4863-af50-48d2e9af7e3f)

**Comment by theowenyoung** [comment]
You can try setting different translation styles on the settings page to make the distinction between translations more obvious.

you can not change word-break settings.
