### ISSUE TITLE
[Bug]: 一个无语的翻译

### ISSUE THREAD

**Issue by thefujunjie** [immersive-translate/immersive-translate#1733]
### 插件版本号 | Version

0.5.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

**英文：We don’t need no inflammation**

- DeepL: 我们不需要炎症
- OpenAI: 我们不需要炎症
- 百度翻译：我们不需要炎症
- 腾讯翻译：我们不需要炎症
- Claude：我们不需要任何炎症
- 微软：我们不需要没有炎症
- Google: 我们不需要没有炎症

这么简单的语句，竟然只有微软和Google的翻译是准确的，其他的翻译出完全相反的意思……包括OpenAI
看来还是要相信大厂。

**Comment by keyboard3** [comment]
讨论的话 去discuss 板块哈
