### ISSUE TITLE
建议：支持译文显示自定义粗细（字重）

### ISSUE THREAD

**Issue by foresee-io** [immersive-translate/immersive-translate#1734]
### 您希望的更新和改进是什么 | Update or Improve

目前译文字重似乎是跟着原始网页走的，但在某些网站这样做，会导致译文变得不可读。希望支持下面几个功能的一种：
- 锁定译文字重（粗细），指定用粗体、标准体还是什么字重；
- 限制最小和最大字重。

https://ar5iv.labs.arxiv.org/html/2009.06732?_immersive_translate_auto_translate=1

（字体 Noto Sans CJK SC ；2024年以前的arXiv文章，会调出这个旧的LaTeX转换器，网页指定的默认字重是300）
<img width="871" alt="截屏2024-05-22 23 32 40" src="https://github.com/immersive-translate/immersive-translate/assets/32860378/5597c236-1327-46d3-ac0c-e4227467191f">

**Comment by flamintune** [comment]
https://dash.immersivetranslate.com/#general

把插件设置页面中的译文显示样式设置为加粗能否满足你的需求，设置为加粗后，译文会默认设置为 700 的字重
![image](https://github.com/immersive-translate/immersive-translate/assets/79519446/5577d71f-4d46-4826-899b-5fb99ce78478)

**Comment by foresee-io** [comment]
谢谢推荐，但我认为还不能满足需求。粗体还是太粗了，仍然会使文章可读性变差。 @flamintune

**Comment by flamintune** [comment]
好的，我们正在考虑实现一版让用户自定义的译文显示样式，而不是只能选预设好的，后续有进展会在此issue上同步

**Comment by flamintune** [comment]
最新版本1.5.7已支持设置译文字重
