### ISSUE TITLE
[Bug]: 双语翻一下，YouTube 无法调整字幕大小 

### ISSUE THREAD

**Issue by thomasTAT** [immersive-translate/immersive-translate#1735]
### 插件版本号 | Version

1.5.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome, Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

[Bug]: 双语翻一下，you 无法调整字幕大小 
![image](https://github.com/immersive-translate/immersive-translate/assets/109513632/6b940b40-e2e9-4a37-9f07-5b506bb1e477)

### 出现问题的网址 | URL

https://www.youtube.com/watch?v=T8RXlaIOw_s

**Comment by FattySpring** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/25144301/cd00dd0b-9528-4f2f-a9e7-f653b3c69a46)
![image](https://github.com/immersive-translate/immersive-translate/assets/25144301/b7a880d7-dae1-4c79-ae0f-98b724da684c)

**Comment by FattySpring** [comment]
这个问题已经有一段时间没有新的回复，因此我们决定关闭它。如果有更多信息或者问题仍未解决，请随时重新打开。谢谢！
