### ISSUE TITLE
[Bug]: 在 floorp 侧边栏中无法使用

### ISSUE THREAD

**Issue by lost22git** [immersive-translate/immersive-translate#1736]
### 插件版本号 | Version

1.5.6

### 平台 | Platform

Windows

### 浏览器 | Browsers

Other

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在 floorp 浏览器使用右键翻译/alt-a,只会触发主界面翻译, 侧边栏中无法翻译

![image](https://github.com/immersive-translate/immersive-translate/assets/65008815/aca7e5bf-dc56-4ad4-b6af-35f21ca22a83)

**Comment by keyboard3** [comment]
这个浏览器的侧边栏，插件插件没有权限访问

**Comment by lost22git** [comment]
> 这个浏览器的侧边栏，插件插件没有权限访问

啥意思 要手动添加权限么 还是插件无法实现？

**Comment by keyboard3** [comment]
插件无法实现，浏览器不给这个权限

**Comment by lost22git** [comment]
> 插件无法实现，浏览器不给这个权限

可是KISS translator 可以实现啊，机制不一样？

**Comment by keyboard3** [comment]
> > 插件无法实现，浏览器不给这个权限
> 
> 可是KISS translator 可以实现啊，机制不一样？
> 
> 当然，没有要求插件一定要实现，纯属好奇

不确定，要看下

**Comment by flamintune** [comment]
看起来似乎是快捷键触发被主网页拦截掉了，导致侧边栏没有触发（即使鼠标的焦点在侧边栏），后面我们再继续看下，当前的解决方案是推荐开启悬浮球，通过悬浮球来控制侧边栏的翻译
![image](https://github.com/immersive-translate/immersive-translate/assets/79519446/306b04bb-8079-4c2d-8131-16098ca67832)

**Comment by flamintune** [comment]
经过排查发现是，floorp的侧边栏是不会算在总的页面里面的。

而插件的快捷键触发方式一般是通过后台去监听，后台通过检查哪个tab是激活的，从而向对应tab发送消息，触发翻译操作。在后台检查tabs的时候，侧边栏没有在tabs中，因此只会去向左边的主页面去发送翻译消息，从而导致了快捷键触发在侧边栏失效的情况。

所以这个问题是 floorp 未支持侧边栏快捷键的相关操作导致，想要解决的话，可以去 floorp 提 issue 试试。还有就是其实floorp最开始侧边栏对于插件注入的支持不是很友好，相关issue在[这里](https://github.com/Floorp-Projects/Floorp/issues/385)。
