### ISSUE TITLE
[Bug]: 点击自动开启双语字幕，bilibili视频未成功显示双语字幕

### ISSUE THREAD

**Issue by YuexingZeng** [immersive-translate/immersive-translate#1739]
### 插件版本号 | Version

1.5.6

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

点击自动开启双语字幕，bilibili视频未成功显示双语字幕，没有反应

### 出现问题的网址 | URL

https://www.bilibili.com/

**Comment by keyboard3** [comment]
B站cc字幕有没有开启

**Comment by YuexingZeng** [comment]
> B站cc字幕有没有开启

打开cc字幕，只显示了自动翻译的中文字幕，关闭cc字幕，则什么都没有

**Comment by keyboard3** [comment]
> > B站cc字幕有没有开启
> 
> 打开cc字幕，只显示了自动翻译的中文字幕，关闭cc字幕，则什么都没有

那是B站cc字幕只给中文，你可以将目标语言设置成英文

**Comment by YuexingZeng** [comment]
> > > B站cc字幕有没有开启
> > 
> > 
> > 打开cc字幕，只显示了自动翻译的中文字幕，关闭cc字幕，则什么都没有
> 
> 那是B站cc字幕只给中文，你可以将沉浸式目标语言设置成英文

好的，我尝试了一下，是ok的，非常感谢！

**Comment by ZeguanXiao** [comment]
@keyboard3 请问如果B站视频如果没有cc字幕，就不能使用双语字幕功能吗？

**Comment by keyboard3** [comment]
> @keyboard3 请问如果B站视频如果没有cc字幕，就不能使用双语字幕功能吗？

是的
