### ISSUE TITLE
不同网站，相同样式 但不同颜色应该怎么写配置？

### ISSUE THREAD

**Issue by photkey** [immersive-translate/immersive-translate#174]
我想在一些常用的网站，使用none样式：黑底白字的网站，译文用黄色；白底黑字的网站，译文用蓝色。
目前的功能可以实现吗？如果可以的话，请教配置应该怎么写？如果不可以的话，是否可能实现一下？

不同网站不同样式（同一颜色）这个我会写。

**Comment by theowenyoung** [comment]
目前无法实现。

这个感觉有点困难啊？ 检测网站真实的 light/dark 模式 是吗？

**Comment by theowenyoung** [comment]
那目前也是实现不了的。

下个版本新加一个类似 none 的样式，只不过给一个默认的颜色，是不是就能满足你的需求了？

**Comment by theowenyoung** [comment]
最新版本添加了一个黑灰色的theme～

商店版还在审核中
