### ISSUE TITLE
中華民國總統賴清德的英文姓氏(Lai)都會被翻譯為黎智英

### ISSUE THREAD

**Issue by wtkao** [immersive-translate/immersive-translate#1740]
### 您希望的更新和改进是什么 | Update or Improve

例如下面這則新聞：
https://www.reuters.com/world/asia-pacific/china-starts-second-day-war-games-around-taiwan-2024-05-24/

**Comment by keyboard3** [comment]
这个是翻译服务返回的，可以切换到其他翻译服务

**Comment by lost22git** [comment]
笑死
