### ISSUE TITLE
影片中字幕如果是簡體中文就不會翻譯成繁體中文，也無法雙語顯示，字幕如果是英文就都可以正常顯示，麻煩確認一下問題。

### ISSUE THREAD

**Issue by SakaZulu** [immersive-translate/immersive-translate#1743]
### 您希望的更新和改进是什么 | Update or Improve

總體體驗很不錯，但影片中字幕如果是簡體中文就不會翻譯成繁體中文，也無法雙語顯示，字幕如果是英文就都可以正常顯示，麻煩確認一下問題。

**Comment by FattySpring** [comment]
簡體中文與繁體中文之間不會自動翻譯，原文譯文都為中文影響閱讀

**Comment by CJMAX0110** [comment]
> 簡體中文與繁體中文之間不會自動翻譯，原文譯文都為中文影響閱讀

影片字幕選項中可以選擇 "影片字幕雙語/僅限譯文設定"，如果影片原文是簡體中文，我選擇僅顯示譯文，那就僅顯示繁體中文，這樣應該不會有影響閱讀的情況發生，畢竟很多人看不懂簡體中文。

**Comment by FattySpring** [comment]
1.6.1 已支援

**Comment by CJMAX0110** [comment]
測試1.6.2在簡體中文字幕下，選擇僅顯示譯文，但影片還是簡體中文，並非繁體中文

**Comment by keyboard3** [comment]
> 測試1.6.2在簡體中文字幕下，選擇僅顯示譯文，但影片還是簡體中文，並非繁體中文

![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/5a95b13c-bbda-45d2-aed5-d2fc6c927fe4)
测了下，正常的呀

**Comment by CJMAX0110** [comment]
測試youtube是正常的，但我常用的Udemy沒有作用
![1](https://github.com/immersive-translate/immersive-translate/assets/171788417/be18430b-d58e-49c9-88d5-6d7b182c526f)

**Comment by FattySpring** [comment]
1.6.2 已支持
