### ISSUE TITLE
[Bug]: 偶发性出现翻译英文时会更改原文内容，并显示在译文处

### ISSUE THREAD

**Issue by HSpeechless** [immersive-translate/immersive-translate#1744]
### 插件版本号 | Version

1.5.5

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

偶然触发的bug，如图

将原文的“PSUserConfig.txt”自动改为了“PSUserSecure.html”

甚至还贴心的使用了驼峰版式😂

<img width="1506" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/30715281/cabcccd6-e53d-4bf6-956e-517b83d75b5c">

### 出现问题的网址 | URL

https://helpx.adobe.com/photoshop/kb/enable-optional-extensions-photoshop-cc.html#deprecated-macos-save-api

### 重现步骤 | To Reproduce

1.开启鼠标悬停直接翻译
2.将鼠标移至该段文字即可

**Comment by keyboard3** [comment]
这个由选择的翻译服务翻译出来的，插件无法干预
