### ISSUE TITLE
[Bug]: 折叠框内英文内容被生成的中文压缩

### ISSUE THREAD

**Issue by dunsnan** [immersive-translate/immersive-translate#1747]
### 插件版本号 | Version

1.5.6

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

一个网页中有折叠框，框内有英文10行，但生成中文后，后续5行英文及中文翻译不可见，因为中文翻译挤占了原有的位置。同时框的大小不变。
![WechatIMG337](https://github.com/immersive-translate/immersive-translate/assets/170990520/d160917a-b555-4471-a5b4-c8709abe365c)
![WechatIMG338](https://github.com/immersive-translate/immersive-translate/assets/170990520/58dd00bd-55f9-4f8e-be55-5841a92b748e)

### 出现问题的网址 | URL

https://www.cpaaustralia.com.au/your-cpa-program/your-experience

**Comment by keyboard3** [comment]
打开面板更新下规则，已适配

**Comment by dunsnan** [comment]
翻译后，个别单词翻译不对，可否手动修改相关单词？
![WechatIMG339](https://github.com/immersive-translate/immersive-translate/assets/170990520/bdaf4bfd-71c6-4172-8506-759eff92e410)

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/7c54597c-20a7-47cc-94b8-39aed31d33d9)
可以手动编辑译文
