### ISSUE TITLE
[Bug]: 在线pdf翻译无法显示，加载后白屏

### ISSUE THREAD

**Issue by aono817** [immersive-translate/immersive-translate#1748]
### 插件版本号 | Version

1.5.2

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在线pdf 无法显示翻译，点击翻译按钮后出现加载，之后白屏
![WX20240528-151735@2x](https://github.com/immersive-translate/immersive-translate/assets/171003081/523669ae-6eff-4392-bfd8-79959ca71b6e)

### 出现问题的网址 | URL

https://moodle.telt.unsw.edu.au/pluginfile.php/11945070/mod_resource/content/1/MDIA5031%20-%20Assessment%20Outline%20%282024%29.pdf

### 重现步骤 | To Reproduce

1.打开在线pdf 
![WX20240528-151951@2x](https://github.com/immersive-translate/immersive-translate/assets/171003081/98cc651a-8d58-4f6a-8098-431b3db38315)
2，
<img width="311" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/171003081/cb9a6c26-debb-4af1-ac86-2f31e8ca4092">使用pdf翻译
3.
<img width="1428" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/171003081/fbfbff6a-2f03-4259-9a5d-69b5df0b6e89">
<img width="1438" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/171003081/cca2f285-b22d-481a-b540-b3d07c47a88c">

**Comment by keyboard3** [comment]
你这个pdf地址需要登录授权才能访问，插件无法访问到这个文件内容，下载之后离线翻译吧
