### ISSUE TITLE
能否优化页面翻译顺序

### ISSUE THREAD

**Issue by heheda123123** [immersive-translate/immersive-translate#1754]
### 您希望的更新和改进是什么 | Update or Improve

比如这个页面 `https://www.uvicorn.org/release-notes/#0300-2024-05-28`
翻译的时候会优先翻译左侧和右侧的目录，最后才翻译中间的内容，但用户最关心的其实是中间的内容
特别是这种目录很长的页面 ，得等一会儿才能开始翻译正文内容
![image](https://github.com/immersive-translate/immersive-translate/assets/97490782/502a5553-57dc-45f9-8c4b-a6922c0422ce)

**Comment by keyboard3** [comment]
有正文优先，只不过不是所有网页都能准确的识别人眼看到的正文，大部分文章的正文部分都会优先翻译。比如你可以试试这个地址 https://react.dev/learn

**Comment by heheda123123** [comment]
但是我这边遇到多个类似的页面都没有先识别到正文，能否优化下呢，比如这些页面都是优先翻译目录。
应该是有共性的问题
```
https://book.hacktricks.xyz/welcome/readme
https://www.thehacker.recipes/
https://ppn.snovvcrash.rocks/
https://dmcxblue.gitbook.io/red-team-notes-2-0/
https://www.vincentyiu.com/
https://pentestbook.six2dez.com/
https://mobile-security.gitbook.io/mobile-security-testing-guide/
https://www.ired.team/
https://swisskyrepo.github.io/InternalAllTheThings/
https://lsecqt.github.io/Red-Teaming-Army/
```

**Comment by keyboard3** [comment]
> 但是我这边遇到多个类似的页面都没有先识别到正文，能否优化下呢，比如这些页面都是优先翻译目录。 应该是有共性的问题
> 
> ```
> https://book.hacktricks.xyz/welcome/readme
> https://www.thehacker.recipes/
> https://ppn.snovvcrash.rocks/
> https://dmcxblue.gitbook.io/red-team-notes-2-0/
> https://www.vincentyiu.com/
> https://pentestbook.six2dez.com/
> https://mobile-security.gitbook.io/mobile-security-testing-guide/
> https://www.ired.team/
> https://swisskyrepo.github.io/InternalAllTheThings/
> https://lsecqt.github.io/Red-Teaming-Army/
> ```

这个不太好优化，这个问题我先重开吧，后续看看有没有更好的办法

**Comment by keyboard3** [comment]
1.9.7 版本已优化正文翻译
