### ISSUE TITLE
[Bug]: iOS上Safari插件

### ISSUE THREAD

**Issue by Hikari2333** [immersive-translate/immersive-translate#1755]
### 插件版本号 | Version

1.5.7

### 平台 | Platform

iOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

iOS上Safari插件版不支持谷歌云盘同步，油猴脚本版和chrome插件版都支持。这是有意为之还是bug呢？

**Comment by keyboard3** [comment]
因为扩展内Safari不允许谷歌授权，可以去 https://dash.immersivetranslate.com/ 在线设置页去同步
