### ISSUE TITLE
[Bug]: OpenAI翻译的文本占位符替换不成功

### ISSUE THREAD

**Issue by hidamarink** [immersive-translate/immersive-translate#1756]
### 插件版本号 | Version

1.5.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

使用OpenAI翻译服务(模型 GPT3.5 turbo)时，GPT返回的翻译结果中的占位符未替换。使用的是鼠标悬停翻译。
OpenAI翻译结果如图，其他翻译引擎显示正常。
![image](https://github.com/immersive-translate/immersive-translate/assets/16144634/b58fbc8f-19ff-4ff4-9848-a20cc9db5c2a)
![image](https://github.com/immersive-translate/immersive-translate/assets/16144634/9933d620-cc15-4349-9266-2fd0c32d594e)

### 出现问题的网址 | URL

https://github.com/elastic/elasticsearch-js/issues/1716

### 补充说明 | Additional context

同页面的谷歌翻译结果
![image](https://github.com/immersive-translate/immersive-translate/assets/16144634/b3d857a1-3a65-42eb-8070-eeb416ad4e6d)
![image](https://github.com/immersive-translate/immersive-translate/assets/16144634/6dbabff0-a182-4bb0-ad04-02f2346c7178)

**Comment by keyboard3** [comment]
你自定义了提示词？ 我这边正常的
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/e21c40e2-2750-4d75-b9cb-9a23b882fb96)

**Comment by hidamarink** [comment]
> 你自定义了提示词？ 我这边正常的 ![image](https://private-user-images.githubusercontent.com/13177744/335061357-e21c40e2-2750-4d75-b9cb-9a23b882fb96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNTI2OTcsIm5iZiI6MTcxNzA1MjM5NywicGF0aCI6Ii8xMzE3Nzc0NC8zMzUwNjEzNTctZTIxYzQwZTItMjc1MC00ZDc1LWI5Y2ItOWEyM2I4ODJmYjk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDA2NTk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyNGU0YjczNDU2ZjUwYjAzYjQxNWVjOGM4NDcyN2ZjZmNjMDg0OTNlOTg2YWNlYjI5MzRiMjk5YjcxZTEwNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.20wRW7zzUglH0fKDVHv4SH5iK6Hs24V6DGydmBfWXmM)

印象没动过关于提示词自定义功能，只修改过悬浮翻译按键相关的设置，以及翻译结果显示设置。就是突然某段时间就替换不出来了，公司和家里两台电脑(Chrome市场插件)都是相同的故障，一开始以为是OpenAI的故障而且用平时得少没在意，今天好奇打开日志看了一下，结果发现貌似OpenAI返回的结果上是没什么问题的，占位符也原样返回了，但是没有进行替换。

**Comment by keyboard3** [comment]
重置设置呢？

**Comment by hidamarink** [comment]
感谢大佬帮助。
