### ISSUE TITLE
请求支持带有Secret Key& API Key 授权的大模型API服务(如最近免费的百度ERNIE-Speed)

### ISSUE THREAD

**Issue by ThemanRonin** [immersive-translate/immersive-translate#1757]
### 您希望的更新和改进是什么 | Update or Improve

ERNIE-Speed-128k 提供的是使用 Secret Key& API Key生成鉴权签名（Access Token）后调用使用 。
但是在 【沉浸式翻译】 调用第三方api的时候，只有填写 APIKey 的地方，并没有其他的参数(如 Secret Key )传递的填写入口。所以无法使用
![image](https://github.com/immersive-translate/immersive-translate/assets/35099500/6d395e1f-e35c-4a9c-ac88-d3073ef30ef1)

尝试使用生成出来的鉴权签名（Access Token）作为 APIKey 使用，但是一直报错无法使用

**Comment by flamintune** [comment]
这个在后面的版本会支持，但是可能是把百度大模型单独拎出来作为一个服务，因为百度那边的请求和响应格式不太一样

**Comment by flamintune** [comment]
1.6.2版本已支持百度千帆大模型
