### ISSUE TITLE
增加DeepL的第三方中转支持（类似OpenAI/Gemini/Claude支持自定义中转服务器URL）

### ISSUE THREAD

**Issue by leslietoo** [immersive-translate/immersive-translate#1761]
### 您希望的更新和改进是什么 | Update or Improve

目前已经有些第三方实现的deepl api的中转服务，例如deepl-pro.com，其接口规范和官方保持一致。
官方api pro订阅的接口为api.deepl.com，api free订阅的接口为api-free.deepl.com，而这个中转方的api订阅接口为api.deepl-pro.com，直接换下接口地址即可，其他完全一样。价格也便宜。对于无法注册deepl的或者需要deepl pro api又囊中羞涩的用户来说是个好选择。

**Comment by theowenyoung** [comment]
目前可以通过手动修改开发者配置来自定义，短期内没有计划增加到UI中，配置如下：

![image](https://github.com/user-attachments/assets/92138a0a-627d-48d7-8874-174db4d84d0a)

```json
"translationServices": {
    "deepl": {
      "authKey": "xxxxx",
      "freeApiUrl": "https://api-free.deepl.com/v2/translate",
      "proApiUrl": "https://api.deepl.com/v2/translate",
      "provider": "custom"
    }
  }
```
