### ISSUE TITLE
English -> (Vietnamese - English) instead of (English-Vietnamese).

### ISSUE THREAD

**Issue by trionline1234** [immersive-translate/immersive-translate#1762]
### 您希望的更新和改进是什么 | Update or Improve

i would be better for foreign language learner if it is supported this mode, especially TTS(text to speech) with AI multilingual voices for bilingual text.
Example:
I love you. -> ( Anh yêu em. I love you.) instead (I love you. Anh yêu em.)

### 补充说明 | Additional context

Example:
I love you. -> ( Anh yêu em. I love you.) instead (I love you. Anh yêu em.)

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/ab5442f7-df25-4e41-823a-777aec37735f)
1.6.3 fixed
