### ISSUE TITLE
[Bug]: 自己的cahtgpt API，测试服务显示通过，翻译网页却不响应

### ISSUE THREAD

**Issue by SuSheng13T** [immersive-translate/immersive-translate#1763]
### 插件版本号 | Version

1.5.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

自己的cahtgpt API，测试服务显示通过，翻译网页却不响应

### 重现步骤 | To Reproduce

1.api：sk-4650d2af381b312ba7fcea280ea92b2c9c1d72dbc9ece3bee0ae4404348cec56
2.自定义网址：https://chat.opao.xyz/api
3.其他无改动

**Comment by mapicccy** [comment]
类似的问题，我是译文会覆盖原文，截图如下：
<img width="1023" alt="截屏2024-06-01 21 18 58" src="https://github.com/immersive-translate/immersive-translate/assets/11815231/cc542412-c566-443d-9e7d-8a0aeeeb6895">

**Comment by keyboard3** [comment]
> 类似的问题，我是译文会覆盖原文，截图如下： <img alt="截屏2024-06-01 21 18 58" width="1023" src="https://private-user-images.githubusercontent.com/11815231/335803802-cc542412-c566-443d-9e7d-8a0aeeeb6895.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNDk4MjYsIm5iZiI6MTcxNzI0OTUyNiwicGF0aCI6Ii8xMTgxNTIzMS8zMzU4MDM4MDItY2M1NDI0MTItYzU2Ni00NDNkLTllN2QtOGEwYWVlZWI2ODk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDEzNDUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkYzQ1NjdjODFkOThiMmNhOTUyNDczZTE3MzMyNTM4ZDBhZDMzZDI2YTk0YWE2MzI2MDQwYzU1Y2Q3ZGRlNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z-Q12VDDq-JGMFKWTYztnSSGnje1haff2YmjJqXpl9E">

译文覆盖原文是你点了仅译文显示
