### ISSUE TITLE
[Bug]: 有时点击选项没有任何反应。

### ISSUE THREAD

**Issue by despairTK** [immersive-translate/immersive-translate#1764]
### 插件版本号 | Version

1.5.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

虽然开了年费会员，但是额度不够我用。然后额度用完了后我会使用本地AI翻译，插件这几个版本更新下来后，长时间使用本地AI翻译插件会变得巨卡，表现现象为点击插件设置里任何选项无效，切换翻译引擎也无效，相当于插件死机。重启电脑依然插件死机。必须删除插件重新安装，以前删除重新安装还会保留用户配置信息，从1.5.6开始删除重装后用户配置信息都删除了。自己电脑配置I7-13700K+4090+64G内存+固态。不会是硬件问题，本地AI我用命令行长时间使用不会有卡顿。

**Comment by keyboard3** [comment]
你没有登录会员吗，会员会自动同步设置的呀

**Comment by keyboard3** [comment]
卡顿的时候插件的翻译缓存多大？ 本地AI的每秒翻译频率多大？

**Comment by despairTK** [comment]
> 你没有登录会员吗，会员会自动同步设置的呀

一直登陆着会员，但是遇到插件卡死后，卸载插件重装就无法同步用户配置。以前卸载重装账户也会自动登录。
我一直没有开启缓存。
我翻译字幕的设置是每次字幕请求最大段落数：5。每秒最大请求数：1.

这种卡死不一定100%长时间使用触发，目前在1.5.6和1.5.7各遇到过一次。
![QQ截图20240601222922](https://github.com/immersive-translate/immersive-translate/assets/111871110/835a7ed5-cec6-4724-a633-55f28e519062)

**Comment by keyboard3** [comment]
> > 你没有登录会员吗，会员会自动同步设置的呀
> 
> 一直登陆着会员，但是遇到插件卡死后，卸载插件重装就无法同步用户配置。以前卸载重装账户也会自动登录。 我一直没有开启缓存。 我翻译字幕的设置是每次字幕请求最大段落数：5。每秒最大请求数：1.
> 
> 这种卡死不一定100%长时间使用触发，目前在1.5.6和1.5.7各遇到过一次。 ![QQ截图20240601222922](https://private-user-images.githubusercontent.com/111871110/335807983-835a7ed5-cec6-4724-a633-55f28e519062.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNTI4MzgsIm5iZiI6MTcxNzI1MjUzOCwicGF0aCI6Ii8xMTE4NzExMTAvMzM1ODA3OTgzLTgzNWE3ZWQ1LWNlYzYtNDcyNC1hNjMzLTU1ZjI4ZTUxOTA2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxNDM1MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MmFiZDVhMzI4YWYxMzEzOTY1MzcxMWMyYWE3ZDcxMGM3NTNiMjg5ZTE5NmQ0Zjk3YTNmMjFiYWYyN2U4ODdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aYBvuNzQnT3c65cxgQvbhlI4SSSJ2Pr9nLM65r2GELA)

没开启缓存卡死？这个表现跟长时间使用关系不大，感觉像是触发了什么bug，导致触发了chrome读写限制，所以表现才是无法同步配置和变更设置。理论上重启浏览器或者关闭开启插件就可以避免，不过如果你下次遇到，可以把配置导出来，我们试试看能不能复现
