### ISSUE TITLE
[Bug]: 触屏平台点击翻译图标交互逻辑不正确

### ISSUE THREAD

**Issue by NealDeal34** [immersive-translate/immersive-translate#1766]
### 插件版本号 | Version

1.5.8

### 平台 | Platform

Android

### 浏览器 | Browsers

Firefox, Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在Android平台上firefox和edge的原生插件的悬浮翻译图标，点击后类似“翻译成中文”的提示文本会一直存在，无论之后再点击哪里都不会消失，除非刷新页面；且点击也无法呼出设置等图标，长按才可以，但实际上点不到；通过油猴的插件则无此问题
![Screenshot_2024-06-02-16-29-01-498_com microsoft emmx canary](https://github.com/immersive-translate/immersive-translate/assets/130116696/a17651ef-87c7-4d6c-9c6c-e17dec8f7fb2)

**Comment by FattySpring** [comment]
1.6.1 已修复

**Comment by NealDeal34** [comment]
https://github.com/immersive-translate/immersive-translate/assets/130116696/d608a370-343c-4c74-86fa-edff1b4b7fcb
并没有，虽然部分情形下好像确实点出稳定的了

**Comment by FattySpring** [comment]
> https://github.com/immersive-translate/immersive-translate/assets/130116696/d608a370-343c-4c74-86fa-edff1b4b7fcb 并没有，虽然部分情形下好像确实点出稳定的了

长按可以打开设置吗？

**Comment by NealDeal34** [comment]
确实，长按会打开设置而且悬浮也稳定了，但单纯点触还是会鬼畜

**Comment by FattySpring** [comment]
> 确实，长按会打开设置而且悬浮也稳定了，但单纯点触还是会鬼畜

该问题将在 1.6.2 修复
