### ISSUE TITLE
xml等文件中底部有大量样式

### ISSUE THREAD

**Issue by lxccc812** [immersive-translate/immersive-translate#1768]
### 您希望的更新和改进是什么 | Update or Improve

能否删除或者不予展示呢

### 补充说明 | Additional context

![image](https://github.com/immersive-translate/immersive-translate/assets/110974969/c1384556-5156-4e11-85fe-edee8abc983c)

**Comment by keyboard3** [comment]
你是一打开就出现吗？还是点击翻译按钮之后出现？

**Comment by keyboard3** [comment]
打开面板更新下规则，已经屏蔽了xml后缀的地址

**Comment by lxccc812** [comment]
并不是只有xml底部有大量样式代码，这种静态存储服务错误的话也是有大量样式代码的，chrome浏览。其他返回类型的就不太清楚了，我感觉可能也会有这种情况，目前我只看到这两个类型的，有其他发现我在提issue。
![image](https://github.com/immersive-translate/immersive-translate/assets/110974969/e0444923-78b1-42ee-865d-0f2dc58ef78a)
