### ISSUE TITLE
Orion浏览器支持

### ISSUE THREAD

**Issue by kaiyo655** [immersive-translate/immersive-translate#1769]
### 您希望的更新和改进是什么 | Update or Improve

![2024-06-03 16 51 16](https://github.com/immersive-translate/immersive-translate/assets/3762388/fa7a024c-63ed-4e73-b9d8-3ab0c2aaa495)
[Orion](https://kagi.com/orion/)是一个基于webkit引擎的浏览器, 支持Chrome插件, 但目前菜单显示不正常如上图

**Comment by flamintune** [comment]
这个似乎是 orion 浏览器的问题，我们在代码中控制不了这个，可以去 orion 那边提下 issue，参考链接：https://orionfeedback.org/d/7944-immersive-translate-extension-popup-is-cropped

**Comment by kaiyo655** [comment]
okay 谢谢开发老师

Hu Langmin ***@***.***>于2024年6月14日 周五17:57写道：
