### ISSUE TITLE
报告一个小bug：译文顺序与原文不同

### ISSUE THREAD

**Issue by zhao-hx** [immersive-translate/immersive-translate#177]
https://journals.asm.org/doi/full/10.1128/AEM.00928-21
里面的摘要最后一句，译文里边放到了第一句。

**Comment by theowenyoung** [comment]
可以给个截图吗？以及你使用的翻译引擎。也许是翻译引擎的问题？

**Comment by zhao-hx** [comment]
我换了引擎，顺序还是错的。一般出现在摘要部分。
又发现了第二个网页也有这个问题，也顺便贴这里了https://www.nature.com/articles/s41598-019-45804-w
两张图：
![1-G](https://user-images.githubusercontent.com/55905765/221618305-41ff866a-728e-453d-93c7-b88fbe3dfc70.jpg)
![2-B](https://user-images.githubusercontent.com/55905765/221618322-a2e8db6e-aac7-4742-b205-58b2982de3cc.jpg)
