### ISSUE TITLE
[Bug]: 点击翻译后，每次都会自动开启“总是翻译该网站”的选项

### ISSUE THREAD

**Issue by ZLFboy** [immersive-translate/immersive-translate#1770]
### 插件版本号 | Version

1.5.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

点击翻译后，每次都会自动开启“总是翻译该网站”的选项

### 出现问题的网址 | URL

https://www.justfree.io/

### 重现步骤 | To Reproduce

点击“沉浸式翻译”扩展图标，点击“翻译”按钮，之后“总是翻译该网站”选项便会自动开启

**Comment by keyboard3** [comment]
方便录个屏吗？你不点击就不会选中吗？

**Comment by ZLFboy** [comment]
> 方便录个屏吗？你不点击就不会选中吗？

感谢回复，我昨天重装了扩展，目前已经正常了
