### ISSUE TITLE
🔴 添加将字幕样式作用于简繁字幕的功能

### ISSUE THREAD

**Issue by Thomas-Harrell** [immersive-translate/immersive-translate#1771]
### 您希望的更新和改进是什么 | Update or Improve

这样可以把「简繁（未翻译）」字幕的样式统一，以获得一致的观看体验

**Comment by keyboard3** [comment]
没看懂，你详细描述下吗

**Comment by FattySpring** [comment]
1.6.1 已支持

**Comment by FattySpring** [comment]
简体到繁体使用翻译符合预期，未能复现上述视频字幕不显示情况，暂无计划提供三个独立的开发选项。

**Comment by FattySpring** [comment]
> @FattySpring
> 
> * 感谢回复
> 
> * 钟文泽那个视频今天看已经可以加载出字幕了
> * 何同学的视频，刚刚测试了一下，选择简体字幕，还是没有办法正常显示，https://www.youtube.com/watch?v=OuBZ2m2DRYI
> * 样式覆盖有时会失效的问题，清空了一下 YouTube 缓存，目前现在还没有复现
> 
> * 原先以为会用「简繁转换」之类的脚本实现，没想到直接用翻译引擎了
> * 如果用 LLM 翻译，这样会造成不必要的 Token 消耗，然后速度也慢
> * 然后不同的 LLM 模型、不同的 Prompt，繁体翻译成简体的效果都有些差别
> * 昨天测试的时候因为忘了关「AI 专家 - 意译大师」，两次翻译导致意思差的更远了
> * 如果用机器翻译的话，谷歌翻译效果是最好的，速度快，而且字幕是从繁体直接转换成简体
> * 发现 DeepLX 是只有繁体的，没有办法翻译成简体，https://www.youtube.com/watch?v=JpQC0W91E6k

- https://www.youtube.com/watch?v=OuBZ2m2DRYI 测试正常
- 简体中文与繁体中文在表达上有所不同，还是需要翻译引擎来处理
- 可以在设置页为视频字幕单独指定翻译服务

**Comment by FattySpring** [comment]
【多次刷新页面或关闭页面再打开有几率导致「沉浸式翻译」的字幕翻译失效的问题还是存在】 使用的是什么浏览器

**Comment by FattySpring** [comment]
「字幕仅译文」 不显示字幕问题在 1.6.4 已修复

**Comment by FattySpring** [comment]
多次刷新页面或关闭页面再打开有几率导致「沉浸式翻译」的字幕翻译失效的问题还是存在
1.5.4 已修复
