### ISSUE TITLE
[Bug]: 有的网站点翻译只翻译左侧目录，不翻译正文

### ISSUE THREAD

**Issue by gengruihuan** [immersive-translate/immersive-translate#1772]
### 插件版本号 | Version

1.5.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

我们自己公司的教研云网站做好讲义后，点翻译，只翻译左侧目录，不翻译正文，是识别bug吗？希望尽快适配修复一下
![1](https://github.com/immersive-translate/immersive-translate/assets/28974422/dedc477c-ff30-43a4-8653-bec8aefb3d45)

### 出现问题的网址 | URL

https://console.jiaoyanyun.com

### 重现步骤 | To Reproduce

你注册个账号，新建文档，最好分一二三级标题，然后点翻译，只翻译标题（而且乱码看不见），不翻译文章
![1](https://github.com/immersive-translate/immersive-translate/assets/28974422/a5c0ece4-a206-49ea-93cf-03b5a1e394d4)

**Comment by keyboard3** [comment]
这应该是你们公司使用了类似pre、code标签或者强制约定了notranslate。你可以通过沉浸式的快照功能生成一个网页快照链接发出来
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/f2cb71ba-9f56-4c03-a54e-4b7209d1ec32)

**Comment by gengruihuan** [comment]
> 这应该是你们公司使用了类似pre、code标签或者强制约定了notranslate。你可以通过沉浸式的快照功能生成一个网页快照链接发出来 ![image](https://private-user-images.githubusercontent.com/13177744/336324297-f2cb71ba-9f56-4c03-a54e-4b7209d1ec32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NTQzOTAsIm5iZiI6MTcxNzU1NDA5MCwicGF0aCI6Ii8xMzE3Nzc0NC8zMzYzMjQyOTctZjJjYjcxYmEtOWY1Ni00YzAzLWE1NGUtNGI3MjA5ZDFlYzMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDAyMjEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2NTM4N2NlODljZDY1ZWRiNGJlY2Y2MDEzNDMzZmZkMWJjYWU0Mzg1MDgyNGM3OWUyZGI3YTY3MjIwNDE0NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4nrFnEL3_PlpJEcfhBH09v2xV6TVxJv8fjxqT_f0xwI)

[https://readit.plus/a/xhdhl](https://readit.plus/a/xhdhl/w_cpak3v8f0r9g02ktm0r0)

**Comment by keyboard3** [comment]
这是因为你们后台的页面都是可编辑的，如果翻译就会导致译文干扰到原文编辑状态，可能就会将这类译文内容被网站保存。所以我们针对编辑状态的内容都不会进行翻译

**Comment by gengruihuan** [comment]
> 这是因为你们后台的页面都是可编辑的，如果翻译就会导致译文干扰到原文编辑状态，可能就会将这类译文内容被网站保存。所以我们针对编辑状态的内容都不会进行翻译

预览界面不能编辑，也无法翻译

**Comment by keyboard3** [comment]
> > 这是因为你们后台的页面都是可编辑的，如果翻译就会导致译文干扰到原文编辑状态，可能就会将这类译文内容被网站保存。所以我们针对编辑状态的内容都不会进行翻译
> 
> 预览界面不能编辑，也无法翻译

你发的那个页面是可以编辑的
