### ISSUE TITLE
增加自定义词库/术语表功能

### ISSUE THREAD

**Issue by bwy727** [immersive-translate/immersive-translate#1774]
### 您希望的更新和改进是什么 | Update or Improve

有道有个自定义术语表很好用，可以指定翻译成自己设定的意思。希望沉浸式翻译也能有。

**Comment by keyboard3** [comment]
沉浸式是个插件功能，术语需要翻译服务支持，你可以在沉浸式中选择有道和百度携带术语

**Comment by bwy727** [comment]
我说的是一种功能，而不是某种服务支持。请看下图：

![image](https://github.com/immersive-translate/immersive-translate/assets/149705207/3f0c4861-7b89-4441-a7c5-518ae09f4885)

这是有道词典翻译选项里的一项功能，可以自定义指定词汇的翻译内容。我的请求是希望沉浸式翻译可以增加类似的功能。

**Comment by keyboard3** [comment]
术语是属于翻译服务的能力，插件无法独立做这个功能，做了也是通过类似占位符实现，会导致翻译结果歧义

**Comment by bwy727** [comment]
请你忽略术语这个词，我只是用术语这个词举个例子。我的意思是自定义词语功能。我看到沉浸式翻译 “进阶设置” 中已经有了类似的功能：

![image](https://github.com/immersive-translate/immersive-translate/assets/149705207/894e5931-0277-4e0b-84b2-1859011546df)

可这个功能只能保持所设定词语不被转换，保持原样，而不是转换成为用户自定义的内容。

**Comment by keyboard3** [comment]
上面那个就是解释了我们没有做转换的原因，在很多情况下替换词语会导致整句话歧义，所以我们针对这个功能只原样保留单词
