### ISSUE TITLE
### 新功能 | New Feature

### ISSUE THREAD

**Issue by cammywhite** [immersive-translate/immersive-translate#1776]
### 新功能 | New Feature

1.希望能增加付费翻译失效后、自动切换到谷歌翻译的功能.
2.或者增加在特定网站指定特定翻译源的功能。

### 为什么您想要添加这些功能 | Why you want to add these features

1.我购买了DeepL的沉浸式翻译服务，但每个月只能翻译50万字，很快就会用完，每次都得手动切换。
2.如果这个功能无法实现的话，那么希望能增加在特定网站、指定特定翻译源的功能，比如我默认选择了谷歌翻译源，但在YOUTUBE上可以另外指定为DeepL翻译源（如果把DeepL只用在YOUTUBE上，一个月基本还是够用的）。

### 提议 | Proposal

关于第一条建议不知道怎么实现，但第二条建议，我认为可以在插件界面的【总是翻译该网站】下边，再增加一行【总是用（○○○翻译服务）翻译该网站】。
或者在进阶设置里增加一行【总是用（○○○翻译服务）翻译○○○网站】。

而因为不同翻译源擅长的语言不同，如果能再增加【总是用（○○○翻译服务）翻译○○○语】就更好了。

_Originally posted by @cammywhite in https://github.com/immersive-translate/immersive-translate/discussions/1775_

**Comment by keyboard3** [comment]
https://immersivetranslate.com/docs/advanced/#%E7%BF%BB%E8%AF%91%E6%9C%8D%E5%8A%A1%E9%85%8D%E7%BD%AE

![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/c97d0586-4bfc-4e14-88fc-e6292322ec29)
