### ISSUE TITLE
Roman Urdu Translation Integration 🙏

### ISSUE THREAD

**Issue by UsmanMaqbool** [immersive-translate/immersive-translate#1778]
### 您希望的更新和改进是什么 | Update or Improve

Urdu language generally writes from right to left. Translating Pdf is causing a lot of issue in terms of writing modes. 
I'm requesting to an translation option of Roman Urdu or Latinized Urdu.
For example: 
**English:** However, images geographically close to each other do not necessarily share overlapping regions.
**Urdu:** ہاں لیکن ایسی تصاویر جو جغرافیائی طور پر ایک دوسرے کے قریب ہوتی ہیں ان میں ضروری نہیں کہ اوورلیپنگ علاقے ہوں۔
**Roman Urdu:** Haan lekin aisi tasweerain jo geographical taur par aik dusre ke qareeb hoti hain un mein zaroori nahin ke overlapping ilaqay hon.

It will help a lot!. **all the LLM models can help in translating.** I dont know how to add such customized language support. 
I've used OpenAI ChatGPT, LLama3, both works great.

Thanks in Advance

**Comment by keyboard3** [comment]
Are you suggesting to add Roman Urdu or Latinized Urdu to OpenAI?

**Comment by theowenyoung** [comment]
Is Roman Urdu written from right to left or from left to right?

**Comment by UsmanMaqbool** [comment]
Thanks for the reply. It's written same like English from Left to Right. 
It's kind of transiliteration of Urdu. 

Actually Roman Urdu is the representation of the Urdu language using the Latin/English alphabet instead of the traditional Perso-Arabic script. This form of writing Urdu is particularly popular in digital communication, like on social media, messaging apps, and informal writing, where users might find it easier to type using a Latin keyboard.

For example:
- Urdu in Perso-Arabic script: "میں ٹھیک ہوں"
- Roman Urdu: "Main theek hoon"
- English translation: "I am fine"

**Comment by theowenyoung** [comment]
谢谢您的澄清，我们将在下个版本为 OpenAI 添加 Roman Urdu 的支持。

**Comment by flamintune** [comment]
we already support using openai to translate Roman Urdu in version 1.6.3. Welcome to update the extension in time.

**Comment by flamintune** [comment]
sorry, it seemd like we forget to add it to the pdf app. now you can pick Roman Urdu in the pdf app.
![image](https://github.com/user-attachments/assets/554d1f59-2118-4235-abd1-7d16ab28436b)
