### ISSUE TITLE
多处标记内容翻译错误

### ISSUE THREAD

**Issue by Vixb1122** [immersive-translate/immersive-translate#178]
地址：https://developer.android.google.cn/jetpack/compose/animation

![image](https://user-images.githubusercontent.com/17810492/221887671-f32d6275-d410-426b-b171-d1506848ed5f.png)
![image](https://user-images.githubusercontent.com/17810492/221887895-aafc5a18-65d6-416c-87b1-031269917e28.png)

**Comment by theowenyoung** [comment]
谢谢反馈，是bug，下个版本修复。

**Comment by theowenyoung** [comment]
可以了，新版修复了一下～

**Comment by Vixb1122** [comment]
试了一下，只有第二张图的修复了，第一张图的问题还在。
![image](https://user-images.githubusercontent.com/17810492/222083409-4fc2b7b1-2b51-466c-825c-880d685502a1.png)
![image](https://user-images.githubusercontent.com/17810492/222083372-2de39ea2-7670-408f-84b1-5f887a06fff5.png)

**Comment by theowenyoung** [comment]
确认，最新版本已修复～
