### ISSUE TITLE
最新版本插件PDF翻译时一页英文后面会有三页同样的中文

### ISSUE THREAD

**Issue by lambs13** [immersive-translate/immersive-translate#1780]
### 插件版本号 | Version

1.5.8

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

整个PDF每一页英文后面都跟着3页一模一样的中文翻译

### 重现步骤 | To Reproduce

所有的PDF文档翻译都这样

### 补充说明 | Additional context

![image](https://github.com/immersive-translate/immersive-translate/assets/55617991/a7bef25c-48cd-4fc6-aa4b-735eafc4a331)

**Comment by keyboard3** [comment]
刷新下已修复
