### ISSUE TITLE
Cancel or collapse the taskbar in the PDF function

### ISSUE THREAD

**Issue by zhubing96** [immersive-translate/immersive-translate#1781]
### 您希望的更新和改进是什么 | Update or Improve

I suggest either removing or collapsing the toolbar at the top of the PDF feature, as it reduces the reading space for PDFs, which is particularly important given that most users are on laptops.

### 补充说明 | Additional context

![图片_1](https://github.com/immersive-translate/immersive-translate/assets/131648116/952f636e-b600-4a43-bc2f-6cfc1553ec36)

**Comment by ffawei-6** [comment]
Cancel or collapse it, please. It takes up too much room

**Comment by FattySpring** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/25144301/4ba8eedf-0105-47d3-ac52-9a74e809e668)

Hiding has been supported

**Comment by zhubing96** [comment]
谢谢，taskbar占用空间问题已被解决。建议将"隐藏顶部"改为"默认隐藏顶部"，因为每次启动pdf翻译功能时需要点击。

**Comment by ffawei-6** [comment]
如果可以的话建议能把整个栏都隐藏起来， 或者把栏做的和旧版的一样细，因为laptop用户真的对于屏占比例很敏感，感谢！

**Comment by FattySpring** [comment]
> 如果可以的话建议能把整个栏都隐藏起来， 或者把栏做的和旧版的一样细，因为laptop用户真的对于屏占比例很敏感，感谢！

暂无此计划
