### ISSUE TITLE
1.5.8更新后chrome翻译pdf上方的bar太占屏幕空间

### ISSUE THREAD

**Issue by zhaoliang0302** [immersive-translate/immersive-translate#1782]
### 您希望的更新和改进是什么 | Update or Improve

![image](https://github.com/immersive-translate/immersive-translate/assets/42333702/5a74b45e-ab10-493a-a939-8a579c8854f5)
最上方的bar个人认为用处不大，14寸电脑占用屏幕空间很大，能否优化布局使屏幕空间利用最大化，谢谢

**Comment by zhubing96** [comment]
+1,建议删除或折叠

**Comment by ffawei-6** [comment]
是的，强烈建议删除，或者设置为可调节关闭！

**Comment by ffawei-6** [comment]
对小屏使用者来说真的很占空间，哭了，建议优化界面布局，实现屏幕空间利用效益最大化，谢谢！

**Comment by FattySpring** [comment]
感谢您反馈！这个问题已经在 #1781  被报告过了。为了保持讨论的连贯性，我们将关闭这个重复的 issue。请在原来的 issue 中跟进，以获取最新的更新和信息。
