### ISSUE TITLE
[Bug]: service Worker（无效），插件失效

### ISSUE THREAD

**Issue by YummyLau** [immersive-translate/immersive-translate#1783]
### 插件版本号 | Version

1.5.8

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

插件失效，插件扩展显示Service worker无效，chrome版本 125.0.644.142（arm64）

### 出现问题的网址 | URL

任何一个页面

**Comment by keyboard3** [comment]
闲置的 Service worker 会自动被chrome挂起节约内存。 需要的时候会自动调用唤醒。 不影响正常使用

**Comment by YummyLau** [comment]
"background": {
      "service_worker": "background.js"
   },

**Comment by YummyLau** [comment]
> 闲置的 Service worker 会自动被chrome挂起节约内存。 需要的时候会自动调用唤醒。 不影响正常使用

那如何处理呢

**Comment by YummyLau** [comment]
现在是功能失效。功能没有任何反应

**Comment by YummyLau** [comment]
悬浮球也没有显示，理解应该是视图注入失败

**Comment by keyboard3** [comment]
插件关闭重新启用之后呢？

**Comment by YummyLau** [comment]
一样，卸载重启很多次了

**Comment by keyboard3** [comment]
重新安装，录个完整的视频看下看

**Comment by YummyLau** [comment]
由于是公司的设备不方便录制，我尝试过：

**Comment by keyboard3** [comment]
感觉浏览器不太正常，要不试试装个油猴插件，然后去沉浸式官网 https://immersivetranslate.com/ 装个油猴脚本看

**Comment by keyboard3** [comment]
暂无反馈，暂时关闭这个问题
