### ISSUE TITLE
 适配Chrome浏览器新推出的Google 学术搜索 PDF 阅读器

### ISSUE THREAD

**Issue by yrqUni** [immersive-translate/immersive-translate#1784]
### 您希望的更新和改进是什么 | Update or Improve

最近Google为Chrome浏览器开发了新的插件Google 学术搜索 PDF 阅读器，用作Chrome浏览器打开PDF的首选方式。我注意到目前翻译器无法像适配Google 学术搜索 PDF 阅读器，或许可以像适配Google原始PDF阅读器那样适配一下Google 学术搜索 PDF 阅读器？

**Comment by keyboard3** [comment]
它一个浏览器插件，插件无法干预插件，这个没有办法
