### ISSUE TITLE
🔴 关于「阿里云百炼大模型」和「DeepSeek」使用「AI 专家」的问题，以及一些功能上的建议

### ISSUE THREAD

**Issue by Thomas-Harrell** [immersive-translate/immersive-translate#1787]
### 您希望的更新和改进是什么 | Update or Improve

---

> 沉浸式翻译版本为：1.6.2

- 如图 1 所示，模型 qwen-turbo 使用「AI 专家 意译大师」后，会出现一些多余的提示词文字，但是 qwen-long 和 qwen-plus 模型都没有出现这个问题

- 如图 2 所示，「阿里云百炼大模型」和「DeepSeek」的 Subtitle Prompt 为空，而 Multiple Prompt 里面的内容原本应该是放在 Subtitle Prompt 的位置吧？看「百度千帆大模型」的提示词是满满当当的

- 继续如图 2 所示，「阿里云百炼大模型」和「DeepSeek」是中文模型，使用中文提示词的效果会不会好一些？默认的提示词和 AI 专家里面的提示词都是英语的

- 如图 3，4 所示，「阿里云百炼大模型」和「DeepSeek」在选择「AI 专家」后，下面的选项还是处于可编辑状态；而 OpenAI 服务在选择「AI 专家」后，连「自定义 API 接口地址」选项都会处于不可编辑的灰色状态。不知道是 BUG 的缘故还是就是这样设计的

---

- 在「插件设置 - 基本设置」页面的右上角有一个「重置设置」按钮，如果在每个设置页面（如：视频字幕、输入框增强、鼠标悬停、进阶设置等等之类）的右上角都添加一个「重置设置」按钮，只用于重置「当前页面设置」，可以大大提升使用体验

- 还有一些小样式，关于「YouTube」的「T」是需要大写的，但是有些地方使用了小写的「t」。截图只举例了一些地方，有一几处是没有截图的

### 补充说明 | Additional context

<img width="798" alt="SCR-20240609-cult" src="https://github.com/immersive-translate/immersive-translate/assets/106761803/240fd4ee-3887-4103-af98-713a9376b560">

---

![SCR-20240609-cvlc](https://github.com/immersive-translate/immersive-translate/assets/106761803/d5b44f19-4df2-4c90-bd66-0c561d083983)

---

<img width="616" alt="SCR-20240609-cwab" src="https://github.com/immersive-translate/immersive-translate/assets/106761803/0af01b4b-d0c4-45e3-a7df-e0e9e2bde968">

---

<img width="690" alt="SCR-20240609-cwfg" src="https://github.com/immersive-translate/immersive-translate/assets/106761803/da54d5f2-9d6d-4e12-8612-34ab09ef7e1a">

---

![SCR-20240609-dedw](https://github.com/immersive-translate/immersive-translate/assets/106761803/50f4cba1-075c-46ab-a8be-dfd4e97bf8de)

---

<img width="627" alt="SCR-20240609-dela" src="https://github.com/immersive-translate/immersive-translate/assets/106761803/3a50634f-1da2-4e7a-b749-48bf8507789d">

**Comment by flamintune** [comment]
感谢指出bug，

> 如图 2 所示，「阿里云百炼大模型」和「DeepSeek」的 Subtitle Prompt 为空，而 Multiple Prompt 里面的内容原本应该是放在 Subtitle Prompt 的位置吧？看「百度千帆大模型」的提示词是满满当当的

> 如图 3，4 所示，「阿里云百炼大模型」和「DeepSeek」在选择「AI 专家」后，下面的选项还是处于可编辑状态；而 OpenAI 服务在选择「AI 专家」后，连「自定义 API 接口地址」选项都会处于不可编辑的灰色状态。不知道是 BUG 的缘故还是就是这样设计的

这两个已修复，进入这个[页面](https://dash.immersivetranslate.com/#about)更新下适配规则

关于提示词的问题，可能需要再测一下，有后续会在 本 issue 更新进展

**Comment by flamintune** [comment]
两个都是 bug，下个版本修复该问题，正确逻辑是：

启动 AI 专家后，prompt 等与 AI 专家设置相关的应当不可编辑，但 API 接口地址应当是可以编辑的

**Comment by keyboard3** [comment]
此问题是自定义配置超过chrome存储限制，下一版优化
