### ISSUE TITLE
🔴 [Bug]: 在「阿里云百炼大模型」下会出现字幕漏翻的问题

### ISSUE THREAD

**Issue by Thomas-Harrell** [immersive-translate/immersive-translate#1789]
### 插件版本号 | Version

1.6.2

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

- 如果在「阿里云百炼大模型」里面调用「通义千问」模型，会出现字幕漏翻的问题

- 播放视频一两分钟左右会出现一次，连续漏掉 3 - 4 条字幕的翻译

- 但是如果在「OpenAI」里面调用「通义千问」模型，这个问题就不会出现

- 或者将「每次字幕请求最大段落数」从默认值 3 改为 1，也可以避免这个问题

- 测试了 `qwen-long`、`qwen-trubo`、`qwen-plus` 都会这样，「DeepSeek」也会有同样的问题

- 测试是在关闭并清空「本地翻译缓存」的情况下进行的，并且已经重置了「阿里云百炼大模型」的设置

![SCR-20240610-cfrv](https://github.com/immersive-translate/immersive-translate/assets/106761803/36a2fccf-162f-4b91-9ad0-70345f7a94c1)

### 出现问题的网址 | URL

https://www.youtube.com/watch?v=8reaJG7z-is

**Comment by keyboard3** [comment]
这个就是大模型不遵守提示词导致的，字幕段落数调整到1就可以了

**Comment by keyboard3** [comment]
两个设置的请求都抓个包，对比下
