### ISSUE TITLE
大佬，能否加一个选项可以把原文用翻译后的文本替换掉？

### ISSUE THREAD

**Issue by zoverdoser** [immersive-translate/immersive-translate#179]
大佬，能否加一个选项可以把原文用翻译后的文本替换掉，想看原文的话鼠标hover后再显示原文？

**Comment by HKTY569** [comment]
> 大佬，能否加一个选项可以把原文用翻译后的文本替换掉，想看原文的话鼠标hover后再显示原文？

就和谷歌浏览器自带的那种就就挺好

**Comment by theowenyoung** [comment]
这个功能在计划中，相关issues：

- https://github.com/immersive-translate/immersive-translate/issues/59
