### ISSUE TITLE
[Bug]: Compatibility with other browser extenion

### ISSUE THREAD

**Issue by galaxypayoff** [immersive-translate/immersive-translate#1794]
### 插件版本号 | Version

1.6.2

### 平台 | Platform

Windows, Android

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

Immersive Translate used to work (about version 0.12.5) with other browser extensions (specifically this one [Chinese Words Separator](https://chromewebstore.google.com/detail/chinese-words-separator-c/gacfacdpfimbkgcnlegknnmcccjgcbnp)) to shows pinyin and dictionary.
After generating the translation, you can get pinyin to show up:
![image](https://github.com/immersive-translate/immersive-translate/assets/166029599/8af01118-84d7-493c-b578-2b062e2228a8)
Then hover over Chinese text for dictionary pop-up:
![image](https://github.com/immersive-translate/immersive-translate/assets/166029599/7794e41e-8bea-4363-af91-36f59ccd4085)
This was super helpful for language learning.

Newer versions don't allow this anymore, the inserted translations would just disappear. Is it possible to make Immersive Translate compatible with other extensions again?

### 出现问题的网址 | URL

https://chromewebstore.google.com/detail/chinese-words-separator-c/gacfacdpfimbkgcnlegknnmcccjgcbnp

**Comment by galaxypayoff** [comment]
Sorry, videos will be easier.

This is how it was with older version of Immersive Translate (v. 0.12.5):

https://github.com/immersive-translate/immersive-translate/assets/166029599/ae344ed0-7629-409d-ad60-5e57dcf8f84e



The inserted translation would persist.

This is how it is with current version of Immersive Translate, the inserted translation would disappear:

https://github.com/immersive-translate/immersive-translate/assets/166029599/25ca92d1-53bd-49ba-bc83-6b55c2d28e6d

**Comment by keyboard3** [comment]
打开面板，更新一下规则，然后重新尝试一下。
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/25a0f189-3ce6-4430-a959-f4a3032943a3)

**Comment by galaxypayoff** [comment]
It's fixed now, thank you so much!!!
