### ISSUE TITLE
[Bug]: 推特上的繁体字无法被翻译为简体

### ISSUE THREAD

**Issue by ShixianShe** [immersive-translate/immersive-translate#1795]
### 插件版本号 | Version

1.0.1

### 平台 | Platform

macOS, iOS

### 浏览器 | Browsers

Safari, Other

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

繁体似乎无法触发翻译

**Comment by keyboard3** [comment]
你版本有点低，升级一下

**Comment by ShixianShe** [comment]
> 你版本有点低，升级一下

不好意思版本打错了，我是最新的1.6.2

**Comment by keyboard3** [comment]
选的什么翻译服务

**Comment by ShixianShe** [comment]
deepseek和open ai的都用过


| |
佘实现
暨南大学光学工程硕士研究生
|
|
18065727569
***@***.***
广东省广州市番禺区南村镇兴业大道东855号暨南大学南校区光子技术研究院
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年06月13日 10:55 |
| 收件人 | ***@***.***> |
| 抄送人 | ShixianShe ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [immersive-translate/immersive-translate] [Bug]: 推特上的繁体字无法被翻译为简体 (Issue #1795) |

选的什么翻译服务

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/24e39d28-2a7d-47b7-99f0-7fc58364d7bd)
打开面板看下你原文检测是不是繁体中文，如果不是请指定下
