### ISSUE TITLE
关于一次性一键开关

### ISSUE THREAD

**Issue by duwei-coder** [immersive-translate/immersive-translate#180]
希望大佬能够用一个快捷键  例如 F11等一键开关   比如进入某个网页之后 我可以按一下 f11  就会自动打开并且翻译  翻译完毕之后就会又是关闭插件的状态  希望油猴和这个强大的插件对接好能支持这样的功能  这样就能节约API的调用翻译的字数

**Comment by theowenyoung** [comment]
现在的设置页面里的快捷键就是做这件事的吧？

默认的快捷键是 `alt+a` , 进入页面 按 `alt+a` 就会翻译，然后进入下一个页面，也不会自动翻译的。每次都需要按快捷键才能翻译

**Comment by duwei-coder** [comment]
> 现在的设置页面里的快捷键就是做这件事的吧？
> 
> 默认的快捷键是 `alt+a` , 进入页面 按 `alt+a` 就会翻译，然后进入下一个页面，也不会自动翻译的。每次都需要按快捷键才能翻译

不行啊  现在alt+a只能是当前页面不翻译  但是跳到其他新的页面的时候还是会继续翻译的.我刚刚试了的

**Comment by theowenyoung** [comment]
你是不是开启了 自动翻译 英语？ 或者永远翻译该网址？

**Comment by duwei-coder** [comment]
> 你是不是开启了 自动翻译 英语？ 或者永远翻译该网址？

是的  自动翻译英语   谢谢
