### ISSUE TITLE
[Bug]: 百度千帆大模型 Token拼接错误

### ISSUE THREAD

**Issue by Junxiao-Liao** [immersive-translate/immersive-translate#1800]
### 插件版本号 | Version

1.6.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

`错误原因：Access token invalid or no longer valid`

### 出现问题的网址 | URL

moz-extension://.../options.html#services/qianfan

### 重现步骤 | To Reproduce

在插件中`点此测试服务`, 或者在网页中调用服务

### 补充说明 | Additional context

- 确认账号还有余额
- 尝试重新生成API Key和Secret Key, 依然报同样的错误

**Comment by flamintune** [comment]
能否再提供下错误码

**Comment by flamintune** [comment]
下个版本修复该问题

**Comment by flamintune** [comment]
1.6.3已修复该问题，欢迎及时更新插件
