### ISSUE TITLE
希望推出自定义单词本，支持部分单词自定义译文或不翻译。并将此功能放在悬浮按钮里，方便操作

### ISSUE THREAD

**Issue by DuanChangfeng0708** [immersive-translate/immersive-translate#1802]
### 您希望的更新和改进是什么 | Update or Improve

作为一名程序员，很多时候需要去阅读外文，很多单词是一些专用名词，翻译的不对或者不用翻译。翻译了反而会造成我的误解。（我使用沉浸式翻译的初衷就是害怕有的翻译不对，我可以自己阅读原文以修正）。 如果可以自定义单词本，那就很完美了， 参考Edge插件《火山翻译》。

**Comment by theowenyoung** [comment]
火山翻译有自己的翻译引擎，所以可以在服务端做一些专业术语的优化。

为了实现类似的能力，沉浸式翻译的【进阶设置】里可以指定一些单词保持原样。
