### ISSUE TITLE
[Bug]: 翻译服务或网络似乎出了点问题... 

### ISSUE THREAD

**Issue by geekgao** [immersive-translate/immersive-translate#1803]
### 插件版本号 | Version

1.6.2

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

使用快捷键翻译部分文字，会有错误提示：
翻译服务或网络似乎出了点问题...
Rejected to access, please check user and token value, or contact with transmart@tencent.com

**但是当前并未使用腾讯的翻译服务，用的是Google。**

### 出现问题的网址 | URL

任何

### 重现步骤 | To Reproduce

随意找个英文网页，用快捷键翻译部分文字

**Comment by keyboard3** [comment]
1.6.3 已修复，等商店更新
