### ISSUE TITLE
[Bug]: 翻译接口链接在不同网络环境下互相冲突

### ISSUE THREAD

**Issue by NealDeal34** [immersive-translate/immersive-translate#1804]
### 插件版本号 | Version

1.6.2

### 平台 | Platform

Windows, Android

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

  能够使用google翻译的网络环境下微软翻译就无法使用，频繁切换网络的同时就要反复切换默认首选翻译器，否则只能等待很久服务器无响应后点击retry或弹出切换弹窗，能否引入多线程ping之类的逻辑实现根据延迟自动选择默认翻译器，或引入优先级首选与备选自动择优切换功能，实现更快速稳定的翻译而不是报错再手动切换？

**Comment by theowenyoung** [comment]
正常来说，微软翻译在中国和国外都能访问的。

引入自动切换翻译服务会带来额外的复杂性，用户也无法感知当前使用的翻译服务是什么。

建议结合网络情况选择一个稳定的翻译服务。
