### ISSUE TITLE
[Bug]: 1.6以上版本开启“自动开启双语字幕（当前支持的所有视频平台）”会造成YouTube中文字幕不显示

### ISSUE THREAD

**Issue by gggccc44** [immersive-translate/immersive-translate#1806]
### 插件版本号 | Version

1.6.3

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

1.6以上版本开启“自动开启双语字幕（当前支持的所有视频平台）”会造成YouTube中文字幕不显示，降级到1.5.8正常

### 出现问题的网址 | URL

https://www.youtube.com/watch?v=lE2SyQnJyrc

### 重现步骤 | To Reproduce

我的设置

YouTube 自动开启双语字幕  关闭
使用沉浸式翻译来翻译 YouTube 字幕 关闭
自动开启双语字幕（当前支持的所有视频平台）  开启
优先使用人工字幕  开启

### 补充说明 | Additional context

“自动开启双语字幕（当前支持的所有视频平台）”如果关闭可以正常显示中文字幕。

扩展未测试，我使用脚本方式就是因为这样遇到bug降级会更简单

**Comment by FattySpring** [comment]
是否使用了仅译文显示字幕

**Comment by gggccc44** [comment]
> 是否使用了仅译文显示字幕

确实设置了仅译文，但是1.5.8正常说明是新版的问题
