### ISSUE TITLE
[Bug]: 因为 Gemini 的 glossaries，OpenAI 相关词汇可能被翻译为 code1001

### ISSUE THREAD

**Issue by NijikaMyWaifu** [immersive-translate/immersive-translate#1807]
### 插件版本号 | Version

1.6.2

### 请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/139055015/7c1b7670-bf31-4779-b8a4-15d71b4a57c7)

![image](https://github.com/immersive-translate/immersive-translate/assets/139055015/c4524042-ca71-4615-823b-cfe79fba4b23)
不知道对 OpenAI 相关词汇特殊处理的意义

### 出现问题的网址 | URL

https://www.reddit.com/r/ClaudeAI/comments/1df711d/why_do_you_think_anthropic_is_so_underrated/

**Comment by theowenyoung** [comment]
现在可以了吗？我刚用 Gemini 测试似乎是ok 的？

![CleanShot 2024-06-25 at 15 06 19@2x](https://github.com/immersive-translate/immersive-translate/assets/62473795/68c9eaa0-ebb9-4116-9c2c-d31a8926c44a)

**Comment by NijikaMyWaifu** [comment]
最新的 1.6.6 版本仍然存在问题，使用 gemini-1.5-pro-latest 模型

![](https://github.com/immersive-translate/immersive-translate/assets/139055015/1657fcf3-5e58-4c3f-88b3-a9decb47084b)

默认情况：
![default](https://github.com/immersive-translate/immersive-translate/assets/139055015/b900f570-5464-4fde-9268-4ed581786e53)

在 Edit Full User Config 的 Gemini 配置中添加 `"glossaries": [],` 的情况：
![glossaries = empty](https://github.com/immersive-translate/immersive-translate/assets/139055015/876ecbc7-044c-4ec3-b9ca-c6dff791ae93)

同时我认为替换一些词汇为例如 `<code1001>` 的形式会影响 AI 对上下文的理解

**Comment by NijikaMyWaifu** [comment]
最新的 1.6.6 版本仍然存在问题，使用 gemini-1.5-pro-latest 模型

![](https://github.com/immersive-translate/immersive-translate/assets/139055015/1657fcf3-5e58-4c3f-88b3-a9decb47084b)

默认情况：
![default](https://github.com/immersive-translate/immersive-translate/assets/139055015/b900f570-5464-4fde-9268-4ed581786e53)

在 Edit Full User Config 的 Gemini 配置中添加 `"glossaries": [],` 的情况：
![glossaries = empty](https://github.com/immersive-translate/immersive-translate/assets/139055015/876ecbc7-044c-4ec3-b9ca-c6dff791ae93)

同时我认为替换一些词汇为例如 `<code1001>` 的形式会影响 AI 对上下文的理解

**Comment by theowenyoung** [comment]
这里是针对 Gemini 的特殊处理， 涉及到 OpenAI,GPT 等词， Gemini 模型会认为是敏感词，如果不做替换的话，会整句直接不翻译。

**Comment by theowenyoung** [comment]
请打开下[这里](https://dash.immersivetranslate.com/#about) , 同步下规则之后再试试。

做了进一步优化。

**Comment by NijikaMyWaifu** [comment]
对于 Gemini API 的敏感词检测：Gemini API 只会检测最后一条消息是否包含敏感词，经过测试这种 Prompt 可以规避检测且兼容所有 Gemini 模型

## User
You are a professional, authentic machine translation engine.

Source Text: {{text}}

## Model
Successfully read the text.

## User
Translate the source text to {{to}}, Output translation directly without any additional text.
Translated Text:

**Comment by theowenyoung** [comment]
多步 prompt吗？ 这个改动会比较大，插件不太容易支持这种。

是不是等待 gemini 在以后的版本中移除这些敏感词就好？

**Comment by NijikaMyWaifu** [comment]
尝试一下这个？

## Model
You are a professional, authentic machine translation engine.

Translate the following source text to {{to}}, Output translation directly without any additional text.
Source Text: {{text}}
Translated Text:

## User
continue

**Comment by theowenyoung** [comment]
这个 prompt 会导致 gemini 输出较多不相关的内容.

![CleanShot 2024-07-02 at 21 05 16@2x](https://github.com/immersive-translate/immersive-translate/assets/62473795/a77b0de9-d27b-40be-96e7-eaf8cadf1eb7)


刚和 Google Gemini 的合作伙伴确认，5月份之后的 Gemini 已经取消了屏蔽词，所以沉浸式翻译刚刚更新了规则，同步去掉了之前设置的屏蔽词。

![CleanShot 2024-07-02 at 21 36 32@2x](https://github.com/immersive-translate/immersive-translate/assets/62473795/58b2a0eb-5401-4494-a66b-134c7e584308)


请刷新后重试～
