### ISSUE TITLE
更新过后翻译PDF，原文原本能进行选择搜索的，现在变成图片了

### ISSUE THREAD

**Issue by zjx863** [immersive-translate/immersive-translate#1808]
### 您希望的更新和改进是什么 | Update or Improve

希望保留原来的功能，之前的原文如果不是图片，翻译后的原文也可以选择搜索，这样双语对照看的时候如果机翻不准还可以复制去其他翻译工具。现在改成翻译完双语的页面都不可选择搜索了

### 补充说明 | Additional context

None

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/59c063b1-92c3-4a10-97dd-b89e54ff38f9)
可以搜索呀
