### ISSUE TITLE
[Bug]: 使用Adobe Acrobat作为默认Pdf阅读器后，点击翻译PDF功能失效

### ISSUE THREAD

**Issue by Jack251970** [immersive-translate/immersive-translate#1811]
### 插件版本号 | Version

1.6.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在Egde中，我将下载了Adobe Acrobat插件，并将其作为浏览器的默认PDF打开器。
但我希望对某个打开的PDF进行翻译时，其出现的界面是空。

<img width="1259" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/53996452/47d52bdf-c0d9-4087-9002-b4e4b7ef0fd9">

似乎无法处理浏览器插件的链接：extension://amkbmndfnliijdhojkpoglbnaaahippg/pdf/index.html?file=chrome-extension%3A%2F%2Fefaidnbmnnnibpcajpcglclefindmkaj%2Ffile%3A%2F%2F%2FC%3A%2FUsers%2F11602%2FOneDrive%2F%25E6%2596%2587%25E6%25A1%25A3%2FMy-Data%2F%25E6%25A8%25A1%25E5%25BC%258F%25E8%25AF%2586%25E5%2588%25AB%25E8%25AF%25BE%25E8%25AE%25BE%2FQuantifying_and_Detecting_Collective_Motion_in_Crowd_Scenes.pdf。

### 重现步骤 | To Reproduce

在Microsoft Edge浏览器中从Chorme商店下载Adobe Acrobat并将其作为默认PDF阅读器。
打开本地PDF文件，并点击 翻译PDF 按钮。

**Comment by keyboard3** [comment]
好的 将在1.6.4 兼容
