### ISSUE TITLE
请更新支持一下AfreecaTV的UI翻译

### ISSUE THREAD

**Issue by Jayesslee1** [immersive-translate/immersive-translate#1812]
### 您希望的更新和改进是什么 | Update or Improve

目前不支持AfreecaTV，AfreecaTV于近期停止了其他语言的支持，请更新支持一下网站UI翻译！谢谢
![Uploading QQ截图20240617202847.png…]()

**Comment by keyboard3** [comment]
你的图没发出来，不懂你的需求

**Comment by Jayesslee1** [comment]
![QQ截图20240617202847](https://github.com/immersive-translate/immersive-translate/assets/62415418/2cd4d289-a0f0-4143-bf51-7ead7fde237f)

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/a0ca40da-a820-4d03-9214-239c1a10acff)
翻译很正常，打开悬浮球的面板看下

**Comment by Jayesslee1** [comment]
好的 谢谢，已解决
