### ISSUE TITLE
[Improvement] Request translation support for .vtt subtitle.

### ISSUE THREAD

**Issue by moleoxa** [immersive-translate/immersive-translate#1813]
### 您希望的更新和改进是什么 | Update or Improve

> https://app.immersivetranslate.com/subtitle/

This function only support .srt and .ass subtitle now. Since .vtt can be converted to .srt loselessly, I request an improvement to support .vtt subtitle.

### 补充说明 | Additional context

- While an input is .vtt file, output is not necessary to keep the same format.
- Can this option be stored in settings? Its effective scope is limited to the current conversion now.
![图片](https://github.com/immersive-translate/immersive-translate/assets/147070258/bda4acd2-ee32-4ab6-8529-ffbb87b40d09)

**Comment by TaoLoading** [comment]
vtt 字幕翻译功能已上线；考虑到大众用户，选项存储功能暂无开发计划。感谢建议
