### ISSUE TITLE
增加一个选项可以选择不翻译网页标题

### ISSUE THREAD

**Issue by tacitli** [immersive-translate/immersive-translate#1814]
### 您希望的更新和改进是什么 | Update or Improve

希望能够增加一个选项，允许用户选择是否翻译网页标题。目前，在使用immersive translate插件时，网页标题会被自动翻译。但多数情况下译文因为字节过长无法看到原文标题。

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/f2dec962-32f1-4d45-ab46-cc3c0093be3d)
