### ISSUE TITLE
[Bug]: 腾讯交互翻译失效

### ISSUE THREAD

**Issue by tanyuhe** [immersive-translate/immersive-translate#1815]
### 插件版本号 | Version

1.62

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

使用腾讯交互翻译时失效，无法翻译

**Comment by keyboard3** [comment]
问题重复 https://github.com/immersive-translate/immersive-translate/issues/1803
