### ISSUE TITLE
[Bug]: 输入框翻译连按三次空格没有任何反应

### ISSUE THREAD

**Issue by leon0333** [immersive-translate/immersive-translate#1816]
### 插件版本号 | Version

V1.6.3

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 请描述这个Bug | Describe the bug

输入框翻译连按三次空格没有任何反应,同时我对中/英标点都进行了替换。

### 出现问题的网址 | URL

google.com

### 重现步骤 | To Reproduce

随机在输入框内输入中文内容
连按三下，无任何反应

### 补充说明 | Additional context

无

**Comment by keyboard3** [comment]
不要在不带网址的页面尝试。 具体测试请参考 https://immersivetranslate.com/docs/input/#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
