### ISSUE TITLE
请恢复到以前youtube翻译自动展开“长”文

### ISSUE THREAD

**Issue by crysishacker** [immersive-translate/immersive-translate#1818]
### 您希望的更新和改进是什么 | Update or Improve

现在youtube翻译出现离谱的问题，很多评论都要我点击一次“阅读更多”展开中文翻译，更离谱在于原本英文都不用展开长文，中文只显示一行，然后要我次次都点击
更加别说以前youtube评论哪怕英文需要点击展开长文都好，沉浸式翻译都会默认展开并翻译
youtube没有多少超长评论，过往的设计非常方便
现在是越改越难用了

**Comment by keyboard3** [comment]
并不会默认展开翻译，因为展开与否是YouTube自己控制，它根据原文自己控制的。你说的自动展开应该是YouTube自己的设置，跟沉浸式无关
