### ISSUE TITLE
[Bug]: 1.6.3版本会导致YouTube视频自带的简体中文字幕显示出现问题

### ISSUE THREAD

**Issue by lianwensheng** [immersive-translate/immersive-translate#1820]
### 插件版本号 | Version

1.6.3

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

1.6.3版本YouTube视频自带的简体中文字幕会按照“原文字体设置”显示
![屏幕截图 2024-06-19 054623](https://github.com/immersive-translate/immersive-translate/assets/36002202/79bfb015-2f20-42de-a096-aea1f4913c16)

因为之前字幕原文基本都是外语，所以字幕原文字体大小会设置的比译文小很多，原文和译文的字体也设置的不一样，导致新版本一旦调用自带简体中文字幕就出现问题了
![屏幕截图 2024-06-19 054709](https://github.com/immersive-translate/immersive-translate/assets/36002202/293a53d9-d276-402f-ab32-73fc54b1b5b8)

建议改成YouTube视频自带的“目标语言”字幕按照“译文字体设置”显示，这样双语和单语字幕显示效果都比较统一。
![屏幕截图 2024-06-19 054936](https://github.com/immersive-translate/immersive-translate/assets/36002202/2544d76b-d82d-4f5a-bab9-da12176074b7)

**Comment by keyboard3** [comment]
自带按照原文显示符合预期呀，因为确实不是译文，只有是译文内容才会应用译文样式

**Comment by FattySpring** [comment]
1.6.5 已支持
