### ISSUE TITLE
[Bug]: 无法翻译按钮文字

### ISSUE THREAD

**Issue by gengjiawen** [immersive-translate/immersive-translate#1821]
### 插件版本号 | Version

1.6.3

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![CleanShot 2024-06-19 at 11 07 48@2x](https://github.com/immersive-translate/immersive-translate/assets/3759816/f70a0b55-fe0b-4478-a138-85985eb9ddbf)

### 出现问题的网址 | URL

https://store-jp.nintendo.com/list/software/70070000015223.html

**Comment by keyboard3** [comment]
https://dash.immersivetranslate.com/#about 打开面板自动更新规则之后刷新页面试下

**Comment by gengjiawen** [comment]
thx, it works.

**Comment by gengjiawen** [comment]
@keyboard3 这个问题重新出现了
