### ISSUE TITLE
您好，可否增加支持一次翻译多个本地翻译SRT文件呢？

### ISSUE THREAD

**Issue by chenbruce1** [immersive-translate/immersive-translate#1822]
### 您希望的更新和改进是什么 | Update or Improve

您好，

“翻译本地字幕”这个功能，目前一次只能翻译一个本地翻译SRT文件。

我有几百个本地SRT文件，我想同时丢进去翻译，等他们全部翻译完后，弹出提醒“翻译完成”，我再一次性全部统一导出。

也许可以变成下面的样子，仅供参考。

![完成](https://github.com/immersive-translate/immersive-translate/assets/128974009/cde2e451-a200-4146-be94-f2bd1a53b8f7)

**Comment by keyboard3** [comment]
问题重复了哈 https://github.com/immersive-translate/immersive-translate/issues/1422
