### ISSUE TITLE
[Bug]: Twitter deck面板翻译一直出不来

### ISSUE THREAD

**Issue by linbintalk** [immersive-translate/immersive-translate#1823]
### 插件版本号 | Version

1.6.3

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

twitter pro看板，翻译经常出不来，提示正在注入，刷新页面也不行。

### 出现问题的网址 | URL

https://pro.twitter.com/

### 重现步骤 | To Reproduce

https://pro.twitter.com

### 补充说明 | Additional context

无

**Comment by keyboard3** [comment]
正在注入表明网页资源还没有加载完，插件还没有插入。如果刷新也不行的话，试试切换下代理试试
