### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by guaiguaimo** [immersive-translate/immersive-translate#1824]
### 插件版本号 | Version

1.4.8

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

大概从上周开始，点翻译时网页都不能翻译了，不知道怎么回事。把所有免费服务都切换了一遍，微软、谷歌、腾讯都不行。

**Comment by keyboard3** [comment]
卸载重装吧，顺便更新下插件版本

**Comment by guaiguaimo** [comment]
> 卸载重装吧，顺便更新下插件版本

确实好了，谢谢！
