### ISSUE TITLE
[Bug]:  兼容 OpenAI 接口的自定义 AI 翻译服务，不显示“AI专家”下拉框

### ISSUE THREAD

**Issue by oubeichen** [immersive-translate/immersive-translate#1826]
### 插件版本号 | Version

1.6.3

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

配置了兼容OpenAI接口的大模型（我用的是智谱的 GLM-4），配置页面可以选择AI专家，如图。
![20240620155251](https://github.com/immersive-translate/immersive-translate/assets/2402901/7b66b818-4c81-457d-b4b7-35f7b21d91f1)

但外面的页面没有“AI专家”这个下拉框，如图。
![20240620154746](https://github.com/immersive-translate/immersive-translate/assets/2402901/158ce63f-ce32-40ed-8d23-e38cc5e5f3a8)

如果选择正版的OpenAI或者其他大模型就会有AI专家下拉框，如图。当然直接替换OpenAI的网址也许可以，但毕竟偶尔还是想用下正版的。
![image](https://github.com/immersive-translate/immersive-translate/assets/2402901/41ea2def-94c5-49de-b25b-5bc9ea327101)

### 补充说明 | Additional context

这个界面，要是还能添加自由切换模型、每次提交段落数的下拉框，那就更好了，毕竟不同模型价格和速度不一样，适合不同的翻译需求。
不然就得加一堆自定义翻译服务，或者每次都要到配置页面手动修改来实现，也不是不可以就是稍微麻烦一点。

**Comment by flamintune** [comment]
下个版本修复自定义 AI 翻译服务 不显示AI专家下拉框

**Comment by T-Atlas** [comment]
一样的问题

**Comment by flamintune** [comment]
1.6.5已修复该问题，欢迎及时更新插件体验
