### ISSUE TITLE
[Bug]: YouTube 回報bug

### ISSUE THREAD

**Issue by ggyy020406** [immersive-translate/immersive-translate#1828]
### 插件版本号 | Version

1.6.4

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

當youtube影片原字幕為 廣東話(香港)
開了插件影片翻譯繁體中文時
插件不知道原字幕已經是繁體字幕會再去翻譯多一次
廣東話 粵語 香港 這些字眼的都是代表已經是繁體字幕了，不需要二次翻譯

### 出现问题的网址 | URL

https://youtu.be/sH7y9TZb_6k?si=E4c3VwJYdr-6JwPJ

### 重现步骤 | To Reproduce

1. youtube設定為繁體中文(香港)
2. 插件設定翻譯為繁體中文
3. 插件開啟影片自動雙語字幕

**Comment by FattySpring** [comment]
1.6.6 已修复
