### ISSUE TITLE
制作双语epub电子书，功能改进

### ISSUE THREAD

**Issue by a14907** [immersive-translate/immersive-translate#1829]
### 您希望的更新和改进是什么 | Update or Improve

希望增加一个生词模式，双语电子书并不需要全部翻译，只需要针对比较难的词汇给出翻译就行了！可以给单词难度一个级别，级别不一样，翻译的单词数量不一样。主要是因为现在出来的翻译，质量不怎么样，还不如只针对生词进行翻译，效果可能更好

**Comment by theowenyoung** [comment]
抱歉，这不是沉浸式翻译的发展方向。

也许您可以向 Relingo 提议这个功能： https://relingo.net/en
