### ISSUE TITLE
与gitlab的mermaid冲突

### ISSUE THREAD

**Issue by immadolf** [immersive-translate/immersive-translate#183]
在gitlab的issue的评论中填入如下内容
````
```mermaid
graph TD
    A["lc1 <br/> [AA]"] --> B["lc2 <br/> [BB]"]
    B --> C
    C --> D
```
````

期望的效果
<img width="554" alt="image" src="https://user-images.githubusercontent.com/12369197/222322563-93daec0c-0046-4afc-b006-a814d978caf2.png">

实际的效果
<img width="993" alt="image" src="https://user-images.githubusercontent.com/12369197/222322491-3c665c8c-c2e3-4343-a8bc-9ba241f5cf49.png">

**Comment by immadolf** [comment]
扩展和油猴脚本都存在这个现象

**Comment by theowenyoung** [comment]
有点没明白～

我测试它的显示是这样的

<img width="746" alt="Screenshot 2023-03-03 at 00 05 04" src="https://user-images.githubusercontent.com/62473795/222483680-906c4d9f-6064-4828-b86c-2dd7ea176b08.png">

**Comment by immadolf** [comment]
出于隐私性的考虑，我不能直接上传到GitHub，能提供一下邮箱吗，我发录屏给你。

**Comment by theowenyoung** [comment]
请问这个问题还存在吗？ owen@owenyoung.com

**Comment by immadolf** [comment]
> 请问这个问题还存在吗？ [owen@owenyoung.com](mailto:owen@owenyoung.com)

从效果上来看已经修复了
