### ISSUE TITLE
support bilingual subtitle for https://tver.jp/

### ISSUE THREAD

**Issue by Dereklam0407** [immersive-translate/immersive-translate#1830]
### 您希望的更新和改进是什么 | Update or Improve

support bilingual subtitle for https://tver.jp/

### 补充说明 | Additional context

support bilingual subtitle for https://tver.jp/

**Comment by keyboard3** [comment]
Please submit the sites that need to be supported in [this issue](https://github.com/immersive-translate/immersive-translate/issues/1179)
