### ISSUE TITLE
[Bug]: Youtube 英语字幕始终被翻译成繁体中文

### ISSUE THREAD

**Issue by Jancat** [immersive-translate/immersive-translate#1831]
### 插件版本号 | Version

1.6.4

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

Chrome 扩展里已经指定目标语言是“简体中文”，但 Youtube (HK) 英语字幕还是被翻译成繁体中文，无法更改。
切换翻译服务也不生效。

<img width="1489" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/11827786/5311da36-d462-4a99-8717-56a454f4eb51">

Youtube 已经设置跟随主翻译服务

<img width="838" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/11827786/c648cef6-05f5-4b82-98ad-bb1427c2122f">

### 出现问题的网址 | URL

https://www.youtube.com/watch?v=6sSDXurPX-s

**Comment by FattySpring** [comment]
为能复现，换个其他翻译服务呢

**Comment by FattySpring** [comment]
这个视频源字幕有问题，可以关闭 【优先使用人工字幕】 选项解决

**Comment by Jancat** [comment]
@FattySpring 谢谢，确实关闭了 【优先使用人工字幕】 选项之后就显示简体了

不过顺便了解下，为什么视频源英文字幕会影响翻译的简/繁体呢？关闭了 【优先使用人工字幕】选项后，沉浸式翻译扩展会自动识别语音转成英文字幕后再翻译吗？
