### ISSUE TITLE
[Bug]: 豆包大模型问题

### ISSUE THREAD

**Issue by NEXTZERO000** [immersive-translate/immersive-translate#1832]
### 插件版本号 | Version

1.6.4

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

测试豆包大模型时出错

401: {"error":{"code":"AccessDenied","message":"The request failed because you do not have access to the requested resource.","param":"","type":"AccessDenied"}}

### 出现问题的网址 | URL

https://en.wikipedia.org/wiki/Interview#:~:text=An%20interview%20is%20a%20structured,an%20interviewer%20and%20an%20interviewee.

### 重现步骤 | To Reproduce

<img width="337" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/152939188/b0137884-3d3a-4942-bc4f-756cbf60ac52">

### 补充说明 | Additional context

没了

**Comment by flamintune** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/79519446/34e9adba-3d27-46b6-a8fa-5060242bc333)
这是豆包大模型那边的相关文档说明，可能是APIKEY填错了？

**Comment by NEXTZERO000** [comment]
谢谢，其实是推理 id 填错了😅
