### ISSUE TITLE
[Bug]: 在翻译网页文献时，出现明显卡顿，且恢复后进入下一翻译端继续卡顿，无法完整阅读文献。

### ISSUE THREAD

**Issue by Azure-Fairy** [immersive-translate/immersive-translate#1833]
### 插件版本号 | Version

1.6.4

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome, Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在翻译中，键盘卡死无反应，鼠标移动出现显著延迟。且很长时间无法恢复。恢复后若鼠标滚轮滚动进入未翻译页面，则重新卡顿。想请教一下这个可能是什么问题。
控制台情况：
![image](https://github.com/immersive-translate/immersive-translate/assets/77707863/f932e2e3-5871-4d37-9659-3cbbfa0097aa)

### 出现问题的网址 | URL

https://www.sciencedirect.com/science/article/pii/S221287782100154X?via%3Dihub

**Comment by keyboard3** [comment]
一直这样，还是最近这样？清除插件缓存再试下

**Comment by Azure-Fairy** [comment]
> 一直这样，还是最近这样？清除插件缓存再试下

一直这样，之前一直用的edge，这两天重新下载chrome使用也出现了类似的情况。插件也尝试重新安装过。极少数情况下，会卡顿到直接显示无法连接服务器。

**Comment by keyboard3** [comment]
> > 一直这样，还是最近这样？清除插件缓存再试下
> 
> 一直这样，之前一直用的edge，这两天重新下载chrome使用也出现了类似的情况。插件也尝试重新安装过。极少数情况下，会卡顿到直接显示无法连接服务器。

[你把缓存关闭试试](https://dash.immersivetranslate.com/#about)

**Comment by Azure-Fairy** [comment]
> > > 一直这样，还是最近这样？清除插件缓存再试下
> > 
> > 
> > 一直这样，之前一直用的edge，这两天重新下载chrome使用也出现了类似的情况。插件也尝试重新安装过。极少数情况下，会卡顿到直接显示无法连接服务器。
> 
> [你把缓存关闭试试](https://dash.immersivetranslate.com/#about)

好了一些，不会出现鼠标移动掉帧的情况了。但是还是会出现一定程度的网页卡死（但确实比之前好了一点）

**Comment by keyboard3** [comment]
缓存问题去掉之后，仍卡顿基本上跟电脑性能关系比较大。 可以在设置-进阶设置页面将前4999设置为0

**Comment by keyboard3** [comment]
还可以试试关闭插件使用油猴脚本会不会改善

**Comment by youngerruan** [comment]
被这个问题困扰几个月了。
- 之前有个10代低压i5笔记本。浏览综述论文的时候（网页很多段落文字），点击翻译，会卡死。鼠标也动不了。然后系统从win11重装换成了win10，这个问题消失了。同一个网页，很快。
- 现在有一个amd 锐龙8845hs的笔记本，32g内存，理论上性能不可能是瓶颈，系统版本win11。同样卡顿。。期间用过的方法有（从网上找的），更换浏览器（chrome和edge），关闭缓存，关闭浏览器硬件加速，flags里面关闭gpu的两个选项，flags里面有个选项调整为d3d9，关闭效率模式，电脑驱动重装为oem提供的gpu驱动，更新到最新amd驱动，通通没有用。。。

现在不知道怎么办了。有谁能提供一点思路吗？难道是锐龙的兼容性问题？还是说win11的问题？

**Comment by keyboard3** [comment]
@youngerruan 可以换到火狐浏览器试试

**Comment by youngerruan** [comment]
> @youngerruan 可以换到火狐浏览器试试
我刚吧插件禁用了，然后点击edge浏览器自己的翻译，也是一样卡。应该不是插件的问题。是浏览器的问题。但是又找不到解决办法。除了换浏览器没招了吗？哭

**Comment by keyboard3** [comment]
> > @youngerruan 可以换到火狐浏览器试试
> > 我刚吧插件禁用了，然后点击edge浏览器自己的翻译，也是一样卡。应该不是插件的问题。是浏览器的问题。但是又找不到解决办法。除了换浏览器没招了吗？哭

可以用鼠标悬停按需翻译

**Comment by Azure-Fairy** [comment]
我后面也是换成了火狐就解决了，edge和Chrome这些都是翻译卡顿。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月1日(周五) 晚上7:41
收件人: ***@***.***&gt;;
抄送: "Maozheng ***@***.******@***.***&gt;;
主题: Re: [immersive-translate/immersive-translate] [Bug]: 在翻译网页文献时，出现明显卡顿，且恢复后进入下一翻译端继续卡顿，无法完整阅读文献。 (Issue #1833)




  
@youngerruan 可以换到火狐浏览器试试
 我刚吧插件禁用了，然后点击edge浏览器自己的翻译，也是一样卡。应该不是插件的问题。是浏览器的问题。但是又找不到解决办法。除了换浏览器没招了吗？哭

**Comment by youngerruan** [comment]
> > > @youngerruan 可以换到火狐浏览器试试
> > > 我刚吧插件禁用了，然后点击edge浏览器自己的翻译，也是一样卡。应该不是插件的问题。是浏览器的问题。但是又找不到解决办法。除了换浏览器没招了吗？哭
> 
> 可以用鼠标悬停按需翻译

这个试过了，也是会稍稍卡顿。感觉就是兼容性问题，跟amd不太兼容。不管怎样，谢谢您的回复~

**Comment by youngerruan** [comment]
> 我后面也是换成了火狐就解决了，edge和Chrome这些都是翻译卡顿。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年11月1日(周五) 晚上7:41 收件人: ***@***.***&gt;; 抄送: "Maozheng ***@***.******@***.***&gt;; 主题: Re: [immersive-translate/immersive-translate] [Bug]: 在翻译网页文献时，出现明显卡顿，且恢复后进入下一翻译端继续卡顿，无法完整阅读文献。 (Issue #1833) @youngerruan 可以换到火狐浏览器试试 我刚吧插件禁用了，然后点击edge浏览器自己的翻译，也是一样卡。应该不是插件的问题。是浏览器的问题。但是又找不到解决办法。除了换浏览器没招了吗？哭 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

只能这样了，但是我不想换浏览器。现在edge用侧边栏copilot、chatgpt、outlook还挺顺手哈哈哈。

**Comment by Azure-Fairy** [comment]
我也一样，现在就是翻译文献的时候用火狐
打开翻译，只希望这个bug能早点修好。

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月1日(周五) 晚上7:54
收件人: ***@***.***&gt;;
抄送: "Maozheng ***@***.******@***.***&gt;;
主题: Re: [immersive-translate/immersive-translate] [Bug]: 在翻译网页文献时，出现明显卡顿，且恢复后进入下一翻译端继续卡顿，无法完整阅读文献。 (Issue #1833)




  
我后面也是换成了火狐就解决了，edge和Chrome这些都是翻译卡顿。
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年11月1日(周五) 晚上7:41 收件人: @.&gt;; 抄送: "Maozheng @.@.&gt;; 主题: Re: [immersive-translate/immersive-translate] [Bug]: 在翻译网页文献时，出现明显卡顿，且恢复后进入下一翻译端继续卡顿，无法完整阅读文献。 (Issue #1833) @youngerruan 可以换到火狐浏览器试试 我刚吧插件禁用了，然后点击edge浏览器自己的翻译，也是一样卡。应该不是插件的问题。是浏览器的问题。但是又找不到解决办法。除了换浏览器没招了吗？哭 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
只能这样了，但是我不想换浏览器。现在edge用侧边栏copilot、chatgpt、outlook还挺顺手哈哈哈。

**Comment by KJH-x** [comment]
同样遇到这个问题，希望早日修复=_=，也在用火狐替代
