### ISSUE TITLE
缩进页面显示异常

### ISSUE THREAD

**Issue by DarcySail** [immersive-translate/immersive-translate#1836]
### 您希望的更新和改进是什么 | Update or Improve

![image](https://github.com/immersive-translate/immersive-translate/assets/7321683/9b75d0b3-b239-4c06-b348-b624902c0996)
![image](https://github.com/immersive-translate/immersive-translate/assets/7321683/bb331ae3-bce8-4b81-af08-548907fec02f)
> https://man7.org/linux/man-pages/man1/tmux.1.html

在很多 linux man 手册页面中，有缩进的行会被压缩到一行进行翻译，阅读体验较差。
希望可以不要压缩到一行进行显示。

**Comment by keyboard3** [comment]
这种手册网页都是通过空格换行报保留样式，非标签富文本。无法准确还原格式
