### ISSUE TITLE
[Bug]: 文档翻译无法翻译英文和繁体中文

### ISSUE THREAD

**Issue by ApolloZhangOnGithub** [immersive-translate/immersive-translate#1837]
### 插件版本号 | Version

0.5.5

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

翻译完文档还是英文

### 出现问题的网址 | URL

任何url

### 重现步骤 | To Reproduce

选择任意pdf
点击翻译

### 补充说明 | Additional context

。

**Comment by keyboard3** [comment]
版本太低了，升级到最新版试试 https://immersivetranslate.com/
