### ISSUE TITLE
[Bug]: 翻译导致网站跳转到404

### ISSUE THREAD

**Issue by jerryc127** [immersive-translate/immersive-translate#1838]
### 插件版本号 | Version

1.6.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

sbs 韩国电视台网站
点击翻译成中文

网页或跳转到 .../zh 导致404

### 出现问题的网址 | URL

https://www.sbs.co.kr/

**Comment by keyboard3** [comment]
没能复现，举一个具体的例子，或者录个屏看下

**Comment by jerryc127** [comment]
> 没能复现，举一个具体的例子，或者录个屏看下
![screenshot_2024-06-27_12-16-38](https://github.com/immersive-translate/immersive-translate/assets/16351105/33f795bc-5f80-4501-9557-89a82b45f202)

**Comment by keyboard3** [comment]
我测试了，这个跟插件无关，网站自身有Bug 会自己重定向到404页面，我不翻译来回点击也会自动到404
