### ISSUE TITLE
文本翻译的输入框不能随内容的增多变长

### ISSUE THREAD

**Issue by hrk1205** [immersive-translate/immersive-translate#1839]
### 您希望的更新和改进是什么 | Update or Improve

<img width="1281" alt="截屏2024-06-24 18 33 28" src="https://github.com/immersive-translate/immersive-translate/assets/53370978/d1698cc1-525c-4492-b8f3-2fecdedfb6f2">

当我输入很多行的内容的时候，这个框不能变长，变成需要框滚动才能看全内容。希望当用户输入很多行的时候，这框和Google翻译的输入框一样，可以变长...

**Comment by flamintune** [comment]
因为这个最开始针对的就是短文本的翻译，所以输入框和输出框都限制了最高高度，对于长文本，我理解的是就属于文档翻译的范畴了。

以及这个设计的初衷是为了对比相同文本情况下的多翻译服务的翻译效果，所以在下滑时浏览其他翻译结果的时候，会固定左侧的输入框，方便起到一个对照的效果。

然后的话，让输入框随文本自适应变高的话，会导致现在滚动下划，固定输入框的效果会出现 bug。即这个输入文本框的高度是不能超过屏幕的高度的。

所以相应的交互设计，我们可能得稍微讨论一下得出结果。暂时想到的一个不太友好的解决方案是通过搜索关键词或者文本行数来快速定位想要看的文本

**Comment by theowenyoung** [comment]
其实两者区别可能不大，谷歌的文本框 即使变长，也需要手动滚动。区别只是滚动条的位置？

感觉还好，似乎也可以不调整。

**Comment by hrk1205** [comment]
1、你们输入框实在是太小，我的需求是比文档翻译少，但比短文长，google 翻译的做法是，如果没有一屏，则撑大到一屏，超过后会翻页的形式。
2、“以及这个设计的初衷是为了对比相同文本情况下的多翻译服务的翻译效果”，这个问题，我到是没想过。我自己的做法是，如果我要对照，我就切换，看看哪个更好，我就固定用哪个就好... 感觉同时出多个结果进行对照这个习惯可以问问其他使用的人，我确实是只用一个,, 哈
