### ISSUE TITLE
ipinfo.io不能自动翻译

### ISSUE THREAD

**Issue by photkey** [immersive-translate/immersive-translate#184]
https://ipinfo.io/developers/database-download

这个网址不能自动翻译，我手动写了`User Rules` 还是不能自动翻译。

**Comment by theowenyoung** [comment]
我这可以？
<img width="864" alt="Screenshot 2023-03-02 at 23 59 41" src="https://user-images.githubusercontent.com/62473795/222482378-d3549f4c-64c3-4b50-b677-4bb052b3b5df.png">
