### ISSUE TITLE
[Bug]: Translate HTML/txt file - text color issue and not all the text is translated

### ISSUE THREAD

**Issue by iG8R** [immersive-translate/immersive-translate#1840]
### 插件版本号 | Version

1.6.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

The best way is to show in the screenshot.

![image](https://github.com/immersive-translate/immersive-translate/assets/11407417/4d2d7383-d8eb-4264-9b4d-258e0b422d49)

The example file: [info.json.zip](https://github.com/user-attachments/files/15955568/info.json.zip)

**Comment by TaoLoading** [comment]
bug fixed.

**Comment by iG8R** [comment]
@TaoLoading 
Thank you for your efforts, but still the issue with not all translated text is present.

![image](https://github.com/immersive-translate/immersive-translate/assets/11407417/95cea9e3-6e74-4926-9494-7bffc457929f)

**Comment by iG8R** [comment]
@TaoLoading 
Please, re-open this issue.

**Comment by keyboard3** [comment]
没有翻译部分，应该和翻译服务有关，因为在翻译服务看来是中英混合，你切换下到其他翻译服务试试。或者你将文件发送上来

**Comment by iG8R** [comment]
@keyboard3 
IMHO, if the question was about translated services, there would not be the following, e.i. missing translations in the same positions:

![image](https://github.com/immersive-translate/immersive-translate/assets/11407417/dd5e3135-5b6f-4182-83f7-d1917c0c26ae)

**Comment by keyboard3** [comment]
Please attach this file

**Comment by iG8R** [comment]
Thanks for your attention.
I've already attached it in the OP.

![image](https://github.com/immersive-translate/immersive-translate/assets/11407417/4e373fd6-4ad8-4d1c-a300-b024a89686ae)

**Comment by keyboard3** [comment]
Because of the mix of Chinese and English so some paragraphs will be recognized as English, you can specify the source language is Chinese in the panel, and then in the translation
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/47098eff-286f-4cd1-8c7a-9b47239f7814)

**Comment by iG8R** [comment]
Thanks a lot! It worked.
Is it possible to automatically re-translate a file after changing the source language, or at least have an option that would allow this behavior?

PS. Could you please tell what program you use to process screenshots and insert arrows?

**Comment by keyboard3** [comment]
The page is automatically translated, but this is a file translation, which is essentially a remedy and does not automatically trigger the translation

The arrow on the screenshot uses WeChat

**Comment by iG8R** [comment]
Thank you very much again!
