### ISSUE TITLE
[Bug]: 翻译一个GitHub上超长的网页，直接所有CPU吃满卡顿只能重启

### ISSUE THREAD

**Issue by WolfWithoutDuck** [immersive-translate/immersive-translate#1841]
### 插件版本号 | Version

V1.65

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

当我翻译一个GIitHub上内容很多的网页时候，直接开始了， 一直翻译。最后只能重启，鼠标想移动到去关闭网页都搞不来

### 出现问题的网址 | URL

https://github.com/tranek/GASDocumentation

### 重现步骤 | To Reproduce

~1.打开网页，

2.点击翻译

3，直接卡死

### 补充说明 | Additional context

无

**Comment by keyboard3** [comment]
把缓存关闭试试 https://dash.immersivetranslate.com/#about

**Comment by keyboard3** [comment]
还可以试试关闭插件使用油猴脚本会不会改善

**Comment by anshangtangyuan** [comment]
同  翻译太长的综述论文 就容易卡

**Comment by NoSW** [comment]
翻译速度是受哪些因素影响啊？CPU配置？网速？API响应速度？我这也是翻译一个超长网页电脑明显卡住，cpu占用变高一点，内存占用明显升高。

或许可以只翻译屏幕显示的部分+上下文一点点？当屏幕范围移动时丢弃未完成的翻译任务？

**Comment by keyboard3** [comment]
> 翻译速度是受哪些因素影响啊？CPU配置？网速？API响应速度？我这也是翻译一个超长网页电脑明显卡住，cpu占用变高一点，内存占用明显升高。
> 
> 或许可以只翻译屏幕显示的部分+上下文一点点？当屏幕范围移动时丢弃未完成的翻译任务？

现在就是这个策略。 理论上不应该卡顿，在低端电脑上我们也测试过长网页不会卡顿。 群里有用户反馈windows装了有道翻译影响chrome内核浏览器卡顿，火狐流畅。你可以参考下有无类似表现

**Comment by NoSW** [comment]
> > 翻译速度是受哪些因素影响啊？CPU配置？网速？API响应速度？我这也是翻译一个超长网页电脑明显卡住，cpu占用变高一点，内存占用明显升高。
> > 或许可以只翻译屏幕显示的部分+上下文一点点？当屏幕范围移动时丢弃未完成的翻译任务？
> 
> 现在就是这个策略。 理论上不应该卡顿，在低端电脑上我们也测试过长网页不会卡顿。 群里有用户反馈windows装了有道翻译影响chrome内核浏览器卡顿，火狐流畅。你可以参考下有无类似表现

我换了Edge，再打开同个网页就不卡了😋

**Comment by MavisTok** [comment]
我好像没有这个问题 边看边往下拉没问题

**Comment by Gokou-Ruri** [comment]
我感觉是你们可能还装了其它什么扩展或篡改猴js产生了冲突才会导致卡死吧？我这边试了这个页面，并没有任何问题，负载也几乎可以忽略。篡改猴js版，调用的是谷歌翻译。

**Comment by keyboard3** [comment]
问题重复，卡顿问题汇总到这个帖子 https://github.com/immersive-translate/immersive-translate/issues/1746
