### ISSUE TITLE
[Bug]: 使用Claude官方API作为翻译服务时异常缓慢

### ISSUE THREAD

**Issue by EvanClausen111** [immersive-translate/immersive-translate#1842]
### 插件版本号 | Version

1.6.5

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

如题所示，Claude账户是付费账户，且在Claude API 控制台可以看到Token使用，Claude API控制台的模拟对话以及python程序运行时不会出现这个问题，翻译时大致需要等待4-5翻译的文本才会逐段出现

**Comment by EvanClausen111** [comment]
使用的是Claude 3 Haiku

**Comment by keyboard3** [comment]
claude 响应慢理论上跟插件无关。你可以打开设置页面，然后打开开发者模式，观察下请求情况。注意翻译的tab和观察请求的tab同时显示
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/06c52a69-c2f5-4885-bf1b-f13be58cac18)

**Comment by zmm147** [comment]
你设置请求频率了吗
