### ISSUE TITLE
Can the console debug log be cleared?

### ISSUE THREAD

**Issue by SerMs** [immersive-translate/immersive-translate#1843]
### 您希望的更新和改进是什么 | Update or Improve

我的工作经常需要用到浏览器的控制台，一打开控制台就会看到一堆有关你们插件的日志输入，请问能否不要让他显示？      

### 补充说明 | Additional context

![image](https://github.com/immersive-translate/immersive-translate/assets/67584847/4f793a37-8bfc-4b68-945d-b4db6ed210e7)

![image](https://github.com/immersive-translate/immersive-translate/assets/67584847/7737e7e2-608e-4c28-8964-dc1df91a62bf)

**Comment by keyboard3** [comment]
https://dash.immersivetranslate.com/#developer
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/735349d5-01f8-466a-b845-d1781d49a6d0)
关闭日志
