### ISSUE TITLE
[Bug]: .ass字幕文件翻译格式消失...

### ISSUE THREAD

**Issue by hrk1205** [immersive-translate/immersive-translate#1844]
### 插件版本号 | Version

v.1.6.5

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

不知道开发者是否做过.ass文件，.ass文件是带格式的... 翻译完的格式会不见

[bug.zip](https://github.com/user-attachments/files/15980474/bug.zip)
上面是我附加的一个.ass文件，文件里面的字幕格式如下
Dialogue: 0,0:00:01.51,0:00:03.89,Default,,0,0,0,,{\pos(640,105.696)}I'm Michael Cera, and I'm pleased to announce
Dialogue: 0,0:00:03.89,0:00:04.51,Default,,0,0,0,,{\c&HFFFFFF&}that this is2222

注意【{\pos(640,105.696)}...】 和 【{\c&HFFFFFF&}】 是字幕的格式..

第一个问题：把这个.ass文件放到https://app.immersivetranslate.com/subtitle/ 这个页面，翻译完，我点击下载，下载完的.ass文件里面的格式...【{\pos(640,105.696)}...】 和 【{\c&HFFFFFF&}】 会都不见...

变成这样：
Dialogue: 0,0:00:01.51,0:00:03.89,DefaultVCD, NTP,0000,0000,0000,,我是迈克尔·塞拉，我很高兴地宣布
Dialogue: 0,0:00:03.89,0:00:04.51,DefaultVCD, NTP,0000,0000,0000,,这是 2222

希望能改进的是，翻译并下载完之后，保留样式...

第二个问题：
Dialogue: 0,0:00:01.51,0:00:03.89,Default,,0,0,0,,{\pos(640,105.696)}I'm Michael Cera, and I'm pleased to announce
Dialogue: 0,0:00:03.89,0:00:04.51,Default,,0,0,0,,{\c&HFFFFFF&}that this is2222

这个里面的【Default,,0,0,0，】也会被替换成DefaultVCD, NTP,0000,0000,0000,... 

希望改进的是，不要替换这个...

### 出现问题的网址 | URL

https://app.immersivetranslate.com/subtitle/

**Comment by TaoLoading** [comment]
确实存在这个问题，我这边记录下，修改后给你反馈

**Comment by TaoLoading** [comment]
你好，问题已修复。其中问题 1 现阶段的解决策略是保留原文样式
