### ISSUE TITLE
separate sentences to chunking and comment translated.

### ISSUE THREAD

**Issue by trionline1234** [immersive-translate/immersive-translate#1847]
### 您希望的更新和改进是什么 | Update or Improve

For example:

𝐓𝐡𝐞 𝐩𝐨𝐰𝐞𝐫 𝐨𝐟 𝐠𝐫𝐚𝐭𝐢𝐭𝐮𝐝𝐞 𝐢𝐬 𝐚 𝐦𝐢𝐫𝐚𝐜𝐮𝐥𝐨𝐮𝐬 𝐟𝐨𝐫𝐜𝐞 . 𝐈𝐭 𝐜𝐚𝐧 𝐭𝐫𝐚𝐧𝐬𝐟𝐨𝐫𝐦 𝐲𝐨𝐮𝐫 𝐥𝐢𝐟𝐞 𝐢𝐧 𝐰𝐚𝐲𝐬 𝐲𝐨𝐮 𝐧𝐞𝐯𝐞𝐫 𝐭𝐡𝐨𝐮𝐠𝐡𝐭 𝐩𝐨𝐬𝐬𝐢𝐛𝐥𝐞
Convert to format:
 (Sức mạnh của lòng biết ơn) 𝐓𝐡𝐞 𝐩𝐨𝐰𝐞𝐫 𝐨𝐟 𝐠𝐫𝐚𝐭𝐢𝐭𝐮𝐝𝐞 (là một lực lượng kỳ diệu) 𝐢𝐬 𝐚 𝐦𝐢𝐫𝐚𝐜𝐮𝐥𝐨𝐮𝐬 𝐟𝐨𝐫𝐜𝐞 . (Nó có thể biến đổi)𝐈𝐭 𝐜𝐚𝐧 𝐭𝐫𝐚𝐧𝐬𝐟𝐨𝐫𝐦 (cuộc sống của bạn) 𝐲𝐨𝐮𝐫 𝐥𝐢𝐟𝐞 (theo những cách mà bạn không bao giờ nghĩ đến)  𝐢𝐧 𝐰𝐚𝐲𝐬 𝐲𝐨𝐮 𝐧𝐞𝐯𝐞𝐫 𝐭𝐡𝐨𝐮𝐠𝐡𝐭 𝐩𝐨𝐬𝐬𝐢𝐛𝐥𝐞. 

It will better for foreign language learner when text to speech with bilingual sentences.

**Comment by trionline1234** [comment]
Although there are many extension support Text to speech but i think it will be better if Immersive translate develope this function, because it will read bilingual text for Immersive create, especially it can repeat each sentence many times before next to the following sentence, to practice listening skills.

**Comment by theowenyoung** [comment]
Hello, these are not the main purpose of the Immersive Translate extension and will not be considered for support in the short term.
