### ISSUE TITLE
Text to speech for bilingual text.

### ISSUE THREAD

**Issue by trionline1234** [immersive-translate/immersive-translate#1848]
### 您希望的更新和改进是什么 | Update or Improve

Although there are many extension support Text to speech but i think it will be better if Immersive translate develope this function, because it will read bilingual text for Immersive create, especially it can repeat each sentence many times before next to the following sentence, to practice listening skills.

**Comment by theowenyoung** [comment]
Hello, this is a great addition to the complexity of the current plugin and will not be considered in the short term to support this feature in the Immersive Translate plugin. 

It is recommended that you use it with other plugins.
