### ISSUE TITLE
[Feature Request] Support for OpenAI's gpt-3.5-turbo model

### ISSUE THREAD

**Issue by celerysoft** [immersive-translate/immersive-translate#185]
The current translation engine is based on the [Completions API](https://api.openai.com/v1/completions), which does not support the latest gpt-3.5-turbo model. This new model requires the use of the [Chat API](https://platform.openai.com/docs/api-reference/completions), which has slight differences in URI, requests and responses compared to the Completions API.

The gpt-3.5-turbo model is cheaper while being faster, but the downside is that free-trail accounts often trigger the [Rate Limits](https://platform.openai.com/docs/guides/rate-limits) when translating web pages.

Hope that the immersive-translate project can soon add support for the gpt-3.5-turbo model. Good time:D

**Comment by theowenyoung** [comment]
Thanks, I have finished this feature, will release it a couple hours.

**Comment by theowenyoung** [comment]
0.2.78 has released

**Comment by celerysoft** [comment]
Thank you very much for your work.
