### ISSUE TITLE
deeplx 能否配置多个url，权重调度进行翻译

### ISSUE THREAD

**Issue by kingxjs** [immersive-translate/immersive-translate#1851]
### 您希望的更新和改进是什么 | Update or Improve

本身deeplx不适合网页高频率翻译，我又没有资源可进行负载，但周边朋友能提供几个自己的api接口，是否可以进行权重调度访问？能在一定程度上解决Failed to fetch异常

**Comment by theowenyoung** [comment]
您可以用 `,` 分割多个url来实现多个接口的负载均衡。

**Comment by kingxjs** [comment]
效果不是很好，还是会报429: {"code":429,"message":"Too Many Requests"}，难道还是调的同一个url？

**Comment by theowenyoung** [comment]
这个您需要自己调试解决了，程序本身是按随机顺序调用其中的某个接口。
