### ISSUE TITLE
为什么沉浸式翻译和直接在google翻译网页得到的结果不一样？

### ISSUE THREAD

**Issue by crysishacker** [immersive-translate/immersive-translate#1852]
### 您希望的更新和改进是什么 | Update or Improve

![图片](https://github.com/immersive-translate/immersive-translate/assets/43438174/99afd62e-4913-429d-9d9f-ec012fd9c921)
![图片](https://github.com/immersive-translate/immersive-translate/assets/43438174/5559f710-b9ef-494a-b84e-db8b9e7b1733)

**Comment by crysishacker** [comment]
另一个更为灾难的结果
![图片](https://github.com/immersive-translate/immersive-translate/assets/43438174/79cfd9a2-7084-4514-8240-eb4378d37363)
![图片](https://github.com/immersive-translate/immersive-translate/assets/43438174/ad9c7ed2-05eb-4408-9acd-fad460d0f95e)

**Comment by theowenyoung** [comment]
可能是谷歌为不同的翻译类型back 了不同的后端，目前沉浸式翻译只能调用谷歌为网页翻译提供的接口，结果如下：


https://translate.googleapis.com/translate_a/single?client=gtx&dt=t&sl=en&tl=zh-CN&q=Chang%27e-3%27s+successful+2013+landing+made+China+the+3rd+nation+to+achieve+a+soft+landing+after+the+US+and+Russia+efforts+both+ended+in+the%0A70s.


```json
[[["2013年嫦娥三号成功着陆，使中国成为继美俄努力均告失败后第三个实现软着陆的国家。\n","Chang'e-3's successful 2013 landing made China the 3rd nation to achieve a soft landing after the US and Russia efforts both ended in the\n",null,null,3,null,null,[[]],[[["6ffafab0da7e640be86ac09d0d5e539c","en_zh_2023q1.md"]],[null,true]]],["70 年代。","70s.",null,null,3,null,null,[[]],[[["6ffafab0da7e640be86ac09d0d5e539c","en_zh_2023q1.md"]]]]],null,"en",null,null,null,null,[]]
```
