### ISSUE TITLE
视频字幕允许选中文字

### ISSUE THREAD

**Issue by edr1412** [immersive-translate/immersive-translate#1853]
### 您希望的更新和改进是什么 | Update or Improve

希望视频字幕可以选中字幕里的文字；
或者，增加「文字可选中」的选项开关，开启时取代拖动动作。

理由如下：
1. 我们开启双语对照字幕（而非中文字幕）时很多是学习语言的场景。这时除了知道整句话的意思，查词也是必要的。因此，选中文字，复制到词典查词很有用。我想这也符合沉浸式翻译鼓励语言学习的初衷。
2. 拖动字幕并不常用，默认位置一般就是最佳位置。至少我个人从没有遇到过需要拖动字幕的情况。

### 补充说明 | Additional context

这是一个让Youtube字幕文字可选中的油猴脚本，希望达到这个效果。 https://greasyfork.org/zh-CN/scripts/451626-make-youtube-caption-selectable
可惜的是，它无法适用于沉浸式翻译的字幕。

**Comment by Jancat** [comment]
+1
确实字幕里遇到某个单词想要选中复制粘贴到某个地方查词，或者通过其它浏览器扩展选中之后直接查词。但是目前的视频字幕无法选中文本，只能拖动

**Comment by theowenyoung** [comment]
多家一个选项似乎是一个不必要的复杂抽象。

有没有可能在同时支持 选中 和 拖动？

不知道有没有见过类似的交互？

**Comment by edr1412** [comment]
> 多家一个选项似乎是一个不必要的复杂抽象。
> 
> 有没有可能在同时支持 选中 和 拖动？
> 
> 不知道有没有见过类似的交互？

加选项，我是完全可以接受的啦。。
要同时支持的话，要么字幕的边缘可以拖动？要么，按住修饰键拖动？

**Comment by edr1412** [comment]
或者，
左键选中，右键拖动，如何呢

**Comment by Jancat** [comment]
字幕框有鼠标悬浮时，边缘加个拖拽的 icon，字幕框主体都是可选中文字区域

**Comment by theowenyoung** [comment]
我们尝试后发现好像可以既支持拖动，又支持选中，请测试下最新的 1.7.5 版本，已实现。

**Comment by edr1412** [comment]
谢谢。
试了下，选中的同时也能拖动，不知道是设计成这样的还是bug？

https://github.com/immersive-translate/immersive-translate/assets/40953911/849c0414-ccb3-453b-abc8-b9c56d6e7866

**Comment by edr1412** [comment]
@theowenyoung 
似乎我的 Safari 上仍不允许字幕选中文字，但 Chrome可以。均为最新版。你能测试下吗？
我印象中 1.7.5 版本 Safari 是可以的，不知道是不是之后的更新导致现在不行了。
