### ISSUE TITLE
开启翻译后，部分内容会显示在该段的最后

### ISSUE THREAD

**Issue by hbliyafei** [immersive-translate/immersive-translate#1854]
### 插件版本号 | Version

1.6.6

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

翻译前的内容
![image](https://github.com/immersive-translate/immersive-translate/assets/14961742/a025aeed-c6af-45d6-8d0a-4c9a30512c09)
翻译后的内容
![image](https://github.com/immersive-translate/immersive-translate/assets/14961742/62f82ff6-0bfe-4640-95cc-8e51ecccf0b5)

开启翻译后 在 code 标签中的内容会显示在该段的最后

### 出现问题的网址 | URL

https://docs.spring.io/spring-boot/reference/features/external-config.html#features.external-config.typesafe-configuration-properties.relaxed-binding

### 重现步骤 | To Reproduce

1. 翻译网页/显示原文

**Comment by flamintune** [comment]
1.用的什么翻译服务呢

2.这个bug有点奇怪，以至于我们本地无法复现。能否提供一下翻译之后的网页快照，生成快照的方法是在翻译面板右上角点击生成网页快照，方便我们进行debug。

![image](https://github.com/immersive-translate/immersive-translate/assets/79519446/5219f7db-84e4-404c-bf09-390ba77eabcb)

**Comment by keyboard3** [comment]
> 1. 使用微软翻译
> 2. 生成网页快照提示："此站点的连接不安全immersivetranslate.com 使用不受支持的协议。"
> 
> 经过测试发现应该是和浏览器内置翻译冲突了导致页面显示不正常（不确定这是不是插件的问题）
> 
> 1. 打开网页
> 2. 点击”翻译网页/显示原文“显示中英双语(此时是正常的)
> 3. 点击”翻译网页/显示原文“只显示英文(此时也是正常的)
> 4. 浏览器内置的翻译工具，翻译为中文（此时页面显示不正常了）
>    4.1 单纯使用浏览器内置的翻译时，没有出现这个问题

这是当前域名解析有点文档，稍后等待恢复
