### ISSUE TITLE
建议：向免费用户开放权限，能够下载翻译前的视频字幕（原文字幕）

### ISSUE THREAD

**Issue by arena7981** [immersive-translate/immersive-translate#1855]
### 您希望的更新和改进是什么 | Update or Improve

已有youtube视频字幕下载功能，但属于付费功能
希望能向免费用户开放权限，能够下载翻译前的视频字幕（也就是油管原来就有的原文字幕）
能够下载翻译后的字幕需要付费理解，但下载原文字幕并没有占用是插件什么资源，建议开放权限
目前有不少插件或脚本能实现该功能，建议也集成到本插件

**Comment by theowenyoung** [comment]
建议使用其他免费替代方案实现，如： https://downsub.com/
