### ISSUE TITLE
[Bug]: 没有查看到多设备列表了

### ISSUE THREAD

**Issue by duohereshui999** [immersive-translate/immersive-translate#1856]
### 插件版本号 | Version

1.6.6

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

以前可以看到设备列表，现在看不到了

**Comment by keyboard3** [comment]
什么设备列表？ 没有过这个功能呀
