### ISSUE TITLE
建议：浏览器插件图标下拉菜单中可以选择模型

### ISSUE THREAD

**Issue by hidenmaskvip** [immersive-translate/immersive-translate#1857]
### 您希望的更新和改进是什么 | Update or Improve

建议：浏览器插件图标的下拉菜单中，同一个翻译服务提供商可以选择不同模型，如openai有gpt35、gpt4，现在只能到插件后台去选择，比较麻烦

![image](https://github.com/immersive-translate/immersive-translate/assets/146368179/ef79ad92-7883-4689-92fb-c3f366b89990)

**Comment by theowenyoung** [comment]
可以在翻译服务里，为不同的模型，新建新的自定义AI翻译服务。
