### ISSUE TITLE
Translate each sentence instead of translate each paragraph

### ISSUE THREAD

**Issue by trionline1234** [immersive-translate/immersive-translate#1858]
### 您希望的更新和改进是什么 | Update or Improve

Hi admin,
this extension should support "translate sentence" instead of "translate paragraph".
For example:
Scurvy killed more than [2 million] mariners during the Age of Sail, a period from the 1490s to the 1850s. As Stephen Bown writes in his book , naval captains signed up more sailors than they needed because they expected to lose many of them to scurvy during their voyages.

to

[Bệnh scorbut đã giết chết hơn 2 triệu thủy thủ trong Thời đại Cánh buồm, giai đoạn từ những năm 1490 đến những năm 1850.] Scurvy killed more than mariners during the Age of Sail, a period from the 1490s to the 1850s. [Như Stephen Bown viết trong cuốn sách Bệnh scorbut của mình, các thuyền trưởng hải quân đã đăng ký nhiều thủy thủ hơn mức họ cần vì họ dự kiến ​​sẽ mất nhiều người trong số họ vì bệnh scorbut trong chuyến hành trình của mình.] As Stephen Bown writes in his book [Scurvy], naval captains signed up more sailors than they needed because they expected to lose many of them to scurvy during their voyages.

instead of

Bệnh scorbut đã giết chết hơn 2 triệu thủy thủ trong Thời đại Cánh buồm, giai đoạn từ những năm 1490 đến những năm 1850. Như Stephen Bown viết trong cuốn sách Bệnh scorbut của mình, các thuyền trưởng hải quân đã đăng ký nhiều thủy thủ hơn mức họ cần vì họ dự kiến ​​sẽ mất nhiều người trong số họ vì bệnh scorbut trong chuyến hành trình của mình.
Scurvy killed more than [2 million] mariners during the Age of Sail, a period from the 1490s to the 1850s. As Stephen Bown writes in his book [Scurvy], naval captains signed up more sailors than they needed because they expected to lose many of them to scurvy during their voyages.

**Comment by theowenyoung** [comment]
Hi, have you tried this setting?

![CleanShot 2024-07-04 at 02 48 34@2x](https://github.com/immersive-translate/immersive-translate/assets/62473795/460ea50e-261c-496e-8238-e777b96c7239)

**Comment by mehdifirefox** [comment]
I will not open a new topic 
 Suggest a new feature 
I want only a part of a site to be translated. Not the whole site 
 I think it happens faster this way

**Comment by keyboard3** [comment]
> I will not open a new topic Suggest a new feature I want only a part of a site to be translated. Not the whole site I think it happens faster this way

 You should be able to replace this with other word translation plugins

**Comment by trionline1234** [comment]
Yes, i have tried this setting and set maximum 10 character per sentence after line break but it don't work like i want.
I means, instead of translating a paragraph, it will translate each sentence before translate the next sentence.
For example:

I love english. I study English everyday.

to
I love English. Tôi yêu tiếng Anh. I study English everyday. Tôi học tiếng Anh mỗi ngày.

not
I love english. I study English everyday.
Tôi yêu tiếng Anh. Tôi học tiếng Anh mỗi ngày.

**Comment by trionline1234** [comment]
Yes, i have tried this setting and set maximum 10 character per sentence after line break but it don't work like i want.
I means, instead of translating a paragraph, it will translate each sentence before translate the next sentence.
For example:

I love english. I study English everyday.

to
I love English. Tôi yêu tiếng Anh. I study English everyday. Tôi học tiếng Anh mỗi ngày.

not
I love english. I study English everyday.
Tôi yêu tiếng Anh. Tôi học tiếng Anh mỗi ngày.

**Comment by trionline1234** [comment]
> Hi, have you tried this setting?

Yes, i have tried this setting and set maximum 10 character per sentence after line break but it don't work like i want.
I means, instead of translating a paragraph, it will translate each sentence before translate the next sentence.
For example:

I love english. I study English everyday.

to
I love English. Tôi yêu tiếng Anh. I study English everyday. Tôi học tiếng Anh mỗi ngày.

not
I love english. I study English everyday.
Tôi yêu tiếng Anh. Tôi học tiếng Anh mỗi ngày.

**Comment by theowenyoung** [comment]
@trionline1234 we're not planning to ship feature like this.

have you tried  https://github.com/fishjar/kiss-translator ? it's an open-source translator, maybe you can do some custom feature by yourself.
