### ISSUE TITLE
[Bug]: 使用OpenAI等大模型翻译英文到中文时，标点符号不会被转换成中文的标点符号

### ISSUE THREAD

**Issue by oneness0** [immersive-translate/immersive-translate#1859]
### 插件版本号 | Version

1.6.6

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

**问题图例：**
![image](https://github.com/immersive-translate/immersive-translate/assets/25880389/6e72f1d1-b598-4543-9512-8147415ae2e6)
![image](https://github.com/immersive-translate/immersive-translate/assets/25880389/c3931a33-8791-40fb-b19b-6f0a89adba5c)

**使用的AI专家：** 通用

### 补充说明 | Additional context

希望能优化AI 翻译策略(Prompt)，来修复这个问题

**Comment by theowenyoung** [comment]
请问是否使用了 Claude 模型？ Claude 模型对中文标点符号支持的不太好。

OpenAI 一半是 是正常


![CleanShot 2024-07-04 at 02 37 30@2x](https://github.com/immersive-translate/immersive-translate/assets/62473795/a6d45f31-308f-412d-bab0-1e1987a9cd00)

**Comment by oneness0** [comment]
> 请问是否使用了 Claude 模型？ Claude 模型对中文标点符号支持的不太好。
> 
> OpenAI 一半是 是正常
> 
> ![CleanShot 2024-07-04 at 02 37 30@2x](https://private-user-images.githubusercontent.com/62473795/345572417-a6d45f31-308f-412d-bab0-1e1987a9cd00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNTYzNDgsIm5iZiI6MTcyMDA1NjA0OCwicGF0aCI6Ii82MjQ3Mzc5NS8zNDU1NzI0MTctYTZkNDVmMzEtMzA4Zi00MTJkLWJhYjAtMWUxOTg3YTljZDAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDAxMjA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0MmU3ODQ4ZjBjZDRkOWRjOGU0MGRhNzg1ODJkYzJjODQ3YTE5ZjhjMTQyMDIzZGI2NGEyOTA0MmY5MWViMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bc2v3Rpfm1G9jLmUEDV_13e5HwToFiZ2OiXnR7lk6K0)

是的，使用的是中转的Claude API，这个可以通过优化Prompt来解决吗

**Comment by theowenyoung** [comment]
不可以。只能等 Claude 自己解决。
