### ISSUE TITLE
【建议】原文与译文的区分

### ISSUE THREAD

**Issue by FistChina** [immersive-translate/immersive-translate#186]
使用了几天发现如果在篇幅较大，原文样式较多的情况下， 开启翻译后，译文与原文的样式基本完全相同，无法快速的分辨原文与译文。
建议增加原文与译文的区别显示。
例如译文另起段落，译文增加边框，背景，译文增加标记，译文使用特殊字体，颜色或样式等。

也看到之前有人提过类似的建议，我个人更倾向修改译文展示方式，而非修改原文样式。

【补充】导致眼花的问题还有这个，篇幅较大的时候翻译并不是所有内容都能翻译，所以译文中也穿插着原文

**Comment by theowenyoung** [comment]
译文样式现在已经支持很多种了呀，也可以自定义颜色，边框等等～ 你在界面设置-> 译文设置 试试？

**Comment by FistChina** [comment]
好的，这个功能没发现，我试一下
