### ISSUE TITLE
[Bug]: 由于安卓Firefox浏览器最近有切换程序后网页重复刷新的重大Bug，导致流量计算可能存在错误

### ISSUE THREAD

**Issue by TFX202X** [immersive-translate/immersive-translate#1861]
### 插件版本号 | Version

1.6.2

### 平台 | Platform

Android

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

本人使用安卓Firefox浏览器beta版本128.0b9 (Build #2016029423),最近有切换app后网页重复刷新的重大Bug，导致流量计算可能存在错误，本人账号内的额度已经达到上限
![Screenshot_2024-07-03-15-54-30-935_org mozilla firefox_beta](https://github.com/immersive-translate/immersive-translate/assets/45474716/b1e0dc75-ab12-4f51-92cd-8df300a474ab)，请求开发人员查明原因

### 出现问题的网址 | URL

https://immersivetranslate.com/accounts/usage

**Comment by keyboard3** [comment]
加入微信群或者邮件联系客服 support@immersivetranslate.com 处理 https://immersivetranslate.com/docs/communities/

**Comment by keyboard3** [comment]
会员问题联系客服，方便及时跟进
