### ISSUE TITLE
[Bug]: 无法进行漫画翻译

### ISSUE THREAD

**Issue by Aloxaf** [immersive-translate/immersive-translate#1863]
### 插件版本号 | Version

1.7.1

### 平台 | Platform

Linux

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

尝试了多个漫画翻译网站，均无法进行翻译，会报错：`Immersive Translate ERROR: err TypeError: e.entries() is not iterable`

### 出现问题的网址 | URL

https://www.pixiv.net/artworks/120213591

### 重现步骤 | To Reproduce

1. 进入网站
2. 点击翻译
3. 打开控制台，等待报错

**Comment by keyboard3** [comment]
感谢反馈，火狐执行环境的bug，将在1.7.2修复

**Comment by keyboard3** [comment]
1.7.2 已经更新
