### ISSUE TITLE
增加译文提示样式

### ISSUE THREAD

**Issue by bladeXue** [immersive-translate/immersive-translate#1864]
### 您希望的更新和改进是什么 | Update or Improve

在双语模式下，翻译出来的中文和原版英文如果字体和颜色都一致的话，有时候其实观感不是很直接，能不能在设置中增加一个选项，让翻译出来的中文译文部分，比如有个边框，或者特殊的字体，或者字色，看上去醒目些，可以一眼区分哪些是翻译出来的文字，哪些是英文页面本来的文字

**Comment by theowenyoung** [comment]
目前就是支持的，请在 基本设置里设置即可。

**Comment by theowenyoung** [comment]
![CleanShot 2024-07-04 at 02 35 53@2x](https://github.com/immersive-translate/immersive-translate/assets/62473795/ab9303e0-6ca3-493c-8cd8-233e284e10fa)
