### ISSUE TITLE
[Bug]: github前进返回时会丢失译文显示样式

### ISSUE THREAD

**Issue by ThemanRonin** [immersive-translate/immersive-translate#1865]
### 插件版本号 | Version

1.7.1

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

github中，在主页翻译后点击任意一个文件后会跳转到新页面（覆盖当前页面），然后点击返回上一个页面后，原本翻译好的文本的 译文显示样式 会丢失。好像只有github会出现这个情况 
gif:
![6d4a2f056badf335044853b715c9541f_022ba2b5429fed9c1b9d5fd3f46582cb1282](https://github.com/immersive-translate/immersive-translate/assets/35099500/48ad3c62-568f-4864-bc42-b1fef6792bd5)

### 出现问题的网址 | URL

https://github.com/WinMerge/winmerge

**Comment by Mutter45** [comment]
在google chrome 样式显示
![image](https://github.com/immersive-translate/immersive-translate/assets/93197952/de387d44-4764-44b3-aa91-38180f2e8e94)
在 arc 样式显示
![image](https://github.com/immersive-translate/immersive-translate/assets/93197952/dfc3117e-a05e-4b06-950d-1cf38df9a2a6)
<b>不同浏览器也会出现样式丢失</b>
