### ISSUE TITLE
[Bug]:  macOS 上 Safari 边栏显示配置页的标签页 UI 错乱

### ISSUE THREAD

**Issue by julee** [immersive-translate/immersive-translate#1867]
### 插件版本号 | Version

1.7.1

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

Safari 版本： 17.5 (19618.2.12.11.6)

1. Safari 点击工具栏的“显示边栏”按钮
2. 边栏中点击展开标签页组
3. 工具栏点击沉浸式翻译图标，在菜单中点击“设置”，设置页被打开，这时可以看到边栏中沉浸式翻译的设置页标签页显示错乱。
4. 点击标签页组名称后的向下翻折的按钮，收起侧边栏的标签页列表，然后再点击该按钮展开，边栏中沉浸式翻译的设置页标签页显示将恢复正常。

错乱的图：
<img width="1442" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/1493342/0fbd6db7-a5be-4eb0-9b8d-e74a253b566b">

正常的图：
<img width="1263" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/1493342/a2725e2e-1807-4377-bd08-b295df40fcfc">

**Comment by keyboard3** [comment]
这个是Safari浏览器的问题，插件做不了啥

**Comment by julee** [comment]
> 这个是Safari浏览器的问题，插件做不了啥

没有 work around 的方案吗？ 看着难受。 看起来是沉浸式翻译的那个图标有关系

**Comment by theowenyoung** [comment]
我这里似乎是正常的？或者是我操作的不对？

![CleanShot 2024-07-04 at 17 48 07@2x](https://github.com/immersive-translate/immersive-translate/assets/62473795/24e4f62c-8d9a-494a-91e9-a4f22e1a5dbe)

**Comment by julee** [comment]
> 我这里似乎是正常的？或者是我操作的不对？
> 
> ![CleanShot 2024-07-04 at 17 48 07@2x](https://private-user-images.githubusercontent.com/62473795/345782205-24e4f62c-8d9a-494a-91e9-a4f22e1a5dbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwODY4NzMsIm5iZiI6MTcyMDA4NjU3MywicGF0aCI6Ii82MjQ3Mzc5NS8zNDU3ODIyMDUtMjRlNGY2MmMtOGQ5YS00OTRhLTkxZTktYTRmMjJlMWE1ZGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDA5NDkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0OTYxODJjYWM4NDViMmVmMTI1YmEzNzNjNmY1MGQ4MTJjYTkxMjE3ODc0OTg1MTljZGRhMmUwMmFmMmM1MTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JvOWh6aihYFvWZF6oK5aOIjy8jCQfJF4PpCT276JakI)

1. 需要一开始标签页组就是展开的。 先折叠再展开，侧边栏中的标签页就恢复正常了。
2. 不知道是否是浏览器和沉浸式翻译扩展的差异。 我这按照上文步骤是必现的
