### ISSUE TITLE
[Bug]: 上下标较多的内容，使用腾讯翻译君来翻译，会丢失内容

### ISSUE THREAD

**Issue by 457963413** [immersive-translate/immersive-translate#1868]
### 插件版本号 | Version

至少一年以来的所有版本

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/117076288/0d2a9857-15b7-4bc3-9eb2-a767a4fb7c7c)
有时候内容丢失发生在段落中部，导致难以发现。建议可以使用手动复制网页文本得到的内容作为原文去翻译，虽然这样会失去上下标格式但不会影响理解。我切换到别的翻译服务，似乎能减少此问题。

### 出现问题的网址 | URL

https://www.mdpi.com/2073-4344/11/1/17

### 重现步骤 | To Reproduce

在不同的出版商的网站上阅读论文，大多都会出现此问题。

**Comment by keyboard3** [comment]
这应该是腾讯翻译君问题针对占位符支持的不太好导致的，你可以设置长段落换行，每一段单独翻译
https://dash.immersivetranslate.com/#advanced
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/ba72aabd-3f5d-400d-a8ec-1af016273ce9)

**Comment by 457963413** [comment]
使用DeepL，也出现了内容丢失，在同一个网站。

**Comment by 457963413** [comment]
使用DeepL，也出现了内容丢失，在同一个网站。
![image](https://github.com/immersive-translate/immersive-translate/assets/117076288/7dd651d5-7b58-4896-88bc-777b303bcd83)

**Comment by keyboard3** [comment]
段落越长，这种特殊符号越多越容易出问题。设置长段落换行短一点

**Comment by 457963413** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/117076288/1ee73e5a-fbe5-4e7b-b593-c2a313b4979a)
内容就算很短，也可能会出问题。（https://pubs.acs.org/doi/10.1021/acscatal.7b00588）

**Comment by keyboard3** [comment]
因为原文对公式的处理本身就不合理，未将公式作为整体，这个没啥办法。得看那个翻译引擎更多这个公式的含义了
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/f140dafa-ee51-4fe3-b4d9-7bbf3d5d9b17)

**Comment by flamintune** [comment]
现在针对 pubs.acs 该网站的处理策略是将上下标当作纯文本来处理了，这样能够保证到公式的顺序，以及内容的尽可能保留，但是会丢失上下标效果。

有什么问题欢迎及时反馈，如果效果比较好的话，我们会将此策略延续到其他站点上
