### ISSUE TITLE
增加在原文上生词自动标注功能.每个用户可以设置自己的英语单词级别,外加自己的已掌握单词本

### ISSUE THREAD

**Issue by sherman-yang** [immersive-translate/immersive-translate#1869]
### 您希望的更新和改进是什么 | Update or Improve

默认每个用户可以设置自己的默认英文单词级别. 这个级别以上的单词自动在原文上标注出来. 
在使用的过程中,用户可以点击已标注的单词为"已掌握". 这个单词就加入用户已掌握单词本.以后不再标注.
比如下图中红色单词.就是自动标注的.

![image](https://github.com/immersive-translate/immersive-translate/assets/58446328/bde4bbca-3369-41da-bb86-79d729dc3fa8)

**Comment by sherman-yang** [comment]
用户可以定义热键开启/关闭 自动标注

**Comment by keyboard3** [comment]
你反馈错地方了，你这应该是用的 Relingo ，应该去给relingo 插件反馈

**Comment by sherman-yang** [comment]
没有错. 就是希望这个插件增加这个功能. 这个插件总体来说比relingo好的多. 但是就缺少这个只翻译生词功能. relingo做的太差了.目前看不到希望. 试用了一下 就卸载了

**Comment by sherman-yang** [comment]
用户不是一直需要翻译全文. 有时需要翻译整个网页. 有时只需要翻译一段. 更有时只需要标注自己不认识的生词. 这是不同的翻译需求. 
其实也就是三个翻译级别: 全文/段落/单词(当然如果可以有词组功能那就是最佳的了,我觉得这个非常难实现)

**Comment by keyboard3** [comment]
生词功能不是沉浸式的发展方向，目前不会添加该功能
