### ISSUE TITLE
[Bug]: 我更新了国际象棋专家的棋子名称和常用术语（AI国际象棋专家）

### ISSUE THREAD

**Issue by ptd150891** [immersive-translate/immersive-translate#1870]
### 插件版本号 | Version

1.7.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

我更新了国际象棋专家的棋子名称和常用术语（AI国际象棋专家）

帥=Tướng
仕=Sĩ
相=Tượng
俥=Xe
炮=Pháo
傌=Mã
兵=Tốt
砲=Pháo
馬=Mã
將=Tướng
士=Sĩ
象=Tượng
車=Xe
卒=Tốt
马=Mã
Tiến=进
Thoái=退	
Bình=平
先手=Đi trước
后手=Đi sau
子力优势=Ưu Thế Quân lực
位置优势=Ưu thế vị trí
先机=Tiên cơ
子力劣势=Kém thế quân lực
位置劣势=Nhược thế vị trí
被动=Bị động
均势=Thế cờ cân bằng
平衡=Cân bằng
攻=Tấn công
守=Phòng thủ
和=Hòa
弃=Hy sinh
交换=Trao đổi
冷着=Nước cờ không cần suy nghĩ kỹ
妙手=Nước cờ hay
昏招=Nước cờ sai lầm
跳马=Nhảy Mã
出车=Xuất Xe
跳边马=Tấn Mã biên 
平炮换车=Bình Pháo đổi Xe
炮头=Pháo đầu
兵头=Tốt đầu
补象=Bổ Tượng
平炮=Bình Pháo
进=Tiến
退=Thoái
换=Đổi
吃=Ăn
将军=Chiếu tướng
防守=Phòng thủ
进攻=Tấn công
局势=Thế trận
均衡=Cân bằng
路线=Lộ
胜=Thắng
负=Thua
平=Bình
一=1
二=2
三=3
四=4
五=5
六=6
七=7
八=8
九=9

谢谢。(thank you)

**Comment by akira0245** [comment]
这是中国象棋的术语列表吧，现在的AI国际象棋专家并不是适用于中国象棋的。
而且prompt是通用于各个语言的，没法单独对某个语言进行优化，
把这么多术语都加入prompt也不现实。

**Comment by keyboard3** [comment]
正如楼上所说，不适合加到提示词中

**Comment by ptd150891** [comment]
@akira0245 
As a Vietnamese person with expertise in Xiangqi (Chinese chess), I've noticed that the names of the chess pieces are often mistranslated when using your system. I strongly recommend updating your system to accurately pronounce and translate the correct terminology.

To ensure accurate translations, I suggest referring to reliable sources like:

http://www.01xq.com/
http://dpxq.com/
It's crucial to use the correct names for chess pieces, player names, formations, evaluations, and moves. The two websites mentioned above are specifically dedicated to Xiangqi (Xiangqi), the traditional chess game of China, not Western chess.

In this context, the term "Chess Expert" would be most accurately translated as "Xiangqi Expert" or "Chinese Chess Expert" to reflect the specific game being referred to.

Sincerely thanks!
