### ISSUE TITLE
[Bug]: 开启翻译网页所有区域后部分内容不显示

### ISSUE THREAD

**Issue by fankuiz6** [immersive-translate/immersive-translate#1871]
### 插件版本号 | Version

1.71

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

已更新最新规则，开启翻译网页所有区域后部分内容不显示，实际是存在的，关闭可以正常显示，希望开启翻译网页所有区域后完整显示内容
![图片](https://github.com/immersive-translate/immersive-translate/assets/156877102/7cf227ef-7542-413d-b949-29830bc46cc0)
![图片](https://github.com/immersive-translate/immersive-translate/assets/156877102/5d0e0d0e-c64c-48b6-9315-5099aeeeee24)
![图片](https://github.com/immersive-translate/immersive-translate/assets/156877102/4df1b9e7-cd5a-4c96-bed0-584a84d923de)

### 出现问题的网址 | URL

https://ipinfo.io/

### 重现步骤 | To Reproduce

进阶设置内开启翻译网页所有区域后绿色字体翻译结果不可见，实际是存在的

**Comment by keyboard3** [comment]
更新规则，然后刷新重试

**Comment by fankuiz6** [comment]
> 更新规则，然后刷新重试
我已经更新到最新规则，并且在当前内置config里查看到了ipinfo.io的规则，遍操作步骤：1.7.1版本，点击基本设置，重置设置，新建标签页打开 ipinfo.io 进行翻译，绿色字体内容正常显示翻译结果，进入进阶设置，开启 "是否翻译网页所有区域" 后，新建标签页打开 ipinfo.io 翻译，绿色字体内容翻译结果不可见
![图片](https://github.com/immersive-translate/immersive-translate/assets/156877102/a694b6f6-3819-4f64-8bfc-95be17804845)
![图片](https://github.com/immersive-translate/immersive-translate/assets/156877102/1c1a3994-3f3b-4eb8-8356-eede9fadc2bd)
![图片](https://github.com/immersive-translate/immersive-translate/assets/156877102/5343225e-f49d-4fb1-92e2-0c75476420db)

**Comment by keyboard3** [comment]
你的规则没有更到最新，重新更新

**Comment by fankuiz6** [comment]
> 你的规则没有更到最新，重新更新
在刚才已经卸载重装插件，显示：本地适配规则已是最新: 2024年7月5日 下午6:07:22，问题没有解决，请按我的操作步骤重试一遍：火狐浏览器卸载重装浏览器扩展，1.7.1版本，点击基本设置，重置设置
重点步骤，打开进阶设置里"是否翻译网页所有区域"，新建标签页打开 ipinfo.io 进行翻译，绿色字体内容无法正常显示
![图片](https://github.com/immersive-translate/immersive-translate/assets/156877102/5edc2350-0d19-4431-8b42-4ec5fa2ab9ac)
关闭进阶设置里"是否翻译网页所有区域"，新建标签页打开 ipinfo.io 进行翻译，绿色字体内容正常显示翻译结果
![图片](https://github.com/immersive-translate/immersive-translate/assets/156877102/f9e483c0-a639-4621-bc33-c307b1934e4d)

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/5e74b6b1-6f54-46d9-b8b8-99c108828204)
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/4b0ce51d-b995-4c67-96d7-aafe57e4a0e2)
再更新下

**Comment by fankuiz6** [comment]
> ![image](https://private-user-images.githubusercontent.com/13177744/346125611-5e74b6b1-6f54-46d9-b8b8-99c108828204.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxODM2MDcsIm5iZiI6MTcyMDE4MzMwNywicGF0aCI6Ii8xMzE3Nzc0NC8zNDYxMjU2MTEtNWU3NGI2YjEtNmY1NC00NmQ5LWI4YjgtOTljMTA4ODI4MjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDEyNDE0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2Yjg2M2E2MjhhNzU3ZGExYzZiZTc5MTZlMDI0NzI4MmU5ZmFjMTA2OTU4NzMxZjUyYzQ0YzRhMzYzNDNjMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ma-PbwYn_w-6X4VSzEzDFhWwoTtjq8Gwui9ROSZjbfI) ![image](https://private-user-images.githubusercontent.com/13177744/346125799-4b0ce51d-b995-4c67-96d7-aafe57e4a0e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxODM2MDcsIm5iZiI6MTcyMDE4MzMwNywicGF0aCI6Ii8xMzE3Nzc0NC8zNDYxMjU3OTktNGIwY2U1MWQtYjk5NS00YzY3LTk2ZDctYWFmZTU3ZTRhMGUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDEyNDE0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjMTlmNzAwYzMyMDViZTUwNzlkYzc2YjM5NGIxZDAwYmZkMmU4ZWU1NzQxMTk2MjJjN2FmNTJkYmE5OGFlNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xme16P2RKbpHlQ7OhEGO-WzytDd2BuB3GTCukxoJsEA) 再更新下

感谢更新，没有问题了
