### ISSUE TITLE
从英语翻译成中文后用查找功能时输入中文连一个中文都查找不出来

### ISSUE THREAD

**Issue by 777LLL777** [immersive-translate/immersive-translate#1872]
### 您希望的更新和改进是什么 | Update or Improve

从英语翻译成中文后用查找功能时输入中文连一个中文都查找不出来。比如从英语翻译成中文，连常见词“的”都查找不出来，等于是没有中文查找功能。

**Comment by keyboard3** [comment]
截图或者录屏，浏览器可以正常查找译文的

**Comment by keyboard3** [comment]
暂无反馈，关闭此issue
