### ISSUE TITLE
[Bug]: 重大灾难，沉浸式翻译总是导致youtube页面卡死崩溃

### ISSUE THREAD

**Issue by crysishacker** [immersive-translate/immersive-translate#1874]
### 插件版本号 | Version

1.7.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

edge和火狐都这样

### 出现问题的网址 | URL

youtube.com

**Comment by theowenyoung** [comment]
请问是否有重现的路径？

**Comment by crysishacker** [comment]
请问具体是怎么做？

**Comment by theowenyoung** [comment]
您可以选择录个屏，发上来。

**Comment by crysishacker** [comment]
Uploading 20240710_120713 - Compressed with FlexClip.mp4…

**Comment by keyboard3** [comment]
> Uploading 20240710_120713 - Compressed with FlexClip.mp4…

视频没有上传完，你需要等这个uploading变成地址之后才行

**Comment by crysishacker** [comment]
https://github.com/immersive-translate/immersive-translate/assets/43438174/7360cb96-aa29-4efc-b2a7-8c7abc5bac7c

**Comment by keyboard3** [comment]
你这个很奇怪啊，翻译为什么会影响播放，真没遇到过。 你试试给插件隐身窗口权限，然后再隐身窗口中试试

**Comment by keyboard3** [comment]
把油猴关掉就正常了？

**Comment by crysishacker** [comment]
牛逼，真不愧是程序员，命中问题真精准
我现在只是不会冻死整个页面，但是卡顿的问题依然出现
但是继续排查，是return youtube dislike
只要继续打开更多回复，页面拉到够下
整个页面就崩溃了

**Comment by crysishacker** [comment]
我又把油猴加进去，然后用那种极限的方式试，没出问题
我也不知道为什么
所以是return youtube dislike

**Comment by crysishacker** [comment]
我估计是因为我最后测试油猴的，把插件一个一个再点回禁止隐私模式太烦了
所以我直接在原浏览器（非隐私）测试了关闭油猴

**Comment by dzm211** [comment]
edge插件安装后，插件服务工作进程出错，如下：
background.js:5467 
 Immersive Translate ERROR: create menu error Error: IO error: .../MANIFEST-000001: Unable to create sequential file (ChromeMethodBFE: 7::NewSequentialFile::4)
    at background.js:5450:7833
如何解决？给个方案吧

**Comment by keyboard3** [comment]
> edge插件安装后，插件服务工作进程出错，如下： background.js:5467 Immersive Translate ERROR: create menu error Error: IO error: .../MANIFEST-000001: Unable to create sequential file (ChromeMethodBFE: 7::NewSequentialFile::4) at background.js:5450:7833 如何解决？给个方案吧

这个应该是更新浏览器导致的，试试卸载重装浏览器或者用chrome
