### ISSUE TITLE
翻译接口

### ISSUE THREAD

**Issue by anshangtangyuan** [immersive-translate/immersive-translate#1875]
### 您希望的更新和改进是什么 | Update or Improve

希望能增加讯飞星火的翻译接口。同时希望翻译后的文档保存pdf后可以编辑和选中。感谢

**Comment by theowenyoung** [comment]
讯飞星火我们目前测试还不太适合沉浸式翻译，官方提供的 速率限制 太严格，而且经常出错，等后续稳定之后，我们再评估接入吧～

> 翻译后的文档保存pdf后可以编辑和选中

这个您可以使用 PDF 编辑软件做到。
