### ISSUE TITLE
[Bug]: 控制台报错

### ISSUE THREAD

**Issue by zbw-zbw** [immersive-translate/immersive-translate#1877]
### 插件版本号 | Version

1.7.5

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

<img width="829" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/64134946/118b82bc-81ae-4cb9-a8f7-01e274a85685">
控制台报错

### 重现步骤 | To Reproduce

<img width="829" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/64134946/1d194b5d-8122-4a67-a2b5-67b15d4b1766">

### 补充说明 | Additional context

<img width="829" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/64134946/3988f8c8-0e35-4c47-8141-90e7e6473cf1">

**Comment by keyboard3** [comment]
给下复现路径？

**Comment by keyboard3** [comment]
暂无反馈 暂时关闭此问题
