### ISSUE TITLE
希望提供沉浸式翻译目前支持的所有翻译服务使用的api接口

### ISSUE THREAD

**Issue by fankuiz6** [immersive-translate/immersive-translate#1879]
### 您希望的更新和改进是什么 | Update or Improve

希望在wiki新增一个页面提供沉浸式翻译支持的所有翻译服务使用的api接口，并及时更新，以便在clash、surge等软件中正确分流，防止使用去广告等规则集时导致某个翻译服务无法使用

**Comment by theowenyoung** [comment]
可以。

**Comment by flamintune** [comment]
已提供，在这个页面查看：https://immersivetranslate.com/docs/services/

**Comment by fankuiz6** [comment]
> 已提供，在这个页面查看：https://immersivetranslate.com/docs/services/

已经提供为什么又删除了？

**Comment by flamintune** [comment]
不好意思，之前merge的时候，不小心被覆盖掉了，已修复请查看
