### ISSUE TITLE
对多个较短的段落，一次性发送几段翻译文本，以减少触发 API 频率限制

### ISSUE THREAD

**Issue by iFwu** [immersive-translate/immersive-translate#188]
<img width="419" alt="image" src="https://user-images.githubusercontent.com/16523864/222727023-970228a7-6b2b-4af9-a862-caa3c56581f5.png">

目前 ChatGPT 模型 API 的请求频率限制 20/min（免费版本）对很多有大量短段落的网页来说太低了。

**Comment by theowenyoung** [comment]
目前已经是一次性发送多段文本了。

每次最多1500个字符。
