### ISSUE TITLE
[Bug]: PDF翻译 一句话 多次翻译 导致翻译后显示重叠

### ISSUE THREAD

**Issue by yiumanlenong** [immersive-translate/immersive-translate#1881]
### 插件版本号 | Version

1.7.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

[snuza-user_manual.pdf](https://github.com/user-attachments/files/16136332/snuza-user_manual.pdf)
![Bug](https://github.com/immersive-translate/immersive-translate/assets/123855809/89c44b59-c81b-410e-88e8-7507492be109)

**Comment by keyboard3** [comment]
这是源文件存在脏数据导致的元数据重复，没啥好办法，手动删除多余部分
