### ISSUE TITLE
网页全文翻译时能否排除所有参考文献？

### ISSUE THREAD

**Issue by renaissancecode** [immersive-translate/immersive-translate#1887]
### 您希望的更新和改进是什么 | Update or Improve

如题，对参考文献的翻译意义不大，而且翻译出来格式也不好看，例如这个
<img width="371" alt="Snipaste_2024-07-11_14-23-26" src="https://github.com/immersive-translate/immersive-translate/assets/40464697/1b206186-d1ae-4cf7-a5cb-bc763729fd86">

而且，在对学术论文的网页进行翻译时，参考文献一般在文章末尾，很好识别出来。

因此希望增加一个开关，可以排除所有学术论文网页中的参考文献部分。

**Comment by theowenyoung** [comment]
可以提供一个示例的网址吗？

**Comment by keyboard3** [comment]
已排除引用部分的翻译，打开 https://dash.immersivetranslate.com/#about 自动更新规则，然后重试

**Comment by renaissancecode** [comment]
> 已排除该站点引用部分的翻译，打开 https://dash.immersivetranslate.com/#about 自动更新规则，然后重试

感谢！如果可以的话，能否为所有出版社都适配一下并增加一个开关（可能有些人需要翻译参考文献）？

上面的网页是sciencedirect.com域名（elsevier出版社），以下是其他出版社及其示例文章网页：

- springer，https://link.springer.com/article/10.1007/s12144-024-06037-x
- taylor & francis，https://www.tandfonline.com/doi/full/10.1080/14780887.2020.1725953
- frontiers，https://www.frontiersin.org/journals/psychology/articles/10.3389/fpsyg.2024.1414852/full
- wiley，https://onlinelibrary.wiley.com/doi/10.1002/capr.12648
- oxford academic，https://academic.oup.com/socpro/article/71/2/480/6550377
- sage，https://journals.sagepub.com/doi/abs/10.1177/20552076221129084
