### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by fmvp742637** [immersive-translate/immersive-translate#1888]
### 插件版本号 | Version

1.1.6

### 平台 | Platform

iOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

I cannot change the settings of the extension. For example,  the extension will still use my previous API after I changed to a new API.
插件没法保存我更改后的设置，比如说我更改完api之后，插件依然在用旧的api翻译

### 出现问题的网址 | URL

All URLs. 所有网站

### 重现步骤 | To Reproduce

1. Go to the separate setting page
2. Change any setting, such as api
3. Close the setting page and start translation in a new website. Any setting is not changed. For example, the extension will still use my previous api

**Comment by keyboard3** [comment]
iOS 什么版本？

**Comment by fmvp742637** [comment]
15.1

**Comment by fmvp742637** [comment]
> iOS 什么版本？

15.1

**Comment by keyboard3** [comment]
15.1 是有这个问题。可以下载沉浸式翻译浏览器或者下载油猴脚本的沉浸式翻译
