### ISSUE TITLE
Only inject dark mode-related CSS if current website supports it?

### ISSUE THREAD

**Issue by cheemeng** [immersive-translate/immersive-translate#1889]
### 您希望的更新和改进是什么 | Update or Improve

Currently these CSS styles are injected into every website that has Immersive Translate enabled:

```
/* dark */
@media (prefers-color-scheme: dark) {
  .immersive-translate-search-recomend {
    border: 1px solid #3c4043;
  }

  .immersive-translate-close-action svg {
    fill: #bdc1c6;
  }

  .immersive-translate-search-enhancement-en-title {
    color: #bdc1c6;
  }
}
```

While useful, it creates 2 problems:

1. User is currently having the OS set to dark mode. The website the user is browsing does not support switching of light/dark themes, and only has colours that are light-themed. However, the browser will render Immersive Translate-related stuff using dark theme colours... making some elements hard to see (for instance the close button of the floating ball):

![image](https://github.com/user-attachments/assets/b3e44c79-ba4d-4323-b85c-001a3da33655)

2. Some of the more 'modern' dark mode browser extensions (Noir for example) will try to first detect if the current website has custom styles for dark mode, and if yes, will not auto apply any 'darkening'. I believe the extensions perform that check by detecting for CSS styles with the `prefers-color-scheme: dark/light` media feature. However, because Immersive Translate injects CSS style with `@media (prefers-color-scheme: dark)` in every website, the other extensions think that the website already supports dark mode and thus will not enable anymore 'darkening'.

Would Immersive Translate be able to only inject dark mode CSS if it detects that the current website already supports dark mode in the first place? Thank you!

**Comment by theowenyoung** [comment]
Thank you, we'll remove these css on 1.8.2 version.
