### ISSUE TITLE
proposal: 用正文提取算法自动识别出正文、只翻译正文

### ISSUE THREAD

**Issue by seeflood** [immersive-translate/immersive-translate#189]
因为用chatgpt api 要收费，因此想只翻译正文、减少不必要内容的翻译。
看到咱们有规划“只翻译选中文本” https://github.com/immersive-translate/immersive-translate/issues/176

要不要考虑用正文提取算法来自动识别正文、只翻译正文？

**Comment by theowenyoung** [comment]
额，我们目前的默认设置就是自动识别正文和只翻译正文的？

你会发现大多数网站的头部，尾部，侧边栏都是不翻译的。 不过这个算法还在持续优化中～

**Comment by seeflood** [comment]
感谢解答！
可能是因为我用的时候遇到一些bad case，所以误会了……

比如 https://blog.envoyproxy.io/envoy-stats-b65c7f363342 
会把底部的推荐内容也翻译了
<img width="748" alt="image" src="https://user-images.githubusercontent.com/26001097/222950060-54dea056-54ac-4d8a-96ed-2541a24d79e1.png">

**Comment by theowenyoung** [comment]
好吧，这是 feature，我指的非正文的内容是 那些头部和尾部的： 比如 Terms, 导航 这类的东西。

这可能是一种权衡，也许未来可以区分一下等级：

超级清爽 - 清爽 -全部区域


第一个等级就只翻译正文..

**Comment by seeflood** [comment]
ok，那我先关issue啦
