### ISSUE TITLE
同一个网站文字版本可以被翻译，但是视频页面无法获得翻译文字

### ISSUE THREAD

**Issue by YCisYC** [immersive-translate/immersive-translate#1891]
### 您希望的更新和改进是什么 | Update or Improve

希望该网页能获得中文翻译，因为该网站是在可被翻译的网页清单中。
https://learning.edx.org/course/course-v1:MITx+CTL.SC0x+2T2024/block-v1:MITx+CTL.SC0x+2T2024+type@sequential+block@93ce0c72070548c4b661f59f9c67d486/block-v1:MITx+CTL.SC0x+2T2024+type@vertical+block@0c8402fd25094a74a9a8a8cc458e9d46

**Comment by keyboard3** [comment]
切换字幕之后试试看

**Comment by keyboard3** [comment]
暂无反馈 关闭此issue
