### ISSUE TITLE
建议把“翻译文本”加入浏览器右键菜单项，选中原文后可以便捷使用多个翻译服务对比

### ISSUE THREAD

**Issue by lianwensheng** [immersive-translate/immersive-translate#1897]
### 您希望的更新和改进是什么 | Update or Improve

直接点击悬浮球来翻译网页很方便，感觉右键“翻译网页”使用率很低，建议把“翻译文本”加入浏览器右键菜单项，选中原文后可以便捷跳转到这里  https://app.immersivetranslate.com/text/  使用多个翻译服务对比，很多翻译不准确的句子很需要这个对比功能...

**Comment by theowenyoung** [comment]
这个交互看起来很自然，我觉得可以支持一下。 让右键菜单在不同的场景里改为不同的功能。
