### ISSUE TITLE
[Bug]: 双语字幕时间线错乱

### ISSUE THREAD

**Issue by renaissancecode** [immersive-translate/immersive-translate#1899]
### 插件版本号 | Version

1.7.6

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

youtube双语字幕时间线不对
<img width="641" alt="1" src="https://github.com/user-attachments/assets/2265d2ff-214e-4fae-b8a2-561d0f919e6e">
<img width="641" alt="2" src="https://github.com/user-attachments/assets/a3399e82-46c5-43ad-9f82-58c9b5dfd7db">

### 出现问题的网址 | URL

https://www.youtube.com/watch?v=a55TFQ4VHKw

**Comment by keyboard3** [comment]
我这里正常的。刷新重试下，看下该视频选择的字幕类型
![image](https://github.com/user-attachments/assets/348c0507-ee34-4312-ab55-6824aac2233c)
![image](https://github.com/user-attachments/assets/420935ba-70db-4647-adf0-854fc2da75dc)

**Comment by renaissancecode** [comment]
> 我这里正常的。刷新重试下，看下该视频选择的字幕类型 ![image](https://private-user-images.githubusercontent.com/13177744/348516220-348c0507-ee34-4312-ab55-6824aac2233c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5MzQzMzEsIm5iZiI6MTcyMDkzNDAzMSwicGF0aCI6Ii8xMzE3Nzc0NC8zNDg1MTYyMjAtMzQ4YzA1MDctZWUzNC00MzEyLWFiNTUtNjgyNGFhYzIyMzNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDA1MTM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmZDlkNmVkNzJlNWQ3OGYxYTdkYWYyODhjNTlkMWUxYWU5YWQyZGI1MTk4ODA0MmRkZGFjZjA2N2Y3MGI4YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dKF01F-N-fqgGN8AhxUbeCc-m7fZjNgz4uZDr1zImSs) ![image](https://private-user-images.githubusercontent.com/13177744/348516242-420935ba-70db-4647-adf0-854fc2da75dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5MzQzMzEsIm5iZiI6MTcyMDkzNDAzMSwicGF0aCI6Ii8xMzE3Nzc0NC8zNDg1MTYyNDItNDIwOTM1YmEtNzBkYi00NjQ3LWFkZjAtODU0ZmMyZGE3NWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDA1MTM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2MzE1OWU0OTQ1ZDE5NDRlMzhhMjE2YjM4N2E5MWJmMWI5NjM0Njk0YWY2ODU3OWY2MzkwYjBkNjYzNDI4NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7IwpMKGOZvli5lDAhzPpcN3SsHuwhv-wmZ7LyTY_Ubs)

刷新后依然错乱（且每次刷新后，错乱的内容还不一样），字幕设置和你的一样。翻译服务之前是deeplx，更换豆包、谷歌后依然如此。youtube相关的拓展只安装了这个（但禁用后字幕依然错乱）https://chromewebstore.google.com/detail/improve-youtube-%F0%9F%8E%A7-for-yo/bnomihfieiccainjcjblhegjgglakjdd
<img width="641" alt="Snipaste_2024-07-14_13-14-51" src="https://github.com/user-attachments/assets/c7f74186-bde4-4d21-bb76-da4ca3f5db64">
<img width="641" alt="Snipaste_2024-07-14_13-20-59" src="https://github.com/user-attachments/assets/70425653-1d34-4e5e-bb4c-c881357a7d61">

**Comment by keyboard3** [comment]
给插件隐身窗口权限，在隐身窗口下试试

**Comment by renaissancecode** [comment]
> 给插件隐身窗口权限，在隐身窗口下试试

无痕模式下是正常的，很奇怪，不知道是和哪个插件冲突了，但应该是最近才冲突的，因为之前都是正常的
