### ISSUE TITLE
加一个支付宝、微信收款码

### ISSUE THREAD

**Issue by lin64850** [immersive-translate/immersive-translate#19]
加一个支付宝、微信收款码方便国内用户赞助支持

**Comment by theowenyoung** [comment]
谢谢你的提议，但是我由于个人原因，目前还没准备好关联一个实名的账户，但是也许未来会！

我今天开通了Github的Sponsor主页： <https://github.com/sponsors/theowenyoung> , 它支持用Paypal的中国账户赞助。抱歉带来的麻烦。

**Comment by theowenyoung** [comment]
感谢大家～ 我已经开通了国内的 爱发电主页： <https://afdian.net/a/translate> ,  可以使用微信和支付宝赞助了～
