### ISSUE TITLE
是否有源代码开源计划？

### ISSUE THREAD

**Issue by oodzchen** [immersive-translate/immersive-translate#190]
我看了下仓库里面只有构建后生成的代码，没有打包之前的源码，这样似乎不方便其他开发者参与贡献，请问是否有源码开源计划？

**Comment by theowenyoung** [comment]
https://github.com/immersive-translate/immersive-translate/issues/41

目前已经有超过30位同学加入私有项目的团队了，所以想贡献的同学可以联系我～

**Comment by Glaceon2** [comment]
@theowenyoung  可以让我也加入吗? 我想贡献Azure TTS的功能

**Comment by a0c5a5d** [comment]
现在还有计划邀请新贡献者不，目前负责做大模型微调和应用，希望加入

**Comment by a0c5a5d** [comment]
@theowenyoung  现在还有计划邀请新贡献者不，目前负责做大模型微调和应用，希望加入

**Comment by theowenyoung** [comment]
@a0c5a5d 您好，目前停止邀请了，谢谢！

**Comment by a0c5a5d** [comment]
Hello, I have received your email. I will deal with it within two days after I see it. (auto reply)
