### ISSUE TITLE
能不能加个默认仅译文？中英对照看着太难受了，我又不是来学英语的

### ISSUE THREAD

**Issue by randook** [immersive-translate/immersive-translate#1901]
### 您希望的更新和改进是什么 | Update or Improve

如题

### 补充说明 | Additional context

无

**Comment by keyboard3** [comment]
https://immersivetranslate.com/docs/usage/#%E4%BB%85%E6%98%BE%E7%A4%BA%E8%AF%91%E6%96%87

**Comment by randook** [comment]
好的
