### ISSUE TITLE
一个命令（快捷键）可以切换三种模式，而不是要多个命令

### ISSUE THREAD

**Issue by heartacker** [immersive-translate/immersive-translate#1902]
### 您希望的更新和改进是什么 | Update or Improve

![image](https://github.com/user-attachments/assets/720cc7ff-2b38-43f8-8a66-5d7d036fc25b)

切换翻译，不翻译和双语模式，是不同的命令，

希望可以用一个 命令（快捷键） 可以在以下几种模式切换
1. 双语模式
2. 仅仅翻译模式
3. 显示原文

**Comment by keyboard3** [comment]
3种模式切换通过一个按键会带来很多问题，这个我们在早期也尝试过
