### ISSUE TITLE
[Bug]: 无法翻译该网页，且没有提示问题，单纯的不工作

### ISSUE THREAD

**Issue by ftdlee1104** [immersive-translate/immersive-translate#1909]
### 插件版本号 | Version

1.7.6

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

无法翻译该网页，全文和鼠标悬停都不可以，感觉对学术wiley期刊支持得不太好，UI也比较不好看

### 出现问题的网址 | URL

https://onlinelibrary.wiley.com/doi/10.1111/apt.15650

### 重现步骤 | To Reproduce

1. 打开网页
2. 全文翻译，无响应
3. 鼠标悬停，无响应
4. 刷新网页，重复上述操作，依然无效

### 补充说明 | Additional context

无

**Comment by keyboard3** [comment]
![image](https://github.com/user-attachments/assets/58447a94-bf04-4af5-811f-ecb714520c0b)
正常翻译呀，你其他网页能翻译吗？重启下浏览器试试

**Comment by ftdlee1104** [comment]
抱歉打扰，重启浏览器解决。谢谢

________________________________
