### ISSUE TITLE
【建议】添加一个隐藏原文的选项

### ISSUE THREAD

**Issue by oodzchen** [immersive-translate/immersive-translate#191]
可以把原文隐藏掉，网页翻译之后就只看翻译后的文本就行了，同时显示原文和译文我个人觉得有点分心，不够沉浸式。

同时可以考虑设置 hover 的时候显示原文，或者添加一个小按钮，想看原文的话点击一下就行。

**Comment by 759852125** [comment]
正有此意

**Comment by theowenyoung** [comment]
这个功能在计划中，相关issues：

- https://github.com/immersive-translate/immersive-translate/issues/59
