### ISSUE TITLE
pdf pro会员翻译医学论文文献时数字被翻译成了图片格式无法后续编辑

### ISSUE THREAD

**Issue by gtxyqjc** [immersive-translate/immersive-translate#1910]
### 您希望的更新和改进是什么 | Update or Improve

能不能翻译后的格式跟之前一样，数字以及符合也可以复制粘贴

**Comment by theowenyoung** [comment]
这个一般是 AI 无法把它转为文本格式才会用图片，大多数数学公式都可以被转为文本。您可以上传下 PDF 和 对应出问题的截图，我们跟进下看看有没有优化空间。

**Comment by gtxyqjc** [comment]
感谢你们的回复，是这样的，如果我在网页上有插件翻译，是不会有这些图片格式的，但是又有一个问题就是论文里引用的内容，比如(4), 这种对应的reference也会有，但是如果上传pdf这个反而会被变成图片格式，但是数字也会没有，变成空格无法复制，也就是图片格式，你们可以随便找一个论文一测便知。 现在有没有好的办法既可以保留数字，让它可以复制，又可以自动把论文括号里引用的部分自动去除掉

**Comment by gtxyqjc** [comment]
是的，pro pdf

Owen ***@***.***> 于2024年7月22日周一 17:18写道：

**Comment by theowenyoung** [comment]
我懂了，您指的是这里的 公式被转为了 SVG 是吗？

如果是这个问题的话，我们目前没有更多的优化方式，因为数学公式在HTML里本身并不是有效，可复制的文字。


示例公式PDF 翻译：[公式识别demo-zh-CN-dual.html.zip](https://github.com/user-attachments/files/16337316/demo-zh-CN-dual.html.zip)

**Comment by gtxyqjc** [comment]
没错，是这样的，就跟你发来的demo问题一样，那么基于现在的情况，如果我又想解析出pdf(那种比较复杂的论文文献), 又想保留数字公式是不可能的是吗？
我只能一次性复制完然后再去填里面的数字公式空白吗

Owen ***@***.***> 于2024年7月23日周二 01:06写道：

**Comment by keyboard3** [comment]
数字公式现在在pdf-pro鼠标右键支持复制公式了
![image](https://github.com/user-attachments/assets/d3ca57d9-0ebf-4441-a2c7-f1bb40117ad3)
