### ISSUE TITLE
[Bug]: Youtube视频翻译时间轴错乱

### ISSUE THREAD

**Issue by knatman** [immersive-translate/immersive-translate#1912]
### 插件版本号 | Version

1.7.7

### 平台 | Platform

macOS

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

使用沉浸式翻译翻译youtube 视频的字幕时，时间轴错乱，无法正常使用

**Comment by keyboard3** [comment]
YouTube 字幕分几类，自动生成字幕和非自动生成字幕，沉浸式不会修改时间轴。这两类时间轴中非自动生成字幕经常和视频对不上，这个是yt自身问题。一般建议使用自动生成字幕，这个是yt采用asr识别生成的字幕

**Comment by keyboard3** [comment]
如果你有使用广告类插件也会影响时间轴
