### ISSUE TITLE
[Bug]: Shopify的inbox功能里面部分内容无法翻译

### ISSUE THREAD

**Issue by crazycock** [immersive-translate/immersive-translate#1913]
### 插件版本号 | Version

1.7.6

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

shopify的inbox功能，聊天内容部分无法翻译，通常都是短一些的句子。
![WechatIMG8](https://github.com/user-attachments/assets/38b1e548-4561-400b-b4d7-ebf14617acdf)
![WechatIMG9](https://github.com/user-attachments/assets/62623403-715f-4011-951e-e957aa2ab41f)
![WechatIMG10](https://github.com/user-attachments/assets/8cb19644-7aab-464d-9fb5-dafce89a8012)

**Comment by keyboard3** [comment]
![image](https://github.com/user-attachments/assets/93481c25-ccf5-49b1-9430-116118fab833)
生成个网页快照出来看看

**Comment by keyboard3** [comment]
多语言识别问题，需要指定源语言

**Comment by crazycock** [comment]
已解决
