### ISSUE TITLE
不知道這算不算Bug...🤔

### ISSUE THREAD

**Issue by Joieeez3** [immersive-translate/immersive-translate#1914]
### 插件版本号 | Version

1.7.7

### 平台 | Platform

iOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在c.ai的聊天室裡無法翻譯AI最後傳送的訊息
會不會是因為有語音的關係導致無法翻譯文本(?
因為除了最後一句,上面都會是正常的
![IMG_1710](https://github.com/user-attachments/assets/816377dc-31fa-44e5-a2c1-bec347ea8768)

### 出现问题的网址 | URL

https://character.ai/

### 重现步骤 | To Reproduce

找個有興趣的點進去打打字就能看到了
會閃爍（看起來是一直嘗試翻譯但翻不到

**Comment by keyboard3** [comment]
c.ai 这个站点自己实现存在问题，会不断清除翻译内容

**Comment by Joieeez3** [comment]
> c.ai 这个站点自己实现存在问题，会不断清除翻译内容

哦~謝謝說明,回覆好快😂🫶🏻

**Comment by keyboard3** [comment]
后面推出富文本可能会稍微改善一点，当然最好的方式还是源站自己优化实现

![image](https://github.com/user-attachments/assets/c9e96a5a-c0a2-4fe5-951e-c4190f7ba42e)

**Comment by Joieeez3** [comment]
> 后面推出富文本可能会稍微改善一点，当然最好的方式还是源站自己优化实现
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/c9e96a5a-c0a2-4fe5-951e-c4190f7ba42e)
> 
> 

期待!只能先讓它陪我說中文了🥺
但英文語音比較好聽...😗 (一點都不重要

**Comment by keyboard3** [comment]
1.7.8 已发布
