### ISSUE TITLE
https://discord.com/ 网站的优化和更好的适配

### ISSUE THREAD

**Issue by ictsmc** [immersive-translate/immersive-translate#1915]
### 您希望的更新和改进是什么 | Update or Improve

1.聊天对话框中的名称不要翻译，
2.discord中的直播能否增加字幕翻译功能，
3.或者作者认为更好的优化 适配这个网站

**Comment by keyboard3** [comment]
打开 https://dash.immersivetranslate.com/#about 自动更新下规则，然后重试下 。userName应该不翻译了

2 没办法，沉浸式目前可以翻译已存在字幕，直播无法支持
