### ISSUE TITLE
[Bug]: “翻译输入框 ”不支持 shadow dom 中的输入框

### ISSUE THREAD

**Issue by KnIfER** [immersive-translate/immersive-translate#1918]
### 插件版本号 | Version

1.7.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

“翻译输入框 ” 该功能似乎不支持 shadow dom 中的输入框，按下快捷键没有反应。将 shadow dom 换成普通的 dom ， 又可以了。

### 出现问题的网址 | URL

any

**Comment by keyboard3** [comment]
给下具体地址
