### ISSUE TITLE
[功能请求]快速设置网站样式

### ISSUE THREAD

**Issue by photkey** [immersive-translate/immersive-translate#192]
![image](https://user-images.githubusercontent.com/60434581/222880538-db8b6d87-5826-4c23-999c-eef2cc8ff58b.png)
类似这个`针对该网站`，增加一个`该网站样式`，可以快速选择网站样式。
目前我的默认样式是`斜体`，需要个性化配置的网站分为两大类：黑底白字的网站使用 `None` 淡黄色；白底黑字的网站使用 `黑灰色`，现在每次都要进配置文件手写 很麻烦，希望可以增加这种快速选择的方式。

**Comment by theowenyoung** [comment]
感觉这里需要一个二级菜单，或者新增一个一级菜单才行？

**Comment by theowenyoung** [comment]
如果只是想要一个快捷入口的话，也可以添加那个开发者设置页面为书签，然后快速点击进去？ Edit full user script?

**Comment by theowenyoung** [comment]
编辑fullconfig 只有离开焦点的才会自动保存，输入的时候不会自动保存呀

**Comment by theowenyoung** [comment]
奇怪 我这没这个问题呀。 要不你在隐私模式下试试？ 试试只开这个插件

**Comment by theowenyoung** [comment]
我试了一下chrome，好像也是正常的..

**Comment by keyboard3** [comment]
时间太久，该问题关闭，有新需求可以开新的issue
