### ISSUE TITLE
希望能针对rfc html文档进行优化

### ISSUE THREAD

**Issue by Linyh0115** [immersive-translate/immersive-translate#1920]
### 您希望的更新和改进是什么 | Update or Improve

![image](https://github.com/user-attachments/assets/da19ff60-c2cb-4ee5-a48f-0f4b234b542b)

例如rfc这种文本表示的图、表会被翻译，希望不用翻译。

**Comment by keyboard3** [comment]
rfc文本是纯字符排版，非html排版很难识别它是一个表格
