### ISSUE TITLE
🔴「临时使用 XX 翻译」支持更多翻译服务

### ISSUE THREAD

**Issue by Thomas-Harrell** [immersive-translate/immersive-translate#1921]
### 您希望的更新和改进是什么 | Update or Improve

---

- 希望「临时翻译页面」能对更多翻译服务（其他 LLM 模型、DeepLX、自定义 AI 等）进行适配

---

![image](https://github.com/user-attachments/assets/3d6bece7-ae09-47f7-bc27-1585daad65f3)

---

**Comment by theowenyoung** [comment]
浏览器没有为插件提供修改 快捷键 的API，所以必须跳转到浏览器自己的页面去设置快捷键，同时快捷键声明也必须预先声明，所以只能以折衷的交互支持。

> 临时调用翻译在左下角会出现提示弹窗，在「进阶设置」添加设定是否显示提示的选项，获得更沉浸的体验

(不想再增加更多设置了，设置越多，普通用户越懵逼..）

```
LLM 模型的 temperature 选项没有注释，可以把教程文档里面 temperature 的部分添加上去

temperature 开头字母「t」使用大写「T」

LLM 模型增加 top_p 选项，虽然并不是所有模型都支持设置
```

Temperature 的大小写和描述问题将在下个版本优化，感谢～


`top_p`,`top_k` 选项暂时没有计划支持.

> 缓存自动清理：以「日期或缓存大小」为界定，在到达设定值后，自动清理最早缓存的内容

谢谢，这个有在我们的路线图中，预计将直接支持自动删除30天之前的缓存。

> 将 AI 专家 GitHub 仓库里对应配置添加到 AI 专家的子页面里，可以更方便直观的查看

谢谢建议，这个我们应该可以支持下。

**Comment by theowenyoung** [comment]
因为它预先定义了所有快捷键：


![CleanShot 2024-07-25 at 23 55 43@2x](https://github.com/user-attachments/assets/33bb66ae-9af6-4795-84a5-5502a5561ebd)

**Comment by theowenyoung** [comment]
理论上插件自己也能实现快捷键监听，但是有可能和系统快捷键有冲突。 像我们的油猴脚本就是自己实现的快捷键监听。

![CleanShot 2024-07-26 at 14 39 42@2x](https://github.com/user-attachments/assets/c0d5ae1e-9293-4bf3-bc9e-33333a50cd2e)

**Comment by theowenyoung** [comment]
> 1.7.8 版本「阿里云百炼大模型」服务里面没有「富文本翻译」选项，百度和腾讯的也是

我们正在逐步测试不同模型对富文本翻译的兼容性，测试ok的话，预计将在 1.8.2 版本支持该选项，想提前用的话，也可以手动在 【开发者设置】中编辑用户配置，在翻译服务下： `enableRichTranslate: true` 即可开启。

> 开启富文本后（默认开启），YouTube 中文字幕视频会出现多余的字幕注释，还有单词漏翻的情况

看下 1.7.9 有没有解决,1.7.9 单独处理了 字幕翻译，字幕翻译强制都纯文本翻译。


> 「通义千问」模型在英语字幕视频会出现多余字幕注释的问题，但中文字幕视频是没有这类问题的

具体是通义千问的哪个模型？ 可以试试 1.7.9版本，确实不同的模型的能力不太一样，很难兼顾所有的模型，我们是优先考虑 openai gpt3.5, gpt-4o-mini 模型。

> 1.7.8 版本「在播放器显示双语字幕快捷方式」选项失效的 BUG 已经看到有人在反馈了

已经修复。

**Comment by theowenyoung** [comment]
目前已经支持在设置页 快捷键 里设置自定义翻译服务的快捷键。

> 在「AI 专家」相应专家的子页面添加用于跳转到 GitHub 仓库内对应专家配置文件的超链接如何

可以的～ 将在 1.9.2 版本支持，作者的部分加一个超链接即可。

> 要是能把「阿里云百炼大模型」里面的第三方服务适配一下，相当于变相支持了一堆 LLM 翻译服务

这个应该暂时没计划

> 后续会出三步骤「直译、反思、意译」的 AI 专家吗？看到 Discussions 里面也有在https://github.com/immersive-translate/immersive-translate/discussions/1917的

会的，但是这个issue 暂时先关了哈～
