### ISSUE TITLE
[Bug]: Automatic downloading of subtitle files

### ISSUE THREAD

**Issue by SHAY5555-gif** [immersive-translate/immersive-translate#1923]
### 插件版本号 | Version

1.7.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

When translating a subtitle file, the system automatically downloads a bilingual file with the translation. It cannot be disabled; clicking the box does nothing.

### 出现问题的网址 | URL

https://app.immersivetranslate.com/download-subtitle/

**Comment by flamintune** [comment]
You can choose whether or not to download automatically here.  And what is you said about box.
![image](https://github.com/user-attachments/assets/2eb495df-7464-4a92-92c9-605ab7f77f2a)
