### ISSUE TITLE
[Bug]: 自定义prompt为空时，不要传入参数，而不是传空字符串

### ISSUE THREAD

**Issue by GrayXu** [immersive-translate/immersive-translate#1925]
### 插件版本号 | Version

1.7.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 请描述这个Bug | Describe the bug

包括google gemma等模型在内是不支持system prompt的。  
虽然自定义prompt可以不填东西，但仍然参数会传role=system的信息，内容是空串。  
建议多加个判断，空的prompt就不传这个参数了。

**Comment by keyboard3** [comment]
下一个版本支持

**Comment by keyboard3** [comment]
1.7.8 已支持
