### ISSUE TITLE
[Bug]: vtt文件翻译后用Subtitle Edit编辑无法正常显示内容

### ISSUE THREAD

**Issue by gggccc44** [immersive-translate/immersive-translate#1927]
### 插件版本号 | Version

1.7.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

打开后只显示最后一行，应该是生成的格式有错。播放视频可以正常加载。应该只是个小bug

**Comment by gggccc44** [comment]
> 能正常播放，那难道不该找 Subtitle Edit ？

因为我看了下格式，手工修改后Subtitle Edit能正常编辑，所以我才说是本软件的错，实际上就是个文本文件，但是翻译后格式不对，播放器估计是不识别文件头标识和序号只识别时间所以能用。不要随便甩锅

**Comment by TaoLoading** [comment]
> > 能正常播放，那难道不该找 Subtitle Edit ？
> 
> 因为我看了下格式，手工修改后Subtitle Edit能正常编辑，所以我才说是本软件的错，实际上就是个文本文件，但是翻译后格式不对，播放器估计是不识别文件头标识和序号只识别时间所以能用。不要随便甩锅

具体是哪块格式不正确呢，请给出示例方便定位问题

**Comment by gggccc44** [comment]
> > > 能正常播放，那难道不该找 Subtitle Edit ？
> > 
> > 
> > 因为我看了下格式，手工修改后Subtitle Edit能正常编辑，所以我才说是本软件的错，实际上就是个文本文件，但是翻译后格式不对，播放器估计是不识别文件头标识和序号只识别时间所以能用。不要随便甩锅
> 
> 具体是哪块格式不正确呢，请给出示例方便定位问题

本软件直接翻译vtt文件会自动加序号，而且不是1开头而是2开头，这点肯定是本软件的问题。vtt文件默认文件头是“WEBVTT”，我看了下Subtitle Edit转换后用的文件头内容是“WEBVTT FILE”。只要把翻译后的文件头改了那个序号不改也能正常编辑，不过建议你们还是查下代码，可能和那个有关，因为“WEBVTT”文件头没序号的vtt文件能正常编辑的。要么就像原始vtt文件一样别加序号，反正这个错误肯定是本软件的锅

**Comment by TaoLoading** [comment]
你好，经核查确实存在序号错误问题，现已修复，感谢反馈。此外正常情况下序号只是每个字幕块唯一的标识，并不会影响字幕的功能和显示，另外根据 W3C 规范标准的 vtt 文件应以“WEBVTT”开头，正如楼内 @moleoxa 所说考虑是 Subtitle Edit 做了特殊处理。

有其他问题欢迎反馈，大家友好交流哈，我们共建和谐社区

**Comment by gggccc44** [comment]
> > 因为我看了下格式，手工修改后Subtitle Edit能正常编辑，所以我才说是本软件的错，实际上就是个文本文件，但是翻译后格式不对，播放器估计是不识别文件头标识和序号只识别时间所以能用。不要随便甩锅
> 
> 不是很明白你这句话里面的逻辑，Subtitle Edit 又不是行业标准，难道我写一个只支持 srt 的编辑的程序，非 srt 字幕就全部是 bug 产物吗？
> 
> 不要随便给别人扣黑锅。

本软件也不是行业标准啊。但是结果是本软件造成的吧？你可以说Subtitle Edit也有问题，但是我说本软件有问题哪里错了？怎么就扣黑锅了？

**Comment by TaoLoading** [comment]
虽然但是楼内的 moleoxa 只是用户，并非官方人员。。。不要误伤。。。有问题还是欢迎反馈的 @gggccc44

**Comment by gggccc44** [comment]
> subtitle edit 这个长久失修？？？

你张嘴就来啊。自己看https://github.com/SubtitleEdit/subtitleedit/releases

我都关闭问题了你还来bb，幸好你不是开发者。。。看了下你也没开发过啥啊，一副很懂的样子。。。你反馈过什么bug提过什么有用的建议说来听听？

VTT文件本身标准是不带序号只有时间码的吧，那这软件为什么要带序号？难道这不算bug？你懂个球啊

以下给开发者：

开发者别怪我，是这二货先开始的，我都关关闭问题了。。。你也申明的丫就只是用户，幸好幸好。。。

再补充下我为啥先在本软件反馈，首先我看到SubtitleEdit编辑出错，然后打开文件看到是转换后的文件加了序号而且2开始（我看到vtt文件默认是没序号的）觉得更可能是本软件bug，还有本软件开发者应该有国人，当然我会先来这边反馈，万一是你们的锅咱们改了不是更好？如果不是也不费啥事。那边老外的除非特别不能忍我是懒得去说的，而且我也手工自己解决了前面说过“WEBVTT FILE”。
