### ISSUE TITLE
可以去除扩展按钮的感叹号

### ISSUE THREAD

**Issue by elonshen** [immersive-translate/immersive-translate#1928]
### 您希望的更新和改进是什么 | Update or Improve

在浏览网站时,如果当前网站没有授权过会出现感叹号,看着很不舒服.

<img width="47" alt="Screenshot 2024-07-23 at 11 00 25" src="https://github.com/user-attachments/assets/dea471b0-0133-423e-83db-a1817939accf">

### 补充说明 | Additional context

Safari浏览器的扩展

**Comment by keyboard3** [comment]
授权就可以了，Safari针对没有授权站点所有扩展都会提示这个，不是插件可以控制的

**Comment by elonshen** [comment]
我另外有个插件没授权也没有感叹号,是因为需要的权限级别不同的原因吗?

<img width="366" alt="Screenshot 2024-07-23 at 11 14 10" src="https://github.com/user-attachments/assets/28f1e50c-2a04-4927-a538-7edee48e95df">

**Comment by keyboard3** [comment]
你在设置中针对插件的其他网站选择”拒绝“就可以了
![image](https://github.com/user-attachments/assets/74cc5e02-588f-4ab7-81c7-be7d3e243a05)
![image](https://github.com/user-attachments/assets/20664344-36c7-4dd2-abe1-4b502fb25e9a)
