### ISSUE TITLE
[BUG] The Tampermonkey script affects the floating components of the YouTube video window.

### ISSUE THREAD

**Issue by Roiocam** [immersive-translate/immersive-translate#193]
# before disabling the `immersive-translate` script

![image](https://user-images.githubusercontent.com/26020358/222909567-afabc3e2-fc50-4333-a3d5-ff2c2ef9dde6.png)

![image](https://user-images.githubusercontent.com/26020358/222910918-eba5877a-c71f-4197-8178-ea882658171a.png)

# after disabling the `immersive-translate` script

![image](https://user-images.githubusercontent.com/26020358/222909844-3f9c1228-bf4a-4cdb-afab-8dafc24a380f.png)

![image](https://user-images.githubusercontent.com/26020358/222913356-259c122b-8c60-41d0-b911-7e2656b80666.png)

## diffrence

look like this script adds a "disable icon" DOM after the youtube progress bar.

![image](https://user-images.githubusercontent.com/26020358/222913321-efdee08d-d6bb-47a8-980b-e82e341d1402.png)

**Comment by Roiocam** [comment]
But this is not a problem, because I could filter youtube on the setting.

**Comment by theowenyoung** [comment]
Sorry for the late reply, I tried today, it seems everything is fine with the latest version of Immersive Translate, do you still have this issue? @Roiocam

**Comment by Roiocam** [comment]
> Sorry for the late reply, I tried today, it seems everything is fine with the latest version of Immersive Translate, do you still have this issue? @Roiocam

In a certain version of history, this issue was fixed. The plugin always adds elements to the DOM after site has been render, regardless of whether the user chooses to translate or not. This may have been the cause of this issue.

However, the problem has been fixed, and I will close this issue. Thank you.
