### ISSUE TITLE
[Bug]: Error of not translating some paragraphs, translation was missed

### ISSUE THREAD

**Issue by ptd150891** [immersive-translate/immersive-translate#1930]
### 插件版本号 | Version

1.7.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 请描述这个Bug | Describe the bug

Error of not translating some paragraphs, translation was missed.
![fix](https://github.com/user-attachments/assets/c675ab8d-d1a1-4282-87e9-4090fd2a8c9e)

### 补充说明 | Additional context

Error of not translating some paragraphs, translation was missed
The proper name was misread. I used gemini and chess expert to translate the subtitle file from Chinese to Vietnamese.
![fix1](https://github.com/user-attachments/assets/cc3c1959-a000-4e40-bdff-9c0bc31c6296)
![fix2](https://github.com/user-attachments/assets/b5af74dd-ceaf-4969-89b4-dd3b8ea7199d)
Hope to have it resolved soon, thank you.

**Comment by keyboard3** [comment]
Try setting the number of paragraphs in the subtitles to 1? 
![image](https://github.com/user-attachments/assets/db3e1ae5-ec23-46e1-9667-8d0d47265c26)
Subtitle files can be attached to this post

**Comment by ptd150891** [comment]
gemini's translation is much better, claude's translation is not suitable for xiangqi.
please fix the error, thank you.
