### ISSUE TITLE
[Bug]: 翻译网页特别是github的时候译文显示样式不显示

### ISSUE THREAD

**Issue by DaLiWan666** [immersive-translate/immersive-translate#1931]
### 插件版本号 | Version

1.7.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

自动翻译英文，在打开特别是github网页时候，概率出现翻译后设置的翻译译文显示样式不显示，什么都没有，设置的译文显示样式
为引用，手动点击按钮重新翻译后恢复正常显示

### 出现问题的网址 | URL

https://github.com/

### 重现步骤 | To Reproduce

设置英文等语言自动翻译，打开github网页，翻译后

**Comment by keyboard3** [comment]
没能复现，试试重置设置之后，再修改样式。然后重试看看，或者换个浏览器试试

**Comment by MCQSJ** [comment]
> 没能复现，试试重置设置之后，再修改样式。然后重试看看，或者换个浏览器试试

我再次测试，只有github的网页存在该问题，并且是大概率出现。其他网页没有这个情况，浏览器是Microsoft Edge
版本 128.0.2730.0 (正式版本) dev (64 位)

**Comment by MCQSJ** [comment]
> 没能复现，试试重置设置之后，再修改样式。然后重试看看，或者换个浏览器试试

已经重置设置重新设置了

**Comment by keyboard3** [comment]
给插件隐身窗口访问权限，在隐身窗口试试

**Comment by MCQSJ** [comment]
> 给插件隐身窗口访问权限，在隐身窗口试试

测试了，也是一模一样的结果

**Comment by keyboard3** [comment]
无法复现，暂时关此issue
