### ISSUE TITLE
edge 浏览器新建标签页中的搜索栏和地址栏不支持3空格快速翻译

### ISSUE THREAD

**Issue by LZJ-high** [immersive-translate/immersive-translate#1933]
### 您希望的更新和改进是什么 | Update or Improve

希望能够做到和谷歌浏览器的搜索栏一样，能够3空格翻译
目前用起来很奇怪，使用edge浏览器的用户，搜索都是从新建标签页开始的，然后这个页面的搜索栏不支持3空格快速翻译，这让我感到很困惑

**Comment by LZJ-high** [comment]
无

**Comment by keyboard3** [comment]
插件没有访问地址栏权限
