### ISSUE TITLE
希望输入框三击空格时“单独用LLM”来翻译保证质量，而网页翻译依然用非LLM服务来保证速度。

### ISSUE THREAD

**Issue by Allen-GX** [immersive-translate/immersive-translate#1934]
### 您希望的更新和改进是什么 | Update or Improve

希望输入框三击空格时“单独用LLM”来翻译保证质量，而网页翻译依然用非LLM服务来保证速度。

**Comment by keyboard3** [comment]
![image](https://github.com/user-attachments/assets/0ac17561-8838-4923-8515-9df4ab2dbc5e)
你可以在输入增强板块单独设置翻译服务
