### ISSUE TITLE
[Bug]: 谷歌翻译似乎不可用了？

### ISSUE THREAD

**Issue by Diplproveably** [immersive-translate/immersive-translate#1938]
### 插件版本号 | Version

V1.7.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

发现沉浸式翻译的谷歌翻译服务不可用了。
google Translate、Wikipedia之类的可以上说明我的网络没问题，但是沉浸式翻译插件里面的谷歌翻译不能正常使用。

**Comment by keyboard3** [comment]
谷歌翻译用不了只有一种结果，就是谷歌限流你的ip，切换翻译节点或者切换翻译服务
