### ISSUE TITLE
[Feature Request] 能否增加对漫画翻译文本的手动编辑功能

### ISSUE THREAD

**Issue by Kimcao1217** [immersive-translate/immersive-translate#1939]
### 您希望的更新和改进是什么 | Update or Improve

您好，请问后面的版本是否会考虑增加：对漫画翻译文本的手动编辑功能？
有的翻译能肉眼看出bug，但目前似乎不支持在网页版插件对相关翻译文本进行手动修改，导出为图片后还需要手动用PS才能改正，有点麻烦。
非常感谢！

**Comment by keyboard3** [comment]
无法支持编辑功能，在原站点的图片上通过网页渲染的方式还原翻译结果不现实

**Comment by Kimcao1217** [comment]
好的，谢谢

**Comment by keyboard3** [comment]
漫画问题可以在漫画集中贴中反馈，我们会通过迭代模型来解决
