### ISSUE TITLE
建议增加输入框翻译功能和手动选择翻译功能

### ISSUE THREAD

**Issue by SoXunwa** [immersive-translate/immersive-translate#194]
![image](https://user-images.githubusercontent.com/30725732/222935106-057d443d-a286-40a2-aba6-6f2a49b88c37.png)
![image](https://user-images.githubusercontent.com/30725732/222935129-09f982ac-3637-40a8-ad03-bed97da8ed45.png)

**Comment by ForestL18** [comment]
手动选择文字翻译非常需要，因为有的网页设计问题，有些段落一直无法翻译，加上手动选择翻译就方便很多

**Comment by theowenyoung** [comment]
嗯，选中翻译和划词翻译都在计划中， 输入框目前还没有计划要实现..

**Comment by Eyion** [comment]
借楼：希望增加编辑译文的功能，方便修正。

**Comment by theowenyoung** [comment]
输入框翻译已经支持，另外 支持鼠标悬停翻译，所以现在你可以悬停到某个段落上来翻译了。
