### ISSUE TITLE
[Bug]: DeepL 服务返回错误， 请求参数错误，请检查相应配置。  400: {"message":"Parameter 'tag_handling' is invalid."}

### ISSUE THREAD

**Issue by GomoXU** [immersive-translate/immersive-translate#1940]
### 插件版本号 | Version

1.7.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

服务返回错误， 请求参数错误，请检查相应配置。

400: {"message":"Parameter 'tag_handling' is invalid."}

### 出现问题的网址 | URL

chrome-extension://bpoadfkcbjbfhfodiogcnhhhpibjhbnh/options.html#general

### 重现步骤 | To Reproduce

确认密钥正确，并且是Free Plan

**Comment by keyboard3** [comment]
打开 https://dash.immersivetranslate.com/#about 会自动规则，然后再试下

**Comment by GomoXU** [comment]
可以用了
