### ISSUE TITLE
[Bug]: 域名通配符无法匹配顶级域名 ( 例如 *.local, *.test )

### ISSUE THREAD

**Issue by SuSuSoo** [immersive-translate/immersive-translate#1942]
### 插件版本号 | Version

1.7.8

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

本地开发一般会配置*.local或*.test作为本地开发服务器域名, 
禁用翻译或者禁用悬浮球的域名通配符匹配有问题, 
无法通过设置禁用这个插件, 只能通过悬浮球的x来关闭, 非常不方便
应该算个bug

### 出现问题的网址 | URL

aaa.bbb.local

### 重现步骤 | To Reproduce

1. 安装插件
2. 设置->禁用悬浮球->添加 *.local
3. 关闭网站标签
4. 重新打开网页
5. 悬浮球依然可见

**Comment by flamintune** [comment]
经过测试，这样设置应该是可以的吧，如图

![image](https://github.com/user-attachments/assets/214a8032-f613-49b4-8934-9c719b8c572c)
![image](https://github.com/user-attachments/assets/eb6063c7-0afb-47e6-9680-508c5821f619)
![image](https://github.com/user-attachments/assets/d707e758-cbfe-4c11-a95f-892abe381a43)

然后如果还是不行，可以看一下我们的 url match 匹配规则，https://immersivetranslate.com/docs/advanced/#rules-matches-%E5%8C%B9%E9%85%8D%E9%80%BB%E8%BE%91
