### ISSUE TITLE
添加名词特定翻译功能（译前替换）

### ISSUE THREAD

**Issue by 5418541** [immersive-translate/immersive-translate#1943]
### 您希望的更新和改进是什么 | Update or Improve

1.设置里把保留单词不翻译的选项改掉，变成翻译前进行替换的选项

### 补充说明 | Additional context

人名或者一些特殊名词，翻译服务无法翻译的很好。
说白了其实就是一个译前替换的功能，将单词直接修改成自定义后的名词，再跟着原文一起提交给翻译服务不就好了吗。
比如
Ukraine may get another Patriot battery.
这里面battery除了电池，还有炮架的意思。

一般翻译服务会误解成乌克兰可能会获得另外一个爱国者电池

在翻译请求提交前，直接把battery替换成炮架。

那么在提交时就会变成
Ukraine may get another Patriot 炮架
这样翻译服务就能很好翻译成

乌克兰可能会获得另外一套爱国者导弹系统
只要能实现译前替换就好了，不需要译后再替换。效果都一样，还简单

**Comment by keyboard3** [comment]
可以在开发项中配置替换，参考 https://github.com/immersive-translate/immersive-translate/issues/91 中Owen的回答
![image](https://github.com/user-attachments/assets/c03b3e56-85ea-4d0c-b86e-0e339fecfa16)
