### ISSUE TITLE
[Bug]: 视频字幕-在播放器显示双语字幕快捷方式，关闭无效

### ISSUE THREAD

**Issue by XXXXuan** [immersive-translate/immersive-translate#1945]
### 插件版本号 | Version

1.7.8

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

无论在播放器界面选择不在显示该快捷方式或者进入设置界面关闭，都无效

### 出现问题的网址 | URL

youtube

### 重现步骤 | To Reproduce

随便点一个带字幕的视频就复现了

**Comment by keyboard3** [comment]
下一个版本修复

**Comment by keyboard3** [comment]
1.7.9 已修复
