### ISSUE TITLE
[Bug]: DeepL翻译在某些页面出现超链接的时候翻译大幅错误

### ISSUE THREAD

**Issue by leonlan1992** [immersive-translate/immersive-translate#1948]
### 插件版本号 | Version

1.7.8

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在某些页面上，比如https://app.tegus.co/，页面文本中有大量超链接，使用沉浸式翻译并使用DeepL时，有超链接的段落翻译出现大范围错误，比如下图：

![image](https://github.com/user-attachments/assets/bd673002-d22f-485a-ba40-48084fb6607b)

这里正常的翻译应该为我设置的蓝色字体，有超链接的段落不仅格式错误，翻译内容的质量很差。

解决建议：能否可以设置忽略超链接。

### 出现问题的网址 | URL

https://app.tegus.co/

**Comment by keyboard3** [comment]
![image](https://github.com/user-attachments/assets/5c6ec53a-984f-4268-aaab-ced6f311dfa4)
这个站点需要注册登录，生成个未翻译前的链接，我们复现下

**Comment by keyboard3** [comment]
![image](https://github.com/user-attachments/assets/9d3882de-3fc1-44ec-92db-e9221a57a867)
你目前可以在开发设置中的用户配置关闭deepl的富文本翻译

```
    "deepl": {
      "enableRichTranslate": false
    }
```

**Comment by keyboard3** [comment]
![image](https://github.com/user-attachments/assets/470b0c4a-01de-4d26-982c-ce9c0b4fd847)
1.7.9 已修复 错误，且已在面板中支持关闭富文本翻译

**Comment by leonlan1992** [comment]
多谢，已经解决
