### ISSUE TITLE
[Bug]: 在WOS搜索结果页面出现冗余翻译占用大量页面

### ISSUE THREAD

**Issue by Lan-Cell-Master** [immersive-translate/immersive-translate#1949]
### 插件版本号 | Version

1.7.8

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

在WOS搜索结果页面出现冗余翻译占用大量页面
![222](https://github.com/user-attachments/assets/d0efc348-174e-440e-858e-f0898c4e176c)
![111](https://github.com/user-attachments/assets/2ae1fe82-5794-40a8-81da-476fe9046c2f)

### 出现问题的网址 | URL

https://webofscience.clarivate.cn/wos/alldb/summary/b7afb816-aa1f-4093-9309-e6f2710ce12d-fe9f781a/relevance/1

### 重现步骤 | To Reproduce

1.搜索
2.插件自动翻译

**Comment by keyboard3** [comment]
选择了哪个翻译服务？

**Comment by Lan-Cell-Master** [comment]
> 选择了哪个翻译服务？

微软翻译跟谷歌翻译都试过

**Comment by keyboard3** [comment]
![image](https://github.com/user-attachments/assets/06b599a8-5dae-4116-9e01-510dd8e79373)
没复现出来， 你重置设置也一样吗？

**Comment by Lan-Cell-Master** [comment]
> ![image](https://private-user-images.githubusercontent.com/13177744/352851285-06b599a8-5dae-4116-9e01-510dd8e79373.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxODI2NzAsIm5iZiI6MTcyMjE4MjM3MCwicGF0aCI6Ii8xMzE3Nzc0NC8zNTI4NTEyODUtMDZiNTk5YTgtNWRhZS00MTE2LTllMDEtNTEwZGQ4ZTc5MzczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDE1NTkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1Y2FkMjA0MjhlYjMzNTIyZTE0YTg3NGIzNTc4NDZmNzZkMjZjMWQzOTU1NGFhYmE3Mzc5M2I2OTM4YzhiOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VKTm-aH-0k9hwAFw6UH41WMxv5JIEQZ7OD1XhmD3oNg) 没复现出来， 你重置设置也一样吗？

刚从实验室回来。等我明天看看，有问题的话再来回你。老哥早点睡先

**Comment by Lan-Cell-Master** [comment]
> ![image](https://private-user-images.githubusercontent.com/13177744/352851285-06b599a8-5dae-4116-9e01-510dd8e79373.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMjA0NDQsIm5iZiI6MTcyMjIyMDE0NCwicGF0aCI6Ii8xMzE3Nzc0NC8zNTI4NTEyODUtMDZiNTk5YTgtNWRhZS00MTE2LTllMDEtNTEwZGQ4ZTc5MzczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDAyMjkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljYTk2MjExMTQ3OTdhMTc2YTA1ZDIxMDgyZmVhZDk1NTAxZmQ1YzgyNmI3YTcyY2U4YTYyOGMwYzUwNWRmMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HdNRO--OKkN_WslDzeZdKbSYbj2PyMY53lL6Sg8n794) 没复现出来， 你重置设置也一样吗？

还原设置以后还是这样子。一翻译成英文就自动展开期刊具体信息

**Comment by Lan-Cell-Master** [comment]
> ![image](https://private-user-images.githubusercontent.com/13177744/352851285-06b599a8-5dae-4116-9e01-510dd8e79373.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMjA0NDQsIm5iZiI6MTcyMjIyMDE0NCwicGF0aCI6Ii8xMzE3Nzc0NC8zNTI4NTEyODUtMDZiNTk5YTgtNWRhZS00MTE2LTllMDEtNTEwZGQ4ZTc5MzczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDAyMjkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljYTk2MjExMTQ3OTdhMTc2YTA1ZDIxMDgyZmVhZDk1NTAxZmQ1YzgyNmI3YTcyY2U4YTYyOGMwYzUwNWRmMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HdNRO--OKkN_WslDzeZdKbSYbj2PyMY53lL6Sg8n794) 没复现出来， 你重置设置也一样吗？

![333](https://github.com/user-attachments/assets/a97afc85-a892-4148-a097-a96ebd9f07d8)
这是我的其他扩展，你看看这些会互相影响不？

**Comment by Lan-Cell-Master** [comment]
试过把其它扩展都关掉了，但是没用

**Comment by keyboard3** [comment]
你方便录个屏吗？可以给插件授权访问隐私窗口权限，在隐私窗口试试？

**Comment by Lan-Cell-Master** [comment]
> 你方便录个屏吗？可以给插件授权访问隐私窗口权限，在隐私窗口试试？

![444](https://github.com/user-attachments/assets/624872dc-8718-446c-952e-25b9ddbddd01)
试了一下隐私窗口，还是会出现那种情况

**Comment by Lan-Cell-Master** [comment]
> 你方便录个屏吗？可以给插件授权访问隐私窗口权限，在隐私窗口试试？

录屏要录什么操作呢？

**Comment by keyboard3** [comment]
录制下你的翻译过程，同时生成下你未翻译的快照链接
![image](https://github.com/user-attachments/assets/551198f2-b361-4ed5-84b4-ecfc52c16e2c)

**Comment by Lan-Cell-Master** [comment]
https://github.com/user-attachments/assets/0ebf1575-ff98-4a73-bbc1-310d7544eab2
这是录屏

https://readit.plus/a/9E5QS/1
这是快照

**Comment by Lan-Cell-Master** [comment]
https://f.ws28.cn/f/epk6lg9twh6 复制链接到浏览器打开

重发录屏，用了文叔叔中转，上面那个好像看不了

**Comment by keyboard3** [comment]
嗯 看到了，你的登录态比我的权限高级，会有展开逻辑，我这权限太低没有展开的项

**Comment by Lan-Cell-Master** [comment]
> 嗯 看到了，你的登录态比我的权限高级，会有展开逻辑，我这权限太低没有展开的项

有解决办法的话滴滴我一下哈。

**Comment by keyboard3** [comment]
你可以先切换到微软翻译服务

**Comment by Lan-Cell-Master** [comment]
> 你可以先切换到微软翻译服务

切换过啦。微软跟谷歌、腾讯翻译都会这样

**Comment by keyboard3** [comment]
这个手动展开的内容需要翻译吗？

**Comment by Lan-Cell-Master** [comment]
> 这个手动展开的内容需要翻译吗？

我个人感觉不是很需要。那些展开的东西，就算是英文也挺好懂的，而且没什么很重要的信息

**Comment by keyboard3** [comment]
好的，暂时不翻译这块内容。 打开这个地址 https://dash.immersivetranslate.com/#about 会自动更新规则，然后重试下。

**Comment by Lan-Cell-Master** [comment]
> 好的，暂时不翻译这块内容。 打开这个地址 https://dash.immersivetranslate.com/#about 会自动更新规则，然后重试下。

还是会出现，ha好怪
![555](https://github.com/user-attachments/assets/ddd0d42b-8c80-4edb-91a1-c766cec6a8bd)

**Comment by keyboard3** [comment]
啊 我没有排除对吗，我在快照链接试试

**Comment by Lan-Cell-Master** [comment]
> 啊 我没有排除对吗，我在快照链接试试

好滴

**Comment by keyboard3** [comment]
![image](https://github.com/user-attachments/assets/b90eb3bf-c7ef-43ad-8bf0-118237fbbe99)
再试下

**Comment by Lan-Cell-Master** [comment]
> ![image](https://private-user-images.githubusercontent.com/13177744/352909504-b90eb3bf-c7ef-43ad-8bf0-118237fbbe99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMjU4MDQsIm5iZiI6MTcyMjIyNTUwNCwicGF0aCI6Ii8xMzE3Nzc0NC8zNTI5MDk1MDQtYjkwZWIzYmYtYzdlZi00M2FkLThiZjAtMTE4MjM3ZmJiZTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDAzNTgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5MTEzYmViNjg2NzI2ZjFmODYwNjg4NzE2YzgzODNhOGQ3YmYyZDdhY2Y5YWI4NmFhNmNlZDhlMmI3NDkzODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qy-ww8mLzaxsxLV7GcGUh0_ttpOR5tVnCvHAHkvo_XA) 再试下

OK了，谢谢老哥
