### ISSUE TITLE
[Bug]: After translating the local epub, it is impossible to open it in calibre.

### ISSUE THREAD

**Issue by justafreaky** [immersive-translate/immersive-translate#1950]
### 插件版本号 | Version

1.7.7

### 平台 | Platform

Linux

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

After translating the local epub, it is impossible to open it in calibre.

### 重现步骤 | To Reproduce

1. Translate local epub with Immersive Translate.
2. Откройте переведенный epub в calibre.  An “ERROR: Failed to load book” window will appear

### 补充说明 | Additional context

I am on Fedora 40 now.

**Comment by keyboard3** [comment]
Is it possible to attach documents

**Comment by justafreaky** [comment]
[Caliban's War.zip](https://github.com/user-attachments/files/16409647/Caliban.s.War.zip)
I was also unable to open this file in Foliate Reader as well.

**Comment by keyboard3** [comment]
你发过来的不是未翻译的文件？

**Comment by justafreaky** [comment]
OK. I did it all over again. I took an untranslated book and translated it. The file in the archive is the translated epub.
[Corey, James S A - Caliban's War translated.zip](https://github.com/user-attachments/files/16411219/Corey.James.S.A.-.Caliban.s.War.translated.zip)

**Comment by keyboard3** [comment]
I can't open either of the files you gave me, I need the most original file, I need to reproduce the process

**Comment by justafreaky** [comment]
It's original, untranslated file.
[Corey, James S A - Caliban's War untranslated.zip](https://github.com/user-attachments/files/16411290/Corey.James.S.A.-.Caliban.s.War.untranslated.zip)

**Comment by keyboard3** [comment]
After testing Firefox translation export does have problems, Safari and chrome translation export is normal, you can temporarily complete the operation in other browsers. Let's track down the issue with Firefox in this scenario

**Comment by justafreaky** [comment]
@keyboard3, thank you! I'll be using Chrome for now.

**Comment by TaoLoading** [comment]
Hi, the problem has been fixed and you can now export epub files properly in Firefox as well.
