### ISSUE TITLE
[Bug]: Google 翻譯報錯[safari/macos]

### ISSUE THREAD

**Issue by Lawlietr** [immersive-translate/immersive-translate#1952]
### 插件版本号 | Version

1.7.8

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

在 safari 上只要使用 google 翻譯就會報錯 
但實際上有進行翻譯，但是不完全，排版會面目全非
使用其他家如 bing 進行翻譯皆正常

同一台 mac 使用 chrome 或其他瀏覽器都正常
同一個 ip 使用 windows 上任何瀏覽器也正常

**Comment by keyboard3** [comment]
哪个网址？

**Comment by keyboard3** [comment]
截个图看下，我这边没有没复现出来

**Comment by Lawlietr** [comment]
都是顯示同樣的錯誤
有些實際上已經翻譯了，但沒翻完就報錯
如果退回 1.7.7 是可以的

![截圖 2024-07-29 14 58 17](https://github.com/user-attachments/assets/c8863caa-210e-48e4-99c0-b5f4cd1746de)

![截圖 2024-07-29 15 00 04](https://github.com/user-attachments/assets/b7e4d3c2-450e-4882-b451-edef09f4385c)
 
![截圖 2024-07-29 15 02 14](https://github.com/user-attachments/assets/1a99ddde-1ccd-4425-b31e-96dff5008e71)

**Comment by keyboard3** [comment]
更新下油猴脚本 1.7.9 已修复
