### ISSUE TITLE
[Bug]: arxiv页面 双语翻译 链接消失

### ISSUE THREAD

**Issue by wangyuchen333** [immersive-translate/immersive-translate#1953]
### 插件版本号 | Version

1.7.7

### 平台 | Platform

Windows, macOS, iOS, Android

### 浏览器 | Browsers

Chrome, Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

[Bug]: arxiv页面 双语翻译 链接消失，尝试了chrome和safari以及brave，都有这个问题

### 出现问题的网址 | URL

arxiv

### 重现步骤 | To Reproduce

click any arxiv paper

**Comment by keyboard3** [comment]
更新到1.7.9

**Comment by wangyuchen333** [comment]
> 更新到1.7.9

试了一下，还是有这个问题😭

**Comment by keyboard3** [comment]
给个复现地址

**Comment by wangyuchen333** [comment]
> 给个复现地址

https://arxiv.org/abs/2405.00200
我一周前看的时候还行

**Comment by keyboard3** [comment]
![image](https://github.com/user-attachments/assets/dca435a9-006f-457f-9a23-88d0453704d1)
这不是都有吗？

**Comment by wangyuchen333** [comment]
<img width="594" alt="截屏2024-07-30 12 11 23" src="https://github.com/user-attachments/assets/19c2551d-8ab2-4f75-bfa4-8a341b95c6b2">
右侧的双语翻译没了

**Comment by keyboard3** [comment]
那是因为旧版双语链接用来的html版本被arxiv下掉了。 如果右边没有就说明这个文章不支持html

**Comment by wangyuchen333** [comment]
> 那是因为旧版双语链接的html版本被arxiv下掉了。 如果右边没有就说明这个文章不支持html

哦好吧，不过他应该是支持 html5 的， 可以手动切换成 html5 页面然后翻译

**Comment by keyboard3** [comment]
目前的检测逻辑强依赖页面元素，可能站点发生变化了。可能尝试请求一下html地址，存在才展示侧边栏更靠谱一点

**Comment by keyboard3** [comment]
下一版更新

**Comment by wangyuchen333** [comment]
> 下一版更新

感谢🙏！

**Comment by keyboard3** [comment]
1.8.1 已支持，下一版将会迭代改进支持其他站点比如 ar5iv.labs.arxiv.org 的探测
