### ISSUE TITLE
[Bug]: 有时候会抽风无法翻译网页的东西，偶尔刷新网页后可以，但是大多数时候不行，一般我都把插件重新删了然后添加，但是这也太麻烦了

### ISSUE THREAD

**Issue by Linder-Y** [immersive-translate/immersive-translate#1955]
### 插件版本号 | Version

V1.7.9

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

有时候会抽风无法翻译网页的东西，偶尔刷新网页后可以，但是大多数时候不行，一般我都把插件重新删了然后添加，但是这也太麻烦了，以及多语种混合在同一个网站上的时候——例如波斯语+英语的情况只能翻译波斯语

### 出现问题的网址 | URL

许多外国客户网站

### 重现步骤 | To Reproduce

1.打开网页；2.点击翻译or快捷键后无反应

### 补充说明 | Additional context

无

**Comment by keyboard3** [comment]
多语种页面的话 可以用AI类翻译服务，因为他们可以自动识别语种。其他机器翻译的话，多语种混合会导致语种识别错误，有可能会翻译不了或者出错。 
你可以在未翻译的页面上生成一个快照链接，我们帮你看下
![image](https://github.com/user-attachments/assets/e8b91e83-0eef-4ae8-be4e-64e2f2c1f7a2)

**Comment by Linder-Y** [comment]
没弄成功，跟着教程设置了网页快照，没跳出来分享界面，其实翻译不是单个网页的问题，它很随机，一般都是某次刚打开浏览器开始翻译的时候，就像今天现在我刚上班一样











在 2024-07-30 14:20:59，"keyboard3" ***@***.***> 写道：

多语种页面的话 可以用AI类翻译服务，因为他们可以自动识别语种。其他机器翻译的话，多语种混合会导致语种识别错误，有可能会翻译不了或者出错。
你可以在未翻译的页面上生成一个快照链接，我们帮你看下
image.png (view on web)

**Comment by Linder-Y** [comment]
我刚才重新移除拓展程序也可以生成快照和翻译了，所以……也蛮无奈的，一崩什么功能也无法使用











在 2024-07-31 09:02:28，"OGNI酱" ***@***.***> 写道：

没弄成功，跟着教程设置了网页快照，没跳出来分享界面，其实翻译不是单个网页的问题，它很随机，一般都是某次刚打开浏览器开始翻译的时候，就像今天现在我刚上班一样











在 2024-07-30 14:20:59，"keyboard3" ***@***.***> 写道：

多语种页面的话 可以用AI类翻译服务，因为他们可以自动识别语种。其他机器翻译的话，多语种混合会导致语种识别错误，有可能会翻译不了或者出错。
你可以在未翻译的页面上生成一个快照链接，我们帮你看下
image.png (view on web)

**Comment by keyboard3** [comment]
如果你是chrome有问题，试着卸载重装下chrome？或者换edge试试
