### ISSUE TITLE
[Bug]: 在 Orion 浏览器上，开启插件后选择文本变得卡顿

### ISSUE THREAD

**Issue by inhzus** [immersive-translate/immersive-translate#1956]
### 插件版本号 | Version

1.7.9

### 平台 | Platform

macOS

### 浏览器 | Browsers

Other

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在 Orion 浏览器上
不开启插件时：https://imgur.com/a/6Ezuilk
可以看到移动光标时是跟手的
开启插件后：https://imgur.com/a/tGEmmwM
明显变得不跟手，有些卡顿

### 重现步骤 | To Reproduce

使用 Orion 浏览器（Chrome 和 Firefox 两个商店版本均能复现）
1. disable 插件，在任意界面上选取文本
2. enable 插件，在任意界面上选取文本

**Comment by flamintune** [comment]
好的，这个问题应该是由于1.7.8版本新功能：选中文本右键菜单点击跳转到文本翻译导致的，我们正在排查中，临时的解决方案是回滚到1.7.7

**Comment by inhzus** [comment]
感谢，回滚至 1.7.7 后不再能复现

**Comment by flamintune** [comment]
下个版本修复，大概会在下周一发出新的版本

**Comment by flamintune** [comment]
在1.8.1中已修复，及时更新下插件，如果还有问题，欢迎反馈。

优化策略为：延长了选中触发的防抖时间
