### ISSUE TITLE
[Bug]: 微软会在特殊情况下将2直译成"阿拉伯数字"

### ISSUE THREAD

**Issue by MLRichard** [immersive-translate/immersive-translate#1957]
### 插件版本号 | Version

1.7.9

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在翻译较长文本时，会把标题中的数字直译成"阿拉伯数字"
![问题反馈](https://github.com/user-attachments/assets/8b57c47e-29c0-445d-8f19-4ed728db879d)
![问题反馈2](https://github.com/user-attachments/assets/5314720a-d86b-44b3-a6f6-43951b44e551)

**Comment by keyboard3** [comment]
用的什么翻译服务，给个复现的网址

**Comment by MLRichard** [comment]
> 用的什么翻译服务，给个复现的网址

使用微软翻译，网站如下
https://ar5iv.labs.arxiv.org/html/1903.09756?_immersive_translate_auto_translate=1

**Comment by keyboard3** [comment]
这个是微软在这种特殊场景下的bug，很尴尬。其他数字都没问题，且文字很近才会出现。这个属于微软的非常场景苛刻的bug了。
<img width="696" alt="image" src="https://github.com/user-attachments/assets/ffadc1f9-b9f4-47e3-b1e5-0ad9e8c59b48">
可以在进阶设置中添加2即可避免
<img width="439" alt="image" src="https://github.com/user-attachments/assets/00feebce-e692-4035-a2fa-09b7c5f5c2ee">

**Comment by MLRichard** [comment]
感谢

**Comment by keyboard3** [comment]
不过刚刚那个占位符的方案可能不太合适，会可能在出现2的地方都保留，某种情况下会影响翻译质量。
