### ISSUE TITLE
[Bug]: jmanga 的漫画模式适配问题

### ISSUE THREAD

**Issue by weijinzhongyi** [immersive-translate/immersive-translate#1959]
### 插件版本号 | Version

1.7.9

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![Clip_2024-08-01_15-12-00](https://github.com/user-attachments/assets/2810b6a5-1392-4fb6-82ac-05c0d7100a11)
jmanga 显示翻译完成，但是并没有显示到屏幕上

### 出现问题的网址 | URL

https://jmanga.org/

**Comment by keyboard3** [comment]
因为该站点部分漫画内容采用的是webp格式，目前不支持，将在下一版插件支持

**Comment by keyboard3** [comment]
1.8.1 已支持
