### ISSUE TITLE
[功能改进] 允许为某些语言单独设置"仅显示译文"

### ISSUE THREAD

**Issue by vhxnyu** [immersive-translate/immersive-translate#1960]
### 您希望的更新和改进是什么 | Update or Improve

让"仅显示译文"功能, 允许为某些语言单独设置启用或关闭

### 补充说明 | Additional context

1. 例如繁体到简体中文的转换, 或是日文到中文的转换. 
这些语言比较熟悉或是完全不熟悉, 没有必要显示, 关闭原文可以让我更好阅读.
但如果再次遇到英文网页, 又要手动关闭"仅显示译文了"

建议使用白名单或者黑名单来设置, 这样可以适用不同人群

**Comment by theowenyoung** [comment]
可以在进阶设置中 设置仅显示译文的语言，这个可以满足需求吗？

![CleanShot 2024-08-30 at 23 04 17@2x](https://github.com/user-attachments/assets/0bb199c6-78c6-4639-8ea1-897ebcb913a9)
