### ISSUE TITLE
[Bug]: 配置claude显示400错误，但是免费版也有每分钟5次的使用频率啊，怎么就400呢

### ISSUE THREAD

**Issue by Re-hd** [immersive-translate/immersive-translate#1961]
### 插件版本号 | Version

1.7.9

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

如题，附图
![屏幕截图 2024-08-01 211036](https://github.com/user-attachments/assets/de6bfa42-4131-49fd-9e50-268f449f3cfc)

### 出现问题的网址 | URL

extension://amkbmndfnliijdhojkpoglbnaaahippg/options.html#general

**Comment by keyboard3** [comment]
看报错，错误内容不是频率被限制，是你需要充值才能使用了。具体问题你得找cluade
