### ISSUE TITLE
字體

### ISSUE THREAD

**Issue by cheng-cooper** [immersive-translate/immersive-translate#1962]
### 您希望的更新和改进是什么 | Update or Improve

希望中英文的字體可分開設定

--題外話希望可以有twitch直播的翻譯--

**Comment by theowenyoung** [comment]
> 希望中英文的字體可分開設定

原文的字体我们不太容易做改动。译文的字体目前可以自定义（按语言分开配置的话有点复杂，所以应该不会支持）

> 題外話希望可以有twitch直播的翻譯

Twitch 直播的字幕我们尝试适配的时候发现，他的字幕是一个词一个词的出现和消失，不太容易适配。
