### ISSUE TITLE
新增选项 不要翻译 `<code>` 块

### ISSUE THREAD

**Issue by MrXiaoM** [immersive-translate/immersive-translate#1963]
### 您希望的更新和改进是什么 | Update or Improve

![image](https://github.com/user-attachments/assets/af542fb0-bb5e-4f2a-87a3-918e3bc69c7d)

如图所示，`<code>` 块也被翻译了，在一些情境中，这是不需要翻译的，甚至可能因为翻译改变的字母大小写而产生歧义。
我没有在 1.7.9 版本的设置中找到类似屏蔽 code 块、禁止翻译某种类型元素的选项。
建议新增一个不翻译`<code>`块的选项，并默认开启。或新增翻译页面元素类型的黑白名单。

**Comment by keyboard3** [comment]
![image](https://github.com/user-attachments/assets/e6cdb4f9-361b-4fca-ac21-011b05ff18a5)
`"rich.stayOriginalTags.remove": [],`
这么加就行了

**Comment by theowenyoung** [comment]
@MrXiaoM 你用的是什么翻译服务？网址发一下？

**Comment by MrXiaoM** [comment]
> @MrXiaoM 你用的是什么翻译服务？网址发一下？

微软翻译
https://github.com/MrXiaoM/TimeOperate-Expansion
