### ISSUE TITLE
"翻译HTML/TXT"功能无法匹配设置的规则

### ISSUE THREAD

**Issue by xluu233** [immersive-translate/immersive-translate#1964]
### 您希望的更新和改进是什么 | Update or Improve

在设置的相关规则仅对在线网页翻译生效，对本地HTML翻译的时候不生效，希望统一

**Comment by keyboard3** [comment]
比如那些规则？

**Comment by xluu233** [comment]
以在线网页http://124.222.40.9/html/docs/access_report.html为例，在线翻译样式：
![屏幕截图_2-8-2024_104516_124 222 40 9](https://github.com/user-attachments/assets/2bc523c1-abe7-4389-b79d-f0f17371aece)

将本地网页为例（同样的文件），它将一些不需要翻译的元素也翻译了，看起来是规则没生效
![屏幕截图_2-8-2024_10554_app immersivetranslate com](https://github.com/user-attachments/assets/fb3b4c5d-1c4c-4ee3-a951-ea26034d940e)

规则文件：
`{
  "aiAssistantIds": [
    "paraphrase",
    "twitter",
    "tech",
    "reddit",
    "paper",
    "news",
    "music",
    "medical",
    "legal",
    "github",
    "game",
    "ecommerce",
    "financial",
    "fiction",
    "ao3",
    "ebook",
    "design",
    "bilingual-mix",
    "web3",
    "VocabularyAssistant"
  ],
  "beta": false,
  "debug": false,
  "generalRule": {
    "blockMinTextCount": 0,
    "blockMinWordCount": 0,
    "glossaries": [
      {
        "k": "WargamingScene",
        "v": "WargamingScene"
      },
      {
        "k": "PlaybackHall",
        "v": "PlaybackHall"
      },
      {
        "k": "ExperimentTable",
        "v": "ExperimentTable"
      },
      {
        "k": "Model Factory",
        "v": "ModelFactory"
      },
      {
        "k": "ModelFactory",
        "v": "ModelFactory"
      },
      {
        "k": "ACSDF",
        "v": "算石仿真系统(ACSDF)"
      },
      {
        "k": "AFSIM",
        "v": "算石仿真系统(ACSDF)"
      },
      {
        "k": "mission",
        "v": "mission"
      },
      {
        "k": "EVT Reader",
        "v": "EVT Reader"
      },
      {
        "k": "EVT",
        "v": "EVT"
      },
      {
        "k": "Unclassified",
        "v": "Unclassified"
      },
      {
        "k": "n/a",
        "v": "n/a"
      },
      {
        "k": "integer",
        "v": "integer"
      },
      {
        "k": "string",
        "v": "string"
      },
      {
        "k": "tags",
        "v": "tags"
      },
      {
        "k": "timestamp",
        "v": "timestamp"
      },
      {
        "k": "decimal",
        "v": "decimal"
      }
    ],
    "isTranslateTitle": false,
    "lineBreakMaxTextCount": 280,
    "mouseHoverHoldKey": "Off",
    "mouseHoverPreferenceKey": "Shift"
  },
  "inputTranslationService": "inherit",
  "interfaceLanguage": "zh-CN",
  "isChangedAlwaysTranslatedUrls": true,
  "localUpdatedAt": "2024-08-01T09:10:18.620Z",
  "modifiedBySystem": true,
  "mouseHoverTranslationService": "inherit",
  "pcFloatBall": {
    "afterInstalledAt": "2023-10-28",
    "blockUrls": [
      "*immersivetranslate.com/preview",
      "https://app.immersivetranslate.com/",
      "https://app.immersivetranslate.cn/",
      "https://app.immersivetranslate.com/pdf-pro*",
      "https://app.immersivetranslate.cn/pdf-pro*",
      "https://app.immersivetranslate.com/text*",
      "*.immersivetranslate.com/download-subtitle*"
    ],
    "clickType": "translate",
    "enable": false,
    "fixedPosition": "right",
    "guideBlockUrls": [
      "https://onboarding.immersivetranslate.com*",
      "https://immersivetranslate.com/accounts/login*",
      "https://immersivetranslate.cn/accounts/login*"
    ],
    "isPc": true
  },
  "pcFloatBallMainBtnTooltipShownCount": 5,
  "rules": [
    {
      "excludeSelectors": [
        "h1",
        "h2",
        "h3",
        "dt",
        "code",
        ".title",
        "table",
        ".head",
        ".admonition-title",
        ".notranslate immersive-translate-target-inner immersive-translate-target-translation-theme-dashedBorder-inner",
        "[class='reference internal']"
      ],
      "excludeTags": [
        "reference internal"
      ],
      "matches": [
        "http://127.0.0.1:5500/*",
        "http://124.222.40.9/*"
      ],
      "selectors": [
        "p",
        ".line"
      ]
    }
  ],
  "selectTranslationFont": "",
  "subtitleTranslateService": "inherit",
  "targetLanguage": "zh-CN",
  "translationService": "google",
  "translationServiceChangedbyUserAt": "2024-07-24T09:31:18.757Z",
  "translationServices": {
    "deepl": {
      "authKey": "1b5870bd-be0d-4d92-a567-52176b505495:fx",
      "provider": "custom"
    }
  },
  "translationTheme": "dashedBorder",
  "translationUrlPattern": {
    "excludeMatches": [],
    "matches": [
      "twitter.com",
      "x.com",
      "www.reddit.com",
      "www.kadaza.com",
      "en.wikipedia.org",
      "*.medium.com",
      "news.ycombinator.com",
      "127.0.0.1",
      "124.222.40.9"
    ]
  },
  "updatedAt": "2024-08-01T09:10:18.620Z"
}`

**Comment by keyboard3** [comment]
看起来你是本地网页文件样式丢失了呀。你得把文件贴上来

**Comment by xluu233** [comment]
[access_report.zip](https://github.com/user-attachments/files/16464783/access_report.zip)

无法上传html,我压缩成zip了

**Comment by keyboard3** [comment]
![image](https://github.com/user-attachments/assets/fe1b8d99-0943-4001-b6f7-5adbe9a9f5d7)
因为你规则匹配的地址和网页翻译的地址不是一个呀，肯定应用不到你的规则呀

**Comment by xluu233** [comment]
okok,懂了，如果我要将规则应用到全部网页，需要怎么改

**Comment by keyboard3** [comment]
把地址改成 “*”
