### ISSUE TITLE
[Bug]: deepl的翻译问题

### ISSUE THREAD

**Issue by voiotikos** [immersive-translate/immersive-translate#1968]
### 插件版本号 | Version

1.7.9

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

deepl在网页中的翻译要比直接用deepl网站的效果差很多，之前是没有这个问题的，不知道是否和1.7.8更新后“保持文本格式”有关
![Z$98_C3EV`ZY03F8 3 `SD](https://github.com/user-attachments/assets/cacdad9d-ac32-4b71-9554-7409161ac479)
![4S`%W3$A70P~_$99NBQ530Z](https://github.com/user-attachments/assets/8b50f4f1-57b2-46c2-875e-75d79edc4fd6)

### 出现问题的网址 | URL

https://www.nisanyanadlar.com/isim/Deniz

**Comment by voiotikos** [comment]
![GC$_)R{_Z8`2$AO2XOX1WPR](https://github.com/user-attachments/assets/27d8ccf9-4284-43aa-aa7e-a4ebc6fb8b8f)
![YKHO6LRUA59C~7 X}A`@1L9](https://github.com/user-attachments/assets/100dde0a-5eb1-4ff8-bbb9-c556106be8d4)

**Comment by keyboard3** [comment]
![image](https://github.com/user-attachments/assets/642e0b9d-77e4-4fa3-83b4-b61aa176c0aa)
这是因为这个站点的内容每个字都带了格式，所以导致了富文本翻译效果不佳。你可以在设置页手动关闭deepl的富文本

**Comment by voiotikos** [comment]
好的，果然是因为富文本的问题。谢谢
