### ISSUE TITLE
[Bug]: PDF文件翻译时不时会只翻译少部分，关闭浏览器在打开有时候会恢复。

### ISSUE THREAD

**Issue by ictsmc** [immersive-translate/immersive-translate#1969]
### 插件版本号 | Version

1.8.1

### 请描述这个Bug | Describe the bug

PDF文件翻译时不时会只翻译少部分，关闭浏览器在打开有时候会恢复。
同一个文件。有时候会只翻译少部分。有时候又全部翻译。以前没有这种问题。最新经常性出现 基本不可用状态
PDF翻译他是结合上下文的吗 ？我看着翻译的时候都是一段一段的。不知道能否结合上下文去翻译 一次性发送给AI

**Comment by meijin1123** [comment]
Hi ，方便给一下PDF文件吗？我这边看看能不能复现你的问题。

**Comment by keyboard3** [comment]
你可以去设置页调整AI的每次请求最大文本长度。

**Comment by keyboard3** [comment]
暂无反馈，关闭此issue
