### ISSUE TITLE
翻译本地PDF时，译文出现重叠

### ISSUE THREAD

**Issue by Eyion** [immersive-translate/immersive-translate#197]
![1678082000148](https://user-images.githubusercontent.com/26318038/223029799-f8c34af7-ecae-466e-87de-ad1637348a10.jpg)
如图中框选部分，不知什么原因造成的。
另外，一本PDF书，是会自动全翻译，还是需要每页操作，想把翻译过后的中英对照书保存到本地。

**Comment by theowenyoung** [comment]
pdf 目前还有不少问题. 需要一点时间做优化..

可以点击 浏览器图标 -》  立即翻译到网页底部，这样就能翻译全部了。

但是我更建议先试用其他软件把pdf转为 html 或者 epub，然后再翻译，这样效果会好很多。

**Comment by Eyion** [comment]
> 

翻译pdf也支持翻译epub？我还特地把epub转成pdf

**Comment by theowenyoung** [comment]
https://immersive-translate.owenyoung.com/usage#epub-%E6%96%87%E4%BB%B6%E7%BF%BB%E8%AF%91

使用这些在线网站打开epub即可翻译～

**Comment by Eyion** [comment]
> https://immersive-translate.owenyoung.com/usage#epub-%E6%96%87%E4%BB%B6%E7%BF%BB%E8%AF%91
> 
> 使用这些在线网站打开epub即可翻译～

谢谢，虽然这些不太符合使用，但只能先这样吧。

**Comment by theowenyoung** [comment]
我正在添加本地epub文件的支持～ 稍等几天！

**Comment by Eyion** [comment]
> 我正在添加本地epub文件的支持～ 稍等几天！

好的，辛苦了。顺便借此问下有没有可以管理插件的软件（最好还支持webdav等云同步的，本地的也行）。

**Comment by theowenyoung** [comment]
0.5.5版本已基本解决～

**Comment by Eyion** [comment]
> 0.5.5版本已基本解决～

翻译PDF文件的效果略有改善，但还不完善，同时有2个疑惑：
1.只有epub才能制作双语书吗？
2.书籍的目录没有翻译。

翻译PDF文件效果
![image](https://github.com/immersive-translate/immersive-translate/assets/26318038/83d639d2-3f80-4039-b792-36ddf86fea70)

**Comment by theowenyoung** [comment]
1. 是的
2. 目前好像不会翻译目录，这个我加一下吧，在这个issue追踪下进度： https://github.com/immersive-translate/immersive-translate/issues/368

3. 更新的pdf还是只适合一些较规整的文档哈，你可以分享下你的pdf？ 记录下来再看看好不好优化。

**Comment by Eyion** [comment]
> 1. 是的
> 2. 目前好像不会翻译目录，这个我加一下吧，在这个issue追踪下进度： [希望能够对照翻译 epub 的书签 #368](https://github.com/immersive-translate/immersive-translate/issues/368)
> 3. 更新的pdf还是只适合一些较规整的文档哈，你可以分享下你的pdf？ 记录下来再看看好不好优化。

1.我是将以下链接中的epub文件转换成PDF进行测试的：
https://docs.digikam.org/en/epub/DigikamManual.epub

2.epub制作双语书时，翻译后编辑能否增加批量替换的功能？

**Comment by theowenyoung** [comment]
1. （好吧，最好还是用真实的pdf测试好一点～
2. 这个可能要在未来用 术语表来支持了，前置替换.

**Comment by Eyion** [comment]
同一个词有些地方翻了有些地方却没翻，前置替换可以解决这种问题吗？

**Comment by theowenyoung** [comment]
可以的
