### ISSUE TITLE
YouTube字幕默认语言

### ISSUE THREAD

**Issue by LidoCKT** [immersive-translate/immersive-translate#1970]
### 您希望的更新和改进是什么 | Update or Improve

目前的视频字幕自动翻译，你观看一个日文视频，将语言设置成日语-自动翻译中文或者日语（自动生成）-自动翻译中文后，下次你观看比如英语语言视频时，就会变成英语(自动生成)>>日语，再进行翻译。如下图所示：
![image](https://github.com/user-attachments/assets/e3aa9518-e95a-4203-8351-6f5f34d43aa4)

这样会导致YouTube自动识别后先由Google自己翻译一遍再过沉浸式翻译进行翻译到目标语言，多了一道翻译就会增加一次错误率。

我建议增加如下的机制：
1.当由发布者自己上传的字幕时，优先选择作者自己提供的字幕，并直接通过翻译到目标语言。
2.当发布者没有自己提供字幕时，优先选择视频源语言的自动生成字幕，并通过翻译到目标语言。
3.当发布者自己上传字幕的语言就是目标语言，或是视频源语言自动生成字幕就是目标语言，优先选中该字幕并关闭字幕翻译功能。

**Comment by gtxyqjc** [comment]
这个问题我也补充一下，怎么修改youtube翻译的默认语言呢？有的时候会自动给我翻译成繁体，我想看简体中文完全没办法，试着点了很多都无济于事啊

**Comment by keyboard3** [comment]
> 这个问题我也补充一下，怎么修改youtube翻译的默认语言呢？有的时候会自动给我翻译成繁体，我想看简体中文完全没办法，试着点了很多都无济于事啊

你这个case 应该是有自带中文字幕，而这个中文字幕内容就是繁体...，可以关闭人工字幕就可以了

**Comment by FattySpring** [comment]
该行为为 YouTube 的默认行为，如果特殊处理会出现，用户选择源语言字幕后不生效问题

**Comment by theowenyoung** [comment]
如果 您不主动选择youtube 自己的翻译的话，并且设置如下，那么我们目前的逻辑几乎和您建议的一致：

![CleanShot 2024-09-05 at 13 19 00@2x](https://github.com/user-attachments/assets/43cdd4c9-0593-46c9-8b53-3da231a02958)

1.当发布者没有自己提供字幕时，优先选择视频源语言的自动生成字幕，并通过翻译到目标语言。
1.当由发布者自己上传的字幕时，优先选择作者自己提供的字幕，并直接通过翻译到目标语言。
3.当发布者自己上传字幕的语言就是目标语言，或是视频源语言自动生成字幕就是目标语言，优先选中该字幕并关闭字幕翻译功能。
