### ISSUE TITLE
[Bug]: 火山翻译突然之间不能用了

### ISSUE THREAD

**Issue by MrArlong** [immersive-translate/immersive-translate#1971]
### 插件版本号 | Version

1.7.9

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

最近这几天火山翻译突然不能翻译了，在设置里面点测试key显示正常，但是页面上翻译就报错
![image](https://github.com/user-attachments/assets/3002f17b-e160-4f42-8411-3aa1f2b97310)

### 出现问题的网址 | URL

https://app.immersivetranslate.com/text#auto/en/11

### 重现步骤 | To Reproduce

直接在文本翻译页面输入任何文字都提示翻译失败

**Comment by meijin1123** [comment]
Hi ,我这边看起来是正常的，你刷新再试试？
<img width="1465" alt="image" src="https://github.com/user-attachments/assets/ccda0293-24e3-4e40-8a86-6c9d32e996ce">
