### ISSUE TITLE
[Bug]: PDF中图片翻译后旋转180度

### ISSUE THREAD

**Issue by L-BT-P** [immersive-translate/immersive-translate#1972]
### 插件版本号 | Version

V1.8.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

上传PDF文件翻译，中间有个图片翻译后排版被旋转了180度。
![image](https://github.com/user-attachments/assets/cd8e72cb-68e0-4d5f-992b-b09bef1f66e2)

### 重现步骤 | To Reproduce

PDF文件为经济学人2024年8月2日刊。

**Comment by L-BT-P** [comment]
问题无法稳定复现，重新上传PDF后现象消失，无法确定复现手法。

**Comment by meijin1123** [comment]
Hi 我这边翻译正常，没有复现该问题。
<img width="1471" alt="image" src="https://github.com/user-attachments/assets/f5a27f85-0c41-4d9d-925e-d9ae277f9e0d">
