### ISSUE TITLE
使用pdf文档翻译，在默认的双页视图下，右侧翻译的文档有一部分不能正常显示[Bug]: 

### ISSUE THREAD

**Issue by Little-attendant** [immersive-translate/immersive-translate#1974]
### 插件版本号 | Version

1.81

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![QQ_1722847231966](https://github.com/user-attachments/assets/cbb4865e-8698-4355-a1b8-f1ae91910c45)
[korean_history.pdf](https://github.com/user-attachments/files/16493152/korean_history.pdf)

### 出现问题的网址 | URL

extension://bpoadfkcbjbfhfodiogcnhhhpibjhbnh/pdf/index.html?file=https%3A%2F%2Fmirror.adversec.com%2Fdprk%2Fdprk-34c4%2FDPRK-34C3-PDFs%2FEducation%2FSecondary%2F1%2Fkorean_history.pdf

**Comment by meijin1123** [comment]
Hi 
这个是源文件数据会导致这个问题，可以通过点击样式设置，调整译文布局的距离左边百分比，如同所示，可以解决该问题。
<img width="1388" alt="image" src="https://github.com/user-attachments/assets/b5f2afb3-e949-4e31-ae10-941d40212b78">
