### ISSUE TITLE
youtube的字幕翻译会遮挡视频中原来的字幕 可否把双语字幕放在整个视频页面的下面

### ISSUE THREAD

**Issue by zaizhe** [immersive-translate/immersive-translate#1975]
![Snipaste_2024-08-05_19-06-27](https://github.com/user-attachments/assets/89fe884c-6fce-4c94-8935-56c07a5ad862)
![Snipaste_2024-08-05_19-08-02](https://github.com/user-attachments/assets/e347b01c-b0b0-4e5e-82fc-ed0e3defcd1b)

**Comment by meijin1123** [comment]
Hi
字幕可以上下移动的 
![image](https://github.com/user-attachments/assets/3aec6103-b263-4db2-be1e-136108418197)

**Comment by zaizhe** [comment]
I see, thanks a lot for the reply. And thank you so much for developing such a great tool!

**Comment by zaizhe** [comment]
或许我还有另外一个问题，请问安卓手机上下载了内置沉浸式翻译的浏览器，在该浏览器内观看youtube视频的时候如何实现双语字幕的拖动？

**Comment by meijin1123** [comment]
你可以试试，也是可以正常拖动移动的字幕的。

**Comment by zaizhe** [comment]
IOS客户端可以 安卓好像不行 会和全屏的手势冲突，不过我发现在广告页面反而可以hhh 正常的播放页面会和全屏或者更多视频的手势冲突
