### ISSUE TITLE
DeepL繁體中文翻譯

### ISSUE THREAD

**Issue by shawnhsieh2019** [immersive-translate/immersive-translate#1976]
### 您希望的更新和改进是什么 | Update or Improve

DeepL已經正式支持繁體中文的翻譯
https://www.deepl.com/en/blog/deepl-translator-now-supports-traditional-chinese
不知道現在是使用你們團隊自己開發的繁體中文翻譯工具還是直接調用DeepL原生的繁體中文翻譯？

**Comment by theowenyoung** [comment]
将在1.8.2 版本支持

**Comment by theowenyoung** [comment]
好吧，重新测试了一下，发现 DeepL 的网页翻译接口目前还不支持繁体，我们需要等待官方支持。

**Comment by theowenyoung** [comment]
您好，从 1.8.4 版本起已经支持native的中文繁体。
