### ISSUE TITLE
[Bug]: old reddit - Translation fails for posts containing galleries

### ISSUE THREAD

**Issue by kaoh08** [immersive-translate/immersive-translate#1977]
### 插件版本号 | Version

1.8.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

When attempting to translate posts that include a gallery, the main content remains untranslated. However, translation works correctly for text-only posts or posts with inline images.

### 出现问题的网址 | URL

https://old.reddit.com/r/MouseReview/comments/1el5syt/i_got_the_zowie_u2_24_hour_review/

### 重现步骤 | To Reproduce

1. Navigate to a post that includes a gallery. (for example: https://old.reddit.com/r/MouseReview/comments/1el5syt/i_got_the_zowie_u2_24_hour_review/)
2. Attempt to translate the post using either the translation button or the auto-translate feature.
3. Observe that the main content does not translate, while other comments translate normally.

**Comment by meijin1123** [comment]
Hi  This issue has been fixed, you can try again.
<img width="1475" alt="image" src="https://github.com/user-attachments/assets/b507f0f0-5852-433a-ab89-97848b2214e6">

**Comment by kaoh08** [comment]
Thank you for the fix on the issue; it works correctly now. However, I’ve noticed the same problem happened on another case (https://old.reddit.com/r/MouseReview/comments/1eli7u9/razer_gen2_optical_switch_feels_very_stiff/) with posts containing just one picture. Could this be checked?

**Comment by keyboard3** [comment]
> Thank you for the fix on the issue; it works correctly now. However, I’ve noticed the same problem happened on another case (https://old.reddit.com/r/MouseReview/comments/1eli7u9/razer_gen2_optical_switch_feels_very_stiff/) with posts containing just one picture. Could this be checked?

Okay has been fixed, can try it
