### ISSUE TITLE
[Bug]: pdf 翻译，每隔一页漏翻译一页

### ISSUE THREAD

**Issue by fluidog** [immersive-translate/immersive-translate#1978]
### 插件版本号 | Version

1.8.1

### 请描述这个Bug | Describe the bug

翻译 pdf 文件时，会每隔一页才翻译，比如仅仅翻译 1,3,5,7.... 页。
<img width="849" alt="image" src="https://github.com/user-attachments/assets/d7bda7f5-a270-4b8d-9b83-88577df9be4e">
已试过多个翻译引擎，重装插件，重启浏览器。依然会出现相同问题。

### 补充说明 | Additional context

稳定复现

**Comment by meijin1123** [comment]
可以提供下你的pdf文件吗？我这边需要复现一下

**Comment by fluidog** [comment]
> Hi , 问题已修复，你可以再翻译一下 <img alt="image" width="1430" src="https://private-user-images.githubusercontent.com/175077240/355750701-4b9e4751-b706-4a35-9168-0c160009e0ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMjg0MjgsIm5iZiI6MTcyMzAyODEyOCwicGF0aCI6Ii8xNzUwNzcyNDAvMzU1NzUwNzAxLTRiOWU0NzUxLWI3MDYtNGEzNS05MTY4LTBjMTYwMDA5ZTBlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QxMDU1MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZDg0NWI3YTQ5MmVlZDI1ZWU2ODI0Yzg5MGM5MDA4Nzg1MjNlMGZhZjNmNmU4MzdjN2MxOWQ1MjZlYTM2OTNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rc5ate1l5yMk18fHM5G4F3Y5ukvT594G2OhgmlaRClc">

试了一下，正常了，为你们的效率点赞👍
