### ISSUE TITLE
[Bug]: ai 专家-分词对照翻译助手 ：出现乱码

### ISSUE THREAD

**Issue by fluidog** [immersive-translate/immersive-translate#1979]
### 插件版本号 | Version

1.8.1

### 请描述这个Bug | Describe the bug

稳定复现乱码
使用任意 ai 模型，包括 openai、siliconcode 等，选择ai 专家：分词对照翻译助手后，出现乱码
<img width="1042" alt="image" src="https://github.com/user-attachments/assets/74ff6636-505e-4796-b0c4-46bdad90bbdb">

**Comment by TaoLoading** [comment]
你好，受限于文件排版，分词对照翻译并不适合翻译文件。这是由于字符太多挤压造成的
