### ISSUE TITLE
[功能建议]OpenAI翻译支持多key

### ISSUE THREAD

**Issue by smark-d** [immersive-translate/immersive-translate#198]
支持多个OpenAI密钥，以提升翻译速度。如果作者没有时间，我可以帮忙完善一下。

**Comment by theowenyoung** [comment]
欢迎呀！已经邀请你了！

之前也有用户对 Deepl 或者 有道 等服务提过类似的需求，多个key 轮流用这样～

**Comment by theowenyoung** [comment]
楼主非常高效，已经贡献了这个特性,最新版本已经支持。

但是目前只贡献了 openai的，可以用 `,` 分割多个key.

**Comment by GrayXu** [comment]
类似地，DeeplX这种自建的API也会受限于单IP的并发量，也可以考虑做多个API URL轮询来提升速度。

**Comment by theowenyoung** [comment]
还是给所有可填写key的服务都加一个类似的功能吧。

**Comment by Root-FTW** [comment]
> 还是给所有可填写key的服务都加一个类似的功能吧。 Let's add a similar feature to all services that have fillable keys.

我希望你能做到这一点，谢谢你!

**Comment by smark-d** [comment]
> 还是给所有可填写key的服务都加一个类似的功能吧。

好的，我晚会加一下。由于长时间未活跃，目前仓库代码已隐藏，麻烦作者开通一下

**Comment by theowenyoung** [comment]
0.5.8 已支持，用逗号, 分开即可。

**Comment by kettly1260** [comment]
> 0.5.8 已支持，用逗号, 分开即可。
deeplx可以添加多个url实现负载均衡吗
