### ISSUE TITLE
翻译的有问题，如图[Bug]: 

### ISSUE THREAD

**Issue by youngledo** [immersive-translate/immersive-translate#1980]
### 插件版本号 | Version

1.8.1

### 平台 | Platform

macOS

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

<img width="783" alt="image" src="https://github.com/user-attachments/assets/285efa12-6289-452a-9cc0-d76f1fefbb93">

<img width="886" alt="image" src="https://github.com/user-attachments/assets/24ec70a7-a92d-4d7b-97a8-c7ea4fd46c3c">

<img width="892" alt="image" src="https://github.com/user-attachments/assets/5dc00d1b-487c-4e64-a0a1-105e5c89b5d1">

这种情况很常见，这只是其中几个错误。

### 出现问题的网址 | URL

https://www.jetbrains.com/help/idea/tutorial-get-started-with-profiling.html#analyze

### 重现步骤 | To Reproduce

点击图标即可复现。

**Comment by meijin1123** [comment]
我这里正常，你用的什么翻译服务
![image](https://github.com/user-attachments/assets/1ba4db11-512f-42b6-bb9e-ff6de384c5b7)
![image](https://github.com/user-attachments/assets/bff117f1-7fd3-422b-ad1b-43b599eb9918)
![image](https://github.com/user-attachments/assets/37b1f123-062a-4dcc-a2ef-d9185885a993)
![image](https://github.com/user-attachments/assets/5c3e7507-8e96-46c0-8c1a-40ef8e3f6d15)

**Comment by youngledo** [comment]
我知道了，是翻译的问题
