### ISSUE TITLE
[Bug]: Google界面无法使用翻译插件，并且无法使用输入框增强功能

### ISSUE THREAD

**Issue by zhouziran23** [immersive-translate/immersive-translate#1981]
### 插件版本号 | Version

1.8.1

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

使用Chrome浏览器打开google网页后插件显示“暂无权限翻译当前页面（可能的原因是：新标签页或浏览器特权页面等）”
<img width="1327" alt="Snipaste_2024-08-07_11-53-07" src="https://github.com/user-attachments/assets/7724d874-4d0b-4745-9f6d-8c68ae898727">

### 出现问题的网址 | URL

www.google.com

**Comment by meijin1123** [comment]
你截图的浏览器没有地址，你输入一下地址www.google.com，就可以正常使用了

**Comment by fight46** [comment]
一样的问题
