### ISSUE TITLE
[Bug]: 在线阅读电子书-鼠标悬停功能失效

### ISSUE THREAD

**Issue by flower-design** [immersive-translate/immersive-translate#1984]
### 插件版本号 | Version

1.8.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

鼠标悬停没有反应

### 重现步骤 | To Reproduce

网页端鼠标悬停功能正常，但阅读电子书的时候经常没反应。

### 补充说明 | Additional context

鼠标悬停避免了全文翻译的浪费，是一项非常好的功能。建议优先修复该功能。

**Comment by theowenyoung** [comment]
目前为已知问题，技术原理是因为电子书阅读的实现方式是 Iframe 嵌套，监听 iframe 中的鼠标悬停比较困难，我们继续研究下有没有更好的解决方案。

**Comment by keyboard3** [comment]
1.10.6 已支持鼠标悬停电子书
