### ISSUE TITLE
PDF跟随翻译

### ISSUE THREAD

**Issue by jahangirW** [immersive-translate/immersive-translate#1985]
### 您希望的更新和改进是什么 | Update or Improve

将PDF的中英文翻译分开不是个很方便的想法，尤其是需要文章精读的情况下，反复在左右两边来回操作和定位翻译的词句是非常麻烦的一件事，如果能像网站一样跟随翻译就非常舒服了，可以随时操作笔记，这一点对屏幕较小的用户会非常友好。考虑到需要阅读大量PDF的人群往往采用较为便携的移动设备，小屏幕还要进行分别观看两种语言的文件，对于我来说就是个灾难。

### 补充说明 | Additional context

非常期待PDF能够像你们阅读电子图书那样跟随翻译而不是分成两大区域，这对于阅读体验而言是十分割裂的，也很不方便，既然是沉浸式翻译软件，电子图书都能像网站一样跟随翻译，PDF为什么不行呢

**Comment by keyboard3** [comment]
因为PDF本身是PDF格式，不是网页。免费方案只能够做到将右边尽量保持排版格式翻译内容。无法做到网页效果。如果你想要那种上下的效果的需要ocr识别+重排版。你可以试试 https://app.immersivetranslate.com/pdf-pro ,不过比较适合公式类型的pdf
