### ISSUE TITLE
[Bug]: epub 翻譯時，html tag來源語言lang="en"沒有同時轉換

### ISSUE THREAD

**Issue by Benlee1129** [immersive-translate/immersive-translate#1986]
### 插件版本号 | Version

v1.8.1

### 平台 | Platform

Android

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

由於來源語言的html tag，沒有轉換為目標語言，導致Google play 圖書App 在語音朗讀時，使用錯誤的語言理境。用英語音唸中文的怪異現象。

### 出现问题的网址 | URL

none.

**Comment by keyboard3** [comment]
没看懂，方便录个屏吗？

**Comment by keyboard3** [comment]
我们的译文段落都会带上lang属性，你看下那边是否存在这个属性？

**Comment by keyboard3** [comment]
暂无反馈 关闭此issue
