### ISSUE TITLE
[Bug]: 页面存在重复翻译和过度翻译情况

### ISSUE THREAD

**Issue by zhufeizzz** [immersive-translate/immersive-translate#1987]
### 插件版本号 | Version

1.8.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

段落被重复翻译
![image](https://github.com/user-attachments/assets/831667f0-c11f-40a6-847a-3dc4f73a9797)

结尾的JSON的代码也被翻译，而且JSON选中按Shift也无法取消翻译
![image](https://github.com/user-attachments/assets/9bb9de6b-5fcd-4ea4-a723-ec9d22c298f6)

### 出现问题的网址 | URL

https://ar5iv.labs.arxiv.org/html/2307.16789#A1.SS5

### 重现步骤 | To Reproduce

翻译设置
![image](https://github.com/user-attachments/assets/9632993e-e7fe-4cc8-ace9-eed9363c2d5c)

问题网址
https://ar5iv.labs.arxiv.org/html/2307.16789#A1.SS5

**Comment by keyboard3** [comment]
你这个比较难办的事情是，代码部分只是普通的内容，无法识别区分出来。正常的代码都是由pre、code标签包裹是不翻译的。
<img width="599" alt="image" src="https://github.com/user-attachments/assets/a24346c6-9be6-4a24-a9c2-4c79e7dedeba">
这个给个解决办法就是，可以用鼠标悬停，选择自己需要翻译的部分，不想翻译的跳过

**Comment by keyboard3** [comment]
重复翻的我们在继续跟，这个网站的排版有点奇怪

**Comment by zhufeizzz** [comment]
> 你这个比较难办的事情是，代码部分只是普通的内容，无法识别区分出来。正常的代码都是由pre、code标签包裹是不翻译的。 <img alt="image" width="599" src="https://private-user-images.githubusercontent.com/13177744/356442763-a24346c6-9be6-4a24-a9c2-4c79e7dedeba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxODM1MjgsIm5iZiI6MTcyMzE4MzIyOCwicGF0aCI6Ii8xMzE3Nzc0NC8zNTY0NDI3NjMtYTI0MzQ2YzYtOWJlNi00YTI0LWE5YzItNGM3OWU3ZGVkZWJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDA2MDAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkZGZiMzgyODgxZTZmNDEwYzhmMjVkNjM2M2JiMDJiYjRjYTFiNzg2Mzg1NTY0ZTYxNmMyOWEyNWJkNGU3OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.liC-XGIliHuXe9QH9G8UDT_-QnU0yiGA_B9tNSsy1RY"> 这个给个解决办法就是，可以用鼠标悬停，选择自己需要翻译的部分，不想翻译的跳过

这是几个问题
1、过度翻译问题。即使没在Code里面，JSON或其它代码可以尝试通过规则方式跳过。
2、段落翻译最少字符数未生效。我设置了最短50字符翻译，实际里面的JSON字符全翻译。
3、无法取消翻译。通过“悬停翻译触发键”无法取消。

**Comment by keyboard3** [comment]
> > 重复翻的我们在继续跟，这个网站的排版有点奇怪
> 
> 我发现**译文在先，原文随后**也会出现重复翻译的问题。下面这2页面在我这100%复现重复翻译问题： https://github.com/AntiMicroX/antimicrox/releases ![1](https://private-user-images.githubusercontent.com/47630168/356858523-8481ecd9-bd8d-49c2-ad58-105e289e748f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MTg2NjYsIm5iZiI6MTcyMzYxODM2NiwicGF0aCI6Ii80NzYzMDE2OC8zNTY4NTg1MjMtODQ4MWVjZDktYmQ4ZC00OWMyLWFkNTgtMTA1ZTI4OWU3NDhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDA2NTI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxYjE5ZGZmMTg4ZmQ2OWVhODYwZTRiODg5OGM3OGVjZmJmMjgxNmRiNmVhN2I2OTEwMmQ3YjM3ZTY0Zjg4OWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HrxQp1T2C1e7mytmYanhcwnW9JvnIWZIVeeuBtauSx4)
> 
> https://www.nexusmods.com/skyrimspecialedition/mods/29416 不开启**长段落自动换行**就没问题 ![2](https://private-user-images.githubusercontent.com/47630168/356858577-8d3a33d9-772e-4f5a-8cfe-83977bfac5e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MTg2NjYsIm5iZiI6MTcyMzYxODM2NiwicGF0aCI6Ii80NzYzMDE2OC8zNTY4NTg1NzctOGQzYTMzZDktNzcyZS00ZjVhLThjZmUtODM5NzdiZmFjNWUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDA2NTI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjY2Y1OTM4YmRhYTg1OGI0YzRmZGVjOGZmNDhhNDM3ZjY1MTA2NDlhNjk3NjE2ZTA3YzYxZGVmOWQ1OTQwZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kVOPokC1A-I33KRGSspSQVN5LvT9ck5a899DIqH24-M)
> 
> 一旦开启就这样了。还存在漏翻的情况，比如“Introduction”就没翻译，上面那个图就正常 ![3](https://private-user-images.githubusercontent.com/47630168/356858591-f8dc82e8-86d8-4cb7-97a0-d4677b4e1c66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MTg2NjYsIm5iZiI6MTcyMzYxODM2NiwicGF0aCI6Ii80NzYzMDE2OC8zNTY4NTg1OTEtZjhkYzgyZTgtODZkOC00Y2I3LTk3YTAtZDQ2NzdiNGUxYzY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDA2NTI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMzYwZTUyMmU5NzRlNjQ2YzE4NjdhNmUzNTM0ZGZmZjY0NmMyMTQ5N2IyZmM3OGRhZWFmMjA1ODQwOWNhOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zI7C6P4_6fU7ApLjD6Edqo9SOjgvA9LR76JA2-X6sBU)
> 
> 上述2个例子如果**译文在后**模式就不会有问题，只有**译文在前**才会这样；长段落没问题，单句才会出问题；开启自动翻译必定复现，关闭自动翻译且在网页加载完成后稍等会再手动打开翻译，出问题的概率会小很多，但绝不是一点问题没有；在重复翻译之后，取消翻译，再次打开翻译就会正常，刷新下网页，问题就会复现。
> 
> Chrome 126.0.6478.57 沉浸式翻译 1.8.1 浏览器扩展版

这个问题单独开新帖子

**Comment by keyboard3** [comment]
![image](https://github.com/user-attachments/assets/e5abab4a-fd1c-4eab-bcdf-90fd35224279)
![image](https://github.com/user-attachments/assets/b1c1625b-4dd8-4b75-8110-bfbcb3873d4f)
打开[这里](https://dash.immersivetranslate.com/#about)会自动更新规则，然后重试下
针对你的文章，目前排除了json部分的内容。但是不确定json部分的class会不会和其他文章需要翻译部分冲突，等其他人反馈
