### ISSUE TITLE
TED双字幕全屏后不显示

### ISSUE THREAD

**Issue by soeos** [immersive-translate/immersive-translate#1988]
### 您希望的更新和改进是什么 | Update or Improve

Chrome浏览器
TED不全屏的时候：（可以看到字幕）
![不全屏的时候](https://github.com/user-attachments/assets/b4bbce11-a13f-44ec-8db7-37a0749cbd05)
全屏后：（字幕消失）
![image](https://github.com/user-attachments/assets/4d48a0d5-ed9d-482f-9e09-25e0cfbc3c67)

**Comment by meijin1123** [comment]
全屏是字幕可以正常显示的，你是什么翻译服务？
1.检查一下你的字幕，自动开启双语字幕了，图二
2. 设置这里选择双语 图三
3. <img width="1489" alt="image" src="https://github.com/user-attachments/assets/1bdc46ed-2bf6-4c60-a496-8b983dd4636f">
<img width="1455" alt="image" src="https://github.com/user-attachments/assets/89472e20-b3f5-4f98-a3dc-b00560dd3920">

<img width="1483" alt="image" src="https://github.com/user-attachments/assets/bcda57b2-a091-46d9-99e5-24e47d24f1fe">

**Comment by TaoLoading** [comment]
问题已修复，进入 https://dash.immersivetranslate.com/#about 页面自动更新规则后即可使用
