### ISSUE TITLE
[Bug]: pro 用户 openai无法翻译长英文段落文字，但是切换其他翻译deep gemini 微软 都可以正常翻译

### ISSUE THREAD

**Issue by wzgrx** [immersive-translate/immersive-translate#1989]
### 插件版本号 | Version

1.8.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

pro 用户 openai无法翻译长英文段落文字，但是切换其他翻译deep gemini 微软 都可以正常翻译

**Comment by wzgrx** [comment]
pro体验和狗屎一样，还不如免费的好用，白白浪费5万tk

**Comment by meijin1123** [comment]
Hi 
方便提供一下你的PDF文件吗？我重现一下问题。
方便提供一下你的账号吗？关于你的5万tk 可以补偿给你。

**Comment by keyboard3** [comment]
暂无反馈 暂时关闭此issue
