### ISSUE TITLE
[功能建议]翻译出错部分一併重新翻译按钮

### ISSUE THREAD

**Issue by joeywen0830** [immersive-translate/immersive-translate#199]
如题，可以在翻译弹窗加上一个翻译出错部分一併重新翻译的按钮吗，不然有时候翻译长文，有时候有数个地方同时出错，需要一个一个错误部分按重新翻译按钮有些麻烦

**Comment by theowenyoung** [comment]
嗯，可以的～ 这个功能在计划中。

当前可以先点击 显示原文， 再重新翻译， 因为已翻译的部分有缓存，所以其实也相当于是只翻译失败的部分～

**Comment by theowenyoung** [comment]
已支持了哈。
