### ISSUE TITLE
quora显示错误

### ISSUE THREAD

**Issue by crysishacker** [immersive-translate/immersive-translate#1990]
### 您希望的更新和改进是什么 | Update or Improve

能不能不要翻译那个upvote了
![图片](https://github.com/user-attachments/assets/b96c1048-f253-4a95-b822-fc41278857ba)

**Comment by keyboard3** [comment]
已处理，打开这个[地址](https://dash.immersivetranslate.com/#about)自动更新规则，然后刷新重试下
