### ISSUE TITLE
[Bug]: 有些arxiv页面无法显示翻译链接

### ISSUE THREAD

**Issue by zhufeizzz** [immersive-translate/immersive-translate#1991]
### 插件版本号 | Version

1.8.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

比如这个论文：https://arxiv.org/abs/2302.04166
![image](https://github.com/user-attachments/assets/52bd7af8-72d8-4fec-babb-0b1c52a164f5)

而下面这个又是好的：https://arxiv.org/abs/2306.05685
![image](https://github.com/user-attachments/assets/a6be7f83-a8a4-49e8-8328-af99a823db33)

规律看起来应该是跟这个论文有没有默认带HTML版本有关，之前版本是没问题的。本来就可以直接跳转到https://ar5iv.labs.arxiv.org/地址，根本没有必要加这种约束
![image](https://github.com/user-attachments/assets/3162043b-77e8-42ee-b48c-ad03ef7f1bb7)

### 出现问题的网址 | URL

https://arxiv.org/abs/2302.04166

**Comment by keyboard3** [comment]
这是因为arxiv html版本有两个地址
1. https://arxiv.org/html
2. https://ar5iv.labs.arxiv.org/html
1.8.1只探测了1，下周将支持探测2

**Comment by keyboard3** [comment]
1.8.2 已支持
