### ISSUE TITLE
将AI翻译和附加扩展功能分开收费

### ISSUE THREAD

**Issue by Alexeu9136** [immersive-translate/immersive-translate#1993]
### 您希望的更新和改进是什么 | Update or Improve

提出这个请求的原因是，对于我来说，我有能力开通DeepL和OpenAI的API服务。所以在使用沉浸式翻译时，我一直作为一个免费用户。但是沉浸式翻译提供的，需要Pro会员的附加功能，如下载双语字幕、漫画翻译、用户设置多端同步等功能。我认为对于这些维护成本较小的功能，沉浸式翻译官方能够考虑与使用API的功能分开收费，我会很乐于为这些附加功能付费。

**Comment by keyboard3** [comment]
这里有一个隐藏的纯功能会员，就是没有任何额度的会员资格，能够使用下载双语字幕，多端同步设置。但是你说的漫画翻译它需要翻译额度，这个你可以按照自己的需求单独购买漫画流量包。
https://immersivetranslate.com/accounts/pre-order?price_id=price_1PSxxeGc8iUjvqOFykbfw67N

**Comment by youngledo** [comment]
> 这里有一个隐藏的纯功能会员，就是没有任何额度的会员资格，能够使用下载双语字幕，多端同步设置。但是你说的漫画翻译它需要翻译额度，这个你可以按照自己的需求单独购买漫画流量包。 https://immersivetranslate.com/accounts/pre-order?price_id=price_1PSxxeGc8iUjvqOFykbfw67N

为什么会员中心不显示这个呢？我只需要翻译的功能，不需要高级功能。放开吧。

**Comment by theowenyoung** [comment]
> 为什么会员中心不显示这个呢？我只需要翻译的功能，不需要高级功能。请问这个入口购买的会员是不是只包含这些：

如果只是需要翻译功能（谷歌翻译，微软翻译等）的话，免费即可使用，无需付费。

如果需要使用 DeepL 翻译等，需要开通 Pro
