### ISSUE TITLE
[Bug]: 油猴无法翻译youtube字幕

### ISSUE THREAD

**Issue by ysdj** [immersive-translate/immersive-translate#1994]
### 插件版本号 | Version

1.8.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

翻译按钮也没显示，控制台报错见图片：
![微信截图_20240810141307](https://github.com/user-attachments/assets/6996337b-a6cd-4f56-85ef-b01eb7bb327e)

导出配置文件：
[immersive-translate-config-2024-8-10_14-11-49.txt](https://github.com/user-attachments/files/16568692/immersive-translate-config-2024-8-10_14-11-49.txt)

### 出现问题的网址 | URL

https://www.youtube.com/watch?v=LtUx9edYcK0

**Comment by keyboard3** [comment]
这是YouTube最近严格了csp内容安全策略，油猴脚本都无法使用了。建议使用插件

**Comment by keyboard3** [comment]
`Content-Security-Policy: require-trusted-types-for 'script'`
![image](https://github.com/user-attachments/assets/5fce476a-6009-437c-8bcd-a784688be5c6)

![img_v3_02dl_e1f8a9e8-d27a-41c2-8e66-81627bdc11ag](https://github.com/user-attachments/assets/04b8592d-6f11-4d3e-984d-c3aa8c61849a)
youtube 这个变动主要影响chrome系浏览器
