### ISSUE TITLE
[Bug]: 微软翻译不可用

### ISSUE THREAD

**Issue by MrMingFang** [immersive-translate/immersive-translate#1995]
### 插件版本号 | Version

1.8.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Other

### 请描述这个Bug | Describe the bug

[微软翻译] 翻译服务或网络出现问题
您当前所使用的 [微软翻译] 服务因网络连接或服务提供商的问题暂时无法访问。
错误原因：Failed to fetch

### 出现问题的网址 | URL

https://app.immersivetranslate.com/text#auto/en/hello

### 重现步骤 | To Reproduce

任意英文网站点击翻译，均提示错误
F12控制台报错如下
Immersive Translate DEBUG: background received message fetch {responseType: 'text', url: 'https://edge.microsoft.com/translate/auth', headers: {…}, body: null, method: 'GET', …}
Immersive Translate DEBUG: fetch error https://edge.microsoft.com/translate/auth TypeError: Failed to fetch
    at Ro (background.js:5355:1661)
    at Ai (background.js:5147:16063)
    at Yt (background.js:5355:1086)
    at Sp (background.js:5599:464728)
    at background.js:5356:6005
    at background.js:5147:9692
Immersive Translate ERROR: fetchError: Failed to fetch
    at Tt (options.js:5710:3764)
    at async Dn (options.js:5710:1533)
    at async Object.onClick (options.js:5710:77038)

**Comment by keyboard3** [comment]
重启下浏览器试试

**Comment by MrMingFang** [comment]
> 重启下浏览器试试

已经尝试，没有解决，换手机热点也无法翻译

**Comment by MrMingFang** [comment]
更换edge浏览器之后可以了，应该是brave浏览器的某些隐私保护设置导致的，我重置了brave浏览器的设置之后可以正常使用了

**Comment by MrMingFang** [comment]
定位到问题原因，隐私獾扩展会阻止edge.microsoft.com域名，
![image](https://github.com/user-attachments/assets/c7fec0a1-90ac-468e-b10e-191d4c29dec9)
在设置里允许即可
