### ISSUE TITLE
[Bug]: Midjourney AI绘画提示词输入框无法进行翻译

### ISSUE THREAD

**Issue by linhaiboma** [immersive-translate/immersive-translate#1996]
### 插件版本号 | Version

1.8.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在https://discord.com 中输入 Midjourney AI绘画提示词就无法进行翻译，下图中输入的“一只猫”汉字，不管直接悬停翻译，还是全部翻译，还是3个空格翻译都无法翻译。其它谷歌搜索之类的输入框和翻译是正常的。

有什么办法能解决吗？我想了一个办法，是否可以通过选中文字的形式去翻译，相当于与我在输入框里面选中这一段文字，然后按快捷键进行翻译，翻译之后直接自动模拟Ctrl+V形式粘贴替换掉输入框里面选中的原文。
![MJ 输入框无法翻译截图](https://github.com/user-attachments/assets/06f50d48-1e20-4831-9e65-f46f6bf54e9e)

### 出现问题的网址 | URL

https://discord.com/

**Comment by keyboard3** [comment]
因为这个输入框特殊，嵌套了2层coetenteditable，比较难获取当前激活焦点

**Comment by TaoLoading** [comment]
该问题将会在 1.8.3 版本修复

**Comment by linhaiboma** [comment]
> 该问题将会在 1.8.3 版本修复

牛逼。Midjourney作为AI绘画产品的老大，有非常非常多人有这个翻译需求的。

**Comment by TaoLoading** [comment]
1.8.3 版本已发布，欢迎升级使用
