### ISSUE TITLE
[Bug]: 我购买了500页的PDF Pro 流量包并使用，但是翻译后文档无法导出。

### ISSUE THREAD

**Issue by flysaber** [immersive-translate/immersive-translate#1997]
### 插件版本号 | Version

1.8.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

我的账号：tideclaw@gmail.com
我缴费了500页的pdf pro 翻译费用，采用open ai 翻译，但是翻译完毕后导出不了pdf文件，总是提示谷歌浏览器奔溃，换电脑换浏览器都不行，可以帮我导出翻译完毕的PDF吗。现在费用扣了 文件导出不了，请官方人员帮忙导出。这是翻译链接：https://app.immersivetranslate.com/pdf-pro/39742fa1-1094-475c-a478-fad9b323476a
如果能帮我导出翻译后的pdf，可以帮忙发我邮箱tideclaw@gmail.com
非常感谢

### 出现问题的网址 | URL

https://app.immersivetranslate.com/pdf-pro/39742fa1-1094-475c-a478-fad9b323476a

**Comment by keyboard3** [comment]
最好不要在公开站点留下你的个人信息哈，尽量微信联系工作人员，我看到Owen已经在微信和你沟通，将这个issue关闭了
