### ISSUE TITLE
[Bug]: ytb视频字幕翻译功能失效

### ISSUE THREAD

**Issue by ceirogs** [immersive-translate/immersive-translate#1999]
### 插件版本号 | Version

1.8.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

在youtube主界面翻译功能正常，点进任意一个视频后都没有字幕自动翻译，同时侧边的悬浮球没有了鼠标悬停的提示，点击也没有变化
![QQ截图20240811215335](https://github.com/user-attachments/assets/60d40653-0d45-47b2-a8a3-8a6e6d844988)

**Comment by keyboard3** [comment]
这是YouTube最近严格了csp内容安全策略，油猴脚本无法使用了。建议使用插件

**Comment by ceirogs** [comment]
是这样的，我更换了插件版后解决了
