### ISSUE TITLE
自动翻译的失效

### ISSUE THREAD

**Issue by Andy-AO** [immersive-translate/immersive-translate#20]
我观察到这样一种现象，当我一次性在后台打开两个页面以上的时候，有时会发现没有阅读的那个页面被激活时，它不会自动翻译。但是我在最初的时候并没有复现出来，虽然这个经常出现，但我好像没有掌握复现它的关键点。

今天我突然意识到原因，可能是时间，我在后台打开两个页面，然后不去激活他们，而去阅读别的网页，很长时间之后我回来再激活它们，我发现自动翻译机制失效了。

**Comment by theowenyoung** [comment]
这个好像是 浏览器 在长时间没有活跃的链接，会自动断开连接。 一般是至少5分钟后才能这样。

这个好像时间不固定..

遇到这个情况刷新一下网页即可。

不过可以先不关闭这个问题，再观察一下。

**Comment by Andy-AO** [comment]
> 这个好像是 浏览器 在长时间没有活跃的链接，会自动断开连接。 一般是至少5分钟后才能这样。
> 
> 这个好像时间不固定..
> 
> 遇到这个情况刷新一下网页即可。
> 
> 不过可以先不关闭这个问题，再观察一下。

是的，刷新是个办法，但更简单的是重新按下翻译键。这导致了该功能的不稳定，自动翻译变成有时候手动翻译。

**Comment by theowenyoung** [comment]
我去掉了一个60分钟的超时设置。 下个版本再试下吧。

**Comment by Andy-AO** [comment]
> 我去掉了一个60分钟的超时设置。 下个版本再试下吧。

好的

**Comment by Andy-AO** [comment]
> 我去掉了一个60分钟的超时设置。 下个版本再试下吧。

经过测试，问题依旧存在，但很难确定具体的触发时间，但大概不会有 60 分钟，我经常是打开2~3篇文章，看完之后再看别的，我看一篇文章的时间应该不会超过一小时。

**Comment by YJL12345** [comment]
发现翻译全部失效了，不知道什么原因

**Comment by theowenyoung** [comment]
这个问题最近还有出现吗？  我自己感觉大多数情况好像没什么问题了？

要不有问题再打开？ 暂时先关掉了～
