### ISSUE TITLE
deeplx 翻译 url 怎么配置？

### ISSUE THREAD

**Issue by Vixb1122** [immersive-translate/immersive-translate#200]
我本地试了没问题
![image](https://user-images.githubusercontent.com/17810492/223077028-92284696-bbd5-4671-85a2-0b3d1ff3cd78.png)
配上url测试有问题
![image](https://user-images.githubusercontent.com/17810492/223077094-1a07b91b-311f-42be-ba4b-505ab6361bf2.png)

**Comment by Vixb1122** [comment]
好了

**Comment by theowenyoung** [comment]
下个版本内置一下 localhost的域名～
