### ISSUE TITLE
[Bug]: 翻译PDF下载保存后，英文原件和翻译的页面尺寸不一致

### ISSUE THREAD

**Issue by zjx863** [immersive-translate/immersive-translate#2000]
### 插件版本号 | Version

1.8.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

翻译英文PDF文件，下载双语后，两个页面的尺寸不一致，有时发生有时不发生，之前一直都是好的
EDGE和chrome都是，是pdf文件的问题吗？
![Snipaste_2024-08-12_08-44-42](https://github.com/user-attachments/assets/2e8d19bc-5104-4cef-be71-9fab0cfb640c)
![Snipaste_2024-08-12_09-53-29](https://github.com/user-attachments/assets/715b1be0-6130-4dd5-b73f-a7276fcdff23)

**Comment by FattySpring** [comment]
可以提供下原文件吗

**Comment by zjx863** [comment]
给我个邮箱或者什么吧，我把文件私发你，不是保密内容，但版权不是我的

**Comment by keyboard3** [comment]
已修复，在尝试下

**Comment by zjx863** [comment]
![Snipaste_2024-08-12_15-25-38](https://github.com/user-attachments/assets/6677ef36-73fa-4404-af27-10f73db59ac8)
刚重新拖进去了一个文件，保存下载后再打开，还是高低之分，之前是在高的页面中间（居中），现在上对齐了，下面长出一截

**Comment by keyboard3** [comment]
你这个pdf看起来每张大小都不一样，你试过打印另存为吗？

**Comment by zjx863** [comment]
[
[26_PDFsam_Bioreactor_RJL02_2024.pdf](https://github.com/user-attachments/files/16596451/26_PDFsam_Bioreactor_RJL02_2024.pdf)
[111_PDFsam_food emulsifiers.pdf](https://github.com/user-attachments/files/16596452/111_PDFsam_food.emulsifiers.pdf)
](url)
我直接给两个文档的部分，你测试吧，我刚试了还是不行，
我下面这个初始设置还是偏的，虽然用设置里面的工具能调整
![Snipaste_2024-08-13_20-15-03](https://github.com/user-attachments/assets/66a59e8f-0a3f-4446-b403-600e0c556703)

感谢你们做了这个，很适合快速想过一遍，英文看太慢，用中文扫一遍，用的时候自己再翻译

**Comment by FattySpring** [comment]
已修复

**Comment by FattySpring** [comment]
已修复
