### ISSUE TITLE
[Bug]: 使用自定义大模型gemini-1.5-flash翻译时频繁出错

### ISSUE THREAD

**Issue by Nicecsh** [immersive-translate/immersive-translate#2001]
### 插件版本号 | Version

1.8.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

免费账号，使用自定义 Auth Key的gemini-1.5-flash大模型，“意译大师”模式，每秒最大请求数为10，自动翻译推特网站时频繁出现错误提示。
但是同样情况下使用大模型gpt-4o-mini、SiliconCloud都基本没有出错过，疑似是gemini-1.5-flash与沉浸式翻译插件适配有问题？点击重试按钮后大多数情况下还是会出现同样的错误提示。
<img width="240" alt="gemini" src="https://github.com/user-attachments/assets/b0b468b4-cc78-4277-b943-c89bf291bb8c">

### 出现问题的网址 | URL

x.com

**Comment by keyboard3** [comment]
看你的错误描述，说你的请求超过频率限制，这个对方接口限制。你可以自行去设置页调整每秒发送频率
