### ISSUE TITLE
[Bug]: 使用google翻譯時句子沒有全部翻譯

### ISSUE THREAD

**Issue by ggyy020406** [immersive-translate/immersive-translate#2005]
### 插件版本号 | Version

1.8.1

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

如圖
<img width="782" alt="螢幕截圖 2024-08-13 08 46 12" src="https://github.com/user-attachments/assets/53bb2d6f-b549-4298-9e8b-eb908d390de1">

那句 **_But I didn't use the quest 2. My only VR experience is with PS VR 1 and 2. The Quest 3 has been a far superior experience._**
只翻譯了 **_但我沒有使用 Quest 2。_**
後面全失蹤了

發生在使用google翻譯時，如使用bing翻譯是可以正常整句翻譯

### 出现问题的网址 | URL

https://www.reddit.com/r/OculusQuest/comments/175e7y3/comment/k4gv0lm/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by meijin1123** [comment]
我这边使用谷歌翻译服务，翻译正常的，你可以刷新一下页面，再翻译一下。
<img width="1445" alt="image" src="https://github.com/user-attachments/assets/4d275f48-0641-4669-a692-6b4cbf97989e">

**Comment by ggyy020406** [comment]
> 我这边使用谷歌翻译服务，翻译正常的，你可以刷新一下页面，再翻译一下。 <img alt="image" width="1445" src="https://private-user-images.githubusercontent.com/175077240/357251575-4d275f48-0641-4669-a692-6b4cbf97989e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MTYzMTgsIm5iZiI6MTcyMzUxNjAxOCwicGF0aCI6Ii8xNzUwNzcyNDAvMzU3MjUxNTc1LTRkMjc1ZjQ4LTA2NDEtNDY2OS1hNjkyLTZiNGNiZjk3OTg5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QwMjI2NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZGI2NGE5M2VjNzEzZjY0ZDY1MWUwMWE2MTA4ZTkwNDRjYmE2MTU2MDk5MDg4NWE1YTVlNDczMmY3ZjI1MDk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.p-44iJ_00imfRCXSHkb1iSmSqQoMy3cOJKoOwAs6V5A">

我發現即使直接在Google翻譯網站翻譯那一句
翻譯做簡體中文是可以完整翻譯，翻譯做繁體中文就只會翻譯頭一句
