### ISSUE TITLE
[Bug]: 当启用openAI富文本进行翻译时，翻译缓存会失效，只能多消耗tokens

### ISSUE THREAD

**Issue by 2776108571** [immersive-translate/immersive-translate#2007]
### 插件版本号 | Version

1.8.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

如题，不启用富文本翻译有时会导致超链接失效或排版问题，但是启用后只能消耗更多tokens

**Comment by keyboard3** [comment]
对呀 鱼与熊掌不可兼得

**Comment by 2776108571** [comment]
好吧，谢谢大佬回复，
所以我现在在学习如何使用rules自定义翻译内容来改善这一现状，遇到了一点小问题，还望大佬不吝赐教.
这段是网页的html代码

```
<div id="codeCheck" class="item">
    <h3>Enter the <strong>Mode code</strong>:</h3>
    <input
      id="textbox-codeinput"
      name="textbox-codeinput"
      type="text"
      inputmode="text"
      tabindex="0"
      class="macro-textbox"
    >
    <div id="codeInfo">
      <a class="link-internal macro-link" role="button" tabindex="0">
        <div class="btn med width75">
          <span class="btnText">Activate</span>
        </div>
      </a>
      <a href="https://xxxxxxxx.com" target="_blank" class="linkSml">
        Where to find the Mode code?
      </a>
    </div>
  </div>
```

我想要匹配的元素是
 <div class="btn med width75">
          <span class="btnText">Activate</span>
里面的···Activate···这个单词.

我此前都是写"[class='xxxxx']"来匹配里面的文本

到这里我写[class=’btnText‘]却失效了，但是我写[class='btn med width75']有效
可是很多时候一个vid里面会有多个span，还有icon图标什么的，导致翻译出现问题

我发现似乎是span里面的class都不行，而大部分vid里面的可以（我不懂html，只是临时看了看基础）
而且这个网站所有的按钮文本全都是span里面带上一个[class=’btnText‘]：（ <span class="btnText">文本</span>）

所以我想问一下大佬，怎么写才能匹配到所有<span class="btnText">？


下面是我刚写的匹配该网站里其他元素的ruler，测试有效
```
[
  {
    "matches": "xxxxxxxxxxx.com",
    "selectors.add": [
      "body h1",
      "body h2",
      "body h3",
      "body h4",
      "body h5",
      "body h6",
      "body p",
      "[id='supportGet']",
      "[class='btn menu blink']",
      "[class='btn menu']",
      "[class='btn wide']",
      "[class='btn med']",
      "[class='btn']",
      "[class='btnText']"
    ]
  }
]
```
