### ISSUE TITLE
[Bug]: 无法导出epub双语电子书

### ISSUE THREAD

**Issue by YunFeng86** [immersive-translate/immersive-translate#2009]
### 插件版本号 | Version

1.8.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox, Chrome, Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/9b4b510b-5f81-439c-b1d9-c2f26d88f8c3">
点击导出时会弹出提示框"undefined"

### 出现问题的网址 | URL

https://app.immersivetranslate.cn/ebook/make/  https://app.immersivetranslate.com/ebook/make/ 

### 重现步骤 | To Reproduce

1.从扩展中打开PDF/epub
2.打开文件
3.翻译
4.导出（无法导出）

**Comment by meijin1123** [comment]
Hi ，你好，方便提供一下你的文件吗？
我这边文件翻译成功后点击导出，可以看到下载正常的。
<img width="1457" alt="image" src="https://github.com/user-attachments/assets/775dfecc-eb82-4054-9807-002ede14efcd">

**Comment by YunFeng86** [comment]
[Supercommunicators.zip](https://github.com/user-attachments/files/16608801/Supercommunicators.zip)

**Comment by theowenyoung** [comment]
无法复现： 超级通讯员-Supercommunicators.epub.zip ，可以正常导出

**Comment by meijin1123** [comment]
使用window 电脑，chrome 和edge 浏览器 该文件可以正常翻译和导出。
<img width="1508" alt="image" src="https://github.com/user-attachments/assets/8c4b3214-53e2-4869-b6f4-1ea02bb14dbd">
