### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by aetly666** [immersive-translate/immersive-translate#2010]
### 插件版本号 | Version

1.8.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

youtube双语字幕翻译不稳定，刚开始可以运行，过了一段时间又不行，得重新安装插件

**Comment by meijin1123** [comment]
你好，发一下视频地址，我这边需要重现一下问题
我这边edge的浏览器双语字幕展示正常的
<img width="1044" alt="image" src="https://github.com/user-attachments/assets/0ac370bc-45bf-4a0b-9b10-46900195182e">

**Comment by keyboard3** [comment]
暂无反馈关闭此issue
