### ISSUE TITLE
请问这种是翻译的问题还是插件的问题呢？

### ISSUE THREAD

**Issue by youngledo** [immersive-translate/immersive-translate#2011]
### 您希望的更新和改进是什么 | Update or Improve

<img width="615" alt="image" src="https://github.com/user-attachments/assets/31be77d6-4b39-406f-9ca4-e442abad747a">
看样子是翻译的问题，这种是不是插件没办法处理？

**Comment by keyboard3** [comment]
是的 插件只负责发送翻译内容，这是翻译服务的处理结果

**Comment by keyboard3** [comment]
上面链接是纯高级功能的购买链接，如需翻译服务额度请从官网购买

**Comment by youngledo** [comment]
> 上面链接是纯高级功能的购买链接，如需翻译服务额度请从官网购买

应该有很多人跟我一样，只需要翻译服务，是否考虑下把“翻译服务”单独拿出来作为一个选择？毕竟用不上的也很浪费，费用上也增加了。如果推出这个选项，合适的话我会购买的。
