### ISSUE TITLE
edx网站无法翻译同个网页的多个视频，只能翻译第一个视频

### ISSUE THREAD

**Issue by dinosaur-fear** [immersive-translate/immersive-translate#2012]
### 您希望的更新和改进是什么 | Update or Improve

希望能够全覆盖视频

### 补充说明 | Additional context

![image](https://github.com/user-attachments/assets/ea20f584-9fc2-4a13-b10c-a6a113ef92b6)

**Comment by TaoLoading** [comment]
你好，你可以打开 [开发者设置](chrome-extension://bpoadfkcbjbfhfodiogcnhhhpibjhbnh/options.html#developer)，在 Edit User Rules 中输入配置解决这个问题：
```
[
  {
    "id": "edx",
    "subtitleRule.add": {
      "generalSetting": {
        "itemsPath": "text"
      },
      "injectedCss": [
        ".subtitles-menu span,.closed-captions {white-space: pre-line;}",
        "#immersive-translate-quick-button-container {display: inline-block; vertical-align: middle;}"
      ],
      "loadingContainerSelector": ".tc-wrapper",
      "quickButtonRule": {
        "appendSelector": ".secondary-controls",
        "insertBeforeSelector": ".speeds.menu-container"
      },
      "subtitleUrlRegExp": "/transcript/translation/",
      "type": "general"
    },
    "subtitleRule.add_v.[1.7.1]": {
      "attachRule": null
    }
  }
]
```

见下图：
![image](https://github.com/user-attachments/assets/4e5b5497-f89a-4725-aa50-a94c1d8e15f8)

**Comment by TaoLoading** [comment]
视频地址发一下。另外你可以点击视频中的沉浸式翻译图标，如果展开的菜单中包含了“下载字幕”选项则说明你的配置没有生效。你可以检查配置是否正确，或者手动触发保存

**Comment by bohancao888** [comment]
***@***.******@***.******@***.******@***.***

TaoLoading ***@***.***> 于2024年8月16日周五 09:28写道：

**Comment by bohancao888** [comment]
https://learning.edx.org/course/course-v1:HarvardX+CS50+X/block-v1:HarvardX+CS50+X+type@sequential+block@6dc3b19a2300489e8f680fa787b11bc2/block-v1:HarvardX+CS50+X+type@vertical+block@f5cd7dfd973e4b6b85ed8e914982f3f1

**Comment by TaoLoading** [comment]
按钮只会在一个视频上增加，你应该通过双语字幕判断是否生效
![image](https://github.com/user-attachments/assets/949a02a4-3bd1-48d4-8861-5b9d1b00a478)

**Comment by bohancao888** [comment]
好的，明白
