### ISSUE TITLE
[Bug]: 在Copilot的侧边栏中使用不了输入框增强功能

### ISSUE THREAD

**Issue by zhouziran23** [immersive-translate/immersive-translate#2014]
### 插件版本号 | Version

1.8.1

### 平台 | Platform

macOS

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在Copilot的侧边栏中使用不了输入框增强功能
<img width="1470" alt="Snipaste_2024-08-14_17-57-34" src="https://github.com/user-attachments/assets/ca2ffff9-b398-4da1-b7ba-5465d2ddf4b6">

### 出现问题的网址 | URL

https://www.bing.com/

### 重现步骤 | To Reproduce

在Copilot的侧边栏中使用不了输入框增强功能
<img width="1470" alt="Snipaste_2024-08-14_17-57-34" src="https://github.com/user-attachments/assets/066b4852-2b88-4311-a91f-ce425d451513">

**Comment by keyboard3** [comment]
是的 这里插件没有权限注入

**Comment by zhouziran23** [comment]
请问后续会有更新吗，加入相关权限？

周子然
***@***.***

**Comment by keyboard3** [comment]
这个主要看edge是否会开放权限

**Comment by zhouziran23** [comment]
好的好的，感谢解答


周子然
***@***.***
