### ISSUE TITLE
不要翻译Claude.ai代码框里的内容

### ISSUE THREAD

**Issue by temporalu** [immersive-translate/immersive-translate#2015]
### 您希望的更新和改进是什么 | Update or Improve

Hello。可以让插件不要翻译Claude代码框里的代码么？看起来会有点冗余。感谢❤️
https://claude.ai/chat/

### 补充说明 | Additional context

无。

**Comment by keyboard3** [comment]
没有代码块的示例，你用沉浸式的快照功能生成个链接
<img width="324" alt="image" src="https://github.com/user-attachments/assets/c636ca6f-637b-4d15-acb1-b0fca9b372c3">

**Comment by keyboard3** [comment]
已排除代码块翻译。打开[这里](https://dash.immersivetranslate.com/#about) 插件会自动更新规则，然后重试下
