### ISSUE TITLE
鼠标悬停快捷键`alt`显示改进

### ISSUE THREAD

**Issue by soxft** [immersive-translate/immersive-translate#2016]
### 您希望的更新和改进是什么 | Update or Improve

在插件快捷页面中，MacOs 系统上的 `ALT` 按键得到了正确的图标表示
<img width="317" alt="image" src="https://github.com/user-attachments/assets/0848a9b4-9028-463d-8302-066580e4a673">

但是在设置界面中, 此按键依然为 `ALT` 
<img width="964" alt="image" src="https://github.com/user-attachments/assets/46091cb7-318d-4f99-97d7-e8e1700588bb">

**Comment by soxft** [comment]
同时鼠标悬停 按下快捷键后，文字段落后方，可以考虑出现 loading 标识，以标识文本在翻译过程中

**Comment by flamintune** [comment]
下个版本修复
