### ISSUE TITLE
“译文在先，原文随后”模式下存在重复翻译的问题

### ISSUE THREAD

**Issue by pbxs666** [immersive-translate/immersive-translate#2017]
我发现**译文在先，原文随后**也会出现重复翻译的问题。下面这2页面在我这100%复现重复翻译问题：
https://github.com/AntiMicroX/antimicrox/releases
![1](https://github.com/user-attachments/assets/8481ecd9-bd8d-49c2-ad58-105e289e748f)

https://www.nexusmods.com/skyrimspecialedition/mods/29416
不开启**长段落自动换行**就没问题
![2](https://github.com/user-attachments/assets/8d3a33d9-772e-4f5a-8cfe-83977bfac5e0)

一旦开启就这样了。还存在漏翻的情况，比如“Introduction”就没翻译，上面那个图就正常
![3](https://github.com/user-attachments/assets/f8dc82e8-86d8-4cb7-97a0-d4677b4e1c66)

上述2个例子如果**译文在后**模式就不会有问题，只有**译文在前**才会这样；长段落没问题，单句才会出问题；开启自动翻译必定复现，关闭自动翻译且在网页加载完成后稍等会再手动打开翻译，出问题的概率会小很多，但绝不是一点问题没有；在重复翻译之后，取消翻译，再次打开翻译就会正常，刷新下网页，问题就会复现。

Chrome 126.0.6478.57
沉浸式翻译 1.8.1 浏览器扩展版

**Comment by keyboard3** [comment]
<img width="787" alt="image" src="https://github.com/user-attachments/assets/e7e599c6-f005-47b7-bb60-aae93b88320c">
按照你的步骤似乎并没有复现。给插件隐身权限，试试在隐身窗口下
