### ISSUE TITLE
[Bug]: “译文在先，原文随后”模式下存在重复翻译的问题

### ISSUE THREAD

**Issue by pbxs666** [immersive-translate/immersive-translate#2018]
### 插件版本号 | Version

1.8.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

我发现**译文在先，原文随后**也会出现重复翻译的问题。下面这2页面在我这100%复现重复翻译问题：
https://github.com/AntiMicroX/antimicrox/releases
![1](https://github.com/user-attachments/assets/8481ecd9-bd8d-49c2-ad58-105e289e748f)

https://www.nexusmods.com/skyrimspecialedition/mods/29416
不开启**长段落自动换行**就没问题
![2](https://github.com/user-attachments/assets/8d3a33d9-772e-4f5a-8cfe-83977bfac5e0)

一旦开启就这样了。还存在漏翻的情况，比如“Introduction”就没翻译，上面那个图就正常
![3](https://github.com/user-attachments/assets/f8dc82e8-86d8-4cb7-97a0-d4677b4e1c66)

### 出现问题的网址 | URL

https://github.com/AntiMicroX/antimicrox/releases和https://www.nexusmods.com/skyrimspecialedition/mods/29416

### 重现步骤 | To Reproduce

每次刷新必定复现

### 补充说明 | Additional context

上述2个例子如果**译文在后**模式就不会有问题，只有**译文在前**才会这样；长段落没问题，单句才会出问题；开启自动翻译必定复现，关闭自动翻译且在网页加载完成后稍等会再手动打开翻译，出问题的概率会小很多，但绝不是一点问题没有；在重复翻译之后，取消翻译，再次打开翻译就会正常，刷新下网页，问题就会复现。

**Comment by keyboard3** [comment]
<img width="1065" alt="image" src="https://github.com/user-attachments/assets/95fa52b5-51c3-4d7f-b944-c21a350eea51">
按照你的步骤并没有复现，给插件隐身窗口权限，在隐身窗口下试一试

**Comment by keyboard3** [comment]
![image](https://github.com/user-attachments/assets/d25ba64f-0789-4b93-be82-070124668474)
依然没复现

**Comment by keyboard3** [comment]
你升级到1.8.2之后，用这个反馈下，我看看有没有其他额外信息
![image](https://github.com/user-attachments/assets/6379d6a7-2293-4eb0-8bfb-cf757b4b8815)

**Comment by keyboard3** [comment]
看不出来问题，你除了上述这些网页，你其他每个网页都有这个问题吗？

**Comment by keyboard3** [comment]
嗯 试用几天之后确实复现了这个问题，将在1.8.4 修复
