### ISSUE TITLE
[Bug]: https://x.com/整页都翻译不了 

### ISSUE THREAD

**Issue by ayun110** [immersive-translate/immersive-translate#2019]
### 您希望的更新和改进是什么 | Update or Improve

[Bug]: https://x.com/整页都翻译不了 

### 补充说明 | Additional context

[Bug]: https://x.com/整页都翻译不了

**Comment by keyboard3** [comment]
重置下设置，应该是你的配置问题  http://dash.immersivetranslate.com/
