### ISSUE TITLE
#bug 后退上一个页面时，会重复翻译已经翻译过的文本

### ISSUE THREAD

**Issue by IlluminateDarkheat** [immersive-translate/immersive-translate#202]
示例：
![image](https://user-images.githubusercontent.com/28666767/223086217-d7f239e3-f85e-4c73-9ed6-57600a0590fb.png)
![image](https://user-images.githubusercontent.com/28666767/223086317-838db31d-10e9-4057-9fc2-534682770ebb.png)

**Comment by theowenyoung** [comment]
确认， 已修改规则。

点击下 浏览器图标，更新一下规则即可～
