### ISSUE TITLE
[Bug]: chrome扩展的injected css保存失败

### ISSUE THREAD

**Issue by ysdj** [immersive-translate/immersive-translate#2021]
### 插件版本号 | Version

1.8.2

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

如图，仅设置7个css项就开始无法保存，疑与字数限制有关
（点图片右上角播放动画）
![动画](https://github.com/user-attachments/assets/e394c1b6-f5be-4eb1-9286-386a7195d05f)

之前油猴没这个问题

**Comment by keyboard3** [comment]
小于7个就可以保存？可以看下控制台是否有报错。应该是超出了总配置数据超过了sync的8kb

**Comment by keyboard3** [comment]
这是chrome对插件的限制，油猴的存储方式不受限制

**Comment by keyboard3** [comment]
1.8.3 已修复
