### ISSUE TITLE
[Bug]: XSS 隐患

### ISSUE THREAD

**Issue by simonmysun** [immersive-translate/immersive-translate#2022]
### 插件版本号 | Version

1.8.2

### 平台 | Platform

Linux

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

类似 #1437、#744、#702，但 #1437 似乎又重新出现，而剩下两个没有正确实现 XSS。

翻译后会执行 &lt;img> 的 onerror 函数，翻译后的其它元素也会被渲染，所以还有 onmouseover 等更多靶点。

### 出现问题的网址 | URL

~~https://gistpreview.github.io/?28f7f7861598258038b0a9dbdbc6d15e~~

### 重现步骤 | To Reproduce

前往以下 HTML，翻译页面会弹窗一次，鼠标划过渲染出的按钮也会弹窗一次

```html
123<button onmouseover=alert(123)><img src="/404" onerror=alert(789)>im a button<script>alert(456)</script></button>456
```

### 补充说明 | Additional context

`<script>` 确实被过滤掉了。另外严格设置了 CSP 的页面不会触发，比如 Github 上控制台会报错：

```
Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src github.githubassets.com". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.
```

编辑：将外链替换为源码

**Comment by keyboard3** [comment]
确实 这是支持富文本翻译之后忽略了这种场景。下一版修复

**Comment by keyboard3** [comment]
1.8.3 已修复
