### ISSUE TITLE
仅译文模式时，设置了自定义样式的网站 依然保持双语显示

### ISSUE THREAD

**Issue by photkey** [immersive-translate/immersive-translate#2024]
对于大多数 可能只是临时看一次的网站 通常使用`仅译文模式`体验更好一些；但是一些常用的网站，需要更严谨一些，经常对照英文原文看；

但是目前我测试 勾选了`仅译文模式`的话 就对所有网站生效了，那些特别设置了译文样式的网站也是只显示译文，这个体验就不太好了。

我想了以下3种改进的方式：
1、`进阶设置`→`仅译文模式` 移动到 `基本设置`→`译文显示样式`，生效的逻辑跟之前完全一样；
2、不改变现在的设置项，如果勾选了`仅译文模式`，那些设置了自定义译文样式的网站，仍然按照自定义的样式**双语显示**；
我说的自定义样式的网站，指下面部分：
```
  "translationTheme": "weakening",
  "translationThemePatterns": {
    "grey": {
      "matches": [
        "pypi.org"
      ],
      "textColor": "#345b8d"
    },
    "none": {
      "matches": [
        "www.google.com/search*",
        "www.youtube.com",
        "github.com"
      ],
      "textColor": "#cacdc1"
    }
  },
```
3、类似现有设置项“仅译文模式的网址”，增加一个设置项：“双语模式的网址”，因为大多数网址 可能使用“仅译文模式”体验更好，但是域名未知（谷歌搜索到的），一定需要双语模式的网址 可能还少一点，这样设置起来更容易。

我认为这三种设置方式，最合理的应该是1，因为`仅译文模式`跟其它译文显示样式一样，也是显示方式的一种；
但是如果真这么改动吧，恐怕有些习惯了之前设置的用户 会找不到设置入口了，所以 我更推荐2的改进方式。
方式3 有可能就需要把设置过自定义译文样式的网址 重新添加一遍，繁琐了。

**Comment by theowenyoung** [comment]
这样怎么样？

- 当用户选 双语模式时， 进阶设置里出现 仅译文的网址设置。
- 当用户选 仅译文模式时，进阶设置出现 双语对照的网址 设置。

@keyboard3

**Comment by theowenyoung** [comment]
1.9.1 已支持。
