### ISSUE TITLE
[Bug]: 按钮按不动

### ISSUE THREAD

**Issue by hxse** [immersive-translate/immersive-translate#2026]
### 插件版本号 | Version

1.8.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

这几个按钮按不动
![动画](https://github.com/user-attachments/assets/87af0651-b132-4c60-96c6-0ff2aee81378)

### 出现问题的网址 | URL

每个网址上都有问题

**Comment by keyboard3** [comment]
插件或者浏览器重装下，这种情况是由浏览器导致的

**Comment by hxse** [comment]
我发现重装后表现正常, 但是一旦从drive中恢复配置文件, 就又点不动按钮了
是不是配置文件版本的问题

**Comment by keyboard3** [comment]
> 我发现重装后表现正常, 但是一旦从drive中恢复配置文件, 就又点不动按钮了 是不是配置文件版本的问题

？感觉不应该，配置数据多嘛，手动在配置回去呢？

**Comment by hxse** [comment]
手动配置回去后能用了

**Comment by keyboard3** [comment]
那我就先关掉这个issue

**Comment by hxse** [comment]
[immersive-translate-config-2024-8-19_14-44-36.txt](https://github.com/user-attachments/files/16656831/immersive-translate-config-2024-8-19_14-44-36.txt)
@keyboard3 
你试试我这个配置文件, 能复现问题不

**Comment by hxse** [comment]
我测试这个配置文件, 第一次导入会遇到按不动
然后, 把"matches"列表里面删除任意一个, 就正常了
但是, 再添加上就又按不动了
还有把"url"连接删除几个字符, 就又正常了
看起来好像是, 配置文件大小有限制?

**Comment by keyboard3** [comment]
对的 浏览器是有这个限制，你得mathces比较多是吧。下一个版本把matches单独存储就可以了
