### ISSUE TITLE
[Bug]: 悬浮球没有彻底关闭，在手机尺寸下刷新时仍然会出现

### ISSUE THREAD

**Issue by shinexoh** [immersive-translate/immersive-translate#2027]
### 插件版本号 | Version

1.8.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在彻底关闭悬浮球时，使用F12并设置手机尺寸在刷新网页时，右侧还是会出现悬浮球。
![image](https://github.com/user-attachments/assets/a227215b-2bad-4251-ae33-e666247d2a39)
![image](https://github.com/user-attachments/assets/0b415da1-77be-475d-b8b3-ace10fc1f168)

### 出现问题的网址 | URL

在所有网址上

### 重现步骤 | To Reproduce

1. 在设置关闭悬浮球显示
2. 打开任意网页
3. 按F12并设置手机尺寸显示
4. 刷新网页

### 补充说明 | Additional context

只在设置手机尺寸下会复现，正常浏览网页不会复现。
Chrome版本号：
![image](https://github.com/user-attachments/assets/273c6c89-7fc1-49f7-9add-2e28002e2425)

**Comment by theowenyoung** [comment]
因为 PC 版的悬浮球和手机版的悬浮球式独立的设置，所以你需要在手机模式下关闭悬浮球，如图


![CleanShot 2024-08-19 at 18 32 22@2x](https://github.com/user-attachments/assets/8a8ac2d1-696f-46cd-92dd-3381fb9879a9)
