### ISSUE TITLE
[Bug]: 推特帖子翻译后显示不完全

### ISSUE THREAD

**Issue by wengwulue** [immersive-translate/immersive-translate#2028]
### 插件版本号 | Version

1.8.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

使用翻译服务后，推特帖子打开详情页不显示页首内容和图片。关闭即可显示

### 出现问题的网址 | URL

https://x.com/home

### 重现步骤 | To Reproduce

1.打开推特任意帖子
2.打开翻译服务

**Comment by theowenyoung** [comment]
无法复现。
比如打开： https://x.com/Locati0ns/status/1825012208637477054

![CleanShot 2024-08-19 at 18 29 45@2x](https://github.com/user-attachments/assets/8f7a1d5c-78d9-4b46-898b-7712e8f2a789)


可以截图或者视频截图说明下问题吗？

**Comment by wengwulue** [comment]
经测试似乎与油猴脚本 Twitterᴾˡᵘˢ  https://openuserjs.org/src/libs/sizzle/GM_config.js
   冲突，关闭脚本后正常
