### ISSUE TITLE
[Bug]: Google 翻譯 tavily.com 漏翻跟元素缺失

### ISSUE THREAD

**Issue by Lawlietr** [immersive-translate/immersive-translate#2031]
### 插件版本号 | Version

1.8.2

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

存在大量漏翻以及元素消失問題

<img width="1242" alt="截圖 2024-08-21 09 52 59" src="https://github.com/user-attachments/assets/dd1e62b9-ad3f-41f5-ba41-091c97e69646">
<img width="1276" alt="截圖 2024-08-21 09 52 36" src="https://github.com/user-attachments/assets/38b09c86-c0e5-4849-b3a2-4e2517038872">

### 出现问题的网址 | URL

https://tavily.com

**Comment by keyboard3** [comment]
我试了下，没有复现。方便录个屏吗

**Comment by Lawlietr** [comment]
> 我试了下，没有复现。方便录个屏吗

我平常使用 Google 翻譯
我剛使用 Bing 翻譯是沒有問題的

還沒在 macos 錄過屏，要先研究下..

**Comment by keyboard3** [comment]
暂无反馈先关闭这个issue
