### ISSUE TITLE
一些网站的navigation bard导航栏无法被翻译

### ISSUE THREAD

**Issue by lswang6** [immersive-translate/immersive-translate#2033]
### 您希望的更新和改进是什么 | Update or Improve

比如：bbc.com 的导航栏
或许可以有办法翻译导航栏？
<img width="1454" alt="image" src="https://github.com/user-attachments/assets/368b9f5f-3ccc-46af-b51b-d746735456da">

**Comment by keyboard3** [comment]
默认只翻译主要区域，你可以切换到翻译全部区域，或者通过鼠标悬停翻译这个位置的文字
![image](https://github.com/user-attachments/assets/9601243a-79e8-4a06-b6b2-9dad6f1cfd37)
