### ISSUE TITLE
[Bug]: 谷歌浏览器长页面直接卡死

### ISSUE THREAD

**Issue by chenyigg** [immersive-translate/immersive-translate#2034]
### 插件版本号 | Version

1.8.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

浏览器版本128.0.6613.85，翻译长页面英文就会卡死，整个电脑和鼠标都卡死的那种，一顿一顿的，issue里面别的解决方案试过，什么最小最大字符、翻译字数什么的都试过不行。但是火狐不会，edge和谷歌同样问题

### 出现问题的网址 | URL

leafletjs.com

**Comment by keyboard3** [comment]
卡顿问题 统一在这个帖子中 https://github.com/immersive-translate/immersive-translate/issues/1746
