### ISSUE TITLE
[Bug]: 输入框增强, 当触发翻译的字符与部分翻译的分隔字符设置为同一字符时, 功能失效

### ISSUE THREAD

**Issue by XMB-7** [immersive-translate/immersive-translate#2036]
### 插件版本号 | Version

1.8.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/user-attachments/assets/02cb6455-4a8f-4609-b3b2-232e25f14424)

![recording](https://github.com/user-attachments/assets/c446574a-8ad5-49cc-a8f2-2a7cd7a81004)

除了会把分隔符之前的也给翻译出来之外, 还让原文错误地保留了下来, 而正常是原文会被译文替代.

### 出现问题的网址 | URL

https://immersivetranslate.com/docs/usage/?force=1

**Comment by theowenyoung** [comment]
这个可能无法避免，建议此种情况配合，选中之后右键输入框翻译，或者设置快捷键：

![CleanShot 2024-08-30 at 18 32 22@2x](https://github.com/user-attachments/assets/7920635d-41f0-4792-ac0b-c8322c96b00d)
