### ISSUE TITLE
希望在浏览器沉浸式阅读模式下也能够对选中的文本通过右键菜单项进行翻译。

### ISSUE THREAD

**Issue by Negaentropy** [immersive-translate/immersive-translate#2037]
### 您希望的更新和改进是什么 | Update or Improve

大量文本是在沉浸式阅读模式下浏览的，希望能像其他翻译插件一样，在阅读模式下仍能对选中的文本，在弹出的页面进行多服务商对比翻译，不一定要全文翻译。

**Comment by keyboard3** [comment]
浏览器的阅读模式，理论上插件是无法执行的。不清楚你说的是不是浏览器的阅读模式

**Comment by Negaentropy** [comment]
对我说的就是浏览器阅读模式，但其他翻译插件，如Depth Translator for DeepL，Edge Translate等，都是可以将划选的句子传递给插件，并弹出一个页面进行翻译。浏览器阅读模式下页面更清爽，选中翻译的需求更大。

**Comment by Negaentropy** [comment]
![image](https://github.com/user-attachments/assets/cd540b7e-9248-4cde-960a-b3179d67387f)
![image](https://github.com/user-attachments/assets/6b74e73b-b4cb-4184-a025-a00e77852558)

**Comment by flamintune** [comment]
这个问题有点麻烦，改动可能会影响到非阅读模式网页的右键菜单行为。

因为插件无法注入到阅读模式的网页，其他插件能做到的原因是他们的右键菜单和功能是不变的，即一直都是 Translate selected text with DeepL，一直都是翻译选中的文本。

对于沉浸式翻译来说，右键菜单是根据页面的选中状态来进行变化的，因为插件无法注入，插件无法获取到页面是否存在选中状态，无法判断右键菜单是否应该切换成翻译选中文本，还是翻译网页的状态，继而去做不同的处理。

**Comment by nicesky365** [comment]
如果改动和影响太大的话，建议阅读模式以后再考虑添加
