### ISSUE TITLE
[Bug]: pro.x.com 无法翻译，始终提示：等待注入页面中...若长时间未响应，请尝试刷新页面

### ISSUE THREAD

**Issue by Shawnli1874** [immersive-translate/immersive-translate#2038]
### 插件版本号 | Version

1.8.2

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome, Other

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

pro.x.com 无法翻译，始终提示：等待注入页面中...若长时间未响应，请尝试刷新页面
<img width="1819" alt="image" src="https://github.com/user-attachments/assets/1bb21993-3a49-4f1c-9e13-5a9ab2b77b10">

### 出现问题的网址 | URL

pro.x.com

### 重现步骤 | To Reproduce

1. 使用 arc 浏览器，打开登陆后的 pro.x.com 网页
2. 翻译插件无响应，显示：等待注入页面中...若长时间未响应，请尝试刷新页面
3. 切换翻译模型无效，重置设置无效，重启浏览器无效，重新安装插件无效

**Comment by theowenyoung** [comment]
感谢反馈，可以复现，我们调查一下。

**Comment by theowenyoung** [comment]
调查发现是 pro.x.com 网页似乎一直处于 loading 过程，而沉浸式翻译的插件注入时机是在网站加载完成后，所以一直没有注入成功，经测试其他插件在该网站也是类似的表现。

这个可能插件这边做不了什么。
