### ISSUE TITLE
[Bug]: 和欧路高亮同时使用时，会判定高亮的单词为一整段

### ISSUE THREAD

**Issue by babelfish4222** [immersive-translate/immersive-translate#2039]
### 插件版本号 | Version

1.8.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

这是单独开启欧路翻译插件的重点单词高亮功能时的样子
![微信图片_20240824153410](https://github.com/user-attachments/assets/d41c751a-9ac6-4275-b585-7862c27998e1)
这是同时开启沉浸式翻译的样子
![微信图片_20240824153415](https://github.com/user-attachments/assets/4cf9c0c2-1bcb-4605-9553-c48cb9912415)
我猜测是沉浸式翻译将欧路词典的每个高亮的单词都当做了一个段落，使得上下文割裂了。希望能更改一下。

### 出现问题的网址 | URL

https://www.nybooks.com/

### 重现步骤 | To Reproduce

1.在edge扩展商店里下载欧路翻译插件
2.打开任意一个英文网站
3.打开欧路翻译插件的设置，在重点单词高亮里选几个等级，并在显示方式中选择单词高亮。
![微信图片_20240824154029](https://github.com/user-attachments/assets/a8be86ab-4cb0-498e-8a81-3c6fae30c2c6)
4.打开沉浸式翻译

### 补充说明 | Additional context

如果无法修改判定欧路翻译插件的高亮单词为一整段的bug的话，希望沉浸式翻译也能出类似的功能，就是按照四六级、考研、雅思、更高难度这样来分成不同颜色高亮单词。

**Comment by keyboard3** [comment]
你可以在网页上复现这个问题之后，在这里提交下反馈
![image](https://github.com/user-attachments/assets/8da1836a-244f-4cc6-b8f3-5892f13fd91e)

**Comment by babelfish4222** [comment]
@keyboard3 已反馈，感谢回复

**Comment by keyboard3** [comment]
已修复
