### ISSUE TITLE
[Request] Exchange places of the original and translated texts and apply the display style also to the original text

### ISSUE THREAD

**Issue by iG8R** [immersive-translate/immersive-translate#204]
Hi.
Thank you for the excellent addon and userscript!
1. Could you, please, implement an option to show the translated text first, and then the original one?
2. It would also be great to apply different and separated display style to the translated text from the original.
3. Please, could you make it possible to show only translated text without the original?

**Comment by theowenyoung** [comment]
Thanks, I'm working on this feature (show only translated text), but it take times, cause this addon is designed for dual language.

> It would also be great to apply different and separated display style to the translated text from the original

change the original text style is not planned. cause this may bring  breaks for the original website.

**Comment by iG8R** [comment]
Thanks for such a quick response.
Since the addon is designed for a dual language concept, in some cases it would be convenient to have the translated text in the first place, and below it the original one with another, for example blurry, display style.
Also, if there is only translated text would be shown, it'll be great to show popup tooltip or window when hovering above translated text, as implemented in https://github.com/FilipePS/Traduzir-paginas-web

**Comment by theowenyoung** [comment]
We have supported translation only mode now, please click [More] -> [Switch to Translation Only]

**Comment by iG8R** [comment]
Yeah, I know about this new feature, but it isn't the same as I requested before.

**Comment by theowenyoung** [comment]
Sorry, I misunderstood, this feature should not be done, because modifying the style of the original text will cause problems with the functionality of some pages, so we do not consider implementing this.

**Comment by iG8R** [comment]
At least could you simply blur the original text and the translated text to be clearly visible, while the original text became clearly visible only when you hover the mouse over it?

**Comment by theowenyoung** [comment]
sorry, to make the original text ambiguous means to modify some style of the original element, which is not what we want to do.

**Comment by iG8R** [comment]
OK.
