### ISSUE TITLE
注释功能需要优化

### ISSUE THREAD

**Issue by skyknoow** [immersive-translate/immersive-translate#2042]
### 您希望的更新和改进是什么 | Update or Improve

注释功能需要优化

点击字体后添加的文本框不能缩放，导致文本过长影响原文观感

建议：整合进highlight里

### 补充说明 | Additional context
尽管我知道使用 web highlights可以方便注释，但是，这只对web方便。对于本地文件而言，当使用[immersive-translate]打开本地pdf进行翻译后，如果想对原文进行注释，那么web highlights只会将[immersive-translate]的固定路径{https://app.immersivetranslate.com/pdf/}当作笔记所标记的地址，这使得web highlights根本无法正常工作。

故此，希望[immersive-translate]可以推出注释功能。

这个功能实际上在其他平台已经实现，比如{https://www.scholaread.com}。

我相信整合高亮（注释）后[immersive-translate]会更加好用！至少对于本地pdf阅读用户而言。

_No response_

**Comment by keyboard3** [comment]
本地pdf阅读器是利用[moaizla](https://mozilla.github.io/pdf.js/)，所有注释功能基础此。暂无计划对它做更进一步开发
