### ISSUE TITLE
腾讯翻译君默认请求限制

### ISSUE THREAD

**Issue by lingfengyu-dreaming** [immersive-translate/immersive-translate#2043]
### 您希望的更新和改进是什么 | Update or Improve

近期换用了腾讯翻译君的服务，在翻看api文档的时候发现了调用api是有很大限制的，查看了沉浸式翻译的文档后发现这些限制需要手动配置，并且配置方式对于没有接触过编程或者编辑配置文件的用户来说可能会有些难用，于是建议可以在启用腾讯翻译君并配置好密钥之后自动给配置文件的对应字段区域添加以下字段：（我手动添加之后复制出来的）
```json
"tencent": {
      "limit": 5,
      "maxTextLengthPerRequest": 2000
    },
```
腾讯翻译君的api里面写了翻译请求的限制是每秒5次，每次不超过2000字符（含汉字、字母、标点）。没有跟客服拉扯过的基本上就是默认限制，于是可认为是通用限制。

### 补充说明 | Additional context

[机器翻译 请求限制-文档中心-腾讯云](https://cloud.tencent.com/document/product/551/32572)

**Comment by theowenyoung** [comment]
默认的腾讯翻译君配置是： limit: 3,  最大字数:1800

我们实际测试发现腾讯翻译君的API 在配置为 5 的时候，在大量请求下会提示频率超出限制，比如翻译电子书。

> 建议可以在启用腾讯翻译君并配置好密钥之后自动给配置文件的对应字段区域添加以下字段

确实如果有默认配置的直观展示对需要高级配置的用户更友好，但是如果直接放在目前的用户配置中的话，程序后续无法区分用户是否手动改过默认配置。并且部分默认配置会根据不同情况动态处理，无法给一个默认的静态值。 我目前看到的最好做法是 Firefox 的 about:config 的设计，每个选项都是一个独立的 key value, 并且可以搜索，对普通用户也算是很友好。

**Comment by lingfengyu-dreaming** [comment]
感谢回复，默认配置下初次翻译时确实会出现超出限制问题，原因未知，重试就不会了，所以我才会去看文档






---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月26日(周一) 凌晨3:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [immersive-translate/immersive-translate] 腾讯翻译君默认请求限制 (Issue #2043)




 
默认的腾讯翻译君配置是： limit: 3,  最大字数:1800
 
我们实际测试发现腾讯翻译君的API 在配置为 5 的时候，在大量请求下会提示频率超出限制，比如翻译电子书。
  
建议可以在启用腾讯翻译君并配置好密钥之后自动给配置文件的对应字段区域添加以下字段
  
确实如果有默认配置的直观展示对需要高级配置的用户更友好，但是如果直接放在目前的用户配置中的话，程序后续无法区分用户是否手动改过默认配置。并且部分默认配置会根据不同情况动态处理，无法给一个默认的静态值。 我目前看到的最好做法是 Firefox 的 about:config 的设计，每个选项都是一个独立的 key value, 并且可以搜索，对普通用户也算是很友好。
