### ISSUE TITLE
github浏览文件时，文件名出现了不应该有的翻译

### ISSUE THREAD

**Issue by screw-hand** [immersive-translate/immersive-translate#2046]
### 您希望的更新和改进是什么 | Update or Improve

https://github.com/immersive-translate/immersive-translate/blob/main/README_english.md
<img width="1155" alt="image" src="https://github.com/user-attachments/assets/252f86d5-75ff-4eb9-867a-bd5a5b0fa77c">

如图，截图中标记处应该是不用翻译的，使用openai的时候会，没有调整过prompt，AI专家“github翻译增强器” / “通用”都是如上图所示。

### 补充说明 | Additional context

翻译完整内容如下：
```
 项目名称 这是一个示例项目，用于展示如何使用 GitHub。 ## 安装 要安装此项目，请运行以下命令： ```bash git clone https://github.com/username/repo.git ``` ## 使用 使用以下命令启动项目： ```bash npm start ``` ## 贡献 欢迎贡献！请查看 [贡献指南](CONTRIBUTING.md) 以获取更多信息。 ## 许可证 此项目采用 MIT 许可证。有关详细信息，请参阅 [LICENSE](LICENSE) 文件。
 ```

**Comment by keyboard3** [comment]
已排除这块区域的翻译，打开[这里](https://dash.immersivetranslate.com/#about)会自动更新规则，然后刷新重试下
