### ISSUE TITLE
希望在翻译引擎中增加通义千问的Api使用

### ISSUE THREAD

**Issue by SaltyFishOTL** [immersive-translate/immersive-translate#2048]
### 您希望的更新和改进是什么 | Update or Improve

经过实测，通义千问的Max模型目前翻译质量远超OpenAI，与Claude3.5相当，且更具性价比一些。因此，希望在可选地翻译引擎中加入使用通义千问的选项。

**Comment by lingfengyu-dreaming** [comment]
还真有api，链接如下[如何使用通义千问API](https://help.aliyun.com/zh/dashscope/developer-reference/use-qwen-by-api)
下次可以在补充说明贴链接

**Comment by theowenyoung** [comment]
![CleanShot 2024-08-30 at 14 47 05@2x](https://github.com/user-attachments/assets/0cea8170-da3b-441e-a1bc-b23bb78007d1)

选择这个即可。
