### ISSUE TITLE
希望增加对warpcast.com的支持

### ISSUE THREAD

**Issue by xiebangrong** [immersive-translate/immersive-translate#2051]
### 您希望的更新和改进是什么 | Update or Improve

warpcast.com已经是很热门的新型社交网站，希望支持自动匹配。

**Comment by keyboard3** [comment]
你翻译完之后，然后点击悬浮球旁边的反馈按钮反馈一下

**Comment by keyboard3** [comment]
暂无反馈关闭此issue
