### ISSUE TITLE
[Bug]: 冠词翻译问题

### ISSUE THREAD

**Issue by sino1641** [immersive-translate/immersive-translate#2054]
### 插件版本号 | Version

1.8.3

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

最近发现使用本插件无法翻译冠词：
例如：
维基的文段
`
"The quick brown fox jumps over the lazy dog" is an English-language pangram – a sentence that contains all the letters of the alphabet. The phrase is commonly used for touch-typing practice, testing typewriters and computer keyboards, displaying examples of fonts, and other applications involving text where the use of all letters in the alphabet is desired.
`
会被翻译成：
<img width="914" alt="Snipaste_2024-08-27_19-38-46" src="https://github.com/user-attachments/assets/d7aec7d3-b7a1-496e-9600-a16b1aca6dbb">
使用百度、谷歌等网页服务可以正常翻译：
<img width="688" alt="百度" src="https://github.com/user-attachments/assets/b6fa51f3-bbd4-4031-894b-6e57cb528d7b">
<img width="848" alt="微软" src="https://github.com/user-attachments/assets/9ed4be94-140a-4c53-8d04-3ad4f9741900">
<img width="958" alt="谷歌" src="https://github.com/user-attachments/assets/bb77bb20-8047-4a30-be28-f7b76503a4bd">

### 出现问题的网址 | URL

any

**Comment by keyboard3** [comment]
插件不会干预翻译服务给的结果

**Comment by sino1641** [comment]
以百度翻译为例，
使用官方的api python demo：
https://fanyi-api.baidu.com/doc/21
https://fanyiapp.cdn.bcebos.com/api%2Fdemo%2FBaidu_Text_transAPI.rar

对以上文段执行的翻译结果是：
```json
"trans_result": [
        {
            "src": "\"The quick brown fox jumps over the lazy dog\" is an English-language pangram – a sentence that contains all the letters of the alphabet. The phrase is commonly used for touch-typing practice, testing typewriters and computer keyboards, displaying examples of fonts, and other applications involving text where the use of all letters in the alphabet is desired.",
            "dst": "“快速的棕色狐狸跳过懒惰的狗”是一个英语的pangram——一个包含字母表中所有字母的句子。该短语通常用于触摸打字练习、测试打字机和计算机键盘、显示字体示例以及其他涉及文本的应用程序，其中需要使用字母表中的所有字母 。"
        }
    ]
```
其中冠词可以正常翻译成 `一个`

@keyboard3 麻烦您再看看，在插件和翻译服务之间是否有其他中间层可能会产生影响？

**Comment by keyboard3** [comment]
<img width="1210" alt="image" src="https://github.com/user-attachments/assets/eba1cc31-8864-4dfd-b768-73fded86ca7f">
检查下你是否在高级设置中添加了某些单词不翻译。我这边都正常翻译

**Comment by sino1641** [comment]
嗯嗯感谢！
重置貌似好了，
可能是与高级设置里 `以下单词保持原文，不要翻译` 的功能有冲突。
