### ISSUE TITLE
右键翻译逻辑异常

### ISSUE THREAD

**Issue by wx-11** [immersive-translate/immersive-translate#2055]
### 您希望的更新和改进是什么 | Update or Improve

在我右键网页翻译时 会自动把网页变成以后都自动翻译 而我只是想临时翻译一下 这个体验很差 每次翻译后需要关闭自动翻译 本来右键就是为了不点进设置里快速翻译 希望可以改进

**Comment by theowenyoung** [comment]
无法复现，可以在设置页面看下是否设置过 总是翻译的语言 或者 总是翻译的网址
