### ISSUE TITLE
[Bug]: 希望不要翻译论文表格内的字段值

### ISSUE THREAD

**Issue by zhufeizzz** [immersive-translate/immersive-translate#2056]
### 插件版本号 | Version

1.8.3

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

论文表格里面的短字段也被翻译了，而且我明明设置了50字符才翻译，也没有生效

![image](https://github.com/user-attachments/assets/2ae96944-6c13-4a76-ad5d-6c0c7d2c4575)

![image](https://github.com/user-attachments/assets/bc9b1cf9-2fbf-4ed8-b26d-e03df0800776)

### 出现问题的网址 | URL

https://ar5iv.labs.arxiv.org/html/2302.04166?_immersive_translate_auto_translate=1

**Comment by keyboard3** [comment]
是生效的，不过目前是拿富文本长度来判断的。下一版本将用实际的纯文本内容判断

**Comment by keyboard3** [comment]
1.9.1 已支持
