### ISSUE TITLE
[Bug]: 油猴 Youtube 输入框增强失效

### ISSUE THREAD

**Issue by ikali** [immersive-translate/immersive-translate#2060]
### 插件版本号 | Version

1.8.3

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome, Other

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

油猴版 Youtube 输入框增强失效，而在其他页面如 google 等均正常使用。此情况在多月前已然出现，清理缓存与重置设置均告无效。
ps 没使用扩展版测试该功能是否正常。

### 出现问题的网址 | URL

https://www.youtube.com

**Comment by theowenyoung** [comment]
感谢反馈，1.8.4 版本已修复，请升级新版本。
