### ISSUE TITLE
[Bug]: macOS  Safari浏览器上 鼠标悬停翻译经常失效

### ISSUE THREAD

**Issue by Wakagixsx** [immersive-translate/immersive-translate#2061]
### 插件版本号 | Version

V1.8.3

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

macOS  Safari浏览器上 鼠标悬停翻译经常失效

### 出现问题的网址 | URL

https://ideogram.ai

**Comment by keyboard3** [comment]
没能复现这个问题，只有这个网址？点击悬浮球翻译呢？

**Comment by keyboard3** [comment]
暂无反馈 关闭此issue
