### ISSUE TITLE
希望增加不同网站设置默认翻译服务的功能

### ISSUE THREAD

**Issue by lavender010101** [immersive-translate/immersive-translate#2065]
### 您希望的更新和改进是什么 | Update or Improve

希望能够想 SwitchyOmega 那样增加不同网页选择不同翻译服务的功能，有看到AI专家可以匹配不同的网站，希望翻译服务级别也能有类似的切换功能

**Comment by flamintune** [comment]
这个功能是支持的但是需要去配置，可以看下官方的文档教程
https://immersivetranslate.com/zh-Hans/docs/advanced/#%E5%A6%82%E4%BD%95%E8%AE%A9%E4%B8%8D%E5%90%8C%E7%9A%84%E7%AB%99%E7%82%B9%E9%BB%98%E8%AE%A4%E9%80%89%E6%8B%A9%E4%B8%8D%E5%90%8C%E7%9A%84%E7%BF%BB%E8%AF%91%E6%9C%8D%E5%8A%A1%E4%BE%8B%E5%A6%82%E6%9C%89%E7%9A%84%E7%BD%91%E7%AB%99%E6%88%91%E6%83%B3%E8%A6%81%E5%A5%BD%E4%B8%80%E7%82%B9%E4%BD%86%E8%A6%81%E8%8A%B1%E9%92%B1%E7%9A%84%E7%BF%BB%E8%AF%91%E6%95%88%E6%9E%9C%E6%9C%89%E7%9A%84%E7%BD%91%E7%AB%99%E6%88%91%E5%8F%AA%E9%9C%80%E8%A6%81%E5%85%8D%E8%B4%B9%E8%83%BD%E7%9C%8B%E7%9A%84%E7%BF%BB%E8%AF%91%E5%B0%B1%E8%A1%8C%E4%BA%86

**Comment by actforjason** [comment]
@flamintune 其中的translationServices不支持阿里百炼大模型吗
