### ISSUE TITLE
[Bug]: 设置的操作是自动检测语言，翻译为中文。点击翻译后，自动将当前带有表格的网页语言检测为中文，然后呢对表格中的数据有些英文翻译为了中文，有些未进行翻译，所以我理解有两个问题，一是检测的语言类型错误，二是翻译的内容没有保持统一性，没有将所有的英文字段翻译出来

### ISSUE THREAD

**Issue by zhang-xianhong** [immersive-translate/immersive-translate#2067]
### 插件版本号 | Version

1.8.3

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome, Safari, Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

设置的操作是自动检测语言，翻译为中文。点击翻译后，自动将当前带有表格的网页语言检测为中文，然后呢对表格中的数据有些英文翻译为了中文，有些未进行翻译，所以我理解有两个问题，一是检测的语言类型错误，二是翻译的内容没有保持统一性，没有将所有的英文字段翻译出来
操作步骤：
设置自动检测语言：https://img.ltwebstatic.com/images3_ccc/2024/09/01/00/1725188021c77493622abe64dc6b74f84d55a27431.png
点击翻译后，表格中某些行翻译为了中文，某些未进行成功翻译：https://img.ltwebstatic.com/images3_ccc/2024/09/01/2d/17251881223abb2e07b52c55a5698a5785cb537174.png
这个时候再打开查看沉浸式翻译插件的设置，显示的自动检测语言是中文：https://img.ltwebstatic.com/images3_ccc/2024/09/01/a6/1725188249b285e91abaa09d59a560ebcfa7a44fc6.png

### 出现问题的网址 | URL

带有表格的网页，表格中的某一列全部展示的是其他语言类型

**Comment by keyboard3** [comment]
中英混杂的页面，你需要手动指定下源语言，有些短词浏览器是检测不出语言的

**Comment by zhang-xianhong** [comment]
即便是浏览器检测不出语言，那为什么有些能够翻译出来呢，请问下这个是什么原理呢？这种情况是必须手动指定为英语转中文吗？

**Comment by keyboard3** [comment]
检测不出语言的内容就会以页面检测语言为准。你中英混杂页面识别的页面语言是中文。当源语言和目标语言一致就不会触发翻译

**Comment by zhang-xianhong** [comment]
那意思是自动检测语言，这个行为是浏览器触发检测的吗？以它的检测为准？那当我页面中有中英文，另外还有巴西、葡萄牙等语言，这种情况下，我个人是期望能自动检测每一项语言，然后翻译为中文的。如果我指定了源语言为英语，那其他语言也无法正确翻译过来吧？有没有什么好的解决方案呢？

**Comment by keyboard3** [comment]
> 那意思是自动检测语言，这个行为是浏览器触发检测的吗？以它的检测为准？那当我页面中有中英文，另外还有巴西、葡萄牙等语言，这种情况下，我个人是期望能自动检测每一项语言，然后翻译为中文的。如果我指定了源语言为英语，那其他语言也无法正确翻译过来吧？有没有什么好的解决方案呢？

每一项都会单独检测，浏览器的语言检测针对短字符也是无法正确检测出语言，长内容是能够检测出来。检测不出来的语言会以页面语言为准

**Comment by zhang-xianhong** [comment]
> > 那意思是自动检测语言，这个行为是浏览器触发检测的吗？以它的检测为准？那当我页面中有中英文，另外还有巴西、葡萄牙等语言，这种情况下，我个人是期望能自动检测每一项语言，然后翻译为中文的。如果我指定了源语言为英语，那其他语言也无法正确翻译过来吧？有没有什么好的解决方案呢？
> 
> 每一项都会单独检测，浏览器的语言检测针对短字符也是无法正确检测出语言，长内容是能够检测出来。检测不出来的语言会以页面语言为准

那如果当前界面有中文、英文、葡萄牙语言，都想翻译为中文，那这样有好的方式推荐吗？个人是期望检测到什么语言就翻译该语言为中文这样，如果设定了源语言为英文，那么其他语言应该不会进行翻译了吧

**Comment by keyboard3** [comment]
你可以使用大模型翻译服务，AI类型翻译服务不会指定源语言
