### ISSUE TITLE
希望加入智谱API

### ISSUE THREAD

**Issue by x18-1** [immersive-translate/immersive-translate#2068]
### 您希望的更新和改进是什么 | Update or Improve

在 #1368我看到了你们有关智谱API的测试，但现在智谱API强大且免费，希望可以加入。可以用做专门翻译文献的API（比如计算机方向）

**Comment by BiFangKNT** [comment]
同求。不过现阶段也可以暂时手动添加，即使下方的Prompt部分维持默认的不改，也能获得不错的翻译效果。

翻译服务底部点击“添加兼容 OpenAI 接口的自定义 AI 翻译服务？”
![image](https://github.com/user-attachments/assets/a252f938-5106-484c-ada9-1f6a1ab2e8dd)

接口地址在官方文档中可以找到：[官方文档](https://open.bigmodel.cn/dev/api#language)
![image](https://github.com/user-attachments/assets/75861bda-c238-49ab-bbe3-a46505475472)
![image](https://github.com/user-attachments/assets/e80a52a1-bc0e-41db-8cd8-daf0594ea762)

模型列表往下拉选择“设置更多模型”，按要求写上就行了
![image](https://github.com/user-attachments/assets/10823e30-7d72-4743-9810-45f95621e6ec)

每秒最大请求数建议设置为5，因为免费用户的4plus限速为5，也足够快了

**Comment by BiFangKNT** [comment]
在1.9.1版本似乎失效了，返回“400: {"error":{"code":"1210","message":"API 调用参数有误，请检查文档。"}}”

**Comment by BiFangKNT** [comment]
> 在1.9.1版本似乎失效了，返回“400: {"error":{"code":"1210","message":"API 调用参数有误，请检查文档。"}}”

没事了，温度不能超过1，而在deepseek里是可以的，我没认真看文档

**Comment by theowenyoung** [comment]
预计会在接下来的几周支持智谱API

**Comment by crysishacker** [comment]
国产大模型碰到敏感词会怎么做？我很担忧这个啊

**Comment by BiFangKNT** [comment]
> 国产大模型碰到敏感词会怎么做？我很担忧这个啊

只能尝试用prompt去催眠。像glm4plus的审核就不严格，不手动设置，用扩展默认的也能翻译敏感词，就是话有点多
![image](https://github.com/user-attachments/assets/90f01b8e-ee38-4579-9601-a926098345fc)

**Comment by BiFangKNT** [comment]
> 预计会在接下来的几周支持智谱API

非常好更新，使我浏览器旋转👍

**Comment by theowenyoung** [comment]
> 国产大模型碰到敏感词会怎么做？我很担忧这个啊

目前fallback 到 微软翻译。

**Comment by theowenyoung** [comment]
已默认支持智谱翻译。
