### ISSUE TITLE
[Bug]: 输入框增强功能，使用openai翻译时，翻译结果没有空格

### ISSUE THREAD

**Issue by arshcaria** [immersive-translate/immersive-translate#2069]
### 插件版本号 | Version

1.8.4

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

输入框增强功能，使用openai翻译时，翻译结果没有空格。使用微软或者谷歌翻译，结果正常（有空格）。

中文：

![image](https://github.com/user-attachments/assets/f283c58e-04e3-4e7a-a92c-b54b097831cf)

OpenAI翻译英文（异常，没有空格）：

![image](https://github.com/user-attachments/assets/45d28286-a0af-4034-8b6a-1db265e694ea)

微软翻译英文（正常，有空格）：

![image](https://github.com/user-attachments/assets/2cd99c2c-8929-4687-a4fb-6163bb7724c8)

### 出现问题的网址 | URL

www.google.com

### 重现步骤 | To Reproduce

1. 插件设置为openai翻译
2. 启用输入框增强
3. 在google搜索页或其他有输入框的页面，连按三次空格进行输入框增强翻译
4. 观察翻译结果，发现结果中没有空格

**Comment by theowenyoung** [comment]
无法复现，可以在 https://app.immersivetranslate.com/text#zh-CN/en/%E5%A2%9E%E5%BC%BA%E5%AD%A6%E4%B9%A0%E7%AE%97%E6%B3%95 测试下翻译结果是否正常吗？

**Comment by arshcaria** [comment]
可能是使用的中转API或者官方api在当时临时有问题。后来确实无法复现了。
