### ISSUE TITLE
[功能建议]希望可以增加类似谷歌浏览器自带的覆盖式译文显示样式

### ISSUE THREAD

**Issue by Huaxidesu** [immersive-translate/immersive-translate#207]
如图，原文译文同时存在会导致很多网页排版错误，故希望增加覆盖原文的译文显示样式
<img width="960" alt="image" src="https://user-images.githubusercontent.com/45794248/223187176-0a4f4332-922b-4b95-8547-9c092aecb225.png">
<img width="690" alt="image" src="https://user-images.githubusercontent.com/45794248/223187239-3d7b3ace-f019-4cd6-a0dc-0f2d97d2a226.png">
最后一张图是谷歌翻译版本的
<img width="956" alt="image" src="https://user-images.githubusercontent.com/45794248/223188060-cf2c6df1-fee9-4093-a73c-1ac3ebc10ebf.png">

**Comment by Axlax336** [comment]
这种情况，应该可以直接使用google翻译，无需沉浸式翻译了。

**Comment by Huaxidesu** [comment]
> 这种情况，应该可以直接使用google翻译，无需沉浸式翻译了。

事实上只是想用其他翻译平台的服务实现网页翻译，顺带一提国内直接用谷歌翻译如果改hosts的话只能用几天，接下来还需要继续改，比较麻烦

**Comment by XiaoYingYo** [comment]
加急 @theowenyoung

**Comment by varwav** [comment]
附议

**Comment by versun** [comment]
0.5.7版本已添加该功能, 火狐浏览器已上架更新, 其他平台的还在审核
点击[更多] -> [切换为仅显示译文]
