### ISSUE TITLE
Improve reading local e-books

### ISSUE THREAD

**Issue by ankb90** [immersive-translate/immersive-translate#2070]
### 您希望的更新和改进是什么 | Update or Improve

Please add the following features for reading local e-books:

1. Allow choosing a light or dark theme instead of following the system setting.
2. Allow changing the font size.
3. Save the reading progress (current page) of an e-book so that it doesn't reload from the beginning the next time.
4. Add an option to display text full screen width (instead of leaving margins on both sides).
![Screenshot 2024-09-03 at 11 50 52](https://github.com/user-attachments/assets/063501de-00d7-4d8b-b3e9-de91edc16337)

**Comment by theowenyoung** [comment]
Thanks for your suggestion, optimizing the interface for reading eBooks is not a high priority in our roadmap at the moment, you can just translate ePub file and read it on your favorite reader.

**Comment by ankb90** [comment]
Thanks for the feedback. I will close this ticket. I hope the team will improve the Reader at some point.
