### ISSUE TITLE
希望添加字幕默认高度选项

### ISSUE THREAD

**Issue by huaodehao** [immersive-translate/immersive-translate#2072]
### 您希望的更新和改进是什么 | Update or Improve

默认字幕总是在最底部，实际看各种电视剧电影会发现字幕总是离底部有一段距离的高度上，有高度选项就不用每个视频手动调高了

**Comment by theowenyoung** [comment]
最新版本已经默认会记住你的调整，直接拖动，后续会记住当前网站的字幕位置。
