### ISSUE TITLE
[Bug]: 使用youtube时，如果开启沉浸式翻译会出现乱码的情况

### ISSUE THREAD

**Issue by rookkkie** [immersive-translate/immersive-translate#2073]
### 插件版本号 | Version

1.8.3

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![1725453944414](https://github.com/user-attachments/assets/9e3d601a-95b5-443f-83e9-ba9ece9348f3)
一旦打开沉浸式翻译youtube视频或者直播界面就会出现这种情况，尚不清楚是不是和youtube弹幕插件相冲突

### 出现问题的网址 | URL

https://www.youtube.com

### 重现步骤 | To Reproduce

1.打开沉浸式翻译，默认翻译youtube视频或者直播界面 2.进入youtube视频或者直播界面

**Comment by theowenyoung** [comment]
你可以测试只开启沉浸式翻译插件，看下是否会出现这个。

**Comment by rookkkie** [comment]
> 你可以测试只开启沉浸式翻译插件，看下是否会出现这个。

我测试了一下，就是和另一款插件https://github.com/ys-j/YoutubeLiveChatFlusher?tab=readme-ov-file
冲突了，只要不开这个弹幕插件，就不会出现乱码
