### ISSUE TITLE
[Bug]: 对华尔街日报英文版翻译出问题

### ISSUE THREAD

**Issue by greyczj** [immersive-translate/immersive-translate#2074]
### 插件版本号 | Version

1.9.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

无论翻译服务改成谷歌还是微软，翻译华尔街日报英文版网页时只会翻译一部分，其他地方会转圈圈，换节点也没用，其他网站正常

### 出现问题的网址 | URL

https://www.wsj.com/

### 重现步骤 | To Reproduce

1.打开华尔街日报英文版首页或进入任一文章
2.Alt+A
3.无法完全翻译网页，转圈圈

**Comment by greyczj** [comment]
> 转圈圈结束之后呢？ 有显示错误原因吗？
> 
> 理论上转圈圈不翻译的话，应该是翻译服务没有响应。

现在恢复正常了，之前连续两三天这样，因为更换成微软翻译也出问题，其他网站翻译正常，才觉得奇怪，不知道恢复是不是暂时的

**Comment by theowenyoung** [comment]
好的，如果有问题请再次打开此issue
