### ISSUE TITLE
鼠标悬浮停留能不能增加一个 不是翻译段落，只翻译单词的选项？

### ISSUE THREAD

**Issue by lucykwok** [immersive-translate/immersive-translate#2075]
### 您希望的更新和改进是什么 | Update or Improve

rt, 感觉这个功能跟文本翻译有点重复，有时候只想看单独单词的解释。 或者可以增加不同快捷键来区分是翻译整段还是只翻译悬浮的单个单词？

另外遇到一个问题，为什么在reddit 输入栏空格三下后文本自动转英文，会出现两段一模一样的单词或句子。 比如：猪  pigpig  ； 非常好 very goodvery good ，其他网站不会。

**Comment by theowenyoung** [comment]
> rt, 感觉这个功能跟文本翻译有点重复，有时候只想看单独单词的解释。 或者可以增加不同快捷键来区分是翻译整段还是只翻译悬浮的单个单词？

目前只有选中文本之后，右键翻译某个单词的功能，未来如果添加单词翻译的话，会考虑支持。


> 另外遇到一个问题，为什么在reddit 输入栏空格三下后文本自动转英文，会出现两段一模一样的单词或句子。 比如：猪 pigpig ； 非常好 very goodvery good ，其他网站不会。

请问具体是哪个网页会有这个问题，我测试了一个帖子回复是正常的。

**Comment by lucykwok** [comment]
> > rt, 感觉这个功能跟文本翻译有点重复，有时候只想看单独单词的解释。 或者可以增加不同快捷键来区分是翻译整段还是只翻译悬浮的单个单词？
> 
> 目前只有选中文本之后，右键翻译某个单词的功能，未来如果添加单词翻译的话，会考虑支持。
> 
> > 另外遇到一个问题，为什么在reddit 输入栏空格三下后文本自动转英文，会出现两段一模一样的单词或句子。 比如：猪 pigpig ； 非常好 very goodvery good ，其他网站不会。
> 
> 请问具体是哪个网页会有这个问题，我测试了一个帖子回复是正常的。

每个页面都这样！

**Comment by keyboard3** [comment]
reddit 页面最新版未复现，暂时关闭此issue
