### ISSUE TITLE
可不可以给改进一下啊，应该不麻烦，前面已经提过了

### ISSUE THREAD

**Issue by Negaentropy** [immersive-translate/immersive-translate#2076]
### 您希望的更新和改进是什么 | Update or Improve

希望在浏览器的阅读模式，也能够对选中的文本通过右键菜单项进行翻译。其他翻译插件，如Depth Translator for DeepL，Edge Translate等，都是可以在阅读模式下将划选的句子传递给插件，并弹出一个页面进行翻译。浏览器阅读模式下选中翻译的需求更大。以下图片就是例子：
![image](https://github.com/user-attachments/assets/4c72a5d0-ca0e-4e31-93b2-1d803d925372)
![image](https://github.com/user-attachments/assets/c259bd28-282a-4a98-aa2c-62355cf32e00)

**Comment by keyboard3** [comment]
#https://github.com/immersive-translate/immersive-translate/issues/2037
问题重复
