### ISSUE TITLE
[Bug]: 使用SiliconCloud作为翻译引擎时，报错无法访问。代理是开启的，SiliconCloud官网访问也无问题。

### ISSUE THREAD

**Issue by deepfree2023** [immersive-translate/immersive-translate#2080]
### 插件版本号 | Version

1.9.3

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

您当前所使用的 [SiliconCloud] 服务因网络连接或服务提供商的问题暂时无法访问。建议您尝试刷新页面或通过[设置](https://dash.immersivetranslate.com/#general)更换其他翻译服务。若您是[Pro会员](https://immersivetranslate.com/pricing/?utm_source=extension&utm_medium=webpage&utm_campaign=service_error)，可以选择使用更为稳定的 DeepL, OpenAI, Claude 或 Gemini 翻译服务（[点此免费体验](https://immersivetranslate.com/pricing/?utm_source=extension&utm_medium=webpage&utm_campaign=service_error)）。 另外，您也可能需要检查您的网络或代理设置。

错误原因：Failed to fetch

### 重现步骤 | To Reproduce

基本设置，点此测试服务

**Comment by theowenyoung** [comment]
是否尝试过 关闭代理？

**Comment by deepfree2023** [comment]
关闭代理报同样的错误。使用其他工具开代理调用SiliconCloud的api是没问题的。

**Comment by theowenyoung** [comment]
使用的是默认的 SiliconCloud 服务吗？是Chrome插件版本最新版吗？

**Comment by deepfree2023** [comment]
是默认的 SiliconCloud 服务，是Chrome插件版本最新版1.9.3

**Comment by theowenyoung** [comment]
你测试是否可以在浏览器中访问：

https://api2.immersivetranslate.com/

https://api.siliconflow.cn

正常的话，会显示 404

**Comment by deepfree2023** [comment]
分别显示：
{"message": "not found"}
404 page not found

**Comment by deepfree2023** [comment]
点此测试服务还是一样报错

**Comment by deepfree2023** [comment]
![image](https://github.com/user-attachments/assets/fc022f70-9849-485c-babe-f3f52133ba49)

**Comment by theowenyoung** [comment]
要不要试下卸载重装？ 您可以先保存下您的设置。

我这边测试一切正常。。

**Comment by deepfree2023** [comment]
重装确实可以了，多谢！
