### ISSUE TITLE
[Bug]: Pro版本的pdf翻译，原文部分在页面中间产生了样式变化，出现了删除线

### ISSUE THREAD

**Issue by jacintagu** [immersive-translate/immersive-translate#2081]
### 插件版本号 | Version

1.9.3

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

Pro版本的pdf翻译，原文部分在页面中间产生了样式变化，出现了删除线
译文显示模式：双语对照，跟随系统。

![image](https://github.com/user-attachments/assets/02362667-27ea-4cd5-b084-dcfd6adff058)

### 出现问题的网址 | URL

https://arxiv.org/pdf/2408.02215

### 补充说明 | Additional context

https://readit.plus/a/vPRzF/08c01e57-3333-4cf8-b3dc-e710d83cd065
这个是翻译后的分享页面

**Comment by TaoLoading** [comment]
您好，我使用了您的文件确实复现了这个问题，当前临时的解决办法需要您手动修改下 html 标签。我们会在这个 bug 修复后再此 issue 回复您

**Comment by TaoLoading** [comment]
问题已修复
