### ISSUE TITLE
如何才能在不用梯子的情况用谷歌微软翻译？？

### ISSUE THREAD

**Issue by LessenX** [immersive-translate/immersive-translate#2083]
### 您希望的更新和改进是什么 | Update or Improve

我不用梯子的时候，谷歌翻译是100%报错网络连接问题，微软是有可能一段时间过后会显示网络连接无法翻译，这个是可以解决的吗？还是我使用有错误？

**Comment by theowenyoung** [comment]
您可能需要在代理规则里添加谷歌翻译的域名： https://immersivetranslate.com/zh-Hans/docs/faq/#9-%E8%B0%B7%E6%AD%8C%E7%BF%BB%E8%AF%91%E6%8E%A5%E5%8F%A3%E8%A2%AB%E5%A2%99%E9%97%AE%E9%A2%98

微软的网络问题可能也需要用类似的方式解决。


或者您也可以使用会员服务提供的稳定翻译服务如 DeepL 和 OpenAI.

**Comment by LessenX** [comment]
> 您可能需要在代理规则里添加谷歌翻译的域名： https://immersivetranslate.com/zh-Hans/docs/faq/#9-%E8%B0%B7%E6%AD%8C%E7%BF%BB%E8%AF%91%E6%8E%A5%E5%8F%A3%E8%A2%AB%E5%A2%99%E9%97%AE%E9%A2%98
> 
> 微软的网络问题可能也需要用类似的方式解决。
> 
> 或者您也可以使用会员服务提供的稳定翻译服务如 DeepL 和 OpenAI.

我没太懂？如果使用代理规则，比如说我在clash里面使用谷歌翻译api的代理规则，那不也是需要一直启动clash才能使用谷歌翻译吗？那和直接开启梯子有区别吗？

**Comment by theowenyoung** [comment]
是的，必须要开代理。我只是提醒 可以只为 这个域名设置代理，如果你不想让其他的域名也走代理的话。
