### ISSUE TITLE
[Bug]: 无法使用开发者设置翻译行内tag

### ISSUE THREAD

**Issue by timelic** [immersive-translate/immersive-translate#2085]
### 插件版本号 | Version

1.9.3

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在该示例网址上，我想将行内的数学公式<d-math>保持原样，但是似乎无法做到。

尝试过的代码

```json
{
    "matches": "tridao.me",
    "excludeSelectors": [
      "d-math"
    ],
    "stayOriginalSelectors": [
      "d-math"
    ],
    "stayOriginalTags": [
      "d-math"
    ],
    "additionalSelectors": [
      "d-math"
    ]
  }
```

### 出现问题的网址 | URL

https://tridao.me/blog/2024/mamba2-part2-theory/

**Comment by keyboard3** [comment]
![image](https://github.com/user-attachments/assets/ae06f6c3-9989-403c-9e08-5be4dea22481)
已重新适配，打开 https://dash.immersivetranslate.com/#about 会自动更新规则，然后重试下

**Comment by timelic** [comment]
@keyboard3 非常感谢你的帮助！这确实解决了我的问题。

除此之外，我想问个问题，就是我用nougat将pdf转为html之后尝试使用沉浸式翻译进行翻译。我不想翻译行内公式，所以我写了用户脚本：

```json
[
  {
    "atomicBlockSelectors": [
      ".math-inline"
    ],
    "excludeSelectors": [
      ".math-inline ",
      ".table"
    ],
    "matches": "localhost:2734"
  }
]
```

它在以前的插件版本是可用的：

<img width="1372" alt="截屏2024-09-09 16 26 32" src="https://github.com/user-attachments/assets/720f460b-861c-4068-b696-37c762cd0da5">

但是在最新版本不可用了，行内公式不会保留原样，table这种block倒是没问题。（我不确定这个问题具体在哪个版本出现的）

<img width="1161" alt="截屏2024-09-09 16 30 16" src="https://github.com/user-attachments/assets/bb1e31de-d929-4edd-87d6-e07b68f7c967">

想问下这是bug吗？还是我使用不当呢。
很抱歉测试网址我没法给出，因为这是部署在我本地上的。但是你们官方的pro版pdf我想也是类似我这样做的吧，所以我想还是有借鉴意义的。

**Comment by keyboard3** [comment]
没事你可以点击悬浮球旁边的反馈，我就可以看到了。现在是富文本翻译，以前是纯文本翻译，可能是这个差异

**Comment by keyboard3** [comment]
反馈的时候邮箱和理由记得加上

**Comment by timelic** [comment]
明白，我待会反馈一下。非常感谢！

> 没事你可以点击悬浮球旁边的反馈，我就可以看到了。现在是富文本翻译，以前是纯文本翻译，可能是这个差异

**Comment by timelic** [comment]
已提交反馈。

**Comment by keyboard3** [comment]
![image](https://github.com/user-attachments/assets/cbae0e7f-2d99-42c8-8b0c-243907f022b6)
好了 再试下

**Comment by timelic** [comment]
> ![image](https://private-user-images.githubusercontent.com/13177744/365588812-cbae0e7f-2d99-42c8-8b0c-243907f022b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4ODkyODEsIm5iZiI6MTcyNTg4ODk4MSwicGF0aCI6Ii8xMzE3Nzc0NC8zNjU1ODg4MTItY2JhZTBlN2YtMmQ5OS00MmM4LThiMGMtMjQzOTA3ZjAyMmI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDEzMzYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlMTIwZDUxNTJmM2I0MGFhOGQ4ODY3ZmIxOTU2NzU0NzQ1NWUxM2ExZTFjM2NmYmY4NjBjMmI4Zjk5NDVhZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YC1Hx_sdUaV2vutNh-2HUInuHRzpUgdVJl1Gfiotji4) 好了 再试下

非常感谢🙏，这真的帮了我很大的忙
