### ISSUE TITLE
[Bug]: 推特（twitter x.com）开启双语显示，翻译后的内容显示不完全

### ISSUE THREAD

**Issue by corwin1949** [immersive-translate/immersive-translate#2086]
### 插件版本号 | Version

V1.9.3

### 平台 | Platform

Windows

### 浏览器 | Browsers

Other

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/user-attachments/assets/a4ee4294-6158-4528-9687-9f2ba45643f8)

### 出现问题的网址 | URL

https://x.com/StephenKing/status/1833136252964503634

### 重现步骤 | To Reproduce

https://x.com/yuris/status/1832845593741553833

这个链接也是。

**Comment by corwin1949** [comment]
油猴脚本已关闭

**Comment by theowenyoung** [comment]
无法复现，是否和其他插件冲突？


![CleanShot 2024-09-10 at 00 21 52@2x](https://github.com/user-attachments/assets/b636b786-fbf2-438b-b4cf-c3a94ab3f767)

**Comment by corwin1949** [comment]
@theowenyoung 排查出原因了，因为我在 Edit User Rules 里添加了规则，如何把规则去掉，显示就是你图片里正常的状态。

我的规则是：

```
[
  {
    "excludeSelectors": [
      ".word_card"
    ],
    "matches": "*"
  }
]
```
我用了一个查词典的插件，词典画面出现后，沉浸式会去翻译词典内容；我不需要，所以把词典弹窗排除掉了。
然后导致了这个问题，是我规则没写对吗？

**Comment by theowenyoung** [comment]
* 匹配后，会让默认的规则都失效。 可以改 user config ，这样写：


```
{
  "generalRule": {
       "excludeSelectors.add": [
           ".word_card"
        ]
   }
}

```

**Comment by corwin1949** [comment]
成功了！感谢 @theowenyoung 的帮助。如果有其他人遇到同样的问题，需要排除网页中的部分元素，可以这样写：

```
[
  {
    "generalRule": {
      "excludeSelectors.add": [
        ".word_card"
      ]
    }
  }
]
```
规则最外面是数组，往excludeSelectors.add里面添加选择器。

再次感谢！
