### ISSUE TITLE
[Bug]: 在翻译markdown文件之后，导出的markdown文件把原文件中的html标签全部删除了。

### ISSUE THREAD

**Issue by wooemans** [immersive-translate/immersive-translate#2087]
### 插件版本号 | Version

0.5.5

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在翻译markdown文件之后，导出的markdown文件把原文件中的html标签全部删除了。能否修改一下程序，让它可以把html标签保持原样？

**Comment by TaoLoading** [comment]
能否给示例文件说明下

**Comment by TaoLoading** [comment]
由于 markdown => html => markdown 转换逻辑的需要无法合理的将全部标签保留，而且即使删除了 html 标签如 ul，最终也会展示为 markdown 语法的列表。不过可以对部分需要的标签进行特殊处理，现在补充保留了如下标签，如有其他需要请在此 issue 回复我：["table", "from", "input", "select", "audio", "video", "canvas", "svg"]
