### ISSUE TITLE
[Bug]: PDF翻译中经常有重影问题

### ISSUE THREAD

**Issue by CyrusYin** [immersive-translate/immersive-translate#2088]
### 插件版本号 | Version

1.9.3

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome, Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

我是Pro 用户，翻译一本书的过程中，经常有几段是重影，请问怎么解决？
![image](https://github.com/user-attachments/assets/453defed-01c5-4264-967b-e49da79ea2b0)

**Comment by theowenyoung** [comment]
您好，请问可以重现吗？如果可以的话，请上传一下出现问题的原epub文件，您可以打包为 zip 包在这里上传。
