### ISSUE TITLE
[Bug]: 设置user rules后无法翻译<h1>里的内容

### ISSUE THREAD

**Issue by ysdj** [immersive-translate/immersive-translate#2089]
### 插件版本号 | Version

1.9.3

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

设置User Rules：
`[
  {
    "id": "ncbi",
    "matches": [
      "*ncbi.nlm.nih.gov*"
    ],
    "stayOriginalSelectors": [
      ".doi"
    ]
  }
]`
后，ncbi.nlm.nih.gov网址下的h1标签里的内容无法翻译，如图：

![image](https://github.com/user-attachments/assets/ce82720f-577e-4b80-8849-f28d85df3fcf)

### 出现问题的网址 | URL

https://pubmed.ncbi.nlm.nih.gov/30036453/

**Comment by keyboard3** [comment]
因为插件默认情况下只翻译主要内容，所以会排除一些疑似标题栏的元素，这个h1正好在header标签下。 
可以通过选择翻译全部区域 或者 这么设置

```
[
  {
    "excludeSelectors": [],
    "id": "ncbi",
    "matches": [
      "*ncbi.nlm.nih.gov*"
    ],
    "stayOriginalSelectors": [
      ".doi"
    ]
  }
]
```

**Comment by keyboard3** [comment]
因为这个网站有插件默认设置，允许该元素翻译。 你的配置覆盖了插件的默认设置，你如果想要继承插件的配置 id写成 pubmed.ncbi.nlm.nih.gov

**Comment by keyboard3** [comment]
![image](https://github.com/user-attachments/assets/65342a56-5388-498a-8603-3f529fdf5100)

**Comment by Sinandiao** [comment]
> ![image](https://private-user-images.githubusercontent.com/13177744/366374454-65342a56-5388-498a-8603-3f529fdf5100.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NzkzNDIsIm5iZiI6MTczNDc3OTA0MiwicGF0aCI6Ii8xMzE3Nzc0NC8zNjYzNzQ0NTQtNjUzNDJhNTYtNTM4OC00OThhLTg2MDMtM2Y1MjlmZGY1MTAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDExMDQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwYzg3NmJkNGU0N2Q1YzFmYzEwYWJlODg2MTJmMTNlODBhNjk3YzdlZjdjOTZlZTY0NDYwOWY5NjExNzEyNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UGFc6dsw70FmKTzI0K9EuA11c9qAUiLKof6PAA7pM_k)

我没有设置过user rule 但是现在也翻译不了标题 按照您发的这个配置还是没能解决 求问怎么处理

**Comment by keyboard3** [comment]
@Sinandiao  你说的是哪个站点？
