### ISSUE TITLE
[Bug] OpenAI Bad Request

### ISSUE THREAD

**Issue by iG8R** [immersive-translate/immersive-translate#209]
Hi.
On some sites, I came across the Bad Request issue from Immersive Translate when using OpenAI.
E.g. https://www.ptwxz.com/html/8/8989/5883458.html

<details><summary>Screenshots (Bad Request OpenAI)</summary>

![Immersive-Translate-OpenAI-BadRequest-2023-03-07_004248](https://user-images.githubusercontent.com/11407417/223278891-98420bd9-a0ce-4027-a036-59f5d2a956e8.jpg)

![Immersive-Translate-Options-OpenAI-2023-03-07_004558](https://user-images.githubusercontent.com/11407417/223278905-069657a2-25d7-442f-bd79-81a0ebaa049a.jpg)

</details>

**Comment by theowenyoung** [comment]
Thanks for feedback.

it seems like this request has reached the max token 4096 of openai, so I have changed the max text chars per per request , from 1500 to 1300, it seems ok now, I'll release this on next version.

<img width="1117" alt="截屏2023-03-07 14 32 05" src="https://user-images.githubusercontent.com/62473795/223340063-001f7cce-86b6-4b05-bbad-261f9487267e.png">

**Comment by iG8R** [comment]
It has become much better, but still the issue remains on some pages.
Is there possible to add an option to allow a user to adjust max text chars per request?
E.g.
p561 https://www.ptwxz.com/html/8/8989/5883503.html
p564 https://www.ptwxz.com/html/8/8989/5883506.html
p586 https://www.ptwxz.com/html/8/8989/5883528.html

![Immersive-Translate-BadReq561-2023-03-07_173220](https://user-images.githubusercontent.com/11407417/223486603-7e428f98-297d-4c5a-b6a0-80a850cbb6f7.jpg)
![Immersive-Translate-BadReq564-2023-03-07_173120](https://user-images.githubusercontent.com/11407417/223486624-f65e8398-23ec-4718-a7fe-6807e3ff68b1.jpg)
![Immersive-Translate-BadReq586-2023-03-07_173920](https://user-images.githubusercontent.com/11407417/223486637-77737fd8-e9c2-49e4-a096-6b3be6d64ea0.jpg)

**Comment by theowenyoung** [comment]
Hi, the latest version 0.3.0 has supported to change this option on `Settings` -> `General` -> `OpenAI`.
<img width="1198" alt="截屏2023-03-09 21 42 43" src="https://user-images.githubusercontent.com/62473795/224042230-877787b0-44f1-421d-ab8c-a0358560e831.png">

**Comment by iG8R** [comment]
Thank you so much!
Preliminary, 1100 works the best.

**Comment by iG8R** [comment]
PS. Could you, please, make it possible to select the style of the addon's icon on toolbar? I'm using the dark theme but prefer red icon very much.

**Comment by theowenyoung** [comment]
The dark icon is the new feature today. but for now, it's a static config based addon manifes.json:

```json
  "browser_action": {
    "default_icon": "icons/32.png",
    "default_popup": "popup.html",
    "theme_icons": [{
      "dark": "icons/32.png",
      "light": "icons/dark-32.png",
      "size": 32
    }, {
      "dark": "icons/48.png",
      "light": "icons/dark-48.png",
      "size": 48
    }, {
      "dark": "icons/64.png",
      "light": "icons/dark-64.png",
      "size": 64
    }, {
      "dark": "icons/128.png",
      "light": "icons/dark-128.png",
      "size": 128
    }, {
      "dark": "icons/256.png",
      "light": "icons/dark-256.png",
      "size": 256
    }]
  },
```

**Comment by iG8R** [comment]
I hope, in the future releases there would be an option to select the icon's style:)

**Comment by theowenyoung** [comment]
maybe we can use a better dark icon in the future..

**Comment by iG8R** [comment]
As you can see, at the moment, the icon blends into the background and is therefore difficult to see.

![image](https://user-images.githubusercontent.com/11407417/224053378-ac6934cb-b74e-498a-b581-c026002f4bfe.png)

**Comment by theowenyoung** [comment]
<img width="460" alt="Screenshot 2023-03-10 at 00 04 28" src="https://user-images.githubusercontent.com/62473795/224082604-bd4bc2fd-5c3f-414e-bfcf-4bf47396da95.png">

I'll use the transparent icon as the default dark icon next version.

it seems that you have so many addons.. so maybe the identification is more important for you. I'll consider to offer an option for this. Thanks!

**Comment by iG8R** [comment]
Thanks a lot!

**Comment by theowenyoung** [comment]
Hi, I'll close this issue, cause the main issue had been solved. 

And the second issue about offering a new option for icon, I don't think we have plan for this now, sorry, I have to close this issue now.
