### ISSUE TITLE
[Bug]: deepl api fail to fetch

### ISSUE THREAD

**Issue by DOCTOR-WHO-1** [immersive-translate/immersive-translate#2090]
### 插件版本号 | Version

lastest

### 平台 | Platform

Windows

### 浏览器 | Browsers

Other

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

[Custom DeepL] 翻译服务或网络出现问题
您当前所使用的 [DeepL] 服务因网络连接或服务提供商的问题暂时无法访问。建议您尝试刷新页面或通过更换其他翻译服务。若您是，可以选择使用更为稳定的 DeepL, OpenAI, Claude 或 Gemini 翻译服务（）。 另外，您也可能需要检查您的网络或代理[设置](https://dash.immersivetranslate.com/#general)。

错误原因：Failed to fetch

### 出现问题的网址 | URL

https://www.khanacademy.org/math/differential-calculus/dc-limits/dc-epsilon-delta/v/proving-a-limit-using-epsilon-delta-definition

### 重现步骤 | To Reproduce

1.用deepl  的个人api翻译

**Comment by keyboard3** [comment]
这是你的插件没有访问网络成功，你重启下浏览器或者卸载重装下插件
