### ISSUE TITLE
[Bug]: 谷歌浏览器安装后无法使用

### ISSUE THREAD

**Issue by nowscott** [immersive-translate/immersive-translate#2091]
### 插件版本号 | Version

1.9.3

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/user-attachments/assets/1acc65fe-289e-415b-8600-4f3ed01d631f)

现在显示这样的，options页面打不开

### 出现问题的网址 | URL

所有

**Comment by keyboard3** [comment]
打开 http://dash.immersivetranslate.com/ 重置设置试试？ 如果显示没有安装的话，试着卸载重装看看

**Comment by nowscott** [comment]
昨天通过重装chrome解决了，不知道什么原因
