### ISSUE TITLE
[Bug]: Bing translate error

### ISSUE THREAD

**Issue by dzungitx** [immersive-translate/immersive-translate#2092]
### 插件版本号 | Version

5.6.0

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge, Other

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

Error: Connection time out.
![ZYZEN_11 09 2024_17 26 23 186](https://github.com/user-attachments/assets/58bf16d6-d50c-4ffa-9513-5c40a79cd3aa)

**Comment by keyboard3** [comment]
你这个不是沉浸式翻译得插件，你反馈错地方了
