### ISSUE TITLE
[Bug]: 浏览器插件 中打开 电子书 epub 无法显示图片

### ISSUE THREAD

**Issue by Gabriellamm** [immersive-translate/immersive-translate#2094]
### 插件版本号 | Version

最新的

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

电子书格式的  epub图片不显示

### 重现步骤 | To Reproduce

sss

### 补充说明 | Additional context

sss

**Comment by theowenyoung** [comment]
请问是 阅读电子书，还是 制作双语电子书？有没有示例的 epub 文件，请传一下。

**Comment by keyboard3** [comment]
制作电子书目前是不显示图片的，导出文件正常。
暂无反馈关闭此issue
