### ISSUE TITLE
[Bug]: 开启“翻译网页所有区域”后谷歌学术显示异常

### ISSUE THREAD

**Issue by ysdj** [immersive-translate/immersive-translate#2099]
### 插件版本号 | Version

1.9.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

开启前（正常）：
![image](https://github.com/user-attachments/assets/502f47a2-d0df-4051-846a-9382c52c5f61)

开启后（标题部分重复）
![image](https://github.com/user-attachments/assets/29e04c81-7d5c-4397-a7d6-f0453ca4fd04)

### 出现问题的网址 | URL

https://scholar.google.com/scholar?hl=zh-CN&num=20&as_sdt=0%2C5&as_vis=1&authuser=1&q=trametinib+trial&btnG=

**Comment by keyboard3** [comment]
感谢反馈 1.9.6 已修复
