### ISSUE TITLE
维基百科中的段落被错误切分

### ISSUE THREAD

**Issue by Andy-AO** [immersive-translate/immersive-translate#21]
![image](https://user-images.githubusercontent.com/38101170/212784754-c4c80002-a71a-4f22-a315-e3b9f340ffab.png)

![image](https://user-images.githubusercontent.com/38101170/212784747-c0d9a584-9896-4623-960a-db979dd28f3c.png)

# links
- [Muscle contraction - Wikipedia](https://en.wikipedia.org/wiki/Muscle_contraction#Excitation-contraction_coupling)

**Comment by theowenyoung** [comment]
晚点看~

**Comment by theowenyoung** [comment]
已修复

**Comment by Andy-AO** [comment]
经测试问题已修复，谢谢
