### ISSUE TITLE
[Bug] Failed to sync latest adaptive rules

### ISSUE THREAD

**Issue by iG8R** [immersive-translate/immersive-translate#210]
Hi.
Browser: Firefox 110.0.1 (64-bit)
Immersive Translate: 0.2.81
The title says for itself.

![Immersive-Translate-OpenAI-BadRequest-2023-03-07_004248](https://user-images.githubusercontent.com/11407417/223279530-2c73497e-0e66-4c2e-8028-2155d4fc09d6.jpg)

**Comment by iG8R** [comment]
> hi, do you try this one? `reset` button on General settings.

Hi, yes. It was the first action what I did.

**Comment by iG8R** [comment]
What I've noticed - addon and userscript share the same data.
If any settings are changed in addon the same changes occur in userscript and vice versa.

**Comment by iG8R** [comment]
Also, if both addon and userscript on at the same time then only userscript is working.

**Comment by theowenyoung** [comment]
it's so weird, but first, you should never do this thing -- install both immersive translate userscript and the addon. they definitely have conflicts.

And I also don't believe  they are using the same storage, it makes no senses. 

Could you please do me a favor, open the options page devtools panel -> network panel, see what is the response of this `buildin_config.json` request?

<img width="1671" alt="Screenshot 2023-03-09 at 21 58 13" src="https://user-images.githubusercontent.com/62473795/224048826-37c6a535-4d71-4f02-b684-a50ccfed0bf1.png">

**Comment by iG8R** [comment]
It's so weird.
I did the following:
1. Only turned off the userscript, didn't uninstall it.
2. Reset general settings
3. Re-installed addon, didn't manually clear data.
4. Manually set the setting, !didn't import them!

And now:)
![image](https://user-images.githubusercontent.com/11407417/224051192-0112651c-90da-4f1f-9836-5224213cbff2.png)

**Comment by theowenyoung** [comment]
so everything is fine now?

**Comment by iG8R** [comment]
Yes, thanks for your concern, at the moment the synchronization is working fine.
