### ISSUE TITLE
[Bug]: 换了很多模型，很多漏翻译直接以英文内容填写到了翻译的内容中

### ISSUE THREAD

**Issue by microbabywe** [immersive-translate/immersive-translate#2101]
### 插件版本号 | Version

1.9.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

很多漏翻译直接以英文内容填写到了翻译的内容中，特别是我一次提交30条字幕，有时候30翻译出来还是英文。

**Comment by theowenyoung** [comment]
大模型在处理多条翻译请求时 幻觉较多，建议使用其他机器翻译服务，或者每次最多设置5条。

**Comment by microbabywe** [comment]
> 大模型在处理多条翻译请求时 幻觉较多，建议使用其他机器翻译服务，或者每次最多设置5条。

我测试了下，应该是上下文合并的问题，如果大模型把上下文合并了，比如输入20行，只返回18行结果，程序估计就识别不出来怎么对应了
