### ISSUE TITLE
[Bug]: iPadOS reddit 部分页面卡死

### ISSUE THREAD

**Issue by MaroonYS** [immersive-translate/immersive-translate#2103]
### 插件版本号 | Version

1.9.6(418)

### 平台 | Platform

iOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

浏览reddit某些网页时会出现卡死的情况，设备iPad Pro 13英寸，iPadOS 18.1 (22B5034e)

### 出现问题的网址 | URL

https://www.reddit.com/r/Supernote/comments/1fgf22i/a5_x2_details_coming_next_week/

### 重现步骤 | To Reproduce

只需浏览就会出现这种情况

**Comment by keyboard3** [comment]
ios 没能复现，在这里 https://dash.immersivetranslate.com/#general 关闭自动翻译，对比看看

**Comment by MaroonYS** [comment]
> ios 没能复现，在这里 https://dash.immersivetranslate.com/#general 关闭自动翻译，对比看看

关闭后不再卡死，可能和iPadOS有关
