### ISSUE TITLE
[Bug]: Claude translate doesnt work anymore: "extension CORS requests must set 'anthropic-dangerous-direct-browser-access"

### ISSUE THREAD

**Issue by laobaishu92** [immersive-translate/immersive-translate#2105]
### 插件版本号 | Version

1.9.3

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome, Other

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

Claude translations now encounter the error: "401: {"type":"error","error":{"type":"authentication_error","message":"CORS requests must set 'anthropic-dangerous-direct-browser-access' header"}}"

look like a new issue because of Anthropics API changes

 {
  "type": "error",
  "error": {
    "type": "authentication_error",
    "message": "CORS requests must set 'anthropic-dangerous-direct-browser-access' header"
  }
}

### 出现问题的网址 | URL

all websites

### 重现步骤 | To Reproduce

use claude's service (with a working API)

**Comment by Anankke** [comment]
Same here, the easy fix would be the dev add the header `anthropic-dangerous-direct-browser-access: true` for us ASAP.

**Comment by keyboard3** [comment]
This feature will be supported in 1.9.7

**Comment by liyimengwork** [comment]
Anticipating the release of 1.9.7 at the earliest. Thanks!

**Comment by SakaZulu** [comment]
`anthropic-dangerous-direct-browser-access: true`
這個應該在主體程序就有修正 在自訂API 反而沒修正 ?

**Comment by laobaishu92** [comment]
看起來已經解決了，謝謝！
