### ISSUE TITLE
关于字幕翻译的功能，能不能同时支持多个字幕同时上传，翻译

### ISSUE THREAD

**Issue by byeage** [immersive-translate/immersive-translate#2106]
### 您希望的更新和改进是什么 | Update or Improve

有时候需要翻译一些教程的字幕，教程分成很多节，需要一次一次的选择，操作有点繁琐

### 补充说明 | Additional context
类似 TinyPNG 的效果
![2024-09-15_10-18](https://github.com/user-attachments/assets/e449f09e-7898-4133-b012-0868163f6af0)

_No response_

**Comment by theowenyoung** [comment]
和 #1422 重复。这个功能未来应该会支持。
