### ISSUE TITLE
[Bug]: Claude api 需要在header加入瀏覽器許可

### ISSUE THREAD

**Issue by silver0416** [immersive-translate/immersive-translate#2107]
### 插件版本号 | Version

1.9.6

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

使用自訂Auth key時，進行測試或翻譯時就會收到
`401: {"type":"error","error":{"type":"authentication_error","message":"CORS requests must set 'anthropic-dangerous-direct-browser-access' header"}}`

**Comment by keyboard3** [comment]
下一版本会支持这个请求头
