### ISSUE TITLE
[功能建议]选中翻译/取消翻译

### ISSUE THREAD

**Issue by waikr** [immersive-translate/immersive-translate#211]
在阅读代码参考的时候,经常翻译代码里面的内容,导致代码的可读性大大降低

**Comment by waikr** [comment]
刚才看了看issue,没注意到有人提出过相同的建议

**Comment by waikr** [comment]
刚才看了看issue,没注意到有人提出过相同的建议

**Comment by theowenyoung** [comment]
嗯，可以贴出来一些网址，可以研究一下模式，大多数情况来讲 代码是不会被翻译的。

你的建议很好～我后面要给译文增加一些可点击的操作按钮，在这里里面可以增加删除该段译文。

**Comment by theowenyoung** [comment]
目前已支持鼠标悬停 翻译该段，这个问题应该可以关闭了？

有问题再开哈～
