### ISSUE TITLE
提升长篇页面翻译速度性能优化的建议

### ISSUE THREAD

**Issue by cbingb666** [immersive-translate/immersive-translate#2114]
### 您希望的更新和改进是什么 | Update or Improve

问题：在翻译长篇网页时，我们可能需要快速滚动到某个段落进行查看，需要等待很久才呈现翻译结果

优化方案：

1. 为每个翻译请求设立一个优先级：
   - 可视区域的翻译请求为高
   - 非可视区域为低，并且距离可视区域越远的内容优先级越低
2. 页面滚动时实时刷新他们的优先级
3. 维护一个“翻译请求池”，同时设置一个最高阈值，若有新的请求并且池中溢出时，将优先级低的请求取消加入等待队列

**Comment by keyboard3** [comment]
默认只会翻译可视区域内容。你如果想要实时翻译效果建议鼠标悬停按需翻译，无需等待
