### ISSUE TITLE
[Bug]: Full User Config内键入"frequency_penalty": "0.15",后消失的问题

### ISSUE THREAD

**Issue by CodeSnowC** [immersive-translate/immersive-translate#2115]
### 插件版本号 | Version

1.9.6

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![QQ图片20240917121854](https://github.com/user-attachments/assets/03a126ce-933f-46a5-99b8-007e70b4d512)
如图此模型需要指定frequency_penalty推理参数来抑制退化问题但在user config里输入后点击save此行参数会消失。

### 重现步骤 | To Reproduce

1.在开发者设置的Edit Full User Config里键入"frequency_penalty": "0.15",
2.点击save
3."frequency_penalty": "0.15",内容消失

### 补充说明 | Additional context

希望在custom-ai服务的设置内加入除temperature外更多推理参数的设置能力

**Comment by keyboard3** [comment]
> chrome配置有字数限制，至今未解决

这是chrome浏览器对插件的限制

**Comment by keyboard3** [comment]
导出一份你的用户配置出来看下

**Comment by CodeSnowC** [comment]
[Full_User_Config(CodeSnowC).txt](https://github.com/user-attachments/files/17088084/Full_User_Config.CodeSnowC.txt)

**Comment by keyboard3** [comment]
哈哈 不是不见了，是被重排到前面去了。 你看下你的配置文件中已经有了它
![QQ_1727233519200](https://github.com/user-attachments/assets/d98216d7-44e8-4766-8d49-661c1a8a9d66)
