### ISSUE TITLE
在网页对照翻译有一点比不上Trancy，比如很多技术的官方文档，Trancy是不会把左边菜单栏给翻译的，但沉浸式翻译会..

### ISSUE THREAD

**Issue by fa1c0n1** [immersive-translate/immersive-translate#2117]
### 您希望的更新和改进是什么 | Update or Improve

在网页对照翻译有一点比不上Trancy，比如很多技术的官方文档，Trancy是不会把左边菜单栏给翻译的，但沉浸式翻译会..
以TypeScript的官方文档为例：

沉浸式翻译的效果如下：
<img width="1059" alt="image" src="https://github.com/user-attachments/assets/c0ed91d7-4628-4777-a481-cb974386fc94">

Trancy的翻译效果如下：
<img width="1014" alt="image" src="https://github.com/user-attachments/assets/dcfc9480-8e86-4b10-b8b7-525942a5393f">

**Comment by keyboard3** [comment]
侧边栏这个东西该不该翻译，不同的人需求不一样，有的人需要翻，有的人不需要翻。 无法满足所有人的需求，沉浸式提供了自定义翻译区域的能力  https://immersivetranslate.com/zh-Hans/docs/advanced/
