### ISSUE TITLE
输入框增强的结束的触发字符不支持中文

### ISSUE THREAD

**Issue by nadirvishun** [immersive-translate/immersive-translate#2118]
### 您希望的更新和改进是什么 | Update or Improve

测试用中文`；`来触发翻译，但不行，只有切换到英文`;`才行，但问题是我本身就是在用中文输入法，想要翻译成英文，还有先按shift来切换到英文输入法，再输入三次`;`，额外增加操作，不是很合理。

### 补充说明 | Additional context

无

**Comment by theowenyoung** [comment]
我这里测试中文分号是支持的，可能是输入法的问题？你用的是什么输入法？

https://github.com/user-attachments/assets/7c2caedc-d9b6-4aaa-8da6-a834a59a291a

**Comment by nadirvishun** [comment]
用的win11自带微软输入法，看视频中你的分号不像是中文的分号，是不是开启了中文自动英文标点？
![动画](https://github.com/user-attachments/assets/d44d043a-703b-460b-84cf-afe714fb33d6)
![image](https://github.com/user-attachments/assets/3335ad08-b371-476e-aa5d-16552e65a04c)

**Comment by flamintune** [comment]
这个问题看起来似乎是因为：在 windows 上，中文输入法的分号的keycode会被识别成 229， 含义是文本正在合成中，所以导致中文分号无法生效。

我们正在积极评估改完之后的条件判断会不会影响到其他情况的触发输入框翻译。

目前临时的解决办法，换成用快捷键去触发，或者换成空格这种不会受中文输入法影响的。

**Comment by nadirvishun** [comment]
@flamintune 
我测试了下，监听`keydown`时中文返回的一直是`229`，但是监听`keyup`时则会触发两条消息，先是`229`，然后又返回正确的`186`，是否可以监听`keydown`然后做去重或防抖处理。

**Comment by flamintune** [comment]
下个版本修复

**Comment by yyyyyyounger** [comment]
遇到同樣的問題，搜狗輸入法。Mac可以中文直接三下 `：`，Windows11下中文輸入狀態的 `；` 不觸發。
等待修復 辛苦了！❤️

**Comment by nadirvishun** [comment]
测试当前版本`1.10.2`下已修复。
