### ISSUE TITLE
优化edge侧边栏

### ISSUE THREAD

**Issue by myh66** [immersive-translate/immersive-translate#2119]
### 您希望的更新和改进是什么 | Update or Improve

Edge的侧边栏无法正常加载文本翻译功能
环境：win11
版本 V1.9.6
一直转圈圈
![image](https://github.com/user-attachments/assets/dd139f20-bb3d-4360-8ceb-23f67a2a9a9a)

**Comment by keyboard3** [comment]
这个是由于edge侧边栏插件无权限访问导致的

**Comment by myh66** [comment]
> 这个是由于edge侧边栏插件无权限访问导致的

我看看哥
