### ISSUE TITLE
[Bug]: edx翻译失败

### ISSUE THREAD

**Issue by bohancao888** [immersive-translate/immersive-translate#2121]
### 插件版本号 | Version

V1.8.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

edx只能使用自带字幕，无法使用沉浸式翻译插件的字幕翻译

### 出现问题的网址 | URL

https://learning.edx.org/course/course-v1:HarvardX+CS50+X/block-v1:HarvardX+CS50+X+type@sequential+block@6dc3b19a2300489e8f680fa787b11bc2/block-v1:HarvardX+CS50+X+type@vertical+block@5277fa5a7e324a63bf30fa42a081038d

### 重现步骤 | To Reproduce

![屏幕截图 2024-09-20 173022](https://github.com/user-attachments/assets/4b6eb126-24f9-4490-93d8-24dab819e241)

### 补充说明 | Additional context

![屏幕截图 2024-09-20 173408](https://github.com/user-attachments/assets/babf19d5-ef1d-4480-8fa2-d5f6cb504737)

**Comment by keyboard3** [comment]
你当前插件比价旧。更新下插件试试，我这里正常

![QQ_1727074126630](https://github.com/user-attachments/assets/6df396d5-d431-46cc-84be-221fab96bc58)

**Comment by keyboard3** [comment]
暂无反馈关闭此issue
