### ISSUE TITLE
[Bug]: 目标语言为英语时，漫画翻译排版问题

### ISSUE THREAD

**Issue by zhech567** [immersive-translate/immersive-translate#2122]
### 插件版本号 | Version

1.9.6

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

目标语言为英文时，译文排版为vertical-rl，但是英文漫画一般采用horizontal-tb. 
![image](https://github.com/user-attachments/assets/066b68c7-5342-4045-8b21-293b0b693061)

### 出现问题的网址 | URL

https://www.pixiv.net/artworks/122549006

**Comment by keyboard3** [comment]
![QQ_1727276929749](https://github.com/user-attachments/assets/f7ab168f-4558-45bd-8716-e13628787371)
已更新模型支持
