### ISSUE TITLE
[Bug]: Don't automatically translate subtitles in Apple Developer videos on Safari

### ISSUE THREAD

**Issue by ankb90** [immersive-translate/immersive-translate#2124]
### 插件版本号 | Version

1.9.6

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

Don't automatically translate subtitles in Apple Developer videos on Safari

<img width="1005" alt="Screenshot 2024-09-21 at 11 29 53" src="https://github.com/user-attachments/assets/e18ad925-16e3-4d75-ade0-05c2350e8a63">

### 出现问题的网址 | URL

https://developer.apple.com/videos/play/wwdc2024/10140

### 重现步骤 | To Reproduce

1. Open a video in Apple Developer (e.g. https://developer.apple.com/videos/play/wwdc2024/10140)
2. Enable "Auto-enable billingual captions"
3. The video does not show translated subtitles, only the original subtitles

**Comment by theowenyoung** [comment]
![CleanShot 2024-12-06 at 13 51 45@2x](https://github.com/user-attachments/assets/f297bda9-0960-4065-9f25-a69056b965e6)

it seems this issue fixed.
