### ISSUE TITLE
Duplicate OpenAI Translation Service

### ISSUE THREAD

**Issue by iG8R** [immersive-translate/immersive-translate#2125]
### 您希望的更新和改进是什么 | Update or Improve

Hi.
Currently, there are many online (DDG, Liaobots, You, ChatgptFree, AiChatOnline, CodeNews, MagickPen, Airforce, OpenaiChat, Koala, etc.) and offline (ollama) translation services that support OpenAI API-like requests.
Using several of them in Immersive Translate right now is quite a challenge - every time, you either need to manually edit the properties of the OpenAI Translation Service in Immersive Translate for each needed translation service or, after pre-saving settings for these services, import the needed one.
It would be great if there was a feature that allowed to duplicate the built-in OpenAI Translation Service and create a custom one based on it.

**Comment by keyboard3** [comment]
Currently supported
![QQ_1726970893836](https://github.com/user-attachments/assets/9fa5765c-6ea8-49e0-a4e2-8869c55a1f11)

**Comment by iG8R** [comment]
Thank you very much!
Sorry for my inattention.
