### ISSUE TITLE
鼠标悬停:增加单击长按触发

### ISSUE THREAD

**Issue by psychosispy** [immersive-translate/immersive-translate#2126]
### 您希望的更新和改进是什么 | Update or Improve

目前版本鼠标悬停翻译只有快捷键触发和直接触发，快捷键无法单手使用，直接触发又因为不能自定义延时，很容易误触
希望可以提供一个单击长按触发选项，通过长按左键悬停触发，对于可点击元素，在触发后也可以稍微移动鼠标来避免打开，监听mousedown对性能影响应该也较小

**Comment by theowenyoung** [comment]
感谢建议，我们研究一下，看起来很适合！

**Comment by TaoLoading** [comment]
你好，1.9.8 版本已支持鼠标长按翻译
