### ISSUE TITLE
支持切换当前网页翻译样式为透明模式的快捷键

### ISSUE THREAD

**Issue by buwenyuwu** [immersive-translate/immersive-translate#2127]
### 您希望的更新和改进是什么 | Update or Improve

当前沉浸式翻译支持了使用快捷键切换翻译样式为模糊模式/普通模式，这样能让我们动态的修改翻译样式。但是个人使用下来模糊模式比较刺眼，更喜欢使用10%的透明模式，希望能提供类似的快捷键支持，切换透明模式/普通模式。

**Comment by theowenyoung** [comment]
设置默认译文样式为透明模式即可，参加 #890
