### ISSUE TITLE
[Bug]: markdown文件的 “$ $”翻译后格式异常

### ISSUE THREAD

**Issue by Refarin** [immersive-translate/immersive-translate#2131]
### 插件版本号 | Version

1.9.6 

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

markdown文件翻译中 类似 “$1\%$” 的文本翻译后，格式发生变化 
“$$
1
$$”，中间的符号会丢失。如何保留 “$ $”内的字符不更改。

> 原文 1.1.3   Refill the tank with fuel, water or other ballast to a mass equivalent to   $100\%$   of the  tank’s capacity of fuel. 
  翻译后的.md文件 
1.1.3 用燃料、水或其他压载物重新填充油箱，使其质量等于 $$
100
$$ 油箱的燃料容量。

**Comment by keyboard3** [comment]
源文件发下，用的什么翻译服务

**Comment by Refarin** [comment]
> 源文件发下，用的什么翻译服务
源文件 (https://github.com/Refarin/github-issues-blog/raw/refs/heads/master/v72.md)

服务用的 siliconflow 模型用的 Qwen/[Qwen2.5-32B-Instruct]

**Comment by TaoLoading** [comment]
你好，$$ 之间 % 丢失的问题已修复

**Comment by Refarin** [comment]
> 你好，$$ 之间 % 丢失的问题已修复

感谢。格式还是发生了变化。$会变成$$，中间会加换行。希望是保留“$文本$”不改变
源文件是： “$100\%$ ”
翻译后会变成
$$
100%
$$

**Comment by TaoLoading** [comment]
> > 你好，$$ 之间 % 丢失的问题已修复
> 
> 感谢。格式还是发生了变化。$会变成$$，中间会加换行。希望是保留“$文本$”不改变 源文件是： “$100%$ ” 翻译后会变成 $$ 100% $$

了解了，这个情况是发生在导出后的 markdown 文件，该问题将稍后修复

**Comment by TaoLoading** [comment]
已修复，保留了行内公式和块级公式，并对特殊字符进行了处理，感谢反馈

**Comment by Refarin** [comment]
markdown转换还是有问题，会对 $文本或字符$ 中间的字符进行变换，加双引号是为了让字符可见。
用gpt_academic翻译md文件不会改变两个$  $之间的内容。
原文
> 2.5.1.1   The dummy(ies) shall have a stabilised temperature in the range of   "$20.6^{\circ}\mathrm{C}$"   to   "$22.2^{\mathrm{o}}\mathbf{C}$"  . 
翻译后就会变成

>2.5.1.1 The dummy(ies) shall have a stabilised temperature in the range of "$20.6\{circ\}mathrm\{C\}$" to "$22.2\{mathrm\{o\}\}mathbf\{C\}$" .  
2.5.1.1 dummy人应在 $20.6\{circ\}mathrm\{C\}$ 到 $22.2\{mathrm\{o\}\}mathbf\{C\}$ 的范围内具有稳定的温度。

**Comment by TaoLoading** [comment]
> markdown转换还是有问题，会对 文 本 或 字 符 中间的字符进行变换，加双引号是为了让字符可见。 用gpt_academic翻译md文件不会改变两个$ $之间的内容。 原文
> 
> > 2.5.1.1   The dummy(ies) shall have a stabilised temperature in the range of   "$20.6^{\circ}\mathrm{C}$"   to   "$22.2^{\mathrm{o}}\mathbf{C}$"  .
> > 翻译后就会变成
> 
> > 2.5.1.1 The dummy(ies) shall have a stabilised temperature in the range of "$20.6{circ}mathrm{C}$" to "$22.2{mathrm{o}}mathbf{C}$" .
> > 2.5.1.1 dummy人应在 
> >   20.6
> >   c
> >   i
> >   r
> >   c
> >   m
> >   a
> >   t
> >   h
> >   r
> >   m
> >   C
> >  到 
> >   22.2
> >   m
> >   a
> >   t
> >   h
> >   r
> >   m
> >   o
> >   m
> >   a
> >   t
> >   h
> >   b
> >   f
> >   C
> >  的范围内具有稳定的温度。

将在晚些优化对公式内特殊字符的处理

**Comment by TaoLoading** [comment]
你好，已对 markdown 中的公式进行优化，现在会完整保留公式内容
