### ISSUE TITLE
[Bug]: Youtube 站点自动识别成韩语

### ISSUE THREAD

**Issue by chaoran162** [immersive-translate/immersive-translate#2133]
### 插件版本号 | Version

V1.9.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

当我浏览youtube网站视频的时候，改插件会将英文内容自动识别成韩语导致翻译错误。

### 出现问题的网址 | URL

https://www.youtube.com

**Comment by keyboard3** [comment]
请在翻译按钮的悬浮球处反馈，它会收集当前快照和翻译服务等一些基本信息给开发

**Comment by keyboard3** [comment]
暂无反馈关闭这个问题
