### ISSUE TITLE
去除电子书翻译结束后特效

### ISSUE THREAD

**Issue by zhengshuo123** [immersive-translate/immersive-translate#2134]
### 您希望的更新和改进是什么 | Update or Improve

翻译epub电子书结束后，建议去除散花特效，页面如果有没翻译到的需要重试，特效会导致页面长时间卡顿

**Comment by keyboard3** [comment]
翻译到百分百才会有特效，没有翻译到需要重试这句话啥意思？

**Comment by zhengshuo123** [comment]
> 翻译到百分百才会有特效，没有翻译到需要重试这句话啥意思？

特效出来了，但是没有翻译完，有些段落需要重试，那个花出来后一直消不下去，然后非常卡

**Comment by keyboard3** [comment]
特效出来的时候 左上角的进度条是100%吗？方便截个图吗

**Comment by meijin1123** [comment]
@zhengshuo123 您这边再试一下，我这边试了一下是正常的。

**Comment by zhengshuo123** [comment]
> 特效出来的时候 左上角的进度条是100%吗？方便截个图吗

![image](https://github.com/user-attachments/assets/37154ab3-9498-48af-b306-3ad9a78bb8bf)
那个特效不知为何没截图上，用的硅基流动阿里云72b翻译的，他好像有点慢，然后会出现这种情况，特效出来后会很卡，然后也没翻译完全，我刷新了页面重新来两次就好了

**Comment by keyboard3** [comment]
暂无法复现，关闭此issue
