### ISSUE TITLE
[Bug]: app store更新后，所有配置丢失

### ISSUE THREAD

**Issue by Kirk300** [immersive-translate/immersive-translate#2135]
### 插件版本号 | Version

1.9.7

### 平台 | Platform

iOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

基本上每更新两三次，所有配置都自动重置了，配置的api key都没了，很麻烦。最近更新格外频繁，app store也不写更新日志，不知道更新了什么，就为了重置设置吗

### 出现问题的网址 | URL

所有

**Comment by keyboard3** [comment]
Safari更新并不会丢失配置。请问你的iOS版本是多少

更新日志 https://immersivetranslate.com/zh-Hans/docs/CHANGELOG/

**Comment by keyboard3** [comment]
我也是iOS18，我这升级更新 配置数据并不会丢。 如果配置丢的话，建议定期手动同步到google drive或者到本地 https://dash.immersivetranslate.com/#import_export
