### ISSUE TITLE
[Bug]: 本地PDF翻译，双语下载，原文会被转换成图片

### ISSUE THREAD

**Issue by kaiwu-astro** [immersive-translate/immersive-translate#2137]
### 插件版本号 | Version

1.9.7

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

如题。上传本地PDF来翻译，选择右上角【翻译全部并下载】，再选择【打印机-另存为PDF】，打开发现下载的文件里面，原文变成了图片形式。
![iShot_2024-09-25_20 43 00](https://github.com/user-attachments/assets/daaea203-f706-4c3f-a383-294e8e2a500a)

这一方面导致原文没有那么清晰，另一方面在翻译字数很多的文件的时候（例如学术论文），双语翻译的文件比原文件甚至会大10倍。
<img width="742" alt="image" src="https://github.com/user-attachments/assets/3106a540-83d2-4b9e-9d02-0dfd9518c3c7">

**Comment by kaiwu-astro** [comment]
非常感谢回复。请问目前有没有办法让原文和译文**都不是**图片？如果没有办法的话，我想request这个feature，谢谢

**Comment by keyboard3** [comment]
目前没有办法 当前提供这两个导出选项也是权衡很久给出的选择

**Comment by kaiwu-astro** [comment]
明白了。谢谢
