### ISSUE TITLE
[Bug]: 开启翻译后，谷歌学术列表的文章标题消失了

### ISSUE THREAD

**Issue by douxy1994** [immersive-translate/immersive-translate#2138]
### 插件版本号 | Version

v1.9.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

如图所示，
![photo_2024-09-26_10-20-25](https://github.com/user-attachments/assets/9270ea02-3ee0-4e3b-a7a2-b35870044253)
开启翻译后，谷歌学术列表的文章标题消失了，landslides等Springer nature公司的期刊在文章页面也有这种情况，再次点击停止翻译后，标题依然不显示，必须刷新网页

### 出现问题的网址 | URL

https://scholar.google.com/scholar?hl=zh-CN&as_sdt=0%2C5&q=angular-distance+weighting&btnG=

### 重现步骤 | To Reproduce

打开网页
点击悬浮球翻译
再次点击停止翻译后，标题依然不显示

**Comment by keyboard3** [comment]
![QQ_1727317677064](https://github.com/user-attachments/assets/22fd3ee9-7782-4ee9-abf2-dd2f4772565e)
我试了下并不会消失呀

你在悬浮球那边点击下反馈按钮，它会收集当前网页快照。我看下你的快照

**Comment by douxy1994** [comment]
> ![QQ_1727317677064](https://private-user-images.githubusercontent.com/13177744/370962275-22fd3ee9-7782-4ee9-abf2-dd2f4772565e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMTgxMjcsIm5iZiI6MTcyNzMxNzgyNywicGF0aCI6Ii8xMzE3Nzc0NC8zNzA5NjIyNzUtMjJmZDNlZTktNzc4Mi00ZWU5LWFiZjItZGQyZjQ3NzI1NjVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDAyMzAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5ODY2MTc2ZjQ4OTE0NmYyMmE1Mzk0MTMyNzZjN2MwNWIzODBiOTZjY2Q1ZGUyNTNiZTE0ODQzYTYyZTdlZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LA-ywxjsHX_3qXvxcLlMj2LvLlJ-Fjg72Xomxfi2UQE) 我试了下并不会消失呀
> 
> 你在悬浮球那边点击下反馈按钮，它会收集当前网页快照。我看下你的快照

已经提交了。请检查一下。

**Comment by douxy1994** [comment]
> ![QQ_1727317677064](https://private-user-images.githubusercontent.com/13177744/370962275-22fd3ee9-7782-4ee9-abf2-dd2f4772565e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMTgxMjcsIm5iZiI6MTcyNzMxNzgyNywicGF0aCI6Ii8xMzE3Nzc0NC8zNzA5NjIyNzUtMjJmZDNlZTktNzc4Mi00ZWU5LWFiZjItZGQyZjQ3NzI1NjVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDAyMzAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5ODY2MTc2ZjQ4OTE0NmYyMmE1Mzk0MTMyNzZjN2MwNWIzODBiOTZjY2Q1ZGUyNTNiZTE0ODQzYTYyZTdlZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LA-ywxjsHX_3qXvxcLlMj2LvLlJ-Fjg72Xomxfi2UQE) 我试了下并不会消失呀
> 
> 你在悬浮球那边点击下反馈按钮，它会收集当前网页快照。我看下你的快照

同时麻烦测试一下这个网页，这个情况在我这里是一直都有的必现bug：https://link.springer.com/article/10.1007/s10346-024-02284-y  该页面的快照刚刚也提交了。
![QQ20240926-103225](https://github.com/user-attachments/assets/e2a30a3b-91a3-4b2a-b28a-af583b79edc9)

**Comment by keyboard3** [comment]
你关闭 easyscholar 插件再试试看

**Comment by douxy1994** [comment]
> 你关闭 easyscholar 插件再试试看

关闭了easyscholar插件并清理了缓存，谷歌学术页面仍然存在问题，landslides网页恢复正常。
![QQ20240926-104625](https://github.com/user-attachments/assets/25d1b6da-8b2e-4846-86af-9a835d994e74)

**Comment by keyboard3** [comment]
你双语翻译效果长啥样？

**Comment by douxy1994** [comment]
> 你双语翻译效果长啥样？

双语效果是正常的。另外，我发现mdpi，Springer和wiley翻译后参考文献会消失，刚刚分别点击了反馈。
![QQ20240926-105219](https://github.com/user-attachments/assets/d7130f9f-823f-4c44-9373-02adb4d90919)

**Comment by keyboard3** [comment]
你这些地址 我试了，我这边仅译文都正常。感觉是不是有其他插件影响到了。你给沉浸式插件隐私窗口权限，然后再隐私窗口中试试

**Comment by douxy1994** [comment]
> 你这些地址 我试了，我这边仅译文都正常。感觉是不是有其他插件影响到了。你给沉浸式插件隐私窗口权限，然后再隐私窗口中试试

隐私窗口里是正常的，这个问题感觉是最近才出现的。所以不知道到底是哪个插件影响了，最近我也没有新增的其它插件。

**Comment by keyboard3** [comment]
挨个禁用试试吧

**Comment by douxy1994** [comment]
> 挨个禁用试试吧

非常离谱，我全都关了一个个打开尝试，都开完了结果这个bug也没有再出来。。。。。等我下次遇到了我再看反馈是啥情况吧。。。
另外有个问题是，有一些文章，翻译后就不能点击了，这是啥情况啊
![QQ20240926-111755](https://github.com/user-attachments/assets/fd5627a0-932c-4bac-92e8-f064bf4f93c9)

**Comment by keyboard3** [comment]
我要看下原始快照，这个网页不要翻译，在这里反馈
![QQ_1727321382249](https://github.com/user-attachments/assets/41206b26-c5cf-4551-bed0-1d06d49c2dbb)

**Comment by douxy1994** [comment]
> 我要看下原始快照，这个网页不要翻译，在这里反馈 ![QQ_1727321382249](https://private-user-images.githubusercontent.com/13177744/370973993-41206b26-c5cf-4551-bed0-1d06d49c2dbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzE0OTUsIm5iZiI6MTcyNzMzMTE5NSwicGF0aCI6Ii8xMzE3Nzc0NC8zNzA5NzM5OTMtNDEyMDZiMjYtYzVjZi00NTUxLWJlZDAtMWQwNmQ0OWMyZGJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA2MTMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkODFkNzljN2M4ZGQ0MzkxNDFmMGNiZWViMDdiNDkyODEyOTg2OWJjNTU2ODQ1NThkOTNjYTQxODM2Yjk5YjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6XM6KxHw7sVf8RJL3OAgilCrCIhWV64bobjc7krlPB4)

已提交了反馈。
