### ISSUE TITLE
[Bug]: 以前翻译twitter帖子很正常  现在推特帖子里面的tag 也就是#也一起翻译了  不像以前有突出的蓝色字符  现在看帖子赶紧好恶心啊能不能赶快修复

### ISSUE THREAD

**Issue by fariskiteen** [immersive-translate/immersive-translate#2139]
### 插件版本号 | Version

1.9.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

[Bug]: 以前翻译twitter帖子很正常  现在推特帖子里面的tag 也就是#也一起翻译了  不像以前有突出的蓝色字符  现在看帖子赶紧好恶心啊能不能赶快修复

### 出现问题的网址 | URL

https://x.com/

### 重现步骤 | To Reproduce

当我点击翻译后  不像以前tag里面的字符是蓝色的  蓝色字符证明tag是有效 可点击的  现在就是纯文本

**Comment by keyboard3** [comment]
你用的什么翻译服务？

**Comment by fariskiteen** [comment]
@keyboard3   我一直用的是谷歌翻译  之前还好好的  现在用就一直这个问题

**Comment by fariskiteen** [comment]
@keyboard3 我现在即使换成微软翻译照样有这个错误  请你们自行去检查一下  twitter  帖子里面的tag也会被带着翻译  请你们修复  
不然tag内容和原文会混淆  我会给你个图片举例
![Uploading 实例.png…]()

**Comment by fariskiteen** [comment]
@keyboard3  我现在即使换成微软翻译照样有这个错误 请你们自行去检查一下 twitter 帖子里面的tag也会被带着翻译 请你们修复
不然tag内容和原文会混淆 我会给你个图片举例
![实例](https://github.com/user-attachments/assets/f60536e1-778c-490a-b060-ecd15229b60f)

**Comment by keyboard3** [comment]
给一个具体的帖子链接，我这边没能复现你的问题

**Comment by fariskiteen** [comment]
https://x.com/hashtag/%E8%A3%8F%E5%9E%A2%E7%94%B7%E5%AD%90?src=hashtag_click
我这里是这样的[
![这个是](https://github.com/user-attachments/assets/ad278dbe-62f3-4e52-800a-6d06df566abc)
](url)

**Comment by fariskiteen** [comment]
@keyboard3 我这里是这样的  按道理tag部分应该原文显示  也就是翻译过后依旧是蓝色高亮的字符  而不是没用任何改动的纯生生翻译  以前貌似没这个问题  我在edge也同样这样
![这个是](https://github.com/user-attachments/assets/c7938e65-5809-4f65-9b7a-9162afb27197)

**Comment by keyboard3** [comment]
悬浮球的反馈按钮反馈下，它会收集日志快照

**Comment by keyboard3** [comment]
看到了 明天我看下

**Comment by keyboard3** [comment]
这是一个富文本翻译的一个BUG,  你可以在 【[开发者设置](https://dash.immersivetranslate.com/#developer)】-> 【Edit User Rules】中填写下面规则即可。下一个版本会修复它

`[
  {
    "enableRichTranslate": false,
    "id": "twitter"
  }
]`

**Comment by fariskiteen** [comment]
好的成功了 @keyboard3
