### ISSUE TITLE
txt网页无法翻译

### ISSUE THREAD

**Issue by davidricardo1026** [immersive-translate/immersive-translate#214]
https://www.kernel.org/doc/Documentation/power/states.txt

比如这个网页是txt就无法翻译

**Comment by davidricardo1026** [comment]
这款软件真的非常不错,解决了,chrome翻译无法使用的大问题,而且非常高效,谢谢作者

**Comment by theowenyoung** [comment]
恩 因为他是pre 标签. 也许可以对txt后缀做一个处理

**Comment by theowenyoung** [comment]
最新版0.3.0 已支持～

**Comment by davidricardo1026** [comment]
谢谢作者,已经可以完美支持了,真高效,没问题了
