### ISSUE TITLE
[Bug]: youtube 视频字幕翻译，翻译成日语了。

### ISSUE THREAD

**Issue by Wooden-Gear** [immersive-translate/immersive-translate#2142]
### 插件版本号 | Version

1.9.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

插件设置、浏览器设置、youtube设置默认语言都是中文。
用的是硅基流动的AI翻译。
视频字幕开始是翻译成中文的（有时候一句，有时候几句），之后就会变成日语（无论英语、韩语）。

### 出现问题的网址 | URL

youtube

**Comment by theowenyoung** [comment]
其他翻译服务呢？ 这可能是硅基流动的模型比较小的问题？

**Comment by Wooden-Gear** [comment]
> 其他翻译服务呢？ 这可能是硅基流动的模型比较小的问题？

好了是模型的缘故
