### ISSUE TITLE
翻译时排除 `[aria-hidden="true"]` 的元素

### ISSUE THREAD

**Issue by balthild** [immersive-translate/immersive-translate#2143]
### 您希望的更新和改进是什么 | Update or Improve

`[aria-hidden="true"]` 意味着这个元素是纯粹装饰性的、重复的或者未显示的，不应该被诸如屏幕阅读器的辅助功能读取（[MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-hidden)）。这一特性也应当适用于翻译插件（翻译插件实际上十分符合辅助功能的概念）。

经尝试，这个功能无法通过开发者设置中的 User Rules 实现，因为它不是排除被翻译的元素，而是在一个元素被翻译时排除其中的某些子元素。

### 补充说明 | Additional context

MathJax 在开启 Assistive MathML 功能后，会输出两套不同的渲染结果，分别用于显示和屏幕阅读器，前者被标上了 `[aria-hidden="true"]` 即对辅助功能不可见，而后者在视觉上不可见。

目前包含上述渲染结果的段落在被翻译时，会显示重复的数学公式，其中一个的排版被破坏，另外一个排版正常的则是提供给屏幕阅读器的 Assistive MathML。

![image](https://github.com/user-attachments/assets/9605f32b-b400-4bac-94b3-0ba38c5a5c09)

**Comment by keyboard3** [comment]
已排除, 打开 https://dash.immersivetranslate.com/#about 会自动更新规则，然后重试下

**Comment by balthild** [comment]
显示「本地适配规则已是最新: 2024/9/27 20:19:56」，但是似乎没有起作用

![image](https://github.com/user-attachments/assets/719baa45-aecd-4c9d-8cdb-a09e3772d168)

**Comment by keyboard3** [comment]
不好意思，构建失败 稍等

**Comment by keyboard3** [comment]
你再试下更新规则

**Comment by balthild** [comment]
不好意思…… 好像还是没有什么变化……

**Comment by keyboard3** [comment]
你把公式的文章地址发出来 不然我没法确认你的问题是否解决

**Comment by balthild** [comment]
https://balthild.github.io/sicp/1_002e3.xhtml#g_t1_002e3_002e1

**Comment by keyboard3** [comment]
早点贴文章就可以了。 更新规则重试下

![QQ_1727538200116](https://github.com/user-attachments/assets/688f608a-a1d9-4fc9-99f9-9f07c417276b)

**Comment by balthild** [comment]
抱歉…… 现在可以了，谢谢！
