### ISSUE TITLE
[Bug]: jssdk中包含乱码字符

### ISSUE THREAD

**Issue by imfenghuang** [immersive-translate/immersive-translate#2144]
### 插件版本号 | Version

1.9.6

### 请描述这个Bug | Describe the bug

`https://download.immersivetranslate.com/immersive-translate-sdk-latest.js` 1.9.6 包含乱码字符
![image](https://github.com/user-attachments/assets/929935ff-575c-45ed-ad9c-40734bdc077f)

`1.9.7` user script
![image](https://github.com/user-attachments/assets/9e4ef767-a6ce-4beb-9a77-3fa95e4aaacc)

**Comment by keyboard3** [comment]
新版已修复
