### ISSUE TITLE
[Bug]: 无法显示正常排版

### ISSUE THREAD

**Issue by myh66** [immersive-translate/immersive-translate#2145]
### 插件版本号 | Version

1.9.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/user-attachments/assets/690c8794-6e9d-48f5-8b8a-36a273045be7)

### 出现问题的网址 | URL

https://controlpanel.tech/

### 重现步骤 | To Reproduce

Manage Orders栏目

**Comment by theowenyoung** [comment]
这个没啥好办法，原网站放不下双语，建议使用仅译文翻译：

![CleanShot 2024-09-28 at 18 18 40@2x](https://github.com/user-attachments/assets/39986168-0638-4cb9-9d5e-3c3f9647dfe3)

**Comment by myh66** [comment]
> 这个没啥好办法，原网站放不下双语，建议使用仅译文翻译：
> 
> ![CleanShot 2024-09-28 at 18 18 40@2x](https://private-user-images.githubusercontent.com/62473795/371748636-39986168-0638-4cb9-9d5e-3c3f9647dfe3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MTkwNTYsIm5iZiI6MTcyNzUxODc1NiwicGF0aCI6Ii82MjQ3Mzc5NS8zNzE3NDg2MzYtMzk5ODYxNjgtMDYzOC00Y2I5LTlkNWUtM2MzZjk2NDdkZmUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI4VDEwMTkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2NzZjNmJiNjllMzY3MjgzMTM0ZDVjNmQzNTcyZDFmNzNhNDU5ZGFlZTM0ZWYwM2JmMzM5ZGYzOTIyZDk4ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3bUZ8ZQnjrMIL1GSYAEs4bXd3_-tck9YsvkkLzgYemA)

知道谢谢owen
