### ISSUE TITLE
youtube翻譯字幕位置顯示問題

### ISSUE THREAD

**Issue by FrankTsai69** [immersive-translate/immersive-translate#2146]
### 您希望的更新和改进是什么 | Update or Improve

![螢幕擷取畫面 2024-10-01 121346](https://github.com/user-attachments/assets/aeb357f5-d81f-4037-ae94-a97e2427383a)
翻譯後的字幕會直接顯示在影片的正中央，我有試過調整原文和譯文的字體、大小，但仍然有這個問題。

**Comment by keyboard3** [comment]
字幕可以拖动

**Comment by FrankTsai69** [comment]
感謝!已解決
