### ISSUE TITLE
[Bug]: Discord forum列表显示异常

### ISSUE THREAD

**Issue by qh0814** [immersive-translate/immersive-translate#2147]
### 插件版本号 | Version

1.9.8

### 平台 | Platform

Windows

### 浏览器 | Browsers

Other

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/user-attachments/assets/9def5596-5f76-4ee1-a902-770f95db610e)

**如图所示，翻译标题时文字显示不全**

运行环境：

- 操作系统：Windows 11 Version 23H2
- 浏览器：Vivaldi 6.9.3447.51 (Stable channel)

### 出现问题的网址 | URL

https://discord.com/channels/1089972953506123937/1089973194242412615

### 重现步骤 | To Reproduce

1. 进入Discord对应的页面
2. 使用插件进行翻译

### 补充说明 | Additional context

但并不是所有的这类页面都会显示不全，比如下图的翻译结果是**部分**显示不全：
![image](https://github.com/user-attachments/assets/7676647f-1192-46aa-8109-e14114d6b0f5)

我尝试过以下操作，但仍然无法解决问题：

- 调整翻译的字体及字体大小
- 调整翻译样式，比如无样式、虚线下划线、引用样式
- 调整浏览器当前页面的缩放
- 更换翻译服务
- 在PWA界面上进行翻译
- 更换浏览器为edge

**Comment by theowenyoung** [comment]
这个是因为 discord 强行限制了标题的高度，所以放不下译文， @flamintune  我们看下能不能做强行适配。

**Comment by flamintune** [comment]
已适配，打开popup面板更新规则再试试呢

**Comment by qh0814** [comment]
谢谢，已经正常了。
