### ISSUE TITLE
[Bug]: 翻译pdf文件，一旦遇到右上角引用角标的地方，就会换行并且字体变大，导致翻译不连贯，字体重叠

### ISSUE THREAD

**Issue by niuniu132** [immersive-translate/immersive-translate#2148]
### 插件版本号 | Version

1.9.8

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

 翻译pdf文件，一旦遇到右上角引用角标的地方，就会换行并且字体变大，导致翻译不连贯，字体重叠
![Screenshot 2024-10-03 at 09 38 22](https://github.com/user-attachments/assets/b5bac4a9-a731-4eda-b5dd-919a3d9d4f38)

附上原pdf文件
[333333sss.pdf](https://github.com/user-attachments/files/17238127/333333sss.pdf)

**Comment by theowenyoung** [comment]
已知问题，普通PDF目前还无法处理原文件比较复杂的情况。试了下 Pro PDF https://app.immersivetranslate.com/pdf-pro/ , 效果还行：


[333333sss --- 333333sss.pdf](https://github.com/user-attachments/files/17296977/333333sss.---.333333sss.pdf)
