### ISSUE TITLE
对话时选中翻译的功能

### ISSUE THREAD

**Issue by ArayTendor** [immersive-translate/immersive-translate#215]
场景：与外国人，chatgpt等对话时
比如chatgpt，普遍认为英文对话会获得更好的答案，但是要把自己想的内容去翻译网站翻译一遍复制粘贴回来，如果能在对话框、输入框中先写上中文，选中翻译，再点击发送，这样就真正实现了单网页“沉浸式”对话。

**Comment by ceeeeeeeeeeeeeeeeb** [comment]
同时 请考虑一下自动翻译chatgpt回答，现在情况是gpt回答后可以翻译    但如果正在回答时翻译的话只会翻译之前的对话，后续生成的对话不会翻译 要想翻译的话需要再点一次翻译， 虽然也不麻烦，但若能在gpt生成回答的同时就动态翻译的话会更好

**Comment by theowenyoung** [comment]
目前已经完美支持了输入框翻译功能，请查看文档： https://immersivetranslate.com/docs/input/

应该可以满足需求了～
