### ISSUE TITLE
[Bug]: 我是手机浏览器kiwibrowser  也是用的插件  但是没办法快速点击三次空格随后输入框翻译

### ISSUE THREAD

**Issue by fariskiteen** [immersive-translate/immersive-translate#2151]
### 插件版本号 | Version

最新版本

### 平台 | Platform

Android

### 浏览器 | Browsers

Other

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

我没办法在这个浏览器上启用''输入框增强''功能

### 出现问题的网址 | URL

google.com

### 重现步骤 | To Reproduce

三击空格键后无法像电脑一样翻译输入框
![Screenshot_20241005-111226_Pixel 启动器](https://github.com/user-attachments/assets/c5c1444a-4406-443d-b18f-192780ba0225)

**Comment by theowenyoung** [comment]
移动端安卓浏览器目前只有 Firefox 支持输入框翻译，请使用 Firefox
