### ISSUE TITLE
增加漫画网站https://www.dlsite.com/comic/

### ISSUE THREAD

**Issue by ahjdzbc** [immersive-translate/immersive-translate#2153]
### 您希望的更新和改进是什么 | Update or Improve

增加对https://www.dlsite.com/comic/ 网页漫画支持，这个网站基本都是付费的，用户付费意愿强，而且种类多

**Comment by keyboard3** [comment]
在这里提供 https://github.com/immersive-translate/immersive-translate/issues/1809 申请。付费漫画需要提供账密给开发者才能去适配

**Comment by ahjdzbc** [comment]
> 在这里提供 #1809 申请。付费漫画需要提供账密给开发者才能去适配

怎么提供

**Comment by Angela924128** [comment]
我也需要！强推！这个网站上的漫画是最新的，怎么提供账号！！
