### ISSUE TITLE
鼠标悬停翻译的内容能否始终固定住，不消失。

### ISSUE THREAD

**Issue by teraStars** [immersive-translate/immersive-translate#2155]
### 您希望的更新和改进是什么 | Update or Improve

这是非常棒的一个应用，现在唯一让我困扰的就是，鼠标悬停翻译的内容，我希望它能始终固定在那里。

我现在用的是ctrl+翻译/还原，一般情况下，比如我按下ctrl后，它会翻译，然后我ctrl松开，翻译的内容消失。但如果我此时移动鼠标，再松开ctrl，这时大部分情况下，它不会消失。我为了让它不消失，都是用这种方法。但有时还是会消失（我也没找到规律），我又只好重新来一次。

我的需求就是希望增加一个选项，勾了这个选项后，松开ctrl后，翻译的内容仍然不消失，只要翻译了就固定在那里。因为它这个不像翻译软件的鼠标悬停是按词翻译，它这是悬停后进行一长段翻译，意味着我为了读完这一长段，必须始终按着ctrl键。然后还不能对翻译的内容进行拷贝。

**Comment by keyboard3** [comment]
你是不是 【鼠标悬停】设置了【直接翻译该段】

**Comment by teraStars** [comment]
> 你是不是 【鼠标悬停】设置了【直接翻译该段】

不是，我是ctrl+翻译。
就是这段翻译有时会消失，有时又不消失。而我希望的是，只要翻译好后，就一直固定在那里。
一般情况下，比如我按下ctrl后，它会翻译，然后我ctrl松开，翻译的内容消失。但如果我此时移动一下鼠标，再松开ctrl，这时就有时消失有时不消失了。我为了让它固定在那里，往往会ctrl后，移动一下鼠标，然后再松开ctrl。但这时它有时还是会消失。挺搞的。

**Comment by theowenyoung** [comment]
他的实际逻辑是，按一次就检测一次，再次按下就消失。所以可能你需要避免松开的操作。

**Comment by teraStars** [comment]
> 他的实际逻辑是，按一次就检测一次，再次按下就消失。所以可能你需要避免松开的操作。

我的需求就是希望增加一个选项，松开后，翻译的内容仍然不消失，只要翻译就固定在那里。

**Comment by theowenyoung** [comment]
翻译后，直接松开 ctrl 键，之后不再按下 Ctrl 键应该就可以了？

**Comment by teraStars** [comment]
> 翻译后，直接松开 ctrl 键，之后不再按下 Ctrl 键应该就可以了？

翻译后，直接松开ctrl键，一般就消失了。但如果此时移动鼠标，再松开ctrl键，大部分情况，它不会消失，我为了让它不消失，都是用这种方法，但有时还是会消失，我又只好重新来一次。它这个不像翻译软件按词翻译，它这是悬停后一长段翻译，意味着我为了读完这一长段，必须始终按着ctrl键。

**Comment by keyboard3** [comment]
不知道是你的操作问题还是那个网页的问题，正常情况下 【ctrl+鼠标悬停】就会触发逻辑 显示或者删除译文。而显示的元素就是永久的，除非你再次触发了上述逻辑删除了译文元素

**Comment by teraStars** [comment]
> 不知道是你的操作问题还是那个网页的问题，正常情况下 【ctrl+鼠标悬停】就会触发逻辑 显示或者删除译文。而显示的元素就是永久的，除非你再次触发了上述逻辑删除了译文元素
感谢您的回复，搞了半年，原来我一直用错了，我一直是始终按着ctrl键等翻译出来后再松开ctrl键。原来只需要点按一次ctrl键就行了。

**Comment by teraStars** [comment]
> 不知道是你的操作问题还是那个网页的问题，正常情况下 【ctrl+鼠标悬停】就会触发逻辑 显示或者删除译文。而显示的元素就是永久的，除非你再次触发了上述逻辑删除了译文元素

感谢您的回复，搞了半年，原来我一直用错了，我一直是始终按着ctrl键等翻译出来后再松开ctrl键。原来只需要点按一次ctrl键就行了。
