### ISSUE TITLE
[Bug]: 电子书翻译后无法导出，对话框弹出undefine

### ISSUE THREAD

**Issue by simoon189** [immersive-translate/immersive-translate#2157]
### 插件版本号 | Version

V1.9.8

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

电子书全文翻译后无法输出，显示undefine

### 出现问题的网址 | URL

https://app.immersivetranslate.com/?utm_source=extension&utm_medium=extension&utm_campaign=popup_btn_document

**Comment by theowenyoung** [comment]
请问可以附上电子书原文件吗？可以zip 一下上传到这里。

**Comment by simoon189** [comment]
[Oil-Money-Split-David-M-Wight.zip](https://github.com/user-attachments/files/17301592/Oil-Money-Split-David-M-Wight.zip)
非常感谢！

**Comment by keyboard3** [comment]
有用户反馈也有类似问题，chrome版本升级之后这个问题就解决了。你试下升级chrome看看

**Comment by simoon189** [comment]
升级chrome已经解决问题，多谢Owen!
