### ISSUE TITLE
[Bug]EPUB阅读长段落翻译顺序错乱(与原文顺序不符)

### ISSUE THREAD

**Issue by Bill686** [immersive-translate/immersive-translate#216]
蓝色标注的翻译对应原文红色划线部分, 原文中后面的文字翻译后放在了前面, 切换翻译服务同样存在这个问题

![Snipaste_2023-03-10_10-26-57](https://user-images.githubusercontent.com/87408615/224209050-7000be12-c552-4a56-8f2d-e462966fade0.png)

**Comment by Bill686** [comment]
epub文件
[HFUL.zip](https://github.com/immersive-translate/immersive-translate/files/10938036/HFUL.zip)

**Comment by theowenyoung** [comment]
确认bug，下个版本修复。

**Comment by Bill686** [comment]
已收到邮件！

**Comment by theowenyoung** [comment]
0.3.1 已修复。

**Comment by Bill686** [comment]
已收到邮件！
