### ISSUE TITLE
[Bug]: 当出现“<”号时翻译混乱

### ISSUE THREAD

**Issue by ysdj** [immersive-translate/immersive-translate#2163]
### 插件版本号 | Version

1.9.8

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

用的谷歌翻译，翻译错误部分<10 id=2>如图，疑似与”<“号有关
![image](https://github.com/user-attachments/assets/d27b7ab7-ae53-4ab7-b8b3-fb17d3738e8a)

### 出现问题的网址 | URL

https://link.springer.com/article/10.1186/s13073-016-0361-5

**Comment by keyboard3** [comment]
1.10.2 已支持
