### ISSUE TITLE
希望能优化仅译文模式下对链接文本的翻译

### ISSUE THREAD

**Issue by 567-su** [immersive-translate/immersive-translate#2167]
### 您希望的更新和改进是什么 | Update or Improve

希望能优化仅译文模式下对链接文本的翻译。
我想到的是以下两个方向：
1. 对译文插入和原文一样的超链接（就像Edge自带的翻译那样）；
2. 识别到链接，就索性不翻译该链接文本。

### 补充说明 | Additional context

我知道双语模式可以点原文的链接，但是双语模式真的不如仅译文模式美观，而且有些网站用双语模式还会出现因为地方太小而显示不全译文的清况。所以真的希望能优化仅译文模式下对链接文本的翻译🥺，开发者们辛苦了。

**Comment by keyboard3** [comment]
没懂 你用的是什么版本插件，早就支持了译文链接翻译啊，可以直接点击译文的链接

**Comment by 567-su** [comment]
> 没懂 你用的是什么版本插件，早就支持了译文链接翻译啊，可以直接点击译文的链接

噢噢噢，你说完我又去试了试，原来是 CiliconCloud 的原因，换成谷歌翻译后译文可以直接点链接了，抱歉抱歉。

**Comment by keyboard3** [comment]
CiliconCloud 的高级选项也可以开启富文本翻译

**Comment by 567-su** [comment]
> CiliconCloud 的高级选项也可以开启富文本翻译

原来如此，感谢！
