### ISSUE TITLE
[Bug]: youtube视频字幕无法使用，控制台报错

### ISSUE THREAD

**Issue by HlgdB** [immersive-translate/immersive-translate#2168]
### 插件版本号 | Version

1.9.8

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在设置中已经正确配置了双语字幕，但是随便打开一个油管的视频页都没有字幕出现，打开控制台有content-script.js的报错
![image](https://github.com/user-attachments/assets/9563e907-e2b3-44fa-a473-3e0000b3e279)

### 出现问题的网址 | URL

https://www.youtube.com/watch?v=KvZoBV_1yYE

**Comment by keyboard3** [comment]
![QQ_1728546590024](https://github.com/user-attachments/assets/6648b94d-cbb2-405c-a1b7-756060b02684)
我这边的macOS chrome测试正常，可能是第三方插件影响到了。
你可以试下给插件隐身窗口权限，在隐身窗口中试试

**Comment by HlgdB** [comment]
我按照你说的试了下，在无痕模式下字幕功能很丝滑正常。然后我试着清了下chrome缓存和插件缓存，字幕功能也能使用了，只是偶尔还是会出现打开YouTube界面字幕没出现的情况，刷新页面也能解决。
我上报了之前content-script报错时的日志，有空的话可以查看一下原因。
