### ISSUE TITLE
[Bug]: 翻译全部网页和鼠标悬停翻译共用导致内容消失

### ISSUE THREAD

**Issue by jhj0411jhj** [immersive-translate/immersive-translate#2169]
### 插件版本号 | Version

1.9.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

翻译全部网页和鼠标悬停翻译共用导致内容消失，详见步骤

### 出现问题的网址 | URL

英文网页

### 重现步骤 | To Reproduce

1. 将英文网页翻译为中文
2. 鼠标悬停+ctrl对一个内容按两次，从中文变英文，再变回中文
3. 将中文网页显示原文为英文
4. 发现悬停翻译过的内容消失了

**Comment by keyboard3** [comment]
将在1.10.5修复
