### ISSUE TITLE
[Feature Request]字体回退

### ISSUE THREAD

**Issue by timelic** [immersive-translate/immersive-translate#217]
我注意到现在译文的字体是和原文一致的，但是原文的字体往往是英文字体，无对应汉字区域，所以会回退到中文，回退到默认的系统字体。

能不能添加一个回退字体的选项，让我手动选择或者输入回退字体？

假如原文有这样的样式

```
p {
  font-family: xxx, yyy, seilf;
}
```

我希望设置回退字体为zzz之后，译文的样式是这样的

```
p {
  font-family: xxx, yyy, zzz;
}
```

**Comment by theowenyoung** [comment]
嗯，这个有计划增加一个字体设置的选项～ 但是时间上可能要后面一点了

**Comment by timelic** [comment]
按照你们开发进度吧 感谢🙏

**Comment by theowenyoung** [comment]
先关掉这个issue，统一在 #784 讨论吧。
