### ISSUE TITLE
希望在翻译pdf中添加一个仅显示原文的功能

### ISSUE THREAD

**Issue by suisbuds** [immersive-translate/immersive-translate#2172]
### 您希望的更新和改进是什么 | Update or Improve

首先感谢各位开发者提供如此好用的翻译插件！
希望能够在翻译pdf的功能中添加**仅显示原文**的功能。原先的沉浸式翻译体验很好，而且在使用pdf翻译功能的过程中，pdf的阅读体验也很好！所以稍稍希望添加一个仅显示原文的功能，沉浸式阅读pdf！

**Comment by keyboard3** [comment]
阅读原文pdf不是沉浸式的目的，有太多的替代工具
