### ISSUE TITLE
[Bug]: 使用仅译文模式在某些页面会出现行间距过大

### ISSUE THREAD

**Issue by Wei-Winter** [immersive-translate/immersive-translate#2173]
### 插件版本号 | Version

1.9.8

### 平台 | Platform

iOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

具体复现为在某些不需要刷新的网站多次重定向会出现此问题

> `
![IMG_4160](https://github.com/user-attachments/assets/bd2e9503-ce4c-409b-97b9-97e5229158af)
`

### 出现问题的网址 | URL

任何类似这样不需要刷新网页前进后退都有概率出现此问题

### 重现步骤 | To Reproduce

比如GitHub的Issues界面>点开某个问题>后退，这样就有一定概率出现行间距过大

**Comment by keyboard3** [comment]
这个概率复现，浏览器会回收部分资源，插件干预不了，暂时先关闭
