### ISSUE TITLE
[Bug]: 大模型富文本翻译遇到`&nbsp`时空格丢失

### ISSUE THREAD

**Issue by edr1412** [immersive-translate/immersive-translate#2175]
### 插件版本号 | Version

1.9.8

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome, Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

原文包含`&nbsp`时，译文空格丢失

### 出现问题的网址 | URL

https://example.immersivetranslate.com/nbsp

### 重现步骤 | To Reproduce

1. 翻译服务使用gpt-4o/claude-3-5-sonnet/gemini-1.5-pro-002，或任意其他大模型
2. 打开“富文本翻译”
3. 翻译 https://example.immersivetranslate.com/nbsp ，或者带有 `&#160;` `\u00a0`用来代替空格的EPUB文件
4. 发现译文对应的地方空格丢失，如图黄色部分，'for' 'to'之后的空格丢失

<img width="843" alt="Screenshot 2024-10-11 at 22 18 30" src="https://github.com/user-attachments/assets/83f2f19d-4931-400f-ad11-cdfba269d5b5">

### 补充说明 | Additional context

使用谷歌翻译时无此问题

**Comment by keyboard3** [comment]
将在未来1.10.3支持

**Comment by edr1412** [comment]
> 将在未来1.10.3支持

谢谢回复！请问什么时候发布 1.10.3 呢？

**Comment by theowenyoung** [comment]
预计下周五
