### ISSUE TITLE
翻译遇到超链接时在译文中保留超链接

### ISSUE THREAD

**Issue by YuCN0010** [immersive-translate/immersive-translate#2179]
### 您希望的更新和改进是什么 | Update or Improve

参考豆包浏览器插件，翻译时遇到超链接，会将超链接翻译后保留到译文中，可以直接点击

**Comment by keyboard3** [comment]
现在就支持，如果你使用AI翻译服务，需要手动去设置页启用富文本翻译，普通翻译服务默认支持
![QQ_1728719957854](https://github.com/user-attachments/assets/6a434f8e-3200-446a-85fb-a594d3e26cf9)
