### ISSUE TITLE
[功能建议]关于OpenAI翻译服务的功能建议

### ISSUE THREAD

**Issue by winterggg** [immersive-translate/immersive-translate#218]
1. 填写API可以用用逗号分隔填写多个，以实现负载均衡。
2. 可以自定义API URL

**Comment by theowenyoung** [comment]
0.3.2 已支持自定义，不过需要在开发者设置里操作一下：

"apiUrl":""

https://immersive-translate.owenyoung.com/advanced#%E7%BF%BB%E8%AF%91%E6%9C%8D%E5%8A%A1%E9%85%8D%E7%BD%AE

**Comment by winterggg** [comment]
十分感谢！
