### ISSUE TITLE
[Bug]: Mac Safari上无法进行翻译

### ISSUE THREAD

**Issue by LoneFireBlossom** [immersive-translate/immersive-translate#2181]
### 插件版本号 | Version

1.9.8

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

我之前使用macOS 13.7，使用本插件没有遇到过问题。
从macOS 15正式版发布后，Safari 18也发布了，于是我在macOS 13上更新了Safari 18 for macOS 13，然后插件在Safari上就失效了。
之后我更新到了macOS 15，15.0.1，Safari也跟着更新了，但是还是失效。
这从系统正式版发布到现在我还想着肯定有人反馈过了，会修复的，但是今天打开issue一看难道只有我遇到了这个问题？！😢
只好发一个issue了。

![CleanShot 2024-10-13 at 09 41 04](https://github.com/user-attachments/assets/60ba0b00-0dca-4e3e-96ce-3961fa5f03b1)

### 出现问题的网址 | URL

Safari上所有网址全部翻译失效，视频字幕翻译也失效

### 补充说明 | Additional context

1. Chrome上没有这个问题。
2. 尝试过重启电脑、重启Safari、卸载插件重新安装、关闭Safari上其它所有插件、更换翻译源都不行。
3. iPhone端我就没遇到这个问题，插件能正常翻译。

**Comment by keyboard3** [comment]
其他网页呢。可以在 https://app.immersivetranslate.com/text#auto/zh-CN/hello 这个地址试下插件是否能正常翻译

**Comment by LoneFireBlossom** [comment]
![14262](https://github.com/user-attachments/assets/fca5b5cd-0afb-48b0-bd39-0d6c866bf4a3)

**Comment by LoneFireBlossom** [comment]
是这样测试吗，还需要测试啥呢

**Comment by keyboard3** [comment]
那你其他网页翻译正常吗？还是只有一个站点有问题？

**Comment by LoneFireBlossom** [comment]
上面说了呀，所有网页翻译全部失效

**Comment by keyboard3** [comment]
额。。。。你仔细看下你面板上选择的目标语言，你选择的是英文

**Comment by LoneFireBlossom** [comment]
卧槽，我也太傻逼了。实在对不起。
没想到更新了Safari，插件自己的设置被重置了……根本没往这方面想。
