### ISSUE TITLE
麻烦加快一下 crx 安装包的更新速度

### ISSUE THREAD

**Issue by Lang45** [immersive-translate/immersive-translate#2182]
### 您希望的更新和改进是什么 | Update or Improve

immersivetranslate.com/zh-Hans/manual-chrome-extension
官网的沉浸式翻译 crx 安装包版本还是1.98版本，麻烦加快一下 crx 安装包的更新速度，最好如果新版本发布的时候能直接加上crx 安装包那最好了。
辛苦，万分感受

**Comment by theowenyoung** [comment]
CRX 安装包依赖Chrome商店的审核，建议您直接使用 Github 仓库中的 zip 包进行安装： https://github.com/immersive-translate/immersive-translate/releases
