### ISSUE TITLE
会员太贵，能否调用系统的语音识别生成字幕

### ISSUE THREAD

**Issue by Lang45** [immersive-translate/immersive-translate#2183]
### 您希望的更新和改进是什么 | Update or Improve

你们这插件太好用了，为了你们能持久更新，我想付费支持一下，但你们这会员太贵了，能不能出个几块钱的会员.  

对于顶尖AI翻译服务，我根本没这需求。我就只翻译英文网页，能变成汉字就行，准确无所谓，有问题我直接去搜英文原单词。 翻译PDF，字幕，表格等文档，看视频希望有个中文字幕，就这些需求。

我想到，你们可以用每天调用的顶尖AI翻译服务的翻译数据，自己简单训练个AI啊，还可以让海量用户对翻译进行纠错，然后出个便宜会员。
对了，对于没有字幕的视频，我看原生Chrome浏览器和window系统的无障碍设置里，都集成了语音识别生成字幕功能，但是不好用，你们能否调用一下？

**Comment by theowenyoung** [comment]
感谢！

对于顶尖AI翻译没有需求的朋友，我们有一个隐藏的 纯功能会员的 订阅链接，如果您需要的话，可以考虑： https://immersivetranslate.com/accounts/pre-order?price_id=price_1PWg9EGc8iUjvqOFATBhujeS

> 我想到，你们可以用每天调用的顶尖AI翻译服务的翻译数据，自己简单训练个AI啊，还可以让海量用户对翻译进行纠错，然后出个便宜会员。

我们有在做类似的工作，并且已经开源了相关模型： https://github.com/immersive-translate/immersiveL ，但是还不够好，还需要继续研究。

> 对了，对于没有字幕的视频，我看原生Chrome浏览器和window系统的无障碍设置里，都集成了语音识别生成字幕功能，但是不好用，你们能否调用一下？

插件没有权限调用，我们也在同步研究无字幕视频的解决方案。感谢反馈！
