### ISSUE TITLE
从右到左书写语言翻译问题

### ISSUE THREAD

**Issue by oqughin** [immersive-translate/immersive-translate#2184]
### 您希望的更新和改进是什么 | Update or Improve

当把从左到右书写语言内容翻译成从右到左的语言时，翻译后的内容没有按从右到左书写的语言的格式去显示内容。需要改进

**Comment by keyboard3** [comment]
这个是支持的，如果遇到问题请给出具体的例子和复现的路径

**Comment by keyboard3** [comment]
暂无反馈，关闭此issue
