### ISSUE TITLE
[Bug]: Mac Safari 插件无法使用自定义字体

### ISSUE THREAD

**Issue by mrzzmrzz** [immersive-translate/immersive-translate#2186]
### 插件版本号 | Version

1.10.2

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

macOS 商店安装的Safari插件，输入自定义字体，例如lxgw-wenkai，会提示没有安装此字体。但是Chrome 浏览器安装的插件不存在该问题。

**Comment by FattySpring** [comment]
这是由于 Safari 的安全策略，无法访问本地字体
