### ISSUE TITLE
悬浮球位置调整后，希望记录下来保持在该位置

### ISSUE THREAD

**Issue by Victor-Sava** [immersive-translate/immersive-translate#2187]
### 您希望的更新和改进是什么 | Update or Improve

悬浮球位置调整后，希望记录下来保持在该位置，默认在右下角，但外接屏大多数会被挡住，因此再找按钮时比较麻烦

感谢您的优化

**Comment by theowenyoung** [comment]
默认情况下应该就会记住，您那里是没有记住吗？移动后刷新页面看看？

**Comment by Victor-Sava** [comment]
忘记备注，我是使用的Tampermonkey，就在收到您回复的前几分钟
收到了脚本更新提示，目前是可以的，之前确实不行，每次刷新页面或者打开其他页面就都到了默认位置

感谢支持
