### ISSUE TITLE
[Bug]: 输入框翻译误触发

### ISSUE THREAD

**Issue by Alan-CRL** [immersive-translate/immersive-translate#2188]
### 插件版本号 | Version

1.10.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

使用拼音输入法在输入框中打字时，比如我需要打出 `你好 再见`，那么在打 `你好` 需要一次空格，在打空格需要一次，然后按下 z 就导致输入框被翻译了，可是这时候只按下 2 次空格，并且 `你好` 的空格不应该被计入计算。具体的复现请看下面的 gif。

### 出现问题的网址 | URL

所有的输入框

### 重现步骤 | To Reproduce

![UniConverter 15_20241018124129](https://github.com/user-attachments/assets/879f8739-d352-4869-8c23-18226c7e4be2)

**Comment by keyboard3** [comment]
看起来不是沉浸式翻译的，沉浸式翻译在输入框翻译的时候会有三个点的loading效果。你试着把沉浸式关闭之后看看

**Comment by Alan-CRL** [comment]
不，只是录屏帧率的问题，三个点确定显示了，并且第一次还会弹出使用提示弹框

**Comment by keyboard3** [comment]
将在1.10.4 修复该问题

**Comment by Bisstocuz** [comment]
我也有这个鬼问题

**Comment by lacafjh** [comment]
同样的问题，以楼主的这句为例，我是打出「你好」一下的选字空格，再敲占位空格会导致输入框内容立马被翻译，大概就是最近一个月内的更新后出现的情况。以

往输入框增强的判定体感比现在严格多，必须是中间没有别的操作，快速连敲 3 次空格，但最近总是很容易触发，导致我每次使用空格后都得强迫自己暂停个 1、2 秒再做别的键盘输入操作。

**Comment by keyboard3** [comment]
> 同样的问题，以楼主的这句为例，我是打出「你好」一下的选字空格，再敲占位空格会导致输入框内容立马被翻译，大概就是最近一个月内的更新后出现的情况。
> 
> 以往输入框增强的判定体感比现在严格多，必须是中间没有别的操作，快速连敲 3 次空格，但最近总是很容易触发，导致我每次使用空格后都得强迫自己暂停个 1、2 秒再做别的键盘输入操作。

你插件什么版本？

**Comment by Alan-CRL** [comment]
@keyboard3 该问题依旧存在，在 V1.10.6 版本中，我可以在 ChatGPT 的输入框中复现这个问题

**Comment by keyboard3** [comment]
1.0.6做了严格校验 必须大于3个空格以上才会触发翻译。我这边windows 下载最新版1.0.6已经正常了啊

**Comment by Alan-CRL** [comment]
奇怪的是，我现在确认我使用的是 1.0.6 版本，并且我在 github 输入框中无论如何都无法复现。但是到了 ChatGPT 100% 可以复现。

视频复现：https://www.123865.com/s/duk9-VoHAd

**Comment by Bisstocuz** [comment]
> 1.0.6做了严格校验 必须大于3个空格字符以上才会触发翻译。我这边windows 下载最新版1.0.6已经正常了啊

ChatGPT 的输入框还是有这个问题，只能把插件禁用才能解决，设置关什么都没用。

**Comment by keyboard3** [comment]
嗯 确实忘记考虑gpt这类输入框了，下个版本修复

**Comment by keyboard3** [comment]
1.11.1 已修复
