### ISSUE TITLE
🔴「SiliconCloud 翻译」添加 Temperature 选项

### ISSUE THREAD

**Issue by Thomas-Harrell** [immersive-translate/immersive-translate#2189]
### 您希望的更新和改进是什么 | Update or Improve

- 如题所示

---

- 目前「SiliconCloud 翻译」没有「Temperature」选项

![image](https://github.com/user-attachments/assets/7a67a7d6-f60f-4403-aa0b-e3f3c7baa02c)

---

- 需要在「自定义 OpenAI」里面才可以设置

<img width="655" alt="image" src="https://github.com/user-attachments/assets/26b8e8e2-f4b4-4d84-8e12-cc7d30dfdc8e">

**Comment by flamintune** [comment]
下个版本修复
