### ISSUE TITLE
点击翻译后 但是并没有进行翻译

### ISSUE THREAD

**Issue by KANNADQINE** [immersive-translate/immersive-translate#219]
重装+试了多个翻译服务都不行
前几天刚装好的时候可以翻译，今天打开浏览器要用的时候 不起作用了

**Comment by KANNADQINE** [comment]
![1](https://user-images.githubusercontent.com/86684100/224335239-d61f3792-ce27-422f-8a44-0271d4693643.png)
也换了好几个网页 都试了下 都不能翻译

**Comment by theowenyoung** [comment]
amazon.com 做了特殊适配，但是没有照顾到首页，试试搜索一个商品，列表页会被翻译。或者还有个办法，就是点击【更多】 ，切换到翻译全部区域。

**Comment by KANNADQINE** [comment]
原来如此 多谢
