### ISSUE TITLE
[Bug]: 使用除通用之外的 Ai 专家会导致富文本失效

### ISSUE THREAD

**Issue by shinexoh** [immersive-translate/immersive-translate#2190]
### 插件版本号 | Version

1.10.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在各种网站上使用 Ai 专家会导致富文本翻译失效，但是除了将 Ai 专家换成默认的“通用”就能正常翻译富文本，下面拿推特举例。

下面是“通用” Ai 专家，会正常翻译富文本

![image](https://github.com/user-attachments/assets/0c15ce17-bf24-4906-b2b0-c13e4c99e9de)

下面是“twitter增强器”和“科技翻译大师” Ai专家

![image](https://github.com/user-attachments/assets/0e330c15-f23b-496b-86ef-41620dab61bd)
![image](https://github.com/user-attachments/assets/a7d73de8-53f9-4c5b-8be6-b4f3be85c348)

### 出现问题的网址 | URL

x.com

### 重现步骤 | To Reproduce

1. 使用 openai 翻译
2. 把 ai 专家切换到除通用之外的，比如 twitter 翻译增强器

**Comment by TaoLoading** [comment]
这个问题是与提示词有关，后续我们会完善 AI 专家的提示词。如果你有效果更好的提示词可以在插件【AI 专家】底部【添加自定义 AI 专家】，同时也欢迎一起优化我们的官方提示词仓库，在这里：[prompts](https://github.com/immersive-translate/prompts)
