### ISSUE TITLE
部分网页的顶部的/上方的导航栏/菜单栏包含下拉菜单翻译不到

### ISSUE THREAD

**Issue by fangquinlan** [immersive-translate/immersive-translate#2193]
### 您希望的更新和改进是什么 | Update or Improve

例如`https://mgimo.ru/` 
![image](https://github.com/user-attachments/assets/044bc6c2-98cb-4902-bae3-256ce3509beb)

**Comment by keyboard3** [comment]
插件默认翻译主要内容区域，上方标题栏大部分情况显示会破坏排版所以默认没有翻译。可以通过开启鼠标悬停强制翻译
后面会考虑在仅译文模式下，针对上述区域也默认进行翻译
