### ISSUE TITLE
[Bug]: Skipping issue in whole page translation and minor errors in pdf output.

### ISSUE THREAD

**Issue by qorenx** [immersive-translate/immersive-translate#2194]
### 插件版本号 | Version

1.10.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

1. Problem: I have an HTML text that is about 500kb in size. It translates. However, it skips %2-3 of the text. I right click and say "Translate the entire page" with the built-in translator. It translates that part like that. However, the application immersivetranslate does not translate this %2-3 of the text even if I undo and translate it again. The worst thing is that it does it if I try a few times. After translating the entire page, it should check again.
2. Problem: When we translate a PDF, I want to get only the translated PDF output. I tried a few times. It always gives double translations. Then I separate the numbers like even/odd in the application, it takes a long time. Similarly, when doing PDF translation, it can make incomplete translations. PDF outputs also take a long time. I give a PDF as text. It should come out as a PDF as text. Should I say, it is in a picture style, it comes out crooked. The texts do not fit exactly. I couldn't figure out if the person who made the application did not use it.

### 出现问题的网址 | URL

https://app.immersivetranslate.com/html/?utm_source=extension&utm_medium=extension&utm_campaign=float_ball_popup_more

**Comment by keyboard3** [comment]
For the problem you mentioned above, please provide a screenshot of the problem and the reproduction path including the source file.

**Comment by keyboard3** [comment]
No feedback yet， Close this issue
