### ISSUE TITLE
[Bug]: 部分元素未翻译

### ISSUE THREAD

**Issue by baagod** [immersive-translate/immersive-translate#2196]
### 插件版本号 | Version

1.10.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

谷歌应用商店

### 请描述这个Bug | Describe the bug

一开始感觉很惊艳，后面越来越烂，全屏翻译好多内容消失，甚至部分元素被屏蔽，根本用不了！

### 出现问题的网址 | URL

大部分网站。包括但不限于 medium.com、github.com、https://www.manning.com/books/get-programming-with-go

### 重现步骤 | To Reproduce

网页全屏翻译大部分内容、元素缺失。

## github
![582a6ec667775c0c7aa8b4368010d6a](https://github.com/user-attachments/assets/24a2c546-ca11-44d5-9b77-591bb2ab3f41)
----
![58ffd26f883ccda9462192ccb5f0ec6](https://github.com/user-attachments/assets/ad4e31c6-7357-4075-8e84-a80e3208af55)

## medium
![2cb55652d1759870752c48852734964](https://github.com/user-attachments/assets/d2c63642-048d-4810-9a7f-0f6fee5e9755)
----
![ac7f332653b0b204a13d8289341a296](https://github.com/user-attachments/assets/4fecd3fd-3462-4d26-a6ae-0f7e24fec564)

### https://pkg.go.dev/github.com/huandu/go-sqlbuilder
![618339cd4149ce3df9ddce7d2f68e9e](https://github.com/user-attachments/assets/75f9d814-462b-4070-829c-fcfa79ae0d8d)
----
![73216dbf633a89199c8fb5ca0027146](https://github.com/user-attachments/assets/77e4f6da-86f1-4823-954e-b6e469e2f3bd)

### https://www.manning.com/books/get-programming-with-go
![154d92bd0a811acd3fa26060847ad51](https://github.com/user-attachments/assets/55520a07-f983-4f9e-802e-4a54241f012b)
----
![12ff2983f2a5b344ae4fe8cd2cb1b2d](https://github.com/user-attachments/assets/e173b126-82d1-4a9e-92d4-6c5a8ac3451d)

**Comment by keyboard3** [comment]
标题请不要带攻击性字眼，请正常反馈

**Comment by theowenyoung** [comment]
第一个 Github 请给一下URL可以吗？

medium 未复现：

![CleanShot 2024-10-28 at 03 14 38@2x](https://github.com/user-attachments/assets/f0b6245e-57db-46d9-afe6-81952b77f98f)


第三个也没有复现，可能和你用的翻译服务有关系？你用的是什么翻译服务？

![CleanShot 2024-10-28 at 03 16 05@2x](https://github.com/user-attachments/assets/f4a75f3c-0076-4fa5-ab05-ebb342174e40)


https://www.manning.com/books/get-programming-with-go 可以复现。

**Comment by baagod** [comment]
github 上的 Readme 只要有标题的翻译都会直接缺失。看了很多网站，【仅译文】模式大部分都丢失标题、列表。

不知道为什么这么久没有人反馈这个问题，而且我反馈了，复现一直说是好的，我不知道这是为什么，我谷歌浏览器，Edge 浏览器和 Brave 浏览器都是这样。

可以以这简单的网页为例：https://medium.com。我一直切换翻译服务：谷歌、微软、腾讯交互、Silicon Cloud。然后在刷新网页，重新【仅译文】翻译，全部没用，就如同我反馈中所截图的那样。

但是使用双语翻译就很正常，或者双语翻译后转【仅译文】也正常，因为那样就不是重新翻译了，只是把翻译原文隐藏。

**Comment by baagod** [comment]
现在似乎又正常了，不知道是什么原因，总之非常感谢！
