### ISSUE TITLE
有些亚马逊商品评论翻译不完整

### ISSUE THREAD

**Issue by Andy-AO** [immersive-translate/immersive-translate#22]
![image](https://user-images.githubusercontent.com/38101170/212794432-cd49e25b-1873-4ca4-b12c-5371f1ba98c4.png)

有的完整有的不完整，这可能是 bug

# links

- [Amazon.com: Betrayal by the Brain: The Neurologic Basis of Chronic Fatigue Syndrome, Fibromyalgia Syndrome, and Related Neural Network eBook : Goldstein, Jay: Books --- Amazon.com：大脑的背叛：慢性疲劳综合症、纤维肌痛综合症和相关神经网络的神经学基础电子书：Goldstein, Jay：书籍](https://www.amazon.com/Betrayal-Brain-Neurologic-Syndrome-Fibromyalgia-ebook/dp/B00G24VTDK)

**Comment by theowenyoung** [comment]
0.2.1 已修复

**Comment by Andy-AO** [comment]
> 0.2.1 已修复

新版本的确有问题已解决，但似乎引入了新的问题，一直转圈不会停止

![image](https://user-images.githubusercontent.com/38101170/213293249-4b363675-ef59-4791-b74c-7fc213bfb121.png)

![image](https://user-images.githubusercontent.com/38101170/213293287-97168b11-1279-4eca-893e-aa97f55cf1e5.png)

**Comment by Andy-AO** [comment]
经测试问题已修复，谢谢！~
