### ISSUE TITLE
[Bug?] OpenAI translates from bottom to top and discrepancies in translation texts

### ISSUE THREAD

**Issue by iG8R** [immersive-translate/immersive-translate#220]
Hi.

Stumble upon a weird issue.
When using OpenAI, the page is translated from bottom to top, and sometimes there are significant differences between translated texts obtained using Immersive Translate.
Maybe because of such a strange direction of translation such discrepancies appear?

PS. In the bellow video I also use "Google select text translator" userscript https://greasyfork.org/en/scripts/36842-google-select-text-translator

PPS. https://www.ptwxz.com/html/8/8989/5883506.html

[Immersive-Translate-564-OpenAI-FromBottom-DifTranslation-Video_2023-03-10_181455.webm](https://user-images.githubusercontent.com/11407417/224373767-9f302ec1-400a-4e2e-aacb-5e07be783e0c.webm)

**Comment by theowenyoung** [comment]
we send multiple requests in the same time, sometimes, the later requests get a faster response, so you can see the bottom text was translated first. 

there are differences between immersive translate and the others, may be because the prompt text, and even the prompt text is same, the result may not be the same for OpenAI.

**Comment by iG8R** [comment]
Any site that I translated with the OpenAI service has this issue - translation from bottom to top.
So, IMHO, it's not occasionally occurred situation. Maybe that's exactly how OpenAI works - the last request is processed first.
You are right, OpenAI translation result differs depending on how the OpenAI service receives the text, even the same text with and without quotes will be translated with the different results.
Is it possible to have an option to change the sequence in which the translated text sends to the OpenAI service - the bottom text will be sent first and the top text last?
Also, why the whole page is translated at once while the option "Translate to the bottom of the page immediately after opening the page?" is off?

**Comment by theowenyoung** [comment]
> Is it possible to have an option to change the sequence in which the translated text sends to the OpenAI service - the bottom text will be sent first and the top text last?

it sounds weird to offer an option like this... and it's also  not easy, cause we walk the dom tree from to bottom.

> Also, why the whole page is translated at once while the option "Translate to the bottom of the page immediately after opening the page?" is off?

we want to reduce the api requests. but if you don't care the api fees, you can enable this  option, it surely has a better experience.

**Comment by iG8R** [comment]
> > Also, why the whole page is translated at once while the option "Translate to the bottom of the page immediately after opening the page?" is off?
> 
> we want to reduce the api requests. but if you don't care the api fees, you can enable this option, it surely has a better experience.

On the contrary, I thought that when "Translate to the bottom of the page immediately after opening the page?" is OFF the page should be translated in parts, starting with the visible part and as you read and scroll down, all new sections of the text will be translated. But with the OpenAI service, the behavior looks like it always translates the entire page regardless of this option.

**Comment by theowenyoung** [comment]
https://github.com/immersive-translate/immersive-translate/blob/fddfbd6567c22079306540337101f571e147dfab/docs/buildin_config.json#L82

ohoh, there is another special option for openai, 

```
"immediateTranslationTextCount": 10000
```

cause openai is so slow, so we want to  ensure the bottom parts are translated as soon as possible. but you can override the default option on developer settings by:

```
 "translationServices": {
    "openai": {
      "placeholderDelimiters": [
        "{{",
        "}}"
      ],
      "immediateTranslationTextCount": 10000,
      "translationDebounce": 300,
      "newlinePlaceholderDelimiters": [
        "\n\n###",
        "###\n\n",
        "\n?\n?###\\d+###\n?\n?"
      ]
    }
}
```

**Comment by iG8R** [comment]
Oh, thank you! I'll try it.

**Comment by iG8R** [comment]
IMHO, there is something wrong with the ImmersiveTranslate text parser for OpenAI.
Very often I encounter omissions in the translated text and double `"` and triple single ` ``` ` quotes  in the translated text where they are not present in the original text at all. Moreover, this happens with the identical original text but on different sites.
Maybe because of these errors in the text parsing discrepancies in the translations occur?
Could you please check it?

![ImmersiveTranslate-773-BlankParagraph-Screenshot 2023-03-12 at 02-56-40](https://user-images.githubusercontent.com/11407417/224582008-7c74620e-a35d-4ee1-a7ab-215dec3d722b.jpg)
<img width="1900" alt="ImmersiveTranslate-BlankParagraph-804-Comparison-2023-03-13_013424" src="https://user-images.githubusercontent.com/11407417/224582013-e34d1e8b-0e80-495d-a8b3-546872412548.png">

**Comment by theowenyoung** [comment]
okay, thanks for the feedback, i'll investigate it. maybe i should change the prompts

**Comment by iG8R** [comment]
More examples:

Ch.867 https://www.kdxs.net/chapter/6040/7721391
<img width="949" alt="Screenshot 2023-03-13 at 06-12-34 丹道宗師_第867章 你要征服誰？！_只是小蝦米著_蝌蚪小說 --- Dan Dao Grandmaster_Chapter 867 Who Do You Want to Conquer !_Just a Small Shrimp's Work_Tadpole Novel" src="https://user-images.githubusercontent.com/11407417/224619545-08135dec-163c-42e4-af2b-bfaf471f8d0d.png">


Ch.863 https://www.kdxs.net/chapter/6040/7721387
<img width="949" alt="Screenshot 2023-03-13 at 05-03-50 丹道宗師_第863章 圣地往事_只是小蝦米著_蝌蚪小說 --- Dan Dao Grandmaster_Chapter 863 Holy Land Past_Just a Small Shrimp Writing_Tadpole Novel" src="https://user-images.githubusercontent.com/11407417/224619619-dca74ce1-3bb1-434f-9a8c-4deb718b0938.png">



Ch.862 https://www.kdxs.net/chapter/6040/7721386
<img width="949" alt="Screenshot 2023-03-13 at 04-49-45 丹道宗師_第862章 小獸相護_只是小蝦米著_蝌蚪小說 --- Dan Dao Grandmaster_Chapter 862 Little Beast Protection_Just a Small Shrimp Wearing_Ketoad Novel" src="https://user-images.githubusercontent.com/11407417/224619646-09753a90-6963-4465-bd47-ccfcab35eb87.png">



Ch.855 https://www.kdxs.net/chapter/6040/7721379
<img width="949" alt="Screenshot 2023-03-13 at 03-43-04 丹道宗師_第855章 太昊圣湖_只是小蝦米著_蝌蚪小說 --- Dan Dao Grandmaster_Chapter 855 Taihao Holy Lake_Just a Small Shrimp Writing_Tadpole Novel" src="https://user-images.githubusercontent.com/11407417/224619720-058d5cb1-f9ac-4240-ad25-30a8bfc76ea2.png">
<img width="949" alt="Screenshot 2023-03-13 at 03-42-42 丹道宗師_第855章 太昊圣湖_只是小蝦米著_蝌蚪小說 --- Dan Dao Grandmaster_Chapter 855 Taihao Holy Lake_Just a Small Shrimp Writing_Tadpole Novel" src="https://user-images.githubusercontent.com/11407417/224619724-364bdeab-3c5f-403f-8cc1-72a670f838b9.png">
<img width="949" alt="Screenshot 2023-03-13 at 03-37-43 丹道宗師_第855章 太昊圣湖_只是小蝦米著_蝌蚪小說 --- Dan Dao Grandmaster_Chapter 855 Taihao Holy Lake_Just a Small Shrimp Writing_Tadpole Novel" src="https://user-images.githubusercontent.com/11407417/224619725-c11b02e0-a971-46d5-99f8-114128b85be6.png">



Ch.853 https://www.kdxs.net/chapter/6040/7721377
<img width="949" alt="Screenshot 2023-03-13 at 03-21-50 丹道宗師_第853章 不是尋常之火_只是小蝦米著_蝌蚪小說 --- Dan Dao Grandmaster_Chapter 853 Not Ordinary Fire_Just Little Shrimp Wearing_Tadpole Novel" src="https://user-images.githubusercontent.com/11407417/224619751-ed9c09f2-ff6f-4d91-b0ac-5016ba598520.png">



Ch.852 https://www.kdxs.net/chapter/6040/7721376
<img width="949" alt="Screenshot 2023-03-13 at 03-12-44 丹道宗師_第852章 御千秋_只是小蝦米著_蝌蚪小說 --- Dan Dao Grandmaster_Chapter 852 Yu Qianqiu_Just a Small Shrimp Writing_Tadpole Novel" src="https://user-images.githubusercontent.com/11407417/224619777-676f8267-56a2-4164-878d-a79a5c280b82.png">
<img width="949" alt="Screenshot 2023-03-13 at 03-07-34 丹道宗師_第852章 御千秋_只是小蝦米著_蝌蚪小說 --- Dan Dao Grandmaster_Chapter 852 Yu Qianqiu_Just a Small Shrimp Writing_Tadpole Novel" src="https://user-images.githubusercontent.com/11407417/224619780-13ddee80-103b-42e1-b4a9-ec75037fcea6.png">
<img width="949" alt="Screenshot 2023-03-13 at 03-04-57 丹道宗師_第852章 御千秋_只是小蝦米著_蝌蚪小說 --- Dan Dao Grandmaster_Chapter 852 Yu Qianqiu_Just a Small Shrimp Writing_Tadpole Novel" src="https://user-images.githubusercontent.com/11407417/224619783-b7fbba0c-e7a5-4360-b681-66cb17bbfbde.png">


Ch.851 https://www.kdxs.net/chapter/6040/7721375
<img width="949" alt="Screenshot 2023-03-13 at 02-56-47 丹道宗師_第851章 遭遇截殺_只是小蝦米著_蝌蚪小說 --- Dan Dao Grandmaster_Chapter 851 Encountering Ambush_Just a Small Shrimp Writing_Tadpole Novel" src="https://user-images.githubusercontent.com/11407417/224619819-87324532-becb-487f-88cb-03a33e2e6acb.png">
<img width="949" alt="Screenshot 2023-03-13 at 02-54-13 丹道宗師_第851章 遭遇截殺_只是小蝦米著_蝌蚪小說 --- Dan Dao Grandmaster_Chapter 851 Encountering Ambush_Just a Small Shrimp Writing_Tadpole Novel" src="https://user-images.githubusercontent.com/11407417/224619823-e5fb4e96-a6d2-4517-89fe-1a737aa0eaa4.png">

**Comment by iG8R** [comment]
Also constantly facing the problem of "underloading" of the translation without any error reports - permanent spinning icon.
Is there any way to resolve this without completely reloading the page?
E.g.

Ch.857 https://www.kdxs.net/chapter/6040/7721381
<img width="949" alt="Screenshot 2023-03-13 at 04-02-40 丹道宗師_第857章 百煉金光_只是小蝦米著_蝌蚪小說 --- Dan Dao Grandmaster_Chapter 857 Hundred Refining Golden Light_Just a Small Shrimp Wearing_Kedou Novel" src="https://user-images.githubusercontent.com/11407417/224619680-ffea8718-0d42-494c-8b3b-dd48239efb9d.png">

**Comment by iG8R** [comment]
Here are examples of translations using Immersive Translate, which even have the opposite or other emotional meaning compared to the original texts and are translated using Immersive Translate, but only in one sentence, and not by combining several together.
Maybe when Immersive Translate combines several sentences, adds some control characters that change the way OpenAI translates text?

Ch.886 - https://www.kdxs.net/chapter/6040/7721410

![Screenshot 2023-03-13 at 14-38-19 丹道宗師_第886章 大戰降至_只是小蝦米著_蝌蚪小說 --- Dan Dao Grandmaster_Chapter 886 The Great War is Coming_Just a Small Shrimp Writing_Tadpole Novel](https://user-images.githubusercontent.com/11407417/224723581-de8fff9c-d5b3-451b-b52b-8a34741b38cd.png)


Ch.881 - https://www.kdxs.net/chapter/6040/7721405

![Screenshot 2023-03-13 at 14-40-20 丹道宗師_第881章 不能相比_只是小蝦米著_蝌蚪小說 --- Dan Dao Grandmaster_Chapter 881 Cannot Be Compared_Just a Small Shrimp Writing_Tadpole Novel](https://user-images.githubusercontent.com/11407417/224723668-ceb93805-a3fc-4854-b2c8-5c95246367b9.png)

**Comment by theowenyoung** [comment]
I believe it's ok now.
