### ISSUE TITLE
[Bug]: <ruby> tags (used to display furigana above kanji) breaks Japanese translation

### ISSUE THREAD

**Issue by M4rtinK** [immersive-translate/immersive-translate#2200]
### 插件版本号 | Version

1.10.2

### 平台 | Platform

Windows, Linux, Android

### 浏览器 | Browsers

Firefox, Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

I have noticed that if a web page uses <ruby> tags to display furigana (eq. phonetic reading) above Japanese kanji characters, immersive-translate includes both the kanji & its reading when translating a paragraph. As a result the text that gets translated usually does not make sense.

A text without furigana & ruby tags gets translated without issues.

I've tried this on a NHK easy news (a web page that has furigana by default) article (https://www3.nhk.or.jp/news/easy/ne2024101811389/ne2024101811389.html#) & the title:

お年寄りの車いす「シニアカー」9年間で25人が亡くなった

Gets translated as:

Elderly Car "Senior Car" 9 years ago, 25 people died

When I select the same line, right click and select "Translate" form the context menu, the same line is translated correctly:

25 people died in 9 years using wheelchair for the elderly ``Senior Car''

With a website without furigana, the translation works correctly, for example (https://www3.nhk.or.jp/news/html/20241020/k10014614231000.html):

【日曜討論】与野党9党幹部 経済政策のあり方めぐり議論

Gets translated correctly right away:

Sunday Debate: Leaders of the Nine Ruling and Opposition Parties Discuss Economic Policy

I've enabled debugging prints and the difference in input strings can be clearly seen:

`Immersive Translate DEBUG: on paragraph お<c0>年寄<c1>としよ</c1></c0>りの<c2>車<c3>くるま</c3></c2>いす「シニアカー」9<c4>年<c5>ねん</c5></c4><c6>間<c7>かん</c7></c6>で25<c8>人<c9>にん</c9></c8>が<c10>亡<c11>な</c11></c10>くなった `

Even though pureText seems almost fine, but note the extra whitespace:

`pureText: " お 年寄 りの 車 いす「シニアカー」9 年 間 で25 人 が 亡 くなった "`

The resulting text still gets corrupted by all those ruby tags:

`Elderly <ruby data-immersive-translate-walked="99284561-a502-419c-96ca-f838a81e59ac"><rt>and Shiyori's</rt></ruby> <ruby data-immersive-translate-walked="99284561-a502-419c-96ca-f838a81e59ac">Car<rt></rt></ruby> "Senior Car" 9 <ruby data-immersive-translate-walked="99284561-a502-419c-96ca-f838a81e59ac">years ago<rt></rt></ruby><ruby data-immersive-translate-walked="99284561-a502-419c-96ca-f838a81e59ac">, 25<rt></rt></ruby> people died<ruby data-immersive-translate-walked="99284561-a502-419c-96ca-f838a81e59ac"><rt></rt></ruby><ruby data-immersive-translate-walked="99284561-a502-419c-96ca-f838a81e59ac"><rt></rt></ruby>`

In comparison, debug output for that regular NHK article without furigana:

`Immersive Translate DEBUG: on paragraph 【日曜討論】与野党9党幹部 経済政策のあり方めぐり議論` 

Pure text looks identical, as expected:

`pureText: "【日曜討論】与野党9党幹部 経済政策のあり方めぐり議論 "`

Target text ends up fine:

`"Sunday Debate: Leaders of the Nine Ruling and Opposition Parties Discuss Economic Policy"`

### 出现问题的网址 | URL

https://www3.nhk.or.jp/news/easy/ne2024101811389/ne2024101811389.html#

### 重现步骤 | To Reproduce

1. install Firefox
2. install immersive-translate
3. configure immersive-translate to translate from Japanese to English
4. visit https://www3.nhk.or.jp/news/easy/ne2024101811389/ne2024101811389.html#
5. press the floating icon to translate the page
6. note the nonsensical translation due to furigana being included to the translation of the paragraph, confusing the translation process

### 补充说明 | Additional context

I've started using immersive translate in around April/May 2024 & I'm sure translations of text with furigana worked back then - the furigana text was correctly ignored & the translation was correct thanks to that. But some time after that, immersive translate started including furigana into the text of the paragraph & this broke translations of any text with furigana.

BTW, one more way how to trigger this issues, is to use an extension to add furigana to a web page - such as for example:
https://addons.mozilla.org/cs/firefox/addon/furiganaize/

Those addons just add the `<ruby>` tags at runtime & if immersive-translate is triggered afterwards, the same breakage that occurs on NHK Easy News (that has furigana by default) happens.

**Comment by M4rtinK** [comment]
One more thing to add - I've seen this same thing happen across Firefox & Chrome and on Window, Linux & on Android (eq. Firefox for Android with the immersive-translate extension).

**Comment by keyboard3** [comment]
Open this [address](https://www3.nhk.or.jp/news/easy/ne2024101811389/ne2024101811389.html#?imt_refresh_rule=1) and try again

**Comment by M4rtinK** [comment]
Works perfectly now, thanks a lot! :)
