### ISSUE TITLE
[Bug]: 在英文网站的客服聊天对话框中使用增强式输入这个功能，弹出提示对话框，无法正常关闭

### ISSUE THREAD

**Issue by nicesky365** [immersive-translate/immersive-translate#2201]
### 插件版本号 | Version

1.10.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

在英文网站的客服聊天对话框中使用增强式输入这个功能，弹出提示对话框，无法正常关闭

### 出现问题的网址 | URL

很多有实时聊天客服的英文网站页面

### 补充说明 | Additional context

![1](https://github.com/user-attachments/assets/35f8febb-53eb-4a99-93f7-30cc393174cf)

**Comment by keyboard3** [comment]
直接点击下面2个按钮点击都没有反应吗？还是点按钮之前还有其他什么操作吗？

**Comment by nicesky365** [comment]
肯定都没反应，如果能正常，我还发帖吗，只能重新刷新页面，重新开始聊天，你这个地方是一个bug，肯定是和页面某个地方有冲突导致类似死锁的现象。
还有就是这个情况根本不应该弹窗，如果不想用输入式增强，我可以在设置中关闭他，我既然已经打开了，而且现在也触发了，就是想用，你弹窗的目的是什么，让用户认为你软件水平很高，还是这个软件交互性很好，很人性化。拜托，你能不能站在使用者的角度考虑问题直接去掉这种弹窗，啥事没有，你这不是画蛇添足吗

**Comment by nicesky365** [comment]
要的就是简约，实用，不是那些花里胡哨的功能，做软件需求分析，麻烦你站在使用者角度考虑，不要自己闭门造车，全凭想象

**Comment by keyboard3** [comment]
这个弹窗目的是为了用户无意间触发该功能的时候给的提示，给用户继续使用或者禁用的一个选择。
询问点击按钮的表现是为了确认这个bug的具体表现，方便定位问题。因为我们没能复现该问题，所以需要更多的信息才能定位该问题
当然为了避免这类情况，设置页中我们考虑再提供一个开关永久不提示

**Comment by nicesky365** [comment]
这个问题确实有，具体原因我也不知道，目前也只能只有这样，建议在设置中增加禁止弹窗提示即可，这样不用加代码，不方便，如果在很多电脑上都要用，都加代码好麻烦，直接做个开关在设置中
