### ISSUE TITLE
关于翻译pdf的问题

### ISSUE THREAD

**Issue by 3073554169** [immersive-translate/immersive-translate#2202]
### 您希望的更新和改进是什么 | Update or Improve

我希望能设置不自动翻译一些公式 因为公式翻译过来就会形成乱码 而且不能手动撤销一小段公式的翻译 因为公式不能像单词那样形成一个文本框来取消翻译

### 补充说明 | Additional context

nothing

**Comment by keyboard3** [comment]
免费对照工具无法识别出是不是公式， https://immersivetranslate.com/zh-Hans/docs/pdf-helper/
