### ISSUE TITLE
[Bug]: 我完全无法使用输入框增强翻译功能了, 敲击三次空格后没有任何反应.

### ISSUE THREAD

**Issue by shawchen123** [immersive-translate/immersive-translate#2203]
### 插件版本号 | Version

0.5.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

我完全无法使用输入框增强翻译功能了, 敲击三次空格后没有任何反应.

**Comment by keyboard3** [comment]
你这版本不对，0.5.5 太旧了

**Comment by shawchen123** [comment]
> 你这版本不对，0.5.5 太旧了

不是055, 我写错了, 就是最新版本1.10.2

**Comment by keyboard3** [comment]
不要在浏览器默认页使用，你可以在 https://www.bing.com/ 的输入框试下，记得空格快一点

**Comment by keyboard3** [comment]
暂无反馈 关闭此issue
