### ISSUE TITLE
[Bug]: Clarivate搜索结果页面，翻译的内容会被页面上标黄的搜索关键词打断

### ISSUE THREAD

**Issue by oxygen-dioxide** [immersive-translate/immersive-translate#2205]
### 插件版本号 | Version

1.10.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/user-attachments/assets/fe233d01-c954-465a-bb28-c2f97d901932)
例如这里，“小说”就很明显是把Novel这个单词单独拿出来翻译了，正确的翻译是“新型”。每个标黄的关键词都会和前后文断开。

作为对比，论文详情页面没这问题
![image](https://github.com/user-attachments/assets/48f9e9a8-6d86-4944-b6f5-7ef8ed11a484)

### 出现问题的网址 | URL

https://webofscience.clarivate.cn/wos/alldb/summary/e584f57f-6fdc-4d99-a774-bc21850cbeca-0111b470e7/relevance/1

### 重现步骤 | To Reproduce

1. 在webofscience上搜索任意内容
2. 用immersive translate翻译

**Comment by keyboard3** [comment]
这是翻译服务针对高亮关键词的富文本翻译时没有很好的联系上下文，你可以切换到其他翻译服务
![QQ_1729504917907](https://github.com/user-attachments/assets/a637e4e9-51be-40b4-8b3d-8f38cb93f55b)
