### ISSUE TITLE
[Bug]: kickstarter始终展示为"仅译文"而非设置中选择的"双语对照"

### ISSUE THREAD

**Issue by puttin** [immersive-translate/immersive-translate#2208]
### 插件版本号 | Version

1.10.2

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

未设置kickstarter为仅译文
![image](https://github.com/user-attachments/assets/8590f0bd-0ff6-4973-9e0e-75cd54f534a0)

### 出现问题的网址 | URL

https://kickstarter.com/

### 重现步骤 | To Reproduce

1. 打开kickstarter
2. 使用插件翻译

### 补充说明 | Additional context
bug展示
![20241022140655_rec_](https://github.com/user-attachments/assets/58be2dc8-2325-43d8-945b-b2b653b32114)
对应页面：https://www.kickstarter.com/projects/peak-design/the-outdoor-line-by-peak-design/faqs

**Comment by keyboard3** [comment]
点击下悬浮球旁边的反馈按钮，它会收集日志给开发

**Comment by puttin** [comment]
> 点击下悬浮球旁边的反馈按钮，它会收集日志给开发

已操作

**Comment by puttin** [comment]
可能知道原因了。

该网站语言自动设置为“繁体中文”
![20241022143007_rec_](https://github.com/user-attachments/assets/797fe404-62a7-429b-b6c5-bcf1860df52e)


可能命中了插件中的设置：
![image](https://github.com/user-attachments/assets/de14d47e-6ef7-48fe-b8b8-bc7eb8155b71)

将网站设置成英语后功能正常

**Comment by keyboard3** [comment]
是的，这是因为该网站页面语言是繁体中文，命中繁体简繁互换的逻辑了。可以通过在面板上临时让这个页面开启双语效果
![QQ_1729578805585](https://github.com/user-attachments/assets/90eb4cd1-b74e-41a9-9381-7335fe83f568)

**Comment by puttin** [comment]
现在有点好奇是怎么检测该网站为zh-tw了

![image](https://github.com/user-attachments/assets/9609bf9a-cb9e-44b7-85fc-da7b80e33b08)

网站的meta信息中确实有zh标识

但正文绝大多数内容都是英文

**Comment by keyboard3** [comment]
chrome浏览器提供  chrome.tabs.detectLanguage api 检测tab 语言
![QQ_1729579887516](https://github.com/user-attachments/assets/3066e609-cc2d-414d-bab5-429f7ee4e391)
