### ISSUE TITLE
vivaldi 浏览器装上没法用

### ISSUE THREAD

**Issue by yds1024** [immersive-translate/immersive-translate#221]
vivaldi 也是chrome 内核的浏览器，但是这个插件装上没法使用，其他 chrome 浏览器的插件都正常使用

**Comment by theowenyoung** [comment]
是快捷键无法使用，还是整个插件无法使用?

如果是快捷键的话，似乎是Vivaldi的一个bug： https://www.reddit.com/r/vivaldibrowser/comments/qy78fs/keyboard_shortcuts_for_extensions_dont_seem_to/

**Comment by yds1024** [comment]
点图标，没有下拉菜单

**Comment by theowenyoung** [comment]
我这测试是可以用的，mac. 最新版 vivaldi.

<img width="1293" alt="Screenshot 2023-03-11 at 18 10 11" src="https://user-images.githubusercontent.com/62473795/224478451-be234735-caf0-42b5-b97c-72d0037a4b4b.png">

**Comment by yds1024** [comment]
感谢解答，我重装浏览器看看。

**Comment by yds1024** [comment]
重装就可以了
