### ISSUE TITLE
希望可以自定义英文翻译对应的词语

### ISSUE THREAD

**Issue by dugumoss** [immersive-translate/immersive-translate#2211]
### 您希望的更新和改进是什么 | Update or Improve

使用过一段时间，十分好用。为开发人员点赞。
在用它进行全网页翻译后，由于软件翻译水平的局限性。有些词汇，句子翻译得十分不准确。
机翻的常规表现，不能很好的翻译成中文。往往需要开启译文临时编辑来人工校对。
但是可能浏览器的限制，开启译文临时编辑偶尔会造成网页崩溃。
这样，我每次花费大精力人工校对编辑的工作就付之流水。
对于某些特定词汇，翻译器并不能准确翻译出来。
我想，如果有一个专门的容器来自定义英文词汇对应的中文。这样会大大方便我的使用。
这是我的建议，希望后续能实现这个功能

### 补充说明 | Additional context

举个例子。比如 BMW， BMW往往是宝马汽车品牌的缩写。但是自从黑神话悟空游戏出来后。BMW （Black Myth: Wukong）又代表黑神话。在开启软件翻译后，机翻往往会把BMW翻译成宝马。翻译体现十分不好。而开启的临时编辑又不能批量操作。所以十分不便利。

**Comment by keyboard3** [comment]
有这个功能 可以在这里配置 https://immersivetranslate.com/zh-Hans/docs/advanced/#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%93%E4%B8%9A%E6%9C%AF%E8%AF%AD%E7%9A%84%E7%BF%BB%E8%AF%91
