### ISSUE TITLE
edx线上课程网站，不能的翻译文章内容

### ISSUE THREAD

**Issue by AfraidofTime** [immersive-translate/immersive-translate#2213]
### 您希望的更新和改进是什么 | Update or Improve

希望能够翻译课程中文章内容

### 补充说明 | Additional context

![Uploading 屏幕截图 2024-10-23 000100.png…]()

**Comment by keyboard3** [comment]
图片没有上传完，你直接在悬浮球旁边的反馈按钮反馈下吧

**Comment by AfraidofTime** [comment]
谢谢你的回复，我已经按你要求的操作反馈了











刘浪


---Original---
From: ***@***.***&gt;
Sent at: 2024年10月23日(Wed) AM9:36
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [immersive-translate/immersive-translate] edx线上课程网站，不能的翻译文章内容 (Issue #2213)




 
图片没有上传完，你直接在悬浮球旁边的反馈按钮反馈下吧

**Comment by keyboard3** [comment]
看到了，不过你的正文我这边看不到，感觉似乎是一个文档？
![QQ_1729674136490](https://github.com/user-attachments/assets/3e5c2318-a9c9-4ed2-9584-87bcf5522576)

**Comment by AfraidofTime** [comment]
ok,既然是文档而不能翻译，那就解决了，谢谢你的回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "immersive-translate/immersive-translate"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月23日(星期三) 下午5:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [immersive-translate/immersive-translate] edx线上课程网站，不能的翻译文章内容 (Issue #2213)





 
看到了，不过你的正文我这边看不到，感觉似乎是一个文档？
 QQ_1729674136490.png (view on web)
