### ISSUE TITLE
[Bug]: "<"号有关的翻译混乱问题没有完全解决

### ISSUE THREAD

**Issue by ysdj** [immersive-translate/immersive-translate#2214]
### 插件版本号 | Version

1.10.3

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

仍然有部分情况出现<6 id=5>之类的混乱翻译，用的谷歌翻译，如图所示

![image](https://github.com/user-attachments/assets/07b66251-f9b3-4e9f-a9a3-3aa313cd54df)
![image](https://github.com/user-attachments/assets/26987ffa-8320-498f-9d5b-04618cfe9659)

### 出现问题的网址 | URL

https://ascopubs.org/doi/abs/10.1200/jco.2011.29.15_suppl.5087 和 https://ascopubs.org/doi/abs/10.1200/jco.2006.24.18_suppl.15054

### 补充说明 | Additional context

关联问题：https://github.com/immersive-translate/immersive-translate/issues/2163

**Comment by keyboard3** [comment]
油猴脚本更新1.10.5再试下
