### ISSUE TITLE
[Bug]: 输入框增强无法撤销已经翻译的内容！！！

### ISSUE THREAD

**Issue by Ahdjdus** [immersive-translate/immersive-translate#2215]
### 插件版本号 | Version

1.10.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

Ctrl+Z 不起作用，无法撤销已经翻译的内容回到原来的语言
![image](https://github.com/user-attachments/assets/9454fb99-efb2-4476-9045-f3b42b33154f)

**Comment by keyboard3** [comment]
在什么站点的输入框无法撤销，你可以在www.google.com输入框来测试这个撤销功能

**Comment by Ahdjdus** [comment]
感谢您，他现在在 www.google.com 工作良好
![chrome_BuQFlXDBm5](https://github.com/user-attachments/assets/64fd3f93-114c-45fe-9843-be96f15499a0)

之前也是这么测试，但他不起作用，现在他好了
