### ISSUE TITLE
OpenAI翻译乱码 

### ISSUE THREAD

**Issue by Jagerx** [immersive-translate/immersive-translate#222]
<img width="1469" alt="2023-03-11_18-49-20" src="https://user-images.githubusercontent.com/42521386/224480184-6aea85b9-a365-4bd8-af23-69235fec1e7d.png">

插件是TamperMonkey，Safari浏览器，测试Google翻译服务正常。无论重启还是换网页翻译，OpenAI都是乱码，请问何解，谢谢

**Comment by theowenyoung** [comment]
tamperMonkey 的问题， Deepl 在safari的tamper monkey也是这样。 可以换用 userscripts 应该就可以了

**Comment by Jagerx** [comment]
> tamperMonkey 的问题， Deepl 在safari的tamper monkey也是这样。 可以换用 userscripts 应该就可以了

好的，谢谢。首先在MAC的这么贫瘠的插件生态下，还有特别通过JS支持，十分感激。如果插件冲突的话，因为在Tam已经管理了不少JS，再换嫌麻烦，我先用Google翻译。不过有定位冲突点的可能不

**Comment by Jagerx** [comment]
实测userscripts，也是乱码
![WX20230314-170007@2x](https://user-images.githubusercontent.com/42521386/224949451-e4670b37-fc93-4f44-b7df-dce7fae8c451.png)

**Comment by versun** [comment]
请更新下插件，目前最新是0.4.2，我这边测试是正常的
