### ISSUE TITLE
PDF阅读器，希望能增加“仅原文”、“原文+对照翻译”的试图选择

### ISSUE THREAD

**Issue by JokerQianwei** [immersive-translate/immersive-translate#2223]
### 您希望的更新和改进是什么 | Update or Improve

PDF阅读器，希望能增加“仅原文”、“原文+对照翻译”的视图选择

**Comment by demybugs** [comment]
是的，有时我们并不想显示右侧的翻译侧边栏、只想专注于阅读原文。

**Comment by keyboard3** [comment]
阅读的话，直接用浏览器的阅读器就可以了,或者用它阅读 https://mozilla.github.io/pdf.js/web/viewer.html ，只有需要翻译的时候再打开沉浸式翻译
