### ISSUE TITLE
[Bug]: 输入框翻译变成了网页翻译

### ISSUE THREAD

**Issue by Mishasama** [immersive-translate/immersive-translate#2224]
### 插件版本号 | Version

1.10.6

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/user-attachments/assets/a2f6c497-45fe-4c09-a0d5-741af78e3eea)
当输入框翻译网络出错的时候，在弹出的窗口中点击重试触发的不是输入框的重试，而是整个页面的翻译。但页面翻译本来就没有使用，谈何重试？

### 出现问题的网址 | URL

任意

### 重现步骤 | To Reproduce

1. 在输入框打字
2. 按3空格触发翻译
3. 断开网络导致出错
4. 接回网络让其检测
5. 根据提示点击使用其它服务重试

### 补充说明 | Additional context

单纯的没有考虑到这个功能需要重试，结果就调用了同样的提示元素，最后那个按钮被做成了固定的页面翻译重试而不是哪个功能出错就重试哪个。

**Comment by flamintune** [comment]
下个版本修复，这个bug是因为之前新加的一个 翻译错误自动切换可用翻译服务 的优化造成的：

即当前翻译服务失败，会检测可用的翻译服务，并且按钮行为为切换到可用的翻译服务，然后重新开始翻译。

因为之前加的这个特性，以及输入框翻译的错误处理那里没有对这个类型的错误进行判断，从而造成了重试按钮的行为是翻译整个页面
