### ISSUE TITLE
iOS端悬浮窗字幕

### ISSUE THREAD

**Issue by Versahein** [immersive-translate/immersive-translate#2229]
### 您希望的更新和改进是什么 | Update or Improve

咱们 ios 端的沉浸式翻译目前只有 Safari 浏览器插件的版本，会不会考虑以后做一个像 live caption 那样的悬浮窗显示翻译，也可以跨软件自动识别字幕，不用只限制在浏览器里

**Comment by keyboard3** [comment]
夸软件这个技术上做不了，只能让操作系统自己去考虑这个事情
