### ISSUE TITLE
希望能在「设置-进阶设置」单词保持原文功能中，添加屏蔽词的同步功能

### ISSUE THREAD

**Issue by ztkuaikuai** [immersive-translate/immersive-translate#2230]
### 您希望的更新和改进是什么 | Update or Improve

希望能在同一个账号，不同电脑、不同浏览器环境中同步屏蔽词信息。目前只能手动在不同电脑不同浏览器中设置，如下：

![image](https://github.com/user-attachments/assets/344fea28-6fef-4b9e-b916-11baf9bd0a71)

![image](https://github.com/user-attachments/assets/96fa3b8e-77cc-470e-9c0e-b9ee5a9773ac)

**Comment by theowenyoung** [comment]
目前多设备自动同步功能是 Pro 功能： https://immersivetranslate.com/zh-Hans/pricing

![CleanShot 2024-10-29 at 01 25 40@2x](https://github.com/user-attachments/assets/ff0081ce-91c6-45db-9288-921b94dd08ff)

您也可以手动导入/导出，或通过 Google Drive 免费同步
