### ISSUE TITLE
[Bug]: macOS Safari右键菜单不显示翻译网页/显示原文按键

### ISSUE THREAD

**Issue by JOJOforshaun** [immersive-translate/immersive-translate#2232]
### 插件版本号 | Version

1.10.5

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

macOS 15 Safari右键菜单不显示翻译网页/显示原文按键，以前是可以正常显示的，noir扩展也可以正常显示右键菜单的按键，就沉浸式翻译不能显示
<img width="259" alt="Screenshot 2024-10-28 at 21 58 13" src="https://github.com/user-attachments/assets/d0f98199-cf49-40f1-a026-31d9dd36d3da">

### 出现问题的网址 | URL

任意网页

**Comment by keyboard3** [comment]
1.11.1 已修复
