### ISSUE TITLE
[Bug]: 自定义模型列表高阶语法中 模型名=展示名 不成功

### ISSUE THREAD

**Issue by deanhzed** [immersive-translate/immersive-translate#2235]
### 插件版本号 | Version

1.10.2
1.10.6

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

[Bug]: `自定义模型列表`  `高阶语法` 中 `模型名=展示名` 不成功
```
服务返回错误， 请求参数错误，请检查相应配置。
400: {"error":{"message":"invalid param model:免费
```
```
-all,+lite,lite=免费
```
直接使用lite正常

**Comment by TaoLoading** [comment]
你这里的操作是先去掉全部的，增加“lite”，再将“lite”重命名为“免费”，也就是最终的模型名称为“免费”，所以返回 “invalid param model:免费” 有什么问题吗？

**Comment by deanhzed** [comment]
> 你这里的操作是先去掉全部的，增加“lite”，再将“lite”重命名为“免费”，也就是最终的模型名称为“免费”，所以返回 “invalid param model:免费” 有什么问题吗？

我的理解是，实际传给对面的还是模型名，展示名只是备注；您可以提供一个 模型名=展示名 原本设计所应用的场景吗，麻烦了。

**Comment by TaoLoading** [comment]
这确实是个 bug，“=” 应该只是修改展示名（即备注），该问题将在下一版（1.11.2）中修复

**Comment by TaoLoading** [comment]
1.11.2 已发布，修复了该问题
