### ISSUE TITLE
[Bug]: Youtube雙語字幕置中顯示

### ISSUE THREAD

**Issue by alex8788** [immersive-translate/immersive-translate#2238]
### 插件版本号 | Version

1.10.6

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

幾天前開始雙語字幕變成顯示在影片正中間，設定也沒有相關的選項。

下面第一張是YT內建字幕，第二張是沉浸式翻譯的字幕。
![image](https://github.com/user-attachments/assets/dcbddf57-d2cf-41f1-910a-285748657b15)
![image](https://github.com/user-attachments/assets/6defce1c-dd16-4e28-8892-091ca418c689)

### 出现问题的网址 | URL

https://www.youtube.com/

### 重现步骤 | To Reproduce

1. 開YT
2. 隨便找一個有字幕的影片
3. 開雙語字幕

**Comment by TaoLoading** [comment]
这应该是你之前无意间拖动过字幕，为支持用户个性化，我们会记住最后一次的字幕位置，重新拖回原处即可
