### ISSUE TITLE
请求网站适配

### ISSUE THREAD

**Issue by theowenyoung** [immersive-translate/immersive-translate#224]
有一些常见的论坛或社交媒体网站，比如Twitter，Reddit 等，用专用的规则去适配，体验会更好。如果你有想要特殊适配的网站，请在这个 issue  下留言。

**Comment by shenjackyuanjie** [comment]
dimforge 系网站
#238 
https://rapier.rs/docs/user_guides/rust/rigid_bodies
![image](https://user-images.githubusercontent.com/54507071/224732649-f97e4caf-7034-4ea8-a7dc-ab32baa77e26.png)

**Comment by lockmatrix** [comment]
希望增加对于飞书妙计语音识别后文字的支持。

飞书妙计是允许点一个词之后跳转到目标时间，翻译不需要处理这个。可以考虑直接把整段的译文加在文字之后。

飞书妙计虽然自带翻译，但感觉有点烂，希望能够调用外挂翻译。


飞书妙计也支持到处到飞书文档，但飞书文档也同样不被本插件支持。也找了一些其他在线编辑网站，好像也不行。

**Comment by timelic** [comment]
希望加入对于谷歌学术搜索的适配。搜索结果里面的摘要有两行，应该合并翻译而非分开翻译。

这是一个[示例](https://scholar.google.com.hk/scholar?cites=7310944231388037759&as_sdt=2005&sciodt=0,5&hl=zh-CN)

**Comment by versun** [comment]
> 希望加入对于谷歌学术搜索的适配。搜索结果里面的摘要有两行，应该合并翻译而非分开翻译。
> 
> 这是一个[示例](https://scholar.google.com.hk/scholar?cites=7310944231388037759&as_sdt=2005&sciodt=0,5&hl=zh-CN)
已是合并翻译了
<img width="628" alt="2023-04-06" src="https://user-images.githubusercontent.com/2398708/230224273-f5ccecad-55d5-4677-b10a-67d41d3c4ade.png">

**Comment by timelic** [comment]
> 希望加入对于谷歌学术搜索的适配。搜索结果里面的摘要有两行，应该合并翻译而非分开翻译。
> 
> 这是一个[示例](https://scholar.google.com.hk/scholar?cites=7310944231388037759&as_sdt=2005&sciodt=0,5&hl=zh-CN)

抱歉我可能没有很清晰地表达我的意思🙂。

<img width="609" alt="截屏2023-04-07 10 07 38" src="https://user-images.githubusercontent.com/20257354/230526285-910cd2ea-49e9-45d3-80bf-bfac00eb8506.png">

比如这个截图中，两行英文实际上是应该合并的，中间是没有分段的。但是中文翻译依旧是将两行英文分开翻译了。

**Comment by versun** [comment]
@timelic  应该可以了，你更新下规则后再试一试

**Comment by LuoTang2413** [comment]
使用了插件之后，网页版Fiverr的聊天框无法回复消息，网页被迫强制刷新，烦请修复一下，感谢♪(･ω･)ﾉ

**Comment by versun** [comment]
@LuoTang2413  更新规则了, 你点击下插件更新下规则应该就可以了

**Comment by versun** [comment]
@Kinda2419 notion官方有做限制哈,不让乱改样式,所以效果不是很好,没啥办法

**Comment by zryyyy** [comment]
notion的输入框增强可以适配吗🥺真的很想要这个功能谢谢开发者大大🥺
