### ISSUE TITLE
智谱 glm-4-plus 模型在翻译单独的专有名词时增加不必要的解释

### ISSUE THREAD

**Issue by kunedo** [immersive-translate/immersive-translate#2242]
### 您希望的更新和改进是什么 | Update or Improve

如题，使用智谱 glm-4-plus 模型时，单独出现的专有名词在翻译时会解释为什么不翻译，而使用原单词；或者是解释这个名词是什么意思。
不知道是否能通过修改Prompt使这种单独出现的专有名词就单纯不翻译？

如下图：

![图1](https://github.com/user-attachments/assets/a55b58a6-e74c-41eb-baae-ef2eb65734f6)

而在段落中的名词就是正常的，不会解释，如下图左侧：

![图2](https://github.com/user-attachments/assets/380e6b2b-c838-4d3e-8519-3a35bb5beb25)

**Comment by theowenyoung** [comment]
提供一下网址，我们看下能不能调整一下 prompt

**Comment by kunedo** [comment]
https://www.fullstackpython.com/environment-configuration.html

这是一个普遍现象，在下面的地址又出现一样的问题。
https://github.com/neovim/neovim/wiki/Related-projects#gui
![1](https://github.com/user-attachments/assets/f7dd26a4-6391-4d78-b3ba-e7bdcb162be1)

**Comment by theowenyoung** [comment]
我们优化了一下 智谱的 prompt，现在应该好多了，可以再试一下吗？刷新页面重试应该就好了。
