### ISSUE TITLE
[Bug]: Netflix无法使用人工字幕！

### ISSUE THREAD

**Issue by YihanZhu24** [immersive-translate/immersive-translate#2246]
### 插件版本号 | Version

1.10.6

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox, Chrome, Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

我一直使用沉浸式翻译进行翻译视频字幕。

然而最近我在使用netflix看美剧时，发现贵软件出现了问题，它无法正常使用汉语人工字幕

我在设置中已经勾选了优先使用人工字幕，但是在播放中，它还是用的软件翻译的字幕。

以前并非如此，以前我在勾选了“优先人工字幕”之后，它的双语字幕就不会再软件翻译，而是直接取用netflix已有的人工字幕

请贵公司修复一下这个bug，极度影响使用体验！谢谢

### 出现问题的网址 | URL

https://www.netflix.com/browse

### 重现步骤 | To Reproduce

1. 进入Netflix选择任意一部内含英文和中文字幕的剧
2. 选择英文字幕后，（并在沉浸式翻译内勾选了优先人工字幕后），双语字幕的中文仍然是机翻

### 补充说明 | Additional context

请尽快解决，多谢

**Comment by keyboard3** [comment]
新版不支持人工字幕，仅支持实时字幕翻译。如果想回退到旧版 参考这个配置 https://immersivetranslate.com/zh-Hans/docs/faq/#4-netflix-%E5%AD%97%E5%B9%95%E7%BF%BB%E8%AF%91%E7%94%A8%E5%8E%9F%E5%A7%8B%E5%AD%97%E5%B9%95%E6%A0%B7%E5%BC%8F
