### ISSUE TITLE
希望支持的新视频网站 加拿大主要网站 

### ISSUE THREAD

**Issue by ld709** [immersive-translate/immersive-translate#2247]
### 您希望的更新和改进是什么 | Update or Improve

https://www.crave.ca/en/tv-shows/friends/the-one-where-nana-dies-twice-s1e8
可以看老友记的法语配音字幕网站 只是不支持沉浸式翻译 所以不能看双语 

### 补充说明 | Additional context

十分感谢！

**Comment by keyboard3** [comment]
在这个帖子中集中反馈 https://github.com/immersive-translate/immersive-translate/issues/1179

然后你这个站点需要账号密码，需要联系开发人员私信账密才能调试该站点
