### ISSUE TITLE
[Bug]: 翻译网页后，鼠标悬停还原该段功能异常

### ISSUE THREAD

**Issue by Subject-Z** [immersive-translate/immersive-translate#2248]
### 插件版本号 | Version

1.10.6

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

具体表现为：还原该段为英文后，又瞬间变回译文

**Comment by keyboard3** [comment]
下个版本修复
