### ISSUE TITLE
[功能建议]可以加个功能吗

### ISSUE THREAD

**Issue by oceanhunt** [immersive-translate/immersive-translate#225]
网络不好，可以加个用户自定义每隔几秒自动刷新感叹号的功能吗

**Comment by theowenyoung** [comment]
好吧，其实默认情况下（在看到感叹号之前） 已经会重试1次了。

你 也可以快速按下快捷键， `alt+a`, 2次，这个时候如果已经成功翻译了的，会使用之前的缓存，只有失败的会重试
