### ISSUE TITLE
[Bug]: 总是显示等待注入页面中...若长时间未响应，请尝试刷新页面

### ISSUE THREAD

**Issue by kevinweb3** [immersive-translate/immersive-translate#2250]
### 插件版本号 | Version

1.10

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

总是显示等待注入页面中...若长时间未响应，请尝试刷新页面，悬浮球也显示不出来，翻译点击按钮灰色的

**Comment by keyboard3** [comment]
这是表示网页资源没有全部加载完，插件还没有注入。刷新页面等待注入，如果仍未成功，建议切换网络或者卸载重装插件
