### ISSUE TITLE
[Bug]: 智谱在设置中的开关状态有问题

### ISSUE THREAD

**Issue by Mishasama** [immersive-translate/immersive-translate#2251]
### 插件版本号 | Version

1.11.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/user-attachments/assets/2aa6bc35-e393-44e1-b6ce-4ba0661cf588)
如图，即便是开着也显示关闭。

### 补充说明 | Additional context

从旧版一路升级过来的，没有测试过重装。

**Comment by keyboard3** [comment]
如果之前没有手动开启过，在新版策略中繁体页面会默认隐藏它，你可以手动开启智谱

**Comment by Mishasama** [comment]
> 如果之前没有手动开启过，在新版策略中繁体页面会默认隐藏它，你可以手动开启智谱

什么意思？为什么要隐藏它？隐藏了要怎么手动开启？
我的问题是指无论怎么点击开关都没有效果，其它服务的开关当鼠标指向的时候都是变成手指的，但是它却不会，而且点击就是进入设置页面而不是切换开关。

**Comment by keyboard3** [comment]
![QQ_1731547710813](https://github.com/user-attachments/assets/b1455fb3-4c7c-4245-8d65-e9d17a3198e9)
![QQ_1731547718747](https://github.com/user-attachments/assets/c05d80f1-e086-4132-9ce0-e505e8bf35e6)
可以正常开关切换啊

**Comment by Mishasama** [comment]
> 可以正常开关切换啊

![6045297e-3a3f-4868-ac91-dd3aa814e7a6](https://github.com/user-attachments/assets/6b92e3b1-6f64-44ff-b6b5-45b2770330a5)

**Comment by keyboard3** [comment]
你将其他翻译服务设置为默认，然后再回来点击切换开启
