### ISSUE TITLE
[Bug]: web of science 翻译后显示网页二级页面内部信息翻译出来

### ISSUE THREAD

**Issue by boilingwaterone** [immersive-translate/immersive-translate#2252]
### 插件版本号 | Version

V1.11.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 请描述这个Bug | Describe the bug

翻译前如下
![PixPin_2024-11-06_15-30-02](https://github.com/user-attachments/assets/4ae9f91d-378f-4c58-9d9f-8e3d9e69d00e)
翻译后如下，将影响因子等翻译出来，并呈现特大号字体
![PixPin_2024-11-06_15-30-21](https://github.com/user-attachments/assets/c5318ed3-41f8-490c-b8de-060c6e236233)

### 出现问题的网址 | URL

https://webofscience.clarivate.cn/wos/alldb/basic-search

**Comment by keyboard3** [comment]
点击悬浮球的反馈旁边的反馈按钮，会收集网页快照和相关日志给开发

**Comment by boilingwaterone** [comment]
好的

**Comment by keyboard3** [comment]
这个邮件反馈了，测试下是否正常了
