### ISSUE TITLE
www.discord.com网站能否优化改进一下.

### ISSUE THREAD

**Issue by ictsmc** [immersive-translate/immersive-translate#2253]
### 您希望的更新和改进是什么 | Update or Improve

1.是否翻译网页所有区域
开启后，整个网页的所有区域都会被翻译。关闭则使用默认的智能识别，仅翻译主要区域。
(不推荐开启)
开启1功能所有内容都翻译.开启这个能否不翻译昵称.聊天对话框中的昵称会被翻译.

2.如果不开启.左侧栏目又不能翻译.能否针对这个网站进行优化一下.

**Comment by JHB-L** [comment]
https://immersivetranslate.com/zh-Hans/docs/advanced/
高级自定义选项好像有

**Comment by ictsmc** [comment]
www.discord.com  大佬 你这个高级配置自定义不适合小白.如果这个网站其他都翻译.只要用户名不翻译如何设置.

**Comment by JHB-L** [comment]
> [www.discord.com](http://www.discord.com) 大佬 你这个高级配置自定义不适合小白.如果这个网站其他都翻译.只要用户名不翻译如何设置.


我用这个网站少，都是直接是用网站自带的语言选择中文，调用插件翻译好像没什么用户名翻译问题

**Comment by keyboard3** [comment]
1.11.7 已支持单独开关侧边栏翻译
![QQ_1732688049789](https://github.com/user-attachments/assets/bc5c400d-2ca9-4c68-b13d-43b0d2270913)
