### ISSUE TITLE
[Bug]: Facebook 仅译文展开消失

### ISSUE THREAD

**Issue by keePeepin** [immersive-translate/immersive-translate#2255]
### 插件版本号 | Version

1.10.6

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

FB网页的帖子或者评论区使用【翻译页面主要区域/显示原文】功能后，点击**展开**之后，该帖子或评论会直接消失不见。望解决。

https://github.com/user-attachments/assets/457e0ba3-0131-41b8-9928-2a947f378242

https://github.com/user-attachments/assets/7633bd42-8271-40e9-bcd2-8f0814d66109

### 出现问题的网址 | URL

https://www.facebook.com/groups/347472001391009/?ref=share&rdid=ij1HiLjitVyyNtDA&share_url=https%3A%2F%2Fwww.facebook.com%2Fshare%2Fg%2F158jiJoRYZ%2F

**Comment by keyboard3** [comment]
facebook 需要登录，你可以在未翻译情况下，在这个页面的悬浮球更多处反馈下
![QQ_1730971468169](https://github.com/user-attachments/assets/d3c80f53-6d68-41de-b417-4812c284e997)
