### ISSUE TITLE
某些元素无法翻译，比如ozon网站上，导航栏的内容无法翻译

### ISSUE THREAD

**Issue by q1343135559** [immersive-translate/immersive-translate#2256]
### 您希望的更新和改进是什么 | Update or Improve

![image](https://github.com/user-attachments/assets/c6728c8b-fc7f-4021-81a4-48babc497213)

**Comment by keyboard3** [comment]
插件默认翻译主要区域，如果想翻译所有区域可以通过这里设置
![QQ_1730970688118](https://github.com/user-attachments/assets/0383c2e9-29fb-4bd9-af42-43c7ae202729)

**Comment by q1343135559** [comment]
感谢解答,问题已解决




jiajun
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "immersive-translate/immersive-translate"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月7日(星期四) 下午5:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [immersive-translate/immersive-translate] 某些元素无法翻译，比如ozon网站上，导航栏的内容无法翻译 (Issue #2256)





 
插件默认翻译主要区域，如果想翻译所有区域可以通过这里设置
 QQ_1730970688118.png (view on web)
