### ISSUE TITLE
[Bug]: 打开输入框增强，但还是无法三击空格键自动翻译

### ISSUE THREAD

**Issue by Sm1letk** [immersive-translate/immersive-translate#2257]
### 插件版本号 | Version

 1.10.6

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

打开输入框增强，但还是无法三击空格键自动翻译；完全没有反应

### 出现问题的网址 | URL

https://www.google.com.hk/search?q=%E7%BE%8E%E5%9B%BD%E7%9A%84%E5%B7%A6%E5%92%8C%E5%8F%B3&rlz=1C5CHFA_enUS1082US1083&oq=&gs_lcrp=EgZjaHJvbWUqCQgDECMYJxjqAjIJCAAQIxgnGOoCMgkIARAjGCcY6gIyCQgCECMYJxjqAjIJCAMQIxgnGOoCMgkIBBAjGCcY6gIyCQgFECMYJxjqAjIJCAYQIxgnGOoCMgkIBxAjGCcY6gLSAQkxODMzajBqMTWoAgiwAgE&sourceid=chrome&ie=UTF-8

**Comment by keyboard3** [comment]
不要修改输入增强的间隔时间，然后空格输入快一点

**Comment by keyboard3** [comment]
暂无反馈 关闭此issue
