### ISSUE TITLE
Bing Chat 页面无法翻译

### ISSUE THREAD

**Issue by Andy-AO** [immersive-translate/immersive-translate#226]
在微软的 Bing Chat 页面中，扩展没有办法翻译，即使是开启翻译所有区域也不行。建议适配该页面。
![image_994](https://user-images.githubusercontent.com/38101170/224531781-82d6adce-c46b-47c5-97f8-33f0769ef6ff.png)

# links
- [hello](https://www.bing.com/search?q=hello)

**Comment by theowenyoung** [comment]
确认。

这个可能要一段时间，因为 他用的技术是 shadow root 技术，整个文档脱离里正常的网页流，目前插件对这种情况支持的不太好。

**Comment by theowenyoung** [comment]
已修复～
