### ISSUE TITLE
低于某一字符串长度的内容不予翻译

### ISSUE THREAD

**Issue by Geo123abc** [immersive-translate/immersive-translate#2261]
##### 新功能 | New Feature
添加一个设置，如果一段文字（一个待翻译的对象）字符串长度短于某个设定值，就不翻译这段内容

##### 为什么您想要添加这些功能 | Why you want to add these features
1. 经常看的网页中有很多表格，目前沉浸式翻译会对表格中的数字、表头进行翻译，其实这种翻译不仅是没必要的，并且会占用翻译资源；
2. 页面中的一些比较短的内容，通常是一些常见的文章结构性词语，这种词的含义一般都知道，也没必要翻译；

##### 提议 | Proposal
设置中添加一个可选选项（类似 v1.11.1版本设置中“每次请求最大文本长度：”），当字符串少于这个设定值，这段内容就不予翻译。

[低于某一字符串长度的内容不予翻译 · immersive-translate/immersive-translate · Discussion #2260](https://github.com/immersive-translate/immersive-translate/discussions/2260)

**Comment by FattySpring** [comment]
在进阶设置中有这个功能 [进阶设置](https://dash.immersivetranslate.com/#advanced) 【翻译段落所需的最少字符数】
