### ISSUE TITLE
[Bug]: paragraphMinTextCount疑似失效

### ISSUE THREAD

**Issue by ysdj** [immersive-translate/immersive-translate#2264]
### 插件版本号 | Version

1.11.1

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

即使设置paragraphMinTextCount=100，表格中内容依然翻译

![image](https://github.com/user-attachments/assets/fd14bfa2-211c-438f-bdf9-1d4fa55e4899)

![image](https://github.com/user-attachments/assets/e2b77629-5bd6-49e6-80e1-0e305afbf998)

### 出现问题的网址 | URL

https://pmc.ncbi.nlm.nih.gov/articles/PMC8421942/table/t2/

**Comment by theowenyoung** [comment]
请在 【进阶设置】界面中修改，直接从配置修改会少一个地方。
