### ISSUE TITLE
[Bug]: 无法添加兼容Openai格式的自定义接口

### ISSUE THREAD

**Issue by BryceWG** [immersive-translate/immersive-translate#2266]
### 插件版本号 | Version

1.11.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

最近发现无法添加自定义的openai接口，但是之前添加的可以使用，目前一共添加了六个：
![wkcd3hm1 ycd](https://github.com/user-attachments/assets/1fecd351-2640-4392-afa4-6d244c8b05dd)
尝试添加时页面出现空白：
![slieru10 c1w](https://github.com/user-attachments/assets/bc1008a5-d5a1-48e9-82c0-e14e95214794)

### 出现问题的网址 | URL

插件设置页面

### 重现步骤 | To Reproduce

1. 点击翻译服务设置
2. 选择“添加兼容 OpenAI 接口的自定义 AI 翻译服务？”
3. 发现无法添加

### 补充说明 | Additional context

最近由于更换浏览器，有过几次导入导出配置文件，跨过了一些插件版本

**Comment by FattySpring** [comment]
无法复现，方便提供一份脱敏的配置文件吗

**Comment by keyboard3** [comment]
暂无反馈关闭此问题

**Comment by BryceWG** [comment]
抱歉,漏掉消息了,我之前也已经重置过插件数据了,提供不了配置文件
