### ISSUE TITLE
给“是否翻译网页所有区域”添加一个黑名单

### ISSUE THREAD

**Issue by fangquinlan** [immersive-translate/immersive-translate#2269]
### 您希望的更新和改进是什么 | Update or Improve

例如可以开启此选项，但是排除`https://github.com/*`

**Comment by theowenyoung** [comment]
您对默认翻译主要区域的问题是？

**Comment by fangquinlan** [comment]
> 您对默认翻译主要区域的问题是？

有些菜单栏/导航栏还是很重要的（例如之前我提的[issue](https://github.com/immersive-translate/immersive-translate/issues/2193)），但是开始`翻译主要区域`就不会翻译。但是开启`翻译全部区域`后，会有大量不该翻译内容，比如我所说的GitHub等等

**Comment by theowenyoung** [comment]
这是一个权衡，目前的策略更符合我们目标用户的需要的阅读体验和效率。

不过我觉得加一个例外网站的设置也可以，我先记录下来。
