### ISSUE TITLE
Insert text on Over or behind for mouse hover

### ISSUE THREAD

**Issue by neoOpus** [immersive-translate/immersive-translate#227]
Hi,

Thank you for making this great userscript, I find it very well done and pretty useful, it is part of my arsenal of productivity tools right now :)

I would like to suggest a feature that could be useful and maybe a better option to present the translated text, is to have it on top or behind the original and on mouse hover it smoothly show it (with some blur unblur effect maybe), this provides the advantage to have the page uncluttered and make it easier on eyes and allows focusing better on the content but over most it would keep the layout as it is, I guess it will be a bit harder to implant.

Another suggestion is to allow using the own CSS for the styling of the translated text.

**Comment by theowenyoung** [comment]
> Another suggestion is to allow using the own CSS for the styling of the translated text.

Now, you can edit the custom css on developer settings:

<img width="1259" alt="Screenshot 2023-03-12 at 22 24 19" src="https://user-images.githubusercontent.com/62473795/224550928-8dbb7574-460b-4796-808f-8cd92543e12a.png">

> I would like to suggest a feature that could be useful and maybe a better option to present the translated text, is to have it on top or behind the original and on mouse hover it smoothly show it (with some blur unblur effect maybe), this provides the advantage to have the page uncluttered and make it easier on eyes and allows focusing better on the content but over most it would keep the layout as it is, I guess it will be a bit harder to implant.

Yes, this is a great feature, and I'm planning to support it, but it take times. :)

**Comment by neoOpus** [comment]
Thank you

**Comment by theowenyoung** [comment]
Hi, we have supported it, you can enable it on the popup.

**Comment by neoOpus** [comment]
Hi, 

You mean you've implanted this  "maybe a better option to present the translated text, is to have it on top or behind the original and on mouse hover it smoothly show it (with some blur unblur effect maybe), this provides the advantage to have the page uncluttered and make it easier on eyes and allows focusing better on the content but over most it would keep the layout as it is, I guess it will be a bit harder to implant." ???
