### ISSUE TITLE
建议为使用API的用户定制会员级别

### ISSUE THREAD

**Issue by Loveacup** [immersive-translate/immersive-translate#2270]
### 您希望的更新和改进是什么 | Update or Improve

建议为使用API的用户定制一个专属的会员级别。目前的会员价格较高，这对使用我们API的用户来说可能会造成一定的负担。然而，我们仍希望能够使用一些高级功能。希望能推出一个适合API用户的会员方案，以便在合理的价格下享受专业版的功能。

**Comment by keyboard3** [comment]
有功能会员 不包含任何额度（可享受其他非额度的会员功能），如果需要其中的额度，可以单独购买流量包即可。 https://immersivetranslate.com/accounts/pre-order?price_id=price_1PWg9EGc8iUjvqOFATBhujeS
