### ISSUE TITLE
[Bug]: 当与adguard同时使用时，Safari、edge浏览器的插件，智谱glm、零一、硅流翻译服务都无法使用

### ISSUE THREAD

**Issue by skz110** [immersive-translate/immersive-translate#2271]
### 插件版本号 | Version

1.11.1

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

您好，Mac版浏览器插件在safaria及edge浏览器填好APIKEY总是出现错误
macos版本：14.1.1
沉浸式翻译版本：1.11.1
ios版没有问题，macos就会出现这种错误。
试着重启 mac，重新安装沉浸式翻译，也没有解决问题。
后来发现在Adgurd设置中关闭“自动过滤应用程序流量”时，全部恢复正常，但这样Adguard无法拦截广告
<img width="712" alt="截屏2024-11-12 18 46 28" src="https://github.com/user-attachments/assets/f5c8872e-3080-4611-80ee-63e800c71a58">
<img width="817" alt="截屏2024-11-12 18 41 29" src="https://github.com/user-attachments/assets/58dadab6-035c-4853-96af-ffc52e8d1aff">
<img width="825" alt="截屏2024-11-12 18 41 06" src="https://github.com/user-attachments/assets/0477aab3-c0aa-49d3-ae5e-fbda80f7e50b">
<img width="846" alt="截屏2024-11-12 18 40 51" src="https://github.com/user-attachments/assets/142de026-f216-4a3c-80cc-53b3d2774a15">

**Comment by theowenyoung** [comment]
https://github.com/AdguardTeam/AdguardForWindows/issues/2491

看下有没有地方设置 允许 第三方 header ？

**Comment by skz110** [comment]
感谢，已解决。在设置中不要勾选“拦截第三方授权头部”。
![Uploading 截屏2024-11-13 18.12.40.png…]()
