### ISSUE TITLE
[Bug]: 網頁快照分享可能導致用戶信任風險與敏感數據洩露

### ISSUE THREAD

**Issue by qq96932100** [immersive-translate/immersive-translate#2272]
### 插件版本号 | Version

1.11.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 問題描述

當翻譯後的頁面內容托管在 `https://readit.plus` domain下時，訪問者可能會認為此domain值得信任。這可能導致使用者對可能存在惡意內容的頁面產生信任，從而造成個人資訊洩露或遭受釣魚攻擊的風險。

### 具體風險與攻擊場景

- **用戶信任問題**：由於翻譯內容被托管在 `readit.plus` 主域下，用戶訪問時會認為該內容是受信任的，若攻擊者在翻譯過程中插入惡意代碼，這些代碼會因為託管在可信域下而更具欺騙性。
  
- **敏感數據洩露**：攻擊者可以利用分享翻譯後的惡意網頁快照來收集用戶的 IP、地理位置和設備資訊，並進行針對性攻擊。

- **XSS 和釣魚攻擊**：該設計使攻擊者能夠更方便地植入惡意腳本或偽造的釣魚信息，增加了潛在的安全風險。

### 重現步驟

1. 使用擴充套件翻譯一個包含惡意內容的頁面，並生成分享鏈接。
2. 用戶訪問分享後的鏈接，觸發頁面上包含的惡意腳本。(domain為readit.plus，看似正常)
2.1 案例一: 攻擊者植入自動轉跳的惡意腳本 => https://readit.plus/a/TgfzQ/shaber_evil.html
![案例一](https://github.com/user-attachments/assets/495c1c81-baa3-403f-8115-495bcbdd6077)
![案例一](https://github.com/user-attachments/assets/7f40e605-e995-4b51-88b6-6e97c9057eb9)

   2.2 案例二: 攻擊者引入外部js，竊取用戶的IP、設備資訊...等等 => https://readit.plus/a/YPNJJ/test.html
![案例二](https://github.com/user-attachments/assets/76f6c5d0-439d-43c1-9ff6-b5c763372215)

### 改進建議

1. **基礎的 HTML 和 JavaScript 過濾**：進行基礎的內容過濾，去除可能存在的惡意代碼，從而防範基本的 XSS 攻擊。
2. **重新思考網頁快照功能** : 考慮未來將網頁快照功能僅限於展示「翻譯內容」，保留樣式但去除頁面上的互動功能（如按鈕、表單），這樣可以降低快照內容的潛在風險，並避免用戶與可能的惡意元素進行互動。

### 潛在影響

若此信任問題得不到解決，攻擊者可能會利用 `readit.plus` 的可信度來進行更具欺騙性的釣魚和數據收集攻擊。
從長期來看，這將對平台的用戶信任度和本產品形象帶來潛在的負面影響。
通過基礎過濾等改進，不僅能增強用戶的安全性，也能增強平臺在用戶心目中的信任和可靠性。

### 出现问题的网址 | URL

案例一: 攻擊者植入自動轉跳的惡意腳本 => https://readit.plus/a/TgfzQ/shaber_evil.html
案例二: 攻擊者引入外部js，竊取用戶的IP、設備資訊...等等 => https://readit.plus/a/YPNJJ/test.html

**Comment by keyboard3** [comment]
感谢反馈，已在线修复，可以重新分享一下

**Comment by qq96932100** [comment]
已複測，問題已解決。
