### ISSUE TITLE
[Bug]: inoreader翻译页面异常

### ISSUE THREAD

**Issue by Vstory** [immersive-translate/immersive-translate#2274]
### 插件版本号 | Version

1.11.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

![翻译前](https://github.com/user-attachments/assets/42bc1b95-2ea6-494a-b435-4c00441424a8)

翻译后，显示视频时长的元素错位了
![翻译后](https://github.com/user-attachments/assets/3f2e4986-6286-4f7a-8a8b-255a64b590d4)

### 出现问题的网址 | URL

https://www.youtube.com/feeds/videos.xml?channel_id=UCV5jhU4ntp08bfdzBpmMzeQ

### 重现步骤 | To Reproduce

1. 使用inoreader订阅 `https://www.youtube.com/feeds/videos.xml?channel_id=UCV5jhU4ntp08bfdzBpmMzeQ`
2. 尝试翻译![翻译前](https://github.com/user-attachments/assets/42bc1b95-2ea6-494a-b435-4c00441424a8)

**Comment by keyboard3** [comment]
在悬浮球旁边的反馈按钮进行反馈
