### ISSUE TITLE
[Bug]: 无法打开弹出窗口

### ISSUE THREAD

**Issue by TianMengLucky** [immersive-translate/immersive-translate#2278]
### 插件版本号 | Version

1.11.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

无法打开弹出窗口
![image](https://github.com/user-attachments/assets/15798406-b9b2-4c25-9db6-2bbde1fab1ad)
![image](https://github.com/user-attachments/assets/9017fb54-949a-4777-b8ff-4d48ba101eea)
控制台出现下面报错
`popup.js:5361 
 Uncaught (in promise) Error: IO error: .../MANIFEST-000001: Unable to create sequential file (ChromeMethodBFE: 7::NewSequentialFile::4)`

### 重现步骤 | To Reproduce

1.打开浏览器
2.点击扩展图标

**Comment by TianMengLucky** [comment]
删除扩展，删除AppData\Local\Microsoft\Edge\User Data\Default\Sync Extension Settings下扩展数据文件夹后重装恢复

**Comment by keyboard3** [comment]
这种一般是浏览器问题，插件暂无手段处理
