### ISSUE TITLE
翻译时希望保留markdown格式中的数学公式

### ISSUE THREAD

**Issue by justcyl** [immersive-translate/immersive-translate#228]
当网页正文使用markdown时，遇到公式符号 `$$` 时，会自动换行影响阅读体验。比如下段文字:
![image](https://user-images.githubusercontent.com/37929641/224533533-1e46a196-328a-4ecb-9261-50ada2608006.png)
翻译后变成了这样
![image](https://user-images.githubusercontent.com/37929641/224533553-556b1c1a-487e-42ed-830e-c225d0bdefa6.png)

应该是网站适配的问题，翻译后一段文字被分成了好几段。
网址示例https://codeforces.com/contest/1801/problem/D

**Comment by theowenyoung** [comment]
加了一个针对该元素的规则～ 可以了，刷新一次再试试～
