### ISSUE TITLE
[Bug]: 输入框增强经常失效

### ISSUE THREAD

**Issue by ahJanet** [immersive-translate/immersive-translate#2280]
### 插件版本号 | Version

1.11.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

输入框增强经常失效，连击三次空格键后无效，无论是Google界面还是默认界面，另，为什么默认界面无法进行输入框增强？不是很方便

### 出现问题的网址 | URL

https://www.google.com/search?q=%E5%BE%88%E5%A5%BD&oq=%E5%BE%88%E5%A5%BD&gs_lcrp=EgZjaHJvbWUyDggAEEUYJxg5GIAEGIoFMgcIARAAGIAEMgcIAhAAGIAEMgcIAxAAGIAEMgcIBBAAGIAEMgcIBRAAGIAEMgcIBhAAGIAEMgcIBxAAGIAEMgcICBAAGIAEMgcICRAAGIAEqAIAsAIA&sourceid=chrome&ie=UTF-8

### 重现步骤 | To Reproduce

1. Go to "   ", 2. translate

### 补充说明 | Additional context

none

**Comment by keyboard3** [comment]
默认页面浏览器不让插件生效。 空格连击快一点

**Comment by ahJanet** [comment]
了解了，感谢！
请问可以连击慢一点吗



发自我的iPhone


------------------ Original ------------------
From: keyboard3 ***@***.***&gt;
Date: Fri,Nov 15,2024 9:44 AM
To: immersive-translate/immersive-translate ***@***.***&gt;
Cc: ahJanet ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [immersive-translate/immersive-translate] [Bug]: 输入框增强经常失效 (Issue #2280)





 
默认页面浏览器不让插件生效。 空格连击快一点

**Comment by keyboard3** [comment]
https://dash.immersivetranslate.com/#input 可以在这里调整间隔时间，默认是200毫秒，可以往大的调，比如400

**Comment by ahJanet** [comment]
收到，感恩。这个插件非常棒！！👍




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "immersive-translate/immersive-translate"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月15日(星期五) 上午9:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [immersive-translate/immersive-translate] [Bug]: 输入框增强经常失效 (Issue #2280)





 
https://dash.immersivetranslate.com/#input 可以在这里调整间隔时间，默认是200毫秒，可以往大的调，比如400
