### ISSUE TITLE
[Bug]: YouTube视频下展开多层评论时，布局混乱

### ISSUE THREAD

**Issue by TaoLeeyu** [immersive-translate/immersive-translate#2284]
### 插件版本号 | Version

1.11.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

如图展开评论时，点赞、踩与回复图标错行叠行
![微信图片_20241115220927](https://github.com/user-attachments/assets/0a6f84f8-d4e4-4a00-b975-d6a4781dd7a8)

### 出现问题的网址 | URL

https://www.youtube.com/watch?v=ViQty5yqfCA

### 重现步骤 | To Reproduce

1.点开评论区任意一条有多个回复的评论；
2.点击插件进行翻译

**Comment by keyboard3** [comment]
打开 https://www.youtube.com/watch?v=ViQty5yqfCA&imt_refresh_rule=1 再试下
