### ISSUE TITLE
pdf翻译改进

### ISSUE THREAD

**Issue by lqz2** [immersive-translate/immersive-translate#2286]
### 您希望的更新和改进是什么 | Update or Improve

你们的网页翻译非常棒！但是关于pdf翻译功能，能否支持在pdf中选中翻译。我希望只在pdf中翻译鼠标选中的文本，这样对于学术论文的阅读翻译更加方便。现在的pdf翻译模式下，当我使用gpt的api进行翻译时(api存在每日调用限制)，全文翻译一次性会消耗大量api，导致无法完整翻译论文，希望后续版本可以改进

**Comment by theowenyoung** [comment]
目前的产品设计，不太容易加入这个功能。

我记得有其他同类产品应该支持这个功能～
