### ISSUE TITLE
[Bug]: 识别原文语言错误

### ISSUE THREAD

**Issue by Asa-Cullen** [immersive-translate/immersive-translate#2289]
### 插件版本号 | Version

1.11.4

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 请描述这个Bug | Describe the bug

我需要翻译的epub文件是西班牙语，我需要将其翻译为英文，但是在选择目标语言为英文后，提示我当面页面原语言和目标语言是相同的，无法进行翻译。应该是插件错误识别原文为英文了，原文应该是西班牙语
<img width="1693" alt="image" src="https://github.com/user-attachments/assets/f7ee1a0f-af59-428e-8946-a0bf2e2dbd19">

### 出现问题的网址 | URL

无

### 重现步骤 | To Reproduce

1. 打开翻译epub/pdf功能
2. 放一本西班牙语epub书进去
3. 设置目标语言为英文，点击开始翻译

### 补充说明 | Additional context

无

**Comment by keyboard3** [comment]
![QQ_1731944529551](https://github.com/user-attachments/assets/c723fb04-f6ad-481e-b06b-627cda52f0f8)
可以点击修改原语言然后重新翻译
