### ISSUE TITLE
能加上划线翻译就更好了

### ISSUE THREAD

**Issue by yzhengwei** [immersive-translate/immersive-translate#229]
目前只有整个网页翻译，要是能加上单词或者段落的划线翻译功能就更好了

**Comment by theowenyoung** [comment]
嗯， 在计划中的！

**Comment by pingfangdeguang** [comment]
顺便加个搜索翻译，可以支持自己输入内容进行翻译，因为我现在就是有时候需要中文翻译为英文需要自己单独去百度翻译或者其他翻译工具单独搜索一下

**Comment by xwlops** [comment]
> 目前只有整个网页翻译，要是能加上单词或者段落的划线翻译功能就更好了

+1

**Comment by theowenyoung** [comment]
现在已经有针对段落的鼠标悬停翻译了～ 把鼠标放在某个段落上，即可自动翻译该段。

点击扩展图标，在面板里可以设置快捷键。

<img width="337" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/f416ca25-bc0d-4802-8cca-78c10da7f44b">

**Comment by xwlops** [comment]
> 现在已经有针对段落的鼠标悬停翻译了～ 把鼠标放在某个段落上，即可自动翻译该段。
> 
> 点击扩展图标，在面板里可以设置快捷键。
> <img alt="image" width="337" src="https://user-images.githubusercontent.com/62473795/241844470-f416ca25-bc0d-4802-8cca-78c10da7f44b.png">

考虑划词自动/按键指令翻译吗？

**Comment by yzhengwei** [comment]
通鼠标选中翻译嘛？有时候一段特别长，而我只需要翻译其中一句或者一个单词，通过 鼠标选中更准确一些

**Comment by yzhengwei** [comment]
能通过鼠标选中翻译嘛？有时候一段特别长，而我只需要翻译其中一句或者一个单词，通过 鼠标选中更准确一些
