### ISSUE TITLE
[Bug]: Can't used 1.0 pro

### ISSUE THREAD

**Issue by ehwgagc00** [immersive-translate/immersive-translate#2290]
### 插件版本号 | Version

1.11.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/user-attachments/assets/4bf1df10-7bc2-4c0c-88f7-aae195304e34)

**Comment by keyboard3** [comment]
错误上不是已经说的很清楚吗？ 该模型已经废弃了
