### ISSUE TITLE
[Bug]: Zoom多个视频镜头双语字幕的位置错误

### ISSUE THREAD

**Issue by Rizumu85** [immersive-translate/immersive-translate#2292]
### 插件版本号 | Version

0.5.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome, Other

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/user-attachments/assets/3119f814-dba1-4772-9d71-41b48ea8829a)
字幕显示在小的那个视频而不是大的

### 重现步骤 | To Reproduce

打开双语字幕
刷新后

### 补充说明 | Additional context

双语字幕没开就没问题

**Comment by TaoLoading** [comment]
这好像是录屏，方便的话可以将该视频的链接评论在该 issue，或在 telegram 私信 Taoloading， 我们将进一步修复该问题

**Comment by TaoLoading** [comment]
已修复
