### ISSUE TITLE
翻译本地的html无法进行翻译

### ISSUE THREAD

**Issue by MissingDirection** [immersive-translate/immersive-translate#2294]
### 您希望的更新和改进是什么 | Update or Improve

当我在阅读一些官方的文档手册的时候，一些厂家会直接封装html页面，当我打开离线的文档页面无法进行翻译

**Comment by TaoLoading** [comment]
我没有复现你的问题。在翻译前你可以点开插件面板查看源语言与目标语言是否一致，一致时则不会出发翻译，此时手动指定源语言即可。如果此时还无法翻译，方便的话可以将 html 文件发送到我们的官方邮箱并注明 github issue，我们将会进一步排查问题。

或者你可以直接使用我们的 html 翻译功能：https://app.immersivetranslate.com/html/
