### ISSUE TITLE
pdf翻译内置到插件中

### ISSUE THREAD

**Issue by HandSonic** [immersive-translate/immersive-translate#2297]
### 您希望的更新和改进是什么 | Update or Improve

普通pdf翻译能否直接集成到插件中，无需访问网站进行。

### 补充说明 | Additional context

如果直接集成到插件中可以做到完全本地离线翻译，在某些情况下可能无法连接到互联网，但是又有pdf翻译需求，因此希望可以将pdf翻译直接集成到插件中，而不用访问那个网页

**Comment by theowenyoung** [comment]
这个是我们权衡之后的策略，考虑的点主要是为了能及时修改pdf的bug，以及减少插件包的大小。
