### ISSUE TITLE
建议设置中智能换行逻辑如果不换行的，使用两个空格分隔

### ISSUE THREAD

**Issue by luojunv** [immersive-translate/immersive-translate#2298]
### 您希望的更新和改进是什么 | Update or Improve

建议设置中“译文换行设置”的智能换行逻辑改进一下，如果不换行的，使用两个空格分隔（目前是一个空格分隔），以便自动文本识别工具将原文和译文分割开。

**Comment by keyboard3** [comment]
自动文本识别工具，为什么不通过标签选择器识别

**Comment by luojunv** [comment]
开源阅读app（安卓），将整段文本送给开源的tts server，只有文本，没有选择器标签。如果有两个空格，自己编写朗读规则将原文、译文分割的算法非常简单。现在只有一个空格分隔，则算法复杂很多。

**Comment by keyboard3** [comment]
将在1.12.1 支持

**Comment by luojunv** [comment]
谢谢！
