### ISSUE TITLE
Open Links in New Tabs

### ISSUE THREAD

**Issue by neoOpus** [immersive-translate/immersive-translate#230]
Hi,

It would be better if this internal links and the configuration open in new tab instead of into the same tab, which can cause some form filling loss…

(I can do the modification myself and do a PR if you agree)

**Comment by theowenyoung** [comment]
Hi, Thanks, that sounds good for me, I've invited you to the source repo: https://github.com/immersive-translate/next-translator

**Comment by theowenyoung** [comment]
we have supported it.
