### ISSUE TITLE
集成 js sdk 到 electron 中的问题

### ISSUE THREAD

**Issue by jimu-os** [immersive-translate/immersive-translate#2300]
### 您希望的更新和改进是什么 | Update or Improve

我把插件集成到 electron app中 使用的 js sdk 方式，我遇到了一些问题，我通过 electron 提供的 webview 标签成功的登陆了插件，在插件插件的悬浮面板上并没有显示登陆，我查看了浏览器内的缓存状态，登录的缓存数据都存在，所以在想是不是可以在js sdk中提供一些可以配置登录的 api 通过编程方式进行登录使用

**Comment by keyboard3** [comment]
js sdk 当前并不支持会员登录

**Comment by keyboard3** [comment]
暂时没有这个计划，后续有进展会在这里更新

**Comment by jimu-os** [comment]
嗯
