### ISSUE TITLE
ai翻译质量：<p>标签中包含<code>标签时，翻译不准确

### ISSUE THREAD

**Issue by beiguang-011** [immersive-translate/immersive-translate#2301]
### 您希望的更新和改进是什么 | Update or Improve

我在翻译时，感觉ai翻译准确度不如微软翻译和谷歌翻译，感觉是因为传递给ai的原代码格式(`<p>标签中包含<code>标签`)的问题。我使用的是普通ai，不是顶尖ai。

原代码格式：
<p>In the previous chapter the security system (which is based on the dependency injection system) was giving the <em>path operation function</em> a <code>token</code> as a <code>str</code></p>

原文：In the previous chapter the security system (which is based on the dependency injection system) was giving the path operation function a token as a str

微软翻译：
在上一章中，安全系统（基于依赖注入系统）为路径操作函数提供了一个 str 令牌
谷歌翻译：
在上一章中，安全系统（基于依赖注入系统）为路径操作函数提供了一个token作为str
SiliconCloud 翻译：
在上一章中，基于依赖注入系统的安全系统将路径操作函数作为 token 传递给了 str
智谱 GLM 翻译
在前一章中，安全系统（基于依赖注入系统）正在给路径操作函数提供一个 token 作为 str

原文是在介绍：
```
token: Annotated[str, Depends(oauth2_scheme)]
```

上下文：
```
from typing import Annotated

from fastapi import Depends, FastAPI
from fastapi.security import OAuth2PasswordBearer

app = FastAPI()

oauth2_scheme = OAuth2PasswordBearer(tokenUrl="token")


@app.get("/items/")
async def read_items(token: Annotated[str, Depends(oauth2_scheme)]):
    return {"token": token}
```

### 补充说明 | Additional context

不清楚原因是因为传递给ai的内容格式问题，还是ai的水平问题。如果是内容格式问题不知道是否可以改进？

网站地址：
https://fastapi.tiangolo.com/tutorial/security/get-current-user/

**Comment by beiguang-011** [comment]
还是说，原文结构太复杂，难以翻译？

**Comment by keyboard3** [comment]
可以去掉CODE标签
![QQ_1732679472336](https://github.com/user-attachments/assets/4681df7f-ec4e-4c67-84d0-be23c61a0aca)
![QQ_1732679529755](https://github.com/user-attachments/assets/5203ddd3-d0dc-4546-9556-9c8c6b677233)

```
    "stayOriginalTags.remove": [
      "CODE"
    ]
