### ISSUE TITLE
有关edx课程视频的翻译

### ISSUE THREAD

**Issue by Mysteryfans** [immersive-translate/immersive-translate#2302]
### 您希望的更新和改进是什么 | Update or Improve

如果一个课程页面有多个视频，沉浸式翻译只会提供第一个视频的中英字幕，希望能够改进一下

**Comment by Mysteryfans** [comment]
不行，我昨天试过了，只有第一个视频有中英字幕，后面就是全英文了，而且有的视频字幕是错的

**Comment by Mysteryfans** [comment]
> 我记得之前适配过，目前按钮只会在一个视频上增加，而双语字幕是在所有字幕上生效的，你仔细看下

不行，我昨天试过了，只有第一个视频有中英字幕，后面就是全英文了，而且有的视频字幕是错的

**Comment by TaoLoading** [comment]
url 发一下

**Comment by Mysteryfans** [comment]
> url 发一下

https://learning.edx.org/course/course-v1:GTx+CS1301xI+1T2024/block-v1:GTx+CS1301xI+1T2024+type@sequential+block@45a6a02b575d42dd80957c755005a111/block-v1:GTx+CS1301xI+1T2024+type@vertical+block@e961c7bddf6a434995bf7c97d901de94
第一个块的第一个视频字幕是错的，而且下面的视频没有字幕，别的多视频的块也是这样的

**Comment by TaoLoading** [comment]
已修复，首先将插件升级到最新版，然后访问如下链接再试下：

https://learning.edx.org/course/course-v1:GTx+CS1301xI+1T2024/block-v1:GTx+CS1301xI+1T2024+type@sequential+block@45a6a02b575d42dd80957c755005a111/block-v1:GTx+CS1301xI+1T2024+type@vertical+block@e961c7bddf6a434995bf7c97d901de94?imt_refresh_rule=1

**Comment by Mysteryfans** [comment]
> 已修复，首先将插件升级到最新版，然后访问如下链接再试下：
> 
> https://learning.edx.org/course/course-v1:GTx+CS1301xI+1T2024/block-v1:GTx+CS1301xI+1T2024+type@sequential+block@45a6a02b575d42dd80957c755005a111/block-v1:GTx+CS1301xI+1T2024+type@vertical+block@e961c7bddf6a434995bf7c97d901de94?imt_refresh_rule=1

nb，问题已修复，请问是只针对这个url进行的修复吗？还是其他的类似界面也进行了调整？

**Comment by TaoLoading** [comment]
> > 已修复，首先将插件升级到最新版，然后访问如下链接再试下：
> > https://learning.edx.org/course/course-v1:GTx+CS1301xI+1T2024/block-v1:GTx+CS1301xI+1T2024+type@sequential+block@45a6a02b575d42dd80957c755005a111/block-v1:GTx+CS1301xI+1T2024+type@vertical+block@e961c7bddf6a434995bf7c97d901de94?imt_refresh_rule=1
> 
> nb，问题已修复，请问是只针对这个url进行的修复吗？还是其他的类似界面也进行了调整？

edx 的视频全修复了

**Comment by Mysteryfans** [comment]
> > > 已修复，首先将插件升级到最新版，然后访问如下链接再试下：
> > > https://learning.edx.org/course/course-v1:GTx+CS1301xI+1T2024/block-v1:GTx+CS1301xI+1T2024+type@sequential+block@45a6a02b575d42dd80957c755005a111/block-v1:GTx+CS1301xI+1T2024+type@vertical+block@e961c7bddf6a434995bf7c97d901de94?imt_refresh_rule=1
> > 
> > 
> > nb，问题已修复，请问是只针对这个url进行的修复吗？还是其他的类似界面也进行了调整？
> 
> edx 的视频全修复了

明白，顺便再反映一下coursera上面偶尔会出现视频放着放着就只有英文字母没有翻译的问题，有时候多次刷新页面能解决，这个问题属于偶发没法稳定复现所以就在这稍微提一下吧

**Comment by TaoLoading** [comment]
> > > > 已修复，首先将插件升级到最新版，然后访问如下链接再试下：
> > > > https://learning.edx.org/course/course-v1:GTx+CS1301xI+1T2024/block-v1:GTx+CS1301xI+1T2024+type@sequential+block@45a6a02b575d42dd80957c755005a111/block-v1:GTx+CS1301xI+1T2024+type@vertical+block@e961c7bddf6a434995bf7c97d901de94?imt_refresh_rule=1
> > > 
> > > 
> > > nb，问题已修复，请问是只针对这个url进行的修复吗？还是其他的类似界面也进行了调整？
> > 
> > 
> > edx 的视频全修复了
> 
> 明白，顺便再反映一下coursera上面偶尔会出现视频放着放着就只有英文字母没有翻译的问题，有时候多次刷新页面能解决，这个问题属于偶发没法稳定复现所以就在这稍微提一下吧

可能是网络问题，翻译的比较慢，可以切换下其他翻译服务试试。之前没有对 coursera 做过会有副作用的处理
