### ISSUE TITLE
[Bug]: 当翻译两对花括号``` {{text}} ```中所包括的内容时，翻译内容会变为“联系我们”

### ISSUE THREAD

**Issue by ButterBartel3C3A** [immersive-translate/immersive-translate#2305]
### 插件版本号 | Version

1.11.4

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在使用Alt+A快捷键对整个页面进行翻译的时候，在两对花括号中包括着的内容`{{text}}` 的内容全部被翻译为了`联系我们`
![image](https://github.com/user-attachments/assets/36c5e75e-6217-4960-bbec-4f3538c23f23)
这显然有问题

### 出现问题的网址 | URL

https://toramameseven.github.io/markdown-docx-doc/en/basic/template/

### 重现步骤 | To Reproduce

1. 启用扩展，翻译服务使用腾讯交互翻译，打开网页
2. 键盘摁下Alt+A
3. 如问题描述所示

**Comment by keyboard3** [comment]
![QQ_1732539495708](https://github.com/user-attachments/assets/5770b87b-fe6e-4a68-a682-42ba6aa7104e)
翻译服务问题，切换下其他翻译服务
