### ISSUE TITLE
[Bug]: 英文页面无法正常翻译，一直在等待。

### ISSUE THREAD

**Issue by tianhua6636** [immersive-translate/immersive-translate#2306]
### 插件版本号 | Version

1.11.4

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

只提示“等待注入页面中...若长时间未响应，请尝试刷新页面”，刷新后还是没有翻译。

**Comment by keyboard3** [comment]
这说明当前网站没有加载完全，刷新之后等待悬浮球注入之后就可以翻了。你可以把网址贴出来，我们帮你验证下
