### ISSUE TITLE
[Bug]: 一些似乎是用于分词的标签出现在译文里

### ISSUE THREAD

**Issue by surinrasu** [immersive-translate/immersive-translate#2307]
### 插件版本号 | Version

1.8.1

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![](https://github.com/user-attachments/assets/e74bbd75-6231-4c01-b1dc-a33d80ee6b72)
![](https://github.com/user-attachments/assets/386faeef-76a1-421e-949a-50cea5b0e91b)

### 出现问题的网址 | URL

bsky.app

### 重现步骤 | To Reproduce

点击进入任何一条帖文或回复

**Comment by keyboard3** [comment]
你版本太低了，升级下版本，另外贴一个具体帖子的例子方便复现
