### ISSUE TITLE
Papago 401

### ISSUE THREAD

**Issue by neoOpus** [immersive-translate/immersive-translate#231]
For some reason I get 401 error when I use Papago in this userscript but I installed the Papago Translate who contacts the same api and it works...

Please let me know if you need more details

**Comment by theowenyoung** [comment]
Yes, when using userscrips, I believe papago block the tamper monkey requests. when you are using extension on firefox, it seems everything is fine.

**Comment by neoOpus** [comment]
You are right! I would love to know what is causing thing internally in TamperMonkey so I can fill a bug report to its developer.

**Comment by theowenyoung** [comment]
papago has down now.
