### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Micah123321** [immersive-translate/immersive-translate#2311]
### 插件版本号 | Version

1.11.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

目前版本在翻译discord的信息时会非常卡,非常占用cpu
我用的是deepseek翻译
关了翻译后就好了

### 出现问题的网址 | URL

https://discord.com/channels/

### 重现步骤 | To Reproduce

使用deepseek翻译频道的英文消息

**Comment by keyboard3** [comment]
打开 https://discord.com/channels/?imt_refresh_rule=1 再试下
