### ISSUE TITLE
更新后推文译文显示方式改变，影响原文整体性

### ISSUE THREAD

**Issue by kowasoul** [immersive-translate/immersive-translate#2312]
### 您希望的更新和改进是什么 | Update or Improve

更新前，译文显示在整条推文的下方，不会打乱原文本身的排版。
更新后，译文会穿插进推文中，变成这样→
![image](https://github.com/user-attachments/assets/ebfa591f-2a82-4218-af30-1f0a81e425a1)

即使在此处更改最小字符数也无效：
![image](https://github.com/user-attachments/assets/2ac99927-c893-4830-9c25-15ca6a5e5ec6)
（也许此处并非相关设置？）

这种逐句翻译后将译文逐句插进推文中的显示方式会对阅读原文时的整体性产生影响，如果原文有特殊排版还会打乱排版，用起来体验不太好。
能否在设置中增加一个可选用旧版显示方式的选项呢？
非常感谢。

**Comment by keyboard3** [comment]
![QQ_1732759496115](https://github.com/user-attachments/assets/b4e3efe6-a231-4998-88d9-e1306756d3ae)
这么配置

```
[
  {
    "id": "twitter",
    "isTransformPreTagNewLine": false
  }
]

**Comment by keyboard3** [comment]
因为发现现在分行有些bug，暂时全部回退到旧版效果。如果有小伙伴想用新版的每行分段翻译，按照上述过程，然后填入如下配置

```
[
  {
    "id": "twitter",
    "isTransformPreTagNewLine": true
  }
]

**Comment by prismriverrr** [comment]
@keyboard3 最新版本下，应该是默认整体翻译了，请问下如何改成分段翻译呢？我尝试把isTransformPreTagNewLine改成true后，仍然是整体翻译。
```
[
  {
    "id": "twitter",
    "isTransformPreTagNewLine": true
  }
]
```

https://x.com/immersivetrans/status/1762131486562767151

<img width="723" height="700" alt="Image" src="https://github.com/user-attachments/assets/6b3fd72c-f4ad-4033-8f30-1bc3c88d6354" />
