### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by StephenPan** [immersive-translate/immersive-translate#2314]
### 插件版本号 | Version

1.11.7 (2024-11-25)

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

推特点进长文或者推特文章时，基本上只要时进文章就会。会在翻译初期或者翻译一部分时出错，
网页内容全没有，显示：

出错了。请尝试重新加载。

### 出现问题的网址 | URL

https://x.com

**Comment by keyboard3** [comment]
能举个具体的帖子例子吗？在时间线上很难找这个

**Comment by StephenPan** [comment]
随机看到了：https://x.com/Defi0xJeff/status/1858927451415671004
打开沉浸的状态，点进去看一会（翻译后的状态）会崩溃，之后再打开同样的网页很快就直接崩溃。见图片
[image: image.png]

keyboard3 ***@***.***> 于2024年11月28日周四 11:03写道：

**Comment by StephenPan** [comment]
![FireShot Capture 003 - X 上的 0xJeff：“Why Virtuals Will Be a Unicorn by New Year's” _ X - x com](https://github.com/user-attachments/assets/e2242f48-1b06-4ae0-874e-64e1a16062eb)

**Comment by keyboard3** [comment]
推特这个文章页比较怪，会不停的纠正，你滑动到下面可以明显观察到在闪动，这个不太好确定是什么问题导致的，你之前没遇到是吧？可以暂时按照这个帖子方法回退旧效果再试试 https://github.com/immersive-translate/immersive-translate/issues/2312

**Comment by StephenPan** [comment]
你好，#23312回退旧效果无效，还是一样会崩溃。但我把“选择翻译后的显示方式：从仅显示译文改为双语对照后，就没在出现崩溃情况了，现在可以愉快玩耍了

**Comment by keyboard3** [comment]
仅译文在部分站点触发这个概率会高，因为原理是隐藏了原文，站点在重渲染时当发现原来的东西不见了就会崩溃
