### ISSUE TITLE
[Bug]: 有些类似按钮之类的选项不翻译

### ISSUE THREAD

**Issue by Emilia66666** [immersive-translate/immersive-translate#2315]
### 插件版本号 | Version

1.11.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/user-attachments/assets/45b77128-e4cf-4128-9637-3d51e81d1da7)

**Comment by keyboard3** [comment]
这是故意为之，未来保证排版整洁，只翻译正文区域。如果想要翻译所有区域，可以在这里开启
![QQ_1732765684059](https://github.com/user-attachments/assets/e9beb650-dbf6-4599-bd14-55db5d6e3e06)
但是不建议这么做
