### ISSUE TITLE
SiliconCloud 翻译 里面希望加入Qwen/Qwen2.5-7B-Instruct 模型支持

### ISSUE THREAD

**Issue by wangshankun** [immersive-translate/immersive-translate#2317]
### 您希望的更新和改进是什么 | Update or Improve

硅基流动Qwen/Qwen2.5-7B-Instruct 已经免费，希望翻译里面加入

https://cloud.siliconflow.cn/models?target=Qwen/Qwen2.5-7B-Instruct

**Comment by keyboard3** [comment]
你也可以自定义模型名，下个版本会加上

**Comment by wangshankun** [comment]
> 你也可以自定义模型名，下个版本会加上

谢谢，会用了
