### ISSUE TITLE
[Bug]: 插件浮窗没有显示，不能翻译

### ISSUE THREAD

**Issue by anlijun** [immersive-translate/immersive-translate#2322]
### 插件版本号 | Version

1.11.7

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

这个网站的页面子，不能显示翻译浮窗，不能翻译。（快捷键也不能响应、右键翻译也不能响应）
https://chromewebstore.google.com

### 出现问题的网址 | URL

https://chromewebstore.google.com/detail/chatgpt-sidebar-gpt-4-vis/becfinhbfclcgokjlobojlnldbfillpf

**Comment by keyboard3** [comment]
chrome商店是chrome浏览器保护页面，不允许插件修改，你可以用其他浏览器来翻译这个页面
