### ISSUE TITLE
[Bug]: Firefox 中无法对 addons.mozilla.org 上的页面进行翻译

### ISSUE THREAD

**Issue by function2-llx** [immersive-translate/immersive-translate#2324]
### 插件版本号 | Version

1.11.4

### 平台 | Platform

Linux

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

如题，在 Firefox 中无法对 addons.mozilla.org 上的页面进行翻译。打开网站后，悬浮球不会弹出，点开插件页面会显示“等待注入页面中...若长时间未响应，请尝试刷新页面”。
![image](https://github.com/user-attachments/assets/8a7f30fe-6f57-4ea4-a8b1-fe27ee1d9341)

### 出现问题的网址 | URL

https://addons.mozilla.org

### 重现步骤 | To Reproduce

1. 用 Firefox 访问 https://addons.mozilla.org
2. 检查悬浮球（不会出现）
3. 点开插件页面，会显示“等待注入页面中...若长时间未响应，请尝试刷新页面”。

**Comment by keyboard3** [comment]
火狐浏览器对该地址保护，插件无法生效。可以借用其他浏览器来翻译该页面

**Comment by function2-llx** [comment]
非常感谢解答。查了一下，确实官方有[提到过](https://hacks.mozilla.org/2016/02/implementing-content-security-policy)对此网站实现了 CSP。为了不使用其它浏览器，我最后是勉强用 Wayback Machine 这样的工具打开页面来查看翻译了。
