### ISSUE TITLE
希望沉浸式翻译可以翻译Shadow DOM内的内容，不知道技术上能否实现

### ISSUE THREAD

**Issue by lianwensheng** [immersive-translate/immersive-translate#2326]
### 您希望的更新和改进是什么 | Update or Improve

有些浏览器插件（例如ChatGPT for Google）使用了Shadow DOM，导致鼠标悬停翻译失效...
![屏幕截图 2024-12-01 122540](https://github.com/user-attachments/assets/cf5ce722-0ced-44bb-bba4-b167c071ea58)

**Comment by keyboard3** [comment]
因为它用的谷歌插件的sidepanel 特性，此sidepanel是一个独立的沙盒环境，插件无法干预
