### ISSUE TITLE
为不同网站设置不同默认翻译引擎

### ISSUE THREAD

**Issue by indexss** [immersive-translate/immersive-translate#2327]
### 您希望的更新和改进是什么 | Update or Improve

沉浸式翻译插件中，可以设置总是翻译该网站。然而，如果想要准确性，我们就要用LLM，比如ChatGPT的api去做翻译，但是使用LLM的翻译速度远不如使用传统翻译引擎如Google Translate快。而对于类似Reddit的页面，我就希望默认用Google Translate来快速翻译，扫一眼大家在大概说什么；但对于一些技术文章等需要精读的内容，我就希望能用LLM翻译，即使慢一点。

现在的情况是，如果我设置了Reddit和Midium默认翻译该网站，那么它们会调用目前设置的翻译引擎，而不是记住当时用的翻译引擎。希望能够增加选项来改善这一点。

**Comment by keyboard3** [comment]
参考这里 https://immersivetranslate.com/zh-Hans/docs/advanced/#%E5%A6%82%E4%BD%95%E8%AE%A9%E4%B8%8D%E5%90%8C%E7%9A%84%E7%AB%99%E7%82%B9%E9%BB%98%E8%AE%A4%E9%80%89%E6%8B%A9%E4%B8%8D%E5%90%8C%E7%9A%84%E7%BF%BB%E8%AF%91%E6%9C%8D%E5%8A%A1%E4%BE%8B%E5%A6%82%E6%9C%89%E7%9A%84%E7%BD%91%E7%AB%99%E6%88%91%E6%83%B3%E8%A6%81%E5%A5%BD%E4%B8%80%E7%82%B9%E4%BD%86%E8%A6%81%E8%8A%B1%E9%92%B1%E7%9A%84%E7%BF%BB%E8%AF%91%E6%95%88%E6%9E%9C%E6%9C%89%E7%9A%84%E7%BD%91%E7%AB%99%E6%88%91%E5%8F%AA%E9%9C%80%E8%A6%81%E5%85%8D%E8%B4%B9%E8%83%BD%E7%9C%8B%E7%9A%84%E7%BF%BB%E8%AF%91%E5%B0%B1%E8%A1%8C%E4%BA%86
