### ISSUE TITLE
[Bug]: vk video网站不能实现双语字幕

### ISSUE THREAD

**Issue by 569972301** [immersive-translate/immersive-translate#2329]
### 插件版本号 | Version

1.11.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

vk网站不能实现视频字幕，YouTube是可以的。。请帮忙查看原因，多谢

### 出现问题的网址 | URL

https://vkvideo.ru/

**Comment by keyboard3** [comment]
现在应该好了
