### ISSUE TITLE
Loading icon color

### ISSUE THREAD

**Issue by iG8R** [immersive-translate/immersive-translate#233]
Hi.
I noticed that there is a possibility appeared in 0.3.3 to select "Loading icon color, from black to blue, for adapt the dark mode web page."
Where in the settings could I select this option?
Could it be possible to choose not only blue but also red colored icon like it was in previous builds?

**Comment by theowenyoung** [comment]
Sorry, there is no option for this   yet, and like the change logs, the previous version loading spinner color is black, not red.

**Comment by iG8R** [comment]
Ah, thanks.
