### ISSUE TITLE
[Bug]: 屏幕上翻译的文字每隔4秒种抖动一下

### ISSUE THREAD

**Issue by dearsn** [immersive-translate/immersive-translate#2331]
### 插件版本号 | Version

1.11.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

[Bug]: 屏幕上翻译的文字每隔4秒种抖动一下 ，很多网址都出现过这个抖动的问题

### 出现问题的网址 | URL

https://tlcr.amegroups.org/article/view/89807/html

### 重现步骤 | To Reproduce

1. go to https://tlcr.amegroups.org/article/view/89807/html
2. click 翻译

**Comment by keyboard3** [comment]
没能复现抖动情况，应该是你有其他插件修改页面文字。给插件隐私窗口权限，在隐身窗口中尝试。或者禁用相关插件排除下

**Comment by keyboard3** [comment]
暂无反馈 关闭此issue
