### ISSUE TITLE
右键菜单显示过长

### ISSUE THREAD

**Issue by oneo-me** [immersive-translate/immersive-translate#2332]
### 您希望的更新和改进是什么 | Update or Improve

是否可以考虑将右键菜单中的 Translate to xxxx 修改为 Translate Page 之类的（正常翻译目标语言就一个），并支持隐藏快捷键提示

![image](https://github.com/user-attachments/assets/dcf7b793-2e24-40d8-bbbe-3977ae632278)

备注：截图是 Safari 版本的

**Comment by theowenyoung** [comment]
（这个有点太自定义了... 

如果不需要这个菜单的话，可以在 进阶设置 中 关闭 右键菜单即可～

![CleanShot 2024-12-06 at 13 30 56@2x](https://github.com/user-attachments/assets/98ed9b04-abbd-460b-900e-f0a5fcd74eac)
