### ISSUE TITLE
[Bug]: “鼠标悬停翻译当前段落”功能无法设置快捷键

### ISSUE THREAD

**Issue by dan-kuroto** [immersive-translate/immersive-translate#2334]
### 插件版本号 | Version

1.11.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

如下图所示，“鼠标悬停翻译当前段落”只能设置触屏手势，无法设置快捷键（以前应该是可以选择ctrl/shift/alt的）

![image](https://github.com/user-attachments/assets/ea9ba877-3945-4ab2-97f9-fd45fcaf3d0a)
![image](https://github.com/user-attachments/assets/0064c7d7-0e92-4945-a765-39bec4321cb5)

**Comment by keyboard3** [comment]
这是因为当前浏览器两种模式都支持，你可以在 https://dash.immersivetranslate.com/#advanced 这里找到这个选项开启
![QQ_1733328403215](https://github.com/user-attachments/assets/9065e61c-318f-4f4a-a7bf-075189e521e0)
