### ISSUE TITLE
[Bug]: 无法翻译 readthedocs 网站上 `code` 标签的内容

### ISSUE THREAD

**Issue by dnomd343** [immersive-translate/immersive-translate#2335]
### 插件版本号 | Version

1.11.7

### 平台 | Platform

macOS, iOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

相当部分计算机类文档，特别是 python 相关的文档会托管在[readthedocs.io](https://readthedocs.io/)这个网站上，目前发现这个网站在 iOS 与 macOS 的 Safari 浏览器上，开启双语翻译会出现 html 中的 `code` 块内容缺失的情况。例如这篇 pybind11 的[文档](https://pybind11.readthedocs.io/en/stable/advanced/functions.html)中，由于这些 `术语` 的缺失，翻译结果需要参照英语原文才能阅读，如图：

![IMG_5148](https://github.com/user-attachments/assets/a1e31a7d-7d65-481e-b7ea-505b3ae34426)

### 出现问题的网址 | URL

https://pybind11.readthedocs.io/en/stable/advanced/functions.html

### 重现步骤 | To Reproduce

1. 进入上述链接或其他包含 `code` 块的 readthedocs 页面
2. 触发插件翻译功能，查阅带有 `code` 块的段落

**Comment by keyboard3** [comment]
![QQ_1733368938738](https://github.com/user-attachments/assets/f340693c-60a2-4678-b130-ba5a5c1a235f)
你使用了什么翻译服务？没能复现

**Comment by dnomd343** [comment]
我这边使用谷歌翻译和微软翻译，在macOS和iOS上都可以复现，我尝试抓包以下段落谷歌翻译的请求：
![IMG_5152](https://github.com/user-attachments/assets/ce6655c3-9866-4644-b07c-d88397120948)

请求API如下：
![IMG_5151](https://github.com/user-attachments/assets/494c8481-762c-4414-a625-7f9f26859e2f)

请求体如下：
![IMG_5150](https://github.com/user-attachments/assets/ff9cbd4c-4ffb-4970-a522-71213f62d39e)

响应体如下：
![IMG_5149](https://github.com/user-attachments/assets/03d1fbb7-7e7b-4b6a-8ecf-4c3f8d81a63c)

可以看到请求内容中就缺失 code 块内容了，因此最终不会显示出来。

奇怪的是，除了这个网站，其他页面例如 github 的 README 都是正常的。

**Comment by keyboard3** [comment]
点击下页面旁边的悬浮球反馈按钮，反馈下，我看下日志

**Comment by dnomd343** [comment]
谢谢，已提交反馈。

在尝试后发现智谱GLM翻译正常，抓包后发现code块被替换成标记符了，看起来似乎是谷歌翻译和微软翻译没有被这样子替换。

![Picsew_20241205115637](https://github.com/user-attachments/assets/221361d4-d259-44ed-9f9b-42b0fd7761a8)

**Comment by keyboard3** [comment]
嗯 我可以复现了，我待会看下问题

**Comment by keyboard3** [comment]
https://pybind11.readthedocs.io/en/stable/advanced/functions.html?imt_refresh_rule=1重试下

**Comment by dnomd343** [comment]
> [https://pybind11.readthedocs.io/en/stable/advanced/functions.html?imt_refresh_rule=1重试下](https://pybind11.readthedocs.io/en/stable/advanced/functions.html?imt_refresh_rule=1%E9%87%8D%E8%AF%95%E4%B8%8B)

感谢，加入这个字段后看起来正常了。

这个字段看起来是传递给插件的，相当多 issue 也能发现加入 `imt_refresh_rule=1` 的处理方式，它是否能作为网站列表直接内置在插件中，在识别到对应域名时自动开启呢？

**Comment by keyboard3** [comment]
不是 这个参数只是让插件立刻更新规则。打开面板已经定时都会更新规则，只是让你能够立刻更新看到变化
