### ISSUE TITLE
[Bug]: 之前在arxiv H5版本( ar5iv.labs.arxiv.org )是不翻译公式的，现在突然开始试图翻译公式了

### ISSUE THREAD

**Issue by RaySibay** [immersive-translate/immersive-translate#2336]
### 插件版本号 | Version

1.11.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

之前在arxiv H5版本( ar5iv.labs.arxiv.org )是不翻译公式的，现在突然开始试图翻译公式了，然后公式就会变成一堆奇怪的东西
![image](https://github.com/user-attachments/assets/45545b3b-c346-4fd6-9c17-c75ec3934750)

### 出现问题的网址 | URL

https://ar5iv.labs.arxiv.org/html/2107.10374

**Comment by keyboard3** [comment]
打开 https://ar5iv.labs.arxiv.org/html/2107.10374?imt_refresh_rule=1 再试下
