### ISSUE TITLE
四指触摸翻译能改成三指吗？

### ISSUE THREAD

**Issue by Jeasin** [immersive-translate/immersive-translate#2337]
### 您希望的更新和改进是什么 | Update or Improve

设备iPhone 15 Pro，Safari iOS端。四指触摸，我手比屏幕大，而且要把小拇指放屏幕上也有点不舒服。如果三指就从容多了！

**Comment by keyboard3** [comment]
https://dash.immersivetranslate.com/#shortcuts 在这里选择

**Comment by Jeasin** [comment]
> https://dash.immersivetranslate.com/#shortcuts 在这里选择

感谢
