### ISSUE TITLE
希望悬浮窗可以隐藏

### ISSUE THREAD

**Issue by Jeasin** [immersive-translate/immersive-translate#2338]
### 您希望的更新和改进是什么 | Update or Improve

希望可以自定义悬浮窗显示，粉粉的悬浮窗有点影响网页沉浸感。

**Comment by keyboard3** [comment]
https://dash.immersivetranslate.com/#floating 自行关闭

**Comment by Jeasin** [comment]
不好意思我是代笔，手机上没看见，电脑上看到了
