### ISSUE TITLE
[Bug]: pdf翻译的文字灰白色

### ISSUE THREAD

**Issue by actforjason** [immersive-translate/immersive-translate#2339]
### 插件版本号 | Version

1.11.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

原文字黑色，但翻译后灰白色，不易看见
![image](https://github.com/user-attachments/assets/f608f4a1-732c-4481-9a02-7a48bc75049e)

**Comment by keyboard3** [comment]
检查是否存在主题相关插件

**Comment by actforjason** [comment]
关闭dark reader后还是这样

**Comment by meijin1123** [comment]
<img width="1307" alt="image" src="https://github.com/user-attachments/assets/4ae1fe2c-3f12-4cd0-879f-02a5363263f1">
我这边使用window  火狐和edge浏览器验证都是正常的，卸载重装一下再检查一下是否有其他插件都关掉再试试。

**Comment by actforjason** [comment]
用stylebot插入css解决了，顺便实现了深色功能
```css
.textLayer{
  background-color: #222;
}
```
![图片](https://github.com/user-attachments/assets/0354a54b-e104-4ff1-bca7-2a362d6ebfe3)
#734
