### ISSUE TITLE
请求支持自定义OpenAI API地址

### ISSUE THREAD

**Issue by levie-vans** [immersive-translate/immersive-translate#234]
因为国内api.openai.com被墙，通过代理速度又慢，现在很多人会采取在韩国等地方进行api.openai.com的反向代理，来提高速度和绕过封锁。
所以，请求支持可以自定义API地址。

**Comment by theowenyoung** [comment]
好 下个版本加一个ui的选项。

其实现在的版本可以自定义的： https://immersive-translate.owenyoung.com/advanced#%E7%BF%BB%E8%AF%91%E6%9C%8D%E5%8A%A1%E9%85%8D%E7%BD%AE

在开发者配置里自己修改 apiUrl 的配置即可。

**Comment by theowenyoung** [comment]
0.3.5 已支持

**Comment by levie-vans** [comment]
感谢，太好了

**Comment by mobilestack** [comment]
> 0.3.5 已支持

请问如何设置？是在选项中吗？0.3.17版本是这样的

<img width="1173" alt="image" src="https://user-images.githubusercontent.com/5794691/230717131-f6b0e42f-3e97-4cbb-9da9-6c96c256278b.png">

**Comment by mobilestack** [comment]
恕我眼拙

找到了，不好意思


<img width="645" alt="image" src="https://user-images.githubusercontent.com/5794691/230718210-c945c1b7-f50a-4b15-aaa0-6c9c3a299b20.png">
