### ISSUE TITLE
[Bug]: Twitter的@句柄会翻译，且无法hover查看详情

### ISSUE THREAD

**Issue by lunula8** [immersive-translate/immersive-translate#2340]
### 插件版本号 | Version

最新

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

Twitter的@句柄会翻译，且无法hover查看详情。
预期是无需翻译，且不影响hover查看详情

**Comment by keyboard3** [comment]
参考 https://github.com/immersive-translate/immersive-translate/issues/2312
