### ISSUE TITLE
多语言提示词变量

### ISSUE THREAD

**Issue by function2-llx** [immersive-translate/immersive-translate#2341]
### 您希望的更新和改进是什么 | Update or Improve

希望能加入多语言提示词变量，例如对于目标语言变量 {{to}} （值：English, Chinese, etc.）提供对应中文版 {{to:zh}}（值：英文，中文，等等）。

### 补充说明 | Additional context

动机：我在用一些中国国内的大语言模型时，发现有时用中文提问效果稍好，因此希望能对应构造中文的 prompt。

**Comment by flamintune** [comment]
对于不同语言使用不同的prompt这个是支持的，可以看下下面的文档来配置

https://immersivetranslate.com/zh-Hans/docs/advanced/#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%A4%9A%E8%AF%AD%E8%A8%80%E6%8F%90%E7%A4%BA%E8%AF%8D
