### ISSUE TITLE
[Bug]: via脚本版沉浸式翻译推特显示分段

### ISSUE THREAD

**Issue by Zhangyx0824** [immersive-translate/immersive-translate#2343]
### 插件版本号 | Version

1.11.7

### 平台 | Platform

Android

### 浏览器 | Browsers

Other

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

推特翻译的内容会分段
图一是via 图二是雨见用的插件是正常的

![Screenshot_2024-12-06-03-22-41-833_mark via](https://github.com/user-attachments/assets/63ed8858-7f03-4639-a3d2-5a6ab76cd36b)
![Screenshot_2024-12-06-03-24-36-114_com yujian ResideMenuDemo](https://github.com/user-attachments/assets/ab2a4125-2d31-4c57-a26a-559df6b3cd31)

### 出现问题的网址 | URL

https://x.com/home

### 重现步骤 | To Reproduce

推特翻译

**Comment by keyboard3** [comment]
参考这个帖子 https://github.com/immersive-translate/immersive-translate/issues/2312

**Comment by Zhangyx0824** [comment]
可以了 十分感谢🙏🏻
