### ISSUE TITLE
[Bug]: firefox浏览器打开arxiv中的pdf无法翻译，一直显示等待注入页面

### ISSUE THREAD

**Issue by d-stortion** [immersive-translate/immersive-translate#2346]
### 插件版本号 | Version

1.11.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

使用arxiv时，通过View PDF打开pdf，右侧没有悬浮按钮，点击右上角图标，提示“等待注入页面中...若长时间未响应，请尝试刷新页面”

### 出现问题的网址 | URL

https://arxiv.org/pdf/2411.17911

### 重现步骤 | To Reproduce

1.打开上面的URL，或者任意arxiv论文pdf页面
2.出现上述情况

**Comment by keyboard3** [comment]
这是因为火狐不允许插件和内置pdf阅读器交互
https://bugzilla.mozilla.org/show_bug.cgi?id=1454760
