### ISSUE TITLE
[Bug]: outlook邮箱网页版无法显示双语翻译

### ISSUE THREAD

**Issue by JiatongBu** [immersive-translate/immersive-translate#2347]
### 插件版本号 | Version

1.11.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox, Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

使用outlook邮箱网页版时，不会出现双语对照翻译页面，中文翻译会覆盖原英文翻译，其余邮箱均可正常翻译。

### 出现问题的网址 | URL

https://outlook.live.com

### 重现步骤 | To Reproduce

1.打开上面的URL,点击翻译
2.出现上述情况

**Comment by keyboard3** [comment]
这是故意设置，因为outlook.live的网页结构无法适配双语，双语效果会导致整个排版非常丑陋。可以通过如下配置恢复
https://dash.immersivetranslate.com/#developer
![QQ_1733538650781](https://github.com/user-attachments/assets/b12dea8d-9bfc-4fd5-af9a-abfebf7e73d9)

```
[
  {
    "id": "outlook",
    "matches": "outlook.live.com",
    "translationMode": ""
  }
]```
