### ISSUE TITLE
pdf 翻译时出现错位重叠的情况

### ISSUE THREAD

**Issue by xiaozhu1337** [immersive-translate/immersive-translate#235]
特别是原文中字体不一样的时候，会出现错位，重叠的情况
![image](https://user-images.githubusercontent.com/50901869/224604331-2ba6fb65-3d06-4edf-ac3a-d883e0c1eaf4.png)
![image](https://user-images.githubusercontent.com/50901869/224604409-30371605-5a63-4b58-b97c-0a480f1c260e.png)

**Comment by wk-mike** [comment]
同问，可以在arxiv上面找了一篇论文测试
https://arxiv.org/pdf/2303.05813.pdf

一个屏幕还显示不完整

**Comment by xiaozhu1337** [comment]
> 

是的，目前观察，只要出现字体不一样的情况就会重叠

**Comment by wk-mike** [comment]
如果是arxiv网站，可以集合一个这个服务 
https://github.com/dginev/ar5iv 
直接生成HTML
这样就很方便了

**Comment by theowenyoung** [comment]
0.5.5版本已基本解决～
