### ISSUE TITLE
[Bug]: ChatGPT没有完全屏蔽公式翻译

### ISSUE THREAD

**Issue by EllyL0615** [immersive-translate/immersive-translate#2350]
### 插件版本号 | Version

V1.11.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome, Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension, 油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

有的公式被成功屏蔽翻译，但并不是所有
![e51063300d3d6f00dc8b51a745128cc](https://github.com/user-attachments/assets/e3abab12-8d94-4874-855e-7a0f7168c6b9)
![image](https://github.com/user-attachments/assets/0411b471-adcf-42ff-b3c3-784f2746888b)

### 出现问题的网址 | URL

https://chatgpt.com/

### 重现步骤 | To Reproduce

1. 打开chatgpt网页版
2. 让它生成任何包含latex公式的文本，例如：
Since the price in £ of the EU bond and stock are \( E B_f \) and \( E S_f \), where \( E := E_{€/£} \) (the exchange rate), a British investor would model this market with the processes \( (B_d, S_d, E B_f, E S_f) \), whereas a European investor would model the same market as \( (E^{-1} B_d, E^{-1} S_d, B_f, S_f) \).  
Moreover, the British investor would normally use \( B_d \) as the numeraire, whereas the European investor would use \( B_f \).

**Comment by keyboard3** [comment]
在当前页面翻译完点击下 悬浮球的反馈按钮反馈下，会收集快照方便开发调试

**Comment by keyboard3** [comment]
暂无反馈 关闭此issue
