### ISSUE TITLE
[Bug]: 在pdf的翻译中  文本总是被设置为白色  总是被设置黑色的背景图

### ISSUE THREAD

**Issue by 363139368** [immersive-translate/immersive-translate#2352]
### 插件版本号 | Version

1.11.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

我在翻译一个pdf的文章后  字体的颜色总是固定的白色  翻译后的字体背景 总是黑色的  并且 在一些代码块中的注释 并不能被正确的列入到翻译范围中   
pdf是这个链接对应的ebook  https://unity.com/cn/resources/introduction-to-dots-ebook

### 出现问题的网址 | URL

https://unity.com/cn/resources/introduction-to-dots-ebook

### 重现步骤 | To Reproduce

下载他 然后翻译

### 补充说明 | Additional context

下载他 然后翻译

**Comment by keyboard3** [comment]
免费对照工具是以原文作为背景，所以译文的文字会和原文重叠，所以会有文字的白色背景来覆盖原文

PDF 翻译中，所有PDF内容都是纯文本被翻译
