### ISSUE TITLE
https://vkvideo.ru/ 网站视频，实时字幕不像youtube一样稳定

### ISSUE THREAD

**Issue by 569972301** [immersive-translate/immersive-translate#2355]
### 您希望的更新和改进是什么 | Update or Improve

https://vkvideo.ru/ 网站视频，实时字幕不像youtube一样稳定，不能像youtube一样提前翻译好，然后整段出现。现在是，说一个词，屏幕翻译就会跳（重新翻译），都看不清字幕了。。。感谢沉浸翻译的大佬，希望帮忙改进。

**Comment by keyboard3** [comment]
现在呢？

**Comment by 569972301** [comment]
> 现在呢？

已经完美了。。大佬，多谢
