### ISSUE TITLE
[Bug]: 手势无法正常触发翻译，也找不到更改手势的界面了。

### ISSUE THREAD

**Issue by ppovxxvoqq** [immersive-translate/immersive-translate#2356]
### 插件版本号 | Version

1.11.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

手势无法正常触发翻译，也找不到更改手势的界面了。

**Comment by keyboard3** [comment]
在快捷键设置中 https://dash.immersivetranslate.com/#shortcuts

**Comment by keyboard3** [comment]
你说的是你目前是手势触发，想用鼠标翻译吧？  https://dash.immersivetranslate.com/#advanced 
![image](https://github.com/user-attachments/assets/ce666dbc-c0e4-4936-98c5-5a184824b73c)
