### ISSUE TITLE
【增加功能】支持编辑翻译内容

### ISSUE THREAD

**Issue by Eyion** [immersive-translate/immersive-translate#236]
编辑翻译内容算是个痛点吧，之前使用过某云小译后来收费了（编辑后保存为单文件，好像还能进行二次编辑），是否方便加入此功能？

**Comment by theowenyoung** [comment]
一般是什么场景下会想编辑并保存html文件呢？

**Comment by Eyion** [comment]
外文的文章经中外对照翻译后保存到本地(mhtml格式)供以后离线翻阅，有些内容不那么准确时能修改并保存。

**Comment by theowenyoung** [comment]
好，了解，未来确实有计划针对译文做一系列的操作的，比如编辑译文～

**Comment by Eyion** [comment]
辛苦了，期待越来越好用

**Comment by keyboard3** [comment]
1.4.12 已支持。 面板【更多】入口添加临时开启译文编辑功能
