### ISSUE TITLE
[Bug]: WIN10+Firefox ESR 128.5.2 插件的翻译快捷键被锁定在Four-finger Touch 无法修改

### ISSUE THREAD

**Issue by esyvjlomh** [immersive-translate/immersive-translate#2365]
### 插件版本号 | Version

1.11.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/user-attachments/assets/5ea0bc76-bf68-412c-8aa1-ba97ed291ff0)
暂不确定是不是浏览器的问题，但在不久前某次更新后翻译插件的快捷键就一直被锁在了Four-finger Touch且无法修改（但使用的是桌面WIN10，且为没有触摸功能的Desktop）。尝试卸载插件重装无果。

### 出现问题的网址 | URL

与URL无关。

**Comment by keyboard3** [comment]
https://dash.immersivetranslate.com/#advanced

![image](https://github.com/user-attachments/assets/e8e54fd4-8e23-4f24-bcc7-274879ffd5c9)
改下这个看

**Comment by esyvjlomh** [comment]
> https://dash.immersivetranslate.com/#advanced
> 
> ![image](https://private-user-images.githubusercontent.com/13177744/395785856-e8e54fd4-8e23-4f24-bcc7-274879ffd5c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxODQ3MDQsIm5iZiI6MTczNDE4NDQwNCwicGF0aCI6Ii8xMzE3Nzc0NC8zOTU3ODU4NTYtZThlNTRmZDQtOGUyMy00ZjI0LWJjYzctMjc0ODc5ZmZkNWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE0VDEzNTMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MTBlMTMwODdiZDY3ODFjZDA1MDZhMWU4NDE5MWI5MmUzMTgxNWIwZDdjNWRmMzRkY2QyYTk5YzZmMGY3YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Wl1ZhX0FYz_91cNCwFCbyq5lmDmNLYGOEgF_lEtrSBQ) 改下这个看

您好 我的插件里好像没有这个可选项，如下图：
![image](https://github.com/user-attachments/assets/846f55fe-0cba-4a76-a136-3b6efe2e3aef)

**Comment by keyboard3** [comment]
那你不可能有是触摸模式呀，你https://dash.immersivetranslate.com/#shortcuts 长什么样

**Comment by esyvjlomh** [comment]
> 那你不可能有是触摸模式呀，你https://dash.immersivetranslate.com/#shortcuts 长什么样

确实没什么道理 所以我怀疑是浏览器有奇怪的bug，shortcuts界面如下：
![image](https://github.com/user-attachments/assets/6cf1dca4-5728-4d7e-946c-35cf2aef6165)

**Comment by esyvjlomh** [comment]
> > 那你不可能有是触摸模式呀，你https://dash.immersivetranslate.com/#shortcuts 长什么样
> 
> 确实没什么道理 所以我怀疑是浏览器有奇怪的bug，shortcuts界面如下： ![image](https://private-user-images.githubusercontent.com/69969014/395787474-6cf1dca4-5728-4d7e-946c-35cf2aef6165.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxODU4NjQsIm5iZiI6MTczNDE4NTU2NCwicGF0aCI6Ii82OTk2OTAxNC8zOTU3ODc0NzQtNmNmMWRjYTQtNTcyOC00ZDdlLTk0NmMtMzVjZjJhZWY2MTY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE0VDE0MTI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkYTI4YzExOTY4NGRjOGYwMDdjMzEzOTFjYjA2MDc4NDQyYmRlMmY0MzdjZmIxNzY2NzUzZWFiNGEzNjU1YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.73hxiEk8kJ9QHhHXa__CgC6qCB4amD008NMAwmRI_Xw)

左侧是滚动截屏导致的重复出现（非插件问题）

**Comment by keyboard3** [comment]
有个方法或许可以，你打开网页的开发者模式，然后调整窗口成移动端效果。然后会模拟出现出现我说的那个选项。然后点击开启试试
![image](https://github.com/user-attachments/assets/704f3a30-a3fd-4949-bf4d-4e38ffbe66e7)

**Comment by esyvjlomh** [comment]
> 有个方法或许可以，你打开网页的开发者模式，然后调整窗口成移动端效果。然后会模拟出现出现我说的那个选项。然后点击开启试试 ![image](https://private-user-images.githubusercontent.com/13177744/395791231-704f3a30-a3fd-4949-bf4d-4e38ffbe66e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMTIwMjIsIm5iZiI6MTczNDMxMTcyMiwicGF0aCI6Ii8xMzE3Nzc0NC8zOTU3OTEyMzEtNzA0ZjNhMzAtYTNmZC00OTQ5LWJmNGQtNGUzOGZmYmU2NmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDAxMTUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiNjRkODJiZWRhMjQwODJjZTgzMTQ2YzFjMjNkMGI2YjljNmNhMjVhMzNiNTkyZDdlYTZjYzYzMWMxNjQ0M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lCcaYxwtYQhbRQMwQOQQD-hQg0p_5qEJEaK9h0Y7kqo)

进行了尝试但依旧没有成功debug，同时我在另一台WIN11电脑的同版本浏览器上进行了check，并没有出现类似问题。我之后尝试一下重装浏览器看看，没有问题的话会Close Issue，感谢支持！

**Comment by esyvjlomh** [comment]
> > 有个方法或许可以，你打开网页的开发者模式，然后调整窗口成移动端效果。然后会模拟出现出现我说的那个选项。然后点击开启试试 ![image](https://private-user-images.githubusercontent.com/13177744/395791231-704f3a30-a3fd-4949-bf4d-4e38ffbe66e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMTIwMjIsIm5iZiI6MTczNDMxMTcyMiwicGF0aCI6Ii8xMzE3Nzc0NC8zOTU3OTEyMzEtNzA0ZjNhMzAtYTNmZC00OTQ5LWJmNGQtNGUzOGZmYmU2NmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDAxMTUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiNjRkODJiZWRhMjQwODJjZTgzMTQ2YzFjMjNkMGI2YjljNmNhMjVhMzNiNTkyZDdlYTZjYzYzMWMxNjQ0M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lCcaYxwtYQhbRQMwQOQQD-hQg0p_5qEJEaK9h0Y7kqo)
> 
> 进行了尝试但依旧没有成功debug，同时我在另一台WIN11电脑的同版本浏览器上进行了check，并没有出现类似问题。我之后尝试一下重装浏览器看看，没有问题的话会Close Issue，感谢支持！

经过排查的结论是，之前因为一些需求安装了网易uu远程软件，安装后造成了一些奇怪的影响，导致所有浏览器（包括Firefox和edge）都会出现如上问题，将该软件卸载后恢复了正常。
