### ISSUE TITLE
智谱GLM和SiliconCloud保留链接

### ISSUE THREAD

**Issue by wyy-ybb** [immersive-translate/immersive-translate#2366]
### 您希望的更新和改进是什么 | Update or Improve

在用质谱GLM和SiliconCloud翻译时，所有超链接会变为普通文本，希望能保留链接。
毕竟这俩是最好的免费翻译嘛

**Comment by wyy-ybb** [comment]
别的html格式好像都可以，就超链接不行

**Comment by keyboard3** [comment]
展开 自定义选项，选择富文本翻译。不过不建议启用，大模型纯文本翻译的翻译质量要高于富文本翻译

![image](https://github.com/user-attachments/assets/738a9dab-8c91-4fc9-8b32-6dfd484c11f3)

**Comment by wyy-ybb** [comment]
yes that's really good
~~man what can i say~~
