### ISSUE TITLE
[Bug]: 无法修改自定义API（API-KEY，模型等）

### ISSUE THREAD

**Issue by wang-zerui** [immersive-translate/immersive-translate#2368]
### 插件版本号 | Version

1.11.7

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

无法修改自定义API（API-KEY 模型），如图字段均无法修改，但是功能可以正常使用。
![image](https://github.com/user-attachments/assets/8dd8630f-810d-4cdc-af52-eb782a44bbc7)

**Comment by keyboard3** [comment]
切换AI专家到通用就可以修改了，1.12.3+ 已修复
