### ISSUE TITLE
[Bug]: 翻译本地网页显示“等待注入页面中...”

### ISSUE THREAD

**Issue by OpenNETList** [immersive-translate/immersive-translate#2370]
### 插件版本号 | Version

1.11.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

使用edge打开本地HTML，插件总是提示“等待注入页面中...若长时间未响应，请尝试刷新页面”，即使网页已加载完成。我尝试下载一个可以正常翻译的网页，在本地打开时，仍然提示“等待注入页面中...”。

### 出现问题的网址 | URL

本地网页

### 重现步骤 | To Reproduce

1.使用edge打开本地HTML
2.打开沉浸式翻译插件扩展

**Comment by keyboard3** [comment]
本地文件需要给插件授权访问本地文件权限，你授权了吗，没有的话，可以百度下如何给插件授权访问本地文件

**Comment by OpenNETList** [comment]
谢谢，授权访问本地文件后可以正常翻译了。
