### ISSUE TITLE
[Bug]: 翻译PDF下载，矢量的源页面变成像素化的了，附解决方式

### ISSUE THREAD

**Issue by HaujetZhao** [immersive-translate/immersive-translate#2372]
### 插件版本号 | Version

0.5.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

原本的 PDF 论文是矢量的：

![image](https://github.com/user-attachments/assets/acc307e6-cc88-45ee-918f-584011d1b342)

用沉浸式翻译打开，翻译后，下载：

![image](https://github.com/user-attachments/assets/f3707f79-a33f-4e04-b418-d0945e24b5b9)

在保存页面，会发现原来的页面被栅格化，变成图像了，不是原来的矢量化的了，放大看下：

![image](https://github.com/user-attachments/assets/e3e63889-32bc-4483-86bd-1543497fa2a3)

这导致里面的引用和链接，都点击不了。

理想的双语版本，是将译文隔页插入源文件，而不需要把源文件给改坏。

--- 

通过查看历史 issue，你们应该已经知道这个问题，但是暂无解决办法。目前已知导出的原文，会被栅格化，但译文是矢量化的，出问题的目骤，应该是生成新 pdf 的这个部分。

为了解决问题，我只把生成的译文下载了下来，检查后发现，新的译文 PDF，页面宽度竟是 32.38cm，而不是原文的 20.58cm，因此，为了保留原文档的矢量化、标签和索引等元数据，合并译文需要两步：

1. 将译文PDF页面缩放至统一大小
2. 将译文按页交替插入到原文档

然后我用 Python 写了一个脚本，调用 pymupdf 的库，实现了上述两步：

```python
"""
脚本作用：将第二个 PDF 文件交替插入第一个 PDF 文档，并确保大小一致，另存为 merged.pdf

安装依赖的命令：pip install pymupdf

"""

import fitz  # PyMuPDF
import sys
import os
from pathlib import Path
import shlex



def insert_pages_alternately(pdf1_path, pdf2_path, output_path):
    # 打开第一个 PDF 文件
    pdf1 = fitz.open(pdf1_path)

    # 打开第二个 PDF 文件
    pdf2 = fitz.open(pdf2_path)

    # 遍历第二个 PDF 文件的每一页
    for i in range(pdf2.page_count):

        # 获取第一个 PDF 对应页面的宽高
        page_num = min(2*i, pdf1.page_count-1)
        print(f'{pdf1.page_count=}, {2*i=}')
        page = pdf1[page_num]
        width, height = page.rect.width, page.rect.height

        # 插入新页面，缩放显示第二个 PDF 文件对应的页面
        new_page = pdf1.new_page(page_num + 1, width=width, height=height)
        new_page.show_pdf_page(new_page.rect, pdf2, i)
        
    # 保存合并后的 PDF 文件
    pdf1.save(output_path)

    # 关闭原始 PDF 文件
    pdf1.close()
    pdf2.close()


def check_file(file_path):
    if not os.path.isfile(file_path):
        print("文件不存在：", file_path)
        sys.exit(1)


# 获取 pdf 文件参数，如果没有提供，则提示输入文件路径
if len(sys.argv) >= 3:
    paths = sys.argv[1:]
    paths = [os.path.realpath(x) for x in paths]
else:
    paths = shlex.split(input("请拖入两个要合并的 PDF 文件："))

pdf1_path, pdf2_path = paths[0], paths[1]

check_file(pdf1_path)
check_file(pdf2_path)

output_path = Path(pdf1_path).with_stem('merged')  # 输出文件路径

insert_pages_alternately(pdf1_path, pdf2_path, output_path)


```

使用 MuPDF 进行无损合并后，体积上也保持了矢量原文的小巧，而沉浸式翻译的默认导出结果由于将原文栅格化导致体积大幅增长：

![image](https://github.com/user-attachments/assets/0bb86f57-7d7e-4f8a-8263-5aec80d6464e)

我将我的原文件、合并结果，与沉浸式翻译的默认导出结果，都放上来，技术人员可以用上述代码验证下。

[1.原文.pdf](https://github.com/user-attachments/files/18166321/1.pdf)
[2.译文.pdf](https://github.com/user-attachments/files/18166323/2.pdf)
[3.合并结果.pdf](https://github.com/user-attachments/files/18166326/3.pdf)
[4.沉浸式翻译导出合并版.pdf](https://github.com/user-attachments/files/18166328/4.pdf)

---

MuPDF 也提供了 JavaScript 的 API ：https://www.npmjs.com/package/mupdf  ，这可能是修复这个问题的方案之一。

**Comment by keyboard3** [comment]
感谢提供思路，我们后续会安排尝试

**Comment by chinarui-na** [comment]
现在pdf的分段思路是怎么样的？现在有的pdf如果没有明显的换行，就会被分到一段里面。
<img width="487" alt="image" src="https://github.com/user-attachments/assets/0f970de9-c13b-4509-bced-2c6c171f5eb1" />

**Comment by FattySpring** [comment]
【保存为图片版PDF】是将译文插入到原PDF中，不会修改内容，【打印机-另存为PDF】是调用的系统打印功能，会将所有内容重新生成新的PDF，如果您需要让原文保持原样，您可以使用 【保存为图片版PDF】 来导出
