### ISSUE TITLE
discord 网站翻译顺序改进

### ISSUE THREAD

**Issue by talking-toaster** [immersive-translate/immersive-translate#2375]
### 您希望的更新和改进是什么 | Update or Improve

当前，大部分网页是从上往下浏览的，所以翻译的顺序是优先翻译上方的文字，然后翻译下方的文字。
而在discord网站中，每个讨论区打开都是默认在最下方的最新消息处，上方还缓存了1-2屏的历史消息，此时默认的策略导致优先翻译了不可见的内容，当前屏幕内的可见内容在延迟一段时间后才翻译。

**Comment by keyboard3** [comment]
在 https://dash.immersivetranslate.com/#advanced 这里预翻译字数为0试试
