### ISSUE TITLE
[Bug]: google学术glossaries翻译错乱

### ISSUE THREAD

**Issue by ysdj** [immersive-translate/immersive-translate#2376]
### 插件版本号 | Version

1.12.4

### 请描述这个Bug | Describe the bug

当设置glossaries：
` "glossaries": [
      {
        "k": "Trastuzumab deruxtecan",
        "v": "德曲妥珠单抗"
      }
    ]`
无法将"Trastuzumab deruxtecan"翻译为完整的"德曲妥珠单抗"，如图：
![image](https://github.com/user-attachments/assets/01aa99ff-3d5a-426f-9462-fb804e110d46)

### 出现问题的网址 | URL

https://scholar.google.com/scholar?hl=zh-CN&num=20&as_sdt=0%2C5&as_vis=1&q=deruxtecan&btnG=

**Comment by keyboard3** [comment]
你的术语不能是中间高亮的。因为高亮的单词是包含富文本的，类似翻译时上面的内容是这样的 Trastuzumab <a>deruxtecan</a>  所以无法匹配它。你可以这样搜 https://scholar.google.com/scholar?hl=zh-CN&num=20&as_sdt=0%2C5&as_vis=1&q=Trastuzumab+deruxtecan&btnG=

![image](https://github.com/user-attachments/assets/582cd8d4-d0ae-42be-a55f-73b3429f9ae0)

**Comment by keyboard3** [comment]
![image](https://github.com/user-attachments/assets/b4fc7b82-582b-4cf8-81b8-db554605dcd5)
因为摘要部分它不是一个整体。目前没啥办法
