### ISSUE TITLE
[Bug]: 自定义user rule后部分区域无法翻译

### ISSUE THREAD

**Issue by ysdj** [immersive-translate/immersive-translate#2377]
### 插件版本号 | Version

1.12.4

### 请描述这个Bug | Describe the bug

自定义前，标题翻译正常：
![image](https://github.com/user-attachments/assets/ff644086-c69c-4eca-a2fb-c736283fcfce)

当自定义user rule后（即使不加具体设置项）：
`[
  {
    "id": "cell",
    "matches": [
      "https://www.annalsofoncology.org/article/*"
    ],
    "urlChangeDelay": 5000
  }
]`

标题不再被翻译：
![image](https://github.com/user-attachments/assets/f1fced9b-23c5-4f87-9d1d-581a824904d0)

用的谷歌翻译

### 出现问题的网址 | URL

https://www.annalsofoncology.org/article/S0923-7534(21)00157-5/fulltext

**Comment by keyboard3** [comment]
用这个
```
[
  {
    "id": "cell",
    "matches": [
      "https://www.annalsofoncology.org/article/*"
    ],
    "preTranslateLimiter": {
      "header.enableTranslate": true
    },
    "urlChangeDelay": 5000
  }
]
