### ISSUE TITLE
[Bug]: 切换为翻译所有区域，某些网页上的内容无法仍然无法翻译

### ISSUE THREAD

**Issue by q1343135559** [immersive-translate/immersive-translate#2379]
### 插件版本号 | Version

1.12.4

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

你好，某些网站，在开启翻译所有区域，仍然无法翻译，网址：https://www.wildberries.ru/catalog/145549392/detail.aspx?targetUrl=EX

并且，当网页局部刷新时，页面并不会刷新翻译后的内容,复现录屏：邮件附件（例如在购物网站上，切换商品的不同规格）

### 出现问题的网址 | URL

https://www.wildberries.ru/catalog/145549392/detail.aspx?targetUrl=EX

### 重现步骤 | To Reproduce

https://github.com/user-attachments/assets/4e69dfd1-e7f7-4233-a49f-801b6102110a

**Comment by q1343135559** [comment]
![Uploading 微信图片_20241220170203.png…]()

**Comment by q1343135559** [comment]
![微信图片_20241220170203](https://github.com/user-attachments/assets/16fd18c9-034f-449a-992c-cb34d1617687)
未被翻译的区域

**Comment by keyboard3** [comment]
打开 https://www.wildberries.ru/catalog/145549392/detail.aspx?targetUrl=EX&imt_refresh_rule=1 再试下
