### ISSUE TITLE
[Bug]: YouTube的繁体中文字幕无法翻译成简体中文

### ISSUE THREAD

**Issue by PromiseNev** [immersive-translate/immersive-translate#2382]
### 插件版本号 | Version

1.12.4

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![微信图片_20241221135335_25](https://github.com/user-attachments/assets/806e4aa7-1cd3-46d4-a28e-ebc0288a6b62)

如图所示,繁体中文的字幕无法翻译成简体中文

### 出现问题的网址 | URL

https://www.youtube.com/watch?v=QJOkcgCHB98

**Comment by FattySpring** [comment]
该视频原字幕语言标记有问题，将繁体中文字幕标记为简体中文了。
解决方式：
1. 在 https://dash.immersivetranslate.com/#subtitle 中关闭【优先使用人工字幕】选项
2. 将原视频字幕选为英语（如下图所示）
![image](https://github.com/user-attachments/assets/e2fe18f5-35c5-4025-b221-6f0078ef9f7d)
