### ISSUE TITLE
关于在vk video（https://vkvideo.ru/）使用上的建议

### ISSUE THREAD

**Issue by 569972301** [immersive-translate/immersive-translate#2383]
### 您希望的更新和改进是什么 | Update or Improve

大佬，确实感谢沉浸翻译的推出，帮了很大的忙。同时就我使用的感受上，希望大佬帮忙改进。
vk video这个视频网站，因俄语学习的需要，会大量的使用（yourube在这上面的资源并不多）。但视频字幕却并能像youtube视频字幕一样适配的完美。。上次因插件在此网站不能使用，大佬也第一时间帮忙改进，在此感谢。同时希望大佬能帮忙，在技术上再改进下插件在vk video这个视频网站感受。。。多谢。这个网站比较小众，在此仅仅表达希望。。

**Comment by FattySpring** [comment]
很抱歉，不同平台的视频字幕实现方案不同，vkvideo 站点目前只能这样来适配。

**Comment by 569972301** [comment]
> 很抱歉，不同平台的视频字幕实现方案不同，vkvideo 站点目前只能这样来适配。

我明白的，只是表达自己迫切的心情，希望在大佬进一步的开发过程中，能一步步的实现。。。。。多谢
