### ISSUE TITLE
[Bug]: pubmed.ncbi.nlm.nih.gov的Title翻译不了

### ISSUE THREAD

**Issue by Sinandiao** [immersive-translate/immersive-translate#2384]
### 插件版本号 | Version

1.12.4

### 平台 | Platform

macOS

### 浏览器 | Browsers

Other

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

title翻译不了,位置是 \<h1 class="heading-title">

### 出现问题的网址 | URL

https://pubmed.ncbi.nlm.nih.gov/34241914/

**Comment by keyboard3** [comment]
![QQ_1734881768992](https://github.com/user-attachments/assets/f0df09e9-7614-452d-b8c0-1049e2d9f206)
我这macos 1.12.4 翻译正常。 你点击下悬浮球的反馈按钮反馈下看

**Comment by Sinandiao** [comment]
> ![QQ_1734881768992](https://private-user-images.githubusercontent.com/13177744/397995732-f0df09e9-7614-452d-b8c0-1049e2d9f206.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5MTk3MzIsIm5iZiI6MTczNDkxOTQzMiwicGF0aCI6Ii8xMzE3Nzc0NC8zOTc5OTU3MzItZjBkZjA5ZTktNzYxNC00NTJkLWI4YzAtMTA0OWUyZDlmMjA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDAyMDM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiNWQwNmZhNDIzOTg3OGRmYmRkZDBiNDhmODk4MmRhODk5NmFiZWNiODYwZWZmNGZjODQwNGFkOWNhY2ZjOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.c-E-UxewsIz29JgtGlUFnEGgQ0eujkoe9iFpkvVEa6c) 我这macos 1.12.4 翻译正常。 你点击下悬浮球的反馈按钮反馈下看

可以了 重装大法解决

**Comment by keyboard3** [comment]
已适配 https://pubmed.ncbi.nlm.nih.gov/34241914/?imt_refresh_rule=1 再试下
