### ISSUE TITLE
[Bug]: 阿里云翻译服务器挂了

### ISSUE THREAD

**Issue by allentown521** [immersive-translate/immersive-translate#2386]
### 插件版本号 | Version

1.12.4

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

https://[mt.aliyuncs.com](https://mt.aliyuncs.com/)/ 无法访问

**Comment by keyboard3** [comment]
这个是阿里云翻译服务器问题，非插件问题
