### ISSUE TITLE
[求助] 请告知我正确的插件版本

### ISSUE THREAD

**Issue by SMFDrummer** [immersive-translate/immersive-translate#2389]
### 您希望的更新和改进是什么 | Update or Improve

这是一个求助，我正在使用一台老电脑，并且使用最后支持Flash的Chrome版本87.0.4280.141，我迫切地想知道沉浸式翻译插件最后支持这个Chrome版本的插件版本是什么，请回复

### 补充说明 | Additional context

如果开发者已回复，请将issue置于discussions项

**Comment by keyboard3** [comment]
插件一直不支持这个浏览器版本，因为该浏览器太低不支持v3插件。 你可以试试是否能装油猴插件，通过油猴安装沉浸式翻译
