### ISSUE TITLE
输入框增强分隔符支持指定范围

### ISSUE THREAD

**Issue by Mishasama** [immersive-translate/immersive-translate#2393]
### 您希望的更新和改进是什么 | Update or Improve

举个例子：
当在输入框输入以下的内容
`Why /en 你们会做出 / so hard to use /en 的产品 / ？`
希望能按照用户的意图来仅翻译`//`框选范围内的内容，而不是仅从`/`开始就一直翻译到最后。

### 补充说明 | Additional context

当用户这样操作的时候，最好还能结合用户在输入框里的上下文内容来进行“正确”的翻译，而不是仅根据`//`中的内容来进行独立的翻译。
可能需要涉及到类似润色的二次翻译动作。（不过也许AI能直接理解这样多语言混用的句子吧？不知道传统的机器翻译行不行了。）

**Comment by keyboard3** [comment]
你在输入框中，选中你要翻译部分的文字，然后右键就可以看到翻译文本的选项。点击翻译就会替换到你要翻译的内容。设置快捷键触发输入增强也同样支持选中翻译部分

**Comment by Mishasama** [comment]
> 设置快捷键触发输入增强也同样支持选中翻译部分

输入增强的快捷键不是会用空格替换掉选中的内容，且不触发翻译吗？
我选中部分文本后使用快捷键只会出现上述情况，没有你说的效果。

**Comment by keyboard3** [comment]
<img width="452" alt="image" src="https://github.com/user-attachments/assets/4c1f8f3c-77d7-4376-938c-caf1d93ee36a" />
<img width="293" alt="image" src="https://github.com/user-attachments/assets/43870a30-f59c-4117-b24d-38e0a929a602" />
快捷键在这边配置 https://dash.immersivetranslate.com/#shortcuts
快捷键是一样的效果

**Comment by Mishasama** [comment]
> 快捷键在这边配置 https://dash.immersivetranslate.com/#shortcuts 快捷键是一样的效果

但是这样做就无法临时修改目标语言了
而且这样一次也就只能翻译其中一段的内容，不能一口气翻译所有特定的部分，也没有联系上下文的效果。

**Comment by keyboard3** [comment]
你这个需求或许直接交给chagpt对话就行了。输入框增强不适合处理复杂需求

**Comment by Mishasama** [comment]
> 输入框增强不适合处理复杂需求

那能不能增加对浏览器侧栏的支持？ 感觉对单一目标语言的话现在的机器已经能很好地理解意图了。
![image](https://github.com/user-attachments/assets/7f29b26e-fdae-457d-b0e5-59b3b847e050)
