### ISSUE TITLE
[Bug]: [Custom DeepL] 翻译服务或网络出现问题 456: {"message":"Quota Exceeded"}

### ISSUE THREAD

**Issue by Bruce199908** [immersive-translate/immersive-translate#2394]
### 插件版本号 | Version

V1.12.4

### 请描述这个Bug | Describe the bug

[Custom DeepL] 翻译服务或网络出现问题
456: {"message":"Quota Exceeded"}, 会员DeepL翻译不可用，请修复

### 出现问题的网址 | URL

https://app.immersivetranslate.com/text

### 补充说明 | Additional context

会员DEEPL翻译不可用

**Comment by keyboard3** [comment]
看标题 你当前试用的是自定义DeepL。 你需要去 https://dash.immersivetranslate.com/ 设置页切换使用会员deepl

**Comment by Bruce199908** [comment]
![iissue](https://github.com/user-attachments/assets/a8cd2da6-60ee-4a3a-96bd-27d366b46b69)
我一直是用的是会员Deepl而不是自定义，翻译还是这个问题

**Comment by keyboard3** [comment]
会员的报错不可能显示Custom Deepl错误。你肯定是没有选中会员的deepl，检查 https://dash.immersivetranslate.com/ 。记得修改完要刷新页面
![image](https://github.com/user-attachments/assets/c7507fb0-8f3f-4a3c-9323-e28fe05e6e6f)

**Comment by Bruce199908** [comment]
好的，多谢
