### ISSUE TITLE
能否使用流式输出提高AI翻译效率？

### ISSUE THREAD

**Issue by WangYiShion** [immersive-translate/immersive-translate#2396]
### 您希望的更新和改进是什么 | Update or Improve

我在使用DeepSeek翻译的时候，感觉长文本段落翻译输出缓慢，这是否和非流式输出有关？官方是这么说的：
“API 默认使用非流式输出（stream=false），即模型在所有内容输出完后，才会返回给用户。您可以通过开启 API 的 stream 模式来提升交互性。”
所以能否在调用API时，将 stream 设置为 true 使用流式输出来提高翻译效率呢？

**Comment by keyboard3** [comment]
流式输出不适合网站翻译，适合对话。流式输出会导致页面元素不断变动，元素排版会不断抖动
