### ISSUE TITLE
[Bug]: 基本设置中的Temperature的优先级问题。

### ISSUE THREAD

**Issue by despairTK** [immersive-translate/immersive-translate#2398]
### 插件版本号 | Version

1.12.4

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

我想问下基本设置中的Temperature参数优先级问题。
我目前使用LM Studio作为本地API使用，我在LM Studio设置的模型Temperature参数和插件基本设置中的Temperature哪个是最终生效的参数？或者说哪边的优先级更高？

**Comment by keyboard3** [comment]
跟插件无关，插件请求发送都是插件配置的temperature数值，至于最后生效就看翻译服务自己的策略了。
