### ISSUE TITLE
bing translate doesn't work...

### ISSUE THREAD

**Issue by ghost** [immersive-translate/immersive-translate#24]
<img width="200" alt="statuscode_205" src="https://user-images.githubusercontent.com/88955536/212910461-fee51f13-84a9-4b9e-995e-2464c9b208c0.png">

![text](https://user-images.githubusercontent.com/88955536/212910821-9a6aceec-1b8e-4112-afa4-9d72774e4f45.png)

I think it's the same reason as this issue.
https://github.com/chunibyocola/sc-translator-crx/issues/112#issuecomment-1381343479

**Comment by theowenyoung** [comment]
confirmed, thanks for your link, I have fixed it. not yet release.

**Comment by theowenyoung** [comment]
released at 0.2.1.
