### ISSUE TITLE
[Bug]: Follow.is 网站 1）英文新闻条目无法显式译文 2）详细新闻内容中有显示译文，但样式不正确

### ISSUE THREAD

**Issue by CavemanWork** [immersive-translate/immersive-translate#2400]
### 插件版本号 | Version

1.8.1

### 平台 | Platform

macOS

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

订阅英文的 RSS，在 feed 中可以看到两大类内容，左边是新闻条目、右边是对应新闻条目的详细内容。
现问题是查看英文的新闻的时候
1）英文新闻条目无法显式译文
2）详细新闻内容中有显示译文，但样式不正确

### 出现问题的网址 | URL

https://app.follow.is/feeds

### 重现步骤 | To Reproduce

1. https://app.follow.is/feeds 
2. 参考 RSS: ID: 42371779203556352  or  rsshub://reuters/world
<img width="1926" alt="11811735447540_ pic" src="https://github.com/user-attachments/assets/8c0838d6-cf29-467a-974d-85bf22a870d0" />
<img width="1106" alt="11831735447655_ pic_hd" src="https://github.com/user-attachments/assets/5dc16b3f-491f-4c66-8b6d-666db5fe6444" />

**Comment by keyboard3** [comment]
![image](https://github.com/user-attachments/assets/8fc1279d-c3d3-4fab-96da-dcd5b7f0ec2e)
打开再试下 https://app.follow.is/feeds/?imt_refresh_rule=1

因为正文部分该网站是采用shdowRoot技术，隔离了站点的样式
