### ISSUE TITLE
建议增加设置翻译上限的功能

### ISSUE THREAD

**Issue by o0oo0ooo0** [immersive-translate/immersive-translate#241]
您的immersive-translate太棒了，我用了几天就把彩云接口的100万额度用掉了。于是我转向了腾讯云机器翻译，腾讯云有500万的免费额度，但是它没有设置免费额度用光就停服的功能，也就是说我有可能用着用着就欠费了，所有我希望您可以让油猴脚本增加一个统计已翻译字数的功能（或者通过腾讯云的接口查看已翻译字数情况，这个更准确同时也更复杂，因为腾讯似乎没有给我们提供这个接口，用爬虫可能有法律风险，不建议），超出用户设定的上限就不再进行翻译，而是弹窗提示用户关闭上限或者更换接口，这样可以防止出现无感欠费的情况。谢谢您！

**Comment by theowenyoung** [comment]
统计本地已翻译的字数似乎更加通用。

**Comment by o0oo0ooo0** [comment]
> 

是的
