### ISSUE TITLE
翻译电子书时，失败的条目是否可以增加重试机制？

### ISSUE THREAD

**Issue by levie-vans** [immersive-translate/immersive-translate#242]
![image](https://user-images.githubusercontent.com/66657337/225198600-dcf8b6b3-f261-4a3d-8232-473dee6efe0c.png)
有一些条目怎么都翻译不了，有没有可能增加重试机制？甚至这些失败的条目能否手动更换一个引擎再重试？

**Comment by levie-vans** [comment]
在网页中，超时和重试机制是OK的，但是电子书中会有一直在转圈，或者重试点击无效的问题。

**Comment by iG8R** [comment]
Some web pages also have texts where translation "stumbles" occur.

**Comment by theowenyoung** [comment]
最新版的电子书制作已提供一键重试的按钮。

> 确实电子书里面的重试按钮目前是不工作的。目前的机制有点难搞
