### ISSUE TITLE
你好使用本地翻译pdf文件时，选中左半部分的原始内容会出现蓝色乱码的现象，是什么原因呢

### ISSUE THREAD

**Issue by yxyxnrh** [immersive-translate/immersive-translate#244]
![image](https://user-images.githubusercontent.com/82510221/225223176-d1b90f44-7779-42f1-96a1-fddad21ba7d4.png)

**Comment by theowenyoung** [comment]
似乎是bug，选中的遮罩似乎覆盖了原文

**Comment by theowenyoung** [comment]
0.5.5版本已解决
