### ISSUE TITLE
Why the openai api key can't work on Reuters news

### ISSUE THREAD

**Issue by zylearncode** [immersive-translate/immersive-translate#245]
Here is the link of news, will it be solve?

https://www.reuters.com/world/china/time-money-love-china-brainstorms-ways-boost-birth-rate-2023-03-15/

![image](https://user-images.githubusercontent.com/12198117/225299782-1afb2986-07f7-4e8e-8c89-793480b9bcd0.jpeg)

**Comment by theowenyoung** [comment]
it seems just slow, but it works, exampe:

<img width="1264" alt="Screenshot 2023-03-15 at 19 56 06" src="https://user-images.githubusercontent.com/62473795/225302056-ef542fe7-0454-4f33-8a92-5fc195b18dc6.png">

**Comment by zylearncode** [comment]
thanks for your tool and also for your reply. 

It seems is my config need add a new rule. It's solved now. 

Sincerely. Thanks again.
