### ISSUE TITLE
只显示译文

### ISSUE THREAD

**Issue by XiaoYingYo** [immersive-translate/immersive-translate#246]

**Comment by theowenyoung** [comment]
我之前想过一种办法：

伪代码：

```
.parentContainer {
   font-szie: 0;
   visible: hidden;
}
.parrentContainer .immersive-translate-target {
   font-size: original size;
   visible: visible
}
```

不确定可行性。

**Comment by theowenyoung** [comment]
https://github.com/immersive-translate/next-translator/blob/3396eb64925ceda254a5ea014ebdd2dc55b26d0a/interface.ts#L531

可以在这里新增一种mode: `translationOnly`

**Comment by baa-god** [comment]
> https://github.com/immersive-translate/next-translator/blob/3396eb64925ceda254a5ea014ebdd2dc55b26d0a/interface.ts#L531
> 
> 可以在这里新增一种mode: `translationOnly`

连接没了？现在怎么做？

**Comment by theowenyoung** [comment]
> > https://github.com/immersive-translate/next-translator/blob/3396eb64925ceda254a5ea014ebdd2dc55b26d0a/interface.ts#L531
> > 可以在这里新增一种mode: `translationOnly`
> 
> 连接没了？现在怎么做？

这个链接是私有项目的～ 现在还没实现这个特性

**Comment by landchenxuan** [comment]
+1，在读Feedly这样的列表RSS的时候没有空间同时显示原文和译文，只显示译文这个需求对我来说是刚需。

**Comment by versun** [comment]
0.5.7版本已添加该功能, 火狐浏览器已上架更新, 其他平台的还在审核
点击[更多] -> [切换为仅显示译文]
