### ISSUE TITLE
希望增加快捷键能唤醒翻译框进行输入翻译

### ISSUE THREAD

**Issue by jaychoubaby** [immersive-translate/immersive-translate#247]
工具很好用，但是有时候从其他地方复制的文字需要翻译，目前只能打开翻译网页，希望增加弹出小窗口进行输入翻译功能

**Comment by theowenyoung** [comment]
这个目前应该有不少替代插件可以实现这个功能～

**Comment by theowenyoung** [comment]
目前已支持所有网页的输入框翻译了。https://immersivetranslate.com/docs/input/
