### ISSUE TITLE
希望有两个Target语言

### ISSUE THREAD

**Issue by simoncao2022** [immersive-translate/immersive-translate#250]
首先这是非常棒的插件，没有之一。
我相信很多人像我一样用它当成语言学习，比如当我学习德语时，我除了希望它能翻译为英文，同时还想看到翻译为中文，这样我不用切换两次。谢谢

**Comment by theowenyoung** [comment]
这个可能会支持，但是我的疑虑是这会为普通用户使用带来一些歧义... 我可能要想想怎么规划一下设置页.

**Comment by theowenyoung** [comment]
暂时不考虑这个功能哈～
