### ISSUE TITLE
mail.126.com 报错

### ISSUE THREAD

**Issue by xufanghui** [immersive-translate/immersive-translate#253]
![126](https://user-images.githubusercontent.com/1429094/225791730-1d9e7620-edca-4380-a6d9-8571db15804c.png)

**Comment by theowenyoung** [comment]
额，这个报错应该不影响流程。

这个网页没有翻译吗？

**Comment by xufanghui** [comment]
目前来看，是翻译不了126里面的email

**Comment by theowenyoung** [comment]
可能只是这封邮件？我测试我这是可以翻译的，你也可以拉到页面最后面看看

**Comment by xufanghui** [comment]
好了，和默认设置有关系，我关闭comment
