### ISSUE TITLE
翻译下拉内容后相互重叠覆盖

### ISSUE THREAD

**Issue by ayrb13** [immersive-translate/immersive-translate#254]
![image](https://user-images.githubusercontent.com/3375743/225920845-453dcb81-d9d4-4837-a267-afdee018a8d0.png)
点击more后，下拉内容翻译后相互重叠覆盖
https://www.ncbi.nlm.nih.gov/clinvar/variation/1343763/?oq=c.9244a%3Eg[varname]+&m=NM_206933.4(USH2A):c.9244A%3EG%20(p.Ile3082Val)

**Comment by theowenyoung** [comment]
看了一下这个，有点难搞，因为原网页设置了固定的高度，导致译文无法撑开..

我尝试去掉原网页的高度设置，但还是不行，可能还有别的地方在控制.. 感觉这个网页可能不适合双语翻译..

**Comment by ayrb13** [comment]
辛苦，插件很喜欢，如果这个页面能支持的话，就更喜欢了^_^
