### ISSUE TITLE
发现两个网站无法完全现实翻译

### ISSUE THREAD

**Issue by suibianzai** [immersive-translate/immersive-translate#255]
https://www.hancom.com/hanfriends/friendsTyping.do
![image](https://user-images.githubusercontent.com/42022663/226075683-1828c223-1b76-4e93-8680-2d46e95fa163.png)
https://www.hancomtyping.com/
https://www.hancomtyping.com/en
![image](https://user-images.githubusercontent.com/42022663/226075733-d8ea90c6-4779-4033-98ca-d9a3149b0db8.png)
（第二个网站部分可能是由于特效，这个可以理解，但是也有没动画特性的部分无法显示翻译）

**Comment by theowenyoung** [comment]
默认情况下好像对于日韩文字的处理不太好，像这种没有翻译的是因为检测到字符数太少。

我刚发布了一个新版本，部分优化了非英语网站的字符数检测，可以更新下油猴脚本再试试～

**Comment by suibianzai** [comment]
> 默认情况下好像对于日韩文字的处理不太好，像这种没有翻译的是因为检测到字符数太少。
> 
> 我刚发布了一个新版本，部分优化了非英语网站的字符数检测，可以更新下油猴脚本再试试～

我提交issue只当是记录一下，没想到你们还能改进，真的辛苦了，现在的插件已经非常非常好用了！非常感谢更新！！
