### ISSUE TITLE
韩译中（简体中文）文章中会出现粤语

### ISSUE THREAD

**Issue by arisunqq** [immersive-translate/immersive-translate#258]
**长篇文章用PAPAGO翻译，韩语翻译简体中文，会出现如图的粤语翻译。**
![bug](https://user-images.githubusercontent.com/104204977/226243836-ac448db4-355e-4295-8eed-e67cdad6cbc4.jpg)

**这个问题在postype.com 这个网站上复现很多次。**

**在naver使用也有遇到过：**

![bug3](https://user-images.githubusercontent.com/104204977/226243889-37be6f36-2417-4f87-84b8-4e10d7b73417.jpg)

**Comment by theowenyoung** [comment]
这个应该属于papago的问题. 他们的接口有的时候好像会抽风..
