### ISSUE TITLE
英文维基百科，右侧目录无法翻译

### ISSUE THREAD

**Issue by FUCKgithubffff** [immersive-translate/immersive-translate#259]
![屏幕截图 2023-03-20 124718](https://user-images.githubusercontent.com/120788444/226249303-d7968dcf-ccbf-4891-932f-188e7181a6e7.png)

**Comment by theowenyoung** [comment]
你指的是左侧还是右侧？

可以在更多里选择翻译全部区域。默认情况下是只翻译主要区域。

**Comment by pingfangdeguang** [comment]
我实在是好奇作者是如何用代码对每一句进行翻译，并且完美的将翻译内容嵌入网页，并且机会适配了所有网页，实在是感觉吃惊。如果看到的话，可否分享一下思路，因为源码没有开源，我现在在使用的过程中还没有想到要给作者贡献一些怎么的代码让这款软件更加好用，因为实在是太好了。

**Comment by theowenyoung** [comment]
> 我实在是好奇作者是如何用代码对每一句进行翻译，并且完美的将翻译内容嵌入网页，并且机会适配了所有网页，实在是感觉吃惊。如果看到的话，可否分享一下思路，因为源码没有开源，我现在在使用的过程中还没有想到要给作者贡献一些怎么的代码让这款软件更加好用，因为实在是太好了。

主要思路就是 分析整个网页的 tag，tag要么是 block的，要么是inline的，如果是block的，就直接作为一个完整的段落，如果是inline 的，就组成一个 inline group直到下个block tag出现～
