### ISSUE TITLE
可以增加 直接导入txt 和只显示译文吗？ 

### ISSUE THREAD

**Issue by lhj5426** [immersive-translate/immersive-translate#260]
https://user-images.githubusercontent.com/30548000/226273263-2b9a1865-7da4-472b-b21b-d6a19e9f83ed.mp4

现在是用这种变相的方式 。。来翻译TXT 
虽然可以翻译 但是还保留了译文。。。。
所以可以在这里增加直接txt选项吗
![image](https://user-images.githubusercontent.com/30548000/226273426-90714e54-f930-4408-957e-c06976fd3e94.png)
然后还有只保留译文不要双语对照

**Comment by theowenyoung** [comment]
有计划支持～ 包括markdown文件，目前的话，你可以 在扩展的管理页面，允许扩展访问本地文件，然后直接在浏览器打开txt文件就能翻译了。

**Comment by versun** [comment]
0.5.7版本已添加该功能, 火狐浏览器已上架更新, 其他平台的还在审核
点击[更多] -> [切换为仅显示译文]
