### ISSUE TITLE
Chatgpt 翻译 润色

### ISSUE THREAD

**Issue by yhy0** [immersive-translate/immersive-translate#261]
chatgpt 翻译能否加个润色功能 
https://github.com/yetone/bob-plugin-openai-translator
这是gpt原始翻译
<img width="873" alt="image" src="https://user-images.githubusercontent.com/31311038/226275940-28a05638-2a90-40ab-b949-ec10e1762308.png">
bob-plugin-openai-translator 插件润色
这种才润色后语感明显好多了
<img width="394" alt="image" src="https://user-images.githubusercontent.com/31311038/226276088-53df6234-7f84-4fb1-9d7b-7536a5fd4482.png">

**Comment by yhy0** [comment]
使用 gpt 翻译的时候加个 Prompt 
<img width="699" alt="image" src="https://user-images.githubusercontent.com/31311038/226277320-042609ec-a3d8-418f-aec0-11da2224aeb3.png">

类似这种

https://github.com/yetone/bob-plugin-openai-translator/blob/main/src/main.js#L39

**Comment by theowenyoung** [comment]
你指的是修改这里的自定义 Prompt吗？

也许可以你可以本地试试效果？

<img width="884" alt="Screenshot 2023-03-20 at 15 49 12" src="https://user-images.githubusercontent.com/62473795/226277728-48d73937-240f-4f19-9cab-bfe54363f008.png">

**Comment by yhy0** [comment]
属实眼瞎， 没发现这个功能，设置好了
