### ISSUE TITLE
本地html文件翻译问题

### ISSUE THREAD

**Issue by 1164origami** [immersive-translate/immersive-translate#263]
在尝试打开某些软件的指南类文件(.html)时，无法正常翻译。
(Design-Expert%2012/help/tutorials/general-multilevel-categoric-one-factor.html)

在尝试使用插件自带的browser. translatelocalHtmlfile从路径打开.html时，html显示不完整。

请问有什么解决方法吗？

**Comment by theowenyoung** [comment]
可以用 chrome浏览器，在扩展管理页面，允许访问本地地址，然后应该就可以翻译了吧

**Comment by 1164origami** [comment]
问题解决了，十分感谢。
