### ISSUE TITLE
quora翻译相关

### ISSUE THREAD

**Issue by pilileishen** [immersive-translate/immersive-translate#264]
以前都是每个段落翻译，现在变成了整篇文章翻译放在最后，没有以前友好了。退回2.7.9版本了

**Comment by pilileishen** [comment]
> 可以提供一个网址吗，我看看.

https://www.quora.com/What-would-it-have-been-like-to-be-a-medieval-king

**Comment by theowenyoung** [comment]
可以了，更新了一下规则～

点击一下浏览器图标更新下规则～

**Comment by pilileishen** [comment]
> 可以了，更新了一下规则～
> 
> 点击一下浏览器图标更新下规则～

你好，更新规则后确实解决了一些帖子的翻译问题，但是quora首页多刷新几次，还是会遇到之前的问题。我又退回0.2.85版本，这个版本没有类似问题。

**Comment by theowenyoung** [comment]
当前最新版本我测试是ok了哈～
