### ISSUE TITLE
[Bug] Found out why OpenAI freezes when translating

### ISSUE THREAD

**Issue by iG8R** [immersive-translate/immersive-translate#268]
Hi.
Firstly, I found out that the following prompt "Please provide translation {{to}} for these sentences: {{text}}" gives a more accurate result than the default.
Secondly, and the main topic - often on different pages, OpenAI freezes during translation with a constantly rotating icon next to the original text, even after multiple page reloads. The essence of this issue is that OpenAI sometimes sends a response that Immersive Translate cannot parse.
Could you, please, fix this?
https://www.kdxs.net/chapter/6040/7721412

![ImmTran-888-Req-BadResp-2023-03-21_193624](https://user-images.githubusercontent.com/11407417/226700274-b1bbe6c1-99ce-45c8-8067-72758717098e.jpg)
![ImmTran-888-Resp-BadResp-2023-03-21_193650](https://user-images.githubusercontent.com/11407417/226700267-437eaf6d-6caa-464c-b968-184182c1005d.jpg)

![ImmTran-888-Req-GoodResp-2023-03-21_193731](https://user-images.githubusercontent.com/11407417/226700266-278079cd-6c39-41d5-bbaa-19258fc8fa03.jpg)
![ImmTran-888-Resp-GoodResp-2023-03-21_193737](https://user-images.githubusercontent.com/11407417/226700259-aad4b5bd-ede2-4edf-afa7-45422defb15d.jpg)

**Comment by theowenyoung** [comment]
yes , it seems that openai do not treat the placeholder ### as a placeholder.

I think we should find a more efficient prompt to demand openai respect the placeholder.

**Comment by iG8R** [comment]
But there are 3 placeholders in the request and 4 in the response - doesn't that make parsing more difficult?

**Comment by theowenyoung** [comment]
this is a goog example that openAI does not respect the source text placeholder.

yes, this makes parsing more difficult. so we must find a better method to ask openAI to respect the placeholder.

**Comment by iG8R** [comment]
In the original text there are 4 sentences, but ImmersiveTranslate somehow divide them to only 3.

![image](https://user-images.githubusercontent.com/11407417/226932529-9fa52ccf-b477-4ba6-9403-a4c55eae3c6e.png)

**Comment by iG8R** [comment]
Here are examples of "good" placeholders

![image](https://user-images.githubusercontent.com/11407417/226933894-3193b7cd-e38a-4998-bda5-4761b3dba929.png)
![image](https://user-images.githubusercontent.com/11407417/226933931-49a9a0fc-2bcb-4893-87cf-f80e826033eb.png)

**Comment by theowenyoung** [comment]
The default setting works for me:

<img width="1576" alt="Screenshot 2023-03-22 at 22 31 14" src="https://user-images.githubusercontent.com/62473795/226936879-0aff3c4e-92a2-4105-9bf7-9204dfc8a198.png">

**Comment by iG8R** [comment]
> The default setting works for me:

Yes, the default placeholders works, but not in all cases.
Try this page https://www.kdxs.net/chapter/6040/7721874

**Comment by theowenyoung** [comment]
> Is it possible to add options in the settings to manually adjust placeholders between sentences and how they would be parsed?

yes, you can set it on developer settings, like:

```json
"translationServices": {
    "openai": {
      "placeholderDelimiters": [
        "{{",
        "}}"
      ],
      "immediateTranslationTextCount": 10000,
      "translationDebounce": 300,
      "newlinePlaceholderDelimiters": [
        "\n\n###",
        "###\n\n",
        "\n?\n?###\\d+###\n?\n?"
      ]
    }
}
```

**Comment by iG8R** [comment]
> yes, you can set it on developer settings, like:

I saw these setting, but sorry for the dumb question - how can i change them since they can't be edited?

![image](https://user-images.githubusercontent.com/11407417/226938784-19bf4aa4-c8cc-498f-bff3-432e6c6b28ab.png)

**Comment by iG8R** [comment]
And also the question still haunts me about the division of 4 sentences into 3 when parsing the page.

**Comment by theowenyoung** [comment]
it's ok! cause this is an advanced settings only for developers,  try change it here:

<img width="1195" alt="Screenshot 2023-03-22 at 22 41 34" src="https://user-images.githubusercontent.com/62473795/226940335-12403466-41af-4e2f-8d79-92b7c3d62bf7.png">

**Comment by theowenyoung** [comment]
> 



> In the original text there are 4 sentences, but ImmersiveTranslate somehow divide them to only 3.
> 
> ![image](https://user-images.githubusercontent.com/11407417/226932529-9fa52ccf-b477-4ba6-9403-a4c55eae3c6e.png)

this is expected, 4 sentences, 3 delimiters.

we expected openai response 3 delimiters too.

**Comment by theowenyoung** [comment]
Change prompts to 

    If the text contains ###, don't change it, do not explain, translate the following text to {{to}}: ```\n{{text}}\n```

This is the default config for openAI now:

```
    "openai": {
      "placeholderDelimiters": ["{{", "}}"],
      "immediateTranslationTextCount": 10000,
      "translationDebounce": 300,
      "maxTextGroupLengthPerRequest": 25,
      "prompt": "If the text contains ###, don't change it, do not explain, translate the following text to {{to}}: ```\n{{text}}\n```",
      "newlinePlaceholderDelimiters": [
        "\n\n###",
        "###\n\n",
        "\n?\n?###\\d+###\n?\n?"
      ]
    }
```

**Comment by theowenyoung** [comment]
it seems that you can test it now, click the browser addon icon , update the latest rules, try it !

**Comment by theowenyoung** [comment]
you are welcome! by the way, are you seriously using openAI as the translation engine? don't you think it's too slow for a real-time web page translator?

**Comment by iG8R** [comment]
Yes, it is slow compared to other translation services, BUT this is incredibly compensated by the great quality of the translation.
In comparison to other services, it is head and shoulders above in the translation quality, at least from Chinese into English.

**Comment by theowenyoung** [comment]
yes, I agree with that. but I just can not endure its speed, I hope they can release a direct translate API, which may change things.

 Now I'm using deepl as an alternative considered both speed and quality.

**Comment by iG8R** [comment]
Could you please explain what the following line means: `"maxTextGroupLengthPerRequest": 25,` ?

**Comment by theowenyoung** [comment]
this means there are max 25 paragraphs sent to openAI per request.

the previous value is `100`, and It seems that openai can not handle too many paragraphs.

for example https://www.kdxs.net/chapter/6040/7721874

the previous settings will merge 42 paragraphs per request, and openai will mess it up. 

so I try to reduce the paragraph count, 25 seems a good default value.

**Comment by iG8R** [comment]
Oh, exactly! Thank you!
