### ISSUE TITLE
BUG提交 此网站启用扩展即显示不正常 禁用就恢复正常

### ISSUE THREAD

**Issue by 1208041822** [immersive-translate/immersive-translate#269]
网站：https://arad.hange.jp/

![2023 03 22 20 36 40](https://user-images.githubusercontent.com/28993260/226906839-b72dc1cc-b64b-4ed0-b50a-78404341da92.png)
![2023 03 22 20 36 54](https://user-images.githubusercontent.com/28993260/226906864-55ab5c0e-e432-4be2-8e3b-447dc716c1af.png)

**Comment by theowenyoung** [comment]
确实，看了一下，似乎是不兼容。

插件会在这个网站的不同iframe之间互相发送消息，但是似乎这个网站对这个情况兼容的不是很好。

我看看有没有兼容的办法.

**Comment by 1208041822** [comment]
> 确实，看了一下，似乎是不兼容。
> 
> 插件会在这个网站的不同iframe之间互相发送消息，但是似乎这个网站对这个情况兼容的不是很好。
> 
> 我看看有没有兼容的办法.

好的 辛苦您了
