### ISSUE TITLE
希望能优先翻译视频 字幕/弹幕

### ISSUE THREAD

**Issue by millionart** [immersive-translate/immersive-translate#270]
比如在 udemy 和 youtube 上看一些教程的时候，如果使用了openai，似乎只会在字幕出现后进行翻译操作，很有可能刚翻译好就进入下一条字幕了，如果能在一开始就把所有字幕都翻译完全就好了。

**Comment by millionart** [comment]
目前确实是在用其他插件这么做，不过对比了openai的翻译效果要更好。

**Comment by theowenyoung** [comment]
也许这个issue提给YouTube双语字幕的插件，请求他们支援一下openai翻译可能会更快点...

因为这个插件要推出这个功能应该需要做不少工作.

**Comment by millionart** [comment]
没关系，本身也不是什么紧急的功能，只是希望这个插件越来越好
youtube 双字幕似乎也不支持其他网站
谢谢开发这么好的插件

**Comment by asasas234** [comment]
@millionart 老铁，我教你个办法，你可以用readwise上传youtube的URL，他会载入youtube的同时，下面出现整段字幕
<img width="977" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/4795442/5cacafd9-db92-45e7-bf25-a770c83518c1">
例如上面图的样子，然后你用翻译插件对这个进行翻译，在写点代码粘贴到chrome 控制台或者油猴脚本上，读取翻译的内容，用TTS的API进行语音播放就可以了~

**Comment by theowenyoung** [comment]
最新版本已支持 Youtube 的双语字幕，欢迎体验～ 

<img width="303" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/1ed9dd07-ad78-44d3-8fc9-53a275074394">


你可以在视频字幕设置中手动启用用沉浸式翻译来翻译字幕：

<img width="907" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/6655afa1-9897-4ed6-9568-0d31f220960c">
