### ISSUE TITLE
AP NEWS偶现Open AI翻译引擎下翻译带有注释

### ISSUE THREAD

**Issue by QiongBan** [immersive-translate/immersive-translate#271]
https://apnews.com/article/tiktok-ceo-shou-zi-chew-security-risk-cc36f36801d84fc0652112fa461ef140
使用Open AI翻译时存在以下错误：

HOW HAS TIKTOK ALREADY BEEN RESTRICTED?
如果文本包含###，请不要更改它，不要解释，将以下文本翻译为zh-Hans：

![4521679516307_ pic](https://user-images.githubusercontent.com/50990433/227028911-2a1b5780-a017-4c17-a37f-bdf08839e3f3.jpg)

**Comment by theowenyoung** [comment]
感谢反馈，再试试？ 我更新了规则。

**Comment by theowenyoung** [comment]
如果是扩展的话，扩展的设置页面 -> 关于 里面可以清除缓存
