### ISSUE TITLE
YouTube上无法进行翻译，插件的小图标不出现

### ISSUE THREAD

**Issue by groxtao** [immersive-translate/immersive-translate#272]
YouTube上无法进行翻译，插件的小图标不出现

**Comment by theowenyoung** [comment]
你是什么浏览器，用的是什么油猴插件呢？ 换 userscripts 是可以的

groxtao ***@***.***>于2023年3月23日 周四10:49写道：

**Comment by groxtao** [comment]
chrome浏览器， Tampermonkey BETA 4.19.6180 版本， 不过我使用了您那边的chrom扩展程序版的 翻译插件， 这个可以

**Comment by bowencool** [comment]
我也是这种情况，没有小图标，完全没反应，菜单都没出来：
<img width="270" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/20217146/747ec7cd-daf3-43aa-b4cd-2f8691cfafd9">

<img width="388" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/20217146/ce5607c3-7073-4dc7-845f-3afcefdbdcfb">
<img width="537" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/20217146/d5004516-e67a-4e39-ad4b-fde906857f0f">

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

**Comment by keyboard3** [comment]
暂时关闭此issue，如果还有问题可以重开
