### ISSUE TITLE
如何实现在其他插件更新网页时不重复翻译

### ISSUE THREAD

**Issue by JinghuaMu** [immersive-translate/immersive-translate#276]
平时会使用一些例如Hypothesis这种网页高亮工具，但在开启翻译后高亮处与其前后会被分成三段并且再次被重新翻译。在Element Inspect里可以看到文本片段被打上了新的tag，请问这个是否可以通过开发者选项屏蔽掉，我对这方面一窍不通，尝试了也没有成功。

**Comment by sandyplus** [comment]
我也遇到了同样的问题，在读英文页面的时候，将翻译的文字转成语音，就会再次翻译，有没有手动关闭“继续翻译”的开关？

**Comment by theowenyoung** [comment]
抱歉，很晚才回复，最新版我刚刚测试应该已经修复了该问题，暂时关闭这个issue了哈。有问题再重新open就好～
