### ISSUE TITLE
应该限制油猴脚本悬浮图标的可拖动范围，不让它能被拖到网页之外

### ISSUE THREAD

**Issue by QiTianzu** [immersive-translate/immersive-translate#278]
悬浮图标被拖到网页之外以后，刷新或关闭之后再打开图标被拖出的网页都没用，要打开其它域名的网站才能重新显示出来。

**Comment by theowenyoung** [comment]
怎么样才会被拖在网页之外呢？

**Comment by QiTianzu** [comment]
> 怎么样才会被拖在网页之外呢？

就是用鼠标点住图标往屏幕以外的区域拖动，只有往左边拖才不能拖出屏幕，往上下右都可以拖到看不见的地方。

**Comment by theowenyoung** [comment]
我试了一下，拖到上面或者右边外侧区域，它会自动回到边缘的地方呀.

**Comment by QiTianzu** [comment]
> 我试了一下，拖到上面或者右边外侧区域，它会自动回到边缘的地方呀.

是不能往右上角和右下角拖。

**Comment by theowenyoung** [comment]
我的意思是所有方向随便拖，放开之后，都会回到屏幕内，我不太知道你的操作是什么，如果方便的话，录个屏好一点～

**Comment by QiTianzu** [comment]
> 我的意思是所有方向随便拖，放开之后，都会回到屏幕内，我不太知道你的操作是什么，如果方便的话，录个屏好一点～

https://user-images.githubusercontent.com/50047003/228205855-80b9235c-32aa-451d-9ada-7bdf138c7a89.mp4

**Comment by theowenyoung** [comment]
感谢录制这个详细的视频，这可能是一个 windows only 的问题，我在mac上似乎不能复现，（等我的windows到了我再研究一下！

**Comment by theowenyoung** [comment]
已修复。
