### ISSUE TITLE
Annas archive 页面主要内容无法被翻译

### ISSUE THREAD

**Issue by Andy-AO** [immersive-translate/immersive-translate#28]
![image](https://user-images.githubusercontent.com/38101170/213090067-30e618a1-037e-4d83-891c-7ceb5b02bef5.png)

无法翻译，按下「翻译页面全部区域」也没反应
#  links
[Neuropharmacology - Search - Anna’s Archive --- 神经药理学 - 搜索 - 安娜的档案](https://annas-archive.org/search?q=Neuropharmacology)

**Comment by theowenyoung** [comment]
我这似乎是前几项可以翻译，后几项不行，似乎他们用了特殊的技术先隐藏，后展示，导致扩展没检测到这些元素，我要晚点调查下是用了什么技术隐藏，刚简单看了下没看出来。

**Comment by theowenyoung** [comment]
已发布

**Comment by theowenyoung** [comment]
感谢 @bxb100 的快速修复～

**Comment by Andy-AO** [comment]
经测试发现问题已经成功解决
