### ISSUE TITLE
开启插件导致网页导航栏消失

### ISSUE THREAD

**Issue by zhang07yi** [immersive-translate/immersive-translate#280]
使用Edge 最新的 dev 版本浏览器插件，翻译结束后网页会整体上移，导致原网页的导航栏消失

**Comment by theowenyoung** [comment]
请问有网址吗？

**Comment by zhang07yi** [comment]
> 

可以参考亚马逊云服务器界面，开启插件进入网站，翻译结束后，界面上方的导航栏就会有一半被遮盖https://signin.aws.amazon.com/signin?redirect_uri=https%3A%2F%2Fap-northeast-1.console.aws.amazon.com%2Fconsole%2Fhome%3FhashArgs%3D%2523%26isauthcode%3Dtrue%26region%3Dap-northeast-1%26state%3DhashArgsFromTB_ap-northeast-1_446d91a1a4d198aa&client_id=arn%3Aaws%3Asignin%3A%3A%3Aconsole%2Fcanvas&forceMobileApp=0&code_challenge=1Edqq-qYDaOfS9V4_OhDfxwVwFglD-HNJvRk9l4kHVM&code_challenge_method=SHA-256

**Comment by theowenyoung** [comment]
我这翻译后是这样，好像没有折叠呀

<img width="1538" alt="Screenshot 2023-03-27 at 19 43 05" src="https://user-images.githubusercontent.com/62473795/227931884-5d0aa645-14ae-4c86-87da-09069358db8e.png">
