### ISSUE TITLE
希望可以手动纠正页面中个别单词的翻译

### ISSUE THREAD

**Issue by Faputa** [immersive-translate/immersive-translate#282]
如题，希望插件支持纠正页面中个别单词的翻译，并且可以作为对当前路径或者是当前网站的配置保存起来

**Comment by theowenyoung** [comment]
保存起来作为一个自定义术语，然后应用在以后的翻译中吗？

**Comment by Faputa** [comment]
![image](https://user-images.githubusercontent.com/14192199/227785018-25b983f4-3bb7-43fb-bfd4-bfa710508a4d.png)
是的，比如[这篇文章](https://leanprover.github.io/theorem_proving_in_lean4/tactics.html)中，lean不应该翻译，[Tactic](https://leanprover.github.io/theorem_proving_in_lean4/tactics.html#entering-tactic-mode)应该翻译为策略，我希望有地方能够纠正这些翻译，然后保存起来并应用到整个网站（或者特定的路径，可以考虑支持用正则表达式设置这些路径）。

PS：插件很好用，谢谢大佬的工作

**Comment by theowenyoung** [comment]
嗯，这是一个很好的优化点，我之前是有计划做 用户级别的 个人术语库， 但是像你这个场景，似乎和网站关联起来也是一个不错的选项. 要想想怎么做到简单易用不过度复杂..


不过双语翻译的一个好处其实就是能看到原文，所以即使译文有瑕疵，就暂时忽略一下也还能接受.

**Comment by Faputa** [comment]
感觉可以选中单词→右键→设置术语→弹框这样子，或者点击图标→设置术语→弹框，弹框里面可选四种作用域分别为当前网页、当前网站、全局、自定义，选择自定义的时候可以自己设置匹配规则，可以记忆用户上一次选择的作用域（不是匹配规则）。

——一点个人的建议哈，期待大佬的更新

**Comment by theowenyoung** [comment]
嗯，原理上应该就这样。


我感觉大家一起建立一个公共的术语库，似乎也是一个不错的选择？毕竟大多数用户其实更想用现成的术语库，而不是自己建立，当然也允许自定义自己的术语库.

**Comment by Faputa** [comment]
感觉可以单独弄个术语的repo，每个人可以把自己的整理的术语PR到这个repo里面，然后插件可以请求这个repo里面的文件内容，然会用户可以手动勾选保存自己需要的术语。

**Comment by theowenyoung** [comment]
直接个人术语会自动覆盖 公共的就可以了吧？ 我相信公共的术语库质量应该是可以保证的？

**Comment by Faputa** [comment]
我觉得这是一个优先级的问题。对于某个冲突的术语，个人配置的优先级大于公共配置，然后特定网页的配置大于自定义大于网站大于全局的配置，对于公共配置后添加的大于新添加的，大概应该是这个样子

**Comment by pingfangdeguang** [comment]
应该插件只是帮我们调了接口，并没有存到后台，因为免费的，国内的api都没有谷歌翻译的好，如果可以有记忆，修改以后，下次再翻的时候会纠正过来就好了，不知道这个有没有实现的思路，或者是把纠正的存到本地浏览器里面，翻译的时候可以进行优先级的判断。不知道怎么样实现比较好。感觉大家提的issue都特别的好

**Comment by versun** [comment]
move to discussion https://github.com/immersive-translate/immersive-translate/discussions/385
i will close this issue now

**Comment by ictsmc** [comment]
这个问题很久了.一直没有实现自定义术语表这个功能吗?目前没有在插件中看见

**Comment by theowenyoung** [comment]
试下这个替代项：

![CleanShot 2024-04-01 at 13 02 16@2x](https://github.com/immersive-translate/immersive-translate/assets/62473795/62aff125-a21d-4432-831d-dddeb20e5fe9)
