### ISSUE TITLE
Some issues with excludeSelectors in Edit User Rules (Developer settings)

### ISSUE THREAD

**Issue by iG8R** [immersive-translate/immersive-translate#284]
Hi.
I ran into an issue where Immersive Translator's selector exclusion rule doesn't work.
URL in the following example: https://www.kdxs.net/chapter/6040/7722028

I use the script "Google select text translator" https://greasyfork.org/en/scripts/36842-google-select-text-translator in conjunction with Immersive Translator.
![image](https://user-images.githubusercontent.com/11407417/227957351-99871d13-9d47-44ba-a5d6-79ec7c0ff43e.png)

When the "Always translate \<site name\>" option is ON and at the same time I'm using "Google select text translator", sometimes the contents of the "Google select text translator" window are also translated with Immersive Translator despite all the languages that present in the "Google select text translator" window are marked as "Never Translated Languages" in the Immersive Translator's settings.

![image](https://user-images.githubusercontent.com/11407417/227957176-a52436fc-485e-4b26-8c4e-8297db0d9e7d.png)

I tried to exclude all "Google select text translator"'s 'li' tags except the first one from the Immersive Translator's processing with the following user rule but to no avail:
```
    "matches": "*",
    "selectors": [],
    "excludeSelectors": [
      "ul.gt_prefs_translator_div_li > :not(li:first-child)"
```

![image](https://user-images.githubusercontent.com/11407417/227958420-065be235-af8f-4a56-bbd7-4590d7bdcb3c.png)

It is convenient to have the translation of the first 'li' child in the "Google select text translator" window, but how to exclude all other 'li's?

**Comment by iG8R** [comment]
I use it in Firefox, TemperMonkey. But still on Windows.

**Comment by theowenyoung** [comment]
Uncaught TypeError: can't access property "style", $(...) is null

I have no idea about this.

**Comment by iG8R** [comment]
Eh, sorry.
And if theoretically, my rule should work for Immersive Translator?

**Comment by theowenyoung** [comment]
your first rule will be the top priority rule, so on this site, the second rule will not be used.

You should add that excludedSelectors rule to the first rule too.

**Comment by iG8R** [comment]
Thank you, I'll try a little later.

**Comment by iG8R** [comment]
It seems it doesn't work:(
Here is my Full User Config:

```
{
  "targetLanguage": "en",
  "updatedAt": "2023-03-27T18:18:37.672Z",
  "translationService": "openai",
  "translationServices": {
    "openai": {
      "APIKEY": "xxxxxxxxxxxxxxxxxxxxxx",
      "maxTextLengthPerRequest": "1000",
      "model": "gpt-3.5-turbo",
      "limit": "15",
      "prompt": "If the text contains ###, don't change it, do not explain, translate the following sentences to {{to}}: {{text}}"
    },
    "deepl": {
      "authKey": "xxxxxxxxxxxxxxxxxxxxx"
    }
  },
  "translationLanguagePattern": {
    "excludeMatches": [
      "en",
      "ru",
      "uk"
    ],
    "matches": []
  },
  "translationTheme": "solidBorder",
  "generalRule": {
    "additionalExcludedSelectors": [
      "ul.gt_prefs_translator_div_li > :not(li:first-child)"
    ],
    "blockMinTextCount": 0,
    "blockMinWordCount": 0
  },
  "rules": [
    {
      "matches": "www.kdxs.net",
      "selectors": [],
      "excludeSelectors": [
        ".navbar"
      ]
    }
  ],
  "translationUrlPattern": {
    "matches": [
      "www.kdxs.net"
    ],
    "excludeMatches": []
  }
}
```

**Comment by iG8R** [comment]
Only works in this way:
Edit User Rules:
```
[
  {
    "matches": "www.kdxs.net",
    "selectors": [],
    "excludeSelectors": [
      ".navbar",
      "ul.gt_prefs_translator_div_li > :not(li:first-child)"
    ]
  }
]
```

![image](https://user-images.githubusercontent.com/11407417/228033433-bbbfa9cb-25e4-40fc-b247-2e74548bf3ca.png)

But how to make this rule general?

**Comment by theowenyoung** [comment]
sorry, typo error:  `additionalExcludeSelectors`

**Comment by theowenyoung** [comment]
all advanced rules: https://immersive-translate.owenyoung.com/advanced

**Comment by iG8R** [comment]
Oh, thanks a lot! Now it works:)

**Comment by iG8R** [comment]
Yes, language mishandling only happens in the user scripts.

**Comment by theowenyoung** [comment]
https://www.npmjs.com/package/franc-min

we use this lib to detect language, it seems the only library for js.

while we use browser native API for that.

**Comment by iG8R** [comment]
OK, it's understandable that this approach doesn't work with the user scripts, unfortunately.

**Comment by iG8R** [comment]
Another example with the language mishandling.
This time it's not a user script, but an addon - LiuChan https://addons.mozilla.org/en-US/firefox/addon/liuchan/
URL of example - https://www.kdxs.net/chapter/6040/7722106

![image](https://user-images.githubusercontent.com/11407417/228310452-c89ddaf3-943d-45ba-8894-e47fdf5578d9.png)

![image](https://user-images.githubusercontent.com/11407417/228310255-549be762-c5b2-4715-8315-78a442fd0991.png)

Also, I tried to exclude the entire LiuChan window from Immersive Translate processing, but to no avail.

In this way:

![image](https://user-images.githubusercontent.com/11407417/228311305-0b76cccd-6df6-472f-ac3e-b15039b533d3.png)

And even in these ways:

![image](https://user-images.githubusercontent.com/11407417/228311828-671690b7-0295-43d3-b845-b28aa6d94739.png)

![image](https://user-images.githubusercontent.com/11407417/228312165-fe206659-c569-4365-a87b-33b8242e7ced.png)

And another problem - when I insert the wildcard {{from}} into the prompt, instead of the page language, `auto` is inserted into the request.

**Comment by iG8R** [comment]
Hi, thank you:) I'll try `#liuchan-window` and write about the result.
From the latest version `{{from}}` will be replaced by the appropriate language?
BTW, "Maximum number of paragraphs per request" in the OpenAI settings equals "3" makes the best result - the speed of the processing doesn't have much differences with the "1" and  the resulted text is more consistent and has far fewer artifact characters such as ` ``` ` and `"`.
One more question - How could I restore or choose between default and custom prompt line after updating config from the server or after updating Immersive Translate? Is it possible to restore the default settings not entirely, but individually? Now instead of going to `Developer settings -> Click to expand the local storage object` and manually copy parameters to `Edit Full User Config` I just leave prompt blank.
![image](https://user-images.githubusercontent.com/11407417/229175825-9263efc6-b2c1-4c11-92c3-9a6e95c3f33c.png)

**Comment by theowenyoung** [comment]
oh, no, it's a historical legacy problem, for now `{{from}}` will be `auto` forever, and actually OpenAI do not need this `from`, it can detect the source language.

This is because we want to let OpenAI carry paragraphs as more as possible for considering the trial user rate limit.  if we use `auto`, then all paragraphs will be merged into a request.

But in the latest version, I change my mind, because the experiment for the trial users is too bad, so I'll focus the experiment on paid openAI users.

I change the default rate limit to `1500` per minute and the default paragraphs to `1` per request.

so it's time to change `{{from}}` to the real `from` language now, yes, I'll do it next version.

`1` and `3` depending on the website content, if the paragraph is short, yes, `3` may be the better option. but `1` seems more common in most cases.




>  One more question - How could I restore or choose between default and custom prompt line after updating config from the server or after updating Immersive Translate? Is it possible to restore the default settings not entirely, but individually? Now instead of going to Developer settings -> Click to expand the local storage object and manually copy parameters to Edit Full User Config I just leave the prompt blank.

Good advice, I'll add a `reset` button for this next version

**Comment by iG8R** [comment]
Could you please a support for `ChatGPT API Free` endpoint https://github.com/ayaka14732/ChatGPTAPIFree ?

**Comment by theowenyoung** [comment]
They have down the endpoint now as the README doc.

**Comment by iG8R** [comment]
Yes, I've seen that, but there may be other endpoints acting as proxies that don't need an API key, whereas now Immersive Translate mandatory requires an API key.

**Comment by theowenyoung** [comment]
I think you can customise the endpoint at the OpenAI Settings?

<img width="1286" alt="Screenshot 2023-04-01 at 01 22 10" src="https://user-images.githubusercontent.com/62473795/229188051-fb2b0f99-c9cf-4b83-9955-9d6e7c459005.png">

**Comment by iG8R** [comment]
Yes, I changed the default endpoint to `https://chatgpt-api.shn.hk/v1/`, but I don't know how the FreeAPI endpoint responds if a custom API key is present in the request. Is it possible to add an option that will allow not to send the API key and will not raise an error that the key is needed.

**Comment by theowenyoung** [comment]
I believe it's fine if they don't need an API key, but you provided it.

**Comment by iG8R** [comment]
![image](https://user-images.githubusercontent.com/11407417/229191363-12137ab2-6919-44a4-8517-a62cfad4f373.png)

**Comment by iG8R** [comment]
It seems, if there is an API key in request to the FreeAPI endpoint it passes to OpenAI.

**Comment by theowenyoung** [comment]
:( fine.

I'll make the API key optional.

**Comment by iG8R** [comment]
Regarding `#liuchan-window` - it doesn't work too :(

**Comment by iG8R** [comment]
> :( fine.
> 
> I'll make the API key optional.

Could you please make it optional by selecting appropriate checkbox near "Show password" and leaving existing API key? Since as of now to omit transfer an API key to the FreeAPI endpoint it needs to delete API key entirely but this is not very convenient as there might be a situation when a user needs to come back to the official endpoint and they needs to search their OpenAI API key somewhere again.

Also, could you make it so that the process of resetting the default options does not affect all the options on the setting's page as a whole, but one at a time, for example, reset to default only "Prompt" or only "Maximum text length per query", etc.

I noticed, that new "Prompt" is "Do not explain, translate the text below to {{to}}:" - where is the "{{text}}" parameter disappeared?

**Comment by theowenyoung** [comment]
> Could you please make it optional by selecting appropriate checkbox near "Show password" and leaving existing API key? Since as of now to omit transfer an API key to the FreeAPI endpoint it needs to delete API key entirely but this is not very convenient as there might be a situation when a user needs to come back to the official endpoint and they needs to search their OpenAI API key somewhere again.

:( you can save it on your note app? or some password manager? Actually, I think it's weired to provide this option. cause  it's an unusual use case.

> Also, could you make it so that the process of resetting the default options does not affect all the options on the setting's page as a whole, but one at a time, for example, reset to default only "Prompt" or only "Maximum text length per query", etc.

:( sorry.. I just don't want to make the interface too complex

> I noticed, that new "Prompt" is "Do not explain, translate the text below to {{to}}:" - where is the "{{text}}" parameter disappeared?

as the description of the Prompt: `Send as a user to OpenAI conversation, where {{text}} indicates the text of the paragraph,{{from}} indicates the language of the paragraph,{{to}} indicates the target language, you can omit {{text}}, if so, it'll be sent as a separated message`

we can omit {{text}}, and it 'll be sent as a separated message, like:

```json
{
    "model": "gpt-3.5-turbo",
    "temperature": 0,
    "max_tokens": 2048,
    "messages": [
        {
            "role": "system",
            "content": "You are a translation engine that translates auto to zh-Hans, you can only translate text and cannot interpret it."
        },
        {
            "role": "user",
            "content": "Translate the text below to en"
        },
       {
          "role":"user",
          "content": "the whole text need to translate"
      }
    ]
}
```

**Comment by iG8R** [comment]
> :( you can save it on your note app? or some password manager? Actually, I think it's weired to provide this option. cause it's an unusual use case.

Yeah, I understand that it is weird, but only if OpenAI is used with the default parameters. Since Immersive Translate already can use Custom API interface address it implies that the users could use it in an unusual use case. Then why not provide options for these cases?

> :( sorry.. I just don't want to make the interface too complex (also, every single new option needs more works to handle :)

The interface become complex when there are inscriptions in the language, but if there are nearby (small) icons for the reset function it would be way convenient for the users to handle different aspects of requests to OpenAi, moreover this "complexity" only seems to be with OpenAI and not with any other translate services.

> we can omit {{text}}, and it 'll be sent as a separated message, like:

Oh, sorry... My bad, I didn't notice the reminder that {{text}} could be omitted.

PS.
Could you please help me resolve the issue regarding `#liuchan-window`, since it consumes unnecessary requests to OpenAI.

**Comment by theowenyoung** [comment]
> Yeah, I understand that it is weird, but only if OpenAI is used with the default parameters. Since Immersive Translate already can use Custom API interface address it implies that the users could use it in an unusual use case. Then why not provide options for these cases?

I mean the current options are fine for your case and the other case, And I also understand what you concerned, it's like the PostMan UI:

<img width="931" alt="Screenshot 2023-04-01 at 23 00 32" src="https://user-images.githubusercontent.com/62473795/229296975-de9d7cf6-183f-4201-ae6d-19956d57c4a6.png">

But in the current stage, Immersive Translate does not intend to provide large custom options like some production tools, instead, we want to simplify the settings to let more users use it easily. 

> The interface become complex when there are inscriptions in the language, but if there are nearby (small) icons for the reset function it would be way convenient for the users to handle different aspects of requests to OpenAi, moreover this "complexity" only seems to be with OpenAI and not with any other translate services.

Like the previous answer, I also think it might be more convenient to have this feature for that use case, but it's not a very frequent use case for most users, so at this stage I don't really want to spend too much effort on similar use cases, sorry, maybe I'll improve the usability of this in the future, hope you understand.

> Could you please help me resolve the issue regarding #liuchan-window, since it consumes unnecessary requests to OpenAI.

ok, let me install the userscript and do some tests.

**Comment by theowenyoung** [comment]
`#liuchan-window > .liuchan-container > *`

This works fine!

**Comment by iG8R** [comment]
Thanks a lot! It works finally!

> Like the previous answer, I also think it might be more convenient to have this feature for that use case, but it's not a very frequent use case for most users, so at this stage I don't really want to spend too much effort on similar use cases, sorry, maybe I'll improve the usability of this in the future, hope you understand.

Oh, sorry, I didn't mean it has to be done immediately. Even if this is implemented over time, it would be great.
