### ISSUE TITLE
翻译PDF文件，出现文字重叠，影响浏览

### ISSUE THREAD

**Issue by xiaoluome** [immersive-translate/immersive-translate#286]
![image](https://user-images.githubusercontent.com/3965507/228115262-98af51e3-aa89-4bec-abe2-8ccf2cfed1c8.png)

**Comment by theowenyoung** [comment]
已知问题, pdf 处理有点困难  正在排期优化.

**Comment by loopwang2021** [comment]
不能把翻译pdf文件保存下来吗

**Comment by theowenyoung** [comment]
0.5.5版本已基本解决～

**Comment by theowenyoung** [comment]
@loopwang2021 目前还不行
