### ISSUE TITLE
页面行内有许多公式或符号时，翻译结果很不友好

### ISSUE THREAD

**Issue by ChaoZhao4056** [immersive-translate/immersive-translate#288]
页面行内有许多公式或符号时，翻译结果很不友好，希望能进行优化

**Comment by theowenyoung** [comment]
请问有网址吗？ 因为不同的页面结构不太一样，需要看看模式～

**Comment by ChaoZhao4056** [comment]
除了公式符号，超链接对应词语的翻译也直接缺省了，示例如下：
https://wandb.ai/ayush-thakur/RLHF/reports/Understanding-Reinforcement-Learning-from-Human-Feedback-RLHF-Part-1--VmlldzoyODk5MTIx#learning-to-summarize-with-human-feedback

**Comment by theowenyoung** [comment]
这个网页结构比较特殊，已做特殊处理。

<img width="270" alt="updaterule" src="https://user-images.githubusercontent.com/62473795/228292671-2d676edb-71bf-49cf-8d20-9bf5e5fb1057.png">


点击浏览器图标更新规则之后，再试试看～

**Comment by ChaoZhao4056** [comment]
解决了，感谢！
