### ISSUE TITLE
部分超链接文本被忽略

### ISSUE THREAD

**Issue by kincorn** [immersive-translate/immersive-translate#289]
原文：The Qt Quick module provides both a [QML API](https://doc.qt.io/qt-6/qtquick-qmlmodule.html), which supplies QML types for creating user interfaces with the QML language, and a [C++ API](https://doc.qt.io/qt-6/qtquick-module.html) for extending QML applications with C++ code.
译文：Qt Quick 模块提供了一个 ，它提供了用于使用 QML 语言创建用户界面的 QML 类型，以及一个用于使用 C++ 代码扩展 QML 应用程序的 。
问题：超链接文本“QML API” 和 “C++ API” 被忽略，与所选翻译引擎无关。HTML代码：
`<p>The Qt Quick module provides both a <a href="[qtquick-qmlmodule.html](https://doc.qt.io/qt-6/qtquick-qmlmodule.html)" translate="no">QML API</a>` 
参考网站： https://doc.qt.io/qt-6/qtquick-index.html  （注：整个 QT 文档的网站，均会被忽略超链接中的文本）

**Comment by theowenyoung** [comment]
谢谢反馈，看了一下，是因为他的 A 链接有这个属性 : `translate="no"`, 所以被忽略了。

我刚更新了一下这个站点的规则, 点击popup图标更新一下应该就可以了～

<img width="270" alt="image" src="https://user-images.githubusercontent.com/62473795/228268689-64678a76-15d0-4f21-8cc4-96aa6daffa3c.png">

**Comment by kincorn** [comment]
可以了，谢谢大牛
