### ISSUE TITLE
不该翻译的翻译，该翻译的没翻译……

### ISSUE THREAD

**Issue by photkey** [immersive-translate/immersive-translate#29]
![image](https://user-images.githubusercontent.com/60434581/213227198-5242ecdc-ea29-4391-93ea-2493f552a660.png)
网址：https://docs.ipdata.co/docs

另外：之前一直用一些翻译绕过代码块的插件，比方：[谷歌翻译绕过代码块](https://greasyfork.org/zh-CN/scripts/392357-%E8%B0%B7%E6%AD%8C%E7%BF%BB%E8%AF%91%E7%BB%95%E8%BF%87%E4%BB%A3%E7%A0%81%E5%9D%97)，但是效果都不理想，在一些类似这个上面网址的文档中，代码部分也都会翻译。希望immersive 能在这方面优化一下，谢谢。

**Comment by theowenyoung** [comment]
似乎该网站屏蔽了我的访问。无论直连还是翻墙..

**Comment by theowenyoung** [comment]
这个网址，我测试它会检测当前网页的语言是简体中文，理论上并不会自动翻译啊。

你是强制点击的翻译按钮吗？

**Comment by YJL12345** [comment]
好奇怪，推特并不会翻译，不管怎么设置？

**Comment by theowenyoung** [comment]
你的是什么版本，试一下最新版，然后切换翻译引擎试试。

**Comment by theowenyoung** [comment]
这个问题应该解决了，升级到最新版本即可～ 有问题再打开，谢谢～
