### ISSUE TITLE
网络受阻一直加载

### ISSUE THREAD

**Issue by derotyoung** [immersive-translate/immersive-translate#290]
翻译服务使用的OpenAI，对网络比较高一点时，会一直在加载状态，切换到谷歌翻译时仍处于加载状态。

建议：1)切换服务时阻断上一个服务；2)翻译服务添加一个默认超时时间设置，超出时间停止服务不影响原网页的浏览

**Comment by derotyoung** [comment]
我还有一个想法是添加设置一个主翻译服务和备选翻译服务，主翻译超时后再自动启用备选服务，不过转念一想这种方式有点复杂也没太大的服务，因为现在的接口绝大多数场景足够快了。还是比较倾向于做服务请求统一管理，最终的架构的也比较优雅

**Comment by derotyoung** [comment]
这个扩展确实好用，已经作为主力翻译扩展了，不过我也是仅个人使用习惯上考虑提供的一些想法。不过我是后端开发，应该开发不了扩展程序

**Comment by theowenyoung** [comment]
（来自后端的严谨性！

我们前端仔：“精细化控制请求？释放不用等内存？没事，随便丢弃，靠js去做垃圾回收就好了，不用管”

**Comment by theowenyoung** [comment]
暂时没有计划解决这个问题，先关掉了哈～
