### ISSUE TITLE
Translated sentence first, original sentence second and TTS(Text to speech) option.

### ISSUE THREAD

**Issue by trionline1234** [immersive-translate/immersive-translate#291]
I think this app will be wonderful for language learner if it can show translated sentence first instead original sentence as well as  bilingual TTS(Text to speech) option.

**Comment by theowenyoung** [comment]
We can use the edge browser native translation to do this? they also provide the tts service.

**Comment by trionline1234** [comment]
But it don't read two language at once, and how can i setup Immersive Translate extension on Edge browser ?.
It is better for "translated language - original language" option.

**Comment by theowenyoung** [comment]
Thanks, I mean immersive translate do not support show translated text only yet, and if you need this feature now,  you can the Edge Browser native translate function.

**Comment by trionline1234** [comment]
No, i mean it show 2 text(not translated text only), example: "I love you." --> "Anh yêu em. I love you. " instead of "I love you. Anh yêu em." and it can text to speech 2 language at once.

**Comment by theowenyoung** [comment]
Hi, we reviewed this issue today, as we want to keep Immersive Translate simple and easy to use, so we are not planning to support feature like this, so I'll close this issue for now, thanks for your feedback.
