### ISSUE TITLE
Error when translate PDF

### ISSUE THREAD

**Issue by trionline1234** [immersive-translate/immersive-translate#292]
![image](https://user-images.githubusercontent.com/63534659/228552303-5de57f58-6dea-42bd-97fc-70f6c1ea2210.png)

**Comment by theowenyoung** [comment]
sorry, we are working on PDF translation now, the current version is a basic PDF translator, which can only handle some simple PDF files, there is too much to improve it.

**Comment by theowenyoung** [comment]
0.5.5 has a better experiment for pdf.
