### ISSUE TITLE
在https://www.buzzing.cc/选了几篇文章，翻译等了很久之后，failed to fetch

### ISSUE THREAD

**Issue by yyy-charlie** [immersive-translate/immersive-translate#294]
![QQ截图20230330101350](https://user-images.githubusercontent.com/33770139/228710584-00251a56-d51f-48b0-98b6-659f67dda531.png)
试了谷歌翻译和百度翻译，都是这样的结果

**Comment by theowenyoung** [comment]
试试腾讯交互翻译呢.

看起来是网络问题. 鼠标放在感叹号上可以看到错误原因
