### ISSUE TITLE
多语言段落展示问题

### ISSUE THREAD

**Issue by lindeer** [immersive-translate/immersive-translate#295]
现在的译文是以段落的形式，跟在原文段落之后，但是很多时候如果一段的文本非常长，那在阅读过程中想比照原文或译文会非常凌乱，找不到对应的位置。期望能把原文和译文展示成一个段落，如下图：
![](https://camo.githubusercontent.com/374d569269d71d42ea214eedf3d6427853a9348c6c78bd85f9a9ecc098b59f14/68747470733a2f2f692e737461636b2e696d6775722e636f6d2f534c736e6d2e6a7067)

请问这样的效果怎么实现呢？

**Comment by theowenyoung** [comment]
可以在界面设置里设置强制分段.

**Comment by lindeer** [comment]
@theowenyoung 能给更多些细节吗，怎么运行才能找到这个设置，是写配置文件吗？:pray:
