### ISSUE TITLE
option to translate into intermediate language

### ISSUE THREAD

**Issue by trionline1234** [immersive-translate/immersive-translate#297]
It is better to translate through intermediate language instead of direct language.
For example: "我爱你. -> I love you. -> Anh yêu em." instead of "我爱你. -> Tôi yêu bạn."
Because translating from English to Vietnamese is better from Chinese to Vietnames.

**Comment by theowenyoung** [comment]
got it.  But it seems a little complicated... Maybe some translation engines are better for Chinese to Vietnamese directly?
