### ISSUE TITLE
safari浏览器的重复出现问题

### ISSUE THREAD

**Issue by arisunqq** [immersive-translate/immersive-translate#304]
不好意思，在safari上经常会出现这个报错【重复出现问题】的页面。
虽然我也不清楚是不是因为插件引起的，但是在安装这个插件之前没有遇到过这个问题。
请问有解决方法，或者知道是什么引起的吗？
盼回复，非常感谢！
![重复出现问题](https://user-images.githubusercontent.com/104204977/229266833-c49f183e-a373-4c87-ac2e-153eb3d734e0.jpg)

**Comment by theowenyoung** [comment]
请问你使用的版本是？在0.2.60 左右的几个版本会有这个问题，请升级到最新版～

如果已经是最新版的话～请发一下网址～

**Comment by arisunqq** [comment]
原来是这样，应该是版本问题。我升级一下最新版，谢谢！

**Comment by arisunqq** [comment]
之前的版本是0.2.66，更新到最新版后重复问题已解决，非常感谢~
