### ISSUE TITLE
为什么不能设置谷歌翻译的国内镜像？像“划词翻译”插件里那样？

### ISSUE THREAD

**Issue by pendave** [immersive-translate/immersive-translate#307]
一直喜欢把google翻译作为首选，但是你这个用的是官方的啊，我不挂梯子还真用不成。

“划词翻译”插件里就可以设置国内镜像，这样在不开梯子的前提下也能翻译，很爽的！请加入这样的设置。

![image](https://user-images.githubusercontent.com/1331881/229323203-5142d459-420c-4cf2-9cc9-f20d8090b563.png)

**Comment by theowenyoung** [comment]
这个当前在开发者设置里，可以手动修改 user config 来实现，目前还没有做界面，因为可能会对普通用户造成困扰。类似这样，可以不填具体路径，如:`https://your-domain.com` 即可。

```json
"translationServices": {
  "google": {
    "apiUrl":""
  }
}
```

文档： https://immersive-translate.owenyoung.com/advanced#%E7%BF%BB%E8%AF%91%E6%9C%8D%E5%8A%A1%E9%85%8D%E7%BD%AE

**Comment by versun** [comment]
@pendave 
(插件设置->开发者设置->Edit Full User Config)
找到字段translationServices，添加即可(注意，多个Services直接要有逗号分隔)
```
"translationServices": {
 "deepl": {
      "authKey": "111010100101"
    },
  "google": {
    "apiUrl":"https://your-domain.com"
  }
}
```

**Comment by angle233** [comment]
> @pendave (插件设置->开发者设置->Edit Full User Config) 找到字段translationServices，添加即可(注意，多个Services直接要有逗号分隔)
> 
> ```
> "translationServices": {
>  "deepl": {
>       "authKey": "111010100101"
>     },
>   "google": {
>     "apiUrl":"https://your-domain.com"
>   }
> }
> ```
翻译失败，感叹号显示cannot read properties of undefined(reading 'class')

**Comment by versun** [comment]
@angle233 我用你给的镜像是可以的，请参考下面的设置自行修改**并点击保存**：
`{
  "interfaceLanguage": "zh-CN",
  "updatedAt": "2023-05-10T02:01:11.974Z",
  "translationService": "google",
  "translationServices": {
    "openai": {
      "APIKEY": "11111111111"
    },
    "google": {
      "apiUrl": "https://translate.amz.wang"
    }
  },`

**Comment by pendave** [comment]
是的，很好用的镜像。
