### ISSUE TITLE
使用网页版chatgpt的服务

### ISSUE THREAD

**Issue by gudezhi** [immersive-translate/immersive-translate#308]
目前只支持api版本，对于已经开通会员服务的来说，希望多提供一种选择

**Comment by theowenyoung** [comment]
chatgpt网页版有限流，其实不太适合用来网页翻译，网页翻译的请求量很大.  但是欢迎想贡献的同学～

**Comment by iG8R** [comment]
Has this feature already been implemented or has the topic been closed because it will no longer be developed?

**Comment by versun** [comment]
@iG8R 
I will reopen this issue. I confirm that the feature is currently in development, and we will update you as soon as it is ready.

**Comment by iG8R** [comment]
@versun 
Thanks a lot.

**Comment by versun** [comment]
0.4.3版本已增加该功能, 请更新插件并在开发者设置中开启beta.
该功能需要先打开https://chat.openai.com/进行登录后才可使用.

Please Update To 0.4.3 version
Feat: support ChatGPT Plus Website as Translation Service, This is a beta feature, so you can access it by enabling Beta Feature on developer settings. This is very slow, cause chatgpt can only send one request at once. Make sure you have ChatGPT Plus Account, cause there are more limit on Free Account, and I'm not sure if this bring risk for your account, be careful to use it.
BTW, it's use the cookies, so you need login to https://chat.openai.com/ first
