### ISSUE TITLE
Papago 503

### ISSUE THREAD

**Issue by bestpika** [immersive-translate/immersive-translate#310]
前幾天開始 Papago 翻譯出現無法翻譯的狀況，測試發現他出現 503 的錯誤。
有一段訊息寫著
```html
<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>
```
然後我去安裝 Papago 的官方擴充套件是可以翻譯的。
我用的是 Chrome 的瀏覽器擴充套件。

**Comment by theowenyoung** [comment]
我们的papago 是使用的这个扩展： https://chrome.google.com/webstore/detail/papago-translate/enddgifdbfoefnelepppgaabobdfbcpe

但是该扩展的作者在前几天发了一个声明，说由于个人原因，要关闭该服务：

<img width="661" alt="Screenshot 2023-04-03 at 13 23 39" src="https://user-images.githubusercontent.com/62473795/229418865-5dc3e964-65cb-4e19-a8d4-73e79d016c34.png">

原文： https://www.buymeacoffee.com/kkd927/n-a-1650726


所以沉浸式翻译的papago暂时应该也无法使用了，下个版本会先下线处理。然后再看看有没有别的方案吧...

官方的扩充套件指的是哪个呢？可以提供下链接吗？

**Comment by bestpika** [comment]
喔不對這不是官方的
https://chrome.google.com/webstore/detail/kjlcghnjglnjdagnpdhphkbljflodhda
只是 Chrome 幫他標了精選商品

**Comment by theowenyoung** [comment]
我看了它的接口，似乎也是一个私人部署的API端点，可能也不可靠。
