### ISSUE TITLE
最需要的不是沉浸式体验！

### ISSUE THREAD

**Issue by x3hong** [immersive-translate/immersive-translate#311]
最痛的不是体验，而是翻译的质量！

**Comment by heheda123123** [comment]
都能对照看了，翻译得不好你直接看原文呗

**Comment by versun** [comment]
翻译质量/服务是第三方提供的，比如谷歌翻译或者有道翻译，并不是这个插件提供的。

**Comment by theowenyoung** [comment]
DeepL 和 OpenAI的翻译质量评价较好，可以试试～

- DeepL: https://immersive-translate.owenyoung.com/services/deepL
- OpenAI: https://immersive-translate.owenyoung.com/services/openai
