### ISSUE TITLE
无法检测并翻译正文

### ISSUE THREAD

**Issue by RoyRao2333** [immersive-translate/immersive-translate#313]
首先非常感谢开发者做出的贡献，虽然本人英语水平尚可，但很多时候仍然需要一个好的翻译软件来加速阅读体验。

刚通过推荐安装了该插件，但是当我使用[Hacking With Swift](https://www.hackingwithswift.com/quick-start/concurrency/how-to-use-mainactor-to-run-code-on-the-main-queue)做测试的时候，发现貌似翻译检测不到正文，只翻译了作者名字（根据插件提示，我并未开启整个网页翻译）：

<img width="1331" alt="image" src="https://user-images.githubusercontent.com/31413093/229668294-4593dc0f-a87c-41e9-af6d-6637c79877a7.png">

<img width="1295" alt="image" src="https://user-images.githubusercontent.com/31413093/229668386-e9007c59-1836-4502-b578-1be36140fd93.png">

系统：macOS 13.3
浏览器：Firefox Developer Edition 112.0b9 (64-bit)

**Comment by versun** [comment]
@RoyRao2333 
我这边是可以正常翻译的:
<img width="876" alt="2023-04-04" src="https://user-images.githubusercontent.com/2398708/229782064-482c93ff-c4e8-4eee-b3ce-cc9acea1a6f9.png">
系统：macOS 13.2
浏览器：Safari and Firefox 111.0.1 (64-bit)
插件: V0.3.17
试一试更新下插件?

**Comment by RoyRao2333** [comment]
@versun 

插件是最新的：

<img width="756" alt="image" src="https://user-images.githubusercontent.com/31413093/229786781-0f34e3c0-9ce7-4f8d-8be1-ac500b792c74.png">

不知道是不是Firefox Developer Edition太新了？还得等作者来解答一下 😂

**Comment by theowenyoung** [comment]
我这也可以哦。 你是不是设置了什么规则？要不切换个翻译引擎试试？

<img width="1436" alt="Screenshot 2023-04-04 at 20 13 54" src="https://user-images.githubusercontent.com/62473795/229787938-7333ffe7-b978-4edc-ab9a-a4d0fe55790d.png">

**Comment by RoyRao2333** [comment]
@theowenyoung 

用的Google翻译，但不确定是不是翻译引擎的问题。

可以帮忙检查一下是不是Firefox版本的问题吗？请在Developer Edition上看一下呢 🚧

**Comment by theowenyoung** [comment]
我用的就是 firefox developer edition. 谷歌也可以～ 你是主动点击翻译，还是自动翻译英文？

**Comment by RoyRao2333** [comment]
@theowenyoung 

主动点的，无论是点击插件入口还是Option + A，都不行的

**Comment by theowenyoung** [comment]
> @theowenyoung 
> 
> 我发现了，新安装插件或进行任何设置后，需要重启浏览器后才能生效，不知道是不是bug？

新安装插件，是从商店新安装吗？还是自己手动load 安装包？

**Comment by RoyRao2333** [comment]
> > @theowenyoung 
> > 
> > 我发现了，新安装插件或进行任何设置后，需要重启浏览器后才能生效，不知道是不是bug？
> 
> 新安装插件，是从商店新安装吗？还是自己手动load 安装包？

是从Firefox插件商店直接安装，如果不重启，就会遇到我这个问题

**Comment by versun** [comment]
> 
安装插件后, 不用重启, 刷新下网页试一试

**Comment by RoyRao2333** [comment]
@versun 

在我这边，刷新网页肯定是不管用的，毕竟我还换过好几个网页😂只有重启才行

**Comment by versun** [comment]
@RoyRao2333 
我这边使用了和你一模一样的环境, 也是正常的...
<img width="917" alt="2023-04-05" src="https://user-images.githubusercontent.com/2398708/229980130-19184696-b036-4ecf-bf40-e2675bbbe0f6.png">

**Comment by RoyRao2333** [comment]
@versun 

不知道为什么我的会出问题😂但还是很感谢帮我排查，目前重启后就能使用了
