### ISSUE TITLE
能否保存翻译后的文章?

### ISSUE THREAD

**Issue by seeflood** [immersive-translate/immersive-translate#314]
非常感谢做出这么优秀的软件！
有一个需求想讨论下: 有时候一篇文章翻译好了、短时间看不完，想留着以后再看
但是以后重看的话需要重新翻译，如果翻译完了能“导出/保存翻译后的文章”就好了~ 这样下次重新看就不用重新翻译了，而且也方便人工二次修改（修改机翻不太准确的地方）

**Comment by Faputa** [comment]
https://chrome.google.com/webstore/detail/save-page-we/dhhpefjklgkmgeafimnjhojgjamoafof

**Comment by theowenyoung** [comment]
直接浏览器右键保存该网页！

**Comment by seeflood** [comment]
感谢，能解决我的问题!
