### ISSUE TITLE
希望在OpenAI的翻译选项中添加api网站的设置

### ISSUE THREAD

**Issue by dgqyushen** [immersive-translate/immersive-translate#315]
由于openai官方的封禁大陆，导致很多人无法付费使用openai的官方api来进行翻译，市面上有许多的“转发”api服务，通过调用他们的第三方key来转发到openai的服务器来间接使用openai的api，希望提供一个第三方的api网址的自定义

**Comment by theowenyoung** [comment]
现在就是支持的呀

**Comment by dgqyushen** [comment]
> 现在就是支持的呀

抱歉，我没看到更多选项，我的错误，我现在关掉这个issue
