### ISSUE TITLE
【功能】对 translate='no' 属性进行全局应用

### ISSUE THREAD

**Issue by kincorn** [immersive-translate/immersive-translate#316]
上次读 doc.qt.io 发现  `<a translate='no'>`标记的文本丢失，暂时通过针对该网站的特定规则解决。今天又遇到一个网站是这样的，我通过添加用户规则解决了，顺便看了下HTML 文档关于 `translate` 的解释 [translate](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Global_attributes/translate)，发现这是HTML的一个全局属性，不单单`<a>`用到，所有标签都支持。)

translate='no' 意味着对应的内容无需做任何翻译，只需要原样保留该文本即可。几乎主流的浏览器都能识别这个属性，谷歌翻译等自动翻译系统也会遵守这个属性，人类翻译者使用的工具也会遵守这个属性。

既然是标准，建议把 translate='no' 不翻译做成所有网站都适用，所标注的文本直接插入无需翻译，而不是现在的直接丢掉该文本的方式。

插件做得非常好用，经常用了。对作者致敬！希望越来越好！

**Comment by theowenyoung** [comment]
现在应该就是不翻译的呀，是哪个网页的该元素会被丢弃？

**Comment by kincorn** [comment]
版本：0.3.13
引擎：谷歌翻译
网页： https://doc-snapshots.qt.io/qt6-6.5/qtqml-qtquick-compiler-tech.html
`<p>The <a href="[qtqml-tool-qmltc.html](https://doc-snapshots.qt.io/qt6-6.5/qtqml-tool-qmltc.html)" translate="no">QML Type Compiler</a>, <i>(qmltc)</i> compiles QML types to C++ classes. These C++ classes are then added to your application and`
被翻译成：`, (qmltc) 将 QML 类型编译为 C++ 类。`

**Comment by versun** [comment]
@kincorn 
所以你期望的结果是: 该 QML Type Compiler, (qmltc) 将 QML 类型编译为 C++ 类。
对吧

**Comment by theowenyoung** [comment]
ok, 我改一下规则。将这个应用到全局而不是 qt.io

**Comment by theowenyoung** [comment]
已更新规则～
