### ISSUE TITLE
youtube等主流视频网站的双语显示支持

### ISSUE THREAD

**Issue by wongchenv** [immersive-translate/immersive-translate#317]
希望使用openai的语音转文字模型, 达成支持视频的双语显示的功能. (Google 自带的英文字幕生成不太准确)

**Comment by theowenyoung** [comment]
这个功能要实现可能要配合服务端做.. 而且速度应该还挺慢. 生成和翻译都需要一定的时间。

**Comment by theowenyoung** [comment]
目前已完美支持Youtube 的字幕双语显示了：

随便打开一个视频 <https://youtube.com/watch?v=EWX0bbGAd0k> ，点击沉浸式翻译面板，然后选中【自动开启双语字幕】即可开启。

![](https://s.immersivetranslate.com/assets/youtube-subtitle.jpeg)
