### ISSUE TITLE
有的内容没有进行翻译

### ISSUE THREAD

**Issue by duoluodexiaoxiaoyuan** [immersive-translate/immersive-translate#320]
浏览器:edge
![image](https://user-images.githubusercontent.com/59086082/229975541-e5ad09a8-946c-49d2-add9-94c892c4dc57.png)
地址：https://portal.azure.com/?quickstart=true#create/Microsoft.CognitiveServicesOpenAI

![image](https://user-images.githubusercontent.com/59086082/229975658-0d64fd26-ac92-40ca-804f-eedafe813090.png)
![image](https://user-images.githubusercontent.com/59086082/229975695-8c3fcebc-5a76-4f67-a404-c159d7eca37b.png)

使用的必应翻译，发现有的内容没有翻译到

**Comment by theowenyoung** [comment]
好吧，这其实是feature，默认情况下对很短的词语不翻译。

**Comment by duoluodexiaoxiaoyuan** [comment]
> 好吧，这其实是feature，默认情况下对很短的词语不翻译。

如果后续有划词翻译就可以不用管了，感觉还是有必要翻译的毕竟单词不认识

**Comment by theowenyoung** [comment]
嗯，这个会有的！

**Comment by duoluodexiaoxiaoyuan** [comment]
不知道划词翻译大佬计划什么时候开发
今天自己琢磨了一次发现划词翻译(其实就是选中翻译)功能还是比较容易实现的，我觉得解决了这个问题，至少类似有些内容不翻译，翻译错乱导致影响正常阅读效果这些就找到了替代品。

加个监听鼠标弹起即可解决
document.addEventListener("mouseup", function(){
  var selectedText = window.getSelection().toString();
  console.log(selectedText);
});

判断一下弹起内容是否为空

因为源码我现在启动遇到bug,导致我改起代码测试有很大的阻碍，所以我现在只能想如果我自己实现应该怎么做。

**Comment by theowenyoung** [comment]
用鼠标滑过解决～
