### ISSUE TITLE
[Feature Request] 能否增加对 Azure OpenAI Service 的支持

### ISSUE THREAD

**Issue by wangyingang** [immersive-translate/immersive-translate#321]
[Azure OpenAI Service 目前已支持GPT-3.5-Turbo 和 GPT-4 的预览版](https://learn.microsoft.com/zh-cn/azure/cognitive-services/openai/chatgpt-quickstart?tabs=command-line&pivots=programming-language-studio)

**Comment by theowenyoung** [comment]
似乎和 openai 的API 请求格式一样？你有azure的权限吗？

有没有试过在设置直接自定义 API为你在azure上获得的endpoint? 

看起来直接改设置页面里的这个值就可以了呢。

**Comment by silvonli** [comment]
我申请到了Azure OpenAI服务。
在设置页面中，修改了自定义API地址，并填入了API密钥。
点击“测试服务”时，出现了错误，显示以下提示内容：

```
401: { "statusCode": 401, "message":
"Unauthorized. Access token is missing,
invalid, audience is incorrect (https:|/
cognitiveservices.azure.com), or have
```
实际翻译页面时也报同样的错。

报401感觉是apikey不正确，但同一apikey搭配相同的URL，在另一个应用中可以正常使用。

下面是官方文档，其中有python调用示例，供参考。
https://learn.microsoft.com/en-us/azure/cognitive-services/openai/quickstart?tabs=command-line&pivots=rest-api

**Comment by wangyingang** [comment]
> 似乎和 openai 的API 请求格式一样？你有azure的权限吗？
> 
> 有没有试过在设置直接自定义 API为你在azure上获得的endpoint?
> 
> 看起来直接改设置页面里的这个值就可以了呢。

我有 Azure 的使用权限，实际上 Azure API 接口在调用细节上和  [OpenAI Chat completions](https://platform.openai.com/docs/guides/chat/chat-completions-beta)  的有着一些细微差别，因此目前自定义 API endpoint 是无法有效工作的。

不过经过一番尝试，发现了一个 workaround 供大家参考。总体思路很简单，构建一个代理，把 Azure OpenAI Service 的接口包装的与 OpenAI Chat completions 接口完全兼容，再在 immersive-translate 中设置自定义 API endpoint 为代理即可。可以使用 Cloudflare 的 worker 构建代理，代理可以自己编码，也可以使用现成的 [cf-openai-azure-proxy](https://github.com/haibbo/cf-openai-azure-proxy)。整理一下具体步骤：

1. 在 [Cloudflare](https://www.cloudflare.com) 中 创建 worker 并部署 [cf-openai-azure-proxy](https://github.com/haibbo/cf-openai-azure-proxy)。(具体部署细节在该项目中有详细描述，在此就不再复述)
2. 为该 worker 绑定一个自定义二级域名。（该步骤可选，如果你希望该代理 API 无需科学上网即可使用，那么就需要绑定一个国内可以访问的域名。如果你可以科学上网，那么完全可以使用worker自带的 workers.dev 域名）
3. 在 immersive-translate 中设置自定义API中填写该代理绑定的域名。**注意：这里除了域名以外，需要填写调用地址的全路径，** 即 `https://your-proxy.domain/v1/chat/completions`，这个`/v1/chat/completions`不可省略。API key 填写 Azure 中的就好。

以上步骤我已经实际测试过，并正在使用中。作者可以采用这个 workaround ，也可以实现支持 Azure OpenAI Service 的功能。如果希望我来实现这个功能请艾特我，我是非常乐意帮忙的。

该 Issue 可以关闭了。
