### ISSUE TITLE
safari 10.14.6+Tampermonkey，无法出现浮窗

### ISSUE THREAD

**Issue by JustinYuan94** [immersive-translate/immersive-translate#323]
作者您好，报告一个问题。

使用safari 10.14.6+Tampermonkey，浮窗无法出现，并且出现错误提示：SyntaxError: Unexpected private name #callIteratorNext. Cannot parse class method with private name.

谢谢！

**Comment by theowenyoung** [comment]
请问是任何网站都不会出现吗？

你可以试试这个简单网页： https://immersive-translate.owenyoung.com/example/

**Comment by JustinYuan94** [comment]
是的，依然无法出现。经过测试，发现在0.044及之前都可以使用，后面的版本就开始不能用的。

**Comment by versun** [comment]
@JustinYuan94 更新下插件，然后把safari完全退出再打开试一试
