### ISSUE TITLE
翻译pdf报错

### ISSUE THREAD

**Issue by duoluodexiaoxiaoyuan** [immersive-translate/immersive-translate#324]
浏览器: edge
pdf地址:https://azure.microsoft.com/mediahandler/files/resourcefiles/azure-for-architects/Azure_for_Architects.pdf
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/59086082/230319037-932a3884-34b9-4e4e-bf8c-da29ca72bf8c.png">

**Comment by theowenyoung** [comment]
油猴脚本暂不支持，下个版本把这里的按钮提示改一下。

**Comment by theowenyoung** [comment]
暂不支持的页面，这个按钮都应该显示“暂不支持翻译该页面” 才对～

**Comment by duoluodexiaoxiaoyuan** [comment]
打算这么改吗，应该好改，我回去研究一下，贡献下代码，我以前你要支持pdf打印

**Comment by theowenyoung** [comment]
当然在油猴中支持pdf更好～

但是可能需要多一点时间，所以暂时可以先做这个变更？

**Comment by theowenyoung** [comment]
油猴已关闭该选项
