### ISSUE TITLE
Unable to translate

### ISSUE THREAD

**Issue by windkind88** [immersive-translate/immersive-translate#326]
https://******.github.io    Unable to translate
https://github.com/***    Cannot load floating window.
i wish to  the developer can solve it,   ths！😘

**Comment by theowenyoung** [comment]
Maybe you should change your userscript extension. it's because the userscript extension can not inject to github.

**Comment by windkind88** [comment]
> Maybe you should change your userscript extension. it's because the userscript extension can not inject to github.

but EdgeBrowsers can translate github & github.io, The Via-browser's Google Translate tool can also translate GitHub &github.io.  could you learn from their implementation methods?

**Comment by theowenyoung** [comment]
I think they are not userscript?

**Comment by Eyion** [comment]
其实前面某个版本已经出现，所以切回0.3.13，看到0.4.0以为修复了，结果还是不行

**Comment by Eyion** [comment]
其实前面某个版本已经出现，所以切回0.3.13，看到0.4.0以为修复了，结果还是不行

**Comment by Eyion** [comment]
刚才试了一下，又可以翻译了，但有些内容没翻译到
![image](https://user-images.githubusercontent.com/26318038/230442867-8ded79d4-4bba-412f-bdb1-1d156d30d2c7.png)

**Comment by Eyion** [comment]
刚才试了一下，又可以翻译了，但有些内容没翻译到
![image](https://user-images.githubusercontent.com/26318038/230442867-8ded79d4-4bba-412f-bdb1-1d156d30d2c7.png)

**Comment by theowenyoung** [comment]
较短的内容目前默认是自动跳过的.

**Comment by Eyion** [comment]
切换为翻译所有区域可以解决吗

**Comment by windkind88** [comment]
Just tried it, this plugin does not work with Via Browser, can support other Browsers.

**Comment by theowenyoung** [comment]
yes, We do not support via yet.
