### ISSUE TITLE
对页面进行可控翻译

### ISSUE THREAD

**Issue by wongchenv** [immersive-translate/immersive-translate#327]
现在开启翻译后有三个问题.
1. 对于适配过的网站可以有很好的支持, 但对于大量没有适配过的网站效果欠佳, 容易排版异常造成阅读困难.
2. 部分页面只需要对最主要的部分进行翻译, 而不是整个页面.
3. 有时候翻译后只想看译文, 而不是同时显示.

所以诞生了两个需求:
1. 对网站可以进行可控翻译控制, 控制哪里翻译, 哪里不翻译. 并且支持保存/同步/重置每个页面的自定义配置.
2. 显示模式可控, 分为显示译文和原文译文同时显示.

**Comment by theowenyoung** [comment]
> 对网站可以进行可控翻译控制, 控制哪里翻译, 哪里不翻译. 并且支持保存/同步/重置每个页面的自定义配置.

这个是比较高级，所以目前是放在开发者 设置里， https://immersive-translate.owenyoung.com/advanced ，按照这个文档可以自助调整每个网页的布局。


> 显示模式可控, 分为显示译文和原文译文同时显示.

这个在计划中了～

**Comment by wongchenv** [comment]
> > 对网站可以进行可控翻译控制, 控制哪里翻译, 哪里不翻译. 并且支持保存/同步/重置每个页面的自定义配置.
> 
> >这个是比较高级，所以目前是放在开发者 设置里， https://immersive-translate.owenyoung.com/advanced ，按照这个文档可以自助调整每个网页的布局。
> 期待普通用户的可视化的操作.

**Comment by versun** [comment]
https://github.com/immersive-translate/immersive-translate/discussions/377
