### ISSUE TITLE
考虑对open ai的接口支持流模式吗？

### ISSUE THREAD

**Issue by lastIndexOf** [immersive-translate/immersive-translate#328]
官方文档： https://platform.openai.com/docs/api-reference/completions/create#completions/create-stream
支持后可以支持openai 的接口通过流式返回数据，这样可以避免由于openapi接口响应比较慢导致每次翻译等待很久体验不佳。

**Comment by theowenyoung** [comment]
目前对openai已经调整为每次只发一个小段落，速度还可以。

每一个段落都用流去展示的话，其实看起来会有点乱。

**Comment by theowenyoung** [comment]
正在重新评估~ 可能会提供该特性

**Comment by Rory-Z** [comment]
> 正在重新评估~ 可能会提供该特性

请问有任何更新么？

**Comment by fredericky123** [comment]
请问有任何更新么？

**Comment by theowenyoung** [comment]
暂时还没有计划实现该模式。

如果要实现的话，在网页翻译里需要建立大量并行的长连接，已经对网页的高频修改，暂时没有计划实现该特性。

未来应该也不会支持。暂时关闭该issue了哈。
