### ISSUE TITLE
Replace Original or onHover show the translation

### ISSUE THREAD

**Issue by neoOpus** [immersive-translate/immersive-translate#329]
Hi,

I think the best thing to use this to learn languages is to have it keep the original text and replace it like browsers default translator do, but what would be a plus is to make the translations show and hide (smoothly) when we move the mouse over, it make it easy to spot differences between certain languages and see the sentences structure and focus on finding patterns which allow learning naturally but quicker since we don't move our eyes from one side to another but just keep them foucsed on the specific part and then move the mouse in and out of the sentences to see them transformed into the translated version, this will reinforce learning but also reduce clutter caused by the actual way to translate the pages, it will keep the layout as close as possible to the non-translated version...

End-user should be capable to select to see the translation or the original from the menu by default... and when they move the mouse they see the vice-versa.

I hope this makes sense otherwise I will try to make a visual representation of this.

**Comment by theowenyoung** [comment]
Have you tried this extension? https://chrome.google.com/webstore/detail/mouse-tooltip-translator/hmigninkgibhdckiaphhmbgcghochdjc?hl=en

**Comment by neoOpus** [comment]
Right now the replacement works fine but it doesn't allow to see the original when hovered with the mouse, I hope you can make this available too as it can be a good option and having it work with a trigger key (Shift / Alt / Ctrl) would help controlling the replacement back and forth, and will allow to see some of the broken links that are caused by the translation (and clicking over them) while maintaining and understanding of the description.

I hope this makes sense.

**Comment by theowenyoung** [comment]
Hi, @neoOpus  we have finally supported this feature now, Have you tried the latest version of immersive translate? You can configure a trigger key in the popup and try it out. When the mouse hovers over a paragraph, the translation will appear below the paragraph

**Comment by neoOpus** [comment]
What I mean is that the translation should appear but also disappear with the same trigger key so we can see what the original text is and it also as I told you before allows to fix some urls, learn the language by doing live comparison and making progress, what I love about this extension is that it has many features and allows to use several services unlike other extension I prefer on a daily basis [Mouse Translator Tip](https://chrome.google.com/webstore/detail/mouse-tooltip-translator/hmigninkgibhdckiaphhmbgcghochdjc) as well as QTranslate, but I would love to just use this one and I think it will not be useful to me this request but to everyone who is learning a language or in need to translate partially something (that's why I asked for this feature and I am grateful that you did the implantation of the replacement which works great) to resume what is missing is to do the reverse and allow to see the original text, without clutter nor layout breaking… I hope this makes sense.


Thank you again for your time and commitment work. I really appreciate it.
