### ISSUE TITLE
关于本地 pdf 翻译功能的疑问

### ISSUE THREAD

**Issue by Andy-AO** [immersive-translate/immersive-translate#33]
这个好像没有识别出段落，复制出来分段是不对的，这个是 bug 还是目前还没做分段的功能？

![image](https://user-images.githubusercontent.com/38101170/213326409-532cc054-8494-473e-983b-c4b8557df701.png)

缩小之后完全乱了，这个是已知的 bug 吗？

![image](https://user-images.githubusercontent.com/38101170/213326376-beb140fa-9469-48c9-9b09-012393e4a7a6.png)

# links

[Structural and functional brain abnormalities in chronic low back pain A systematic review☆ 慢性腰痛的大脑结构和功能异常：系统评价☆ J Kregel 2015.pdf](https://github.com/immersive-translate/immersive-translate/files/10452264/Structural.and.functional.brain.abnormalities.in.chronic.low.back.pain.A.systematic.review.J.Kregel.2015.pdf)

**Comment by theowenyoung** [comment]
因为现在分段是根据行高判断的..你这个似乎看起来每行隔的空间太大了..

我想想有没有更好的办法..

缩小这个我还没测试过。

目前pdf翻译还很初级，可能有不少问题

**Comment by Andy-AO** [comment]
> 因为现在分段是根据行高判断的..你这个似乎看起来每行隔的空间太大了..
> 
> 我想想有没有更好的办法..
> 
> 缩小这个我还没测试过。
> 
> 目前pdf翻译还很初级，可能有不少问题

这种行高在论文中很常见的，我经常下到这样的文件。对于这类情况来说，感觉缩进是个比较好的识别方法。

**Comment by theowenyoung** [comment]
也会识别缩进，当时只是认为缩进一定是一个新段落。

但是行间距那个有点头疼，因为我测试的pdf文件，有的行间距非常之短.

**Comment by Andy-AO** [comment]
> Structural and functional brain abnormalities in chronic

感觉如果识别出来的段落是那种齐刷刷的一样长而且很多，那肯定是有问题的，除非是写什么诗集之类的东西，没有人会这样做的。

**Comment by theowenyoung** [comment]
所以是不是可以把行间距调的更高一点？ 因为大多数排版良好的pdf 都会有缩进是吗？

**Comment by Andy-AO** [comment]
> 所以是不是可以把行间距调的更高一点？ 因为大多数排版良好的pdf 都会有缩进是吗？

抽了5篇论文，发现都有缩进

**Comment by theowenyoung** [comment]
好的，我准备将这个间距调整到2.5倍 ， 之前是 1.9倍, 你的示例文档的间距是2.3倍。· 我本地测试后发现都是正常的。

**Comment by theowenyoung** [comment]
可以了，该版本已经发布了，有空可以试试。

**Comment by Andy-AO** [comment]
> 可以了，该版本已经发布了，有空可以试试。

好的，辛苦了

**Comment by theowenyoung** [comment]
PDF相关问题统一在 https://github.com/immersive-translate/immersive-translate/issues/37 里讨论，暂时先关闭这个问题了
