### ISSUE TITLE
feature request: support azure openai api

### ISSUE THREAD

**Issue by wxxb789** [immersive-translate/immersive-translate#330]
will this plugin support Azure OpenAI api?

**Comment by theowenyoung** [comment]
yes, a couple days.

**Comment by theowenyoung** [comment]
0.4.1 has supported both azure openai and openai api

**Comment by wxxb789** [comment]
update to v0.4.2. but there is still only openai, no Azure Openai Api.

![image](https://user-images.githubusercontent.com/49564443/233762919-d8755794-d946-448e-a270-0a0215f3d647.png)
![image](https://user-images.githubusercontent.com/49564443/233762929-0183b095-aea6-49c3-a8c6-b91c70f752e4.png)
