### ISSUE TITLE
可以自定义网页不同区域用不同的显示样式么？

### ISSUE THREAD

**Issue by lianwensheng** [immersive-translate/immersive-translate#331]
可以自定义网页不同区域用不同的显示样式么？
例如：YouTube的评论区用“引用样式”，更多推荐区用“无”
这样看起来好像更美观些😁
![Inked屏幕截图 2023-04-07 183238](https://user-images.githubusercontent.com/36002202/230595710-e4a4fcd2-10a1-417c-bfba-cb90695edc7e.jpg)
![屏幕截图 2023-04-07 184028](https://user-images.githubusercontent.com/36002202/230595721-2a146e96-e899-4d83-9bbf-d34ce0c11d5e.png)

**Comment by theowenyoung** [comment]
好吧，这个不好实现，且过于复杂... 无法抽象...
