### ISSUE TITLE
悬浮的通知是否也可以支持翻译

### ISSUE THREAD

**Issue by duoluodexiaoxiaoyuan** [immersive-translate/immersive-translate#332]
![image](https://user-images.githubusercontent.com/59086082/230694119-1b47dd11-291b-4de7-aadc-417741727447.png)

**Comment by theowenyoung** [comment]
已支持～ 更新一下规则

<img width="270" alt="updaterule" src="https://user-images.githubusercontent.com/62473795/230770161-a3f4918b-9001-44d2-a560-c6d66e02b31a.png">
