### ISSUE TITLE
epub翻译章节序号问题

### ISSUE THREAD

**Issue by 0xueping** [immersive-translate/immersive-translate#335]
在双语翻译epub电子书时，每一章的数字，例如（第1章）1、2、3，它也会去翻译出来，“1 (请提供更多上下⽂以获得更准确的 翻译)”。
索性，不要翻译这些章节序号更好一些。

**Comment by theowenyoung** [comment]
请问有示例电子书吗？

如果标题只是简单的数字，当前应该就是不会翻译的。

**Comment by Pengree** [comment]
感谢Owen热线回复。

电子书链接如下：https://drive.google.com/file/d/1cB5i4Cxn8fF0sex-Q5by8FoVG4nF1GC2。
其中很多章节开头类似如下效果：
![IMG_1735](https://user-images.githubusercontent.com/14105110/230780883-80995dfc-4f9f-43b3-8976-ab5fa1556267.jpg)
![IMG_1734](https://user-images.githubusercontent.com/14105110/230780886-2d401e3b-c5f9-49cc-a2ea-88b63042f573.jpg)

**Comment by theowenyoung** [comment]
目前的 Prompt 应该优化过了～ 有问题再 reopen 哈～
