### ISSUE TITLE
有些网站段落识别上可能有问题，没有翻译

### ISSUE THREAD

**Issue by sunday-will** [immersive-translate/immersive-translate#337]
有些网站段落识别上可能有问题，没有翻译：
[俄通社-塔斯社]https://tass.ru/politika/17481669

**Comment by theowenyoung** [comment]
由于该网站自己的一些样式导致译文没有显示出来～ 已添加规则修复～

<img width="270" alt="updaterule" src="https://user-images.githubusercontent.com/62473795/230769777-2eacbc06-027d-451e-9607-69c045fe43a1.png">
