### ISSUE TITLE
【bug】添加总是翻译的网站，正则识别错误

### ISSUE THREAD

**Issue by ChloeKurumi** [immersive-translate/immersive-translate#338]
比如我想匹配：
https://ncode.syosetu.com/n9391gu/166
不匹配：
https://ncode.syosetu.com/n9391gu/
正则写成：https://ncode.syosetu.com/.+/.+
不起作用，用在线正则测试了，没毛病
但是写成https://ncode.syosetu.com/.+/.*就能匹配了

**Comment by theowenyoung** [comment]
这里的规则不是正则哦，是一个简单版本的，只支持`*` ，你的这个例子可以这样写：

```json

"matches": "https://ncode.syosetu.com/n9391gu/*",
"excludeMatches":"https://ncode.syosetu.com/n9391gu/"
```

**Comment by theowenyoung** [comment]
如果detect到没有 `*`, 会认为是一个 exact == 的匹配。

**Comment by ChloeKurumi** [comment]
> 如果detect到没有 `*`, 会认为是一个 exact == 的匹配。
原来如此，懂了，已解决，谢谢
