### ISSUE TITLE
如何设置原文语言这里为自动检测语言，因为插件自动检测到的语言不准确，比如会自动检测中文为英文以及自动检测英文为中文的情况

### ISSUE THREAD

**Issue by Suny256888-sy** [immersive-translate/immersive-translate#34]
![image](https://user-images.githubusercontent.com/73524145/213337888-6ea795b9-07d5-4c1a-a271-14885aaf59ee.png)

**Comment by theowenyoung** [comment]
> 如何设置原文语言这里为自动检测语言，因为插件自动检测到的语言不准确?

不好意思，我没听明白，你是想设置为「自动检测」？还是设置为「英文」？

**Comment by theowenyoung** [comment]
暂时先关了哈～
