### ISSUE TITLE
翻译本地PDF的排版很糟糕

### ISSUE THREAD

**Issue by Zhaoge8888** [immersive-translate/immersive-translate#340]
我想翻译本地PDF文件，可是上传开始翻译后，翻译的结果竟然在右边，而且排版惨不忍睹。我只想要双语对照翻译，我不知道这是怎么一回事。

**Comment by duoluodexiaoxiaoyuan** [comment]
如果你在提issue的时候可以放几张效果图就更好了，这样可以方便的排查bug，因为开发者在开发的时候可能只是试了一下本地的pdf文件，所以这种情况是可能出现的。

**Comment by Tinyglimmer** [comment]
是这样的，基本没法正常使用

**Comment by saiumr** [comment]
## 对本地pdf排版的问题，有些地方有翻译，有些地方没翻译（这个也许是网络问题），如下面对目录的翻译  
![image](https://user-images.githubusercontent.com/43678794/233520234-7f695845-33d5-4f76-b6c3-b16402b3b3e1.png)  

## 有些地方重叠，对小字号重叠更是严重（这是不是因为译文的字体大小都是固定的，没有动态变化呢？）  
![image](https://user-images.githubusercontent.com/43678794/233520688-7082db7f-36e3-43f0-879e-e7a54221751e.png)  
![image](https://user-images.githubusercontent.com/43678794/233521042-fc074497-97cf-495b-8681-0a7a99d9c646.png)

**Comment by theowenyoung** [comment]
0.5.5版本已基本解决～
