### ISSUE TITLE
翻译一个链接的tooltip后，增高的浮动窗口有时会挡住原链接

### ISSUE THREAD

**Issue by BreakingLead** [immersive-translate/immersive-translate#343]
![image](https://user-images.githubusercontent.com/30070684/230784705-d4537a60-10bf-49fc-8baa-67e0edca18c3.png)
![image](https://user-images.githubusercontent.com/30070684/230784722-abc663c6-ea74-40a0-9165-2b0582f0fe67.png)
可以看到此时无法点击原链接了

**Comment by BreakingLead** [comment]
。

**Comment by theowenyoung** [comment]
这种就取消 hover 即可？ 这个应该没什么好办法.
