### ISSUE TITLE
关于沉浸式翻译脚本和插件点击禁用扩展这个功能？

### ISSUE THREAD

**Issue by duoluodexiaoxiaoyuan** [immersive-translate/immersive-translate#344]
首先在我的理解下点击禁用扩展以后就是不让这个插件或者脚本翻译了
但是在插件里面点击禁用扩展显示已禁用但是其实是可以正常用的
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/59086082/230809208-149cea38-c468-4ce6-82d2-d4c3bffa593d.png">

上面的还可以接受
但是在油猴脚本假如当前页面不刷新，和插件一样的效果，但是一刷新悬浮按钮就消失了，应该之前的设计就是禁用扩展以后这个悬浮窗就不在的。但是用户去哪里打开扩展就懵逼了，甚至我以为脚本运行出问题了。

原来需要点击打开设置页
<img width="429" alt="image" src="https://user-images.githubusercontent.com/59086082/230809640-23033423-d828-4118-b769-750c98df2e0b.png">

然后在关于里面启用扩展
<img width="1229" alt="image" src="https://user-images.githubusercontent.com/59086082/230809682-501a102b-d55e-4c59-8c76-197743bb6bbb.png">

我暂时也没有想到好的设计，但是我感觉这个禁用扩展这个功能是可以不要的。

**Comment by theowenyoung** [comment]
插件的初始化可能会影响一些网站，所以这里提供了一个方便的临时禁用功能。对于油猴来说，可能需要收藏一下设置页面，是一个在线的网址。

**Comment by duoluodexiaoxiaoyuan** [comment]
插件的初始化会如何影响网站呢，可否举例说明一下。因为正常用操作禁用是会质疑这个禁用功能是否有效或者是存在bug的

**Comment by theowenyoung** [comment]
比如 初始化的时候，如果有iframe， 会尝试在iframe之间进行通信，这会破坏部分不规范网站的功能
