### ISSUE TITLE
右键菜单丢了？

### ISSUE THREAD

**Issue by lizhuoqi** [immersive-translate/immersive-translate#345]
插件功能设计与实现是否有变化？

在火狐上，从工具栏上启动翻译功能表现正常，但页面上 **右键时菜单的快捷菜单不见了**。

版本:
* os: macOS 13.3.1
* firefox: 111.0.1
* 沉浸式翻译扩展: 0.4.0

**Comment by versun** [comment]
@lizhuoqi 
可否录个动图重现下这个问题，我这边是正常的，重现不了你的问题。
或者详细的步骤？

**Comment by CryMasK** [comment]
同樣111.0.1版本的火狐，一台Win10設備正常，另一台Win10則出現跟樓主同樣情況。 

嘗試過關閉/重啟插件，重開火狐都無效

**Comment by versun** [comment]
确实有这个问题，我们会尽快修复。
**问题：** Firefox安装插件后，重启Firefox，右键菜单项消失
**版本：** V0.4.0

**Comment by theowenyoung** [comment]
请更新到 0.4.1 版本 ~ 已解决～
