### ISSUE TITLE
Could you please add a new feature to support *Azure OpenAI*

### ISSUE THREAD

**Issue by milesplay** [immersive-translate/immersive-translate#346]
The current specification only supports OpenAI, Are there any plans to add new features that would allow us to use Azure OpenAI Keys?

**Comment by theowenyoung** [comment]
yes, a couple days~

**Comment by milesplay** [comment]
@theowenyoung 
There is no option available that allows us to input detailed API information like the one below.

https://xxxxxxxxx.openai.azure.com/openai/deployments/xxxxxx/completions?api-version=xxxxxxx

**Comment by theowenyoung** [comment]
Click expand options.

**Comment by milesplay** [comment]
thanks, but it will get into "400: sunsupported data type "errors with setting "APIKEY" and "Custom API interface address",
any possible reasons here?
@theowenyoung

**Comment by theowenyoung** [comment]
do you use  0.4.2 version?

**Comment by milesplay** [comment]
yes. I used the latest release 0.4.2

**Comment by limfoo** [comment]
> yes. I used the latest release 0.4.2



> thanks, but it will get into "400: sunsupported data type "errors with setting "APIKEY" and "Custom API interface address", any possible reasons here? @theowenyoung

You also need to check “Model: Enter customization content” and input Azure OpenAI model name.
