### ISSUE TITLE
在sciencedirect搜索页面的排版效果略差

### ISSUE THREAD

**Issue by niu971001** [immersive-translate/immersive-translate#347]
主要在左侧栏，遮挡比较严重

**Comment by versun** [comment]
@niu971001 麻烦给个网哈

**Comment by niu971001** [comment]
不好意思哦，现在发给你。


在搜索结果界面，左边的排版有点乱。 https://www.sciencedirect.com/search?qs=Engine%20calibration


另外，沉浸翻译真的很好用，谢谢你，已经发电啦！






&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "immersive-translate/immersive-translate"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月15日(星期六) 中午1:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [immersive-translate/immersive-translate] 在sciencedirect搜索页面的排版效果略差 (Issue #347)





 
@niu971001 麻烦给个网址哈

**Comment by versun** [comment]
@niu971001  感谢支持哈!
我刚试了下你给的网址, 是正常的,如下图:
<img width="870" alt="2023-04-15" src="https://user-images.githubusercontent.com/2398708/232188064-a2306e1e-a57b-4b3f-9219-66ed55679514.png">
你试一试更新下插件,目前是0.4.2版本的, 然后重启下浏览器?
还不行的话, 你可以截图过来我们看下哈, 还有浏览器版本哈

**Comment by niu971001** [comment]
从 0.4.0 更新到 0.4.2，现在完全 OK 了。感谢！

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "immersive-translate/immersive-translate"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月15日(星期六) 下午2:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [immersive-translate/immersive-translate] 在sciencedirect搜索页面的排版效果略差 (Issue #347)





 
@niu971001  感谢支持哈!
 我刚试了下你给的网址, 是正常的,如下图:
 
 你试一试更新下插件,目前是0.4.2版本的, 然后重启下浏览器?
 还不行的话, 你可以截图过来我们看下哈, 还有浏览器版本哈
