### ISSUE TITLE
!!!自动重定向 无法使用New bing

### ISSUE THREAD

**Issue by ElonMuMu** [immersive-translate/immersive-translate#348]
该插件的代码中, 含有重定向信息. 会导致开启该插件后, bing.com会被自动重定向到bing.com.cn造成New bing无法使用. 
折腾了好久重定向的问题, 最终发现源头在这里.

**Comment by derotyoung** [comment]
我说怎么前段时间bing.com指定策略走us线路代理好好的，后面不知道老是重定向，流量日志也正常，还是不断重定向，最后加hosts解决了。原来问题根源在这，老哥牛逼！

**Comment by versun** [comment]
默认使用的就是bing.com, 这应该是浏览器或本地的问题。
