### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by MrzeroY** [immersive-translate/immersive-translate#35]
1.希望支持全局关闭阅读模式也就是沉浸，有些网站因此界面异常
2.大多数时候会把中文也跟着翻译了，希望改进

**Comment by MrzeroY** [comment]
非常抱歉，第一个是我的测试问题，请无视它😂
关于第二个反馈，只是我有些使用场景会导致这样，不必为此添加。我是在安卓端火狐使用这个脚本，意外的好用，就是扩展版本的用不了，作者或许可以考虑适配下，最后十分感谢您的作品！

**Comment by theowenyoung** [comment]
ok，如果有中英文一起的网站，还是请告诉我一下～ 添加很方便，目前是为了性能好一点，所以不再检测任何网站的中英文了。

扩展版本理论上也可以用，只不过你需要点击浏览器为扩展提供的 popup 窗口。

**Comment by theowenyoung** [comment]
第二个问题，已经优化了，重新开启所有网页都检测语言，自动去除非目标语言的翻译。

**Comment by MrzeroY** [comment]
好的，非常感谢！
