### ISSUE TITLE
[功能建议]界面设置的字体颜色是否可以考虑分别设置亮色/暗色主题？

### ISSUE THREAD

**Issue by lonelygo** [immersive-translate/immersive-translate#351]
目前的“译文显示样式”只能对译文字体设置一个颜色，并没有考虑不同主题下的显示问题。
这样的问题就是，求稳只能设置灰色，这样不管是黑色/白色背景才能有一定“可读性”，但是两头兼顾，会导致两种主题下的显示效果都不好。

**Comment by theowenyoung** [comment]
这个确实是技术上无法识别。
