### ISSUE TITLE
OpenAI翻译网页的的请求量太大了，费用很高

### ISSUE THREAD

**Issue by shouyiwang** [immersive-translate/immersive-translate#353]
比如一个reddit帖子，经常几百个请求。这几百个请求其实重复包含了完全一样的prompt，太浪费tokens了。
能不能想个办法把这些翻译请求整合一下，服务器回复的翻译再重新放到该放的地方好了。（可能需要想想办法具体怎么实现）
这样改一下，费用可能能降低50-80%

**Comment by versun** [comment]
@shouyiwang 
你可以先在"进阶设置"中, 把"直接翻译页面前多少个字符，而无需等待滚动到可视区域" 该为50或者0, 可以降低请求量哈.
