### ISSUE TITLE
github有个页面无法进行翻译

### ISSUE THREAD

**Issue by duoluodexiaoxiaoyuan** [immersive-translate/immersive-translate#356]
![image](https://user-images.githubusercontent.com/59086082/231767953-1dbac3cd-588f-4b96-b4f2-b740e15b27db.png)

使用的是油猴脚本在edge浏览器

**Comment by versun** [comment]
@duoluodexiaoxiaoyuan 
因为这个规则里面只选择翻译gist的markdown内容哈,其他都不翻的
<img width="336" alt="2023-04-14" src="https://user-images.githubusercontent.com/2398708/231896564-f5d66209-2629-4115-ba7c-f601a69250ec.png">
<img width="1249" alt="2023-04-14" src="https://user-images.githubusercontent.com/2398708/231896713-19bf1868-0a9f-4000-b351-a6fab303d873.png">
