### ISSUE TITLE
只设置了自动翻译日语韩语，但是经常自动翻译英语，而且常见词翻译错误

### ISSUE THREAD

**Issue by sobeautifu** [immersive-translate/immersive-translate#357]
比如下边这个G.E.M，应该保持不变
![image](https://user-images.githubusercontent.com/75425426/231821287-f885614d-62ac-4543-9f94-f1c0ca1aea64.png)

**Comment by theowenyoung** [comment]
自动翻译韩语表示的是如果该页面是韩语，则会自动翻译该网页里的所有段落，

如果你不需要翻译英语的话，请设置 永不翻译 英语，才会不翻译页面中的英语。
