### ISSUE TITLE
感觉覆盖在原文上的翻译才贴合“沉浸式”这个名字，就好像它原来就是中文网页

### ISSUE THREAD

**Issue by narulmcto** [immersive-translate/immersive-translate#358]
在原文下方扩展一段用于显示翻译的中文，很多网页的结构会被破坏、打乱布局。
世上网页千千万，作者不可能每个网页都去逐一优化、适配、解决，所以客观上造成了该插件的实用性不是特别高，因为用户每天访问的新网站总会遇到一些与该插件冲突的。
当然，如果用户常访问的只有几个网站，且都能得到适配，那实用性还是挺高的

**Comment by heheda123123** [comment]
你这说的就是google翻译，直接用不就行了。
问题的关键在于翻译很多不准确，需要对照原文看

**Comment by narulmcto** [comment]
@heheda123123  谷歌翻译殉了，hosts重定向法三天两头失效、速度也慢、还有延迟，
所以大家才会找到这里来、用这个的腾讯翻译引擎

**Comment by duoluodexiaoxiaoyuan** [comment]
> 在原文下方扩展一段用于显示翻译的中文，很多网页的结构会被破坏、打乱布局。 世上网页千千万，作者不可能每个网页都去逐一优化、适配、解决，所以客观上造成了该插件的实用性不是特别高，因为用户每天访问的新网站总会遇到一些与该插件冲突的。 当然，如果用户常访问的只有几个网站，且都能得到适配，那实用性还是挺高的

免费的api翻译是机翻的，如果是覆盖，是无法让你沉浸式阅读的，所以中英文都显示才是这款插件的最大一个亮点，同时也顺便学了一下英语，如果是想快速获取文章内容，只需要关注中文即可，语义不对的地方我们可能需要结合英文看一下。所以我很喜欢这款软件。并且它做的很好，bug应该会不断完善的

**Comment by versun** [comment]
若需要全文覆盖翻译的，可以先用谷歌浏览器或者微软的Edge浏览器哈

**Comment by duaneya** [comment]
这个项目的优点就是方便中英对照。。。
