### ISSUE TITLE
Text to speech for bilingual text

### ISSUE THREAD

**Issue by trionline1234** [immersive-translate/immersive-translate#359]
https://youtu.be/QllKhDdgY-4
here is a bilingual audio for language learner. this extension will be wonderful when show translated text before original text as well read aloud(TTS) bilingual text.
Love you.

**Comment by versun** [comment]
Hi @trionline1234 
Thanks for your suggestion, 
I have created a discussion to discuss this new feature. https://github.com/immersive-translate/immersive-translate/discussions/379
