### ISSUE TITLE
原文语言设置自动, 弹窗错误显示总是翻译 undefined

### ISSUE THREAD

**Issue by bxb100** [immersive-translate/immersive-translate#36]
<img width="250" alt="image" src="https://user-images.githubusercontent.com/20685961/213520482-048ca76c-a5ef-4f63-ad7b-b53e3109bc42.png">

**Comment by theowenyoung** [comment]
奇怪，这里选择自动检测语言的话，下面应该不显示才对呀。你是手动安装的吗？试试更新到最新版？

**Comment by theowenyoung** [comment]
你视频截图好像没有显示always 翻译 undefined了呀 ？
