### ISSUE TITLE
关于总是翻译英语这个勾选框的按钮的功能

### ISSUE THREAD

**Issue by duoluodexiaoxiaoyuan** [immersive-translate/immersive-translate#360]
今天发现假如我不勾选总是翻译英语，我点击页面跳转到一个新页面它依旧翻译了，不知道是不是因为spa页面的原因，它依旧是翻译的。

或者难道是会把总是翻译存储到本地localStorage里面，但是页面没有勾选此处存在小bug.希望可以排查一下
网站：https://www.joshwcomeau.com/

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/59086082/232001688-76dd73d7-b4bf-41fe-8f32-e38674904206.png">

**Comment by theowenyoung** [comment]
应该是spa页面的问题。默认情况下，他会记住前一个页面是否进行了翻译，然后会记住这个设置。

这个问题需要重新考虑下，因为其实更多的情况下，对于spa页面，如果前一个页面，用户主动点击了翻译，那么接下来点击进入其他内部页面，用户也会期望翻译。
