### ISSUE TITLE
【功能】请问支持选定区域的翻译吗？

### ISSUE THREAD

**Issue by Zhang21** [immersive-translate/immersive-translate#361]
并不想翻译整个页面，只想翻译选定的内容。
设置里面没有找到设置选择区域来翻译。

![image](https://user-images.githubusercontent.com/18358275/232009127-3b82e6e5-ee73-42ac-a8f5-fdcac2b803c3.png)

<br/>

如openai-translator或其他翻译插件那样。

![image](https://user-images.githubusercontent.com/18358275/232008911-26cd1bc4-5ac6-46c1-8118-60964e3c6f53.png)

**Comment by versun** [comment]
@Zhang21 
有的，在开发了

**Comment by versun** [comment]
@chin33z 
it's hover translate function
![2024-08-09 -09-09-46](https://github.com/user-attachments/assets/2539c48d-61f0-4888-ac74-5099850b4e04)

**Comment by chin33z** [comment]
if i use the hover, it send each <br> line as translation unit separately.
Ex. [this page](http://www.datahelper.com/mi/search.phtml?nofool=youbet&mid=27081753)
But a single sentence can cross multiple lines, which i would like the plugin to treat them as a single translation block.
You can try the link i provided. Is there any way i can ask the plugin to translate the whole post content as a single unit?

**Comment by versun** [comment]
@chin33z 
This may need to be adapted separately, and as I'm not involved in the coding at the moment, I'd suggest you create a new issue for it.

**Comment by theowenyoung** [comment]
> @versun if i use the hover, it send each < br > line as translation unit separately. Ex. [this page](http://www.datahelper.com/mi/search.phtml?nofool=youbet&mid=27081753) But a single sentence can cross multiple lines, which i would like the plugin to treat them as a single translation block. You can try the link i provided. Is there any way i can ask the plugin to translate the whole post content as a single unit?

This is just a special case, based web page elements, the extension can not detect it as seperated paragraphs.

In most case, it works well.
