### ISSUE TITLE
希望能够对照翻译 epub 的书签

### ISSUE THREAD

**Issue by Andy-AO** [immersive-translate/immersive-translate#368]
### 您希望的更新和改进是什么 | Update or Improve

epub 翻译完成后，书签是没有翻译的，希望也可以提供对照翻译，这样查看起来方便很多

![image](https://user-images.githubusercontent.com/38101170/232488337-ff9a3b11-497d-461f-b00a-7fe7317b2c6c.png)

**Comment by theowenyoung** [comment]
书签是目录吗？

**Comment by Andy-AO** [comment]
这个 issue 自己关闭了，显示是我关闭的。收到邮件后我感到很奇怪，明明我记得没关(因为没解决)。今天看到重开了，想起来这个事情。

**Comment by Andy-AO** [comment]
该需求已经实现

**Comment by theowenyoung** [comment]
确定吗... 

（好像没加呀...

**Comment by Andy-AO** [comment]
> 确定吗...
> 
> （好像没加呀...

![image](https://github.com/immersive-translate/immersive-translate/assets/38101170/fe214c86-8179-4143-b77d-b29b22100b97)


上传文件了， 
[破除成功学的迷信 Barking Up the Wrong Tree The Surprising Science Behind Why Everything You Know About Success Is (Mostly) Wrong 2017.epub.zip](https://github.com/immersive-translate/immersive-translate/files/11778019/Barking.Up.the.Wrong.Tree.The.Surprising.Science.Behind.Why.Everything.You.Know.About.Success.Is.Mostly.Wrong.2017.epub.zip)
你检查检查
[破除成功学的迷信 Barking Up the Wrong Tree The Surprising Science Behind Why Everything You Know About Success Is (Mostly) Wrong 2017(腾讯 Translated).epub.zip](https://github.com/immersive-translate/immersive-translate/files/11778018/Barking.Up.the.Wrong.Tree.The.Surprising.Science.Behind.Why.Everything.You.Know.About.Success.Is.Mostly.Wrong.2017.Translated.epub.zip)

**Comment by theowenyoung** [comment]
好像是因为你这本刚好把目录放在内容里面了：

<img width="1306" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/34562e97-c56a-4394-acee-392ed14496c8">

**Comment by Andy-AO** [comment]
> 好像是因为你这本刚好把目录放在内容里面了：
> 
> <img alt="image" width="1306" src="https://user-images.githubusercontent.com/62473795/246588599-34562e97-c56a-4394-acee-392ed14496c8.png">

哦哦，那就开开。

**Comment by Andy-AO** [comment]
@theowenyoung 
借个楼问问，本项目自己训练的GPT测试名额还有吗？

**Comment by theowenyoung** [comment]
下周会继续发送一批名额～

**Comment by keyboard3** [comment]
现在还存在这个问题吗？
