### ISSUE TITLE
Stable Diffusion WebUI error

### ISSUE THREAD

**Issue by cgnerds** [immersive-translate/immersive-translate#369]
### 插件版本号 | Version

0.4.0

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

When I use Stable Diffusion WebUI, who's  url is http://127.0.0.1:7860/, I click the drop list, it will stuck.

**Comment by versun** [comment]
@cgnerds 
we are unable to update the rules for a local address.
You can try inserting the following rules in the settings page of the immersive-translate plugin (click on "Developer settings" at the bottom left, and then click on "Edit User Rules"):
```json
[
  {
    "matches": "127.0.0.1:7860"
    "excludeSelectors": [
      "div#quicksettings"
    ]
  }
]
```
Please test and modify the rule yourself
