### ISSUE TITLE
关于PDF双栏或多栏布局的建议

### ISSUE THREAD

**Issue by Andy-AO** [immersive-translate/immersive-translate#37]
这种双栏或者多栏布局，感觉并不适合在html上呈现，因为排版会变得很复杂。双栏布局的好处主要是缩小每行的字符数，这样阅读起来会很方便。如果有人有这种需求，在html上完全可以通过缩放来实现这点。

在 ABBYY 中如果选择输出html为格式化文本，那么会将双栏和三栏拆成单栏，大大降低了排版的复杂度，提升了阅读体验。

可以借鉴这种做法。

**Comment by theowenyoung** [comment]
这是一个很好的思路，谢谢，我完了研究一下看看好不好做到。

相当于，我们默认把双栏自适应为单栏是吧？

**Comment by Andy-AO** [comment]
> 这是一个很好的思路，谢谢，我完了研究一下看看好不好做到。
> 
> 相当于，我们默认把双栏自适应为单栏是吧？

这样建议是基于这样的观察，将双栏变成单栏的  ABBYY 在转换中给出了几乎完美的排版，Word 应对这种情况时倾向于继续双栏，做出来的效果很差。

如果有需要的话可以提供文件供参考。

**Comment by theowenyoung** [comment]
可以提供的话更好～ 谢谢！

**Comment by Andy-AO** [comment]
提供的文件以及两种不同的思路做出来的html，word 排版明显出现了失误，可读性下降

[share.zip](https://github.com/immersive-translate/immersive-translate/files/10461711/share.zip)

**Comment by theowenyoung** [comment]
天呐... 这效果也太好了吧。。。 abbyy 有api什么的可以调用吗..

**Comment by Andy-AO** [comment]
> 天呐... 这效果也太好了吧。。。 abbyy 有api什么的可以调用吗..

应该有吧，印象中他们官方网站上有服务，可以部署在服务器上，很多国内软件的OCR解决方案都是它提供的(例如，福昕)，做出来的效果相当惊艳，新的版本还加入了机器学习。不过作为商业软件可能不会免费提供这些东西，这是最大的问题。

**Comment by theowenyoung** [comment]
他们这个pdf转 html是OCR转的吗？

你的这个例子中的。

**Comment by Andy-AO** [comment]
> 他们这个pdf转 html是OCR转的吗？
> 
> 你的这个例子中的。

并不是OCR！它会智能识别里面到底是图片还是文本，文本的话，就直接提取，图片的话就OCR，所以支持混合的PDF。

**Comment by Andy-AO** [comment]
> 他们这个pdf转 html是OCR转的吗？
> 
> 你的这个例子中的。

![image](https://user-images.githubusercontent.com/38101170/213583921-9a408938-182d-40fc-9779-fc3961f1c050.png)

**Comment by theowenyoung** [comment]
也许应该换个方向，寻找类似的库。

而不是像现在这样，使用pdf.js 这个库，这个库旨在渲染和原pdf一模一样的html。

要是找到能在前端这样用的库就好了。

这个体验太棒了。

**Comment by Andy-AO** [comment]
> 也许应该换个方向，寻找类似的库。
> 
> 而不是像现在这样，使用pdf.js 这个库，这个库旨在渲染和原pdf一模一样的html。
> 
> 要是找到能在前端这样用的库就好了。
> 
> 这个体验太棒了。

绝对定位排出来的那个东西，实在不适合后期加工处理，直接看倒是还不错。如果能转成普通的html，那么就根本不用费心了，直接按照原来的方式翻译就可以。

**Comment by theowenyoung** [comment]
https://github.com/jzillmann/pdf-to-markdown

找到一个PDF to markdown 的库。有在线版可以测试。

**Comment by theowenyoung** [comment]
https://willus.com/k2pdfopt/

又找到一个 pdf 转化工具。记录一下。

**Comment by theowenyoung** [comment]
效果好像也不是太好。而且需要设置太多选项。（看来这个领域付费的产品做的好是有原因的）

**Comment by Andy-AO** [comment]
还有个工具也相当厉害，是免费试用的在线工具，pdf to docx，效果相当棒，感觉 word 的格式和 html 很近了，经常用来转换成
docx 然后再导出 html，来翻译电子书，效果真是好。我只用来处理电子书，论文一般在本地就行了。

[PDF to WORD | Convert PDF to Word online for free --- PDF转WORD |免费在线将 PDF
转换为 Word](https://www.ilovepdf.com/pdf_to_word)

Owen ***@***.***> 于2023年1月24日周二 22:34写道：

**Comment by theowenyoung** [comment]
<https://www.pdftron.com/>

支持pdf转html 重排。试了下效果，非常不错。提供非常完善的各平台API支持。

就是（贵）

**Comment by theowenyoung** [comment]
pdf.js 中的一个讨论： <https://github.com/mozilla/pdf.js/issues/8772>

**Comment by theowenyoung** [comment]
https://manual.calibre-ebook.com/generated/en/ebook-convert.html

发现一个免费的软件，全平台通用，也有命令行，可以方便的把pdf转为epub。效果很好。

也许可以在服务端提供一个api来转化pdf。

**Comment by HaveF** [comment]
这个思路倒是也不错。calibre 毕竟是电子书一哥，转换啥都是全的

不过估计因为是 Python ，所以就比较慢了

**Comment by theowenyoung** [comment]
python，那是不是不适合在服务端部署..

**Comment by HaveF** [comment]
今天看到 https://fanyipdf.com/ 效果看上去也不错
双排的，首页就可以看到示例

这个活应该比想象中复杂许多
我在 deepl 上翻译 pdf 时，deepl 告诉我，要先发给 adobe 看一下

![image](https://user-images.githubusercontent.com/54462/216625435-752be975-c349-4c22-a3be-3b535676b351.png)

https://www.deepl.com/zh/blog/deepl-pdf-files-translation

> DeepL与Adobe公司合作
DeepL使用Adobe API将PDF内容转换为格式化文本，然后再将翻译后的文件转换为PDF。该过程仅需片刻，但值得注意的是，你的PDF文件和翻译后的文档将被发送到位于美国的Adobe公司进行转换。当然，翻译工作将由DeepL完成。更多信息请查看我们的[隐私政策](https://www.deepl.com/en/privacy)。


国内，大概能打的也就福昕了...肯定也是收费

**Comment by theowenyoung** [comment]
嗯。 我昨天试用deepl的时候也发现了。

**Comment by HaveF** [comment]
实在不行，考虑变成划句翻译

![image](https://user-images.githubusercontent.com/54462/216629404-bba86a3e-015d-4207-9290-9f069548a8b4.png)

不过你的段落和缓存机制可能也得相应调整，毕竟用户随便就划起了

不过这也就不够沉浸式了 = =; 如果有比划句翻译更沉浸一点的其实也不错，使用方式想象不来

**Comment by theowenyoung** [comment]
还是优先实现 整个翻译吧～

**Comment by scruel** [comment]
其实我感觉双栏对照挺讨厌的，因为会显示不全，屏幕还不够大QAQ
![image](https://user-images.githubusercontent.com/16933298/216879084-426af8a9-ee52-424f-974b-ce89bba1ad4c.png)

**Comment by theowenyoung** [comment]
如果能实现单栏 在段落下面显示pdf的译文当然是最好的～ 但是目前没法实现..

因为 pdf.js 对所有元素都是绝对定位的。没法插入在段落后面。

总之，pdf 实在太复杂了（web前端没有什么免费的方案可以处理好pdf的 reflow html化）。

**Comment by scruel** [comment]
> 如果能实现单栏 在段落下面显示pdf的译文当然是最好的～ 但是目前没法实现..
> 
> 因为 pdf.js 对所有元素都是绝对定位的。没法插入在段落后面。
> 
> 总之，pdf 实在太复杂了（web前端没有什么免费的方案可以处理好pdf的 reflow html化）。

是的，技术上比较麻烦，我也没有什么好的办法，暂时先搁置着吧

**Comment by theowenyoung** [comment]
0.5.5 版本已基本解决这个问题～
