### ISSUE TITLE
无法禁止自动翻译本地文件

### ISSUE THREAD

**Issue by Andy-AO** [immersive-translate/immersive-translate#38]
设置不翻译`file://*`，但发现打开本地文件还是会自动翻译，可以参考视频
# files
[文献.zip](https://github.com/immersive-translate/immersive-translate/files/10461798/default.zip)
# video

https://user-images.githubusercontent.com/38101170/213581503-3e6a21d7-ae61-49f7-b757-5fb4dd0401ea.mp4

**Comment by theowenyoung** [comment]
我调查一下

**Comment by theowenyoung** [comment]
mac 是ok的，你看一下控制台的打印信息？ 如果匹配到永不翻译的域名，不会打印东西

**Comment by Andy-AO** [comment]
> mac 是ok的，你看一下控制台的打印信息？ 如果匹配到永不翻译的域名，不会打印东西

打印东西了

![image](https://user-images.githubusercontent.com/38101170/213583759-c82eef66-94e6-4629-926a-eed8ea537703.png)

**Comment by theowenyoung** [comment]
点开 ctx 看一下，看看里面的url～

**Comment by Andy-AO** [comment]
`"file:///E:/%E6%96%87%E6%A1%A3%E5%AD%98%E5%82%A8/Mechanisms%20of%20use-dependent%20block%20of%20sodium%20channels%20in%20excitable%20membranes%20by%20local%20anesthetics%20%E5%B1%80%E9%BA%BB%E8%8D%AF%E4%BD%BF%E7%94%A8%E4%BE%9D%E8%B5%96%E6%80%A7%E9%98%BB%E6%96%AD%E5%85%B4%E5%A5%8B%E8%86%9C%E9%92%A0%E9%80%9A%E9%81%93%E7%9A%84%E6%9C%BA%E5%88%B6%E4%B8%A8starmer1984_%E5%AF%B9%E7%85%A7%E7%BF%BB%E8%AF%91.html"`

![image](https://user-images.githubusercontent.com/38101170/213584450-1fe68d2f-7568-42c9-b856-8f71c7c4b072.png)


[-1674170659957.log](https://github.com/immersive-translate/immersive-translate/files/10461922/-1674170659957.log)

**Comment by theowenyoung** [comment]
怀疑你的星号是中文的星号? 试试复制我的这个?： `file://*`

**Comment by Andy-AO** [comment]
> 怀疑你的星号是中文的星号? 试试复制我的这个?： `file://*`

搜索发现页面上两个`*`是相同的，而且我有个脚本，在中文状态下也禁止打出中文信号，感觉验证的必要性小。

![image](https://user-images.githubusercontent.com/38101170/213585388-542c1e74-bdbd-4f28-ab9d-7d6842a4ec50.png)


实际验证后发现的确没区别的。

**Comment by Andy-AO** [comment]
> 怀疑你的星号是中文的星号? 试试复制我的这个?： `file://*`

设置`file:///*`问题解决

**Comment by Andy-AO** [comment]
我突然想起来有些匹配规则并不是类似正则表达式的纯文本，而是有结构的，如果少写了一个东西，就不行

**Comment by theowenyoung** [comment]
好奇怪。 明明你的url可以通过我的测试用例。

**Comment by theowenyoung** [comment]
或者直接在 h5 这里 长按一下图标，然后点击 “x”，关闭悬浮球就好了。 @feipinxiang

**Comment by feipinxiang** [comment]
> @feipinxiang PC版的悬浮球 和 移动版的悬浮球是独立设置的，你需要在 h5 的模式下，打开设置页，再设置悬浮球。

感谢。搞定了
