### ISSUE TITLE
建议提供 永不翻译 的缺省设置

### ISSUE THREAD

**Issue by wang20150419** [immersive-translate/immersive-translate#384]
### 您希望的更新和改进是什么 | Update or Improve

建议提供 永不翻译 的缺省（默认）设置。

也就是浏览网站的时候，不希望 这个插件 自动开启翻译。

这样，用户使用它建立一个 翻译的白名单网站，使用体验会更好。

**Comment by itinglight** [comment]
在插件设置里面添加 * 通配符可以达到你想要的效果
![image](https://user-images.githubusercontent.com/58711135/233241830-34a04bc3-2b9f-402a-a676-dfc0be2ca9c3.png)

**Comment by wang20150419** [comment]
> 在插件设置里面添加 * 通配符可以达到你想要的效果 ![image](https://user-images.githubusercontent.com/58711135/233241830-34a04bc3-2b9f-402a-a676-dfc0be2ca9c3.png)

这样设置后，永远翻译的网站（如：twitter）不翻译了。
