### ISSUE TITLE
希望在翻译服务加入ChatGPT web模式   国内用户无法充值token 

### ISSUE THREAD

**Issue by yuan2333ace** [immersive-translate/immersive-translate#387]
### 您希望的更新和改进是什么 | Update or Improve

已经有插件支持chatgpt web keep在线，已经使用一段时间了，挺稳定的，接入web体验直接无敌。跪求大佬！！！

**Comment by versun** [comment]
@yuan2333ace 
0.4.4版本已支持，请更新插件
翻译服务选择“ChatGPT Plus”即可使用(需要先登录ChatGPT)

**Comment by yuan2333ace** [comment]
这效率  👍大佬发自我的 iPhone在 2023年4月21日，15:32，Versun ***@***.***> 写道：﻿
@yuan2333ace
0.4.4版本已支持，请更新插件
翻译服务选择“ChatGPT Plus”即可使用(需要先登录ChatGPT)
