### ISSUE TITLE
无法翻译本地的Epub文件（超过100Mb）

### ISSUE THREAD

**Issue by Eyion** [immersive-translate/immersive-translate#388]
### 您希望的更新和改进是什么 | Update or Improve

1.选择更多--制作双语Epub电子书--将本地文件拖进去
2.页面空白

**Comment by Eyion** [comment]
出现几次以下情况
![1](https://user-images.githubusercontent.com/26318038/233836629-60397628-9fb4-4d96-b078-407926a24311.jpg)
![2](https://user-images.githubusercontent.com/26318038/233836647-83576783-1762-4b1f-ab6d-1e66e7e71e63.jpg)

**Comment by theowenyoung** [comment]
请提供epub文件，谢谢。

**Comment by keyboard3** [comment]
长时间未反馈，暂时关闭
