### ISSUE TITLE
快捷键切换到翻译全部区域，只能翻译1次，不能全局翻译。手机端二者不能灵活切换。

### ISSUE THREAD

**Issue by xiaoxin6182** [immersive-translate/immersive-translate#39]
快捷键切换到翻译全部区域，只能翻译1次，不能全局翻译。手机端二者不能灵活切换。

**Comment by theowenyoung** [comment]
这个目前是设计如此。全局翻译的用例应该很少被用到才对？

**Comment by xiaoxin6182** [comment]
当“需要这个模式”偶尔查1次资料的时候，也希望是全局模式来查。希望“更多”里面的那个翻译全部区域，优化一下逻辑，修改为全局。当用户手动点了这个选项后。

**Comment by theowenyoung** [comment]
最新版将更多里的逻辑改为切换到全部区域了。

**Comment by xiaoxin6182** [comment]
非常感谢，已经升级到最新版了，感觉效果很好。
