### ISSUE TITLE
谷歌插件页面希望可以支持翻译

### ISSUE THREAD

**Issue by duoluodexiaoxiaoyuan** [immersive-translate/immersive-translate#391]
### 您希望的更新和改进是什么 | Update or Improve

谷歌插件页面希望可以支持翻译，现在还不支持
![image](https://user-images.githubusercontent.com/59086082/233758448-639c4c50-904a-45f7-97bc-9e85df9b37c8.png)

**Comment by versun** [comment]
这是官方的限制，任何插件在官方的插件商店中都是无法进行任何修改的哈

**Comment by duoluodexiaoxiaoyuan** [comment]
> 这是官方的限制，任何插件在官方的插件商店中都是无法进行任何修改的哈（安全问题）

脚本是不是可以实现？

**Comment by versun** [comment]
那脚本可能得单独编译了，得确认下，脚本我不熟 @theowenyoung

**Comment by duoluodexiaoxiaoyuan** [comment]
> 那脚本可能得单独编译了，得确认下，脚本我不熟 @theowenyoung

在想一个问题，脚本和插件到底独立分开写还是写一块比较好，还是都写在一块好。不知道当时@theowenyoung是怎么考虑的。

**Comment by theowenyoung** [comment]
脚本应该也不能，脚本也是用的 tampermonkey, tampermonkey也不能访问特权页面。

（变通方法是用firefox访问谷歌的特权页面
