### ISSUE TITLE
希望正增加手动段落翻译

### ISSUE THREAD

**Issue by venkate123** [immersive-translate/immersive-translate#392]
### 您希望的更新和改进是什么 | Update or Improve

因为大多数时候并不需要将整个页面全部翻译，而且全文翻译会增加api的消耗，所以希望增加手动段落翻译。

### 补充说明 | Additional context

我注意到如果api繁忙无法翻译时，翻译失败的段落后面都有重新翻译的小图标，点击重新翻译小图标后，未翻译的段落会尝试自动翻译。这意味着，目前的版本本身就具备自动段落检测功能，并且能在段落后面添加半手动的翻译图标。

那么，是否可以尝试这样的技术路径：

1. 在目前全文翻译的基础上，增加手动全文翻译选项，开启手动全文翻译模式后，自动对页面进行分析-分段-段落后添加手动翻译图标。在此过程中不进行任何翻译。
2. 点击某段末尾的手动翻译图标，则只将该段落内容送至api进行翻译，其它内容保持不变。

不知道这样的改动容不容易实现？

**Comment by Leon2xiaowu** [comment]
最新的0.5版本增加了单独翻译鼠标所在段落的功能，应该可以满足你的需求了。

**Comment by venkate123** [comment]
> 最新的0.5版本增加了单独翻译鼠标所在段落的功能，应该可以满足你的需求了。

非常强！感谢！
