### ISSUE TITLE
翻译本地 html/txt 文件时背景颜色太暗

### ISSUE THREAD

**Issue by CavemanWork** [immersive-translate/immersive-translate#395]
### 插件版本号 | Version

0.4.2

### 平台 | Platform

macOS

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

使用本地 html/txt 翻译、epub 翻译时背景颜色与文字内容太暗了，以至于看不清文字内容。

以下文翻译本地 html/txt 时的情景
<img width="939" alt="image" src="https://user-images.githubusercontent.com/35189719/233785973-79f28761-a65e-4223-ba9e-f51da78ab6f1.png">

以下为翻译本地电子书（epub）时的情景
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/35189719/233785871-0ca2e687-afc6-442f-b843-0edfe82ab038.png">

如果能够提供此部分自定义渲染功能，是最完美的方。 

### 补充说明 | Additional context

- 分别在 Chrome，Edge 用最新插件实验过，均有同样的问题。 
- 确认关闭（甚至卸载了）背景颜色修改的其他插件。 
- 卸载重新安装「沉浸」，也有同样问题。

**Comment by theowenyoung** [comment]
是不是dark模式导致的？ 切换为light模式正常吗？

**Comment by CavemanWork** [comment]
把 dark mode 插件关闭了也同样如此。

**Comment by theowenyoung** [comment]
最新版，我这里 Dark 模式下字体颜色是白色，可能这个问题已经被解决了？先关闭issue哈，有问题再开。

<img width="1680" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/07ac94a4-8390-4c5c-9c00-1771340bb8ee">
<img width="1475" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/65384f67-4e5d-4e3e-99e1-5b09c58ec155">
