### ISSUE TITLE
沉浸式翻译脚本悬浮球在Pico.css官网样式有点问题

### ISSUE THREAD

**Issue by duoluodexiaoxiaoyuan** [immersive-translate/immersive-translate#397]
### 插件版本号 | Version

0.4.4

### 平台 | Platform

macOS

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

官网：https://picocss.com/
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/59086082/233816419-03f3cf96-54ee-4d77-bd8b-04dbe95ef565.png">
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/59086082/233816425-21077003-a291-4e6e-be25-15949ac464f2.png">

**Comment by theowenyoung** [comment]
感谢反馈～ 最新版本 0.4.6 已解决～
