### ISSUE TITLE
有没有办法提供自定义关键字不翻译的选项？

### ISSUE THREAD

**Issue by sws797** [immersive-translate/immersive-translate#398]
### 您希望的更新和改进是什么 | Update or Improve

关键字不翻译可以使翻译更加准确，有时候把关键字翻译了会看得一懵，特别是在阅读代码文档或专业文档时。

可能的需求

1. 可以针对域名或网站设置关键字，避免关键字串用
2. 关键字识别大小写，可以避免与关键字重复的单词未参与翻译

可能的拓展

1. 划词右键添加本域名或网站下的关键字

### 补充说明 | Additional context

![image](https://user-images.githubusercontent.com/33458935/233877558-b1c07b0f-44e8-4985-a83e-d453a81363a9.png)

**Comment by sws797** [comment]
这个好像和搜索引擎有更大的关系🤔
图中使用的是必应翻译，但是百度翻译不会有这个问题。
但是想对的
```
What is Next.js?

// 百度
什么是Next.js？

// 有道
Next.js是什么?

// 必应
下一步是什么.js？

// DeepL
什么是Next.js？
```

但是如果在给关键字用字符框起来，必应的翻译也可以稍微靠谱一点，但是有的就识别不出了
```
What is `Next.js`?

// 百度
什么是“下一个.js”？

// 有道（依然识别）
Next.js是什么?

// 必应
什么是“下一步.js”？

// DeepL
什么是 "Next.js"？
```

**Comment by tanhh326** [comment]
以前用自带谷歌翻译确实会很困惑，但是这双语对照应该不碍事吧
