### ISSUE TITLE
Show translation text only

### ISSUE THREAD

**Issue by mehdifirefox** [immersive-translate/immersive-translate#40]
1.
There are two languages on a page like Dutch and English
It doesn't work fast here and sometimes translates
This problem does not have the rest of the translation extensions

2.
We don't understand the foreign language
So there is no need to have this language on the page
Please add an option to delete the original external language and the translation is on the page only

**Comment by theowenyoung** [comment]
1. What website is in both Dutch and English? In response to this question, the extension maintains a list of multilingual sites. Only after being configured as a multilingual site, the language of each paragraph will be automatically recognized.

2. Sorry, this extension is developed for bilingual translation, if you don't need bilingual translation, maybe you should try other similar extensions? The current technical implementation makes it difficult for us to display only translations.

**Comment by mehdifirefox** [comment]
> 1. What website is in both Dutch and English? In response to this question, the extension maintains a list of multilingual sites. Only after being configured as a multilingual site, the language of each paragraph will be automatically recognized.
> 
>     2. Sorry, this extension is developed for bilingual translation, if you don't need bilingual translation, maybe you should try other similar extensions? The current technical implementation makes it difficult for us to display only translations.

1.
Did not notice your answer.
But many sites i see that bilingual
And translates late

2.
If you are technically difficult
Well add an option to get the original text at the end of the page
Put the translation on the top of the page

**Comment by theowenyoung** [comment]
Sorry for late reply:

Updates:

1. The latest version has already detect the paragraph language, so we can translate multiple languages now.
2. This feature has been planed, I'll support this feature.

**Comment by theowenyoung** [comment]
the latest version has supported translation only, please click [More] to switch the mode.
