### ISSUE TITLE
建议提供 永不翻译 的缺省设置(第二次建议) 

### ISSUE THREAD

**Issue by wang20150419** [immersive-translate/immersive-translate#400]
### 您希望的更新和改进是什么 | Update or Improve

前面的建议被  close 了。但是回答者提供的方法并不能解决问题。按在插件里，添加通配符 * 到永不翻译网站里，
则会导致 总是翻译 的网站 也不自动翻译了。
https://github.com/immersive-translate/immersive-translate/issues/384

建议提供 永不翻译 的缺省（默认）设置。
也就是浏览网站的时候，不希望 这个插件 自动开启翻译，但对永远翻译的网站，则需要进行翻译。

一般用户常用的网页，设置为自动翻译，其它网站临时决定。
如果都缺省翻译，则有些网站的格式处理并不好，影响阅读和网页响应。

应用场景：
如：看github, stackoverflow, codeproject之类的网站，因为是IT技术方面的，不需要翻译，基本行。
但看新闻网站，或用twitter之类，则需要借助翻译看。

**Comment by theowenyoung** [comment]
是我哪里没明白吗？ 

首先默认情况下，所有网站都不会被自动翻译。

只有当你把网站添加到永远翻译，或者手动设置了自动翻译英语，这个时候才会有满足条件的网站被自动翻译。

从我领会到的意思，你需要做的操作仅仅是把twitter.com 添加到永远翻译的网站中，似乎就解决你的问题了？

**Comment by wang20150419** [comment]
> 

抱歉，的确是我理解错了。

我设置了 “总是翻译的语言” 为英语。这个取消后就可以达到我的要求了。非常好用的插件！
我对这个选项的理解为：如果网页里夹杂多种语言，总是翻译英文，其它不管。
