### ISSUE TITLE
ios14无法启动js

### ISSUE THREAD

**Issue by csuleiw** [immersive-translate/immersive-translate#401]
### 插件版本号 | Version

0.4.4

### 平台 | Platform

iOS

### 浏览器 | Browsers

Other

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

ios14无法使用userscripts，因此找到支持油猴的浏览器（Gear浏览器、Focus浏览器）替代。js都能正常安装，但无法启用，看不到浮球。希望作者能帮忙看看。

**Comment by versun** [comment]
现在上架了原生插件应用了哈，可以去应用商店下载看看
