### ISSUE TITLE
翻译时希望能跳过pre code等显示代码的标签

### ISSUE THREAD

**Issue by HCenggel** [immersive-translate/immersive-translate#402]
### 您希望的更新和改进是什么 | Update or Improve

翻译时希望能跳过pre code等显示代码的标签
因为这些标签往往不需要翻译的

### 补充说明 | Additional context

遇到pre code等代码标签时跳过翻译

**Comment by theowenyoung** [comment]
默认情况下就是会跳过，如果没有跳过，基本上是因为那个网站并没有按照标准使用 pre code 标签。请给出一些具体的网址～ 我们可以做一些特殊的适配

**Comment by HCenggel** [comment]
> 默认情况下就是会跳过，如果没有跳过，基本上是因为那个网站并没有按照标准使用 pre code 标签。请给出一些具体的网址～ 我们可以做一些特殊的适配

确实是您的情况，我看错了

**Comment by HCenggel** [comment]
> 默认情况下就是会跳过，如果没有跳过，基本上是因为那个网站并没有按照标准使用 pre code 标签。请给出一些具体的网址～ 我们可以做一些特殊的适配

您可以看一下这个网页  https://angular.io/guide/what-is-angular

**Comment by theowenyoung** [comment]
好的～ 将在 0.4.7 适配
