### ISSUE TITLE
翻译pdf时版面出现混乱

### ISSUE THREAD

**Issue by kinson08** [immersive-translate/immersive-translate#404]
### 插件版本号 | Version

0.4.4

### 平台 | Platform

macOS

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

进入pdf翻译模式时，译文会和原文重叠在一起，原来应该是独立一列在右侧的，但从大概第4-5页开始就出现译文移动到左侧，并与原文叠加显示，不仅无法对照阅读，连单独阅读原文和译文都不可能了。这可能与pdf不同页面大小有关，也有可能就是程序代码的问题。

### 重现步骤 | To Reproduce

1.用浏览器打开pdf；
2.点击沉浸式翻译的pdf翻译按钮；
3.开始翻译后，滚动页面就可发现问题。

### 补充说明 | Additional context

无

**Comment by kinson08** [comment]
这个导致pdf翻译功能名存实亡

**Comment by keyboard3** [comment]
pdf已经重构了第一版，排版上做了优化，edge已经在审核中了，edge审核的比较慢...

**Comment by Gnblink0** [comment]
> pdf已经重构了第一版，排版上做了优化，edge已经在审核中了，edge审核的比较慢...

更新到了0.5.3后，再次试用了PDF翻译功能。
请问更新之后，翻译PDF是否变成一次性的了？即 翻译PDF后再次按下翻译键，不会再显示原文，多次按翻译键也不会有任何改变。之前版本的PDF翻译，按一次会显示原文，再按一次会刷新翻译，我以前经常这么调整排版和更换翻译源。现在如果PDF不能重复翻译，影响还是比较大的，用起来体验不是很好
<img width="1513" alt="image" src="https://user-images.githubusercontent.com/90372670/236793744-fe4e0d73-6ecf-40e8-b16c-32da86ce4a6d.png">

**Comment by keyboard3** [comment]
> > pdf已经重构了第一版，排版上做了优化，edge已经在审核中了，edge审核的比较慢...
> 
> 更新到了0.5.3后，再次试用了PDF翻译功能。 请问更新之后，翻译PDF是否变成一次性的了？即 翻译PDF后再次按下翻译键，不会再显示原文，多次按翻译键也不会有任何改变。之前版本的PDF翻译，按一次会显示原文，再按一次会刷新翻译，我以前经常这么调整排版和更换翻译源。现在如果PDF不能重复翻译，影响还是比较大的，用起来体验不是很好 <img alt="image" width="1513" src="https://user-images.githubusercontent.com/90372670/236793744-fe4e0d73-6ecf-40e8-b16c-32da86ce4a6d.png">

能附上Pdf吗，方便我们对排版进行修复

**Comment by Gnblink0** [comment]
> 文字排版跟翻译源无关，更换翻译源(手动触发翻译)会导致懒翻译失效，一旦pdf文件过大，会导致新翻译源过度翻译。切换翻译源之后，刷新页面再次选择下打开，它会记住原来的位置，并且只会按需翻译当前位置的页面

感谢解释

总之我又测试了几个pdf，其中一个33页的期刊论文的格式很棒，比起旧版本有很大改善；但是两个超过百页的书籍和博士论文的格式都很奇怪，看上去像是单行翻译而不是整段翻译？不知道是字体还是文件大小还是其他原因
<img width="1514" alt="image" src="https://user-images.githubusercontent.com/90372670/236810514-a532058a-3901-45e0-8dd3-55a33eae60c9.png">

<img width="1514" alt="image" src="https://user-images.githubusercontent.com/90372670/236810441-f192747f-b74c-45fe-8d87-3bf17dbbcf3b.png">

<img width="1514" alt="image" src="https://user-images.githubusercontent.com/90372670/236810485-d8b68bb7-9f78-4de5-ba16-80fe5c67904a.png">


书籍PDF：[8520225.pdf](https://github.com/immersive-translate/immersive-translate/files/11420553/8520225.pdf)

**Comment by keyboard3** [comment]
> > 文字排版跟翻译源无关，更换翻译源(手动触发翻译)会导致懒翻译失效，一旦pdf文件过大，会导致新翻译源过度翻译。切换翻译源之后，刷新页面再次选择下打开，它会记住原来的位置，并且只会按需翻译当前位置的页面
> 
> 感谢解释
> 
> 总之我又测试了几个pdf，其中一个33页的期刊论文的格式很棒，比起旧版本有很大改善；但是两个超过百页的书籍和博士论文的格式都很奇怪，看上去像是单行翻译而不是整段翻译？不知道是字体还是文件大小还是其他原因 <img alt="image" width="1514" src="https://user-images.githubusercontent.com/90372670/236810514-a532058a-3901-45e0-8dd3-55a33eae60c9.png">
> 
> <img alt="image" width="1514" src="https://user-images.githubusercontent.com/90372670/236810441-f192747f-b74c-45fe-8d87-3bf17dbbcf3b.png">
> 
> <img alt="image" width="1514" src="https://user-images.githubusercontent.com/90372670/236810485-d8b68bb7-9f78-4de5-ba16-80fe5c67904a.png">
> 
> 书籍PDF：[8520225.pdf](https://github.com/immersive-translate/immersive-translate/files/11420553/8520225.pdf)

应该是这个字间距和行间距过大，导致了没有合并成一个完整的段落。贸然兼容更大的距离可能会导致不同段落的被合并在一起了。这个感觉得在下一版调整的时候才能完整的考虑进去

**Comment by keyboard3** [comment]
> > > 文字排版跟翻译源无关，更换翻译源(手动触发翻译)会导致懒翻译失效，一旦pdf文件过大，会导致新翻译源过度翻译。切换翻译源之后，刷新页面再次选择下打开，它会记住原来的位置，并且只会按需翻译当前位置的页面
> > 
> > 
> > 感谢解释
> > 总之我又测试了几个pdf，其中一个33页的期刊论文的格式很棒，比起旧版本有很大改善；但是两个超过百页的书籍和博士论文的格式都很奇怪，看上去像是单行翻译而不是整段翻译？不知道是字体还是文件大小还是其他原因 <img alt="image" width="1514" src="https://user-images.githubusercontent.com/90372670/236810514-a532058a-3901-45e0-8dd3-55a33eae60c9.png">
> > <img alt="image" width="1514" src="https://user-images.githubusercontent.com/90372670/236810441-f192747f-b74c-45fe-8d87-3bf17dbbcf3b.png">
> > <img alt="image" width="1514" src="https://user-images.githubusercontent.com/90372670/236810485-d8b68bb7-9f78-4de5-ba16-80fe5c67904a.png">
> > 书籍PDF：[8520225.pdf](https://github.com/immersive-translate/immersive-translate/files/11420553/8520225.pdf)
> 
> 应该是这个字间距和行间距过大，导致了没有合并成一个完整的段落。贸然兼容更大的距离可能会导致不同段落的被合并在一起了。这个感觉得在下一版调整的时候才能完整的考虑进去

pdf的各种各样的排版确实太过复杂，感觉可以做个补偿机制，可以编辑右侧的译文的原文，觉得自动提取的有问题，可以手动从右侧复制出来修改提取的内容，重新触发翻译。不过还有个难点是很难记住你的操作，下次又翻译的话，还是会自动提取。

**Comment by theowenyoung** [comment]
0.5.5版本已基本解决～
