### ISSUE TITLE
iOS 15.1无法在Safari打开扩展

### ISSUE THREAD

**Issue by androidcn** [immersive-translate/immersive-translate#407]
### 插件版本号 | Version

0.4.2

### 平台 | Platform

iOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![E66928CC-47A2-440A-829E-5F400A990E4B](https://user-images.githubusercontent.com/271715/234750695-8ba20128-4c19-4189-b7a4-86eba782cabe.png)

无法打开，提示Unable To Load "Immersive
Translate Extension"
An unsupported 'manifest version'
was specified.

### 重现步骤 | To Reproduce

Unable To Load "Immersive
Translate Extension"
An unsupported 'manifest version'
was specified.

**Comment by theowenyoung** [comment]
ios 版本 最小为 15.4版本，

下个版本会调整一下最低版本号要求：

苹果从15.4 版本开始支持 manifest v3:

In our ongoing commitment to a [cross-browser interoperable model for extensions](https://www.w3.org/community/webextensions/2021/06/04/forming-the-wecg/), Safari 15.4 includes additional support for Web Extensions, including support for manifest_version 3 and related API changes. New capabilities include

Safari 15.4 ships with the iOS and iPadOS 15.4 and macOS 12.3.

**Comment by androidcn** [comment]
可惜了，放弃
