### ISSUE TITLE
繁体中文翻译无效果

### ISSUE THREAD

**Issue by damieai** [immersive-translate/immersive-translate#408]
### 插件版本号 | Version

ipadOS16.4.1

### 平台 | Platform

iOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

繁体中文翻译为简体中文功能在网站中没有任何效果，不仅是ios新上架的这个app没有效果，之前我在stay里面启用这个脚本的时候，这个插件的繁体中文翻译功能也是没有任何效果的，是压根对繁体中文没有任何效果

**Comment by theowenyoung** [comment]
确实...

因为这个扩展做的是双语翻译，繁体中文目前会被当作中文而不被翻译，主要是考虑到主要场景中，比如推特信息流，中间会出现不少繁体的内容，大多数用户其实不希望把这部分文字也翻译. 所以目前就简单粗暴的把繁体中文也当作简体中文了。

繁体中文其实比较适合隐藏原文的情况下翻译，所以我一直在等隐藏原文的功能出来后再加上繁体中文的翻译...

**Comment by damieai** [comment]
隐藏原文功能的开放？是指safari的接口么，还是说什么的开放，可不可以把繁体中文的选项给出来，毕竟不是可以选择翻译或者不翻译嘛，可以不用直接封死的

**Comment by theowenyoung** [comment]
是指沉浸式翻译支持隐藏原文，只显示译文的功能。

你是在什么浏览器下使用呢？ 暂时是不是可以直接用系统自带的翻译？

**Comment by WhaleLetter** [comment]
谷歌浏览器在看油管视频时，对于繁体评论阅读很不顺畅。是否可以增加一个选项，段落中只要包含特定语言就必翻译。不知道是否合理或者实现困难？

**Comment by theowenyoung** [comment]
最新版本已支持繁体翻译到简体。

**Comment by damieai** [comment]
谢谢您的付出

**Comment by imtianx** [comment]
当前最新版本`0.8.0`，在 twitter 上一直无法将 `中文繁体翻译成简体`，翻译英文是正常，有没有办法解决。
尝试了翻译全文、更换翻译服务，依然无效。
