### ISSUE TITLE
苹果 App Store 商店版建议

### ISSUE THREAD

**Issue by Jagerx** [immersive-translate/immersive-translate#409]
### 您希望的更新和改进是什么 | Update or Improve

第一时间安装，效率太强啦！！！ 关于Safari工具栏图标的一点建议。：
<img width="455" alt="2023-04-27_13-02-15" src="https://user-images.githubusercontent.com/42521386/234764003-a5a25673-79e3-4900-80bc-f6cb3182a134.png">
参考截图上其他拓展的图标，都可以根据工具栏颜色或系统颜色调整、融合。就说咱这图标，一粉到底，显得突兀些了

**Comment by theowenyoung** [comment]
这个似乎不是自定义调整的，而是其他扩展的图标都选用了 比较暗的配色..

**Comment by Jagerx** [comment]
<img width="521" alt="2023-04-27_22-08-35" src="https://user-images.githubusercontent.com/42521386/234888972-452fd5f4-f0a7-47c1-8a89-1f831fc28268.png">
和系统设置的强调色同步，没错的

**Comment by theowenyoung** [comment]
> 0.4.5 版本更新里就有Fix: macOS safari extension shortcuts
> 
> 兴冲冲的一路试到0.4.8依旧，是我对这段英文的理解有误吗。老板

这个更新修复的是快捷键问题(`Option+A`触发翻译)，不是icon的问题～

icon的问题可能还要一点时间

**Comment by XieL1989** [comment]
AppStore版貌似无法开启Google同步，总是提示授权失败而没弹出授权界面？

**Comment by theowenyoung** [comment]
@XieL1989 点击扩展图标，再点击 左下角的设置，从在线网页版的设置页面里可以同步。

**Comment by Jagerx** [comment]
0.7.7版本起和Safari那是相当搭配了，感谢感谢
