### ISSUE TITLE
在未来是否有将源码开源的打算呢？

### ISSUE THREAD

**Issue by wangrongding** [immersive-translate/immersive-translate#41]
这段时间一直在使用这款插件，体验感和交互都非常好🌸  
大佬在未来是否有将源码开源的打算呢？很想学习下它的一些实现方式。

**Comment by theowenyoung** [comment]
我邀请你进团队了。

目前没开源主要是考虑到市场上付费的同类产品太多，开源出去容易被修改后做成付费插件。

未来也许会开源～

想参与的同学都欢迎～ 我会拉大家进team

**Comment by wangrongding** [comment]
非常感谢你~

> 我邀请你进团队了。
> 
> 目前没开源主要是考虑到市场上付费的同类产品太多，开源出去容易被修改后做成付费插件。
> 
> 未来也许会开源～
> 
> 想参与的同学都欢迎～ 我会拉大家进team

非常感谢
