### ISSUE TITLE
论文网页只翻译很少的部分

### ISSUE THREAD

**Issue by babikiu** [immersive-translate/immersive-translate#411]
### 插件版本号 | Version

0.4.4

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在“spiedigitallibrary.org”网站上，基本不翻译论文。
https://www.spiedigitallibrary.org/journals/journal-of-biomedical-optics/volume-24/issue-5/051414/Unraveling-the-molecular-nature-of-melanin-changes-in-metastatic-cancer/10.1117/1.JBO.24.5.051414.full?SSO=1

**Comment by versun** [comment]
@babikiu 
这个网站暂时不大好弄哈，得需要大佬来弄了
我看它们有提供自带的谷歌翻译，效果挺好，你可以试一试哈

**Comment by theowenyoung** [comment]
将在 0.4.7 版本修复～
