### ISSUE TITLE
ios15.2 无法启用

### ISSUE THREAD

**Issue by b19g3r** [immersive-translate/immersive-translate#412]
### 插件版本号 | Version

0.4.4（16）

### 平台 | Platform

iOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![AEB5E2B2-B96F-4FB1-BF05-94A881F59735](https://user-images.githubusercontent.com/9430684/234845523-2da94046-9888-4e99-93fb-0cb2a7f4d7d4.png)

![7570D6A0-2815-4A21-83A7-12A98C783E5E](https://user-images.githubusercontent.com/9430684/234845641-84a30583-e8da-45b5-960a-57627356cb8f.png)

### 重现步骤 | To Reproduce

无法启用

### 补充说明 | Additional context

无法启用

**Comment by theowenyoung** [comment]
下个版本修复～ 已经在审核了。

**Comment by theowenyoung** [comment]
0.4.5 已审核通过，请更新到最新版本使用，支持15.0 及以上～
