### ISSUE TITLE
希望能够增加一个选项

### ISSUE THREAD

**Issue by sherman-yang** [immersive-translate/immersive-translate#413]
### 您希望的更新和改进是什么 | Update or Improve

目前是一段一段翻译.如果是很长一段, 译文距离原文太远了,不易对照. 能不能增加一个选项:按句翻译. 就是一句原文紧跟着一句译文. 像ImTranslator的Inline Translator功能一样(这个的缺点是要先选择要翻译的文字,对于很长文章, 非常麻烦).多谢多谢

**Comment by versun** [comment]
类似划词/划句翻译？

**Comment by theowenyoung** [comment]
在界面设置里 可以设置长段落自动换行翻译

**Comment by sherman-yang** [comment]
这是另一个软件逐句翻译的样子. 我觉得这样译文很近 便于参考
***@***.***

From: Owen ***@***.***>
Reply-To: immersive-translate/immersive-translate ***@***.***>
Date: Thursday, April 27, 2023 at 11:40 PM
To: immersive-translate/immersive-translate ***@***.***>
Cc: Sherman Yang ***@***.***>, Author ***@***.***>
Subject: Re: [immersive-translate/immersive-translate] 希望能够增加一个选项 (Issue #413)

在界面设置里 可以设置长段落自动换行翻译

**Comment by versun** [comment]
@sherman-yang 看不到你发的图,能重新发下吗

**Comment by sherman-yang** [comment]
![image](https://user-images.githubusercontent.com/58446328/235838647-3157a272-4cba-475c-bb2b-3675ec7cc7b2.png)

**Comment by sherman-yang** [comment]
Reduced Interest Rate Risk: Since these ETFs hold fixed-income securities with short maturities, they are less sensitive to changes in interest rates. [降低利率风险：由于这些 ETF 持有期限较短的固定收益证券，因此它们对利率变化不太敏感。] This means that the value of these ETFs is less likely to be impacted by fluctuations in interest rates, which can be a significant risk for longer-term bond funds. [这意味着这些 ETF 的价值不太可能受到利率波动的影响，而利率波动对长期债券基金来说可能是一个重大风险。]

**Comment by sherman-yang** [comment]
就是像上面的那样 逐句翻译. 这样译文和原文很近,更便于双语阅读. 多谢多谢

**Comment by theowenyoung** [comment]
目前已经支持，在界面设置里可以开启

Sherman Yang ***@***.***> 于 2023年5月3日周三 下午1:32写道：

**Comment by sherman-yang** [comment]
目前是按段落翻译 不是逐句翻译啊

**Comment by theowenyoung** [comment]
@sherman-yang 需要在界面设置里面，启用这个选项：【开启长段落自动换行】
