### ISSUE TITLE
Azure OpenAI returned 404 error

### ISSUE THREAD

**Issue by blaisewang** [immersive-translate/immersive-translate#414]
### 插件版本号 | Version

0.4.4

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

model gpt-3.5-turbo

got "404: {"error":{"code":"404","message": "Resource not found"}}"

**Comment by theowenyoung** [comment]
填写完整地址，例如：

https://xxx.openai.azure.com/openai/deployments/gpt-35-turbo/chat/completions?api-version=2023-03-15-preview

**Comment by limfoo** [comment]
我的经验是 自定义模型名称处应该填Azure里的model name，保持和API URL path保持一致，比如这个例子里api path是gpt-35-turbo，在自定义模型名称里也要输入"gpt-35-turbo".

**Comment by Cuauhtemoc9** [comment]
实测加了cloudflare代理后用这个可行 https://your-proxy.domain/v1/chat/completions #321
