### ISSUE TITLE
github页面没有进行翻译

### ISSUE THREAD

**Issue by duoluodexiaoxiaoyuan** [immersive-translate/immersive-translate#417]
### 插件版本号 | Version

0.4.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

![image](https://user-images.githubusercontent.com/59086082/235308629-763fee8e-08e1-4292-84a6-b955907761e8.png)

**Comment by theowenyoung** [comment]
这是特性，Github 默认只翻译 重要区域， 如果想翻译全部的话，可以点击 更多 -> 切换为翻译全部

**Comment by duoluodexiaoxiaoyuan** [comment]
> 这是特性，Github 默认只翻译 重要区域， 如果想翻译全部的话，可以点击 更多 -> 切换为翻译全部
![image](https://user-images.githubusercontent.com/59086082/235380707-c0ae3fbb-80f8-4ca3-a2eb-9e98473f0afb.png)
