### ISSUE TITLE
开启该插件会导致 Safari 启动速度变慢

### ISSUE THREAD

**Issue by xylagbx** [immersive-translate/immersive-translate#418]
## 插件版本号 | Version

0.4.2

## 平台 | Platform

macOS

## 浏览器 | Browsers

Safari

## 插件类型 | Extension Type

浏览器插件 | Browser Extension

## 更新或改进 | Update or Improvement

希望能对启动速度进行优化，目前开启该插件之后会导致 Safari 启动变慢。如果不启用插件，Safari 可以立即启动，但启用插件后需要大约 4 次图标跳动才能启动，希望大佬能优化一下，谢谢。

**Comment by theowenyoung** [comment]
更新到最新版本试试呢？ 我这好像没什么感觉..
