### ISSUE TITLE
Android Firefox 油猴脚本0.4.6无法显示悬浮球

### ISSUE THREAD

**Issue by ponyjoy** [immersive-translate/immersive-translate#420]
### 插件版本号 | Version

0.4.6

### 平台 | Platform

Android

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

Android Firefox 112.2加TamperMonkey 4 .18.1
使用
0.4.6版脚本，悬浮球无法显示，降级到0.4.4版又可以显示出来了。设置里已经开启了悬浮球

### 重现步骤 | To Reproduce

Android Firefox 112.2加TamperMonkey 4 .18.1
使用
0.4.6版脚本，悬浮球无法显示

### 补充说明 | Additional context

无

**Comment by hexone2086** [comment]
## 类似的问题
### 插件版本号 | Version

`0.4.6`
### 平台 | Platform

`PC Windows10`
### 浏览器 | Browsers

`Firefox 112.0.2`
### 插件类型 | Extension Type

`油猴 | Tampermonkey | Userscripts`
### 请描述这个 Bug | Describe the bug

`Win10 Firefox 112.0.2`   `TamperMonkey 4.18.1`

使用 0.4.6 版脚本，悬浮球无法显示，**降级到 0.4.4 版正常**。设置里已经开启了悬浮球

### 补充说明 | Additional context

无

**Comment by theowenyoung** [comment]
已确认，正在修复～

原因是 0.4.5中为了解决一些内容安全策略严格的网站样式无法注入的问题（比如： https://fosstodon.org/）， 引入了一个新的添加样式的API， GM.addElement, 但是似乎 firefox 里工作的不太好。

**Comment by theowenyoung** [comment]
0.4.7 已修复～ 请更新一下·

**Comment by hexone2086** [comment]
> 0.4.7 已修复～ 请更新一下・

非常感谢，该版本在 Firefox 中工作良好👍

**Comment by ponyjoy** [comment]
升级0.4.7后，无法显示悬浮球问题已经修复。非常感谢👏👏
