### ISSUE TITLE
0.4.6 懸浮球如果在頂層會造成跟懸浮球同高的按鈕失效

### ISSUE THREAD

**Issue by Lawlietr** [immersive-translate/immersive-translate#421]
### 插件版本号 | Version

0.4.6

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

懸浮球如果在頂層會造成跟懸浮球同高的按鈕失效
但如果位置是在兩側則沒有這個問題

**Comment by theowenyoung** [comment]
可以给一个示例网址吗？

**Comment by Lawlietr** [comment]
> 可以给一个示例网址吗？

所有網頁都會，沒有例外
以 github 舉例，當懸浮球在最上方時
github 的最右上角的通知，跟個人頭像那位置的三個按鈕都沒法按

**Comment by theowenyoung** [comment]
确认～ 下个版本修复。

**Comment by theowenyoung** [comment]
请更新到 0.4.12 版本～ 已修复
