### ISSUE TITLE
edge pc浏览器，右键里的菜单关不掉

### ISSUE THREAD

**Issue by Sui-Yun** [immersive-translate/immersive-translate#428]
### 插件版本号 | Version

0.4.8

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

“将翻译网页加入右键菜单项”这个开关关了，“ "isShowContextMenu": false”，但是右键菜单还是在😵

### 补充说明 | Additional context

BTW，edge商店的扩展版本0.4.4，太久没更新了。
我目前用的是GitHub下载的Chrome zip 0.4.8。
油猴脚本都0.4.12了，然后扩展会提示我更新。。。。。。
希望版本能同步一下~~~

**Comment by Sui-Yun** [comment]
> 确认～下个版本修复

v5.0.0 修复完毕😘感谢作者大大~

btw，edge扩展是不允许作用于edge://flags界面吗？

**Comment by theowenyoung** [comment]
> btw，edge扩展是不允许作用于edge://flags界面吗？

是的～

**Comment by Sui-Yun** [comment]
> > btw，edge扩展是不允许作用于edge://flags界面吗？
> 
> 是的～

好的，谢谢作者大大！！还有个问题，edge扩展商店是0.4.4版本，没更最新是上架审核中吗

**Comment by theowenyoung** [comment]
是的，edge商店最近审核有点慢，在审核的版本是 0.4.8 ，已经一周了还没过。
