### ISSUE TITLE
[feature request]有没有可能增加 kaggle 等网站的翻译支持

### ISSUE THREAD

**Issue by HaveF** [immersive-translate/immersive-translate#43]
据我所知目前 jupyter（数据科学中的典型工具） 类的网页似乎没有翻译工具能翻译的, 不管是 google、彩云、百度等等。

可能这一类的网页需要等渲染完毕了才能翻译，所以需要支持这些网站可能需要一个个适配，或者是适配一个大类？我不太懂。有没有可能获得支持？感谢！

https://github.com/guillaume-chevalier/seq2seq-signal-prediction/blob/master/seq2seq.ipynb
https://www.kaggle.com/code/carlolepelaars/understanding-the-metric-rmsle/notebook
https://observablehq.com/@observablehq/build-your-first-map-with-observable-plot

**Comment by theowenyoung** [comment]
这个是iframe，现在还不支持，稍后会支持～

**Comment by theowenyoung** [comment]
可以了，最新版本已支持～欢迎尝试。

**Comment by HaveF** [comment]
似乎没有区别？我打开方式不对？Version 0.2.24
第一个没反应，不知道是不是 github 浏览方式的原因
![image](https://user-images.githubusercontent.com/54462/215079503-a1f5aa9d-57fe-49fe-8469-ae5bba0fe7a0.png)

第二个中的内容似乎没变化？外侧是中文，内侧没变化？
![image](https://user-images.githubusercontent.com/54462/215079742-fa71fa2e-c5be-4b67-a0cd-707d95e77845.png)

第三个似乎也没变化？外侧是中文，内侧没变化？
![image](https://user-images.githubusercontent.com/54462/215079838-9627d092-7572-4e53-91a0-6cfe6c6d5e05.png)

**Comment by theowenyoung** [comment]
哦哦哦，最新版商店还在审核， 需要再等等，或者手动安装最新版..

**Comment by HaveF** [comment]
手动安装了下，感动到哭...三个站两个已经没问题了

只有这一个站还不行：
https://observablehq.com/@observablehq/build-your-first-map-with-observable-plot

这个站应该不是 iframe 的原因？

**Comment by HaveF** [comment]
you saved my life
