### ISSUE TITLE
 Material Design 官网正文不翻译

### ISSUE THREAD

**Issue by Ryan-dddong** [immersive-translate/immersive-translate#435]
### 插件版本号 | Version

0.4.8

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 请描述这个Bug | Describe the bug

https://m3.material.io/foundations/layout/applying-layout/compact

**Comment by versun** [comment]
试了下, 不大好搞, 主要节点都在shadow-root下, 后面看看大佬们怎么搞

**Comment by theowenyoung** [comment]
0.5.8 已支持所有 shadowroot的网站～
