### ISSUE TITLE
鼠标滑过翻译bug

### ISSUE THREAD

**Issue by forchannot** [immersive-translate/immersive-translate#436]
### 插件版本号 | Version

0.5.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

使用鼠标滑过翻译该功能，设置里面是alt键才会翻译，但实际会出现鼠标滑过了就翻译，无需点击alt。
且无法更改该设置，即无法更改快捷键，无法取消该功能。

### 重现步骤 | To Reproduce

录制了一段视频
https://user-images.githubusercontent.com/100580891/236505064-f36a0683-5ff9-40f7-a2eb-16b8ca43437f.mp4

**Comment by theowenyoung** [comment]
谢谢反馈，确认，油猴这里设置快捷键有问题～ 待会儿发个版本修复一下

**Comment by theowenyoung** [comment]
0.5.2 已修复～

**Comment by forchannot** [comment]
似乎依然还是有点问题，理想中的结果是每次滑过某个地方都需要按alt，实际上点按一次alt后所有地方滑过都会直接翻译，且无法直接取消当前翻译得刷新页面或者按两次翻译全文（alt a或者w），更改设置为不做任何事情也需要刷新页面才能生效
