### ISSUE TITLE
tradingview.com/script/  页面翻译没有排除代码块

### ISSUE THREAD

**Issue by sacrfaceeey** [immersive-translate/immersive-translate#437]
### 插件版本号 | Version

0.48

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

tradingview.com/script/  页面翻译没有排除代码块

**Comment by theowenyoung** [comment]
这个网址进去 好像没有看到有代码块？

**Comment by theowenyoung** [comment]
暂时关闭了哈～有更新请重新 open

**Comment by zhangweiii** [comment]
https://www.flenker.blog/hecto-chapter-3/

您好，这个页面中代码块中有部分英文被翻译了

<img width="728" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/31117497/4254f692-4d7f-430f-956d-0d574dd12f60">
