### ISSUE TITLE
能加入翻译结果显示背景色或样式并能让内容点击后可编辑 contenteditable="true" 嘛？

### ISSUE THREAD

**Issue by pendave** [immersive-translate/immersive-translate#438]
### 您希望的更新和改进是什么 | Update or Improve

很喜欢你们的这个插件，在我实际应用中，我想有这样的功能：
![image](https://user-images.githubusercontent.com/1331881/236594222-f1c7febb-bcfa-4bd1-a87b-916e3d435562.png)

给全部翻译成中文（目标语言）结果的<font> 里面加上这样的：
 contenteditable="true" style="width: 560px; background: rgb(195, 236, 191);"

目的是用背景色显示所有机翻出来的内容，发现不顺眼的机翻结果，可以点击进去翻译做人工校对。这样有时候我们保存页面为 PDF 的时候比如教程，就有很高效的校对结果了。

能否作为一个选项可以再你们这个插件里去勾选或者自定义编辑呢？这样会灵活很多，方便中高级用户哦！

谢谢！很需要这样的更新。

**Comment by theowenyoung** [comment]
【界面设置】->【译文样式】 应该是你想要的功能？

**Comment by duoluodexiaoxiaoyuan** [comment]
<img width="1328" alt="image" src="https://user-images.githubusercontent.com/59086082/236785226-8b37f1d6-2dea-41a5-a9e2-24e9cdeaa4f4.png">
这里可以进行设置
上面你说的保存为pdf是用的别的插件吗，你的这个思路很nice,但是好像网页不支持编辑。最近我一直想做一个生词本的功能，就是为了校验机翻的问题，你又给了我新的思路 @pendave

**Comment by pendave** [comment]
好的，高亮显示翻译结果只是我要的效果之一，我主要还是想编辑 - 手动更新翻译的结果。已经在 GPT 的辅助下写了 bookmarklet 这样我点一下就实现了我要的效果，而且会根据网页的背景颜色来用不同深浅的背景色显示。 @duoluodexiaoxiaoyuan
保存为 pdf 可以直接 Ctrl + P，或者先选亮图文区域再 Ctrl + P 来打印成 PDF。

**Comment by duoluodexiaoxiaoyuan** [comment]
> 

感谢解答的如此详细，这样确实可以解决对于一些论文类的或者书本类的保存这样以后确实会看。但是对于一些问答类的，保存为pdf就类似于收藏等于学会哈哈。不知道你一般保存的是那种网站。

**Comment by keyboard3** [comment]
此问题不再更新，暂时关闭此issue
