### ISSUE TITLE
希望可以编辑的当前网页中哪里不翻译

### ISSUE THREAD

**Issue by yyzhiqiu** [immersive-translate/immersive-translate#439]
### 您希望的更新和改进是什么 | Update or Improve

如题

**Comment by keyboard3** [comment]
pc 浏览器从0.5.3版本开始支持了快捷键+鼠标划过翻译

**Comment by theowenyoung** [comment]
> > pc 浏览器从0.5.3版本开始支持了快捷键+鼠标划过翻译
> 
> 你好，怎么关闭划词翻译呢，我在浏览自己github源码的时候，不小心鼠标滑过，就翻译了

默认是需要按下 alt 键才会激活鼠标滑过翻译。点击扩展图标，里面可以彻底关闭
