### ISSUE TITLE
功能请求：github搜索页优化

### ISSUE THREAD

**Issue by photkey** [immersive-translate/immersive-translate#44]
![Snipaste_2023-01-27_11-22-14](https://user-images.githubusercontent.com/60434581/215003193-a5e97fec-367d-412d-b89c-db99c9daaa28.png)
希望能把github搜索页的项目说明，如上图所示的红色部分 给翻译一下。

**Comment by theowenyoung** [comment]
可以了，Github 搜索结果页已经加了。规则应该自动更新了，再试一下～

多个api这个，有点过于增加复杂度了，我建议还是手动更换一下？或者可以手动在浏览器安装2个同样的插件，或者多个浏览器轮替使用？

**Comment by theowenyoung** [comment]
看了下我的：

> 本地适配规则已是最新: 2023/1/28 00:07:28

似乎你的规则没有更新到最新。

**Comment by theowenyoung** [comment]
我测试了一下商店版的应用，好像是ok的呀。规则我确认了，线上的是最新的。

<img width="1215" alt="Screenshot 2023-01-28 at 02 23 03" src="https://user-images.githubusercontent.com/62473795/215164908-fff2be1b-04df-4159-a70d-d01e3206b14d.png">


<img width="1219" alt="图片" src="https://user-images.githubusercontent.com/62473795/215164981-130fa349-591b-48f8-b613-789b47098b87.png">

**Comment by theowenyoung** [comment]
会不会是dark模式 ui不一样... 我试试 dark

**Comment by theowenyoung** [comment]
<img width="1219" alt="图片" src="https://user-images.githubusercontent.com/62473795/215165371-1b1bd4e2-d189-4508-90c1-7960955e6f76.png">

我这dark模式也是对的

**Comment by theowenyoung** [comment]
时间是一样的，看我上面那个截图，我用全新的浏览器 下载了商店版的应用，更新时间和你的是一样的。

**Comment by theowenyoung** [comment]
https://github.com/immersive-translate/immersive-translate/blob/16083c944c9589c6e9e0a127396b941267d617d2/docs/buildin_config.json#L478-L493

这里。

github 的 dark 方案似乎有很多个，我选的是默认的dark

**Comment by theowenyoung** [comment]
搜索结果是这个 selector : `     "div > span.search-match", `

**Comment by theowenyoung** [comment]
<https://github.com/settings/appearance>

看下你用的是哪套呢？

你图里那样搜索是没法搜到的。

可以运行一下：

`$("div > span.search-match")`

看看结果

**Comment by theowenyoung** [comment]
看起来你的这个页面真的和我的不一样。 我的似乎也是dark default。

你可以定位下那个元素，想我下图中这样，然后截图看看

<img width="1666" alt="图片" src="https://user-images.githubusercontent.com/62473795/215171670-763d99aa-3055-4fa8-a87c-3ce959f67b76.png">

**Comment by theowenyoung** [comment]
好的，我添加了一个 `"li.repo-list-item p"`, 2分钟后应该能生效，然后刷新一下 about 页面更新下规则再试试～

**Comment by theowenyoung** [comment]
嗯，可能有缓存，稍等一下再试试，明天再试也行～
