### ISSUE TITLE
pdf翻译，渲染了html语句

### ISSUE THREAD

**Issue by heheda123123** [immersive-translate/immersive-translate#442]
### 插件版本号 | Version

0.5.3

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

如图，这个应该处理一下只显示原文吧，这样不符合翻译预期，也有安全风险
![image](https://user-images.githubusercontent.com/97490782/236718022-39fad1dc-4023-45f6-8209-29ea2df5b6e0.png)

**Comment by keyboard3** [comment]
嗯 这种情况可以识别，用pre或者code标签渲染

**Comment by heheda123123** [comment]
[How_to_hack_like_a_pornstar.pdf](https://github.com/immersive-translate/immersive-translate/files/11418052/How_to_hack_like_a_pornstar.pdf)

**Comment by keyboard3** [comment]
新版已经针对译文内容做了处理，当然针对这种特殊html标签会丢失一些属性，参考左边原文
