### ISSUE TITLE
pdf翻译，如果是非标准大小的页面会错位

### ISSUE THREAD

**Issue by heheda123123** [immersive-translate/immersive-translate#443]
### 插件版本号 | Version

0.5.3

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

如图，因为这个pdf的单个页面不标准，本身比较小，变成了一行显示三页或者一页
![image](https://user-images.githubusercontent.com/97490782/236718215-4eed44a3-c238-41a4-9944-f6b25974b9b4.png)
只有放大到150%才会符合预期一行两页，是不是可以固定为一行两页，不然没法对照看
![image](https://user-images.githubusercontent.com/97490782/236718358-49e7fd0a-24ab-4e80-9f46-a8b912018aa9.png)

**Comment by keyboard3** [comment]
默认采用的是页宽来缩放，正常情况下就是一行两页，你试试手动按照页宽缩放看
