### ISSUE TITLE
pdf翻译，没有正确处理引用标记

### ISSUE THREAD

**Issue by heheda123123** [immersive-translate/immersive-translate#444]
### 插件版本号 | Version

0.5.3

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

如图，把引用标记显示为一个字母，引起整句出现格式错误
可以考虑去掉引用标记？或者也显示为原文那样的标记，而且和其他文本的格式分开处理？
这本书是 c++ crash course.pdf 需要测试的话可以留言发邮件
![image](https://user-images.githubusercontent.com/97490782/236718870-4c7c3aeb-8918-4eaf-8f65-2ff6b5b5d776.png)

**Comment by keyboard3** [comment]
这种情况大概率是原始Pdf提取出来的是特殊编码不显示的字符，这种情况可能需要借助更加专业的adobe的提取服务来处理

**Comment by heheda123123** [comment]
意思是这种属于特殊情况，得自己先把原pdf处理一遍是吧？

**Comment by keyboard3** [comment]
这种情况我发现许多pdf的个别字符都是特殊编码，个人怎么处理？找个工具转成字符正常的pdf吗

**Comment by heheda123123** [comment]
pdf和这个一样 https://github.com/immersive-translate/immersive-translate/issues/445#issuecomment-1537777050
