### ISSUE TITLE
pdf翻译，丢失了原pdf的部分非文本格式

### ISSUE THREAD

**Issue by heheda123123** [immersive-translate/immersive-translate#445]
### 插件版本号 | Version

0.5.3

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

如图，原文的横杠这种非文本的格式是不是可以保留
![image](https://user-images.githubusercontent.com/97490782/236719309-4042f781-37cd-4b05-b151-74fabe44baa5.png)

**Comment by keyboard3** [comment]
译文会对原始pdf的文本进行重排版，这种特殊符号如何正确的保留要思考下，目前如果保留还是只能绝对定位，但是译文结果比原文高度高的情况下，会造成覆盖

**Comment by theowenyoung** [comment]
最好能附上有问题的PDF，方便我们修复～ @heheda123123

**Comment by heheda123123** [comment]
[c++ crash course.pdf](https://github.com/immersive-translate/immersive-translate/files/11418044/c%2B%2B.crash.course.pdf)

**Comment by keyboard3** [comment]
这种线非纯文本，无法保留这种样式
