### ISSUE TITLE
pdf翻译，无序列表的格式丢失了

### ISSUE THREAD

**Issue by heheda123123** [immersive-translate/immersive-translate#446]
### 插件版本号 | Version

0.5.3

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

如图
![image](https://user-images.githubusercontent.com/97490782/236720657-32beb5ff-e841-4058-9c90-2712677ee5cb.png)
数字列表的格式就能正确处理，用一样的方式处理应该就可以
![image](https://user-images.githubusercontent.com/97490782/236720707-eb0ba223-c418-4072-b6e3-16ac96114ecb.png)

**Comment by keyboard3** [comment]
pdf和html不一样，没有无序列表和有序列表的概念，能够拿到的都是原始的零碎的绝对定位的文本片段，所以这里的独立成段落的逻辑不一样，能够处理，不过要正确的覆盖更多的文本排版场景，还需要更良好的设计，这个计划安排中

**Comment by heheda123123** [comment]
[C++ System Programming Cookbook Practical recipes for Linux system-level programming using the latest C++ features by Onorato Vaticone (z-lib.org).pdf](https://github.com/immersive-translate/immersive-translate/files/11418058/C%2B%2B.System.Programming.Cookbook.Practical.recipes.for.Linux.system-level.programming.using.the.latest.C%2B%2B.features.by.Onorato.Vaticone.z-lib.org.pdf)

**Comment by heheda123123** [comment]
这个问题还比较常见
[MOS-TOC.pdf](https://github.com/immersive-translate/immersive-translate/files/11443064/MOS-TOC.pdf)
![image](https://github.com/immersive-translate/immersive-translate/assets/97490782/f3840927-17a3-4c54-a69a-94561a3715b7)

**Comment by keyboard3** [comment]
下个版本会修复

**Comment by keyboard3** [comment]
> 这个问题还比较常见 [MOS-TOC.pdf](https://github.com/immersive-translate/immersive-translate/files/11443064/MOS-TOC.pdf) ![image](https://user-images.githubusercontent.com/97490782/237425179-f3840927-17a3-4c54-a69a-94561a3715b7.png)

0.6.19 这个问题已处理

**Comment by heheda123123** [comment]
段落的格式在这本书也出现了问题，最新版0.6.19
[c++ crash course.pdf](https://github.com/immersive-translate/immersive-translate/files/11861733/c%2B%2B.crash.course.pdf)
![Snipaste_2023-06-26_09-55-22](https://github.com/immersive-translate/immersive-translate/assets/97490782/51c0b9ef-5481-424c-97bf-6d77a1ac74e4)

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/aa4d3d8b-bad0-4bf8-b9b8-d38dfbbcee1d)
验证 已处理
