### ISSUE TITLE
雨见拓展商店是否可以收录您的拓展

### ISSUE THREAD

**Issue by Auj625197595** [immersive-translate/immersive-translate#45]
谷歌翻译退出中国后，您的翻译拓展确实给中国的翻译带来了一线生机。
我是雨见浏览器开发者，希望可以获得您的授权将该拓展收录到拓展商店

**Comment by Auj625197595** [comment]
![图片](https://user-images.githubusercontent.com/32589249/215015176-a22c7108-3ea3-4e8a-8372-9ac14ad386fd.png)

**Comment by theowenyoung** [comment]
谢谢，可以呀，需要我操作什么吗？

**Comment by Auj625197595** [comment]
得到您的许可就可以了，我会自动从火狐/edge拓展中心抓取。您无需操纵什么。再次感谢

**Comment by theowenyoung** [comment]
好的，多谢！
