### ISSUE TITLE
关于鼠标划过翻译说一下作为用户的体验

### ISSUE THREAD

**Issue by duoluodexiaoxiaoyuan** [immersive-translate/immersive-translate#450]
### 您希望的更新和改进是什么 | Update or Improve

因为使用过沙拉查词，我理解的划过翻译就是鼠标选择哪部分就应该翻译哪部分。但是显然没有达到这个效果。根据实际测试其实不划，把鼠标光标移动到要翻译的那一句话。因为用户其实要的是实现选中内容的翻译。(刚才注意到确实是写的也是翻译该段，但是还是想要可以翻译任何地方的内容)

mac电脑 正常我会理解为ctrl就是command键，经过测试其实是mac的control键。

另外就是存在有些地方还是翻译不了的内容，所以是否鼠标划来有一个区分的效果，让我知道鼠标划过翻译是否会触发。

<img width="781" alt="image" src="https://user-images.githubusercontent.com/59086082/236783189-b1f0b69e-21bb-4a22-9ec1-6e7ba44f6e8c.png">

**Comment by duoluodexiaoxiaoyuan** [comment]
刚才用的时候注意到了右侧的小loading了，刚开始可能不熟没注意到，还是希望增加以后鼠标经过来个类似沙拉查词小图标的这种选项，有时候用的时候分不清是快捷键冲突的问题还是别的问题导致的

**Comment by theowenyoung** [comment]
0.5.5版本已修复

**Comment by duoluodexiaoxiaoyuan** [comment]
> 0.5.5版本已修复

太强了大佬
