### ISSUE TITLE
您好，谷歌翻译选项勾选后，翻译没反应，不知是什么问题，以前好使

### ISSUE THREAD

**Issue by jxgm520** [immersive-translate/immersive-translate#451]
### 插件版本号 | Version

v0.5.3

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

您好，谷歌翻译选项勾选后，翻译没反应，不知是什么问题，以前好使，人在中国

**Comment by jxgm520** [comment]
又好使了，得刷新一下，不好意思了，能用了

**Comment by keyboard3** [comment]
那先关闭哈
