### ISSUE TITLE
SPA单页网站切换页面后会被重复翻译

### ISSUE THREAD

**Issue by icepole-jon** [immersive-translate/immersive-translate#452]
### 您希望的更新和改进是什么 | Update or Improve

能否给段落一个已经翻译的标记，避免重复翻译，
因为spa的网页会有缓存，页面开启翻译后，来回切换会导致重复翻译
<img width="814" alt="Snipaste_2023-05-09_13-44-21" src="https://user-images.githubusercontent.com/3428205/237004769-b8fddbdb-4650-4b00-b47f-d8bccb58744e.png">
😂

**Comment by theowenyoung** [comment]
请问是哪个版本？

**Comment by icepole-jon** [comment]
@theowenyoung  ``` V0.5.3 ```

**Comment by theowenyoung** [comment]
我这好像复现不了，是什么浏览器？扩展还是油猴？

**Comment by icepole-jon** [comment]
油猴脚本
![GIF](https://github.com/immersive-translate/immersive-translate/assets/3428205/f918dfda-ca7a-4849-82d3-f899eb236eca)

**Comment by theowenyoung** [comment]
奇怪，我这还是复现不了，有做什么特殊设置吗？ 可以看下开发者设置里面的userConfig?

**Comment by theowenyoung** [comment]
可以复现了，稍等我看下。

**Comment by theowenyoung** [comment]
0.5.4 已修复

**Comment by icepole-jon** [comment]
perfect! 👍
