### ISSUE TITLE
从5月9号开始，基于油猴脚本的X浏览器，via浏览器，所有的翻译都失效了。

### ISSUE THREAD

**Issue by BossDiablo** [immersive-translate/immersive-translate#453]
### 插件版本号 | Version

0.5.3

### 平台 | Platform

Android

### 浏览器 | Browsers

Other

### 请描述这个Bug | Describe the bug

原来版本对X浏览器完美支持必应翻译。从5月9号开始，基于油猴脚本的X浏览器，via浏览器，微软翻译都失效了。
刚开始是最新的0.5.3版本，失效。试着降低版本到0.4.2，0.4.3都是失效的，又试着换了浏览器，via浏览器还是失效的

**Comment by BossDiablo** [comment]
我查询油猴插件的提供网站，下面的评论有很多和我一样的情况，都是从5月9号开始的，另外我试了一下在相同的网络条件下，安卓的狐猴浏览器下用chrome插件的方式完全没有问题。因为X浏览器是Android下的主力浏览器，所以这个改变对我非常不方便，希望能够更新bug

**Comment by CookieNuts** [comment]
chrome扩展插件也是相同问题， 版本: 0.5.4, Chrome版本: 113.0.5672.92

**Comment by theowenyoung** [comment]
@CookieNuts Chrome插件是什么问题？所有翻译失效？

**Comment by theowenyoung** [comment]
@BossDiablo 这可能是 X 浏览器更新的问题？ 其他浏览器的油猴似乎没有问题

**Comment by BossDiablo** [comment]
我试过安装X浏览器之前的版本，还有via浏览器,都是一样的问题，应该不是x浏览器的问题.另外之前的沉浸式翻译，谷歌翻译也一直不好用，只有必应翻译好用，似乎是改名为微软翻译以后不好用的

**Comment by BossDiablo** [comment]
因为我也开发软件，所以你说的这些情况我都试过，比如更换X浏览器的之前版本，和X浏览器差不多内核的浏览器，比如via浏览器都是相同的问题.另外为了排除是网络环境的原因，我在同一个手机上安装了插件版的狐猴浏览器，完全没问题。应该是只有油猴版本的有问题。

**Comment by BossDiablo** [comment]
另外因为免费的只有谷歌翻译和微软翻译，我只试了这两个，其他的因为需要API，没有试

**Comment by theowenyoung** [comment]
X, via 浏览器似乎是内部会对 一些域名做拦截和过滤？比如之前的谷歌接口好像就会被拦截，

0.4.8 版本及之后的微软翻译更新为新的api接口，之前老的bing接口是网页版的爬虫接口，很不稳定，新版的接口用的是edge浏览器自带翻译的接口，更稳定。

我之前调试过x浏览器，我不知道如何从脚本这边做适配.. 似乎有些网络请求就是发不出去..

**Comment by BossDiablo** [comment]
以前的必应翻译在x浏览器非常完美运行，谷歌翻译不行，这都是在梯子运行环境下。我估计新版本必应翻译接口改了，我装回0.4.2版本，刚装的时候叫必应翻译，可运行一会儿也自动改成微软翻译，不能用了，版本号还是0.4.2，不知道怎么回事儿

**Comment by BossDiablo** [comment]
“0.4.8 版本及之后的微软翻译更新为新的api接口”
就在一分钟以前，我在X浏览器又安装了0.4.6版本，以必应翻译无限loading...，还是不能翻译，以前是完美运行的。
