### ISSUE TITLE
翻译本地PDF时日语总是识别成西班牙语且无法切换

### ISSUE THREAD

**Issue by qpwo111** [immersive-translate/immersive-translate#454]
### 插件版本号 | Version

0.4.8

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension, 油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

翻译本地PDF时日语总是识别成西班牙语且无法切换，再次选择日语并翻译最后还是识别成西班牙语

**Comment by theowenyoung** [comment]
试下最新的0.5.4呢？

**Comment by keyboard3** [comment]
请试下最新的版本，或者提供有效的pdf让我们验证
