### ISSUE TITLE
点击 alt 触发自动翻译

### ISSUE THREAD

**Issue by Ares-Chang** [immersive-translate/immersive-translate#455]
### 插件版本号 | Version

0.5.4

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

插件在十分钟前自动更新了适配规则，我再使用点击 alt 或都在网页中待一会，会触发自动翻译。
![image](https://github.com/immersive-translate/immersive-translate/assets/36911513/d800ca9a-97fa-4c5b-be5c-e3f3e2c32bb1)
![image](https://github.com/immersive-translate/immersive-translate/assets/36911513/c5afad62-906f-423a-8c2c-70550bcc436d)

### 重现步骤 | To Reproduce

1. 打开英文网页
2. 点击 alt 或静默一会，(本地项目热更新也会触发)

**Comment by theowenyoung** [comment]
可以在这里关闭这个新功能：

<img width="291" alt="截圖 2023-05-10 16 38 17" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/02711905-4b21-42dd-bb17-54cd4f700071">

**Comment by Ares-Chang** [comment]
感谢解答

**Comment by theowenyoung** [comment]
以后的版本还是默认关闭吧。感谢反馈～
