### ISSUE TITLE
Openai baseurl配置

### ISSUE THREAD

**Issue by Lix1993** [immersive-translate/immersive-translate#460]
### 您希望的更新和改进是什么 | Update or Improve

希望可以自己配置openai的url，这样可以用一些速度更快的api

**Comment by versun** [comment]
@Lix1993  可以自己改下哈:
插件设置->开发者设置->Edit Full User Config
给openai加个apiUrl即可:
 "openai": {
      "apiUrl":"https://yourdomain.com",
      "APIKEY": "11111"
    }
