### ISSUE TITLE
Read local e-book 与 Calibre 冲突

### ISSUE THREAD

**Issue by 0gif** [immersive-translate/immersive-translate#461]
### 插件版本号 | Version

0.5.5

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari, Other

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

使用 Read local e-book 功能的同时, 如果对 Calibre 打开的电子书进行标注操作, 浏览器电子书的阅读页面就会定格, 具体表现是不能前后翻页, 可以打开目录, 但不能进行目录跳转

### 重现步骤 | To Reproduce

1. 打开 Brave/Safari 浏览器, 新开一个 tab
2. 点开插件选 Read local e-book, 拖入一本电子书 (epub)
3. Calibre 也打开一本电子书
4. 对 Calibre 的电子书进行标注操作
5. Brave/Safari 电子书阅读页面定格, 具体表现是不能前后翻页, 可以打开目录, 但不能进行目录跳转

**Comment by theowenyoung** [comment]
抱歉很晚才回复，请问现在还有这个问题吗？

理论上两者之间不会有任何关系的。
