### ISSUE TITLE
如何导出带有译文的PDF

### ISSUE THREAD

**Issue by gitTreeYoung** [immersive-translate/immersive-translate#462]
### 您希望的更新和改进是什么 | Update or Improve

希望可以导出带有译文的PDF，目前翻译后导出只有原文，没有译文。
I hope you can export the PDF with the translation, currently only the original text is exported after translation, there is no translation.

**Comment by Chenm4** [comment]
同求一个这个功能，很需要，并且想问问有没有曲线救国实现的方式

**Comment by FattySpring** [comment]
0.7.9 已支持PDF双语导出

**Comment by FattySpring** [comment]
0.7.9 已支持PDF双语导出
