### ISSUE TITLE
本地PDF翻译在更新后大量变为逐行翻译

### ISSUE THREAD

**Issue by aer12138** [immersive-translate/immersive-translate#467]
### 插件版本号 | Version

0.5.5

### 请描述这个Bug | Describe the bug

原本可以整段翻译的文档现在只能逐行翻译了，与文档的行间距有关，只要是超过单倍行距就会变成逐行翻译

**Comment by theowenyoung** [comment]
可以上传一下示例的pdf文件吗？

我们现在确实是按照间距来判断是否一段的，之前的比较松一点，现在可能更严格了一点. 这个可能需要提供一个选项出来，用户可以自定义间距好一点。

**Comment by aer12138** [comment]
您好，邮件已收到，谢谢。

**Comment by invisprints** [comment]
https://arxiv.org/pdf/2004.09666.pdf

全都是逐行翻译😂，希望能改进！
![image](https://github.com/immersive-translate/immersive-translate/assets/15833553/72d8c8ba-c02d-4d88-aee0-83d70bfc37e3)

**Comment by keyboard3** [comment]
0.8.8 已支持在快捷控制样式按钮上通过调整行间距来重新识别段落

**Comment by aer12138** [comment]
您好，邮件已收到，谢谢。
