### ISSUE TITLE
关于颜色的建议

### ISSUE THREAD

**Issue by HaveF** [immersive-translate/immersive-translate#47]
对于双语阅读，建议增加个颜色选项【毕竟字变多了】，有助于跳看或捡着看（需要才回去细读英文）

如下是我的经验（用的是另外一个油猴脚本）：

![image](https://user-images.githubusercontent.com/54462/215128853-76ee5380-c3bd-4599-82e0-8d0606827f1f.png)

**Comment by theowenyoung** [comment]
现在有一个高亮的样式可以满足吗？

<img width="882" alt="Screenshot 2023-01-28 at 00 32 44" src="https://user-images.githubusercontent.com/62473795/215141171-0d03493f-c292-4fa0-b511-39267b4235c2.png">


也许可以新增一个有颜色的样式。你有推荐的颜色吗，同时适合light 和dark的。

**Comment by HaveF** [comment]
居然有这个选项！我都没仔细看！amazing！
那就非常够用了

同时适合light 和dark的可是个大学问...
当然可以有其他方式实现...你的源码要是 react 的话，[可以考虑先检测 prefers-color-scheme](https://www.kindacode.com/article/react-check-if-user-device-is-in-dark-mode-light-mode/), 再适配个颜色就行
不过我觉得现在就非常够用了，不用再扣这些细节了？

建议把 Translation display style 选项的默认配置从 None 改为其他任何一种样式？（除了高亮，高亮在黑色背景下太刺眼了）

这样用户就知道这个选项了，就会自己去探索选项了？你觉的怎样？

**Comment by HaveF** [comment]
BTW, 感觉你这个双语翻译还是有点厉害的，感觉有很多可以做的（可以考虑以后翻译功能更完善之后出一个 pro 版本 😆），脑洞了一下功能，逻辑是：

双语的人对两个语言有同时存在的需求，也就是说，除了阅读外，他有“学习语言的需求”
那么，可以增加标记“不熟悉的”单词或句子功能【生词本/生句本】
且因为你已经缓存了翻译对照内容
那么就完全可以把标记后的“不熟悉的”语料变成抽认卡来满足“学习语言的需求“....

甚至对于标记的单词，如果在新文章中出现，可以再次标记，方便用户回顾掌握等等等等
