### ISSUE TITLE
油猴版找不到翻译页面

### ISSUE THREAD

**Issue by hooplee5** [immersive-translate/immersive-translate#470]
### 插件版本号 | Version

0.5.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

浏览器：Chromium 83.0.4089.0（开发者内部版本） （32 位）
找不到翻译按钮，鼠标右键也没有。油猴里显示运行正常

**Comment by theowenyoung** [comment]
浏览器可以似乎有点旧？ 可以更新一下吗？或者有没有试过扩展版本是否可以使用？

**Comment by hooplee5** [comment]
it指定的不能更新。请问扩展版在哪啊

**Comment by theowenyoung** [comment]
https://chrome.google.com/webstore/detail/immersive-translate/bpoadfkcbjbfhfodiogcnhhhpibjhbnh
