### ISSUE TITLE
支持OpenAI和Azure的text-davinci-003

### ISSUE THREAD

**Issue by limfoo** [immersive-translate/immersive-translate#472]
### 您希望的更新和改进是什么 | Update or Improve

支持text-davinci-003模型，理由: text-davinci-003对于翻译来说更优秀。

**Comment by theowenyoung** [comment]
当前就是支持的，在模型里填写自定义模型 `text-davinci-003` 即可。

openai 是ok的， azure我还没测试过.

**Comment by limfoo** [comment]
嗯 Azure应该是有问题的，报错"400: Unsupported data type"。
