### ISSUE TITLE
悬浮球无法移动到浏览器底部

### ISSUE THREAD

**Issue by QuantumRoseinAmethystVase** [immersive-translate/immersive-translate#475]
### 插件版本号 | Version

0.5.5

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

今天悬浮球移动范围突然出现了下限，如下图，在此位置以下都不能移动，之前一直可以放在底部。我尝试重新安装脚本、Tampermonkey，重置油猴设置都无法恢复到以前的情况。

<img width="1527" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62452364/af6571c6-e9d0-4ae0-ab82-4f5b91065b71">

### 重现步骤 | To Reproduce

1.设置中打开显示悬浮球
打开任意网站，如 https://www.baidu.com

**Comment by keyboard3** [comment]
试着更新下油猴脚本，可以拖动的
