### ISSUE TITLE
【Medium】与medium的文章编辑功能协同出现问题

### ISSUE THREAD

**Issue by realmusicyuan** [immersive-translate/immersive-translate#476]
### 插件版本号 | Version

0.5.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/34225159/353b29f2-b658-4c94-8705-50982c48181d)
如上图所示，在已经完成翻译的情况下，如果在medium网站上使用文章的高亮/标注等功能，翻译的内容会自动置顶到你所编辑的文字之后；然后更严重的是，后续的所有布局其实都是错位的，已经无法选中到正确的文字。

### 重现步骤 | To Reproduce

1. 进入medium网站，并进入任意一篇文章的页面
2. 使用“沉浸翻译”对文章进行翻译（目前一切正常）
![image](https://github.com/immersive-translate/immersive-translate/assets/34225159/823afad9-16bb-45a9-8875-2d91b6f12762)
3. 使用medium的对单词高亮功能后，翻译的部分会自动置顶在高亮单词之后（如图我这里高亮的是“the other day”这个短语）
![image](https://github.com/immersive-translate/immersive-translate/assets/34225159/b0b6c69c-47b4-4c45-8b33-24b5171ee306)
4.后续所有的选中单词都是错位的（我怀疑是翻译的布局在第3步已经导致错落）

**Comment by theowenyoung** [comment]
确认～ 感谢反馈

**Comment by theowenyoung** [comment]
这个似乎无法解决... 网站本身的问题。

**Comment by keyboard3** [comment]
已修复 刷新下页面即可

**Comment by theowenyoung** [comment]
团队再次调试了该问题，发现无法解决，经测试其他同类插件也有类似的问题。

原因是原网站在实现高亮的时候重新动态计算了位置，强制插入到译文节点后方，我们没法干涉此行为。

目前只能关闭该issue.
