### ISSUE TITLE
为什么无法翻译谷歌扩展应用商店的页面呢？https://chrome.google.com/webstore/detail/youtube-dual-subtitles/hkbdddpiemdeibjoknnofflfgbgnebcm?hl=en-US　

### ISSUE THREAD

**Issue by ningshunqiang** [immersive-translate/immersive-translate#477]
### 插件版本号 | Version

0.5.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

无法翻译：　https://chrome.google.com/webstore/detail/youtube-dual-subtitles/hkbdddpiemdeibjoknnofflfgbgnebcm?hl=en-US

**Comment by theowenyoung** [comment]
特权页面，插件无法访问。

一个办法是：可以用firefox浏览器访问谷歌浏览器的特权页面。
