### ISSUE TITLE
无法在safari浏览器中启用

### ISSUE THREAD

**Issue by ziilee** [immersive-translate/immersive-translate#478]
### 插件版本号 | Version

0.5.5

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

无法触发翻译功能，无法进入preferences页面。

### 重现步骤 | To Reproduce

1.可以从applestore中安装。
2.可以在safari设置中enable启用。
3.在打开网页后，无法触发翻译功能，显示白色区域，如图。
![image](https://github.com/immersive-translate/immersive-translate/assets/120491334/7cc39215-b3ee-4829-b9d7-5b7563376d2a)

4.无法打开Preferences页面，Options页面显示空白，如图。
![image](https://github.com/immersive-translate/immersive-translate/assets/120491334/731f73a3-7d45-4121-90b9-3f168901cf8e)

5.整体完全无法使用，卸载重装等多次操作都无法解决该问题。
macOS版本11.5.2

**Comment by keyboard3** [comment]
应该是macOS低版本兼容问题，有许多小伙伴也是这个操作系统版本，不过他们重启浏览器似乎都解决了

**Comment by ziilee** [comment]
> 应该是macOS低版本兼容问题，有许多小伙伴也是这个操作系统版本，不过他们重启浏览器似乎都解决了

也重启了浏览器，重启电脑，重新安装，遇到的几乎是同一个问题，反倒是中间切换过ip地址后，打开preference时，页面曾出现过loading字样，其他情况时，打开preference页面，都是一篇空白，刷新什么的，都无效，应该算是严重BUG了。

**Comment by theowenyoung** [comment]
应该是兼容问题。（但是我没有11.5的系统来测试..

我的版本是13.x
