### ISSUE TITLE
增加“是否翻译字幕”按钮

### ISSUE THREAD

**Issue by JimWho** [immersive-translate/immersive-translate#479]
### 您希望的更新和改进是什么 | Update or Improve

由于已经有其他字幕翻译扩展，这样会导致字幕被翻译两次，并且翻译字幕存在延迟，影响观看体验
能否增加“是否翻译字幕”按钮，来排除和字幕翻译扩展造成的问题

**Comment by theowenyoung** [comment]
嗯～ 可以的。这里可以有一个单独的开关。

**Comment by yenuoGithub** [comment]
同意，如果可以专门优化一下字幕翻译（有的时候换行翻译看起来不连贯）

**Comment by theowenyoung** [comment]
已支持，【进阶设置】里。
