### ISSUE TITLE
PDF翻译依然存在部分遮盖

### ISSUE THREAD

**Issue by hai178912522** [immersive-translate/immersive-translate#481]
### 插件版本号 | Version

0.5.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![8a55627a4d2a96f7d606c8085e32699](https://github.com/immersive-translate/immersive-translate/assets/59815858/df3bdbb7-777e-42f2-8580-8c681bef643d)

**Comment by keyboard3** [comment]
附件图片不对题啊，另外Pdf最佳体验建议firefox上打开
