### ISSUE TITLE
这个网页的正文部分不生效

### ISSUE THREAD

**Issue by 1762757171** [immersive-translate/immersive-translate#483]
### 插件版本号 | Version

0.5.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

https://www.braynzarsoft.net/viewtutorial/q16390-03-initializing-directx-12
这个网址的正文部分翻译不生效。

### 重现步骤 | To Reproduce

1. 进入网址 https://www.braynzarsoft.net/viewtutorial/q16390-03-initializing-directx-12
2. 右键-翻译网页

**Comment by 1762757171** [comment]
但利用「当鼠标滑过」功能却可以生效

**Comment by versun** [comment]
这个网页写的不是很标准哈，有点乱，我这边只修复了正文翻译，多段落一起翻译的问题不好解决哈
