### ISSUE TITLE
每秒最大请求数不能调更低吗？

### ISSUE THREAD

**Issue by amstc** [immersive-translate/immersive-translate#484]
### 您希望的更新和改进是什么 | Update or Improve

openai免费api只给每分钟3次，设置里最低只能设置1秒1次，设小数不起作用。有没有办法设置更低的频率？在官网的截图里，看到以前版本里是“Max requests per minute”，现在变“Max requests per second”了
![1](https://github.com/immersive-translate/immersive-translate/assets/58633843/c5f1ff00-192f-4a93-9370-bc6b556d6fb4)
![2](https://github.com/immersive-translate/immersive-translate/assets/58633843/f7e0da70-3976-4fd6-88c3-7f02008e7c0d)

**Comment by hibichann** [comment]
一分钟三次那还能用么。。

**Comment by theowenyoung** [comment]
每分钟3次对于网页翻译确实太少了...   https://immersive-translate.owenyoung.com/services/openai

不太建议在沉浸式中使用试用版 api.

**Comment by amstc** [comment]
> 每分钟3次对于网页翻译确实太少了... https://immersive-translate.owenyoung.com/services/openai
> 
> 不太建议在沉浸式中使用试用版 api.

把“每次请求最大文本长度”和“每次请求最大段落数”调高，再把“开启翻译网页标题”关掉（会消耗一次次数），还是能在3次内应付完大部分网页的。其实这两个参数本是越大越好，每次提交的内容越多，前后文联想越强，翻译越准。目前“每次请求最大文本长度”这个参数有bug，不能调太大，如果调到四五千，在F12里面能看到收到了返回数据包，但网页还是转圈。

当然每分钟3次也确实难达实用标准，但聊胜于无，只是希望官方能改回v0.4.8之前按分钟设置的功能。

**Comment by theowenyoung** [comment]
还有一种变通办法, 就是在开发者设置里直接修改配置：

```json
  {
"translationServices": {
    "openai": {
      "interval": 60000,
      "limit": 3
    }
  }
}
```

这种方式可以把秒变成分钟。
