### ISSUE TITLE
China Daily部分区域无法翻译

### ISSUE THREAD

**Issue by Chenyigit** [immersive-translate/immersive-translate#485]
### 插件版本号 | Version

0.5.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

尊敬的开发者，部分区域本插件无法翻译, 但使用腾讯翻译插件可以进行翻译
这是本插件的效果
![QQ截图20230523003714](https://github.com/immersive-translate/immersive-translate/assets/72935252/da37f7f4-fbfe-45e5-b2e2-87397d13b3bc)
这是腾讯翻译的
![QQ截图20230523003739](https://github.com/immersive-translate/immersive-translate/assets/72935252/66788933-3404-48fa-832e-10f93c9866b1)

**Comment by theowenyoung** [comment]
Sorry, 之前看错了， safari上确实好像被内容安全策略限制了. 看看有没有办法绕过..
