### ISSUE TITLE
特定网站自定义「译文显示样式」不起效

### ISSUE THREAD

**Issue by SunBK201** [immersive-translate/immersive-translate#486]
### 插件版本号 | Version

0.5.6

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug
问题网站：https://developer.apple.com/documentation/safariservices/
问题：自定义「译文显示样式」不起效
浏览器：Safari 16.4
控制台报错：Refused to apply a stylesheet because its hash, its nonce, or 'unsafe-inline' appears in neither the style-src directive nor the default-src directive of the Content Security Policy.

**Comment by versun** [comment]
duplicate https://github.com/immersive-translate/immersive-translate/issues/212#issuecomment-1549517223

**Comment by theowenyoung** [comment]
下个版本将会修复。

**Comment by SunBK201** [comment]
v0.5.8 依然存在此问题

**Comment by theowenyoung** [comment]
Sorry, 之前看错了， safari上确实好像被内容安全策略限制了. 看看有没有办法绕过..

**Comment by keyboard3** [comment]
> v0.5.8 依然存在此问题

没有办法绕过，safari针对内容安全策略没有显示声明style-src: 'unsafe-inline'，我们都没办法插入样式
