### ISSUE TITLE
能否增加对多个Deppl API密钥的支持？

### ISSUE THREAD

**Issue by Root-FTW** [immersive-translate/immersive-translate#488]
### 您希望的更新和改进是什么 | Update or Improve

能否增加对多个Deppl API密钥的支持？

我创建了5个免费的deepl账户，我想添加所有5个API密钥，这样当一个密钥用完时，就会自动使用下一个密钥，这可能吗？

### 补充说明 | Additional context

Can you add support for multiple Deppl API keys?

I created 5 free deepl accounts, I want to add the 5 API keys so when one runs out of use automatically use the next key, is it possible?

**Comment by hibichann** [comment]
#198 已经有相关issue了

**Comment by theowenyoung** [comment]
0.5.7 已支持。 用逗号分开即可。
