### ISSUE TITLE
在 "翻译显示风格 "部分，你可以添加一个名为 "替换 "的风格？

### ISSUE THREAD

**Issue by Root-FTW** [immersive-translate/immersive-translate#489]
### 您希望的更新和改进是什么 | Update or Improve

在 "翻译显示风格 "部分，你可以添加一个名为 "替换 "的风格？

我想要一种风格，当我翻译一些东西时，它会自动用翻译后的内容替换，就像官方的Deepl插件那样，这样我就不会同时出现两种文本。

### 补充说明 | Additional context

In the "Translation display style" section can you add a style called "Replacement"?

I would like a style that when translating something automatically replaces the content with the translated one, like the official Deepl plugin does, so as not to have both texts at the same time.

**Comment by versun** [comment]
会做这个功能的哈，关注更新

**Comment by versun** [comment]
0.5.7版本已添加该功能, 火狐浏览器已上架更新, 其他平台的还在审核
点击[更多] -> [切换为仅显示译文]
