### ISSUE TITLE
开发者你好，facebook遇到个BUG。

### ISSUE THREAD

**Issue by luzhenhua** [immersive-translate/immersive-translate#49]
使用脚本在facebook展开折叠内容时帖子会消失，就像点了X一样。
我使用的是浏览器是Cent Browser 5.0.1002.295
Tampermonkey版本4.18.1，昨天使用扩展也是如此。

**Comment by luzhenhua** [comment]
https://imgloc.com/i/j35bF
这是我截的gif，点击展开后帖子会消失。
展开评论也是如此。

**Comment by theowenyoung** [comment]
好的，感谢反馈，我看看～

**Comment by theowenyoung** [comment]
facebook 看起来不好搞，试了下别的同类插件，也是类似问题。

它的网页不允许别人修改，别人一修改它就报错..

**Comment by theowenyoung** [comment]
刚发布的最新版本 解决了消失的问题，但是样式有点不好看。 只能先将就用着。facebook的网站有点恶心。。

**Comment by luzhenhua** [comment]
> 刚发布的最新版本 解决了消失的问题，但是样式有点不好看。 只能先将就用着。facebook的网站有点恶心。。

感谢修复。
我刚想来说好像变正常了。
