### ISSUE TITLE
导致我的vue项目出错 

### ISSUE THREAD

**Issue by zhang-wei-jian** [immersive-translate/immersive-translate#491]
### 插件版本号 | Version

0.55

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome, Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

是vue项目开发的时候会报错vue运行时错误和警告可能是vue内部错误，我排查了两天时间才知道是这个插件导致的。但是修复不修复无所谓，确实是少见的问题。但是我估计如果有类似的项目也一样会报错的。项目是这个你可以打开预览项目进入去试

### 重现步骤 | To Reproduce

只要执行就报错代码运行浏览器答应报错，页面显示不出来。他是table表格的地方比如权限管理的里面有和首页table

### 补充说明 | Additional context

是vue3项目3.2

**Comment by zhang-wei-jian** [comment]
https://github.com/pure-admin/vue-pure-admin  可以去预览项目并且运行了翻译插件。项目的几个使用table的页面会报错

**Comment by hibichann** [comment]
@theowenyoung https://stackoverflow.com/questions/72494154/a-listener-indicated-an-asynchronous-response-by-returning-true-but-the-messag

**Comment by keyboard3** [comment]
0.5.7 版本的双语翻译 已经修复这类基于虚拟dom的前端框架的网页报错

**Comment by theowenyoung** [comment]
@hibichann 可以更新到最新版 0.5.8 试试吗？ 看看问题解决了没～

**Comment by hibichann** [comment]
@theowenyoung 可以了

**Comment by hibichann** [comment]
![ZL2RT50T@ RHGM$(F{3R8F](https://github.com/immersive-translate/immersive-translate/assets/17671678/11cfb8ab-a12d-4edf-a1b6-9b9954228514)

**Comment by theowenyoung** [comment]
没法复现啊，我怀疑不是沉浸式的报错？..

也许隐私模式，只开启沉浸式试试？

**Comment by hibichann** [comment]
@theowenyoung 可能吧，主要我这里也不能稳定复现，又试了下无痕和正常模式都没报

**Comment by hibichann** [comment]
@theowenyoung 关了吧，应该是其他插件原因，应该是哪个小钱包或者deepl的划词翻译插件导致的，有几条黄的警告指过去，还有很多cookie和同源的错误，但是无痕模式只开沉浸式控制台一直很干净
![F75D{%{O`99(%_NS(Z0E4N9](https://github.com/immersive-translate/immersive-translate/assets/17671678/107daeed-9a81-44ec-b356-cd59c92c0bb6)
![~VJI05_%28N HP2R$KG{R93](https://github.com/immersive-translate/immersive-translate/assets/17671678/aa8dee7e-4b37-4d4c-b7c7-874a8a75942a)
