### ISSUE TITLE
chrome应用商店的后续会上架最新版本吗

### ISSUE THREAD

**Issue by 505Games-oss** [immersive-translate/immersive-translate#493]
### 您希望的更新和改进是什么 | Update or Improve

我看了一下chrome应用商店的版本是0.5.5，请问作者后续会把新的0.5.7版本上架到chrome应用商店吗，因为今天我从github下载0.5.7安装包安装后使用火绒清理的时候会把本插件当作缓存一同清理掉。

**Comment by versun** [comment]
会，chrome审核比较慢，firefox审核最快，目前已上架
