### ISSUE TITLE
对Wiki的翻译存在翻译信息缺失

### ISSUE THREAD

**Issue by ifp1090** [immersive-translate/immersive-translate#495]
### 您希望的更新和改进是什么 | Update or Improve

我实验了一下沉浸式翻译和彩云翻译对同一个页面的翻译效果，发现沉浸式翻译对于页面内容存在翻译信息的缺失现象。具体如下：

网页：[[Wiki-Cluster sampling](https://en.wikipedia.org/wiki/Cluster_sampling)](https://en.wikipedia.org/wiki/Cluster_sampling)

沉浸式翻译截图：

![image-20230526110548712](https://pbox.online/202305261105760.png)

彩云翻译截图：

![image-20230526110623636](https://pbox.online/202305261106664.png)

我们看到，相同的页面，彩云翻译将左边的目录、正文的标题都进行了翻译，但沉浸式翻译未能同步翻译：

![image-20230526110937674](https://pbox.online/202305261109894.png)

以上，希望能改进，谢谢！

**Comment by theowenyoung** [comment]
感谢。

这里是默认的设置里，段落有最小单词限制，3个，我刚加了规则，现在维基百科不再限制字符，通通都翻～
