### ISSUE TITLE
[Bug]: 鼠标悬停翻译时，部分翻译丢失超链接。

### ISSUE THREAD

**Issue by xwlops** [immersive-translate/immersive-translate#496]
### 插件版本号 | Version

0.5.8

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

鼠标悬停翻译时，部分翻译丢失超链接。

### 重现步骤 | To Reproduce

![](https://www.helloimg.com/images/2023/05/26/oJdmIr.gif)

### 补充说明 | Additional context

好像不是必现的，暂时还没有发现规律。

**Comment by theowenyoung** [comment]
你用的是仅显示译文吗？还是双语翻译？

**Comment by xwlops** [comment]
仅显示译文

**Comment by xwlops** [comment]
> 你用的是仅显示译文吗？还是双语翻译？


仅显示译文

**Comment by theowenyoung** [comment]
那这是正常的，因为用的是纯文本翻译整个段落，丢失链接是预期行为，等后面会支持富文本翻译就好了～
