### ISSUE TITLE
README.md 英文介绍

### ISSUE THREAD

**Issue by Zeng95** [immersive-translate/immersive-translate#497]
### 您希望的更新和改进是什么 | Update or Improve

能够提供 README.md 英文版的介绍，可以让全世界的用户都了解到这款插件。

### 补充说明 | Additional context

如果作者没有时间，我愿意帮忙完成

**Comment by theowenyoung** [comment]
现在有一个简单的版本：

https://github.com/immersive-translate/immersive-translate/blob/main/README_english.md

欢迎编辑 :)
