### ISSUE TITLE
[Bug]: 翻译英文Pdf产生的中文乱码

### ISSUE THREAD

**Issue by zhuhongchao** [immersive-translate/immersive-translate#499]
### 插件版本号 | Version

0.5.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

翻译英文Pdf产生的中文乱码

### 重现步骤 | To Reproduce

1. 下载pdf   https://sun6-21.userapi.com/c235131/u448173336/docs/d37/e0af371d0c46/Model_Engineers_39_Workshop__June_2023.pdf?extra=p8JIIb3_lCcTFcPGCc2itQEMwGSozUO8tnZ7TD1wAiIIYF5YWc4xOXOGMTZWOFiV1eO_XhDiYtCcDWnyPFo7VocoxCuN13GiJTOzVhw0SYjWiyBKJIENlZnPYo9WI5EbdpmHmhCNRLGzfUI
2. 打开pdf，翻译，乱码。

### 补充说明 | Additional context

无

**Comment by keyboard3** [comment]
该文件访问已失效，麻烦提供下有效链接
