### ISSUE TITLE
可否设置对某些网站自动应用翻译，比如推特网站

### ISSUE THREAD

**Issue by zhahuya** [immersive-translate/immersive-translate#5]
无需再去点击确认。

**Comment by theowenyoung** [comment]
你可以在设置里，添加 twitter.com 到 always 翻译这些网站。

**Comment by theowenyoung** [comment]
或者打开推特，然后在浏览器扩展图标那，选择alwasy翻译该网站：

<img width="340" alt="image" src="https://user-images.githubusercontent.com/62473795/201957470-ce403555-2071-4972-817e-9032a6c00da9.png">

**Comment by zhahuya** [comment]
> 或者打开推特，然后在浏览器扩展图标那，选择alwasy翻译该网站：
> 
> <img alt="image" width="340" src="https://user-images.githubusercontent.com/62473795/201957470-ce403555-2071-4972-817e-9032a6c00da9.png">

谢谢。我使用的是安卓-狐猴浏览器，有点类似kiwi浏览器，可以安装插件。
我更新了最新的0.0.26版本，但似乎没有发现设置always的选项。🤔

**Comment by theowenyoung** [comment]
那就进入插件设置页面就能看到 添加always翻译的网站的 按钮，大概在这个位置，你检查下看看～

<img width="1304" alt="截屏2022-11-16 00 36 40" src="https://user-images.githubusercontent.com/62473795/201975529-53bc86a5-b7c6-41bc-af0e-0c53aba4daec.png">

**Comment by theowenyoung** [comment]
https://github.com/immersive-translate/immersive-translate/releases/tag/v0.0.28

已支持移动版添加always翻译。
