### ISSUE TITLE
deepL 翻译显示403

### ISSUE THREAD

**Issue by al123xiaaaa** [immersive-translate/immersive-translate#50]
已填写正确的key，在 [https://www.deepl.com/docs-api/simulator/](https://www.deepl.com/docs-api/simulator/) 用那个key测试通过，但是用插件翻译时出现红色感叹号，显示403

**Comment by theowenyoung** [comment]
我这测试是可以的呀，你的是free api key 还是 pro的？ 任何网页都不行吗

**Comment by Ken-UCD** [comment]
遇到了同样的问题，经测试当js是外部加载的就不行（AdGuard/Surge），浏览器内加载就可以，有可能是DeepL判定了useragent

**Comment by theowenyoung** [comment]
js是外部加载的就不行？ 可以具体描述下吗？我没太懂，确实有几位用户反馈deepl有问题，但是我没能复现, 可以提供个网址吗？

**Comment by al123xiaaaa** [comment]
> 我这测试是可以的呀，你的是free api key 还是 pro的？ 任何网页都不行吗

<img width="553" alt="Snipaste_2023-01-30_23-07-58" src="https://user-images.githubusercontent.com/6868760/215515688-9ffe90af-725f-4b65-bdc1-f9077ca52281.png">
用的free api key，任何网页都不行

**Comment by theowenyoung** [comment]
你的key式这样的吗？  

`xxxxxx-xxxxx:fx`

后面有个:fx

**Comment by Ken-UCD** [comment]
> js是外部加载的就不行？ 可以具体描述下吗？我没太懂，确实有几位用户反馈deepl有问题，但是我没能复现, 可以提供个网址吗？
> […](#)

就是没有采用油猴这种浏览器插件的形式加载JS，而是通过AdGuard在系统层面加载JS。可以下载一个[AdGuard for Mac ](https://adguard.com/en/adguard-mac/overview.html)看看能不能复现。
<img width="611" alt="image" src="https://user-images.githubusercontent.com/27730203/215672965-79299fd0-c4f2-47b1-b0b0-72c376907527.png">

**Comment by theowenyoung** [comment]
> > js是外部加载的就不行？ 可以具体描述下吗？我没太懂，确实有几位用户反馈deepl有问题，但是我没能复现, 可以提供个网址吗？
> > […](#)
> 
> 就是没有采用油猴这种浏览器插件的形式加载JS，而是通过AdGuard在系统层面加载JS。可以下载一个[AdGuard for Mac ](https://adguard.com/en/adguard-mac/overview.html)看看能不能复现。 <img alt="image" width="611" src="https://user-images.githubusercontent.com/27730203/215672965-79299fd0-c4f2-47b1-b0b0-72c376907527.png">

通过外部加载肯定不行呀，脚本调用了油猴的API，如果通过外部加载就没法读取配置信息，以及发送网络请求。

**Comment by al123xiaaaa** [comment]
> 你的key式这样的吗？
> 
> `xxxxxx-xxxxx:fx`
> 
> 后面有个:fx

我的没有:fx这个后缀，但是自己测试用来调用https://api-free.deepl.com/v2/translate这个地址的api是正常的

**Comment by theowenyoung** [comment]
<img width="854" alt="Screenshot 2023-01-31 at 14 24 04" src="https://user-images.githubusercontent.com/62473795/215682990-8a2f4b1f-91a6-4c38-b532-faf61b24cad1.png">


我的界面是这样，你确定没有:fx 后缀吗？

目前代码里是根据有没有 fx后缀来判断是否是免费API，才会调用免费api接口。

我以为所有免费api后缀都是有fx，麻烦你再check一下？

如果没有的话，我需要对deepl的设置加一个免费/pro的选项

**Comment by al123xiaaaa** [comment]
> <img alt="Screenshot 2023-01-31 at 14 24 04" width="854" src="https://user-images.githubusercontent.com/62473795/215682990-8a2f4b1f-91a6-4c38-b532-faf61b24cad1.png">
> 
> 我的界面是这样，你确定没有:fx 后缀吗？
> 
> 目前代码里是根据有没有 fx后缀来判断是否是免费API，才会调用免费api接口。
> 
> 我以为所有免费api后缀都是有fx，麻烦你再check一下？
> 
> 如果没有的话，我需要对deepl的设置加一个免费/pro的选项

确定是没有的。不过我点了创建新的密钥后就有了，用上新生成的KEY就正常了，可能是以前生成的KEY是没有那个后缀的

**Comment by LiuWenJia-ops** [comment]
我有一个问题, 来自[这里](https://stackoverflow.com/questions/75055049/deepl-api-request-blocked-by-cors-policy)

主要说的是 deepl 会拒绝服务来自前端的 request, 来自跨域问题

**Comment by ringcrl** [comment]
> 我有一个问题, 来自[这里](https://stackoverflow.com/questions/75055049/deepl-api-request-blocked-by-cors-policy)
> 
> 主要说的是 deepl 会拒绝服务来自前端的 request, 来自跨域问题

同样的问题，curl是可以的，在前端就是403
