### ISSUE TITLE
增加一个左右页面对照的模式

### ISSUE THREAD

**Issue by jelipo** [immersive-translate/immersive-translate#501]
### 您希望的更新和改进是什么 | Update or Improve

https://lore.kernel.org/bpf/20230526064531.zohcgjbaraq7c2ui@soft-dev3-1/T/#t

比如这个网站，因为代码和评论都是在一起的，导致很难区分开，所以是否可以出个左右对照的模式，也是一个当无法智能识别主内容的兜底策略。

**Comment by theowenyoung** [comment]
这种可以配合 鼠标悬停翻译该段落 来补充一下～ 

左右对照也会把代码都翻译的。
