### ISSUE TITLE
覆盖原文功能会让网页元素失去链接属性

### ISSUE THREAD

**Issue by RemyYYZ** [immersive-translate/immersive-translate#502]
### 插件版本号 | Version

0.5.9

### 平台 | Platform

Android

### 浏览器 | Browsers

Kiwi Browser

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

https://github.com/immersive-translate/immersive-translate/assets/105116818/65b9a231-c03d-470e-b545-5bab33cb0ead

如视频所示，覆盖后失去链接属性，点不动

### 重现步骤 | To Reproduce

如视频

**Comment by theowenyoung** [comment]
可以发一个地址吗？
