### ISSUE TITLE
[Bug]: 0.5.9版本无法翻译medium.com和towardsdatascience.com的付费会员文章

### ISSUE THREAD

**Issue by myfenix** [immersive-translate/immersive-translate#503]
### 插件版本号 | Version

0.5.9

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

0.5.9版本无法翻译medium.com和towardsdatascience.com的付费会员文章
如果退出会员登录 则一切正常 
不知道是不是付费会员打开的页面代码使用了与非会员文章不同的呈现方式
手动安装0.5.5版本则没有任何问题 会员非会员文章都可以正常翻译

**Comment by theowenyoung** [comment]
0.5.10 已修复 https://github.com/immersive-translate/immersive-translate/releases/tag/v0.5.10
