### ISSUE TITLE
Support (GPT-3.5)(Mobile) and GPT-4 (Mobile,V2)

### ISSUE THREAD

**Issue by bs10081** [immersive-translate/immersive-translate#505]
### 您希望的更新和改进是什么 | Update or Improve

Support (GPT-3.5)(Mobile) and GPT-4 (Mobile,V2)

like OpenAI Translator tweet: https://twitter.com/yetone/status/1659483165038354433?s=46&t=YQd_F61eA0uLaUZhZQfC2g

**Comment by theowenyoung** [comment]
目前ChatGPT Plus 默认的已经是 GPT 3.5 Mobile 了。

**Comment by lesliehua** [comment]
我始终不能拿GPT-4来用作翻译，但我明明买了plus了，这会是什么问题？

**Comment by 1PercentSync** [comment]
> 目前ChatGPT Plus 默认的已经是 GPT 3.5 Mobile 了。

能否加上GPT4 Mobile？

**Comment by 1PercentSync** [comment]
> 我始终不能拿GPT-4来用作翻译，但我明明买了plus了，这会是什么问题？

目前应该只有OpenAI Api版本能使用GPT4，然而OpenAI的API和ChatGPT的API是两个不同的东西，前者按量付费，后者3.5免费，4需要会员。OpenAI GPT4 API也是按量付费但是需要加入Waitlist，要排挺久的。
目前沉浸式翻译使用ChatGPT翻译的API是ChatGPT3.5的手机版本。

**Comment by lesliehua** [comment]
> 

感谢，了解了～

**Comment by lroolle** [comment]
Hi，
- 希望可以自动加载 ChatGPT Web Session Model 并支持选择；
- 当前版本（V0.7.1）已经支持 ChatGPT Web(3.5 Mobile) Model；
- 
<img width="284" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/14071051/1283eaa6-bdf1-49ce-bcce-b81c60c95f5b">

- 对于 ChatGPT Web Session，Model 应该也是可以用 AccessToken 通过 API 获取到的；
- API: https://chat.openai.com/backend-api/models
- Models:
<img width="753" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/14071051/25033614-ff3a-40c0-995c-e1136299b201">
- 其中 gpt-4-plugins 基于 gpt-4 且有较长的 max_token limit，因此希望可以支持 ChatGPT 的 Model 加载选择功能， thx

**Comment by theowenyoung** [comment]
由于 ChatGPT 网页版的频率限制较大，并不适合作为网页翻译的后端接口，所以本项目将不再花精力适配ChatGPT网页版了，建议使用 OpenAI 接口代替。
