### ISSUE TITLE
[Bug]: discord频道列表会在显示原文后消失

### ISSUE THREAD

**Issue by Sui-Yun** [immersive-translate/immersive-translate#506]
### 插件版本号 | Version

0.5.9

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

我使用的是  翻译全部区域  和  仅显示译文  。
在discord随便一个服务器内，先开始翻译，正常的，如下图所示：
![image](https://github.com/immersive-translate/immersive-translate/assets/104718844/1d89c790-d214-4542-a0b2-44012ca8f32f)
但是当我点击显示原文后，频道列表文字有概率丢失（不是能稳定复现，但遇到好几次了）：
![image](https://github.com/immersive-translate/immersive-translate/assets/104718844/8ddaf26e-5dbd-485a-bd92-4de9d33eb279)

**Comment by keyboard3** [comment]
旧版本尝试了好几次，也没有复现。你试试更新下版本，看还会出现吗

**Comment by Sui-Yun** [comment]
没问题了，Thanks♪(･ω･)ﾉ
