### ISSUE TITLE
[Bug]: markdown特殊格式内容丢失

### ISSUE THREAD

**Issue by OutlierXu** [immersive-translate/immersive-translate#509]
### 插件版本号 | Version

0.5.9

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![1685172368021](https://github.com/immersive-translate/immersive-translate/assets/37931718/6dacf191-8b41-4d03-bd83-3cfb0bae49f5)

问题网页：https://python.langchain.com/en/latest/modules/models/chat/getting_started.html

**Comment by theowenyoung** [comment]
感谢，已确认。

**Comment by theowenyoung** [comment]
0.5.10 已修复。 https://github.com/immersive-translate/immersive-translate/releases/tag/v0.5.10
