### ISSUE TITLE
没有划词翻译吗？

### ISSUE THREAD

**Issue by drw2005** [immersive-translate/immersive-translate#51]
选择一个词或者一个句子，弹出翻译按钮，点击后自动翻译。

建议增加这个功能。

**Comment by theowenyoung** [comment]
目前专注于网页翻译，市面已经有很多划词翻译的优秀扩展了，建议同时与本扩展使用

**Comment by dxhuii** [comment]
希望能出此功能

**Comment by keyboard3** [comment]
滑动翻译功能新版已支持

**Comment by Alc-z** [comment]
> 目前专注于网页翻译，市面已经有很多划词翻译的优秀扩展了，建议同时与本扩展使用

1. 用app的功能去划词，会占用资源，大部分时间都不希望它划词翻译，所以基本是关闭的
2. safari上没有chrome上google translate简单的插件
3. 可以悬停翻译整段，但是翻译单个词却没有，使用上有点不适（不知道悬停和划词的实现方式是否差异很大）

**Comment by alvin96** [comment]
> > 目前专注于网页翻译，市面已经有很多划词翻译的优秀扩展了，建议同时与本扩展使用
> 
> 1. 用app的功能去划词，会占用资源，大部分时间都不希望它划词翻译，所以基本是关闭的
> 2. safari上没有chrome上google translate简单的插件
> 3. 可以悬停翻译整段，但是翻译单个词却没有，使用上有点不适（不知道悬停和划词的实现方式是否差异很大）

我也有同样的需求，只是我是网页端用户，尤其是第3项，大部分时候我只想翻译某个单词，并不想翻译整个句子

**Comment by Liu0915** [comment]
电脑端，同样需要悬停翻译单词，建议添加翻译悬停或选中单词的开关

**Comment by pilgrimlyieu** [comment]
我倒觉得这有点超出插件的范围了。关于划词翻译，应该很多字典软件都有支持。比如我正在使用的 [GoldenDict-ng](https://github.com/xiaoyifang/goldendict-ng)，就有用快捷键 <kbd>Ctrl</kbd> + <kbd>C</kbd> <kbd>Ctrl</kbd> + <kbd>C</kbd> 显示选中词释义的功能（当然字典及相关设置需要自行配置），同时这种方式的支持不仅限于网页，还能支持文档等。因此我认为没必要推出划词翻译的功能。

**Comment by cbingb666** [comment]
我觉得他专注于网页翻译就好了，这样才有足够的精力把他做到完美，需要划词翻译可以交给 [Bob](https://github.com/ripperhe/Bob) 或 [Pot](https://github.com/pot-app/pot-desktop)，他们在这划词翻译领域很棒👍🏻
