### ISSUE TITLE
字幕文件支持导出仅译文

### ISSUE THREAD

**Issue by theowenyoung** [immersive-translate/immersive-translate#510]
### 您希望的更新和改进是什么 | Update or Improve

字幕文件支持导出仅译文

**Comment by qihuoren** [comment]
建议在增加结合上下文翻译

**Comment by theowenyoung** [comment]
https://github.com/immersive-translate/immersive-translate/releases/tag/v0.5.11

已支持

**Comment by theowenyoung** [comment]
> 建议在增加结合上下文翻译

在大多数翻译服务中 已经结合了上下文，并不是一句一句的。
