### ISSUE TITLE
不要翻译代码

### ISSUE THREAD

**Issue by xiaomingcom-cs** [immersive-translate/immersive-translate#511]
### 您希望的更新和改进是什么 | Update or Improve

默认会将所有英文都进行翻译，包括代码，这将极大地阻碍开发者阅读代码，希望在遇到代码的时候不要进行翻译

**Comment by theowenyoung** [comment]
默认就是不翻译代码的哈，如果遇到代码被翻译的网页，说明那个网页不太标准，需要专门适配一下，贴一下对应的网址～
