### ISSUE TITLE
[Bug]: 翻译全部网页，再次还原快捷键失效

### ISSUE THREAD

**Issue by Icy-Cat** [immersive-translate/immersive-translate#513]
### 插件版本号 | Version

0.5.10

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

快捷键无法正常工作，当使用快捷键“翻译页面全部区域/显示原文：”后，可以显示翻译，再次按下快捷键无法显示原文，页面闪动后仍会显示翻译。

### 重现步骤 | To Reproduce

1. 按下 翻译页面全部区域/显示原文  快捷键，显示翻译
2. 再次按下快捷键，无法取消显示翻译

**Comment by theowenyoung** [comment]
确认，感谢反馈，下个版本修复。

**Comment by theowenyoung** [comment]
https://github.com/immersive-translate/immersive-translate/releases/tag/v0.5.11

已修复
