### ISSUE TITLE
[Bug]: 针对此网站设置无效

### ISSUE THREAD

**Issue by ottocsb** [immersive-translate/immersive-translate#514]
### 插件版本号 | Version

0.5.10

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

设置localhost永不翻译或localhosr加端口的网址永不翻译，依然会加载脚本，如下图：
![image](https://github.com/immersive-translate/immersive-translate/assets/83228451/8edf8197-08c3-48dd-a408-1a7b51491604)

![image](https://github.com/immersive-translate/immersive-translate/assets/83228451/65f1ba7e-bc35-4528-95c0-b0513fa282ba)
我默认理想的结果是永不翻译的网址并不应该加载任何脚本，这阻止了我打开debug时的效率，暂时还没有使用油猴测试是否会复现

### 重现步骤 | To Reproduce

如上描述

**Comment by ottocsb** [comment]
油猴复现了一遍，结果一样

**Comment by theowenyoung** [comment]
这个没法避免，脚本不是动态插入的，而且每个网页都会插件，只是会在运行开始的时候被中止继续运行。

按道理来说他不会影响到你本地的调试，你是在开发者面板里 catch 所有的错误吗？理论上你截图的错误会被我们代码里的流程给catch掉。

**Comment by ottocsb** [comment]
我使用的浏览器是cent，没有被catch掉，我也很纳闷，我下载了原版chrome没有复现出这个问题

**Comment by ottocsb** [comment]
// @match      *://*/*
// @exclude    *://localhost/*
// @exclude    *://127.0.0.1/* 
这样屏蔽本地开发环境的规则不生效吗，下面injec的那条我删除了，在网页还是展示，头大

**Comment by ottocsb** [comment]
用户排除：/^[^:/#?]*:\/\/([^#?/]*\.)?localhost(:[0-9]{1,5})?\/.*$/ 下列规则生效，系统排除上列不知道为什么不生效
