### ISSUE TITLE
[Bug]:  And also, there is no capacity() method available on str variable.

### ISSUE THREAD

**Issue by linpan** [immersive-translate/immersive-translate#515]
### 插件版本号 | Version

lastest version

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/6077601/fd685a40-3ad4-4eff-a49e-53e765523e00)
And also, there is no capacity() method available on str variable.

### 重现步骤 | To Reproduce

And also, there is no capacity() method available on str variable.

### 补充说明 | Additional context

And also, there is no capacity() method available on str variable.

**Comment by linpan** [comment]
test page:: https://dev.to/ssivakumar/rust-string-vs-str-6p6

**Comment by linpan** [comment]
微软翻译会出现， google 翻译正常

**Comment by theowenyoung** [comment]
我这里微软似乎是正常的：

<img width="1412" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/088d20b4-5605-4cf7-995a-6e0c7475cfb3">

**Comment by keyboard3** [comment]
可以试下最新版 0.5.11，微软翻译正常
