### ISSUE TITLE
[Bug]: 遇到中英文混杂的段落，就无法翻译了

### ISSUE THREAD

**Issue by softmetal66** [immersive-translate/immersive-translate#516]
### 插件版本号 | Version

0.5.10

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

遇到中英文混杂的段落，就无法翻译了：https://www.pekingnology.com/p/top-ten-trends-in-digital-tech-according
![image](https://github.com/immersive-translate/immersive-translate/assets/112331657/a8795c1a-c49b-436a-8856-89487a40d46f)

有些电子书，中英文混杂的，也是这种问题
![image](https://github.com/immersive-translate/immersive-translate/assets/112331657/8df16e0e-c6b0-4c61-808d-eb714e366ddc)

**Comment by theowenyoung** [comment]
这个和翻译服务有关，我使用默认的微软翻译是ok 的：

<img width="892" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/9c8ed537-1bb9-4764-8b61-795f7cb88d1b">

**Comment by theowenyoung** [comment]
我这里只有 腾讯翻译有问题，微软和谷歌都没有问题。

不过这个问题我们客户端应该没法做什么，依赖于服务端的翻译。
