### ISSUE TITLE
[Bug]: 更新后软件图标自动出现在工具栏

### ISSUE THREAD

**Issue by shenyinzhe** [immersive-translate/immersive-translate#517]
### 插件版本号 | Version

0.5.10

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

我在自定义工具栏中去掉了这个插件的图标，但是每次更新后，插件图标又会自动出现在工具栏。

### 重现步骤 | To Reproduce

更新插件

**Comment by theowenyoung** [comment]
这个是不是mac safari的bug呀？ 我们没有特殊的添加图标呀。

**Comment by shenyinzhe** [comment]
> 这个是不是mac safari的bug呀？ 我们没有特殊的添加图标呀。

我再观察一下别的插件更新时候会不会出现这个情况

**Comment by shenyinzhe** [comment]
> 这个是不是mac safari的bug呀？ 我们没有特殊的添加图标呀。

应该是safari的问题，别的插件也是，每次更新，图标都会出现在工具栏。。。
