### ISSUE TITLE
Safari 暗主题看不清文字

### ISSUE THREAD

**Issue by 0gif** [immersive-translate/immersive-translate#518]
### 您希望的更新和改进是什么 | Update or Improve

暗主题下看不清文字

macOS 12.6.6
Safari 16.5
插件 0.5.10

<img width="1106" alt="1" src="https://github.com/immersive-translate/immersive-translate/assets/65489614/ea5006e9-eb56-42fa-a572-194f668ca4ce">

**Comment by theowenyoung** [comment]
这是 电子书阅读吗？

**Comment by theowenyoung** [comment]
刚测试了下最新版，目前在dark模式下的颜色应该是修复了。有问题在重新开哈。
