### ISSUE TITLE
[Bug]: pdf翻译格式错乱

### ISSUE THREAD

**Issue by 459266263** [immersive-translate/immersive-translate#519]
### 插件版本号 | Version

0.5.12

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

pdf翻译格式错乱叠在一起看不了了，看得出这里两行的英文才会出现，不知道什么原因
![image](https://github.com/immersive-translate/immersive-translate/assets/10046158/a7d20522-64ff-4987-a544-e272b613e322)
长段落最新版本的也是分行错误，全部换行了导致翻译很难读懂，0.4.8版本却没问题
希望能够改进一下

### 重现步骤 | To Reproduce

[https://documents.blackmagicdesign.com/UserManuals/DaVinci-Resolve-18-Beginners-Guide.pdf?_v=1678777211000](url)
143页

**Comment by theowenyoung** [comment]
>  长段落最新版本的也是分行错误，全部换行了导致翻译很难读懂，0.4.8版本却没问题
这个说的是哪个功能？有示例网址吗？


pdf 还需要时间继续优化下～ 我保存了你的pdf，下次优化的时候再着重看下。

**Comment by hiwei93** [comment]
也遇到了同样的问题，防疫过后，文本产生重叠

插件版本号 | Version
0.5.12

平台 | Platform
MacOS

浏览器 | Browsers
Chrome

插件类型 | Extension Type
浏览器插件 | Browser Extension

请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/17758336/ef8e6ebc-345e-4484-957e-33d11e9f6356)

文件地址：https://arxiv.org/pdf/2305.17126.pdf

**Comment by scruel** [comment]
还有 LaTeX、图表的识别也建议整一整，就不新开 issue 啦
![图片](https://github.com/immersive-translate/immersive-translate/assets/16933298/da708171-f71d-4e02-a566-4ee7e4703def)
https://arxiv.org/pdf/1712.09381.pdf

**Comment by miaooo0000OOOO** [comment]
我也遇到了相同的问题
![2023-06-05 22-38-22 的屏幕截图](https://github.com/immersive-translate/immersive-translate/assets/72688030/b3220029-5622-4026-902e-fab5df14efca)
https://citeseerx.ist.psu.edu/doc/10.1.1.368.2522

**Comment by yekuliu** [comment]
不过这个bug现在可以通过放大页面临时解决，不过就失去了双语对照了

**Comment by foresee-io** [comment]
论文：https://arxiv.org/abs/2207.07061

我觉得第一阶段先不求公式拆分多准确，可以先弄一下格式问题？至少避免出现段落重叠这样的大bug

![image](https://github.com/immersive-translate/immersive-translate/assets/32860378/f794f5e2-4caf-444c-b796-a68238278fc3)

**Comment by theowenyoung** [comment]
> 论文：https://arxiv.org/abs/2207.07061
> 
> 我觉得第一阶段先不求公式拆分多准确，可以先弄一下格式问题？至少避免出现段落重叠这样的大bug
> 
> ![image](https://private-user-images.githubusercontent.com/32860378/293644048-f794f5e2-4caf-444c-b796-a68238278fc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxODA3MTYsIm5iZiI6MTcwNDE4MDQxNiwicGF0aCI6Ii8zMjg2MDM3OC8yOTM2NDQwNDgtZjc5NGY1ZTItNGNhZi00NDRjLWI3OTYtYTY4MjM4Mjc4ZmMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDA3MjY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmYjdkYjEwYzZkNmZjYTJmOTBmMGM1YjM3YjUxMWYwOGQ1NDJmYTRkYmI1MTAzMjc2OTBhZWZhYWZhZDRhMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o4DtGn65oe9U78xzIxm5fz3MsuwAqA2BLcAaHmOWjSQ)

arxiv 建议直接点击页面右侧的沉浸式双语翻译 https://ar5iv.labs.arxiv.org/html/2207.07061?_immersive_translate_auto_translate=1 ，里面是 html 版本的翻译：
![CleanShot 2024-01-02 at 15 28 56@2x](https://github.com/immersive-translate/immersive-translate/assets/62473795/4cba94a1-c263-4c42-9819-3bb7a107701a)

![CleanShot 2024-01-02 at 15 27 49@2x](https://github.com/immersive-translate/immersive-translate/assets/62473795/ebf792b0-b0c2-4457-a884-7547e88b76f3)

**Comment by keyboard3** [comment]
查看目前pdf工具未发现此问题
