### ISSUE TITLE
小牛翻译

### ISSUE THREAD

**Issue by Ben11029** [immersive-translate/immersive-translate#52]
不知道能添加小牛翻译么？谢谢啦

**Comment by theowenyoung** [comment]
最新版本已支持： 谷歌商店还在审核。 https://github.com/immersive-translate/immersive-translate/releases

<img width="1207" alt="Screenshot 2023-01-30 at 12 02 52" src="https://user-images.githubusercontent.com/62473795/215384992-f76a40c9-b2e2-4a4b-b906-9a3002b6304c.png">

**Comment by theowenyoung** [comment]
这个问题应该解决了，升级到最新版本即可～ 有问题再打开，谢谢～
