### ISSUE TITLE
[Bug]: 语雀的知识库翻译有点问题

### ISSUE THREAD

**Issue by duoluodexiaoxiaoyuan** [immersive-translate/immersive-translate#520]
### 插件版本号 | Version

0.5.6

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

知识库地址:  https://www.yuque.com/zenany/fe_weekly/20230529

![image](https://github.com/immersive-translate/immersive-translate/assets/59086082/90dd507a-5597-4c98-ba14-2325b9a228ed)
如图可知，我设置的是翻译主要区域，但是左侧的导航栏部分也进行了翻译(主要是格式错乱了)，不知道是否可以帮忙适配。

**Comment by keyboard3** [comment]
因为侧边栏每个菜单都是绝对定位的，所以没办法让他适配效果成自适应高度成我们双语翻译的效果。这里建议屏蔽侧边栏翻译
[
  {
    "matches": "https://www.yuque.com/*",
    "excludeSelectors": [
      ".lark-virtual-tree"
    ]
  }
]

**Comment by theowenyoung** [comment]
@keyboard3 直接添加到默认规则吧？

**Comment by duoluodexiaoxiaoyuan** [comment]
> 

感谢大佬写了下规则，之前我一直懒得用，哈哈，发现规则还是挺有效的
