### ISSUE TITLE
工具栏图标与safari浏览器的颜色不搭

### ISSUE THREAD

**Issue by BarrySong** [immersive-translate/immersive-translate#524]
### 您希望的更新和改进是什么 | Update or Improve

希望图标可以自由选择为原版图标或简笔画图标
<img width="243" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/23122409/6d5ea3c0-df80-42eb-85b6-fb09d0d35540">
<img width="205" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/23122409/2dd4aa98-d0c8-4edb-aa40-0ba924a32afd">

**Comment by yekuliu** [comment]
同意！

**Comment by Jagerx** [comment]
#409 可能优先级是真的很低。已经又过去了十多个版本

**Comment by BarrySong** [comment]
> #409 可能优先级是真的很低。已经又过去了十多个版本

哈哈，这不就改了么
<img width="774" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/23122409/18fe7122-0249-4cf1-a448-4177aaa9835c">

**Comment by Jagerx** [comment]
> > #409 可能优先级是真的很低。已经又过去了十多个版本
> 
> 哈哈，这不就改了么 <img alt="image" width="774" src="https://user-images.githubusercontent.com/23122409/253271193-18fe7122-0249-4cf1-a448-4177aaa9835c.png">

真不错#409 已关闭
