### ISSUE TITLE
官网页面优化以及域名迁移

### ISSUE THREAD

**Issue by theowenyoung** [immersive-translate/immersive-translate#525]
### 您希望的更新和改进是什么 | Update or Improve

目前官网是个人域名： immersive-translate.owenyoung.com

不太好记，预期迁移到： immersivetranslate.com

目前官网是一个文档的格式，不够直观，展示一些效果的时候也比较受限制，设计一个更易用的官网。

**Comment by versun** [comment]
ImmTrans.app也不错

**Comment by Guwalgiyakuan** [comment]
> ImmTrans.app也不错
这个不错 简洁
