### ISSUE TITLE
api.cloudflare.com “沉浸式翻译”拖慢了您的Firefox……

### ISSUE THREAD

**Issue by photkey** [immersive-translate/immersive-translate#53]
![Snipaste_2023-01-30_20-50-19](https://user-images.githubusercontent.com/60434581/215481886-ecb887a6-bd18-4799-9aa7-a6b49f9d78a8.png)
每次打开 [https://api.cloudflare.com](https://api.cloudflare.com) 都很慢，Firefox提示图上图，希望能优化一下。

**Comment by theowenyoung** [comment]
这个应该不好搞。

网页本身太大了，分析都要老半天。只能等...

不确定优化的方向会是什么..

目前是进来之后就要分析整个网页。

也许可能优化为，边分析，边翻译。中间再歇一会儿..

**Comment by ttttmr** [comment]
可以只翻译可视区域内的部分，滚动之后再翻译新的部分（可能类似图片懒加载）
