### ISSUE TITLE
tor浏览器

### ISSUE THREAD

**Issue by xiaoxingtxdys** [immersive-translate/immersive-translate#531]
### 您希望的更新和改进是什么 | Update or Improve

希望能支持tor浏览器，目前在tor里面不支持。

**Comment by versun** [comment]
虽然tor本质上也是firefox，但不建议在tor上安装插件，原因参考[官方](https://support.torproject.org/glossary/add-on-extension-or-plugin/)
其次，通过tor网络请求api很慢的，因此建议手动翻译吧
