### ISSUE TITLE
[Bug]: 在线翻译pdf失效

### ISSUE THREAD

**Issue by judecumt** [immersive-translate/immersive-translate#532]
### 插件版本号 | Version

0.5.13

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

我在使用kodbox，使用浏览器打开kodbox中的pdf文档时，不能出现`点击翻译PDF`的按钮
![image](https://github.com/immersive-translate/immersive-translate/assets/18454206/025dde05-f22f-4de0-ac65-9daced0ea74e)
测试其他在线pdf是可以的
![image](https://github.com/immersive-translate/immersive-translate/assets/18454206/5f772cf8-3a10-4202-98ba-5aa6e495fb76)

### 重现步骤 | To Reproduce

1. 使用demo/demo登陆http://demo.kodcloud.com/
2. 上传任意pdf
3. 右击pdf，选择使用浏览器打开

**Comment by versun** [comment]
@judecumt 
在更多里面哈
![image](https://github.com/immersive-translate/immersive-translate/assets/2398708/466269f9-f852-43e5-b550-20152d1aeaef)

**Comment by keyboard3** [comment]
在线翻译pdf只支持 路径的后缀带.pdf的地址
