### ISSUE TITLE
高亮下的字体颜色看不清

### ISSUE THREAD

**Issue by dwzrlp** [immersive-translate/immersive-translate#536]
### 您希望的更新和改进是什么 | Update or Improve

当使用高亮的时候，黄色高亮，我发现会使用原来字体的颜色来显示翻译字体的颜色，可是当原来背景是黑色字体为白色时，高亮情况下，黄色底白色字体就完全看不清楚了
![image](https://github.com/immersive-translate/immersive-translate/assets/15451182/9de5e405-88da-480f-8f00-99ca5b60c943)

**Comment by theowenyoung** [comment]
这个技术上没法解决哈，因为不同的网站有不同的配色方案，这种情况下 可以切换到 默认的【无】译文样式是最通用的。
