### ISSUE TITLE
可以加上讯飞翻译的接口支持吗？

### ISSUE THREAD

**Issue by huiyanghu12** [immersive-translate/immersive-translate#537]
### 您希望的更新和改进是什么 | Update or Improve

之前开发产品，用讯飞翻译的接口翻译效果还行。可以加上讯飞翻译的接口支持吗？

这是接口地址 ：https://www.xfyun.cn/doc/nlp/xftrans_new/API.html#%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E

**Comment by culyzhao** [comment]
支持，实际对比科技书籍的翻译，翻译质量比谷歌要好

**Comment by theowenyoung** [comment]
为了保持产品的简单性，暂无计划添加更多的翻译引擎哈，我们已经支持了 【自定义API】，理论上有需要的同学可以接入任何翻译服务，请查看文档：

https://immersivetranslate.com/docs/services/custom/
