### ISSUE TITLE
[Bug]: epub翻译错误 - Cannot read properties of undefined (reading 'children')

### ISSUE THREAD

**Issue by Andy-AO** [immersive-translate/immersive-translate#539]
### 插件版本号 | Version

0.5.10

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox, Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

这个文件用 SumatraPDF 可以打开，但是用插件翻译却不行，打开文件就报错。

> Cannot read properties of undefined (reading 'children')
![image](https://github.com/immersive-translate/immersive-translate/assets/38101170/0a6aae7c-e1e3-44cd-a597-532bd8622620)

文件如下，将去掉后缀 `.zip` 即可使用。

[Defense Mechanisms Theoretical, Research and Clinical Perspectives 防御机制：理论、研究和临床观点 Uwe Hentschel 2004_6.2.2023.epub.zip](https://github.com/immersive-translate/immersive-translate/files/11630802/Defense.Mechanisms.Theoretical.Research.and.Clinical.Perspectives.Uwe.Hentschel.2004_6.2.2023.epub.zip)

**Comment by theowenyoung** [comment]
epub后缀难道不是必须的嘛？

**Comment by Andy-AO** [comment]
> epub后缀难道不是必须的嘛？

是也不是。
你可以试着上传 epub 文件到 GitHub 评论区，然后你会发现不能上传，这就是现在它的后缀为 zip 的原因，我使用的时候是 epub。
对于上传而言 epub 后者不仅不是必须的，而且是多余的。
对于翻译来说可能是必须。

**Comment by theowenyoung** [comment]
哦哦，sorry，理解错你的意思了～

我试试

**Comment by theowenyoung** [comment]
这个文件似乎在 苹果的 ibooks 中也打不开。

**Comment by Andy-AO** [comment]
> 这个文件似乎在 苹果的 ibooks 中也打不开。

猜文件的格式可能出现了一些问题，但是在windows上我的两个阅读器都可以打开，比如SumatraPDF和Calibre。

所以我在想是否应该增加一些容错空间？HTML 的设计好像就在这方面有很多的考虑。

目前的解决方案是用Calibre转mobi，然后再转epub，之后就可以了。

**Comment by theowenyoung** [comment]
嗯～ 我完了兼容一下这种情况。

**Comment by theowenyoung** [comment]
这个问题暂时可能也不好解决，因为依赖的是上游的epub和zip库，对于不标准的格式确实没法识别。
