### ISSUE TITLE
建议“译文显示样式”可以自定义边框、下划线颜色

### ISSUE THREAD

**Issue by iseeyo** [immersive-translate/immersive-translate#54]
建议“译文显示样式”可以自定义边框、下划线颜色

**Comment by theowenyoung** [comment]
@jtsang4 

我们是不是应该给已有的样式全部都增加一个自定义颜色，其实就能满足绝大多数需求了？ 而且好像还比让用户自己写css更人体工学一点？

**Comment by jtsang4** [comment]
> @jtsang4
> 
> 我们是不是应该给已有的样式全部都增加一个自定义颜色，其实就能满足绝大多数需求了？ 而且好像还比让用户自己写css更人体工学一点？

感觉可以在自定义 CSS 之后做，有了自定义 CSS 之后，再加一个颜色选择器，可以生成自定义样式，用户不用手写，只用使用选择器导出的结果就可以。

**Comment by theowenyoung** [comment]
但是自定义css 加颜色选择器？ 

我感觉自定义css好像用户输入的只是一些字符串，怎么选颜色呢？

我是觉得大多数用户想要其实只是自定义颜色，每个主题都支持自定义颜色之后，其实都可以没有自定义css的选项.(有点太技术流了)

**Comment by jtsang4** [comment]
> 

UI 上是一个文本输入框用于输入 CSS，旁边再加上一个颜色选择的按钮，点击以后出来一个类似这样 https://www.w3schools.com/colors/colors_picker.asp 的色盘。

如果是专业用户可以手动输入 CSS，如果是非专业用户可以直接在色盘上选择或者填颜色，确认以后生成 CSS 自动回填到输入框中。

这样两种用户的需求都能满足，CSS 的好处是自定义能力更强，在这个的基础上又能去延展颜色选择器的功能

**Comment by theowenyoung** [comment]
但是如果只是选择颜色，怎么生成css呢？ css应该要包括 下划线或者边框之类的东西，颜色只是其中很小的一个属性？

**Comment by theowenyoung** [comment]
最新版本已支持 自定义文字颜色，和边框颜色，请在界面设置里体验，谢谢！

**Comment by theowenyoung** [comment]
这个问题应该解决了，升级到最新版本即可～ 有问题再打开，谢谢～
