### ISSUE TITLE
[Bug]: producthunt网站搜索页没有自动翻译

### ISSUE THREAD

**Issue by Fokkyp** [immersive-translate/immersive-translate#540]
### 插件版本号 | Version

0.5.14

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

https://www.producthunt.com/search?q=ppt
这个网址没有自动翻译

翻译服务：腾讯交互翻译

总是翻译 英语打勾
<img width="1677" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/5858642/f2493136-addf-4979-9f32-79cc45f37649">

**Comment by theowenyoung** [comment]
已修复，再试试～
