### ISSUE TITLE
增加一个像编辑器的字体回退(第二字体)类似的翻译回退(第二翻译服务)

### ISSUE THREAD

**Issue by photkey** [immersive-translate/immersive-translate#541]
### 您希望的更新和改进是什么 | Update or Improve

我现在默认使用的deepl翻译，但是deepl支持的语种还是不够多，GitHub经常有一些项目是有一部分小语种的语言，这种情况下deepl就翻译不了，要临时切换到Google翻译；
所以我想，能不能添加第二翻译服务，就是遇到当默认的翻译服务不支持的语种时，自动用第二种翻译服务来翻译

### 补充说明 | Additional context
或者是可以根据语种设置翻译服务，比方英语用deepl，越南语就用Google翻译服务
_No response_

**Comment by theowenyoung** [comment]
抱歉，很晚才回复。

目前为了保持工具的简单易用性，暂时没有计划引入更复杂的机制。
