### ISSUE TITLE
[Bug]: safari 快捷键描述问题

### ISSUE THREAD

**Issue by LRainner** [immersive-translate/immersive-translate#543]
### 插件版本号 | Version

0.5.14

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

快捷键描述应该是 option+A
![image](https://github.com/immersive-translate/immersive-translate/assets/47016648/233fefbf-9a1e-4db2-ba30-9a05d6060200)

**Comment by FattySpring** [comment]
[版本 0.12.9](https://immersivetranslate.com/docs/CHANGELOG/#0129) 已修复
