### ISSUE TITLE
[Bug]: serviceworker似乎有点性能问题，高cpu占用

### ISSUE THREAD

**Issue by freemedom** [immersive-translate/immersive-translate#544]
### 插件版本号 | Version

最新

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

任务管理器cpu大概30%
chrome://serviceworker-internals/ Unregister这个扩展后cpu就降下来了
不太清楚是扩展的bug还是chrome的bug

**Comment by theowenyoung** [comment]
这是在标签页很少的情况下，还是标签页很多的情况下？

**Comment by freemedom** [comment]
@theowenyoung 我一般是开着四五十个标签页，不太确定标签页数量少的时候的情况（刚打开浏览器的时候是没问题的，一般要用一段时间才会出现这个问题）

**Comment by theowenyoung** [comment]
这些网页都使用了翻译吗？还是只有部分使用了？

**Comment by freemedom** [comment]
@theowenyoung 只有一两个使用了

**Comment by theowenyoung** [comment]
和 #1006 类似的问题，但是不知道如何复现。先关掉这个问题，统一在 #1006 讨论吧～

**Comment by freemedom** [comment]
@theowenyoung 最近没这个问题了
