### ISSUE TITLE
[Bug]: PDF翻译版式

### ISSUE THREAD

**Issue by Sui-Yun** [immersive-translate/immersive-translate#545]
### 插件版本号 | Version

0.5.14

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

PDF翻译排版问题，应该和以前某些issue类似。这里放个pdf权当样本嘿嘿。不着急。
https://proceedings.neurips.cc/paper_files/paper/2017/file/3f5ee243547dee91fbd053c1c4a845aa-Paper.pdf
![image](https://github.com/immersive-translate/immersive-translate/assets/104718844/69ac518d-fbb6-4c61-b01e-181ee8d4a286)

**Comment by keyboard3** [comment]
试下0.6.18+新版，大部分排版问题应该解决了

**Comment by keyboard3** [comment]
试了0.6.19 这块的折行问题已解决
