### ISSUE TITLE
[Bug]: 我无法在默认是old reddit中使用翻译

### ISSUE THREAD

**Issue by rsyqvthv** [immersive-translate/immersive-translate#546]
### 插件版本号 | Version

0.5.14

### 平台 | Platform

Windows

### 浏览器 | Browsers

Other

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在reddit中, 如: 
https://www.reddit.com/r/Velo/comments/ztxdn/what_is_your_routine_when_you_clean_and_degrease/

等页面loaded后, 
右键菜案选择 "toggle translate page"
没有任何反映. 

在console中, 有个提示: 

```
ntent_script.js:3810    Immersive Translate WARN: injectCSS failed, rootDocument does not have head node null
```

这个情况只在reddit中出现, 无论是帖子内容还是首页什么的, 都是如此. 
访问其他网站没有这个问题. 

### 重现步骤 | To Reproduce

1. 打开任意reddit页面, 比如:
https://www.reddit.com/r/Velo/comments/ztxdn/what_is_your_routine_when_you_clean_and_degrease/
2. 等页面loaded后, 
3. 右键菜案选择 "toggle translate page"
4. 没有任何反映.

**Comment by theowenyoung** [comment]
你是否安装了其他脚本或者插件对Reddit做过修改呢？

**Comment by rsyqvthv** [comment]
恩, 我尝试使用另外的profile, 安装了immersive translate, 确实问题就消失了. 
可能是我当前的profile的什么设置/插件干扰了immersive translate在reddit的发挥. 

不知道你知道如何排查这种问题吗? 比如通过console?

**Comment by theowenyoung** [comment]
排除法？hhh （把其他插件一个个禁用试试..

**Comment by rsyqvthv** [comment]
非常感谢你的回复, 我将所有的插件全部禁用, 包括greasemonkey. 只留下了immersive translate. 并且恢复了当前profile下浏览器内置的隐私设置. 且重启了浏览器. 但是还是无法翻译reddit.

真是十分怪异. 

不知道 @theowenyoung 有没有什么建议? 还有什么会干扰immersive translate翻译reddit吗? 

console提示的 `ntent_script.js:3810` 有没有参考价值?

**Comment by theowenyoung** [comment]
那个提示理论上应该没有关系, 不会阻塞主流程，它只是一个warning. 但是我这也的确没有这个warning.

沉浸式翻译扩展针对reddit有特殊的规则，只有指定的元素才会被翻译。

这种情况看起来：

1. 要么你的Reddit网站布局被其他插件修改
2. 要么你修改过默认规则？你有在【开发者设置】-> 【User Rule】 这里修改过规则吗？

**Comment by rsyqvthv** [comment]
> 沉浸式翻译扩展针对reddit有特殊的规则
> 要么你的Reddit网站布局被其他插件修改

似乎你说的是对的.

我使用的是old reddit版面布局: 

> user settings (drop down in the top right, click user settings), and at the very bottom should be a toggle that says "Opt out of the redesign".

新版布局很多功能用不了, 还不能显示groups. 所以我一直用old version. 
但是这种情况下, reddit就无法翻译. 

如果切换回new reddit, 或者在默认new reddit的情况下, 临时使用old.reddit.com来访问旧版, 似乎都是可以翻译的.

不知道可否能针对默认是旧版的情况做一下特殊规则? 让immersive translate可以工作?

> 只有指定的元素才会被翻译。

另外, 这个我不知道怎么做到? 
是选中某些文字, 然后右键菜单进行翻译吗?

>. 你有在【开发者设置】-> 【User Rule】 这里修改过规则吗？

我第一次听说有这个功能. 
找了半天才发现这个入口,
看样子我只是使用默认设置, 
这里我并未有任何修改. 


感谢你的回复. 期望能得到默认old.reddit.com的支持.

**Comment by theowenyoung** [comment]
确实对 old.reddit.com 做过适配。

但是你的情况是在新版的reddit里设置了使用旧版的布局。

我刚尝试在0.5.15版本里做了一点兼容，不知道有没有效果。商店可能需要一点时间审核

**Comment by rsyqvthv** [comment]
> 我刚尝试在0.5.15版本里做了一点兼容，不知道有没有效果。

非常感谢, 问题解决了!!!

你是我遇到最好的开发者, 高效, 倾听, 积极. 
给你点好多好多的赞!
