### ISSUE TITLE
[Bug]: 我选择了按ctrl加悬停才翻译但是在YouTube评论区好像失效了，不需要ctrl就能翻译出来，其他网站目前没发现这个问题

### ISSUE THREAD

**Issue by Chenm4** [immersive-translate/immersive-translate#547]
### 插件版本号 | Version

0.5.14

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

我选择了按ctrl加悬停才翻译但是在YouTube评论区好像失效了，不需要ctrl就能翻译出来，其他网站目前没发现这个问题

**Comment by theowenyoung** [comment]
刷新重试呢？

**Comment by Chenm4** [comment]
> 刷新重试呢？

噢噢，可以了，感谢感谢
