### ISSUE TITLE
使用new bing 搜索时开启翻译后出现文字重叠

### ISSUE THREAD

**Issue by evelynn996** [immersive-translate/immersive-translate#549]
### 您希望的更新和改进是什么 | Update or Improve

关闭翻译的界面：
![image](https://github.com/immersive-translate/immersive-translate/assets/93717293/ffc3faa9-097b-4190-86d1-d7acdf57ae83)

开启翻译后：
![image](https://github.com/immersive-translate/immersive-translate/assets/93717293/8fa69442-7fe4-40d3-baa6-7dc41fd44995)

**Comment by theowenyoung** [comment]
可以提供一个链接吗？ 我测试了一下，好像没有复现～

你用的是默认设置吗？

**Comment by keyboard3** [comment]
试下最新版 应该修复了
