### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jihongboo** [immersive-translate/immersive-translate#551]
### 插件版本号 | Version

0.5.15

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

1. 自定义快捷键失效，无法捕捉到键盘
2. 默认按键没有对Mac键盘进行适配，没有option和command按钮

**Comment by theowenyoung** [comment]
请问你自定义的快捷键是？


2. 默认快捷键是 alt+A , 在mac下是 option+A

**Comment by jihongboo** [comment]
<img width="640" alt="Screenshot 2023-06-04 at 4 12 08 PM" src="https://github.com/immersive-translate/immersive-translate/assets/15397647/dc42420e-fa1d-40dd-af25-7eb5160e77ac">
我想要自定义的是鼠标hover时翻译单词的快捷键，我这边设置面板无法捕捉到按键，而是普通的输入框。

**Comment by theowenyoung** [comment]
这个就是普通输入框，还没有做自动捕捉.

下面有说明： 请输入 `Ctrl+A`, `Command+C` 类似对格式即可。

**Comment by jihongboo** [comment]
在Mac下Alt会被映射到Option是吧，但是hover翻译局部的快捷键貌似设置成Alt（Option）不生效，设置成Shift可以。但是Alt（Option）+ A翻译网页是OK的。
