### ISSUE TITLE
[Bug]: youtube网站无法翻译

### ISSUE THREAD

**Issue by wongchenv** [immersive-translate/immersive-translate#555]
### 插件版本号 | Version

0.5.15

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

youtube网站无法翻译. 切换翻译服务也无服务

**Comment by theowenyoung** [comment]
是翻译报错吗？还是没有反应？

我这里测试是ok的，尝试在设置页面重置一下设置，看是否你有修改设置。

**Comment by wongchenv** [comment]
> 

<img width="1155" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/14831158/b78b736a-5021-42f6-839b-202ae39e038a">
没有报错 , 但也没有翻译. 其他网站可以翻译, 但youtube不行.

**Comment by theowenyoung** [comment]
发一下这个链接～

应该是这个链接里的内容没有适配。

**Comment by wongchenv** [comment]
> 发一下这个链接～
> 
> 应该是这个链接里的内容没有适配。

https://www.youtube.com/results?search_query=tana

**Comment by theowenyoung** [comment]
我这里好像有被翻译：

<img width="1090" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/ae060228-0f67-4419-b59b-34e9a180231d">

**Comment by wongchenv** [comment]
> 我这里好像有被翻译：
> 
> <img alt="image" width="1090" src="https://user-images.githubusercontent.com/62473795/243311311-ae060228-0f67-4419-b59b-34e9a180231d.png">

擦, 为啥我的没反应....

**Comment by wongchenv** [comment]
> 我这里好像有被翻译：
> 
> <img alt="image" width="1090" src="https://user-images.githubusercontent.com/62473795/243311311-ae060228-0f67-4419-b59b-34e9a180231d.png">

找到原因了, 是与插件 [Language Reactor](https://chrome.google.com/webstore/detail/language-reactor/hoombieeljmmljlkjmnheibnpciblicm) 有冲突.
