### ISSUE TITLE
[Bug]: 无法导出文件名过长的文件

### ISSUE THREAD

**Issue by Andy-AO** [immersive-translate/immersive-translate#556]
### 插件版本号 | Version

0.5.10

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

无法导出文件名过长的文件，比如`Dating Sucks, but You Don't The Modern Guy's Guide to Total Confidence, Romantic Connection, and Finding the Perfect Partner约会很糟糕，但你做不到现代男人的完全自信、浪漫联系和寻找完美伴侣指南 Tiller Press, 2021 Connell Barrett`这样的文件导出就会失败，如果改成`1.epub`，导出就会成功。

建议设置最长文件名的阈值，如果达到阈值，那么就用`……`替代过长的文件名，从而使之顺利导出。

**Comment by theowenyoung** [comment]
下个版本 限制到 160个字。
