### ISSUE TITLE
[Bug]: 選擇繁體中文卻出現簡體中文

### ISSUE THREAD

**Issue by rockstyle** [immersive-translate/immersive-translate#557]
### 插件版本号 | Version

0.5.15

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

選擇了翻譯成繁體中文，但結果卻是簡體中文。或是比較像是全篇有的地方是繁體中文沒錯，但有的地方變成了簡體中文

**Comment by theowenyoung** [comment]
请问是什么翻译服务？

rockstyle ***@***.***> 于 2023年6月5日周一 下午12:38写道：

**Comment by rockstyle** [comment]
OpenAI，gpt3.5

**Comment by theowenyoung** [comment]
这是一个bug，请更新到0.5.16版本～

**Comment by rockstyle** [comment]
好的感謝！🙏
