### ISSUE TITLE
[Improvement]在Safari状态栏中沉浸翻译生效后的颜色

### ISSUE THREAD

**Issue by Vinetan** [immersive-translate/immersive-translate#558]
### 您希望的更新和改进是什么 | Update or Improve

在Safari中大多数的extensions在生效后都会变成蓝色，而沉浸翻译使用的红色的配置，我能理解这是沉浸翻译的主题色，但是在一片蓝色中有一个**红色太过于突兀**，**希望增加或更改为蓝色**。

<img width="192" alt="CleanShot 2023-06-05 at 16 18 09@2x" src="https://github.com/immersive-translate/immersive-translate/assets/80163603/8bec510e-03ef-4dc8-baef-26bf1b557bcc">

上图中的其他三个app的主题色均不是蓝色，但是在Safari状态栏中他们也使用了统一的蓝色。

**Comment by Jiafan666** [comment]
upvote

**Comment by keyboard3** [comment]
0.7.7 已调整
