### ISSUE TITLE
[Bug]: 在microsoft edge浏览器中通过非文件夹的安装方式安装，打开pdf文件后无法使用点击翻译Pdf按钮

### ISSUE THREAD

**Issue by Jack251970** [immersive-translate/immersive-translate#559]
### 插件版本号 | Version

0.5.16

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

通过非文件夹的安装方式安装，打开pdf文件后使用点击翻译Pdf按钮，翻译出来的是一个空文档。
而通过develop mode下的load unpacked选项安装不会出现这个问题。
我认为这可能与翻译文档的缓存机制有关。

### 重现步骤 | To Reproduce

1. 打开一个pdf文件
2. 点击翻译pdf

### 补充说明 | Additional context

我的Microsoft edge浏览器是最新稳定版本。

**Comment by Jack251970** [comment]
翻译本地文档的功能是可用的。

**Comment by theowenyoung** [comment]
非文件夹方式的安装指的是什么方式？可以详细描述一下吗？

**Comment by Jack251970** [comment]
使用Microsoft Edge Add-ons安装，或者Chorme Web Store安装

**Comment by theowenyoung** [comment]
这个应该和你的设置有关，打开的如果是本地pdf的话，那么默认是没有权限打开的，你需要在沉浸式翻译扩展的扩展管理详情页，允许沉浸式翻译访问本地文件权限，再试试应该就可以了。

**Comment by Jack251970** [comment]
请问如何设置文件权限？我似乎没有找到相关的设置选项

**Comment by Jack251970** [comment]
感谢，我已经解决了这个问题。文件权限默认似乎为关闭。

**Comment by Jack251970** [comment]
感谢，我已经解决了这个问题。文件权限默认似乎为关闭。
