### ISSUE TITLE
使用Android的via游览器在无法翻译

### ISSUE THREAD

**Issue by mengqiansiguang** [immersive-translate/immersive-translate#56]
via游览器可以自带油猴插件，安装沉浸式翻译他会提示你本地扩展版本过旧v0.0.0无法使用，尝试过使用其他翻译服务，也不行。安装的昨天更新的v0.2.35，感叹号报错为network request falled
![QQ图片20230131173443](https://user-images.githubusercontent.com/117538631/215722733-a351efc8-6025-460f-b2de-2e4e0c6d0746.jpg)

**Comment by theowenyoung** [comment]
via 浏览器没有正确实现油猴的接口，所以其实不支持Via浏览器的。建议使用完整支持油猴插件的浏览器，比如firefox nightly版本。

<https://immersive-translate.owenyoung.com/installation>
