### ISSUE TITLE
[Bug]: chrome浏览器 选择腾讯翻译以后pdf无法翻译 

### ISSUE THREAD

**Issue by wanghaisheng** [immersive-translate/immersive-translate#561]
### 插件版本号 | Version

0.6.1

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

我在不同的翻译引擎中间切换，主要是那几个不需要配置的
只有微软翻译是正常的
其他需要配置的，双语pdf也是可以加载，就是翻译的部分仍然是英文罢了

**Comment by wanghaisheng** [comment]
要么是插件显示有误，无需配置的  微软翻译 谷歌翻译 腾讯翻译
要么就是我理解有误

**Comment by wanghaisheng** [comment]
标题正常，页数那里是00

**Comment by versun** [comment]
我这边测试都是可以的，能否提供下无法翻译的PDF文件

**Comment by keyboard3** [comment]
请提供无法翻译的pdf文件

**Comment by wanghaisheng** [comment]
我后来复现不了
