### ISSUE TITLE
[Bug]: 在tor浏览器上面无法打开插件的设置

### ISSUE THREAD

**Issue by a15355447898a** [immersive-translate/immersive-translate#562]
### 插件版本号 | Version

0.6.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Other

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

我在tor浏览器上面安装了这个插件,但是当我想要查看插件的选项时发现是一片空白的

### 重现步骤 | To Reproduce

https://github.com/immersive-translate/immersive-translate/assets/62456287/24d34e91-aed1-4b72-a3f3-79b9065e0f6c

### 补充说明 | Additional context

我搜索issue的时候找到了https://github.com/immersive-translate/immersive-translate/issues/531
但是还是麻烦作者支持一下把,外面的世界没有沉浸式翻译真的看不太懂啊

**Comment by theowenyoung** [comment]
Tor 浏览器有点特殊，他的官方文档不推荐任何人安装插件。

我刚在 最新版 13.0 测试了一下，发现是可以启用的：

首先在商店安装 沉浸式翻译，然后打开： `about:config`, 搜索 `webextensions.storage.sync.enabled`选项，改为 true，因为沉浸式翻译依赖这个API。

最后，在Tor里，默认安装的插件是不显示在工具栏的，你需要在Tor的插件管理页面，找到沉浸式翻译，然后允许沉浸式翻译在【隐私窗口】运行，这样就可以显示在Tor浏览器里。

我测试翻译应该是正常的。

<img width="1680" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/a1cbdc80-dd20-43f7-ac2d-50e88aeff819">

**Comment by GarveyZh** [comment]
您好，请问可以在什么地方找到about:config？多谢

**Comment by theowenyoung** [comment]
直接在浏览器地址栏输入： `about:config`
