### ISSUE TITLE
[Bug]: 在翻译时，偶尔会出现页面中的<code></code>代码块变为数字的问题

### ISSUE THREAD

**Issue by Tansan-CC** [immersive-translate/immersive-translate#563]
### 插件版本号 | Version

0.6.1

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

翻译时的译文偶尔会讲code块整体替换成数字
<img width="723" alt="截屏2023-06-08 14 21 09" src="https://github.com/immersive-translate/immersive-translate/assets/82657286/9de84e98-08ab-4478-b442-2288ba449591">

### 重现步骤 | To Reproduce

1. 打开https://nuxt.com/docs/getting-started/views#components
2. 翻译为中文
3. 会产生如下效果<code>Component</code>在返回后变为字符0
<img width="723" alt="截屏2023-06-08 14 21 09" src="https://github.com/immersive-translate/immersive-translate/assets/82657286/9de84e98-08ab-4478-b442-2288ba449591">

**Comment by versun** [comment]
我这边是正常的。。。。
![image](https://github.com/immersive-translate/immersive-translate/assets/2398708/1bf52ac2-7353-490b-929c-960f54d4ed4e)
你试一试重新安装下插件？

**Comment by theowenyoung** [comment]
@versun 微软翻译确实会这样，下个版本修复~

**Comment by theowenyoung** [comment]
v0.6.19已修复
