### ISSUE TITLE
[Bug]: 设置当鼠标悬停 + Ctrl 翻译该段 失效

### ISSUE THREAD

**Issue by tomomuy** [immersive-translate/immersive-translate#564]
### 插件版本号 | Version

0.5.14

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

插件设置当鼠标悬停时 + Crtl键翻译该段后，使用Ctrl + F对网页进行搜索后，变成了鼠标悬停时翻译，刷新网页可重置

### 重现步骤 | To Reproduce

1. 将快捷键设置为  Crtl键 
  Go to https://github.com/immersive-translate/immersive-translate
2. 按下 Ctrl + F 进行搜索
3. 将鼠标移至英文区域，会自动翻译

### 补充说明 | Additional context

![image](https://github.com/immersive-translate/immersive-translate/assets/116566664/2e4fa74e-616d-4a83-9668-f96515f3e1e3)

**Comment by versun** [comment]
升级下插件哈

**Comment by tomomuy** [comment]
已升级至0.6.1，仍存在此问题

**Comment by duoluodexiaoxiaoyuan** [comment]
我在使用的过程中其实这种情况也会偶尔发生，这个时候可能鼠标移动到文字上再按一下就出现了，或者重新刷新网页就好了，这个偶发的情况，我也不知道是脚本的问题还是自己操作不当的问题，你也可以试一下我的方法

**Comment by tomomuy** [comment]
@duoluodexiaoxiaoyuan 谢谢，不过我是只要Ctrl+F一直保持搜索状态，这个问题就一直存在，目前通过更改其他快捷键避免了这个bug

**Comment by theowenyoung** [comment]
可以复现～ 下个版本修复哈。

具体复现条件：

当按住 ctrl 一会儿（2秒）之后，才按下 f键，此时 页面不需要按ctrl也会翻译段落。

**Comment by theowenyoung** [comment]
v0.6.19已修复
