### ISSUE TITLE
对不同网站设置不同的默认的翻译模式(仅显示译文/双语模式)

### ISSUE THREAD

**Issue by wongchenv** [immersive-translate/immersive-translate#565]
### 您希望的更新和改进是什么 | Update or Improve

对不同网站设置不同的默认的翻译模式(仅显示译文/双语模式)

### 补充说明 | Additional context

在大多数情况下我使用双语模式模式, 但在一些个别网站双语模式非常干扰阅读, 如slack, discord之类.
在当前, 每次使用slack, discord等网站都需要再手动切换一下插件的翻译模式, 略微麻烦. 所以希望可以对不同网站自定义默认的翻译模式.

**Comment by theowenyoung** [comment]
> 这类网站建议只翻译聊天区域。。。菜单啥的就不用了（现在确实干扰阅读），那几个词认的全。。

现在应该就是只翻译聊天内容的，你那里不是吗？

**Comment by theowenyoung** [comment]
如果有相关网站，可以贴在这个 issue 下面： https://github.com/immersive-translate/immersive-translate/issues/212

我们做一下适配。
