### ISSUE TITLE
界面设置 允许增加缩进

### ISSUE THREAD

**Issue by jiangying000** [immersive-translate/immersive-translate#567]
### 您希望的更新和改进是什么 | Update or Improve

界面设置 允许增加缩进 可以更强烈的区分原文和译文

### 补充说明 | Additional context

减少视觉干扰

**Comment by theowenyoung** [comment]
现有的译文样式都没法满足你的需求是吗～

**Comment by theowenyoung** [comment]
抱歉这么晚回复，其实【引用样式】已经包含了缩进，为了保持工具的简单易用性，目前还是没有计划增加该特性。
