### ISSUE TITLE
[Bug]: 无法翻译。

### ISSUE THREAD

**Issue by zhanghengxin** [immersive-translate/immersive-translate#568]
### 插件版本号 | Version

0.6.1

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

任何网站都无法翻译。
重置后，点击翻译还是无法翻译。
切换任何翻译服务，还是无法翻译。

### 重现步骤 | To Reproduce

![image](https://github.com/immersive-translate/immersive-translate/assets/24197448/6baadd3f-f721-4eb9-b372-fc56b534c102)
翻译按钮无法点动。

**Comment by versun** [comment]
我这边可以用, 可能你的插件之间有冲突, 你试一试把其他插件都禁用下看看能不能用

**Comment by theowenyoung** [comment]
今天看到群里也有一位用户反馈这个问题，有可能哪里真的有问题？

可以在扩展管理页面，点击 开启开发者模式，然后找到沉浸式翻译，开启收集错误，然后查看是否有任何错误。

这是个新装的扩展吗？

**Comment by chenqianhe** [comment]
也遇到了这个问题

**Comment by chenqianhe** [comment]
> 也遇到了这个问题

更新浏览器又好了

**Comment by tanpaper** [comment]
> 我这边可以用, 可能你的插件之间有冲突, 你试一试把其他插件都禁用下看看能不能用

确实是有冲突，我的版本是0.6.7，它在YouTube上面和Language Reactor 冲突，必须关闭Language Reactor 才能继续使用
