### ISSUE TITLE
翻译后能否关闭译文

### ISSUE THREAD

**Issue by kingzzkxyink** [immersive-translate/immersive-translate#57]
翻译后能否关闭译文，做到沉浸式翻译。

**Comment by kingzzkxyink** [comment]
翻译后不显示译文，而是直接类似谷歌浏览器自带翻译的效果。

**Comment by theowenyoung** [comment]
你想问的是不显示原文吧？

**Comment by kingzzkxyink** [comment]
> 

对的，是这个意思。请问能实现吗？

**Comment by theowenyoung** [comment]
好吧，我研究一下。

**Comment by kingzzkxyink** [comment]
> 好吧，我研究一下。

好的，感谢。

**Comment by crocodile2021** [comment]
和这个issue重复了https://github.com/immersive-translate/immersive-translate/issues/59，隐藏原文功能后续会添加，谢谢关注～
