### ISSUE TITLE
中英文之间添加空格

### ISSUE THREAD

**Issue by kahosan** [immersive-translate/immersive-translate#570]
### 您希望的更新和改进是什么 | Update or Improve

部分翻译服务是默认进行了排版
但有些没有排版的希望可以优化一下中英文的排版，也许可以使用 [pangu](https://github.com/vinta/pangu.js) 这个库

**Comment by theowenyoung** [comment]
（有点不确定该不该这样做...

**Comment by kahosan** [comment]
可以先讨论一下，我个人觉得排版后的阅读体验是会比较 ok 的

**Comment by hubery055** [comment]
支持，word也是这样做的

**Comment by theowenyoung** [comment]
沉浸式翻译的首要目标是保持工具简单易用，所以目前还是没有计划增加这个特性哈。
