### ISSUE TITLE
[Bug]:翻译特定epub无法导出 

### ISSUE THREAD

**Issue by gitous** [immersive-translate/immersive-translate#572]
### 插件版本号 | Version

0.6.1

### 平台 | Platform

Windows, iOS, Android

### 浏览器 | Browsers

Chrome, Other

### 插件类型 | Extension Type

浏览器插件 | Browser Extension, 油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

翻译本地epub功能翻译该epub文件时翻译正常，导出就一直卡住了
试过ios，android狐猴浏览器装chrome插件，windows chrome插件模式，firefox插件模式
使用的软件版本0.6.1与0.6.2
[test book.zip](https://github.com/immersive-translate/immersive-translate/files/11712413/test.book.zip)

### 重现步骤 | To Reproduce

1、任意平台（包括但不限于iOS android win下的chrome与firefox）打开翻译epub模式
2、翻译
3、翻译完成点导出，然后就一直卡住了

**Comment by theowenyoung** [comment]
好的～ 我研究下。

**Comment by theowenyoung** [comment]
下个版本修复～

**Comment by theowenyoung** [comment]
v0.6.19 已发布，已解决该问题。
