### ISSUE TITLE
按场景自动默认切换翻译服务

### ISSUE THREAD

**Issue by RedwindA** [immersive-translate/immersive-translate#573]
### 您希望的更新和改进是什么 | Update or Improve

允许在不同的翻译场景中默认使用不同的翻译引擎，比如全文翻译使用谷歌，鼠标划过使用chatgpt web 翻译

**Comment by keyboard3** [comment]
0.8.0 已支持可以独立设置翻译服务。包括输入增强和鼠标悬停
