### ISSUE TITLE
[Bug]: 折叠页面折叠部分无法自动翻译

### ISSUE THREAD

**Issue by unclehuo** [immersive-translate/immersive-translate#576]
### 插件版本号 | Version

0.6.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

**折叠界面英文无法自动翻译，需要再显示原文重新翻译。不知道是我使用设置问题还是BUG。**

- **全部折叠界面**

![image](https://github.com/immersive-translate/immersive-translate/assets/124486532/b7489c1f-3684-4b51-b629-9c2ddf5bce08)
- **打开第一个**

![image](https://github.com/immersive-translate/immersive-translate/assets/124486532/26036ec8-0180-40b3-abf5-f750224308fa)
- **打开第二个**

![image](https://github.com/immersive-translate/immersive-translate/assets/124486532/bd0f8c13-dd13-42d9-be97-16cf4550c09a)

### 重现步骤 | To Reproduce

https://tryhackme.com/room/contentdiscovery 打开翻译即可

**Comment by versun** [comment]
@unclehuo 
这是因为打开task的时候网页才加载内容, 插件才能获取到内容.
你可以打开总是翻译功能, 就会自动翻译了
![image](https://github.com/immersive-translate/immersive-translate/assets/2398708/6dc08594-ee0b-4571-b806-f8ddba5b1052)
