### ISSUE TITLE
[Bug]: quora 无法翻译

### ISSUE THREAD

**Issue by qianweikhm** [immersive-translate/immersive-translate#578]
### 插件版本号 | Version

0.6.5

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

Quora 网站，打开评论以后，评论的内容无法进行翻译

**Comment by theowenyoung** [comment]
请问有具体链接吗？

**Comment by keyboard3** [comment]
新版0.6.6+已经解决该问题
