### ISSUE TITLE
翻译一个页面中部分文本

### ISSUE THREAD

**Issue by aoaim** [immersive-translate/immersive-translate#58]
希望能对一个页面中的部分段落进行翻译，目前似乎只能全文都翻译？部分翻译的话可能可以减少 too many request 报错的次数，也可以减轻一下 api 的使用量。谢谢！

**Comment by theowenyoung** [comment]
目前支持在开发者配置里面做一些针对特定网站，翻译特定区域的功能： <https://immersive-translate.owenyoung.com/advanced>

但是比较需要开发人员技能才能用。


我有计划添加一个上下文菜单，来翻译选中的的段落。但是这个人是一次性的。不知道能不能满足。

**Comment by aoaim** [comment]
好的，谢谢开发者！
