### ISSUE TITLE
输入框翻译功能，希望提供独立的总控开关

### ISSUE THREAD

**Issue by wang20150419** [immersive-translate/immersive-translate#581]
### 您希望的更新和改进是什么 | Update or Improve

输入框翻译功能使用的感觉很好。但是，需要把当前网页设置为自动翻译，才能使用。

希望能把这个功能和 自动翻译该网页 解耦，独立出来，用一个开关控制。

也就是不管该网页是否启用了侵沉式翻译功能，均能启用输入框翻译功能。

**Comment by theowenyoung** [comment]
最新版本已支持。
