### ISSUE TITLE
建议优化bart输入增强的界面显示

### ISSUE THREAD

**Issue by sh3300** [immersive-translate/immersive-translate#584]
### 您希望的更新和改进是什么 | Update or Improve

![image](https://github.com/immersive-translate/immersive-translate/assets/11268717/15f017e1-dbc7-467e-abf2-fce0328a7236)

输入增强真的非常实用，但我在bard上使用输入增强功能后输入框样式会有点问题，另外发送按钮也是灰的认为没有内容，要按一下空格才能发送，建议可以优化一下，感谢！

**Comment by theowenyoung** [comment]
0.6.10 版本已优化
