### ISSUE TITLE
[Bug]: figma兼容性bug

### ISSUE THREAD

**Issue by FunnyPCCCC** [immersive-translate/immersive-translate#585]
### 插件版本号 | Version

0.6.8

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

插件运行时，Figma拖动画布(空格键)白屏，关闭插件后正常

### 重现步骤 | To Reproduce

1.打开插件
2.访问Figma并打开任意草稿
3.按住空格键同时长按鼠标左键拖动画布
4.问题出现：画板区域白屏

**Comment by theowenyoung** [comment]
应该是和输入框的空格键监听冲突了？

我刚刚把figma 排除了，现在试试呢？
