### ISSUE TITLE
[Bug]:输入框增强功能bug

### ISSUE THREAD

**Issue by xinzeyi** [immersive-translate/immersive-translate#587]
### 插件版本号 | Version

0.6.10

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

 在github搜索栏使用插件的输入框增强功能时，按下三下空格翻译的内容显示空白，实际翻译的内容存在。

**Comment by theowenyoung** [comment]
我这里测试是ok 的：

<img width="359" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/faebb790-79c4-498c-b300-3f3ef911f4d3">

可以截图说明一下吗？或者录屏？

**Comment by xinzeyi** [comment]
ok，截图给你，这是翻译之前的：
这是翻译之后的情况：
这是回车删掉一个空格之后的情况：
 
发件人： Owen
发送时间： 2023-06-15 12:36
收件人： immersive-translate/immersive-translate
抄送： xinzeyi; Author
主题： Re: [immersive-translate/immersive-translate] [Bug]:输入框增强功能bug (Issue #587)
我这里测试是ok 的：
可以截图说明一下吗？或者录屏？

**Comment by theowenyoung** [comment]
邮件发送的回复似乎没有图片..?

**Comment by xinzeyi** [comment]
我用的是foxmail客户端回的信息

**Comment by xinzeyi** [comment]
1.这是翻译之前的情况：
![QQ截图20230615121309](https://github.com/immersive-translate/immersive-translate/assets/70065876/90c3819a-4730-4f47-873a-86734a93f23f)
2.这是翻译之后的情况：
![QQ截图20230615121406](https://github.com/immersive-translate/immersive-translate/assets/70065876/35d73d63-3f3b-4691-9a9d-0bb48765612a)
3.这是回车删掉一个空格之后的情况：
![QQ截图20230615124937](https://github.com/immersive-translate/immersive-translate/assets/70065876/bf6423bc-f8ee-41d5-ab1e-872da087e425)

**Comment by theowenyoung** [comment]
这个的搜索框所在的页面地址是？

**Comment by xinzeyi** [comment]
主页面
![QQ截图20230615132117](https://github.com/immersive-translate/immersive-translate/assets/70065876/2c1eb6de-f53d-4fa5-83a5-880f6148feae)

**Comment by theowenyoung** [comment]
确实，已复现～

下个版本修复，正在发版了
