### ISSUE TITLE
[Bug]: 0.6.10版本制作双语epub时会设置图片宽高为一个很小的值

### ISSUE THREAD

**Issue by fairjm** [immersive-translate/immersive-translate#588]
### 插件版本号 | Version

0.6.10

### 平台 | Platform

Windows

### 浏览器 | Browsers

Other

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

使用0.6.10的浏览器为vivaldi 0.5.5的浏览器为chrome

在0.6.10版本翻译时 发现插件自动加入了width和height 导致生成的epub的图片很小
```html
<img alt="Figure 3.1: Adding a XAML page" src="image/Figure_3.1_B16588.jpg" width="186.140625" height="16" data-immersive-translate-effect="1" data-immersive_translate_walked="a99b4a34-8653-4180-a805-5a5a8040c0b9">
```
而在0.5.5版本中图片没有进行处理 保持了原样
```html
<img alt="Figure 3.1: Adding a XAML page" src="image/Figure_3.1_B16588.jpg">
```

### 重现步骤 | To Reproduce

1.更多中 选择制作双语epub电子书 
2.导入电子书 翻译 后查看元素 发现img被添加了width和height

**Comment by fairjm** [comment]
在尝试将这段内容保存到本地html 翻译时 发现并没有加上宽高
```html
<img alt="Figure 3.1: Adding a XAML page" src="image/Figure_3.1_B16588.jpg" data-immersive-translate-effect="1" data-immersive_translate_walked="8c2184ee-060b-486b-bca4-e613b90aa2c0">
```
可能是制作epub下的额外行为？

**Comment by fairjm** [comment]
另外一种复现方式是正常翻译一个网页 比如这个issue页
然后编辑去除其中一个图片的长宽 比如我的头像
```
<img class="avatar rounded-2 avatar-user" src="https://avatars.githubusercontent.com/u/4281721?s=80&amp;u=34fad121d60ac48fbf7227693c0da2ad0bb79f47&amp;v=4" width="40" height="40" alt="@fairjm" data-immersive-translate-effect="1" data-immersive_translate_walked="a5afcec1-8f8b-49dd-9e8e-c47b24b9e534">
```
变为
```
<img class="avatar rounded-2 avatar-user" src="https://avatars.githubusercontent.com/u/4281721?s=80&amp;u=34fad121d60ac48fbf7227693c0da2ad0bb79f47&amp;v=4" alt="@fairjm" data-immersive-translate-effect="1" data-immersive_translate_walked="a5afcec1-8f8b-49dd-9e8e-c47b24b9e534">
```
![image](https://github.com/immersive-translate/immersive-translate/assets/4281721/6521f55a-c8ff-4669-bf06-2bfca221ecbb)

在页面元素发生变化的情况下 比如我提交了一下评论 或者编辑评论
图片的宽高会被自动加上


epub编辑下无法获取图片 所以应该是使用了错误的图片尺寸
![image](https://github.com/immersive-translate/immersive-translate/assets/4281721/978239fa-ea57-43bf-91ae-de9ed04eebc7)

**Comment by theowenyoung** [comment]
感谢反馈，下个版本修复。

**Comment by theowenyoung** [comment]
这也可能是vivaldi 独有的问题，我记得chrome下img会返回 0，0的大小，这个时候就不会写入宽高。

**Comment by fairjm** [comment]
> 这也可能是vivaldi 独有的问题，我记得chrome下img会返回 0，0的大小，这个时候就不会写入宽高。

嗯 之前用vivaldi制作过一本 没有问题 今天发现了这个问题 
但刚好今天vivaldi升了级顺带他同步了最新的插件版本 变量有点多...

使用chrome的老版本没有问题 我后续再观察下 :)

**Comment by theowenyoung** [comment]
图片的宽高自动添加这个是有意的行为，因为有些图片在译文里复制后，由于原网页对图片的宽高的样式是作用在原文的地方的，很多时候译文部分的图片是没有样式的，所以图片会按照原始大小展示，所以我们对图片做了一个特殊处理.

比如这样的样式：
```
p > img {
 width: 48px;
}
```

**Comment by theowenyoung** [comment]
但是对 epub 制作来说，这个图片一般不需要修改，下个版本在epub制作中 会去掉这个行为。

**Comment by theowenyoung** [comment]
已修复哈
