### ISSUE TITLE
[Bug]: pdf翻译排版问题导致字符区域覆盖

### ISSUE THREAD

**Issue by volador16** [immersive-translate/immersive-translate#589]
### 插件版本号 | Version

0.6.12

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

<img width="1192" alt="截屏2023-06-15 下午2 28 03" src="https://github.com/immersive-translate/immersive-translate/assets/19202192/4e974912-9ded-4226-b550-0d8254556825">

**Comment by keyboard3** [comment]
该重叠问题 试下0.6.13
