### ISSUE TITLE
希望能不显示原文

### ISSUE THREAD

**Issue by xfdyd** [immersive-translate/immersive-translate#59]
现在只有这个扩展能用，所以希望加个设置，不显示原文。

**Comment by leikes** [comment]
不显示原文跟普通翻译一样，所以这才叫做沉浸式翻译。

**Comment by JuchiaLu** [comment]
> 不显示原文跟普通翻译一样，所以这才叫做沉浸式翻译。

多数时候并不需要所有段落都要比对原文，所有的段落都显示原文太占地方，只有当某些句子翻译不通顺时才需要看原文。希望做到鼠标放上某句子后弹框显示原文，并且高亮译文句子，这样更好。

**Comment by theowenyoung** [comment]
正在研究方案，因为之前这个扩展是为了解决双语翻译的问题。没想到用户变多之后有相当多的用户希望能隐藏原文，所以这里还是加一个切换到只显示译文的功能。

> 希望做到鼠标放上某句子后弹框显示原文，并且高亮译文句子，这样更好。

嗯，这个也有计划，会在译文开头加一个 低调 的按钮，可以做一些动作，比如该段使用别的翻译服务进行翻译，以便对照等等。

**Comment by zhuliangyu** [comment]
对于我个人体验来说, 我阅读机翻的文档是无法做到不看原文的, 中英文上下对照翻译反而是我推荐这款软件的原因. 
如果是希望不显示原文的翻译, 我觉得Google 内置的全文翻译功能, 已经做的非常出色.

**Comment by JuchiaLu** [comment]
> 对于我个人体验来说, 我阅读机翻的文档是无法做到不看原文的, 中英文上下对照翻译反而是我推荐这款软件的原因. 如果是希望不显示原文的翻译, 我觉得Google 内置的全文翻译功能, 已经做的非常出色.

谷歌浏览器内置翻译太单纯，要么全显示译文，要么全显示原文，为了看某一句原文切回去再切回来，段落会错位，找很久才能找到原来的位置，我看的英文书籍或国际标准一般都成百上千页（PDF 转 Html 后翻译），全文显示双语不太好。

**Comment by xfdyd** [comment]
> 不显示原文跟普通翻译一样，所以这才叫做沉浸式翻译。

嗯。我并不需要，只是因为其他谷歌扩展都挂了，想找个支持必应的扩展。

**Comment by weykon** [comment]
不显示原文不是直接使用Chrome的翻译功能一样吗

**Comment by xfdyd** [comment]
> 

是的。谷歌翻译不是不能用了嘛。

**Comment by xfdyd** [comment]
> 不显示原文不是直接使用Chrome的翻译功能一样吗

是的。谷歌翻译不是不能用了嘛。

**Comment by weykon** [comment]
> > 不显示原文不是直接使用Chrome的翻译功能一样吗
> 
> 是的。谷歌翻译不是不能用了嘛。
 
你说的是网络问题吗，代理换个好节点嘛

**Comment by XiaoYingYo** [comment]
**加急,立马把谷歌翻译换了**

**Comment by billng** [comment]
强烈建議添加 "隱藏原文" 的選項!!! 請求給用戶多一個選擇. 理由如下:

- 可以省去多安裝一個 Google Translate 擴展
- 雙語對照在朗讀文字時非常困擾, 因爲我只需要朗讀中文
- 如果能夠針對每一個段落, 單獨地對該段落開/關對照翻譯, 更好!
- 如果能夠針對每一個段落, 單獨地對該段落切換翻譯引擎, 更好!

**Comment by weykon** [comment]
我是从Google Translate 扩展到使用这个库的插件，我使用Google Translate 对英语的学习一点进展都没有，使用这个库的插件还能学学英语，同时看英文和中文能更快的看懂原文，因为翻译大多数时候会有不能达到英文原文的意思。
工具是辅助，进步是自己的。

**Comment by billng** [comment]
> 我是從Google Translate 擴展到使用這個庫的外掛程式，我使用Google Translate 對英語的學習一點進展都沒有，使用這個庫的外掛程式還能學學英語，同時看英文和中文能更快的看懂原文，因為翻譯大多數時候會有不能達到英文原文的意思。 工具是輔助，進步是自己的。

我完全同意你的觀點. 雙語對照的確對於學習是很有幫助的. 我看原文是沒有問題的, 但是始終沒有母語全中文來的快和舒適. "關閉原文" 僅僅是出於效率的目的, 並不是為了學習. 希望作者給用戶多一個選項, "關閉原文" 太有必要了.

**Comment by keyboard3** [comment]
0.5.11 已支持隐藏原文

**Comment by nljxlove** [comment]
> 0.5.11 已支持隐藏原文

在哪设置隐藏原文呢？我是[0.7.14]版本

**Comment by Dzs-HF** [comment]
在界面设置最下面有个当网站为下列域名时，总是使用 ⌈无⌋ 译文样式。点击添加 URL里输入 *.*.* 保存就可以只显示译文了

**Comment by GF-Huang** [comment]
1.15.2 怎么隐藏原文？

![Image](https://github.com/user-attachments/assets/a4dc424e-0522-4cea-b99b-074153b17356)

**Comment by keyboard3** [comment]
> 1.15.2 怎么隐藏 PDF 原文？
> 
> ![Image](https://github.com/user-attachments/assets/a4dc424e-0522-4cea-b99b-074153b17356)

PDF 对照页面不支持隐藏原文
