### ISSUE TITLE
[Bug]: code字体大小有误

### ISSUE THREAD

**Issue by hibichann** [immersive-translate/immersive-translate#593]
### 插件版本号 | Version

0.6.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![GX4PFV3$3 SG @}$JC9M(GA](https://github.com/immersive-translate/immersive-translate/assets/17671678/c8f5f2e7-87f7-4887-b09a-334e1a0ef441)

### 重现步骤 | To Reproduce

所有类似地方，code字体大小不对

**Comment by theowenyoung** [comment]
提供一下网址可以吗？

**Comment by hibichann** [comment]
@theowenyoung https://github.com/vuejs/core/pull/8328
使用的 加粗 样式

**Comment by theowenyoung** [comment]
好吧，这种可能不太好弄，因为原网页的样式比较严格，仅适用于原文的code，译文里的code没有应用到它的样式.

这个不太好做适配，暂时就不修了哈~ 感谢报告。
