### ISSUE TITLE
[Bug]: Throws the error when entering a value in an input element using auto-completion

### ISSUE THREAD

**Issue by PinkChampagne17** [immersive-translate/immersive-translate#594]
### 插件版本号 | Version

0.6.10

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

The console outputs `Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')`.

### 重现步骤 | To Reproduce

1. Click an input element.
2. Enter a value using auto-completion(aka autofill).
3. The error is thrown.

### 补充说明 | Additional context

This bug may be related to [Issue 904420: Selecting autocomplete suggestion for form input element fires keydown event with event.key undefined.](https://bugs.chromium.org/p/chromium/issues/detail?id=904420)

Stack trace:

![debugger_screenshot](https://github.com/immersive-translate/immersive-translate/assets/45930107/173275bd-a325-49da-a2b0-80da1e4a3ae6)

![debugger_screenshot](https://github.com/immersive-translate/immersive-translate/assets/45930107/50226e72-6ff8-4512-b8ab-42163fa4898d)

```javascript
function zE(e, t, n) {
  let u = e.code.toLowerCase()
    , a = e.key.toLowerCase()
    , r = e.keyCode
    , o = n[t] || [];
  return r === 229 && t !== "space" ? !1 : !!(o.includes(u) || o.includes(a) || u === t || a === t)
}
```

```javascript
function i(l) {
  if (Ou) {
    return;
  }
  const c = l;
  const d = c.target || c.srcElement;
  const m = d?.tagName;
  (d?.isContentEditable || m == "INPUT" || m == "SELECT" || m == "TEXTAREA") &&
    (zE(l, a.triggerKey, a.codePrefixAlias) ? s(l) : (r = 0));
}
```

**Comment by theowenyoung** [comment]
感谢～ 我加一个兼容。

**Comment by theowenyoung** [comment]
最新版本应该可以了～
