### ISSUE TITLE
同步配置的方式希望能添加坚果云之类的

### ISSUE THREAD

**Issue by small-ora** [immersive-translate/immersive-translate#599]
### 您希望的更新和改进是什么 | Update or Improve

同步配置的方式希望能添加坚果云之类的云盘；
有些场景可能不太方便使用科学上网，所以没办法使用google drive；
感谢您的开发。

**Comment by wongchenv** [comment]
我多个浏览器同时使用, 同步问题也挺麻烦.

**Comment by keyboard3** [comment]
0.8.0 已支持登录用户自动多设备同步设置
