### ISSUE TITLE
[Feature Request]: Hope to support self-built translation API

### ISSUE THREAD

**Issue by missuo** [immersive-translate/immersive-translate#60]
I hope we can support self-built translation API, such as `DeepL` **self-built API**.

**Comment by theowenyoung** [comment]
Ok, I'll add it at next version.

**Comment by GrayXu** [comment]
It appears that this feature has not been implemented yet. Should we reopen the enhancement issue?

**Comment by missuo** [comment]
@GrayXu It actually already supports it. If you are using something other than DeepLX, your self-built API's Request and Response will work as long as they are consistent with DeepLX.

[https://github.com/OwO-Network/DeepLX#setup-on-immersive-translate](https://github.com/OwO-Network/DeepLX#setup-on-immersive-translate)

**Comment by GrayXu** [comment]
@missuo Thank you very much! This great feature should be included in the documents, not just in the changelog :)
