### ISSUE TITLE
[Bug]: 输入框增强模式下，GPT输出只有英语，没有双语

### ISSUE THREAD

**Issue by stanleyssss** [immersive-translate/immersive-translate#601]
### 插件版本号 | Version

0.6.12

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在我使用输入框增强模式下，GPT输出只有英语，没有双语，请问怎么解决？截图如下：
<img width="737" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/135083345/cc0e24b9-fcf2-4e08-ab69-eeb205b6b183">

**Comment by theowenyoung** [comment]
需要对该网页开启翻译才行。永远翻译该网页 或者自动翻译英语

**Comment by stanleyssss** [comment]
明白了，非常感谢！
