### ISSUE TITLE
[Bug]: Checkbox got hidden or some button unable to click after translation

### ISSUE THREAD

**Issue by triet205** [immersive-translate/immersive-translate#603]
### 插件版本号 | Version

0.6.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

When I use 1688 website, there are 2 checkboxes for Gender selection (Mr. and Mrs.), but when I choose to translate, just only 1 checkbox left and the name become "Mr. Mrs", you can refer to the attachments.

Before:
![Checkbox_Before](https://github.com/immersive-translate/immersive-translate/assets/9526143/3cfdca80-b847-44ad-867e-9eea1edf7963)
After:
![Checkbox_After](https://github.com/immersive-translate/immersive-translate/assets/9526143/769c382e-9e44-454d-9ca3-dce8037c543e)

And when I use the delete button in shopping cart, the original shows that there are 2 buttons are Delete and Cancel, but when I turn on the translation, there is no button left, just only a plain text translation, I also put in attachments.

Before:
![Button_Before](https://github.com/immersive-translate/immersive-translate/assets/9526143/1dc8632c-8339-40ba-ab16-77e4174bddd7)
After:
![Button_After](https://github.com/immersive-translate/immersive-translate/assets/9526143/02704202-7c4c-4f6c-a63d-e200d257d566)

### 出现问题的网址 | URL

1688.com

### 重现步骤 | To Reproduce

For first issue, you can create an account and go to account management link and turn on translation.
https://work.1688.com/home/page/index.htm?#app/accountmanagement//

For second issue, you can add some product and go to shopping cart, then turn on translation then click on Trash button next to the product.

**Comment by theowenyoung** [comment]
Hello, this is a known issue, because the translation we are using now is a plain text translation, so when you use the translation-only mode, some styles will be lost, it is recommended to use the bilingual translation mode, which can retain the original text. We will optimize the translation-only mode later.

**Comment by triet205** [comment]
> 

Got it, thank you very much for the reply. Looking forward for the fix. The extension is very helpful.

**Comment by Root-FTW** [comment]
> Hola, este es un problema conocido, porque la traducción que estamos utilizando ahora es una traducción de texto plano, por lo que cuando se utiliza el modo de sólo traducción, algunos estilos se perderán, se recomienda utilizar el modo de traducción bilingüe, que puede conservar el texto original. Optimizaremos el modo sólo traducción más adelante.

I have exactly the same problem, I will be looking forward to the update that fixes this :D

**Comment by keyboard3** [comment]
抱歉时间过去很久，这个问题应该已经修复，你可以更新下插件
