### ISSUE TITLE
能否支持第三方OpenAI接口代理的URL，就是类似下面网址这样的

### ISSUE THREAD

**Issue by himonster1** [immersive-translate/immersive-translate#605]
### 您希望的更新和改进是什么 | Update or Improve

https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/README_CN.md#base_url-%E5%8F%AF%E9%80%89

因为我用的不是官方的api，官方的申请不下来API，用的是二道贩子的

**Comment by theowenyoung** [comment]
已支持的，请查看文档：

https://immersivetranslate.com/docs/services/openai/#%E8%87%AA%E5%AE%9A%E4%B9%89-openai-%E7%9A%84-api-%E5%9C%B0%E5%9D%80

**Comment by himonster1** [comment]
看见了 谢谢
