### ISSUE TITLE
建议增加对选中文字进行翻译的功能

### ISSUE THREAD

**Issue by shing-yu** [immersive-translate/immersive-translate#607]
### 您希望的更新和改进是什么 | Update or Improve

如题，建议增加对选中文字进行翻译的功能，可以添加到右键菜单。
同时，还可以增加一个可选的，选中非目标语言自动弹出翻译的功能，类似于Google翻译插件，可以在选中部分内容后自动翻译并弹出翻译后的结果。

### 补充说明 | Additional context

感谢各位的辛苦付出！( •̀ ω •́ )✧

**Comment by hhaishen** [comment]
同求，这个功能非常实用！

**Comment by chachako** [comment]
~~其实是不是已经有这个功能了？~~
<img width="326" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/58068445/ffbaab2d-7eed-43c7-8d1b-731ff6dcfb9c">
<img width="688" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/58068445/b9c674f8-787c-4213-afd8-83828fcf9b0b">

**Comment by xing-yv** [comment]
> ~~其实是不是已经有这个功能了？~~
> <img width="326" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/58068445/ffbaab2d-7eed-43c7-8d1b-731ff6dcfb9c">
> <img width="688" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/58068445/b9c674f8-787c-4213-afd8-83828fcf9b0b">
> 

这个我知道且在用，只是如果有多段要翻译，有不想翻译网页 还是要选中翻译
（另外，我更想要的还是类似谷歌翻译的选中非目标语言自动翻译并弹出的功能）

**Comment by keyboard3** [comment]
暂无计划增加此功能
