### ISSUE TITLE
[Bug]: PDF文件翻译后，部分行未完整显示，出现切割现象，具体见截图

### ISSUE THREAD

**Issue by feng9152** [immersive-translate/immersive-translate#609]
### 插件版本号 | Version

0.6.15

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

<img width="1221" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/20027716/520716e7-81ff-478b-bcf9-09b67a8b9af7">

**Comment by theowenyoung** [comment]
可以手动点击译文被切割的地方，调整边框大小～

**Comment by keyboard3** [comment]
能附上pdf吗，我们check下，看看能不能优化。0.6.16 应该已经处理了

**Comment by szlysms** [comment]
我这里也是，版本0.6.16仍然未解决，甚至有的页每一行都是这样
![image](https://github.com/immersive-translate/immersive-translate/assets/99026228/9fe58a5f-38ea-4edf-a431-305d634257db)
这是我的用的pdf文件：https://www.logicmatters.net/resources/pdfs/LogicStudyGuide.pdf
貌似只有在在翻译一些带有特殊样式的文本时才会有这些问题，比如目录（尤其是有跳转功能的目录，几乎必定会有这个bug

**Comment by szlysms** [comment]
我这里也是，版本0.6.16仍然未解决，甚至有的页每一行都是这样
![image](https://github.com/immersive-translate/immersive-translate/assets/99026228/9fe58a5f-38ea-4edf-a431-305d634257db)
这是我的用的pdf文件：https://www.logicmatters.net/resources/pdfs/LogicStudyGuide.pdf
貌似只有在在翻译一些带有特殊样式的文本时才会有这些问题，比如目录（尤其是有跳转功能的目录，几乎必定会有这个bug

**Comment by keyboard3** [comment]
下个版本修复，针对单行显示不进行限制高

**Comment by keyboard3** [comment]
> 我这里也是，版本0.6.16仍然未解决，甚至有的页每一行都是这样 ![image](https://user-images.githubusercontent.com/99026228/247828438-9fe58a5f-38ea-4edf-a431-305d634257db.png) 这是我的用的pdf文件：https://www.logicmatters.net/resources/pdfs/LogicStudyGuide.pdf 貌似只有在在翻译一些带有特殊样式的文本时才会有这些问题，比如目录（尤其是有跳转功能的目录，几乎必定会有这个bug

0.6.19 版本修复，针对单行显示不进行限制高

**Comment by keyboard3** [comment]
0.6.19 版本修复，针对单行显示不进行限制高
