### ISSUE TITLE
GitHub 中很多地方都没有翻译到

### ISSUE THREAD

**Issue by Pauluooooo** [immersive-translate/immersive-translate#61]
例如菜单，侧边栏等等

**Comment by ublock-ghost** [comment]
我的GitHub都没显示悬浮球，快捷键也没用

**Comment by theowenyoung** [comment]
> 我的GitHub都没显示悬浮球，快捷键也没用

你可能用的油猴插件不支持注入github，换个油猴插件或浏览器。比如 Firefox Nightly

**Comment by ublock-ghost** [comment]
> > 我的GitHub都没显示悬浮球，快捷键也没用
> 
> 你可能用的油猴插件不支持注入github，换个油猴插件或浏览器。比如 Firefox Nightly

可以了，感谢
