### ISSUE TITLE
单个字词的手动处理

### ISSUE THREAD

**Issue by dongrentianyu** [immersive-translate/immersive-translate#610]
### 您希望的更新和改进是什么 | Update or Improve

有一些短语或者缩略语不能很好地翻译出来，比如程序员讨论时常用的PR，其意思是Pull requests，也就是提交请求。但时常翻译成公关，而公关这个词语现在好像也有特别的涵义了，就很冲突。

希望可以用户自定义一些字词翻译，比如对tiddlywiki，这种专门名词，直接给定用户设置的，而不是音译，不然看着怪怪的。

**Comment by theowenyoung** [comment]
和 #91 重复，暂时先关掉了，在那里统一讨论哈～
