### ISSUE TITLE
输入框翻译适配一下手机端狐猴浏览器吧

### ISSUE THREAD

**Issue by luchao900** [immersive-translate/immersive-translate#611]
### 您希望的更新和改进是什么 | Update or Improve

大佬，可以给手机端优化一下吗，PC端三次空格刷刷刷直接翻译很方便，很期待给手机端也适配相应的功能，软键盘敲三次空格好像不能翻译

**Comment by theowenyoung** [comment]
尝试兼容过，但是似乎搞不定。狐猴浏览器对空格键事件给出的响应不是空格键。

安卓目前可以用火狐浏览器，试一试官网打包的火狐浏览器，直接可以安装沉浸式翻译：

https://immersivetranslate.com/
