### ISSUE TITLE
[Bug]: pdf翻译格式问题

### ISSUE THREAD

**Issue by yuanzhexingtian** [immersive-translate/immersive-translate#612]
### 插件版本号 | Version

0.6.16

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/59595785/1d67f1a4-4ca6-4338-9144-edbb4c3602a8)

**Comment by keyboard3** [comment]
0.6.17+ 已经解决该问题
