### ISSUE TITLE
[Bug]: Needs to escape html

### ISSUE THREAD

**Issue by fishel-feng** [immersive-translate/immersive-translate#613]
### 插件版本号 | Version

0.6.16

### 平台 | Platform

macOS

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

The textarea html element is rendered as an textarea not text.

<img width="372" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/20787523/9d281ae1-085c-4443-ac0e-8b4781e17619">

### 出现问题的网址 | URL

https://github.com/solidjs/solid-start/discussions

### 重现步骤 | To Reproduce

Just use option+A to translate this page with <textarea>

**Comment by theowenyoung** [comment]
We will fix it next version.

**Comment by theowenyoung** [comment]
0.6.19 released, has fixed this problem.
