### ISSUE TITLE
[Bug]: 某些网页顶部导航栏无法翻译，且会影响其他翻译插件，使其出现相同的问题。

### ISSUE THREAD

**Issue by cyfxxx** [immersive-translate/immersive-translate#614]
### 插件版本号 | Version

0.6.16

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在某些网页中顶部导航栏无法被翻译，而且激活插件后，会使其它翻译插件出现相同的问题，关闭插件后其他插件能够正常翻译整个网页。

### 出现问题的网址 | URL

较多，如https://news.agpt.co/

### 重现步骤 | To Reproduce

1. 打开网页，https://news.agpt.co/
2. 在不启用该插件的情况下，使用浏览器自带翻译功能翻译网页，网页被正常翻译。
3. 启用该插件，刷新网页，使用插件或浏览器自带的翻译功能进行翻译，会发现网页顶部的导航栏内容没有被翻译。

**Comment by theowenyoung** [comment]
这是feature哈，沉浸式翻译默认情况下只翻译网页的主要内容。

如果需要翻译整个网页的话，点击【更多】，切换到翻译整个网页。

> 而且激活插件后，会使其它翻译插件出现相同的问题，关闭插件后其他插件能够正常翻译整个网页。

这个是什么意思？激活插件指的是？安装插件，但是没有点击翻译的情况下，会影响其他插件？ 如果是的话，是哪个网页以及与哪个插件有冲突？

**Comment by cyfxxx** [comment]
原来如此，抱歉是我没注意到这个功能。
关于激活插件，是指我在扩展中启用了插件但是在网页中没有点击翻译。
我只在部分网页中使用双语显示，在一般的英文网页中是直接使用谷歌浏览器的翻译功能翻译整个网页，然后就出现了一些网页顶部导航栏没有被翻译的情况。
经过测试，谷歌和微软浏览器自带的翻译功能会受到影响，别的翻译插件也会被影响，如mate translate。

**Comment by duoluodexiaoxiaoyuan** [comment]
> 如果没有翻译的内容可以试一下沉浸式翻译的鼠标悬停翻译看看能不能翻，我一般还装了一个沙拉查词结合使用。

**Comment by duoluodexiaoxiaoyuan** [comment]
> 原来如此，抱歉是我没注意到这个功能。 关于激活插件，是指我在扩展中启用了插件但是在网页中没有点击翻译。 我只在部分网页中使用双语显示，在一般的英文网页中是直接使用谷歌浏览器的翻译功能翻译整个网页，然后就出现了一些网页顶部导航栏没有被翻译的情况。 经过测试，谷歌和微软浏览器自带的翻译功能会受到影响，别的翻译插件也会被影响，如mate translate。
 如果没有翻译的内容可以试一下沉浸式翻译的鼠标悬停翻译看看能不能翻，我一般还装了一个沙拉查词结合使用。

**Comment by theowenyoung** [comment]
已修复。
