### ISSUE TITLE
[Bug]: 某份本地PDF较为特殊 会出现乱码 

### ISSUE THREAD

**Issue by ohayo-aidi** [immersive-translate/immersive-translate#616]
### 插件版本号 | Version

0.6.16

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

[IfYouCan.pdf](https://github.com/immersive-translate/immersive-translate/files/11811298/IfYouCan.pdf)
<img width="1680" alt="Screen Shot 2023-06-21 at 09 22 57" src="https://github.com/immersive-translate/immersive-translate/assets/74085268/454d9359-0d20-40cd-b39a-42cba1a8d709">
在翻译此本地PDF文件时总是乱码 同样环境其他PDF则正常

### 重现步骤 | To Reproduce

1.打开插件 选择“更多”
2.点击制作本地PDF文件
3.将此本地PDF文件拖入窗口

**Comment by keyboard3** [comment]
这是pdf本身问题，藏毒了。你拿chrome浏览器自带的PDF阅读器打开，然后选中段落复制出来也是乱码的。只能靠第三方ocr识别了，这个我们没办法处理

**Comment by ohayo-aidi** [comment]
> 这是pdf本身问题，藏毒了。你拿chrome浏览器自带的PDF阅读器打开，然后选中段落复制出来也是乱码的。只能靠第三方ocr识别了，这个我们没办法处理

好的 非常感谢
