### ISSUE TITLE
[Bug]: Feeder 中翻译不能随文章预览的变化更新

### ISSUE THREAD

**Issue by Andy-AO** [immersive-translate/immersive-translate#617]
### 插件版本号 | Version

0.6.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在 Feeder  中浏览文章的时候，右侧会出现预览，点击，不同的文章阅览会发生变化，而在 Feeder 中翻译不能随页面的变化而更新。

![image_1045](https://github.com/immersive-translate/immersive-translate/assets/38101170/08f65a70-c1c8-4273-8cad-3982b4d1cec0)

### 出现问题的网址 | URL

https://feeder.co/reader?ctx=extension

**Comment by theowenyoung** [comment]
v0.6.19 已发布，已解决该问题。
