### ISSUE TITLE
[Bug]: 飞书文档翻译会直接卡住

### ISSUE THREAD

**Issue by wangkechun** [immersive-translate/immersive-translate#618]
### 插件版本号 | Version

0.6.16

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

飞书文档开启翻译会直接卡住，chrome CPU 100%，只能杀掉进程，稍候会进程崩溃
![image](https://github.com/immersive-translate/immersive-translate/assets/4022174/fa42371c-b5e0-409d-91d6-1912cfd9b406)

### 出现问题的网址 | URL

https://bytedance.feishu.cn/docx/TXQZdeyGgoLIfexwWnEcCWd3nph

### 重现步骤 | To Reproduce

1. 打开网址
2. 右键翻译

**Comment by theowenyoung** [comment]
飞书网站本身做的太复杂了，而且文档页面里专门标识了 translate=no 属性，表示不允许翻译，卡死问题可能是双方的监听冲突了。 下个版本我直接屏蔽掉飞书吧，因为他本身也不允许别的插件翻译。

**Comment by theowenyoung** [comment]
v0.6.19 已发布。

**Comment by lcw0622** [comment]
@theowenyoung 你好，版本0.6.20看起来开启了“总是翻译”后还是会对添加了class="notranslate"的页面进行翻译，从而导致出现其他问题。这个问题有计划修复吗？

> v0.6.19 已发布。
