### ISSUE TITLE
不能翻译本地 html 文件

### ISSUE THREAD

**Issue by deweixu** [immersive-translate/immersive-translate#62]
我把一本 epub 的英文电子书修改为 zip 文件解压得到 html 文件，通过 Chrome 打开 html 使用插件并不能翻译
这样我想把翻译的文件保存覆盖再压缩或许就能得到一个双语的电子书了

**Comment by theowenyoung** [comment]
你好～ 这个使用场景其实是我制作这个扩展的初衷之一～ 所以是可以用的！

你只需要在谷歌浏览器的插件管理里，找到这个扩展，进入详情页面，然后允许扩展读取本地文件即可～


<img width="850" alt="Screenshot 2023-02-02 at 17 33 45" src="https://user-images.githubusercontent.com/62473795/216286648-ce759ab9-8f7f-4268-ba5c-dc99df0a76ec.png">

**Comment by deweixu** [comment]
可以了，谢谢，谢谢。
