### ISSUE TITLE
希望支持。

### ISSUE THREAD

**Issue by keen0309** [immersive-translate/immersive-translate#620]
### 您希望的更新和改进是什么 | Update or Improve

可以申请配置anygpt  https://getquicker.net/Sharedaction?code=41345e7b-0427-48ef-fb90-08db350ccd85 
![image](https://github.com/immersive-translate/immersive-translate/assets/103982843/7fde5ea8-6f41-4c3b-b066-c286761219df)

### 补充说明 | Additional context

可以申请配置anygpt  https://getquicker.net/Sharedaction?code=41345e7b-0427-48ef-fb90-08db350ccd85 
![image](https://github.com/immersive-translate/immersive-translate/assets/103982843/7fde5ea8-6f41-4c3b-b066-c286761219df)

**Comment by theowenyoung** [comment]
anygpt 应该是支持的呀，自定义 openai 地址就好了吧，这里似乎有文档：

<https://www.yuque.com/jamily.blog/vrf8tc/kulbx3sbqo2oz7gz?singleDoc#%20%E3%80%8A%E6%9D%BF%E5%9D%974%EF%BC%9AAnyGPT%20%E7%9B%B4%E6%8E%A5%E7%94%A8%E4%BA%8E%E5%8E%9F%E7%94%9FChatGPT%E5%BA%94%E7%94%A8%E3%80%8B>
