### ISSUE TITLE
[Bug]: 插件预览窗口宽度异常

### ISSUE THREAD

**Issue by yekuliu** [immersive-translate/immersive-translate#621]
### 插件版本号 | Version

0.6.17

### 平台 | Platform

iOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

[![pCJMpLt.md.png](https://s1.ax1x.com/2023/06/22/pCJMpLt.md.png)](https://imgse.com/i/pCJMpLt)

**Comment by Wcowin** [comment]
我也有类似的问题

**Comment by theowenyoung** [comment]
最新版已修复
