### ISSUE TITLE
[Bug]: alfred forum文本输入框无法使用输入框增强

### ISSUE THREAD

**Issue by EdwinWang0508** [immersive-translate/immersive-translate#622]
### 插件版本号 | Version

0.6.16

### 平台 | Platform

macOS

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在alfred论坛中发表新帖子或者回复的文本输入框无法使用输入框增强，触发后会复制原文，但是无法添加翻译，

搜索框的输入框增强是正常的
![iShot_2023-06-22_16 12 53](https://github.com/immersive-translate/immersive-translate/assets/64629689/599c3e08-18fb-4ebf-b7f2-132ee65a33ce)

### 出现问题的网址 | URL

https://www.alfredforum.com/

**Comment by keyboard3** [comment]
chrome 可以正常使用，Firefox 浏览器这个输入框对它支持不好，有适配问题，暂不支持

**Comment by EdwinWang0508** [comment]
来函敬悉，谢谢！祝径情直遂，安常履顺。Your letter has been received, thank you. Have a nice day!
