### ISSUE TITLE
平板（桌面UA）不应隐藏悬浮球 | Touchball on pads using a desktop user-agent shouldnot be hidden

### ISSUE THREAD

**Issue by THR-hub** [immersive-translate/immersive-translate#624]
### 您希望的更新和改进是什么 | Update or Improve

实测来看（暂时没看源码）插件会根据UA来判定是否显示悬浮球，但这一点放在平板上不太适合。平板一般桌面UA又没有工具栏（例如火狐），用起来很不方便，只能舍插件而用脚本。设置里的显示悬浮球不起作用。
For Firefox addon, usually pads use desktop UA and have no toolbar, in this situation the touchball is hidden and it is not easy to start translate.

**Comment by theowenyoung** [comment]
目前是根据设备有没有 touch 的事件来判断，理论上平板应该是有touch事件的？所以应该是有悬浮球的？

**Comment by THR-hub** [comment]
> 目前是根据设备有没有 touch 的事件来判断，理论上平板应该是有touch事件的？所以应该是有悬浮球的？

测试情况如下：安卓平板Firefox Beta115.0b7，安装插件时，桌面ua无悬浮球，设置里有显示悬浮球选项；移动ua有悬浮球。安装脚本时均有悬浮球。

**Comment by theowenyoung** [comment]
这里要不统一为桌面也添加一个展示悬浮球的选项吧。

**Comment by THR-hub** [comment]
> 这里要不统一为桌面也添加一个展示悬浮球的选项吧。

我觉得可以，比如所有环境设置中一律有悬浮球选项但是桌面环境默认不开启，移动环境默认开启。但问题是平板中也有这个选项，默认也是开启，却始终没有悬浮球（至少网页可视范围内没有悬浮球）。
