### ISSUE TITLE
[Bug]: mathjax 兼容问题

### ISSUE THREAD

**Issue by HaiBooLang** [immersive-translate/immersive-translate#626]
### 插件版本号 | Version

0.6.13

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

翻译前：
<img width="987" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/53350622/7c650c1b-5cce-4f3a-b8f7-520768c0931a">
翻译后：
<img width="669" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/53350622/7257d9a3-c854-4809-bbb0-5037c497b4ac">
BUG 描述：
遇到 mathjax 时翻译会被分隔成两块

### 出现问题的网址 | URL

https://catlikecoding.com/unity/tutorials/basics/mathematical-surfaces/

### 补充说明 | Additional context

希望可以添加对 mathjax 的支持，将 mathjax 和普通文字识别成一句话，不会因为 mathjax 而分隔或换行。

**Comment by theowenyoung** [comment]
0.6.19 已兼容
