### ISSUE TITLE
chess.com GM

### ISSUE THREAD

**Issue by yjhwang** [immersive-translate/immersive-translate#628]
### 您希望的更新和改进是什么 | Update or Improve

在Chess.com的英文
GM 正確的中文翻譯應該是特級大師
中文：特級大師
英文：Grandmaster
不是通用汽車

### 补充说明 | Additional context

沈浸式英文應該要判斷，有特殊專有名詞的網站內容

**Comment by theowenyoung** [comment]
和 #91  重复，暂时关掉了。术语库会是一个新特性，这个还在研究中哈。
