### ISSUE TITLE
网页适配

### ISSUE THREAD

**Issue by keen0309** [immersive-translate/immersive-translate#629]
### 您希望的更新和改进是什么 | Update or Improve

改进间距高度。
![image](https://github.com/immersive-translate/immersive-translate/assets/103982843/4032aa5f-5636-4f34-aab0-8b0e26391e15)
[remnote.com_flashcards_home.zip](https://github.com/immersive-translate/immersive-translate/files/11855844/remnote.com_flashcards_home.zip)

**Comment by keyboard3** [comment]
请参考文档，保存成正确格式, mht/.mhtml才是正确格式，它包好了当前网页的所有内容，html文件是不对的 。https://immersivetranslate.com/docs/faq/#%E7%BD%91%E9%A1%B5%E7%BF%BB%E8%AF%91%E6%9C%89%E9%97%AE%E9%A2%98%E5%A6%82%E4%BD%95%E4%BF%9D%E5%AD%98%E7%BD%91%E9%A1%B5%E5%8F%8D%E9%A6%88。 同一类问题不要开多个

**Comment by keyboard3** [comment]
无反馈 暂时关闭此issue
