### ISSUE TITLE
小建议: 进行 开发版和稳定版 开发

### ISSUE THREAD

**Issue by Mixlining** [immersive-translate/immersive-translate#63]
更新太频繁了,对于手动更新扩展的不太友好,同时扩展商店的更新是由延迟的,一天提交多个版本的更新不如开发到稳定时再提交商店
建议在github action中发布开发版,当新版本稳定后再release,提交商店

**Comment by theowenyoung** [comment]
可以按照 [安装教程](https://immersive-translate.owenyoung.com/installation) ，使用 `git pull` 更新即可？不用每次都在release里下载。

或者你也可以按照你自己的节奏采用隔几个版本再更新即可？

当前处于早期阶段，所以新特性或者bug比较多，发布的比较频繁，后续稳定之后肯定会降下来啦～ 感谢
