### ISSUE TITLE
网页适配2

### ISSUE THREAD

**Issue by keen0309** [immersive-translate/immersive-translate#630]
### 您希望的更新和改进是什么 | Update or Improve

![image](https://github.com/immersive-translate/immersive-translate/assets/103982843/94c505d7-e6f1-46fe-b00e-fa066bfda4e5)
[LingQ Learning Languages Simply --- LingQ 简单学习语言.zip](https://github.com/immersive-translate/immersive-translate/files/11855848/LingQ.Learning.Languages.Simply.---.LingQ.zip)

**Comment by keyboard3** [comment]
请参考文档，保存成正确格式, mht/.mhtml才是正确格式，它包好了当前网页的所有内容，html文件是不对的 。https://immersivetranslate.com/docs/faq/#%E7%BD%91%E9%A1%B5%E7%BF%BB%E8%AF%91%E6%9C%89%E9%97%AE%E9%A2%98%E5%A6%82%E4%BD%95%E4%BF%9D%E5%AD%98%E7%BD%91%E9%A1%B5%E5%8F%8D%E9%A6%88。 同一类问题不要开多个

**Comment by keyboard3** [comment]
请参考文档，保存成正确格式, mht/.mhtml才是正确格式，它包好了当前网页的所有内容，html文件是不对的 。https://immersivetranslate.com/docs/faq/#%E7%BD%91%E9%A1%B5%E7%BF%BB%E8%AF%91%E6%9C%89%E9%97%AE%E9%A2%98%E5%A6%82%E4%BD%95%E4%BF%9D%E5%AD%98%E7%BD%91%E9%A1%B5%E5%8F%8D%E9%A6%88。 同一类问题不要开多个 #629
