### ISSUE TITLE
为OpenAI翻译单独设置快捷键

### ISSUE THREAD

**Issue by Andy-AO** [immersive-translate/immersive-translate#631]
### 您希望的更新和改进是什么 | Update or Improve

希望能为OpenAI翻译单独设置快捷键

### 补充说明 | Additional context

使用OpenAI的大模型翻译内容，速度慢，而且代价大，如果网页上的内容比较适合传统的翻译方式，使用OpenAI就没有必要性。

现在的情况是如果设置为OpenAI翻译，那么之后的网页也会是OpenAI翻译。

因此希望为OpenAI的翻译提供单独的快捷键，在需要的时候使用，这样能够降低成本。

如果这个功能颗粒度更细会更好，即可以选择特点的段落执行OpenAI翻译。

**Comment by theowenyoung** [comment]
和 #878 可能也有一定的关系，快捷键这块之后可能要专门找时间重新规划一个更加科学的快捷键管理。

**Comment by theowenyoung** [comment]
1.1.0 版本已经支持为 openai 单独指定快捷键哈。
