### ISSUE TITLE
via浏览器：求试配

### ISSUE THREAD

**Issue by justincnn** [immersive-translate/immersive-translate#633]
### 您希望的更新和改进是什么 | Update or Improve

ios的safari完美适配，现在看英文新闻很舒服，

不过安卓上，目前发现找不到解决方案，via的浏览器可以支持script，也能运行脚本，出现那个迷人的 中英 标识的图标，

但是点击translate之后，网页的英文内容边上只会出现一个不断转圈的小圆圈，但是一直没有出现翻译内容

求作者对via浏览器做下适配，谢谢。

**Comment by justincnn** [comment]
![Screenshot_20230625-154102_Via.png](https://github.com/immersive-translate/immersive-translate/assets/37951994/f245d6b4-6394-481c-9bf7-5046171bea31)


截图如上

**Comment by theowenyoung** [comment]
暂不支持 via 油猴脚本哈，见支持范围： https://immersivetranslate.com/docs/faq/#%E6%B2%89%E6%B5%B8%E5%BC%8F%E7%BF%BB%E8%AF%91%E6%B2%B9%E7%8C%B4%E8%84%9A%E6%9C%AC%E6%94%AF%E6%8C%81%E7%9A%84%E6%B5%8F%E8%A7%88%E5%99%A8 ，

推荐直接使用沉浸式翻译封装的firefox安卓浏览器，直接安装沉浸式翻译扩展即可：

在 官网下载： https://immersivetranslate.com/

**Comment by theowenyoung** [comment]
由于 via 的油猴api实现的不完整，所以暂时无法支持哈～
