### ISSUE TITLE
[Bug]: 不支持本地html文件

### ISSUE THREAD

**Issue by QuarkPixel** [immersive-translate/immersive-translate#636]
### 插件版本号 | Version

0.6.13

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

访问本地html时貌似只会显示（请先刷新当前页面，再开始翻译），无法正常刷新。
![image](https://github.com/immersive-translate/immersive-translate/assets/65812149/925f3ed8-efa1-4bd8-824a-fff86378b9ce)

### 出现问题的网址 | URL

file:///D:/UnityHub/Editor/2021.3.27f1/Editor/Data/Documentation/en/ScriptReference/Quaternion-identity.html

**Comment by theowenyoung** [comment]
最新版本已经修复了这个问题哈，edge 商店还在审核，可以用chrome商店的最新版： https://chrome.google.com/webstore/detail/immersive-translate/bpoadfkcbjbfhfodiogcnhhhpibjhbnh
