### ISSUE TITLE
在平板的狐猴浏览器无法通过、、快捷翻译各种输入栏的中文到英文

### ISSUE THREAD

**Issue by zdoek001** [immersive-translate/immersive-translate#637]
### 您希望的更新和改进是什么 | Update or Improve

希望优化一下平板端的支持。方便使用chatgpt以及mj

**Comment by theowenyoung** [comment]
请查看兼容性： https://immersivetranslate.com/docs/input/#%E5%85%BC%E5%AE%B9%E6%80%A7

安卓建议直接使用官方封装的firefox浏览器，目前安卓只有firefox浏览器是支持的：

https://immersivetranslate.com/
