### ISSUE TITLE
[Bug]:安卓的 firefox beta中，使用 、、翻译输入框时出现退格失效的问题

### ISSUE THREAD

**Issue by zdoek001** [immersive-translate/immersive-translate#638]
### 插件版本号 | Version

0.6.19

### 平台 | Platform

Android

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

在安卓的 firefox beta中，在网页版discord的聊天室中使用、、翻译聊天输入框的中文到英文，翻译完成后，使用退格键无法删除翻译的内容。此时只能点其他聊天室再回来，输入框才正常能打字和删除文字，但是只要使用我们的插件翻译一次输入框后，就会出现异常。

### 出现问题的网址 | URL

discord.com

### 重现步骤 | To Reproduce

1：输入、、并按下3个空格 翻译聊天框的文字到英文
2：此时聊天框开始出现异常，无法退格，无法删除文字，必须CTRL+A全选再打字才能打出来
3：切换到其他聊天室再回来后正常，但是不能使用输入框翻译，不然又出现退格键失效的问题

**Comment by keyboard3** [comment]
试下最新版的0.7.6 应该已经修复了

**Comment by zdoek001** [comment]
试了下0.7.6还是不行，它现在会变成另外一种奇怪的问题，就是空格翻译完后，会自动全选锁定那一串翻译出来的英文，光标也在首位，点到末尾也会自动弹回首位。然后随便输入一个字。这串英文就消失了，好像是强制全选状态+强制光标在首位 一样



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月11日(周二) 上午9:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [immersive-translate/immersive-translate] [Bug]:安卓的 firefox beta中，使用 、、翻译输入框时出现退格失效的问题 (Issue #638)




 
试下最新版的0.7.6 应该已经修复了

**Comment by zdoek001** [comment]
这个还有拯救的空间吗，因为平时都是用平板AI生图的，就差这个bug修复了就完美了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月11日(周二) 下午4:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [immersive-translate/immersive-translate] [Bug]:安卓的 firefox beta中，使用 、、翻译输入框时出现退格失效的问题 (Issue #638)




 
好的，了解了。firefox 还是有点奇怪的

**Comment by keyboard3** [comment]
应该可以的，等等 我空了来看下

**Comment by zdoek001** [comment]
> 应该可以的，等等 我空了来看下

追加一下测试的最新信息，除了上面描述的，我发现它好像是被覆盖了一层翻译的文字在原有的输入框上面，因为3个空格翻译好后，如果我此时再重新打字，已被翻译的中文就会再次被直接显示回来，然后就算已经翻译好了，我点击发送消息。发出去的也还是中文。而不是聊天框的英文

**Comment by keyboard3** [comment]
你试过插件吗？

**Comment by FattySpring** [comment]
> > 应该可以的，等等 我空了来看下
> 
> 追加一下测试的最新信息，除了上面描述的，我发现它好像是被覆盖了一层翻译的文字在原有的输入框上面，因为3个空格翻译好后，如果我此时再重新打字，已被翻译的中文就会再次被直接显示回来，然后就算已经翻译好了，我点击发送消息。发出去的也还是中文。而不是聊天框的英文

您好，在 Android 平板和手机端的 Firefox beta 和 Firefox 中都未能重现该问题

**Comment by keyboard3** [comment]
暂时关闭此issue啊，如果有更新可以重开
