### ISSUE TITLE
建议：希望能手动设置一些网站选用的翻译引擎

### ISSUE THREAD

**Issue by yaozijin** [immersive-translate/immersive-translate#64]
因为一些众所周知的原因，Deepl的开发者账号很难弄到，所以在绝大部分网页中Google翻译绝对为最优解。
但是，Google翻译在翻译 日语→中文 时疑似流程为：日语→英语→汉语 ，这将导致绝大部分的语句都不能翻译成流畅的句子。即使少部分一些看起来很流畅的句子也都不符合原文语义。
故请求开发者能够开发一个 记住一些网址使用特定翻译引擎 的功能！

另外，使用腾讯交互式翻译时，有时后面几句话的翻译会因为前一句话翻译卡住而翻译失败（未知原因）。
这里可能需要特殊适配或者是bug需要修复一下。
另外这里的翻译逻辑也可能需要修改一下，在翻译失败时自动重试（重试时可以为单线程查询而不是并行以避开部分限制）。

再次感谢作者！

eg：
>https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.108.0-b.26

部分原文：
>DNS64 support (https://github.com/AdguardTeam/AdGuardHome/issues/5117). The function may be enabled with new use_dns64 field under dns object in the configuration along with dns64_prefixes, the set of exclusion prefixes to filter AAAA responses. The Well-Known Prefix (64:ff9b::/96) is used if no custom prefixes are specified.

**Comment by theowenyoung** [comment]
> 因为一些众所周知的原因，Deepl的开发者账号很难弄到，所以在绝大部分网页中Google翻译绝对为最优解。
但是，Google翻译在翻译 日语→中文 时疑似流程为：日语→英语→汉语 ，这将导致绝大部分的语句都不能翻译成流畅的句子。即使少部分一些看起来很流畅的句子也都不符合原文语义。
故请求开发者能够开发一个 记住一些网址使用特定翻译引擎 的功能！

好吧，其实这个已经支持了，只不过还没有界面. 可以在【开发者设置】-【userConfig】 里面手动设置，[文档](https://immersive-translate.owenyoung.com/advanced) , 大概如下， 表示腾讯 匹配 "*.twitter.com"

```json
{
 "translationServices": {
    "tencent": {
      "secretId": "xxx",
      "secretKey": "xxx",
      "matches":["*.twitter.com"]
    }
  }
}
```

**Comment by theowenyoung** [comment]
> 另外，使用腾讯交互式翻译时，有时后面几句话的翻译会因为前一句话翻译卡住而翻译失败（未知原因）。
这里可能需要特殊适配或者是bug需要修复一下。
另外这里的翻译逻辑也可能需要修改一下，在翻译失败时自动重试（重试时可以为单线程查询而不是并行以避开部分限制）。

这个可能是接口限制， 好，我优化一下重试逻辑。

**Comment by yaozijin** [comment]
> 一下重试逻辑。

感谢！=-=

**Comment by theowenyoung** [comment]
当前已经会重试2次

**Comment by theowenyoung** [comment]
这个问题应该解决了，升级到最新版本即可～ 有问题再打开，谢谢～
