### ISSUE TITLE
[Bug]: 鼠标滑动翻译，多滑动页面，之前的翻译就会被还原。

### ISSUE THREAD

**Issue by hhaishen** [immersive-translate/immersive-translate#641]
### 插件版本号 | Version

V0.6.19

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

使用的谷歌浏览器，开启了“鼠标悬停自动翻译”，然后右键网页全翻译，当阅读文档，鼠标悬停的时候，偶尔会触发整个页面翻译全部没了，要重新右键翻译下才行，频率还是挺高的，把鼠标悬停翻译关了后，就不会出现这个问题了。

Goole Chrome：版本 114.0.5735.134（正式版本） （64 位）
immersive-translate：V0.6.19

鼠标滑动翻译，多滑动页面，之前的翻译就会被还原。

### 出现问题的网址 | URL

https://docs.oracle.com/en/database/oracle/oracle-database/19/admin/getting-started-with-database-administration.html#GUID-10287280-C2E4-4FB1-ABF9-993327419603

### 重现步骤 | To Reproduce

鼠标滑动翻译，你多滑动页面，之前的翻译就会被还原。

**Comment by hidaris** [comment]
I have also encountered this problem

**Comment by keyboard3** [comment]
这个网站已修复
