### ISSUE TITLE
[Bug]: pdf翻译时，目录里的点变成了句号导致格式混乱

### ISSUE THREAD

**Issue by heheda123123** [immersive-translate/immersive-translate#642]
### 插件版本号 | Version

0.6.19

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

[Mastering Emacs (Mickey Petersen) (Z-Library) (2)2022.pdf](https://github.com/immersive-translate/immersive-translate/files/11870124/Mastering.Emacs.Mickey.Petersen.Z-Library.2.2022.pdf)
如图，遇到好几个pdf都有这种问题了
![image](https://github.com/immersive-translate/immersive-translate/assets/97490782/f30accb4-2417-4ae0-b112-2be75723aee6)

**Comment by heheda123123** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/97490782/c08d6d67-b496-4797-a8b2-36f0ae5dac94)
[an introduction to programming in emacs lisp.pdf](https://github.com/immersive-translate/immersive-translate/files/12034884/an.introduction.to.programming.in.emacs.lisp.pdf)

**Comment by keyboard3** [comment]
目前版本已处理该问题
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/4ca0b8db-a4bd-440a-b579-658ef1138b42)
