### ISSUE TITLE
[Bug]影响b站快进快退: 

### ISSUE THREAD

**Issue by SJA2C2A** [immersive-translate/immersive-translate#643]
### 插件版本号 | Version

laste

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome, Microsoft Edge

### 请描述这个Bug | Describe the bug

在开启此插件时，网页视频如B站中的前进后退快进功能失效，

### 出现问题的网址 | URL

https://www.bilibili.com/

**Comment by theowenyoung** [comment]
你可以在 隐私窗口里 只开启沉浸式翻译扩展来测试是否是此插件影响。

**Comment by theowenyoung** [comment]
暂时关掉了哈，有问题再反馈。
