### ISSUE TITLE
提供调节译文透明度的设置

### ISSUE THREAD

**Issue by chachako** [immersive-translate/immersive-translate#644]
### 您希望的更新和改进是什么 | Update or Improve

当 `译文显示样式` 为 **透明** 时允许调节透明度。默认的透明度太低了，很难能一眼全部浏览完，允许调节默认透明度会好得多~
<img width="860" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/58068445/7916beb9-a7a3-4d3f-9a63-1deae80884c6">

**Comment by keyboard3** [comment]
0.8.0 已支持透明度调节
