### ISSUE TITLE
建议支持 RapidAPI 的翻译服务

### ISSUE THREAD

**Issue by lgtnice** [immersive-translate/immersive-translate#645]
### 您希望的更新和改进是什么 | Update or Improve

因为 DeepL账户 总是被封，建议支持 RapidAPI 的翻译服务，通过第三方访问 deepl api

**Comment by theowenyoung** [comment]
了解了一下，rapid API 频率限制严格，不适合作为网页翻译的API. 暂时先关闭了哈，如果有需求，你可以使用 自定义API 接入任何API：

https://Immersivetranslate.com/docs/services/custom/
