### ISSUE TITLE
[Bug]: 无法正确翻译含有公式的句子

### ISSUE THREAD

**Issue by hubery055** [immersive-translate/immersive-translate#646]
### 插件版本号 | Version

0.8.19

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/46236062/fb1eba8e-3886-43e2-910d-6f640d547667)
含有公式的句子不能正确识别并翻译，我不知道这是一个BUG还是一个功能上的缺失。

### 出现问题的网址 | URL

https://textbooks.math.gatech.edu/ila/systems-of-eqns.html

### 重现步骤 | To Reproduce

1. 进入页面
2. 找到任意一行带有公式的文本
3. 点击Alt+A开始翻译

### 补充说明 | Additional context

如果公式不能翻译的化，可以考虑使用一个占位符来代替公式，在翻译之后再将占位符替换为原始内容，也许我的想法能给您带来一些启发。

**Comment by Tyqfat** [comment]
版本0.6.17也出现了无法翻译含公式的句子
![image](https://github.com/immersive-translate/immersive-translate/assets/100210376/dc567f1c-5f82-4914-a469-c21a1e061b49)

**Comment by theowenyoung** [comment]
0.7.9 修复。
