### ISSUE TITLE
[Bug]: 新版本发布后把已经设置的 `总是翻译` 设置更改了

### ISSUE THREAD

**Issue by Nauxscript** [immersive-translate/immersive-translate#647]
### 插件版本号 | Version

0.6.20

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

之前安装插件的时候（大半年前）我把 `总是翻译` 取消选中了，但是今天早上发现这个设置被选中了，我并没有更改过这个设置，而且近期也没有怎么使用过这个插件；估计是插件更新后把我的设置重置了？不确定。

**Comment by theowenyoung** [comment]
https://immersivetranslate.com/docs/CHANGELOG/

![IMG_20230628_100730.jpg](https://github.com/immersive-translate/immersive-translate/assets/62473795/cdf23f3f-f675-472e-a7c6-4a761720cfd8)




![IMG_20230628_100447.jpg](https://github.com/immersive-translate/immersive-translate/assets/62473795/fd9a90d8-675a-423d-96b8-ba28a7698e9e)

**Comment by theowenyoung** [comment]
但是如果之前设置过的用户，并不会覆盖哦

**Comment by Sevichecc** [comment]
我觉得在用户第一次安装时可以跳转到一个新的页面显示设置，也就是新手引导，而不是修改现有的设置，这样对老用户并不是很友好。

**Comment by Nauxscript** [comment]
大概明白了，感谢回复~
