### ISSUE TITLE
[Bug]: 如何关闭国外网页自动双语翻译？

### ISSUE THREAD

**Issue by jiangaq** [immersive-translate/immersive-translate#648]
### 插件版本号 | Version

0.6.20

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome, Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

以前还正常，这几天突然会自动翻译，请问怎么关闭？

### 出现问题的网址 | URL

google

### 重现步骤 | To Reproduce

如题

### 补充说明 | Additional context

如题

**Comment by theowenyoung** [comment]
![IMG_20230628_100447.jpg](https://github.com/immersive-translate/immersive-translate/assets/62473795/75b410ef-ce42-421b-914e-d6d37d4eaff7)

取消勾选总是翻译英语

**Comment by keyboard3** [comment]
http://localhost:3000/docs/faq/#%E5%A6%82%E4%BD%95%E5%85%B3%E9%97%AD%E8%87%AA%E5%8A%A8%E7%BF%BB%E8%AF%91

**Comment by keyboard3** [comment]
https://immersivetranslate.com/docs/faq/#%E5%A6%82%E4%BD%95%E5%85%B3%E9%97%AD%E8%87%AA%E5%8A%A8%E7%BF%BB%E8%AF%91
