### ISSUE TITLE
功能建议： 用户词典和遵循原文样式

### ISSUE THREAD

**Issue by PoisonousGame** [immersive-translate/immersive-translate#65]
增加翻译领域和术语。每个翻译领域有一组术语。术语有用户定义，还可以设置是否翻译术语。当翻译时遇到术语时优选采用用户的设置。

在双语对照中：希望遵循样式，某些原文的粗体没有在英文遵循，超文本链接希望能在译文中用链接的颜色标注。

**Comment by theowenyoung** [comment]
> 增加翻译领域和术语。每个翻译领域有一组术语。术语有用户定义，还可以设置是否翻译术语。当翻译时遇到术语时优选采用用户的设置。

嗯，在规划一个用户词典，应该会在之后的版本里支持。

> 在双语对照中：希望遵循样式，某些原文的粗体没有在英文遵循，超文本链接希望能在译文中用链接的颜色标注。

这个暂时无法做到，因为支持众多翻译引擎的原因，采用的是文本翻译，所以会丢掉绝大多数样式。除了一些 `code` 或者 显式的`https://xxxxx.com` 可以在翻译之前被发现而保留原格式，其他的都没法做到。

**Comment by lindeer** [comment]
人名和地名翻译能否尽量使用《世界人名翻译大辞典》和《世界地名翻译大辞典》？

**Comment by theowenyoung** [comment]
该问题和  #91   合并一下吧，由于翻译服务不受沉浸式翻译插件控制，所以实际上在前端实现这个有不少的困难，而且还会显著增加普通用户的理解成本，我们更想让沉浸式翻译保持简单一点。

同时沉浸式翻译的双语对照本身就是为了解决翻译准确度的问题，有疑问的译文建议直接对照原文～

不过这个功能也许未来会再次考虑。
