### ISSUE TITLE
添加一个备用翻译选项

### ISSUE THREAD

**Issue by ydivho12123** [immersive-translate/immersive-translate#653]
### 您希望的更新和改进是什么 | Update or Improve

现在只能固定使用一个翻译源,比如当我使用vpn的时候可以正常使用谷歌翻译,但有时候得断开vpn,这时候翻译就完全不能用了,得转到设置设置成腾讯翻译之类的.重连vpn后又得改成谷歌的(主要谷歌确实快也好用),很多时候避免不了得关闭vpn,来回改设置非常麻烦.

改进方案: 添加一个备用翻译源设置.比如默认翻译源是谷歌.插件会自动检测,如果谷歌翻译用不了,自动切换备用翻译源使用(比如自己设置腾讯翻译就调用腾讯翻译),当检测到谷歌翻译能正常使用的时候,把备用翻译源又自动切换会谷歌翻译

**Comment by theowenyoung** [comment]
抱歉这么晚回复。沉浸式翻译的首要目标是保持简单易用性，目前确实暂无计划在这里额外添加复杂性，先关闭了这个isssue了哈～
