### ISSUE TITLE
[Bug]: 腾讯交互翻译无法翻译韩语

### ISSUE THREAD

**Issue by kkk48ku** [immersive-translate/immersive-translate#655]
### 插件版本号 | Version

任意版本

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

腾讯交互翻译无法翻译韩语，应该是因为语言分析服务code是ko，而翻译接口传的是kr

**Comment by theowenyoung** [comment]
感谢，下个版本修复。

**Comment by theowenyoung** [comment]
最新版已修复了哈。
