### ISSUE TITLE
希望支持翻译选中的单词

### ISSUE THREAD

**Issue by qiuyongjin** [immersive-translate/immersive-translate#659]
### 您希望的更新和改进是什么 | Update or Improve

希望能够支持翻译选中的文本，感谢

**Comment by theowenyoung** [comment]
抱歉这么晚回复，沉浸式翻译的首要目标是保持简单，对用户勿打扰，所以无意对选中的文本添加一些烦人的图标。

未来应该也不会支持该特性。
