### ISSUE TITLE
希望可以根据用户设定的源语言和目标语言进行翻译

### ISSUE THREAD

**Issue by k650dg4d2** [immersive-translate/immersive-translate#66]
比如我的网页是英文网页，点击翻译可以翻译成英语。当我的网页是中文网页，点击翻译可以自动翻译成英语。
![image](https://user-images.githubusercontent.com/32454224/216335522-e8800a0b-6e5e-4de8-86f7-92d624234c80.png)
就是希望设置这里可以添加一个自动对应的源和目标的选项：自动翻译：中文->英文，英文->中文。
比如检测到中文根据用户设定的翻译成英文，检测到英文根据用户设定的翻译成中文。
这样就不用去设置里设置目标语言了

**Comment by theowenyoung** [comment]
这个好像有点侵入性太强了？

这个逻辑似乎有点复杂化了...

建议暂时先用多个浏览器，保存不同的配置？

**Comment by k650dg4d2** [comment]
> 

那好吧，希望以后可以考虑一下。我想着这个不算难，检测网页语言，然后读取用户配置文件翻译目标语言，可能我是我想简单了。主要是不仅想学英译汉也想学汉译英。现在做的也挺好的，继续支持！

**Comment by theowenyoung** [comment]
这个实现上是很简单～ 因为我们已经能检测到语言和目标语言了，我是说这种自动转换的逻辑，对普通用户来讲，可能会很困惑。

**Comment by k650dg4d2** [comment]
> 

那就是我的问题，我没表达清楚。我的意思不是自动转换，是点击
![image](https://user-images.githubusercontent.com/32454224/216344959-2e5fe308-b9f3-486f-a52c-3c7a2292e855.png)
这个翻译按钮时，可以自动把中文网页的目标语言设置为英文，英文的目标语言设置为中文。不好意思，表达不清楚

**Comment by theowenyoung** [comment]
就算是 点击 也是会困惑的呀.

所以最好还是明确的选择目标语言后再翻译，是最符合直观感受的。

自动变为英语 也并不是一个 合理的默认值， 因为有的用户可能需要是日语或者别的语言，所以如果要引入这个特性，可能要增加设置项才行。 所以我觉得会由于一个不是很常用的需求而变得很困惑。

**Comment by k650dg4d2** [comment]
> 就算是 点击 也是会困惑的呀.
> 
> 所以最好还是明确的选择目标语言后再翻译，是最符合直观感受的。
> 
> 自动变为英语 也并不是一个 合理的默认值， 因为有的用户可能需要是日语或者别的语言，所以如果要引入这个特性，可能要增加设置项才行。 所以我觉得会由于一个不是很常用的需求而变得很困惑。

是的，要增加或修改一个设置选项来存储。所以我第一次提交建议的时候给你截图了那个设置选项，就是希望你可以修改它来增加新特性。不过话说回来，我大多数时候也是只翻译英文界面，中文翻译英文用的也比较少，也没什么影响。 可以忽略我的这条建议，没问题的。一个人有一个人怪异的想法，哈哈哈
