### ISSUE TITLE
[Bug]: 翻译要求流入正文 | Translate Prompt Leakage

### ISSUE THREAD

**Issue by CharlezXue** [immersive-translate/immersive-translate#660]
### 插件版本号 | Version

0.6.21

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

翻译维基百科页面 [Original Version](https://en.wikipedia.org/wiki/Fortress_of_Solitude#Original_version) 段落时，疑似将翻译的要求流入正文渲染
![image](https://github.com/immersive-translate/immersive-translate/assets/36230781/a78bad1e-46b3-4916-8449-5ecdcaba8d0a)

### 出现问题的网址 | URL

https://en.wikipedia.org/wiki/Fortress_of_Solitude#Original_version

### 重现步骤 | To Reproduce

1. Go to provided link
2. press 'translate'

**Comment by RedwindA** [comment]
这是模型的问题，你需要编辑prompt严格要求它只输出翻译后的文本（仍然有概率犯错），跟插件没关系
