### ISSUE TITLE
Translate (Writing) Config to English

### ISSUE THREAD

**Issue by neoOpus** [immersive-translate/immersive-translate#661]
### 您希望的更新和改进是什么 | Update or Improve

Translate to English (and maybe other languages)

### 补充说明 | Additional context

This section (Writing) remains in Chinease

extension://bpoadfkcbjbfhfodiogcnhhhpibjhbnh/options.html#input

**Comment by keyboard3** [comment]
Okay, we'll make adjustments in the next version

**Comment by neoOpus** [comment]
![msedge_6QOLX4he9q](https://github.com/immersive-translate/immersive-translate/assets/1388336/0fa8f0bf-966e-47c5-ac08-aecf6f28b6d1)

**Comment by neoOpus** [comment]
![d9QuL5hAwH](https://github.com/immersive-translate/immersive-translate/assets/1388336/ecc80d6b-71ee-4ca5-919f-d71538e12b34)

**Comment by theowenyoung** [comment]
Thanks, solved now.
