### ISSUE TITLE
[Bug]: 当设置了永不翻译*时，无法翻译pdf

### ISSUE THREAD

**Issue by garywill** [immersive-translate/immersive-translate#663]
### 插件版本号 | Version

0.6.1

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

我想要所有网页都不要自动翻译，只在我点击后翻译，因此设置了永不翻译`*`

发现设置了之后，pdf文件总是无法翻译，不管点翻译按钮多少次

**Comment by keyboard3** [comment]
pdf是打开后自动翻译。永不翻译* 你是如何设置的

**Comment by garywill** [comment]
设置页面里 基本设置->永不翻译的网址
添加一个`*`

**Comment by keyboard3** [comment]
> 设置页面里 基本设置->永不翻译的网址 添加一个`*`

不要*所有，换成 https://* 。这样就可以避免插件内部网页不被激活
