### ISSUE TITLE
[Bug]: 插件会影响浏览器自带的翻译功能

### ISSUE THREAD

**Issue by lianwensheng** [immersive-translate/immersive-translate#664]
### 插件版本号 | Version

0.7.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome, Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

插件会影响浏览器自带的翻译功能，个别网站在默认没被插件翻译的情况下，浏览器自带的翻译无法翻译网站导航区域，把沉浸式翻译禁用了之后网站导航区域就能正常翻译了。。。

1、
![屏幕截图 2023-07-01 165453](https://github.com/immersive-translate/immersive-translate/assets/36002202/fc47eab4-886d-4c64-91b7-3c83e123abca)

2、
![屏幕截图 2023-07-01 115030](https://github.com/immersive-translate/immersive-translate/assets/36002202/7d127179-9b6a-4e99-ab34-8a10a14486f2)

3、
![屏幕截图 2023-07-01 113658](https://github.com/immersive-translate/immersive-translate/assets/36002202/41156391-de94-4d1f-a741-194eea1fdea7)

![屏幕截图 2023-07-01 112947](https://github.com/immersive-translate/immersive-translate/assets/36002202/befe62e8-7a2e-4d09-b08a-311c308d01d1)

### 出现问题的网址 | URL

https://www.16personalities.com/

https://www.telegraph.co.uk/

https://www.semafor.com/

### 重现步骤 | To Reproduce

1、默认配置如图
![屏幕截图 2023-07-01 170527](https://github.com/immersive-translate/immersive-translate/assets/36002202/991c5df6-e89a-4e3d-b280-71c835a27da1)

2、打开浏览器自带翻译就能看到网站导航栏无法被翻译

**Comment by theowenyoung** [comment]
最新版本已修复～
