### ISSUE TITLE
[Bug]: 翻译过程中丢失高亮词

### ISSUE THREAD

**Issue by happyjustyn** [immersive-translate/immersive-translate#665]
### 插件版本号 | Version

0.7.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

整页翻译结果中丢失原文高亮词的翻译, 如图:

![image](https://github.com/immersive-translate/immersive-translate/assets/35069723/274bdb87-524a-4f64-81ab-438e1eaa59a3)

### 出现问题的网址 | URL

https://openjfx.cn/openjfx-docs/#maven

**Comment by keyboard3** [comment]
0.7.6已测无该问题，升级下版本试试

**Comment by happyjustyn** [comment]
@keyboard3 目前插件版本v0.7.7 , 尝试清理了缓存, 还是存在上面的问题.
![image](https://github.com/immersive-translate/immersive-translate/assets/35069723/481417e4-8821-481f-af13-66193776d826)
![image](https://github.com/immersive-translate/immersive-translate/assets/35069723/23a91509-baf5-41f1-85ed-4424738a02fa)

**Comment by theowenyoung** [comment]
确实～，我看下。

**Comment by theowenyoung** [comment]
已修复～
