### ISSUE TITLE
[Bug]: 使用Edge朗读所选内容时，会重复翻译所读内容

### ISSUE THREAD

**Issue by srsng** [immersive-translate/immersive-translate#666]
### 插件版本号 | Version

0.6.17

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

保持插件正在翻译英文，选中英文然后使用浏览器自带的“朗读所选内容”，插件会**重复翻译**黄色高亮的内容，也就是**当前正在读的单词**，并且译文会一直跟随在单词后面，直到使用插件显示原文。

### 重现步骤 | To Reproduce

1. 保持插件正在翻译英文
2. 选中英文
3. 使用浏览器自带的“朗读所选内容”(右键选中内容，右键菜单中可见）
4. （看到bug现象）

### 补充说明 | Additional context

实际来讲，不是英文的问题，应该是单词被浏览器黄底高亮时，被识别为新的段落而被“边看边译”

**Comment by theowenyoung** [comment]
已修复
