### ISSUE TITLE
[Bug]: macos11.2.3，safari安装后无法使用，显示空白

### ISSUE THREAD

**Issue by hellozgl** [immersive-translate/immersive-translate#667]
### 插件版本号 | Version

0.6.21

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

先前安装0.5.x版本也无法使用，现在更新到最新版本0.6，仍然无法使用。
是否与macos版本有关？macos版本是11.2.3，safari是随系统的safari版本，没有更新过，Safari版本14.0.3 (16610.4.3.1.7)
在插件设置界面：https://dash.immersivetranslate.com，网页无法打开，只显示“Loading...”字样。

### 出现问题的网址 | URL

所有

**Comment by theowenyoung** [comment]
是的，11.5以下应该都无法用，可以升级到12 吗？
