### ISSUE TITLE
[Bug]: openai使用相同的自定义 API 接口地址，safari中正常，chrome下验证一直不通过

### ISSUE THREAD

**Issue by gray0128** [immersive-translate/immersive-translate#668]
### 插件版本号 | Version

0.7.1

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome, Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

使用相同的openai的api，和自定义 API 接口地址，safari测试正常，但chrome一直提示“网络问题，无法连接到服务，请检查你的代理或本地网络连接后重试。 Failed to fetch”

**Comment by gray0128** [comment]
safari插件版本：0.6.21

**Comment by theowenyoung** [comment]
是否 chrome 本身有特殊设置，开了代理之类的？

**Comment by gray0128** [comment]
> 是否 chrome 本身有特殊设置，开了代理之类的？

是的，开了代理，但代理并没有区分应用。所以我排除了。chrome和safari代理相关的设置都是进入wifi的代理设置界面。关掉代理后，safari仍然验证成功，chrome仍然验证失败

**Comment by theowenyoung** [comment]
Chrome用的是插件还是油猴版本呢？

**Comment by gray0128** [comment]
> Chrome用的是插件还是油猴版本呢？

插件

**Comment by theowenyoung** [comment]
请问现在正常了吗？

我们自己测试是从来没遇到该问题。

**Comment by gray0128** [comment]
我现在用 azure，验证不了。先关掉吧。
