### ISSUE TITLE
[Bug]:  opera 浏览器显示请先刷新当前页面，再开始翻译，无法使用

### ISSUE THREAD

**Issue by izhaoqing** [immersive-translate/immersive-translate#670]
### 插件版本号 | Version

0.7.1

### 平台 | Platform

macOS

### 浏览器 | Browsers

Other

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

我试使用的是 opera 浏览器，重启浏览器后不能使用了，显示请先刷新当前页面，再开始翻译，刷新网页后还是如此。我重新安装插件，也不能使用。
![image](https://github.com/immersive-translate/immersive-translate/assets/23057194/b634ef76-1a20-4382-8adb-88a46d4a9d73)

**Comment by FattySpring** [comment]
![80f3a48aaf4869c9c586449844352ec](https://github.com/immersive-translate/immersive-translate/assets/25144301/6664f603-0ea3-4495-a58d-9b79e7a9a7d9)

opera浏览器在访问 google 等搜索页面中，需要在浏览器插件设置中开启【允许访问搜索页面结果】选项
