### ISSUE TITLE
关于PDF翻译格式的问题，我推荐两个仓库作为参考

### ISSUE THREAD

**Issue by hubery055** [immersive-translate/immersive-translate#671]
### 您希望的更新和改进是什么 | Update or Improve

https://github.com/Raychanan/ChatGPT-for-Translation  # 理论ChatGPT批量翻译文件
https://github.com/kermitt2/grobid #  基于深度学习的学术PDF信息提取

### 补充说明 | Additional context

希望能帮到你们

**Comment by keyboard3** [comment]
感谢，我们会去了解下这几个方案
