### ISSUE TITLE
Firefox 版本太低，与 Google 版本不一致

### ISSUE THREAD

**Issue by qiqingfu** [immersive-translate/immersive-translate#672]
### 您希望的更新和改进是什么 | Update or Improve

升级 FireFox 扩展的版本，目前在 FireFox 安装的版本是 0.3.10，有写功能无法使用。

Google 扩展程序的版本是 0.7.1

**Comment by featherwit** [comment]
github里firefox版本一直有更新，但是商店还停留在4个月之前的0.3.10。

现在普通版的firefox不能手动安装未签名的离线包，要最新版似乎只能使用油猴版本了。

**Comment by keyboard3** [comment]
火狐  0.7.6 审核已通过
