### ISSUE TITLE
[Bug]: 字幕能结合上下文翻译呢.gpt-3.5-turbo-16k添加这个能否改进翻译速度呢

### ISSUE THREAD

**Issue by ictsmc** [immersive-translate/immersive-translate#673]
### 插件版本号 | Version

0.7.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 请描述这个Bug | Describe the bug

字幕翻译准确度太差了.英文断句不合适导致翻译的字幕内容完全曲解了意思能够结合上下文内容翻译呢.

速度不重要.重要的是翻译的准确度  gpt-3.5-turbo-16k 也提供了更大的文本字符 

希望改进字幕翻译的准确度

**Comment by theowenyoung** [comment]
字幕上下文的建议统一在 #705 讨论哈。
