### ISSUE TITLE
[Bug]: 特殊pdf(旋转)

### ISSUE THREAD

**Issue by keyboard3** [immersive-translate/immersive-translate#674]
### 插件版本号 | Version

0.7.1

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

pdf正常显示，但是内容被旋转过。还有就是字体大小需要使用transform同级的height参数

**Comment by JamesW99** [comment]
pdf中竖版字会被横过来
https://arxiv.org/pdf/2304.04370
chrome v0.7.9!

[image](https://github.com/immersive-translate/immersive-translate/assets/44286680/c7fb35bb-07bf-472e-8db8-93a3641c260d)

**Comment by keyboard3** [comment]
0.7.13 已支持
