### ISSUE TITLE
【悬停翻译】的改进建议

### ISSUE THREAD

**Issue by wongchenv** [immersive-translate/immersive-translate#675]
### 您希望的更新和改进是什么 | Update or Improve

1. 希望悬停翻译的快捷键支持双键(command+option), 和支持 Fn + 悬停. (快捷键都占满了, 但 Fn 没几个软件支持...🙁🙁)
2. 在已翻译文本上, 再二次使用悬停翻译, 可以关闭该段文本的翻译.
3. 悬停翻译的翻译样式可以和网站翻译的样式不一样. (例如通过**不同的快捷键**, 可以**切换**悬停**翻译**的**样式**为"仅显示译文" 或 "双语显示")
4. 悬停翻译可以和网站翻译使用不同的接口. (网页翻译我希望使用更快的谷歌接口, 但悬停翻译我需要更准确的Chatgpt翻译)

**Comment by vvanglro** [comment]
> 2. 在已翻译文本上, 再二次使用悬停翻译, 可以关闭该段文本的翻译.

+1

**Comment by gmugu** [comment]
2.在已翻译文本上, 再二次使用悬停翻译, 可以关闭该段文本的翻译.
4.悬停翻译可以和网站翻译使用不同的接口. (网页翻译我希望使用更快的谷歌接口, 但悬停翻译我需要更准确的Chatgpt翻译)
+1

**Comment by echofly** [comment]
> 2. 在已翻译文本上, 再二次使用悬停翻译, 可以关闭该段文本的翻译.

+1

**Comment by wongchenv** [comment]
悬停翻译的翻译样式可以和网站翻译的样式不一样. (例如通过不同的快捷键, 可以切换悬停翻译的样式为"仅显示译文" 或 "双语显示")

**Comment by theowenyoung** [comment]
> 1. 希望悬停翻译的快捷键支持双键(command+option), 和支持 Fn + 悬停. (快捷键都占满了, 但 Fn 没几个软件支持...🙁🙁)

Fn应该是技术上无法支持, 你可以在设置中手动配置一些类似 `command+i` 之类的快捷键
   
> 2.  在已翻译文本上, 再二次使用悬停翻译, 可以关闭该段文本的翻译.

最新版已支持。再次按下 Ctrl 键并鼠标滑过，即可显示原文。
    
> 3. 悬停翻译的翻译样式可以和网站翻译的样式不一样. (例如通过不同的快捷键, 可以切换悬停翻译的样式为"仅显示译文" 或 "双语显示")

这个暂时应该不会引入这个复杂性。


> 3. 悬停翻译可以和网站翻译使用不同的接口. (网页翻译我希望使用更快的谷歌接口, 但悬停翻译我需要更准确的Chatgpt翻译)

目前最新版已经支持。
