### ISSUE TITLE
输入框增强功能在iPad不能使用[Bug]: 

### ISSUE THREAD

**Issue by 734662653** [immersive-translate/immersive-translate#676]
### 插件版本号 | Version

0.6.21

### 平台 | Platform

iOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在safa浏览器输入框上进行输入框增强（//译文）没有反应，不能正常使用  。在ChatGPT输入框里有同样问题。

### 出现问题的网址 | URL

safa 百度搜索框

### 重现步骤 | To Reproduce

1，在safa浏览器百度搜索输入框中，输入//译文+三个空格 不能翻译

### 补充说明 | Additional context

。

**Comment by theowenyoung** [comment]
百度不支持，其他的网页应该都支持的，试试：谷歌

兼容性： https://immersivetranslate.com/docs/input/#%E5%85%BC%E5%AE%B9%E6%80%A7

**Comment by 734662653** [comment]
在safa浏览器中谷歌搜索输入框中不能使用输入框增强  ，已测试

**Comment by theowenyoung** [comment]
ipad上可能是你的输入法问题，你试试原生输入法？ 我这测试是ok的。

**Comment by keyboard3** [comment]
> 
这里注意谷歌搜索框一定是在Google网址的网页，而不能在浏览器主页，地址栏空白的地方使用
