### ISSUE TITLE
请求译文推出下载功能

### ISSUE THREAD

**Issue by Super-cz** [immersive-translate/immersive-translate#679]
### 您希望的更新和改进是什么 | Update or Improve

希望作者大大给PDF全文翻译后的译文推出下载功能，可选择文献译文同时下载在一个pdf里，或者单独下载翻译后的译文为一个独立的PDF文件。

### 补充说明 | Additional context

在今天购买了deepl free api后翻译才发现，功能栏第三个“保存”选项仍然是下载原pdf文件，呜呜呜呜痛失23.9w字符，还烦请作者大大采纳。

**Comment by 2686259124** [comment]
老哥，你deepl api在哪买的

**Comment by Super-cz** [comment]
> 老哥，你deepl api在哪买的

tb花了15

**Comment by keyboard3** [comment]
0.7.9 已支持
