### ISSUE TITLE
本地多个浏览器间设置自动同步

### ISSUE THREAD

**Issue by photkey** [immersive-translate/immersive-translate#68]
不知道现在有没有这个功能，本地同时在使用 Edge，Chrome，Firefox，每次改动后 每个浏览器都要修改一遍，很麻烦。
希望：
1、在本地多个浏览器间自动同步设置；
2、可选择不同步的部分，比方api，每个浏览器的api可以独立设置 不同步，能多薅点免费字符量。

**Comment by theowenyoung** [comment]
最新版已经支持了呀， 通过google drive，同步设置～ 在【导入导出】里面

**Comment by ublock-ghost** [comment]
> 最新版已经支持了呀， 通过google drive，同步设置～ 在【导入导出】里面

后续会添加坚果云之类的webDave吗？Google这个对于某些用户可能存在使用问题
