### ISSUE TITLE
[Bug]: 悬停翻译欧陆词典和沉浸式冲突

### ISSUE THREAD

**Issue by keyboard3** [immersive-translate/immersive-translate#680]
### 插件版本号 | Version

0.7.2

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 请描述这个Bug | Describe the bug

悬停不显示沉浸阅读的段落翻译，只有在某个单词上显示欧路词典的单词翻译。chrome浏览器

**Comment by theowenyoung** [comment]
这两个功能本身是冲突的，建议只使用某一家的功能即可。
