### ISSUE TITLE
[Bug]: iOS safari 插件升级之后打开插件空白

### ISSUE THREAD

**Issue by keyboard3** [immersive-translate/immersive-translate#681]
### 插件版本号 | Version

0.7.2

### 平台 | Platform

iOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

iOS safari 插件升级之后打开插件空白，无悬浮球。卸载重装问题依然在

**Comment by keyboard3** [comment]
目前建议措施是换成[油猴脚本](http://localhost:3000/docs/installation/#%E9%80%9A%E8%BF%87%E6%B2%B9%E7%8C%B4%E8%84%9A%E6%9C%AC%E5%AE%89%E8%A3%85)

**Comment by theowenyoung** [comment]
0.7.8 正常了吗？
