### ISSUE TITLE
[Bug]: 输入框增强中，三次连击直接翻译选项设置无效

### ISSUE THREAD

**Issue by sunls233** [immersive-translate/immersive-translate#682]
### 插件版本号 | Version

0.7.2

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

<img width="1354" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/57647932/32ea1b79-aa4a-4833-afd5-484a006bb74d">
当这个选项关闭时，在谷歌搜索输入框中不使用 // 前缀，连击三次空格文本仍然会被翻译。

### 出现问题的网址 | URL

google.com

### 重现步骤 | To Reproduce

1. 关闭`启用快速连击 3 次<空格键>，直接翻译整个输入框为英语 (English)`选项
2. 打开谷歌，输入 “你好”，连击三次空格，文本会被翻译为 Hello
3. 当关闭这个选项时应该输入 “//你好”，才会被翻译

### 补充说明 | Additional context

这个选项关闭时，`导出/导入`中的当前配置：
<img width="1269" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/57647932/49b770f5-3f1e-43ff-bd41-1dd0c617a5f1">
这个选项开启时，`导出/导入`中的当前配置：
<img width="1305" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/57647932/cc13a57d-9e6f-4b51-a211-fbf118801954">

**Comment by keyboard3** [comment]
好的 下个版本修复
