### ISSUE TITLE
[Bug]: 插件无法打开使用

### ISSUE THREAD

**Issue by gmugu** [immersive-translate/immersive-translate#683]
### 插件版本号 | Version

0.7.2

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension, 油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

插件无法打开使用，在开发者工具中提示：

SyntaxError: Unexpected private name #u. Cannot parse class method with private name.

**Comment by keyboard3** [comment]
在哪个网址？ 有悬浮球，悬浮球无法打开？

**Comment by gmugu** [comment]
在任意网址都是，没有悬浮球出现

**Comment by keyboard3** [comment]
> 在任意网址都是，没有悬浮球出现
mac os 什么版本

**Comment by gmugu** [comment]
macOS Big Sur(11.4)

**Comment by gmugu** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/8317478/4371d9e0-3a18-4bf4-ac80-558bfaa40464)
<img width="285" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/8317478/ccafbecc-ed76-4f82-a201-b40e732541fb">

**Comment by keyboard3** [comment]
没有低版本备，我们很难复现这个问题。 可能是跟mac os 版本有关，或者你有Chrome浏览器嘛，试试它看看

**Comment by gmugu** [comment]
chrome没问题，应该是Safari版本太低的问题
