### ISSUE TITLE
[Bug]: youtube 视频字幕存在无法翻译的问题

### ISSUE THREAD

**Issue by lcyjerry** [immersive-translate/immersive-translate#685]
### 插件版本号 | Version

0.7.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

youtube 视频字幕存在无法翻译的问题

### 出现问题的网址 | URL

https://www.youtube.com/

**Comment by keyboard3** [comment]
再试下，应该可以了
