### ISSUE TITLE
[Bug]: 在某些网站打开翻译时,会不停的自动跳转滚动

### ISSUE THREAD

**Issue by Tinyu-Zhao** [immersive-translate/immersive-translate#687]
### 插件版本号 | Version

0.6.21

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在某些网站打开翻译时,会不停的自动跳转滚动

如下视频所示

https://github.com/immersive-translate/immersive-translate/assets/44396641/c9805bd4-c1df-45bb-9a96-fd71775eb0b8

### 出现问题的网址 | URL

https://community.m5stack.com/topic/957/solved-guru-meditation-error/9

### 重现步骤 | To Reproduce

1.进入上述网站
2.打开翻译
3.慢慢往下滑蛋

**Comment by Tinyu-Zhao** [comment]
类似的问题:
https://forum.m5stack.com/post/11558

https://github.com/immersive-translate/immersive-translate/assets/44396641/4df8b364-4eac-42d8-be0e-119f6d6d452a

**Comment by Benlee1129** [comment]
遇過相同的問題。
英國 https://www.channel5.com/ 內的字幕在翻譯後，都會跳動。

**Comment by keyboard3** [comment]
抱歉这么久回复。 楼主提到这两个站点适配了

**Comment by keyboard3** [comment]
> 遇過相同的問題。 英國 https://www.channel5.com/ 內的字幕在翻譯後，都會跳動。

你这网站没有没权限登录，这个可能需要你录个屏看下实际情况了
