### ISSUE TITLE
敲击空格三次，被翻译的内容无法撤回为原来的内容

### ISSUE THREAD

**Issue by you-hengh** [immersive-translate/immersive-translate#688]
### 您希望的更新和改进是什么 | Update or Improve

敲击空格三次，被翻译的内容无法撤回为原来的内容，

示例场景：需要被翻译的内容想做修改，但是三次空格后，内容被替换为翻译的内容，然后就无法撤回并修改了

### 补充说明 | Additional context

示例：
我希望明天下午两点会准时到达，翻译后，想修改时间为两点半，但无法通过撤销操作（command+z）让翻译后的内容变回原来的内容

我希望能够通过command+z来撤销翻译操作，能够让被翻译的内容回到原来的模样，方便我做修改

**Comment by keyboard3** [comment]
好的，我们看下

**Comment by keyboard3** [comment]
下个版本就支持

**Comment by keyboard3** [comment]
0.7.6 已支持撤销
