### ISSUE TITLE
自动翻译时与「自动无缝翻页」油猴脚本搭配的问题

### ISSUE THREAD

**Issue by pilgrimlyieu** [immersive-translate/immersive-translate#689]
### 您希望的更新和改进是什么 | Update or Improve

例如我开启了英文自动翻译，并且使用了油猴的「[自动无缝翻页](https://greasyfork.org/zh-CN/scripts/419215-%E8%87%AA%E5%8A%A8%E6%97%A0%E7%BC%9D%E7%BF%BB%E9%A1%B5)」脚本，然后在一些可自动翻页的英文网站如 Github Issues, Google 等就会出现问题：一开始正常显示翻译，往下拉的过程中反复出现翻译消失并重新加载的现象。

推测原因是「自动无缝翻页」脚本更新了网址，使「沉浸式翻译」插件更新翻译，造成阅读不流畅。

希望能够改进这个问题！非常棒的插件！

### 补充说明 | Additional context

![动画](https://github.com/immersive-translate/immersive-translate/assets/80107081/1831df6a-65fa-4cba-808f-b1b4c42658aa)

附个 GIF，希望有所帮助。图中所示操作大概是一开始进入网页，正常出现翻译，下滑，注意地址栏更新，脚本让多页内容合并，于是再往上拉，翻译消失并重新加载出现翻译。

**Comment by keyboard3** [comment]
github 不是分页的嘛，你怎么无限滚动的？

**Comment by pilgrimlyieu** [comment]
> github 不是分页的嘛，你怎么无限滚动的？

> 并且使用了油猴「[自动无缝翻页](https://greasyfork.org/zh-CN/scripts/419215-%E8%87%AA%E5%8A%A8%E6%97%A0%E7%BC%9D%E7%BF%BB%E9%A1%B5)」脚本

**Comment by pilgrimlyieu** [comment]
> 你在用户规则里这么写试试
> 
> ```
> [
>   {
>     "matches": [
>       "https://github.com/*/issues/*"
>     ],
>     "urlChangeDelay": 0
>   }
> ]
> ```

感谢，确实可行。不过是任何出现此类问题的都需要添加进规则里吗？这样似乎还是有点麻烦。不过还是非常感谢！

**Comment by keyboard3** [comment]
因为你是油猴脚本修改了默认的行为，理论上不会加到默认支持中。如果是网站自身的行为会做兼容

**Comment by pilgrimlyieu** [comment]
> 因为你是油猴脚本修改了默认的行为，理论上不会加到默认支持中。如果是网站自身的行为会做兼容

好的，感谢帮助！
