### ISSUE TITLE
为啥翻译的全是感叹号啊

### ISSUE THREAD

**Issue by Mrytn** [immersive-translate/immersive-translate#69]
![image](https://user-images.githubusercontent.com/31368606/216505216-fd504f18-d0fa-41de-904d-fc72f9e92f28.png)

**Comment by theowenyoung** [comment]
你用的什么翻译服务，翻译服务返回错误，可以切换下别的试试。是不是网络情况问题

**Comment by Mrytn** [comment]
刚才vpn配的韩国，现在切换到香港  可以正常翻译了

**Comment by Mrytn** [comment]
谢谢

**Comment by Mrytn** [comment]
不过现在配韩国有可以了  也不知道咋回事  应该不是这个原因
