### ISSUE TITLE
[Bug]: 在Opera One浏览器中无法使用输入框增强翻译功能

### ISSUE THREAD

**Issue by ZEERDEER** [immersive-translate/immersive-translate#693]
### 插件版本号 | Version

0.7.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Other

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在Opera One浏览器中无法使用输入框增强翻译功能
同样是Chromium 版本：115.0.5790.3
![image](https://github.com/immersive-translate/immersive-translate/assets/10573857/e8fbbbbd-cafe-4342-acb8-a104af307e31)

### 补充说明 | Additional context

在谷歌，duckduckgo，bing 等搜索引擎都无效。
在哔哩哔哩，GitHub的搜索框有效。
没有试更多的网站。

**Comment by FattySpring** [comment]
![80f3a48aaf4869c9c586449844352ec](https://github.com/immersive-translate/immersive-translate/assets/25144301/7d89d07e-1a62-4b5f-8b26-3d7371518976)
opera浏览器，需要在浏览器插件设置中开启[允许访问搜索页面结果]选项
