### ISSUE TITLE
GPT translation should translate tranches of 1500 characters instead of paragraphs.

### ISSUE THREAD

**Issue by Emasoft** [immersive-translate/immersive-translate#696]
### 您希望的更新和改进是什么 | Update or Improve

The GPT translation feature in Immersive Translate is awesome! The quality of the translation is way better than google or deepl. 
But there is a way to improve it even more! 
GPT understand how to translate a text from the entire context, not just from a single paragraph at time, like google translate or deepl. The bigger the context, the better is the translation accuracy.
The advantage of a bigger context is that it is much more consistent in translating names, verbs, pronouns, articles, genders, etc.
Currently even using the batch option, immersive translate still translate one paragraph for each query. The batch option is still interpreted as a list of independent queries by GPT, so it does not consider the text as originating from the same context.
To make use of the full capabilities of GPT-3.5 you shold add the option to send chunks of 1500-2000 characters for each query (for chinese, 1000 characters should be enough since 2000 chinese characters costs around 5000 tokens, while 2000 english characters are around 400 tokens). GPT-4, being the context 8k, can translate even 3000 characters for each query. GPT-3.5 with 16k is also available, and then even 6000 characters could be translated for each query.
Please add this option to immersive translate. Thanks! 🙏

**Comment by theowenyoung** [comment]
Sorry for the late reply. I think you can config it like this:

<img width="890" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/8300f7ea-cb61-4b90-9ade-c863cdbde4d2">

But I belive it will very slow.
