### ISSUE TITLE
[Bug]: immersive translator 与 Firefox 上两个常用的高亮插件不兼容

### ISSUE THREAD

**Issue by Andy-AO** [immersive-translate/immersive-translate#697]
### 插件版本号 | Version

0.6.18

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

当高亮文本之后，被高亮的部分被识别为新出现的内容而被二次翻译，导致页面混乱。

# 视频

https://github.com/immersive-translate/immersive-translate/assets/38101170/f4eb2d04-8db0-4824-99fe-0d3b98d0fccd

https://github.com/immersive-translate/immersive-translate/assets/38101170/2b8a7bf6-a453-48a9-90e9-8f666345b25f

# 扩展链接

Highlight – 下载 🦊 Firefox 扩展（zh-CN） https://addons.mozilla.org/zh-CN/firefox/addon/highlight-by-trix/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

Highlighter + Notes – 下载 🦊 Firefox 扩展（zh-CN） https://addons.mozilla.org/zh-CN/firefox/addon/highlighter-notes/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

**Comment by theowenyoung** [comment]
下个版本修复～

**Comment by theowenyoung** [comment]
最新版已兼容。
