### ISSUE TITLE
浮窗不能关闭？chrome浏览器找了很久没找到关闭

### ISSUE THREAD

**Issue by kangodyan** [immersive-translate/immersive-translate#699]
### 您希望的更新和改进是什么 | Update or Improve

难道没有做关闭浮窗的功能？而且我点击禁止翻译那个网站了，还是有浮窗出来！！
![image](https://github.com/immersive-translate/immersive-translate/assets/36319737/41615d77-fce9-4767-b5e0-4f2bb9251958)

**Comment by theowenyoung** [comment]
触摸屏才会显示，设置为 【永不翻译该网站】 即可隐藏。


或者在触摸屏页面下打开【设置页】，【界面设置】 里可以关闭。

**Comment by kangodyan** [comment]
@theowenyoung 还是没找到在哪里关闭......界面设置哪个选项？
![微信截图_20230719145840](https://github.com/immersive-translate/immersive-translate/assets/36319737/65422bb4-e88f-4c09-8fbf-49bbca3f229d)

**Comment by theowenyoung** [comment]
在这个设置页面，打开浏览器的【检查元素】，切换为 移动浏览器模式，再刷新一下页面，就能看到了

**Comment by kangodyan** [comment]
有了，thx！
![image](https://github.com/immersive-translate/immersive-translate/assets/36319737/35df6587-0615-4f32-a4a4-9dbbaca2f559)
