### ISSUE TITLE
本地pdf翻译为啥翻译不了

### ISSUE THREAD

**Issue by Mrytn** [immersive-translate/immersive-translate#70]
![image](https://user-images.githubusercontent.com/31368606/216523372-bb4d1a07-06bb-49c0-bec9-654e1a601da3.png)

**Comment by theowenyoung** [comment]
如果遇到不能翻译的pdf，建议先用其他工具转成 html 后再翻译。

pdf有点难, 目前有一些别的更有优先级的事在做.. 所以暂时还没有进一步优化pdf。 希望能理解～

**Comment by theowenyoung** [comment]
PDF相关问题统一在 https://github.com/immersive-translate/immersive-translate/issues/37 里讨论，暂时先关闭这个问题了
