### ISSUE TITLE
右键菜单按钮标题动态显示"翻译/还原"

### ISSUE THREAD

**Issue by reece00** [immersive-translate/immersive-translate#700]
### 您希望的更新和改进是什么 | Update or Improve

点击后标题改变，出现未翻译文本能明确显示没有点错。
参考其他扩展
![image](https://github.com/immersive-translate/immersive-translate/assets/37351410/87ab075b-6658-4ec3-9bf3-0ffadde93095)

**Comment by theowenyoung** [comment]
感谢建议，很好的建议，未来应该会加入该特性。

**Comment by keyboard3** [comment]
![image](https://github.com/user-attachments/assets/324692da-988d-4780-8c6c-ae9c58e4d482)
