### ISSUE TITLE
feat: support force refresh cache ?

### ISSUE THREAD

**Issue by jiangying000** [immersive-translate/immersive-translate#701]
### 您希望的更新和改进是什么 | Update or Improve

Could you support force refresh cache on a website ?

**Comment by theowenyoung** [comment]
Sorry for the late reply. Maybe you can turn off the cache temporarily in the [About] settings so you can force a cache refresh.
We don't have any plans to do more fine-grained management of the cache at the moment, thanks for your suggestion.
