### ISSUE TITLE
翻译过后url跳转链接不显示了

### ISSUE THREAD

**Issue by Phoebus888** [immersive-translate/immersive-translate#703]
### 您希望的更新和改进是什么 | Update or Improve

源图
![image](https://github.com/immersive-translate/immersive-translate/assets/45359605/111eb876-baa7-4171-aafc-505139d2a175)
翻译过后的图
![image](https://github.com/immersive-translate/immersive-translate/assets/45359605/b1ca3059-9a5e-4a29-b2d5-efac9538f9c7)

### 补充说明 | Additional context

能不能翻译后把url跳转也显示出来，这样可以直接跳转过去

**Comment by theowenyoung** [comment]
已知问题，因为我们用的是纯文本翻译，所以目前确实无法显示链接。所以推荐使用双语翻译，这样既保留了原文，又能快速对照译文。

**Comment by theowenyoung** [comment]
#635 重复

**Comment by mefengl** [comment]
@theowenyoung 感觉适合用 https://github.com/sindresorhus/linkify-urls ?
它能提取链接然后换回 a tag

**Comment by theowenyoung** [comment]
这个库只能解决 https://xxxx.com 这种链接。

没法解决段落中有文本，有含义的超链接

**Comment by mefengl** [comment]
的确
