### ISSUE TITLE
与水印共能冲突会导致浏览器进入死循环从而内存崩溃

### ISSUE THREAD

**Issue by aikec** [immersive-translate/immersive-translate#704]
### 您希望的更新和改进是什么 | Update or Improve

飞书文档现在无法正常使用该插件,企业微信的腾讯文档也会出现这样的情况。

### 补充说明 | Additional context

你好，可以向你这里提一个冲突bug吗？问题上下文:
1. 飞书文档水印时防止篡改的，但是改插件会去强行去改水印的DOM，导致水印的防策略机制和插件的更改进入了死循环，导致内存不足浏览器崩溃。
2. 目前我们这水印的逻辑并不好修改，想让插件这边做下兼容，比如说插件只去更改 元素本身有text的DOM。
3. 这个插件我们这边的飞书客户确实挺多人用的，但是现在该插件与我们的产品无法兼容，实在是太遗憾了。

**Comment by theowenyoung** [comment]
最新版应该已经兼容了飞书的文档。应该已经不会冲突了吧？

**Comment by keyboard3** [comment]
0.7.6 已适配 https://immersivetranslate.com/docs/CHANGELOG/#076

**Comment by theowenyoung** [comment]
对的～ 看到你在商店的留言了。

**Comment by aikec** [comment]
> 最新版应该已经兼容了飞书的文档。应该已经不会冲突了吧？

同学 这个问题又在v0.11.5 又出现了 帮你看看哈

**Comment by theowenyoung** [comment]
又出现指的是，开启翻译的情况下，还是说 安装了插件就会有死循环？ @aikec 

我这里似乎正常。

**Comment by aikec** [comment]
是的 只要使用该插件就会 崩溃 v11.5 版本

**Comment by aikec** [comment]
你安装 11.5版本去 飞书文档中体验下就可以复现了  https://feishu.feishu.cn/drive/home/

**Comment by theowenyoung** [comment]
[My Movie 2.mp4.zip](https://github.com/immersive-translate/immersive-translate/files/13422538/My.Movie.2.mp4.zip)

我这里似乎是正常的，会不会是别的插件影响的？

要不在 隐私模式下，只允许沉浸式翻译插件（排除其他插件的影响），录个屏？

**Comment by aikec** [comment]
你飞书账号多少 我们直接加飞书聊怎么样 ？这边录屏体积太大了 发不了 而且面对面聊也比较方便些 （我只运行了一个插件, 实在chrome 浏览器复现的）

**Comment by theowenyoung** [comment]
可以， https://horuspass.com/send?token=1700554437056#U2FsdGVkX192KsNo/e6fROVuMDn7wQCTA6C6HA1chRfDcq5tLWT8dKEk6G0rxwVdiTF+hyXVSPlZSGMjDfdqOrfMrPiG6XqilWKYNvmoUrw1haG56xH+lDuAmG4jAiAA42+kjQNN4ZeY/ju82xvxVSGSa30jK0AN93Z/1vqrWkxPzhmLvpCz+sUXUGhJ93xZAg7wagCaUPcwuSGZ78gafvAknZdJA41ZAzvSvGfEHaEaCAcyugVHt7+uX1KIfKoC/gY0eMdRt14nlnVuJIOBWA==

点进去之后，点【View】

**Comment by aikec** [comment]
点 view 没有反应 请求发不出去 要不你通过飞书 oncall（影响非常快）然后转到研发这边进行沟通怎么样？

**Comment by theowenyoung** [comment]
sorry, 刚那个链接可能10分钟过期了，我重新生成了一个（7天有效期），里面是我的飞书链接：

https://onetimesecret.com/secret/c257lx26eoo0lu2m7gs7t36qflc1uy
