### ISSUE TITLE
针对 Perplexity.ai 英文结果翻译优化

### ISSUE THREAD

**Issue by wulabing** [immersive-translate/immersive-translate#707]
### 您希望的更新和改进是什么 | Update or Improve

针对 Perplexity.ai 英文结果翻译进行优化，目前存在错位，遗漏，乱码问题

### 补充说明 | Additional context

测试页面：https://www.perplexity.ai/search/9ed11712-63f0-4efc-8f53-76f4b11c46be

**Comment by theowenyoung** [comment]
可以截个图吗？我这是这样：

<img width="1082" alt="图片" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/ebf4f50a-a85d-4207-b105-1fd3e6b5b2bf">

**Comment by wulabing** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/17747326/21661c63-5c04-497a-835a-b80cdf8174b4)
下面设计的代码关键字的时候翻译会错位这样

**Comment by theowenyoung** [comment]
抱歉这么晚回复，再次检查了下这个问题，比较棘手，他们的网页非常特殊，可能需要重新研究下我们的分段策略，加了一个 bug-todo 的label，优先解决下。

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/bdbe5b6d-8133-402e-b3b3-4b2d3a365378)
1.2.2 已修复

**Comment by wulabing** [comment]
感谢
