### ISSUE TITLE
[Bug]: OpenAI API 翻译几乎不可用

### ISSUE THREAD

**Issue by LuciusChen** [immersive-translate/immersive-translate#708]
### 插件版本号 | Version

0.7.6

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/4947981/0b7261f5-689e-4b32-a7d2-c0744ca1ad81)

### 出现问题的网址 | URL

https://karthinks.com/software/avy-can-do-anything/

### 重现步骤 | To Reproduce

几乎所有英文网站都无法利用 openai 翻译，试了下 api 在其他工具是正在的，在沉浸式插件中也可以验证通过。沉浸式翻译插件选择 Google 翻译可以正常使用。

**Comment by theowenyoung** [comment]
我这里还好，你点击下？看看提示什么。

<img width="1244" alt="图片" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/f8b70db8-f7da-4016-85fa-be310a094adf">

**Comment by LuciusChen** [comment]
应该是免费 api 有速率限制，我设置了付款方式就可以了，打扰了。
