### ISSUE TITLE
将 透明效果->半透明效果 ，然后增加 全透明效果

### ISSUE THREAD

**Issue by sunshaoce** [immersive-translate/immersive-translate#709]
### 您希望的更新和改进是什么 | Update or Improve

现在的透明效果，没办法通过调整样式数值来完全隐藏，若隐若现的样子其实更加吸引注意力。建议增加一个全透明的效果，然后可以考虑加个特殊符号或图层，来显示译文位置。感谢！

**Comment by keyboard3** [comment]
0.8.0 已支持调节透明度
