### ISSUE TITLE
[Bug]: iPad端更新后悬浮球消失且无法翻译

### ISSUE THREAD

**Issue by xm1005** [immersive-translate/immersive-translate#710]
### 插件版本号 | Version

0.7.7

### 平台 | Platform

iOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

更新至最新版本后，悬浮球消失，手动点击扩展翻译也没有反应

**Comment by keyboard3** [comment]
0.7.8 已修复 更新下
