### ISSUE TITLE
功能请求：对PDF文件和网页翻译提供独立的翻译API设置选项

### ISSUE THREAD

**Issue by hongwen000** [immersive-translate/immersive-translate#711]
### 您希望的更新和改进是什么 | Update or Improve

1. 添加一个选项，允许用户为PDF文件和网页设置不同的翻译API。
2. 改进处理复杂PDF布局的方式。

### 补充说明 | Additional context

尊敬的开发者您好：

我最近在使用过程中发现您的插件直接翻译PDF文件，这个功能解决了我长期存在的学术文献翻译需求，而这些文献通常包含丰富且复杂的内容。

但在我使用中，我发现在翻译PDF文件和网页时，存在不同的翻译需求。因为PDF文件通常含有复杂的内容，我希望能使用更为智能的基于GPT API的翻译；而对于网页的内容，使用如Google翻译这样的通用翻译API就已经足够。

在现有功能下，我需要根据正在阅读的内容类型手动切换翻译设置，这样无疑增加了使用中的不便。因此，我提议开发一项新功能，允许用户根据PDF文件和网页的特性分别设置翻译API，这样无疑可以简化用户操作，提升使用体验。

另外，我注意到在翻译一些排版较为复杂的PDF时，现有的翻译功能表现不尽人意。因此，我建议对此进行持续改进。

总的来说，我的建议是：

1. 开发新功能，允许用户为PDF文件和网页分别设置翻译API。
2. 对于处理复杂PDF布局的翻译方法进行改进。
我认为这些改进的实施能够显著提升沉浸式翻译功能的用户体验。

谢谢！

**Comment by theowenyoung** [comment]
感谢建议，目前沉浸式翻译的首要目标是保持工具的简单易用性～ 所以暂时没有计划额外增加该特性。

建议手动切换即可。
