### ISSUE TITLE
[Bug]翻译无反应: 

### ISSUE THREAD

**Issue by im-zhangchenyi** [immersive-translate/immersive-translate#714]
### 插件版本号 | Version

0.7.7

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

今天突发情况：点击“翻译”按钮或使用快捷键翻译网页全文时，网页无反应，且无Loading 样式出现。
Chrome版本：114.0.5735.198（正式版本） (x86_64)
macOS版本：13.3.1 (a) (22E772610a)
翻译服务：谷歌翻译
<img width="1226" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/70785131/cd75dbf8-67ab-4ec9-982a-1106bbeb7dda">

### 出现问题的网址 | URL

所有网址

### 重现步骤 | To Reproduce

1. 打开任意英文站点
2. 点击“翻译”按钮

### 补充说明 | Additional context

1. 卸载重装后依旧无效
2. 使用“划词翻译”翻译网页全文没有问题

**Comment by theowenyoung** [comment]
试试 0.7.8 版本呢？

**Comment by lavender010101** [comment]
遇到相同问题，有时只有第一个标题有译文，其他内容在翻译加载动画消失后没有显示译文

**Comment by theowenyoung** [comment]
暂时关掉了哈，有问题再反馈～
