### ISSUE TITLE
将透明效果纳入学习模式, 添加是否开启学习模式的开关, 统一学习模式的行为/功能

### ISSUE THREAD

**Issue by Ekuboh** [immersive-translate/immersive-translate#719]
### 您希望的更新和改进是什么 | Update or Improve

1. 建议单独划分一个`学习模式`的开关, 设置内可选择学习模式的样式, 其中包括`透明效果`和`模糊效果` (学习模式的行为均是翻译后会遮掩译文, 区别为遮掩的方式是模糊还是透明)
2. 用户可自行设置`透明效果`的**透明度**
3. `透明效果`也可使用模糊效果的功能快捷键`显示/隐藏译文模糊效果`, 统一学习模式的快捷键

ps:  其实感觉有了透明效果, 模糊效果可以不要了, 模糊效果一堆黑漆漆的译文块很影响注意力

**Comment by keyboard3** [comment]
新版可以针对透明度调节和鼠标滑上去的显示

**Comment by Ekuboh** [comment]
可以像"模糊模式"一样, 为"透明模式"提供一个快捷键, 在"透明/不透明"进行切换吗
