### ISSUE TITLE
太强了作者，我想支持你一下，但GitHub的支持有点复杂，能提供一个支付宝收款码或者淘宝购买支持？

### ISSUE THREAD

**Issue by who10086** [immersive-translate/immersive-translate#72]
我看作者似乎比较在意隐私，甚至可以提供一个网页的类似论坛月卡购买支持也行。（最好还是支付宝收款码，因为那样比较简单）

**Comment by theowenyoung** [comment]
真的很感谢！（你 get 到了我的纠结...） （你有推荐的这种论坛的月卡的东西吗？)

**Comment by HaveF** [comment]
> 我看作者似乎比较在意隐私，甚至可以提供一个网页的类似论坛月卡购买支持也行。（最好还是支付宝收款码，因为那样比较简单）

@who10086 
Github 支持其实不复杂...绑一个双币的信用卡就行了,一次打钱或是月月打钱就行了... 难道你没想绑定之后试试 GitHub Copilot 🐶

@theowenyoung 什么卡之类的也可以考虑你在本地平时用的卡或服务呀...不管哪国的，淘宝上买好发给你码就行

**Comment by Hinlavic** [comment]
> 真的很感谢！（你 get 到了我的纠结...） （你有推荐的这种论坛的月卡的东西吗？)
国内的爱发电，国外的PATREON，不都是月付订阅的形式吗。
国内的那个就不多说了。
P站用个PAYPAL绑张银联的“借记卡”都行，我刚捐过1块钱，支付方式门槛低。GITHUB这种交钱之前还要先填一堆东西的确实不喜欢。
不过要特别注意汇率的问题：
PAYPAL付款那个记得选择使用银联的汇率，基本接近实时汇率，不要用PAYPAL自己默认的那个实时汇率基础上额外+4%的坑爹自定义汇率。
作者最好在P站的介绍中注明使用的接受币种或者默认美元，不然订阅的人除了PAYPAL那个坑爹汇率外，很可能还要再经历一次PATREON的坑爹汇率，同样大概是正常汇率的基础上额外+4.5%左右。

再说到隐私，现在就没啥靠得住的隐私支付方式。
安全性最好的莫过于现金；早期的去中心加密货币隐私性倒是不错，可惜没有任何物质抵押，更多的是炒作，人人喊打，过去一年币值缩水近50%；新出现的所谓稳定币连去中心都做不到，锚定美元，就靠不断买进美元活者，一样没有地基，而美元自己就是个印钞机，更何况美元的附庸，而且汇率波动不见得美元就是最值钱的那个货币；不过又是一场资本的游戏罢了，养几年就可以减剪羊毛了，而且由于“稳定”，一般人恐怕连赚钱的一点点机会都没有，纯纯的待宰羔羊，说不定哪天一早醒来钱就没了，这还不如比特币呢。
第三方和银行卡支付买卖双方的个人信息基本都是透明的，更谈不上隐私；唯一还算有点靠谱，恐怕也只剩下央行发行的正在推行的数字人民币了，以此方式发生的交易，交易双方的信息好歹仅限于银行和国家监管机构可见，要隐私不如放个数字人民币钱包的收钱二维码。

一些无赖，一些吐槽，不见得是对的。

**Comment by theowenyoung** [comment]
patreon 已经支持了。  

主要是国内的渠道～

**Comment by theowenyoung** [comment]
感谢大家～ 我已经开通了国内的 爱发电主页： <https://afdian.net/a/translate> ,  可以使用微信和支付宝赞助了～
