### ISSUE TITLE
输入框增强的翻译服务的单独配置

### ISSUE THREAD

**Issue by ATFmxyl** [immersive-translate/immersive-translate#720]
### 您希望的更新和改进是什么 | Update or Improve

为了区分在输入框增强页面和普通网页翻译时所使用的翻译服务，我们需要添加一个配置项。这样，在普通网页翻译时，我们可以使用微软/谷歌的翻译服务；而在输入框增强时，我们可以选择使用自己申请的一些翻译API。

**Comment by hhe5586** [comment]
输入框三连空格键，用不了是什么原因？

**Comment by theowenyoung** [comment]
> 输入框三连空格键，用不了是什么原因？

可以看下兼容性： https://immersivetranslate.com/docs/input/#%E5%85%BC%E5%AE%B9%E6%80%A7

**Comment by keyboard3** [comment]
下个版本会支持

**Comment by ATFmxyl** [comment]
好的

**Comment by keyboard3** [comment]
0.8.0 已经支持 输入增强和鼠标悬停独立设置翻译服务
