### ISSUE TITLE
【API翻译功能改进】增加电子书多页翻译和关联上下文字幕翻译设置

### ISSUE THREAD

**Issue by LaLuna302** [immersive-translate/immersive-translate#722]
无论是 OpenAI 还是 DeepL 都能实现关联上下文的智能翻译，一次翻译的字符量越多，翻译质量就越高。若是逐行翻译或段落翻译，关联上下问的优势将无法体现。增加电子书整页或多页同时翻译和关联上下文字幕翻译的设置选项，可解决因逐行翻译或段落翻译导致速度和准确率下降的问题。

**Comment by theowenyoung** [comment]
deepl 默认情况下是发送多个段落的。每次请求最多1800字。 openai 由于速度的问题（字数越多越慢），默认是每次一个段落。可以在设置页面自定义调整每次发送的段落数。
