### ISSUE TITLE
[Bug]: 长段落自动换行识别问题

### ISSUE THREAD

**Issue by Wongony** [immersive-translate/immersive-translate#723]
### 插件版本号 | Version

0.7.9

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

如果文本中包含 "(i.e. at higher addresses)" 类似的文本，"i.e." 的 "." 有可能被识别成句子的结束符，导致文本插入换行符分隔文本。

### 出现问题的网址 | URL

https://www.cs.virginia.edu/~evans/cs216/guides/x86.html

### 重现步骤 | To Reproduce

1.配置文件里设置长文本自动换行。
2.翻译文本后需要 "(i.e. )" 文本，可能出现上述情况。

**Comment by theowenyoung** [comment]
和 #86 重复，暂时关掉这个了哈～
