### ISSUE TITLE
[Bug]: 翻译后位置错误

### ISSUE THREAD

**Issue by oeieo** [immersive-translate/immersive-translate#724]
### 插件版本号 | Version

0.7.9

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

机器人回答的内容，翻译的时候正常出现，等翻译结束后就会出现在英语内容的上方，会有一点心理上的不适应
![image](https://github.com/immersive-translate/immersive-translate/assets/112836653/8238a49a-c76d-40cb-9cd3-18f990115bec)

### 出现问题的网址 | URL

https://pi.ai/talk

### 重现步骤 | To Reproduce

正常对话就可以复现

### 补充说明 | Additional context

太爱这个插件了，十分感谢作者！！！

**Comment by theowenyoung** [comment]
这个有点不太好适配了，目前的效果是能做到的最佳效果了..
