### ISSUE TITLE
[Bug]: chrome 下插件没法用，前段时间是好的

### ISSUE THREAD

**Issue by isgbuddy** [immersive-translate/immersive-translate#725]
### 插件版本号 | Version

0.7.9

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

测试了一下，所有 Translation Service 都不通，但是我在浏览器里是能访问翻译网站的

**Comment by FattySpring** [comment]
有没有设置代理

**Comment by keyboard3** [comment]
没有反馈 暂时关闭
