### ISSUE TITLE
建议本地适配规则不要自动更新，可以手动设置

### ISSUE THREAD

**Issue by ChloeKurumi** [immersive-translate/immersive-translate#726]
### 您希望的更新和改进是什么 | Update or Improve

建议本地适配规则不要自动更新，或者可以选择历史版本的规则，避免每次更新造成误伤。
对我翻译看小说来说，之前的版本已经够用了，很稳定了，不希望更新了，但突然的规则更新让人猝不及防。
平时都是翻译那么几个固定的网站，本来一直用的很舒服，很稳定，但是突然规则更新却产生了bug，导致漏翻。

**Comment by theowenyoung** [comment]
请问是哪个网站更新之后有bug了呢？

**Comment by ChloeKurumi** [comment]
> 请问是哪个网站更新之后有bug了呢？
小说网站，看小说翻译的时候，以前好的，现在基本上每页都有那么几段漏掉了
https://syosetu.com/

**Comment by theowenyoung** [comment]
你用的是什么翻译服务？ 我试了谷歌似乎是正常的。

**Comment by ChloeKurumi** [comment]
> 你用的是什么翻译服务？ 我试了谷歌似乎是正常的。
我用的彩云，比如这一页

https://ncode.syosetu.com/n3814hg/7/

**Comment by theowenyoung** [comment]
测试了一下，这个似乎是Bug， 下个版本会修复～ 并不是规则的变更导致的。
