### ISSUE TITLE
[Bug]: 和Language Reactor 5.0.0同步开启后，youtube内翻译失灵，无响应

### ISSUE THREAD

**Issue by plutomiao** [immersive-translate/immersive-translate#727]
### 插件版本号 | Version

v0.7.9

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

和Language Reactor 5.0.0插件一同开启后，youtube内翻译失灵，无响应。然后我扩展库管理里面禁用了Language Reactor 之后，刷新之后又可以开启了。

### 出现问题的网址 | URL

随便哪个都是这样

### 重现步骤 | To Reproduce

2个插件一同开张，都开启，随便点击任一视频，沉浸式翻译没有反应，英文无法翻译

### 补充说明 | Additional context

无

**Comment by theowenyoung** [comment]
这两个插件同时都对youtube有改动，有冲突是正常的。建议在youtube里只选择使用其中之一就好了。
