### ISSUE TITLE
Bug：在该网站上翻译出现循环错位

### ISSUE THREAD

**Issue by Alphabet1226** [immersive-translate/immersive-translate#73]
https://old.reddit.com/r/Bitcoin/comments/10sggko/damus_app_banned_from_china_app_store/
<img width="1586" alt="image" src="https://user-images.githubusercontent.com/51783873/216741697-219e67bb-17ce-4b11-b3d3-1a339b744a53.png">

**Comment by theowenyoung** [comment]
<img width="1644" alt="Screenshot 2023-02-04 at 10 29 24" src="https://user-images.githubusercontent.com/62473795/216741750-5d7ddac6-b7c5-4a89-a487-c929e2a0a50a.png">

**Comment by theowenyoung** [comment]
我这好像正常
