### ISSUE TITLE
[Bug]: indie hacker 站点的内容主体区域不会被翻译

### ISSUE THREAD

**Issue by xdlrt** [immersive-translate/immersive-translate#730]
### 插件版本号 | Version

0.7.9

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

https://www.indiehackers.com/@Mubs/finding-the-time-for-side-projects-d3fd11de76

![image](https://github.com/immersive-translate/immersive-translate/assets/13093537/6b36409c-1813-43ff-a202-59dbd3749f59)

内容主体区不会被翻译，其它部分可以。

### 出现问题的网址 | URL

https://www.indiehackers.com/@Mubs/finding-the-time-for-side-projects-d3fd11de76

### 重现步骤 | To Reproduce

直接点击翻译按钮
![image](https://github.com/immersive-translate/immersive-translate/assets/13093537/c27f5c82-94d2-4e07-9e5b-1cb5e00d35aa)

**Comment by keyboard3** [comment]
我试了可以的，你再试试？

**Comment by xdlrt** [comment]
现在可以了，当时试了几次都不行
