### ISSUE TITLE
[Bug]: 这个页面无法翻译

### ISSUE THREAD

**Issue by cyanhao** [immersive-translate/immersive-translate#731]
### 插件版本号 | Version

0.7.11

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

https://github.com/orgs/community/discussions?discussions_q=     这个网页点击翻译全文没有反应，设置里勾选全部翻译也不行。

### 出现问题的网址 | URL

https://github.com/orgs/community/discussions?discussions_q=

**Comment by theowenyoung** [comment]
感谢反馈，已修复。
