### ISSUE TITLE
頁面上的［超連結］標簽會被覆蓋

### ISSUE THREAD

**Issue by Benlee1129** [immersive-translate/immersive-translate#732]
### 您希望的更新和改进是什么 | Update or Improve

請忽略超連結標簽，不要覆蓋或翻譯。

**Comment by keyboard3** [comment]
你可以去設定中的開發者填寫使用者如下使用者規則自行實現。
`[{
      "id": "all",
      "matches": ["*"],
      "stayOriginalSelectors": ["a"]
    }]`
