### ISSUE TITLE
[Bug]: chrome网页翻译之后变成左右两版，左边是空白

### ISSUE THREAD

**Issue by fanxiaoyu0** [immersive-translate/immersive-translate#733]
### 插件版本号 | Version

0.7.11

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

chrome网页翻译之后变成左右两版，左边是空白

### 出现问题的网址 | URL

任何谷歌网页

### 重现步骤 | To Reproduce

1.随便打开一个谷歌搜索的网页。
2.点击翻译。
![如下图](https://raw.githubusercontent.com/fanxiaoyu0/pictures/main/image-20230720173423951.png)

**Comment by theowenyoung** [comment]
有启用其他插件吗？ 有可能你被分配到了谷歌的A/B test...

**Comment by fanxiaoyu0** [comment]
我把其他插件都禁用了，还是上面的情况

**Comment by fanxiaoyu0** [comment]
只剩下沉浸式翻译一个扩展程序，还是会出现上面的情况
![](https://raw.githubusercontent.com/fanxiaoyu0/pictures/main/image-20230720200009877.png)

**Comment by fanxiaoyu0** [comment]
当我退出谷歌账号的登录时，沉浸式翻译一切正常
![](https://raw.githubusercontent.com/fanxiaoyu0/pictures/main/image-20230721004958806.png)
当我重新登录谷歌账号时，原来的问题又出现了
![](https://raw.githubusercontent.com/fanxiaoyu0/pictures/main/image-20230721005415890.png)
然后我使用谷歌浏览器中“重置设置”的功能
![](https://raw.githubusercontent.com/fanxiaoyu0/pictures/main/image-20230721005610045.png)
重置完之后重新登录谷歌账号，原来的问题又出现了。

**Comment by theowenyoung** [comment]
再试试，我加了一个规则～

**Comment by theowenyoung** [comment]
点击一下浏览器图标，更新最新规则。

**Comment by fanxiaoyu0** [comment]
谢谢你，没想到这么晚了你们还在工作，问题解决了，为什么会出现这样的问题？
当然致以最高的敬意，respect！会向更多人推荐你们的软件。

**Comment by fanxiaoyu0** [comment]
May close this issue.

**Comment by theowenyoung** [comment]
应该是谷歌的A/B test，我们的默认规则没有覆盖到谷歌的另一个界面，导致出问题。刚好群里有一位同学遇到过这个问题，我咨询了他解决方案。
