### ISSUE TITLE
希望翻译 PDF 时能支持深色模式

### ISSUE THREAD

**Issue by shension** [immersive-translate/immersive-translate#734]
### 您希望的更新和改进是什么 | Update or Improve

我当前使用的是 Chrome 浏览器，搭配 Dark Reader 插件，在浏览网页时可以完美适配深色模式，希望翻译 PDF 时也能支持深色模式，谢谢。
PS：我不知道这个建议是不是提错对象了，应该提给 Dark Reader ？如果提错了请见谅。

**Comment by theowenyoung** [comment]
抱歉很晚才回复。该特性技术上无法实现哈。
