### ISSUE TITLE
[Bug]: 翻译会把图标一起翻译了

### ISSUE THREAD

**Issue by Calm-er** [immersive-translate/immersive-translate#736]
### 插件版本号 | Version

0.7.11

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

翻译会把图标一起翻译了
<img width="1468" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/44333360/ae62ac50-ef3b-4006-ab95-13a4a23ab6c5">
<img width="1470" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/44333360/b9225af4-3b29-4fbe-8c6e-e0505d8ce81e">
<img width="1470" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/44333360/e8320068-89f6-42bd-9eeb-6e6ccc6916db">

### 出现问题的网址 | URL

https://m3.material.io/components/bottom-app-bar/overview

**Comment by ygycjdr** [comment]
是的，在noiton中选择图标时，两组图标似乎也是重复的
Yes, it seems that when selecting concept icons, both groups of icons are duplicated.

**Comment by FattySpring** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/25144301/5f2ed694-0141-40eb-be78-86290f0bc8ab)

是否是使用了其他翻译工具，使用沉浸式翻译没有复现该问题

**Comment by theowenyoung** [comment]
> ![image](https://user-images.githubusercontent.com/25144301/255397931-5f2ed694-0141-40eb-be78-86290f0bc8ab.png)
> 
> 是否是使用了其他翻译工具，使用沉浸式翻译没有复现该问题

sorry, 被我修复了，忘记关闭这个issue了。

**Comment by theowenyoung** [comment]
> 



> 是的，在noiton中选择图标时，两组图标似乎也是重复的 Yes, it seems that when selecting concept icons, both groups of icons are duplicated.

有具体地址吗？

**Comment by ygycjdr** [comment]
![截屏2023-09-29 16 31 14](https://github.com/immersive-translate/immersive-translate/assets/52322987/88a4bf3d-6cea-422a-9abe-50eda0a331c6)
现在没问题了
