### ISSUE TITLE
[Bug]:  这个网站根本不显示红色的小按钮 

### ISSUE THREAD

**Issue by zgj1112** [immersive-translate/immersive-translate#739]
### 插件版本号 | Version

0.5.6.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

 这个网站不显示红色的小按钮 

### 出现问题的网址 | URL

https://byrut.org/

### 重现步骤 | To Reproduce

打开看不到

### 补充说明 | Additional context

 这个网站不显示红色的小按钮

**Comment by keyboard3** [comment]
更新下版本，版本太老了。https://immersivetranslate.com/ 官网打开油猴脚本安装最新的。现在已经到0.7.12了
