### ISSUE TITLE
Feature Request：能否考虑支持下 Readwise Reader？

### ISSUE THREAD

**Issue by zzkcode** [immersive-translate/immersive-translate#74]
目前在 [Readwise Reader](https://readwise.io/read) 中看 Youtube 视频使用插件翻译后没有效果，能否考虑支持下或者帮忙看下是什么问题？谢谢。

<img width="1416" alt="image" src="https://user-images.githubusercontent.com/14883608/216741903-6b6029aa-31ad-4585-b0c4-2fb528965f61.png">

PS：不知道作者是否使用 Reader，如果我能提供什么有用信息可以 comment 下，感谢。

**Comment by theowenyoung** [comment]
如何在readwise里看youtube？ 可以分享一个链接吗。

**Comment by zzkcode** [comment]
直接把 youtube 链接添加到 Readwise Reader 里面就可以，或者用 [Readwise Highlighter 插件](https://chrome.google.com/webstore/detail/readwise-highlighter/jjhefcfhmnkfeepcpnilbbkaadhngkbi)。

**Comment by theowenyoung** [comment]
我测试了一下，是可以翻译的呀。

<img width="1034" alt="Screenshot 2023-02-04 at 12 48 12" src="https://user-images.githubusercontent.com/62473795/216749105-6130dc25-12ff-4b6a-9f51-925e3a9c1ffc.png">

**Comment by zzkcode** [comment]
我刚刚试了下：在隐私模式下可以翻译，回到正常模式又不行，所以尝试把 Readwise Highlighter 插件重新启用了下，现在可以了。感谢❤️
