### ISSUE TITLE
能否在地址栏右侧加入一个小图标？

### ISSUE THREAD

**Issue by realcirno** [immersive-translate/immersive-translate#740]
### 您希望的更新和改进是什么 | Update or Improve

地址栏右侧希望能够加入一个翻译的小图标，点击后即可翻译，这个比较方便

**Comment by FattySpring** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/25144301/98630186-d554-4e1a-bf2c-3a2e17b9ccbd)
浏览器地址栏右侧有图标

**Comment by keyboard3** [comment]
为什么不用快捷键翻译？不比鼠标滑动上去要方便？

**Comment by keyboard3** [comment]
> 为什么不用快捷键翻译？不比鼠标滑动上去要方便？

还可以右键的菜单中直接点击翻译啊
