### ISSUE TITLE
[Bug]: Yandex邮箱界面翻译异常，邮件内容不翻译，且右上角头像被多次显示

### ISSUE THREAD

**Issue by Mikachu2333** [immersive-translate/immersive-translate#741]
### 插件版本号 | Version

0.7.9

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

如题，示例图片见下方。
![图片](https://github.com/immersive-translate/immersive-translate/assets/63829496/c1ef603a-af0e-44e4-8c9e-4067b3c63d3c)

### 出现问题的网址 | URL

https://mail.yandex.com

### 重现步骤 | To Reproduce

1.登录yandex邮箱
2.打开任一邮件
3.翻译即可复现bug

### 补充说明 | Additional context

firefox插件快快更新！

脚本管理器之脚本猫无法使用，已向脚本猫官方申请适配。

**Comment by keyboard3** [comment]
保存成mht文件吧，不然不太方便快速复现  https://immersivetranslate.com/docs/faq/#%E7%BD%91%E9%A1%B5%E7%BF%BB%E8%AF%91%E6%9C%89%E9%97%AE%E9%A2%98%E5%A6%82%E4%BD%95%E4%BF%9D%E5%AD%98%E7%BD%91%E9%A1%B5%E5%8F%8D%E9%A6%88

**Comment by Mikachu2333** [comment]
firefox无法导出成mht……只好导出了完整的html
文件如下
https://workdrive.zoho.com/file/swdr9daf805c69e874b3793dbde62f3b62492

**Comment by versun** [comment]
@Mikachu2333 
我这边没有账号，所以还得麻烦你测试一下下面的规则：
在插件设置->开发者设置->Edit User Rules:
```
[
  {
    "matches": "mail.yandex.com",
    "selectors": [
      "article"
    ]
  }
]
```
然后点保存，刷新下mail的页面，再翻译看看

**Comment by Mikachu2333** [comment]
主要功能行了，不过邮件题目还是不翻译……就是这个最关键的地方看不懂，英文反而能看懂
网页链接如下
https://workdrive.zoho.com/file/arqk9787763121c6f4ca88e11cb17b3412552

**Comment by versun** [comment]
@Mikachu2333 
同样的方法，更新下规则：
```
[
  {
    "matches": "mail.yandex.com",
    "selectors": [
      "article",
      ".Title_subject*"
    ]
  }
]
```

**Comment by Mikachu2333** [comment]
新规则用了以后连文章也不翻译了……重新试了试旧规则，旧规则仍然能正常翻译文章

另，请注意邮箱内容，收到说声

**Comment by versun** [comment]
@Mikachu2333 
由于我们这边没法测试, 所以建议您使用旧规则, 然后标题使用"鼠标悬停" 翻译, 这样应该能暂时解决你的问题
