### ISSUE TITLE
希望阅读PDF文件添加高亮模式

### ISSUE THREAD

**Issue by newcoder321546** [immersive-translate/immersive-translate#742]
### 您希望的更新和改进是什么 | Update or Improve

由于AI大热有很多阅读论文需求，论文常以PDF文件形式呈现，使用插件进行双语阅读时候希望边读边高亮标记重点，因为PDF翻译有字符重合问题，当把字符拖拽好后生成PDF再高亮还得再读一次论文效率不高。

**Comment by keyboard3** [comment]
AI 论文推荐 pdf-pro, 对表格和公式支持友好 https://app.immersivetranslate.com/pdf-pro
