### ISSUE TITLE
[Bug]: 还是存在渲染html代码的情况，可能导致xss攻击

### ISSUE THREAD

**Issue by heheda123123** [immersive-translate/immersive-translate#744]
### 插件版本号 | Version

0.7.12

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

之前提过一个issue https://github.com/immersive-translate/immersive-translate/issues/442
现在发现仍然存在这个问题
![image](https://github.com/immersive-translate/immersive-translate/assets/97490782/78f9e089-13a1-4a0d-939d-74beab7e0b7a)
比较担心的问题是可能存在xss，随着用沉浸式翻译用的人越来越多，可能会有人针对性制造这种攻击。
只要在pdf里包含比如script标签，可能能直接执行js代码，而chrome里面，可能会继承插件的权限，最终导致攻击者获得比较高的权限。（这里只是拿script标签举例，只过滤script不行，a标签通过javascript伪协议一样可以）
最好不要渲染pdf里的html代码，对他们进行html实体编码

**Comment by keyboard3** [comment]
不用担心，正常渲染标签而已，所有内容都经过DOMPurify.sanitize处理，消除了安全隐患

**Comment by keyboard3** [comment]
扩展内部页面不允许执行js代码，它有内容安全策略的

**Comment by keyboard3** [comment]
后面pdf工具会在线化并开源。可以直接贡献代码
