### ISSUE TITLE
希望加入弹出窗口翻译剪贴板的功能

### ISSUE THREAD

**Issue by bio-er** [immersive-translate/immersive-translate#746]
### 您希望的更新和改进是什么 | Update or Improve

希望能够做一个独立窗口，增加快捷键直接翻译剪贴板上的内容，方便跨软件翻译。（类似沙拉查词）

### 补充说明 | Additional context

沙拉查词半死不活，希望这个插件能吸收下它的功能。

**Comment by oeieo** [comment]
+1

**Comment by StarDuster** [comment]
这个需求我听着感觉更像 [copytranslator ](https://copytranslator.github.io/) 的功能？

**Comment by bio-er** [comment]
> 这个需求我听着感觉更像 [copytranslator ](https://copytranslator.github.io/) 的功能？如果场景都来到了跨软件的话，有点脱离设计初衷了

CT好像没有弹出独立窗口的功能，而且不精致，基本不咋用，一直在用沙拉。

**Comment by lakevilladom** [comment]
+1，
真心希望加入类似功能，比如有如下场景：在vs code等其他软件中看到源码英文注释，需要翻译，这时候就得或者安装悬浮翻译插件，或者浏览器百度等翻译，或者用本软件输入框增强翻译，但是输入框比较小，不直观，操作好几步，所以希望增加弹出窗口翻译：1、一个快捷键(比如alt+n)，2粘贴剪贴板内容，3、自动翻译，完成

**Comment by theowenyoung** [comment]
目前沉浸式翻译的主要目标是保持简单易用，这个功能应该不会被添加。

系统级别的翻译建议还是使用其他native级别的软件解决。
