### ISSUE TITLE
PDF翻译保存后译文无法复制和编辑

### ISSUE THREAD

**Issue by YanqingyuM** [immersive-translate/immersive-translate#747]
### 您希望的更新和改进是什么 | Update or Improve

按照我的理解，现在PDF文件翻译完下载后，译文部分是以图片的形式插入到PDF中的。
因此，现在有两个问题：
1：译文部分不可复制；
2：当阅读中发现译文不正确时，无法对这部分内容进行修改。

### 补充说明 | Additional context

希望能增加一个保存为可编辑的文件格式或以其他方式解决上述问题，谢谢！

**Comment by keyboard3** [comment]
你可以在保存之前编辑内容啊

**Comment by mafeifei666666** [comment]
> 你可以在保存之前编辑内容啊

我还是希望能有一个能编辑的文件保存格式，谢谢！
