### ISSUE TITLE
[Bug]: 在Edge浏览器的新标签页的地址栏和搜索框都无法触发“连续按空格”自动翻译

### ISSUE THREAD

**Issue by bulabulalaen** [immersive-translate/immersive-translate#749]
### 插件版本号 | Version

0.7.12

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/53595830/96b178fd-7075-4ccd-950d-7a5dce1732b5)
![image](https://github.com/immersive-translate/immersive-translate/assets/53595830/69d8df4b-0bd7-447e-ab30-ec051eb36062)
如图所示。

**Comment by FattySpring** [comment]
新标签页和地址栏不支持
https://immersivetranslate.com/docs/input/#%E5%85%BC%E5%AE%B9%E6%80%A7
