### ISSUE TITLE
qutebrowser 浏览器能否支持下，游猴脚本运行后，翻译不了英文

### ISSUE THREAD

**Issue by winq2008** [immersive-translate/immersive-translate#75]
qutebrowser 浏览器能否支持下，游猴脚本运行后，翻译不了英文
qutebrowser  站点:https://www.qutebrowser.org/

**Comment by theowenyoung** [comment]
好的，我研究一下，请问这个浏览器的油猴脚本使用什么插件呢？

**Comment by winq2008** [comment]
> 好的，我研究一下，请问这个浏览器的油猴脚本使用什么插件呢？

它是将油猴脚本 放到指定的浏览器配置目录下
 ~/.config/qutebrowser/greasemonkey/
然后运后以下命令载入脚本
:greasemonkey-reload

以下参是官方文档参考：https://www.qutebrowser.org/doc/faq.html
How do I make qutebrowser use greasemonkey scripts?

There is currently no UI elements to handle managing greasemonkey scripts. All management of what scripts are installed or disabled is done in the filesystem by you. qutebrowser reads all files that have an extension of .js from the <data>/greasemonkey/ folder and attempts to load them. Where <data> is the qutebrowser data directory shown in the Paths section of the page displayed by :version. If you want to disable a script just rename it, for example, to have .disabled on the end, after the .js extension. To reload scripts from that directory run the command :greasemonkey-reload.

Troubleshooting: to check that your script is being loaded when :greasemonkey-reload runs you can start qutebrowser with the arguments --debug --logfilter greasemonkey,js and check the messages on the program’s standard output for errors parsing or loading your script. You may also see javascript errors if your script is expecting an environment that we fail to provide.

Note that there are some missing features which you may run into:

Some scripts expect GM_xmlhttpRequest to ignore Cross Origin Resource Sharing restrictions, this is currently not supported, so scripts making requests to third party sites will often fail to function correctly.

**Comment by theowenyoung** [comment]
抱歉，很晚才回复，刚又重新调试了下，

尝试启动的时候带上debug参数： `qutebrowser --debug --logfilter greasemonkey,js`

但是似乎没有什么有用的信息. 另外，看到：

Some scripts expect GM_xmlhttpRequest to ignore Cross Origin Resource Sharing restrictions, this is currently not supported, so scripts making requests to third party sites will often fail to function correctly.

这个可能说明对于油猴脚本，他不允许跨域请求？ 那么可能我们的翻译服务也无法使用。

**Comment by lost22git** [comment]
+1 很喜欢这个插件和qutebrowser 但似乎鱼与熊掌不可兼得 🤔

**Comment by lost22git** [comment]
通过调用本地命令来发起http请求，来避免跨域请求不知道可不可行🤔
https://qutebrowser.org/doc/help/commands.html#spawn

**Comment by kqvanity** [comment]
@lost22git 
Did you find a solution to it? currently, the pop doesn't show up at all, nor does `Alt-a` work. Can't even see logs in the dev console
