### ISSUE TITLE
局部区域沉浸式阅读

### ISSUE THREAD

**Issue by Wongony** [immersive-translate/immersive-translate#751]
### 您希望的更新和改进是什么 | Update or Improve

希望能在针对选中的部分区域文本进行沉浸式阅读，可能只是对文章的部分段落需要详细地精读，大部分区域简略的浏览也能看懂大概意思，不需要每一段都对照翻译，这样能减少一部分自身能理解的内容的翻译请求。

**Comment by Vstory** [comment]
选择区域时，类似 AdGuard 等广告拦截器选择元素那样，可视化选择。
可以针对特定域名，设置需要翻译的区域，以便实现区域性翻译。

**Comment by zgayjjf** [comment]
此乃刚需，不然 github 上一堆 commit 记录还有非常短的内容都被翻译了。

**Comment by Wongony** [comment]
类似划词翻译，以段落为翻译单元，译文显示在对应选中段落的下方。

**Comment by theowenyoung** [comment]
目前沉浸式翻译的主要目标是保持简单易用，所以应该没有计划添加该功能。

建议该需求直接使用【鼠标悬停】即翻译来实现。

<img width="292" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/8b6e328b-b3a5-4366-920f-01c011bc2377">
