### ISSUE TITLE
[Bug]: firefox浏览器找不到悬停翻译选项

### ISSUE THREAD

**Issue by WIZeaz** [immersive-translate/immersive-translate#754]
### 插件版本号 | Version

0.7.9

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

firefox浏览器中，右键插件的菜单中找不到开启悬停翻译的选项。在设置页也没看见相关内容。
![bug-picture](https://github.com/immersive-translate/immersive-translate/assets/34786011/84c5c63f-0fc9-4277-aac4-4dfbf221c992)

**Comment by theowenyoung** [comment]
点击浏览器沉浸式翻译图标的左键，或者直接在网页上【右键】
