### ISSUE TITLE
[Bug]: errors and missing chapters in translated epub

### ISSUE THREAD

**Issue by Emasoft** [immersive-translate/immersive-translate#755]
### 插件版本号 | Version

0.5.5

### 平台 | Platform

iOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

The epub translation feature has bugs.
The following issues are present in the translated epub:
- Missing Chapters
- Missing text
- Error in the order of chapters
- Many errors reported when loading the epub in iBooks app

This zip contains the original language epub (chinese) and the translated epub (english). The translation service was Tencent Smart Translator.

[bug immersive translate epub.zip](https://github.com/immersive-translate/immersive-translate/files/12159406/bug.immersive.translate.epub.zip)

### 重现步骤 | To Reproduce

This zip contains the original language epub (chinese) and the translated epub (english). The translation service was Tencent Smart Translator.
To reproduce just unzip, load the safari browser, activate the userscript extension of immersive translate on any page, then activate the epub creation option with the double language option disabled, then select the file from the iOS files folder and start translate. When 100% is reached, export to iOS files folder.

[bug immersive translate epub.zip](https://github.com/immersive-translate/immersive-translate/files/12159406/bug.immersive.translate.epub.zip)

**Comment by theowenyoung** [comment]
Hello, sorry for the late reply, this is a big epub, so I just tried with our mock translation, and it seems fine.

[85745 (Translated).epub.zip](https://github.com/immersive-translate/immersive-translate/files/13175224/85745.Translated.epub.zip)

I believe something wrong with the transmart translation. Could you try google translate for this?

**Comment by keyboard3** [comment]
Long time no reply, temporarily closed
