### ISSUE TITLE
时间轴翻译优化建议

### ISSUE THREAD

**Issue by Vstory** [immersive-translate/immersive-translate#757]
### 您希望的更新和改进是什么 | Update or Improve

目前的 YouTube 简介的时间轴翻译如图所示。

![image](https://github.com/immersive-translate/immersive-translate/assets/20795557/efcad7c7-798a-4b48-8d77-5fe3f85ef413)
![image](https://github.com/immersive-translate/immersive-translate/assets/20795557/3a344730-e193-4aaa-bae3-1096011dcbc9)

能不能将时间轴的翻译内容放在原时间轴下方。

网页文件：

[(8) ASMR Close Ear Licking (Horizontal, Slow, Aggressive) _ Tangerin - YouTube.zip](https://github.com/immersive-translate/immersive-translate/files/12162484/8.ASMR.Close.Ear.Licking.Horizontal.Slow.Aggressive._.Tangerin.-.YouTube.zip)

### 补充说明 | Additional context

原时间轴：
```
00:05:00 AAAA
00:36:00 BBBB
```

翻译后：
```
00:05:00 AAAA
00:05:00 aaaa
00:36:00 BBBB
00:36:00 bbbb
```

其中 `aaaa`、`bbbb` 均为翻译后的内容。

**Comment by theowenyoung** [comment]
抱歉很晚才回复，目前已经完美支持了Youtube 的双语字幕，在这里开启即可： https://immersivetranslate.com/docs/usage/#youtube-%E5%8F%8C%E8%AF%AD%E5%AD%97%E5%B9%95
