### ISSUE TITLE
[Bug]: 『与 Google Drive 同步』按钮如果在副屏点击，会提示无法授权。

### ISSUE THREAD

**Issue by zj1123581321** [immersive-translate/immersive-translate#759]
### 插件版本号 | Version

0.7.12

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

『与 Google Drive 同步』按钮如果在副屏点击，会提示无法授权。
![image](https://github.com/immersive-translate/immersive-translate/assets/33171229/2a639b92-bd7b-4b51-ab65-bf7e78693d1d)

Console 里输出：
```
Immersive Translate ERROR: import_export Google OAuth error:Error: Invalid value for bounds. Bounds must be at least 50% within visible screen space.
error @ options.js:4211
```
看上去是获取授权窗口需要计算当前屏幕边界，而插件只取了主屏边界，所以会调用授权失败？

目前解决的方法也很简单：把配置界面**移动到主窗口完成授权操作**。

### 出现问题的网址 | URL

Config

### 重现步骤 | To Reproduce

![image](https://github.com/immersive-translate/immersive-translate/assets/33171229/ed903d67-3aed-4ddd-8dea-5eb79a6ddd2a)
1. 在账户未进行授权的情况下，将配置界面移动到非主屏窗口(2)
2. 点击『立即与 Google Drive 同步』

**Comment by FattySpring** [comment]
未能复现该问题，若问题依然存在建议【把配置界面移动到主窗口完成授权操作】
