### ISSUE TITLE
翻译插件会导致网页搜索失效

### ISSUE THREAD

**Issue by tangxiaoqi-tangxiao** [immersive-translate/immersive-translate#76]
![截屏2023-02-04 12 13 49](https://user-images.githubusercontent.com/54069236/216748053-03251759-3025-4206-a0d8-088f158c8bba.png)

环境
mac系统版本：13.2
浏览器版本：Microsoft Edge版本 109.0.1518.78 (正式版本) (arm64)
翻译插件版本：V0.2.38

**Comment by tangxiaoqi-tangxiao** [comment]
一直是搜索状态，插件禁用就正常

**Comment by theowenyoung** [comment]
好，我研究下。

你可以暂时设置永不翻译该网页，然后搜索完成后，可以使用快捷键手动再翻译。

**Comment by tangxiaoqi-tangxiao** [comment]
ok

**Comment by theowenyoung** [comment]
最新版本已添加该页面的规则～只翻译描述部分～ 更新一下规则～
