### ISSUE TITLE
如何手动修改缓存？

### ISSUE THREAD

**Issue by zgayjjf** [immersive-translate/immersive-translate#760]
### 您希望的更新和改进是什么 | Update or Improve

希望可以手动修改缓存。

有时候翻译不够精妙或者翻译结果出现问题，需要重新翻译。

目前只能选择清除缓存，但是这样的话，使用 ChatGPT 服务的用户，又要为之前翻译过的内容重新付费了。

所以最好有个手动修改缓存的方法，这样可以单独针对某个不够到位的翻译进行修改。

如下是个典型案例，用 ChatGPT 翻译，“JSON” 一个单词，翻译出来一堆 JSON 的介绍，最好能手动修改缓存。

![image](https://github.com/immersive-translate/immersive-translate/assets/24718872/91d2a74e-c38f-484b-be2a-1aae22f032f4)

**Comment by zgayjjf** [comment]
或者可以允许针对某条原文忽略缓存重新翻译。

**Comment by theowenyoung** [comment]
但是即使重新翻译，同样的原文，大概率返回的原文还是一样？

我们想尽可能保持沉浸式翻译简单一点，所以暂时应该不会支持类似的功能，暂时先关闭了哈～ 未来有更新再重新开启。

**Comment by GuangDai** [comment]
返回的原文会变化，

![image](https://github.com/immersive-translate/immersive-translate/assets/59678726/d7dfde4e-eece-45f6-bffa-b90de96b1bfd)

![image](https://github.com/immersive-translate/immersive-translate/assets/59678726/d3ec3edd-81bc-4ca2-91d2-648b609b4b70)

可以看到第二个的翻译大错特错，此时不修改才会更破坏沉浸感，因此希望能有个快捷键做到“删除缓存-重新翻译”

**Comment by zgayjjf** [comment]
> 但是即使重新翻译，同样的原文，大概率返回的原文还是一样？
> 
> 我们想尽可能保持沉浸式翻译简单一点，所以暂时应该不会支持类似的功能，暂时先关闭了哈～ 未来有更新再重新开启。

也不是，因为使用 OpenAI 的话，我们会调整 prmpot，可以优化翻译的译文。

可以把缓存那边细化一下，删除某些特定的缓存。作为一个子功能，不影响核心业务逻辑。

**Comment by theowenyoung** [comment]
> > 但是即使重新翻译，同样的原文，大概率返回的原文还是一样？
> > 我们想尽可能保持沉浸式翻译简单一点，所以暂时应该不会支持类似的功能，暂时先关闭了哈～ 未来有更新再重新开启。
> 
> 也不是，因为使用 OpenAI 的话，我们会调整 prmpot，可以优化翻译的译文。
> 
> 可以把缓存那边细化一下，删除某些特定的缓存。作为一个子功能，不影响核心业务逻辑。

对于 openai 的缓存问题，我们在0.12.13 版本已经优化： https://immersivetranslate.com/docs/CHANGELOG/#01213

改变 模型，prompt 等，缓存会立即失效。

**Comment by zgayjjf** [comment]
> > > 但是即使重新翻译，同样的原文，大概率返回的原文还是一样？
> > > 我们想尽可能保持沉浸式翻译简单一点，所以暂时应该不会支持类似的功能，暂时先关闭了哈～ 未来有更新再重新开启。
> > 
> > 
> > 也不是，因为使用 OpenAI 的话，我们会调整 prmpot，可以优化翻译的译文。
> > 可以把缓存那边细化一下，删除某些特定的缓存。作为一个子功能，不影响核心业务逻辑。
> 
> 对于 openai 的缓存问题，我们在0.12.13 版本已经优化： https://immersivetranslate.com/docs/CHANGELOG/#01213
> 
> 改变 模型，prompt 等，缓存会立即失效。

优秀！
