### ISSUE TITLE
[Bug]: Mac 端 Safari 无法设置快捷键

### ISSUE THREAD

**Issue by CMD-cmd** [immersive-translate/immersive-translate#761]
### 插件版本号 | Version

0.7.12 (Mac AppStore)

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

<img width="1374" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/79133756/7c9e1b87-667f-4f29-9fd8-4b01e90437d3">

**Comment by theowenyoung** [comment]
点击 浏览器 图标，再进入在线版的 设置 ，应该是可以设快捷键的：

<img width="653" alt="图片" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/4da13be3-56b9-4248-8826-55bc8ebf7455">

**Comment by CMD-cmd** [comment]
喔喔喔可以啦，我之前是从 safari 的设置-扩展-沉浸式翻译里点的设置，发现不行🤣
