### ISSUE TITLE
关于gpt翻译，可以增加一个自定义的openai.api_base填写

### ISSUE THREAD

**Issue by yunshaochu** [immersive-translate/immersive-translate#762]
### 您希望的更新和改进是什么 | Update or Improve

因为市面上有不少api的host不是官方的，所以建议开放host，让使用者自己填写。
例如常见的奇美拉、潘多拉等等api，都有自己的host：
openai.api_key = "your_key"
openai.api_base = "https://chimeragpt.adventblocks.cc/v1"

**Comment by theowenyoung** [comment]
这是已有功能哈，在设置页面，openai，【展开更多自定义设置】
