### ISSUE TITLE
翻译速度问题

### ISSUE THREAD

**Issue by liesauer** [immersive-translate/immersive-translate#764]
### 插件版本号 | Version

0.7.12

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/8676741/afdf31f8-de91-4841-9445-5c59af5643d8)

表格中其实是包含大量重复内容的，但是翻译还是非常慢，貌似还是一个个翻译，没有走缓存

### 出现问题的网址 | URL

https://developer.twitter.com/en/docs/twitter-api/rate-limits

### 补充说明 | Additional context

用的是微软翻译

**Comment by keyboard3** [comment]
你可以翻译完成之后，断网再试下翻译

**Comment by liesauer** [comment]
经测试缓存是有效果的，就是翻译的比较慢，提到的那个网页差不多10秒钟翻译完。

**Comment by keyboard3** [comment]
我这边挺快的啊，就2-3秒左右，微软比谷歌稍慢，但也不会这么久。 如果觉得比较慢，可以选择鼠标悬停翻译，这样就很实时
