### ISSUE TITLE
输入框增强快速点击速度控制

### ISSUE THREAD

**Issue by cjahv** [immersive-translate/immersive-translate#765]
### 您希望的更新和改进是什么 | Update or Improve

有些时候会远程其他电脑，快速点击的时间间隔太短很难触发

### 补充说明 | Additional context

希望可以设置快速点击的每次点击间隔，比如像macos的键盘按键重复速率的设置

**Comment by theowenyoung** [comment]
暂时可以在【开发者设置】里面，编辑用户设置：

```json
{  
"inputTrailingTriggerKeyTimeout": 200
}
```

**Comment by cjahv** [comment]
有用
<img width="555" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/15372793/c5aad948-bf17-4ae3-a8ce-20e3f1006ea6">
