### ISSUE TITLE
翻译本地PDF时，译文显示不全或错位

### ISSUE THREAD

**Issue by Awyugan** [immersive-translate/immersive-translate#768]
### 您希望的更新和改进是什么 | Update or Improve

希望可以显示完全

### 补充说明 | Additional context

如截图所示
![截屏_2023-07-27 17 27 21](https://github.com/immersive-translate/immersive-translate/assets/63247559/6d071b5a-27bc-4434-9a32-62a3379b4bae)

**Comment by theowenyoung** [comment]
有没有试过右下角拖动～

**Comment by Awyugan** [comment]
右下角拖动确实可以解决，但大量重复工作还是要从插件本身入手

**Comment by theowenyoung** [comment]
(逃 我们就是发现插件也很难解决这个问题.. 所以加了这个拖动的功能. 逃

不过还是有优化的空间，继续努力看下！

**Comment by Awyugan** [comment]
加油哇，这个问题影响也不是很大，一般都是在线阅读。不知道相关的导出问题是否也会有影响，那些问题我搜了，没细看。
