### ISSUE TITLE
这个网站有些漏掉的翻译

### ISSUE THREAD

**Issue by HaveF** [immersive-translate/immersive-translate#77]
https://ourworldindata.org/consumption-based-co2

1. 点完下箭头之后
![image](https://user-images.githubusercontent.com/54462/216762508-5298c9f6-df08-44d2-930a-b14bf4c87606.png)

2. 最下面的部分
![image](https://user-images.githubusercontent.com/54462/216762566-b25bad8a-1c11-4567-a5e0-3dda33770415.png)

**Comment by theowenyoung** [comment]
箭头里面的内容，我这正常：

<img width="1618" alt="Screenshot 2023-02-05 at 01 12 27" src="https://user-images.githubusercontent.com/62473795/216780424-21eae685-0235-484f-a10f-e87a2229e5f1.png">


那个 下面没翻译的部分位于 footer 里面，默认不翻译footer里面的东西。

**Comment by HaveF** [comment]
箭头那我这看又好了 = =;
