### ISSUE TITLE
MAC AppStore下架啦？？？

### ISSUE THREAD

**Issue by Jagerx** [immersive-translate/immersive-translate#772]
### 您希望的更新和改进是什么 | Update or Improve

<img width="640" alt="2023-07-28_12-50-04" src="https://github.com/immersive-translate/immersive-translate/assets/42521386/1048b9d8-3a59-4828-8b61-99e3a63de764">

**Comment by keyboard3** [comment]
是的 正在积极和苹果沟通  https://immersivetranslate.com/docs/faq/#%E8%8B%B9%E6%9E%9C%E5%95%86%E5%BA%97%E6%97%A0%E6%B3%95%E4%B8%8B%E8%BD%BD

**Comment by theowenyoung** [comment]
![IMAGE 2023-07-28 15:13:46](https://github.com/immersive-translate/immersive-translate/assets/62473795/f5565897-d186-4a95-8493-c2ca3bae9200)

**Comment by Jagerx** [comment]
我从美区App Store下载了

**Comment by Jagerx** [comment]
<img width="770" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/42521386/62c6a592-e4b8-458f-a618-5af5c3235e6c">
Longman，顶尖英文辞典，可能也是彻底被删了，不知道是否都是相关政策原因

**Comment by happykkAi** [comment]
今天搜不到沉浸式翻译 是不是沉浸式太好用，被人搞事了。

**Comment by keyboard3** [comment]
已经重新上架了国区了
