### ISSUE TITLE
[Bug]: 圖片會重複

### ISSUE THREAD

**Issue by KamiyaMinoru** [immersive-translate/immersive-translate#776]
### 插件版本号 | Version

0.55

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

文章中的圖片會被複製
![image](https://github.com/immersive-translate/immersive-translate/assets/78710607/d6efd195-81b0-4c5b-9361-295c3000120f)

### 出现问题的网址 | URL

https://nypost.com/2023/07/28/facebook-removed-covid-19-posts-under-white-house-pressure-report/

### 重现步骤 | To Reproduce

1. 按右鍵 翻譯
2. 出現錯誤

### 补充说明 | Additional context

無

**Comment by keyboard3** [comment]
更新版本 最新版0.7.15 没有该问题

**Comment by KamiyaMinoru** [comment]
我在edge只看到0.714的
![image](https://github.com/immersive-translate/immersive-translate/assets/78710607/05bebdc9-8247-4489-855e-00a5ea88c7b5)

**Comment by keyboard3** [comment]
> 我在edge只看到0.714的 ![image](https://user-images.githubusercontent.com/78710607/256960736-05bebdc9-8247-4489-855e-00a5ea88c7b5.png)

这个版本也可以的

**Comment by KamiyaMinoru** [comment]
如圖:
![image](https://github.com/immersive-translate/immersive-translate/assets/78710607/151413c6-528e-4f3c-9314-280588c57d9e)
