### ISSUE TITLE
[Bug]:  Android 下无法使用本地电子书翻译 

### ISSUE THREAD

**Issue by TypeHkt** [immersive-translate/immersive-translate#777]
### 插件版本号 | Version

0.7.15  &  0.7.9

### 平台 | Platform

Android

### 浏览器 | Browsers

Firefox, Other

### 插件类型 | Extension Type

浏览器插件 | Browser Extension, 油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

android下，无法使用”阅读本地电子书“、”Epub电子书“、”翻译PDF文件“功能
点击按钮后，我们启动功能页面，但选择电子书后，没有任何反应

硬件：小米平板5（非Pro） 
认证型号：21051182C
硬件版本：V1
安卓版本：11
MIUI： 12.5.13稳定版

使用浏览器&插件版本
Firefox Nightly  110.0a1   +   篡改猴  + 沉浸式翻译  0.7.15
猴狐浏览器 2.4.1.001 + 沉浸式翻译  0.7.14
沉浸式翻译浏览器   + 沉浸式翻译  0.7.9

### 出现问题的网址 | URL

本地

### 重现步骤 | To Reproduce

1.点击”更多“
2.点击”翻译本地PDF文件“ 或 ”阅读本地电子书“ 或 “制作双语Epub电子书”
3.上传电子书
4.没有任何反应，电子书没有打开

**Comment by keyboard3** [comment]
firefox不行。狐猴和wiki都可以呀，我测试过

**Comment by ripley** [comment]
我在文石电子书上安装官方的浏览器，也有这个问题，能打开电子书但是看不到内容。

**Comment by theowenyoung** [comment]
刚在安卓Firefox，Tampermonkey，最新版的沉浸式翻译插件测试，此问题已经被修复了？暂时先关闭了，有问题再开。

![img_v2_960604df-ce7e-4273-b1e0-a934c74ac58g](https://github.com/immersive-translate/immersive-translate/assets/62473795/d8eb538d-a301-4545-bd21-204af76a854f)


![img_v2_15954bdd-5424-4361-a800-db9cd13e946g](https://github.com/immersive-translate/immersive-translate/assets/62473795/388e8cad-72ba-4f34-859b-92cafa927c08)


![img_v2_5f195973-b113-4abb-810a-df87ce5ec2ag](https://github.com/immersive-translate/immersive-translate/assets/62473795/ec85e3e2-c053-4686-bbbc-e1a425f4c2f4)
