### ISSUE TITLE
[Bug]: 自訂色彩無效

### ISSUE THREAD

**Issue by KamiyaMinoru** [immersive-translate/immersive-translate#778]
### 插件版本号 | Version

0.714

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/78710607/5be2ace8-3a5a-410c-84f2-d1cedf40ceee)

**Comment by Vstory** [comment]
色彩变更，需要刷新页面，才能生效。

**Comment by KamiyaMinoru** [comment]
我甚至開了其他頁面 但結果如您所見(附帶一提 我也把Dark Reader關掉過, 所以應該是CSS的問題)
![image](https://github.com/immersive-translate/immersive-translate/assets/78710607/36b96599-ccf4-4ecf-ad74-0b1b228fbf38)

**Comment by KamiyaMinoru** [comment]
看起來問題是「只有特定的顏色」會生效，其餘的選擇是無效的

**Comment by theowenyoung** [comment]
特定的颜色？ 我这里测试是支持全部颜色的。

有没有可能是你的其他扩展影响了？你可以在隐私窗口使用沉浸式翻译来确定是否是沉浸式翻译的问题。

<img width="721" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/361b2ab6-a130-4f00-a9ff-24182fcf3294">

<img width="632" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/af457231-781f-4d43-b42a-3d6f1a4ace68">

**Comment by KamiyaMinoru** [comment]
隱私模式? 在這模式下似乎是沒有沈浸式翻譯的

![image](https://github.com/immersive-translate/immersive-translate/assets/78710607/0fc26c52-110f-419c-a7bc-eaba555fb34d)

**Comment by KamiyaMinoru** [comment]
附帶一提 我剛剛發現這問題解決了 感謝

**Comment by theowenyoung** [comment]
> 隱私模式? 在這模式下似乎是沒有沈浸式翻譯的
> 
> ![image](https://user-images.githubusercontent.com/78710607/278308809-0fc26c52-110f-419c-a7bc-eaba555fb34d.png)

需要在浏览器的 插件管理里，允许 沉浸式翻译 在隐私模式下运行。
