### ISSUE TITLE
[Bug]: 開啟後 github 右上方那三個按鈕(lssues, Pull requests, msg notifications) 的mouse 通知氣泡會消失

### ISSUE THREAD

**Issue by ufft47** [immersive-translate/immersive-translate#779]
### 插件版本号 | Version

0.7.14

### 平台 | Platform

Windows

### 浏览器 | Browsers

Other

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

 開啟後 github 右上方那三個按鈕(lssues, Pull requests, msg notifications) 的mouse 通知氣泡會消失，
油猴的 Github 中文化插件則不會有這問題，
我用的是 brave， chrome系的

### 出现问题的网址 | URL

https://github.com/

**Comment by ufft47** [comment]
而且關閉後這問題會一直存在，直到重新F5

**Comment by theowenyoung** [comment]
抱歉，回复的太晚了。请问现在最新版还有问题吗？我这里测试是正常的：

<img width="1347" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/5c33c3c7-067e-49b4-b94b-8baad05f7ae2">

**Comment by keyboard3** [comment]
暂无反馈关闭此问题
