### ISSUE TITLE
翻译效果有点小问题

### ISSUE THREAD

**Issue by 2686259124** [immersive-translate/immersive-translate#78]
![image](https://user-images.githubusercontent.com/63957367/216814935-6d3d9d04-6c9a-4ba2-b616-30b2ce72ecf6.png)
翻译结果里面的下标全部都不见了，希望能调整下。

**Comment by theowenyoung** [comment]
可以发一下这个的网址吗？

**Comment by 2686259124** [comment]
我这是一篇论文，直接在熊猫学术里面（https://sc.panda321.com/）搜索这个标题就可以了（Metal peroxides for cancer treatment）。而且也不只是这篇文章，其他文章也是一样的。

**Comment by theowenyoung** [comment]
好的，谢谢反馈，我更新了规则，已修复。 （左键点击浏览器扩展图标，即可同步最新规则）

**Comment by 2686259124** [comment]
感谢，生效了，但是下标前面似乎有一个空格，这个可以删除掉吗，要不看着确实不太舒服...
![image](https://user-images.githubusercontent.com/63957367/216882395-cc386a63-05a8-4185-9d79-00cde298bdd6.png)

**Comment by theowenyoung** [comment]
有道理。

但是这个可能要在下个版本优化了，要改下代码～

**Comment by 2686259124** [comment]
好的好的，十分感谢！！！

**Comment by 2686259124** [comment]
还好，作者可不可以加一个译文可以编辑的功能呀，想要一个

**Comment by theowenyoung** [comment]
我记一下，你是想修改之后，然后保存网页是吗？

**Comment by 2686259124** [comment]
嗯嗯是的

**Comment by theowenyoung** [comment]
译文修改暂时还没有考虑做，这个issue的主要问题已经修复了，先关了。
