### ISSUE TITLE
[Bug]: 亚马逊作者页面的书名无法被翻译

### ISSUE THREAD

**Issue by Andy-AO** [immersive-translate/immersive-translate#781]
### 插件版本号 | Version

0.7.9

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![图片](https://github.com/immersive-translate/immersive-translate/assets/38101170/b5f5e2d9-9427-4b16-a7a5-acbd0a41cd39)

### 出现问题的网址 | URL

https://www.amazon.com/stores/author/B001IOFHPK/allbooks?store_ref=ap_rdr&ref_=ap_rdr

**Comment by keyboard3** [comment]
这个是亚马逊网站自己做了保护，任何翻译插件翻译完之后，都会触发它的检测修正机制，我们的是翻译完了，但是被亚马逊给修正回来了。其他的翻译插件会直接触发这个网站无法正常加载图书
