### ISSUE TITLE
能否在电脑版也使用悬浮球？

### ISSUE THREAD

**Issue by FEI352** [immersive-translate/immersive-translate#782]
### 您希望的更新和改进是什么 | Update or Improve

kiwi浏览器在使用沉浸式翻译的时候，右边回出现一个悬浮球，但是我选择“桌面版网站”这个悬浮球就消失了，Kiwi用不了Alt+A，希望选择“桌面版网站”的时候也有悬浮球；另外在surface等触控设备上有个悬浮球也是非常不错的。

### 补充说明 | Additional context

我希望有一个悬浮球的启用开关，UA显示桌面版网站的时候也能用悬浮球。

**Comment by Vstory** [comment]
显示。
只是太相对于屏幕而言，太小了

**Comment by FEI352** [comment]
Kiwi 是显示的沉浸式翻译的小按钮－－－但只有在手机界面的时候才有。我选“桌面版网站”就不会实现。

你能告诉我你是怎么做到的吗？我现在用的是0.7.14版本，需要更新吗？

另外相对于11寸的安卓平板，surface 这个小按钮是够用的。1213寸的surface我没试过，但应该也会有不错的体验。（四指触控其实也不错，但还是喜欢小按钮）

发现开发者之前回答过相关的问题，不知道有没有实现的计划。

**Comment by theowenyoung** [comment]
Hello，更新一下这个问题的进展， 下周的新版本，我们将支持所有设备启用悬浮球。

并且悬浮球的默认操作是【翻译/还原】，而不是目前的打开面板。

**Comment by FattySpring** [comment]
0.10.8 已支持，可以在设置页面开启
