### ISSUE TITLE
新增字体自定义

### ISSUE THREAD

**Issue by jihongboo** [immersive-translate/immersive-translate#784]
### 您希望的更新和改进是什么 | Update or Improve

希望可以自定义翻译字体。
当前翻译使用的字体是根据当前网页的字体选择的，但是大量英文/外文字体匹配到的中文字体不是很适合阅读（宋体）。
建议可以自定义配置字体，然后给不同系统配置默认字体。比如Mac使用苹方，Windows使用微软雅黑。

**Comment by forestsheep911** [comment]
不能同意更多，但官方如果不提供的话，我已经想通过油猴脚本去实现个人的需求了。

**Comment by theowenyoung** [comment]
和 #217 相关。

不确定是否应该影响原网站的默认配置。

目前来看 mac上的fallback 字体其实还挺美观的...

**Comment by theowenyoung** [comment]
统一迁移到 #1158 讨论吧～
