### ISSUE TITLE
[Bug]: zotero官网翻译显示有问题的反馈

### ISSUE THREAD

**Issue by RTcui** [immersive-translate/immersive-translate#785]
### 插件版本号 | Version

0.7.14

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

zotero网站论坛，有些页面翻译可以，但后续很多页面翻译有问题。

![image](https://github.com/immersive-translate/immersive-translate/assets/103620369/ddec1cc8-f2a6-44de-9707-d78281818b3d)

### 出现问题的网址 | URL

https://forums.zotero.org/discussion/106541/the-setting-bar-about-plugins-in-zotero-settings-disappears-for-no-reason

### 重现步骤 | To Reproduce

直接翻译就这样了

**Comment by keyboard3** [comment]
已适配，刷新下
