### ISSUE TITLE
进入（纵向）长英文文本网站会非常卡顿

### ISSUE THREAD

**Issue by xxxcys** [immersive-translate/immersive-translate#786]
### 您希望的更新和改进是什么 | Update or Improve

例如这个网站:http://ip.bczs.net/country_as/GB
尽管如果不使用该插件进入这种类型的网站也有可能会稍微卡顿，但是过一会就好了，开了插件之后直接卡死。
（“是否翻译网页所有区域"此选项未开启）

**Comment by keyboard3** [comment]
我chrome试了还好，没出现你说的卡顿的情况出现。你试着等到网站完全加载完之后触发翻译看看？

**Comment by xxxcys** [comment]
等到网站完全加载完之后触发翻译依旧会卡顿   只不过没之前那么严重(直接卡Edge未响应了)

**Comment by maxxie6418** [comment]
我也在edge遇到了，但是在公司的电脑上翻译同一个页面就没有问题。同一个版本同一个页面但是问题没有重复出现

**Comment by WangJincheng4869** [comment]
EDGE 就是会卡，已经关闭了自动翻译，使用快捷键翻译当前行，但依旧卡顿 https://github.com/intlify/vue-i18n-next/blob/master/CHANGELOG.md

**Comment by WangJincheng4869** [comment]
> EDGE 就是会卡，已经关闭了自动翻译，使用快捷键翻译当前行，但依旧卡顿 https://github.com/intlify/vue-i18n-next/blob/master/CHANGELOG.md

经过了一些测试，发现可能是 chrome 的 bug，在火狐中并不卡，我尝试禁用 Edge 和 Google chrome 的全部插件，打开这个网页依旧卡顿，而火狐并不会。
