### ISSUE TITLE
建议对接一下facebook的NLLB，就可以实现完全的自主托管,[Bug]: 

### ISSUE THREAD

**Issue by smilesmallbird** [immersive-translate/immersive-translate#787]
### 插件版本号 | Version

0.5.5

### 平台 | Platform

macOS

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

NLLB-server:[https://github.com/thammegowda/nllb-serve ]( https://github.com/thammegowda/nllb-serve )

### 出现问题的网址 | URL

https://github.com/thammegowda/nllb-serve

**Comment by theowenyoung** [comment]
目前可以使用我们的自定义接口功能 接入任何自托管的翻译服务哈：

文档见： https://immersivetranslate.com/docs/services/custom/

**Comment by weituotian** [comment]
好~(￣▽￣)~*
