### ISSUE TITLE
[Bug]: bing翻譯失效

### ISSUE THREAD

**Issue by KamiyaMinoru** [immersive-translate/immersive-translate#788]
### 插件版本号 | Version

0.714

### 平台 | Platform

Android

### 浏览器 | Browsers

Other

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

kiwi
突然發現不能用bing翻譯了(改回google則正常)
![image](https://github.com/immersive-translate/immersive-translate/assets/78710607/056b052d-f375-4d4e-9d5e-d41f1cabf59f)

### 出现问题的网址 | URL

所有網站

**Comment by keyboard3** [comment]
这个是本地网络问题，直连服务的
