### ISSUE TITLE
能否支持对 canvas 中绘制的文本进行翻译？

### ISSUE THREAD

**Issue by KeyAI** [immersive-translate/immersive-translate#789]
### 您希望的更新和改进是什么 | Update or Improve

有些网站中的文本是通过 canvas 绘制的，是否可以支持从 canvas 中提取文字并翻译？

### 补充说明 | Additional context

从 canvas 提取文字的实现可以使用 [getImageData](https://developer.mozilla.org/zh-CN/docs/Web/API/CanvasRenderingContext2D/getImageData) 结合 String.fromCharCode。

使用 canvas 绘制文本的网站示例：
 https://sites.google.com/a/chromium.org/dev/developers/fast-intro-to-git-internals

**Comment by keyboard3** [comment]
即使可以提取，但是也没地方显示译文。 暂时不会支持
