### ISSUE TITLE
[Feature Request]: 增加混合设置译文显示样式功能

### ISSUE THREAD

**Issue by aiirobyte** [immersive-translate/immersive-translate#79]
目前的译文显示样式只能设置一种，如下图中的「弱化」样式。

<img width="660" alt="image" src="https://user-images.githubusercontent.com/73283555/216817534-80caaa9b-94b6-429e-9f78-c8f38eaf7d5e.png">

但是我目前的需求是样式不仅仅是「弱化」，还需要「引用样式」，效果如下图所示：

![image](https://user-images.githubusercontent.com/73283555/216818059-47ecb149-713d-418f-b8e8-d516afefdc70.png)

有两个叠加的选项，最终的样式就是两个样式的叠加效果。

**Comment by theowenyoung** [comment]
谢谢建议，这里我正在做一个自定义颜色的设置项，有了这个之后，你可以自定义译文的字体颜色以及引用样式左边这个红色的颜色。
