### ISSUE TITLE
微软 Azure 翻译支持世纪互联

### ISSUE THREAD

**Issue by ceeim** [immersive-translate/immersive-translate#790]
### 您希望的更新和改进是什么 | Update or Improve

目前使用 Azure 翻译不支持世纪互联的 API，希望可以添加支持。
如果 Azure 翻译能支持自定义的终结点（API 地址）就更好了。

### 补充说明 | Additional context

![image](https://github.com/immersive-translate/immersive-translate/assets/18570103/cb986d4e-33d6-460f-b42a-23e4c9b0d576)

**Comment by theowenyoung** [comment]
抱歉 这么晚才回复，该特性将在 0.10.8版本支持：

<img width="989" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/7c1a955e-dfe2-4d28-a12a-da3157333386">

**Comment by ceeim** [comment]
> 抱歉 这么晚才回复，该特性将在 0.10.8版本支持：
> 
> <img alt="image" width="989" src="https://user-images.githubusercontent.com/62473795/278316985-7c1a955e-dfe2-4d28-a12a-da3157333386.png">

感谢支持，建议更新一下教程文档。
