### ISSUE TITLE
Request of complete source code of free versions and clarification on license change

### ISSUE THREAD

**Issue by GeeLaw** [immersive-translate/immersive-translate#794]
### 您希望的更新和改进是什么 | Update or Improve

According to [the history of `LICENSE`](https://github.com/immersive-translate/immersive-translate/commits/main/LICENSE), all versions of this software prior to commit `af489aa72289ba7159f35fd807f38fca20719392` are licensed under AGPL 3.0 (since Dec 2022) or MPL 2.0. In #42, in Jan 2023, the repository has accepted a pull request from someone that appears to **not** be Owen Young, Inc. This makes Owen Young, Inc. a licensee of any subsequent versions of this software, thus subject to the restrictions imposed by AGPL 3.0, among which section 6 mandates that you offer the source code.

Since all versions subsequent to the acceptance of #42 are subject to this restriction, and I have acquired those versions by forking this project to my personal account, I hereby request that you provide all the source code for each commit from `da3d54a7ee452eae8ce7c777cf711ec1b98c5d91` to `af489aa72289ba7159f35fd807f38fca20719392`.

Moreover, I would like to request a clarification that the change of license was legal. In commit `af489aa72289ba7159f35fd807f38fca20719392`, the AGPL 3.0 license was changed to a non-free license. Since at that point, the software has multiple copyright holders, such change is legal only if all copyright holders agree to license the software to Owen Young, Inc. under a separate license that does not prohibit releasing their work under a license that is not AGPL 3.0. I suspect whether this is true. If not, all versions of this software are still bound by AGPL 3.0 --- in that case, I would like a copy of the source code for all versions of this software since commit `da3d54a7ee452eae8ce7c777cf711ec1b98c5d91`.

It is preferable that you provide the source code in its originally source-controlled form, i.e., release the Git repository if it has been so managed.

**Comment by aseaday** [comment]
The immersive-translate/immersive-translate repo is a source code for publishing docs and some artifacts. All its code are still open source to everybody.  
This immersive-translate repo license can't influence the immersive-translate plugin's private property even though the dist are compiled from a open source software. For example, the llama models' trained scripts  and datasets are closed even facebookresearch/llama itself seems a special open source license.
BTW I still think immersive-translate could do something balance the bussiness benefits and open source community.

**Comment by aseaday** [comment]
As for the license change, I think EULA is for software itself and AGPL should be for this repo.  So it should be changed back to AGPL if there is no formal approval process among all contributors.

**Comment by GeeLaw** [comment]
The Facebook example fails for multiple reasons.

1. facebookresearch/llama is not open-source.
2. It is likely that Facebook is the sole copyright holder of Llama. Facebook is free to release facebookresearch/llama under any license and is not bound by its terms, and it is free to release other works derived from facebookresearch/llama under any separate license.

The second reason is also why I do not request the source code before the acceptance of #42 --- even though some prior versions are released under AGPL 3.0, the sole copyright holder, Owen Young, Inc., is not bound by those terms --- but this changes with the acceptance of #42.

A correct example supporting my case is as follows: Suppose A publishes B under (A)GPL, and C acquires B (the form of B does not matter; say binary for concreteness). Suppose now C creates D and combines B (binary) with D (binary) to create E (binary). Now, C's usage of E (binary) is subject to GPL, and the source code of E must be released upon request to anyone acquiring E (binary). Translating the example to the current subject of matter:

- A is the author of pull request #42.
- B is the fix of the typo.
- C is Owen Young, Inc.
- D is immersive-translate/immersive-translate before accepting pull request #42.
- E is immersive-translate/immersive-translate after accepting pull request #42.

The argument that "downstream can't affect upstream"

>This immersive-translate repo license can't influence the immersive-translate plugin's private property. Even the dist is compiled from immersive-translate plugin repo, we can't demand that immersive-translate plugin repo should be open. The downstream can't affect upstream.

is invalid and such "infectious" effect between "downstream" and "upstream" is an intention of (A)GPL.

Your notion of "all [this repo's] code"

>The immersive-translate/immersive-translate repo is a source code for publishing docs and some artifacts. All its code are still open source to everybody.

is not the same as (A)GPL, which governs the releasing of source code for the versions I requested and defines it as

>The "source code" for a work means the preferred form of the work for making modifications to it. "Object code" means any non-source form of a work.

Therefore, if

>Even the dist is compiled from immersive-translate plugin repo, we can't demand that immersive-translate plugin repo should be open.

holds, then the source code is not in this repo and supposedly in the private repo.

**Comment by aseaday** [comment]
It seems that https://github.com/immersive-translate/immersive-translate/pull/42 modify the source code which refers to markdown. And the markdown is still open for users with its non-source form of a work https://immersivetranslate.com/.
So Owen Young，Inc holds the rule by AGPL.

**Comment by aseaday** [comment]
The llama also accept the https://github.com/facebookresearch/llama/pull/46. But I will find a more open source like repo to defend my opinions.
There is a argument between your and me that wether the doc/blog should be part of this software.

**Comment by aseaday** [comment]
What part of these repo are limited by the AGPL is the core problem I think.
You put a AGPL license on your repo (which in fact is a blog software to introduce your software) and you also put a binary software from your private repo here.
Should the dynamic library's source code should be open source?

**Comment by aseaday** [comment]
```
How to Apply These Terms to Your New Programs
If you develop a new program, and you want it to be of the greatest possible use to the public, the best way to achieve this is to make it free software which everyone can redistribute and change under these terms.

To do so, attach the following notices to the program. It is safest to attach them to the start of each source file to most effectively state the exclusion of warranty; and each file should have at least the "copyright" line and a pointer to where the full notice is found.

    <one line to give the program's name and a brief idea of what it does.>
    Copyright (C) <year>  <name of author>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
```
I think that is why this problems rise. Owen didn't add these code to any files in this repo. So we can't know what the AGPL and what this repo is for.

**Comment by GeeLaw** [comment]
For AGPL, the work cannot be separated into different files so that AGPL only applies to a portion of it. Again, this is the "infectious" nature of AGPL. According to AGPL,

>"The Program" refers to any copyrightable work licensed under this License. Each licensee is addressed as "you". "Licensees" and "recipients" may be individuals or organizations.
>
>A "covered work" means either the unmodified Program or a work based on the Program.

Software documentation is copyrightable (which one can infer from the necessity of FSF FDL). My common sense tells me that the copyrightable work under this repository is one single work. Therefore, in some commits, the whole repository has been licensed under AGPL.

>The llama also accept the facebookresearch/llama#46.

The license of that pull request is presumed to be the same as the one used in the repository before its acceptance. The license of Llama does not "bind" Facebook to release the software as free software or open-source software. Therefore, a similar argument cannot be made.

>What part of these repo are limited by the AGPL is the core problem I think.
>You put a AGPL license on your repo (which in fact is a blog software to introduce your software) and you also put a binary software from your private repo here.
>Should the private software should be open source?

Thanks for this reminder! I did not realize that this repository is not the translate software itself, but the publishing software for distribution and promotion.

My request of source code is thus invalid. Still, whether the license can be changed is still a valid question.

>I think that is why this problems rise. Owen didn't add these code to any files in this repo. So we can't know what the AGPL and what this repo is for.

This is not the problem. The suggestion to attach the notice to each file is a courtesy to ensure that the licensing notice survives cherry-picking (inclusion of select files but not the whole repository containing the full license), and it in no way affects the licensee's rights granted by the copyright holder(s).

**Comment by aseaday** [comment]
```
This is not the problem. The suggestion to attach the notice to each file is a courtesy to ensure that the licensing notice survives cherry-picking (inclusion of select files but not the whole repository containing the full license), and it in no way affects the licensee's rights granted by the copyright holder(s).
```
Thanks for your understanding,  I think it is important because it cause the confuses for people about what the repos is really for: translate plugin or a doc website for translate plugin.  

I also agree with your request about license modifictations.

**Comment by theowenyoung** [comment]
Hi, thank you both very much for the quality of the discussion, I actually learned a lot about open source that I never knew before.

I would like to clarify that this public repo was created to host the documentation for the extension, and some scripts that were used to generate the documentation site for the extension. You can see the whole process in the project's [Github Actions](https://github.com/immersive-translate/immersive-translate/blob/main/.github/workflows/publish.yml)

Since this public project is just a repo that hosts the project's documentation, the perfect solution would have been for the project not to have any licenses from the beginning to avoid any misunderstandings or ambiguities.

However, due to my lack of precision on this, it looks like the changes to the license file are a bit confusing.

I agree with @GeeLaw  about the repo's license change, in fact, since it's just a documentation repo, I think it could revert back to the AGPL protocol since the entire history of the project has actually always been public. But I'm not sure if that would cause more misunderstandings? 

In order to make the purpose of the project clearer, I've restated the purpose of the project and the fact that the source code is closed source at the top of the README in both [Chinese](https://github.com/immersive-translate/immersive-translate/blob/main/README.md) and [English](https://github.com/immersive-translate/immersive-translate/blob/main/README_english.md). I hope this will help clear up any misunderstandings.

Thanks again for the quality of the discussion.

**Comment by GeeLaw** [comment]
I think a simple

> The documentation and the website builder are open-source and licensed under [whatever your current license is, but likely AGPL]. The translation extension is hosted in this repository for distribution and not governed by [that license].

is sufficient.

**Comment by TechnologyClassroom** [comment]
This move smells fishy.
