### ISSUE TITLE
[Bug]: 长时间在翻译后与翻译前之间变化（较严重）

### ISSUE THREAD

**Issue by noriole** [immersive-translate/immersive-translate#795]
### 插件版本号 | Version

0.7.14

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

如视频所示，在pubmed中浏览较多结果时比较可能会出现该状况

https://github.com/immersive-translate/immersive-translate/assets/62467022/dd350f71-1a18-47e1-a9b8-3a3ddbc1d9ac

### 出现问题的网址 | URL

pubmed.ncbi.nlm.nih.gov

**Comment by keyboard3** [comment]
这是正常行为，因为需要发送请求才能从翻译服务中获取翻译结果。一旦浏览过多，就会同时发送多个请求到翻译服务。翻译服务处理不过来，页面上显示的就是等待状态。这些免费或者收费的翻译服务都是负载上限的。

**Comment by noriole** [comment]
问题是 已经被翻译的部分变回未翻译状态，然后变回翻译状态了，一直重复，这导致浏览体验很差，你可以看到视频中的页面一直在变化（我不知道这个过程中 原来已翻译的部分是否被再次翻译因而导致请求过多）
我使用的其他网页全文翻译的插件不会出现此问题，比如划词翻译 https://hcfy.app

**Comment by keyboard3** [comment]
这个网站已经适配好了。不好意思没看出你视频的往回滚动的区别。最好加上一些文本描述。
