### ISSUE TITLE
[Bug]: 輸入框增強功能無法套用在 Gmail 的主旨與內文上

### ISSUE THREAD

**Issue by ausir0726** [immersive-translate/immersive-translate#801]
### 插件版本号 | Version

0.7.14

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

輸入框增加功能無法使用在撰寫郵件時的主旨與內文

但是搜尋郵件可以使用

![image](https://github.com/immersive-translate/immersive-translate/assets/7247064/e5e97ac7-5c14-4005-9236-6212622125e0)

### 出现问题的网址 | URL

mail.google.com

### 重现步骤 | To Reproduce

1. 前往 mail.google.com
2. 撰寫新郵件
3. 於主旨輸入 測試 連續按三下空白 ( 無反應 )
4. 於內文輸入 測試 連續按三下空白 ( 無反應 )
5. 於郵件搜尋框輸入 測試 連續按三下空白 ( 回應 test )

### 补充说明 | Additional context

無

**Comment by keyboard3** [comment]
gmail輸入框遮罩了輸入事件監聽，不支援哦。 看相容性文檔  https://immersivetranslate.com/docs/input/#%E5%85%BC%E5%AE%B9%E6%80%A7
