### ISSUE TITLE
[Bug]: 漏失翻譯的區域

### ISSUE THREAD

**Issue by KamiyaMinoru** [immersive-translate/immersive-translate#803]
### 插件版本号 | Version

0.714

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

部份區域沒有被翻譯; 只抓到作者資訊
![image](https://github.com/immersive-translate/immersive-translate/assets/78710607/b438f3d8-0f2a-44bd-85bf-028e9c44fb2c)

### 出现问题的网址 | URL

https://www.cnet.com/tech/services-and-software/

**Comment by keyboard3** [comment]
已适配 刷新下就可以了

**Comment by KamiyaMinoru** [comment]
問題仍然存在(但看起來說不定只是沒有辦法顯示, 供參考)
![image](https://github.com/immersive-translate/immersive-translate/assets/78710607/fce63956-a0f1-4153-b1fa-05a74a54b8c3)

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/f0b42c12-2dee-4a1a-b148-eee25ded3e25)
可以的啊，你多刷新几次
