### ISSUE TITLE
[Bug]: PDF翻译区域偏移

### ISSUE THREAD

**Issue by blacknoiseee** [immersive-translate/immersive-translate#805]
### 插件版本号 | Version

0.7.14

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome, Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

无法上传图片……但是翻译出的区域整体向右迁移，以至于一些翻译词语无法显示。

### 出现问题的网址 | URL

chrome-extension://bpoadfkcbjbfhfodiogcnhhhpibjhbnh/pdf/index.html

### 重现步骤 | To Reproduce

translate local pdf file

**Comment by keyboard3** [comment]
这是原始pdf的数据坐标有误，left偏大导致的。可以通过在设置中的开发者配置中设置如下的规则。手动将译文向左移动一定的距离来抵消偏移
`[
  {
    "id": "pdf",
    "injectedCss": ".immersive-translate-text-layer > div {margin-left:-20%!important;}"
  }
]`
