### ISSUE TITLE
为提高专业领域翻译精准度，新增自定义词库功能

### ISSUE THREAD

**Issue by wlvh** [immersive-translate/immersive-translate#806]
### 您希望的更新和改进是什么 | Update or Improve

简要概述：
我建议在"沉浸式翻译"浏览器插件中开发一个"自定义词库"功能（或者你可以根据你的创新思维来给它起一个更合适的名字）。这个功能将允许用户对某些词语强制执行特定的翻译，尤其是在处理专业领域或特定行业的术语时。当前的翻译引擎可能并不总是能符合用户的期望，特别是在处理专业行业术语，缩写词或特定行业术语时。

描述：
这个新功能的目的是通过允许用户为特定的词语或短语定义他们偏好的翻译，来提高翻译的准确性。当标准翻译引擎提供的翻译不能满足用户的需求或期望时，这个功能将会非常有用。

例如，考虑到缩写词"LLM"。在某些情境下，这可能会被翻译为"法学硕士"，这在教育领域是一个标准的解释。然而，在人工智能的上下文中，"LLM"指的是"大语言模型"。在这种情况下，自定义词库功能将允许用户指定"LLM"应被翻译为"大语言模型"，而不是"法学硕士"，以确保在上下文中的翻译更为准确。

以下是一些更多的例子，这些例子说明了自定义词库功能将是有益的：

1. "DevOps": 在软件开发行业中，"DevOps"是一个知名的术语，指的是一套将软件开发(Dev)和IT运营(Ops)结合在一起的做法。然而，翻译引擎可能无法正确理解这个词，并可能将其字面翻译，导致混淆。有了自定义词库功能，用户可以指定"DevOps"在翻译中应始终保持为"DevOps"。
2. 
3. "GAN": 在机器学习领域中，这个缩写词代表的是"生成对抗网络"。翻译引擎可能无法识别这个术语，并可能将其未翻译或者翻译不当。自定义词库功能将确保"GAN"始终被翻译为"生成对抗网络"。

通过提供用户在自定义词库中定义他们偏好的翻译的能力，我们可以大大提高沉浸式翻译插件的准确性和可用性。对于经常与专业或特定领域内容互动的用户来说，这将非常有价值。

**Comment by theowenyoung** [comment]
感谢建议。

由于翻译服务不受沉浸式翻译插件控制，所以实际上在前端实现这个有不少的困难，还会显著增加普通用户的理解成本，我们更想保持沉浸式翻译简单一点。

同时沉浸式翻译的双语对照本身就是为了解决翻译准确度的问题，有疑问的译文可以方便的对照原文解决。

我们之前调研过术语表的问题，但是后来发现实际上不太好做。不过这个功能也许未来会再次考虑。

**Comment by theowenyoung** [comment]
#91

**Comment by hyhy01** [comment]
> 感谢建议。
> 
> 由于翻译服务不受沉浸式翻译插件控制，所以实际上在前端实现这个有不少的困难，还会显著增加普通用户的理解成本，我们更想保持沉浸式翻译简单一点。
> 
> 同时沉浸式翻译的双语对照本身就是为了解决翻译准确度的问题，有疑问的译文可以方便的对照原文解决。
> 
> 我们之前调研过术语表的问题，但是后来发现实际上不太好做。不过这个功能也许未来会再次考虑。

我想翻译epub这些文档时使用术语表
