### ISSUE TITLE
[Bug]: 漏掉一句

### ISSUE THREAD

**Issue by Abirdcfly** [immersive-translate/immersive-translate#807]
### 插件版本号 | Version

0.7.14

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

A Deployment, which both creates a ReplicaSet to ensure that the desired number of Pods is always available, and specifies a strategy to replace Pods (such as [RollingUpdate](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#rolling-update-deployment)), is almost always preferable to creating Pods directly, except for some explicit [restartPolicy: Never](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy) scenarios. A [Job](https://kubernetes.io/docs/concepts/workloads/controllers/job/) may also be appropriate.
Deployment 既创建 ReplicaSet 以确保所需数量的 Pod 始终可用，又指定替换 Pod 的策略（例如 RollingUpdate），几乎总是优于直接创建 Pod，除了一些显式的 restartPolicy: Never

最后一句被省略了。https://kubernetes.io/docs/concepts/configuration/overview/#naked-pods-vs-replicasets-deployments-and-jobs

### 出现问题的网址 | URL

https://kubernetes.io/docs/concepts/configuration/overview/#naked-pods-vs-replicasets-deployments-and-jobs

**Comment by keyboard3** [comment]
“A Deployment, which both cr...”这一句嘛，我这边测试出来都翻译的。你更新版本再试试？

**Comment by Abirdcfly** [comment]
"scenarios. A [Job](https://kubernetes.io/docs/concepts/workloads/controllers/job/) may also be appropriate." 这句

**Comment by keyboard3** [comment]
这是Google翻译接口吞了。你试试微软看看

**Comment by Abirdcfly** [comment]
看起来是谷歌的问题。竟然会有这种问题，神奇。感谢开发者回复。关issue了。
