### ISSUE TITLE
[Bug]: 同一个段落下，代码块或引用块多于1一个时，代码块或引用块会丢失

### ISSUE THREAD

**Issue by srsng** [immersive-translate/immersive-translate#809]
### 插件版本号 | Version

0.7.16

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

同一个段落下，**代码块**或**引用块**多于1一个时，译文中代码块或引用块会丢失，可能的规律如下
>  代码块刚好有两个，只保留第一个；
> 代码块多于两个，全部丢失。

### 出现问题的网址 | URL

https://www.codewars.com/kata/54eb33e5bc1a25440d000891/rust

### 重现步骤 | To Reproduce

对应URL直接翻译即可重现

### 补充说明 | Additional context

一个频繁发生的问题

**Comment by versun** [comment]
不是很理解你的问题，我这边是正常的：
![image](https://github.com/immersive-translate/immersive-translate/assets/2398708/ca3799fb-a886-4376-8cb7-52df706aa1cb)

**Comment by srsng** [comment]
> 不是很理解你的问题，我这边是正常的： ![image](https://user-images.githubusercontent.com/2398708/258677931-ca3799fb-a886-4376-8cb7-52df706aa1cb.png)

我仔细看了一下，发现不同的翻译服务返回的结果不一样，下面的是腾讯交互翻译：
![image](https://github.com/immersive-translate/immersive-translate/assets/113006793/d9bcb11f-d2f3-4212-aca7-a1baf51fcf62)
使用微软翻译结果是正常的。
可能是因为输入方面的问题

**Comment by versun** [comment]
我这边使用腾讯交互翻译能复现这个bug, 不知道啥问题
我at下大佬看看 @theowenyoung  @keyboard3

**Comment by keyboard3** [comment]
已修复， 刷新重试下

**Comment by srsng** [comment]
> 已修复， 刷新重试下

发现还是有bug，
url：https://github.com/EmbarkStudios/relnotes/issues/2#issuecomment-775909537
腾讯交互翻译对这个评论中的比较长的代码块不能正常返回
