### ISSUE TITLE
Google Drive 似乎哪里还是有点问题，但是没有能复现

### ISSUE THREAD

**Issue by theowenyoung** [immersive-translate/immersive-translate#81]
之前复现过几次，后面就没法触发问题了。

表现是有的时候同步到 Google Drive的文件内容是 `[Object Object]`, 看起来是哪个地方被自动 toString 了，但是我看代码里也没找到。

我是用油猴，和浏览器反复同步的时候出现过该问题。 似乎是在边缘情况才会被触发，正常逻辑似乎没啥问题.

@bxb100  只能平时再多用用，看看能不能复现。

**Comment by bxb100** [comment]
好

**Comment by cesaryuan** [comment]
找到了稳定复现方法：在Chrome浏览器中，【手动管理备份文件】中删除所有文件，然后执行立即同步

**Comment by bxb100** [comment]
> 找到了稳定复现方法：在Chrome浏览器中，【手动管理备份文件】中删除所有文件，然后执行立即同步
> 
> 最新版依旧有效

你方便提个 PR 吗, 我现在改授权流程, 暂时没时间修 😢

**Comment by theowenyoung** [comment]
好吧。。 确实是 object object 问题。

我的锅，我之前以为油猴里没法直接用fetch， 所以改用了 background 代理去请求，但是 上传文件的请求是一个 form data, 似乎不能序列化？

而且似乎firefox可以正确的序列化，但是 chrome不可以.. 

修复后，直接使用 native fetch.
