### ISSUE TITLE
如何自己编译啊，我看到有makefile文件，但是拉去后无效

### ISSUE THREAD

**Issue by dianso** [immersive-translate/immersive-translate#810]
### 您希望的更新和改进是什么 | Update or Improve

如何自己编译啊，我看到有makefile文件，但是拉去后无效

**Comment by theowenyoung** [comment]
可以看下 README 正文第一句说明哈：

> 说明： 该 Repo 仅用于沉浸式翻译管理文档，[用户反馈](https://github.com/immersive-translate/immersive-translate/issues)，和 [发布版本](https://github.com/immersive-translate/immersive-translate/releases)，源代码目前是闭源的。

Makefile 文件用于构建文档网站：

本地服务：

```
make serve
```

文档网站的具体构建流程可参照： [ci文件](https://github.com/immersive-translate/immersive-translate/blob/main/.github/workflows/publish.yml)
