### ISSUE TITLE
[deeplx] 建议未配置deepl 的 api key 时模拟网页调用

### ISSUE THREAD

**Issue by Vixb1122** [immersive-translate/immersive-translate#811]
### 您希望的更新和改进是什么 | Update or Improve

deepl 支持模拟网页调用，建议和划词翻译一样，未配置 api key 时模拟网页调用，配置后使用 api key 调用。
deeplx 还得单启服务，很麻烦。

### 补充说明 | Additional context

参考实现：
https://github.com/HaleShaw/uTools-Translate/blob/ae711e128083dea3f7a9b6b8a3fb670a4008ec44/assets/js/deepL.js

https://github.com/pot-app/pot-desktop/blob/e2ed97d24466f09d001c87eec93f1ef897b508dd/src/interfaces/deepl.js

https://github.com/search?q=LMT_handle_jobs+language%3AJavaScript&type=code&l=JavaScript

**Comment by theowenyoung** [comment]
网页翻译并发量非常大，模拟网页翻译很快会触发速率限制，暂无计划支持哈。
