### ISSUE TITLE
[Bug]: macOS 版本 safari 插件不支持自动暗黑模式

### ISSUE THREAD

**Issue by xiajunwen1007** [immersive-translate/immersive-translate#812]
### 插件版本号 | Version

0.7.16

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

调整到暗黑模式时，弹出面板不支持暗黑模式，但是在ios上却支持。
<img width="425" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/49160447/d4a00550-f5b1-4020-bed9-b31c07cd5d87">

### 出现问题的网址 | URL

无

### 重现步骤 | To Reproduce

1. 点击插件按钮
2. 弹出面板后即可看到

### 补充说明 | Additional context

无

**Comment by theowenyoung** [comment]
由于 Safari 的限制，无法识别当前是否处于暗黑模式。这个只能等待未来safari修复。目前 设置页面是支持的～ 其他浏览器的面板暗黑 模式也是支持的。

<img width="312" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/b778a799-7fdc-4bd0-9764-9c0f141e58fd">
