### ISSUE TITLE
没有权限翻译页面

### ISSUE THREAD

**Issue by zhangqi0131** [immersive-translate/immersive-translate#814]
### 您希望的更新和改进是什么 | Update or Improve

![image](https://github.com/immersive-translate/immersive-translate/assets/77319544/39b7baa5-c60f-4268-90c5-f5ad901121fb)
网址：EDGE的插件，extension://cbdhgldgiancdheindpekpcbkccpjaeb/index.html?source=button

**Comment by theowenyoung** [comment]
扩展 确实 没有权限 访问别的扩展的页面，这个是通用的限制。

所有扩展都没有权限访问别的扩展的页面。
