### ISSUE TITLE
翻译目标语句中夹杂中文时，通常不会正确工作

### ISSUE THREAD

**Issue by inblossoms** [immersive-translate/immersive-translate#815]
### 您希望的更新和改进是什么 | Update or Improve

当翻译目标语句中夹杂中文时，通常不会正确工作。

1. 多次翻译
![image](https://github.com/immersive-translate/immersive-translate/assets/87680384/07a093d6-53b3-4555-8f08-1023cd99b162)
2. 不翻译
![image](https://github.com/immersive-translate/immersive-translate/assets/87680384/21afca93-d1d8-4046-9a32-3ce774542403)

### 补充说明 | Additional context

期待发生的行为 ：

- 原：Why can't you work properly in this situation
- 译：在这种情况下你为什么不能正确工作appropriately

**Comment by inblossoms** [comment]
感觉应该不是插件本身的问题？我尝试了不同的接口，在这个问题上都存在相同的问题，谷歌的情况相对较好。

**Comment by theowenyoung** [comment]
这个应该还可能和 其他插件的冲突有关系，和翻译引擎的关系也比较大。

建议同时只使用一个插件比较好。
