### ISSUE TITLE
在翻译网站的时候 偶尔碰到翻译2次的情况 

### ISSUE THREAD

**Issue by cjh-store** [immersive-translate/immersive-translate#82]
https://vitejs.dev/

![image](https://user-images.githubusercontent.com/88535245/216865646-72e1bbc7-5970-4a87-bab1-7fc920f5b3d5.png)

**Comment by theowenyoung** [comment]
好的, 我调查一下。

**Comment by Axlax336** [comment]
应该是装了其他翻译扩展，我也出现过，卸载了其他翻译扩展，就再也没有出现重复的问题了。
