### ISSUE TITLE
[Bug]: 在GPT写作的时候翻译总会漏掉一些

### ISSUE THREAD

**Issue by SAIL-Fang** [immersive-translate/immersive-translate#821]
### 插件版本号 | Version

V0.7.16

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/135190100/70c6ac92-3ec7-4c48-9bd0-f773b7595588)
![image](https://github.com/immersive-translate/immersive-translate/assets/135190100/e91046ca-b2db-422c-9afb-70a29fdfdefa)

### 出现问题的网址 | URL

https://chat.openai.com/

### 重现步骤 | To Reproduce

1. 翻译页面
2. 向GPT提问
3. 翻译GPT的回答时就会有漏掉的部分，这时候按CTRL也没反应

**Comment by keyboard3** [comment]
1.1.3 已修复
