### ISSUE TITLE
[Bug]: Google Translate displays the word "亚博体育app".

### ISSUE THREAD

**Issue by ottocsb** [immersive-translate/immersive-translate#823]
### 插件版本号 | Version

0.7.13

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 请描述这个Bug | Describe the bug

As the title suggests, when I was searching for GitLab on GitHub, I used this plugin. The translation service used is Google. In the image below, you can see that there are two instances. Please check if the Google service has been compromised.

### 出现问题的网址 | URL

https://github.com/search?q=gitlab&type=repositories

### 重现步骤 | To Reproduce

1. open url
2. Translate and use Google.

### 补充说明 | Additional context

![image](https://github.com/immersive-translate/immersive-translate/assets/83228451/8e8a503b-88ba-4ad5-8e37-715e398c8d0b)

**Comment by ottocsb** [comment]
Or, in other words, is this your advertiser?

**Comment by ottocsb** [comment]
Upgraded to 0.7.16, but the problem still persists.

**Comment by ottocsb** [comment]
Using Microsoft, no issues were found.

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/cef8ef3c-70dd-4afb-bb5f-013829cd3a18)
有没有可能是谷歌自己就是这么翻译的.....
