### ISSUE TITLE
[Bug]: 无法在 iframe 中使用输入框增强

### ISSUE THREAD

**Issue by myuanz** [immersive-translate/immersive-translate#824]
### 插件版本号 | Version

0.7.16

### 平台 | Platform

Linux

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

我们内部使用的邮件系统中，正文输入是放在一个`iframe`中的，不能正常使用输入框增强功能。
![image](https://github.com/immersive-translate/immersive-translate/assets/25359546/408402bc-0472-496b-88f0-57c9044c99c2)

我查了一下今年一月份似乎已经支持了`iframe`的处理，https://github.com/immersive-translate/immersive-translate/issues/25#issuecomment-1396961502 也许还有哪里没有考虑到？

这是一个非公开的系统，由于现在翻译器不再开源，我也不能自行 clone 代码来修复，只能给出相关的 HTML 提 issue 到这里了。

### 出现问题的网址 | URL

https://mail.cstnet.cn/

### 重现步骤 | To Reproduce

按照常规流程触发输入框增强时，在主题框可以触发，在正文框不能触发

**Comment by theowenyoung** [comment]
iframe 的输入框焦点获取目前确实在技术上还有问题，估计短期内不好解决。

暂时先关闭该问题。
