### ISSUE TITLE
是否可以考虑弃用<font>元素

### ISSUE THREAD

**Issue by forestsheep911** [immersive-translate/immersive-translate#825]
### 您希望的更新和改进是什么 | Update or Improve

根据MDN文档
https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/font

font是一个不建议使用的元素，而现在翻译的内容都会放在font元素中。
虽然现在的浏览器还都支持font，但建议将来某个时刻还是弃用font改用其他元素。
这个改动看上去也不会花很长时间。谢谢！

**Comment by keyboard3** [comment]
好建议  我们考虑下

**Comment by theowenyoung** [comment]
由于沉浸式翻译会将译文插入到网页中，所以如果采用常规元素比如`span` 等，会比较容易受到原网站的样式影响。比如类似的css:
`body span {
   color: red;
}

所以其实这是一个有意的设计， font 元素很少被正常网站使用，采用该元素会最大程度的避免被原网站的样式影响。

其他的网页翻译比如edge浏览器自带翻译，谷歌浏览器自带翻译也采用的是 font 元素来包装译文。

正常来说浏览器肯定不会淘汰这个元素，即使淘汰的话，它也是一个合法的自定义元素，不会受到影响。
