### ISSUE TITLE
Language Detection is Incorrect for Norwegian

### ISSUE THREAD

**Issue by heymaad** [immersive-translate/immersive-translate#826]
### 插件版本号 | Version

0.7.16

### 平台 | Platform

iOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

In Safari on ios 16.6, the language detected is incorrect. It detects Norwegian language as Swedish on all the Norwegian websites I have visited. Is it possible to fix this issue?
For example, go to https://no.m.wikipedia.org/wiki/Norge

This page is in Norwegian however it is detected as swedish. 

### 出现问题的网址 | URL

https://no.m.wikipedia.org/wiki/Norge

### 重现步骤 | To Reproduce

1. Go to https://no.m.wikipedia.org/wiki/Norge
2. Click the translator icon
3. It shows detected language as Swedish 
4. The website is in Norwegian so it should be detected as such

**Comment by keyboard3** [comment]
I tried it, and it did detect errors on safari, but it was correct on chrome. I tried to translate, and the result can be translated correctly

**Comment by theowenyoung** [comment]
Hi, I tested this, and in Chrome, Edge, these browsers, the language detection for this page is correct, and the page is recognized as Norwegian. But in Safari it is recognized as Swedish. This is the language code returned by Safari's page language detection API, so there doesn't seem to be much we can do about it. But you can indeed specify the language of any page manually, just select the language you want to specify in the popup panel -> source language. The extension will remember your choice for that page.
