### ISSUE TITLE
[Bug]: digitimesasia

### ISSUE THREAD

**Issue by KamiyaMinoru** [immersive-translate/immersive-translate#827]
### 插件版本号 | Version

0.716

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox, Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

諸多方塊內的新聞標題沒有翻譯 只翻譯到日期

![image](https://github.com/immersive-translate/immersive-translate/assets/78710607/83a87b25-4441-43b0-a028-ad35fad6bab6)

### 出现问题的网址 | URL

https://www.digitimes.com/

### 重现步骤 | To Reproduce

按翻譯(重新整理過也一樣)

**Comment by keyboard3** [comment]
已经支持翻译了，刷新重试下
