### ISSUE TITLE
关于自动翻译Youtube等网站视频字幕的问题

### ISSUE THREAD

**Issue by malaces** [immersive-translate/immersive-translate#828]
### 您希望的更新和改进是什么 | Update or Improve

插件老是自动翻译视频中的字幕导致有时候视频本来自带的翻译字幕和插件的翻译重叠卡bug，希望能改进这个地方不要自动翻译视频字幕。

**Comment by keyboard3** [comment]
进阶设置中可以关闭youtube字幕翻译
