### ISSUE TITLE
[Bug]: 翻譯字幕檔案

### ISSUE THREAD

**Issue by qscaxe** [immersive-translate/immersive-translate#829]
### 插件版本号 | Version

0.7.16

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

翻譯字幕檔案時 翻譯完成後點擊 導出字幕無法下載 會停留在原畫面

**Comment by keyboard3** [comment]
是字幕太大了？  我测试了字幕翻译好之后导出是可以的

**Comment by qscaxe** [comment]
Local Subtitle - 個人 - Microsoft Edge 2023-08-1...
<https://drive.google.com/file/d/1hwWFtt79RhS6PMFAIXHfm-dYI-IYVWuh/view?usp=drive_web>
不確定是不是我電腦的問題  因為在之前的版本都可以正常使用

keyboard3 ***@***.***> 於 2023年8月14日 週一 上午10:16寫道：

**Comment by qscaxe** [comment]
問題解決了，原來是我的srt檔案沒有副檔名，所以我加了副檔名上去就可以了，感謝回復

keyboard3 ***@***.***> 於 2023年8月14日 週一 上午10:16寫道：
