### ISSUE TITLE
[Bug]:  突然无法翻译

### ISSUE THREAD

**Issue by blakegger** [immersive-translate/immersive-translate#830]
### 插件版本号 | Version

0.7.16

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

不知是什么原因，插件突然不能翻译了，点击翻译按钮、翻译快捷键没有反应。
打开了debug模式，点击插件翻译按钮，提示信息如下:
```
message: ping  
content_script.js:4211 Immersive Translate DEBUG: content script received sync message: getPageStatus  
2content_script.js:4211 Immersive Translate DEBUG: content script received sync message: getCurrentPageLanguage  
message: ping  
content_script.js:4211 Immersive Translate DEBUG: content script received sync message: getPageStatus  
2content_script.js:4211 Immersive Translate DEBUG: content script received sync message: getCurrentPageLanguage  
```

翻译服务切换为google或微软，也没有反应

### 出现问题的网址 | URL

所有网址

### 补充说明 | Additional context

[复现过程](https://imgur.com/bWhhYqY)

**Comment by keyboard3** [comment]
这个看视频看不出来啥情况，其他页面都没有反应？ 卸载重装试试看

**Comment by keyboard3** [comment]
无反馈， 暂时关闭此issue
