### ISSUE TITLE
PDF解析工具推荐 | PDF Parser Tools Recommendation

### ISSUE THREAD

**Issue by xihuai18** [immersive-translate/immersive-translate#833]
### 您希望的更新和改进是什么 | Update or Improve

1. Table Extraction - https://github.com/ShaoZhang0115/Table-Extraction-for-Geoscience-Literature
![image](https://github.com/immersive-translate/immersive-translate/assets/23721828/58380481-c096-4130-8bc8-5705ec21052b)
2. Math formulas to Tex
- https://github.com/breezedeus/pix2text
![image](https://github.com/immersive-translate/immersive-translate/assets/23721828/245226f1-71af-4c8e-a906-3cf9c28eae70)
- https://simpletex.cn/
![image](https://github.com/immersive-translate/immersive-translate/assets/23721828/748994ac-6730-40c1-b7ff-d8d8885a759f)

### 补充说明 | Additional context

用起来觉得那个PDF翻译的排版、公式、表格错乱，咨询了一下专门搞这个的同学，上面的是推荐的工具，主要是开源的。
When I used it, the typesetting, formulas, and tables of the PDF translation were messed up. I consulted a classmate who specializes in this. The above open sourced tools (except SimpleTex) are recommended.

**Comment by keyboard3** [comment]
这个方案不适合广大用户的免费方案，免费方案可能还是需要再浏览器端算法做。这类高精度的公式翻译可能需要开放个适配api，或者单独做一个高精度翻译的工具，调用这类的pdf识别服务。不过这类pdf识别服务需要成本运行

**Comment by keyboard3** [comment]
> > 这个方案不适合广大用户的免费方案，免费方案可能还是需要再浏览器端算法做。这类高精度的公式翻译可能需要开放个适配api，或者单独做一个高精度翻译的工具，调用这类的pdf识别服务。不过这类pdf识别服务需要成本运行
> 
> Pix2Tex的免费模型只有几十M，或许放在浏览器也是可行的？

嗯嗯 可能需要等后面把pdf代码开源之后再来尝试

**Comment by 276562578** [comment]
请问现在的pdf翻译用的是什么库呢，我觉得 已经很棒了，想整合进zotero里面，非常非常十分十分的需要！！！！！

**Comment by keyboard3** [comment]
> 请问现在的pdf翻译用的是什么库呢，我觉得 已经很棒了，想整合进zotero里面，非常非常十分十分的需要！！！！！

没有库，人工优化的结果

**Comment by keyboard3** [comment]
免费方案暂时不会继续优化。表格公式需求的建议使用我们的 [pdf pro功能](https://app.immersivetranslate.com/pdf-pro/)
