### ISSUE TITLE
允许切换翻译服务的时候不自动翻译

### ISSUE THREAD

**Issue by Faputa** [immersive-translate/immersive-translate#834]
### 您希望的更新和改进是什么 | Update or Improve

希望能够增加一个选项，设置之后允许切换翻译服务的时候不自动翻译，因为许多时候我只是想在任意一个页面上调整设置而已，并非是想翻译当前页面。

### 补充说明 | Additional context

![image](https://github.com/immersive-translate/immersive-translate/assets/14192199/6e33187d-bf94-4a46-8263-b5cc86d41b19)

**Comment by keyboard3** [comment]
0.8.0 做了调整。针对未翻译过的网页，切换翻译服务不会重新翻译
