### ISSUE TITLE
[Bug]: 英文EPUB文件打开空白，翻译键无反应。

### ISSUE THREAD

**Issue by haog1g1** [immersive-translate/immersive-translate#835]
### 插件版本号 | Version

0.7.16

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

 打开英文epub文件后， 各个.xhtml框里全都空白， 点了翻译也没反应。
![image](https://github.com/immersive-translate/immersive-translate/assets/41842016/6df1674b-77f4-46c2-896f-cfab58467b92)

电子书下载链接： https://ktxr.rs/d1/y/1690857843/150/e/zlib2/pilimi-zlib2-0-14679999-extra/5588580~/K7RAfHFqUcmFC5gY20Lewg/refrigerant-charging-and-service-procedures-for-ac--annas-archive.epub

### 出现问题的网址 | URL

本地

### 重现步骤 | To Reproduce

1. got o "More"- "Make dual EPUB Ebook"
2. select refrigerant-charging-and-service-procedures-for-ac--annas-archive.epub

**Comment by haog1g1** [comment]
可能每次链接都会变。

按照失效提示， 打开 https://www.annas-archive.org/， 搜索 “refrigerant-charging-and-service-procedures-for-ac”， 点击唯一一个结果，；里面6个结果， 一般我选 '- Option #4: [Libgen.li]  (click “GET” at the top)',  在打开的网页点 “GET” 即可下载。

稍有不便请谅解。

**Comment by keyboard3** [comment]
我看了下这个文件好像有20多兆？ 太大了
