### ISSUE TITLE
bug:X浏览器悬浮球页面异常打开

### ISSUE THREAD

**Issue by 5418541** [immersive-translate/immersive-translate#836]
### 插件版本号 | Version

0.716

### 平台 | Platform

Android

### 浏览器 | Browsers

Other

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

手机网页上的悬浮球按钮只要启动之后，在点击网页界面任意地方都会展开翻译界面，非常麻烦。这是什么奇怪bug

### 出现问题的网址 | URL

任意网址

### 重现步骤 | To Reproduce

四指触摸或者点击悬浮球，打开翻译界面即可，之后即使手动关闭翻译界面，点击其他空白地方都会自动展开

### 补充说明 | Additional context

能不能弄成点击悬浮球才能展开界面

**Comment by Vstory** [comment]
X 浏览器使用时，出现这个问题

**Comment by keyboard3** [comment]
你的是什么浏览器？

**Comment by 5418541** [comment]
x浏览器

**Comment by 5418541** [comment]
> 你的是什么浏览器？

x浏览器，我把浏览器清除数据后重新安装脚本，还是有这个bug

**Comment by theowenyoung** [comment]
请问最新版还有此问题吗？ 我刚测试最新版在X浏览器是正常的。

**Comment by 5418541** [comment]
没有问题了，是和别的脚本冲突，抱歉
