### ISSUE TITLE
阅读本地电子书时，能不能根据文件名称，在HTML中生成一个UUID

### ISSUE THREAD

**Issue by byeage** [immersive-translate/immersive-translate#837]
### 您希望的更新和改进是什么 | Update or Improve

epub,mobi电子书本地阅读的时，个别书生成的样式难以阅读，只能在页面中去手动去修改css，修改之后又无法保存，能不能在
阅读本地电子书时，根据文件名称，在HTML中生成一个UUID。这样就能在插件注入时，根据UUID为个别书配置单独的样式，也可以一直保存，不用每次打开又得手动添加样式

**Comment by theowenyoung** [comment]
将在 0.9.7 版本支持。

[data-immersive-translate-hash="7052a9eb4ea5c55f9e6eb43d00f70484"] {
  color:red;
}


<img width="965" alt="图片" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/265c31bc-bf20-4d01-a2f4-dbdaa2d814fb">

**Comment by theowenyoung** [comment]
已release
