### ISSUE TITLE
[Bug]: ios 下载完app扩展程序怎么卸载呀 没有入口卸载 禁用掉 资源库也删除不掉

### ISSUE THREAD

**Issue by 2ru1** [immersive-translate/immersive-translate#838]
### 插件版本号 | Version

0.5.5

### 平台 | Platform

iOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

[Bug]: ios 下载完app扩展程序怎么卸载呀 没有入口卸载 禁用掉 资源库也删除不掉

### 出现问题的网址 | URL

safari

### 重现步骤 | To Reproduce

[Bug]: ios 下载完app扩展程序怎么卸载呀 没有入口卸载 禁用掉 资源库也删除不掉

### 补充说明 | Additional context

[Bug]: ios 下载完app扩展程序怎么卸载呀 没有入口卸载 禁用掉 资源库也删除不掉

**Comment by keyboard3** [comment]
在手机桌面就有app图标啊，长按图标卸载就可以了啊

**Comment by keyboard3** [comment]
无反馈 暂时关闭此issue
