### ISSUE TITLE
在翻译技术文档的时候会出现错乱情况

### ISSUE THREAD

**Issue by danielesk** [immersive-translate/immersive-translate#84]
技术文档原文地址：https://doc.rust-lang.org/stable/core/ptr/fn.write.html

![image](https://user-images.githubusercontent.com/10652829/216877235-8d4fb0e8-01dd-4dd7-989a-545e5c574fa1.png)

![image](https://user-images.githubusercontent.com/10652829/216877247-8db66f09-a478-46d8-9388-355f308c9fc0.png)

**Comment by theowenyoung** [comment]
感谢反馈～ 第一个那个我刚更新了规则，已经解决了。(左键点击浏览器扩展菜单可以更新规则）

后面那个safety 是特意没有翻译的。单个独立的段落，如果文字太短的话，会忽略（要么很简单，要么是一些专有名词）

**Comment by danielesk** [comment]
@theowenyoung 好的好的

**Comment by danielesk** [comment]
@theowenyoung 可以了多谢
