### ISSUE TITLE
鼠标悬停翻译支持切换开关

### ISSUE THREAD

**Issue by wongchenv** [immersive-translate/immersive-translate#840]
### 您希望的更新和改进是什么 | Update or Improve

现在鼠标悬停翻译只能打开, 不能关闭. 
所以希望二次使用悬停翻译快捷键后, 复原已翻译的文本.
并且全局翻译过的页面, 也支持二次使用悬停翻译复原.

**Comment by hustppf-gc** [comment]
附议，希望添加原文/译文切换功能。

**Comment by theowenyoung** [comment]
最新版本已支持哈，Ctrl+鼠标滑过将会显示原文。
