### ISSUE TITLE
[Bug]: I just paid for the pro subscription and I have a problem.

### ISSUE THREAD

**Issue by Root-FTW** [immersive-translate/immersive-translate#842]
### 插件版本号 | Version

0.8.0

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

In the new version 0.8.0, even if you activate the "Show Translation Only" option, it still shows the original and the translated language.

### 出现问题的网址 | URL

ALL websites, example: https://www.inverse.com/

### 重现步骤 | To Reproduce

activate this option:
![2023-08-15 11_23_43](https://github.com/immersive-translate/immersive-translate/assets/108767514/0ff5eede-1397-48a0-bd79-9bdc9d97a007)

update the site or change to another news item within the same site, and the option stops working and shows you the original + translated text, 

### 补充说明 | Additional context

![2023-08-15 11_32_18](https://github.com/immersive-translate/immersive-translate/assets/108767514/8514ae90-13cf-49b8-b31e-3308d7bff59d)

**Comment by keyboard3** [comment]
This may indeed be a bug, but it does work, and all pages are available after refreshing them

**Comment by keyboard3** [comment]
0.8.1+ This issue is fixed
