### ISSUE TITLE
pdf 导出译文缓存

### ISSUE THREAD

**Issue by JuchiaLu** [immersive-translate/immersive-translate#843]
### 您希望的更新和改进是什么 | Update or Improve

现在 pdf 的译文是以图片形式导出，哪些重叠的地方如果没有空间容纳，导出后依然是重叠的，  希望可以把原文 pdf 和译文缓存打包成 zip 导出，之后可以重新导入到插件，把插件当作一个阅读器，这样那些重叠的地方依然可以在插件中滚动查看。

**Comment by keyboard3** [comment]
现在支持仅译文打印，打印出来的不是图片了

**Comment by keyboard3** [comment]
可以通过调整缩放模式来适配打印效果，建议调整至实际大小打印
