### ISSUE TITLE
强烈建议增加IDE插件！！开发人员的福音

### ISSUE THREAD

**Issue by Jackfruit-monster** [immersive-translate/immersive-translate#846]
### 您希望的更新和改进是什么 | Update or Improve

中文：天呐！浏览器插件都有了，开发一个IDE的插件吧，IntelliJ IDEA和Vs Code，这个真的是刚需啊，十个人有十一个都需要看开发文档、接口文档的，不仅仅我们，你们的开发也需要，不信你问问他

English: Gosh! Browser plug-ins are available, let the developers develop an IDE plug-ins, IntelliJ IDEA and Vs Code, this is really just need ah, eleven out of ten people need to see the development documentation, interface documentation, not only us, your development also need, do not believe you ask him!

### 补充说明 | Additional context

中文：查阅开发文、接口文档说明，基本都是英文，需要翻译成中文
English：Access to the development of text, interface documentation, basically in English, need to be translated into Chinese

中文：目前的替代品有：MarketPlace中的Translation，主页地址：[Translation](https://github.com/immersive-translate/immersive-translate/discussions/plugins.jetbrains.com/plugin/8579-translation)，我们只需要把浏览器插件的功能移植过来就可以了，只有沉浸式翻译才是 YYDS！

English：Current alternatives include Translation in MarketPlace, homepage at [Translation](https://github.com/immersive-translate/immersive-translate/discussions/plugins.jetbrains.com/plugin/8579-translation), where we simply port the functionality of the browser plugin over, only the immersive translation is YYDS!

**Comment by keyboard3** [comment]
暂时不会支持IDE

**Comment by Jackfruit-monster** [comment]
> 暂时不会支持IDE

行，干脆直接，哈哈哈
