### ISSUE TITLE
[Bug]: 使用open ai chatgpt4无法翻译pdf

### ISSUE THREAD

**Issue by coderZoe** [immersive-translate/immersive-translate#849]
### 插件版本号 | Version

0.8.0

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

使用open ai 选择chatgpt 4翻译pdf的时候，一直转圈圈无法翻译，但使用deepl就很快的翻译出来了，不知道是不是将整个pdf导入给gpt让他翻译了，如果是的话我的pdf大概900页，不知道能不能分段翻译，先翻译出来一部分吗，不然现在一直转圈圈，一直也没有翻译一行，我也不知道是有没有在进行翻译。

### 重现步骤 | To Reproduce

选择一个稍大的pdf，如《Computer Networking A Top-Down Approach (7th Edition)》，翻译服务选择Open AI其他设置均为默认设置，此时会一直等待，无法翻译

**Comment by coderZoe** [comment]
选择DeepL时 翻译基本是秒出的
![image](https://github.com/immersive-translate/immersive-translate/assets/55009317/cde944cf-bb7a-47de-b20c-764e0170ab3f)

但选择Open Ai的时候 会这样 
![image](https://github.com/immersive-translate/immersive-translate/assets/55009317/c590894b-1733-4fb8-82e9-33e01917e3f9)
点击这些蓝色的循环按钮依然是转圈圈，没有任何用，没翻译任何文本

**Comment by theowenyoung** [comment]
请问你使用的 openai 支持GPT4吗？

**Comment by theowenyoung** [comment]
会员的 openai 不支持GPT4的.

![image](https://github.com/immersive-translate/immersive-translate/assets/62473795/bd6303e8-41b0-4595-95f6-7eb3ee912384)

**Comment by coderZoe** [comment]
> 会员的 openai 不支持GPT4的.
> 
> ![image](https://user-images.githubusercontent.com/62473795/261343078-bd6303e8-41b0-4595-95f6-7eb3ee912384.png)

好的，明白了
