### ISSUE TITLE
关于模糊效果的默认快捷键与常用快捷键冲突的问题

### ISSUE THREAD

**Issue by DCxDESIGN** [immersive-translate/immersive-translate#85]
您好，我正在使用您开发的 Chrome 版扩展程序

我发现您在扩展版里默认将 Alt+D 指定为了 显示/隐藏译文模糊效果 ，但它与一般大众浏览器（以及文件资源管理器等类似软件）的“将焦点切换至地址栏”的默认快捷键是一样的，导致我安装了您的扩展程序后就无法使用 Alt+D 切换焦点到地址栏了，并且因为不了解情况和浏览器开发者一起排查了不少时间才找到原因。在此建议您在默认设置中避开 Alt+D 快捷键，其它使用 Alt+单键 的快捷键可能也需要谨慎使用，最好能默认为空并引导用户在自己需要的情况下再手动设定。

您开发的扩展程序非常好用，非常感谢您

**Comment by theowenyoung** [comment]
好的，感谢建议，之前不知道这是一个系统默认快捷键。

下个版本将会移除～
