### ISSUE TITLE
沉浸式翻译 Google 文档

### ISSUE THREAD

**Issue by Rennix09** [immersive-translate/immersive-translate#851]
### 您希望的更新和改进是什么 | Update or Improve

国外的优秀文档大多存放在 Google 文档中，如果能够像查看普通网页一样使用沉浸式翻译将会对阅读国外文档有特别大的帮助。再次感谢开发者开发如此优秀的软件。
PS: Google 文档是以 canvas 技术渲染的
相关链接： https://docs.google.com

**Comment by theowenyoung** [comment]
canvas 应该做不到。
