### ISSUE TITLE
[Bug]: 翻译pdf时没有正确区分段落

### ISSUE THREAD

**Issue by heheda123123** [immersive-translate/immersive-translate#852]
### 插件版本号 | Version

0.8.0

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

估计是原pdf里面，每行文字的间隔比较大，导致翻译是以行为单位来翻译，跨行句子的意思断开了
![image](https://github.com/immersive-translate/immersive-translate/assets/97490782/c72d1515-de8b-4ee2-a491-be97d374fc2f)

如果用划词翻译，因为是我手动选择了所有文字，翻译出来的句子就很完整
![image](https://github.com/immersive-translate/immersive-translate/assets/97490782/cce81fb0-5bc5-405d-944d-e4d736fdfe2e)

[Bug Bounty Playbook.pdf](https://github.com/immersive-translate/immersive-translate/files/12379863/Bug.Bounty.Playbook.pdf)

是不是可以增加个选项，直接发送一整页的内容去翻译

**Comment by keyboard3** [comment]
是的 但是可能不是发送一页，因为一页无法区分段落。可能还是得依赖手动选中来，这个后面优化一下加一个手动选中的翻译补充

**Comment by heheda123123** [comment]
可以的，增加一个把选中文本标记为段落一起翻译的功能也行。不然翻译效果反而没划词翻译那种效果好

**Comment by heheda123123** [comment]
好像挺多这种情况的，特别是对于epub转成pdf的这种
[PowerShell Automation and Scripting for Cybersecurity-1.pdf](https://github.com/immersive-translate/immersive-translate/files/12385029/PowerShell.Automation.and.Scripting.for.Cybersecurity-1.pdf)

**Comment by keyboard3** [comment]
0.8.8 支持了行间距调整
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/1d16ac51-3719-44cc-9826-2df741403820)

**Comment by keyboard3** [comment]
> 这个间距的单位是啥？

px 单位
