### ISSUE TITLE
PDF最多只能翻译到后2页

### ISSUE THREAD

**Issue by lurui45** [immersive-translate/immersive-translate#854]
### 您希望的更新和改进是什么 | Update or Improve

尝试打开一个有数百页的PDF，我发现默认只会翻译当前页和随后的2页，如果我需要翻译整个PDF文档的话，难道我要一直手动从第一页滚动到最后一页？
能否添加设置允许一直翻译到最后一页。

**Comment by keyboard3** [comment]
是的，插件目前只支持实时浏览翻译。目前技术上在浏览器端也无法支持到这个需求
