### ISSUE TITLE
[Bug]: 点击翻译没有反应

### ISSUE THREAD

**Issue by Yx7777** [immersive-translate/immersive-translate#855]
### 插件版本号 | Version

0.5.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

该网站点击翻译没有反应

### 出现问题的网址 | URL

https://cloud.tencent.com/developer/article/1949426

### 重现步骤 | To Reproduce

1、打开网站
2、点击翻译

### 补充说明 | Additional context

希望改进

**Comment by keyboard3** [comment]
这不是中文网站嘛？ 为啥还要翻译？

**Comment by keyboard3** [comment]
无反馈，暂时关闭此问题
