### ISSUE TITLE
[Bug]: macOS 平台上 chrome 浏览器安装插件后空白页地址栏粘贴变的异常卡顿

### ISSUE THREAD

**Issue by yixinglu** [immersive-translate/immersive-translate#856]
### 插件版本号 | Version

0.8.0

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

macOS 平台上 chrome 浏览器安装插件后空白页地址栏粘贴变的异常卡顿，要等个几秒钟之后才能成功黏贴内容。禁用插件后，chrome 的行为正常，打开插件后又现问题。

### 重现步骤 | To Reproduce

1. 复制一个网页地址
2. 打开 chrome 一个空白页
3. 光标定位到地址栏
4. Ctrl+V 粘贴对应的网页地址
5. 延迟几秒钟之后，地址栏出现对应的网页地址

**Comment by keyboard3** [comment]
我一直都是在macos下使用chrome，没出现过这个问题呀，是在指定网页吗？

**Comment by yixinglu** [comment]
再补充点环境信息：

**Comment by theowenyoung** [comment]
但是该插件不会以任何方式和空白标签页进行交互，同时也没有监听剪切板。

（可以重新安装下chrome试试？
