### ISSUE TITLE
[Bug]: 部分页面使用火山翻译, 和腾讯翻译君时会出现乱码问题.

### ISSUE THREAD

**Issue by wongchenv** [immersive-translate/immersive-translate#857]
### 插件版本号 | Version

0.8

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

部分页面使用火山翻译, 和腾讯翻译君时会出现乱码问题.
<img width="1467" alt="iShot_2023-08-19_18 55 23" src="https://github.com/immersive-translate/immersive-translate/assets/14831158/a642f4e9-44bb-4f21-8739-27545e07a170">

### 出现问题的网址 | URL

https://www.notion.so/help

**Comment by keyboard3** [comment]
这个是这些翻译服务太频繁了，需要自己去设置调低一下频率，你可以点击？看报错。点击刷新图标直接重试
