### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by dantenull** [immersive-translate/immersive-translate#858]
### 插件版本号 | Version

0.8.0

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

翻译重叠，应该是翻译的文章其它部分的内容和本页的内容重叠，因为翻译中明显含有不是本页中内容的翻译
![屏幕截图 2023-08-19 220822](https://github.com/immersive-translate/immersive-translate/assets/29767985/17887d0e-5376-4d8b-a9e5-0581fe4ddbff)

### 出现问题的网址 | URL

https://arxiv.org/pdf/2304.08354.pdf

### 重现步骤 | To Reproduce

就直接点翻译按钮没有其它操作

### 补充说明 | Additional context

第13页

**Comment by keyboard3** [comment]
我看了下 是这一页的原始数据重复了。渲染了两层一模一样的，你可能需要自己删除多余的
