### ISSUE TITLE
为什么不支持gpt翻译了？

### ISSUE THREAD

**Issue by gy-0** [immersive-translate/immersive-translate#860]
### 您希望的更新和改进是什么 | Update or Improve

记得之前可以用OpenAI的API来调用gpt-3.5-turbo翻译，现在为啥没有这个选项了？希望能加上，因为gpt的翻译质量确实高啊

**Comment by theowenyoung** [comment]
支持的啊。请问你用的是什么浏览器？插件版本是？ 可以截图看下你的翻译服务列表。

**Comment by f48vj** [comment]
iOS Safari 插件版本 0.8.0 没有看OpenAI

**Comment by FattySpring** [comment]
【开发者设置】-> 【开启 Beta 测试特性】

**Comment by theowenyoung** [comment]
@f48vj 目前已默认显示了哈。【开启beta测试】后会保证永远显示。
