### ISSUE TITLE
[Bug]:  网页中文也进行了翻译

### ISSUE THREAD

**Issue by wang20150419** [immersive-translate/immersive-translate#861]
### 插件版本号 | Version

0.8.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

看推特的时候，中文推特也进行了翻译。

### 出现问题的网址 | URL

twitter.com

**Comment by keyboard3** [comment]
中文翻译是指繁体中文吗？

**Comment by 93814690** [comment]
简体也翻译了

**Comment by keyboard3** [comment]
> 简体也翻译了

给个帖子我看下

**Comment by 93814690** [comment]
> > 简体也翻译了
> 
> 给个帖子我看下

https://twitter.com/myfxtrader/status/1693261579352244371

**Comment by 93814690** [comment]
<img width="1194" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/13295202/9a1ee757-07a2-4f90-840b-f19154ce9a13">
更新了0.8.3依然是

**Comment by keyboard3** [comment]
你是不是用户规则加了什么，我们这边两个浏览器都没有翻译中文

**Comment by wang20150419** [comment]
我这里没加用户规则。这是0.8.3的状况。在“基本设置”里，已禁止对 简体和繁体中文的段落翻译。

![image](https://github.com/immersive-translate/immersive-translate/assets/12016822/02650080-995f-4c2a-850b-e21687e628a5)

**Comment by wang20150419** [comment]
0.8.4版本修复此BUG。

**Comment by keyboard3** [comment]
> 0.8.4版本修复此BUG。

已经好了是吗？
