### ISSUE TITLE
[Bug]: 使用openai翻译本地日语字幕文件为中文时一些字幕片段会出现不翻译(只显示日语原文)或者翻译成英文

### ISSUE THREAD

**Issue by fycsid** [immersive-translate/immersive-translate#862]
### 插件版本号 | Version

0.8.3

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

尝试了把原文语言从自动设置成日语,
调整了每次请求最大段落数,
但依然无法解决,
使用的是GPT-3.5 turbo 0613
奇怪的是尝试了很多次,出现不翻译或者翻译成英文的日文片段都是固定那几个片段

**Comment by f48vj** [comment]
估计得从 prompt 下手

**Comment by keyboard3** [comment]
如果切换成其他翻译服务没有出现这个问题，那确实需要自己尝试改变下提示词看看

**Comment by theowenyoung** [comment]
可以提供一下字幕文件吗？这样比较好定位问题。
