### ISSUE TITLE
[Bug]: chatGPT web（3.5 mobile)错误

### ISSUE THREAD

**Issue by ajason** [immersive-translate/immersive-translate#863]
### 插件版本号 | Version

0.8.4

### 平台 | Platform

macOS

### 浏览器 | Browsers

Other

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

鼠标悬停 服务选择 chatGPT web（3.5 mobile) 使用时会提示错误：
Cannot read properties of undefined (reading 'split')

### 补充说明 | Additional context

浏览器已登录chatGPT plus

**Comment by keyboard3** [comment]
该翻译服务属于beta测试阶段，经测试目前不可用，已下掉
