### ISSUE TITLE
自定义User规则对epub阅读无效

### ISSUE THREAD

**Issue by buliaoyin** [immersive-translate/immersive-translate#864]
### 您希望的更新和改进是什么 | Update or Improve

在User规则中，我配置了禁止翻译列表的规则，规则如下：
```
    "excludeSelectors": [
      "table"
    ]
```
该规则可以在网页上生效，table项不会被翻译了。但在阅读epub文档时，table项还是会被翻译。

期望自定义配置可以同时在阅读以及翻译epub文档时生效。

**Comment by theowenyoung** [comment]
你是如何自定义的？应该可以这样自定义：

```
"generalRule":{
 "excludeSelectors.add": [
      "table"
    ]
}
```

**Comment by theowenyoung** [comment]
放在 user config 里面，不是 rules 里面。

**Comment by buliaoyin** [comment]
<img width="838" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/4070520/b20b0ea3-352c-49b1-8e37-60a37ebe6701">
配置是这样写的，网页上可以正常生效，本地epub不生效。

**Comment by buliaoyin** [comment]
> 

我试下这个写法

**Comment by buliaoyin** [comment]
> 你是如何自定义的？应该可以这样自定义：
> 
> ```
> "generalRule":{
>  "excludeSelectors.add": [
>       "table"
>     ]
> }
> ```

我试下这个写法

**Comment by buliaoyin** [comment]
> 你是如何自定义的？应该可以这样自定义：
> 
> ```
> "generalRule":{
>  "excludeSelectors.add": [
>       "table"
>     ]
> }
> ```

使用这个写法结果是一致的，也是网页可以生效，但是本地epub不生效

**Comment by keyboard3** [comment]
试下这个
`   {
      "id": "isEbook",
      "excludeSelectors.add": [
        "table"
      ]
    },
    {
      "id": "isEbookBuilder",
      "excludeSelectors.add": [
        "table"
      ]
    }`

**Comment by buliaoyin** [comment]
> ```
> 
> ```

这个配置生效了，非常感谢！
