### ISSUE TITLE
PDF字体大小自定义

### ISSUE THREAD

**Issue by duhd1993** [immersive-translate/immersive-translate#866]
### 您希望的更新和改进是什么 | Update or Improve

希望能够自定义翻译后PDF字体大小。因为汉字信息密度高，保持同样大小的字体，会空出来不少空间。同时因为笔画更密集，同样大小字体情况下，英文尚能看清，汉字看起来就有点费劲。希望能够自定义汉字大小。例如，随意打开一个elsevier的文献
![image](https://github.com/immersive-translate/immersive-translate/assets/2936633/c5f56b61-be81-4d2a-9283-ce38cb8e218b)

**Comment by FattySpring** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/25144301/d936bcc0-f173-4eb5-8f76-5e85046a80eb)
最新版本已支持字体大小缩放
