### ISSUE TITLE
[Bug]: PDF 双语生成的目录样式错乱，.... 变成了 。。。

### ISSUE THREAD

**Issue by blackstoneblackstone** [immersive-translate/immersive-translate#868]
### 插件版本号 | Version

0.8.5

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/7567320/a680c8a2-3712-4005-98e0-53ad1c9781d1)
看图应该一目了然了吧

### 重现步骤 | To Reproduce

1. 使用 PDF 翻译

**Comment by keyboard3** [comment]
pdf 文件发下

**Comment by blackstoneblackstone** [comment]
> pdf 文件发下

PDF 这里下载：https://books-library.net/files/books-library.net-10121732Pl7G6.pdf
