### ISSUE TITLE
deepl API 密钥在其中某一API超过限额时，能够使用其他负载均衡中密钥来翻译

### ISSUE THREAD

**Issue by wchen9** [immersive-translate/immersive-translate#869]
### 您希望的更新和改进是什么 | Update or Improve

比较理想的实现是，在当天某一 API 密钥超量时，把超量 API 标记为不可用，然后使用负载均衡中其他 API，直至所有 API 均不可用才报错用量超限。

第二天时重复探测 API 是否超限，因为可能限额周期已经刷新了。

**Comment by imtipi** [comment]
也可以参考划词翻译，429后把报错密钥放到队列最后面，然后继续使用队列的第一个密钥，直到再次报错

**Comment by theowenyoung** [comment]
暂时没有计划支持特定的复杂逻辑。建议直接使用,自定义API： https://immersivetranslate.com/docs/services/custom/

在自托管的服务中实现个性化的逻辑。
