### ISSUE TITLE
[Feature Request] 增加原文显示样式

### ISSUE THREAD

**Issue by Indekkusu545** [immersive-translate/immersive-translate#87]
现在插件可以设置译文显示样式，建议也可以提供原文显示样式设置。

#59 提到的【不显示原文】也可以作为一种样式。

**Comment by theowenyoung** [comment]
原文样式可能不太适合修改，因为各种网站千奇百怪的... 修改样式后还可能造成原网页的功能失调. 只有译文是插件自己添加的，所以可以随便做修改。
