### ISSUE TITLE
[Bug]: OpenAI输入自己的API但无法翻译，其他翻译就可以

### ISSUE THREAD

**Issue by nicolecee** [immersive-translate/immersive-translate#870]
### 插件版本号 | Version

0.8.5

### 平台 | Platform

Windows

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

OpenAI已设定自己的API但无法翻译，其他翻译比如Google翻译就可以

### 出现问题的网址 | URL

网址都有这个问题，网页会显示“错误段落”，pdf则保持英文

**Comment by keyboard3** [comment]
点击测试按钮  保证测试连通了，你才能去翻译其他的

**Comment by keyboard3** [comment]
截图你的配置

**Comment by nicolecee** [comment]
我这里没有测试按钮哎 
![image](https://github.com/immersive-translate/immersive-translate/assets/104307247/a9239d9d-1156-49c8-97a6-c48704c21600)

**Comment by keyboard3** [comment]
点击设置页面进去就可以看到啊。或者你点击页面上的?号也可以看到报错
