### ISSUE TITLE
[Bug]: 网页中有超链接的文字，翻译后就不能点击跳转

### ISSUE THREAD

**Issue by BAIIIIQ** [immersive-translate/immersive-translate#871]
### 插件版本号 | Version

0.85

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

网页中有超链接的文字，翻译后就会出现有些能点击跳转有些就不能跳转
比如下面图片框住的位置是有链接的
![图片](https://github.com/immersive-translate/immersive-translate/assets/130134009/a8f29ff7-66c9-4742-b916-c7cceff071a6)

### 出现问题的网址 | URL

https://projects.blender.org/
有不少网站都会出现这个问题

### 重现步骤 | To Reproduce

[](url)

**Comment by theowenyoung** [comment]
目前这是期待的行为，因为是纯文本翻译，会丢失 链接 的信息。 后面可能会支持富文本翻译。
