### ISSUE TITLE
[Bug]:  Tampermonkey not work on youtube 

### ISSUE THREAD

**Issue by Alert1700** [immersive-translate/immersive-translate#872]
### 插件版本号 | Version

0.5.6.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

Why it doesn't work on youtube? It work on other website, but not youtube.

### 出现问题的网址 | URL

https://www.youtube.com/

**Comment by keyboard3** [comment]
https://immersivetranslate.com/ ，Official website upgraded to the latest version 0.8.6 。

**Comment by keyboard3** [comment]
Can you take a screenshot of your settings page to see if it's a configuration issue

**Comment by FattySpring** [comment]
Due to the lack of reply for a long time, this issue is temporarily closed
