### ISSUE TITLE
[Bug]: 翻译本地pdf, 中文无法显示半角空格, 无法手动添加半角空格

### ISSUE THREAD

**Issue by ZHLONG-CN** [immersive-translate/immersive-translate#874]
### 插件版本号 | Version

V0.8.6

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

我在使用这个插件阅读"Computer Architecture, Sixth Edition A Quantitative Approach (John L. Hennessy, David A. Patterson)", 发现其部分内容的空格无法显示, 并且无法添加空格. (在按下空格后没有反应, 但其他字符可以输入.)

这本书可以在布加勒斯特理工大学网站上下载pdf文件, 链接如下.
[http://acs.pub.ro/~cpop/SMPA/Computer%20Architecture,%20Sixth%20Edition_%20A%20Quantitative%20Approach%20(%20PDFDrive%20).pdf](http://acs.pub.ro/~cpop/SMPA/Computer%20Architecture,%20Sixth%20Edition_%20A%20Quantitative%20Approach%20(%20PDFDrive%20).pdf)

在Preface ■ xix页可以找到一些词如RISC-V ISA以及一些CPU型号, 这些词的空格没有显示出来. 如下图所示.

![image](https://github.com/immersive-translate/immersive-translate/assets/20869871/dca4aab7-adc6-46e9-b9d4-35b258314cbe)

同时, 我还发现翻译文本的样式不定时在切换, 切换后的样式可以显示空格, 并且可以添加空格. 但又不时自动切换回来. 另一个样式如下图.

![image](https://github.com/immersive-translate/immersive-translate/assets/20869871/c682f41d-f1b7-4ef9-aa69-543e5af77e3a)

我没有在选项中找到可以改变文本样式的选项. 工具栏中的"文本"工具不能改变选中文字的字体大小和颜色.

### 补充说明 | Additional context

浏览器字体设置如下.

![image](https://github.com/immersive-translate/immersive-translate/assets/20869871/9f73c7fa-6154-4aa5-969c-472445bf95fe)

**Comment by keyboard3** [comment]
译文样式会重新获取焦点时，确实会存在样式丢失的问题，这个不太好解决
