### ISSUE TITLE
macOS、iOS设备均频繁间断性无法正常翻译

### ISSUE THREAD

**Issue by p5ydn0** [immersive-translate/immersive-translate#877]
### 您希望的更新和改进是什么 | Update or Improve

macOS、iOS设备均频繁间断性无法正常翻译；
众多论坛反馈开通会员后才可以顺畅翻译。

**Comment by keyboard3** [comment]
请请正常的描述问题，不要但攻击标题。有问题说问题，不能翻译报什么错误

**Comment by keyboard3** [comment]
暂无反馈，暂时关闭issue。如有更新 请重开
