### ISSUE TITLE
切换翻译提供商建议

### ISSUE THREAD

**Issue by keyboard3** [immersive-translate/immersive-translate#878]
### 您希望的更新和改进是什么 | Update or Improve

提供一个是否要立刻刷新页面上已有的翻译内容的选项 
开了会员的话切换deepl跟openai比较频繁 希望开发者可以考虑一下

**Comment by theowenyoung** [comment]
目前不就是立刻刷新的嘛？

**Comment by keyboard3** [comment]
> 目前不就是立刻刷新的嘛？

该用户的需求是提供一个是否立刻刷新。意思有时候刷新并不想刷新重新翻译当前页面

**Comment by akira0245** [comment]
最好再增加一个切换翻译提供商的快捷键 或者更无感知的切换方式 开了会员的话切换deepl跟openai比较频繁

**Comment by theowenyoung** [comment]
1.1.0 版本新增了 6 个可以切换到指定翻译服务的快捷键，欢迎体验和反馈哈～
