### ISSUE TITLE
PDF翻译第三页开始原文和译文就重叠了无法正常查看

### ISSUE THREAD

**Issue by KCIntelligence** [immersive-translate/immersive-translate#88]
论文翻译遇到的情况是这样，
我用的Microsoft Edge版本 109.0.1518.78 
截图中是这样的
<img width="942" alt="截屏2023-02-06 18 18 50" src="https://user-images.githubusercontent.com/16779538/216946421-8b26ea8b-84f7-4a28-920f-ad26b57d7faa.png">

用Chrome也是这样的情况，而且中文译文会超出当前页屏幕，导致一部分看不到了。这个情况在Edge里面有改善。

**Comment by theowenyoung** [comment]
PDF相关问题统一在 https://github.com/immersive-translate/immersive-translate/issues/37 里讨论，暂时先关闭这个问题了
