### ISSUE TITLE
[Bug]: 自动开始翻译选中的这段话

### ISSUE THREAD

**Issue by lagaya** [immersive-translate/immersive-translate#880]
### 插件版本号 | Version

0.8.6

### 平台 | Platform

iOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

选中一句话原意是准备复制（有些时候甚至就是误触导致的选中），结果就自动开始翻译选中的这段话，并且翻译还会直接跟在文字后面，还会导致原文中的下一句话直接换行，非常破坏完整性。也没找到哪里可以关闭这个功能。（要想保留这个功能最好开个popup窗口，而且可以多选几个翻译引擎对比翻译，这样比较有意义）

**Comment by keyboard3** [comment]
选中不会触发自动翻译呀？能录个屏或者截个图嘛？

**Comment by theowenyoung** [comment]
@keyboard3 可以是某些网站的高亮功能，高亮了某段话，然后 插件检测到有新的动态元素出现，然后翻译。

@lagaya 请问有网址吗？具体是哪个网站？
