### ISSUE TITLE
结合edge大声朗读练习听力：能否提供一个按钮将翻译后的中文结果放在该句子的上方

### ISSUE THREAD

**Issue by SilverComet7** [immersive-translate/immersive-translate#884]
### 您希望的更新和改进是什么 | Update or Improve

使用edge大声朗读功能练习听力时，在翻译较长的英文段落后（开启换行后仍会有部分较长句），先听英文再听中文会比较懵。将中文放在句子上方时，edge大声朗读则会先读中文，再听到英文原文。先理解句意后再听更有效。

**Comment by theowenyoung** [comment]
目前技术上无法实现，多谢反馈，暂时先关掉这个issue了。
