### ISSUE TITLE
建议为 Readwise 优化

### ISSUE THREAD

**Issue by xxhk-org** [immersive-translate/immersive-translate#885]
### 您希望的更新和改进是什么 | Update or Improve

建议将 自动换行、译文添加独立的段落标签，这样可以在翻译后使用 Readwise 阅读时继续通过它的快捷键选中想要的段落。

目前翻译过的网页转入 Readwise 后，在按空格键切换，按H键高亮时，换过行的段落还是以换行前的段落为单位，下面的译文和上面的原文也还是在同一个段落里。

如果给换行后的内容添加独立的 p 标签，给译文添加独立的 p 标签，就可以在 Readwise 里直接选中了。

似乎对现有功能没有影响，但对 Readwise 就友好很多了。希望能优化下，感谢。

### 补充说明 | Additional context

例子：https://xxhk.org/addpp

**Comment by theowenyoung** [comment]
添加这个可能会破坏很多非文章类网站的译文布局，所以使用你链接里油猴脚本解决该问题是一个更好的选择。
