### ISSUE TITLE
[Bug]: MacOS上teams翻译遇见表情会一直翻译表情

### ISSUE THREAD

**Issue by AkaHanshan** [immersive-translate/immersive-translate#886]
### 插件版本号 | Version

0.8.9

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

启动翻译后，在teams上开启翻译，遇见表情会一直翻译这个表情导致bug
如图：
https://imgur.com/a/B4l6eTy

### 出现问题的网址 | URL

https://teams.microsoft.com/

### 重现步骤 | To Reproduce

选择有表情的teams页面，开启翻译

**Comment by theowenyoung** [comment]
感谢反馈，下个版本修复

**Comment by theowenyoung** [comment]
已修复。
