### ISSUE TITLE
[Bug]: 很多输入框都是可编辑的div这种 情况下输入框翻译不会生效

### ISSUE THREAD

**Issue by zjy2931** [immersive-translate/immersive-translate#887]
### 插件版本号 | Version

0.8.9

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

很多输入框都是可编辑的div这种 情况下输入框翻译不会生效  例如抖音,quora  这些网站的评论输入框   

### 出现问题的网址 | URL

https://www.quora.com/

**Comment by FattySpring** [comment]
quora 评论对空格输入有限制，可以改为其他触发方式 如：===
抖音无法监听输入的事件
