### ISSUE TITLE
[Bug]: 翻译本地PDF文件时，翻译后的文本显示方向出现错误

### ISSUE THREAD

**Issue by zjf592996468** [immersive-translate/immersive-translate#888]
### 插件版本号 | Version

0.8.9

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

使用翻译本地PDF文件时，翻译后的文本显示方向出现错误。

### 重现步骤 | To Reproduce

1. 使用翻译本地PDF文件功能，并打开一份本地PDF
<img width="1259" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/38467442/aa1f1ad8-7b96-4549-a35c-0655699c94af">

2. 最初正常，然后向上向下滚动页面，模拟自然浏览
<img width="1256" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/38467442/94cd1814-b6ba-4baa-909c-15bd0edf2c6b">

3. 再回到刚才的页面时，文字已经发生了旋转，逆时针转90度
<img width="1259" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/38467442/11591245-6616-4402-8359-eea2109efa94">

4. 此时文档中大部分页面的翻译文字都已经旋转，无法正常阅读
<img width="1253" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/38467442/f20b8c86-472c-4abc-a54e-d5ce3ba7ef3e">

9.

**Comment by keyboard3** [comment]
给个pdf 我们复现

**Comment by szl0834** [comment]
> 给个pdf 我们复现

我也出现了相似的排版错误问题，这里是pdf的链接 https://www.moj.go.jp/isa/content/930001658.pdf

**Comment by keyboard3** [comment]
> > 给个pdf 我们复现
> 
> 我也出现了相似的排版错误问题，这里是pdf的链接 https://www.moj.go.jp/isa/content/930001658.pdf

不一样，你这个原始就是竖版的。竖版很难和现在的兼容。暂不支持

**Comment by FattySpring** [comment]
最新版本已修复
