### ISSUE TITLE
[Bug]: 全文翻译特定网页时图片看不见了？

### ISSUE THREAD

**Issue by baagod** [immersive-translate/immersive-translate#889]
### 插件版本号 | Version

0.8.10

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

全文翻译就看不到图标了。网址：https://maxroll.gg/d4/build-guides/lightning-shred-druid-guide#endgame-gear-&-skill-progression-header

原文：
![image](https://github.com/immersive-translate/immersive-translate/assets/39392770/d2ddba7a-4018-482a-81f3-fa616bc027d7)

沉浸式全文翻译后：
![image](https://github.com/immersive-translate/immersive-translate/assets/39392770/e71fc168-b36a-4aab-b9e5-62d6daf3389a)

但是用浏览器内置【翻译为中文】就能显示：
![image](https://github.com/immersive-translate/immersive-translate/assets/39392770/83534b62-34a1-4817-9636-649291b8dd24)

----

该网站下的所有图标均都如此，反馈下，希望能改善。

### 出现问题的网址 | URL

https://maxroll.gg/d4/build-guides/lightning-shred-druid-guide#endgame-gear-&-skill-progression-header

### 重现步骤 | To Reproduce

Alt+W 全文翻译

**Comment by theowenyoung** [comment]
确实，因为目前的译文是纯文本翻译的，对于 `<img` 标签的图片可以识别和保留，但是该网页里的图片是通过特殊的样式注入的，目前确实不支持。

https://assets-ng.maxroll.gg/d4-tools/static/media/skills.f042c7b8.webp
