### ISSUE TITLE
希望"透明模式"跟"模糊模式"一样, 提供一个"透明/不透明"进行切换的快捷键

### ISSUE THREAD

**Issue by Ekuboh** [immersive-translate/immersive-translate#890]
### 您希望的更新和改进是什么 | Update or Improve

"透明模式"和"模糊模式"都属于"学习模式", 区别在于只是使用了不同的方式掩盖了译文, 或许应该统一一下学习模式的快捷键,: "模糊(透明)/不模糊(不透明)"

**Comment by theowenyoung** [comment]
1.1.0 版本起，如果你设置了默认的译文样式为透明模式，那么原有的快捷键按下之后会按照透明模式来显示译文。
