### ISSUE TITLE
添加"鼠标中键点击"翻译选项

### ISSUE THREAD

**Issue by Ekuboh** [immersive-translate/immersive-translate#892]
### 您希望的更新和改进是什么 | Update or Improve

`Ctrl+鼠标悬停`会与用鼠标选中文本后使用快捷键`Ctrl+c`复制相冲突, 导致误触翻译

**Comment by FattySpring** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/25144301/4b2f8f4f-d020-4d20-8b56-d8599b7e387a)
悬停翻译可更换其他快捷键

**Comment by Ekuboh** [comment]
如题, 请问可以设置为在选定段落按压鼠标中键后翻译吗?

**Comment by theowenyoung** [comment]
浏览器插件无法监听鼠标中键。

建议更换其他快捷键。
