### ISSUE TITLE
离线环境下，翻译本地pdf文件窗口有问题。

### ISSUE THREAD

**Issue by Kouuh** [immersive-translate/immersive-translate#897]
### 您希望的更新和改进是什么 | Update or Improve

离线环境下，想接入自己的翻译api。但在谷歌浏览器装了插件后，翻译本地pdf文件窗口没法打开本地文件，看报错信息是pdf/viewer.js下的pdfjsLib = require(“../build/pdf.js”)这行提示uncaught reference require is not defined.

**Comment by keyboard3** [comment]
在线就没有问题？

**Comment by theowenyoung** [comment]
我这边测试是OK的，关闭 电脑的 Wifi：

1. 允许沉浸式翻译访问文件系统
2. 右键【翻译】
3. 可以看到正常翻译了：


<img width="1680" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/1dd4970e-4d4b-4e04-9123-6e707d9bee3f">
