### ISSUE TITLE
BUG-部分非图片pdf仍无法翻译

### ISSUE THREAD

**Issue by YPJ1999** [immersive-translate/immersive-translate#898]
### 插件版本号 | Version

0.8.9

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在文献平台下载的英文文献，文件类型相同：Microsoft Edge PDF Document (.pdf)，未将其拖入插件翻译页面前，均可进行高光批注等编辑活动。但部分拖入翻译后，左侧原文档就变成图片式不可编辑，右侧也相应显示英文。而拖入后，如左侧依旧是可编辑状态，右侧才会出现字段翻译。

### 出现问题的网址 | URL

extension://amkbmndfnliijdhojkpoglbnaaahippg/pdf/index.html?file=file%3A%2F%2F%2FC%3A%2FUsers%2FHP%2FDesktop%2F%25E6%2596%2587%25E7%258C%25AE%25E7%25BB%25BC%25E8%25BF%25B0%25E5%259B%25BD%25E5%2586%2585%25E5%25A4%2596%2F%25E7%2594%25A8%25E5%25AD%2598%25E5%259C%25A8%25E4%25B8%25BB%25E4%25B9%2589%25E5%2588%2586%25E6%259E%2590%25EF%25BC%2588%25E5%25B7%25A8%25E5%25A4%259A%25EF%25BC%2589%2F%25E5%259C%25A8%25E8%258D%2592%25E8%25AF%259E%25E7%259A%2584%25E4%25B8%2596%25E7%2595%258C%25E4%25B8%25AD%25E8%25BF%25BD%25E5%25AF%25BB%25E7%259C%259F%25E5%25AE%259E%25E7%259A%2584%25E5%25AD%2598%25E5%259C%25A8--%25E5%25AD%2598%25E5%259C%25A8%25E4%25B8%25BB%25E4%25B9%2589%25E8%25A7%2586%25E5%259F%259F%25E4%25B8%258B%25E7%259A%2584%25E3%2580%258A%25E9%25A5%25A5%25E9%25A5%25BF%25E6%25B8%25B8%25E6%2588%258F%25E3%2580%258B.pdf

### 补充说明 | Additional context

两种情况对比截图：（不知是否能显示）

![_I~6TV3Z1XIQN9)28S98JG6](https://github.com/immersive-translate/immersive-translate/assets/143981490/af4e1975-45ef-49a7-aa1d-918f5f60becc)
![~X} RE6~B9ESMPDLF(JFX7W](https://github.com/immersive-translate/immersive-translate/assets/143981490/e5a1a42c-7ffa-4b2f-b15b-47de51ed1628)

**Comment by FattySpring** [comment]
不能翻译的应该是扫描版的PDF， edge 打开扫描PDF可以进行标注操作

**Comment by FattySpring** [comment]
第二张截图，译文逐行翻译，可通过【快速控制样式】调整【行间距】解决
