### ISSUE TITLE
希望网页翻译的PDF左右部分可以放大或者缩小

### ISSUE THREAD

**Issue by freedomspiritJohn** [immersive-translate/immersive-translate#899]
### 您希望的更新和改进是什么 | Update or Improve

![QQ截图20230904140402](https://github.com/immersive-translate/immersive-translate/assets/129288685/5add2506-0332-437c-bb84-d8752ca85131)
希望中间的这个可以左右拉动，以实现放大或者缩小原来的PDF和翻译后的PDF

**Comment by keyboard3** [comment]
这个效果我们目前的技术方案不好做...
