### ISSUE TITLE
[Feature Request] 希望对社交网站增加翻译按钮

### ISSUE THREAD

**Issue by PennHui666** [immersive-translate/immersive-translate#90]
需求参考自Greasy fork的YouTube评论翻译按钮-[https://greasyfork.org/zh-CN/scripts/456108-youtube%E8%AF%84%E8%AE%BA%E7%BF%BB%E8%AF%91%E6%8C%89%E9%92%AE](url)
这种形式很适合按需翻译，但是都适配的话要费一些功夫。不知道后续更新会不会考虑呢？

![image](https://user-images.githubusercontent.com/72249772/217025211-eb414bdb-36ee-44f1-9b7d-2da774024e2b.png)

**Comment by PennHui666** [comment]
当然可以，只要能实现按需翻译即可。只是参考我说的那个脚本的方式，做成翻译按钮的话交互比较自然，没那么割裂。如果是通过点击右键菜单或小图标来实现的话，译文同样还是会出现在原文下方吗？我用quicker的文本悬浮窗也能做到类似的效果，就是译文只能通过弹窗显示就比较割裂了，看完了还要关闭。

**Comment by theowenyoung** [comment]
可以的~

**Comment by theowenyoung** [comment]
目前已支持鼠标悬停翻译，请在小面板里启用即可～
