### ISSUE TITLE
几个建议

### ISSUE THREAD

**Issue by myh66** [immersive-translate/immersive-translate#901]
### 您希望的更新和改进是什么 | Update or Improve

1.是否可以加上多个deepl free api使用自动切换
<img width="821" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/53999290/ef27422c-2265-4312-babf-1df1781e2731">
<img width="807" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/53999290/2ca67b41-fe8d-4ab4-a6e2-c79f78f2c887">

**Comment by theowenyoung** [comment]
你可以通过,来分割多个 api key，程序会自动轮询。

**Comment by theowenyoung** [comment]
你可以通过,来分割多个 api key，程序会自动轮询。

**Comment by keyboard3** [comment]
> > 你可以通过,来分割多个 api key，程序会自动轮询。
> 
> key1, key2, key3
> 
> 这样么

是的
