### ISSUE TITLE
在新标签页中打开pdf翻译

### ISSUE THREAD

**Issue by ldeng-ustc** [immersive-translate/immersive-translate#902]
### 您希望的更新和改进是什么 | Update or Improve

当前对 pdf 文件进行翻译时，会将当前页面直接替换为翻译页面。但有时我们仍需要保留原来的 pdf 页面，所以只能重新打开一次pdf 文件/页面，较为不便。
因此，希望能增加在新标签页中打开 pdf 翻译页面的功能，或者选项中增加类似功能的选项。

**Comment by theowenyoung** [comment]
感谢反馈，这可能是更合理的默认行为，将在 0.9.2 成为默认行为。
