### ISSUE TITLE
[Bug]: 页面有一段话，似乎来自你们，在PDF翻译时会遮挡原文

### ISSUE THREAD

**Issue by jasonboo** [immersive-translate/immersive-translate#903]
### 插件版本号 | Version

0.8.10

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

原文如下：
| 你好，欢迎来到我们的网站。我们是一家专业的翻译机构，致力于提供高质量的翻译服务。我们拥有一支经验丰富、熟练的翻译团队，能够处理各种类型的翻译需求。无论是商务文件、学术论文、技术手册还是个人文件，我们都能提供准确、流畅、规范的翻译结果。我们始终以客户满意为首要目标，竭诚为您提供最佳的翻译解决方案。如果您有任何翻译需求，请随时联系我们，我们将尽力满足您的要求。非常感谢您选择我们的服务，我们期待与您的合作！

**Comment by keyboard3** [comment]
啊？ 没懂 这句话不是Pdf里面的？你用了什么翻译服务，我们不会插入别家的内容的。截个图看下？

**Comment by jasonboo** [comment]
<img width="643" alt="截屏2023-09-06 上午9 19 52" src="https://github.com/immersive-translate/immersive-translate/assets/7005330/82f18e06-6bd7-45e1-b942-41f899185e24">
chrome网页版暂时没有复现，本地PDF翻译的截图如上。
可以明显看到上面有一段话覆盖了原文。

……是一个全球领先的翻译引擎。我们致力于为用户提供高质量的翻译服务，涵盖各种领域和语言对。无论是商务文件还是个人需求，我们都可以满足您的翻译需求。我们的翻译团队由专业的翻译人员组成，具有丰富的经验和良好的语言能力。无论您需要简单短语的翻译还是复杂文档的翻译，我们都能提供准确、流畅且优雅的翻译。我们致力于将翻译服务变得简单、快捷和高效，帮助您跨越语言的障碍，实现全球交流和合作的目标。

**Comment by keyboard3** [comment]
你可以把pdf和你选定翻译服务通过邮箱告知我们嘛 support@immersivetranslate.com ，我尝试复现下看。 我初步看想来可能跟你选择的翻译服务有关系

**Comment by jasonboo** [comment]
不好意思，现在才看到您的回复。已经通过邮件发送给您了。

**Comment by keyboard3** [comment]
时间太久邮件太多了，邮箱名是同名的嘛，没有搜到...

**Comment by keyboard3** [comment]
你是不是用了第三方翻译服务，我又看到有一个用户出现了，它用了第三方的openAI服务出现了这个携带私货的情况。
