### ISSUE TITLE
Yahoo 无法按行翻译

### ISSUE THREAD

**Issue by shatuhi** [immersive-translate/immersive-translate#905]
### 您希望的更新和改进是什么 | Update or Improve

HI,

发现插件对https://news.yahoo.co.jp/的支援有部分问题。无法与其他网站一样逐段翻译，基本是整篇翻译，导致阅读不便。

并且在yahoo news 速览模式下，文字会重叠。

以下是想关网址：
https://news.yahoo.co.jp/pickup/6474402

https://news.yahoo.co.jp/articles/8ec1e5c81a91f3ede32ae056f97eda9511c5ffca

![feedback_202309051040111](https://github.com/immersive-translate/immersive-translate/assets/50195708/4b8b9e4d-9cf6-4ae0-b914-8576dc98f09b)
![feedback_20230905103932](https://github.com/immersive-translate/immersive-translate/assets/50195708/0f0fcec2-a5db-4bec-9173-f8ee05622451)

**Comment by keyboard3** [comment]
修好了 你刷新网页再试下看

**Comment by shatuhi** [comment]
感谢快速修正。

目前逐段翻译问题已经解决了。

不过PC 侧预览模式文字重叠好像还会存在。不过问题不大，主要是在手机侧使用。

再次感谢。

**Comment by shatuhi** [comment]
> > 感谢快速修正。
> > 目前逐段翻译问题已经解决了。
> > 不过PC 侧预览模式文字重叠好像还会存在。不过问题不大，主要是在手机侧使用。
> > 再次感谢。
> 
> 预览模式重叠，是第二张截图吗？没看出来有重叠呀

不是，第1张图，顶部文字标题和翻译重叠了。
刚刚重新查看网站，此问题亦解决了，可能是由于缓存造成的。

再次感谢！
