### ISSUE TITLE
[Bug]: 使用 medium-unlocker 后解锁的内容无法翻译

### ISSUE THREAD

**Issue by crowod** [immersive-translate/immersive-translate#909]
### 插件版本号 | Version

 0.9.1

### 平台 | Platform

Linux

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

使用 [medium-unlocker](https://github.com/und3fined/medium-unlocker) 解锁内容后, 解锁后的内容无法被翻译
没有unlock的内容正常翻译
![image](https://github.com/immersive-translate/immersive-translate/assets/22191245/efbcf974-1b63-4b6f-b0c7-80c14e6a3f9f)
unlock 的内容无法翻译
![image](https://github.com/immersive-translate/immersive-translate/assets/22191245/2ce198eb-c5a7-4db2-8760-9a670b0e037e)

### 出现问题的网址 | URL

https://medium.com/airbnb-engineering/avoiding-double-payments-in-a-distributed-payments-system-2981f6b070bb

### 重现步骤 | To Reproduce

1. 进入网址 (安装好 medium-unlocker chrome 插件后)
2. 确认插件运行正常
3. 使用翻译

### 补充说明 | Additional context

我看 medium-unlocker 解锁后内容在构建的一个 iframe 里 不清楚是不是这个引起的
![image](https://github.com/immersive-translate/immersive-translate/assets/22191245/e31f9816-b26f-4b3c-aeab-1395c9d4d99b)

**Comment by keyboard3** [comment]
应该是它造成的，这个晚点得看这种src里面丢html的  iframe该怎么处理

**Comment by keyboard3** [comment]
看了下 src来自data:text/html也是不同源，无法访问，没办法
