### ISSUE TITLE
[Feature Request] 能否添加翻译词库

### ISSUE THREAD

**Issue by Achuan-2** [immersive-translate/immersive-translate#91]
对于阅读专业性的网站来说，有些名词直接用翻译api翻译并不准确，能否添加翻译词库，来将英语优先翻译成词库里有的词

**Comment by theowenyoung** [comment]
这个功能正在计划中. 谢谢反馈～

**Comment by Achuan-2** [comment]
好，非常期待

**Comment by Axlax336** [comment]
是的，生词功能很需要，最好能有个生词库，根据等级，选择不同的库，然后自动在页面上做生词标记。

**Comment by theowenyoung** [comment]
@Axlax336  这里提到的术语库应该不是你说的生词库的概念。 术语库只是为了替换一些翻译词语为你自己的翻译，以达到更好的效果。

但是生词库是另一种东西了，好像有另一个扩展专门做这个的。这个应该不属于本扩展的功能计划。

**Comment by kifast** [comment]
这个功能翻译引擎自带, 比如百度就有"我的术语库"

**Comment by GrayXu** [comment]
> 这个应该不属于本扩展的功能计划

感觉翻译引擎的API里带的术语库feature还是比较受限，比如彩云是API直接不支持术语库，deepl是限制语种。  
不知道有没有在前端替换关键词的可能性？  
直接替换后，以双语的形式直接作为翻译引擎的输入可能比较奇怪（可能只是名词会好一些），或许gpt3.5可以？

**Comment by Achuan-2** [comment]
@kifast  术语库非常受限，百度的术语库添加了也不见得翻译有所优化

**Comment by theowenyoung** [comment]
@GrayXu 前端可以替换关键词的，应该也不需要事先替换为目标输入，只需要把关键术语用类似这样的占位符替换即可： `{1}`,`{2}` ， 然后翻译之后再进行重新组合。

**Comment by 1208041822** [comment]
极其需要这个功能

**Comment by seeflood** [comment]
非常需要这个功能。另一个思路是使用chatgpt 作为翻译引擎时，在prompt里让chatgpt不要翻译专业术语，比如 "Please do not translate technical terms." 
但是我测试下来不稳定，chatgpt有时候还是会翻译专业术语。感觉可以尝试优化prompt？

**Comment by kagangtuya-star** [comment]
非常期待这个功能的实现

**Comment by theowenyoung** [comment]
大家好，目前最新版本 1.1.0 以上已经支持了指定不翻译某些词语，可以在【进阶设置】里设置：

![CleanShot 2024-01-08 at 18 37 18@2x](https:github.com/immersive-translate/immersive-translate/assets/62473795/89c75793-0a12-419c-b510-390fdb5c0778)


如果你想做进一步的替换的话，还可以在开发者设置里指定要把这些不翻译的词替换为指定的词，示例配置如下：


```json
{ 

"generalRule":{
       "glossaries": [{
          "k": "LLM",
          "v": "大语言模型"
       }, {
          "k": "LLMs",
          "v": ""
       }]
},
}
```

**Comment by NoSW** [comment]
手动在【进阶设置】里设置需要跳过翻译的单词太繁琐了。可以支持右键菜单->添加到个人词库 的操作吗？

**Comment by theowenyoung** [comment]
> 手动在【进阶设置】里设置需要跳过翻译的单词太繁琐了。可以支持右键菜单->添加到个人词库 的操作吗？

由于我们未能控制第三方翻译，目前的实现是简单粗暴的替换，不建议大量使用。

**Comment by 5418541** [comment]
能不能把自定义替换功能直接放到进阶设置里面呢，这样添加词语更快更方便。

**Comment by keyboard3** [comment]
> 能不能把自定义替换功能直接放到进阶设置里面呢，这样添加词语更快更方便。

1.8.3 优化了富文本翻译对词语替换的效果。看未来反馈OK的话，可能会考虑放出来

**Comment by hyhy01** [comment]
我是希望翻译epub这些文档的时候导入术语表
