### ISSUE TITLE
翻译内容显示效果

### ISSUE THREAD

**Issue by FistChina** [immersive-translate/immersive-translate#912]
### 您希望的更新和改进是什么 | Update or Improve

我希望可以在设置中选择覆盖原文的方式显示翻译，鼠标悬浮+快捷键，气泡方式显示原文

### 补充说明 | Additional context

翻译内容会改变网站的篇幅，有些网站可能会出现排版混乱，希望使用替换原文的方式翻译可以解决这个问题

**Comment by theowenyoung** [comment]
由于我们还没有解决译文保留原文格式的问题，所以覆盖的方式对很多网页体验都会很差，建议寻找支持该功能的其他同类插件。
