### ISSUE TITLE
希望不默认启用三次空格键自动翻译

### ISSUE THREAD

**Issue by oxygen-dioxide** [immersive-translate/immersive-translate#913]
### 您希望的更新和改进是什么 | Update or Improve

希望不默认启用三次空格键自动翻译，因为这个功能对于不知情的用户来说容易误触，且难以发现原因

### 补充说明 | Additional context

我经常在Github Wiki上面进行编辑，经常需要表格排版或者yaml排版，需要连续输入空格。但是有一天在一篇英文文档中长按空格的时候，输入了几个空格就突然开始转圈圈，然后把我之前的输入打断。由于我的文档本来就是英文的，所以文本没有变，但是总是打断我的输入，就很奇怪。

我一开始不知道是怎么回事。此后我一直都是在记事本里面打好空格，复制粘贴进来，这样大概用了有几个月，非常烦人。

后来我在编辑一篇中文文档的时候，这一行为又出现了，并把我的文字翻译成英文。我才知道应该是某个软件提供的翻译功能，[但是网上仍然搜不到](https://www.google.com/search?q=github%E9%95%BF%E6%8C%89%E7%A9%BA%E6%A0%BC%E8%87%AA%E5%8A%A8%E7%BF%BB%E8%AF%91)，

<img width="517" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/54425948/8e21c3df-3636-4ba0-aec4-a754e9cbb274">

后来今天终于有时间想看看到底是怎么回事，就一个一个插件关闭，逐个排查（装了几十个插件），最终才找到是immersive-translate插件，然后才在设置项里面找到关闭的方法。

其实找到关闭方法之后回过头来看，这个设计貌似很合理，可以在设置项里面打开和关闭，对于有需要的用户来说很方便。但是我之前一直在不知情的情况下用着，很难把这一行为和“immersive-translate插件”，“翻译”，以及“快速点击三次空格”这个具体的触发条件联系起来，思维总是往错误，甚至离谱的方向想。我甚至还想过是不是Github和Edge的功能，差点去给它们提交反馈了。

**Comment by oxygen-dioxide** [comment]
或者也可以改成：当用户安装这个插件后，默认触发这个功能时，在页面上显示一个提示框：“Immersive Translate插件已将你的文本翻译成英文”，并提供三个按钮：“撤销”、“了解更多”和“不再提示”。如果用户点击“了解更多”，则跳转到对应的设置页面。如果用户点击“不再提示”，则以后不再显示这个提示框。

这样有助于用户发现这一行为来自Immersive Translate插件，而且为不需要该功能的用户提供了快速关闭的入口。

**Comment by imestar712** [comment]
最近在线编辑文档时偶尔遇到莫名其妙被翻译，尤其是修改长文档时，会整页乱掉。还以为是浏览器的问题，居然在这里找到了原因！

**Comment by theowenyoung** [comment]
感谢反馈，下个版本将会在首次触发的时候强提示 提醒用户～
