### ISSUE TITLE
增加对google bard的支持

### ISSUE THREAD

**Issue by evelynEdison** [immersive-translate/immersive-translate#915]
### 您希望的更新和改进是什么 | Update or Improve

增加对google bard的支持

**Comment by myh66** [comment]
> ### 您希望的更新和改进是什么 | Update or Improve
> 增加对google bard的支持
> 
> ### 补充说明 | Additional context
> 补充说明 |额外的背景信息
> _No response 没有反应_

实测能用
![image](https://github.com/immersive-translate/immersive-translate/assets/53999290/307b3878-be6b-4b26-9e0f-cf90b32cd4bf)

**Comment by evelynEdison** [comment]
我是说在翻译服务中增加google bard,你误解我的意思了

**Comment by myh66** [comment]
> 我是说在翻译服务中增加google bard,你误解我的意思了

知道了，但是我刚刚查了一下啊，Google Brad还没有开放api申请，除开调用本地的账号对话，但是这样应该很慢吧

**Comment by theowenyoung** [comment]
Bard 目前没有API，所以目前无法支持。

palm2 目前还有很多限制，还不太适合翻译的高频请求：

> The APIs are currently in limited general availability. You may use them for production use but Google may enforce rate limits during this period.
