### ISSUE TITLE
[Bug]: 点击翻译后不显示译文

### ISSUE THREAD

**Issue by fengurt** [immersive-translate/immersive-translate#918]
### 插件版本号 | Version

0.91

### 平台 | Platform

Windows, macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/24559862/64541f99-90ff-4419-ad5f-882889b997cd)

### 出现问题的网址 | URL

https://hz49mi2hq5.feishu.cn/docx/RuUKdZIyMoHXOlxSVfcckCf4nXf

### 补充说明 | Additional context

自从手贱点了翻译到底部，就再也没显示过 双语内容

**Comment by FattySpring** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/25144301/d654d820-45a9-4770-bc95-fc84eb68ed3a)

飞书文档阅读模式下才可以翻译
