### ISSUE TITLE
希望增加OpenAI翻译的timeout时长设定

### ISSUE THREAD

**Issue by qyhfrank** [immersive-translate/immersive-translate#919]
### 您希望的更新和改进是什么 | Update or Improve

在翻译PDF时，“每次请求最大文本长度”和“每次请求最大段落数”设置会影响翻译引擎对上下文的理解，所以较优的选项是在翻译PDF时通过增大这些设置并放弃即时翻译来获得更好的翻译效果。但是，目前的实现可能设置了请求的timeout时长（或是没有显式设定并fallback到默认值），导致在较大的“每次请求最大文本长度”时翻译就会失败。已经测试过调小该选项翻译就能成功。

**Comment by theowenyoung** [comment]
目前默认的超时时间 被设置为 120秒，下个版本调整为 300s，这样应该够了？

**Comment by qyhfrank** [comment]
感谢回复，300s应该够了，如果未来能作为可配置的开发者选项就更好了。
