### ISSUE TITLE
技术文档（Scheme）部分内容翻译错乱

### ISSUE THREAD

**Issue by danielesk** [immersive-translate/immersive-translate#92]
翻译地址：https://www.scheme.org/schemers/

![image](https://user-images.githubusercontent.com/10652829/217140885-c22e2d7c-1fd0-4fd3-91f1-374d6928e35f.png)

**Comment by theowenyoung** [comment]
<img width="890" alt="Screenshot 2023-02-07 at 11 29 04" src="https://user-images.githubusercontent.com/62473795/217141161-282ac821-6fcf-485a-973c-4e5995d33a1e.png">

我这谷歌正常，你的事什么翻译服务

**Comment by danielesk** [comment]
@theowenyoung 腾讯交互翻译

**Comment by theowenyoung** [comment]
那这是腾讯翻译服务返回的译文... 这个没办法..

**Comment by danielesk** [comment]
@theowenyoung 好的
