### ISSUE TITLE
对这类文本文件翻译不佳

### ISSUE THREAD

**Issue by ceeeeeeeeeeeeeeeeb** [immersive-translate/immersive-translate#920]
### 您希望的更新和改进是什么 | Update or Improve

[Bracket-C3D20R.txt](https://github.com/immersive-translate/immersive-translate/files/12560006/Bracket-C3D20R.txt)
[Job-2.txt](https://github.com/immersive-translate/immersive-translate/files/12560104/Job-2.txt)

会有许多行作为整体进行翻译了，最后的译文挤在一块了，看起来很不方便

**Comment by theowenyoung** [comment]
txt 的换行识别 目前被设置为 中间有真正的空行，才作为一个段落。

这是一种权衡，大多数TXT文件都是以两个 \n\n 作为真正的换行。
