### ISSUE TITLE
[Bug]: Tampermonkey + 沉浸式翻译 无限转圈

### ISSUE THREAD

**Issue by tshu-w** [immersive-translate/immersive-translate#921]
### 插件版本号 | Version

0.9.1

### 平台 | Platform

macOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

Safari + Tampermonkey v0.9.1 无限转圈，+ Userscripts 或者 浏览器插件正常
抓包翻译请求已返回
<img width="1402" alt="Screenshot 2023-09-09 at 15 15 00" src="https://github.com/immersive-translate/immersive-translate/assets/13161779/dbd4ea0b-a7e8-4e8c-a536-0087c443d2b0">

### 出现问题的网址 | URL

https://bun.sh/blog/bun-v1.0

### 重现步骤 | To Reproduce

1. 重置所有设置
2. 翻译

**Comment by theowenyoung** [comment]
tamper monkey 的safari版本有点旧，建议使用 其他油猴插件，比如 Userscript 或者 Stay。

或者直接使用沉浸式翻译的官方 Safari插件： https://immersivetranslate.com/

**Comment by tshu-w** [comment]
userscripts 在一些脚本上也有问题，我用官方插件了
