### ISSUE TITLE
[Bug]: github新版home页面不会智能翻译

### ISSUE THREAD

**Issue by Pa55w0rd** [immersive-translate/immersive-translate#923]
### 插件版本号 | Version

最新

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

github新版home页面不会智能翻译

### 出现问题的网址 | URL

https://github.com/

### 重现步骤 | To Reproduce

githubhome页面更新后，翻译主要区域时，home页面项目介绍不会翻译

**Comment by theowenyoung** [comment]
有截图吗？我这里似乎正常？

<img width="933" alt="图片" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/a6a9df71-57cb-4a10-b70e-94e0ccab4f7f">

**Comment by Pa55w0rd** [comment]
> 有截图吗？我这里似乎正常？
> 
> <img alt="图片" width="933" src="https://user-images.githubusercontent.com/62473795/267258102-a6a9df71-57cb-4a10-b70e-94e0ccab4f7f.png">

咱们两个布局不是一样的，我的github是前几天变化的布局，之前我标红框的部分是会自动翻译的
![image](https://github.com/immersive-translate/immersive-translate/assets/16274549/87a5e022-9995-4b3b-b732-03e0e285304f)

**Comment by keyboard3** [comment]
已修复 刷新下
