### ISSUE TITLE
[Bug]: 鼠标悬停后按键翻译段落貌似对mac键盘支持不太灵？

### ISSUE THREAD

**Issue by prof-yang** [immersive-translate/immersive-translate#924]
### 插件版本号 | Version

0.9.3

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

悬停之后+shift可以实现翻译段落，但是会和搜狗的中英文切换冲突，如果设置成+alt和+ctrl按了又没反应并不会自动翻译？请问怎么能设置+command或者+option呀？

**Comment by prof-yang** [comment]
我之前悬停+shift是可以翻译的，好像插件更新之后就不行了，然后command和option要怎么设置呢？我在自定义按键里写+command或者+option没用

**Comment by theowenyoung** [comment]
没法复现.. 我这似乎挺灵感的啊...

**Comment by theowenyoung** [comment]
#935

**Comment by ZhangTianCi** [comment]
我可以用，但是有些元素会失灵。如图红框内：

<img width="1324" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/10275488/ecb20e98-86ed-4d66-9d2b-5a793caa8b83">

**Comment by theowenyoung** [comment]
红框里的是 中英夹杂，由于中文的字数更多，所以被判断为中文了。不翻译是正常的。

**Comment by ZhangTianCi** [comment]
Thank you for your answer.&nbsp;





------------------ 原始邮件 ------------------
发件人: Owen ***@***.***&gt;
发送时间: 2023年11月3日 19:15
收件人: immersive-translate/immersive-translate ***@***.***&gt;
抄送: 张天赐 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [immersive-translate/immersive-translate] [Bug]: 鼠标悬停后按键翻译段落貌似对mac键盘支持不太灵？ (Issue #924)





 
红框里的是 中英夹杂，由于中文的字数更多，所以被判断为中文了。不翻译是正常的。

**Comment by xpfo-go** [comment]
> 我之前悬停+shift是可以翻译的，好像插件更新之后就不行了，然后command和option要怎么设置呢？我在自定义按键里写+command或者+option没用

大佬解决了吗 我也想设置command

**Comment by FattySpring** [comment]
> 我之前悬停+shift是可以翻译的，好像插件更新之后就不行了，然后command和option要怎么设置呢？我在自定义按键里写+command或者+option没用

![image](https://github.com/immersive-translate/immersive-translate/assets/25144301/fe7d6a11-9bc6-4933-8710-02bdbfc68fec)

我这里这样设置是可以的，如果想 command 触发，不需要前面的 “+”

**Comment by FattySpring** [comment]
> > 我之前悬停+shift是可以翻译的，好像插件更新之后就不行了，然后command和option要怎么设置呢？我在自定义按键里写+command或者+option没用
> 
> 大佬解决了吗 我也想设置command


![image](https://github.com/immersive-translate/immersive-translate/assets/25144301/fe7d6a11-9bc6-4933-8710-02bdbfc68fec)

我这里这样设置是可以的

**Comment by theowenyoung** [comment]
自定义coomand 直接在快捷键里输入： `command` 即可。

另外最新版新增了一个额外的选项，你可以自定义一个组合键，比如 `alt+e`, 这种情况下，会在当前页面临时开启一个鼠标滑过直接翻译，再次按下则会取消该行为。这样的话就不用一直按键了。
