### ISSUE TITLE
scispace 插件对话框 无法 三次空格键 激活翻译

### ISSUE THREAD

**Issue by InnocenseYu** [immersive-translate/immersive-translate#925]
### 您希望的更新和改进是什么 | Update or Improve

[scispace](https://typeset.io/) 的 [chrome 插件](https://chrome.google.com/webstore/detail/scispace-copilot/cipccbpjpemcnijhjcdjmkjhmhniiick) 对话框，输入内容后，三次空格键 连击，无法自动翻译

![image](https://github.com/immersive-translate/immersive-translate/assets/103131176/c1c04b10-ff44-4896-900b-a86aa96545c1)

**Comment by FattySpring** [comment]
不能在其他插件内无法使用， 可以在网页中使用
