### ISSUE TITLE
H5模式下的悬浮球增加开关

### ISSUE THREAD

**Issue by dove-xk** [immersive-translate/immersive-translate#926]
### 您希望的更新和改进是什么 | Update or Improve

启用开发者工具F12，模拟移动设备时，会出现悬浮球，这个有时候会影响页面显示，增加一个开关来控制是否显示更合适。

**Comment by FattySpring** [comment]
点击悬浮球，【设置】【界面设置】【在页面中显示悬浮球】即可关闭
注意：设置页面需要模拟移动设备，才会显示该选项
