### ISSUE TITLE
[Bug]: 非文本内容的翻译，带来内容的冗余和排版混乱

### ISSUE THREAD

**Issue by happyDom** [immersive-translate/immersive-translate#927]
### 插件版本号 | Version

0.8.0

### 平台 | Platform

Windows

### 浏览器 | Browsers

Other

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

有些网页有些位置的内容是非文本的，例如有一些emoji符号，现在的软件貌似把这些非文本内容也翻译了，带来了内容的冗余和版式的混乱，影响阅读体验。
![84c74041ce0eff2c1095d06bea5fdf0](https://github.com/immersive-translate/immersive-translate/assets/36214667/685d6420-fa92-4800-9e99-29eebc152f91)

### 出现问题的网址 | URL

https://github.com/pyproj4/pyproj

### 重现步骤 | To Reproduce

打开网站，打开翻译功能即可重现

### 补充说明 | Additional context

希望对于非文本内容，不进行翻译

**Comment by happyDom** [comment]
我的浏览器是 vivaldi：6.1.3035.204 (Stable channel) (准备更新至 6.2.3105.47) （64 位）

**Comment by theowenyoung** [comment]
检测每一段是否全部都是emoji 要用正则.. 稍微有一点点耗性能..

感觉这种情况也不多。要不还是不检测了。
