### ISSUE TITLE
[Feature request] YouTube 转录对照翻译

### ISSUE THREAD

**Issue by TensorABC** [immersive-translate/immersive-translate#93]
feature request：YouTube 转录对照翻译
![image](https://user-images.githubusercontent.com/95612401/217147457-ed0a831e-677e-4f58-b246-70f2ad9ea0e3.png)
创建一个适用于YouTube转录功能翻译的规则

**Comment by theowenyoung** [comment]
@bxb100 之前是不是研究过这个～
