### ISSUE TITLE
[Bug]: 关于pdf翻译的问题

### ISSUE THREAD

**Issue by duoluodexiaoxiaoyuan** [immersive-translate/immersive-translate#931]
### 插件版本号 | Version

0.9.3

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 请描述这个Bug | Describe the bug

1.首先是点击插件，然后点击更多，我选择翻译本地pdf文件，这个时候会给一个demo
根据效果我有一些疑问，给出的demo似乎没有判断我需要识别目标语言是哪一个，直接就翻译为了英语，我不知道是否进行了判断
![image](https://github.com/immersive-translate/immersive-translate/assets/59086082/96161a44-dc6f-4e4a-ade3-f6bdd3efa44f)

2.然后我开始导入我要读的pdf
这个时候根据测试，我发现确实是读到了我选择的目标语言。没什么问题。
![image](https://github.com/immersive-translate/immersive-translate/assets/59086082/f9c557b0-405a-461f-b397-576634e7bd21)
然后我就开始随意切换目标语言，刚开始几次还正常，后面不管我再怎么切换，都没反应了，我不确定是否是代码的问题，因为我写的pdf是很简单的，如果是复杂的应该可以想到是很难使用的。

写完上面这段话，然后又试了几遍，发现就是又正常了，这种问题说实话感觉真的很难测试，调用翻译接口，翻译的短语太短，我感觉哪些原因都有可能，只是因为今天遇到了，所以想完整的分享出来。希望对大佬测试有用。

3.然后我开始导入我写好的另一个文件，之前导入没有成功覆盖，但是这次又成功了，上次并不是幻觉，所以我不确定是什么原因导致的。
![image](https://github.com/immersive-translate/immersive-translate/assets/59086082/12c0f9c7-ccb0-41c5-8f45-966f8d582c08)

上面的内容是无法翻译为英语的
```md
精通  HTML5，CSS3，JavaScript（ES6）,熟练使用 ES6 推出的新特性。熟练使用 Ajax
进行前
后台交互，理解 get，post 请求区别，深入理解 JavaScript 中的事件机制，JavaScript
中的闭
包，了解面向对象编程。
熟练使用 React，掌握 React-router，redux 等相关技术栈，深入理解 React 中的组件
实例三
大属性，组件生命周期，可以配合 ECharts 做基本的数据可视化管理平台，有封装代码
的习惯。
熟练使用 Vue2，Vue3，深入理解 Vue2，Vue3 响应式原理及区别，使用 Vue-cli 脚手
架快速
搭建 Vue 前端项目框架，熟练使用 vue 相关插件，vuex 状态管理，vue- router 路由
控制，
配合 elementUI 实现模块化基础组件，完成项目的快速落地上线。
熟练使用 ElementUI,Vant,Antd 等 UI 组件库，有自己封装组件的习惯。
熟练使用 git 来进行版本管理，将文件推送到仓库中，如何查看提交的历史记录，以及
如何创
建、查看、删除分支。
基本掌握微信小程序的开发，搭建原生小程序项目，熟练使用微信小程序开发工具，了
解小程
序开发的结构机制，并且能够完成简单应用开发。

```
![image](https://github.com/immersive-translate/immersive-translate/assets/59086082/9f68a97e-5103-46c8-b767-4ba602b7a7be)
但是我发现别的语言是ok的

如果这一块功能做的完美，任何简历可以翻译为不同语言，相信又是一个吸引人的功能。

后面如果有机会还测试出问题，我还是会继续分享到这个下面。

**Comment by theowenyoung** [comment]
抱歉，很晚才回复。

第一个问题，我这边测试是正常翻译为意大利语的，你试下最新的版本？

<img width="1587" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/e0cf4bd8-0c86-495e-8545-1b0af178a603">

> 然后我就开始随意切换目标语言，刚开始几次还正常，后面不管我再怎么切换，都没反应了

如果没反应，可以刷新下页面。

> 上面的内容是无法翻译为英语的

可以附件上传下pdf吗？我们看看。

**Comment by keyboard3** [comment]
目前看下来是正常工作的，暂时关闭此issue。如果有进展可以重开
