### ISSUE TITLE
[Bug]: 特定网页显示支离破碎

### ISSUE THREAD

**Issue by hidaris** [immersive-translate/immersive-translate#932]
### 插件版本号 | Version

0.9.3

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/8336146/ed55f04a-d335-4144-ab9d-bce15f5135ea)

### 出现问题的网址 | URL

https://resources.github.com/devops/

### 重现步骤 | To Reproduce

打开链接，点击翻译

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/f7403839-26c6-47d5-993c-fcaebb206302)
正常的呀，你是不是有什么其他插件影响到了

**Comment by hidaris** [comment]
找到原因了，我改了翻译的提示语，所以模型回答了文章的标题，然后白色的大号字体遮挡了下面的文字，观感上就变成了这种破碎感。。
