### ISSUE TITLE
[Bug]: Orion 浏览器无法登录

### ISSUE THREAD

**Issue by boobb** [immersive-translate/immersive-translate#937]
### 插件版本号 | Version

0.9.3

### 平台 | Platform

iOS

### 浏览器 | Browsers

Other

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在iOS上使用Orion 浏览器使用插件后遇到无法登录问题

### 出现问题的网址 | URL

chrome-extension://bpoadfkcbjbfhfodiogcnhhhpibjhbnh/options.html#general

### 重现步骤 | To Reproduce

1️⃣安装浏览器[https://apps.apple.com/us/app/orion-browser-by-kagi/id1484498200?l=zh-Hans-CN](url)

2️⃣在chrome插件商店安装沉浸式翻译插件[https://chrome.google.com/webstore/detail/immersive-translate/bpoadfkcbjbfhfodiogcnhhhpibjhbnh](url)

3️⃣在Orion浏览器进入设置登录账号

4️⃣点击【登录】后无法显示登录弹窗

**Comment by versun** [comment]
我这边试了下可以的哈，也是用的Chrome插件， 安装完要完全退出app后再打开。
如果还不行的话，试一试安装Firefox的插件
