### ISSUE TITLE
【改进？】以chrome-extension://... 开头的非普通网页页面的无法翻译

### ISSUE THREAD

**Issue by Freddd13** [immersive-translate/immersive-translate#938]
### 您希望的更新和改进是什么 | Update or Improve

FeedBro RSS使用者，这个插件会打开形如 `chrome-extension://mefgmmbdailogpfhfblcnnjfmnpnmdfa/reader.html` 的网页，里面显示订阅内容，测试发现无法在这个页面开启翻译。请问能否解决此问题？

### 补充说明 | Additional context

![image](https://github.com/immersive-translate/immersive-translate/assets/50367552/04f1abf7-0106-4a20-a1ab-95b1a1f968ed)

**Comment by keyboard3** [comment]
插件无法翻译插件的
