### ISSUE TITLE
[Bug]: australian 澳洲新闻网站翻译问题

### ISSUE THREAD

**Issue by lailujiang** [immersive-translate/immersive-translate#939]
### 插件版本号 | Version

0.5.5

### 平台 | Platform

Android

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

The australian， the advertiser这两个澳洲主流新闻网站都不能正常使用翻译功能，经常翻译不了

**Comment by keyboard3** [comment]
升级下版本 版本最新到0.9.3了。 还有这两个网站地址完整发下

**Comment by lailujiang** [comment]
https://www.theaustralian.com.au/
https://www.adelaidenow.com.au/

keyboard3 ***@***.***> 于 2023年9月17日周日 00:54写道：

**Comment by theowenyoung** [comment]
我这似乎无法打开这两网站。直连和梯子都不行...

<img width="1304" alt="图片" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/548c1298-f044-4251-936f-11d71e137d7a">

**Comment by keyboard3** [comment]
我Firefox浏览器用最新的0.9.8 正常翻译
