### ISSUE TITLE
已经有authKey，但Deepl一直翻译失败。

### ISSUE THREAD

**Issue by Axlax336** [immersive-translate/immersive-translate#94]
![image](https://user-images.githubusercontent.com/76145935/217162268-b3d4285e-f241-48c0-9238-50e27207366b.png)

**Comment by theowenyoung** [comment]
尝试重新生成一个key试试？

之前有用户的key是以前生成的，好像现在不兼容了。

free api key需要以 `:fx` 结尾

**Comment by Axlax336** [comment]
我重新生成的key，都是数字结尾的。

**Comment by theowenyoung** [comment]
你的是 free api吗？ 你是不是用错了 pro 账户？ pro账户里的key 是cat工具的key，不是api key

**Comment by Axlax336** [comment]
好吧，我以为是同一个key。感谢解答。
