### ISSUE TITLE
建议加入按需翻译

### ISSUE THREAD

**Issue by cbingb666** [immersive-translate/immersive-translate#942]
### 您希望的更新和改进是什么 | Update or Improve

原因：在浏览一些 github awesome 仓库的时候，通常有大量文本，我直接滚动到需要浏览的部分后开启翻译，基本都要几十秒钟后才能翻译到我需要的部分

建议：
添加按需翻译，及优先翻译可视区域的文本，之后在翻译其他文本

**Comment by theowenyoung** [comment]
可以启用 鼠标悬停翻译功能？

<img width="305" alt="图片" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/8f095696-d799-4a31-8e91-0929bda9fc0a">
