### ISSUE TITLE
[Bug]: 0.9.4 电子书阅读功能坏掉了

### ISSUE THREAD

**Issue by hidaris** [immersive-translate/immersive-translate#943]
### 插件版本号 | Version

0.9.4

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在新的电子书地址点击翻译后，并不会进行文本的翻译，0.9.3还是可以的，在edge也复现了一样的问题

### 重现步骤 | To Reproduce

点击更多，阅读本地电子书，打开一个epub文件，点击翻译

**Comment by theowenyoung** [comment]
是不是epub的问题？ 我这测试是ok的。分享一下 epub？

**Comment by landfreedom45** [comment]
我也遇到同样问题，10个小时前看还是好的，现在epub格式就翻译不了。

**Comment by keyboard3** [comment]
这是个bug修好了 0.9.5 正在发

**Comment by hidaris** [comment]
已确认修复。
