### ISSUE TITLE
输入框增强能否改为类似于DeepL插件那样在输入框显示浮标，点击浮标后进行翻译

### ISSUE THREAD

**Issue by meowlgm** [immersive-translate/immersive-translate#944]
### 您希望的更新和改进是什么 | Update or Improve

如下图deepl的Chrome拓展这种，还可以点击图标选择目标语言，感觉比3连击某个键盘按键方便多了
<img width="647" alt="2023-09-17_211700" src="https://github.com/immersive-translate/immersive-translate/assets/81202884/92a9634a-0edb-4cd0-892e-7238c91761c0">

### 补充说明 | Additional context

另外如果可以指定个别词语不被翻译就更好了，比如对不想翻译的词语加上一个标识：
这是非常受年轻人喜爱的/小红书/应用。
翻译后变为：
This is a very popular 小红书 app among young people.

**Comment by theowenyoung** [comment]
目前这个插件不太愿意侵入用户的界面。所以采用了更加隐蔽，但是习惯之后其实更加高效的快捷键做法。
