### ISSUE TITLE
[Bug]: pdf翻译中出现了没必要的语法检查提示

### ISSUE THREAD

**Issue by heheda123123** [immersive-translate/immersive-translate#945]
### 插件版本号 | Version

0.9.4

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

如图可以看到，翻译的内容中产生了红色的波浪下划线，这些本来是没有的。只要我点了一下这块内容就出现了，而且一直不会消失
![image](https://github.com/immersive-translate/immersive-translate/assets/97490782/0194bd68-bd62-497c-84af-823e5c166fbf)
pdf
[testpdf.pdf](https://github.com/immersive-translate/immersive-translate/files/12642986/testpdf.pdf)

**Comment by FattySpring** [comment]
我这边试了是没有问题的，检查下是不是其他扩展引起的
