### ISSUE TITLE
[Bug]: exclude无效；插件控制台报错

### ISSUE THREAD

**Issue by hzhoup** [immersive-translate/immersive-translate#946]
### 插件版本号 | Version

0.9.4

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

配置exclude规则禁用localhost无效，插件有其他报错

![image](https://github.com/immersive-translate/immersive-translate/assets/109516832/b826b4ae-e860-43d0-b4c1-18f85a860194)

![image](https://github.com/immersive-translate/immersive-translate/assets/109516832/9f515bcd-a13c-465f-9d72-555f2d87c7c1)

### 出现问题的网址 | URL

http://localhost:3000/

**Comment by theowenyoung** [comment]
感谢反馈，将在 0.9.7 版本修复。
