### ISSUE TITLE
建議翻譯成中文的時候用直角引號

### ISSUE THREAD

**Issue by siaoyi** [immersive-translate/immersive-translate#947]
### 您希望的更新和改进是什么 | Update or Improve

如：布魯⽒菌病（也稱為“起伏熱”、“地中海熱”或“⾺爾他熱”）
改為：布魯⽒菌病（也稱為「起伏熱」、「地中海熱」或「⾺爾他熱」）

### 补充说明 | Additional context

在簡體中文環境使用逗點引號多，但也可以使用直角引號。在傳統中文（Traditional Chinese）則直角引號使用非常普遍。建議翻譯目標語言為中文的時候使用直角符號，比較美觀。李如一先生曾因此發過倡議，現簡體中文環境也越來越多使用了直角引號。

**Comment by keyboard3** [comment]
這個是翻譯服務控制的，我們無法干預
