### ISSUE TITLE
[Bug]: Chrome下PDF进行翻译，但是原文件和翻译页面被旋转90°

### ISSUE THREAD

**Issue by dehuanxiong** [immersive-translate/immersive-translate#948]
### 插件版本号 | Version

0.9.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

Chrome下PDF进行翻译
但是原文件和翻译页面被旋转90°，且翻译字符出现重叠和串行
该问题仅出现在PDF翻译首页和某个PDF文件
且出现问题的文件在此前的使用中完全正常

尝试过以下操作，但未果

1、清空插件缓存，并重开浏览器，无法解决
2、PDF文件重新下载，无法解决

但是，在Edge中，一切正常

考虑可能存在键鼠误触，而使浏览器页面缩放，进而导致上述问题。
因此尝试重置PDF翻译页面的缩放比例为100%，依然无法解决该问题。

目前暂无办法解决

### 出现问题的网址 | URL

https://app.immersivetranslate.com/pdf/

### 重现步骤 | To Reproduce

![FireShot Capture 013 - sample-pdf - compressed tracemonkey-pldi-09 pdf --- sample-pdf - comp_ - app immersivetranslate com](https://github.com/immersive-translate/immersive-translate/assets/40299905/2d725ffa-90d0-45d0-b306-9bca0fe0a11f)
![FireShot Capture 012 - POLS 7101 - POLS7101 COURSE-LEARNING-GUIDE-S2, 2023 pdf --- POLS 7101_ - app immersivetranslate com](https://github.com/immersive-translate/immersive-translate/assets/40299905/80570451-d4f5-42c8-bdb0-591ce6396ad4)

### 补充说明 | Additional context

无

**Comment by FattySpring** [comment]
![2a1b62ad474242738ca761f86b46245](https://github.com/immersive-translate/immersive-translate/assets/25144301/96709556-488b-441d-b775-0dcbf55688e9)

调整【顺时针旋转】或 【逆时针旋转】将原文恢复原样，刷新即可

**Comment by dehuanxiong** [comment]
成功解决！
史诗级拯救！
手残党的救星！！！
