### ISSUE TITLE
能支持翻译chrome的实时字幕吗

### ISSUE THREAD

**Issue by heheda123123** [immersive-translate/immersive-translate#950]
### 您希望的更新和改进是什么 | Update or Improve

chrome提供了实时字幕功能，能自动识别视频里的语音，显示为字幕
![image](https://github.com/immersive-translate/immersive-translate/assets/97490782/dcd56819-f147-4f76-8509-241bfcbb2382)
效果非常不错
![image](https://github.com/immersive-translate/immersive-translate/assets/97490782/542afa16-2e77-446b-aa5f-4cd8f7e7d051)
能支持翻译这些字幕吗？

**Comment by keyboard3** [comment]
Chrome的实时字幕是系统组件，插件没有权限访问。
