### ISSUE TITLE
[Bug]: Unable to export the translated epub

### ISSUE THREAD

**Issue by Tuscan-blue** [immersive-translate/immersive-translate#952]
### 插件版本号 | Version

0.9.7

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

After clicking the export button, it continuously displays "Exporting" on the button and the download has never started.
![image](https://github.com/immersive-translate/immersive-translate/assets/141131070/0a892b71-24b9-4d8c-8dca-80f9a6dc16ad)

### 出现问题的网址 | URL

https://app.immersivetranslate.com/ebook/make

### 重现步骤 | To Reproduce

1. Go to https://app.immersivetranslate.com/ebook/make/
2. Choose a file
3. Click the export button

**Comment by keyboard3** [comment]
这个bug已修复，再试下
