### ISSUE TITLE
翻译列表时希望能按照原文那样对齐

### ISSUE THREAD

**Issue by heheda123123** [immersive-translate/immersive-translate#953]
### 您希望的更新和改进是什么 | Update or Improve

原文是这样
![image](https://github.com/immersive-translate/immersive-translate/assets/97490782/7d5f619d-8e1c-4c9e-bb2d-e4915d0123d8)

翻译后如图，一些翻译内容是换行，一些是放在同一行，最好统一一下，不然内容多的时候看起来有点混乱
![image](https://github.com/immersive-translate/immersive-translate/assets/97490782/aed316c6-0adc-46d9-851c-6cca007a2f5d)

链接
https://github.com/marticliment/WingetUI/releases

**Comment by theowenyoung** [comment]
抱歉，回复的较晚，【进阶设置】里有一个选项可以调整为【总是换行】

<img width="1258" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/a934dc5b-fd83-4ad7-b4ab-b7abf0b607cc">
