### ISSUE TITLE
希望有快捷键能够强制刷新某个页面的翻译

### ISSUE THREAD

**Issue by jiangying000** [immersive-translate/immersive-translate#954]
### 您希望的更新和改进是什么 | Update or Improve

翻译之后有缓存
希望有快捷键能够强制刷新某个页面的翻译，比如 alt+shift+z，能够跳过缓存，重新翻译

**Comment by theowenyoung** [comment]
很好的建议～ 将会在快捷键重构的时候支持。

**Comment by theowenyoung** [comment]
再确认一下，跳过缓存的原因是？

是因为openai 修改了prompt之后 依然使用缓存的问题吗？

这个算是一个 bug，openai的翻译缓存应该要把 prompt和模型考虑在内。

**Comment by jiangying000** [comment]
是因为openai 修改了prompt/模型之后 依然使用缓存

**Comment by theowenyoung** [comment]
好的，那么这个问题可以通过优化openai的缓存问题来解决。

**Comment by theowenyoung** [comment]
1.1.0 版本已修复了openai的缓存问题哈。
