### ISSUE TITLE
[Bug]: 翻译侧的图片要模糊一些

### ISSUE THREAD

**Issue by heheda123123** [immersive-translate/immersive-translate#955]
### 插件版本号 | Version

0.9.8

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

任意找一个包含图片的pdf，翻译后看右侧，会发现图片明显比左边更模糊
![image](https://github.com/immersive-translate/immersive-translate/assets/97490782/ddf6ce7a-37fb-40f1-96e1-928151964155)

**Comment by lpkf2018** [comment]
我也多次遇到这种问题，保存后的PDF文件右侧翻译的内容不仅模糊，而且颜色很浅，显示器上是正常的

![显示器的效果](https://github.com/immersive-translate/immersive-translate/assets/38097560/1cd0da89-3b62-47b1-a808-09e0cf7fad7e)
![翻译效果截图](https://github.com/immersive-translate/immersive-translate/assets/38097560/9e80fa34-0e92-4c44-9ffb-72764b531a53)

**Comment by keyboard3** [comment]
右侧图片已优化会比原来清晰2倍，理论上会更加清晰一点。不过清晰度越高，会导致导出pdf越大

**Comment by keyboard3** [comment]
> 我也多次遇到这种问题，保存后的PDF文件右侧翻译的内容不仅模糊，而且颜色很浅，显示器上是正常的
> 
> ![显示器的效果](https://private-user-images.githubusercontent.com/38097560/293963281-1cd0da89-3b62-47b1-a808-09e0cf7fad7e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNDA2MDIsIm5iZiI6MTcwODM0MDMwMiwicGF0aCI6Ii8zODA5NzU2MC8yOTM5NjMyODEtMWNkMGRhODktM2I2Mi00N2IxLWE4MDgtMDllMGNmN2ZhZDdlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDEwNTgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkOGJmNWI1ZDlhMDk0YmJlNTE1NjUxYmIyZjY4OTE3OWZmMmI0MTAyZWJlMjljODVhYmNjZmNhM2VmMDUwMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fnNVLLNbNucAzeJQJS4auaKSGfC3ELvwQzCkpdSTDnA) ![翻译效果截图](https://private-user-images.githubusercontent.com/38097560/293963323-9e80fa34-0e92-4c44-9ffb-72764b531a53.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNDA2MDIsIm5iZiI6MTcwODM0MDMwMiwicGF0aCI6Ii8zODA5NzU2MC8yOTM5NjMzMjMtOWU4MGZhMzQtMGU5Mi00YzQ0LTlmZmItNzI3NjRiNTMxYTUzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDEwNTgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0N2EwNTI1MTZiOTg2MTUyMTM3MWJkNmZjMzc2YjUyODM4OTk5ZGU5MDQ2MjhjY2EyODc3MWQ1ZmVhMGU0NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c85xDlWnbtm6sfzwQFKLI-0waDSRGix5D3OaMnAZJBk)

可以给个文件我们复现下
