### ISSUE TITLE
[Bug]: youtube视频标题翻译还是上一次视频的翻译

### ISSUE THREAD

**Issue by ice-ko** [immersive-translate/immersive-translate#956]
### 插件版本号 | Version

0.9.6

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![微信截图_20230923200517](https://github.com/immersive-translate/immersive-translate/assets/20471045/ce7af92d-aae0-4362-a8fa-421d80175169)
视频标题是上一次这个位置的视频标题翻译，必须刷新浏览器才会更新翻译

### 出现问题的网址 | URL

https://www.youtube.com/

### 重现步骤 | To Reproduce

点击左上角youtube Logo刷新数据出现这种情况

**Comment by keyboard3** [comment]
YouTube网站在刷新数据的时候会复用节点，暂时无法检测这种情况进行重翻，建议遇到这种情况点击插件重新翻一下就可以了
