### ISSUE TITLE
[Bug]: 【插件设置】【UI】【UI按钮绑定】点击 全选文本（永不翻译的网址） 错误绑定至 总是翻译的网址的全选

### ISSUE THREAD

**Issue by popu-web** [immersive-translate/immersive-translate#957]
### 插件版本号 | Version

0.9.8

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

点击 全选文本（永不翻译的网址） 错误绑定至 总是翻译的网址的全选

![image](https://github.com/immersive-translate/immersive-translate/assets/56524751/80cdde7e-e886-4873-b63c-8e3b42c2f0ce)

### 出现问题的网址 | URL

chrome-extension://bpoadfkcbjbfhfodiogcnhhhpibjhbnh/options.html#general

### 重现步骤 | To Reproduce

插件设置 - 基本设置 - 永不翻译的网址 - 全选[非复选框] -  点击 全选文本（永不翻译的网址） 错误绑定至 总是翻译的网址的全选

**Comment by keyboard3** [comment]
奇怪 一样的版本，我这chrome没有复现出来

**Comment by popu-web** [comment]
再次尝试，更换edge，一样的；
注意点击的是全选文字非复选框；
<img width="202" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/56524751/4350987e-76f1-4c48-883a-20a16102226e">

**Comment by keyboard3** [comment]
哦哦 发现了

**Comment by keyboard3** [comment]
修复，下个版本发

**Comment by popu-web** [comment]
另外还有一个问题
![image](https://github.com/immersive-translate/immersive-translate/assets/56524751/ffff1c54-3822-4ea4-b659-9a7ef93f60b0)
