### ISSUE TITLE
[Bug]: 高亮插件兼容问题

### ISSUE THREAD

**Issue by xxhk-org** [immersive-translate/immersive-translate#959]
### 插件版本号 | Version

0.9.8

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在使用 Highlight 一类插件选中文字时就会出现，这个问题由来已久。 比如 https://chrome.google.com/webstore/detail/web-highlights-pdf-web-hi/hldjnlbobkdkghfidgoecgmklcemanhm 和 https://chrome.google.com/webstore/detail/super-simple-highlighter/hhlhjgianpocpoppaiihmlpgcoehlhio

**Comment by keyboard3** [comment]
第一个web-hightlight插件已经适配了，第二个之前就适配过了呀
