### ISSUE TITLE
Google Drive同步403

### ISSUE THREAD

**Issue by wxyShine** [immersive-translate/immersive-translate#96]
![image](https://user-images.githubusercontent.com/42802152/217181802-5bcaada1-7706-4124-a488-21d3a9cf4883.png)

0.2.47

**Comment by theowenyoung** [comment]
嗯，确认，https://github.com/immersive-translate/immersive-translate/issues/81 

0.2.50 已修复。

**Comment by WangChuan0225** [comment]
![image](https://user-images.githubusercontent.com/44333360/218294368-0c894e4e-a5f5-484d-ae54-3c424041e3ab.png)
同步失败使用 google drive  版本0.2.58

**Comment by theowenyoung** [comment]
油猴吗？还是浏览器，我试了浏览器，我这是成功的。是不是网络问题呢？

**Comment by WangChuan0225** [comment]
> 油猴吗？还是浏览器，我试了浏览器，我这是成功的。是不是网络问题呢？

用的是油猴，好像是因为没有需要上传的内容，我设置了一些修改内容就可以上传了，什么都没改动就有这个同步提示
