### ISSUE TITLE
[Bug]: 字幕翻译功能，是不是没有按照设置中的API每秒请求最大个数来工作？

### ISSUE THREAD

**Issue by figozhu** [immersive-translate/immersive-translate#960]
### 插件版本号 | Version

0.9.8

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

翻译字幕的时候，大量失败。
猜测是没有按照设置中“API每秒最大请求个数”来发起调用？

![image](https://github.com/immersive-translate/immersive-translate/assets/4566514/807d90c6-ea10-4844-af04-79c9e4f404ad)

**Comment by theowenyoung** [comment]
请问使用的是什么翻译服务？理论上有做限制的～

**Comment by figozhu** [comment]
> 请问使用的是什么翻译服务？理论上有做限制的～

API2D

**Comment by theowenyoung** [comment]
OpenAI 到默认速率是 10个 每秒，你可以在设置里自助修改这个速率，你设置的是多少呢？
