### ISSUE TITLE
[Bug]: 翻译出现两个

### ISSUE THREAD

**Issue by TianyuanZhu-data** [immersive-translate/immersive-translate#963]
### 插件版本号 | Version

0.9.8

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

开启了自动翻译，经常出现以下翻译出现两遍的情况：
Clearing your browser cache
清除浏览器缓存

清除浏览器缓存

### 出现问题的网址 | URL

codecademy.com

### 重现步骤 | To Reproduce

1开启了自动翻译，随便打开网址
2经常发生：重复两次翻译现象

### 补充说明 | Additional context

在其他网站也出现过好多次

**Comment by keyboard3** [comment]
不会出现两遍的，检查下是不是跟其他插件冲突了？
