### ISSUE TITLE
[Bug]: 翻译 epub 电子书仅保留译文，行末文字显示不全

### ISSUE THREAD

**Issue by deweixu** [immersive-translate/immersive-translate#964]
### 插件版本号 | Version

0.9.8

### 平台 | Platform

macOS

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![截屏2023-09-26 22 17 01](https://github.com/immersive-translate/immersive-translate/assets/10754726/c87b118f-093c-4c3f-9973-5a1099fe6823)
如上图，使用 ebook-viewer 打开翻译导出的电子书后，行末文字显示不全

**Comment by deweixu** [comment]
![截屏2023-09-26 22 17 01](https://github.com/immersive-translate/immersive-translate/assets/10754726/913408dd-19fa-40ef-95e7-cfc9502acc4a)

**Comment by keyboard3** [comment]
已修复，你重试下看

**Comment by deweixu** [comment]
好了，感谢！
