### ISSUE TITLE
[Bug]: 0.8.0 后面的版本 翻译不完整【油猴】

### ISSUE THREAD

**Issue by YuHang-Kuo** [immersive-translate/immersive-translate#965]
### 插件版本号 | Version

0.8.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

从 0.8.1版本开始，翻译出来的内容不完整，好多直接就是原文输出。 
![0 8 00](https://github.com/immersive-translate/immersive-translate/assets/32600329/d308cb14-11da-4d56-9695-2e4288fc1397)
![0 8 0](https://github.com/immersive-translate/immersive-translate/assets/32600329/69f1e811-34c2-4194-904b-1193dd8eb1b6)
![0 8 1](https://github.com/immersive-translate/immersive-translate/assets/32600329/20c3af94-db67-443d-a04c-39f65a1c1f94)

### 出现问题的网址 | URL

https://www.youtube.com/watch?v=yxSvh2z8yxs

### 重现步骤 | To Reproduce

默认设置 只选择谷歌翻译 在0.8.0版本及以前的版本 都能正常完全翻译，0.8.1往后的版本都翻译不完整。

**Comment by keyboard3** [comment]
最新版 0.9.8 无此问题，请更新到最新版尝试

**Comment by YuHang-Kuo** [comment]
> 最新版本 0.9.8 无此问题，请更新到最新版本尝试

没有啊，我就是一直在用最新版。 一直是这样的错误 昨晚我才做的旧版本测试
最新版也是不能完全翻译  
主要是多语言情况下翻译失败 
![0 9 8](https://github.com/immersive-translate/immersive-translate/assets/32600329/f93732c3-9e39-437f-9cf7-48013b6059d0)

**Comment by keyboard3** [comment]
不好意思这么久才修复，最新版油猴已经能正常处理这种情况了
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/968fe649-ce7d-456f-91ff-6808373343fd)
