### ISSUE TITLE
[Bug]: OPENAI翻译使用自定义接口时提示网络错误。

### ISSUE THREAD

**Issue by xgalway** [immersive-translate/immersive-translate#966]
### 插件版本号 | Version

0.9.8

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome, Microsoft Edge

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

OpenAI使用自定义 API 接口地址时，提示：“网络问题，无法连接到服务，请检查你的代理或本地网络连接后重试。 Network request failed”，测试了3组不同的 API 接口地址都是同样的错误。（这三组API地址和KEY在其他软件中都能正常使用）。下面的其中一个地址：https://api.openai-hk.com

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/2936e869-c260-4a8c-91f5-1694e37f0e75)
