### ISSUE TITLE
请问可以增加一个选项不展示页面上的悬浮图标吗？

### ISSUE THREAD

**Issue by richex-cn** [immersive-translate/immersive-translate#967]
### 您希望的更新和改进是什么 | Update or Improve

平时做开发调试的时候，右下角悬浮图标有些碍事，是否可以增加一个不展示的选项？或者能够指定部分网站不展示也可以。

![Snipaste_2023-09-28_16-37-57](https://github.com/immersive-translate/immersive-translate/assets/25103518/71f5cda6-5665-4f1a-9bd5-f32aee2a46d5)

**Comment by keyboard3** [comment]
你再这个开发模式下进入https://dash.immersivetranslate.com/#interface 关闭悬浮球就可以了
