### ISSUE TITLE
iPhone Safari插件名字过长，能否缩短插件名字？

### ISSUE THREAD

**Issue by zhaojulee** [immersive-translate/immersive-translate#968]
### 您希望的更新和改进是什么 | Update or Improve

![592D0FAC-248B-4101-AB48-D95F1E57E0B4](https://github.com/immersive-translate/immersive-translate/assets/50893754/7229448e-800a-4650-a975-2ee35c1dfa4d)

**Comment by keyboard3** [comment]
0.9.9已修复
