### ISSUE TITLE
B站中不必要的翻译

### ISSUE THREAD

**Issue by evelynn996** [immersive-translate/immersive-translate#969]
### 您希望的更新和改进是什么 | Update or Improve

有些东西感觉没必要翻译，但还是翻译出来了。
![image](https://github.com/immersive-translate/immersive-translate/assets/93717293/ac720481-d141-4f26-b1be-526072eb115f)

![image](https://github.com/immersive-translate/immersive-translate/assets/93717293/38e4b28e-d25f-4c8d-8a6a-9b296ded32c3)

**Comment by theowenyoung** [comment]
谢谢反馈，下个版本处理。

**Comment by FattySpring** [comment]
该问题未能复现，建议升级到最新版本试下。

**Comment by evelynn996** [comment]
> 该问题未能复现，建议升级到最新版本试下。

嗯，应该是解决了，我这也没有问题
