### ISSUE TITLE
设置页面改为新标签打开

### ISSUE THREAD

**Issue by HelloDogs** [immersive-translate/immersive-translate#97]
我安装的脚本，点击脚本的打开设置页，是在浏览器当前页面打开的，影响阅读流畅性，应该改成新窗口打开，这样完成设置后，我正在浏览的目标页面直接刷新就可以套用新的设置，而无需一步步返回
![image](https://user-images.githubusercontent.com/60920953/217195068-f35c3396-c3ce-4a36-8a14-c4cadbf64d73.png)

**Comment by theowenyoung** [comment]
好吧，我再优化一下.

这里之前是因为 stay.app 油猴不支持菜单项 打开新tab页。所以就统一页面内跳转了。这里可以做一个判断。只有stay 页面内打开。
