### ISSUE TITLE
PDF翻译很实用，但能不能在编辑时提供一个撤销功能

### ISSUE THREAD

**Issue by lailujiang** [immersive-translate/immersive-translate#971]
### 您希望的更新和改进是什么 | Update or Improve

PDF翻译支持对译文进行编辑，但是有时候误删却无法恢复，只能重新加载，之前的编辑全部丧失。可否提供撤销功能？
另外，只能对已经浏览的文档部分加载翻译，并且保存双语结果时无法将译文保存为文字格式。能否就这一点进行改善？谢谢！

**Comment by keyboard3** [comment]
已增加删除操作弹出确认提示窗
