### ISSUE TITLE
网页里面有类似邮件列表这种**窄列表**可以直接译文替换原文

### ISSUE THREAD

**Issue by aka-phrankie** [immersive-translate/immersive-translate#972]
### 您希望的更新和改进是什么 | Update or Improve

邮件列表这种 **窄列表** 可以直接 **译文替换原文** ，例如 gmail，outlook 等页面。

现在插件的译文在后面展现反而使得页面可读性下降，非常不沉浸。

这种页面极少，可以出个 翻译替换功能，用户来找规则适配自己来替换。

翻译前：

![chrome_231001_18033](https://github.com/immersive-translate/immersive-translate/assets/44957887/40ea5a39-d0a3-4bbf-86a3-ec92bd3ee03d)

翻译后：

![chrome_231001_1803](https://github.com/immersive-translate/immersive-translate/assets/44957887/2942935c-0918-4ab5-a974-3b94bcbb3f5f)

### 补充说明 | Additional context

翻译前：
![chrome_231001_1804](https://github.com/immersive-translate/immersive-translate/assets/44957887/0d94e093-be19-4829-a1b3-159f0b1e386b)

翻译后：

![chrome_231001_18043](https://github.com/immersive-translate/immersive-translate/assets/44957887/3a8d6c4a-d8ed-4fb7-aa11-85745e7e316c)

**Comment by theowenyoung** [comment]
这个页面的网址是？

也许适配一下比较好。

**Comment by aka-phrankie** [comment]
Outlook 网页端邮箱 :https://outlook.live.com/mail/0/
Gmail 网页端邮箱：https://mail.google.com/mail/u/0/

**Comment by keyboard3** [comment]
1.6.3 将支持译文在前

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/713805ea-8bc1-4225-94e1-42885646e1eb)
