### ISSUE TITLE
[Bug]: iPad OS扩展设置界面无法弹出、无法启动

### ISSUE THREAD

**Issue by congnews** [immersive-translate/immersive-translate#973]
### 插件版本号 | Version

0.9.8

### 平台 | Platform

iOS

### 浏览器 | Browsers

Safari

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

/沉浸式翻译突然失效、悬浮球无法弹出、设置面板无法弹出、设置网页打开也无法检测沉浸式翻译打开、卸载重装依然是这样。

### 出现问题的网址 | URL

所有

### 重现步骤 | To Reproduce

1、悬浮球失效
2、无法打开设置面板
3、打开后台、显示沉浸式翻译没有打开
4、卸载重装依然如此

### 补充说明 | Additional context

![IMG_0969](https://github.com/immersive-translate/immersive-translate/assets/66715918/38c082ab-796a-4b93-bf83-801e11ff291d)
![IMG_0970](https://github.com/immersive-translate/immersive-translate/assets/66715918/ec411b99-a093-48dd-8299-23bf1137436f)

**Comment by keyboard3** [comment]
IOS 什么版本？

**Comment by keyboard3** [comment]
因为比较长时间没有反馈，暂时关闭此issue。有进展可以重开哈
