### ISSUE TITLE
ins无法翻译[Bug]: 

### ISSUE THREAD

**Issue by ghost** [immersive-translate/immersive-translate#974]
### 插件版本号 | Version

0.9.8

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

正常翻译页面可以，点开更多文字无法翻译。

### 出现问题的网址 | URL

https://www.instagram.com/

**Comment by keyboard3** [comment]
0.10.1 已修复
