### ISSUE TITLE
建议支持文心一言翻译API

### ISSUE THREAD

**Issue by Andy-AO** [immersive-translate/immersive-translate#975]
### 您希望的更新和改进是什么 | Update or Improve

我发现对于有些内容，文心一言翻译的质量要比GPT好，比如

`The vast majority of axonal proteins are synthesized in the neuronal cell body and transported along axons. Some mRNA translation has been demonstrated within axons.[5][6] Axonal transport occurs throughout the life of a neuron and is essential to its growth and survival. Microtubules (made of tubulin) run along the length of the axon and provide the main cytoskeletal "tracks" for transportation. Kinesin and dynein are motor proteins that move cargoes in the anterograde (forwards from the soma to the axon tip) and retrograde (backwards to the soma (cell body)) directions, respectively. Motor proteins bind and transport several different cargoes including mitochondria, cytoskeletal polymers, autophagosomes, and synaptic vesicles containing neurotransmitters.`

文心一言翻译为

`绝大多数轴突蛋白在神经元细胞体内合成并沿着轴突运输。已在轴突内证实了一些mRNA的翻译。[5][6]轴突运输在神经元的整个生命过程中都会发生，对其生长和存活至关重要。微管（由微管蛋白构成）沿着轴突的长度延伸，为运输提供了主要的细胞骨架“轨道”。驱动蛋白和动力蛋白是马达蛋白，分别负责在顺行（从胞体到轴突尖端的正向）和逆行（反向到胞体）方向上移动货物。马达蛋白结合并运输几种不同的货物，包括线粒体、细胞骨架聚合物、自噬体和含有神经递质的突触囊泡。`

ChatGPT翻译为

`绝大多数轴突蛋白质是在神经元细胞体内合成，然后沿着轴突进行运输。一些mRNA的翻译已经在轴突内部得到证实。轴突运输在神经元的整个生命周期中都会发生，对于其生长和存活至关重要。微管（由微管蛋白组成）沿着轴突的长度延伸，提供了主要的细胞骨架“轨道”来进行运输。动力蛋白基辅和动力蛋白粘附在不同方向上分别进行着前行运输（从细胞体到轴突末端）和后行运输（从轴突返回细胞体）的工作。动力蛋白能够结合并运输多种不同的载体，包括线粒体、细胞骨架聚合物、自噬体和含有神经递质的突触小泡。`

文心一言的专业名词都翻译对了，GPT翻译错了，文心一言的中文明显更流利，况且文心一言在国内的速度要更快，因此建议支持文心一言作为翻译API。

**Comment by Andy-AO** [comment]
> 目前看文心的API 文档，并没有翻译的场景？
> 
> https://wenxin.baidu.com/wenxin/docs#2l6tgx5rc

对API不了解，我用的是文心一言的网页版

**Comment by theowenyoung** [comment]
> > 目前看文心的API 文档，并没有翻译的场景？
> > https://wenxin.baidu.com/wenxin/docs#2l6tgx5rc
> 
> 对API不了解，我用的是文心一言的网页版

因为我们要支持必须有API支持才行。暂时先关掉，有更新再开哈～

**Comment by Andy-AO** [comment]
> > > 目前看文心的API 文档，并没有翻译的场景？
> > > https://wenxin.baidu.com/wenxin/docs#2l6tgx5rc
> > 
> > 
> > 对API不了解，我用的是文心一言的网页版
> 
> 因为我们要支持必须有API支持才行。暂时先关掉，有更新再开哈～

可以调用这个API

https://cloud.baidu.com/doc/WENXINWORKSHOP/s/4lilb2lpf
