### ISSUE TITLE
[Bug]:字幕翻译识别乱码 

### ISSUE THREAD

**Issue by damieai** [immersive-translate/immersive-translate#976]
### 插件版本号 | Version

0.9.8

### 平台 | Platform

Windows

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![image](https://github.com/immersive-translate/immersive-translate/assets/103806899/5e69a4dc-3ada-4987-b3f8-7f446534616b)
字幕文件翻译没有编码格式的切换,导致文件识别乱码,此字幕文件编码类型为GB2312

**Comment by damieai** [comment]
期待添加一个切换编码格式的字幕识别选项

**Comment by theowenyoung** [comment]
可以在这里上传一份不兼容的字幕文件示例吗？我们看下。

**Comment by keyboard3** [comment]
暂无反馈关闭此问题
