### ISSUE TITLE
输入框增强只翻译选中的文本

### ISSUE THREAD

**Issue by hwf1324** [immersive-translate/immersive-translate#977]
### 您希望的更新和改进是什么 | Update or Improve

只翻译输入框内选中的文本。

### 补充说明 | Additional context

例如在Github中填写问题模板时，中间的部分。

**Comment by theowenyoung** [comment]
目前没有计划做类似划词翻译，选中翻译需要 gui界面配合的翻译功能。

建议使用 DeepL 插件，DeepL 插件提供了该功能。
