### ISSUE TITLE
关于原文遮挡译文

### ISSUE THREAD

**Issue by Alison0917** [immersive-translate/immersive-translate#978]
### 您希望的更新和改进是什么 | Update or Improve

希望设置一个新选项：为译文增加一个可移动的悬浮框。
在阅读书籍是译文和原文重叠了。

**Comment by FattySpring** [comment]
是在什么场景下（网页、PDF、EPUB）重叠？方便上传下图片吗？

**Comment by theowenyoung** [comment]
暂时没有进一步的回复，先关了哈。目前应该没有计划为译文增加编辑区域。
