### ISSUE TITLE
[Bug]: 鼠标支持检测兼容性

### ISSUE THREAD

**Issue by r91085** [immersive-translate/immersive-translate#979]
### 插件版本号 | Version

0.9.8

### 平台 | Platform

Linux

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

![photo_2023-10-04_12-53-50](https://github.com/immersive-translate/immersive-translate/assets/37505035/29a1b099-4118-4eeb-8676-cfe76b66ee77)

插件的介面，還有內部設定頁，都缺少了鼠標滑過的熱鍵可以設定

**Comment by keyboard3** [comment]
這個是瀏覽器不讓插件訪問這些特殊頁面

**Comment by r91085** [comment]
我指的是缺少 "鼠標滑過的熱鍵可以設定"，並不是不能使用的問題

![x2scrap](https://github.com/immersive-translate/immersive-translate/assets/37505035/454379d6-bf49-4c98-9513-95526fd8d886)

**Comment by keyboard3** [comment]
沒懂，你截圖的這個頁面就是無法設定熱鍵的，沒有權限

**Comment by r91085** [comment]
請看我兩張圖，我的意思是，在 linux 上，不管在哪個頁面，我第二章圖的那個 UI 都不會顯示出來，在插件設定頁，也沒有熱建設定的區塊。

第二張圖是 windows 上，同樣是在沒有權限的頁面，但是UI 有顯示，linux上面沒有UI的。

**Comment by keyboard3** [comment]
我們透過瀏覽器api檢測出您的裝置不支援滑鼠，所以沒有展示。您是什麼設備？

**Comment by r91085** [comment]
我是一個雲端機器，操作都是透過遠端桌面的，但使用起來和本地機器基本沒有區別，可能檢測方式要修改一下。

**Comment by theowenyoung** [comment]
目前使用这个检测方式，还没找到其他办法，先列出来，看看有没有同学贡献其他方案：

```js
function isMouseSupport(): boolean {
  if (globalThis.matchMedia("(pointer:fine)").matches) {
    // Device has a mouse
    return true;
  }
  return false;
}

```

**Comment by r91085** [comment]
如果沒辦法精確檢測，或許可以提供一個設定讓用戶自行強制啟用鼠標功能？

**Comment by theowenyoung** [comment]
> 如果沒辦法精確檢測，或許可以提供一個設定讓用戶自行強制啟用鼠標功能？

但是新增这样的选项又会引起 普通移动用户的歧义，也许可以以开发者配置的方式支持这个选项。

**Comment by keyboard3** [comment]
0.11.5 已支持针对检测不支持的情况下，可以通过鼠标悬停配置页面强制开启鼠标悬停功能
