### ISSUE TITLE
[Bug]:  arc 浏览器 twitter 不能使用输入框增强

### ISSUE THREAD

**Issue by happykkAi** [immersive-translate/immersive-translate#982]
### 插件版本号 | Version

0.9.8

### 平台 | Platform

macOS

### 浏览器 | Browsers

Other

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

[Bug]:  arc 浏览器 twitter 不能使用输入框增强 功能

**Comment by FattySpring** [comment]
在 arc 浏览器 twitter 中未能重现该问题
