### ISSUE TITLE
pdf翻译后的双语pdf文件，建议使用矢量图可编辑

### ISSUE THREAD

**Issue by saccohuo** [immersive-translate/immersive-translate#983]
### 您希望的更新和改进是什么 | Update or Improve

pdf翻译后的双语pdf文件，当前用的是图片转pdf。
建议使用矢量图可编辑，用pdf的库来生成。
这样即使生成翻译的时候有些点没处理到，在生成之后还可以用pdf编辑工具进一步处理。

**Comment by keyboard3** [comment]
暂时不会生成矢量pdf，现有的方案要适配成矢量pdf，工作量很大。通过浏览器打印出来的PDF已经能够一定程度满足编辑需求了。
