### ISSUE TITLE
[Bug]: 0.5.6.1 google 搜索页面重叠

### ISSUE THREAD

**Issue by emptyboo** [immersive-translate/immersive-translate#986]
### 插件版本号 | Version

0.5.6.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

油猴 | Tampermonkey | Userscripts

### 请描述这个Bug | Describe the bug

重叠问题 见截图
![issue 995Z](https://github.com/immersive-translate/immersive-translate/assets/127120608/f58e40ec-2963-47ec-ae71-9e5aaef7a409)

**Comment by keyboard3** [comment]
版本太久了，最新版本0.9.8 升级下看
