### ISSUE TITLE
[Bug]:  There is no mouse hover

### ISSUE THREAD

**Issue by toprak** [immersive-translate/immersive-translate#988]
### 插件版本号 | Version

0.9.8

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

In linux there were mouse hover translation with pressing specified key, in immersive translator there is mouse hover section but there is nothing to specify key, i tried add it from browser keyboard shortcut section there were not any option about mouse hover there were like activate, toggle page

### 出现问题的网址 | URL

everywhere

### 补充说明 | Additional context

using w10 home 22h2

**Comment by theowenyoung** [comment]
Hi, you can specify the shortcut on the popup:

<img width="358" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/b4a641a4-0baf-4ea5-9cb0-dbbe7e6e704c">


Or [Settings -> Mouse Hover]:

<img width="1416" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/9f5c592d-5a58-41c0-bde6-836bf8476cf8">

**Comment by theowenyoung** [comment]
it seems that your device is detected as touch screen, we use the following code to check if a device is supporting mouse event:

```
function isMouseSupport(): boolean {
  if (globalThis.matchMedia("(pointer:fine)").matches) {
    // Device has a mouse
    return true;
  }
  return false;
}
```

so which device do you use? maybe it can support both touch and mouse?

**Comment by toprak** [comment]
@theowenyoung my device supports mouse, touchscreen, also it has pen, iti s samsung XE700T1C-G01TR

**Comment by theowenyoung** [comment]
got it.

it seems windows has a different response for the check code.

actually we do not have better method for this, but we'll still track this issue.

**Comment by keyboard3** [comment]
0.11.5 Supported: If the detection is not supported, you can force the mouse-over function to be enabled through the mouse-over configuration page

**Comment by toprak** [comment]
Can confirm on my end its fixed, thanks for hardworks!
