### ISSUE TITLE
[Bug]: lwn网站内容悬停翻译跑到底部

### ISSUE THREAD

**Issue by severecold** [immersive-translate/immersive-translate#989]
### 插件版本号 | Version

0.9.8

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

https://lwn.net/Articles/946803/
悬停翻译 该网站资料时，内容都跑到最下边，格式也是混乱的

### 出现问题的网址 | URL

https://lwn.net/Articles/946803/

### 重现步骤 | To Reproduce

1. 打开该网址
2. 使用快捷键翻译鼠标悬停位置内容

### 补充说明 | Additional context

https://lwn.net 上边的所有patch基本都存在这个问题

**Comment by keyboard3** [comment]
![image](https://github.com/immersive-translate/immersive-translate/assets/13177744/dae0e179-4a45-47cc-be44-493a4ae4e98c)
这个网站我做了简单的优化，但是这种纯文档排版网页无法保留原有的格式
