### ISSUE TITLE
翻译epub文件的时候出现链接无法跳转

### ISSUE THREAD

**Issue by danielesk** [immersive-translate/immersive-translate#99]
https://epub-reader.online/#
翻译的中文和英文在一行中右侧没有空白，点击之后则无反应；当原文和中文翻译结果在上下两行的时候是可以的

![image](https://user-images.githubusercontent.com/10652829/217222024-17fff6c3-f068-475d-a56f-baa1d6b3c17d.png)

**Comment by theowenyoung** [comment]
感谢反馈，确实是这样，一会提交一下修复～

**Comment by danielesk** [comment]
@theowenyoung OK
