### ISSUE TITLE
[Bug]: Mouse hover translation does not work with certain setting + suggestion ticking all languages

### ISSUE THREAD

**Issue by BarbzYHOOL** [immersive-translate/immersive-translate#990]
### 插件版本号 | Version

0.9.9

### 平台 | Platform

Linux

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

I just installed this extension.
It correctly translates a page automatically but if I select a text and mouse hover, it doesn't translate anything. I tried with a hotkey, I tried the auto-translation on hovering etc...

It doesn't work because I have set "never translate these languages". But why did I do that? because I wanted to automatically translate ALL languages except a few languages. I didn't to tick the  150 tick boxes, so I ticked "All languages" instead.

So what I suggest is that when you click "All languages", it automatically ticks all the boxes. Then you can untick the languages you don't want translated.

### 补充说明 | Additional context

I found the reason of my bug while testing but I let it so others can read about it and figure it out.

**Comment by theowenyoung** [comment]
Thanks, we'll fix it.

**Comment by FattySpring** [comment]
0.10.7 Fixed

**Comment by BarbzYHOOL** [comment]
nice
