### ISSUE TITLE
Press the shortcut again to hide the translated hovered text

### ISSUE THREAD

**Issue by BarbzYHOOL** [immersive-translate/immersive-translate#991]
### 您希望的更新和改进是什么 | Update or Improve

When you mouse hover a text (and press a shortcut), it is translated. But then you cannot hide it. Just add the hiding effect by pressing the shortcut again.

**Comment by theowenyoung** [comment]
Thank you for your advise, we are planning to support this feature in the future.

**Comment by FattySpring** [comment]
0.10.7 Supported

**Comment by BarbzYHOOL** [comment]
thx
