### ISSUE TITLE
优化多api翻译机制

### ISSUE THREAD

**Issue by myh66** [immersive-translate/immersive-translate#995]
### 您希望的更新和改进是什么 | Update or Improve

优化多个api翻译效率
默认是发请求是每次翻译多个api都要请求一次，可以改进成将，请求没反应（没翻译）记录下来，然后智能排序（翻译失败的api后置），一个月重置一次，填了多个api的时候就默认开启
这样优化，用户的翻译体验会更加好

**Comment by theowenyoung** [comment]
不同的api的策略不太一样，这个不好在插件这里处理。建议自己可以实现一个代理的接口，然后在代理里面根据自己的需求做不同的策略处理。

在开发者模式里开启【beta】选项，选择【自定义api】
<img width="919" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/62473795/7899874f-94ad-4810-80b3-c9d87a8048f2">

相关文档： https://immersivetranslate.com/docs/services/custom/
