### ISSUE TITLE
建议增加更多价格方案

### ISSUE THREAD

**Issue by heheda123123** [immersive-translate/immersive-translate#997]
### 您希望的更新和改进是什么 | Update or Improve

现在只有69一个月的，说实话太贵了。平时也没有那么频繁使用翻译的需求
建议增加便宜一些的方案，比如30一个月的，可以调低翻译的词数量。

**Comment by PixelMonkeyPro** [comment]
还不如根据调用数量来

**Comment by theowenyoung** [comment]
如果需要 按需 付费的话，建议直接使用官方的 key:

教程：

https://immersivetranslate.com/docs/services/openai/#%E9%80%9A%E8%BF%87-openai-%E5%AE%98%E6%96%B9%E5%BC%80%E5%8F%91%E8%80%85%E5%B9%B3%E5%8F%B0%E8%8E%B7%E5%8F%96-api-key

https://immersivetranslate.com/docs/services/deepL/


你的需求主要是 OpenAI 还是 DeepL 呢？

**Comment by heheda123123** [comment]
deepl

**Comment by theowenyoung** [comment]
> deepl 主要我使用的频率不高，也不会一次性翻译一整本书，69一个月有点儿贵

了解，我们讨论下～

**Comment by FattySpring** [comment]
暂无计划增加其他价格方案
