### ISSUE TITLE
建议提供更方便的翻译引擎切换操作

### ISSUE THREAD

**Issue by Autumn-one** [immersive-translate/immersive-translate#998]
### 您希望的更新和改进是什么 | Update or Improve

对网页翻译的时候没有哪个翻译引擎是绝对正确的，所以经常需要切换多个翻译引擎来对比翻译，但是现在的切换必须在浏览器工具栏中通过点击选择来做到，这样不够便捷。
建议在页面中绑定一个快捷键，按下这个快捷键之后立刻弹出选择翻译引擎的选择浮窗，然后可以通过这个选择浮窗来切换，这个浮窗应该支持键盘方向键来选择。

**Comment by theowenyoung** [comment]
我在想这个操作有那么高频嘛？

（因为加这个成本还挺高的... 需要单独实现 选择浮窗..

**Comment by Autumn-one** [comment]
> 我在想这个操作有那么高频嘛？
> 
> （因为加这个成本还挺高的... 需要单独实现 选择浮窗..

我是用来翻译英文书，使用较深度，对翻译要求稍微高一点频繁切换应该是必做的事情，现在openAI API的翻译还没想象的那么强大，一些句子翻译的很难理解就得切换到有道，彩云小译等翻译做参照，有一些句子有道翻译的明显比openAI好，有些则相反，目前还没有一个翻译API有绝对的精准优势，频繁切换翻译引擎只是没办法的办法。切换的时候如果有快捷方式会体验好很多。

**Comment by theowenyoung** [comment]
好吧，只能说这是一个小的痒点，目前确实没有计划实现这个功能。不过后期资源充足之后我们再重新评估一下这个。

我先打个 label 标记一下，未来再重启吧。
