### ISSUE TITLE
建议增加TTS功能

### ISSUE THREAD

**Issue by softmetal66** [immersive-translate/immersive-translate#999]
### 您希望的更新和改进是什么 | Update or Improve

目前主流浏览器中都集成了TTS工具，可以朗读网页；建议本插件增加TTS功能，可以朗读翻译后的文字
同时，还发现一个很有意思的项目，可以朗读翻译后的youtube字幕，效果不错，这个也可以考虑加进来（https://www.youtube-dubbing.com/）

**Comment by kongfu-cat** [comment]
+1, 类似需求, 需要 **划词 TTS** 的功能, 帮助更快速并沉浸式的学习单词发音

**Comment by theowenyoung** [comment]
感谢建议～

目前沉浸式翻译专注于做网页和文档翻译，主要目标是加速信息获取的效率，暂时没有计划加入学习类 feature 的计划。
